### ISSUE TITLE
More flexible password generator

### ISSUE THREAD

**Issue by TitovLab** [nuxsmin/sysPass#100]
sysPass has password generator feature.
But it generates very dificult passwords to remember and to use it.
Maybe it is a good idea to provide configuration options to sysPass admins to select password length and used characters to prevent some situations like zero and letter 'O' in passwords.
I am not a developer and after google I modify ./js/functions.js like:
function password(length, special, fancy, dstId) {
    "use strict";
    var keylistalpha="abcdefhkmnpqrstuvwxyz";
    var keylistalphaupper="ABCDEFHKLMNPQRSTUVWXYZ";
    var keylistint="123456789";
    var keylistspec="@#$_";
    var genPassword='';
    var len = 3;
    var lenspec = 1;
    var i='';

    for (i=0;i<len;i++)
        genPassword+=keylistalpha.charAt(Math.floor(Math.random()*keylistalpha.length));

    for (i=0;i<len;i++)
        genPassword+=keylistalphaupper.charAt(Math.floor(Math.random()*keylistalphaupper.length));

    for (i=0;i<lenspec;i++)
        genPassword+=keylistspec.charAt(Math.floor(Math.random()*keylistspec.length));

    for (i=0;i<len;i++)
        genPassword+=keylistint.charAt(Math.floor(Math.random()*keylistint.length));

        genPassword=genPassword.split('').sort(function(){return 0.5-Math.random()}).join('');

    if (fancy === true) {
        $("#viewPass").attr("title", genPassword);
        //alertify.alert('<div id="alert"><p id="alert-text">' + LANG[6] + '</p><p id="alert-pass"> ' + password + '</p>');
    } else {
        alertify.alert('<div id="alert"><p id="alert-text">' + LANG[6] + '</p><p id="alert-pass"> ' + genPassword + '</p>');
    }

    if (dstId) {
        checkPassLevel(genPassword);
        $('#' + dstId + ' input:password').val(genPassword);
        $('#' + dstId + ' #passLevel').show(500);
    } else {
        checkPassLevel(genPassword);
        $('input:password').val(genPassword);
        $('#passLevel').show(500);
    }
    //return password;

}
Have a nice day!

**Comment by nuxsmin** [comment]
Hi, thank you for your great support.

This feature is already implemented in 1.2 release (under development) with many options like:

* Global password complexity configuration (numbers, upper case, dictionary, symbols)
* In-time generation password complexity (if not locked in global config)
* Password restrictions based on context (account name, username, notes, etc)

Kind regards
