### ISSUE TITLE
Get Custom Field from API or DB

### ISSUE THREAD

**Issue by krubenrc** [nuxsmin/sysPass#1002]
Versión: 2.1 (2.1.15.17101701)

Buenos días Rubén, me gustaría saber si hay alguna forma de extraer un campo personalizado que le he puesto a los clientes. He intentado con la API pero veo que no me lo devuelve, y en la base de datos está cifrado, por lo tanto no sé como conseguir extraerla mediante un programa externo.

¿Hay alguna forma?

Un saludo y muchas gracias de antemano.

---

Hello Rubén, I would like to know if there is any way to extract a custom field that I have put to clients. I have tried with the API but I see that it does not return it to me, and in the database it is encrypted, therefore I do not know how to extract it through an external program.

Is there any way?

Regards and thank you very much in advance.

**Comment by nuxsmin** [comment]
Hola Rubén!

Efectivamente, en estos momentos los campos personalizados no se pueden obtener desde la API. Esta funcionalidad estará disponible en la versión 3.0

Saludos!
---

Hello Rubén!

That's right, currently there's no way to get the custom fields through the API. This feature will be available in 3.0 version.

Regards
