### ISSUE TITLE
sysPassv3 is not working

### ISSUE THREAD

**Issue by kitenberg** [nuxsmin/sysPass#1003]
I installed sysPass v3 beta but it's not working. The installation guide for Centos is not updated with the files structure of this version so performed the command on the folders and files that looked logical but I might did something wrong.   

Getting http 500 error:
![image](https://user-images.githubusercontent.com/9526809/43694146-550deaaa-9975-11e8-9489-0bf777f8ba6d.png)

 - OS: CentOS Linux release 7.5.1804 (Core)
 - Browser Chrome

**Comment by vmario89** [comment]
Hi,

i got some problem now too. I updated from the version from 2018.07.21 to 2018.07.31 + updating from php7.1 to php7.2 on an odroid Ubuntu 18 LTS and getting the error
![grafik](https://user-images.githubusercontent.com/5631071/43736930-ca49c27c-99bf-11e8-9617-89fe8bc8f2f9.png)

I already reinstalled syspass completely with new database and also reinstalled freshly with composer 1.7.0 and cleared caches before. i also tried different browsers and cleared their caches too.

The  /app/config/syspass.log says:
2018-08-06 21:30:43 [EXCEPTION] [N/A] Oops, it looks like this content doesn't exist...
#0 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#1 /var/www/vhosts/pw.thedomain.de/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#2 /var/www/vhosts/pw.thedomain.de/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#3 /var/www/vhosts/pw.thedomain.de/lib/SP/Bootstrap.php(426): Klein\Klein->dispatch(Object(Klein\Request))
#4 /var/www/vhosts/pw.thedomain.de/lib/Base.php(72): SP\Bootstrap::run(Object(DI\Container))
#5 /var/www/vhosts/pw.thedomain.de/index.php(28): require('/var/www/vhosts...')
#6 {main}

The only menus which are working are 
![grafik](https://user-images.githubusercontent.com/5631071/43736989-0f79ccd4-99c0-11e8-9a64-cfe1e24b3bd3.png)
 
and 
![grafik](https://user-images.githubusercontent.com/5631071/43737000-180dc3c8-99c0-11e8-8df9-2dd0ae8ae5f9.png)


i also checked the apache config. i did not find some setting which may cause this.

do you have some idea?

**Comment by nuxsmin** [comment]
Hello @vmario89 !

that's weird, since it's working fine on demo site running on PHP 7.2: http://demo-beta.syspass.org:10082/index.php?r=index

Did you run `php composer.phar update` after switching to 7.2?

**Comment by vmario89** [comment]
Hi @nuxsmin,
yes i first removed php7.1, then i installed php7.2, then i enabled 7.2 in apache modules, after that i ran apt-get upate/upgrade; then i removed caches from composer / deleted it; downloaded 1.7.0 and composed everything again; i also tried with 1.6.5 ... no idea :-O

**Comment by vmario89** [comment]
Hi @nuxsmin,
i made some upgrade documentation because i pushed to version from yesterday to my server:
https://gist.github.com/vmario89/966356c629b7af28d18f97575479d69b

BUT exactly same situation as before :-( Anyone an idea?
regards, Mario

**Comment by vmario89** [comment]
Hey @nuxsmin,

damn it! i just forgot to remove browser cache this time! now it works perfectly :-D

**Comment by nuxsmin** [comment]
Great!

I've just pushed some important changes. Please update ;)

**Comment by nuxsmin** [comment]
Hi @OnoTime 

The last commit implements additional checks for used files, so this error should be managed by the application itself, since this file doesn't exist until the first run. 

I'll fix it shortly (I don't know if creating an empty file would solve the issue).

Sorry for the inconvenience.

**Comment by nuxsmin** [comment]
@OnoTime it should be solved in the latest commit.
