### ISSUE TITLE
Login Attempt exceeded Message after multiple user activation on same machine 

### ISSUE THREAD

**Issue by abaymhjn** [nuxsmin/sysPass#1007]
**sysPass Version**
2.1

**Describe the bug**
Login Attempt exceeded Message after multiple user activation on same machine.
Also For First Login Attempt Master field is not being displayed by default. It show only after submit 
form for first time. System Mark Login Failed attempt and show Master Password Field. 
If we tried to activate at least five user activation. 
Syspass Blocked all users login on all devices.      

**To Reproduce**
1. Login Using Master Admin
2. Create 6 Application Users
3. Logout Master Admin. 
4. Try First Login Activation Of created Users
5. It will ask Master Password After First Attempt of User Login for every created user.
6. After 4-5 Users First Login Activation. It will block All Logins
7. Try Master Admin Login on same device and other devices. It blocks all logins  

**Expected behavior**
1. If User tried to login for first time. It Must activate Master Password Field After Entering User Id. Which will prevent wrong login attempt.
2. If User tried wrong Password for 5 times, Particular Device blocking is understandable. But All Users must work without any issues.

**Platform (please complete the following information):**
 Godday Linux Deluxe Hosting Account 
 - Browser Firefox Chrome

**Comment by nuxsmin** [comment]
Hello, this issue should be fixed in latest releases besides there is a new feature to unlock attempts exceed locking behaviour.

Regards
