### ISSUE TITLE
LDAP sync error

### ISSUE THREAD

**Issue by meduzkin** [nuxsmin/sysPass#1011]
**sysPass Version**
2.1 (2.1.16.18061901)

**Describe the bug**
After updating LDAP sync filtration from issue #853 we get an error in LDAP sync stage.

**Expected behavior**
We can rollback filtration changes from 2.1.15 version and LDAP sync gonna be worked. But it's not the correct way of further support in future updates. 

**Screenshots**
https://www.dropbox.com/s/au8fdilvcwzljm7/syspass_error.jpg?dl=0

**Event log**
"Error while searching the group RDN
Group : (&(cn=\44\65\76\65\6c\6f\70\65\72\73)(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group)(objectCategory=group)))
LDAP ERROR : Success (0)
LDAP FILTER :
(&(cn=\44\65\76\65\6c\6f\70\65\72\73)(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group)(objectCategory=group)))"

**Platform (please complete the following information):**
Installed on: 
- OS: Linux
- OS: Centos 7.5.1804
Tested from:
- OS: Linux
- OS: Mint 19
- Browser: Chrome Latest

**Additional context**
I also get the question about possible database migration between Syspass 2.1.* version into 3.0.

**Comment by animativ** [comment]
Hi, I have the same error. Is there any chance that it could be fixed?

**Comment by nuxsmin** [comment]
@meduzkin sorry about this issue, I've missed it, since I was on holidays during August...

sysPass will complain when they're more than one group with the same name, so it could be the problem.

Another still facing issue is an LDAP filter  behaviour, but this one is related to user type objects.

Regarding your question about v3, yes it could be upgraded from v2 in a seamless way. I still need to add some instructions about how to setup v3.

Regards

**Comment by jonesjardel** [comment]
> @meduzkin sorry about this issue, I've missed it, since I was on holidays during August...
> 
> sysPass will complain when they're more than one group with the same name, so it could be the problem.
> 
> Another still facing issue is an LDAP filter behaviour, but this one is related to user type objects.
> 
> Regarding your question about v3, yes it could be upgraded from v2 in a seamless way. I still need to add some instructions about how to setup v3.
> 
> Regards

I'm getting this issue here and there is no duplicated groups.

Could you help with that?

**Comment by nuxsmin** [comment]
Hello, this issue should have been solved in v3.

Thanks for the feedback!

**Comment by jonesjardel** [comment]
Thanks

Em dom, 24 de fev de 2019 às 19:36, RubénD <notifications@github.com>
escreveu:

**Comment by nuxsmin** [comment]
@jonesjardel You're welcome and sorry for the late reply...
