### ISSUE TITLE
Shared link does not work due to SyntaxError: JSON.parse

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1012]
**sysPass Version**
3.0.0.18081002-beta

**Describe the bug**
Using "Create Public Link" fails with JSON.parse error. No link is created 

**To Reproduce**
![grafik](https://user-images.githubusercontent.com/5631071/44258218-9ce07e00-a20e-11e8-87a0-afb8b8681d27.png)
![grafik](https://user-images.githubusercontent.com/5631071/44258282-c4cfe180-a20e-11e8-863a-b71de69df75f.png)

**Event log**
- is empty - no log line in audit from syspass
- syspass.log:

[Fri Aug 17 11:33:52.735426 2018] [:error] [pid 26338] [client 192.168.33.133:4055] [EXCEPTION] [N/A] Warning: Missing argument 2 for SP\\Modules\\Web\\Controllers\\PublicLinkController::saveCreateFromAccountAction()\n#0 [internal function]: SP\\Modules\\Web\\Controllers\\PublicLinkController->saveCreateFromAccountAction(1)\n#1 /srv/www/vhosts/the.domain/lib/SP/Bootstrap.php(222): call_user_func_array(Array, Array)\n#2 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#3 /srv/www/vhosts/the.domain/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#4 /srv/www/vhosts/the.domain/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#5 /srv/www/vhosts/the.domain/lib/SP/Bootstrap.php(432): Klein\\Klein->dispatch(Object(Klein\\Request))\n#6 /srv/www/vhosts/the.domain/lib/Base.php(72): SP\\Bootstrap::run(Object(DI\\Container))\n#7 /srv/www/vhosts/the.domain/index.php(28): require('/srv/www/vhosts...')\n#8 {main}, referer: https://192.168.100.55:444/index.php
[Fri Aug 17 11:33:52.739644 2018] [deflate:debug] [pid 26338] mod_deflate.c(853): [client 192.168.33.133:4055] AH01384: Zlib: Compressed 110 to 98 : URL /index.php, referer: https://192.168.100.55:444/index.php

**Platform (please complete the following information):**
 - OS: Ubuntu 16.04 LITS
 - Browser: Firefox 61.0.2 (64-Bit)

**Comment by nuxsmin** [comment]
This issue was solved in latest commit. Thanks for the feedback!

Regards
