### ISSUE TITLE
syspass installation centos7

### ISSUE THREAD

**Issue by mrpfbjr** [nuxsmin/sysPass#1016]
**sysPass Version**
2.1.16

**Platform (please complete the following information):**
centos7

**Describe the question**
I have followed your instructions EXACTLY (https://doc.syspass.org/en/installing/centos7.html) 
But I still cannot get syspass/index.php to open the index.php page, just text (see below). I've noticed quite a few people with the same issue but they didn't seem to get any help.

When I first tried to install with php7 index.php page would load with error to use php 5.6 which I have been.

I can always get to the "testing 123" so it's not an apache issue.
Something is wrong.
Can you help me figure it out?
Thank you.

<?php
/**
 * sysPass
 *
 * @author nuxsmin
 * @link http://syspass.org
 * @copyright 2012-2017, Rubén Domínguez nuxsmin@$syspass.org
 *
 * This file is part of sysPass.
 *
 * sysPass is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sysPass is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 *  along with sysPass.  If not, see <http://www.gnu.org/licenses/>.
 */

use SP\Controller\MainController;
use SP\Core\Init;
use SP\Core\Session;

define('APP_ROOT', '.');

require APP_ROOT . DIRECTORY_SEPARATOR . 'inc' . DIRECTORY_SEPARATOR . 'Base.php';

if (!Init::checkPostLoginActions() && Session::getAuthCompleted()) {
    $Controller = new MainController();
    $Controller->getMain();
    $Controller->view();
}

**Comment by nuxsmin** [comment]
Hello, it seems that the PHP module is not enabled on the web server.

Regards

**Comment by 90er** [comment]
Did you enabled the external Repo for PHP? I install sysPass with Ansible and CentOS 7 with SELinux enabled just fine.

**Comment by mrpfbjr** [comment]
How would one go about enabling the PHP module?
I didn't see that step in the instructions.

**Comment by ruzzetto** [comment]
Hi,
I had the same issue because in the guide some information are not exhaustive. First of all syspass requires php versione >= 5.6 but default version on Centos 7 repos is 5.4. So you have to enable remi repos in order to install it. And of course, you have to install php engine too :)

**Comment by mrpfbjr** [comment]
Don't care anymore. I've moved on.
