### ISSUE TITLE
Translation on Poeditor

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1017]
**sysPass Version**
3.0.0.18081002-beta

**Describe the bug**
.pot/.po/.mo contains too much strings

Hey,
i am working on syspass translations for english and german and i got some trouble with the total count of strings.

looking into https://poeditor.com/projects/po_edit?id_language=43&id=78193 returns **1455** language strings for syspass. After translating all the strings i downloaded the .po/.mo files and installed it to my Ubuntu server and reloaded syspass session after cleaning cache. It still figured out that **some strings were not working**.

So i decided to create my own .pot file with xgettext from the checked out git repo on server to check against the state on Poeditor. I uploaded the result to https://poeditor.com/projects/view?id=204555 and re-imported the translated .po file. Now i got **1248** strings. So there are missing **207** strings. Or maybe your file just conaints 207 unused strings.

I used the following command from root directory to create the translation file:
![grafik](https://user-images.githubusercontent.com/5631071/44418696-5e81f080-a579-11e8-85e7-e8c80bb8bb43.png)

## The command i used:
```
#sorted by file with -F flag; key __u means language set by user; key __ means language set by system (global)
xgettext --from-code=utf-8 -o messages_ca_ES.pot $(find .  \( -name "*.php" -o -name "*.inc" \) -not -path "./vendor/*" -not -path "./build/*" -not -path "./schemas/*" ) --language=PHP -F --copyright-holder=cygnux.org --package-name=syspass --package-version=3.0 --force-po -k__u -k__
```

Is there some key missing? i only found "__" and "__u" in .inc and .php files.

regards, Mario

**Comment by vmario89** [comment]
okay i found another bunch of translations in actions.xml

```
vim its.its
<?xml version="1.0"?>
<its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
  <its:translateRule selector="/"                       translate="no"/>
  <its:translateRule selector="/actions"                translate="no"/>
  <its:translateRule selector="/actions/action"         translate="no"/>
  <its:translateRule selector="/actions/action/text"    translate="yes"/>
</its:rules>
 
#generate messages_ca_ES.pot for xml file actions.xml
xgettext --from-code=utf-8 -o messages_ca_ES.pot $(find ./app/config/  \( -name "actions.xml" \) -not -path "./vendor/*" -not -path "./build/*" -not -path "./schemas/*" )  -F --copyright-holder=cygnux.org --package-name=syspass --package-version=3.0 --force-po --its=./its.its
 
 
#expand messages_ca_ES.pot by .php/.inc files, sorted by file with -F flag; key __u means language set by user; key __ means language set by system (global)
xgettext --from-code=utf-8 -j -o messages_ca_ES.pot messages_ca_ES.pot $(find .  \( -name "*.php" -o -name "*.inc" \) -not -path "./vendor/*" -not -path "./build/*" -not -path "./schemas/*" ) --language=PHP -F --copyright-holder=cygnux.org --package-name=syspass --package-version=3.0 --force-po -k__u -k__
```

**Comment by nuxsmin** [comment]
@vmario89 nice hack, I've already done so, but integrated with poedit...

Please, be aware that the current base language is es_ES since ca_ES is for Catalonian language.

Regards

**Comment by vmario89** [comment]
i just made up this now: https://poeditor.com/projects/view?id=204555

but i also updated the main project, which maybe should be cleaned
i just made up this now: https://poeditor.com/projects/view?id=78193

for better sysPass demo on http://demo-beta.syspass.org:10082/index.php?r=index it would be nice to just update those files. Looks better for testers and interested person :-)

**Comment by nuxsmin** [comment]
Sure Mario, thanks for your contribution!

I'll update it shortly.

Regards

**Comment by vmario89** [comment]
Hi @nuxsmin,

i recognized that different fields do not update their lang strings. I already cleared syspass cache, browser cache, etc ... still some unlear things like this:

This appears when sending test email from config menu
![grafik](https://user-images.githubusercontent.com/5631071/44679149-6f7ba780-aa3a-11e8-85f4-3abfdfc5bbb9.png)

This appears when upgrading syspass
![grafik](https://user-images.githubusercontent.com/5631071/44679169-7c000000-aa3a-11e8-91b4-530f465a7cde.png)


The first line is german, the second spanish. Seems to be some more generic thing.

**Comment by vmario89** [comment]
note that i triple-checked if these strings are correctly set in po/mo files. they are fine

**Comment by nuxsmin** [comment]
Hello! You were right, some these strings weren't translated through the UI.

I've fixed it in latest commits.

Thanks for the feedback!

Regards
