### ISSUE TITLE
LDAP loginAttribute always stays samAccountName

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1019]
**sysPass Version**
2.1 (2.1.16.18061901)

**Describe the bug**

I'm trying to migrate my users from using their samAccountName attribute to login into sysPass to their userPrincipalName attribute.
When changing the login attribute in the GUI, it always reverts to samAccountName.

**To Reproduce**
1. Go to config > LDAP
2. Change Login Attribute to something else
3. Save
4. Reload page

*
**Event log**
sysPass eventlog says it updated the config

44782 | 2018-08-24 13:00:51 | INFO | Modifier Configuration | admin| xx.xx.xx.xx | LDAP activéConfiguration actualiséeSection : LDAP

**Platform (please complete the following information):**
 - OS: CentOS 7.5 x64 with php  7.0.27 
 - Client is Win10 x64 with Opera / Vivaldi / Edge

**Additional context**
Nothing fishy in my httpd / php logs.

config.xml file does not include any ldapAttribute to be used:
```
  <ldapAds>1</ldapAds>
  <ldapBase>dc=SomaDomain,dc=local</ldapBase>
  <ldapBindPass>SuperBigPassword</ldapBindPass>
  <ldapBindUser>CN=SomeUser,CN=Users,DC=SomeDomain,DC=local</ldapBindUser>
  <ldapDefaultGroup>2</ldapDefaultGroup>
  <ldapDefaultProfile>2</ldapDefaultProfile>
  <ldapEnabled>1</ldapEnabled>
  <ldapGroup>CN=SomeGroupe,OU=Groupes,DC=SomeDomain,DC=local</ldapGroup>
  <ldapProxyUser></ldapProxyUser>
  <ldapServer>ldap://somefqdnofaADserver.local</ldapServer>
  <ldapUserattr></ldapUserattr>
  <logEnabled>1</logEnabled>
```

Guess the functionnality is just not implemented yet ?
If I happen to "hard change" it in the code, will I have to re-register all users using the master password ?

**Comment by deajan** [comment]
Okay, I get it.
The login attribute selector is used only for the imports, hence it will reset to samAccountName.
Nevertheless, using it with anything else than samAccountName will make LDAP logins fail.

I made #1020 which should allow the usage of the 3 other attributes.

I got one last question. I was successfully able to migrate a user login from samAccountName to userPrincipalName without needing to re-import it using:
```UPDATE usrData SET user_login = 'user@domain.com' WHERE user_login = 'user';```

I can login, but on first attempt it will ask for the earlier password and then for the master password.
Is there any way I can override this ? I can't ask all my users to come see our IT department again in order to type in the master password.

Thanks.

**Comment by nuxsmin** [comment]
Hello @deajan

Right, LDAP attribute selector is only used when importing.

Regarding the users' login change, there's no way to avoid the master password prompt, since it's encrypted using a derivated key from the user's login data, so you can only generate a temporary master password.

Kind regards

**Comment by nuxsmin** [comment]
>  When changing the login attribute in the GUI, it always reverts to samAccountName.

sysPass will use the same data used for logging into the application. The LDAP search filter will be built setting the most common attributes to look for the provided login, so it does not need an attribute selector within the UI.

I've done some improvements in v3
