### ISSUE TITLE
Syspass don't load for me.

### ISSUE THREAD

**Issue by tejadon** [nuxsmin/sysPass#102]
I have installed the syspass plataform and I haven't had any problem but when I put my access login the index.php file don't load fine for me and it shows several errors in my inspector code of chrome. It only loads the search button and some css3 styles.

Anybody can help me?

Thanks. Sorry for my english i'm spanish :D

**Comment by nuxsmin** [comment]
Hola, si lo has instalado en linux, debes de comprobar que los permisos de los directorios y subdirectorios de sysPass sean correctos, es decir, el propietario y grupo sean el mismo usuario que el servidor web y los archivos tengan los permisos 644 y los directorios 755 excepto /config que debe de ser 750

También puedes comprobar si el nivel de logging de PHP es correcto ya que por defecto viene establecido para entornos de desarrollo.

Si puedes enviar una captura de los errores y el código fuente de la página (en el navegador), mejor.

Saludos!

**Comment by tejadon** [comment]
Vale gracias, lo haré tal como dices, si ya te digo, ami se me instala todo bien y demás pero cuando me logueo y ya me manda al index es como si no cargara bien, solo me sale el boton de la lupa a la izquierda y arriba el panelito ese donde pone que usuario tienes y demás y el botón salir, pero sale como si no hubiese cargado bien el código...

En cuanto lo pruebe te aviso. De todos modos he seguido la guía de aquí http://wiki.syspass.org/es/instalar , el servidor es linux, es un nas de synology, no se si los conocerás...

**Comment by tejadon** [comment]
ahh y otra cosa, en el inspector de codigo de chrome me mostraba errores de codigo javascript, ahora tengo que salir en cuanto vuelva te pongo todo detallado.

**Comment by tejadon** [comment]
Buenas hice todo como me dijiste pero aun así sigue pasándome lo mismo. 
![error](https://cloud.githubusercontent.com/assets/6437058/7171033/dd4e027a-e3d3-11e4-9230-7b0972be076b.jpg)

**Comment by nuxsmin** [comment]
Hola, puedes capturar el código del archivo javascript generado?

Para capturarlo tienes que abrir el enlace como en la siguiente captura:

![screenshot 222](https://cloud.githubusercontent.com/assets/1775774/7179284/7fa5fc8c-e436-11e4-831b-78b996d5c9a3.jpg)

Y verás un pantalla como la siguiente:

![screenshot 223](https://cloud.githubusercontent.com/assets/1775774/7179340/1e703922-e437-11e4-9497-0ebf2454d4e9.jpg)

**Comment by nuxsmin** [comment]
Related #98

**Comment by tejadon** [comment]
Uff esto no tiene buena pinta sale ahí como mal codificado o no sé...
![error2](https://cloud.githubusercontent.com/assets/6437058/7185144/67d0d8e0-e461-11e4-8021-9be0f620c91d.jpg)

**Comment by tejadon** [comment]
He vuelto a reinstalarlo pero con el 'display error' de php activado y tampoco lanza errores, creo que esto viene desde el javascript ¿no?

**Comment by nuxsmin** [comment]
Parece que el contenido comprimido no lo interpreta. He hecho una modificación al código para detectar el soporte de compresión por parte del cliente. Puedes descargarla desde aquí:

https://github.com/nuxsmin/sysPass/archive/master.zip

El commit es este https://github.com/nuxsmin/sysPass/commit/98c9911eb95fefd48faa16b4268de12c7e1c54ed

**Comment by tejadon** [comment]
Ok lo probaré y te diré como me ha ido. Muchas gracias.

**Comment by tejadon** [comment]
Acabo de probarlo y me sigue ocurriendo lo mismo... ¿Qué hago?

**Comment by nuxsmin** [comment]
Habrá que ver la cabecera http para ver qué devuelve el servidor de la nas.

En cuanto tenga el chrome a mano te mando capturas de cómo.

**Comment by tejadon** [comment]
El caso es que yo lo tuve instalado y no me dio problemas... fue cuando lo actualice a la nueva versión  pero borrando la anterior y demas, es decir, una instalación nueva. saludos.

**Comment by tejadon** [comment]
lo he instalado en un hosting que tengo de 1and1 y me da estos errores:

Notice: Use of undefined constant __DIR__ - assumed '__DIR__' in /homepages/33/d418961276/htdocs/sysPass/inc/init.php on line 226

Warning: Cannot modify header information - headers already sent by (output started at /homepages/33/d418961276/htdocs/sysPass/inc/init.php:226) in /homepages/33/d418961276/htdocs/sysPass/inc/html.class.php on line 99

Warning: Cannot modify header information - headers already sent by (output started at /homepages/33/d418961276/htdocs/sysPass/inc/init.php:226) in /homepages/33/d418961276/htdocs/sysPass/inc/html.class.php on line 102

Warning: Cannot modify header information - headers already sent by (output started at /homepages/33/d418961276/htdocs/sysPass/inc/init.php:226) in /homepages/33/d418961276/htdocs/sysPass/inc/html.class.php on line 103

Parse error: syntax error, unexpected T_FUNCTION in /homepages/33/d418961276/htdocs/sysPass/inc/util.class.php on line 676

**Comment by nuxsmin** [comment]
Hola, qué versión de PHP tiene el hosting?. 

El error de __DIR__ es debido a la versión de PHP: http://php.net/manual/es/language.constants.predefined.php

Los errores del tipo "Cannot modify header information" son porque se está escribiendo algo en la página antes de enviar la cabecera que indica que la codificación es UTF-8. Esto puede ser por el nivel de logging que tenga el hosting.

El último error es bastante raro, ya que hace referencia a una función anónima que se utiliza para modificar un array. También puede ser por la versión de PHP.

**Comment by tejadon** [comment]
Buenas la versión de php que tengo es la 5.5.23, el hosting es de 1and1. Entonces, ¿como hago para poder arreglarlo?, porque me encanta esta aplicación web y la queremos implementar en nuestra empresa... Lo que no se como me puede estar pasando esto porque en nuestro servidor nas de synology que tenemos en la oficina nos iba perfectamente todo, lo que pasa que no recordaba la clave  de admin para entrar porque estuve haciendo pruebas hace muchos meses y tuve que borrar y reinstalar.

¿Qué hago T.T?

**Comment by tejadon** [comment]
Tengo la opcion de cambiarla a la 5.6,5.4 o 5.2...

**Comment by nuxsmin** [comment]
Vaya...sé que cada instalación es un mundo y trato de adaptarlo a múltiples entornos, pero el problema es disponer de cada uno. Lo he instalado en Debían, Centos, Gentoo, Xampp y varios hostings, pero cualquier detalle influye...

Prueba con la versión 5.4 a ver que tal.

**Comment by tejadon** [comment]
he puesto la 5.6 y me sale pero cuando metos los datos de la base de datos y nombre de usuario etc etc me sale siempre este mensaje

El usuario de MySQL ya existe (sp_jesus)
Indique un nuevo usuario o elimine el existente

**Comment by tejadon** [comment]
ponga el usuario que ponga me sale ese error

**Comment by nuxsmin** [comment]
Prueba a crear el usuario y la bd, sin la estructura y luego selecciona el modo hosting.

**Comment by tejadon** [comment]
como que cree el usuario y luego bd? no te entiendo...

**Comment by tejadon** [comment]
a ver, la base de datos ya esta creada y tengo los datos de conexión, no hay estructura de las tablas de syspass ni nada... pero el usuario y los datos de conexión a la bd los genera 1and1 de forma auto.

**Comment by tejadon** [comment]
he marcado la opcion de hosting off con php 5.4 y 5.6 y pasa a una pagina pero con un bucle infinito de advertencias:

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /homepages/33/d418961276/htdocs/sysPass/inc/db.class.php on line 265

Warning: mysqli::query(): Couldn't fetch mysqli in /homepages/33/d418961276/htdocs/sysPass/inc/db.class.php on line 210

Warning: DB::doQuery(): Couldn't fetch mysqli in /homepages/33/d418961276/htdocs/sysPass/inc/db.class.php on line 216

Warning: DB::doQuery(): Couldn't fetch mysqli in /homepages/33/d418961276/htdocs/sysPass/inc/db.class.php on line 217

Warning: DB::doQuery(): Couldn't fetch mysqli in /homepages/33/d418961276/htdocs/sysPass/inc/db.class.php on line 220

Warning: DB::doQuery(): Couldn't fetch mysqli in /homepages/33/d418961276/htdocs/sysPass/inc/db.class.php on line 220

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /homepages/33/d418961276/htdocs/sysPass/inc/db.class.php on line 265

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /homepages/33/d418961276/htdocs/sysPass/inc/db.class.php on line 265

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /homepages/33/d418961276/htdocs/sysPass/inc/db.class.php on line 265



etc etc etc

**Comment by nuxsmin** [comment]
El modo hosting no crea ni el usuario ni la bd, por lo que el mismo usuario y clave de syspass es el que se utiliza para la conexión a la bd.

Por otro lado, para crear la estructura tienes que poner el usuario de gestión de 1and1 y su clave, ya que es el que tiene permisos para crear tablas.

**Comment by tejadon** [comment]
donde tienes alojadas las versiones anteriores, porque macho esto me desespera ya jajajaja pondré la antigua que si iva jaja

**Comment by nuxsmin** [comment]
Jajajja, en sourceforge tienes todas las versiones.

Si creas sólo el usuario y la bd en el panel de gestión de 1and1, y seleccionas el modo hosting es suficiente. Por ejemplo:

Usuario de syspass: admin
Clave: 1234

Usuario de conexión: tu_usuario_de_1and1
Cakve: clave de 1and1

**Comment by tejadon** [comment]
osea lo hago igual que antes pero sin rellenar en el formulario de syspass la clave y usuario de admin no? solo relleno los de abajo de la bd o que?

**Comment by nuxsmin** [comment]
No no, los rellenas todos como te he puesto (cambiando claves y usuarios claro)

**Comment by tejadon** [comment]
bueno pero si de todas formas me sale un bucle infinito de advertencias y no acaba... desplazas la barra hacia abajo y sigue y sigue y sigue... jajajaja me voy a pegar un tiro jaja

**Comment by tejadon** [comment]
voy a probar la 1.0.9 a ver que tal gracias por tu ayuda te ire comentando jejejeje

**Comment by nuxsmin** [comment]
Espero que te funcione.

**Comment by tejadon** [comment]
si, la 1.09 funciona bien esto es mas raro... aunque va muy lento el logueo hasta que entra... ¿por que con la nueva version no me ira?

**Comment by nuxsmin** [comment]
Me alegro de que funcione, se me ocurre que la actualices directamente como se indica en http://wiki.syspass.org/es/actualizar ya que no crea de nuevo la BD, sólo la actuliza, por lo que lo errores de BD seguramente no aparezcan.

Con respecto a la lentitud, es raro, ya que no hace comprobaciones, sólo comprueba la autentificación. Prueba a desactivar "Comprobar actualizaciones" en la configuración.

**Comment by nuxsmin** [comment]
Hola, he creado un pequeño manual para realizar la instalación en modo hosting: http://wiki.syspass.org/es/modohosting

A ver si te sirve...

**Comment by tejadon** [comment]
Buenas de nuevo campeón!

Lo de actualizar desde la 1.09 a la última versión también lo probé pero me sigue ocurriendo lo mismo lo de la codificación esa rara cuando miro el inspector de código.

He probado lo de desactivar las actualizaciones y sigue tardando en entrar, es decir, meto el login le doy a entrar y se tira cargando 15 segundos y después entra. Una vez dentro la aplicación va con fluidez pero ya sabes, los jefes son exigentes y tenerlos 15 segundos ahí hasta que entran y mas cuando siempre están estresados, eso acaba terminando en riña jaja.

Lo del modo hosting también lo he probado como dices en el manual pero me siguen saliendo errores al cargar la siguiente página en bucle infinito.

Si pudiésemos apañar lo de la lentitud en mi caso me sería suficiente.

**Comment by tejadon** [comment]
Otra cosa:

¿Tienes pensado añadirle diseño responsive a sysPass?, sería la leche.

**Comment by nuxsmin** [comment]
Hola, sigo dándole vueltas, pero es bastante complicado cuando no puedo reproducir el mismo entorno. Lo he instalado en muchos entornos (en nas nunca) con hardware y software diferente, y no he encontrado grandes problemas.

No se me ocurre nada para el problema de espera en el login, solo me h pasado con LDAP y es cuestión de timeout. Comprueba la resolucion de DNS a ver que tal.

Con respecto a la versión 1.1 puedes probar una ultima cosa. Editar el archivo /inc/util.class.php y cambiar donde pone application/x-javascript por text/javascript

Lo de responsive es complicado por la cantidad de información a presentar en pantalla. Voy a desarrollar una API para posteriormente desarrollar una aplicación móvil que conecte con un servidor que ejecute sysPass.

**Comment by tejadon** [comment]
OK probare lo que me has dicho. 

Eso de la app sería muy buena idea jejejejejeje

**Comment by tejadon** [comment]
He probado a loguearme desde la misma lan donde tenemos el nas y sigue tardando lo mismo, se me ocurre que puede ser por la configuracion de php de mi nas...

**Comment by tejadon** [comment]
Creo que vamos bien encaminados he hecho lo que me dijiste de cambiarlo a text/javascript y ahora me sale esto (he usado el modo hosting en el nas,  instala todo bien sin errores ni nada):
![sin titulo](https://cloud.githubusercontent.com/assets/6437058/7331112/547a07aa-eb03-11e4-9b50-ae8569142bc3.jpg)

**Comment by tejadon** [comment]
he observado en el código y para el css hace la misma operación al mandar la cabecera pero no entiendo porque con el css si lo hace bien y no con el javascript....

**Comment by tejadon** [comment]
Buenas perdona por tanto mensaje pero sigo ahí buscando el por qué de este fallo...
He visto en el código que comprimes los css y js para despues mandarlos con el header pero no he conseguido dar con el fallo... con los css si lo hace perfecto pero los js no... aparece ahí una codificación rara... he estado también intentando con varios conversores sacar en que tipo de codificación rara hace eso pero nada he probado de utf a iso etc etc ya me entiendes pero nada... no se si sera por mi nas o algo, el servicio de php, apache... sepa dios.....

**Comment by tejadon** [comment]
muchacho ya di con el fallo a cabezón no me gana nadie jajajajajajaja mira te comento por si alguna vez te vuelve a ocurrir con otro usuario que use un nas synology como el mio a ver.... después de leer y leer y leer y leer y leer jajaja estuve en esta web: https://ardamis.com/2010/07/11/compress-files-without-mod_gzip-or-mod_deflate/

Ahí hablan de diferentes formas de comprimir los archivos de una aplicacion web para que la carga sea mas rápida, total, una de ellas es la que tu usas (ob_gzhandler), y la primera habla sobre zlib, bien, entre a las extensiones de php de mi servicio web de mi nas y desactive el zlib y al recargar la página me lleve una sorpresa, por lo visto se estaban haciendo la puñeta o yo que sé, el caso es que ya me va y punto jajajaja

¿Qué piensas al respecto?

**Comment by tejadon** [comment]
ups se me olvidaba esto pa que lo vieses:
![sin titulo](https://cloud.githubusercontent.com/assets/6437058/7331549/5fd8a5e0-eb15-11e4-8b3c-18ca4f98a015.jpg)

**Comment by tejadon** [comment]
Insisto, perdón por tanto post pero las horas que son se me olvida ya todo... mira aquí otra captura funcionando:
![sin titulo](https://cloud.githubusercontent.com/assets/6437058/7331558/14d62e68-eb16-11e4-9c56-cd1c61d1ca97.jpg)

**Comment by nuxsmin** [comment]
Joder..cuanto me alegro de que funcione, ya que come te dije, estoy atado sin poder probar en un entorno similar.

El contenido se sigue comprimiendo si el navegador lo soporta, de hecho puedes mirar las cabeceras de respuesta, por lo que el deshabilitar la extensión no disminuye el rendimiento.

Espero que ahora te funcione mejor el login y las nuevas características de la versión 1.1

Para la 1.2 hay muchos cambios....

Seguimos!!!

**Comment by tejadon** [comment]
Ok! Creo que deberías anotar este problema especifico de los nas synology porque lo del zlib viene activado por defecto yo pondría un tema o algo de ayuda.

**Comment by nuxsmin** [comment]
Sí, haré una mención en las FAQ de la wiki.

Mira esto...

![php_ob_gzhandler_-_manual_-_2015-04-25_10 28 42](https://cloud.githubusercontent.com/assets/1775774/7332224/eefe3652-eb35-11e4-92c6-7ceb6327995b.png)

Y esto...

http://php.net/manual/es/zlib.configuration.php#ini.zlib.output-compression

Yo creo que lo mejor sería que habilitaras el módulo, ya que puede ser necesario para otras acciones como comprimir archivos desde php y más.

Ahhh, y gracias por tus prueba-error, ya que así logramos que la app sea más compatible ;)

**Comment by nuxsmin** [comment]
Hola, puede probar la última release con el módulo de zlib activado??

https://github.com/nuxsmin/sysPass/releases/tag/1.1.2.21

**Comment by tejadon** [comment]
Hey perdona compañero estaba dormido aun me he acostado de dia jejejeje voy a mirarlo.

**Comment by tejadon** [comment]
Hola, acabo de hacer una instalación limpia de la ultima revisión y no me funciona sigue haciendo lo mismo si activo el modulo zlib. Por defecto tengo deshabilitado el display_error de php pero si lo activo tampoco me muestra error.

¿Qué será?

**Comment by tejadon** [comment]
Hola, lo he solucionado así para solventar el problema que me has dicho que podría tener en un futuro. Ésto lo he hecho en el fichero util.class.php, en el metodo getMinified:

        if(self::checkZlib() && ob_start("ob_gzhandler")) {
			ini_set('zlib.output_compression', 'off');
            ob_start();
        } else {
			ob_start();
		}
De esta manera, si alguien tiene ese mismo problema deshabilitará ese módulo para este script en concreto.

**Comment by nuxsmin** [comment]
Hola, hay que darle una vuelta, ya que así deshabilitas la compresión de la
respuesta para cualquier caso, y es más, PHP recomienda usar zlib si está
disponible.

**Comment by tejadon** [comment]
Si pero lo deshabilita sólo para en ese script, no el módulo completo del servicio php, en los demas scripts sigue funcionando zlib, osea, que si por ejemplo mañana añades otra función que sea descargar todas tus contraseñas desde sysPass a un .zip no tendrías problema.

**Comment by tejadon** [comment]
O eso creo yo...

**Comment by tejadon** [comment]
De todos modos haz una prueba en algun apartado de la app de sysPass, métele esa función a ver si te genera el zip en el servidor ¿no?

**Comment by tejadon** [comment]
Ah y otra cosa, ya si me carga rapidísimo, era todo por el zlib sabes.... jaja

**Comment by tejadon** [comment]
Ah por cierto, parece ser que en el apartado de gestión de clientes, cuando metes la descripción no la guarda bien. Révisalo a ver jeje

**Comment by tejadon** [comment]
heyyy me tienes olvidado jajaja

**Comment by nuxsmin** [comment]
Eyy, aún no he tenido tiempo de probar lo que comentabas de zlib. Con respecto a la gestión de clientes, ya lo he solucionado en la última release 1.1.2.23

Gracias!!

**Comment by nuxsmin** [comment]
Hola, he lanzado nuevas versiones, has podido probar de nuevo a ver que tal va?
