### ISSUE TITLE
LDAD account import

### ISSUE THREAD

**Issue by ruzzetto** [nuxsmin/sysPass#1022]
Hello,
I've setup LDAP integration but I had to import accounts prior to let them to login. Basic authentication (without TLS) works well but I'm wondering if this is the normal application behaviour to import account and not create them the first time user log in.

Thanks,
Fabio

**Comment by nuxsmin** [comment]
Hello @ruzzetto, 

LDAP users will be created on first login and it will set the user group and profile which were saved on LDAP configuration.

Regards

**Comment by ruzzetto** [comment]
Hello @nuxsmin ,
It didn't work for me. I had to import users in order to login. What's wrong?
Regards

**Comment by bitking** [comment]
@ruzzetto we need more information to be able to determine that.

What error msg do you get in the web application and what error does the logging give.
