### ISSUE TITLE
UserAccountControl in LDAP Search Query causes LDAP failures

### ISSUE THREAD

**Issue by 4pack** [nuxsmin/sysPass#1023]
**sysPass Version**
2.1.16.18061901

**Describe the bug**
Adding UserAccountControl checks cause AD LDAP queries to fail silently.

**To Reproduce**
1. Enable LDAP and connect to a standard AD server running Windows Server 2012 R2.
2. Click Check
3. LDAP query doesn't return anything and check fails.

**Expected behavior**
LDAP query succeeds.

Removing ```(!(UserAccountControl:1.2.840.113556.1.4.804:=34))``` on lines 55 and 105 in inc/SP/Auth/Ldap/LdapMsAds.class.php fixes the issue completely. Keeping this in the query causes the LDAP search to return no values. This was also reported in #983, but it was closed and never fixed.

Commits 532e679e553b4e1a2744db1b1e62fd883df28e10 and 4ebc1c7fafe2bb0174b2df9dbbae8239910ec921 should be regressed or should be thoroughly tested first.

**Comment by nuxsmin** [comment]
Hello, I totally agree with you, that change need to be regressed since the UserAccoutControl masked code does enforce accounts with blank password.

Thanks for the feedback!

**Comment by stefanjauker** [comment]
fixed with #1050
