### ISSUE TITLE
SQL Integrity Error on creating new user and parallel "force password change" is activated

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1025]
**sysPass Version**
3.0.0.18082701-beta

**Describe the bug**
When creating a new user and activating the option "force password change" an SQL error is thrown:

![grafik](https://user-images.githubusercontent.com/5631071/44677862-51f90e80-aa37-11e8-89ca-5c2abc64fc93.png)
![grafik](https://user-images.githubusercontent.com/5631071/44677876-59b8b300-aa37-11e8-980b-3aa80a39ba9d.png)

The error is not thrown if the password option is not set

**Comment by vmario89** [comment]
one addition: the error occures but the user gets created

**Comment by nuxsmin** [comment]
Hello, it seems that the newly created user id is not being used when creating the recovery token.

It will be fixed shortly.

Kind regards

**Comment by nuxsmin** [comment]
Solved in latest commits
