### ISSUE TITLE
Clearing the event log removes the whole view

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1026]
**sysPass Version**
3.0.0.18082702-beta

**The problem:**
Clearing the event log removes the whole view

![grafik](https://user-images.githubusercontent.com/5631071/44679265-cc775d80-aa3a-11e8-8594-59853acc7ab4.png)

![grafik](https://user-images.githubusercontent.com/5631071/44679299-e2851e00-aa3a-11e8-8394-5a1ed789a11b.png)

It's not that bad error but it's ugly. After clearing there should just be an empty mask instead of oops. Yes my screenshots are bad for example, because the audit was already empty. the concept counts :D

regards, Mario

**Comment by nuxsmin** [comment]
Hello, this has been solved in latest commits.

Thanks for the feedback!
