### ISSUE TITLE
Events not sent to syslog

### ISSUE THREAD

**Issue by Eddd97** [nuxsmin/sysPass#1029]
**sysPass Version**
2.1 (2.1.16.18061901)

**Describe the question**
Hello! I am running sysPass on a box with Ubuntu 16.04. I've tried enabling syslog under "Events" section in the web UI configuration but the only events sent to syslog are the one from the screenshot below. Then nothing else is sent. Am I doing something wrong? Thanks!

**Screenshots**
![screenshot_1](https://user-images.githubusercontent.com/18093594/44849183-fbbbe380-ac61-11e8-8359-f35ddcd54a14.png)

**Platform (please complete the following information):**
 - Ubuntu 16.04

**Comment by nuxsmin** [comment]
Hello, let me check out if there is any issue about remote syslog handling.

Regards

**Comment by nuxsmin** [comment]
Solved in 3.0 version.
