### ISSUE TITLE
How do i add a language?

### ISSUE THREAD

**Issue by tbalbers** [nuxsmin/sysPass#1030]
I'm missing som info in the docs about how to add translated .po and .mo files. If I just copy them to the 
syspass/inc/locales/da_DK folder, I can't choose them in sysPass. I've checked access rights and SELinux, and everything is fine.

How do I go about getting sysPass to use my files?

**Comment by nuxsmin** [comment]
Hi, you would need to modify this file https://github.com/nuxsmin/sysPass/blob/e0d98e63e94bf5ed446ad27db4013682895d3e88/inc/SP/Core/Language.class.php#L171 and add an entry in the array of languages.
