### ISSUE TITLE
Authenticator check people with it

### ISSUE THREAD

**Issue by romoromor** [nuxsmin/sysPass#1031]
Hi,

please, can i check, if user has two factor authentication set?

In DB i don't see any record. I think, that is in user_preference column encrypted? Can i read it somehow?

Thanks

**Comment by nuxsmin** [comment]
Hi,

It can't be done by 'the easy way' since plugins' data are stored using PHP objects because their data could be variable, so PHP objects is the best way to store them without polluting the database.

It can be done by unserializing the database field plugin_data in plugins table.

Regards

**Comment by romoromor** [comment]
Thanks for answer.
Please, could you help me, how i can deserialize plugin_data column?
I didn't use PHP object anytime. But in PHP i programmed.

Thanks

**Comment by romoromor** [comment]
Yes, i understand, but if i try unserialize, i have only error.
Could you please put here some small code for unserialize data from půugin_data?
Thanks and sorry for annoyance.

**Comment by nuxsmin** [comment]
It could be caused by a missing class object. Here you have a piece of code that should work (not tested):

```php
include '/path_to_syspass_root/inc/SP/Plugins/Authenticator/AuthenticatorData.class.php';

$data = 'paste_here_the_data_from_db';

$pluginData = unserialize($data);

foreach($pluginData as $userData) {
  echo 'User ID: ' . $userData->getUserId();
  echo '2FA Enabled: ' . (int)$userData->isTwofaEnabled();
}

// Comment out the next line to dump all the data
// var_dump($pluginData);
```

Regards

**Comment by romoromor** [comment]
But you have in dtabase plugin_data column encode data. I can't put data from table directly to $data variable. But base64 decode doen't work. What coding you use?

**Comment by nuxsmin** [comment]
It's a blob type field, so data is saved in binary mode. Could you get it in hexadecimal encoding?

**Comment by romoromor** [comment]
Yes, in table are data in HEX format.

**Comment by nuxsmin** [comment]
Please, get the data from the table and set as follows:

```
$data = pack('H*', 'put_hexadecimal_data_here';
```
