### ISSUE TITLE
Failed Import of Accounts from one version of SysPass to another + asking for the admin password multiple times

### ISSUE THREAD

**Issue by Felipe-Tendril** [nuxsmin/sysPass#1032]
**sysPass Version**
3.0-beta (300.18090201) && 3.0-beta (300.18040302)

**Describe the bug**
Bug 1) Cannot import accounts from an exported SysPass.xml file from 3.0-beta (300.18040302)
Bug 2) Needing to enter the master password often when signing into admin account 

**To Reproduce**
Steps to reproduce Bug 1) 
1. Sign into admin account
2. Click on "Configuration"
3. Click on "Import Accounts"
4. Enter the .xml file password and master password from previous syspass version
5. Drag the .xml file into the upload window. 
6. Get error: 
"There was an error
SyntaxError: Unexpected token C in JSON at position 0parsererror" for  3.0-beta (300.18040302) 
and 
"Notice: Trying to get property of non-object" for 3.0-beta (300.18090201)

**To Reproduce**
Steps to reproduce Bug 2) 
1. Sign into admin account and type password
2. Get asked to re-enter password 
3. Get asked to enter password and master password

**Expected behavior**
Bug 1) For SysPass to load and import the accounts OR give a more detailed error (if it was a user error, what I did wrong). 
Bug 2) Only ask for my admin password once, when I know 100% that I typed it in correctly, and not need the master password

**Screenshots**
None needed. 

**Event log**
Some lines from `syspass.log` file (within `config` directory) and sysPass event log that were logged when the error happened.

3.0-beta (300.18040302): https://pastebin.com/v9uPAG9N
3.0-beta (300.18090201): https://pastebin.com/vRRdK7sJ

**Host Platform:**
 - OS: Cent OS 7 Minimal Installation (no gui)

**Guest Platform:**
 - OS: Windows 8.1 Pro
 - Browser Chrome 68.0.3440.106 x64

**Additional context**
Take your time on the fix :)

**Comment by Felipe-Tendril** [comment]
Also, these are the install instructions that I use to install SysPass onto Cent OS 7 (but changing the .tar.gz file to the ones that I listed above): https://pastebin.com/wrzyqyY0

**Comment by nuxsmin** [comment]
Hello Felipe,

Could you tell me which sysPass version was used to export the imported file?

About the 2nd bug, are you entering the username in same letter case on every login?

Regards

**Comment by Felipe-Tendril** [comment]
1) 300.18040302 exported the file
2) Just tested this, and yup, changing the letter case does cause this. Is this fixable so that Admin == admin ?

**Comment by nuxsmin** [comment]
> 1. 300.18040302 exported the file

There were a lot of changes since this release and one of the is an HMAC hash that is added to the XML document, so in this way sysPass can chack the XML data integrity (not altered). You could add it by performing an export and copy&paste a line started with '<Hash ...'. When importing it will complain about the data integrity.

> 2. Just tested this, and yup, changing the letter case does cause this. Is this fixable so that Admin == admin ?

It seems you're using LDAP, though it does not check login letters case, but sysPass will do, since it's a security mechanism and adds more entropy for the derived key for encrypting the master password using the user's data.

Regards
