### ISSUE TITLE
Azure Active Directory for Authentication

### ISSUE THREAD

**Issue by volands** [nuxsmin/sysPass#1033]
**Describe the question**
It is possible to use Azure Active Directory (https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-whatis) for Authentication with Syspass? I see it is possible to use LDAP and AD for Authentication - but I am not quite sure if this is also possible with the Azure AD (with the described way for AD). If it is possible, are there some more documentation in this context? 

Thanks and best regards,
Patrick

**Comment by alexanderbuhler** [comment]
Since slow but steady deprecation of our ldap dir towards azure I'd like to support this question. I think it might be related to OAuth integration, though, since azure offers an OAuth service for authentication.

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in latest commits on v3

Regards
