### ISSUE TITLE
Changing the user's language does not enforce to refresh page after saving the setting

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1035]
**sysPass Version**
3.0.0.18090201-beta

When changing the user language the UI should reload automatically when saving the settings. Additionally maybe some language caches should be deleted too. At the moment the user has to refresh the page manually. I expect to have instant reload of the page afte pressing the save button for smoother usability.

regards, Mario :)

**Comment by nuxsmin** [comment]
Hello!, I was implemented indeed, but there was a condition that was being triggered before the page reloading, so it didn't take effect. It has been solved in latest commit.

Thanks for the feedback!
