### ISSUE TITLE
Download backup issue

### ISSUE THREAD

**Issue by KopNudler** [nuxsmin/sysPass#1036]
**sysPass Version**
2.1.16.18061901

**Describe the question**
I can't download my backups. My browser asks to open or save the file, and no matter what it just fails. Nothing shows in apache error_log, or syspass.log

**Platform (please complete the following information):**
CentOS 7

**Comment by nuxsmin** [comment]
Hello, 

Are you downloading them from sysPass UI?. Be aware that, for security reasons, the Apache config does not allow to download files from sysPass' backup and config directories.

Regards

**Comment by nuxsmin** [comment]
Hi, it's easy, but I wouldn't recommend to change them unless you're sure, since allowing to access to backup files from an untrusted network or PC, would leak your sysPass data (though the data is encrypted).

Cheers
