### ISSUE TITLE
AD Import Users

### ISSUE THREAD

**Issue by lvalentin** [nuxsmin/sysPass#1037]
**sysPass Version**
2.1 (2.1.16.18061901)

**Describe the question**
Import users from Active Directory works fine on the configuration ldap page (Configuration > LDAP), all my users are created, it is ok. BUT the import (LDAP) button on the users manage page (Users and Accesses > Users) doesn't work. Why ?

With the import button on the users manage page, the action is notify like a success. However no users created on the page. Reload page doesn't change anything. On the event log page two events for this action : 

1) LDAP users import finished
Imported users : 0/42
Errors : 0
2) Synchronization finished
Objects found : 42

So, no import without errors...

Unlike with an import from the configuration ldap page, for example : 

LDAP users import finished
Imported users : 42/42
Errors : 0

Did I do something wrong ?

Thx

**Comment by nuxsmin** [comment]
Hello @lvalentin 

This behavior is caused because LDAP import attributes can only be set from the LDAP configuration tab, so importing from users tab won't set the correct attributes for data mapping (ie. name, email, etc)

Kind regards.

**Comment by lvalentin** [comment]
Hi @nuxsmin 

Ok thank you.
