### ISSUE TITLE
Expiry Date won't be removed properly

### ISSUE THREAD

**Issue by D3luxee** [nuxsmin/sysPass#1039]
Hi,
I've experienced some unexpected behavior in syspass 2.1.16.18061901.

If you create a new account and remove the password expiry date it sets the field to `TT.MM.JJJJ` but after saving the account the field is set to 12.12.2018 (3 months in the future).

In the "Edit Account" dialog i can remove the field again and save it, which will finally remove the password expiry.

I will test this behavior in v3 later on this day.

**Update:**
I could not reproduce the behavior in v3 and i appreciate the option to enable / disable it globally.

Regards

**Comment by nuxsmin** [comment]
Hello, sorry I didn't notice about your update..

An option to disable the accounts' password expiry date was added in v3.

Thanks for the feedback!
