### ISSUE TITLE
Tag creation on the fly

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1041]
Hey,
i just have a small feature request regarding to creation of tags. Would it be possible to directly add new tags when creating a new account? For customers and categories it is already possible :-)

**Comment by nuxsmin** [comment]
Hey!

It has already been implemented though it hasn't pushed yet. I'll perform some tests and it will be ready shortly.

Thanks for the feedback!

All the best

**Comment by nuxsmin** [comment]
Hello, just pushed the commit which implements this feature ;)
