### ISSUE TITLE
Migration Caused Database Issue

### ISSUE THREAD

**Issue by govpsadmin** [nuxsmin/sysPass#1042]
**sysPass Version**
2.1 (2.1.16.18061901)

**Describe the bug**
I migrated my Syspass instance to another server using the cPanel account transfer tool (exact copy of every file and setting) but when I logged in the only entry available is a placeholder entry that lists "1" for all its info.

**To Reproduce**
1. Login
2. See the lack of entries showing up

**Expected behavior**
I expected the entries to show properly.

**Screenshots**
![screen shot 2018-09-21 at 3 22 47 pm](https://user-images.githubusercontent.com/43484370/45908607-4557a400-bdb2-11e8-96f7-af9ad699b945.png)

**Event log**
No errors are getting thrown for this problem.

**Platform (please complete the following information):**
CentOS 7.5 + cPanel & WHM accessed with Chrome

**Additional context**
I had to remake the database user after the migration as it did not get copied over. I used the same database password as before and can verify that all entries are still in the database. They just don't show up when someone logs in.

**Comment by nuxsmin** [comment]
Hello, it seems that the database views do not have the correct permissions. Please make sure that sysPass database user is the owner of these views.

Regards
