### ISSUE TITLE
v3 Account name as link for user don't have permission to see account detail

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1047]
**sysPass Version**
0.3-beta

**Describe the bug**
When the "Account name as link" is enabled, an user without permission to see account detail have the link and when he clic on it they have a message : 
`You don't have permission to access this page

Please contact to the administrator `

**To Reproduce**
- Enable "account name as link" option
- login into an account without account detail permission
- clic on account link

**Expected behavior**
It's possible to not print the link to account detail if the user haven't the permission?

**Comment by nuxsmin** [comment]
Hello, unfortunately I cannot reproduce this issue and looking into the code it's implemented as expected, if an user does not have view permission over the account, the account link won't be displayed though it was set on user's preferences:

https://github.com/nuxsmin/sysPass/blob/2581dfd44dab10ab5843557051b94f783338803c/app/modules/web/themes/material-blue/views/account/search-rows.inc#L44

Kind regards

**Comment by nuxsmin** [comment]
Could you provide a more detailed use case?

Thanks!

**Comment by pierrehenrymuller** [comment]
I have an account in a group who have a profil with just only "View password" right, no "View" option.
With disable "Account name as link" admin or user don't see link<
When I enable "Account name as link" option, the simple user have now a link for each account with no permission when he click on it.
