### ISSUE TITLE
why differ import format from keepass csv export format?

### ISSUE THREAD

**Issue by fwilly** [nuxsmin/sysPass#105]
I have export a folder in KeePass 2.29 as KeePass CSV 1,x (an other CSV export format isn't possible). The file has following format:
> `"Account","Login Name","Password","Web Site","Comments"`

But your help say the format must be:
> `"account_name","customer","category","url","user","password","notice"`

Why I must reorder it, if it should be for KeePass import?
When will be a XML import available?
For this point I can not found helps or docus?

**Comment by nuxsmin** [comment]
Hi, XML import is available at this point. You can choose between XML or CSV, because it automatically detects the file format.

**Comment by fwilly** [comment]
Yes, with XML it is okay. The help on the drop field could be better.

**Comment by nuxsmin** [comment]
You are right, help is bit confusing. Main doc is at wiki.syspass.org but this kind of help has not being yet written. It will be available in short.

**Comment by nuxsmin** [comment]
Solved.
