### ISSUE TITLE
Tag adding on the fly removes existent tags from Account in view

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1052]
Hi,
in the current beta when you add tags to an acount and then you new tags from the view, the old tags are getting deleted from the view. means you have to re-add all previous tags.

i wanted to try out if it appears in the demo too but in demo i cannot store accounts. Seems to have a bug

regards, Mario

**Comment by vmario89** [comment]
Hi nux,
this is fixed but i think something is missing. If you add the tag it should also be automatically added into the Tags line of the account:

Step 1:
![grafik](https://user-images.githubusercontent.com/5631071/46372423-627e5380-c68b-11e8-8918-6aed962f2039.png)

Step 2:
![grafik](https://user-images.githubusercontent.com/5631071/46372373-3e227700-c68b-11e8-918f-cdcdf0dd5395.png)

Step 3:
the same view like step 1, because you have to select the tag again from the tag list.

Wish:
![grafik](https://user-images.githubusercontent.com/5631071/46372380-44185800-c68b-11e8-8d2c-418310974d7f.png)

regards, Mario

**Comment by nuxsmin** [comment]
Hi, you're right, and honestly I thought about it, but since it would require some time coding to get the newly created item and push it to the tags list, I let this behavior for later.

It also could be applied to clients and categories list.

Regards

**Comment by vmario89** [comment]
hey,

okay so maybe leave it as feature request for future work :D. I think there are around 500 other feature requests right now :D By the way i am thinking about writing some sysPass v3 documentation because many information is missing and can only be found be deeply crawling all the issues on github. Would be great to have some descriptions about installation, updating, docker usage, compability, usage of API, usage of special features, pitfalls, roadmap, license, overview of pages like syspass.org, gitter, third party plugins, etc. etc. etc.

What about the roadmap of syspass v3? I think some content update for this might be good^^

- https://github.com/nuxsmin/sysPass/projects/2
- https://github.com/nuxsmin/sysPass/milestone/5
- https://github.com/nuxsmin/sysPass/issues/422

 i hope some more developers will join this project to contribute some stuff in the intended. :)

regards, Mario

**Comment by nuxsmin** [comment]
Sure! Documentation will be completed as soon as the v3 is ready to be released, because there will be some new features. I'm currently focused on finishing this release and then start with other tasks like the documentation or the web site, which I will redesign to include a blog and some media content.

It's a large way but step by step it will be achieved though programming is an endless project...

Regards
