### ISSUE TITLE
API to get account details

### ISSUE THREAD

**Issue by xxCoDeBoX** [nuxsmin/sysPass#1053]
I am unable to get the account details : 
curl -k -X POST -d '{"jsonrpc": "2.0","method": "getAccountSearch", "params": { "authToken": "xxxxxxx"} }' -o - https://server_name/api.php

This is the error : 
{"jsonrpc":"2.0","error":{"code":-32600,"message":"Wrong format","data":""},"id":null}

I dont know the id which needs to be put  , can u please help me with this

**Comment by nuxsmin** [comment]
Hello, the id parameter (required) is only used when sending multiple requests to the server, so it can return a reply for each request by referring to the original id. It can be set to 1.

Regards

**Comment by xxCoDeBoX** [comment]
When I set it to 1 the result is empty
