### ISSUE TITLE
Translation Bug in Emails

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1055]
**sysPass Version**
300.18093001

Hey. I put language of syspass and Ubuntu to de_DE.UTF-8. I get emails with german content but spanish titles. The problem occured in all devel-3.0 versions i tested.

![grafik](https://user-images.githubusercontent.com/5631071/46315524-f8ec3f80-c5cd-11e8-9b73-23bbb99e2266.png)

**Comment by nuxsmin** [comment]
Hey, it should be solved in latest commit.

Thanks for the feedback.

PS: I've received your email. I'll give you some feedback tomorrow, it's late.. going to sleep :)

**Comment by nuxsmin** [comment]
Solved in latest commit
