### ISSUE TITLE
Forgotten Master Password - Where I can find DEBUG BOX?

### ISSUE THREAD

**Issue by wszychta** [nuxsmin/sysPass#1056]
Hi,

I have read earlier issue:
https://github.com/nuxsmin/sysPass/issues/621
I copied script and turn on debug mode.

I don't know how to find magic "debug box". I don't see DEBUG logs in event log, and in syslog on machine. I'm not familiar with browser console and I don't know if I need it.
Can you help me with some manual?

Thank you for your help.

**Comment by nuxsmin** [comment]
Hi, debug box should be showed up on every page, but the user needs to be an application admin.

Regards

**Comment by wszychta** [comment]
Thank you for you advise! I found that box after login to admin account :)

Regards
