### ISSUE TITLE
Delete Customer

### ISSUE THREAD

**Issue by FrancescoOriglia** [nuxsmin/sysPass#1057]
sysPass Version 2.1.16

Hello,

I can't delete some customers and I don't know why.

![image](https://user-images.githubusercontent.com/19547118/46360416-62edfe80-c639-11e8-811f-0f209677eaf7.png)

And I don't use them at all : 

![image](https://user-images.githubusercontent.com/19547118/46360484-8dd85280-c639-11e8-8426-c923e955bb50.png)

Did I miss something ? 

Thank you for your help.

**Comment by nuxsmin** [comment]
Hello, it should be caused by customers assigned to accounts in history. Some items need to be related using integrity constraints.

Please take a look to accounts history tab.

Regards

**Comment by FrancescoOriglia** [comment]
It works now, thank you for your fast help.

Sincerely,
Francesco Origlia
