### ISSUE TITLE
Delimit ; in input field

### ISSUE THREAD

**Issue by mota0006** [nuxsmin/sysPass#1059]
**sysPass Version**
2.1 (2.1.16.18061901) 

**Describe the question**
Hello, I am attempting to import a CVS file into sys pass. However some of my fields contain a ";" in the input field. How can I delimit these characters? I have tried to enclose it in "" however I get an error when trying to import.

I have also tried enclosing the ; in ##, '', //

I am using the following format

account_name;customer;category;url;user;password;notes

Thanks and regards,

**Comment by nuxsmin** [comment]
Hello, unfortunately sysPass v2 CSV import process lacks of some functionalities like this one and others like multiline fileds, etc, because legacy support. It was improved in sysPass v3 which will be ready for production shortly.

Regards

**Comment by mota0006** [comment]
Thank you... so syspass v2 does not support multiline imports? I am faced with importing multiline notes. However, this is breaking my import!

When can we expect v3 release date?

Thanks and regards,

**Comment by nuxsmin** [comment]
I'm sorry for the inconvenience, but as the only developer, I cannot afford to be on both sides...

I'm currently finishing the last refinements and tweaks, so in next weeks will be available the release candidates, previous to 3.0 release. You could take a look or give a try on releases page.

Regards.
