### ISSUE TITLE
v3 phpunit tests

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1061]
Hi,
I think I have a regression when a call to an account/delete with API I have always an 500 error.
I would like to launch phpunit over all tests but, it didn't launch anything.
How you start tests with phpunit in this project?

I have tested : 
```
phpunit --configuration phpunit.xml
APP_ROOT=/XXXX/docroot
TEST_ROOT=/XXXX/docroot/tests
SELF_IP_ADDRESS=X.X.X.X
Deleting /XXXX/docroot/tests/tmp
Deleting /XXXX/docroot/tests/res/cache
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.



Time: 105 ms, Memory: 6.00MB

No tests executed!

Generating code coverage report in Clover XML format ... done


Code Coverage Report Summary:
  Classes:  0.00% (0/224)    
  Methods:  0.00% (0/2117)   
  Lines:    0.00% (0/16667)  
```
and with specific file I have : 
```
phpunit --configuration phpunit.xml SP/Modules/Api/ApiTest.php
APP_ROOT=/XXXX/docroot
TEST_ROOT=/XXXX/docroot/tests
SELF_IP_ADDRESS=X.X.X.X
Deleting /XXXX/docroot/tests/tmp
Deleting /XXXX/docroot/tests/res/cache
Class 'SP/Modules/Api/ApiTest' could not be found in '/XXXX/docroot/tests/SP/Modules/Api/ApiTest.php'.
```

Anybody can tell me how to launch tests?

**Comment by nuxsmin** [comment]
Sure, here you have the way they're launched through Travis CI: https://github.com/nuxsmin/sysPass/blob/devel-3.0/.travis.yml

Be aware that there are 2 different test suites, Core and Modules. The latter is used to launch the API tests. Another key point is the database set up, which needs to be performed before launching the API tests. API tests need also to have set the correct API token and key.

Regards

**Comment by pierrehenrymuller** [comment]
ok thanks but I can test this in production server. I will check in dev env later.
