### ISSUE TITLE
Once LDAP is enabled, local accounts no longer work

### ISSUE THREAD

**Issue by dcotruta** [nuxsmin/sysPass#1065]
**sysPass Version**
3.0-beta (300.18093001)

**Describe the bug**
Once LDAP is enabled (which is awesome) any local account (created either before or after fails at login with a generic [in the frontend] "Internal Error".

**To Reproduce**
1. Enable and configure LDAP
2. Create a local user account
3. Attempt to log in via local account.

**Expected behavior**
Local accounts should still work even when LDAP is enabled.

**Event log**
[https://apaste.info/q2EN](https://apaste.info/q2EN)
from attemptiong login the error seen at
[2018-10-10 16:59:17 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Internal error]

**Platform (please complete the following information):**
UBUNTU 18.04
Apache/2.4.29 (Ubuntu)

Version: 7.2.10-1+ubuntu18.04.1+deb.sury.org+1
SERVER_VERSION : 5.7.23-0ubuntu0.18.04.1
CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $

**Comment by odavis1** [comment]
Hi,
I am a colleague of dcotruta, I have pulled the latest version of syspass v3 (3.0-beta (300.18101101))
however this issue is still persistent with the same outcomes.

**Comment by nuxsmin** [comment]
Okay, please let me figure out what could be happening.

It seems that LDAP exception is no being taken into account, so it tries to update an unknown user.

**Comment by nuxsmin** [comment]
Hi, this issue should be solved in latest commit. Some LDAP error codes weren't passed through the stack, so it yields on a non-errored LDAP result which was managed as a normal login and updating the user's data though it wasn't available.

Thanks for the feedback!

Regards
