### ISSUE TITLE
LDAP Groups

### ISSUE THREAD

**Issue by M1k13** [nuxsmin/sysPass#1066]
sysPass Version 2.1.16.1806190

LDAP group sync

Is it possible to import/sync the groups that are configured in LDAP to syspass so that syspass also will have those groups instead of manual re-adding the groups in syspass?

**Comment by nuxsmin** [comment]
Hello, unfortunately this feature has been implemented in v3, which will be ready for production shortly.

Regards

**Comment by AntonTsaberyaby** [comment]
@nuxsmin Hello, sorry. Is this feature ready now for production?

**Comment by nuxsmin** [comment]
@AntonTsaberyaby sure, sysPass v3 was released in January.
