### ISSUE TITLE
SSL Certificate on syspass docker

### ISSUE THREAD

**Issue by CleemL** [nuxsmin/sysPass#1067]
Hi, 

I installed docker-compose on a debian, and a syspass.
I forced SSL on the syspass config
I wanted to add my own certficate, trusted by a CA

But I can't even edit the file in
syspass-app:/etc/apache2/sites-available/default-ssl.conf

So , I don't wanted to add a reverse-proxy on my host or on an other host and wanted to know if it's possible to change the certificate file used by syspass ?

And what if I replace the file ssl-cert-snakeoil by my certificate with that name?

Regards,

**Comment by nuxsmin** [comment]
Hi, you should bind-mount this file from the Docker host, so you could set your own SSL configuration. In this way the container configuration won't be affected by updating the base image.

Keep in mid that Docker containers should be scaled out regardless their configuration, so many containers (ie. updated images) should use the same configuration.

Regards.
