### ISSUE TITLE
Attachment files through API

### ISSUE THREAD

**Issue by FrancescoOriglia** [nuxsmin/sysPass#1068]
sysPass 2.16

Hello,

Thanks to your help, everything is working fine now, I have a question, is it possible to get attachment files throught API ?

Sincerely,
Francesco Origlia

**Comment by nuxsmin** [comment]
You're welcome.  I'm glad to know it's working fine.

Unfortunately, the attachment posting through API is not available, but it can be implemented in future releases, since it would be an useful feature for accounts that require a certificate file or other kind of file.

Thanks for the feedback!

**Comment by FrancescoOriglia** [comment]
Exactly, we need that for SSL certificate :)

Thank you for your answer.

**Comment by M1k13** [comment]
Hey Ruben,

Is there a way that I can install syspass 3.0 without using ius or Remi packages? So I only would like to use packages from ‘base’ ‘epel’ and ‘scl’

Kind regards,
