### ISSUE TITLE
Bug: Al tratar de Agregar "Extensiones de archivos permitidas"

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#107]
Guarda los cambios, pero no se aplican. 

Investigando un poco, veo en los logs:

[Fri May 29 13:04:39.621762 2015] [:error] [pid 2478] [client 10.0.1.39:58390] PHP Fatal error:  Cannot use object of type stdClass as array in /var/www/html/syspass/inc/util.class.php on line 234, referer:

**Comment by nuxsmin** [comment]
Buenas, ese error es referente al método utilizado para detectar actualizaciones.

Voy a revisar el código de las extensiones, pero recuerda que tras añadirlas tienes que guardar la configuración.

**Comment by nuxsmin** [comment]
El fallo de las extensiones esta localizado en el nombre de la variable que se utiliza en el archivo config.php 

En breve publicaré una revisión con este fallo resuelto.

Gracias!
