### ISSUE TITLE
v3 account length

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1071]
Hi,
Is there a reason why accounts should be at maximum 50 characters?

I would like to have account with more chars to be explicit, exemple with a very long FQDN and other infos I can simply over 50 chars : 
server-name long-subdomain.domain-very-long.com loginforuser1 MySQL

Thanks

**Comment by Titus1024** [comment]
Could you not put the hostname as the account name and then put the FQDN in the notes? I imagine the 50 character limit is for formatting but that's just my assumption.

**Comment by pierrehenrymuller** [comment]
In fact our development around syspass especially from Ansible, we decided that account name should be unique.

If we imagine we do a "test" login on a server and to prepare a future server we recreate the "test" user we have a duplicate account.

The idea was to put the maximum information in the account name to make it unique.

There I started to simplify by putting only the server name and login in account name. Then use tags for environments (production, test, dev, rec,...). The url to put the name of the server.
It should pass but I'm not safe from a long enough server name and a slightly longer login that would make me exceed 50 characters.

If it's a formatting problem in the webui, okay to cut beyond 50 in list and print in view details. The goal is that when I search for a character string in account name it should be done on a longer string to be unique.

**Comment by nuxsmin** [comment]
@pierrehenrymuller I agree with you. It's a size limit to avoid performance issues on the database side, but it could be raised though it would be hard to see a long account name.

Noted down for v3. Thanks for the feedback!

Regards

**Comment by pierrehenrymuller** [comment]
Hi,
Feedback with a local change of table structure to `name` varchar(255) since 4 months without problems. The display is not a problem for our team.
Thanks

**Comment by nuxsmin** [comment]
3.1-RC1 has been released out, please check it out for solving this issue.
