### ISSUE TITLE
After unzip SysPAss not working

### ISSUE THREAD

**Issue by tjani10** [nuxsmin/sysPass#1072]
**sysPass Version**
2.1.16

**Describe the question**
Hi Guys,

I need some help in the Syspass install.
After I read the whole install guide for CentOS7 I can't open the main page.
The network is good and port 80 is up. But when I try to connect the server the browser says it is not reachable..
I followed the guide but I think I need to configure something in the apache that this page will be reachable.
I am not expert in the apache.
Can someone help to me?

**Platform (please complete the following information):**
 - OS: CentOS 7 
 - OS version: CentOS Linux release 7.5.1804 (Core) 
 - Browser: Chrome (Version 69.0.3497.100 (Official Build) (64-bit))

Thanks for your help!
BR
jani

**Comment by tjani10** [comment]
Hi,

How can I see which PHP module is missing?

BR
Jani

**Comment by tjani10** [comment]
Now the index.php can be visible, but I just see the code.

**Comment by tjani10** [comment]
in 658 case, you mentioned PHP module isn't allowed. How I can allow the necessary PHP module(s)?

thanks!

**Comment by nuxsmin** [comment]
Unfortunately I don't remember how to enable on CentOS. If it's displaying the PHP code, the PHP is not enabled at all in the web server configuration. You can take a look to the web server log if there are some error messages.

Regards

**Comment by tjani10** [comment]
I find the cause.
the php.conf file was missing under /etc/httpd/conf.d/
These packages are necessary on the CentOS 7:
# yum list installed | grep -i php
php.x86_64                          5.6.38-1.el7.remi                @remi-php56
php-cli.x86_64                      5.6.38-1.el7.remi                @remi-php56
php-common.x86_64                   5.6.38-1.el7.remi                @remi-php56
php-fedora-autoloader.noarch        1.0.0-1.el7                      @epel      
**php-fpm.x86_64**                      5.6.38-1.el7.remi                @remi-php56
php-gd.x86_64                       5.6.38-1.el7.remi                @remi-php56
php-ldap.x86_64                     5.6.38-1.el7.remi                @remi-php56
php-mbstring.x86_64                 5.6.38-1.el7.remi                @remi-php56
php-mcrypt.x86_64                   5.6.38-1.el7.remi                @remi-php56
php-mysqlnd.x86_64                  5.6.38-1.el7.remi                @remi-php56
php-pdo.x86_64                      5.6.38-1.el7.remi                @remi-php56
php-pear.noarch                     1:1.10.6-1.el7.remi              @remi-php56
php-pecl-jsonc.x86_64               1.3.10-2.el7.remi.5.6            @remi-php56
php-pecl-sqlite.x86_64              2.0.0-0.7.svn332053.el7.remi.5.6 @remi-php56
php-pecl-zip.x86_64                 1.15.4-1.el7.remi.5.6            @remi-php56
php-pgsql.x86_64                    5.6.38-1.el7.remi                @remi-php56
php-process.x86_64                  5.6.38-1.el7.remi                @remi-php56
php-xml.x86_64                      5.6.38-1.el7.remi                @remi-php56

on this page, I find the repo configuration:
https://www.tecmint.com/install-php-5-6-on-centos-7/

thanks!

**Comment by nuxsmin** [comment]
Fine, you're welcome!
