### ISSUE TITLE
import more then 10k passwords

### ISSUE THREAD

**Issue by tjani10** [nuxsmin/sysPass#1075]
Hi,

is there any template what I can use to create an xml for passwords import into the syspass?

we have  too much passwords what I don't want to move one by one into syspass.
I would like to see a xml template what I can use to create a new from our passwords records.

Can you help me in this case? Is it possible in the SysPass 2.1.16?

Thanks for your help!
jani

**Comment by nuxsmin** [comment]
Yes. The CSV file format is displayed by clicking on the help of import tab (configuration).

**Comment by tjani10** [comment]
huge thanks!!!

I see the format :)
