### ISSUE TITLE
Integrity check failed

### ISSUE THREAD

**Issue by FrancescoOriglia** [nuxsmin/sysPass#1078]
sysPass 2.1 (2.1.16.18061901)

Hello,

We tried to import some accounts from a sysPass 2.1 (2.1.14.17090102), we can see the accounts but we got "Integrity check failed" when we want to see the password.

I saw in your previous issues, that it could be because of the master key ?

Thank you for your help.

Sincerely,
Francesco Origlia

**Comment by nuxsmin** [comment]
Hello, I'm wondering why you're trying to import the accounts from a previous version, because sysPass can be upgraded from an older version.

The integrity check failed message means that the current master password, used for decrypt the accounts' password, does not match.

Regards.

**Comment by FrancescoOriglia** [comment]
Cause the previous syspass is on a server that we don't want to use anymore, we just need to take the old accounts into our new infrastructure.

The current master password does not match with the 2.1.14 sysPass's password ?
So If I change the password and then, I export account again it should work ? 

Thank you for your fast answer.

**Comment by nuxsmin** [comment]
Hmm, why not to import the database?. By exporting/importing the accounts you will loss many data related to permissions, users, groups, etc.

If you continue importing the accounts, you will need to set the correct master password, but do not re-encrypt the accounts (there is an option on encryption tab), because it will fail.

Regards

**Comment by nuxsmin** [comment]
You can actually (in current instance) perform a master password change without re-encrypting the imported accounts.

**Comment by FrancescoOriglia** [comment]
We don't want to import database cause permissions, users and groups are not the same in the new instance, we decided to change everything.

I changed the master password : 

![image](https://user-images.githubusercontent.com/19547118/47179996-73ff6680-d2ed-11e8-97cb-6c8d54f4ffa0.png)

But I have still the " Integrity check failed " when I try to see a password.

**Comment by nuxsmin** [comment]
In such case, why not to import by setting the old master password?. There's an option to set the source master password on the import tab.

**Comment by FrancescoOriglia** [comment]
Yup, by modifing accounts, everything work now.

Thank you anyway for your help.

**Comment by nuxsmin** [comment]
@FrancescoOriglia fine, glad to know it works, but...

> by modifing accounts, everything work now.

What does it mean?, Did you set every password again?

Regards

**Comment by FrancescoOriglia** [comment]
Hello,

Sorry for the late answer, I just didn't check this box when I changed Master Password : 

![image](https://user-images.githubusercontent.com/19547118/47314613-285ffc00-d610-11e8-973c-e43a36394abe.png)

And everything seems to work fine now.

Sincerely,
Francesco Origlia

**Comment by nuxsmin** [comment]
I'm glad to know it works fine now. This was the option I pointed to.

Regards
