### ISSUE TITLE
User and pass stored in clear text in the web server logs

### ISSUE THREAD

**Issue by dajones70** [nuxsmin/sysPass#1079]
**sysPass Version**
2.1

**Describe the bug**
Web server logs show the GET user and pass arguments in clear text

**To Reproduce**
grep pass= /var/log/httpd/sysPass-ssl-access.log

**Expected behavior**
I am not a web developer but I am pretty sure this information should be sent as POST headers and not as arguments that will be recorded the web server logs in clear text.

**Screenshots**
172.27.0.21 - - [18/Oct/2018:15:21:03 -0500] "GET /ajax/ajax_doLogin.php?user=admin&pass=cleartextpassword&oldpass=&mpass=&login=1&isAjax=1&_=1539894060446 HTTP/1.1" 200 107 "https://syspass.example.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"

**Platform (please complete the following information):**
 - OS: CentOS
 - OS: 7
 - PHP: 7.0.32 (IUS repo)
 - LDAP: enabled pointing to Active Directory
 - Browser: any

**Comment by nuxsmin** [comment]
Hmm, it's weird since sysPass uses PKI for encrypting every password field. You could check the code for it. This behavior could be caused by:

* PKI certificates couldn't be generated in config directory
* Some JavaScript issue

Regards

**Comment by nuxsmin** [comment]
Client side:
https://github.com/nuxsmin/sysPass/blob/4bcbab1e2b75063470c515af26272a45ae0ed7db/js/app-main.js#L632

Server side:
https://github.com/nuxsmin/sysPass/blob/4bcbab1e2b75063470c515af26272a45ae0ed7db/inc/SP/Controller/LoginController.class.php#L122

**Comment by dajones70** [comment]
Note that this is in the Apache logs so this is being logged post decryption by the web server.

Is the code treating the admin user differently?

This is my user account:

sysPass-ssl-access.log-20181230:172.27.0.212 - - [28/Dec/2018:12:26:42 -0600] "GET /ajax/ajax_doLogin.php?user=**djones**&pass=AUXlzic6Rm1oRFaRxobs%2BngzVPDThgurTKFr8r1Sq94BgZIrExcQD4lg20koj6SNJ8mpB%2B6IHRHFWtIlVYhc6zDKdlTm0IZ22yk1sZOAoBU4ydn2Tg%2BGCOleYhBN%2B%2F8JtrdssHYyCErcjg6GFD%2Fkpy3eRhtqLsu6R1VStxSN5Pc%3D&oldpass=&mpass=&login=1&isAjax=1&_=1546021576391 HTTP/1.1" 200 107 "https://pass-cmsd.ena.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

This is my admin account:

sysPass-ssl-access.log-20181230:172.27.0.212 - - [28/Dec/2018:12:33:42 -0600] "GET /ajax/ajax_doLogin.php?user=**admin**&pass=**CLEARTEXTPASSWORD**&oldpass=&mpass=&login=1&isAjax=1&_=1546022020225 HTTP/1.1" 200 107 "https://pass-cmsd.ena.net/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

**Comment by nuxsmin** [comment]
Please, be aware that requests are logged before the PHP code is executed, so  decryption takes place after. RSA encryption is done regardless the user, since every password field is bound to an encryption event, so this behavior might be caused by an unexpected error when encrypting the admin's password.

Regards

**Comment by nuxsmin** [comment]
Sorry, I sightly disagree with you, since it isn't related to the application itself. There are a bunch of REST applications which rely on GET method (the right way indeed) in order to retrieve data from webservices and those query strings (within URL) are being logged by the underlying webserver. These strings might contain auth tokens, users. passwords, etc. and it is the standard (and right) way for accessing to web resources.

I'd rather try to add more security to webserver logs instead of using fancy methods like POST (which aren't logged by default) for querying data from resources (https://www.restapitutorial.com/lessons/httpmethods.html or https://spring.io/understanding/REST).

sysPass implements RSA encryption in order to not send sensitive data through plain channels but not for "hide" these data in the webserver logs. It's up to the administrator to decide how and where to store this kind of data.

I'm really concerned about security, but there are some scopes that couldn't be managed by the application itself. I'm willing to open this thread but only for RFC or discussion about what other contributors have to tell about it.

Regards

**Comment by dajones70** [comment]
I am not suggesting that you change all GETs to POSTs, just the login one that has this password in the clear in the web server logs.  Obviously there is something odd going wrong in the code since the admin password is in the clear of the GET but other accounts are encoded.

**Comment by nuxsmin** [comment]
Every password field should be encrypted using RSA on client side by JavaScript code, so this issue is an unwanted behaviour.

Is there any error in browser's console (F12)?

Regards

**Comment by dajones70** [comment]
This is all the Chrome (F12) console shows:

JQMIGRATE: Migrate is installed with logging active, version 3.0.0

**Comment by dajones70** [comment]
Ok.  Debug enabled in sysPass config.xml and more stuff shows up.  It doesn't look very helpful so I am sure you are wanting me to do something else.  I am not a web developer but I will help in anyway I can.  We could do a Zoom session to share my screen if you need to see that.

This is sitting at the login screen of sysPass 2.1:
JQMIGRATE: Migrate is installed with logging active, version 3.0.0
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 ajax:complete
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 bindPassEncrypt
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 initializeClipboard
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 setupCallbacks
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 views:login
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 views:footer
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 bodyHooks
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 checkLogout
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 initPlugins

This is after logged in:
JQMIGRATE: Migrate is installed with logging active, version 3.0.0
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 ajax:complete
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 bindPassEncrypt
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 main:getUpdates
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 getActionCall
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 initializeClipboard
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 setupCallbacks
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 views:main
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 getActionCall
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 views:footer
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 bodyHooks
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 checkLogout
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 initPlugins
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 ajax:complete
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 history:add
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 sk:set
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 views:common
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 setupDatePicker
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 updateFormHash
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 views:search
js.php?g=1&v=568ecfef51c92a7386dcf7d31d8e3ab5:81 ajax:complete

**Comment by dajones70** [comment]
https://www.tutorialspoint.com/listtutorial/Difference-between-GET-and-POST-method-in-HTTP/3916

**Comment by nuxsmin** [comment]
As I said before, I sightly disagree on this discussion, since POST would make a false security sense, because it could be logged too. https://stackoverflow.com/questions/989967/best-way-to-log-post-data-in-apache

It's really a minor code change (only on JavaScript side), because the server side will process any method, but we are discussing about security, GET vs POST, and the key point is that neither of them are more secure.

The key point about GET request is related to its max length, that might cause unwanted behavior when it's reached.

**Comment by dajones70** [comment]
What can I do now to help figure out why the admin password is not getting encrypted by the client before it does the GET?

**Comment by nuxsmin** [comment]
bindPassEncrypt is the function that initializes the forms password encryption, so it has been successfully triggered.

Does the password field get encrypted after losing the focus?

**Comment by nuxsmin** [comment]
Does it happen on demo site?. You can  create a new user and use a similar password (using same special characters and not the others)

**Comment by dajones70** [comment]
Ok.  I just created a djones account on the demo site so check your web server logs to see if it's in the clear and not a very long encoded string.

**Comment by nuxsmin** [comment]
Fine. it has been stored encrypted:

```
76.*.*.151 - - [07/Jan/2019:19:50:44 +0100] "GET /index.php?r=login/login&user=djones&pass=JOw3VIcHt%2BMpfSNfUmx0mRq872YmcpKXUaOYZmX9zwlS71avWeRa5X0uC4VKB5pX%2FTZrU4EdHQR2RKhNaTQghdU2iZKVZhdDLdOwW54OmZd7X2DreKHKjhkTOvpW73u71B63mxnWrOGmMI%2BjZqC7%2F5DisxntMDMw0rGih7zBzp4%3D&oldpass=&mpass=&login=1&isAjax=1&sk=efbc5c47fb7097faa7e753e5cfdffd9a1af54139&_=1546887039201 HTTP/2" 200 145 "https://demo.syspass.org/index.php?r=login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
76.*.*.151 - - [07/Jan/2019:19:50:50 +0100] "GET /index.php?r=login/login&user=&pass=&oldpass=&mpass=nFI6OWE%2FJF6j6UgRru3IuZMvYe3SUnlTTkldBvxRlsX2PeErYHl5opaW6WD5IqZhpfs2%2B%2BznmFrOoV7frtcPHo7XGAHfqbWe61Xw%2Fq%2FmF%2Fms0zZ8wkPMbkVo464CR4QY4lfVtfgEW9cKy0kmcOd2dvBlrsekC1iFvwd9NG9kF%2FA%3D&login=1&isAjax=1&sk=efbc5c47fb7097faa7e753e5cfdffd9a1af54139&_=1546887039202 HTTP/2" 200 113 "https://demo.syspass.org/index.php?r=login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
76.*.*.151 - - [07/Jan/2019:19:51:00 +0100] "GET /index.php?r=login/login&user=djones&pass=WzfO%2FhNucZ9SRYiqDx2ez9AbAnCaXzp07F%2BHPhrWA9fQmUQxIRGKRVOAbV6Wf60IM8tqlvSuopi5JHmSJujDl06wTvZPtdNLwUCYBPs%2BSufZHtHphR1ra1hkcmKpKWmIGvbAINwhP7O%2FtXEZRhSW2i%2BfFEVXz3yf8rlM292dsuw
```

**Comment by nuxsmin** [comment]
Be aware that demo site is running sysPass v3

**Comment by dajones70** [comment]
Is 3 considered stable enough to use in production?

**Comment by SuperSludge** [comment]
https://owasp-aasvs.readthedocs.io/en/latest/requirement-9.3.html
