### ISSUE TITLE
New: Link for Nagios

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#108]
Can you create another link association (like wiki), for Nagios Monitoring ?

**Comment by allywilson** [comment]
I like this idea, but even if it could be made a bit more generic?

So I have the Wiki Page URL pointing to our Racktables installation like this:

https://racktables.mycompany.net/index.php?page=search&last_page=ui&last_tab=default&q=

Which is actually the search page, but if there's only 1 match it takes you to the object in Racktables. All of my objects have unique names so it works for me (the "Account" name in sysPass is the same as the devices name in Racktables, and the Account Name prefix is specific to device type for me as well, so it easily excludes "Accounts" that aren't in Racktables).
