### ISSUE TITLE
v3 Tags filter and search

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1081]
A great feature would be to search by text and tag.
Example : url.com in text search and in tag drop down Prod selected

Will result : 
- www.url.com / Prod
- cloud.url.com / Prod
- backoffice.url.com / Prod

If we check Prod and Dev in list, it'll result : 
- same as previous
- dev.url.com / Dev
- devback.url.com / Dev
...

An other great feature would be to clic on tag to populate filter by clicked tag.
What do you think about it?

**Comment by pierrehenrymuller** [comment]
Oups I don't see the shadow option with the +

But I have found a bug. When I clic on url address and after enter I can make search, but after one search I cannot make an other search, filters are not applied.
I'll check if I can find a better way to reproduce the bug.

**Comment by nuxsmin** [comment]
Hello,

I don't understand when you told:

> But I have found a bug. When I clic on url address and after enter I can make search, but after one search I cannot make an other search, filters are not applied.

Which "url address" did you click on?. Did you mean entering an URL in the search box and then press enter?

Regards

**Comment by pierrehenrymuller** [comment]
Hello,
Sorry for late reply on this. I just tested with the latest version today and everything is solved for the search filters.
Thanks

**Comment by nuxsmin** [comment]
No worries , just cleaning up some old issues ;)

Thanks for the feedback!
