### ISSUE TITLE
syspass3.0 rpm's

### ISSUE THREAD

**Issue by M1k13** [nuxsmin/sysPass#1082]
Hey Ruben,

Is there a way that I can install syspass 3.0 without using ius or Remi packages? So I only would like to use packages from ‘base’ ‘epel’ and ‘scl’

Kind regards,

**Comment by nuxsmin** [comment]
Hey @M1k13 sysPass v3 does not rely on special requirements, only PHP >= 7.0 and composer (which is a PHP tool that can be downloaded from its website). Which packages does need to be got from "non-official" repositories?

Kind regards.

**Comment by M1k13** [comment]
Good morning Ruben,

All the repositories from the composer I look to replace. Yeah it works perfect and looks great with the repositories from composer but I was just wandering if it was possible to make surpass 3.0 work with only the epel,scl and base repositories.

    "defuse/php-encryption": "^2.1",
    "phpmailer/phpmailer": "^6.0",
    "ademarre/binary-to-text-php": "dev-master",
    "phpseclib/phpseclib": "^2.0",
    "klein/klein": "~2.1",
    "php-di/php-di": "^6.0",
    "doctrine/common": "~v2.7",
    "guzzlehttp/guzzle": "~6.3",
    "monolog/monolog": "^1.23",
    "ext-pdo": "*"
     "require-dev": {
    "phpunit/phpunit": "^6",
    "phpunit/dbunit": "^3",
    "symfony/debug" : "~v3.4",
    "fzaninotto/faker": "~v1.8",
    "fabpot/goutte": "~v3.2"



Kind regards,

**Comment by M1k13** [comment]
Thnx for the great product, I resolved my problems and it works like charm

**Comment by nuxsmin** [comment]
@M1k13 hey, I didn't understand what you pointed. Epel and others are repositories for the operating system, which aren't related to PHP composer. Am I missing anything?

I'm glad to know that sysPass is useful for you!

Regards
