### ISSUE TITLE
Automated XML Export

### ISSUE THREAD

**Issue by Lacour20** [nuxsmin/sysPass#1083]
Hello,

is it possible to configure a auto xml export? With the API i can backup syspass sql and directorys but i didnt find a way to automate the creation of the xml-file.

Im using Syspass2 in a docker environment. 

Best Regards

Jan

**Comment by nuxsmin** [comment]
Hello, I could be implemented in v3, since v2 is frozen and only bug fixes will be applied. It would be an useful feature.

Thanks for the feedback!

**Comment by Lacour20** [comment]
Thanks for the fast reaction!  I will take a look on syspass 3.

By the way - you´re doing a great job with syspass!

Regards

**Comment by nuxsmin** [comment]
Hello I didn't notice that this feature was already implemented in v3....

**Comment by Leopere** [comment]
Could this feature be documented at all?
