### ISSUE TITLE
Problemas instalando  sysPass 2.1.16

### ISSUE THREAD

**Issue by marcsubiratsjimenez** [nuxsmin/sysPass#1084]
Hola,
He instalado la version sysPass 2.1.16 en un RHEL 7.1 (siguiendo tu explicacion en Centos). He seguido todos los pasos pero no consigo que funcione. Veo que dentro del el folder conf no hay ningun fichero ( entiendo que tendría que haber un fichero config.xml?). 

Al acabar toda la instalación y navegando a la URL, veo esto:

![syspass1](https://user-images.githubusercontent.com/44405634/47369698-8a8a3100-d6e4-11e8-807c-1bc989770e56.png)

Saludos

**Comment by nuxsmin** [comment]
Hola, parece que falta la activación de PHP en el servidor web, ya que los archivos .php los debería de ejecutar y no mostrarlos.

Saludos!

**Comment by marcsubiratsjimenez** [comment]
Hola,

Ya lo tengo solucionado, descargue los modulos de php de la version 5,4...
al descargar los de la 5,6 como dice en la doc. todo funciona.

Tengo un par de preguntas mas.

Actualmente tenemos syspass  2.0 en un server y lo tenemos que mover a
otro. Para eso he instalado la version 2.1(la actual, no beta) en este
nuevo server. Ahora tengo que mover toda la metadata d euna al otro. El
nuevo lo he configurado con la misma mastre key y toda la configuración es
la misma.
¿para mover todos los usuarios, grupos, etc... que tengo que hacer? un
backup de la metadata en el servidor antiguo y restaurarla en el nuevo?
esto lo he intentado pero parece que no funciona.

La segunda pregunta es, me gustaria que los users que acceden a syspass se
autentifiquen contra un LDAP que disponemos (en un windows server), se
puede hacer de alguna manera?

Saludos y gracias

**Comment by nuxsmin** [comment]
Hola, no es necesario instalar de nuevo, podrías hacer una copia de la base de datos actual, importarla en el nuevo servidor y copiar los archivos del directorio `config` en la ubicación sysPass 2.1. Tras ello se iniciará el asistente de actualización.

Saludos!

**Comment by marcsubiratsjimenez** [comment]
Hola Ruben,

Acbado de hacer lo que me has dicho y tengo este error al intentar acceder
a la URL:

[image: image.png]

**Comment by nuxsmin** [comment]
@marcsubiratsjimenez perfecto, me alegro que funcione bien.

Con respecto al LDAP, si, es posible conectarlo y utilizar tanto los usuarios de LDAP como los propios de sysPass. Los usuarios de LDAP se crean automáticamente al acceder por primera vez y también es posible importarlos.

Saludos!

**Comment by marcsubiratsjimenez** [comment]
Hola Rubén,
Gracias por toda tu ayuda.

Tengo el LDAP configurado pero tengo algun problemilla. Cuando intento
filtrar por grupo no me funciona:
[image: image.png]
Y si miras mi LDAP esta todo bien en teoría:
[image: image.png]

Si no pongo ningun grupo, me debuelbe los usuarios que estan directamente
en ese OU pero ninguno de los que hay en los grupos:
[image: image.png]

Que debo hacer para filtrar un grupo concretamente?

Saludos

**Comment by nuxsmin** [comment]
Hola, no consigo ver las imágenes...

Prueba a poner sólo el nombre del grupo y tener en cuenta que solo podrá localizar los usuarios que están en la base de búsqueda. Por otro lado los usuarios de los grupos no los usa para el acceso, sólo para verificar que pertenecen a dicho grupo.

Saludos!

**Comment by marcsubiratsjimenez** [comment]
No consigo que me funcione el filtrado por grupos, me devuelve este error:

Error while searching objects in base DN
Please check out the event log for more details

**Comment by nuxsmin** [comment]
Hola, puede ser que haya 2 grupos con el mismo nombre?

**Comment by nuxsmin** [comment]
Hola Marc(?), puedes revisar el log de sysPass en `syspass3/app/config.syspass.log`. Puede ser que alguna extensión de PHP no esté instalada.

Saludos!

**Comment by nuxsmin** [comment]
Con respecto a:

> No consigo que me funcione el filtrado por grupos, me devuelve este error:

Hay algún mensaje en el registro de eventos de sysPass?

**Comment by marcsubiratsjimenez** [comment]
Hola Rubén,

He hecho dos test y te paso los errores de el eventlog:

[image: image.png]

**Comment by marcsubiratsjimenez** [comment]
Hola Rubén,

He buscado este log y no lo tengo.

Estos es todo los modulos de php instalados (version 7):

[image: image.png]

Creo que tengo todos los necesarios.

Saludos

**Comment by marcsubiratsjimenez** [comment]
Hola Ruben,

Hace poco migre de servidor mi syspass y lo upgradee de version 2.0 a 2.1.

Ahora nos damos cuenta que algunos passwordshan desaparecido, es decir la
account existe, pero el password esta en null en la applicacion (no hay
ningun password..): Sabes a que puede ser devido? en el momento de upgrade
no tube ningun error.


Saludos
