### ISSUE TITLE
no se pueden borrar grupos / cant delete user groups

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#109]
Error: "CONSULTA INVÁLIDA"

**Comment by nuxsmin** [comment]
Hola, realmente no es un "bug", el problema viene que cuando se cargan los elementos de la lista de grupos, se genera un token de seguridad, que se vuelve a generar cuando se abre una ventana de nuevo o edición de grupo, pero no se guardan los cambios, por lo que el 2º token generado es el válido, pero como la lista no se ha actualizado, el botón de borrar tiene el código del 1er token, lo que no coincide cuando se hace la petición de eliminar.

Es un poco lioso, pero prueba a abrir de nuevo la lista de grupos y dale directamente a eliminar sobre el grupo que quieras y debería de eliminarse.
