### ISSUE TITLE
sysPass demo missing credentials at login page

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1094]
Hi,

i got a really simple "bug report" for the frontend of the v3 demo:
![grafik](https://user-images.githubusercontent.com/5631071/48093024-7ed35a00-e20e-11e8-945a-026cdc43c2cc.png)

As you can see in v2 frontend demo mode the demo/syspass/1234566900 is shown. this is missing in v3. All dudes who know v2 demo are going to type same credentials into v3 this but new testers maybe not. It's also missing in the description. So maybe some small hint would maybe be helpful for new people. Thats all :-)

![grafik](https://user-images.githubusercontent.com/5631071/48093056-94488400-e20e-11e8-82e9-089d0a54b73b.png)

![grafik](https://user-images.githubusercontent.com/5631071/48093063-9a3e6500-e20e-11e8-9227-1e915be64b7e.png)

regards, Mario

**Comment by nuxsmin** [comment]
Hey!, happy to hear from you and thank you for the notice. I did not realize about this behavior :disappointed:
