### ISSUE TITLE
LDAP connection issue

### ISSUE THREAD

**Issue by berzns** [nuxsmin/sysPass#110]
First of all thank you for the nice tool! I would like to implement it in our environment but I'm unable to logon using AD account and this is a must.

This is the error I get in the log file:
Session start (LDAP)  -  ::1  The user has not associated groups
User: janis 

I'm running sysPass 1.1 on Windows server 2012 R2 with XAMPP 5.6.8 32 bit version.

So I have created a security group in AD with few member accounts:

Security Group: "SysPass"
User account: "Syspass_admin", "janis"
The user accounts and group are located in "Users" OU in AD.

My config:
config.php file:
 'installed' => 1,
  'ldap_ads' => true,
  'ldap_base' => 'CN=Users,DC=JB,DC=local',
  'ldap_bindpass' => 'password',
  'ldap_binduser' => 'syspass_admin',
  'ldap_defaultgroup' => 2,
  'ldap_defaultprofile' => 3,
  'ldap_enabled' => true,
  'ldap_group' => 'CN=SysPass,CN=Users',
  'ldap_server' => '192.168.1.10',
  'ldap_userattr' => '',
  'log_enabled' => true,

Screenshot with LDAP config attached:
![image](https://cloud.githubusercontent.com/assets/12861965/8132879/aa905f10-111c-11e5-9b24-281fcb4f2146.png)

Log:
![image](https://cloud.githubusercontent.com/assets/12861965/8132952/2379206a-111d-11e5-947e-df6526f2977f.png)

When running the LDAP check it reruns green and notifys that has found user accounts. 

After the connection to AD has been established and I log off with the admin account I created when setting up syspass I'm unable to login using AD or the admin account. To get back in I have to cut off access to AD.

Any help is much appreciated!

**Comment by nuxsmin** [comment]
Hi, I'm glad that you like and found it useful :)

About LDAP connection errors, it seems that the user "janis" is not a member of "SysPass" group, does it?.

You need to take into account that when LDAP auth is active, if the login fails, it will fallback to the MySQL backend with the same user and the last saved password for that user and is advisable that you don't use the same admin user for LDAP login, instead you can use another ldap user and give it admin privileges.

**Comment by berzns** [comment]
Hey!
The user "janis" is member of "syspass" group in AD. 
I understand the concept of falling back to MySQL when AD is not reachable. That is the only way I can get back in.

Is there anything else I would need to do on syspass side when LDAP is enabled? 
Does my configure look ok?

**Comment by nuxsmin** [comment]
Hi!

Your config looks ok, and the connection to ADS is right.

The only that I can tell you is that I have it working on a Windows 2012 ADS environment, but the app is running on a linux OS, and there is no issue on LDAP auth.

Please consider this: https://github.com/nuxsmin/sysPass/issues/103#issuecomment-96418673

**Comment by JvdW** [comment]
Try using just SysPass as a group instead of the cn= stuff. I have that in my config and it works. I'm using ldap_ads=true against a Samba4 AD controller.

**Comment by nuxsmin** [comment]
Hi, did it work?

**Comment by allywilson** [comment]
I had issues with LDAP and AD as well (2003-native level forest, but all domain controllers currently 2008 R2 minimum). My working config is as follows:

```
'ldap_ads' => true,
'ldap_base' => 'OU=MyOU,DC=domain1,DC=mycompany,DC=net',
'ldap_bindpass' => 'P@ssw0rd',
'ldap_binduser' => 'CN=syspass,OU=Service_accounts,DC=domain1,DC=mycompany,DC=net',
'ldap_defaultgroup' => 2,
'ldap_defaultprofile' => 2,
'ldap_enabled' => true,
'ldap_group' => 'SysPass_Users',
'ldap_server' => 'ldap://my2k8DC.domain1.mycompany.net',
'ldap_userattr' => '',`
```

So AD users who are allowed to login are members of a global security group (could not get nested group in a domain local group to work) named "SysPass_Users" and all of the users who I want to access the tool are located in an OU called "MyOU"

Hope that helps.

**Comment by nuxsmin** [comment]
Hi, take care about group location, because it should be at the same base as users objects. SysPass uses the same search base for users and groups because a performance behavior.

Also, you can try to leave group in blank, so no restrictions on groups are done when authenticating ldap users.

Let me know if it works.

**Comment by allywilson** [comment]
Ah, I didn't test that, but my ldap_group is also under the same OU as the users who will access it, thanks for the info.

I specified both as I have users in that OU location who I do not want to be able to access the tool.

I also seen this: https://github.com/nuxsmin/sysPass/issues/94 which I guess answers my problem regarding nested groups. 

Thanks for all the hard work, much appreciated.
