### ISSUE TITLE
Enabling the user option "Show filters" fails with "Wrong Code" / user settings fail

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1103]
**sysPass Version**
3.0-rc1

Hi. Enabling the option "Show Filters" and saving it throws visual error, which is not listed in syspass.log
![grafik](https://user-images.githubusercontent.com/5631071/48448868-aa22ef80-e7a0-11e8-91e4-0cac73bd4198.png)

If i change some other setting, the error message gets displayed in spanish
![grafik](https://user-images.githubusercontent.com/5631071/48449036-36351700-e7a1-11e8-9f0d-d5f5dda042de.png)
 *edit 00:14*: found out that now this is hidden due to track delay
in total i cannot save the settings. :-( 

For info: i updated my installation to commit id e37bc14901da2abffe88eb99191061fb48bc4e87, cleared syspass action cache and browser cache, restarted my apache, ran the upgrade procedure from frontend, logged in.

Any idea?

regards, Mario

**Comment by nuxsmin** [comment]
Hello Mario, It seems to be related to the authenticator plugin, since these messages come from the security form.

I'll take a look to the plugin's code.

Regards

**Comment by vmario89** [comment]
Hey. I enabled the Plugin but i did not enable it in user preferences. just for your information

**Comment by nuxsmin** [comment]
Hey

> i did not enable it in user preferences

Once enabled it will display a new tab called "Security" on user preferences view.

**Comment by nuxsmin** [comment]
Hey, this issue has been fixed in latest commit.

Regards
