### ISSUE TITLE
Master Password

### ISSUE THREAD

**Issue by FrancescoOriglia** [nuxsmin/sysPass#1106]
sysPass Version : 

2.1.16.18061901)

Hello,

I have a question, I give temporary master password to my colleagues, but sometimes when they reconnect to syspass, they need another one.

The time set for the temporary master password is only for the first connexion right ? ( If the person enter the temporary master password in time, then the account will be activated forever)

Or after this time the person would not me able to connect anymore ? 

I hope you understand, that's hard to explain.

Sincerely,
Francesco Origlia

**Comment by FrancescoOriglia** [comment]
Thank you for the information.

So it might be a bug cause, some of my colleague, sometimes when they reconnect to syspass, they need an other master password. We didn't change the master password and they can't change their own password cause we use LDAP.

Please tell me if you have an idea how to fix that.

Sincerely,
Francesco Origlia

**Comment by nuxsmin** [comment]
You're welcome. It could be caused by using upper or lower case login, since LDAP doesn't complain about it but sysPass uses this data to build an encryption key, so upper or lower case matters.

Regards

**Comment by FrancescoOriglia** [comment]
Thanks you for the fast answers, I'll check everyday if the problem happen again. If there is something new, I'll send you an other issue ticket.

Sincerely,
Francesco Origlia

**Comment by nuxsmin** [comment]
Fine, thanks for the feedback!
