### ISSUE TITLE
Error when i create database on index.php

### ISSUE THREAD

**Issue by Eztharia** [nuxsmin/sysPass#111]
I see this error message when i try to create any database.

La BBDD ya existe
Indique una nueva Base de Datos o elimine la existente

if i change the name of database the website load an empty page and if i reload it i'm again in the index.php.

what is the solution ?

Thanks for help me and sorry for my bad english :)

**Comment by nuxsmin** [comment]
Don't worry about english...hablo castellano ;)

Es raro que no cargue la página principal, si puedes revisar el log del servidor web, puede que haya algún mensaje. De todas formas, en qué entorno lo estás instalando?

Saludos

**Comment by Eztharia** [comment]
Hi thx for your answer !

SysPass it's installed  on linux debian and i have this in the logs


[Tue Jun 23 07:35:29.088761 2015] [:error] [pid 10] [client 172.17.42.1:37732] Action: wrLogInfo -- Description: ();;SQL: , referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088765 2015] [:error] [pid 10] [client 172.17.42.1:37732] PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 265, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088770 2015] [:error] [pid 10] [client 172.17.42.1:37732] PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 265, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088773 2015] [:error] [pid 10] [client 172.17.42.1:37732] PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 265, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088777 2015] [:error] [pid 10] [client 172.17.42.1:37732] PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 265, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088787 2015] [:error] [pid 10] [client 172.17.42.1:37732] PHP Warning:  mysqli::query(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 210, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088790 2015] [:error] [pid 10] [client 172.17.42.1:37732] PHP Warning:  DB::doQuery(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 216, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088793 2015] [:error] [pid 10] [client 172.17.42.1:37732] PHP Warning:  DB::doQuery(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 217, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088796 2015] [:error] [pid 10] [client 172.17.42.1:37732] PHP Warning:  DB::doQuery(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 220, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088800 2015] [:error] [pid 10] [client 172.17.42.1:37732] PHP Warning:  DB::doQuery(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 220, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088804 2015] [:error] [pid 10] [client 172.17.42.1:37732] PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 265, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.088811 2015] [:error] [pid 10] [client 172.17.42.1:37732] Action: wrLogInfo -- Description: ();;SQL: , referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 07:35:29.230225 2015] [core:notice] [pid 7] AH00052: child pid 10 exit signal Segmentation fault (11)

**Comment by nuxsmin** [comment]
Upss, sorry, I thought that you could speak Spanish....

It seems that database access is wrong due to an incorrect user/pass. Did you take a look to http://wiki.syspass.org/en/install ?

Please take care that the first two fields at the install page are for syspass admin user and the database ones are for the database admin user/pass to create the syspass database structure, but it should be a privileged user. This user is only needed for the installation process, so it won't be needed anymore.

If you still are in trouble, you can try to enable hosting mode install http://wiki.syspass.org/en/hostingmode

**Comment by Eztharia** [comment]
My user / pass i'ts ok ! I find my error ! 

i look u'r old post https://github.com/nuxsmin/sysPass/issues/44

Now i'ts done but after log i have this error 

[Tue Jun 23 08:26:42.356206 2015] [core:error] [pid 16] (13)Permission denied: [client 172.17.42.1:34893] AH00035: access to /sysPass/js/js.php denied (filesystem path '/var/www/html/sysPass/js/js.php') because search permissions are missing on a component of the path, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 08:26:42.357065 2015] [:error] [pid 11] [client 172.17.42.1:34889] PHP Warning:  md5_file(/var/www/html/sysPass/js/fancybox/jquery.fancybox.css): failed to open stream: Permission denied in /var/www/html/sysPass/inc/util.class.php on line 612, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 08:26:55.409306 2015] [core:error] [pid 12] (13)Permission denied: [client 172.17.42.1:34917] AH00035: access to /sysPass/js/js.php denied (filesystem path '/var/www/html/sysPass/js/js.php') because search permissions are missing on a component of the path, referer: http://localhost:81/sysPass/

And i try to give chmod / chown on the js.php and fancybox.css but no change

**Comment by Eztharia** [comment]
My user/ pass is ok ! But i refer to an old post https://github.com/nuxsmin/sysPass/issues/44 who help me !

My problem now i'ts to change the language i see this in apache2 logs 

[Tue Jun 23 08:39:45.260328 2015] [:error] [pid 31] [client 172.17.42.1:35100] PHP Fatal error:  Cannot use object of type stdClass as array in /var/www/html/sysPass/inc/util.class.php on line 234, referer: http://localhost:81/sysPass/index.php
[Tue Jun 23 08:39:49.063750 2015] [:error] [pid 11] [client 172.17.42.1:35112] PHP Fatal error:  Cannot use object of type stdClass as array in /var/www/html/sysPass/inc/util.class.php on line 234, referer: http://localhost:81/sysPass/index.php

**Comment by nuxsmin** [comment]
Great!!.

About permissions, take a llok at https://wiki.apache.org/httpd/13PermissionDenied it seems that directories permissions are wrong.

You can try to issue the following commands:
```
find /var/www/sysPass -type d | xargs chmod 755
find /var/www/sysPass -type f | xargs chmod 644
chown www-data -R /var/www/sysPass
chmod 750 /var/www/sysPass/config
```

**Comment by nuxsmin** [comment]
Translations are done by gettext GNU utilities, so you need to configure system locales by issuing the command <code>dpkg-reconfigure locales</code> and selecting en_US-UTF8 or any supported language like fr_FR-UTF8, de_DE-UTF8, it_IT-UTF8, ru_RU-UTF8 or hu_HU-UTF8

**Comment by Eztharia** [comment]
Haha very good job ! i'ts ok !

**Comment by nuxsmin** [comment]
Great!!!...I hope you find it useful ;)

**Comment by Eztharia** [comment]
I run SysPass with https://www.docker.com/ in linux/debian image, i will give you the complete settings when i finish all configuration.  :)

**Comment by nuxsmin** [comment]
It sounds great...waiting for feedback about that ;)

I want to include the next release in Debian repositories, so it would be easier to install sysPass on debian like systems

**Comment by Eztharia** [comment]
Hello i'm back, the app work correctly but i have an problem with keepass import i see this error !

Field 'account_userEditId' doesn't have a default value(1364)
SQL: 
INSERT INTO accounts SET account_customerId = 1,account_categoryId = 1,account_name = \'NAME\',account_login =
\'admin\',account_url = \'http://my_ip\',account_pass = \'�����t�B�>J�2H���X�(�Ѧ:ۯM�J\',account_IV =
\'/�G.��QI^Y���%�.��h\\rY^����K�\',account_notes = \'Full GB\',account_dateAdd = NOW(),account_userId = 1,account_userGroupId =
1,account_otherUserEdit = 0,account_otherGroupEdit = 0

Syspass add keepass and the database in the list but i didn't  see any accounts

i see this on the main page  'No se encontraron registros' :/ .
