### ISSUE TITLE
Rights of User

### ISSUE THREAD

**Issue by andrucha97** [nuxsmin/sysPass#1110]
Hi :)

first: very cool tool for manage passwords.
My friend and I want to use this system in your companys and installing this as a project of our apprenticeship exampes.

**sysPass Version**
I´m using the 3.0 branch with Version 3.0-rc4 (300.18111902)
He is using the newest from master branch.

**question**
We want to use the permission function but we do have a Problem. Her an example:

*Users*
admin
boss
andreas

*group*
sysPass Admins
Boss
Systemintegrator

*profile*
Admin
Boss
Systemintegrator

*Account*
Bank
Server

*Access*
The Group sysPass Admins should be able to see all Accounts.
The Group Boss should see all entries without Information but is only able to see the password of Bank. He can write a Mail to the Admins.
The Group Systemintegrator should see all entries without Information but is able to see the password of Server.

I tested on 3.0 RC4:

- Add rights to See, Global Search
- Costumer test enabled Globals Search

I can see not see the password. If I enable password access all users of this group can see the password.

*What we need*
- Account Bank = User boss has access to see password and details
- Account Server = User andreas has access to see password and details
- If Boss needs access to Server he can send an request to users which do have the right to see the password of Server and have the right so answer this massage. Something like a superior.

Do you have an idea how to set up this scenario? Or is this at this moment a Bug?

**Comment by nuxsmin** [comment]
Hi, glad to know you found sysPass useful :)

Regarding your questions:

> Account Bank = User boss has access to see password and detail

You can configure a password view profile, so he will be able to see the passwords of accounts in which this user is granted.

> Account Server = User andreas has access to see password and details

Same as above but the profile should be configured to view account details.

> If Boss needs access to Server he can send an request to users which do have the right to see the password of Server and have the right so answer this massage. Something like a superior. 

It's implemented indeed, since users without permissions are able to send requests through the app.


Regards.

**Comment by andrucha97** [comment]
Hi nuxsmin,

oh I found the Problem :D I thought when I enable the right for Global Search it will be activated as default. But I do need to turn it on in the filter.

So what I now did works fine for me:

Group Boss is able to see Bank with Password and details but cannot change details.
Group Systemintegrator is able to see Bank if Global Search is on. He can send an Mail.

Group Systemintegrator is able to see Server with Password and details he also can change details.
Group Boss is able to see Server if Global Search is on. He can send an Mail.

Thats great.

What if I want to change something as User who can see the password and details? Is there a way to send an massage?
Is it possible to add a permission for Profiles witch adds automatic Global Search on?

Thanks for your quick response!

Regards.

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply..

> What if I want to change something as User who can see the password and details? Is there a way to send an massage?

Unfortunately there's no way to notify about change to other users.

>  Is it possible to add a permission for Profiles witch adds automatic Global Search on?

It could be implemented by user's preferences or preset values, but would be done in next releases.

Thanks for the feedback!

Regards
