### ISSUE TITLE
Translation bug when copying password

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1114]
Hi nuxmin,
in the current syspass 3 rc4 i still can see
![grafik](https://user-images.githubusercontent.com/5631071/48910740-048f1080-ee71-11e8-9968-dea233d42557.png)

i configured german language for global and for user. The translation is not used.

regards, Mario

**Comment by nuxsmin** [comment]
Hey, I've just updated all translations that were at 100% completed. Please check it out and let me know if it's displayed as expected.

Thanks for the feedback!

Regards

**Comment by vmario89** [comment]
Hey nux, just pulled to latest state and a mass of strings now works in my instance which did not work before. Really nice!

But i came up with another extra small translation bug lol. It seems to be located in PublicLinkListData.php

I checked the public links from https://github.com/nuxsmin/sysPass/issues/1124 and i also checked event notifications. There i figured out that "ON" is translated in the events notifications, but not in the public links list ;-D

![grafik](https://user-images.githubusercontent.com/5631071/48985055-0d4b4500-f104-11e8-9bef-2fc48025776f.png)

![grafik](https://user-images.githubusercontent.com/5631071/48985064-3075f480-f104-11e8-86a4-d5d6272f80af.png)

regards, Mario

**Comment by nuxsmin** [comment]
Fine, it looks nice now :)

The untranslated string is an issue indeed. It was left untranslated because it should be done in view layer, but I forgot to do it...

I'll fix it shortly. Thanks for the feedback!

Regards

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commit. Thanks for the feedback!

Regards
