### ISSUE TITLE
Changing account password results in exception

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1116]
**sysPass Version**
sysPass 3.0-rc4

**Describe the bug**
Hey. When trying to update an accounts password an exception occures. I did not find the root cause what it could be. It happens at different accounts - but only sometimes. At the moment it occures in ~70% of trials.
![grafik](https://user-images.githubusercontent.com/5631071/48924607-59a34480-eeba-11e8-92dd-e2e8f0bed6de.png)

It happens when clicking the yellow update button
![grafik](https://user-images.githubusercontent.com/5631071/48924587-1052f500-eeba-11e8-82c7-e4636dc26cdc.png)

i already tried to change with different users. makes no difference. What i tried: delete app cache, browser cache, restart web server, ... just some regular stuff

2018-11-23 00:49:18 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-23 00:49:18 [EXCEPTION] [N/A] Ungültige Aktion
#0 /var/www/vhosts/pw.yourdomain.de/app/modules/web/Controllers/AccountController.php(487): SP\Modules\Web\Controllers\ControllerBase->checkSecurityToken('ee84bf1118e31e2...', Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\AccountController->editPassAction(37)
#2 /var/www/vhosts/pw.yourdomain.de/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/vhosts/pw.yourdomain.de/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/vhosts/pw.yourdomain.de/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/vhosts/pw.yourdomain.de/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/vhosts/pw.yourdomain.de/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/vhosts/pw.yourdomain.de/index.php(28): require('/var/www/vhosts...')
#9 {main}
2018-11-23 00:49:18 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Ungültige Aktion
2018-11-23 00:49:18 [WARN] [SP\Mvc\View\Template::SP\Mvc\View\{closure}] Unable to retrieve "skipBackButton" variable

**Comment by nuxsmin** [comment]
Hello, it seems that the exception is caused by a wrong security token. Are you using multiple tabs to view/edit the accounts?.

Security token is refreshed on every request, so in some rare cases, it won't be updated before an Ajax request.

Regards

**Comment by vmario89** [comment]
Hi  @nuxsmin , i know this behaviour about multiple tabs. With syspass i never use multiple tabs :-D

**Comment by vmario89** [comment]
I seems to happen exactly every second time i click on that change password icon.

I recognized that i have to click that 
![grafik](https://user-images.githubusercontent.com/5631071/48950925-0b835500-ef3d-11e8-9045-289682689db1.png) button twice to get back to the previous view. and the previous view is wrong. i am not getting back to account detail view. instead i get back to account search overview. hmmm...

**Comment by nuxsmin** [comment]
Hello, does this issue still going on?

**Comment by nuxsmin** [comment]
3.1-RC1 has been released out, please check it out for solving this issue.
