### ISSUE TITLE
Yet another LDAP group issue

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1120]
**sysPass Version**
Bleeding edge 3.0

**Describe the bug**
Upgraded from 2.1 latest to 3.0
Check LDAP parameters (working)

When trying to login, I get the following in event log:
```
User does not belong to the group
Utilisateur: CN=Some Body,OU=Utilisateurs spéciaux,OU=Utilisateurs,DC=contoso,DC=local
Groupe: cn=SYS GROUPE SysPass,OU=Groupes,DC=contoso,DC=local
LDAP FILTER: (&(|(samaccountname=CN=Some Body,OU=Utilisateurs
spéciaux,OU=Utilisateurs,DC=contoso,DC=local)(cn=CN=Some Body,OU=Utilisateurs
spéciaux,OU=Utilisateurs,DC=contoso,DC=local)(uid=CN=Some Body,OU=Utilisateurs
spéciaux,OU=Utilisateurs,DC=contoso,DC=local)(userPrincipalName=CN=Some Body,OU=Utilisateurs
spéciaux,OU=Utilisateurs,DC=contoso,DC=local))(|(memberOf=cn=SYS GROUPE
SysPass,OU=Groupes,DC=contoso,DC=local)(groupMembership=cn=SYS GROUPE
SysPass,OU=Groupes,DC=contoso,DC=local)(memberof:1.2.840.113556.1.4.1941:=cn=SYS GROUPE
SysPass,OU=Groupes,DC=contoso,DC=local)))
```

The following filter cannot work since we're testing a DN against sAMAccountName, cn, uid and userPrincipalName.
The test should be using the sysPass username instead of it's DN I think.

The filter itself works (even if it gives zero results) on my Win2012 R2 test setup.
Since we got the DN, a way easier filter would be to search the DN as base scope, and only keep the group filters:

```
User does not belong to the group
LDAP BASE SCOPE: CN=Some Body,OU=Utilisateurs spéciaux,OU=Utilisateurs,DC=contoso,DC=local
LDAP FILTER: (|(memberOf=cn=SYS GROUPE
SysPass,OU=Groupes,DC=contoso,DC=local)(groupMembership=cn=SYS GROUPE
SysPass,OU=Groupes,DC=contoso,DC=local)(memberof:1.2.840.113556.1.4.1941:=cn=SYS GROUPE
SysPass,OU=Groupes,DC=contoso,DC=local))
```

Best regards.

**Comment by nuxsmin** [comment]
Hello, this issue should be fixed in latest commits. User's DN is used in Standard LDAP but login is used in ADS implementations. Please check it out and let me know if it works as expected.

Thanks for the feedback!

Regards

**Comment by deajan** [comment]
I'll have new tests done shortly.
I have a dev2dev question:
Why do you keep that complicated LDAP ADS filter of searching a user in cn, uid, samaccountname and userPrincipalName when you could just search the DN as base scopee, and have the groupmembership as filter ? This would be way more performant.

**Comment by nuxsmin** [comment]
About such complicated method, I have been figuring out how to refactor some pieces of code, but the current LDAP implementation gets the results for a given search filter in the core actions LDAP class, which takes the search base from configuration parameters, so passing a new base from an outer class will need to modify all the methods involved.

LDAP classes are mostly decoupled, so they are injected in constructor method to get the needed dependencies, this makes an interfaced development, which allows multiple implementations and testing aware, but sometimes it makes harder to anticipate any feature like this one (ie. changing the search base)

Regards

**Comment by deajan** [comment]
I actually wrote a small patch before posting about the filter.
Two methods are involved in my patch, getObjects and getResults, on which I added an optional searchbase which defines search behavior.

**Comment by nuxsmin** [comment]
@deajan could you share your patches?

> Anyway, tested with latest commits, current fix works too, even if slower :(

Yes it could be. Current way was implemented because I didn't notice about the right way, but it will be improved in next releases.

**Comment by deajan** [comment]
@nuxsmin Made a PR with the improved filter which works way quicker on large AD setups since it only has 4 operations instead of 9, using the user DN as base scope.
Should be retrocompatible with standard LDAP implementations since changing searchbase is an optional parameter.
