### ISSUE TITLE
Add hint for LDAP bind password / pre-propagate LDAP password field

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1122]
Hi,
the current syspass v3 rc4 has a glitch i don't like. I think there are some other person who had the same problem (https://github.com/nuxsmin/sysPass/issues/959). When adding new LDAP users from AD you always have to enter the bind password again. In the UI there is no hint for this. When forgetting it there's just the notice about invalid credentials. I opened this ticket becuase 959 was closed without satisfaction i think.

I dont see the sense of storing the LDAP password into config.xml unencrypted but ignoring it in the frontend property field. Why an admin should re-enter the password all the time? The application admins who use this function are already trusted to do all the sensible stuff. 

An easy fix would be fill-in the pasword field with the real value or to add some visual hint for the admin user that he needs to enter the bind password again for each page refresh (add some question mark icon with an info popup like for other things). Would help in most situations ;)

regards, Mario

**Comment by deajan** [comment]
Hell yes ! See https://github.com/nuxsmin/sysPass/issues/959#issuecomment-404319416 for the big red warning :)
You know what, I'm pushing a PR for this right now :)

**Comment by nuxsmin** [comment]
Fine, I think this feature is  not working as expected, since my first thought was about not allow to import users by anyone who has had access to config section, and it could prevent to perform an unwanted import.

What do you think about it? Maybe a security check when importing or saving LDAP configuration?

Regards.

**Comment by vmario89** [comment]
I think all Application Admins and Account Admins should have permission to import LDAP users in general. By the way is was wondering too why the LDAP user import is located in the config section. It would be great to have it in place here:
![grafik](https://user-images.githubusercontent.com/5631071/48978707-e400c980-f0af-11e8-8264-a4cffe1501d5.png)

**Comment by nuxsmin** [comment]
@vmario89 I agree, but unfortunately since LDAP import feature could take several parameters, it can't be performed from 'Users Management' tab. You may be wondering why not to display a popup instead, it could, but would need some major code tweaks...

**Comment by vmario89** [comment]
hmmm complex stuff with LDAP i know :-O would it maybe make sense to create different LDAP config presets which are saved in the config section? Maybe those presets then could be selected via drop down by an accounts admin who wants to import users from such a preset config (where he is not able to see the password - only a preset title).

**Comment by nuxsmin** [comment]
> hmmm complex stuff with LDAP i know :-O would it maybe make sense to create different LDAP config presets which are saved in the config section? Maybe those presets then could be selected via drop down by an accounts admin in the user config sections who wants to import users from such a preset config (where he is not able to see the password - only a preset title).

Fine, but we could discuss such feature in a separate FR, since the original one about LDAP password issue..

Regarding this issue, a warning notice has been added on LDAP section.

Regards
