### ISSUE TITLE
json config export empty/fails

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1126]
**sysPass Version**
v3 rc4

While checking some infos i found that new button for downloading config as json file. Unfortunately it does not work for me. The browser shows a blank page and an error is shown in protocol.

![grafik](https://user-images.githubusercontent.com/5631071/48985614-96b14600-f109-11e8-961d-f3bf7e6f71db.png)

![grafik](https://user-images.githubusercontent.com/5631071/48985615-987b0980-f109-11e8-9839-709217bdd2da.png)

the sypass.log gives no more details about it. gzip is installed on my system.

Because it is name "Configuration Backup" i think the naming is wrong - i think this comes from recycling ConfigBackupService.php for this functionality. I guess you want to express downloading the instance information as parsable json file, correct?

regards, Mario

**Comment by nuxsmin** [comment]
Hmm,  I can't figure out what could be the issue.

The naming is correct, since it's a configuration backup indeed. Every time you modify the configuration, the old values are saved Inc the database, so if your sysPass server filesystem gets wiped out, so could recover the configuration from the database. The JSON format is used because XML counterpart is too verbose and bigger in size.

Regards

**Comment by deajan** [comment]
Downloading the config via the `DOWNLOAD JSON` button works for me (using latest 3.0 branch from this morning).
@vmario89 What do your web server logs say ?

**Comment by vmario89** [comment]
Hi,
the output of apache log is:

[EXCEPTION] [N/A] Warning: gzuncompress(): data error\n#0 /var/www/vhosts/pw.yourdomain.de/app/modules/web/Controllers/ConfigGeneralController.php(250): SP\\Services\\Config\\ConfigBackupService->getBackup()\n#1 [internal function]: SP\\Modules\\Web\\Controllers\\ConfigGeneralController->downloadConfigBackupAction('json')\n#2 /var/www/vhosts/pw.yourdomain.de/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)\n#3 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#4 /var/www/vhosts/pw.yourdomain.de/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#5 /var/www/vhosts/pw.yourdomain.de/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#6 /var/www/vhosts/pw.yourdomain.de/lib/SP/Bootstrap.php(450): Klein\\Klein->dispatch(Object(Klein\\Request))\n#7 /var/www/vhosts/pw.yourdomain.de/lib/Base.php(74): SP\\Bootstrap::run(Object(DI\\Container))\n#8 /var/www/vhosts/pw.yourdomain.de/index.php(28): require('/var/www/vhosts...')\n#9 {main}, referer: https://leyghis.yourdomain.de:8446/index.php?r=index

its strange. On my Xubuntu/odroid it throws this error. The instance on Ubuntu 16 works - there i can download the file. The setup is i made the same i think.

**Comment by vmario89** [comment]
hey just some notice i wanted to add to the json download: why is it placed on the information tab? shouldnt it be put to backup? it's same kind of functionality except the surrounding files and its json instead of xml. you already named it "configuration backup" :)

![grafik](https://user-images.githubusercontent.com/5631071/49187416-b9409a80-f367-11e8-977b-95cc5d2120e8.png)

**Comment by nuxsmin** [comment]
@vmario89 Although it's a configuration backup (stored in the database), this backup is not about the current configuration but the last used before saving the current one instead, so I think that putting this "button" on its own section doesn't make sense and could be a bit confusing when clicking the "Do backup" button, since the JSON file won't change...
