### ISSUE TITLE
php requirements for latest 3.0 version

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1129]
Hi, running composer against latest 3.0 branch told me I was missing php-xdebug, which previously didn't miss.
Anything you added for this ? Asking because I'll have to update the install / upgrade doc for CentOS.

**Comment by nuxsmin** [comment]
Hi, php-xdebug is only needed when deploying the development version:

https://github.com/nuxsmin/sysPass/blob/034c4c01432b89fe0ad099651cd579440479f7c4/composer.json#L50

You should use `--no-dev` instead:

https://github.com/nuxsmin/docker-syspass/blob/33092b97dd2fbfcee612c55697afdd7a98406dad/sysPass/Dockerfile#L17

**Comment by deajan** [comment]
Indeed, tried to install the dev version in order to get the authenticator plugin. That explains a lot. Thanks.
