### ISSUE TITLE
Import CSV only seems to be viewable by group who importer beings too.

### ISSUE THREAD

**Issue by glenc2004** [nuxsmin/sysPass#113]
I imported about 200 new accounts and they are only viewable by the group who the person belongs to. So if I have an user that belongs to the admin group that imports, only those in the group admins can see the accounts. Any way to bulk change ALL imported accounts? I look at the DB but don't know which column is looked at for the group access.

Can anyone assist?

Thanks so much. Looks great so far.
glenc

**Comment by nuxsmin** [comment]
Hi, it's right, I know that there is no option for default user/group whe importing accounts from CSV, but if there were any, I think that 200 or more accounts wouldn't be associated to only one user/group so IMHO, it would be better to do it later for each one.

BTW, if you have any DB skills, you can get the target group id at usrGroups table and build an SQL sentence like this:

```UPDATE accounts SET account_userGroupId = TARGET_GROUP_ID WHERE account_userGroupId = SOURCE_GROUP_ID;```

**Comment by glenc2004** [comment]
Ok thanks. Well I unfortunately have 1000+ accounts that all belong to the same staff. As you said, just go in and change the owner, which I did. Just would be nice to be able to select it during import so you would not have to do this. Or even just have it an eighth field in the import.

Anyway, thanks.

**Comment by nuxsmin** [comment]
Ok, I think that this feature can be useful, let me some time to get it working for the release.
