### ISSUE TITLE
Copy/Paste with Shortcuts

### ISSUE THREAD

**Issue by andrucha97** [nuxsmin/sysPass#1131]
Hi,

I'm searching for a solution to copy/paste passwords with keyboard shortcuts or sync sysPass to Keepass.

Would be cool if it works on the website without an extra tool.
Something like: ctrl + c to copy password, ctrl + b to copy username or ctrl + u to open URL

**Comment by vmario89** [comment]
i made some comments for this in https://github.com/nuxsmin/sysPass/issues/57
