### ISSUE TITLE
sysPass v3 is coming

### ISSUE THREAD

**Issue by nuxsmin** [nuxsmin/sysPass#1137]
Hello, sysPass v3 is around the corner (currently in RC5), so I'd like to share with you the public demo site before the final release. This could generate some useful feedback that will improve the quality of this release.

**Please let me know any issue by filing a new issue on GitHub**. At this time no more features will be added before the final release.

* PHP 7.0: http://demo-beta.syspass.org:10080
* PHP 7.1: http://demo-beta.syspass.org:10081
* PHP 7.2: http://demo-beta.syspass.org:10082

If you want to install it by your own, please take a look on https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18112601-rc5

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hey!, Authenticator plugin should be ready for stable release and nobody told me about any issue...

>   I had tons of errors last time I tried it (a couple of days ago), trying to get SSO to work.

Please let me know about them :)

**Comment by deajan** [comment]
Okay, give me a couple of days so I can redo all my tests :)

**Comment by jinyiwoo** [comment]
Hi nuxsmin @nuxsmin 
   I have installed and tested for the V3.0 RC5.  So many improvement on this release, Thanks for your work.
    
But There is error when import user from LDAP:
   Below is the log:
   2018-11-29 03:45:32 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2018-11-29 03:45:32 [EXCEPTION] [N/A] Connection error (BIND)
#0 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\Providers\Auth\Ldap\LdapConnection->bind()
#1 /var/www/html/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#2 /var/www/html/lib/SP/Providers/Auth/Ldap/Ldap.php(96): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#3 /var/www/html/lib/SP/Services/Ldap/LdapCheckService.php(51): SP\Providers\Auth\Ldap\Ldap::factory(Object(SP\Providers\Auth\Ldap\LdapParams), Object(SP\Core\Events\EventDispatcher), true)
#4 /var/www/html/app/modules/web/Controllers/ConfigLdapController.php(152): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#5 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#6 /var/www/html/lib/SP/Bootstrap.php(228): call_user_func_array(Array, Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/lib/SP/Bootstrap.php(450): Klein\Klein->dispatch(Object(Klein\Request))
#11 /var/www/html/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#12 /var/www/html/index.php(28): require('/var/www/html/l...')
#13 {main}
2018-11-29 03:45:32 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] exception;Connection error (BIND)
![image](https://user-images.githubusercontent.com/45224195/49198247-26d2e200-f3cd-11e8-9628-02c106c7bd6b.png)

**Comment by nuxsmin** [comment]
@jinyiwoo unfortunately this thread is not about issues on RC5, please open a new issue about it.

Regards.

**Comment by jinyiwoo** [comment]
Hi 
  It is my mistaken. It was resolved. My OS： CentOS 7.5.1804 (Core), php72u-ldap.x86_64  

  **setsebool -P httpd_can_network_connect on**

Thanks

**Comment by nuxsmin** [comment]
@jinyiwoo great!, thanks for the feedback!

**Comment by nuxsmin** [comment]
@derStephan It does indeed and shouldn't have any issue ;)

**Comment by deajan** [comment]
@nuxsmin If I happen to remember well, you still have to move the config directory from root to app, don't you ?

**Comment by deajan** [comment]
> Hey!, Authenticator plugin should be ready for stable release and nobody told me about any issue...
> 
> > I had tons of errors last time I tried it (a couple of days ago), trying to get SSO to work.
> 
> Please let me know about them :)

Tried to reproduce the auth errors, could not.

**Comment by javierlm** [comment]
New RC versions are not showing all new events in the "Event Log" tab. I don't know if the cause is my installation, or a bug in the application. Visualization of accounts are not being tracked.

**Comment by MagicFab** [comment]
Filed Export not working in beta Demo v3 #1167.

**Comment by nuxsmin** [comment]
@MagicFab Unfortunately there would be some missing features because a lack of time, but they will be implemented as soon as possible.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Closing this thread because sysPass v3 has been released out.

Thanks so much for your useful feedback!
