### ISSUE TITLE
Virtualhost now needs special configuration

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1138]
**sysPass Version**
3.0-rc5

**Describe the bug**
In sysPass 2.x, I could create an apache virtualhost using
```DirectoryIndex index.php``` and access sysPass using an url like `https://syspass.local/`

Now, on sysPass 3.0, I must add 'index.php' to the url like `https://syspass.local/index.php`
@vmario89 has posted a rewrite rule in order for apache to automatically add index.php to all urls (see #1093), but I think this shouldn't be the way it is working.
Earlier beta versions of sysPass 3.0 (around august this year) didn't have that problem neither.
Is it possible to investigate that issue before final release ?

Thanks.

**Comment by nuxsmin** [comment]
Hello, I'll take a look to that behavior, but demo version uses the configuration bundled with docker images, which doesn't rely on rewrite.

Regards

**Comment by vmario89** [comment]
hi, i believe you. but i have same behaviour like @deajan describes. since some release it changed and stopped working, I dont know exact version but in my personal doc history i added the rewrite first on 21.08.2018 to make it work again.

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commit. Please, let me know if it works fine.

Regards

**Comment by deajan** [comment]
Works for me.

**Comment by nuxsmin** [comment]
@deajan Fine, thanks for the feedback!
