### ISSUE TITLE
Improve virtualhost documentation

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1139]
@vmario89 has posted a good secure version of apache virtualhost config for sysPass v3.0 in #1093 
Maybe this could be merged into the final doc

**Comment by nuxsmin** [comment]
Sure, I thought about the configuration used in sysPass docker images, which only allows requests to index.php , api.php and plublic files

**Comment by vmario89** [comment]
https://github.com/nuxsmin/docker-syspass/blob/3.0/sysPass-dev/000-default.conf
https://github.com/nuxsmin/docker-syspass/blob/3.0/sysPass-dev-php7.1/000-default.conf
https://github.com/nuxsmin/docker-syspass/blob/3.0/sysPass-dev-php7.2/000-default.conf

They are not exactly the same. I think you have forgotten some options in the php7.0  variant

**Comment by nuxsmin** [comment]
Right, I've rewritten the require sentence to make use of regex, so no need to explicitly allow non-root paths like `/sysPass` or whatever.

Anyway I'll merge these configurations.

Thanks

**Comment by nuxsmin** [comment]
Hello, I'm finishing the new documentation and I've improved the points discussed:

https://doc.syspass.org/en/3.0/application/security.html

Thanks for your contribution!!
