### ISSUE TITLE
Enhance notification handling

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1140]
Hi,

i am missing some button to "mark as read" for multiple notifications selection:
![grafik](https://user-images.githubusercontent.com/5631071/49186748-c066a900-f365-11e8-875f-e2bf262d832c.png)

Some action could be added here:
![grafik](https://user-images.githubusercontent.com/5631071/49186638-7f6e9480-f365-11e8-984e-b47a76771075.png)

regards, Mario

**Comment by nuxsmin** [comment]
Hi, it was the intended behavior, since it "forces" to the user to check out every notification...do you think it's the wrong behavior?

Regards
