### ISSUE TITLE
Enhance account search behaviour on mobile devices

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1141]
Hi,

in the current stated v3 rc5 sysPass on mobile has some bevahiour which could be improved. This will speed up the account search on smartphone a lot. Tried this with google chrome and firefox on android.

When you search an account by entering some title the results are shown when hitting enter key on a desktop computer
![grafik](https://user-images.githubusercontent.com/5631071/49186923-34a14c80-f366-11e8-9bc1-61d953696c3c.png)

in case of mobile device hitting the virtual "enter" key nothing happens. The search result list will only change if you select something from client or category selection box because it will trigger an update action.

I think the input field could be improved to trigger update by onFocus//offFocus so that it will update the result list in case of setting off the focus of the input field OR directly by incremental update if some character in the field changes (on-type search).

**Comment by nuxsmin** [comment]
Hello, I have noticed of this behavior a time ago, but I forgot to note it down...

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commit. Thanks for the feedback!
