### ISSUE TITLE
Browser Notifications Formatting issue

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1142]
**sysPass Version**
v3 rc5

Hi, it did not see this before because i had no in-app notifications the big mass yet. but now i have some. So my browser asked me to enable browser notifications. I said yes. I saw that the formatting is not working correctly. I made screenshots from FireFox and Chrome:

![grafik](https://user-images.githubusercontent.com/5631071/49187844-1721b200-f369-11e8-8fae-7f2a95d376d1.png)
![grafik](https://user-images.githubusercontent.com/5631071/49187857-23a60a80-f369-11e8-8b45-3161ccce88c1.png)

I have other applications where this is working fine, for example my Koel Music Server:
![grafik](https://user-images.githubusercontent.com/5631071/49187914-4afcd780-f369-11e8-8ed6-69ce7e109081.png)

I guess that this is some small encoding bug.

regards, Mario

**Comment by vmario89** [comment]
edit: i am not sure if this behaviour is wanted or not, because it just displays the notification description html

**Comment by nuxsmin** [comment]
Hello, right, I knew it was there, but it needs some tweaks that will be done shortly.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commits. Thanks for the feedback!
