### ISSUE TITLE
copy account permission lost after saving

### ISSUE THREAD

**Issue by Edll** [nuxsmin/sysPass#1145]
**sysPass Version**
3.0-rc5 (300.18112601)

**Describe the bug**
If an account is copied then the permissions are still present before saving. After saving the permissions are no longer available. These can then be set and saved and are then also permanently available.

**To Reproduce**
1. Open an Account with group permissions
2. Use copie Account
3. Edit and Save
4. permissions not set

**Event log**
Some lines from `syspass.log` file (within `config` directory) and sysPass event log that were logged when the error happened.

**Platform (please complete the following information):**
 - OS: Linux
 - OS Version Arch
 - Browser Firefox, Chrome

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commits. Thanks for the feedback!
