### ISSUE TITLE
Account History bug with time/user

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1147]
**sysPass Version**
v3 r5

Hey, when modifying an account a row on account is inserted named "History". This containts the selectable list auf data sets of different states of this account. I found out that the timestamp and creator/user of this modification item is completely wrong. You can try it out on the demo syspass for example
![grafik](https://user-images.githubusercontent.com/5631071/49235205-df167f80-f3f9-11e8-8e5b-2a28c4faa92c.png)

The first item should have some timestamp from 17:00 o clock.

regards, Mario

**Comment by nuxsmin** [comment]
Hmmm, I'd rather say that this is the correct behavior, since the time displayed is the account's last modification time (you can see it on details). I've just done a test and it worked fine

Regards

**Comment by vmario89** [comment]
Hmm thats strange. I have some weird behaviour with the history. please do the following:

1. go to http://demo-beta.syspass.org:10082 and login (logout if already logged in please)
2. open the account detail view of account with title "DB Server" http://demo-beta.syspass.org:10082/index.php?r=account/view/163&sk=fea13ef0846227f133b69522e18b7fb5e482ef5c
At this point the history row is missing:
![grafik](https://user-images.githubusercontent.com/5631071/49236453-6cf36a00-f3fc-11e8-9ed4-7d1cb08217c3.png)
3. make some change on the account and save it. The history will appear:
![grafik](https://user-images.githubusercontent.com/5631071/49236487-7f6da380-f3fc-11e8-904a-3fe119f09a88.png) 
![grafik](https://user-images.githubusercontent.com/5631071/49236524-94e2cd80-f3fc-11e8-87d4-e0b633b9c20d.png)

You will see that there are multiple entries now.

I think this is buggy because it should be always shown.  You are right: in this example the timestamp worked correctly. Maybe i muddled up sth because the current entry was missing due to missing view update

**Comment by nuxsmin** [comment]
> 2. open the account detail view of account with title "DB Server" http://demo-beta.syspass.org:10082/index.php?r=account/view/163&sk=fea13ef0846227f133b69522e18b7fb5e482ef5c
At this point the history row is missing

That's the correct behaviour, since you're editing an account and account's history will only showed up when viewing the account details.

Regards
