### ISSUE TITLE
Configurable session timeout?

### ISSUE THREAD

**Issue by glenc2004** [nuxsmin/sysPass#115]
Hi all. I was wondering if in the next release or so you can have an option to configure the session timeout in the configuration screen and place that inside the DB.

Would be  a great option.

Thanks

Glen

**Comment by nuxsmin** [comment]
Hi, it's already done, doesn't work?

Kind regards

**Comment by glenc2004** [comment]
Oh wow. Now I feel stupid. :-( I think I need to get my glasses checked. lol
