### ISSUE TITLE
search result empty for first search after direct login

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1150]
**sysPass Version**
v3 rc4

Hey,
i have a bug when searching for accounts which i recognized a for a longer time now. i think this also happened in older versions.
If you login in to the instance freshly and type in for something to search, hitting enter the result will be empty. After clicking again to the search mask and typing in the same search phrase again, the result list will appear and *not* be empty.

![grafik](https://user-images.githubusercontent.com/5631071/49296092-9fae6880-f4b7-11e8-967f-a3112be542f0.png)

![grafik](https://user-images.githubusercontent.com/5631071/49296085-9ae9b480-f4b7-11e8-8e19-60c34af05567.png)

**Comment by vmario89** [comment]
Hey,
i tested it in v3 rc5 - there it occures too. I think it belongs to the fact that when you login in into syspass the first view the user will see is account search. If you enter something in the search field and apply search the result will be empty. i guess some initial values are missing which are getting populated by refreshing the page.
Seems it belongs to that warning from log file:
2018-12-02 11:34:16 [WARN] [SP\Mvc\View\Template::SP\Mvc\View\{closure}] Variable "taskId" could not be found

regards, Mario

**Comment by nuxsmin** [comment]
Hey, unfortunately I couldn't reproduce this behaviour neither on local nor demo environment. I used FF on Linux.

![peek 06-12-2018 10-49](https://user-images.githubusercontent.com/1775774/49576201-d287af00-f944-11e8-9b61-40d4377c4db9.gif)

The `taskId` variable is only used when performing any sysPass upgrade or updating the master password, so it isn't related to accounts searching.

Regards

**Comment by vmario89** [comment]
Hi @nuxmin, i have no idea whats the cause. It happens in ~2/10 cases. I tried out again. Most times it worked but not always :O i will give feedback if i recognize more to it.

**Comment by nuxsmin** [comment]
Hi @vmario89 are you still facing this issue?. In latest commits the search for accounts behavior was slightly changed, so it might solve it.
