### ISSUE TITLE
Security Failure Syspass 3.0-RC5

### ISSUE THREAD

**Issue by l0s3rr** [nuxsmin/sysPass#1151]
Good afternoon, how are you?

Depending on the lower print, the /var/www/html/sysPass/app/config/config.xml directory is showing some user and bank passwords as well. Unfortunately I only reviewed this configuration, it may be that other files contain this fault as well. Could you tell me if it's to stay the same or is it some kind of bug?

![image](https://user-images.githubusercontent.com/42104711/49298124-b8ad1e80-f4a3-11e8-80aa-c10e60b49414.png)

![image](https://user-images.githubusercontent.com/42104711/49298151-cf537580-f4a3-11e8-8e58-6ff426b3ff62.png)

![image](https://user-images.githubusercontent.com/42104711/49298178-dbd7ce00-f4a3-11e8-924d-8e88365c0466.png)

I am using a CentOS7 with php7.2 and apache 2.4.6.

If I can help you with something, please tell me, I'll be happy. =)

Thanks in advance for your time.

**Comment by vmario89** [comment]
hey,
thats no bug. It just some usual method to store datbase access like thousands of other programs use (like gitea, grafana, collectd). You need to ensure that only trusted people have access to the server which runs syspass and that the web server / app files have correct permissions and ownership. if you do so everything is safe. Even if somebody steals passwords from those config files they cannot do much with it.
For LDAP you would create a dedicated readonly user. For your sysPass database if somebody steals pw no problem: all accounts are encrypted with some salt (master password).

regards, Mario

**Comment by vmario89** [comment]
some edit: some small enhancement for this would be some obfuscating so its not in plain text ;)

**Comment by l0s3rr** [comment]
I did not understand you, because in my XML, the password is not encrypted .... And yes I could encrypt without any problem, however, and if there is this same problem in other settings, would not you be worried?

I'm just wanting the best, I'm not criticizing or anything, my friend. =)

**Comment by vmario89** [comment]
hi, i did not interprete as bad critics. i just want to tell you that this configuration xml with unecrypted password is fine and absolutely normal. i just wanted to point out some security mechanism of syspass and why its still safe ;)

regards, Mario

**Comment by l0s3rr** [comment]
OK, I got it now =)

 I understand, I would like to know if I could automate the encryption of this data if possible, if not, could you point me to where I will find other cases like these? So I encrypt the passwords with base64.

**Comment by nuxsmin** [comment]
@l0s3rr base64 is not encryption

In such case (encrypting the data), where do you will store the encryption key?.

Please take a look to /etc directory and search for any service password, they are there in a secure place, because they won't be visible by anyone. You can do it with sysPass config by configuring the web server (see documentation) or even modifying `Base.php` file to set the configuration path.

**Comment by nuxsmin** [comment]
@vmario89 thanks for the feedback!
