### ISSUE TITLE
Label line break looks ugly on mobile devices

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1152]
**sysPass Version**
v3 rc5

Hy @nuxsmin,
this is something ive seent for a long while and wanted to ask if this behaviour of filter labels is wanted or could be changed. I think it looks not so good with a line break:
![grafik](https://user-images.githubusercontent.com/5631071/49332149-1460d000-f5a8-11e8-9716-b84536b5ef72.png)

**Comment by akurzawa** [comment]
OMG - is this really reported as an issue?

**Comment by nuxsmin** [comment]
@akurzawa not a critical bug, but just an improvement

**Comment by nuxsmin** [comment]
Hey, this issue has been fixed in latest commit. Thanks for the feedback!
