### ISSUE TITLE
Temporary Password Email not Sent

### ISSUE THREAD

**Issue by jorgemfm** [nuxsmin/sysPass#1156]
**sysPass Version**
3.0-rc5 (300.18112601)

**Describe the bug**
If no group is selected on the Temporary Password option, the email is not sent to every user as described ( Sends an email to all users or only to those whose group is selected. )

If a group is selected the email is sent.

**To Reproduce**
1. Go to Configurations > Encryption > Temporary Password
2. Check the Send Email option
3. Click generate button

**Platform (please complete the following information):**
 - OS: Linux
 - OS Version: Debian 9.5
 - Browser: Chrome

**Comment by nuxsmin** [comment]
Hello, this feature does actually send notifications to users that belongs to the selected group, and not for individual users.

Regards

**Comment by jorgemfm** [comment]
Thanks for the answer!

Although the description on the option is still a bit misleading: 
Sends an email to **all users** OR only to those whose group is selected

The possibility to send to all users would be great, since if you have a large number of groups you have to send a email to each of them.

Thanks :)

**Comment by nuxsmin** [comment]
I should send to all users if no group is selected, doesn't it?

**Comment by jorgemfm** [comment]
No, It doesn't send any email if no group is selected.

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commits. Thanks for the feedback!
