### ISSUE TITLE
How does the email configuration works

### ISSUE THREAD

**Issue by jorgemfm** [nuxsmin/sysPass#1157]
**sysPass Version**
3.0-rc5 (300.18112601)

**Describe the question**

I'm not sure why this is like this, but on the email configuration the field **Recipients** is mandatory and this means that the email will received several notification like: user added, user deleted, etc..

But if I only want to configure the email so that I can send the temporary master password and not to receive those other notifications its not possible, at least from what I understood.

Don't know if I made myself clear :)

**Comment by nuxsmin** [comment]
Hello, the mail configuration does not have any action on temporary master password notifications. It's intended to email those actions performed by the users (including admins).

Regards

**Comment by jorgemfm** [comment]
But if I don't configure the mail setting i'm not able to send the temporary password email.

**Comment by jorgemfm** [comment]
The problem is that I didn't defined any event and i'm still receiving emails like:

- User updated
- User deleted
- etc...

Maybe the problems is this.

Still, the **Recipients** field should only be mandatory if I want to receive event messages.
