### ISSUE TITLE
Can't login after migration to new server

### ISSUE THREAD

**Issue by ramonakoenig** [nuxsmin/sysPass#1158]
Hello :)
I had to move my sysPass installation to a new server in my company.
I installed MySQL on the new server, created the database syspass and imported the mysqldump from the old server. After that I copied the whole syspass directory to the new server. I had to change the Database password in the config.xml but after that the login screen appeard, yay ;)
Sadly I can not log in.. if I enter the user/pw for admin or any other user, I get a red banner with "Internal Error", but if I type the wrong password it says "Incorrect Logon".
The syspass.log is just writing "empty lines"

```
2018-12-05 14:29:59 -
2018-12-05 14:30:30 -
2018-12-05 14:32:53 -
2018-12-05 14:33:43 -
2018-12-05 14:47:47 -
2018-12-05 15:04:18 -
```
My sysPass Version is 2.1.15, and I use RHEL 6 (on the old server I had CentOS 7) and PHP 7.0

Can anybody help me, how can I log in again? 

Greetings, Ramona

**Comment by vmario89** [comment]
Hey, it looks like permission/owner issue. Please double check that the application has correct access to all files. This might be some php files access issue for example. 

Please also check the permissions of your database. Maybe you created the database and imported the dump but forgot to create the user or to grant permissions to user to database?

**Comment by nuxsmin** [comment]
Hello, it might be a SElinux issue. Please check out the web server event log.

Regards

**Comment by ramonakoenig** [comment]
Hello
So, I checked the apache .err logfile (I changed the IP addresses to X.X.X.X (my computer) and Y.Y.Y.Y (the server):
```
[Thu Dec 06 10:25:18.019668 2018] [ssl:info] [pid 12222] [client X.X.X.X:51140] AH01964: Connection to child 4 established (server Y.Y.Y.Y:443)
[Thu Dec 06 10:25:18.019904 2018] [ssl:debug] [pid 12222] ssl_engine_kernel.c(2141): [client X.X.X.X:51140] AH02043: SSL virtual host for servername Y.Y.Y.Y found
[Thu Dec 06 10:25:18.019936 2018] [ssl:debug] [pid 12222] ssl_engine_kernel.c(2141): [client X.X.X.X:51140] AH02043: SSL virtual host for servername Y.Y.Y.Y found
[Thu Dec 06 10:25:18.019940 2018] [core:debug] [pid 12222] protocol.c(2257): [client X.X.X.X:51140] AH03155: select protocol from , choices=h2,http/1.1 for server Y.Y.Y.Y
[Thu Dec 06 10:25:18.042414 2018] [ssl:debug] [pid 12222] ssl_engine_kernel.c(2069): [client X.X.X.X:51140] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-CHACHA20-POLY1305 (256/256 bits)
[Thu Dec 06 10:25:18.051576 2018] [ssl:debug] [pid 12222] ssl_engine_kernel.c(377): [client X.X.X.X:51140] AH02034: Initial (No.1) HTTPS request received for child 4 (server Y.Y.Y.Y:443), referer: https://Y.Y.Y.Y:8437/index.php
[Thu Dec 06 10:25:18.051696 2018] [authz_core:debug] [pid 12222] mod_authz_core.c(809): [client X.X.X.X:51140] AH01626: authorization result of Require all granted: granted, referer: https://Y.Y.Y.Y:8437/index.php
[Thu Dec 06 10:25:18.051722 2018] [authz_core:debug] [pid 12222] mod_authz_core.c(809): [client X.X.X.X:51140] AH01626: authorization result of <RequireAny>: granted, referer: https://Y.Y.Y.Y:8437/index.php
[Thu Dec 06 10:25:23.330193 2018] [ssl:debug] [pid 12222] ssl_engine_io.c(1103): [client X.X.X.X:51140] AH02001: Connection closed to child 4 with standard shutdown (server Y.Y.Y.Y:443)
```

**Some additional information I forgot to mention yesterday:** 

I switched database from MariaDB to MySQL. Can this cause the issue? The connection to the database seems to be possible, because if I type my password wrong the error is "wrong password" and not "internal error".

On the new server sysPass is running on Port 8437 (configured in apache vhosts). But I think that should be no problem since I am able to view the login page.

SELinux is disabled on our system.
```
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#       enforcing - SELinux security policy is enforced.
#       permissive - SELinux prints warnings instead of enforcing.
#       disabled - SELinux is fully disabled.
SELINUX=disabled
# SELINUXTYPE= type of policy in use. Possible values are:
#       targeted - Only targeted network daemons are protected.
#       strict - Full SELinux protection.
SELINUXTYPE=targeted
```

**Comment by ramonakoenig** [comment]
Oh, and the normal apache logfile is just writing this line:
`X.X.X.X - - [06/Dec/2018:10:51:26 +0100] 286 0 "GET /ajax/ajax_doLogin.php?user=ramona&pass=ff0ApCN%2BMwu0LtSVXW0Epahtb6XNRxd8KcizHhcV2HL%2FppHdmMujQxlMZMeiHii27%2FXcIgVzQZIFsWSJ%2FjqGc7RB62bwd%2BEu4GZY%2BUjrGIvrQ2z1ydMOFSAuwOM8%2BAi0AmknHqYpZjsXXh%2F1REoBfoKg%2FSD4dpndxBWPdEalkio%3D&oldpass=&mpass=&login=1&isAjax=1&_=1544088167243 HTTP/1.1" 200 105`

**Comment by deajan** [comment]
You should try to enable php error logging and see if something's not going well there.

**Comment by ramonakoenig** [comment]
Hi :)

I tried to find more information about my "Internal Error"...
In the ajax_doLogin Response I have JSON Status 4... after digging through the files in /inc directory and subdirectories I found the file LoginController.class.php, with all the functions throwing an internal error.
For my debugging, I edited this file and added the function name to the "Error Interno" String.
When I try to log in, it displays "Error interno loadMasterPass". I tried to understand the loadMasterPass function, but my php knowledge is very basic.

Can you help me understand the error with the loadMasterPass function?

Thank you!

**Comment by nuxsmin** [comment]
Hi,

The 'internal error' message could be caused by several errors, so it would be useful to get more info by setting 'debug=true' within 'Base.php' file.

Regards

**Comment by ramonakoenig** [comment]
Okay, I changed the line `define('DEBUG', false);` to `define('DEBUG', true);` in the inc/base.php file.
But I can't see more information in my apache error log and in the syspass log.

**Comment by nuxsmin** [comment]
Could you check out for the latest messages in the database `log` table?

**Comment by ramonakoenig** [comment]
Yes, I checked it:
**log_login** is empty
**log_userId** is 0
**log_ipAddress** is my computer IP-Address
 **log_action** is "Anmelden" (sorry, I'm from germany so it is german, but it is just like "login"
**log_description** is "Error interno loadMasterPass" "Typ: authBrowser" "Typ: authDatabase" 
and the last field (log_level?) is ERROR.

This line appears for every login attempt. But I have one interesting line which says "Aus Sitzung ausloggen" (Session Log Out), "Zeit ohen Aktivität: 88,22 min" (Time without activity) and "Gesamtzeit 132,42 min" (Total Time). 
This is kinda strange, since I never logged in without getting the error...

**Comment by nuxsmin** [comment]
It seems that a missing cryptographic library is causing the issue .

**Comment by ramonakoenig** [comment]
Is this library for php or apache?
Maybe I can find out what libraries are installed?

**Comment by ramonakoenig** [comment]
Thank you :) 
My Modules:
`````
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zlib

[Zend Modules]
`````

**Comment by ramonakoenig** [comment]
I compared them to the Modules on the old server with working sysPass, the list is the same..

**Comment by deajan** [comment]
Does your sql user have sufficient privileges ?
if not, can you do a ```GRANT ALL PRIVILEGES ON syspassdatabase.* TO 'sqluser'@'localhost'; FLUSH PRIVILEGES;``` ?

**Comment by ramonakoenig** [comment]
Hey deajan,
I checked the privileges for sp_admin, this looks good to me:
```
mysql> show grants for 'sp_admin'@'localhost';
+-----------------------------------------------------------------------------------------------------------------+
| Grants for sp_admin@localhost                                                                                   |
+-----------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'sp_admin'@'localhost' IDENTIFIED BY PASSWORD 'xxxxxx' |
| GRANT ALL PRIVILEGES ON `syspass`.* TO 'sp_admin'@'localhost' WITH GRANT OPTION                                 |
+-----------------------------------------------------------------------------------------------------------------+
```

**Comment by ramonakoenig** [comment]
Hello :)
My problem is solved, thank you all for your help! 
PHP was not compiled with OpenSSL.

Greetings Ramona
