### ISSUE TITLE
Unable to conect to DB

### ISSUE THREAD

**Issue by Ataraxxia** [nuxsmin/sysPass#1159]
**sysPass Version**
3.0-rc5

**Describe the bug**
During initial setup via browser the "DB access password" cannot be looked up, it only displays encrypted text. Other password fields preview passwords properly. All in all i can't connect o DB, even as root and the installer won't let me pass.

**Expected behavior**
Preview of input password string and proper installation of syspass.

**Platform (please complete the following information):**
 - OS: Linux
 - Debian 9.6
 - Tested on firefox and chrome

**Comment by jorgemfm** [comment]
Hi,

I'm not from the development team, but during my several test installation I had some issues with bd access too

One of the times, the way I did it was to create the database myself, then created a user and gave it access to the database, then, during the installation I checked the **Hosting Mode** field and I was able to finish the installation

Be aware that in some linux distros the root is only able to connect from the command line and using sudo.

**Comment by Ataraxxia** [comment]
I've discovered that when I input really long (as in, more than 50-70 chars) DB password the javascript function breaks(?) and doesn't try to encrypt the input field, so it let's me pass. The issue still stands however.

**Comment by nuxsmin** [comment]
@Ataraxxia 

>  Preview of input password string and proper installation of syspass.

It can be showed up by standing the pointer over the eye icon.

> I've discovered that when I input really long (as in, more than 50-70 chars) DB password the javascript function breaks(?) and doesn't try to encrypt the input field, so it let's me pass. The issue still stands however.

I've just tested to enter a random 80 chars long password (`BHMfKjUUgua4nXzVj64aJQPrMuuCaHvCbZaXq3Qkwp7kPj7wXKXpj99kaU7CZDqFyvWRgNXNCgb4avU3`) on demo site and it was successfully encrypted. As I know, long passwords (more than 117 chars long) will break RSA encryption, since the key length is 1024 bytes.

Regards

**Comment by Ataraxxia** [comment]
@nuxsmin 

> It can be showed up by standing the pointer over the eye icon.

The whole issue is mainly about this preview (hovering over the eye icon) being encrypted. I thought this was clear, because there is no other way of previewing password input.

**Comment by nuxsmin** [comment]
@Ataraxxia 

Sorry, you're right, this input field isn't properly upgraded to show up the password when hovering over, since `passwordfield__input` is the only class which will trigger this behavior. An additional class `passwordfield__input-show`) needs to be added.

Thanks for the feedback!

**Comment by Ataraxxia** [comment]
> I'm wondering whether the current title (`Unable to conect to DB`) does fit on this issue.

I think it does, because I couldn't connect (during installation setup), but when I broke the encryption by using really long password (and after setting same password on DB side) everything worked. The whole preview thing is probably a side effect.

**Comment by nuxsmin** [comment]
I've checked out the code involved on installation process and it was fine. The server side does the decryption task for the password field and the RSA encrypted data are successfully decrypted. I seems wrong behaviour on client side. My testing environment is like yours (Debian 9 on Docker and FF running on Linux desktop). Sorry, but I can't figure out what could be happening...
