### ISSUE TITLE
Users access - how to write a non-autogenerated password?

### ISSUE THREAD

**Issue by oguevarah** [nuxsmin/sysPass#1160]
**sysPass Version**
Can be found on `Config -> Information` tab

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Event log**
Some lines from `syspass.log` file (within `config` directory) and sysPass event log that were logged when the error happened.

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android]
 - OS Version
 - Browser [e.g. Firefox, Chrome]

**Additional context**

**Comment by oguevarah** [comment]
I'm trying to change a user password or see what password was auto generated, but it's not possible. Genrate the user password it's success but i can see it, any idea? sysPass-2.1.16.18061901 it's my version

**Comment by oguevarah** [comment]
sysPass-2.1.16.18061901 installed on ubuntu server 16.04 lts following the offcial installation guide

**Comment by nuxsmin** [comment]
Hello, did you mean a user password and not an account one? . If so, as I pointed in another issue, users' password are only a bcrypt generated hash from the real password, so there's no way to guess the real password.

Regards

**Comment by xardalph** [comment]
Hi
thanks for the app !  
same problem here, can't edit user password 
at creation :
![image](https://user-images.githubusercontent.com/33491716/49613201-570b1980-f9a7-11e8-9bc5-39261dcacaf1.png)

i select a random password and select password change option but i have that :

![image](https://user-images.githubusercontent.com/33491716/49613289-8e79c600-f9a7-11e8-8dae-b9c277d41eb7.png)

if i try to change password after creation same problem, also  i can't change password length for random password or show it

docker-compose 1.17.1
docker 17.12.1-ce on VM ubuntu 18.04 lts 
last docker-compose file found in the repo 
sysPass version | 2.1 (2.1.16.18061901)

thanks

**Comment by nuxsmin** [comment]
@xardalph hi, glad to know it's useful!

You can see the password before changing the focus from the input box by   moving the pointer over the eye icon (it also works for auto-generated passwords). After changing the focus, it will be encrypted for sending to the server.

Related #279

Regards

**Comment by nuxsmin** [comment]
@xardalph forced password change only works if mail notifications are enabled, because it needs to send a request to the user it's being changed for.

**Comment by xardalph** [comment]
thanks for the reply, 
with firefox(63.0.3), i can't select password field, the cursor apear one instant and disappear so i can't see the password, and i can't right click on it to see in console, but it work well in chrome
