### ISSUE TITLE
Command for ldap

### ISSUE THREAD

**Issue by Eztharia** [nuxsmin/sysPass#117]
Hi ,

In the next commands the entry called "password" it's the admin syspass password or ldap password ?

ldapadd -D cn=admin,cn=config -w "password" -H ldapi:/// -f memberof_add.ldif
ldapadd -D cn=admin,cn=config -w "password" -H ldapi:/// -f memberof_config.ldif

Thanks for u'r job.

**Comment by nuxsmin** [comment]
Hi, that is the LDAP password,  because the syspass users passwords should
be set before you add the member of overlay.

Kind regards
