### ISSUE TITLE
 error 500 

### ISSUE THREAD

**Issue by qn0** [nuxsmin/sysPass#1171]
**sysPass Version**
3.0.0.18121601-rc6
PHP 7.2.13 (cli) (built: Dec  8 2018 12:11:34) ( NTS )

**Describe the question**
Hello.
Can u help me pls, i have some issue with install syspass
Have error 500

**Platform (please complete the following information):**
 -CentOS7
Chrome

[Sat Dec 22 16:16:41.755327 2018] [php7:error] [pid 6615] [client 10.255.0.42:56734] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in /var/www/html/syspass/lib/BaseFunctions.php:149\nStack trace:\n#0 /var/www/html/syspass/lib/BaseFunctions.php(110): __('Context not ini...')\n#1 /var/www/html/syspass/lib/SP/Core/Context/SessionContext.php(102): processException(Object(SP\\Core\\Context\\ContextException))\n#2 /var/www/html/syspass/lib/SP/Core/Context/SessionContext.php(232): SP\\Core\\Context\\SessionContext->getContextKey('userData', Object(SP\\Services\\User\\UserLoginResponse))\n#3 /var/www/html/syspass/lib/SP/Config/Config.php(198): SP\\Core\\Context\\SessionContext->getUserData()\n#4 /var/www/html/syspass/lib/SP/Config/Config.php(119): SP\\Config\\Config->saveConfig(Object(SP\\Config\\ConfigData), false)\n#5 /var/www/html/syspass/lib/SP/Config/Config.php(93): SP\\Config\\Config->initialize()\n#6 /var/www/html/syspass/lib/Definitions.php(61): SP\\Config\\Config->__construct(Object(SP\\Storage\\File\\XmlHandler), Object(SP\\Storage\\File\\FileCache), Object(DI\\Container))\n#7 [internal function]: DI\\Definition\\Sourc in /var/www/html/syspass/lib/BaseFunctions.php on line 149

**Comment by nuxsmin** [comment]
Hello, please install latest RC7 

Regards

**Comment by qn0** [comment]
Hello,
Ty very much for help, but i have new one :(

http://10.111.0.113/syspass/
then i have "/config" directory permissions are wrong

but i did 
chmod -R 777 /var/www/html/syspass
chown -R apache /var/www/html/syspass
chcon -R -t httpd_sys_rw_content_t /var/www/html/syspass

What do i do wrong?
ty

**Comment by qn0** [comment]
or maybe u have some new instruction to install for CentOS 7, or better use another OS? Coz i cat install syspass for a 7 days :)

**Comment by nuxsmin** [comment]
Hello, `config` directory in sysPass v3 is located in `app` directory and permissions, like in previous version, need to be `750`.

Regards

**Comment by qn0** [comment]
ty very much
it helped and worked.
Happy Holidays!!!

**Comment by nuxsmin** [comment]
Sounds good!. Happy holidays too!
