### ISSUE TITLE
sysPass and HAProxy

### ISSUE THREAD

**Issue by alexseys** [nuxsmin/sysPass#1173]
**sysPass Version**
sysPass version | 3.0-rc5 (300.18112601)

Database | SERVER_VERSION : 5.5.60-MariaDB

**Describe the question**
Was wandering how to setup haproxy with ssl termination for sysPass?
Anything special required?

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android]
 - OS Version
 - Browser [e.g. Firefox, Chrome]

**Additional context**
App works as expected, and I am just wandering if anyone in this group have used haproxy with ssl termination for sysPass? Examples would be very appreciated.
I am managing haproxy with puppet and syntax is quite convoluted.

Thank you.
Al

**Comment by nuxsmin** [comment]
Hello, I use to run sysPass behind a reverse proxy like Varnish and pound as SSL backend, so steps should be pretty straightforward like setting up SSL certificates and backend port.

This article might be useful: https://serversforhackers.com/c/using-ssl-certificates-with-haproxy

In sysPass web server side you wouldn't need to deal with SSL but it could be implemented in the web server configuration.

Regards.

**Comment by alexseys** [comment]
Yes, thank you
Seems I got that working per @nuxsmin suggestion.

Thank you.
