### ISSUE TITLE
admin login when ldap on

### ISSUE THREAD

**Issue by kdbrown5** [nuxsmin/sysPass#1177]
Hi, 

For some reason, I can't log into the admin account when LDAP is on.  I do not have a conflicting admin account that has been imported via ldap.  Login for admin works currently when my settings are the following 

![image](https://user-images.githubusercontent.com/46332316/50618067-5df15300-0ea5-11e9-8b26-0c079892ad4b.png)

![image](https://user-images.githubusercontent.com/46332316/50618048-39957680-0ea5-11e9-8685-2dbff9f82312.png)

sysPass version | 2.1 (2.1.16.18061901)
-- | --
Database | SERVER_VERSION : 5.5.5-10.2.20-MariaDB-1:10.2.20+maria~bionic CLIENT_VERSION : mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $ SERVER_INFO : Uptime: 529307 Threads: 7 Questions: 7321 Slow queries: 0 Opens: 46 Flush tables: 1 Open tables: 40 Queries per second avg: 0.013 CONNECTION_STATUS : syspass-db via TCP/IP Name: syspass@syspass-db
PHP | Version: 5.6.36-0+deb8u1

Any help would be greatly appreciated.

Thank you!

**Comment by kdbrown5** [comment]
Thank you for responding.

The syspass default 'admin' login only works when Active Directory setting/toggle is disabled.  Even though I don't have any LDAP users with the name 'admin' being pulled in from LDAP/AD.

**Comment by nuxsmin** [comment]
> Even though I don't have any LDAP users with the name 'admin' being pulled in from LDAP/AD.

It doesn't need to be pulled, since the 'admin' user already exists in sysPass, so that error is most likely because the LDAP search filter is getting an 'admin' user within the results, then the LDAP server returns the `invalid credentials` message.

**Comment by kdbrown5** [comment]
The parameters I have in my ldap search exclude that user entirely though, and is only focused on one OU group

I guess I can just work around this by making a service account with a different name.  Thank you for responding and taking the time.  You are making a fantastic product.  is there any intention or possibility to make a browser extension at some point in the future?

**Comment by nuxsmin** [comment]
> is there any intention or possibility to make a browser extension at some point in the future?

Sure, I'm working on a FF extension.

Thanks for the feedback!

Regards
