### ISSUE TITLE
sysPass v3.0 oddities

### ISSUE THREAD

**Issue by fprina** [nuxsmin/sysPass#1178]
**sysPass Version**
v3.0-rc8

**Describe the bug**
After the update to v3.0-rc8 I noticed these issues:
- I do not receive anymore the CEF logs via syslog
- The X-Forwarded-For header is ignored in the event logs 
- The Enable/Disable debug option is not working properly; look like it's always enable
- Search filters are resetted when you return to the main page clicking the a Back or Search button 
- In my opinion sometime the "Back" button do not have a correct behaviour, but I do not have specific cases  
- In the footer it's still marked as 3.0-rc8 and not 3.0
- If you have "Show Filters" enabled in the "User preferences" and you click on the top-left sysPass log the "additional filters" disappear

**Additional context**
Thanks for your fantastic working

**Comment by nuxsmin** [comment]
Hello, though there aren't many changes, sysPass version should point to 3.0 as set in the variable where version is read from https://github.com/nuxsmin/sysPass/blob/45706ce13b221fb13149928c667405371eebc12e/lib/SP/Services/Install/Installer.php#L58

Please, let me check out the issues you pointed.

>  Thanks for your fantastic working

You're welcome!

Regards

**Comment by fprina** [comment]
The **sysPass-3.0.0.18122601** archive downlodable from the [release page](https://github.com/nuxsmin/sysPass/releases) refer to 3.0-rc8

**Comment by nuxsmin** [comment]
Hello, regarding your points:

>  I do not receive anymore the CEF logs via syslog

Working on a patch

>    The X-Forwarded-For header is ignored in the event logs

It should be logged within description field.

> The Enable/Disable debug option is not working properly; look like it's always enable

Not sure about what you mean with "look like it's always enable". 

> Search filters are resetted when you return to the main page clicking the a Back or Search button

Fixed in latest commits.

> In my opinion sometime the "Back" button do not have a correct behaviour, but I do not have specific cases

Back button will reset its own history when clicking on top menu search button.

> In the footer it's still marked as 3.0-rc8 and not 3.0

Fixed in latest commits

> If you have "Show Filters" enabled in the "User preferences" and you click on the top-left sysPass log the "additional filters" disappear

"addition filters" will be showed up when switching to accounts search view, but they can be hidden by clicking on "-" button though the will be showed up again when switching to this view.

Thanks for the feedback!

Regards

**Comment by fprina** [comment]
The sticky filters works perfectly
Thanks 


**The X-Forwarded-For** 
In the column IP of the  "Event log" page I see the Address of my reverse proxy (haproxy) instead the X-Forwarded-For ; I remember that syspass v2.x showed the X-  one

**Debug** 
Maybe I misunderstood the "debug" and the "tracks events"
What should happen when the debug option is enabled ?

**Additional filters**
When you have "Show Filters" enabled in the "User preferences" the TAG search field is automatically showed prefixed by "-"; If you click on the top bar Search icon this work instead  
if you click on the top left logo the field it's hidden, you see the "+"  but it do not works and you can see the field again
