### ISSUE TITLE
Unable to rename an account

### ISSUE THREAD

**Issue by dajones70** [nuxsmin/sysPass#1180]
**sysPass Version**
2.1
PHP 7.0.33
CentOS 7.6

**Problem**
After renaming an account, it is not able to login.

**To Reproduce**
1. As admin, create a test account.
2. Login with the new account using the master password.
3. Logout
4. As admin, rename the account.
5. Login as the renamed account and it will fail.

**Expected behavior**
Renamed account should be able to login.

**Platform (please complete the following information):**
This should not be specific to client OS or browser since renaming the user back to the old name resolved the problem.

**Comment by nuxsmin** [comment]
Hello, sysPass relies on user's data (and application salt) for creating a secure encryption key and use it for encrypting the master password. This user's data includes login and password, so any change to these data will cause to be prompted for the master password (you can use a temporary master password instead).

Regards
