### ISSUE TITLE
Error message after access Security and Audit

### ISSUE THREAD

**Issue by schleyk** [nuxsmin/sysPass#1182]
**sysPass Version**
3.0 (300.18122601)  (Docker Image nuxsmin/docker-syspass:3.0-php7.2)

**Describe the bug / To Reproduce**
Error message shown after access "Security and Audit" -> Event Log -> klick reload button.
`There was an error
Service Unavailable
Invalid Action`

**Expected behavior**
no error message? :P

**Screenshots**
![grafik](https://user-images.githubusercontent.com/17356113/50740175-fc095400-11ea-11e9-8e83-e5785364319d.png)

**Event log**
Some lines from `syspass.log` file (within `config` directory) and sysPass event log that were logged when the error happened.
`2019-01-06 18:31:16 [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
2019-01-06 18:31:16 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-06 18:31:16 [EXCEPTION] [N/A] UngĂ¼ltige Aktion
#0 /var/www/html/sysPass/app/modules/web/Controllers/EventlogController.php(104): SP\Modules\Web\Controllers\ControllerBase->checkSecurityToken('68bcfcd29e3e9ec...', Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\EventlogController->searchAction()
#2 /var/www/html/sysPass/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')
#9 {main}`

**Platform (please complete the following information):**
 - OS: Windows 10 x64 Build 1809
 - Browser: Firefox 64.0 (64bit)

**Comment by nuxsmin** [comment]
Hello, this error is caused by an expired security token. This token is generated for every action that is performed against the server (search, create, update, etc.), so if you opened a second tab in the same browser, it will invalidate the previous token (generated in other tab). Is this your case?

Regards

**Comment by schleyk** [comment]
Hello nuxsmin,
No, I have not opened a second tab in the same browser.
I just login with an admin user and in the same browser tab klick: `Security and Audit -> Event Log -> reload`

**Comment by yycengbers** [comment]
Just ran across the same issue.  For me, the owner of the cache directory was incorrect.  I could tell because `./app/cache/secure_session` had no new files in it.

**Comment by yycengbers** [comment]
I have the same issue.  The log is the exact same.
sysPass version : 3.0 (300.18122601) - also Fresh Install
SERVER_VERSION : 5.5.5-10.1.34-MariaDB-0ubuntu0.18.04.1
php Version : 7.2.10-0ubuntu0.18.04.1
server : nginx/1.14.0

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commits but it hasn't been released yet.

Thanks for the feedback!
