### ISSUE TITLE
Internal error, LDAP login - AD

### ISSUE THREAD

**Issue by fbernard89** [nuxsmin/sysPass#1183]
**sysPass Version**
3.0 (300.18122601)

**Describe the bug**
Hello, I just configure a fresh syspass under version 3.0. I configure LDAP with Active Directory and Test the connection where it succesfull. Syspass see user in security group for the connection. The problem it's when the user try to connect, I see into the domain controller the succesfull login but I get internal error on the login page. I try to enter the domain sso in the general page, I get the same behavior.

**To Reproduce**
1. Configure LDAP with Windows AD (not azure)
2. Try to connect with user member of the security group

**Expected behavior**
Login with the AD user

**Event log**
#0 /var/www/html/syspass/syspass-3.0-rc8/lib/SP/Providers/Auth/Ldap/LdapAuth.php(156): SP\Providers\Auth\Ldap\LdapActions->getAttributes('(&(|(samaccount...')
#1 /var/www/html/syspass/syspass-3.0-rc8/lib/SP/Providers/Auth/Ldap/LdapAuth.php(121): SP\Providers\Auth\Ldap\LdapAuth->getAttributes('admin')
#2 /var/www/html/syspass/syspass-3.0-rc8/lib/SP/Providers/Auth/AuthProvider.php(115): SP\Providers\Auth\Ldap\LdapAuth->authenticate(Object(SP\DataModel\UserLoginData))
#3 /var/www/html/syspass/syspass-3.0-rc8/lib/SP/Providers/Auth/AuthProvider.php(93): SP\Providers\Auth\AuthProvider->authLdap()
#4 /var/www/html/syspass/syspass-3.0-rc8/lib/SP/Services/Auth/LoginService.php(146): SP\Providers\Auth\AuthProvider->doAuth(Object(SP\DataModel\UserLoginData))
#5 /var/www/html/syspass/syspass-3.0-rc8/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#6 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#7 /var/www/html/syspass/syspass-3.0-rc8/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/syspass/syspass-3.0-rc8/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/syspass/syspass-3.0-rc8/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/syspass/syspass-3.0-rc8/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/syspass/syspass-3.0-rc8/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/html/syspass/syspass-3.0-rc8/index.php(28): require('/var/www/html/s...')
#14 {main}

**Platform (please complete the following information):**
OS : CentoS 7
Windows AD server : server 2012 r2

**Comment by nuxsmin** [comment]
Hello, are there any more messages in `syspass.log` file  before the  first line you posted?. One or two lines before could contain the original error and not the displayed to the user.

Regards

**Comment by fbernard89** [comment]
Hello,

here the line 

2019-01-07 13:06:04 [EXCEPTION] [N/A] Error while searching the user on LDAP

I don't understand because the connection with AD is ok

**Comment by fbernard89** [comment]
After another test we fond that the problem and it,s not directly the code.

Thanks for your help.

**Comment by leonardopiza** [comment]
> After another test we fond that the problem and it,s not directly the code.
> 
> Thanks for your help.

@fbernard89 Could you tell me what the error was? I am facing the same problem
