### ISSUE TITLE
Prestashop Admin Panel not accessible

### ISSUE THREAD

**Issue by asiauvsaa** [nuxsmin/sysPass#1186]
**sysPass Version**
Can be found on `Config -> Information` tab

**Describe the question**
A clear and concise description.

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android]
 - OS Version
 - Browser [e.g. Firefox, Chrome]

**Additional context**

**Comment by asiauvsaa** [comment]
we have taken a look and can see that the site www.asiauvsaa.com/asiauvsaa-prestashop has a script error. 

[message] => Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "mailer_user". in /home/asiauvsa/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:102

You will need to resolve that to correct the 500. In regards to the main URL. That issue appears to be due to a misconfigured .htaccess file. It then tries to resolve to https://www.asiauvsaa.com/en/ which doesn't exist.

Current error is while visiting the admin panel :- 
(
    [type] => 1
    [message] => Uncaught Error: Class 'Symfony\Component\Debug\Debug' not found in /home/asiauvsa/public_html/asiauvsaa-prestashop/index.php:81
Stack trace:
#0 {main}
  thrown
    [file] => /home/asiauvsa/public_html/asiauvsaa-prestashop/index.php
    [line] => 81
)

How to resolve the issue.

**Comment by nuxsmin** [comment]
Unfortunately this issue is not related to sysPass project
