### ISSUE TITLE
Problems with LDAP authentication

### ISSUE THREAD

**Issue by javierlm** [nuxsmin/sysPass#1187]
**sysPass Version**
3.0 (300.18122601)

**Describe the bug**
Login for the first time with an LDAP account, produces an error on the first attempt. The following attempt works as expected, asking for credentials and the master password.

**To Reproduce**
1. Activate LDAP  authentication with server type "Standard" or "Active Directory" in configuration, with correct parameters.
2. Logout with the current user and try to login with an LDAP user for the first time.
3. An error shows as a red notification.
4. Pressing again the login button, works as expected.

**Expected behavior**
Login must be complete without errors at first attempt with a new user.

**Screenshots**
![syspass_first_login_bug](https://user-images.githubusercontent.com/34691743/50890521-43adfc80-13f2-11e9-8b6a-3b607d53b44f.png)

**Event log**
Error doesn't seem to appear at logs.

**Platform (please complete the following information):**
 - Docker compose containers.
 - Firefox and Chromium.

**NOTE**
I will update this report with new information after some more testing.

**Comment by nuxsmin** [comment]
Hello, could you try it out using latest release?

Regards
