### ISSUE TITLE
v3.0 - Event log not recording all information and buttons producing error

### ISSUE THREAD

**Issue by thenathlm** [nuxsmin/sysPass#1191]
**sysPass Version**
3.0 (300.18122601)
Fresh install

**Describe the bug**
The event log isn't recording all information, such as account changes, etc. and when pressing the refresh button or trying to clear the log in the event log, an error appears saying: "service unavailable invalid action".

**Screenshots**
![image](https://user-images.githubusercontent.com/46557932/50958116-dbc1e980-14b7-11e9-8491-c7e9d9aadb51.png)

**Event log**
```
2019-01-10 09:09:28 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-10 09:09:28 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-10 09:09:28 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-10 09:11:27 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-10 09:11:28 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-10 09:11:28 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-10 09:11:38 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-01-10 09:11:39 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-01-10 09:11:39 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-10 09:11:39 [EXCEPTION] [N/A] Invalid Action
#0 /var/www/html/app/modules/web/Controllers/EventlogController.php(104): SP\Modules\Web\Controllers\ControllerBase->checkSecurityToken('936a2ca7b8ed508...', Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\EventlogController->searchAction()
#2 /var/www/html/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/html/index.php(28): require('/var/www/html/l...')
#9 {main}
```

**Platform (please complete the following information):**
 - OS: Centos 7
 - OS Version: Minimal install
 - Browser: All

**Comment by nuxsmin** [comment]
Hello, have you set the events to be logged into the event log?. On v3 you could select which events you want to be  either logged or sent by email.

Regards

**Comment by thenathlm** [comment]
I've had a look through documentation and here on github, however, I can't seem to find anything mentioning where those settings would be.

Could you point me in the right direction?

I also saw that my "service unavailable invalid action" bug is currently being worked on in another thread. If it's any help, I also do not have any other syspass window open, so the security token should be fine.

**Comment by thenathlm** [comment]
Found it.
For anyone who is also blind, like me, it's under:
Configuration > General > Events > Events

You can add them in there from the list that populates when clicking in the text box.

I'll add my part to the other thread that has the same error I'm experiencing with the log and plugins sections.

Thanks for your time @nuxsmin
