### ISSUE TITLE
Upgrade - best practice

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#1192]
Hey, 

I want to do a clean install of the 3.0 version.

But I want to keep my Accounts and Users from the older version.

What is the best way to do this. I replaced the “config.xml”, “key.pem”, “pubkey.pem” within the config folder and imported the old database. Than I opend the application with help of the webbrowser for the first time but there I get the normal installation view.

What is the right way to do this?

**Comment by nuxsmin** [comment]
Did you move the files in 'config' directory to the new directory in sysPass root  ('syspass_root/app/config')?

**Comment by Goatmaster** [comment]
Yes I moved the files to the folder.

**Comment by nuxsmin** [comment]
Is there any message in syspass.log file?
