### ISSUE TITLE
Syspass3.0 Debian Installation

### ISSUE THREAD

**Issue by Kifran16** [nuxsmin/sysPass#1198]
Hi nuxsmin,

I hope you're doing well.

Trying to install syspass 3.0 stable release in standard mode over Debian 9 and it's failing.

Below are the logs during installation.

user@syspass-server:/var/www/html/syspass# ls -l
total 220
-rw-rw-r-- 1 www-data root    961 janv.  2 08:06 api.php
drwxrwxr-x 9 www-data root   4096 janv.  2 08:06 app
drwxrwxr-x 2 www-data root   4096 janv.  2 08:06 build
-rw-rw-r-- 1 www-data root   1824 janv.  2 08:06 composer.json
-rw-rw-r-- 1 www-data root 142635 janv.  2 08:06 composer.lock
-rw-rw-r-- 1 www-data root  35147 janv.  2 08:06 COPYING
-rw-rw-r-- 1 www-data root    960 janv.  2 08:06 index.php
-rw-rw-r-- 1 www-data root   1172 janv.  2 08:06 INSTALL
drwxrwxr-x 3 www-data root   4096 janv.  2 08:06 lib
drwxrwxr-x 6 www-data root   4096 janv.  2 08:06 public
-rw-rw-r-- 1 www-data root   1832 janv.  2 08:06 README.md
drwxrwxr-x 2 www-data root   4096 janv.  2 08:06 schemas
drwxrwxr-x 5 www-data root   4096 janv.  2 08:06 tests
user@syspass-server:/var/www/html/syspass# php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
user@syspass-server:/var/www/html/syspass# ls -l
total 480
-rw-rw-r-- 1 www-data root    961 janv.  2 08:06 api.php
drwxrwxr-x 9 www-data root   4096 janv.  2 08:06 app
drwxrwxr-x 2 www-data root   4096 janv.  2 08:06 build
-rw-rw-r-- 1 www-data root   1824 janv.  2 08:06 composer.json
-rw-rw-r-- 1 www-data root 142635 janv.  2 08:06 composer.lock
-rw-r--r-- 1 root     root 263621 janv. 15 10:10 composer-setup.php
-rw-rw-r-- 1 www-data root  35147 janv.  2 08:06 COPYING
-rw-rw-r-- 1 www-data root    960 janv.  2 08:06 index.php
-rw-rw-r-- 1 www-data root   1172 janv.  2 08:06 INSTALL
drwxrwxr-x 3 www-data root   4096 janv.  2 08:06 lib
drwxrwxr-x 6 www-data root   4096 janv.  2 08:06 public
-rw-rw-r-- 1 www-data root   1832 janv.  2 08:06 README.md
drwxrwxr-x 2 www-data root   4096 janv.  2 08:06 schemas
drwxrwxr-x 5 www-data root   4096 janv.  2 08:06 tests
user@syspass-server:/var/www/html/syspass# php -r "if (hash_file('sha384', 'composer-setup.php') === '93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
Installer verified
user@syspass-server:/var/www/html/syspass# php composer-setup.php
All settings correct for using Composer
Downloading...

Composer (version 1.8.0) successfully installed to: /var/www/html/syspass/composer.phar
Use it: php composer.phar

user@syspass-server:/var/www/html/syspass# php -r "unlink('composer-setup.php');"
user@syspass-server:/var/www/html/syspass# php composer.phar install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 28 installs, 0 updates, 0 removals
  - Installing ademarre/binary-to-text-php (dev-master 5d98d17): Cloning 5d98d17be1
    Failed to download ademarre/binary-to-text-php from source: Failed to clone https://github.com/ademarre/binary-to-text-php.git, git was not found, check that it is installed and in your PATH env.

sh: 1: git: not found

    Now trying to download from dist

  [RuntimeException]
  The zip extension and unzip command are both missing, skipping.
  Your command-line PHP is using multiple ini files. Run `php --ini` to show them.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

user@syspass-server:/var/www/html/syspass#

I missed something ?

Regards

**Comment by Yotouille** [comment]
Hi there,

You may want to check about `git` presence on your system, and perhaps `unzip` too. Then, try again the composer install.

_ps: `sudo apt update && sudo apt install git unzip`_

**Comment by Kifran16** [comment]
Hi Yotouille,

It works like a charm now. Thank you.

@nuxsmin, any chances to update debian 9 installation guide in order to add unzip & git packages as prerequisites ?

Moreover, nothing into documentation regarding mysql connexion with socket access configured by default causing syspass first configuration failure. I had to change it to mysql native password connexion to make it work.

Regards
