### ISSUE TITLE
Is docker image up to date with the stable version 3.0?

### ISSUE THREAD

**Issue by Xumeiquer** [nuxsmin/sysPass#1199]
I am asking because the latest image is one day older than the stable release.

**Comment by nuxsmin** [comment]
Sure, it was built one day after the latest commit on master branch. Please note that `latest` image always points to `master` branch so whenever it was built, it will use the most recent release.

![screenshot_059](https://user-images.githubusercontent.com/1775774/51306584-fa872980-1a3d-11e9-8fe9-ed356eb4efcf.jpg)

![screenshot_060](https://user-images.githubusercontent.com/1775774/51306578-f4914880-1a3d-11e9-9d00-2086930798a6.jpg)

Regards
