### ISSUE TITLE
Agregar a un usuario a mas de un grupo. 

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#120]
Una gran limitación que veo en la aplicación es no poder agregar a un usuario a más de un grupo. 
Creo que sería muy util para poder manejar los permisos mediante grupos. 

Por ejemplo, si quiere agrupar usuario1 + usuario2 para acceder a equipo1, y a la vez usuario1 + usuario3, para equipo2, ahora unicamente lo puedo hacer usuario por usuairo en la config del equipo; con muchos usuarios es una tarea muy complicada y dificil de administrar, sobre todo cuando hay alta y baja de usuarios.

Un abrazo!

**Comment by nuxsmin** [comment]
Buenas, es cierto, sé de esta carencia y está prevista para la versión 1.2

En breve estará disponible ;)

**Comment by gabrielsoltz** [comment]
Hola, estoy probando esta funcionalidad en RC4, y encuentro la siguiente inconsistencia: 
Al crear o modificar un usuario (desde las propiedades del usuario), el campo "grupo" de ese usuario, sólo deja seleccionar uno, no debería dejar seleccionar más de uno ? 
Además luego de seleccionar un grupo, voy a la sección de grupos y edito el que seleccioné (propiedades del grupo) y no veo listado al usuario que asocié a ese grupo desde las propiedades del usuario.
La única forma que encontré de aplicar esta funcionalidad es desde las propiedades de un grupo, asociar a un usuario y luego asociarlo a otro grupo de la misma manera: el problema de esto es que es incosistente con la información seleccionada en las propiedades del usuario, y además que es muy dificil entender a que grupos pertenece cada usuario de manera sencilla, sin tener que entrar a todos los grupos.
Te mando un saludo y gracias.

**Comment by nuxsmin** [comment]
Hola, esta funcionalidad está implantada de esta manera:

* El grupo principal del usuario es el que se encuentra en su ficha de usuario.
* Los grupos secundarios se establecen en cada uno de los grupos en la propia ficha del grupo.

En cuanto a la obtención de los grupos a los que pertenece un usuario, está previsto realizar un apartado para ello.

Esta implementación es debida a que para editar los grupos secundarios, solo basta con tener acceso a la gestión de grupos. De la otra manera es necesario tener permisos para gestión de usuarios, y eso conlleva más riesgos.

Es verdad que es mas confuso, pero me parece que la otra opción es menos segura.

Un saludo.
