### ISSUE TITLE
Old reference to /inc/themes in 3.0

### ISSUE THREAD

**Issue by yycengbers** [nuxsmin/sysPass#1200]
**sysPass Version**
3.0

**Describe the bug**
Setting up server blocks in nginx and using F12 (inspect) to check for errors.  One comes up referencing "https://domain/inc/themes/material-blue/css/Roboto_400.woff2"

Ran a quick search for '/inc/themes' and see the references exist in two files.
/app/modules/web/themes/material-blue/css/fonts.min.css
/app/modules/web/themes/material-blue/css/fonts.css

Great work on the application, we're trialing it out and it seems great so far.

**Comment by DeyV** [comment]
exactly - you can't use relative paths in css, because this files are combined and downloaded by your index.php file.

**Comment by yycengbers** [comment]
DeyV, the bug is that /themes moved to /app/modules/web so the /inc folder doesn't exist.

**Comment by nuxsmin** [comment]
@yycengbers you're right, it's related to a missing file through URL. I'll try to sort out this issue without making big changes, because v3 tries to expose less resources within the web server site, so accessing this kind of files (fonts) from CSS is avoided.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, this issue has been solved in latest commits.
