### ISSUE TITLE
Extended ascii chars bad encoding on account password

### ISSUE THREAD

**Issue by opeshm** [nuxsmin/sysPass#1207]
**sysPass Version**
Can be found on `Config -> Information` tab

Versión sysPass | 3.0 (301.19012002)
-- | --
Base de Datos | SERVER_VERSION : 5.5.5-10.1.37-MariaDB-1~bionic CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $

**Describe the bug**
When I try to use extended ascii chars for an account password, some chars are saved with a bad enconding, so when I get it, I get a bad string.

**To Reproduce**
1. Go to 'New Account'
2. Enter this string: `¨Ü½Ø¤&¼Ö3¤ÌZLNºEs¼ÎJá` in every text field (even in the password input)
3. Save Account'
4. Go to the account and click "View password"
5. The saved password isn't the same `¨Ü½Ø¤&¼&O uml;3¤ÌZLNºEs¼ÎJ&a acute;`

**Expected behavior**
The password showed must be the one we introduced.

**Screenshots**

![acentitos](https://user-images.githubusercontent.com/8150512/51663532-53fbd500-1fb7-11e9-8c99-17d06a163f0b.png)

**Event log**

> There is no log

**Platform (please complete the following information):**
 - OS: Linux Fedora 29 Workstation
 - Browser: 

Vivaldi | 2.2.1388.37 (Stable channel) (64 bits)
-- | --
Agente de usuario | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Vivaldi/2.2.1388.37

**Additional context**
> NONE

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commit.

Thanks for the feedback!

Regards
