### ISSUE TITLE
v3 filter don't work after editing

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1209]
**sysPass Version**
3.0.1

**Describe the bug**
If I'm going to edit an entry (add / edit), to return to the list of entries I click on the syspass logo at the top left.

Once on the home page, when I select a Client or Category filter, it does not apply.

**To Reproduce**
- edit an entry
- clic on Syspass logo up left
- choose a Client to select filter
- the filter is set in drop down menu
- but all entries is listed without filter

**Expected behavior**
the filter is enabled and filter entries

Thanks

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commits.

Thanks for the feedback!

Regards
