### ISSUE TITLE
Idea: Alerta para cambio de Password

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#121]
Se podría setear una fecha en las claves para que nos avise syspass que hay que modificarlas ?

**Comment by nuxsmin** [comment]
Me gusta la idea, voy a ver cómo se podría implementar, ya que puede requerir de nueva tabla para el control de notificaciones.

**Comment by nuxsmin** [comment]
Hecho en sysPass 2.0-beta 

Done in sysPass 2.0-beta
