### ISSUE TITLE
import csv to syspass3 fails

### ISSUE THREAD

**Issue by hoboristi** [nuxsmin/sysPass#1211]
**sysPass Version**
 3.0 (303.19012402) 

**Describe the question**
Tried to import a file with ~4000 rows, but is constantly fails after 1st line, with error 

```
2019-01-24 15:21:51 [EXCEPTION] [N/A] Category Id not set. Unable to import account.
#0 /var/www/syspass/lib/SP/Services/Import/CsvImportBase.php(154): SP\Services\Import\CsvImportBase->addAccount(Object(SP\Services\Account\AccountRequest))
#1 /var/www/syspass/lib/SP/Services/Import/CsvImport.php(53): SP\Services\Import\CsvImportBase->processAccounts()
#2 /var/www/syspass/lib/SP/Services/Import/ImportService.php(73): SP\Services\Import\CsvImport->doImport()
#3 [internal function]: SP\Services\Import\ImportService->SP\Services\Import\{closure}()
#4 /var/www/syspass/lib/SP/Services/Service.php(97): Closure->call(Object(SP\Services\Import\ImportService))
#5 /var/www/syspass/lib/SP/Services/Import/ImportService.php(75): SP\Services\Service->transactionAware(Object(Closure))
#6 /var/www/syspass/app/modules/web/Controllers/ConfigImportController.php(75): SP\Services\Import\ImportService->doImport(Object(SP\Services\Import\ImportParams), Object(SP\Services\Import\FileImport))
#7 [internal function]: SP\Modules\Web\Controllers\ConfigImportController->importAction()
#8 /var/www/syspass/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#9 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/syspass/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#13 /var/www/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#14 /var/www/syspass/index.php(28): require('/var/www/syspas...')
#15 {main}
```

The csv format was:
`Label_#1004;customer1;Category1;fooxahkohthusha;ahcucahl;ohgheenohnaekuohaiteetheiqueeg;ahpahboghaehaihoseinieghoocahrieyeekuwaihoohijohta`

**Platform :**
 - OS: Linux
 - Centos 7
 - Browser:Firefox, Chrome

**Comment by nuxsmin** [comment]
Hello, I'm wondering what could be causing this issue since every sysPass release passes a bunch of tests including CSV import. The following file is used to perform the importing tests:

https://github.com/nuxsmin/sysPass/blob/master/tests/res/import/data.csv

Regards

**Comment by hoboristi** [comment]
Hi there  :)
Unfortunately I've tried it many times, and fails recently.. 
The errors are Category and Client id not set messages.
The data which I used was

[random2.txt](https://github.com/nuxsmin/sysPass/files/2796830/random2.txt)

**Comment by nuxsmin** [comment]
Hi, sorry about this issue, since I've noticed that if an item's id that had already been created wasn't returned as expected. It will be fixed shortly.

Thanks for the feedback!

**Comment by hoboristi** [comment]
> Hi, sorry about this issue, since I've noticed that if an item's id that had already been created wasn't returned as expected. It will be fixed shortly.
> 
> Thanks for the feedback!

Hi there! Thanks for the quick reply, but it seems the issue still presents; I have installed the latest version of Syspass, but it only imports ~490 out of 500 account, and the same error message can be found at the log..
