### ISSUE TITLE
Account add or edit error

### ISSUE THREAD

**Issue by hoboristi** [nuxsmin/sysPass#1212]
**sysPass Version**
 3.0 (303.19012402) 

**Describe the bug**
Error when creating or editing account

**To Reproduce**
Clicking on existing account "Edit"

It returns an error message, when creating or editing account; but second time it always manages to..

**Expected behavior**
no error :)

**Screenshots**
![kijeloles_056](https://user-images.githubusercontent.com/4062730/51688896-cc818680-1ff5-11e9-9c64-93a8fb244665.png)

**Event log**
```
2019-01-24 15:30:31 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-01-24 15:30:31 [EXCEPTION] [N/A] Invalid Action
#0 /var/www/syspass/app/modules/web/Controllers/AccountController.php(378): SP\Modules\Web\Controllers\ControllerBase->checkSecurityToken('de8167c8c8b755e...', Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\AccountController->editAction(15)
#2 /var/www/syspass/lib/SP/Bootstrap.php(234): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/syspass/lib/SP/Bootstrap.php(456): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/syspass/index.php(28): require('/var/www/syspas...')
#9 {main}
```

**Platform (please complete the following information):**
 - OS: Linux
 - Centos 7
 - Browser: Firefox, Chrome

**Comment by possebon** [comment]
I have the same situation here.

**Comment by possebon** [comment]
Thanks Rubén,

What it's not clear to me is if there is something that I can do to fix it. I already set the timeout session to 15 minutes, but even before it reaches the 15 minutes, I get the error message.

The only way I found that I don't get the error message, I need to stay changing from one to another section, for example, after create an account, click on Users and Access, than click again on New Account.

**Comment by nuxsmin** [comment]
That gives more clues about what could be happening, since there's a task that is scheduled to search for notifications every 2 minutes ( "In-app notifications" on user's preferences), so it might be the root of the issue though it was thoroughly tested to avoid this behavior.

**Comment by nuxsmin** [comment]
@possebon I'll try to figure out what could be causing this issue.

Thanks Fernando!

**Comment by nuxsmin** [comment]
Hello, does this issue still going on?
