### ISSUE TITLE
Translation missing/wrong

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1213]
Hey! Just another small translation mistake i've found:

"Data length too big for encrypting"
![grafik](https://user-images.githubusercontent.com/5631071/51703482-b59f5c00-2016-11e9-8c0b-9726408c6ff2.png)

seems that the whole file "/public/js/app-main.js" has no translatable content yet.

regards, Mario

**Comment by vmario89** [comment]
Hi,
nope that's the first thing i checked against:
![grafik](https://user-images.githubusercontent.com/5631071/51787477-b9e08c00-2172-11e9-9f2b-d710a224be22.png)

other strings i checked from strings.js.inc were in place so i guess it was overlooked. Now i checked against pot/po files and i've seen that it's not contained even when using PoEdit extracting method or xgettext on console

![grafik](https://user-images.githubusercontent.com/5631071/51787920-9f5ce180-2177-11e9-9138-a041df8413d4.png)

finally i checked in strings.js.inc - there the string is missing. 

> cat strings.js.inc | grep Data

returns null

does the string numbering play a role in strings.js.inc or can it be added at the bottom?

**Comment by nuxsmin** [comment]
Sorry, you're right, some strings aren't translated because some of them are displayed before the environment is set up, so they can't be translated to the preferred language.

https://github.com/nuxsmin/sysPass/blob/master/public/js/app-main.js

Is there any one more?

Regards
