### ISSUE TITLE
Install error Manifest for nuxsmin/docker-syspass:3.0 not found

### ISSUE THREAD

**Issue by esgeroth** [nuxsmin/sysPass#1219]
I've just tried installing syspass and I have an error message while running docker-compose. The error is "manifest for nuxsmin/docker-syspass:3.0 not found."
I downloaded the docker-compose.yml file from the install documentation and ran the command "docker-compose -p syspass -f docker-compose.yml up -d"
Here is the full output:

PS C:\> docker-compose -p syspass -f docker-compose.yml up -d
Creating network "syspass_default" with the default driver
Creating volume "syspass_syspass-config" with default driver
Creating volume "syspass_syspass-backup" with default driver
Creating volume "syspass_syspass-db" with default driver
Pulling db (mariadb:10.2)...
10.2: Pulling from library/mariadb
38e2e6cd5626: Pull complete
705054bc3f5b: Pull complete
c7051e069564: Pull complete
7308e914506c: Pull complete
35e6984cb587: Pull complete
3a173c4702b4: Pull complete
efd003ff8e24: Pull complete
ba5d30791443: Pull complete
f3e943c9e01d: Pull complete
e5243a434e4f: Pull complete
024a1b141b74: Pull complete
1256e1835420: Pull complete
fe3c563e7a77: Pull complete
5895af743528: Pull complete
Pulling app (nuxsmin/docker-syspass:3.0)...
ERROR: manifest for nuxsmin/docker-syspass:3.0 not found

**Comment by rnssystems** [comment]
Same here Linux Debian x64 under using:

wget https://raw.githubusercontent.com/nuxsmin/docker-syspass/master/docker-compose.yml
docker-compose -p syspass -f docker-compose.yml up -d
Creating network "syspass_default" with the default driver
Creating volume "syspass_syspass-config" with default driver
Creating volume "syspass_syspass-backup" with default driver
Creating volume "syspass_syspass-db" with default driver
Pulling db (mariadb:10.2)...
10.2: Pulling from library/mariadb
38e2e6cd5626: Pull complete
705054bc3f5b: Pull complete
c7051e069564: Pull complete
7308e914506c: Pull complete
35e6984cb587: Pull complete
3a173c4702b4: Pull complete
efd003ff8e24: Pull complete
ba5d30791443: Pull complete
f3e943c9e01d: Pull complete
e5243a434e4f: Pull complete
024a1b141b74: Pull complete
1256e1835420: Pull complete
fe3c563e7a77: Pull complete
5895af743528: Pull complete
Pulling app (nuxsmin/docker-syspass:3.0)...
ERROR: manifest for nuxsmin/docker-syspass:3.0 not found

**Comment by nuxsmin** [comment]
Hello, unfortunately, due to tagging issues, 3.0 was tagged 3.0-php7.0. This was changed on latest builds so the last one was tagged 3.0.4

Thanks for the feedback!

Regards
