### ISSUE TITLE
Cannot import CSV

### ISSUE THREAD

**Issue by AntonTsaberyaby** [nuxsmin/sysPass#1220]
**sysPass Version**
3.0 (304.19012601) 

**Describe the question**
Hi,

I'm trying to import a CSV of accounts and every time I import I get an error saying  "wrong number of fields".

I saw #266 and it works for simple example like file with one line, but if we have more one line it doesn't work.

Could give me any suggestions?

Example of file to reproduce error:

```
name;client;category;url;user;password;notes
Dev DB;Arch;Database;10.107.1.23;root;Test123;root login
```

**Platform (please complete the following information):**
 - Linux Docker
 - Docker image version: Latest
 - Safari

**Comment by nuxsmin** [comment]
Hello, you would need to enclose the fields within double quotes. Here you have an example:

https://github.com/nuxsmin/sysPass/blob/master/tests/res/import/data.csv

Regards

**Comment by AntonTsaberyaby** [comment]
Thanks, @nuxsmin but when I try to import the example, I got the same error "wrong number of fields (25)"

**Comment by AntonTsaberyaby** [comment]
Thanks. Resolved. I had incorrect file endings.

**Comment by AntonTsaberyaby** [comment]
Import works strangely, during the first import only three accounts from the file were imported, during the second import (provided that the previous entries were deleted) only one.

We made PR https://github.com/nuxsmin/sysPass/pull/1232 for fix this issue

**Comment by nuxsmin** [comment]
Hello @AntonTsaberyaby your PR has been merged.

Thanks for the feedback and contribution!
