### ISSUE TITLE
Strange behaviour if I remove index.php from URL after login

### ISSUE THREAD

**Issue by VexedSyd** [nuxsmin/sysPass#1221]
**sysPass Version**
304.19012601

**Describe the question**
my sysPass installation is not the root directory of the webserver. 
The root directory is /var/www/html
sysPass is in /var/www/html/syspass

syspass url https://www.example.com/syspass

If you visit the above URL, you will get redirected to https://www.example.com/syspass/index.php.

After logging in, if you visit https://www.example.com/syspass, you are not redirected to https://www.example.com/syspass/index.php, and the page looks messed up.

in Chrome DevTools, I have noticed that sysPass is trying to call page resources from the root directory (https://www.example.com/index.php) instead of /syspass/ directory https://www.example.com/syspass/index.php), causing multiple 404 errors.

Is that something wrong with my setup?

**Screenshots**
![image](https://user-images.githubusercontent.com/15827925/52100871-7e8c0480-262d-11e9-8879-945bead16fde.png)

![image](https://user-images.githubusercontent.com/15827925/52103127-4d650180-2638-11e9-8e0f-3e96f54e146e.png)

**Platform (please complete the following information):**
 - OS: Debian
 - OS Version 9

Many thanks.

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply...

It seems that your web server isn't handling how to work with URLs without a file, that is default directory index.

Regards
