### ISSUE TITLE
Expiration date removed from account?

### ISSUE THREAD

**Issue by DDH112** [nuxsmin/sysPass#1222]
**sysPass Version**
3.0 (304.19012601) 
Config: 300.18111001 
App: 300.18072902 
DB: 300.18111901

**Describe the bug**
V2 used to contain a 'password expiry' field with a timestamp. V3 does not seems to have this field. You can however still search on expired accounts. Where is this information visible in v3?

**To Reproduce**
1. Go to home page
2. Click on an account
3. Check details

**Expected behavior**
Way to check/update paswoord expiry field.

**Screenshots**

**Event log**
Some lines from `syspass.log` file (within `config` directory) and sysPass event log that were logged when the error happened.

**Platform (please complete the following information):**
 - OS: Windows 7
 - OS Version
 - Browser: Chrome

**Additional context**

**Comment by DDH112** [comment]
Found the answer. Had to activate the general setting.

**Comment by DDH112** [comment]
Still some issue:

1. activated password expiration under 'Configuration' > 'Accounts'
2. Created a new account, was able to set/modify 'expiration time'. Save the new account
3. Re-open the created account
Password expiration field no longer visible within the account?

How do we see the password expiration time once it is set?

**Comment by nuxsmin** [comment]
Hello, it needs to be set on password updating view, since it's related to the password itself.

Regards

**Comment by DDH112** [comment]
Thank you nuxsmin to clarify this. A couple follow-up questions as I could not find anything about this in the documentation. 

What is the result of configuring a password expiration time? Only that you can can retrieve it when searching for "is:expired"? Or does reaching the expiration time for an account trigger any other actions?

Can you configure something for the actual users of syspass as well, to guarantee their passwords for accessing syspass comply with specific policies & they are obliged to change they password if the period in the password expiration time has passed?

**Comment by nuxsmin** [comment]
> What is the result of configuring a password expiration time? Only that you can can retrieve it when searching for "is:expired"? Or does reaching the expiration time for an account trigger any other actions?

It will only mark every expired account on search list, and there won't be any further action with them. In future releases some kind of notification could be performed, but PHP's execution way (in-time parsing) makes this hard to implement.

Regards.

**Comment by DDH112** [comment]
Ok, thx. Question resolved for me.
