### ISSUE TITLE
Standard password complexity not followed

### ISSUE THREAD

**Issue by DDH112** [nuxsmin/sysPass#1226]
**sysPass Version**
3.0 (304.19012601)

**Describe the bug**
As far as I understood correctly, syspass generates 12 character passwords containing numbers, letters (uppercase, lowercase), special character.
Syspass is able to generate passwords, but when using this functionality it sometimes generates new passwords without numbers:
$#eL)mAq(aQu
kX,s¿_mKS^v>

**To Reproduce**
1. Create new account
2. Check complexity password if requires 12 characters, uppercase, lowercase, numbers, letters, special character
3. Generate new password few times
4. Check if all contain a number

**Comment by DDH112** [comment]
Positive side-note:
Just tested to make sure: when you make it mandatory to comply, syspass will complain about the generated password not containing numbers :)

**Comment by nuxsmin** [comment]
Hello, this issue has been solved in latest release (not released yet).

Regards
