### ISSUE TITLE
csv account import error round #2

### ISSUE THREAD

**Issue by hoboristi** [nuxsmin/sysPass#1227]
**sysPass Version**
3.0 (304.19012601)
Config: 304.19012601 
App: 304.19012601 
DB: 304.19012601
**Describe the bug**
The same error presents like we have at [#1211](https://github.com/nuxsmin/sysPass/issues/1211)

**To Reproduce**
Tried to import the same csv (500 lines) as earlier.

**Expected behavior**
Fails with the same error. Imported amount of accounts are the same (491 out of 500)

**Event log**
2019-01-31 14:48:19 [EXCEPTION] [N/A] Category Id not set. Unable to import account.
#0 /var/www/syspass/lib/SP/Services/Import/CsvImportBase.php(154): SP\Services\Import\CsvImportBase->addAccount(Object(SP\Services\Account\AccountRequest))
#1 /var/www/syspass/lib/SP/Services/Import/CsvImport.php(53): SP\Services\Import\CsvImportBase->processAccounts()
#2 /var/www/syspass/lib/SP/Services/Import/ImportService.php(73): SP\Services\Import\CsvImport->doImport()
#3 [internal function]: SP\Services\Import\ImportService->SP\Services\Import\{closure}()
#4 /var/www/syspass/lib/SP/Services/Service.php(97): Closure->call(Object(SP\Services\Import\ImportService))
#5 /var/www/syspass/lib/SP/Services/Import/ImportService.php(75): SP\Services\Service->transactionAware(Object(Closure))
#6 /var/www/syspass/app/modules/web/Controllers/ConfigImportController.php(75): SP\Services\Import\ImportService->doImport(Object(SP\Services\Import\ImportParams), Object(SP\Services\Import\FileImport))
#7 [internal function]: SP\Modules\Web\Controllers\ConfigImportController->importAction()
#8 /var/www/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#9 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollectio
n), Array)
#10 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Kle
in), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/syspass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#13 /var/www/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#14 /var/www/syspass/index.php(28): require('/var/www/syspas...')
#15 {main}

**Platform (please complete the following information):**

- OS: Linux
- Centos 7
- Browser:Firefox, Chrome

**Comment by nuxsmin** [comment]
Hello, could you set the `exception` event category in events list?. It should log some info about the processing line when the exception is thrown.

![imagen](https://user-images.githubusercontent.com/1775774/53304947-83825380-387b-11e9-92ec-eca0201051d2.png)

Regards
