### ISSUE TITLE
Backup restore error

### ISSUE THREAD

**Issue by hoboristi** [nuxsmin/sysPass#1228]
**sysPass Version**
3.0 (304.19012601)
Config: 304.19012601
App: 304.19012601
DB: 304.19012601

**Describe the bug**
Made a backup with GUI, and tried to restore mysql afterwards, and got this error:

[root]# mysql syspass -p  < /tmp/sysPass_db-bfb2d60fd0dfd42c0de183b7937ab5f757274713.sql 
Enter password: 
ERROR 1050 (42S01) at line 545: Table 'account_data_v' already exists

**To Reproduce**
See at description.

**Expected behavior**
Load db backup without error :)

**Event log**
2019-02-04 08:43:22 [EXCEPTION] [N/A] User does not exist
#0 /var/www/syspass/lib/SP/Providers/Auth/Database/Database.php(108): SP\Services\User\UserService->getByLogin('test')
#1 /var/www/syspass/lib/SP/Providers/Auth/Database/Database.php(82): SP\Providers\Auth\Database\Database->authUser()
#2 /var/www/syspass/lib/SP/Providers/Auth/AuthProvider.php(167): SP\Providers\Auth\Database\Database->authenticate(Object(SP\DataModel\UserLoginData))
#3 /var/www/syspass/lib/SP/Providers/Auth/AuthProvider.php(93): SP\Providers\Auth\AuthProvider->authDatabase()
#4 /var/www/syspass/lib/SP/Services/Auth/LoginService.php(146): SP\Providers\Auth\AuthProvider->doAuth(Object(SP\DataModel\UserLoginData))
#5 /var/www/syspass/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#6 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#7 /var/www/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/syspass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/syspass/index.php(28): require('/var/www/syspas...')
#14 {main}
2019-02-04 08:43:22 [EXCEPTION] [N/A] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`syspass`.`User`, CONSTRAINT `fk_User_userGroupId` FOREIGN KEY (`userGroupId`) REFERENCES `UserGroup` (`id`))
#0 /var/www/syspass/lib/SP/Storage/Database/Database.php(234): PDOStatement->execute()
#1 /var/www/syspass/lib/SP/Storage/Database/Database.php(174): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))
#2 /var/www/syspass/lib/SP/Repositories/User/UserRepository.php(476): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))
#3 /var/www/syspass/lib/SP/Services/User/UserService.php(257): SP\Repositories\User\UserRepository->create(Object(SP\DataModel\UserData))
#4 /var/www/syspass/lib/SP/Services/User/UserService.php(242): SP\Services\User\UserService->create(Object(SP\DataModel\UserData))
#5 /var/www/syspass/lib/SP/Services/Auth/LoginService.php(579): SP\Services\User\UserService->createOnLogin(Object(SP\Services\User\UserLoginRequest))
#6 /var/www/syspass/lib/SP/Services/Auth/LoginService.php(152): SP\Services\Auth\LoginService->authLdap(Object(SP\Providers\Auth\Ldap\LdapAuthData))
#7 /var/www/syspass/app/modules/web/Controllers/LoginController.php(62): SP\Services\Auth\LoginService->doLogin()
#8 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#9 /var/www/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#10 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)

**Platform (please complete the following information):**

- OS: Linux
- Centos 7
- Browser:Firefox, Chrome

**Comment by nuxsmin** [comment]
Hello, did you remove the database before importing?

Regards
