### ISSUE TITLE
Upgrading from v1.1.2.24 to v3.0.4

### ISSUE THREAD

**Issue by alexrainbowcookies** [nuxsmin/sysPass#1229]
Hello, 

I'm trying to upgrade SysPass from version 1.1.2 to version 3.0.4 after a long time it hasn't been upgraded - by installing SysPass on a new machine, running Ubuntu Server 18.04 and importing the old database.

What are the procedures to import the DB and configuration from the old machine to work with version 3.0.4?

**Comment by nuxsmin** [comment]
Hello, for upgrading from v1 you will need to upgrade to v2.1 on first step and then to v3.

https://doc.syspass.org/en/3.0/updating/v2_1.html

Regards.

**Comment by alexrainbowcookies** [comment]
If I install php5.6 with all of the other dependencies for 7.2, should it work when the versions mismatch between those packages?

**Comment by deajan** [comment]
sysPass 2.1 and 3.0 are both php 7.0 compatible, that might be the first way to go.
