### ISSUE TITLE
Upgrade from 3.0.0 to 3.0.04

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [nuxsmin/sysPass#1230]
**sysPass Version**
3.0 (300.18122601) 

**Describe the question**
- How do I do a minor upgrade from 3.0.0 to 3.0.4?
- The "upgradeKey" value is empty. Can I just set a upgrade key? Can SysPass create it for me? How does that work?

**Platform (please complete the following information):**
 - OS: Debian GNU/Linux 
 - OS Version: 9.7 (stretch)
 - Browser: Firefox // bash

**Comment by hoboristi** [comment]
has the same "issue" like yours, cant find out how to minor upgrade :(

**Comment by hoboristi** [comment]
> Hello
> 
> > How do I do a minor upgrade from 3.0.0 to 3.0.4?
> 
> You need to update the source code by replacing the old one, and then it will generate an upgrade key. After that, point your browser to sysPass URL and the upgrade process will ask for the upgrade key.
> 
> Regards

Hi, sry for answering instead of the topic owner; if I had repalced the code; it won't generate code, just insert the <update> tags leaving them empty..

**Comment by nuxsmin** [comment]
Hi @hoboristi

if you're running a version greater than 300.18111901 it won't require any DB upgrade, just replacing the code will do the trick.

**Comment by hoboristi** [comment]
> Hi @hoboristi
> 
> if you're running a version greater than 300.18111901 it won't require any DB upgrade, just replacing the code will do the trick.

Thanks for the answer, @nuxsmin :) :+1:

**Comment by cRaZy-bisCuiT** [comment]
Hi @nuxsmin,

I'm not really sure if I got you right. Just by replacing the source code I will obviously not get an upgrade key. 

So this is how I do understand the procedure. Please correct me if I'm wrong or confirm it:

1. move the "syspass" directory to "syspass.backup_xxx"
2. Download the current release and extract it to "syspass" directory
3. Change the permissions accordingly:
`chown apache -R /var/www/html/syspass`
`chmod 750 /var/www/html/syspass/app/config /var/www/html/syspass/app/backup`
4. Generate the update key by executing:
`php composer.phar install --no-dev`
... Is this correct?
5. Access https://IP_OR_SERVER_ADDRESS/syspass/index.php and insert the upgrade key.

Thanks for your help.

**Comment by nuxsmin** [comment]
@cRaZy-bisCuiT Hi, the 4 step isn't needed. sysPass will generate the upgrade key automatically, since it will detect is any upgrade is needed. Be aware that only database upgrades need the key.

**Comment by cRaZy-bisCuiT** [comment]
Thanks, I guess now I got you right! :)

**Comment by cRaZy-bisCuiT** [comment]
@nuxsmin Actually I did the upgrade process as described. Unfortunately I could not access SysPass after the update. The directory...

`/syspass/vendor`

...was missing. 

So my question is: Which directories do I need to restore from my backup after extracting the new source code and change the groups and permissions?

Or am I still missing a step for a minor version upgrade from version 300.18111901 to the recent one?

**Comment by alexebner** [comment]
I have updated from 3.0.4 to 3.0.5.
Now i Have this Versions.


3.0 (305.19020701)
Config: 304.19012601
App: 304.19012601
DB: 304.19012601 


Is that ok or does i have missed something ?

**Comment by cRaZy-bisCuiT** [comment]
Heya...

So finally I did the update! What I did was extracting the source and copying it over to the original installation, replacing existing files and changing permissions afterwards:

0. Stop apache2.service and mariadb.service

1.  copy over the files
`cp ./NEW_SOURCODE/* ./syspass -R`

2. change the permissions (insert the user which should one the files
`chown www-data /var/www/html/syspass/app/config /var/www/html/syspass/app/backup /var/www/html/syspass/app/cache
chown -R www-data /var/www/html/syspass/app/config /var/www/html/syspass/app/backup /var/www/html/syspass/app/cache`

3. Start apache2.service


Thanks for your help!

**Comment by nuxsmin** [comment]
@alexebner that's ok, since version numbers will bump whenever an upgrade is performed but upgrading the code doesn't mean that the data structures need to be upgraded.
