### ISSUE TITLE
View Password, misinterpretting patterns

### ISSUE THREAD

**Issue by Yotouille** [nuxsmin/sysPass#1231]
**sysPass Version**
3.0 (304.19012601)
Config: 300.18112501
App: 300.18072902
DB: 300.18111901 

**Describe the bug**
The function "View Password" do not show the true password if it find a particular pattern. (It tries to interpret something, I think)

**To Reproduce**
It is reproducible on demo.syspass.org
1. Create this new password: `$Soi,,,,,,,,,,,,,wg`
2. Click on 'View Password' (opened-lock icon)
3. You should see: `$Soi,,,,,&com ma;,,,,,,&comm a;wg`
(with a line return between the first 2 `m`)

**Event log**
There seems to be no event related to this.

**Additional context**
I have cut down the password complexity trying to clear up things, obviously there is something syspass don't like with (long) passwords with `$Soi` inside.

**Careful**: in that case the function **"Copy password"** from the _view window_ will not work ! Only the function **"Copy password to clipboard"** (clipboard icon), without showing the password, will give you the real password !

**Comment by Yotouille** [comment]
It seems to be more complex than `$Soi` pattern, I could reproduce the behavior with this password:
`#_pi,,,,,,,,,,,,,wg`
Giving...
`#_pi,,,,,undefined,,,,,,,&undefinedcomma;wg`

Whatever... Something gets wrongly interpreted.

**Comment by ortizleo** [comment]
I have this problem here too.

**Comment by ortizleo** [comment]
Hello.
This problem still ocurr in some cases, using last release.

Example: I have created this password: P$L#P@ss$Word@#2019$
When I show the password in sysPass (unlock icon), it show: P$L#P@ss$Word@&num ;2019$

You can check the problem in demo, using the accounts "Acc to test #1231" and "
Acc2 to test #1231"

**Comment by Altes** [comment]
I'm having the same issue, mainly with **$ +** characters
