### ISSUE TITLE
Impossible to connect with the database

### ISSUE THREAD

**Issue by PPJunior2** [nuxsmin/sysPass#1233]
sysPass Version : 3.0

Hello, 
I had to install mysql-server. 
All installation on debian was proceeding as planned. 
Then, when I try to create the database with SysPass, I have this message : 
![image](https://user-images.githubusercontent.com/47351854/52268813-b43a3180-293c-11e9-84af-b668a392d4f9.png)

I have decided to create a user to give all privileges. 
![image](https://user-images.githubusercontent.com/47351854/52268966-2743a800-293d-11e9-93ff-05a60aaeac97.png)
and ... 
![image](https://user-images.githubusercontent.com/47351854/52269023-4b06ee00-293d-11e9-9bd6-5fadf9710d57.png)

I have also create de database named 'syspass' but there is a issue, somthing like 'Database already exists, delete it and retry'

![image](https://user-images.githubusercontent.com/47351854/52268585-2fe7ae80-293c-11e9-952a-80057d4d19e3.png)
Here is a screen of my last step. I've tried with differents username and databases name. 

Thanks in advance for your help
Nicolas

 - OS: Debian 9 on VMware Workstation 15
 - Browser Firefox

**Comment by nuxsmin** [comment]
Hello, be aware that "localhost" connection is done through unix socket, so some restrictions might be applied. In order to use your own database, you need to switch the hosting mode on, since in normal mode it will try to create "syspass" database and a random user for connecting.

Regards
