### ISSUE TITLE
LDAP Issue - Trying to contact domain AD shows error "Invalid credentials (49)"

### ISSUE THREAD

**Issue by alexrainbowcookies** [nuxsmin/sysPass#1237]
**sysPass Version**
3.0 (304.19012601) 
Config: 304.19012601 
App: 304.19012601 
DB: 304.19012601

**Describe the question**
While trying to communicate with LDAP in Active Directory (in a Domain) and inputting the user and password in the LDAP settings - throws an error "Connection error (BIND), Invalid credentials (49)"

The user and password is confirmed to be correct and appears correct in the `config.xml`.

I've also configured the proxy in Ubuntu and in the Syspass settings to the correct values and checked that the LDAP request is indeed being allowed through the firewall.

**Screenshots**
![syspasslog](https://user-images.githubusercontent.com/26306266/52399060-bc70a900-2ac3-11e9-80aa-51aeb09ed3d7.PNG)
![syspassldap](https://user-images.githubusercontent.com/26306266/52399062-bc70a900-2ac3-11e9-9bdc-ed1052596e1a.PNG)

**Platform (please complete the following information):**
 - OS: Ubuntu Server 18.04

**Comment by nuxsmin** [comment]
Hello, it might be related to the LDAP connection security level, since ADS requires to SSL/TLS for binding.

Regards

**Comment by nblount** [comment]
We are seeing this issue as well on version 3.0.5 and 2.1, we get an error BIND error 49. Have written a simple piece of php code that connects and binds which works fine but the code in sysPass will not bind using exactly the same details. We have tried with and without TLS and with different accounts, it is always the same. This did work at some point but something has changed in the last few months causing it to stop. If it helps it works on a machine using PHP 5.6 and doesn't work on two machines running PHP 7.0.

This is the code we have run from the same machines as sysPass which appears to work fine:

<?php

// LDAP variables
$ldaphost = "ldaps://AD.test.local";  // your ldap servers
$ldapport = 636;                 // your ldap server's port number
$ldaprdn  = 'CN=Service LDAP Read,OU=Services,DC=test,DC=local';     // ldap rdn or dn
$ldappass = 'password';  // associated password

// Connecting to LDAP
$ldapconn = ldap_connect($ldaphost, $ldapport)
          or die("Could not connect to $ldaphost");

if ($ldapconn) {

    // binding to ldap server
    $ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);

    // verify binding
    if ($ldapbind) {
        echo "LDAP bind successful...";
    } else {
        echo "LDAP bind failed...";
    }
}

?>

**Comment by nblount** [comment]
`<?php

// LDAP variables
$ldaphost = "ldaps://AD.test.local";  // your ldap servers
$ldapport = 636;                 // your ldap server's port number
$ldaprdn  = 'CN=Service LDAP Read,OU=Services,DC=test,DC=local';     // ldap rdn or dn
$ldappass = 'password';  // associated password

// Connecting to LDAP
$ldapconn = ldap_connect($ldaphost, $ldapport)
          or die("Could not connect to $ldaphost");

if ($ldapconn) {

    // binding to ldap server
    $ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);

    // verify binding
    if ($ldapbind) {
        echo "LDAP bind successful...";
    } else {
        echo "LDAP bind failed...";
    }
}

?>
`

**Comment by nblount** [comment]
Think we have figured out that why we get the error on test. Before select the check option you have to enter the password, if you don't the system just sends 3 dots as a password. We also found that limiting logins to a specific group was not working and also breaking the test function so had to be removed.

**Comment by stuartz** [comment]
Thank you @nblount.  Had a terrible time connecting to LDAP and checking.  Once we put the password in without saving, we were able to connect.  Then we had to remove groups ldap config and **only** put the group name in the field to get objects back on the check.
