### ISSUE TITLE
Behaviour of permissions on private accounts

### ISSUE THREAD

**Issue by javierlm** [nuxsmin/sysPass#1238]
**sysPass Version**
3.0 (304.19012601) 

**Describe the question**
When I create a private account with any user, profile is applied to this new private account too. So, if the user has a restricted profile assigned, the user can't view, edit, or delete his own account. Is this the expected behaviour?

I think that my own private accounts must be accesible with my user, because I'm the only user that can have this permissions assigned.
To be able to edit my private accounts, I need to modify the assigned profile to allow editing accounts.

**Screenshots**
![screenshot_2019-02-07 syspass systems password manager](https://user-images.githubusercontent.com/34691743/52402994-92b48380-2abd-11e9-9812-23fbc5d438c1.png)
Once the account is created, it displays the following error:
![screenshot_2019-02-07 syspass systems password manager 1](https://user-images.githubusercontent.com/34691743/52403058-bb3c7d80-2abd-11e9-9fcd-1c704fa16642.png)
Pressing the back button...
![screenshot_2019-02-07 syspass systems password manager 2](https://user-images.githubusercontent.com/34691743/52403100-db6c3c80-2abd-11e9-9197-8d02c881c387.png)
![screenshot_2019-02-07 syspass systems password manager 3](https://user-images.githubusercontent.com/34691743/52403443-a3b1c480-2abe-11e9-989a-8f516f90fed4.png)

**SysPass Log**

`
2019-02-07 09:44:31 [EXCEPTION] [N/A] You don't have permission to access this page
#0 /var/www/html/sysPass/app/modules/web/Controllers/Helpers/Account/AccountHelper.php(121): SP\Modules\Web\Controllers\Helpers\Account\AccountHelper->checkActionAccess()
#1 /var/www/html/sysPass/app/modules/web/Controllers/AccountController.php(387): SP\Modules\Web\Controllers\Helpers\Account\AccountHelper->setViewForAccount(Object(SP\DataModel\Dto\AccountDetailsResponse), 5)
#2 [internal function]: SP\Modules\Web\Controllers\AccountController->editAction(709)
#3 /var/www/html/sysPass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')
#10 {main}
2019-02-07 09:44:49 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-02-07 09:44:50 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-02-07 09:44:50 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-02-07 09:45:47 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-02-07 09:45:48 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-02-07 09:45:49 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
2019-02-07 09:45:49 [EXCEPTION] [N/A] Invalid Action
#0 /var/www/html/sysPass/app/modules/web/Controllers/AccountController.php(278): SP\Modules\Web\Controllers\ControllerBase->checkSecurityToken('f9393f62487d4b5...', Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\AccountController->createAction()
#2 /var/www/html/sysPass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')
#9 {main}
`

**Comment by nuxsmin** [comment]
Hello, does the user have edit permission on the profile?

**Comment by javierlm** [comment]
> Hello, does the user have edit permission on the profile?

The user is the owner of the private profile. It seems that the profile is applied to all accounts, included the private ones. That's not an error, because this behaviour means that permissions and profiles are working properly. But in a functional point of view, I think that profiles musn't be applied to private accounts (private accounts for an specific user). This account is "personal" for this user, and not having permissions to make changes doesn't make sense. The solution is change the profile of the user, but if I do that, it will change permissions on all accounts.

For instance, you have an user with only read permissions in all accounts. The user creates a private account, and the "only read" profile is applied to it. The user can't change the information for it, despite it's the owner and the account is a private one, only visible for that user. And if the user wants to delete the private account, it couldn't do that. The account will stay in the application for eternity, even the admin couldn't delete it.

**Comment by nuxsmin** [comment]
Profiles are applied to users, think on them as roles, so every user that is bound to a profile can perform actions enabled on the profile.

Private accounts are special accounts that cannot be visible by administrators, but no other privileges are granted.

In order to restrict read/write permissions, please use the accounts' permissions tab.

Regards
