### ISSUE TITLE
Call for Translations

### ISSUE THREAD

**Issue by nuxsmin** [nuxsmin/sysPass#124]
Hi, for the upcoming sysPass 1.2 release, we need some help to maintain the translations to the following languages:
- German
- French
- Russian
- Hungarian

Any help would be appreciated and if you are able to translate to another language, would be great ;)

Big thanks!!

**Comment by Goatmaster** [comment]
I can help you with the german translation !

**Comment by nuxsmin** [comment]
Great!! Let me finish the implementation of new functionalities and I'll send you the strings to translate.

Actually there are some german translators so I can split the strings to make it more affordable for you.

Thanks for your support!

**Comment by Goatmaster** [comment]
Cool, I am glad to help!

**Comment by Eztharia** [comment]
+1 For French

**Comment by lemonsquash** [comment]
If you need any more help with the german translation, just let me know...

**Comment by nuxsmin** [comment]
Big thanks for your support!

I'll be back in short with strings for translations

**Comment by nuxsmin** [comment]
Hi!!, I've just finished coding a tool for collaborative translations (mostly in the cloud are paid ones), so you can start translating sysPass at http://translate.syspass.org

If you find any bug or need to add your language, please tell me :)

Again, thank you for your support!!

**Comment by wagnst** [comment]
Provided some german translation as well...

**Comment by nuxsmin** [comment]
Big thanks for your support, it's very useful and comfortable to have the app translated to your own language and it helps others to use it without any language knowledge than its own.

**Comment by prybak** [comment]
You do not need it atm but I can help you with polish translation :).

**Comment by nuxsmin** [comment]
Sure @prybak it will be very useful for all those polish folks

I've added the Polish section at http://translate.syspass.org/index.php?translate-sel=po_PO

If you feel more comfortable by editing it in poeditor, feel free to send me the '.po' file

**Comment by sikas89** [comment]
@nuxsmin what about the Arabic, I can help with that

**Comment by nuxsmin** [comment]
Great sikas89!, let me add it to the translation page. Which variant do you prefer?

**Comment by sikas89** [comment]
@nuxsmin Classic-Arabic .. This would be best as it will be valid for nearly all the Arab world

**Comment by nlmaca** [comment]
can you add the Dutch language nuxsmin? i might can help you with that. or is there a way how i can add it to the 1.2 version?

**Comment by nuxsmin** [comment]
Did you mean German?...if so, it's already added and fully translated. Thanks for your offering!!

**Comment by nuxsmin** [comment]
@sikas89 ok I will add it shortly

**Comment by nlmaca** [comment]
@nuxsmin. no not german, Dutch (im from the Netherlands).

**Comment by nuxsmin** [comment]
Wow ...sorry....it will be available for translation shortly.

**Comment by nuxsmin** [comment]
Hi there @nimaca and @sikas89 

I've already enabled both languages at the translation page:http://translate.syspass.org

**Comment by Wrightie** [comment]
I'm working at the Italian translation at http://translate.syspass.org/index.php?translate-sel=it_IT
I found an error on a translation, but I can't review it as I can't edit the text.
Can you help me in this?

**Comment by Wrightie** [comment]
By the way, to correctly translate "customer" (which, in Italian, is a synonym of "client") I need to know more about what's the really meaning you want to give to this word, or some other English synonyms that might be applied.

**Comment by nuxsmin** [comment]
Hi @wrightie, good news that you want to translate sysPass into Italian. The review  feature is to avoid an intentional modification (or deletion) of the translated strings, so I frequently take a look to enable editing those checked strings. Sorry for the inconvenience.

You can go on translating and let me know when you're done to enable them.

I know that the context is quite important when doing translations but it's a bit difficult to show it when it mostly needs a visual context (an app it's quite different from a book), so you will need to make some tweaks after you have finished the translation. There is another way to perform the translation, but it needs some knowledge on gettext tools like poeditor and it won't either provides a context, it would show filenames and line numbers instead (not very useful either).

Thanks for your support!!

**Comment by sikas89** [comment]
@nuxsmin where is the Arabic? seems you have forgotten me

**Comment by nuxsmin** [comment]
@sikas89 you can select it on the language selector button at translate.syspass.org

**Comment by nlmaca** [comment]
is there some way we can test the translation?. im almost done with the dutch one, but translating is one thing, when you see it back in the application it can be the wrong translation. So to be able to test the translation would be a nice thing for testing. Is that possible?

**Comment by nuxsmin** [comment]
Sure, let me do some stuff to get it suited for gettext format.

**Comment by henriquecpa** [comment]
good afternoon ,
What do I can do to assist in the translation into Portuguese / Brazil ?

**Comment by nuxsmin** [comment]
Good afternoon @henriquecpa 

let me enable that locale (pt_BR) in the translation website: http://translate.syspass.org

**Comment by henriquecpa** [comment]
good afternoon
I can not make any changes to the Portuguese / Brazil, because I'm not
performing editions.

2016-08-30 16:49 GMT-03:00 nuxsmin <notifications@github.com>:

**Comment by nuxsmin** [comment]
Sorry, it'll be available shortly. Thanks!

**Comment by henriquecpa** [comment]
thank you, I thank you for the tool, very useful

2016-09-01 13:43 GMT-03:00 nuxsmin <notifications@github.com>:

**Comment by nuxsmin** [comment]
It's just available ;)

**Comment by tobleronealfen** [comment]
I'm up for danish translation

**Comment by nuxsmin** [comment]
Doesn't matter @tobleronealfen 

Thanks for your offering!

**Comment by nuxsmin** [comment]
Hi there:

Recently, sysPass translation service has been moved to POEditor, a professional service which would help us to get it easily translated to many languages.

Many thanks to POEditor for offering this great service to the Open Source Community.

Translations are welcome!!...https://poeditor.com/join/project/fmlsBuugyv

**Comment by stvorenje** [comment]
I have filled cca 600 translations for Croatian. Could you please move it to poeditor?

**Comment by nuxsmin** [comment]
Hi @stvorenje,

sure, you can send me them to nuxsmin@syspass.org

Do they have any special format?

Thanks!

**Comment by nuxsmin** [comment]
Sure, don't worry about it, they are saved, but I've missed to import them to poeditor... I'll upload them shortly.

Sorry for the inconvenience

**Comment by nuxsmin** [comment]
Hi @stvorenje , so sorry for the late response, but I've been very busy in the latest days. Finally I've imported the Croatian translation into POEditor, so you'd need to request an access to the language.

Kind regards

**Comment by stvorenje** [comment]
Thank you, I will try to finish my translations until the end of the week.

Best regards,

Mladen

**Comment by wseredynski** [comment]
@nuxsmin Polish is 94% ready, could you please add it to the project?
Cheers

**Comment by nuxsmin** [comment]
Sure @wseredynski I've just pushed the polish translation to the devel branch.

**Comment by wseredynski** [comment]
@nuxsmin Thanks, just one minor thing - text on language selection dropdown should read 'polski' instead of 'polskie'

**Comment by nuxsmin** [comment]
@wseredynski Upsss...sorry. I've just fixed it!

**Comment by execcr** [comment]
hello i've asked permission on poeditor for the italian translation project. But it still pending approvation.

**Comment by nuxsmin** [comment]
@execcr sorry for the delay, I missed the approving email

You're now approved ;)

**Comment by execcr** [comment]
Thank you nuxsmin. Today i managed to get it to 88%. Have i a way to test it on local? I've tried to download .po e .mo files to my /var/www/html/syspass/inc/locales/it_IT/LC_MESSAGES folder, overwriting existin files, but i think it is not enough.
BTW, my ubuntu 16.04 instllation is in it_IT, but under Configuration Application i get only en_EN.UTF8. On /etc/default/locales i have it_IT.UTF8

**Comment by execcr** [comment]
nevermind added Italiano to Language.class.php files
all is working good, i'll test my translation and changed them accordingly.
thanks!

**Comment by nuxsmin** [comment]
@execcr Thanks for your contribution!, Italian translation isn't listed on available languages, so you would need to edit this file show it:
https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Core/Language.class.php#L171
Regards
