### ISSUE TITLE
Error: Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by ortizleo** [nuxsmin/sysPass#1240]
Hello.

We have this error using the application: 
`SyntaxError: Unexpected token A in JSON at position 0`

**To Reproduce**

1. Enter in some account
2. Click on "Edit account password"

**sysPass Version**
3.0 (304.19012601) 
Config: 300.18111001 
App: 303.19012402 
DB: 300.18111901

**System**
MariaDB 5.60
PHP 7.2.12
Apache 2.4
Centos 7.6

Error attached.
![image](https://user-images.githubusercontent.com/17042298/52434901-9ebd3700-2af7-11e9-81b6-ffb2f803cff0.png)

**Comment by nuxsmin** [comment]
Hello, did you upgrade the plugin to the latest version?

Regards

**Comment by ortizleo** [comment]
Hello.
Yes, version 2.0.1
Compatible version: 3.0

**Comment by nuxsmin** [comment]
Hello, this issue has been solved in latest plugin's version. Please, this kind of issues need to be opened on plugin's repository, since tracking is more effective.

Thanks for the feedback!
