### ISSUE TITLE
Upgrade Syspass 2.1 to 3.0 - Hosting mode

### ISSUE THREAD

**Issue by Bastaxi** [nuxsmin/sysPass#1242]
**sysPass Version**
2.1

**Describe the question**
Hello, I have the question for the updating syspass 2.1 to 3.0 in hosting mode.

To update Syspass, I need to execute some terminal commands but I don't access SSH on my web hosting.

So, do you have a solution or documentation to update syspass in hosting mode ? 

Thank you in advance.

**Comment by nuxsmin** [comment]
Hello, sysPass binaries can be uploaded to any hosting provider, but you need to download its dependencies (using composer) before uploading. This way was followed for setting up the demo website, since no SSH access is available.

Regards
