### ISSUE TITLE
Customizing color scheme

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1243]
Hello Ruben,

I would like to move from the indigo color scheme to another on sysPass v3.
I've found the sass tool in order to generate the material files, but can't find the source scss in /app/modules/web/themes/material-blue/css

Would you mind giving me a clue please ? I'm quite lost.

Best regards.

**Comment by nuxsmin** [comment]
Hello Orsiris, unfortunately there aren't such sass files because MDL does not provide them. You can customize the colors on this site https://getmdl.io/customize/index.html and download the minimized `css` file.

Some other components like select boxes, tags, etc. are customized, so you only need to change some color variables within `_base.scss` file and then build all `scss` files again.

Best regards.

**Comment by deajan** [comment]
Thanks ;)

**Comment by Arash9703** [comment]
Hello, 
Can you please confirm if you succeeded in changing themes via the css index.html file? I still can't change it.
And by the way, I couldn't change the language in French , still searching for the missing package for this.
 
Thanks ;)

![2023-10-04 00_43_24-sysPass __ Systems Password Manager](https://github.com/nuxsmin/sysPass/assets/143269985/8a069cda-babd-442f-921e-25a186e53b9d)

**Comment by deajan** [comment]
Got this css stuff working years ago. Honestly I can't ne bothered to dig into this, I modded the app css file.
I switched from sysPass to something else long ago.

**Comment by Arash9703** [comment]
Thanks , don't you mind if share what alternative you chose over syspass ! 
@deajan

**Comment by deajan** [comment]
Won't talk about other solutions on sysPass's issue page, as I respect Rubén's work (I was actually contributor earlier).
Send me a quick mail to ozy [at ] netpower dot fr and I'll happily explain what I am using. And yes, it's fully LDAP compatible.

**Comment by Arash9703** [comment]
Oh ,totally agree i apologize for this. Same here hats off for the works of @ruben.
