### ISSUE TITLE
Encoding issue for event log

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1244]
**sysPass Version**
3.0.5

**Describe the bug**
When reading the security / audit logs, French accents get bad encoding, ie ```Utilisateur vÃ©rifiÃ© dans le groupe``` where ```Ã© == é```.

**To Reproduce**
1. Set language to French
2. Login in with a user belonging to a group / or log off
3. Login as admin
4. Goto Security & audit, read logs

**Screenshots**
![image](https://user-images.githubusercontent.com/4681318/52623165-f79c1f00-2eab-11e9-9072-87762b6e5b76.png)

**Event log**
Nothing strange in syspass.log

**Platform (please complete the following information):**
 - CentOS 7 x64 w/ apache 2.4 / php 7.2
 - Opera 57 / Win 10 x64

I think the audit log is the only place in sysPass where this happens.
All other French UI strings are well encoded.

**Comment by nuxsmin** [comment]
Hello, it's a known issue when migration from v2, since events were incorrectly encoded. I tried to tweak the upgrade process, but it didn't work.

Regards

**Comment by deajan** [comment]
Indeed, sorry, for a moment I thought these were recent logs :)
