### ISSUE TITLE
2FA Recovery code sent by e-mail is not working

### ISSUE THREAD

**Issue by ortizleo** [nuxsmin/sysPass#1246]
Hello.

Recovery codes for 2FA sent by email is not working and an error ocurr when we try to get a recovery code. The problem only ocurr with e-mail recovery codes, when we get some code from user preferences, works.

**sysPass Version**
3.0 (305.19020701) 
Config: 300.18112501 
App: 303.19012402 
DB: 300.18111901

**To Reproduce**
1. Log in
2. Mark "Forgot My Code" and click in "Log in"
At this time a "not found" error occur, trying to access /undefined page (print attached).
3. Look recovery code at e-mail
4. Log again
5. Try to use the code but it not work with a message "wrong code" (print attached)

**Platform (please complete the following information):**
Centos 7.6
MariaDB 10.3.12
PHP 7.2.14
Apache 2.4

![image](https://user-images.githubusercontent.com/17042298/52635915-5b294b00-2eb2-11e9-88bf-48146ff0dbd6.png)
![image](https://user-images.githubusercontent.com/17042298/52635965-74ca9280-2eb2-11e9-86d9-e1dbabd78c1c.png)

**Comment by nuxsmin** [comment]
Hello, this issue has been solved in latest plugin release. Please update it.

In order to track plugin related issues, please open the issues on the plugin's repository.

Regards.
