### ISSUE TITLE
Unable to delete Group

### ISSUE THREAD

**Issue by alexebner** [nuxsmin/sysPass#1249]
I have user groups that i can not delete.

i always get the error

Integrity constraint
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`db_syspass`.`AccountHistory`, CONSTRAINT `fk_AccountHistory_userGroupId` FOREIGN KEY (`userGroupId`) REFERENCES `UserGroup` (`id`))

**Comment by nuxsmin** [comment]
Hello, there are some restrictions about deleting related items, because the internal application data need to be linked in order to use as less resources as possible. In this way, the user group id is being used by an account history record, so you will need to delete this record.

Regards
