### ISSUE TITLE
Wrong login

### ISSUE THREAD

**Issue by rrajith** [nuxsmin/sysPass#1251]
3.0 (305.19020701) 
Config: 305.19020701 
App: 305.19020701 
DB: 305.19020701

The following error happens only to some LDAP users and most of them are working. The user is question is listed in the user list.

========================

![syspass3](https://user-images.githubusercontent.com/39121041/52788233-53220480-3086-11e9-9b08-a0dfa967885f.png)
![syspass2](https://user-images.githubusercontent.com/39121041/52788234-53220480-3086-11e9-811e-7f7178b13891.png)
![syspass1](https://user-images.githubusercontent.com/39121041/52788235-53ba9b00-3086-11e9-8876-c7654ba6ede0.png)

**Comment by rrajith** [comment]
We have edited the LdapMsAds.php and did the below changes. The problematic accounts are now working.

-----------
const FILTER_USER_OBJECT = '(&(!(UserAccountControl:1.2.840.113556.1.4.804:=34))(|(objectCategory=person)(objectClass=user)))';

Changed to

const FILTER_USER_OBJECT = '(&(objectCategory=Person)(sAMAccountName=*)(memberOf=CN=syspassusers,CN=Users,DC=example,DC=com))';

------------------------------

**Comment by nuxsmin** [comment]
Hello, it seems that the user wasn't found on LDAP and then it tried to authenticate against database, which returned a `Wrong login` message.

Please be aware that if you imported the users using different a search base it will throw errors when searching for these users using the current one.

Reagrds

**Comment by rrajith** [comment]
Thank you! Let me check it briefly
