### ISSUE TITLE
Problem with importing accounts with XML

### ISSUE THREAD

**Issue by Bastaxi** [nuxsmin/sysPass#1252]
**sysPass Version**
3.0 (305.19020701)
Config: 305.19020701
App: 305.19020701
DB: 305.19020701 

**Describe the bug**
When I try to import accounts from the Import Account tab with a different master password, the importation crashes and generates an error : 

There was an error : Internal Server Error 

Importing an account with the same master password works. 

I use an XML file generated from an older version of syspass (2.1),

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'IMPORT ACCOUNT'
3. And import account with a diffrent master password

**Expected behavior**
I am waiting to import accounts with a differente master password. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47448499/52863721-dd2aa580-3138-11e9-8fa7-ee77a1f492b4.png)

**Event log**
It's empty :/

**Platform (please complete the following information):**
 - Hosting Mode
 - Browser Firefox

Thank you for your help.

**Comment by nuxsmin** [comment]
Hello, please take a look to syspass.log file within config directory, it should contain more info about the error.

With regard to the import, are you importing because a sysPass version upgrade?

Regards

**Comment by Bastaxi** [comment]
Hello, 
The log file is empty :|
![image](https://user-images.githubusercontent.com/47448499/53075199-dd39f500-34ec-11e9-9616-8a6c300d0b60.png)

No I test the functionality in case I need it later. 

Thank you in advance for your help 👍

**Comment by nuxsmin** [comment]
Hello, I'm wondering if the exported file was built encrypting the data.

The `Internal server error` message should log an error in the event log or `syspass.log` file. Could you check them besides the web server log?

Regards
