### ISSUE TITLE
When logging in via LDAP, the required group is not assigned to the user.

### ISSUE THREAD

**Issue by AntonTsaberyaby** [nuxsmin/sysPass#1253]
**sysPass Version**
3.0 (304.19012601) 

**Describe the bug**
As far as I understand, when logging in via LDAP, the user should be assigned his LDAP group and not the default group.

Right now the user gets the default group

**Comment by nuxsmin** [comment]
Hello, this is the correct behaviour indeed, since LDAP groups are not automatically assigned to imported users.

Regards
