### ISSUE TITLE
Syspass: password incorrectly shown/saved

### ISSUE THREAD

**Issue by DDH112** [nuxsmin/sysPass#1257]
**sysPass Version**
3.0 (304.19012601

**Describe the bug**
When setting a password, syspass does not manage to save it correctly

**To Reproduce**
Create account with password SiTèè_V@n_Hèlè8%
Show password > SiTèè_V@n_H&egr ave;lè8%
These does not match!! Luckily we detected this in time...

**Comment by nuxsmin** [comment]
Hello, this issue was fixed in latest release. The passwords are correctly saved but not displayed.

Regards

**Comment by DDH112** [comment]
Which version would this be, because I can reproduce it as well on the demo environment of syspass (version 3.0 (305.19020701))?

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply...Next version will be 3.1 and it isn't released yet. It will be ready shortly.

Regards
