### ISSUE TITLE
File encryption

### ISSUE THREAD

**Issue by stuba** [nuxsmin/sysPass#126]
Hi,

would it be possible to encrypt files? For some cases like VPN some additional information is needed, like shared keys and groups. It would be nice that encryption would work within syspass automatically. Now all files are stored as plain text and for me it sounds a bit scary if files contains any detailed information about account.

I can do pull request if this sounds like useful idea.

**Comment by nuxsmin** [comment]
Hi, this feature is already done in the 1.2 beta release, which provides the ability to add custom fields that are encrypted.

I think that encrypting files would be a performance issue because files used to be too big.

You can try this feature at demo.syspass.org

Kind regards

**Comment by stuba** [comment]
Ok thanks that sound better! Would have been just more complicated change :)
