### ISSUE TITLE
ldap import Internal Server Error

### ISSUE THREAD

**Issue by Idriel** [nuxsmin/sysPass#1260]
While doing Import AD Users and Groups from AD I get error: "Internal Server Error". Partially accounts are imported, not all. Groups not imported. 

I dint see any error in Log about Import. 

in log there is only. 

019-02-21 10:17:25 [EXCEPTION] [N/A] Duplicated user login/email
#0 /var/www/html/sysPass/lib/SP/Services/User/UserService.php(257): SP\Repositories\User\UserRepository->create(Object(SP\DataModel\UserData))
#1 /var/www/html/sysPass/lib/SP/Services/Ldap/LdapImportService.php(226): SP\Services\User\UserService->create(Object(SP\DataModel\UserData))
#2 /var/www/html/sysPass/app/modules/web/Controllers/ConfigLdapController.php(264): SP\Services\Ldap\LdapImportService->importUsers(Object(SP\Providers\Auth\Ldap\LdapParams), Object(SP\Services\Ldap\LdapImportParams))
#3 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->importAction()
#4 /var/www/html/sysPass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/sysPass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#9 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#10 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')
#11 {main}

**Comment by nuxsmin** [comment]
Hello, please fill in the issue template, it will help to analyze the issue.

Regarding the error `Duplicated user login/email`means that an imported user is using the same email, so you'll need to modify any duplicated email before importing the accounts.

Regards
