### ISSUE TITLE
Force local user login. LDAP failed

### ISSUE THREAD

**Issue by Senfti123** [nuxsmin/sysPass#1262]
Hi there!
I tried to set Ldap configuration. I saved it, logged out and tried a Ldap user. Doesn't work. So I wanted to login with "administrator" (local user) but it still says that there is a Ldap failure. I can't login anymore. Is there a way to force login with local user?
In username I tried
 .\administrator
.servername\administrator
But always the Ldap failure appears.

**Comment by nuxsmin** [comment]
Hi,  user's login should be entered without any domain, anyway you can disable the LDAP feature by editing 'config.xml' within'app/config' directory.

Regards

**Comment by nuxsmin** [comment]
Please fill in the issue template, it will help to analyze the issue...
