### ISSUE TITLE
Security issues with direct-link and security tab

### ISSUE THREAD

**Issue by srevol** [nuxsmin/sysPass#1263]
**sysPass Version**
3.0 (305.19020701) 
Config: 300.18112501 
App: 300.18072902 
DB: 300.18111901

**Describe the bug**
When I use the "direct link" ; I can't show 

**To Reproduce**
1. Go to one account
2. Click on 'direct link' -> a new page appear
3. in this new page, if I click on 'view password' , I have an error message "invalid action"

**Expected behavior**
just have the password

**Screenshots**

![image](https://user-images.githubusercontent.com/47856648/53226535-99292a80-367b-11e9-8f26-cb0529f05c7b.png)

**Event log**
2019-02-22 07:32:41 [EXCEPTION] [N/A] Invalid Action
#0 /var/www/html/sysPass/app/modules/web/Controllers/AccountController.php(635): SP\Modules\Web\Controllers\ControllerBase->checkSecurityToken('104cf75f6fc456f...', Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\AccountController->viewPassAction(40, 0)
#2 /var/www/html/sysPass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#4 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#8 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')
#9 {main}

**Platform (please complete the following information):**
 - OS: [LINUX]
 - OS Version : CentOS Linux release 7.6.1810 
 - Browser [Chrome & firefox]

**Additional context**
1°) sometimes ,  after waiting some secondes , I click again on the same "view password" and got the password without error , sometimes I have the same error
2°) If I come back on my initial tab , I can't see the account password , the same message appear.
3°) sometimes, I got the same error message when I want to change the account security

**Comment by nuxsmin** [comment]
Hello, this behaviour is caused by the security token, which is generated on every page view and need to be sent to the server on every action. This prevents unknown requests to the server.

If the security token isn't updated through javascript, it will cause the `Invalid action` exception.

I'm working on a better solution to avoid this "known" issue.

Thanks for the feedback!
