### ISSUE TITLE
Account ownership for not yet activated accounts

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1264]
Hey. I recognized a nasty bug / problem in syspass v3.0.5: 

I created a new user in sysPass which did not login yet. I already created 3 accounts for this user which i added and then assigned to the new user. So i changed the ownership of each account to the new user. But that does not work (it does not store - i see this later when i open up that account again). So I am not able to assign the accounts to him. I think it belongs to the fact the if the user did not login first, no accounts are encrypted with the masterkey. 

Can you please add some method to show up an informative warning to prevent assigning account ownership to non-activated accounts? That might help to better administer this thing.

regards, Mario

**Comment by nuxsmin** [comment]
Hey,  It seems weird, since the master key is the same for all users, so I'm trying to figure out what could be going on.

Newly created users will save (requested) the same master key on their first login, and will be able to display any account (if permission is granted).

Regards

**Comment by vmario89** [comment]
hi,
sorry i forgot to attach log output. I tried it 5 times. There is no warning in user interface, but the following error occures in background:

> [Sat Feb 23 00:29:15.235361 2019] [php7:notice] [pid 19202] [client 85.214.33.238:45662] [EXCEPTION] [N/A] Ung\xc3\xbcltige Aktion\n#0 /var/www/vhosts/pw.domain.tld/app/modules/web/Controllers/AccountController.php(865): SP\\Modules\\Web\\Controllers\\ControllerBase->checkSecurityToken('96034741185c006...', Object(SP\\Http\\Request))\n#1 [internal function]: SP\\Modules\\Web\\Controllers\\AccountController->saveEditAction(176)\n#2 /var/www/vhosts/pw.domain.tld/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)\n#3 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#4 /var/www/vhosts/pw.domain.tld/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#5 /var/www/vhosts/pw.domain.tld/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#6 /var/www/vhosts/pw.domain.tld/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#7 /var/www/vhosts/pw.domain.tld/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#8 /var/www/vhosts/pw.domain.tld/index.php(28): require('/var/www/vhosts...')\n#9 {main}, referer: https://pw.domain.tld/index.php?r=index

**Comment by nuxsmin** [comment]
3.1-RC1 has been released out, please check it out for solving this issue.
