### ISSUE TITLE
Password: forced reset

### ISSUE THREAD

**Issue by DDH112** [nuxsmin/sysPass#1265]
**sysPass Version**
3.0 (304.19012601) 

**Describe the question**
We used to have a checkbox on a user profile 'requires reset' where you can force a password reset by a user when logging in. I cannot retrieve this functionality in V3.

Did this disappear of am I looking in the wrong place?

**Comment by nuxsmin** [comment]
Hello, this option should be enabled when  mail settings are set and the user doesn't come from LDAP.

Regards

**Comment by DDH112** [comment]
Ok, that did the trick!
