### ISSUE TITLE
Cannot delete Categorie

### ISSUE THREAD

**Issue by Qualitune** [nuxsmin/sysPass#1266]
I am using Syspass Version **3.0**

**Cannot delete Categorie**
Hello i am not able to delete a categorie. I have read some issues but there are no Accounts in History which could be linked to that Categorie. There is also no Account inside this Categorie.

I am using Firefox in newest Version.
The Syspass Application is installed on a Ubuntu 18.04

![syspass fehler](https://user-images.githubusercontent.com/47979294/53340628-c5f27180-3909-11e9-8c0b-7b83bf2ecaf3.jpg)

**Comment by nuxsmin** [comment]
Hello, please check out the accounts by using special search filters, it would give you more clues about which account is using that category.

Regards

**Comment by Qualitune** [comment]
Hello,
I alreaddy did that. I imported the Accounts from Keepass. So KeePass created his own Categories. Now i added some new Categories and moved the Accounts to the new Category. So the old Categorie which was created from Keepass is now empty ( if i search with special filters i see there are no results when i put in the Category). 
And if i try to delete the category it shows this error.

**Comment by Qualitune** [comment]
I think it is connected with the History but how can i delete those?
Here a screenshot so you see that the category i want to delete is definitly empty.
![category 2](https://user-images.githubusercontent.com/47979294/53422820-7df24e00-39e0-11e9-9490-11ee7e1ab8fd.PNG)
![category](https://user-images.githubusercontent.com/47979294/53422821-7df24e00-39e0-11e9-9952-560e617bef24.PNG)
![category3](https://user-images.githubusercontent.com/47979294/53422822-7df24e00-39e0-11e9-8ded-2885b1195ae2.PNG)

**Comment by nuxsmin** [comment]
Hello, accounts' history can be displayed on `Accounts (H)` tab.

Regards
