### ISSUE TITLE
Bug after upgrade 2.1 to 3.0

### ISSUE THREAD

**Issue by HellChords** [nuxsmin/sysPass#1267]
**sysPass Version**
3.0 (305.19020701) 

**Describe the bug**
After upgrade icons wasn't here

**To Reproduce**
See screen

**Screenshots**
![image](https://user-images.githubusercontent.com/25925581/53417190-53e75e80-39d5-11e9-8c84-55b7b335203d.png)

![image](https://user-images.githubusercontent.com/25925581/53417341-b0e31480-39d5-11e9-98d8-3f7007e9d813.png)

**Event log**
`2019-02-26 14:45:11 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2019-02-26 14:45:11 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
2019-02-26 14:45:11 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-02-26 14:45:11 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache
`

**Platform (please complete the following information):**
 - OS: Linux Debian
 - 9.2
 - Firefox and IE

Thank you for help :)

**Comment by nuxsmin** [comment]
Hello,

Please check out the browser's network console (F12). It should display some errors about not found resources.

Regards

**Comment by HellChords** [comment]
Hi,

Screen of Network tab :
![image](https://user-images.githubusercontent.com/25925581/53418518-48496700-39d8-11e9-8520-a1dba5af717b.png)

**Comment by HellChords** [comment]
After fresh install (Debian 9), same...
Follow this : 
https://doc.syspass.org/en/3.0/installing/debian9.html

**Comment by jucajuca** [comment]
I think I have a similar problem, here is the error log from apache:

starts with:

`[Fri Mar 01 20:34:28.998676 2019] [:error] [pid 15346] [client 80.109.74.247:52830] [ERROR] [SP\\Core\\Language::setLocales] Could not set locale, referer: https://syspass.mydomain.com/index.php?r=index
[Fri Mar 01 20:34:29.254444 2019] [:error] [pid 15349] [client 80.109.74.247:52824] [INFO] [SP\\Core\\UI\\Theme::initIcons] Loaded icons cache, referer: https://syspass.mydomain.com/index.php?r=index
[Fri Mar 01 20:34:29.265427 2019] [:error] [pid 15349] [client 80.109.74.247:52824] [INFO] [SP\\Core\\Acl\\Actions::loadCache] Loaded actions cache, referer: https://syspass.mydomain.com/index.php?r=index
[Fri Mar 01 20:34:29.375053 2019] [:error] [pid 15350] [client 80.109.74.247:52828] [INFO] [SP\\Core\\UI\\Theme::initIcons] Loaded icons cache, referer: https://syspass.mydomain.com/index.php?r=index`

ends with

`[Fri Mar 01 20:34:29.433437 2019] [:error] [pid 15357] [client 80.109.74.247:52798] [INFO] [SP\\Core\\UI\\Theme::initIcons] Loaded icons cache, referer: https://syspass.mydomain.com/index.php?r=index
[Fri Mar 01 20:34:29.435953 2019] [:error] [pid 15357] [client 80.109.74.247:52798] [INFO] [SP\\Core\\Acl\\Actions::loadCache] Loaded actions cache, referer: https://syspass.mydomain.com/index.php?r=index
[Fri Mar 01 20:34:29.439039 2019] [:error] [pid 15346] [client 80.109.74.247:52830] [INFO] [SP\\Core\\UI\\Theme::initIcons] Loaded icons cache, referer: https://syspass.mydomain.com/index.php?r=index
[Fri Mar 01 20:34:29.444131 2019] [:error] [pid 15346] [client 80.109.74.247:52830] [INFO] [SP\\Core\\Acl\\Actions::loadCache] Loaded actions cache, referer: https://syspass.mydomain.com/index.php?r=index`

here is the a larger chunk of the log
https://pastebin.com/tdvHaXUW

**Comment by jucajuca** [comment]
I can confirm this also happens with the docker image. Any ideas on what could possible cause the error?
thx

**Comment by nuxsmin** [comment]
Hello @HellChords this issue is related to the `MaterialIcons-Regular'  font since icons a loaded as a font glyph. Could you check (or force) whether the font is downloaded?

Regards

**Comment by nuxsmin** [comment]
Hello, I've just had the same issue on my development environment, and after struggling a bit with the fonts loading, I noticed that CORS was being applied (browser's console) so the browser was preventing to load the font because the server's domain didn't match with the browser's URL (localhost vs 127.0.0.1), so after changing the URL domain it worked fine.

https://stackoverflow.com/questions/44728115/font-not-loading-cors-says-header-contains-no-access-control-but-there-is

Regards

**Comment by jafamo** [comment]
Hi, 
I resolved this issues:
1. **Error SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared**
You need edit your mysql with this:
```
table_definition_cache  =    16384
table_open_cache      =      32162
table_open_cache_instances = 4
```
Source:
[dba.stackexchange.com](https://dba.stackexchange.com/questions/144427/getting-error-err-1615-prepared-statement-needs-to-be-re-prepared-with-mys)


2. **[ERROR] [SP\\Core\\Language::setLocales] Could not set locale, referer:**
Check your locale on server and put the same on lib/SP/Bootstrap.php on line 125
I have on my server "LANG=es_ES.UTF-8"
```
 Language::setLocales('es_ES');
```

I am using:

- PHP 7.3.14-1~deb10u1 (cli) (built: Feb 16 2020 15:07:23) ( NTS )
- Apache/2.4.38 (Raspbian)
- [Syspass 3.1.2](https://github.com/nuxsmin/sysPass/releases/tag/3.1.2.20030701)


Regards
