### ISSUE TITLE
Problem with the downloading backup files and event logs

### ISSUE THREAD

**Issue by Bastaxi** [nuxsmin/sysPass#1268]
**sysPass Version**
3.0 (305.19020701) 
Config: 305.19020701 
App: 305.19020701 
DB: 305.19020701

Hosting mode.

**Describe the bug**
Hello,

When I download a file on syspass (event logs or backup), the file is alway empty. 

Do you have any idea ? 

Thank you in advance. 

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'BACKUP' or 'INFORMATION'
3. And download the backup file or event logs.
4. The files are emtpy.

**Screenshots**
![image](https://user-images.githubusercontent.com/47448499/53478890-29021680-3a78-11e9-9d24-4305f5f14692.png)

**Event log**
The file is empty.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome and Firefox

**Comment by nuxsmin** [comment]
Hello, are you running sysPass on Windows?

Regards

**Comment by kajla** [comment]
Hello,

I have got the same problem with Linux (SLES15 SP1).
3.1 (310.19081801)
Config: 310.19081801
App: 310.19081801
DB: 310.19081801 
PHP Version: 7.2.5 

I can find these files on the server (app/backup).

Thank you in advance.

Best regards,
Adam
