### ISSUE TITLE
Feature Request: API REST de consulta

### ISSUE THREAD

**Issue by cgarciaarano** [nuxsmin/sysPass#127]
Hola, he visto vuestro proyecto en [Security By Default](www.securitybydefault.com) y resuelve bastante bien el problema de compartir contraseñas, sobre todo con la gestión de usuarios.

Estoy buscando una solución de este estilo para almacenar las contraseñas y que sean accesibles por los automatismos que tenemos en nuestra infraestructura (como Puppet, Chef, Ansible). Una opción es acceder directamente a la BD de sysPass, pero sería mucho más limpio contar con un API REST para poder realizar peticiones via HTTPS. 

No he revisado vuestro código (PHP no es mi fuerte :sweat_smile:)  pero supongo que añadir una serie de URLs de consulta no debería ser mucho más complicado de lo que habeis hecho.

En cualquier caso, gran trabajo.

**Comment by nuxsmin** [comment]
Gracias, me alegra saber que el proyecto es útil ;)

Con respecto a la API REST, efectivamente hay una mínima implementación en la versión 1.2 que aún es beta y falta poco para su lanzamiento.

La API no es RESTful totalmente, ya que requeriría de la implementación de routing de URLs, por lo que he decidido (de momento), realizarla con parámetros en URL para funciones básicas como consultas, ver datos de cuentas, claves y poco más.

Puedes probarla desde la rama dev en github y me cuentas tus impresiones.

Saludos!

**Comment by cgarciaarano** [comment]
Muy bien, yo creo que con la funcionalidad que hay ahora, me sobra. Cuando me ponga con ello os comento impresiones.

Gracias
