### ISSUE TITLE
Accounts filtering by name does not work

### ISSUE THREAD

**Issue by Weptun** [nuxsmin/sysPass#1271]
**sysPass Version**
3.0 (305.19020701) 

**Describe the bug**
Accounts filtering by name does not work using the search bar in the "Items and Customizations" -> "Accounts" page.

**To Reproduce**
1. Log in as admin
2. Click on "Items and Customizations"
3. Select "Accounts"
4. Type something in the search bar (e.g. "Amazon" when using the demo.syspass.org instance), press enter. The sorting seems to change a little bit, but the accounts are not filted, you can still see all accounts. Filtering using "Special Parameters" works as expected.

**Expected behavior**
I expected a fulltext search that covers at least the account name. The list should only display the items that contain the search term.

**Event log**
Nothing special in the log

**Platform (please complete the following information):**
 - OS: Linux
 - OS Ubuntu 18.04
 - Browser Chrome

**Comment by nuxsmin** [comment]
Hello, it will be fixed shortly.

Thanks for the feedback!
