### ISSUE TITLE
Custom fileds missing after upgrade to v3

### ISSUE THREAD

**Issue by VexedSyd** [nuxsmin/sysPass#1273]
**sysPass Version**
3.0 (305.19020701)

**Describe the bug**
I have just realised that custom fields are missing in v3. I believe I updated sysPass from v2.1 to v3.0.0, the I upgraded sysPass with every new release.

**Screenshots**
Custom fields in v2.1 (2.1.16.18061901)
![image](https://user-images.githubusercontent.com/15827925/54006283-c5cb5f00-41b0-11e9-9ead-2f72ab27dc3f.png)

Custom fields in v3.0 (305.19020701)

![image](https://user-images.githubusercontent.com/15827925/54006324-f57a6700-41b0-11e9-9b78-572ae10feacc.png)

I have checked the database and the custom fields and the data is still there.
Is there anything I can do to remap the custom fields again?

Many thanks.

**Comment by atmcommunicaction** [comment]
Sorry... but how did you upgrade from 2.1 to 3.0?
tnx

**Comment by nuxsmin** [comment]
Hello @VexedSyd

Unfortunately it was fixed in latest release but it would require to upgrade again from v2.1. I'll work on a patch for upgraded instances.

Thanks for the feedback!

Regards

**Comment by VexedSyd** [comment]
> Sorry... but how did you upgrade from 2.1 to 3.0?
> tnx

I have followed these instructions 
[https://doc.syspass.org/en/3.0/updating/v3.html](url)

**Comment by VexedSyd** [comment]
> Hello @VexedSyd
> Unfortunately it was fixed in latest release but it would require to upgrade again from v2.1. I'll work on a patch for upgraded instances.
> Thanks for the feedback!
> Regards

Thanks for your prompt reply... Unfortunately we have added a lot of data since the upgrade early this year...
Would you release a patch anytime soon?

Thanks again for your great effort.

**Comment by nuxsmin** [comment]
@VexedSyd I've added a bugfix in latest 3.1 release. Please check it out in your environment and let me know if it worked.

Regards

**Comment by VexedSyd** [comment]
Hi @nuxsmin ,

Many thanks for following up. I have just updated to the latest version and checked the custom fields. I can see them there, but the custom fields name are empty.

![image](https://user-images.githubusercontent.com/15827925/57071863-15e12080-6d1f-11e9-8702-5207bc15602b.png)


The accounts page do not show the custom fields either.

Please let me know if you need further information.

Thanks again.

**Comment by VexedSyd** [comment]
The custom fields appeared in accounts after I updated the fields' names manually, but the data is no longer showing

![image](https://user-images.githubusercontent.com/15827925/57073322-162fea80-6d24-11e9-96d7-6e4a0cba5a77.png)
