### ISSUE TITLE
sysPass Email Audit wrong URL

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1274]
Hey,
i recognized that in mail audit the wrong URL is used. I am running sysPass on pw.domain.tld, but this runs behind some reverse proxy on anotherhost.domain.tld:<someport>. its similar thing like reported in https://github.com/nuxsmin/sysPass/issues/1124. If somebody creates/deletes account i get an email notification. the urls in that mail should point to the public URL if possible.

regards, Mario

**Comment by nuxsmin** [comment]
Hey, this issue has been fixed in latest v3.1 (still in development), so it will be available soon.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Regards
