### ISSUE TITLE
LDAP port is not being saved

### ISSUE THREAD

**Issue by lreiher** [nuxsmin/sysPass#1277]
**sysPass Version**
3.0

**Describe the bug**
Setting LDAP server to `<url>:<port>` and then checking the connection correctly displays the users. When the configuration is saved, the port information is cut off and only `<url>` remains, which of course breaks the configuration, if a non-standard port is used.

**To Reproduce**
1. Go to 'Configuration/LDAP'
2. Set the server field to a valid host with a non-default port
3. Check the connection, it should work
4. Save the connection, the port configuration should disappear

**Platform (please complete the following information):**
 - sysPass running as Docker container
 - Browser: accessed via Safari (macOS)

**Comment by thesystman** [comment]
Also found the same thing. For security reasons i'm not using the standard port. That is now hard to configure.

**Comment by nuxsmin** [comment]
Hello, this is a known behavior since LDAP server's port is actually saved but not shown in the configuration page (you can check it in 'config.xml` file).

I'll implement this improvement in next release.

Thanks for the feedback!
