### ISSUE TITLE
Feature Request: Acceso temporal a claves

### ISSUE THREAD

**Issue by MAGlCUS** [nuxsmin/sysPass#128]
Buenas.

Me parece una aplicación que resuelve bastante bien el problema planteado y que poco a poco se puede ir convirtiendo en una aplicación de referencia.

Una de las cosas que hecho en falta como sysadmin es que pueda conceder acceso temporal a contraseñas a un grupo de usuarios o a un usuario concreto. 

Esto se puede utilizar para guardias, o accesos a terceros que el acceso debe ser temporal. Con esto como base, se podría complementar con notificaciones.

Espero que la funcionalidad que propongo sea de utilidad y la consideréis para próxima versión ;-)

Un saludo,

**Comment by nuxsmin** [comment]
Buenas, gracias por tu apoyo y me alegra saber que la aplicación es util :)

La idea es buena y posible, pero tendría que dejarlo para la próxima versión 1.3, ya que ésta está a punto de lanzarse y llevar a ejecución esto necesitaría de modificaciones en BD y algo de código.

Saludos!

**Comment by pydubreucq** [comment]
Hi,
Excuse-me I don't understand spanish ;) I've used Google Translate to understand this Feature Request.
If I've understand it, this feature could be to transfer a temporary access to another person for transfer a secret ?
If it's that I would like this feature too :) It could be possible to generate a temporary weblink and send it by email or not.
This weblink open a webpage with the secret.
I have to transfer secret with our clients and I would like a secure way to transfer them.
And big thanks to this app, today I'm using Teampass and yours is really user-friendly, I just wait this feature to migrate ;)
Best Regards,
Pierre-Yves

**Comment by nuxsmin** [comment]
Hi, this feature request is what you said, a public link that points to the account details.

It can be accomplished with some coding, so it can be available in the next release.

These are the key points:

* profile option to enable it
* config option to set max num of views
* config option to set expire time
* button on account details to get the link
* A list of active links that are being published and some actions like edit or remove. This will be placed at the users and accesses section.

I hope it can be available in short.

**Comment by nuxsmin** [comment]
Hola, ya que era una funcionalidad bastante requerida, he tenido algo de tiempo para llevarla a cabo. Actualmente está en la rama de desarrollo, por lo que es posible descargarla desde aquí: https://github.com/nuxsmin/sysPass/tree/devel

---
Hi, it was a very popular functionality so I have had some time to code it. Actually it has been pushed  to the devel branch, so you can download it from:
https://github.com/nuxsmin/sysPass/tree/devel

**Comment by MAGlCUS** [comment]
Ok. Thanks a lot. I will try to test it as soon as possible. ;-)

I'll comment my impressions ;-)

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin 

How can I configure this option in sysPass?

**Comment by nuxsmin** [comment]
Done in sysPass v2
