### ISSUE TITLE
Change User Password

### ISSUE THREAD

**Issue by andrucha97** [nuxsmin/sysPass#1282]
sysPass Version
3.0 (305.19020701) on Debian Buster and PHP 7.3.2-3

Password Reset not working great - When I'm rest the password via Mail I get a Link where I can enter a new Password. After setting the password an Login I sould enter my old Password.

To Reproduce

1. Go to Forgot Password
2. Link in Mail
3. Change Password
4. Try to login with new Password

Expected behavior

There should be the option Admins can change the Password (you can but while login with new pw it also ask the old pw)

And when using Forget Password you do not have to enter old Password

Platform

OS: [Linux and Windows]
OS Version: 18.04.2 LTS and Win 10
Browser: Firefox, Chrome

**Comment by cRaZy-bisCuiT** [comment]
No! That's actually for security reasons! This is meant to provide safety from people/admins resetting your password and compromising your account.

In order to reset / set a new password, the user need to enter the old one.

**Comment by andrucha97** [comment]
Ok.... that makes no sense ... "Forgot Password" means I forgot it.

And why you have a Admin if he cannot set a new Password?
Maybe there sould be a new Right for Admins to set with Admin-Admin User

**Comment by cRaZy-bisCuiT** [comment]
I guess it's because if you use a LDAP user and the LDAP password is reset for some reason, then you need to login using your new password, but for the first login you need to login using your old password as well.

But actually it's just me guessing. Maybe @nuxsmin could enlighten us. :)

**Comment by andrucha97** [comment]
I don't use a LDAP at this moment.

My Problem was:

I forgot the Password of the test user. Than I tried reset as Admin-Admin. Old Password was asked. Trying with Forgot Password and auth. over Mail also asked old PW.

To login with that User I needed to remove the User and add the User. But what if the User has privat Passwords or is allowed to see Passwords? You have to change all entries and passwords?

**Comment by nuxsmin** [comment]
The old password is asked because it will try to decrypt de master password using the old one and the encrypt it again with the new one.

**Comment by andrucha97** [comment]
@nuxsmin no wait that's not right.

First Try:

1. Go to User and Access
2. Set new password
3. Logout
4. Login with User -> its asking old and new password

Second Try (E-Mail notification is enabled. Now "Forgot Password appears on login site):

1. Go to "Forgot Password"
2. Receive email
3. Click link in Email
4. Rest new password and save
5. Login with Username and Password -> asking for old and new password

What I think would be right or maybe say would be great:

1. User with new right to reset password
2. Forgot Password -> E-Mail -> Reset -> Login works without old password. Or if it's risky ask for new Temporary Masterpassword

Or you can tell me how to reset password of a user without remove user and create a new one :D

If you remove the user all right to passwords and private passwords would/sould be delete

**Comment by nuxsmin** [comment]
@andrucha97 
> Or you can tell me how to reset password of a user without remove user and create a new one :D

It isn't needed at all. Please enter any random password when asking for the old one (which is the wrong behavior indeed), and then it will ask for the master password (you can enter a temporary password).

Regards
