### ISSUE TITLE
No IP Address at Startup

### ISSUE THREAD

**Issue by lin-unix** [nuxsmin/sysPass#1284]
**sysPass Version**
3.0.5

**Describe the question**
When I startup sysPass, the app (or the container) doesn't get the host's IP address. Is this by design?

I'm sorry for the foolish question but I am new at Docker and I don't know whether the problem exists in sysPass or the Docker yml file.

**Screenshots**
syspass/syspass:3.0.5   "/usr/local/sbin/ent…"   2 days ago          Up 2 seconds        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   syspass-app

**Platform (please complete the following information):**
 - Debian
 - 9
 - N/A

**Additional context**

**Comment by bmols** [comment]
What is the IP address of your docker host?

**Comment by lin-unix** [comment]
128.100.167.x

Unfortunately, I can't access that IP. No response.

**Comment by bmols** [comment]
stop the docker container, remove it, and recreate it with different ports. In my case I'm forwarding 32769 to port 80. I've had issues with port 80 & 443 before so i tend to stick to other ports

**Comment by lin-unix** [comment]
Still not quite right:
b06fe055ce25        syspass/syspass:3.0.5   "/usr/local/sbin/ent…"   9 seconds ago       Up 8 seconds        80/tcp, 443/tcp, 0.0.0.0:80->32769/tcp, 0.0.0.0:443->32770/tcp   syspass-app

Thank you for the help so far. I don't have any firewalls between me and my server either.

**Comment by bmols** [comment]
Thats not right. 

> 0.0.0.0:80->32769/tcp, 0.0.0.0:443->32770/tcp 
This means that you're forwarding port 80 on your host to port 32769 on your container and port 443 on your host to port 32770 on your container

in your create file it should read

> ...
> -p 32769:80
> -p 32770:443
> ..

**Comment by bmols** [comment]
> 128.100.167.x
> 
> Unfortunately, I can't access that IP. No response.

This is the address of the server/computer running docker? Not very often I see a class b network

**Comment by lin-unix** [comment]
> > 128.100.167.x
> > Unfortunately, I can't access that IP. No response.
> 
> This is the address of the server/computer running docker? Not very often I see a class b network

That's the correct address. I have multiple servers in the range.

**Comment by lin-unix** [comment]
Thanks bmols, it was a port conflict with 80 and 443. IOU one beer.
