### ISSUE TITLE
Please change name lang file

### ISSUE THREAD

**Issue by pitrov24** [nuxsmin/sysPass#1288]
HI,

In file language.php is

 private static $langs = [
        'po_PO' => 'Polski',

but file name in /app/locales pl_PL

that's why the language does not work. Change to the installation package, either the name of the folder with the language or the name in the files

**Comment by nuxsmin** [comment]
Hi, you're right, the language is wrongly set..

Thanks for the feedback!

**Comment by nuxsmin** [comment]
3.1-RC1 has been released out, please check it out for solving this issue.
