### ISSUE TITLE
Recover Master Password

### ISSUE THREAD

**Issue by doppia-a** [nuxsmin/sysPass#1289]
**sysPass Version**
3.0.5

**Describe the question**
Hello,
I was enabling the LDAP configuration, but i didnt' remember the original Master Password. So I tried to change it but I probably made a mistake and I don't flag the option to re-encrypt accounts. So now I'm not able to access even with admin account since he is asking the original Master Password that I don't have. My question is if there is the possibility to recover the original Master Password having only the CLI access to the server? 

Many thanks in advance
Regards
Andrea Achilli

**Platform (please complete the following information):**
 - OS: Ubuntu
 - OS Vesion:  18.04
 - Browser Firefox, Chrome

**Comment by nuxsmin** [comment]
Hello, unfortunately sysPas does not store the master password in plain text, so such recovering cannot be performed.

As you told above, you were enabling LDAP and it seems that you can't log into sysPass after it, is it right?. In such case you can disable the LDAP auth by editing `config.xml` file (within `app/config` directory).

Regards
