### ISSUE TITLE
Instalacion en Debian

### ISSUE THREAD

**Issue by yosug** [nuxsmin/sysPass#129]
Siguiendo los pasos que se describen en http://wiki.syspass.org/es/instalar no consigo hacer funcionar la instalacion.

El directorio por defecto en Debian para las paginas web es /var/www/html. Si queremos https hay que habilitar el modulo ssl (a2enmod ssl) pero aun asi me aparece:
```
. * */ define('APP_ROOT', '.'); require_once APP_ROOT . DIRECTORY_SEPARATOR . 'inc' . DIRECTORY_SEPARATOR . 'init.php'; SP_Html::$htmlBodyOpts = 'OnLoad="doAction(\'accsearch\')"'; SP_Html::render("main");
```
en la url de instalacion (/syspass/index.php)

La version que he instalado es 1.1.2.24.tar.gz. El sistema es una Debian 8 Jessie con la instalacion minima de servidor web y ssh.

**Comment by nuxsmin** [comment]
Hola, parece que no está correctamente instalado php. Ejecuta lo siguiente:

```apt-get install php5 && service apache2 restart```

**Comment by yosug** [comment]
Ha funcionado. Faltaba instalar el paquete php5

Otro detalle para el manual de instalacion es que en el fichero comprimido no hay ningun directorio backup. Hay que crearlo a mano.
