### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by lucasdiaas** [nuxsmin/sysPass#1291]
I'm using SysPass V3 but when I try to access the API from the browser it returns this.

![syspass API error](https://user-images.githubusercontent.com/22860001/54831787-c2989e80-4c99-11e9-892a-4a15ad937200.PNG)

While on the older version V2.X

![syspass API work](https://user-images.githubusercontent.com/22860001/54831827-d3491480-4c99-11e9-98ea-a51603a72dfa.PNG)

It seems to get somewhere but doesn't return anything.
Any thoughts why?

**Comment by nuxsmin** [comment]
Hello,  you need to provide a valid JSON payload, https://doc.syspass.org/en/3.0/application/api.html

Regards

**Comment by lucasdiaas** [comment]
I've used your example and it seems to be working now, but I got an Internal error message as shown below:

```json
{"jsonrpc":"2.0","error":{"message":"Internal error","code":0,"data":null},"id":1}
```

And that is my data json:

```json
{
	"jsonrpc": "2.0",
	"method": "account/search",
	"params": {
		"authToken": "#####",
		"text": "#####"
	},
	"id": 1
}
```

**Comment by nuxsmin** [comment]
Hello, is there any error massage in `syspass.log` file? (you can download it from `Configuration > Information` tab.
