### ISSUE TITLE
Error "service unavailable" after password update

### ISSUE THREAD

**Issue by vrdominguez** [nuxsmin/sysPass#1293]
**Version:** 3.0 (305.19020701) 

**Describe the bug**
After changing password, syspass shows a "Service unavailable" error (password is changed, but you have to logout an login again)

**To Reproduce**
1. Go to 'Change user's password'
2. Set new password
3. Click on 'save'

**Expected behavior**
Change the password and logout so you can enter the new password and master password or th old passowrd

**Screenshots**
![syspass-error](https://user-images.githubusercontent.com/5773902/54937663-21257d00-4f25-11e9-8b48-16af0275edbc.jpeg)

**Event log**
Fresh install with new created user, so I attached the full log:
[syspass.log](https://github.com/nuxsmin/sysPass/files/3004478/syspass.log)

**Platform (please complete the following information):**
  - Browser: Google Chrome 73.0.3683.86 on Ubuntu 18.04 x64 (updated)
  - Server: Ubuntu 18.04, Apache2, PHP 7.2.15 and MySQL 5.7.25

**Additional context**
We have the same problem in production enviroment with the same configuration

**Comment by nuxsmin** [comment]
Hello, it seems a nasty UI bug, though the password is changed indeed...I'll fix it shortly.

Thanks for the feedback!
