### ISSUE TITLE
Forgot password requires previous password

### ISSUE THREAD

**Issue by DDH112** [nuxsmin/sysPass#1294]
**sysPass Version**
3.0 (304.19012601) 

**Describe the bug**
I am an issue with some users. They request a password reset through the password reset link, but have to set their previous password (which they obviously forgot) on first login. Only solution for this at the moment is to ask them to reset their password twice and use these passwords to complete the previous password field which is quite odd.
Any idea what might be wrong?

**Comment by nuxsmin** [comment]
Hello, I'll do some tests about this issue, in the meantime, you can skip the previous password request by entering any random password and the it will require to enter the master password.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, I've done several tests and app login works as expected after a password reset, that is it will require the master password.

Regards
