### ISSUE TITLE
v3 text note is truncated with '<' character

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1296]
**sysPass Version**
3.0 (305.19020701) 
Config: 300.18111001 
App: 303.19012402 
DB: 300.18111901
MariaDB 10.1
PHP 7.2.16
Debian 9

**Describe the bug**
Text is truncated when it contain '<' character

**To Reproduce**
1. Generate an random string with cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
2. In this string add a '<' in the middle
3. Add this string in a entry note
4. Save

**Expected behavior**
The text must be identic but when it saved, the text is cut right the '<' character.

**Comment by pierrehenrymuller** [comment]
Hi,
How I can help for search this bug?
Good day

**Comment by nuxsmin** [comment]
Hi, sorry for the late reply. It will be fixed in next release.

Thanks for the feedback!
