### ISSUE TITLE
Severe security breach : private key and backup file publicly accessible

### ISSUE THREAD

**Issue by eandry77** [nuxsmin/sysPass#1297]
**sysPass Version**
3.0 (305.19020701) 

**Describe the bug**
The file key.pem and db.sql are publicly accessible with 750 permission on config folder.
This has been spotted by an openvas scan

**To Reproduce**
1. Go to https://your syspass server/app/config/key.pem
2. The private key is shown, without authentication asked
3. Go to https://your syspass server/tests/res/scripts/db.sql
4. You can download your sql backup !

**Expected behavior**
These 2 files must not be so easily accessible, and shouldn't be accessible through webserver at all

**Platform (please complete the following information):**
 - OS: linux
 - OS version : Debian 9
 - Browser [Firefox]

**Comment by eandry77** [comment]
openvas report : 

![image](https://user-images.githubusercontent.com/6266436/55096176-afcb0300-50b9-11e9-9345-c8d9f1d3f9d3.png)

**Comment by nuxsmin** [comment]
Hello, this isn't a security breach but a misconfiguration instead.
 http://doc.syspass.org/en/3.0/application/security.html

Regards

**Comment by eandry77** [comment]
Ah Ok, my bad...
But I think it should be a part of the install documentation. Maybe merge the security with install procedure ? It's so important IMHO that no one should miss this step !

**Comment by eandry77** [comment]
After applying the recommendation, I've a 403 error, unless I add index.php to the url. 
I'm using relayd on openbsd as a reverse proxy. (I don't know if it matter, but just in case..)
I guess I miss something in my apache.conf to allow redirection to index.php

**Comment by nuxsmin** [comment]
Yes, it's related to the URL redirection, which isn't working. The security tweak should deny any request which does not have `index.php` or `api.php` within the URL.

**Comment by nuxsmin** [comment]
> But I think it should be a part of the install documentation. Maybe merge the security with install procedure ? It's so important IMHO that no one should miss this step !

Some warnings were added to avoid this nasty issues...

http://doc.syspass.org/en/3.0/installing/debian9.html#environment-configuration
