### ISSUE TITLE
Consulta con configuracion LDAP

### ISSUE THREAD

**Issue by anvers** [nuxsmin/sysPass#130]
Que tal! 

Necesitaria ayudar para poder configurar LDAP. Estuve leyendo otros post pero no logro encontrar bien el problema. Perdon pero soy medio nuevo en el tema!

Antes que nada, es necesario especificar un "grupo" ? eso se refiere al filtrado de usuarios?

Copio la configuracion actual que tengo y el error que me figura en el log:

![1](https://cloud.githubusercontent.com/assets/7632485/10031047/4e456a5e-6151-11e5-96a4-f9270e73a511.png)

![2](https://cloud.githubusercontent.com/assets/7632485/10031049/512c1db2-6151-11e5-8369-8fce6cb25eeb.png)

Muy buena la aplicacion!

Gracias

**Comment by nuxsmin** [comment]
Hola!, me alegro que te sea util la aplicación :)

Con respecto a la configuración de LDAP, es necesario crear un grupo del que sean miembros los usuarios que van a iniciar sesión en sysPass. Ten en cuenta que el grupo tiene que estar en la misma base de LDAP donde se realizan las búsquedas, es decir, si tu base de usuarios es "ou=Usuarios,dc=company,dc=com", tanto el usuario como el grupo tienen que estar en una OU que esté por debajo de la principal.

Espero que te funcione.

Un saludo

**Comment by anvers** [comment]
Que Nuxsmin, perdona que te moleste de vuelta pero probe como me habias dicho pero algo debo estar haciendo mal. Te muestro la estructura del AD para que veas y como lo puse ahora

![1](https://cloud.githubusercontent.com/assets/7632485/10045139/d38b078e-61d6-11e5-8c97-23c2d0e93447.png)
![2](https://cloud.githubusercontent.com/assets/7632485/10045141/d38fbc70-61d6-11e5-860b-d60d70c2ab65.png)
![3](https://cloud.githubusercontent.com/assets/7632485/10045140/d38ed684-61d6-11e5-8e16-c75f8c6795f6.png)


Lo que hice fue crear un grupo "usuarios" dentro de Users y ahi dentro puse un usuario "nsangregorio" para probar pero me devuelve el error que te copie ahi

Gracias nuevamente!

**Comment by nuxsmin** [comment]
Hola, la base sería "CN=Users,OU=Cabal,DC=cabal,DC=coop" y el grupo sería "Usuarios"

A ver si conecta ;)

**Comment by anvers** [comment]
Hola!,

Ahi copie la configuracion como me dijiste pero me arrojo el error siguiente:

![1](https://cloud.githubusercontent.com/assets/7632485/10045365/8c1a7fae-61d8-11e5-976a-8feea8a3663a.png)
![2](https://cloud.githubusercontent.com/assets/7632485/10045366/8c1c23a4-61d8-11e5-8d3e-e041e7007f03.png)

Saludos!

**Comment by nuxsmin** [comment]
Me he confundido con CN=Users, sería "OU=Users,OU=Cabal,DC=cabal,DC=coop", ya que el primero es para el que crea por defecto ADS

**Comment by anvers** [comment]
Genio! Ahi funciono! mil gracias!

Te hago una ultima pregunta. Para las cuentas que sean del AD, tambien tienen que poner la clave maestra ? o hay manera de sacar eso que solo use sus credenciales?

Muchas gracias!

**Comment by nuxsmin** [comment]
Perfecto!!

La clave maestra sólo la pide una vez o cada vez que el usuario cambie su clave (sea de AD o de MySQL). 

En vez de dar la clave maestra, te recomiendo que configures el correo y generes una clave maestra temporal en "Configuración > Clave Maestra". Esta clave se envía por correo al buzón configurado para sysPass para que se la puedas remitir a los usuarios que accedan.

El tiempo de validez lo configuras en el mismo sitio.

Saludos!

**Comment by anvers** [comment]
Buenisimo! muy completo!

Y hay manera de poder armar un grupo y que ya tengan un conjunto de contraseñas cargadas? 

Por ejemplo, creo un grupo "SoportE tECNICO" y que todos los que ponga en ese grupo, tengan ya un grupo de cuentas armadas.

gracias nuevamente!

**Comment by nuxsmin** [comment]
Debido al diseño de encriptación, no es posible, ya que es necesario que el usuario introduzca su clave para reencriptar la clave maestra, ya que no se guarda de forma permanente en el servidor.

El proceso es así:

* Se genera una clave maestra, pero no se guarda, sólo el hash de comprobación.
* Se facilita la clave maestra o la temporal al usuario
* El usuario accede con su clave e introduce la clave maestra
* La clave maestra se guarda encriptada con la clave del usuario, para no solicitarla de nuevo
* Cada vez que se quiere ver la clave de una cuenta, se desencripta la clave maestra y con ella se desencripta la clave de la cuenta.
