### ISSUE TITLE
Question mark copied as html code

### ISSUE THREAD

**Issue by 90er** [nuxsmin/sysPass#1300]
**sysPass Version**
3.0 (305.19020701)

**Describe the bug**
Question mark copied as html code instead of "?"

**To Reproduce**
1. Add new account
2. Use an password with an ? (question mark) in it
3. Show password for account and copy it in the clipboard (with the given clipboard icon)
4. The character "?" is copied as "&quest;"

**Expected behavior**
? should be ? and not &quest;

**Platform:**
 - OS: CentOS 7
 - Webserver: Apache httpd
 - PHP: PHP 7.0.33
 - OS Version
 - Browser: unimportant

**Comment by nuxsmin** [comment]
Hello, could you use Markdown syntax to show the wrong character?: https://guides.github.com/features/mastering-markdown/

This issue has probably been fixed in next release (under development), but I want to be sure about the behavior you told above.

Regards.

**Comment by 90er** [comment]
> Hello, could you use Markdown syntax to show the wrong character?: https://guides.github.com/features/mastering-markdown/
> 
> This issue has probably been fixed in next release (under development), but I want to be sure about the behavior you told above.
> 
> Regards.

Right:
`6a?s`

Wrong:
`6a&quest;s`

**Comment by nuxsmin** [comment]
This issue has been fixed for next release.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
3.1-RC1 has been released out, please check it out for solving this issue.

**Comment by 90er** [comment]
Hello @nuxsmin,

i can confirm that this bug is fixed with 3.1-RC1! :-)
Thanks for your work.

Wolfgang
