### ISSUE TITLE
sysPass 3: Error when reopen sysPass tab without logout

### ISSUE THREAD

**Issue by 90er** [nuxsmin/sysPass#1301]
**sysPass Version**
3.0 (305.19020701)

**Describe the bug**
Error when reopen sysPass tab without logout.

**To Reproduce**
1. Login to sysPass
2. close the browser tab (without logout)
3. reopen sysPass by URL
4. (Screenshot)

After it i have to close the browser and reopen it.

**Expected behavior**
No error :-)

**Screenshots**
![2019-04-01_15h28_53](https://user-images.githubusercontent.com/17730136/55331202-0f972480-5493-11e9-9618-1281b81ee422.png)

**Event log**
/var/log/httpd/ssl_error_log

> [Mon Apr 01 15:47:54.803779 2019] [:error] [pid 21741] [client 10.X.X.X:50427] [INFO] [SP\\Core\\PhpExtensionChecker::checkMandatory] Extensions checked
> [Mon Apr 01 15:47:55.087017 2019] [:error] [pid 21741] [client 10.X.X.X:50427] [INFO] [SP\\Core\\UI\\Theme::saveIcons] Saved icons cache
> [Mon Apr 01 15:47:55.107564 2019] [:error] [pid 21741] [client 10.X.X.X:50427] [INFO] [SP\\Core\\Acl\\Actions::loadCache] Loaded actions cache
> [Mon Apr 01 15:47:55.144628 2019] [:error] [pid 21741] [client 10.X.X.X:50427] script '/var/www/html/index.php' not found or unable to stat, referer: https://syspass.XYZ.de/syspass/
> [Mon Apr 01 15:47:55.158918 2019] [:error] [pid 21741] [client 10.X.X.X:50427] script '/var/www/html/index.php' not found or unable to stat, referer: https://syspass.XYZ.de/syspass/
> [Mon Apr 01 15:47:55.160090 2019] [:error] [pid 30375] [client 10.X.X.X:50428] script '/var/www/html/index.php' not found or unable to stat, referer: https://syspass.XYZ.de/syspass/
> [Mon Apr 01 15:47:55.176647 2019] [:error] [pid 32629] [client 10.X.X.X:50429] script '/var/www/html/index.php' not found or unable to stat, referer: https://syspass.XYZ.de/syspass/
> [Mon Apr 01 15:47:55.177504 2019] [:error] [pid 30369] [client 10.X.X.X:50430] script '/var/www/html/index.php' not found or unable to stat, referer: https://syspass.XYZ.de/syspass/

syspass.log

> 2019-04-01 13:51:08 [INFO] [SP\Core\PhpExtensionChecker::checkMandatory] Extensions checked
> 2019-04-01 13:51:08 [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
> 2019-04-01 13:51:08 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache

**Platform (please complete the following information):**
- OS: CentOS 7
- Webserver: Apache httpd
- PHP: PHP 7.0.33
- Browser: unimportant

**Additional context**
Happens with Windows 10. With macOS this doesn't appear.

**Comment by 90er** [comment]
Status: I let colleages test this issue after updating to 3.1-RC1 this evening and will tell you the next days.

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply...

It seems to be related to a web server configuration, since CSS styles aren't being applied. Please let me know if you're already facing this issue.

Regards.
