### ISSUE TITLE
Syslog mismatch vs Eventlog

### ISSUE THREAD

**Issue by sebagarayco** [nuxsmin/sysPass#1302]
Hi Nuxsmin!, 
We are sending the Syspass logs to Elasticsearch via Syslog. We have noticed that the login information and IP Address is not included on Password View events sent trough Syslog.   They are properly stored on the database and printed in the syspass log.  We would like to know where we should perform the proper changes in order to include these two fields on syslog events. 

syspass.log / db:
2019-03-19 19:39:56 [DEBUG] [SP\Providers\Log\FileLogHandler::updateEvent] show.account.pass;Password viewed;Account: TestAccount

Syslog event:
<15>1 2019-03-29T15:37:27-03:00 ope1sup-syspass syspass 26489 - - syspass.DEBUG: show.account.pass;Password viewed;Account: Asterisk Test [] []

Best regards!

**Comment by nuxsmin** [comment]
Hi @sebagarayco !

I think it would be useful too, so I'll add this information in next release.

Thanks for the feedback!

Best regards

**Comment by sebagarayco** [comment]
Hi Ruben,

Apart from the Client IP address it would be useful to know by syslog which user performed an specific action. 

Exactly as how is reported on the Event Log page. Hope it won’t be to late to include this little change.

Best regards,
Seba
