### ISSUE TITLE
Language present but not selectable

### ISSUE THREAD

**Issue by Matwolf08** [nuxsmin/sysPass#1303]
**sysPass Version**
3.0 (305.19020701) 
Config: 305.19020701 
App: 305.19020701 
DB: 305.19020701

**Describe the bug**
The it_IT locale files are present, but there is no "Italian" in the select box for the language setting.

**To Reproduce**
1. Go to 'Configuration'->'General'
2. Open the language select box
4. See that there is no Italian

If I force the it_IT on the user preference (directly into the database) the strings are translated correctly.

Thanks in advance

**Comment by nuxsmin** [comment]
Hello, it's a bug indeed. I missed to include the language option..It will be available in next release

Thanks for the feedback

**Comment by nuxsmin** [comment]
3.1-RC1 has been released out, please check it out for solving this issue.
