### ISSUE TITLE
SysPass Integration - Active Directory

### ISSUE THREAD

**Issue by Mybiku** [nuxsmin/sysPass#1304]
Hi everyone,

I'm coming here because I've an issue with the soft. I've installed Syspass on a VM Ubuntu x64 bits and integrate this machine in our AD with (Realm join). After I've installed Syspass and all the installation was pretty okay but now I want to integrate Syspass with our AD. But when I configure the LDAP section on the Syspass web interface, I can't connect to our LDAP.

See the screenshot for the LDAP configuration in Syspass :
![1](https://user-images.githubusercontent.com/49200298/55410219-c4007b80-5563-11e9-8535-af6d9df8ff5e.PNG)

You can see a little yellow warning that say "This isn't the real LDAP password" I don't know what is ?

The Syslogs : 
2019-04-02 16:16:55 [EXCEPTION] [N/A] Unable to connect to LDAP server
#0 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(156): SP\Providers\Auth\Ldap\LdapConnection->connectTls()
#1 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(113): SP\Providers\Auth\Ldap\LdapConnection->connect()
#2 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#3 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/Ldap.php(96): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#4 /var/www/html/syspass/lib/SP/Services/Ldap/LdapCheckService.php(51): SP\Providers\Auth\Ldap\Ldap::factory(Object(SP\Providers\Auth\Ldap\LdapParams), Object(SP\Core\Events\EventDispatcher), true)
#5 /var/www/html/syspass/app/modules/web/Controllers/ConfigLdapController.php(152): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#6 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#13 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#14 {main}

And the error is : Unable to connect to LDAP (if TLS is enable)
Or : Connection Bind (49) (if TLS is disabled)

Thank you

**Comment by Edll** [comment]
Hey,
The password is stored in the config, but must be re-entered for each action on the LDAP page if it has been replaced by these 3 stars. 
 
The whole thing is probably meant as a security function.  I found this very confusing in the beginning.

**Comment by Mybiku** [comment]
Hey, thank you for your answer, I understand now, it's just a "security". But it'll not solve my issue :(

**Comment by Edll** [comment]
have you try ldap://192.168.*** in the Server field?

**Comment by Mybiku** [comment]
> have you try ldap://192.168.*** in the Server field?

Yes, same error :/

**Comment by Edll** [comment]
Add Port? ldap://192.168.***:389

**Comment by nuxsmin** [comment]
Hello, it seems that you need your ADS CA certificate in order to stablish a secure connection.

Regards.

**Comment by Mybiku** [comment]
> Hello, it seems that you need your ADS CA certificate in order to stablish a secure connection.
> 
> Regards.

Hmm, what do you mean by I need my ADS CA certificate ? I want to understand.
Thank you for your answer !

**Comment by Xumeiquer** [comment]
Check whether you use TLS or not.

**Comment by nuxsmin** [comment]
@Mybiku 

> Hmm, what do you mean by I need my ADS CA certificate ? I want to understand.

You need to get the Active Directory certification authority (CA) certificate, since PHP LDAP client needs it in order to trust on your AD server certificate.

It seems that your AD server requires security, but it might be implemented through TLS or SSL (LDAPS), so you need to set the correct method.

Regards
