### ISSUE TITLE
Unable to import users from Active Directory

### ISSUE THREAD

**Issue by Xumeiquer** [nuxsmin/sysPass#1305]
**sysPass Version**
3.0 (305.19020701)  - Docker version

**Describe the bug**
Active Directory import does not work. It founds same users, but non is imported.

**To Reproduce**

**Expected behavior**
I expect that the users get imported into syspass

**Screenshots**
See attachemt

**Event log**
No errors show up

**Platform (please complete the following information):**
 - OS: CentoOS 7
 - Browser: Chrome
 - Docker: 18.06.1-ce

**Additional context**
![Screenshot_1](https://user-images.githubusercontent.com/2176256/55472335-257c2500-560c-11e9-8579-4d583e15f6ec.png)

**Comment by nuxsmin** [comment]
Hello, you need to set the correct login and name attributes since it will take them when importing the users. If one of them is missing, the user won't be imported

Regards
