### ISSUE TITLE
V3 Search does not work on iOS or Safari

### ISSUE THREAD

**Issue by anthillinc** [nuxsmin/sysPass#1308]
Tested on iPad and iPhone. After login, search does not work... i.e. no credentials can actually be found because cannot search for any terms. Same on Safari.

We used V2 for several years, recently upgraded to V3 specifically so we could use iOS (i.e. there's an iPad in the V3 feature list.

Thanks, Daniel.

**Comment by anthillinc** [comment]
Hello All,

I also tested the demo site with Safari and on iOS and it has the same problem. It seems this same issue was reported and fixed 2 years ago, see issue #502.

V3 works fine on Mac using other browsers (not Safari), but doesn't work on any browser on iOS (Safari, Chrome, Edge). 

Thanks, Daniel

**Comment by hswfuego** [comment]
Hello all, 

we have also multiple users reporting about this issue.  They cannot activate search with keyword by hitting Enter on IOS and safari or chrome. After adjusting the result count slider results appear. 

This would be a much appreciated fix.

**Comment by djsmiley05** [comment]
Hello,

Safari on mac OS not working :(
Waiting for the fix also :) Thanks!

**Comment by stuba** [comment]
I can confirm that search does work only when selecting for example customer.

**Comment by nuxsmin** [comment]
Hello, I've done some changes on 3.1 (to be released yet) but unfortunately I can't test it on Safari browser. Please let me know if it works fine.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
3.1-RC1 has been released out, please check it out for solving this issue.

**Comment by djsmiley05** [comment]
Its working as expected. Thank you for the fix!

**Comment by nuxsmin** [comment]
@djsmiley05 thanks for the feedback!
