### ISSUE TITLE
Error al crear el usuario "admin"

### ISSUE THREAD

**Issue by jrtoocool** [nuxsmin/sysPass#131]
He instalado todo lo que dice en la wiki, trato de instalar en Centos 7, solo tube un warning istalando json, a qué se debe este error?.

![image](https://cloud.githubusercontent.com/assets/1266442/10180517/7d192ae6-66d3-11e5-9db2-c8f2782f48e5.png)

**Comment by nuxsmin** [comment]
Hola, es un error bastante inusual que ocurre casi al final del proceso de instalación, ya que la BD ya ha sido instalada. Prueba a mirar en el log del servidor web (en Apache /var/log/httpd/error.log). Puede ser que no tengas instalado mcrypt?

**Comment by nuxsmin** [comment]
Hola, has podido mirar los logs?
