### ISSUE TITLE
Remote Syslog > Improve

### ISSUE THREAD

**Issue by LeDistordu** [nuxsmin/sysPass#1310]
<15>1 2019-04-08T11:43:00+00:00 d85cd5c0080b syspass 2046 - - syspass.DEBUG: show.account.pass;Password viewed;Compte: Hide hide hide hide [] []

d85cd5c0080b > Hostname
syspass > Application Name

For organisation, we need to change application name

Other question : Why syspass.DEBUG ? We are not in Debug mode.

**Comment by LeDistordu** [comment]
It's complicated at every line to understand who the user is, why i dont see user in my log ?

**Comment by nuxsmin** [comment]
Hello, I've done some logging improvements in 3.1 release, which will be available shortly.

> For organisation, we need to change application name

Unfortunately application name is set within the code, but you can easily change it by transforming the message when reaches the syslog server

> Other question : Why syspass.DEBUG ? We are not in Debug mode.

Debug mode can be set either through the application UI (Configuration section) or by editing `lib/Base.php` file. Please check out the latter.

Regards.

**Comment by nuxsmin** [comment]
3.1-RC1 has been released out, please check it out for solving this issue.
