### ISSUE TITLE
Search by regular expressions

### ISSUE THREAD

**Issue by juangarat** [nuxsmin/sysPass#1311]
**Is your feature request related to a problem? Please describe.**
We use the shell a lot and I'm programming a python client so we can get password directly from shell. I'm getting some difficult work with search operations expecting one record, because the search is not exact match. There is cases when I need just an exact match, for example to see if an account already exists.

**Describe the solution you'd like**
It would be really nice to make search by regular expressions, so I can decide if I want an exact match or not. Or make some more interesting search, when I remember some parts of the account name.

**Describe alternatives you've considered**
I can do some logic in the code to lookup the exact match in the results. But I think that we get more search power with Regular Expressions.

**Additional context**
This addional power also applies for use in GUI.

Thanks.

Juan

**Comment by nuxsmin** [comment]
Hello, this would be an useful feature for next release.

Thanks for the feedback!
