### ISSUE TITLE
v3: force password change: Wrong hash or expired

### ISSUE THREAD

**Issue by juangarat** [nuxsmin/sysPass#1314]
**sysPass Version**
3.0 (305.19020701)
Config: 301.19012002
App: 305.19020701
DB: 301.19012002 

I'm running docker syspass version.

**Describe the bug**
We create users and enable force password change. This send's an email to the user with the password reset link.
The user click de link and when it submit the new password, an error ocurrs.

**To Reproduce**
1. Create a new user
2. Enable Force Password Change
3. Check the user's mail, and click the password reset link.
4. Fill both fields with new password and click CHANGE.
5. Error happens.

**Expected behavior**
That the user can change the password when we force to.

**Screenshots**

**Event log**
The error is:
`[EXCEPTION] [N/A] Wrong hash or expired\n#0 /var/www/html/sysPass/app/modules/web/Controllers/UserPassResetController.php(203): SP\\Services\\UserPassRecover\\UserPassRecoverService->getUserIdForHash('6f42bc7c96016af...')\n#1 [internal function]: SP\\Modules\\Web\\Controllers\\UserPassResetController->saveResetAction()\n#2 /var/www/html/sysPass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)\n#3 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#4 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#7 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#8 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')\n#9 {main}, referer: https://xxxxxxx/index.php?r=userPassReset/reset/6f42bc7c96016af1b486893a4ce5c62d 
`

**Platform (please complete the following information):**
 - OS: Linux, CentOS 7
 - docker-ce-18.03.1, Image: syspass/syspass:3.0.5
 - Browser: Firefox

**Additional context**
We force the change at user creation moment.
it does not always happen. Sometings the same steps works fine.
We are at GMT -3 Timezone.
The server running syspass docker instance is in UTC Timezone.

**Comment by nuxsmin** [comment]
Hello, it seems that recovery time (1 hour) would have been expired, so it will show up that message.

Regards
