### ISSUE TITLE
Several doubts about the operation

### ISSUE THREAD

**Issue by maurorosa123** [nuxsmin/sysPass#1315]
Hello everyone. I am implementing my first syspass server and am taking the time to document the installation steps and configuration steps. Before completing the document I would like to post some questions and ask for help, as I found the documentation on the site poor and also could not find much here. Any doubts are about the administrative use and I would like to know if I am certain of the operation of the tool or if I am doing something wrong. Anyway, there it goes.

1 - Field CLIENTS: My environment is for a single company so I used department names in the CUSTOMERS field. I do not want any users to be able to create / delete CLIENTS. For this, I did not grant these permissions on users' profiles. But initially, after the creation of the CLIENTS, all the users can see all the CLIENTS. To make the CLIENT of each department restricted to the users of the department itself, I had to create a symbolic account for each CLIENT and associate this symbolic account with the department group (yes, I also created a group for each department). My question is this: Am I taking the right action? Would this be a good practice for my environment? Does anyone suggest a different practice?

2 - Can anyone suggest me some applications for the CATEGORIES field? Being this field, a required field for creating accounts, what do people usually put in this field? Currently I put names like Login, Licensing, Printers. However, the CATEGORIES field is a field common to all users and I can not restrict this field the way I do with the CUSTOMERS field. What is the best applicability for this field?

3 - By enabling the SECONDARY GROUP ACCESS setting in the setup menu, I can grant permissions to users from the secondary account permissions. For example, a user u1 is part of the primary group pg1 and the secondary group sg1. With the SECONDARY GROUP ACCESS setting enabled, I can grant privilege to user u1 in account ACCOUNT1 granting secondary permission to group SG1 in account ACCOUNT1. (Was the reasoning clear? It's really hard to explain). This being a true fact, I wanted to know what the resulting permission is in the following case: Account1 with primary group X and secondary group Y. User with group PRIMARY Y. In this scenario, the account would be displayed to the user, but let's go a little deeper ... This user's profile allows editing / deleting accounts, but the privilege level of this account for group Y is ONLY VISUALIZATION. In this case, what would be the resulting user permission for this account? In my tests, the resulting permission was cumulative. Is this right?

4 - My environment has internal users (such as syspass admin) and users imported from AD. However I realize that when my AD server is offline I can not access syspass even with internal users. That does not seem right to me. Do I need to do any additional configuration to be able to access syspass with internal users even when the AD server is offline?

**Comment by maurorosa123** [comment]
Anybody?

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply, a bit busy indeed...

> 1 - Field CLIENTS: My environment is for a single company so I used department names in the CUSTOMERS field. I do not want any users to be able to create / delete CLIENTS. For this, I did not grant these permissions on users' profiles. But initially, after the creation of the CLIENTS, all the users can see all the CLIENTS. To make the CLIENT of each department restricted to the users of the department itself, I had to create a symbolic account for each CLIENT and associate this symbolic account with the department group (yes, I also created a group for each department). My question is this: Am I taking the right action? Would this be a good practice for my environment? Does anyone suggest a different practice?

Clients can only be seen by users who have permission over them.

> 2 - Can anyone suggest me some applications for the CATEGORIES field? Being this field, a required field for creating accounts, what do people usually put in this field? Currently I put names like Login, Licensing, Printers. However, the CATEGORIES field is a field common to all users and I can not restrict this field the way I do with the CUSTOMERS field. What is the best applicability for this field?

That is only a filtering stuff, so I used to use them like global containers (HTTP, SSH, RDP, etc.). Its behavior might be overridden by tags which have been implemented later so categories are there as a legacy feature.

> 3 - By enabling the SECONDARY GROUP ACCESS setting in the setup menu, I can grant permissions to users from the secondary account permissions. For example, a user u1 is part of the primary group pg1 and the secondary group sg1. With the SECONDARY GROUP ACCESS setting enabled, I can grant privilege to user u1 in account ACCOUNT1 granting secondary permission to group SG1 in account ACCOUNT1. (Was the reasoning clear? It's really hard to explain). This being a true fact, I wanted to know what the resulting permission is in the following case: Account1 with primary group X and secondary group Y. User with group PRIMARY Y. In this scenario, the account would be displayed to the user, but let's go a little deeper ... This user's profile allows editing / deleting accounts, but the privilege level of this account for group Y is ONLY VISUALIZATION. In this case, what would be the resulting user permission for this account? In my tests, the resulting permission was cumulative. Is this right?

"Secondary Group Access" feature is intended to grant permission to users who are listed in secondary groups BUT their primary group does not match with the group which you granted permission to in the account. In your use case, the user should only have read-only permission over the account.

> 4 - My environment has internal users (such as syspass admin) and users imported from AD. However I realize that when my AD server is offline I can not access syspass even with internal users. That does not seem right to me. Do I need to do any additional configuration to be able to access syspass with internal users even when the AD server is offline?

sysPass will allow to log in even when the LDAP server is down and internal users will always log in regardless the LDAP state.

Regards
