### ISSUE TITLE
Problem with update to 3.0.5

### ISSUE THREAD

**Issue by nixjua** [nuxsmin/sysPass#1316]
I try to upgrade sysPass 2.1 to 3.0.5, but when I try to run update process I get error message "Error while updating the database"

I view the ssl_error.log and the line before the message is :
 SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'CustomFieldType' already exists\n#0 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(172): PDO->exec('CREATE TABLE `C...')\n#1 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(107): SP\\Services\\Upgrade\\UpgradeDatabaseService->applyUpgrade('300.18010101')\n#2 /var/www/html/syspass/app/modules/web/Controllers/UpgradeController.php(85): SP\\Services\\Upgrade\\UpgradeDatabaseService->upgrade('0.0', Object(SP\\Config\\ConfigData))\n#3 [internal function]: SP\\Modules\\Web\\Controllers\\UpgradeController->upgradeAction()\n#4 /var/www/html/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)\n#5 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#7 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#8 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#9 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#10 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')\n#11 {main}, referer: https://192.168.1.80/syspass/index.php?r=upgrade/index

**Comment by nuxsmin** [comment]
Hello, did you try to resume a previous upgrade?. The table `CustomFieldType` didn't exist on 2.1

Regards

**Comment by nixjua** [comment]
Hello,

Yes, I try to resume previous upgrade.
I search this table on my 2.1 SQL backup, and didnt found any table with this name

**Comment by nuxsmin** [comment]
Hello, 

that's right, as said before: _'The table CustomFieldType didn't exist on 2.1'_

You'll need to restore a previous backup and then start the upgrade again. Why did it fail in first attempt?

Regards

**Comment by nixjua** [comment]
Did you mean restore DB and app? or only I can restore DB and start upgrade again

**Comment by nuxsmin** [comment]
Only the DB

**Comment by nixjua** [comment]
Sorry for many questions, I restore my DB 2.1, did I need to add some values or tags on my original config.xml before I  copied again to syspass/app/conf

Thanks a lot

**Comment by nuxsmin** [comment]
No worries...and no, you don't need to copy again the `config.xml` file, since it will be updated after a successful upgrade.

**Comment by nixjua** [comment]
Hello,

I try to do 3 times upgrade and get the same error

sysPass.log
2019-04-22 00:02:58 [EXCEPTION] [N/A] Error while updating the database
#0 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(107): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade('300.18010101')
#1 /var/www/html/syspass/app/modules/web/Controllers/UpgradeController.php(85): SP\Services\Upgrade\UpgradeDatabaseService->upgrade('0.0', Object(SP\Config\ConfigData))
#2 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#10 {main}

ssl_error_log
[Sun Apr 21 19:02:58.932557 2019] [php7:notice] [pid 7281] [client 10.1.1.84:50458] [EXCEPTION] [N/A] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspass.track' doesn't exist\n#0 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(172): PDO->exec('ALTER TABLE tra...')\n#1 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(107): SP\\Services\\Upgrade\\UpgradeDatabaseService->applyUpgrade('300.18010101')\n#2 /var/www/html/syspass/app/modules/web/Controllers/UpgradeController.php(85): SP\\Services\\Upgrade\\UpgradeDatabaseService->upgrade('0.0', Object(SP\\Config\\ConfigData))\n#3 [internal function]: SP\\Modules\\Web\\Controllers\\UpgradeController->upgradeAction()\n#4 /var/www/html/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)\n#5 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#7 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#8 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#9 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#10 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')\n#11 {main}, referer: https://10.1.1.80/syspass/index.php?r=upgrade/index
[Sun Apr 21 19:02:58.934261 2019] [php7:notice] [pid 7281] [client 10.1.1.84:50458] [EXCEPTION] [N/A] Error while updating the database\n#0 /var/www/html/syspass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(107): SP\\Services\\Upgrade\\UpgradeDatabaseService->applyUpgrade('300.18010101')\n#1 /var/www/html/syspass/app/modules/web/Controllers/UpgradeController.php(85): SP\\Services\\Upgrade\\UpgradeDatabaseService->upgrade('0.0', Object(SP\\Config\\ConfigData))\n#2 [internal function]: SP\\Modules\\Web\\Controllers\\UpgradeController->upgradeAction()\n#3 /var/www/html/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)\n#4 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#7 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#8 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#9 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')\n#10 {main}, referer: https://10.1.1.80/syspass/index.php?r=upgrade/index

Steps I do
1.- Restore DB 2.1
2,.- Put my config.xml 2.1 into the new SysPass
3.- Open mi browser and open https://10.1.1.80/syspass
4.- Get the value from upgradeKey tag
5.- Put this value on the text "Security Code"
6.- Check "I've done a full sysPass backup"
7.- Click on Update button

And popup message show me the error

**Comment by nuxsmin** [comment]
Hello, are there any more messages in `syspass.log`?

**Comment by nixjua** [comment]
Do you need to see entire syspass.log?

**Comment by nixjua** [comment]
> Hello, are there any more messages in `syspass.log`?

This is the entire file
[syspass.log](https://github.com/nuxsmin/sysPass/files/3124554/syspass.log)
