### ISSUE TITLE
Translations -

### ISSUE THREAD

**Issue by luolenny** [nuxsmin/sysPass#1318]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is there any plan to support Chinese locale?  If translation help needed, I could help. Yet I don't know how to help. I searched POEditor  yet still did not catch the point. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nuxsmin** [comment]
Hello, Chinese locale is available in PoEditor. Please sign in to request access to this language: https://poeditor.com/join/project/fmlsBuugyv

Regards
