### ISSUE TITLE
Language Spanish only

### ISSUE THREAD

**Issue by steevegldev** [nuxsmin/sysPass#132]
I can't switch language. Language Spanish only

There is what is just tried.

Removed sysPass's folder
Dropped sysPass's database
git clone https://github.com/nuxsmin/sysPass.git
Set owner apache (www-data) on sysPass's folder and sub-folder
Set permission 750 on sysPass's folder and sub-folder
Opened chrome and get to the sysPass's home page (default language: Spanish).
Filled the form --> "Instalación finalizada"
Logged in, get to setting, set language to English, get to Admin profile, set language to English
(Still Spanish) Logged out, logged in.
Still Spanish
git log --abbrev-commit --name-status HEAD^..HEAD
commit c3675d7
Author: nuxsmin nuxsmin@syspass.org
Date: Fri Oct 2 14:44:19 2015 +0200
* [MOD] Update translations

Versión sysPass 1.2.0.03
Base de Datos SERVER_VERSION : 5.5.5-10.0.20-MariaDB-0+deb8u1 
CLIENT_VERSION : mysqlnd 5.0.11-dev - 20120503
SERVER_INFO : Uptime: 84264 Threads: 1 Questions: 6261 Slow queries: 0 Opens: 78 Flush tables: 1 Open tables: 105 Queries per second avg: 0.074 
CONNECTION_STATUS : Localhost via UNIX socket 
Nombre: syspass@localhost
PHP Versión: 5.6.13-0+deb8u1 
Extensiones: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, mysqlnd, PDO, apcu, curl, gd, imagick, imap, intl, json, ldap, mcrypt, memcache, mysql, mysqli, pdo_mysql, pdo_sqlite, pspell, readline, recode, snmp, sqlite3, tidy, xmlrpc, xsl, mhash, apc, Zend OPcache 
Memoria Usada: 768 KB 
Usuario: www-data
Servidor Apache/2.4.10 (Debian)

**Comment by nuxsmin** [comment]
Hi, did you installed the right locales?

In debian, <code>dpkg --reconfigure locales</code> and set it to en_US-utf8

**Comment by steevegldev** [comment]
I never had to do this, so by default I have this:

dpkg-reconfigure locales:

[*] en_CA.UTF-8 UTF-8

**Comment by steevegldev** [comment]
Did some test:

Set as default:
en_US.UTF-8 UTF-8 ==> SUCCESS
en_CA.UTF-8 UTF-8 == > FAIL
none == > FAIL

**Comment by nuxsmin** [comment]
Great, you don't have to set it as default., only installed. 

I've 7 locales set on my dev environment (local and hosting) and no issues.

**Comment by nuxsmin** [comment]
This kind of issues can be avoided by packing as many locales as variants there are to every language, but it would get more difficult to maintain all the languages up to date, because every variant has its own translation file, for yours it would have another locales directory for with the message.mo file in it, the same as en_US translation, so it would be duplicated!

Hope you find it useful ;)
