### ISSUE TITLE
database user access/permission

### ISSUE THREAD

**Issue by fa-itnoobs** [nuxsmin/sysPass#1322]
**sysPass Version**
3.0

**Describe the question**
Hi nuxmin,

Came across your project from Reddit suggestions and Google search, very interesting and thanks.

I have a MySQL server that holds a few databases and SysPass database will also go on there too. SysPass configuration (via web) requires a database user that can create the database, however I prefer to create the database and provide complete access only to that database for SysPass. 

I've done something similar to set up phpIPAM, where I created the database and imported the schema manually (there's actually an option to select manually created database via web config).

Is this possible for SysPass? Maybe a simple configuration change? I can see some .sql files in the schema folder, which I assume can be used for a manual setup?

Thanks

**Screenshots**

**Platform (please complete the following information):**
 - OS: Ubuntu Linux
 - OS 16.04.1 LTS
 - Browser Chrome & Firefox

**Additional context**
Had a look at this https://github.com/nuxsmin/sysPass/issues/687 and noticed your comment **That error is most likely because the MySQL credentials provided are not granted to create the sysPass database user.**

**Comment by nuxsmin** [comment]
Hello @fa-itnoobs ,

The way you're looking for is achieved by using 'Hosting Mode', which expects to have a database created but only the database and not the structure. It will populate the new database by using the provided user credentials, which would have permissions on this database. In this way you don't need to provide a 'super' admin user.

I hope this solved your question :wink:

Regards
