### ISSUE TITLE
Problem with upgrade to 3.0.5

### ISSUE THREAD

**Issue by nixjua** [nuxsmin/sysPass#1324]
Hello,

I try to upgrade from 2.1 to 3.0.5 but I receive problems to upgrade database.

I attach the entire syspass.log

[syspass.log](https://github.com/nuxsmin/sysPass/files/3125876/syspass.log)

**Comment by nuxsmin** [comment]
Hello, which version are you upgrading from?. It seems that your version does not have `track` table. It was added since  2.1.0.17022601 so you would need to upgrade to the latest 2.1 version and then upgrade to v3.

Regards

**Comment by nuxsmin** [comment]
Please, every time you open an issue you should fill in the issue template for a better understanding of the issue and more information about the environment.

Thanks

**Comment by nixjua** [comment]
Sorry,

I try to upgrade from 2.1 (2.1.16.18061901) to 3.0.5

Current
sysPass version | 2.1 (2.1.16.18061901)
-- | --
Database | SERVER_VERSION : 5.7.25 CLIENT_VERSION : mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $ SERVER_INFO : Uptime: 5232899 Threads: 1 Questions: 124593 Slow queries: 0 Opens: 589 Flush tables: 1 Open tables: 580 Queries per second avg: 0.023 CONNECTION_STATUS : Localhost via UNIX socket Name: syspass@localhost
PHP | Version: 5.6.38 Extensions: Core, date, ereg, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, ldap, exif, mcrypt, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, zip, mysql, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, json, mhash Used Memory: 3840 KB User: apache
Server | Apache/2.4.6 () OpenSSL/1.0.2k-fips PHP/5.6.38

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply (a bit busy indeed...)

The error `Table 'syspass.track' doesn't exist` states that there is a missing table, could you check the database for this table?

**Comment by nixjua** [comment]
Hi,

But that table exist

MariaDB [syspass3]> show tables;
+-----------------------+
| Tables_in_syspass3    |
+-----------------------+
| CustomFieldData       |
| CustomFieldDefinition |
| CustomFieldType       |
| EventLog              |
| accFavorites          |
| accFiles              |
| accGroups             |
| accHistory            |
| accTags               |
| accUsers              |
| account_data_v        |
| account_search_v      |
| accounts              |
| authTokens            |
| categories            |
| config                |
| customers             |
| notices               |
| plugins               |
| publicLinks           |
| tags                  |
| **track**                 |
| usrData               |
| usrGroups             |
| usrPassRecover        |
| usrProfiles           |
| usrToGroups           |
+-----------------------+


MariaDB [syspass3]> desc track;
+--------------+----------------------+------+-----+---------+----------------+
| Field        | Type                 | Null | Key | Default | Extra          |
+--------------+----------------------+------+-----+---------+----------------+
| track_id     | int(10) unsigned     | NO   | PRI | NULL    | auto_increment |
| track_userId | smallint(5) unsigned | YES  |     | NULL    |                |
| track_source | varchar(100)         | NO   |     | NULL    |                |
| track_time   | int(10) unsigned     | NO   |     | NULL    |                |
| track_ipv4   | binary(4)            | NO   |     | NULL    |                |
| track_ipv6   | binary(16)           | YES  |     | NULL    |                |
+--------------+----------------------+------+-----+---------+----------------+

**Comment by nixjua** [comment]
Hi,

Any sugestion to solve this issue

**Comment by nuxsmin** [comment]
Hi, sorry for the late reply...

Why the log file is pointing to `syspass` table and you're displaying `syspass3` table?

Regards
