### ISSUE TITLE
Problem with upgrade from 305.19020701 to 310.19012201

### ISSUE THREAD

**Issue by drewlsvern** [nuxsmin/sysPass#1326]
**sysPass Version**
Attempting to upgrade from 305.19020701 to 310.19012201

**Describe the bug**
Receive an error when attempting to upgrade SysPass: Error while updating the database.

**To Reproduce**
1. Go to syspass website.
2. Enter upgrade key
3. Click 'I've done a full sysPass backup'
4. Click 'Update', click 'Accept when prompted'.
5. Receive the error stated below.

**Expected behavior**
The upgrade to complete successfully.

**Event log**
[2019-04-30 17:58:38] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-04-30 17:58:38] syspass.INFO: logger {"message":"Saved icons cache","caller":"SP\Core\UI\Theme::saveIcons"}
[2019-04-30 17:58:38] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2019-04-30 17:58:38] syspass.DEBUG: upgrade.db.start {"message":"Update DB","user":"N/A","address":"","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::upgrade"} []
[2019-04-30 17:58:38] syspass.DEBUG: upgrade.db.process {"message":"Version: 310.19012201","user":"N/A","address":"","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-04-30 17:58:39] syspass.DEBUG: upgrade.db.process {"message":"Version: 310.19012201","user":"N/A","address":"","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-04-30 17:58:39] syspass.EXCEPTION: logger {"message":"SQLSTATE[42000]: Syntax error or access violation: 1171 All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
#0 /home/sp/public_html/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(173): PDO->exec('create table Pl...')
#1 /home/sp/public_html/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade('310.19012201')
#2 /home/sp/public_html/app/modules/web/Controllers/UpgradeController.php(89): SP\Services\Upgrade\UpgradeDatabaseService->upgrade('305.19020701', Object(SP\Config\ConfigData))
#3 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#4 /home/sp/public_html/lib/SP/Bootstrap.php(240): call_user_func_array(Array, Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /home/sp/public_html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /home/sp/public_html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#8 /home/sp/public_html/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#9 /home/sp/public_html/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#10 /home/sp/public_html/index.php(28): require('/home/sp/public...')
#11 {main}","caller":"N/A"}
[2019-04-30 17:58:39] syspass.EXCEPTION: logger {"message":"Error while updating the database
#0 /home/sp/public_html/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade('310.19012201')
#1 /home/sp/public_html/app/modules/web/Controllers/UpgradeController.php(89): SP\Services\Upgrade\UpgradeDatabaseService->upgrade('305.19020701', Object(SP\Config\ConfigData))
#2 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#3 /home/sp/public_html/lib/SP/Bootstrap.php(240): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /home/sp/public_html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /home/sp/public_html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /home/sp/public_html/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /home/sp/public_html/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#9 /home/sp/public_html/index.php(28): require('/home/sp/public...')
#10 {main}","caller":"N/A"}

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04 LTS - Apache Web Server 2.4.29
 - MySQL version: 5.7.26
 - Browser: Chrome

**Additional context**

**Comment by nuxsmin** [comment]
Hello, it has been fixed in latest commit. I didn't notice in my database, since this behavior was deprecated from MySQL 5.7, in previous versions it silently creates the keys by setting a "NOT NULL" field.

Thanks for the feedback!
