### ISSUE TITLE
What is the problem

### ISSUE THREAD

**Issue by coldcry1** [nuxsmin/sysPass#1327]
I am using syspass v1.0.8;

I am getting this error on a different server that I reinstalled

What's the solution?

![Untitled](https://user-images.githubusercontent.com/50196079/57062676-b418ac00-6c75-11e9-855d-c0c2a99ab740.jpg)

**Comment by nuxsmin** [comment]
Hello, you've restored the accounts with a  different master password, so sysPass won't able to decrypt them.

Please, this version (v1) is really old, consider upgrading to v3. The upgrade path is to apply any update until the latest v1, upgrade to v2.1 and then to v3.

Regards.

**Comment by coldcry1** [comment]
if we forgot the masterpwd, what we need to do?

**Comment by nuxsmin** [comment]
Unfortunately, there's no way to recover the master password.
