### ISSUE TITLE
Error while searching the group RDN

### ISSUE THREAD

**Issue by BorjaMarco** [nuxsmin/sysPass#1328]
Hi guys

I am doing the configuration of the Active directory and I leave here some images so you can see if I have put some incorrect information

![Captura1](https://user-images.githubusercontent.com/50232144/57128546-0e0f9380-6d94-11e9-9eb9-5851850fff0e.PNG)

When I go to the option to check to see if it works, it tells me the error
Error while searching the group RDN

Because you see the picture is that the password is not the good one but if it is the good one, I think there must be a failure that is not reading the destination folder

**Comment by nuxsmin** [comment]
Hello, I'm wondering why you're using an OU as group name. It should be a CN instead...

Regards

**Comment by BorjaMarco** [comment]
> Hello, I'm wondering why you're using an OU as group name. It should be a CN instead...
> 
> Regards

is how it is put in the files of the active directory

**Comment by BorjaMarco** [comment]
Thank you
It is already solved and thanks for your help

**Comment by nuxsmin** [comment]
It sounds good. Thanks for the feedback!
