### ISSUE TITLE
[Documentation - API] tagsId wrong label

### ISSUE THREAD

**Issue by sebagarayco** [nuxsmin/sysPass#1329]
I've been using the account/create api method and discovered that when using tagsId the creation doesn't work. After a couple of tests I figured out that the proper entry is tagsid (all lower case).

Regards!

**Comment by nuxsmin** [comment]
Hello, it's really weird, since the method that handles the account creation looks for `tagsId` https://github.com/nuxsmin/sysPass/blob/ea9b6ee1fd0a9df5d923673edf261c3f49683a61/app/modules/api/Controllers/AccountController.php#L181

Regards
