### ISSUE TITLE
AD and syspass 1.2Rc3

### ISSUE THREAD

**Issue by JvdW** [nuxsmin/sysPass#133]
I'm having issues connecting syspass1.2rc3 to my Samba4 AD domain. This used to work with syspass1.1.
I upgraded 1.1 to 1.2rc1 and now to rc3 but still no go. The check LDAP button tells me that the LDAP parameters are not set. I added a couple of error_log("Ldapserver:".$frmLdapServer",3,"/var/services/syspass.log") to  ajax_checkLdap.php and indeed all the $frmXYZ vars are empty while they are written correctly in the config.
Can I further debug this or do you need more information?
Syspass is installed on my Synology DS214play and working well except for the ldap connection. 1.1 works OK.

Joop

**Comment by nuxsmin** [comment]
Hi, you're right, the javascript LDAP check function is pointing to a wrong form id. Let me do some more tests and it'll be merged into RC4 release. However, you should be able to login through LDAP auth, because this function is only used for checking purposes. 

I'll let you know when it's fixed.

**Comment by nuxsmin** [comment]
Hi, can you test the latest release?

**Comment by JvdW** [comment]
On 5-10-2015 16:36, nuxsmin wrote:
>
> Hi, can you test the latest release?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nuxsmin/sysPass/issues/133#issuecomment-145548539>.
>
Yes I can, later today (its now 16:45 UTC+2), say around 20:30

Joop

**Comment by JvdW** [comment]
Tested and the checkldap now functions BUT when trying to login it won't work.
Adding more error_log statements but now to ldap.class.php I see that ldapServer is not set. Setting ldapServer myself to the address of my Samba4 AD will let me login but that ends with an internal error. Adding even more logging shows that in ldapads.class the parsing of the ip number doesn't work. Replacing it with my servername, domname.ad.internaldom.local let it go further.

    public static function checkLDAPParams()
    {
        self::$_isADS = Config::getValue('ldap_ads', false);
        self::$_searchBase = Config::getValue('ldap_base');
        self::$_ldapServer = (!self::$_isADS) ? Config::getValue('ldap_server') : LdapADS::getADServer(Config::getValue('ldap_server'));
	    self::$_ldapServer = '192.168.1.1';
        self::$_bindDN = Config::getValue('ldap_binduser');
        self::$_bindPass = Config::getValue('ldap_bindpass');
        self::$_ldapGroup = Config::getValue('ldap_group', '*');
        error_log("isADS:".self::$_isADS."\n",3,"/var/services/tmp/syspass.log");
        error_log("SearchBase:".self::$_searchBase."\n",3,"/var/services/tmp/syspass.log");
        error_log("LdapServer:".self::$_ldapServer."\n",3,"/var/services/tmp/syspass.log");
        error_log("BindDN".self::$_bindDN."\n",3,"/var/services/tmp/syspass.log");
        error_log("BindPass:".self::$_bindPass."\n",3,"/var/services/tmp/syspass.log");
        error_log("LdapGroup:".self::$_ldapGroup."\n",3,"/var/services/tmp/syspass.log");

Then I saw the following in the eventlog of syspass:
    SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_hashSalt' cannot be null(0)
    SQL: '
    INSERT INTO usrData SET user_name = :name,
    user_groupId = :groupId,
    user_login = :login,
    user_pass = :pass,
    user_hashSalt = :hashSalt,
    user_email = :email,
    user_notes = :notes,
    user_profileId = :profileId,
    user_isLdap = 1,user_isDisabled = :isDisabled' 
	
Thats about as far as I can get without starting to look at a php debugger :-)

If you need more info, please let me know

Joop

**Comment by nuxsmin** [comment]
Hi, the server issue is related to the function that picks a random server from ADS DNS records, which only accepts servernames and not ip addresses. Now there is a regex to prevent this.

The user issue is because a wrong key supplied to the array that contains the encrypted user password.

These issues has been fixed in the last commit.

Thanks for the feedback ;)

**Comment by gleisonbaioco** [comment]
Hi Nuxsmin,

Will you make available a new version of Syspass in order to correct this bug?

Thank you a lot, Gleison.

**Comment by JvdW** [comment]
On 5-10-2015 23:04, nuxsmin wrote:
>
> Hi, the server issue is related to the function that picks a random
> server from ADS DNS records, which only accepts servernames and not ip
> addresses. Now there is a regex to prevent this.
>
> The user issue is because a wrong key supplied to the array that
> contains the encrypted user password.
>
> These issues has been fixed in the last commit.
>
Did a git pull and retried all my tests --> OK :-)

One thing, but suspect by design, is that the first time an AD user logs
in its account is set to disable and must be disabled by an admin.

One more thing: if you click on the staircase lines left of the search,
which says 'clear' then the found entries beneath it are changing colors.

Joop

**Comment by nuxsmin** [comment]
Great!!

The disabled account behavior is to force a double check of the user's default profile and group, because the default ones couldn't be suitable for that user.

About changing colors, it's a new functionality that highlights the accounts that have the same customer. There are a few colors available and they are randomly picked, so you can get some accounts that shares the same color. Basically it's a visual helper.

Hope you find it useful ;)

**Comment by nuxsmin** [comment]
Changing colors have been removed in the latest release, now colors are fixed until the session ends.
