### ISSUE TITLE
Update to version 3.1.0-rc1 fails

### ISSUE THREAD

**Issue by sysant01** [nuxsmin/sysPass#1330]
**sysPass Version**
3.0 (305.19020701) 

**Describe the bug**
trying to upgrade to version  3.1.0-rc1 from version 3.0 returns an error, screenshot attached

**To Reproduce**
I have a functional 3.0 version of syspass installed. I downloaded the  3.1.0-rc1 tar.gz and overwrite the relevant files, the next time i open syspass got the upgrade screen, entered the security code and got the error. 

**Expected behavior**
Upgrade to version 3.1.0-rc1

**Screenshots**

![syspass](https://user-images.githubusercontent.com/50252094/57168708-8bed9200-6dc8-11e9-90a2-c130382eb1ab.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 
 - OS: 18.04
 - Browser: Firefox 66.0.3

Many thanks for develop syspass!

**Comment by nuxsmin** [comment]
Hello, RC2 was released after noticed about an issue with newer MySQL versions. Please, upgrade to RC2 instead.

Thanks for the feedback!

Regards

**Comment by sysant01** [comment]
Hi nuxmin,  Unfortunately the problem persists on RC2.  Regarding MySQL i am running  version: 5.7.26-0ubuntu0.18.04.1

Thanks a lot

**Comment by anth69** [comment]
Hi @nuxsmin ; same goes for me trying to upgrade a test version from 3.0.5 to 3.1-rc4 ;
looks like **31019012201.sql** provides some errors : 
First it tries to alter the table Plugin which seems to provide this error : 
`syspass.EXCEPTION: logger {"message":"SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'versionLevel'`

Then if I  try to remove this part which tries to duplicate the versionLevel, I end up with an error about the foreign key constraint : 

syspass.EXCEPTION: logger {"message":"SQLSTATE[HY000]: General error: 1005 Can't create table `syspass_test`.`PluginData` (errno: 150 "Foreign key constraint is incorrectly formed")

Any idea ?

**Comment by nuxsmin** [comment]
Hi @anth69 !

Are you trying to upgrade over a failed previous upgrade?. That column is not present on previous version.

Regards

**Comment by anth69** [comment]
Nope, we had 2 versions of syspass running on the same server (syspass & syspass_test) both on 3.0.5

Both use separates databases.

We tried to upgrade the syspass_test one straight from 3.0.5 to 3.1-Rc4 and ran into this error.

**Comment by nuxsmin** [comment]
Could you add `upgrade.` (note the dot) in events logging list before performing the upgrade?. It will throw some useful messages into `syspass.log` file.
