### ISSUE TITLE
Error 500 after installtion

### ISSUE THREAD

**Issue by computergott** [nuxsmin/sysPass#1331]
**sysPass Version**
3.1.0.19043001-rc2

**Describe the bug**
After the Installation I got a Error 500

**Platform (please complete the following information):**
- Debian 9
- No Docker Installation -> https://syspass-doc.readthedocs.io/en/3.0/installing/debian9.html

**Additional context**
Error.log:

[Sun May 05 18:33:05.676734 2019] [php7:warn] [pid 33530] [client 192.168.2.30:59938] PHP Warning:  require(/var/www/html/syspass/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/syspass/lib/Base.php on line 65
[Sun May 05 18:33:05.676777 2019] [php7:error] [pid 33530] [client 192.168.2.30:59938] PHP Fatal error:  require(): Failed opening required '/var/www/html/syspass/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/syspass/lib/Base.php on line 65

There is no /vendor/ Directory

**Comment by nuxsmin** [comment]
Hello, did you install composer and download the dependencies? 

sysPass requires composer in order to get its dependencies.

https://doc.syspass.org/en/3.0/installing/debian9.html#installing-dependencies

Regards
