### ISSUE TITLE
Help with groups and users with the Active Directory

### ISSUE THREAD

**Issue by BorjaMarco** [nuxsmin/sysPass#1332]
Hello I have configured the active directory and tried to enter with the users that I have created in the directory and it does not tell me

![Captura13](https://user-images.githubusercontent.com/50232144/57214267-c1bd9100-6fe9-11e9-8d12-d969d428a972.PNG)

The user does not have associated groups

but in the active directory that user I created has a group but I do not know if the group as the user I have to create it within syspass

**Comment by nuxsmin** [comment]
Hello, it seems that the group is not located within the LDAP search base. 

LDAP groups do not match with sysPass groups, so they aren't linked in any way.

Regards

**Comment by BorjaMarco** [comment]
Hello, I show you some pictures that are the groups created in the syspass and are the same as those in the active directory
![grupos1](https://user-images.githubusercontent.com/50232144/57357805-1f7de480-7174-11e9-8669-8a5d83c55559.PNG)
![grupos2](https://user-images.githubusercontent.com/50232144/57357811-21e03e80-7174-11e9-9d48-2df037c5c154.PNG)

Tried to enter with a user who are within those groups and I get the same error

**Comment by BorjaMarco** [comment]
Hola,
He conseguido importar los grupos pero estoy intentando importar los usuarios dentro del syspass y no me deja o no se hacerlo, para la importación de usuarios de directorio activo al syspass hay que hacerlo de alguna manera en especial

**Comment by BorjaMarco** [comment]
Pues yo intento entrar con los usuarios que tengo creados en el directo activo y me dice login incorrecto
