### ISSUE TITLE
old user pw is asked at login (pw has not been changed, LDAP / FreeIPA account)

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [nuxsmin/sysPass#1334]
**sysPass Version**
3.0 (305.19020701)

**Describe the bug**
- while a certain user tries to logon, that user is asked for his old login password + a master key to complete the authentication process 
- using the current (not old pw) + master key will let the user login
- LDAP / FreeIPA is used for identity management
- none of the other users has the problem

**To Reproduce**
1. Go to syspass URL
2. Try to Login
3. See error

**Expected behavior**
Login should be working as normal. The described behavior should only happen after changing the pw in LDAP/FreeIPA.

**Event log**
Which logs do you need in this case?

**Platform (please complete the following information):**
 - OS: Arch Linux
 - OS Version: rolling release
 - Browser: Firefox 66.0.4

**Comment by nuxsmin** [comment]
Hello, be aware that many LDAP servers  perform case insensitive queries, so it would be possible that some users do perform the log in alternating username case. This behavior will invalidate the key used for encrypting the master password, so it will ask for the previous username and then for the master password.

Regards

**Comment by cRaZy-bisCuiT** [comment]
So a workaround is to e.g. alway use lower case or at least always in the same kind of case all the time?

**Comment by cRaZy-bisCuiT** [comment]
What happens if I delete the user from SysPass and the user tries to login again with the same IPA/LDAP account... will the access to the created accounts still be possible? Is the user still "the same user", so he/she keeps the ownership?

**Comment by nuxsmin** [comment]
@cRaZy-bisCuiT no, deleted users will lost their id, so if the same user logs in again, sysPass will create a new account.
