### ISSUE TITLE
LDAP automatic sync

### ISSUE THREAD

**Issue by hoko18** [nuxsmin/sysPass#1337]
**sysPass Version**

  | 3.0 (301.19012002)
**Describe the question**
How configure automatic sync with LDAP

**Screenshots**
![image](https://user-images.githubusercontent.com/49939379/57380858-127be800-71aa-11e9-874c-27437c242d6b.png)

![image](https://user-images.githubusercontent.com/49939379/57380879-1e67aa00-71aa-11e9-8e83-db1b8b0f045a.png)

**Platform (please complete the following information):**
 - OS: linux
 - OS Version Centos 7
 - Browser [ Firefox, Chrome]

**Additional context**
Hy ,
We configure LDAP connection, I put new user on my group also on my OU  but I have not found the user on my syspass system 
How is the correct way to have automatic synconize with LDAP
Thank's

**Comment by nuxsmin** [comment]
Hello, unfortunately sysPass won't sync your users automatically, since PHP is a interpreted language which is run on every request, so no background tasks are executed.

sysPass will add or update every LDAP user who logs into sysPass, or you can import LDAP users manually.

Regards

**Comment by hoko18** [comment]
Hello,
Thank's for your answer.
I checked by logging in with the domain user first attempt i have error
The second I login .
my question when I deleted the user from my domain I still have access login how come?
My regards

**Comment by hoko18** [comment]
any feedback ?

**Comment by nuxsmin** [comment]
Please see #1342
