### ISSUE TITLE
Is it possible to see quickly all permissions assigned to a specific user ?

### ISSUE THREAD

**Issue by anth69** [nuxsmin/sysPass#1338]
**sysPass Version**

Version de sysPass | 3.0 (305.19020701)                         Config: 305.19020701 

**Describe the question**

Hi, I can see all the permissions assigned on an item by mouseovering the logo. works fine.
Is there a way to see all permissions assigned to a specific USER instead ? 

Think of a company, if you want to change all passwords an employee had access how would you know it ? I can't think of mouse-overing every items 1 by 1 :dancer:

**Comment by nuxsmin** [comment]
Hello,  currently, you can perform an special search for accounts which and user has been granted for, but there isn't any view about permissions. There's also a list with objects in which the user is included, it's within the user's information card.

Regards

**Comment by anth69** [comment]
Nice thanks

**Comment by anth69** [comment]
Hi, I have to reopen this to ask you a bit more details about "search for accounts" options pls.

Let's say I have 3 groups : A, B, C
I have 2 users : user 1, 2

User 1 has maingroup : A and is part of B & C as secondaries
User 2 has maingroup : A and is part of B & C as secondaries too

If user1 didnt add an account (aka is not proprietary of any accounts)  and user2 add an account without permissions (by default then in group A), if I try the search function : 
user:user2 will show me the added account
user:user1 returns blank

How do I know what accounts user:1 can actually access then ?

**Comment by nuxsmin** [comment]
Hi, there is another search filter which will search by primary group.

I'll review the filtering behavior for improving it by including the main group for the given user.

Thanks for the feedback!

**Comment by anth69** [comment]
Awesome ! 

Can't wait !
