### ISSUE TITLE
password is leaked in plain text apache2 error.log when using LDAP (FreeIPA) / LDAP bind error

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [nuxsmin/sysPass#1339]
**sysPass Version**
3.0.5

**Describe the bug**
When a user tries to login to SysPass which is connected to LDAP, the password is leaked in plain text when there is a 

**To Reproduce**
1. Go to syspass url.
2. provide credentials
3. When there's a LDAP bind error -> password is leaked in plain text to apache2 error.log

**Expected behavior**
passwords should NEVER be leaked to a log. Please remove that field or just provide a random/empty string instead.

If this error is not fixable, maybe remove LDAP connectivity....?

**Event log**
username: replaced by me XXX
password: replaced by me with YYY
URL: I replaced the URL with https://example.com
```
[Thu May 09 14:01:24.184391 2019] [:error] [pid 17058] [client 10.0.2.1:46756] [EXCEPTION] [N/A] LDAP-Verbindungsfehler (BIND)\n#0 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/Ldap.php(140): SP\\Providers\\Auth\\Ldap\\LdapConnection->bind('uid=XXX,...', 'YYY')\n#1 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapAuth.php(123): SP\\Providers\\Auth\\Ldap\\Ldap->bind('uid=XXX,...', 'YYY')\n#2 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(115): SP\\Providers\\Auth\\Ldap\\LdapAuth->authent
icate(Object(SP\\DataModel\\UserLoginData))\n#3 /var/www/html/syspass/lib/SP/Providers/Auth/AuthProvider.php(93): SP\\Providers\\Auth\\AuthProvider->authLdap()\n#4 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(146): SP\\Providers\\Auth\\AuthProvider->doAut
h(Object(SP\\DataModel\\UserLoginData))\n#5 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(62): SP\\Services\\Auth\\LoginService->doLogin()\n#6 [internal function]: SP\\Modules\\Web\\Controllers\\LoginController->loginAction()\n#7 /var/www/html/sy
spass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)\n#8 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollect
ion\\RouteCollection), Array)\n#9 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\
DataCollection\\RouteCollection), Array)\n#10 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#11 /var/www/html/syspass/lib/SP/Bootstrap.ph
p(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#12 /var/www/html/syspass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#13 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')\n#14 {main}, referer: https://example.com
gin
```

**Platform (please complete the following information):**
 -  OS (of server): Debian 9

**Comment by craigafinch** [comment]
I am running Syspass version 305.19020701 on CentOS 7 with Nginx and PHP 7.2 FPM. I have LDAP configured with Active Directory, and I am *not* seeing a password or login recorded the Nginx error log, the PHP-FPM error log, or the Syspass log.

I hope this information is useful to help isolate circumstances under which this problem occurs, and resolve it quickly.

**Comment by nuxsmin** [comment]
@cRaZy-bisCuiT hello, I absolutely agree with you and it's done so since the function that logs exceptions is set to not print any arguments

**Comment by cRaZy-bisCuiT** [comment]
Hi @nuxsmin,

thanks for observing the issue. Please let me know if I could change the logging to a lower level to avoid spolinh PWs if this would be a workaround.

Thanks & regards!
