### ISSUE TITLE
syspass.org is down

### ISSUE THREAD

**Issue by pydubreucq** [nuxsmin/sysPass#134]
Hi,
Just to inform you than syspass.org is down
Best Regards

**Comment by nuxsmin** [comment]
Thank you for your notice. I'll contact with the hosting provider to find out if there any issue.

Kind regards

**Comment by nuxsmin** [comment]
This is the reason:

Posted at: 10/06/2015 04:02 pm
Maintenance has now begun. We are currently in the process of shutting down all necessary servers. Please stand by.

Posted at: 10/06/2015 03:12 pm
This is notification of an upcoming preventative power maintenance scheduled for AMS-1 CR3. During annual inspection of the rooms power feed, a loose connection was identified in the Power Bypass Panel for this rooms B power feed. This is not a critical issue, as primary power and UPS availability remains intact, however the ability to switch between UPS feeds is affected by this loose connection. For safety, during this maintenance any server with non-redundant PSU attached to power feed B will need to be shutdown. Failure to fix this issue could lead to unplanned or extended outages in the future. SingleHop is having this maintenance performed as a preventative measure to provide you with the best possible uptime in the future.

**Comment by nuxsmin** [comment]
Online again :+1:
