### ISSUE TITLE
LDAP delete USER 

### ISSUE THREAD

**Issue by hoko18** [nuxsmin/sysPass#1342]
sysPass Version

  | 3.0 (301.19012002)
Describe the question
LDAP delete USER 

    OS: linux
    OS Version Centos 7
    Browser [ Firefox, Chrome]

Additional context
Hyello ,
We configure LDAP connection, If I delete my group or my user on LDAP I still have access login on my sysPass why and how can delete automacly on sysPass user o group that no longer exist in LDAP
Thank's

**Comment by hoko18** [comment]
any feedback ?

**Comment by nuxsmin** [comment]
Hello, that is the correct behavior, since LDAP users are synced to allow access even if the LDAP server is unavailable, so manual action is required in order to block a deleted LDAP user. Please be aware that if you block the user on LDAP, it won't be able to log into sysPass.

Regards
