### ISSUE TITLE
plugin install step

### ISSUE THREAD

**Issue by hoko18** [nuxsmin/sysPass#1343]
**sysPass Version**
Ver3

**Platform (please complete the following information):**
 - OS: Centos 7
Hello,
What is the correct step to installa plugin and import plungin 
Sorry but it not clear how can I do it on the manual 
Thank's

**Comment by hoko18** [comment]
any feedback ?

**Comment by nuxsmin** [comment]
Hello, did you install using the following command?:

```composer require syspass/plugin-authenticator:^v2.0```

Regards

**Comment by bitking** [comment]
Can you perhaps put it somewhere on http://doc.syspass.org/en/3.0/application/plugins.html 

Thanks.

**Comment by nuxsmin** [comment]
@bitking sure, it would be useful there, but not done yet because sysPass installation need to be done using composer, and plugins are installed in the same way.

Nevertheless it's pointed on the plugin's page https://github.com/sysPass/plugin-Authenticator/blob/master/README.md

Regards
