### ISSUE TITLE
fresh installation language error

### ISSUE THREAD

**Issue by crazychatting** [nuxsmin/sysPass#1344]
**sysPass Version**
3.1.0-RC2

**Describe the bug**
After a fresh install of the latest version and following all install steps mentioned in https://doc.syspass.org/en/3.0/installing/centos7.html I´m getting the following error:

> Fatal error: Uncaught Error: Call to undefined function SP\Core\bindtextdomain() in /var/www/html/syspass/lib/SP/Core/Language.php:200

**To Reproduce**
1. Go to 'https://IP_OR_SERVER_ADDRESS/syspass/index.php'

**Expected behavior**
Maybe the app should be showing up to follow the installer steps there.

**Event log**
> Fatal error: Uncaught Error: Call to undefined function SP\Core\bindtextdomain() in /var/www/html/syspass/lib/SP/Core/Language.php:200 Stack trace: #0 /var/www/html/syspass/lib/SP/Bootstrap.php(124): SP\Core\Language::setLocales('en_US.utf8') #1 /var/www/html/syspass/lib/SP/Bootstrap.php(457): SP\Bootstrap->__construct(Object(DI\Container)) #2 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container)) #3 /var/www/html/syspass/index.php(28): require('/var/www/html/s...') #4 {main} thrown in /var/www/html/syspass/lib/SP/Core/Language.php on line 200

**Platform (please complete the following information):**
 - OS: Centos
 - OS Version 7
 - Browser Opera
 - Apache 2.4.6 with PHP 7.3.5

**Comment by nuxsmin** [comment]
Hello, it seems that gettext PHP's module is missing

Regards

**Comment by nuxsmin** [comment]
Done
