### ISSUE TITLE
Wrong master password for some users with Google Chrome

### ISSUE THREAD

**Issue by 90er** [nuxsmin/sysPass#1347]
**sysPass Version**
3.1-RC1 (310.19042801)
Config: 300.18112501
App: 310.19042701
DB: 310.19042701 

**Describe the bug**
Some LDAP Users (2 or 3 of 30) are getting the error message "Wrong master password" when connecting with Google Chrome. Same with Mozilla Firefox is working fine.

**To Reproduce**
1. Try to Login to sysPass using Google Chrome
2. Fill in the correct LDAP informations
3. Error message "Wrong master password" appears. Login not possible.

**Expected behavior**
Login should be possible :-)

**Screenshots**

**Event log**
```
[2019-05-20 06:17:27] syspass.INFO: logger {"message":"Saved icons cache","caller":"SP\Core\UI\Theme::saveIcons"}
[2019-05-20 06:17:27] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2019-05-20 06:17:27] syspass.EXCEPTION: logger {"message":"Ungültiges Masterpasswort
#0 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(180): SP\Services\Auth\LoginService->loadMasterPass()
#1 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#10 {main}","caller":"N/A"}
```

**Platform (please complete the following information):**
- Server: Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core with SELinux enforced
- Client: macOS, Windows 10

**Comment by nuxsmin** [comment]
Hello, I think this question was discussed on some past issues, and it might be caused by using different login username letter case from time to time.

Please let me know if it would be so.

Regards

**Comment by LordBeaver** [comment]
**sysPass Version**
3.1 (310.19081801)
Config: 310.19081801
App: 310.19081801
DB: 310.19081801

**Describe the bug**
1 of 3 LDAP users are getting the error message "Wrong master password" when connecting with Google Chrome.

**Event log**
`[2019-10-23 15:16:53] syspass.EXCEPTION: logger {"message":"Wrong master password
#0 /var/www/html/lib/SP/Services/Auth/LoginService.php(180): SP\Services\Auth\LoginService->loadMasterPass()
#1 /var/www/html/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/html/index.php(28): require(String)","caller":"N/A"}`

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome

**Additional context**
Different login username letter case in not used anywhere.
