### ISSUE TITLE
account/edit api

### ISSUE THREAD

**Issue by Spybull** [nuxsmin/sysPass#1348]
**sysPass Version**
3.1-RC1 (310.19042801) 

**Describe the question**
Hi. I can't edit account from API.
I set up next options:
      'jsonrpc' => '2.0',
      'method' => 'account/edit',
      'params' => [
      'authToken' => 'ce5a64b9ece34493347c768f387811c4645fb6f26770f0665338e044656b0fe5',
                'tokenPass' => '12345',
                'id' => 111,
                'notes' => 'test' ],
        'id' => 1];
I need change 'notes' field, but I get error message:
"error":{"message":"Wrong parameters","code":-32602, .....
All options are сorrect, authToken, tokenPass, id.
I tried to create an account and I did it! But I can't edit account.
What is the problem? Can u help me?

**Comment by nuxsmin** [comment]
Hi, unfortunately account modify will require to set all parameters, since no changeset is performed on app side, but the database will only update those fields which have been changed.

Why is it so?: because it will require an extra query to get the current account data and them look for fields changed.

Regards.

**Comment by andrucha97** [comment]
@nuxsmin do i have to fill the parameter felds?

I also stuck on this issue. I updatet a Account with following parms (set privateGroup to 0):

```
  "jsonrpc": "2.0",
    "method": "account/edit",
    "params": {
		"authToken": "*****",
		"tokenPass": "******",
		"id": 176,
		"name": "Host****",
		"clientId": 8,
		"categoryId": 53,
		"login": "",
	        "url": "http:\/\/faq*****",
		"notes": "",
		"private": 0,
		"privateGroup": 0,
		"parentId": 0,
		"categoryName": "******",
		"clientName": "*****",
		"userGroupName": "IT",
		"userName": "****",
		"userLogin": "*****"
    },
    "id": 1
}
```


Is it possible to use some think like that?:

```
  "jsonrpc": "2.0",
    "method": "account/edit",
    "params": {
		"authToken": "*****",
		"tokenPass": "******",
		"id": 176,
		"clientId": 8,
		"privateGroup": 0
    },
    "id": 1
}
```

**Comment by krnull** [comment]
I have the same issue...
