### ISSUE TITLE
Wrong number of fields (1)

### ISSUE THREAD

**Issue by BorjaMarco** [nuxsmin/sysPass#1349]
No entiendo el por que me sale este error cuando intento importar un csv para llevar mis contraseñas, alguien me podría decir ha que se refiere con Número incorrecto de campos (1)

**Comment by nuxsmin** [comment]
Buenas, podrías completar la información con los datos de la versión de sysPass? 

Ese error es causado porque la aplicación no ha detectado los campos incluidos en el CSV. Estos tienen que estar separados por `;` y entre `"`. Al final de cada conjunto de campos (7), tiene que haber un salto de línea.

Saludos
