### ISSUE TITLE
Master Password

### ISSUE THREAD

**Issue by gleisonbaioco** [nuxsmin/sysPass#135]
Hello Nuxsmin,

First of all I would like to congratulate you by your great engagement in the Syspass project.

I have tried it in order to implement it in my company.

Regarding Master Password, do you plan to do any change in the current approach, which requires to supply the Master Password (or the temporary one) when a personal users' password is changed etc?

My question is because the current approach implies in the problem in obtaining and sending the temporary password to the user whenever its password is changed.

Kind Regards, Gleison.

**Comment by nuxsmin** [comment]
Hi gleisonbaioco, thank you, I'm glad that you find it useful.

Master password implementation has two ways:

* A global master pass that is coded unencrypted in the server side, then the client does not need to provide it
* A global master pass that is **not** coded unencrypted in the server side, it's coded by a derivated key using the app hash and the user password, so every time the user changes his password, the master password need to be encrypted again with his current password.

An approach to the second point, you can ask to the user for its old password, and then unblock the master pass to encrypt with the new one, but there are some cases that can be forced to change his password or need to reset it. Also, we should take into account that LDAP users change their passwords on the directory service, so the app (sysPass), need to ask for the old password before the login process.

I've been thinking about it for many time without a good conclusion.

Do you have any idea?

Kind regards

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin

I'm thinking about these items in order to contribute with some idea.

I didn't understand some points. For example, is the Master Password unique for each user?
