### ISSUE TITLE
Unable to download attached files

### ISSUE THREAD

**Issue by fprina** [nuxsmin/sysPass#1354]
**sysPass Version**
sysPass 3.1-RC2  (no idea with previous version)

**Describe the bug**
I'm not able to download an account attached file; instead the "view file" option work fine 
looking the develop tools I see a 404 error "File not found." after clicking "Download File"

**To Reproduce**
1. load a file in an account 
2. try to download

**Screenshots**
the Same file viewed and "downloaded" 

![syspass1](https://user-images.githubusercontent.com/8728834/58320867-f3718d00-7e1c-11e9-851b-5c9752a67392.png)

![syspass2](https://user-images.githubusercontent.com/8728834/58320873-f79daa80-7e1c-11e9-8aa3-f6df7be8ef33.png)

**Event log**
I don't see any relevant log

**Platform (please complete the following information):**
 - OS: Linux
 - OS CentOS 7.6
 - Browser Firefox and Chrome

**Comment by nuxsmin** [comment]
Hello, It's quite weird since I've tested it on demo site and it worked fine. Are you accessing sysPass through a proxy?. Is there any restriction on web server side?. Be aware that viewing a file does not behave like downloading it.

Regards

**Comment by fprina** [comment]
hello
yes I use a proxy but I see the same error also with a direct connection.
there are no specific restriction on server side:

- modSecurity is present and set to DetectOnly, and there are no message
- Content-Security-Policy is quite permissive (if I disable it is the same)

There are no message in the browser console 


The only related log i found is this apache error log: 
`
[Sat May 25 10:28:51.582235 2019] [proxy_fcgi:error] [pid 12006] [client 10.20.11.20:38870] AH01071: Got error 'Primary script unknown\n', referer: http://10.80.21.42/sysPass/index.php?r=index
`
As senseless test I've also disabled https 

I've just installed the RC3 on a fresh new db (same web server) and again same behaviour

Thanks for any help and for moreover for sysPass

**Comment by fprina** [comment]
I've sysPass under /syspass 
https://www.example.com/syspass/index.php

unlike the demo site that is directly in the root:

Seems the **download icon** refer to https://www.example.com/index.php so without the "subdir"

**Comment by nuxsmin** [comment]
Fine, so your sysPass instance is on `/syspass` though you're using a proxy, and the real instance (behind the proxy) is on `/`, isn't it?

If so, since v3.1 there's an option to configure the visible URL, so it will be replaced when redirecting or within emails sent.

Regards

**Comment by fprina** [comment]
no,

The proxy it's just a passthrough to the real server; at the moment the proxy manage public IP and the SSL certificate nothing else ... so both proxy and server behind are on /syspass

Connecting to the proxy and directly to the server I'see the same results 
is it possible that the download link refer to an absolute path "/index.php" instead to the relative one ?

Regards

**Comment by nuxsmin** [comment]
Okay, sorry for the long discussion...I see the error...it's just the JS code which does not rely on an AJAX call that wasn't building the correct URL.

It has been fixed in latest commit. Thanks for the feedback and testing!

Regards
