### ISSUE TITLE
Questions about time and master password

### ISSUE THREAD

**Issue by Altes** [nuxsmin/sysPass#1356]
**sysPass Version**
3.0 (305.19020701) 

**Describe the question**
Hello, I have a few questions about syspass:

- H̵o̵w̵ ̵t̵h̵e̵ ̵t̵i̵m̵e̵ ̵i̵n̵ ̵s̵y̵s̵p̵a̵s̵s̵ ̵w̵e̵b̵ ̵U̵I̵ ̵i̵s̵ ̵c̵o̵n̵f̵i̵g̵u̵r̵e̵d̵?̵ ̵I̵ ̵h̵a̵v̵e̵ ̵m̵y̵ ̵c̵e̵n̵t̵o̵s̵7̵ ̵w̵i̵t̵h̵ ̵t̵h̵e̵ ̵c̵o̵r̵r̵e̵c̵t̵ ̵d̵a̵t̵e̵ ̵/̵ ̵t̵i̵m̵e̵z̵o̵n̵e̵,̵ ̵b̵u̵t̵ ̵i̵n̵ ̵t̵h̵e̵ ̵s̵y̵s̵p̵a̵s̵s̵ ̵w̵e̵b̵ ̵U̵I̵ ̵t̵h̵e̵ ̵t̵i̵m̵e̵z̵o̵n̵e̵ ̵i̵s̵ ̵w̵r̵o̵n̵g̵.̵ Noob question, skip it.

- Why i cant see the current master password? I click on the "show password" icon but nothing happens, even in debug mode.

- If I want to change the master password why I cant type inside the textbox and I need to generate the password through the generator? And If i update the master password hash by clicking the button and login again my master password has not changed or i cant login anymore.

**Platform (please complete the following information):**
 - OS: Centos7
 - OS Version:  7.6.1810
 - Browser : Firefox / Chrome
 - MariaDB 10.3.15
 - PHP 7.2.18
 - Nginx 1.17

**Comment by BorjaMarco** [comment]
Why i cant see the current master password? I click on the "show password" icon but nothing happens, even in debug mode.


The eye option is only used to copy the password that is entered

**Comment by Altes** [comment]
`Why i cant see the current master password? I click on the "show password" icon but nothing happens, even in debug mode.

The eye option is only used to copy the password that is entered`

For me, I can only copy the password that has been generated. I cant insert manually a new master password or copy the old one using the eye button.

**Comment by Altes** [comment]
> 
> 
> Why i cant see the current master password? I click on the "show password" icon but nothing happens, even in debug mode.
> 
> The eye option is only used to copy the password that is entered

For me, I can only copy the password that has been generated. I cant insert manually a new master password or copy the old one using the eye button

**Comment by BorjaMarco** [comment]
what version of syspass do you have

**Comment by Altes** [comment]
3.0 (305.19020701)

**Comment by BorjaMarco** [comment]
because in theory you have the same as me and I have not had that problems if at the time of installation you put something wrong

**Comment by Altes** [comment]
Which php version are you using?

**Comment by BorjaMarco** [comment]
> Which php version are you using?

7.1

**Comment by Altes** [comment]
Im using the latest php7.2 (7.2.18), I might try to use 7.1.
I've also deployed syspass 3.1-rc4 with php 7.3 and i have the same issue.

**Comment by BorjaMarco** [comment]
> Im using the latest php7.2 (7.2.18), I might try using 7.1.
> I've also deployed syspass 3.1-rc4 with php 7.3 and i have the same issue.

Well I can not help but I'm sorry, I hope the creator read this post and can help you

**Comment by Altes** [comment]
> 
> 
> > Im using the latest php7.2 (7.2.18), I might try using 7.1.
> > I've also deployed syspass 3.1-rc4 with php 7.3 and i have the same issue.
> 
> Well I can not help but I'm sorry, I hope the creator read this post and can help you

Np, your help is greatly appreciated.

**Comment by Altes** [comment]
I have just tried with the docker image 3.1-php 7.1 but still nothing.

**Comment by nuxsmin** [comment]
Hello,

The master password won't be shown anymore once you set it. The eye icon is there for revealing the master password you are setting before change it.

Regarding the master password hash, it will only update the hash that's used for comparing if the master password entered (when logging in) is the right one. By changing the hash you'll increase the security of the system.

Regards.

**Comment by Altes** [comment]
Ah! I see, thanks!
