### ISSUE TITLE
 Problems to configure ldap in sysPass

### ISSUE THREAD

**Issue by alvarocerna** [nuxsmin/sysPass#1357]
**sysPass Version**
3.1-RC4 (310.19052503) Config: 310.19052503 App: 310.19052503 DB: 310.19052503
Base de Datos | SERVER_VERSION : 5.5.5-10.3.15-MariaDB CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $ SERVER_INFO : Uptime: 145801 Threads: 8 Questions: 41875 Slow queries: 0 Opens: 260 Flush tables: 1 Open tables: 88 Queries per second avg: 0.287 CONNECTION_STATUS : Localhost via UNIX socket Nombre: syspassdb@localhost
PHP | Versión: 7.2.10 Extensiones: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu

**Describe the bug**
When configuring the ldap option and when saving the configuration, you see in the view 3 asterisks (***) and not the password that I have set. Also, when checking the configuration, the invalid credentials message appears.

To identify if the problem is due to the password registered by the web, I have modified the value $pass of the LdapConnection.php file by setting my fixed password; When I rechecked, the message that the connection was satisfactory appears.

In summary, the application is not interpreting correctly the password placed by the graphical interface, how can this error be solved?

**Expected behavior**
I need to have this ldap option enabled since we are like 20 administrators and I do not want to be creating a user locally.

**Screenshots**
![image](https://user-images.githubusercontent.com/51207784/58650928-96228380-82d5-11e9-91e3-b07c28798e5d.png)

**Event log**
Log de messages
[Error al conectar (BIND)#012#0 /var/www/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\Providers\Auth\Ldap\LdapConnection->bind()#012#1 /var/www/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()#012#2 /var/www/sysPass/lib/SP/Providers/Auth/Ldap/Ldap.php(96): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()#012#3 /var/www/sysPass/lib/SP/Services/Ldap/LdapCheckService.php(51): SP\Providers\Auth\Ldap\Ldap->factory(Object(SP\Providers\Auth\Ldap\LdapParams),Object(SP\Core\Events\EventDispatcher),Boolean)#012#4 /var/www/sysPass/app/modules/web/Controllers/ConfigLdapController.php(156): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))#012#5 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()#012#6 /var/www/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)#012#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)#012#8 /var/www/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)#012#9 /var/www/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)#012#10 /var/www/sysPass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))#012#11 /var/www/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))#012#12 /var/www/sysPass/index.php(28): require(String)] N/A

**Platform (please complete the following information):**
 - OS: Linux RHEL 7

**Comment by javierlm** [comment]
That's the expected behaviour. Password is set, but not shown (shows 3 * instead to not reveal the password). If you want to modify the options, you need to introduce the password again.

I'm using SysPass with an AD. No problems to login with users from the AD.

**Comment by BorjaMarco** [comment]
Cada vez que hagas un cambio en el ldap tienes que poner la contraseña otra vez
Every time you make a change in the ldap you have to enter the password again

**Comment by alvarocerna** [comment]
> That's the expected behaviour. Password is set, but not shown (shows 3 * instead to not reveal the password). If you want to modify the options, you need to introduce the password again.
> 
> I'm using SysPass with an AD. No problems to login with users from the AD.

What version of SysPass are you using?

**Comment by javierlm** [comment]
> > That's the expected behaviour. Password is set, but not shown (shows 3 * instead to not reveal the password). If you want to modify the options, you need to introduce the password again.
> > I'm using SysPass with an AD. No problems to login with users from the AD.
> 
> What version of SysPass are you using?

3.0.5, but I've been using Syspass since 2.6. I'm testing 3.1 RC4 too. The behaviour has been always the same. Your need to type again the password when you change LDAP options.

**Comment by BorjaMarco** [comment]
> > That's the expected behaviour. Password is set, but not shown (shows 3 * instead to not reveal the password). If you want to modify the options, you need to introduce the password again.
> > I'm using SysPass with an AD. No problems to login with users from the AD.
> 
> What version of SysPass are you using?

I'm using version 3.0.5

**Comment by nuxsmin** [comment]
Hello  @alvarocerna, as said @BorjaMarco, this is the expected behavior.

Regards
