### ISSUE TITLE
How to configure mail settings

### ISSUE THREAD

**Issue by Cefanys** [nuxsmin/sysPass#1358]
**sysPass Version**
3.0

**Describe the question**
I wish to configure mail settings to send password notifications, but i don't know how to fill in the fields. Can I use data from a google account or I have to have a local mail server?

**Platform (please complete the following information):**
 - OS: Linux
 - OS Version: Debian 9
 - Browser Chrome

**Comment by andrucha97** [comment]
Normaly you can use your google account. I`m sending from another Server which is located in a different data center

**Comment by Cefanys** [comment]
Could you help me fill in the fields using the Gmail data? Should i use the settings for smtp?

for example:

the filds are:

Server: smtp.gmail.com
Port: 587
Enable Authentication: ON
User: myuser@gmail.com
Password: mypassword
Security: SSL

it's right? Because after informe this filds i'm getting this error:

![syspass](https://user-images.githubusercontent.com/51325580/58959804-3cf69c00-877c-11e9-99a2-6e4965de8e6b.jpg)

**Comment by andrucha97** [comment]
Did you activate IMAP and POP3 for your account in gmail? 

https://support.google.com/mail/answer/7126229?hl=en

I don’t understand the error because of the language xD

**Comment by Cefanys** [comment]
Yes, the IMAP and POP3 are active ingmail configurations.
Sorry, i send the image bellow witch english language

![syspass](https://user-images.githubusercontent.com/51325580/58964342-1c7f0f80-8785-11e9-8459-b93f9eb42704.jpg)

**Comment by Cefanys** [comment]
Obs: I try to insert the complet email address in User field and the erro is the same :(

**Comment by andrucha97** [comment]
Hmmm as user I would type in yourmail@gmail.com and you I think you need to choose at least on recipient and event

I can look tomorrow at work what I configured.

**Comment by Cefanys** [comment]
Yes, I tried everything you mentioned, and nothing worked for me, always the same mistake.
Another question, the Recipients field, I leave blank on previous tests? How to fill this field?

Thanks a lot for your attencion and dedication on solve my problem.

**Comment by nuxsmin** [comment]
@Cefanys hello, please run a mail checking before saving the mail settings. 

Recipients should be set, since it would need to send emails to someone.

Regards.

**Comment by Cefanys** [comment]
Thanks to all, I solved the problem, my server was having problems in dns resolve.

Anyway I leave the image below how the final configuration was done for others with the same problem in future.

![syspass](https://user-images.githubusercontent.com/51325580/58986338-8d3d2080-87b3-11e9-9f51-c7c06ff6357b.jpg)

Regards to all! 😃

**Comment by nuxsmin** [comment]
@Cefanys thanks for the feedback!
