### ISSUE TITLE
Connection error LDAP AD

### ISSUE THREAD

**Issue by steevegldev** [nuxsmin/sysPass#136]
Config LDAP tab's test return Success with xx number users found.
When I try to login I got wrong user/pass. [Can't contact LDAP server (-1]

Event Log:
3	2015-10-08 11:25:22	Log in		192.168.XXX.XXX	(MySQL)
Incorrect login
User: USERNAME@XXXX.local
2	2015-10-08 11:25:22	ldapBind		192.168.XXX.XXX	Connection error (BIND)
LDAP ERROR: Can't contact LDAP server (-1)
LDAP DN: LDAP
1	2015-10-08 11:25:18	Clear Events	ADMIN	192.168.XXX.XXX	Clear event log
~ Event Log end ~

  'ldap_ads' => true,
  'ldap_base' => 'OU=SBSUsers,OU=Users,OU=XXXXXX,DC=XXXXXXX,DC=local',
  'ldap_bindpass' => 'XXXXXXXX',
  'ldap_binduser' => 'LDAP',
  'ldap_defaultgroup' => 2,
  'ldap_defaultprofile' => 2,
  'ldap_enabled' => true,
  'ldap_group' => false,
  'ldap_server' => 'XXXXXXXX.local',
  'ldap_userattr' => '',

git log --abbrev-commit --name-status HEAD^..HEAD
commit d039ac6
Author: nuxsmin <nuxsmin@users.noreply.github.com>
Date:   Wed Oct 7 02:24:00 2015 +0200

    Update description

M       README.md

sysPass version	1.2.0.05
Database	SERVER_VERSION : 5.5.5-10.0.20-MariaDB-0+deb8u1 
CLIENT_VERSION : mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $ 
SERVER_INFO : Uptime: 610603 Threads: 1 Questions: 9201 Slow queries: 0 Opens: 84 Flush tables: 1 Open tables: 121 Queries per second avg: 0.015 
CONNECTION_STATUS : Localhost via UNIX socket 
Name: syspass@localhost
PHP	Version: 5.6.13-0+deb8u1 
Extensions: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, mysqlnd, PDO, apcu, curl, gd, imagick, imap, intl, json, ldap, mcrypt, memcache, mysql, mysqli, pdo_mysql, pdo_sqlite, pspell, readline, recode, snmp, sqlite3, tidy, xmlrpc, xsl, mhash, apc, Zend OPcache 
Used Memory: 768 KB 
User: root
Server	Apache/2.4.10 (Debian)

**Comment by nuxsmin** [comment]
Hi, the username format is 'login' without domain part.

**Comment by steevegldev** [comment]
sAMAccountName: test


10	2015-10-08 11:41:50	Log in		192.168.0.147	(MySQL)
Incorrect login
User: test
9	2015-10-08 11:41:50	checkLDAPParams		192.168.0.147	LDAP parameters are not set

**Comment by nuxsmin** [comment]
At this moment LDAP isn't queried, only mysql. You need to set LDAP params, check the connection and the save the changes. Now you can try to login

**Comment by steevegldev** [comment]
1. Configuration updated

2. LDAP connection OK
    Objects found: 32

3. User: test
    Pass: XXXXX

Got
4. Wrong user/pass


Event Log:
4	2015-10-08 11:58:37	Log in	ADMIN	192.168.XXX.XXX	(MySQL)
Incorrect login
User: test
3	2015-10-08 11:58:37	ldapBind	ADMIN	192.168.XXX.XXX	Connection error (BIND)
LDAP ERROR: Can't contact LDAP server (-1)
LDAP DN: LDAP
2	2015-10-08 11:58:11	Edit Configuration	ADMIN	192.168.XXX.XXX	LDAP enabled
Section: LDAP
1	2015-10-08 11:57:50	Clear Events	ADMIN	192.168.XXX.XXX	Clear event log
~ Event Log End ~

**Comment by nuxsmin** [comment]
Are you using LDAP as bind user?. This error is thrown in the first step of the ldap connection, when the app get in contact with the server. The next step is to login with the provided login.

**Comment by steevegldev** [comment]
That's right, my bind user is LDAP. I change it to CN=LDAP,CN=Users,DC=XXXXXXX,DC=local

but that's turning me crazy:
6	2015-10-08 12:20:47	Log in		192.168.MY.IP 	(MySQL)
Incorrect login
User: test
5	2015-10-08 12:20:47	ldapBind		192.168.MY.IP 	Connection error (BIND)
LDAP ERROR: Can't contact LDAP server (-1)
LDAP DN: CN=LDAP,CN=Users,DC=XXXXX,DC=local
4	2015-10-08 12:20:24	Log in		192.168.MY.IP 	(LDAP)
Login Server : DC.XXXXXXXXXX.local
User disabled
User: MYUSERNAME
3	2015-10-08 12:20:06	Edit Configuration	ADMIN	192.168.MY.IP 	LDAP enabled
Section: LDAP
2	2015-10-08 12:19:35	Edit Configuration	ADMIN	192.168.MY.IP 	LDAP enabled
Section: LDAP
1	2015-10-08 12:19:29	Clear Events	ADMIN	192.168.MY.IP 	Clear event log


PS1: MYUSERNAME is not disable, I tested twice and I forced "undisabled" it
PS2: My bind user is NOT in the base dn


  'ldap_ads' => true,
  'ldap_base' => 'OU=SBSUsers,OU=Users,OU=XXXXXXXX,DC=XXXXXXXXXXX,DC=local',
  'ldap_bindpass' => 'XXXXXXX',
  'ldap_binduser' => 'CN=LDAP,CN=Users,DC=XXXXXXXXX,DC=local',
  'ldap_defaultgroup' => 2,
  'ldap_defaultprofile' => 2,
  'ldap_enabled' => true,
  'ldap_group' => false,
  'ldap_server' => 'dcfs.jurisconcept.local',
  'ldap_userattr' => '',

**Comment by nuxsmin** [comment]
But as I can see it's working fine now, doesn't it?

The disabled user is a security behavior to double check the newly created users' group.

**Comment by steevegldev** [comment]
Test user return to MySQL. Why?

**Comment by steevegldev** [comment]
fixed with ldap://ldap.XXXXX.local

help bubble was wrong or it's an AD's configuration issue?

**Comment by nuxsmin** [comment]
It is strange because I've tested it in a mixed environment (openldap and ads) and it worked fine with and without the ldap url, even with ldaps

**Comment by nuxsmin** [comment]
Great..hope you find it useful ;)
