### ISSUE TITLE
CVE Contact

### ISSUE THREAD

**Issue by andrucha97** [nuxsmin/sysPass#1360]
Is it possible to add a CVE Contact in the description?

**Comment by nuxsmin** [comment]
Hello, I'm what are you talking about description, please let me know more details about it.

Anyway, CVEs can be sent by email, so we can discuss them before disclosing.

Regards.

**Comment by andrucha97** [comment]
Hello @nuxsmin 

I mean a comment in the Readme.

For example as follows:

`For CVE requests please contact: contact`

Where can I find your mail?

**Comment by nuxsmin** [comment]
> I mean a comment in the Readme.

Sure!

> Where can I find your mail?

It's within the code but you ca reach me on nuxsmin-at-syspass-dot-org.

Regards

**Comment by andrucha97** [comment]
Great Support thanks :)
