### ISSUE TITLE
Install stops with "Warn to developer"

### ISSUE THREAD

**Issue by beeper77** [nuxsmin/sysPass#1362]
If I initially want to create the mysql database I will get an error. If I show in the html traffic I see this response:
`{status: 1, description: "Unable to connect to DB", action: "", data: [],…}
action: ""
container: ""
csrf: null
data: []
description: "Unable to connect to DB"
messages: ["Warn to developer"]
0: "Warn to developer"
status: 1`

I am using the version 3.0.5 as a docker container and the mysql server is the docker host. Connection is possible because if I use a wrong password I will get a "wrong password" message.
What happens here? Maybe a mysql configuration problem? I use mariadb upgraded from mysql.
The error occurs in the installer.php file.

**Comment by nuxsmin** [comment]
Hello, did you set 'hosting Mode' during the installation?. This mode will allow to use your own credentials and database (without any tables inside). Please check out `syspass.log` file within 'app/config' directory.

Regards

**Comment by beeper77** [comment]
Hi @nuxsmin,
i have seen this option, but I had understand it in a different way. After creating an empty db and activating this option the install runs without the error and now all is fine.

Thanks for your fast support!

**Comment by nuxsmin** [comment]
You're welcome. Thanks for the feedback!
