### ISSUE TITLE
LDAP does not find all of the users

### ISSUE THREAD

**Issue by Alexander1170** [nuxsmin/sysPass#1368]
**sysPass Version**

3.1-RC4 (310.19052503) Config: 310.19052503 App: 310.19052503 DB: 310.19052503
--
Database | SERVER_VERSION : 5.5.5-10.1.40-MariaDB-0ubuntu0.18.04.1 CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $ SERVER_INFO : Uptime: 441024 Threads: 1 Questions: 13275 Slow queries: 0 Opens: 58 Flush tables: 1 Open tables: 52 Queries per second avg: 0.030 CONNECTION_STATUS : Localhost via UNIX socket Name: syspass@localhost

PHP | Version: 7.2.19-0ubuntu0.18.04.1 Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache Unavailable extensions: Used Memory: 4096 KB User: www-data Download rate: 43 MB/s OP Cache num_cached_scripts : 364 num_cached_keys : 690 max_cached_keys : 16229 hits : 96696 start_time : 1560234302 last_restart_time : 0 oom_restarts : 0 hash_restarts : 0 manual_restarts : 0 misses : 365 blacklist_misses : 0 blacklist_miss_ratio : 0 opcache_hit_rate : 99.623947826624
Server | Apache/2.4.29 (Ubuntu)

**Describe the question**

Hello all,

When I enter my LDAP info I am able to get results of users being found but, I have noticed that it is missing a lot of users? I am not sure if this is some permissions issue or something to do with the LDAP configuration? 

Below is a for instance screenshot. I drilled down to make this example easier to look at but I cannot find users in many of my OU's and sometimes it will find some and not all of the users. 

In the screenshot below it will not find any users but there are 4 users in that OU. 

The user account that is searching is members of Domain users, Domain Admin, and Account operators. 

any idea's or help would be really appreciated! 

Thank you all! 

**Screenshots**
![image](https://user-images.githubusercontent.com/24646340/59295003-ab41cf80-8c50-11e9-8136-b5338e444ee0.png)

![image](https://user-images.githubusercontent.com/24646340/59295027-b432a100-8c50-11e9-81fc-863994089479.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04 

**Additional context**

**Comment by BorjaMarco** [comment]
https://github.com/nuxsmin/sysPass/issues/1351

**Comment by Alexander1170** [comment]
Turns out the Azure AD setting needed to be enabled. We do not host anything in Azure, so I am wondering why this setting needed to be turned on for me to find all the users?

**Comment by nuxsmin** [comment]
@Alexander1170 Hello, it's all about a filtering tweak, since Azure AD does not work well with `UserAccountControl` values, so by selecting this option skips the filter.

Thanks for the feedback!

Regards

**Comment by nuxsmin** [comment]
This is the code I talked about:
 https://github.com/nuxsmin/sysPass/blob/master/lib/SP/Providers/Auth/Ldap/LdapMsAzureAd.php

**Comment by Alexander1170** [comment]
Thank you!
