### ISSUE TITLE
Problems after updating from 2.1 to 3.0.5

### ISSUE THREAD

**Issue by ednt** [nuxsmin/sysPass#1369]
**sysPass Version**
305.19020701

**Describe the question**
After some trouble I was able to get a running 3.0.5
But syspass.log shows many many errors and exceptions.
Maybe all related to the same reason:
`[ERROR] [SP\Core\Language::setLocales] Could not set locale`

`
[EXCEPTION] [N/A] Kontext wurde nicht initialisiert
#0 /var/www/html/sysPass_30/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/sysPass_30/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey('locale', NULL)
#2 /var/www/html/sysPass_30/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey('locale')
#3 /var/www/html/sysPass_30/lib/SP/Core/Language.php(223): SP\Core\Context\SessionContext->getLocale()`

locale -a shows de_DE.utf8 and this is also the default LANG
But php setlocales(, 0) returns only C

**Platform (please complete the following information):**
 - OS: Linux
 - OS Debian stretch
 - Browser Firefox

And I'm not able to access api.php any more. This results in:

`404 Not found  ... Oops, it looks like this content does not exist...`

Any ideas ?

**Comment by nuxsmin** [comment]
Hello, API is available on sysPass v3, though the method calls has changed. Please take a look to the documentation for more info: https://doc.syspass.org/en/3.0/application/api.html

Regards
