### ISSUE TITLE
Changing Master Password give error

### ISSUE THREAD

**Issue by steevegldev** [nuxsmin/sysPass#137]
93	2015-10-08 14:04:18	Update Master Password	ADMIN	192.168.XXX.XXX	Error on retrieving accounts' passwords
92	2015-10-08 14:04:18	Update Master Password	ADMIN	192.168.XXX.XXX	Start

git log --abbrev-commit --name-status HEAD^..HEAD
commit d039ac6
Author: nuxsmin <nuxsmin@users.noreply.github.com>
Date:   Wed Oct 7 02:24:00 2015 +0200

    Update description

M       README.md

**Comment by nuxsmin** [comment]
This can be thrown because you don't have any accounts created, so the process stops. This isn't the desired behavior, so I'll change it for the next build.

**Comment by steevegldev** [comment]
Fixed

I mixed up "Account" added and "Account" to login. So yeh, I wasn't added any account yet so I check "Do not modify accounts"

Note: Other Password manager, mange password, not account. So that mess my mean. Nice project btw!

**Comment by nuxsmin** [comment]
Great, yes it can be a bit confusing because I think on accounts as entities with a secret.
