### ISSUE TITLE
Can't make backup from GUI

### ISSUE THREAD

**Issue by TPAdamczyk** [nuxsmin/sysPass#1370]
**sysPass Version**
3.1-RC4 (310.19052503) 

**Describe the question**
When starting backup from GUI, I am getting message: There was an error. Internal Server Error

**Screenshots**
![image](https://user-images.githubusercontent.com/51662343/59349860-f58f8300-8d1a-11e9-8e0b-9f67c3051c35.png)

**Platform (please complete the following information):**
 - OS: Linux 
 - OS Version: Cent OS 7.6.1810
 - Browser:  Chrome

**Additional context**
In the backup directory are 3 files created. One gzip file size is 0. 
I found no additional informations in log files.
![image](https://user-images.githubusercontent.com/51662343/59350003-50c17580-8d1b-11e9-9145-9846b015170f.png)

Thank You

**Comment by nuxsmin** [comment]
Hello, I've thoroughly tested this feature using automated an manual tests and it worked fine. How much time does it take to run the backup process?

Regards
