### ISSUE TITLE
Exception while updating accounts password

### ISSUE THREAD

**Issue by misterx00** [nuxsmin/sysPass#1371]
**sysPass Version**
3.0 (305.19020701)

**Describe the bug**
When I try to update an accounts password I get this error (In 50% - 75% of the tries):
![syspass_exception](https://user-images.githubusercontent.com/51750192/59356372-00511480-8d29-11e9-8841-732272aef845.png)

**To Reproduce**
1. Click Edit Account
2. Click Edit Account Password
3. Screen shows the exception (randomy, in 50% to 75% of the cases)

**Expected behavior**
sysPass should show the Edit Account Password form.

**Event log**
Stacktrace:
[Wed Jun 12 15:36:08.466573 2019] [:error] [pid 24660] [client sourceip:60611] [EXCEPTION] [N/A] Invalid Action
#0 /var/www/syspass/app/modules/web/Controllers/AccountController.php(487): SP\\Modules\\Web\\Controllers\\ControllerBase->checkSecurityToken('6fb1a9c98fd8843...', Object(SP\\Http\\Request))
#1 [internal function]: SP\\Modules\\Web\\Controllers\\AccountController->editPassAction(128)
#2 /var/www/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#3 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)
#4 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)
#5 /var/www/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)
#6 /var/www/syspass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))
#7 /var/www/syspass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))
#8 /var/www/syspass/index.php(28): require('/var/www/syspas...')
#9 {main}, referer: https://fqdn/index.php?r=index

**Platform (please complete the following information):**
 - Browser: Chrome, Firefox, ... (doesn't matter)
 - Host: Ubuntu 16.04.6 LTS using the LAMP stack
 - Installation: .zip package
![syspass-appinfo](https://user-images.githubusercontent.com/51750192/59383313-ed0d6b80-8d5f-11e9-9ef8-e0c26db44028.png)

**What I tried so far:**
 - Deleting whole browser history and cookies, etc... and only opened one tab with sysPass to be sure its not related to a problem with multiple syspass tabs and security tokens
 - Moving the config and keys to a freshly downloaded version of sysPass to be sure its not a corrupted file --> Problem persists
 - As upgrading was suggested in https://github.com/nuxsmin/sysPass/issues/1116, I upgraded to version 3.1-RC4 --> Problem persists --> Rollback to 3.0.5

**Any suggestions would be greatly appreciated.**

**Comment by misterx00** [comment]
Issue seems to be related to https://github.com/nuxsmin/sysPass/issues/1116

**Comment by nuxsmin** [comment]
Hello, this issue is not related to imported accounts. Please take a look to https://github.com/nuxsmin/sysPass/issues/1312

Regards

**Comment by nuxsmin** [comment]
Thanks for the feedback!
