### ISSUE TITLE
User Password Policy

### ISSUE THREAD

**Issue by cztoky** [nuxsmin/sysPass#1373]
**sysPass Version**
3.1 RC4

**Describe the question**
Hi, I am looking for how to setup a User Password Policy. Now Users can set as their password everything like 1 or 2 symbols only. Maybe I am blind :) But I didnt found it solution for that.

Thank you soo much!!

**Comment by cztoky** [comment]
any feedback? @nuxsmin?

Thank you

**Comment by andrucha97** [comment]
I think you can only set a Policy for a entry but not for a user

**Comment by cztoky** [comment]
@andrucha97 Thank you for answer.. I will try solve by another way :(

**Comment by andrucha97** [comment]
@cztoky wait for the answer of @nuxsmin he maybe can implent this cool feature

**Comment by cztoky** [comment]
@andrucha97 I will wait. But I dont think that he give me an answer :-) Its 28 days ago

**Comment by andrucha97** [comment]
@cztoky in other projects he says he has not so much time at the moment

**Comment by nuxsmin** [comment]
Hello @cztoky, sorry for the late reply, too much work indeed...

Regarding your question, such level of configuration can't be currently performed, but you can use "Preset Values" to enforce a password policy.

Thanks for the feedback!

Regards

**Comment by cztoky** [comment]
Thank you @nuxsmin preset values and password policy is for users and accounts or just for accounts? 

Thank you again for response

**Comment by nuxsmin** [comment]
Only for accounts. Sorry, I misunderstood your question...

It could be a great feature for next release!

**Comment by andrucha97** [comment]
I also have a question. Maybe its the german translation...

I am currently writing an operating manual for my colleagues.

Now I have not fully understood the preset values. Are these for the accounts or for the user accounts?

**Comment by nuxsmin** [comment]
@andrucha97 Accounts

**Comment by andrucha97** [comment]
Ok. So than I think I found a small bug 😆 

But I have to check it again at work. As soon as I have set a password policy with 12 characters, the hint remains that the password must have 8 characters when you hold the mouse over the eye.

**Comment by nuxsmin** [comment]
> But I have to check it again at work. As soon as I have set a password policy with 12 characters, the hint remains that the password must have 8 characters when you hold the mouse over the eye.

Yes, it's a "known" behavior, since that message is set by JavaScript (client side) and it doesn't know which settings are set on server side...it will be improved in next release

**Comment by andrucha97** [comment]
Great :) Thanks for your comment!
