### ISSUE TITLE
Run Syspass with Azure SaaS ddbb;

### ISSUE THREAD

**Issue by shocker70** [nuxsmin/sysPass#1374]
all

If you use SaaS MySQL from Azure to work as ddbb, not in a docker, or in a vm, you will find out that it cant be deployed. An error with table account_data_v will be found.

1. Start docker compose without ddbb
2. Deploy SaaS MariaDB in Azure. 
3. Go to initial instalation page in Syspass web browser.
4. Try install 
5. An error will ocurr with ddbb permission on 'account_data_v ';

Excepted to work correctly.

No ScreenShots
[Tue Jun 25 09:12:47.728416 2019] [:error] [pid 700] [client XXXXXXX:52439] [EXCEPTION] [N/A] (P) No es posible conectar con la BD\n#0 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(215): SP\\Storage\\Database\\MySQLHandler->getConnection()\n#1 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(174): SP\\Storage\\Database\\Database->prepareQueryData(Object(SP\\Storage\\Database\\QueryData))\n#2 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(135): SP\\Storage\\Database\\Database->doQuery(Object(SP\\Storage\\Database\\QueryData))\n#3 /var/www/html/sysPass/lib/SP/Repositories/Plugin/PluginRepository.php(445): SP\\Storage\\Database\\Database->doSelect(Object(SP\\Storage\\Database\\QueryData))\n#4 /var/www/html/sysPass/lib/SP/Services/Plugin/PluginService.php(290): SP\\Repositories\\Plugin\\PluginRepository->getEnabled()\n#5 /var/www/html/sysPass/lib/SP/Plugin/PluginManager.php(360): SP\\Services\\Plugin\\PluginService->getEnabled()\n#6 /var/www/html/sysPass/app/modules/web/Controllers/BootstrapController.php(114): SP\\Plugin\\PluginManager->getEnabledPlugins()\n#7 /var/www/html/sysPass/app/modules/web/Controllers/BootstrapController.php(67): SP\\Modules\\Web\\Controllers\\BootstrapController->getPlugins()\n#8 [internal function]: SP\\Modules\\Web\\Controllers\\BootstrapController->getEnvironmentAction()\n#9 /var/www/html/sysPass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)\n#10 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#11 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#12 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#13 /var/www/html/sysPass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#14 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#15 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')\n#16 {main}, referer: 

**Platform (please complete the following information):**
 - OS: Centos7
 - OS Version 7
 - Browser:  Firefox ( dosent matter )

SOLUTION:

The issue is that when it tries to create DDBB  ' account_data_v ' it usses motor ddbb : MyISAM, i dont know why it usses it, but in Azure SaaS ddbb it dosent support MyISAM, in order to solve the issue we have to change 
 
                /var/www/html/sysPass/schemas/dbstructure.sql   
 

                sed  - i  "s/MyISAM/InnoDB/g"    dbstructure.sql  

Hope this helps future people who is willing to use Azure SaaS ddbb  with Syspass. 

References:
https://docs.microsoft.com/es-es/azure/mariadb/concepts-limits

**Comment by nuxsmin** [comment]
@shocker70 sorry for the late reply....

Thanks for your contribution!

Regards

**Comment by nuxsmin** [comment]
Done :wink: 

https://syspass-doc.readthedocs.io/en/3.1/howtos/azure_mysql.html
