### ISSUE TITLE
Custom field in "customer" not saved

### ISSUE THREAD

**Issue by ZUNbado** [nuxsmin/sysPass#1375]
**sysPass Version**
3.0 (305.19020701) 
Config: 310.19042801 
App: 310.19042801 
DB: 310.19042801

**Describe the bug**
Custom fields for "Clients" are not saved (when adding or updating Client)

**To Reproduce**
1. Create custom field, for example: "Customer ID" to module "Clients"
2. Create new customer (or update an existing) and edit the custom field
3. Check customer, the field is blank

**Expected behavior**
Custom field saved whan edit items

**Screenshots**
No screenshots required

**Event log**
No events

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Additional context**
No additional context

**Comment by sf32738** [comment]
Confirmed not working on my docker instance pulled from: 
image: syspass/syspass:latest

```
3.1-RC1 (310.19042801) 
Config: 310.19042801 
App: 310.19042801 
DB: 310.19042801
```

**Comment by sf32738** [comment]
Confirmed not working on last RC4 build (340cb75)
```
3.1-RC4 (310.19052503) 
Config: 310.19042801 
App: 310.19042801 
DB: 310.19042801
```
--
