### ISSUE TITLE
Change max login attempts

### ISSUE THREAD

**Issue by Dunt3r** [nuxsmin/sysPass#1376]
**sysPass Version**
3.0

**Describe the question**
Hi @nuxsmin ,
I would like to know where (location/file) I can change the max login attempts.

**Platform:**
 - OS: Debian 9
 - Browser Chrome

**Comment by nuxsmin** [comment]
Hello, max login attempts has been improved in latest 3.1 release by adding a view where you can unlock tracking events.

Unfortunately some values cannot be changed though settings, that is they are set within the app code.

Regards.
