### ISSUE TITLE
Remote Syslog error

### ISSUE THREAD

**Issue by Altes** [nuxsmin/sysPass#1377]
**sysPass Version**
3.1-RC3, 3.1-RC4 (7.2, 7.3)

**Describe the bug**
When I change the remote syslog settings (ip, port and events) and I save the changes, the application returns this error, making the application unusable and broken.

![Capture](https://user-images.githubusercontent.com/45455475/60353452-54ffbb00-99ca-11e9-83e4-e4593aa75cf0.PNG)

I tried with the 3.0.5 version and I didnt encounter the problem

**To Reproduce**
Insert a remote syslog in the syspass configuration

**Event log**
Some lines from `syspass.log` file (within `config` directory) and sysPass event log that were logged when the error happened.

**Platform (please complete the following information):**
 - OS: Linux 
 - OS Version: Centos7
 - Browser: Firefox

**Additional context**
All the tests I've made were in docker environments

**Comment by nuxsmin** [comment]
Hello, please take a look to https://stackoverflow.com/questions/6137823/fatal-error-call-to-undefined-function-socket-create

Regards

**Comment by Altes** [comment]
It shouldnt be already shipped / enable inside the docker image?

**Comment by nuxsmin** [comment]
Sorry, I missed the last sentence of the issue...It should indeed. I'm using the Docker image for development. Which image version are you running?

**Comment by Altes** [comment]
I tried (and got the error) with the following docker images:

- 3.1-RC3
        3.1.0-rc3-php7.2
        3.1.0-rc3-php7.3   

      

- 3.1-RC4
        3.1.0-rc4-php7.2
        3.1.0-rc4-php7.3


I've used a 3.0.5 docker image and i didnt encounter this issue

Note: If i remember correctly for the DB i used the docker image "mariadb-10.3.16"
