### ISSUE TITLE
Wiki URL modification

### ISSUE THREAD

**Issue by WEBudoGT** [nuxsmin/sysPass#1378]
Version 3.1-RC4

I need to change the final Wiki URL to replace spaces by dashes in cases where customers/accounts include spaces %20 because my Wiki (BookStack) uses dashes instead of spaces.
If it's something I can do on source code to make it happen, I would like to know where it is (my programming exprience is limited to Perl, but I can make an effort to figure out how to do it on php).

Thanks!

**Comment by nuxsmin** [comment]
Hello, it could be achieved by creating a new theme (cloning the default one and renaming it) and modifying this line: https://github.com/nuxsmin/sysPass/blob/5eaaac46593ec883c574f8b98f54963c548da2fa/app/modules/web/themes/material-blue/views/account/search-rows.inc#L219

This could be a solution:

```php
<a href="<?php echo $_getvar('wikiPageUrl'), str_replace(' ', '-', $accountSearchData->getName());?>" target="_blank">
  <i class="material-icons" title="<?php echo __('Link to Wiki'); ?>">library_books</i>
</a>
```
By creating a new theme you will avoid to replace your custom code with the original.

Regards
