### ISSUE TITLE
Private Account Preset

### ISSUE THREAD

**Issue by pabloalbea** [nuxsmin/sysPass#1379]
**sysPass Version**
 3.1-RC4 (310.19052503)

**Describe the question**
Hi.
In Private Account Preset I need to enforce Private Account for Group as enabled for a profile but without enforcing the Private account configuration. How can I do that?
Also in Private Account Preset, if you enable Private Account For Group (without forced), that configuration does not apply if the profile has the "Private for Group" permission disabled. Is that behavior okay?
Thanks.

**Platform:**
Ubuntu 18.04.2 LTS (php 7.3)
Browser Chrome (Windows 10)

**Comment by nuxsmin** [comment]
Hi,

> In Private Account Preset I need to enforce Private Account for Group as enabled for a profile but without enforcing the Private account configuration. How can I do that?

You can do it indeed, though I think I'm missing something...

> Also in Private Account Preset, if you enable Private Account For Group (without forced), that configuration does not apply if the profile has the "Private for Group" permission disabled. Is that behavior okay?

Yes, it's the expected behavior, because the computed ACL for the user won't let change this setting unless it's enable on the profile.

Regards
