### ISSUE TITLE
Theme Material Blue: The password update must be confirmed

### ISSUE THREAD

**Issue by steevegldev** [nuxsmin/sysPass#138]
This is minor but I spend time to understand.

this "The password update must be confirmed" refer to "Confirm change"

The warnings under "Do not modify accounts" make the use of  "Confirm change" unclear

**Comment by nuxsmin** [comment]
* "Confirm change" is that, you need to check this before change the master password.
* "Do not modify accounts" means that the accounts' password won't be encrypted again with the new master pass. This worth when you change the master password and there were some errors, so you can go back.
