### ISSUE TITLE
Context not initialized

### ISSUE THREAD

**Issue by dmytro-talko** [nuxsmin/sysPass#1380]
Hello.
I wanted to install syspass 3.0.5. issued permissions to the project, executed the composer update command and there is always an error in the logs:
[EXCEPTION] [N/A] Context not initialized\n#0 /lib/SP/Core/Context/ContextBase.php(143): SP\\Core\\Context\\ContextBase->checkContext()
#1 /lib/SP/Core/Context/SessionContext.php(100): SP\\Core\\Context\\ContextBase->getContextKey('locale', NULL)
#2 /lib/SP/Core/Context/SessionContext.php(392): SP\\Core\\Context\\SessionContext->getContextKey('locale')
#3 /lib/SP/Core/Language.php(209): SP\\Core\\Context\\SessionContext->getLocale()
#4 /lib/SP/Providers/Log/FileLogHandler.php(104): SP\\Core\\Language->setAppLocales()
#5 /lib/SP/Core/Events/EventDispatcherBase.php(121): SP\\Providers\\Log\\FileLogHandler->updateEvent('upgrade.config....', Object(SP\\Core\\Events\\Event))
#6 /lib/SP/Services/Upgrade/UpgradeConfigService.php(214): SP\\Core\\Events\\EventDispatcherBase->notifyEvent('upgrade.config....', Object(SP\\Core\\Events\\Event))
#7 /lib/SP/Bootstrap.php(420): SP\\Services\\Upgrade\\UpgradeConfigService->upgrade('300.18111001', Object(SP\\Config\\ConfigData))
#8 /lib/SP/Bootstrap.php(394): SP\\Bootstrap->checkConfigVersion()
#9 /lib/SP/Bootstrap.php(297): SP\\Bootstrap->initConfig()
#10 /lib/SP/Bootstrap.php(224): SP\\Bootstrap->initializeCommon()
#11 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)
#12 /vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)
#13 /vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)
#14 /lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))
#15 /lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))
#16 /index.php(28): require('...')
#17 {main}

I do not know what to do. Can you help me? Thanks.

**Comment by nuxsmin** [comment]
Hello,  are there any more messages?. This error could be raised quite often because it means that some application code is trying to access to a session object which isn't available yet (due to logout, etc.). 

If this error appears too many times, it could be issued by wrong permissions on PHP directories.

Regards

**Comment by dmytro-talko** [comment]
Hello, i have also another messages. 

[ERROR] [SP\Core\Language::setLocales] Could not set locale

We get null parameter $lang.

**Comment by nuxsmin** [comment]
These error are a "normal" behavior, because, some parts of the application could raise them on a very early stage when loading.
