### ISSUE TITLE
Temporary password - understanding

### ISSUE THREAD

**Issue by halobolah** [nuxsmin/sysPass#1381]
Hi everyone

I have a little problem with understanding what should I need to do.

When new user is trying to log in first time to system, he must insert master password (temporary master password). What I do:

1. I generate new temporary master password and send it to anyone from Admins group

![image](https://user-images.githubusercontent.com/28426539/60594036-5d7a3c00-9da4-11e9-9118-48a557ad8a2c.png)

2. User gets a new email:

![image](https://user-images.githubusercontent.com/28426539/60594073-6ff47580-9da4-11e9-9a73-5788c55a15ff.png)

3. And here is my question: how user can log in with this password ??

I don't understand this mechanism. 
I will be grateful for your help

**Comment by cRaZy-bisCuiT** [comment]
You **must not** create a new master key when a new user should login. All you do is create a temporary (derived) master key and give that one to the new user so he could use it for his first time login.

All the time you create a new master key the whole db will be de- and encrypted with the new key which could in theory cause issues.

@nuxsmin could explain this much better I guess.

**Comment by halobolah** [comment]
Hi cRaZy-bisCuiT :)

Yes, I know that I should use temporary master password:

1. I create new master password and send it to all users from Users group

![image](https://user-images.githubusercontent.com/28426539/60655391-eef1b880-9e4d-11e9-901a-6adcec1afcc3.png)

2. Users got this email:

![image](https://user-images.githubusercontent.com/28426539/60655437-fd3fd480-9e4d-11e9-98d1-a6500529522a.png)

and what next ?? where is this temporary master password ??

The new Master Password is: 0c53ee6cef0a7497be672150f8e0a41781027ec41556d8bb243149563bae8c11 - if I good understand this is hash

Maybe I'm creating this temporary master password wrong ?? So please can you help me do it correctly ??

One more strange thing: when I generate new temp master pass I always see:

![image](https://user-images.githubusercontent.com/28426539/60655629-63c4f280-9e4e-11e9-974f-ffa3429e55af.png)


is it correct ?? :)

**Comment by nuxsmin** [comment]
@halobolah Hello, a master key could be built by any characters, so it would appear like a hash but it's the key used to encrypt the current master key.

Users would receive an email containing the master key (the temporary one indeed), and then they need to enter it when logging in. Why is it called master key and not temporary master key?: It's a matter of fancy naming, so could always call it master key on every context. They don't need to know there are several keys...

Not sure about why it doesn't display the temporary key details, but it should...

Regards

**Comment by halobolah** [comment]
@nuxsmin

thank you for your answer, so if I good understand the "hash" is in fact the password which I should  enter in the "Master password" field when user tries to log in ?? :)

**Comment by nuxsmin** [comment]
@halobolah right!
