### ISSUE TITLE
Duplicate column name 'versionLevel'

### ISSUE THREAD

**Issue by dmytro-talko** [nuxsmin/sysPass#1382]
**sysPass Version**
3.1-rc4

**Describe the question**
After inserted the upgrade key and continued to get an error 

[EXCEPTION] [SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'versionLevel'
#0 /lib/SP/Services/Upgrade/UpgradeDatabaseService.php(173): PDO->exec(String)
#1 /lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\\Services\\Upgrade\\UpgradeDatabaseService->applyUpgrade(String)
#2 /app/modules/web/Controllers/UpgradeController.php(89): SP\\Services\\Upgrade\\UpgradeDatabaseService->upgrade(String,Object(SP\\Config\\ConfigData))
#3 [internal function]: SP\\Modules\\Web\\Controllers\\UpgradeController->upgradeAction()
#4 /lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#5 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)
#6 /vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)
#7 /vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route),Object(Klein\\DataCollection\\RouteCollection),Array)
#8 /lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))
#9 /lib/Base.php(75): SP\\Bootstrap->run(Object(DI\\Container))
#10 /index.php(28): require(String)] N/A, referer: /index.php?r=upgrade/index

Can you help me? Thanks.

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commits.

Thanks for the feedback!
