### ISSUE TITLE
MYSQL Access denied for user

### ISSUE THREAD

**Issue by ktoczyski** [nuxsmin/sysPass#1387]
Hi,

I have problem with sysPass3 when I changed IP address on my WWW server (I change IP address for user in MySQL database).

In log I see:

2019-07-08 10:24:08 [EXCEPTION] [N/A] (P) SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'syspass'@'10.1.1.11' (using password: YES)

When I log to MySQL via MySQL client all is ok:

mysql -h 192.168.200.103 -u syspass -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.

mysql> show tables;
+-----------------------+
| Tables_in_syspass     |
+-----------------------+
| account               |
| account_data_v        |
| account_search_v      |
| accountfile           |
| accounthistory        |
...
28 rows in set (0.00 sec)

I also create second user (with access from all hosts ) and the situation is the same.

2019-07-08 10:25:38 [EXCEPTION] [N/A] (P) SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'syspass2'@'%' (using password: YES)

New sysPass instance with old database and the situation is the same.

All other websites with SQL works ok for ma change, only problem is with sysPass. Any idea what is wrong?

**Comment by sf32738** [comment]
@ktoczyski  -  a little more information about your environment setup would be helpful.  I see to different IP4 subnets represented in your output.  10.1.1.11 and 192.168.200.103

10.1.1.11 appears to be your syspass instance / server
192.168.200.103 appears to be your database instance

are you running two different VMs / two different docker containers / ??

based on the error provided, the password being supplied via the config.xml is invalid.

From your syspass instance (server), please confirm that the password is correctly entered in the config.xml file.

```
cat config.xml | grep "<db"

>>> output <<<

  <dbHost>172.16.1.11</dbHost>
  <dbName>syspass</dbName>
  <dbPass>{{redacted}}</dbPass>
  <dbPort>3306</dbPort>
  <dbSocket></dbSocket>
  <dbUser>sp_5d2352b32682c</dbUser>

```

**Comment by ktoczyski** [comment]
Address 10.1.1.11 it is my web server with sysPass
Address 192.168.200.103  it is my SQL server (MySQL)

I run this in containers (Jails FreeBSD).

Routing between this containers are ok. I can log via mysql client from web server to SQL server.

```
% mysql -h 192.168.200.103 -u syspass -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 104209
Server version: 5.7.25-log Source distribution

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```

Password to database is ok, I use it to login via client in shell.

But via sysPass doesn't work.

```
Service Unavailable

SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'syspass'@'10.1.1.11' (using password: YES)
```

I also change password, privileges for syspass user but situation is the same.

```
SHOW GRANTS FOR 'syspass'@'10.1.1.11';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE  ON `syspass`.* TO 'syspass'@'10.1.1.11';
FLUSH PRIVILEGES; 
```

**Comment by ktoczyski** [comment]
Last update. I found resolution.

In database you use views. Where Definer = user@LOCAL_IP. This values had old IP.

I change this via mysql client to:

```
ALTER ALGORITHM = UNDEFINED DEFINER=`syspass`@`10.1.1.11` SQL SECURITY DEFINER VIEW `account_search_v` ...
ALTER ALGORITHM = UNDEFINED DEFINER=`syspass`@`10.1.1.11` SQL SECURITY DEFINER VIEW `account_data_v` ...
```

and now works all ok. Maybe you add to sysPass detection IP or something else (eg. information how to change this via SQL on wiki/FAQ).

**Comment by sf32738** [comment]
Good to here.  You beat me to my next question -- the VIEW permissions that were set.
