### ISSUE TITLE
Is sysPass 3.1-RC4 production ready?

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [nuxsmin/sysPass#1389]
Hello everyone,

I do currently use **3.0 (305.19020701)** . My question is: Does **sysPass 3.1-RC4** run stable enough for a productive use?

In that case I might switch for security reasons.

**Comment by ortizleo** [comment]
+1 for this question.
We are using version 3.0 (305.19020701) and this version have some bugs that was fixed in 3.1. We really are waiting for 3.1 release version...

**Comment by nuxsmin** [comment]
Hello, yes it should since many major changes are related to plugins architecture, but I'd like to review latest issues for any undetected bug.

I'm lately lacking of time, but I'm pretty sure it will be ready by first week of August.

Thanks for the feedback!

Regards
