### ISSUE TITLE
3.1-RC4 - AD LDAP Group Import doesn't work

### ISSUE THREAD

**Issue by twindscheif** [nuxsmin/sysPass#1390]
**sysPass Version**
3.1-RC4

**Describe the bug**
No groups are imported although the test-button results into 1 possible object to import.

**To Reproduce**
1. LDAP-Configuration page
2. Setup LDAP-Configuration in the upper section.
3. Enable "Import Groups"
4. In the Import section on "Filter" i add following ldap-search-query: 
`(&(objectCategory=group)(memberOf:1.2.840.113556.1.4.1941:=CN=RG-syspass-syncedgroups,OU=ResGroups,OU=syspass,OU=Services,DC=mydomain,DC=int))`
Expression is used for revealing nested groups.
5. Click on Test-button shows:
![syspass_ldap_groupimport_test](https://user-images.githubusercontent.com/39372993/61053060-0d772700-a3ed-11e9-9d0e-74f4518280e4.png)
6. Click on import shows:
![syspass_ldap_groupimport_issue](https://user-images.githubusercontent.com/39372993/61053192-5e871b00-a3ed-11e9-9c99-f09817c85484.png)

**Expected behavior**
I except that the prior with test-button found group is imported if i press import.

**Event log**
There is no error recorded.

**Platform (please complete the following information):**
 - OS: centOS
 - OS 7 (build: 1804)
 - Browser Firefox [Version: 68.0]

**Additional context**
The shown group which is shown on clicking test is member of the group used in the ldap filter. I want to filter the groups imported into syspass via this group.
Both, the User-group in the upper section of the ldap-Configuration and the resolved group which should be imported have one user as member listed.
The LDAP-Source used is Active Directory.

**Comment by twindscheif** [comment]
Found the reason!
[https://github.com/nuxsmin/sysPass/blob/6197c52af128b1aab48af5f5990c73279495617f/app/modules/web/Controllers/ConfigLdapController.php#L272](url)
Currently import of groups is not possible if the Filter is is not empty.
@nuxsmin Is there a reason for it?

If i remove `&& empty($filter)` in that if-clause, the group is imported correctly.

**Comment by nuxsmin** [comment]
Hello, it seems that I forgot to remove that condition. I'll find out is there is some reason to not remove it.

Thanks for the notice!

Regards
