### ISSUE TITLE
How to deploy Authenticator plugin v2

### ISSUE THREAD

**Issue by iansimoneau** [nuxsmin/sysPass#1393]
Hi,

I just deployed latest Syspass version using docker composer. Now I am trying to figure out how to install the Authenticator plugin over that installation. I am new to docker so I do not know how environnement variable works and where to put them exactly. Tried a few things but I cannot get it to work.

Do you have any tips to give me? 

Thank you very much

**Comment by Lightningpicture** [comment]
https://github.com/nuxsmin/sysPass/issues/1281#issuecomment-510914200

**Comment by iansimoneau** [comment]
Thank you very much, the entire thread helped me a lot.
