### ISSUE TITLE
"Application URL" doesn't affect to logo url

### ISSUE THREAD

**Issue by kalxasus** [nuxsmin/sysPass#1395]
**sysPass Version**
3.1-RC4

**Describe the bug**
If set "Application URL" to  https://some-domain.com/syspass in configuration with reverse proxy
changes doesn't affect to url for logo /public/images/logo_full_nobg_outline_color.png
In the result missing syspass logo on all pages and favicon in browser.
Other data have correct url and are displayed correctly.

**To Reproduce**
1. Configuration -> General 
2. Set parameter 'Application URL' to https://some-domain.com/syspass
3. Setup reverse proxy (in my case apache)
```
        ProxyPass /syspass http://127.0.0.1:8086
        ProxyPassReverse /syspass http://127.0.0.1:8086
```
4. Login in syspass and see error

**Screenshots**

![Screenshot_at_09-27-44](https://user-images.githubusercontent.com/29705434/61271971-9b1c9300-a7ae-11e9-978a-0dfb58e95d00.png)

**Event log**
In browser console be error:

> GET https://some-domain.com/public/images/logo_full_nobg_outline_color.png 404 (Not Found)

**Platform:**
 - OS: Linux
 - Browser: Firefox, Chrome
 - sysPass: runing in docker
 - Proxy: Apache

**Comment by nuxsmin** [comment]
Hello, I'll fix it shortly. I forgot to update the logo URL using the  newly  added URL feature.

Thanks for the feedback!

Regards
