### ISSUE TITLE
Problem with importing accounts with XML

### ISSUE THREAD

**Issue by yawnbros** [nuxsmin/sysPass#1396]
**sysPass Version**
3.0 (305.19020701) 

**Describe the bug**
Exported an encrypted xml from a SysPass 2.1 instance. Trying to import the xml returns a message "Internal error while reading the file"

The SysPass log contains the following:
[EXCEPTION] [N/A] Internal error while reading the file

**To Reproduce**
1. Go to Configuration
2. Click on Import Accounts
3. Add exported encrypted XML password as Import Password
4. Add Master password from SysPass instance where the export was made from
5. Click the cloud icon and browse for the exported XML

**Event log**
Lines from `syspass.log` file (within `config` directory) that were logged when the error happened.

2019-07-17 08:50:33 [EXCEPTION] [N/A] Internal error while reading the file
#0 /var/www/html/syspass/lib/SP/Services/Import/FileImport.php(67): SP\Services\Import\FileImport::checkFile(Array)
#1 /var/www/html/syspass/app/modules/web/Controllers/ConfigImportController.php(75): SP\Services\Import\FileImport::fromRequest('inFile', Object(SP\Http\Request))
#2 [internal function]: SP\Modules\Web\Controllers\ConfigImportController->importAction()
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#10 {main}
2019-07-17 08:50:33 [EXCEPTION] [N/A] (P) File not found ()
#0 /var/www/html/syspass/lib/SP/Services/Import/FileImport.php(91): SP\Storage\File\FileHandler->checkFileExists()
#1 /var/www/html/syspass/lib/SP/Services/Import/FileImport.php(67): SP\Services\Import\FileImport::checkFile(Array)
#2 /var/www/html/syspass/app/modules/web/Controllers/ConfigImportController.php(75): SP\Services\Import\FileImport::fromRequest('inFile', Object(SP\Http\Request))
#3 [internal function]: SP\Modules\Web\Controllers\ConfigImportController->importAction()
#4 /var/www/html/syspass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/syspass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#9 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#10 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')

**Platform**
 - OS: Linux
 - OS Version: Centos 7
 - Browser: Firefox

**Additional Information**
The exported XML is over 2mb. This was attempted several times and initially encountered a max file size issue. The server has been rebooted and this has been retried with the same issue.

**Comment by nuxsmin** [comment]
Hello,  it seems that the intermediate temporary file cannot be read. This file is generated by PHP when uploading any file to the web server, then sysPass will parse it to perform the importing task.

Regards

**Comment by nuxsmin** [comment]
I just noticed you're running it on CentOS so it would be possible that selinux is not allowing to read the temporary file.

**Comment by nuxsmin** [comment]
I'm wondering if you're trying to upgrade to sysPass v3. If so, you can upgrade it in-place, since sysPass will upgrade the database structure and data.

**Comment by yawnbros** [comment]
I have set selinux to permissive and the problem still occurs. Do you know where the file is generated and what the permissions on the location should be?

I am trying to setup a new separate v3 instance with some of the data from the original v2 instance. I don't need the original instance's users, groups or permissions so I wanted to just do an export>import.

**Comment by nuxsmin** [comment]
@yawnbros it's generated by PHP itself, inside a default location defined in PHP settings, but I'm quite confident about its permissions, since they were set when PHP was installed by the package manager.

**Comment by yawnbros** [comment]
@nuxsmin Ok, thanks nuxsmin, do you have any other suggestions? Could it be because the export is from 2.1?

**Comment by nuxsmin** [comment]
>  do you have any other suggestions?

What web server are you running on?. Which PHP version are you running?

> Could it be because the export is from 2.1?

No, because sysPass failed before parsing the file, because it wasn't found within temp dir.
