### ISSUE TITLE
Can't edit imported account's password

### ISSUE THREAD

**Issue by shindelhu** [nuxsmin/sysPass#1398]
**sysPass Version**

sysPass version | 3.0 (305.19020701) Config: 305.19020701 App: 305.19020701 DB: 305.19020701
-- | --
Database | SERVER_VERSION : 5.5.60-MariaDB CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $ SERVER_INFO : Uptime: 2318 Threads: 2 Questions: 2794 Slow queries: 0 Opens: 27 Flush tables: 2 Open tables: 53 Queries per second avg: 1.205 CONNECTION_STATUS : 127.0.0.1 via TCP/IP Name: syspass@127.0.0.1
PHP | Version: 7.2.15 Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, mysqlnd, PDO, Phar, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, zip, xdebug Used Memory: 4096 KB User: apache Download rate: 43 MB/s
Server | Apache/2.4.6 (Red Hat Enterprise Linux) PHP/7.2.15

**Describe the bug**
We've imported lots of accounts from CSV.
Not able to edit imported accounts password. The page said saved successfully, no error in the logs, but later, when you check it, it gives the previous password.
Not happening to manually created accounts, only imported.

**Expected behavior**
To be able to edit passwords.

**Platform (please complete the following information):**
 - OS: RHEL7
 - Browser Any

Could you please help us?
Regards,
Imre

**Comment by andrucha97** [comment]
Just for notice. XML does works. I imported from keepass :)

**Comment by shindelhu** [comment]
> Just for notice. XML does works. I imported from keepass :)

The import worked for us too....after the import, can't change the password for the imported items, even if it says password changed, but it's not.

**Comment by andrucha97** [comment]
Yeah I understood. I imported with XML and the edit of passwords works with web or api great.
