### ISSUE TITLE
setup new syspass and add backedup account getting integrity check failed error.

### ISSUE THREAD

**Issue by kkumari-ptc** [nuxsmin/sysPass#1400]
**sysPass Version**
2.1 (2.1.16.18061901)

**Describe the bug**
setup new syspass server and take the account table dump to restore the data but after 1 month getting 'Integrity check failed error' while viewing the passwords with all the user account

**Comment by kkumari-ptc** [comment]
I am using 'nuxsmin/docker-syspass:latest' image for the server do I need to update the image.

**Comment by kkumari-ptc** [comment]
Also updated the syspass image to syspass/syspass:3.0.5 and restored the accounts table but after login with admin user cann't see any accounts.

**Comment by nuxsmin** [comment]
Hello, please take a look to database views permission, since they usually take the user which performed the export.

Regards

**Comment by kkumari-ptc** [comment]
Don't understand I had create new db in differenet aws region and only exported the account table.

**Comment by kkumari-ptc** [comment]
I had restored from back but while login getting : 
error_outline Error while checking the database

**Comment by nuxsmin** [comment]
Did you mean you can't get the passwords?. Besides a database export/import you need to copy the files within config directory. Be aware that the new config directory is within '.../app' directory.

Regards

**Comment by nuxsmin** [comment]
Please restore to the same sysPass version and then perform the upgrade to v3

**Comment by kkumari-ptc** [comment]
After restoring and updating the version from last 1 hour I am getting : 
error_outline Application in maintenance
It will be running shortly

How long will it take to update version .

**Comment by kkumari-ptc** [comment]
After updating the version getting following from last few hours: 
error_outline Application in maintenance
It will be running shortly.
 
how long it will take to update to new version.

following logs are genetrated:
7/22/2019 6:28:47 PMentrypoint: Starting with UID : 9001
7/22/2019 6:28:47 PMsetup_app: Setting up permissions
7/22/2019 6:28:47 PMsetup_locales: Setting up locales
7/22/2019 6:28:47 PMGenerating locales (this might take a while)...
7/22/2019 6:28:49 PM  ca_ES.UTF-8... done
7/22/2019 6:28:50 PM  de_DE.UTF-8... done
7/22/2019 6:28:50 PM  en_GB.UTF-8... done
7/22/2019 6:28:51 PM  en_US.UTF-8... done
7/22/2019 6:28:52 PM  es_ES.UTF-8... done
7/22/2019 6:28:53 PM  fr_FR.UTF-8... done
7/22/2019 6:28:54 PM  nl_NL.UTF-8... done
7/22/2019 6:28:54 PM  pl_PL.UTF-8... done
7/22/2019 6:28:55 PM  pt_BR.UTF-8... done
7/22/2019 6:28:56 PM  ru_RU.UTF-8... done
7/22/2019 6:28:56 PM  da.UTF-8...cannot open locale definition file `da': No such file or directory
7/22/2019 6:28:56 PM done
7/22/2019 6:28:56 PMGeneration complete.
7/22/2019 6:28:56 PM######
7/22/2019 6:28:56 PMsysPass environment installed and configured. Please point your browser to http://10.42.14.159 to start the installation
7/22/2019 6:28:56 PM######
7/22/2019 6:28:56 PMentrypoint: Starting Apache
7/22/2019 6:28:56 PMAH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.14.159. Set the 'ServerName' directive globally to suppress this message

**Comment by kkumari-ptc** [comment]
Attaching log file 
[syspass.log](https://github.com/nuxsmin/sysPass/files/3418000/syspass.log)

**Comment by kkumari-ptc** [comment]
I am searching for 2.1 version docker image but couldn't find it.

**Comment by kkumari-ptc** [comment]
I tried restoring config from backup and also restore db and I am getting login page with error:
undefined 
forbidden

**Comment by kkumari-ptc** [comment]
I just restored data from old db to the new server.
Restoring is a little tricky one as with the update version 3.0 database table name and structure is completely changed, so have to update dump sql query to restore. So I restore the following table data :
'categories'  to  'Category' and 'accounts' to 'Account'.

**Comment by nuxsmin** [comment]
> I am searching for 2.1 version docker image but couldn't find it.

It should be on Docker hub (either on nuxsmin or syspass account).


Please **do not update sysPass manually**, since many changes need to be done through the code itself (ie. Custom fields and public links).

Regards

**Comment by kkumari-ptc** [comment]
Following are step I followed : 

1. deployed latest version of syspass.
2.Created new database for syspass server.
3. Used same admin and master password from the previous server for setup.
4. Restored categories and accounts data.

All we require the account data in decrypted formatted.
I will update in case of an issue in future.

**Comment by nuxsmin** [comment]
Please read the doc on https://doc.syspass.org/en/3.0/updating/v3.html
