### ISSUE TITLE
Failed upgrade to 3.1.0-rc5

### ISSUE THREAD

**Issue by Envikia** [nuxsmin/sysPass#1401]
**sysPass Version**
From a fresh installed `syspass:3.0.5` to `syspass:3.1.0-rc5`  (Both are docker version)

**Describe the bug**
It was found the issue as similar as #1330 .  A table seems failed to create due to Foreign key issue?
An error "Error while updating the database" occurs to perform the upgrade.
For reference: my database version is `mariadb:10.4`

**To Reproduce**
1. Filled in Security Code
2. Checked-out "I have done a full backup"
3. Pressed "Upgrade" button
4. An error "Error while updating the database" occurs on the browser
5. See syspass log as below.

**Screenshots**
![PicPick_20190724_104603_2](https://user-images.githubusercontent.com/45445297/61765210-b589e880-ae0e-11e9-9bdb-1bf0dc42e243.png)

**Event log**
```
syspass    | [Wed Jul 24 10:46:00.943862 2019] [:error] [pid 719] [client 103.26.123.66:57293] [INFO] [Extensions checked] SP\\Core\\PhpExtensionChecker::checkMandatory, referer: https://52.195.3.244/index.php?r=upgrade/index
syspass    | [Wed Jul 24 10:46:00.945670 2019] [:error] [pid 719] [client 103.26.123.66:57293] [INFO] [Loaded icons cache] SP\\Core\\UI\\Theme::initIcons, referer: https://52.195.3.244/index.php?r=upgrade/index
syspass    | [Wed Jul 24 10:46:00.946323 2019] [:error] [pid 719] [client 103.26.123.66:57293] [INFO] [Loaded actions cache] SP\\Core\\Acl\\Actions::loadCache, referer: https://52.195.3.244/index.php?r=upgrade/index
syspass    | [Wed Jul 24 10:46:00.975656 2019] [:error] [pid 719] [client 103.26.123.66:57293] [EXCEPTION] [SQLSTATE[HY000]: General error: 1005 Can't create table `syspassdb`.`PluginData` (errno: 150 "Foreign key constraint is incorrectly formed")\n#0 /var/www/html/sysPass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(173): PDO->exec(String)\n#1 /var/www/html/sysPass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\\Services\\Upgrade\\UpgradeDatabaseService->applyUpgrade(String)\n#2 /var/www/html/sysPass/app/modules/web/Controllers/UpgradeController.php(89): SP\\Services\\Upgrade\\UpgradeDatabaseService->upgrade(String,Object(SP\\Config\\ConfigData))\n#3 [internal function]: SP\\Modules\\Web\\Controllers\\UpgradeController->upgradeAction()\n#4 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)\n#5 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#7 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route),Object(Klein\\DataCollection\\RouteCollection),Array)\n#8 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))\n#9 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap->run(Object(DI\\Container))\n#10 /var/www/html/sysPass/index.php(28): require(String)] N/A, referer: https://52.195.3.244/index.php?r=upgrade/index
syspass    | 103.26.123.66 - - [24/Jul/2019:10:46:00 +0800] "GET /index.php?r=upgrade/upgrade&key=fe9f0cf8c93fe0df04e57dba875823e1&chkConfirm=on&_=1563936326808 HTTP/1.1" 200 1729 "https://52.195.3.244/index.php?r=upgrade/index" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
syspass    | [Wed Jul 24 10:46:00.976879 2019] [:error] [pid 719] [client 103.26.123.66:57293] [EXCEPTION] [Error while updating the database\n#0 /var/www/html/sysPass/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\\Services\\Upgrade\\UpgradeDatabaseService->applyUpgrade(String)\n#1 /var/www/html/sysPass/app/modules/web/Controllers/UpgradeController.php(89): SP\\Services\\Upgrade\\UpgradeDatabaseService->upgrade(String,Object(SP\\Config\\ConfigData))\n#2 [internal function]: SP\\Modules\\Web\\Controllers\\UpgradeController->upgradeAction()\n#3 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)\n#4 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route),Object(Klein\\DataCollection\\RouteCollection),Array)\n#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))\n#8 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap->run(Object(DI\\Container))\n#9 /var/www/html/sysPass/index.php(28): require(String)] N/A, referer: https://52.195.3.244/index.php?r=upgrade/index

```

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 68.0.1

**Comment by nuxsmin** [comment]
Hello, I'm not sure why it throws ```General error: 1005 Can't create table `syspassdb`.`PluginData` (errno: 150 "Foreign key constraint is incorrectly formed"``` since foreign key is well formed (ie. same fields definition).

Could you try to apply the patch manually? (though you should restore the database and then upgrade again from the web UI): https://github.com/nuxsmin/sysPass/blob/master/schemas/31019012201.sql 

Regards

**Comment by Envikia** [comment]
> 
> 
> Hello, I'm not sure why it throws `` General error: 1005 Can't create table `syspassdb`.`PluginData` (errno: 150 "Foreign key constraint is incorrectly formed" `` since foreign key is well formed (ie. same fields definition).
> 
> Could you try to apply the patch manually? (though you should restore the database and then upgrade again from the web UI): https://github.com/nuxsmin/sysPass/blob/master/schemas/31019012201.sql
> 
> Regards

Hi @nuxsmin , thanks for your guide.
I have clean install syspass:3.0.5 with a clean DB, and then execute the DB Patch.
Unfortunately, it is seems failed too ...
```
root@mariadb:/# mysql -u syspassusr2 -p syspassdb305 < /var/lib/mysql/31019012201.sql
Enter password:
ERROR 1005 (HY000) at line 6: Can't create table `syspassdb305`.`PluginData` (errno: 150 "Foreign key constraint is incorrectly formed")
root@mariadb:/#

```

Please suggest, thanks in advance.

**Comment by nuxsmin** [comment]
Hello, it seems to be a MariaDB version issue. I'll check out which changes would have been affected to the DDL scripts.

**Comment by nuxsmin** [comment]
Can you replace the code within `31019012201.sql` file by this one and then run the upgrade again?:

```
DELIMITER $$

alter table Plugin
  add versionLevel varchar(15) null $$

create table PluginData
(
	name varchar(100) not null,
	itemId int not null,
	data blob not null,
	`key` varbinary(2000) not null,
	primary key (name, itemId),
	constraint fk_PluginData_name
		foreign key (name) references Plugin (name)
			on update cascade on delete cascade
)$$
```

**Comment by Envikia** [comment]
> 
> 
> Can you replace the code within `31019012201.sql` file by this one and then run the upgrade again?:
> 
> ```
> DELIMITER $$
> 
> alter table Plugin
>   add versionLevel varchar(15) null $$
> 
> create table PluginData
> (
> 	name varchar(100) not null,
> 	itemId int not null,
> 	data blob not null,
> 	`key` varbinary(2000) not null,
> 	primary key (name, itemId),
> 	constraint fk_PluginData_name
> 		foreign key (name) references Plugin (name)
> 			on update cascade on delete cascade
> )$$
> ```

Hello, I also believe that it is MariaDB version issue...

The SQL still not work, however, when I mysqldump from a clean syspass:3.1.0 DB, and then replace it to `31019012201.sql` for the upgrade, the upgrade successfully.
```
DELIMITER $$

alter table Plugin
  add versionLevel varchar(15) null $$

CREATE TABLE `PluginData` (
  `name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `itemId` int(11) NOT NULL,
  `data` blob NOT NULL,
  `key` varbinary(2000) NOT NULL,
  PRIMARY KEY (`name`,`itemId`),
  CONSTRAINT `fk_PluginData_name` FOREIGN KEY (`name`) REFERENCES `Plugin` (`name`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci$$

```

Weird....it is quite different between your tested environment `MariaDB 10.1`  and my DB version `MariaDB 10.4`...

Thanks @nuxsmin for keep following and helping!

**Comment by nuxsmin** [comment]
It seems that `itemId` int(11) NOT NULL,` is the key point. The other stuff are the defaults settings inherited from the database.

**Comment by nuxsmin** [comment]
Thanks for the feedback again!
