### ISSUE TITLE
LDAP still broken? (invalid credential 49)

### ISSUE THREAD

**Issue by execcr** [nuxsmin/sysPass#1402]
**sysPass Version**

3.0 (305.19020701) Config: 305.19020701 App: 305.19020701 DB: 305.19020701
--
Database | SERVER_VERSION : 5.5.60-MariaDB CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $ SERVER_INFO : Uptime: 153 Threads: 1 Questions: 541 Slow queries: 0 Opens: 17 Flush tables: 2 Open tables: 43 Queries per second avg: 3.535 CONNECTION_STATUS : Localhost via UNIX socket Name: syspass@localhost
PHP | Version: 7.1.30 Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mcrypt, mysqlnd, PDO, Phar, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, zip Used Memory: 4096 KB User: root Download rate: 43 MB/s
Server | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.30
Configuration Backup | Wed, 24 Jul 2019 13:46:58 +0000

**Describe the bug**
I cannot setup LDAP connection to a Server 2012r2 DC.

**To Reproduce**
1. Go to Ldap Setting
2. fill the field as my 2.4 syspass installation
3. Try connection
4. Get Connection Error (BIND) - Invalid Credential (49)

**Expected behavior**
I should get validated, parameters are the same of my old installlation, just new VM.

**Event log**
ssl_error_log:
[php7:notice] [pid 1730] [client 192.168.0.43:43224] [EXCEPTION] [N/A] Connection error (BIND)\n#0 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\\Providers\\Auth\\Ldap\\LdapConnection->bind()\n#1 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\\Providers\\Auth\\Ldap\\LdapConnection->connectAndBind()\n#2 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/Ldap.php(96): SP\\Providers\\Auth\\Ldap\\LdapConnection->checkConnection()\n#3 /var/www/html/sysPass/lib/SP/Services/Ldap/LdapCheckService.php(51): SP\\Providers\\Auth\\Ldap\\Ldap::factory(Object(SP\\Providers\\Auth\\Ldap\\LdapParams), Object(SP\\Core\\Events\\EventDispatcher), true)\n#4 /var/www/html/sysPass/app/modules/web/Controllers/ConfigLdapController.php(152): SP\\Services\\Ldap\\LdapCheckService->checkConnection(Object(SP\\Providers\\Auth\\Ldap\\LdapParams))\n#5 [internal function]: SP\\Modules\\Web\\Controllers\\ConfigLdapController->checkAction()\n#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)\n#7 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#8 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#9 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#10 /var/www/html/sysPass/lib/SP/Bootstrap.php(461): Klein\\Klein->dispatch(Object(Klein\\Request))\n#11 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#12 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')\n#13 {main}, referer: https://syspass.isindustrial.local/index.php?r=index

error_log:
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/openldap/ldap.conf
ldap_init: using /etc/openldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
ldap_create
ldap_url_parse_ext(ldap://192.168.0.5:389)
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP 192.168.0.5:389
ldap_new_socket: 17
ldap_prepare_socket: 17
ldap_connect_to_host: Trying 192.168.0.5:389
ldap_pvt_connect: fd: 17 tm: 10 async: 0
ldap_ndelay_on: 17
attempting to connect: 
connect errno: 115
ldap_int_poll: fd: 17 tm: 10
ldap_is_sock_ready: 17
ldap_ndelay_off: 17
ldap_pvt_connect: 0
ldap_open_defconn: successful
ldap_send_server_request
ldap_result ld 0x55f3bfeabf60 msgid 1
wait4msg ld 0x55f3bfeabf60 msgid 1 (infinite timeout)
wait4msg continue ld 0x55f3bfeabf60 msgid 1 all 1
** ld 0x55f3bfeabf60 Connections:
* host: 192.168.0.5  port: 389  (default)
  refcnt: 2  status: Connected
  last used: Wed Jul 24 15:51:43 2019

** ld 0x55f3bfeabf60 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55f3bfeabf60 request count 1 (abandoned 0)
** ld 0x55f3bfeabf60 Response Queue:
   Empty
  ld 0x55f3bfeabf60 response count 0
ldap_chkResponseList ld 0x55f3bfeabf60 msgid 1 all 1
ldap_chkResponseList returns ld 0x55f3bfeabf60 NULL
ldap_int_select
read1msg: ld 0x55f3bfeabf60 msgid 1 all 1
read1msg: ld 0x55f3bfeabf60 msgid 1 message type bind
read1msg: ld 0x55f3bfeabf60 0 new referrals
read1msg:  mark request completed, ld 0x55f3bfeabf60 msgid 1
request done: ld 0x55f3bfeabf60 msgid 1
res_errno: 49, res_error: <80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_parse_result
ldap_msgfree
ldap_err2string
ldap_err2string
ldap_err2string
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed

syspass.log
2019-07-24 13:51:43 [EXCEPTION] [N/A] Connection error (BIND)
#0 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\Providers\Auth\Ldap\LdapConnection->bind()
#1 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#2 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/Ldap.php(96): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#3 /var/www/html/sysPass/lib/SP/Services/Ldap/LdapCheckService.php(51): SP\Providers\Auth\Ldap\Ldap::factory(Object(SP\Providers\Auth\Ldap\LdapParams), Object(SP\Core\Events\EventDispatcher), true)
#4 /var/www/html/sysPass/app/modules/web/Controllers/ConfigLdapController.php(152): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#5 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(237): call_user_func_array(Array, Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/sysPass/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#11 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#12 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')
#13 {main}

**Platform (please complete the following information):**
- OS Centos 7 CentOS Linux release 7.6.1810 (Core)
Chrome Browser

**Additional context**
fresh install. I've used PHP 7.1

**Comment by deajan** [comment]
Have you tried following this https://github.com/nuxsmin/sysPass/issues/951#issuecomment-519052213 ?

**Comment by romainmunier** [comment]
Hello ! Sorry for my English but I've got a problem with SysPass Docker and LDAP...

I'm sorry to disturb you but I'm trying to use SysPass with Docker and LDAP but I can't connect to my LDAP serveur (because of Errno 49 : Invalid Credentials).

I know my ldap server is working well because I'm using it with another service.

Here is the log : 
```
[Mon Nov 22 19:16:45.477270 2021] [php7:notice] [pid 18] [client 104.28.135.9:18174] [INFO] [Loaded actions cache] SP\\Core\\Acl\\Actions::loadCache, referer: https://5.196.26.2:14001/index.php?r=index
ldap_create
ldap_url_parse_ext(ldap://romainmunier.ovh:389)
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP romainmunier.ovh:389
ldap_new_socket: 15
ldap_prepare_socket: 15
ldap_connect_to_host: Trying 5.196.26.2:389
ldap_pvt_connect: fd: 15 tm: 10 async: 0
ldap_ndelay_on: 15
attempting to connect: 
connect errno: 115
ldap_int_poll: fd: 15 tm: 10
ldap_is_sock_ready: 15
ldap_ndelay_off: 15
ldap_pvt_connect: 0
ldap_open_defconn: successful
ldap_send_server_request
ldap_result ld 0x55d6705ef710 msgid 1
wait4msg ld 0x55d6705ef710 msgid 1 (infinite timeout)
wait4msg continue ld 0x55d6705ef710 msgid 1 all 1
** ld 0x55d6705ef710 Connections:
* host: romainmunier.ovh  port: 389  (default)
  refcnt: 2  status: Connected
  last used: Mon Nov 22 19:16:45 2021


** ld 0x55d6705ef710 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55d6705ef710 request count 1 (abandoned 0)
** ld 0x55d6705ef710 Response Queue:
   Empty
  ld 0x55d6705ef710 response count 0
ldap_chkResponseList ld 0x55d6705ef710 msgid 1 all 1
ldap_chkResponseList returns ld 0x55d6705ef710 NULL
ldap_int_select
read1msg: ld 0x55d6705ef710 msgid 1 all 1
read1msg: ld 0x55d6705ef710 msgid 1 message type bind
read1msg: ld 0x55d6705ef710 0 new referrals
read1msg:  mark request completed, ld 0x55d6705ef710 msgid 1
request done: ld 0x55d6705ef710 msgid 1
res_errno: 49, res_error: <>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_parse_result
ldap_msgfree
ldap_err2string
ldap_err2string
ldap_err2string
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
[Mon Nov 22 19:16:45.520199 2021] [php7:notice] [pid 18] [client 104.28.135.9:18174] [EXCEPTION] [Erreur de connexion (BIND)\n#0 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\\Providers\\Auth\\Ldap\\LdapConnection->bind()\n#1 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\\Providers\\Auth\\Ldap\\LdapConnection->connectAndBind()\n#2 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/Ldap.php(96): SP\\Providers\\Auth\\Ldap\\LdapConnection->checkConnection()\n#3 /var/www/html/sysPass/lib/SP/Services/Ldap/LdapCheckService.php(51): SP\\Providers\\Auth\\Ldap\\Ldap->factory(Object(SP\\Providers\\Auth\\Ldap\\LdapParams),Object(SP\\Core\\Events\\EventDispatcher),Boolean)\n#4 /var/www/html/sysPass/app/modules/web/Controllers/ConfigLdapController.php(156): SP\\Services\\Ldap\\LdapCheckService->checkConnection(Object(SP\\Providers\\Auth\\Ldap\\LdapParams))\n#5 [internal function]: SP\\Modules\\Web\\Controllers\\ConfigLdapController->checkAction()\n#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)\n#7 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#8 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#9 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route),Object(Klein\\DataCollection\\RouteCollection),Array)\n#10 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))\n#11 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap->run(Object(DI\\Container))\n#12 /var/www/html/sysPass/index.php(28): require(String)] N/A, referer: https://5.196.26.2:14001/index.php?r=index
104.28.135.9 - - [22/Nov/2021:19:16:45 +0000] "POST /index.php?r=configLdap/check HTTP/1.1" 200 525 "https://5.196.26.2:14001/index.php?r=index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"
[Mon Nov 22 19:16:49.273483 2021] [php7:notice] [pid 18] [client 104.28.135.9:18174] [INFO] [Extensions checked] SP\\Core\\PhpExtensionChecker::checkMandatory, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:16:49.274658 2021] [php7:notice] [pid 18] [client 104.28.135.9:18174] [INFO] [Loaded icons cache] SP\\Core\\UI\\Theme::initIcons, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:16:49.290543 2021] [php7:notice] [pid 18] [client 104.28.135.9:18174] [INFO] [Loaded actions cache] SP\\Core\\Acl\\Actions::loadCache, referer: https://5.196.26.2:14001/index.php?r=index
104.28.135.9 - - [22/Nov/2021:19:16:49 +0000] "POST /index.php?r=configLdap/save HTTP/1.1" 200 502 "https://5.196.26.2:14001/index.php?r=index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"
[Mon Nov 22 19:16:49.363029 2021] [php7:notice] [pid 18] [client 104.28.135.9:18174] [INFO] [Extensions checked] SP\\Core\\PhpExtensionChecker::checkMandatory, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:16:49.363977 2021] [php7:notice] [pid 18] [client 104.28.135.9:18174] [INFO] [Loaded icons cache] SP\\Core\\UI\\Theme::initIcons, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:16:49.381575 2021] [php7:notice] [pid 18] [client 104.28.135.9:18174] [INFO] [Loaded actions cache] SP\\Core\\Acl\\Actions::loadCache, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:16:49.383698 2021] [php7:notice] [pid 18] [client 104.28.135.9:18174] [INFO] [Loaded MIME types cache] SP\\Core\\MimeTypes::loadCache, referer: https://5.196.26.2:14001/index.php?r=index
104.28.135.9 - - [22/Nov/2021:19:16:49 +0000] "GET /index.php?r=configManager/index&tabIndex=3&isAjax=1&sk=83f429591ca701325d990e4a214ae35a636678fe&_=1637608552500 HTTP/1.1" 200 14209 "https://5.196.26.2:14001/index.php?r=index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"
[Mon Nov 22 19:17:05.262936 2021] [php7:notice] [pid 313] [client 104.28.135.9:18315] [INFO] [Extensions checked] SP\\Core\\PhpExtensionChecker::checkMandatory, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:17:05.266420 2021] [php7:notice] [pid 313] [client 104.28.135.9:18315] [INFO] [Loaded icons cache] SP\\Core\\UI\\Theme::initIcons, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:17:05.284802 2021] [php7:notice] [pid 313] [client 104.28.135.9:18315] [INFO] [Loaded actions cache] SP\\Core\\Acl\\Actions::loadCache, referer: https://5.196.26.2:14001/index.php?r=index
104.28.135.9 - - [22/Nov/2021:19:17:05 +0000] "POST /index.php?r=configLdap/save HTTP/1.1" 200 2342 "https://5.196.26.2:14001/index.php?r=index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"
[Mon Nov 22 19:17:05.363791 2021] [php7:notice] [pid 313] [client 104.28.135.9:18315] [INFO] [Extensions checked] SP\\Core\\PhpExtensionChecker::checkMandatory, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:17:05.364885 2021] [php7:notice] [pid 313] [client 104.28.135.9:18315] [INFO] [Loaded icons cache] SP\\Core\\UI\\Theme::initIcons, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:17:05.381761 2021] [php7:notice] [pid 313] [client 104.28.135.9:18315] [INFO] [Loaded actions cache] SP\\Core\\Acl\\Actions::loadCache, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:17:05.384490 2021] [php7:notice] [pid 313] [client 104.28.135.9:18315] [INFO] [Loaded MIME types cache] SP\\Core\\MimeTypes::loadCache, referer: https://5.196.26.2:14001/index.php?r=index
104.28.135.9 - - [22/Nov/2021:19:17:05 +0000] "GET /index.php?r=configManager/index&tabIndex=3&isAjax=1&sk=2c17b27b4920ac21cda91b982ea1dd6d2c7fa845&_=1637608552501 HTTP/1.1" 200 14202 "https://5.196.26.2:14001/index.php?r=index" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"
[Mon Nov 22 19:17:08.507902 2021] [php7:notice] [pid 313] [client 104.28.135.9:18315] [INFO] [Extensions checked] SP\\Core\\PhpExtensionChecker::checkMandatory, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:17:08.509956 2021] [php7:notice] [pid 313] [client 104.28.135.9:18315] [INFO] [Loaded icons cache] SP\\Core\\UI\\Theme::initIcons, referer: https://5.196.26.2:14001/index.php?r=index
[Mon Nov 22 19:17:08.527325 2021] [php7:notice] [pid 313] [client 104.28.135.9:18315] [INFO] [Loaded actions cache] SP\\Core\\Acl\\Actions::loadCache, referer: https://5.196.26.2:14001/index.php?r=index
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/ldap/ldap.conf
ldap_init: using /etc/ldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: trying ldaprc
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
ldap_create
ldap_url_parse_ext(ldap://romainmunier.ovh:389)
ldap_extended_operation_s
ldap_extended_operation
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP romainmunier.ovh:389
ldap_new_socket: 15
ldap_prepare_socket: 15
ldap_connect_to_host: Trying 5.196.26.2:389
ldap_pvt_connect: fd: 15 tm: 10 async: 0
ldap_ndelay_on: 15
attempting to connect: 
connect errno: 115
ldap_int_poll: fd: 15 tm: 10
ldap_is_sock_ready: 15
ldap_ndelay_off: 15
ldap_pvt_connect: 0
ldap_open_defconn: successful
ldap_send_server_request
ldap_result ld 0x55d6705ecdc0 msgid 1
wait4msg ld 0x55d6705ecdc0 msgid 1 (infinite timeout)
wait4msg continue ld 0x55d6705ecdc0 msgid 1 all 1
** ld 0x55d6705ecdc0 Connections:
* host: romainmunier.ovh  port: 389  (default)
  refcnt: 2  status: Connected
  last used: Mon Nov 22 19:17:08 2021


** ld 0x55d6705ecdc0 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x55d6705ecdc0 request count 1 (abandoned 0)
** ld 0x55d6705ecdc0 Response Queue:
   Empty
  ld 0x55d6705ecdc0 response count 0
ldap_chkResponseList ld 0x55d6705ecdc0 msgid 1 all 1
ldap_chkResponseList returns ld 0x55d6705ecdc0 NULL
ldap_int_select
read1msg: ld 0x55d6705ecdc0 msgid 1 all 1
read1msg: ld 0x55d6705ecdc0 msgid 1 message type extended-result
read1msg: ld 0x55d6705ecdc0 0 new referrals
read1msg:  mark request completed, ld 0x55d6705ecdc0 msgid 1
request done: ld 0x55d6705ecdc0 msgid 1
res_errno: 2, res_error: <unsupported extended operation>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_parse_extended_result
ldap_parse_result
ldap_msgfree
ldap_err2string
ldap_err2string
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
```

I see that SysPass can connect to LDAP server but cannot authenticate user ...

Can you help me please to solve this problem ?

Thank you !
[syspass.log](https://github.com/nuxsmin/sysPass/files/7583815/syspass.log)
