### ISSUE TITLE
Upgrade from version 3.0 to 3.1.0-rc5

### ISSUE THREAD

**Issue by pedroaugustoferreira** [nuxsmin/sysPass#1403]
As I did.

I did it like this and it worked.

1) backup of version 3.0
docker exec syspass-db /usr/bin/mysqldump -u root -pYourPassword syspass > backup.v3.0.sql

2) I installed and configured version 3.1.0-rc5 with the same master password.
	  
3) I commented this line from my backup.v3.0.sql

# DROP TABLE IF EXISTS `Plugin`;

4) And imported the backup.v3.0.sql to the new version.

docker exec -i syspass-db03 mysql -f -uroot -pYourPassword --database=syspass < backup.v3.0.sql

**Comment by nuxsmin** [comment]
Hello, there are many upgrade task that are not related to database structure, but to data itself instead. Doing so it would break some modules like plugin's data, custom fields or public links since the data need to be adapted through code tasks.

Regards
