### ISSUE TITLE
Integrity Check Failed

### ISSUE THREAD

**Issue by Pip3queak** [nuxsmin/sysPass#1405]
**sysPass Version**
sysPass 3.1-RC5

**Describe the question**
I had done an update of master password with the "do not modify" radio button checked. I believe this is the reason why the old accounts are showing "Integrity Check Failed" when viewing passwords or editing accounts.

I tried doing another update of the master password with "do not modify" UNCHECKED this time hoping this will resolve itself but the "Integrity Check Failed" is still appearing. How do I fix this?

**Platform (please complete the following information):**
Linux CentOS7
Using Chrome as browser Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by nuxsmin** [comment]
He

**Comment by nuxsmin** [comment]
Hello, that message states about a wrong master password. The 'do not modify accounts' option is there for changing the master password without rencrypting the accounts, so the accounts should have been encrypted before with the new master password, if not this message will be displayed.

Please restore your master password to the good one by using 'do not modify accounts' option.

Regards.

**Comment by Pip3queak** [comment]
I couldn't get this to work again. I dropped the database and reinstalled.

**Comment by nuxsmin** [comment]
@Pip3queak thanks for the feedback!
