### ISSUE TITLE
INCORRECT MIME TYPE

### ISSUE THREAD

**Issue by DannyStylesUK** [nuxsmin/sysPass#1406]
**sysPass Version**
All versions of 3.0 and above to 3.1 RC5

**Describe the bug**
Typo in MIME TYPE - lib/SP/Services/ImportService.php

You have 'application/vnd.mes-excel' as a mime type. This is a typo. No such mime type exists.
Correct mime types for excel CSV/XLSX:
For BIFF .xls files
'application/vnd.ms-excel'
For Excel2007 and above .xlsx files
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

Once you change mes-excel to ms-excel I can confirm that uploading CSV files created by excel on windows works as expected. Without this change CSV files created by excel on windows will never work with syspass.

**Comment by MagikEh** [comment]
I commented on #1109 about this issue as well a while ago. Since doing the change as reported in the other issue I have not had any issue importing ~5k accounts.

**Comment by nuxsmin** [comment]
@DannyStylesUK  you're right, it seems a typo issue on allowed mime types...

I'll fix it shortly. Thanks for the feedback!

**Comment by nuxsmin** [comment]
Solved in latest release
