### ISSUE TITLE
How to limit category view?

### ISSUE THREAD

**Issue by radoslav-stefanov** [nuxsmin/sysPass#1407]
Hello guys,

How can I limit users from viewing all available categories? I tried setting permissions, but I can't find where can category permissions be configured?

I want the user to see only his own categories.

I am on 3.1-RC5 (310.19072001) syspass version.

**Comment by nuxsmin** [comment]
Hello, unfortunately categories are a filtering behavior, which aren't restricted to users. Please use user groups instead.

Thanks for the feedback!
