### ISSUE TITLE
INSTALLATION PROBLEMS

### ISSUE THREAD

**Issue by Fuquan999** [nuxsmin/sysPass#1408]
**3.1.0.19072001-rc5**
Can be found on `Config -> Information` tab

**Describe the bug**
During installation it repeatedly fails at the steps of the "Composer" parts: No matter what you try whether using the online Docs or any other search related installation guides it fails at the same point. 

When you use the UNix based bash script it gives you a "Memory Error" (which is inaccurate as both my php files (Apache2 php and FPM php) are allocated 4GB ram sp that error is inaccurate) when you follow the guide it then gives you an "Installer Corrupt" warning....basically it is a loose - loose scenario. 

Any installation process should not be this complex and judging from the number of bug reports relating to this one would have hoped the challenge was by now resolved or atleast described clearly what to do to overcome this problem as I see entries as far back as 2016 on this issue.

Is there no other way to install this application as after all the web based installation should be possible once you have unzipped the files into the correct directory similar to how Wordpress or Joomla or even suite CRM etc all install once the files are unzipped in the directory.

If anyone know (a workable way) of how to overcome this issue it would be helpful if they could include the steps as an answer.

Thanks
Fuquan

**To Reproduce**

**Expected behavior**

**Screenshots**

**Event log**
Some lines from `syspass.log` file (within `config` directory) and sysPass event log that were logged when the error happened.

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android]
 - OS Version
 - Browser [e.g. Firefox, Chrome]

**Additional context**

**Comment by bitking** [comment]
I also had troubles installing composer at first but noticed it was my own inability to understand the process.
1. wget composer https://getcomposer.org/composer.phar into the root directory of syspass3.
2. Give it the right permissions so the normal user you loginto can run it -> sudo chown www-data:youruser (Dont run it using sudo)
3. Then run it with normal user -> php composer.phar install --no-dev
4. it should complete everything succesfully and you are done with this part.

Obviously you need to follow all other isntructions mentioned on https://syspass-doc.readthedocs.io/en/3.0/installing/debian9.html

**Comment by nuxsmin** [comment]
@Fuquan999 please let us know which error are you facing with composer...
@bitking thanks for your contribution!
