### ISSUE TITLE
Security & Audit log shows no new entry's after upgrade from 2.1 to 3.0

### ISSUE THREAD

**Issue by bitking** [nuxsmin/sysPass#1409]
sysPass Version: 3.0 (305.19020701) 

After upgrading from syspass 2.1 to 3.0 when i go to security & audit i see no **new** log entry's from people who logged in or view passwords.

I do see logging from config changes i make like below:
28222	2019-07-29 16:05:32	INFO	save.config.mail	admin	10.x.x.x	Mail disabled
	28221	2019-07-29 16:05:14	INFO	save.config.mail	admin	10.x.x.x	
	28220	2019-07-29 15:54:38	INFO	save.config.general	211122	10.x.x.x	

What is the issue or how can i enable audit logging again?

**Comment by bitking** [comment]
When i look in the config.xml i see the following entry's related to the log.

<logEnabled>1</logEnabled>
<logEvents/>

What does "<logEvents/>" do?

**Comment by bitking** [comment]
@nuxsmin still alive?

**Comment by nuxsmin** [comment]
@bitking sure :blush:

This is the correct behaviour, since you need to set which events should be logged on events configuration.

Regards

**Comment by bitking** [comment]
Oh.. now i see ... :)

Sorry for my redundant question.

**Comment by nuxsmin** [comment]
No worries :wink:

Thanks for the feedback
