### ISSUE TITLE
[1.2-RC5] Can't install

### ISSUE THREAD

**Issue by ffflorian** [nuxsmin/sysPass#141]
After following the [Installation steps](http://wiki.syspass.org/en/install), the register page is accessible. But when I enter my user and database data on the page and click **Install**, I only get an empty white page and PHP drops the following error in the log:
```
PHP Fatal error:  Call to a member function fetchColumn() on boolean in /var/www/html/syspass/inc/Installer.class.php on line 258
```
Ubuntu 14.04.3 LTS
Apache 2.4.16
PHP 5.6.14-1
MySQL 5.5.44

//edit: Just tried it with the files in the newest commit (```eea8c1885e```) and I get the same error.

**Comment by nuxsmin** [comment]
It seems that there's a database connection issue. Are you doing it on a hosting server?

**Comment by ffflorian** [comment]
No, not hosting server. The database is working with other projects and I also checked the password :wink:

**Comment by nuxsmin** [comment]
Ok, let me do some tests on that environment, because it has been tested on Debian 7/8, Centos 6/7 and Gentoo, without any issue.

**Comment by nuxsmin** [comment]
Hi, after installing and updating Ubuntu 14 LTS and added the required PPA to get the PHP 5.6 version (not by installed default in that ubuntu release...), the installation process finished without any issue:

![syspass_ubuntu14](https://cloud.githubusercontent.com/assets/1775774/10416737/b2171ba6-7022-11e5-9f19-c21b9008df96.png)

I don't know what can be wrong/different on your environment, but I need more info about the mysql API/driver installed on it.

**Comment by ffflorian** [comment]
@nuxsmin 
> but I need more info about the mysql API/driver installed on it.

What exactly do you need?

**Comment by nuxsmin** [comment]
If you are using the php5-mysqlnd package and its version

BTW, can you run this query? (the sysPass DB user can be found in 'config/config.php' file at the sysPass install dir):

``SELECT COUNT(*) FROM mysql.user WHERE user='SYSPASS_DB_USER' AND host='DB_HOST'``

**Comment by ffflorian** [comment]
I am not using ```php5-mysqlnd``` and I can run the query:
```
mysql> SELECT COUNT(*) FROM mysql.user WHERE user='syspass' AND host='localhost';
+----------+
| COUNT(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)
```

**Comment by ffflorian** [comment]
But from what I see, the sysPass DB user is not set in the config... I created a sysPass user in advance and then entered the details in the sysPass install page. But I don't see this username in the ```config/config.php```.

**Comment by nuxsmin** [comment]
Ummm, the sysPass connection user is the first one you provided on the install form (but it will be preffixed with 'sp_').

The DB user it's only used to create the DB structure and never more is used nor is saved. So that user need to have enough privileges to run the last query and some others like creating tables and the sysPass user.

**Comment by nuxsmin** [comment]
http://wiki.syspass.org/en/hostingmode

**Comment by ffflorian** [comment]
> So that user need to have enough privileges to run the last query and some others like creating tables and the sysPass user.
Ohh now I get it. :open_mouth: 

Yes, the installation was successfull when I entered the details for a root account on the installation page.
Maybe you could add an error if the user tries to install with a MySQL user which has not enough permissions.

Thank you very much!

**Comment by nuxsmin** [comment]
Great!!, you are right, it needs some error reporting when that operation fails.

You're welcome ;)
