### ISSUE TITLE
Sharing Accounts

### ISSUE THREAD

**Issue by wbebw** [nuxsmin/sysPass#1412]
Hi, amazing work!

I have a question - lets assume, one user1 who belongs to group1, wants to share his private account with other user2 who belongs to group1 too. Is it possible? I assume that user1 sets permissions private.

Similar question - if user1(group1) wants to share account with user44(gr4), but account is visible for all group1. Is it possible?

I thought that these things are setted by permissions tab, where i can choose users and group for reading and editing (at the bottom i actually can set private\private for group), but these read-write settings are not working or i misunderstanding.

Thanks!

INFO: version 3.0 (300.18122601), latest available build on docker xubuntu 18.04

**Comment by nuxsmin** [comment]
Hi, thanks for your support!

Private user accounts are only visible by the user, so there is no way to share it using groups. You can use private user group instead and then make all those users members of that group by setting it as primary group.

Regards.
