### ISSUE TITLE
Preset values

### ISSUE THREAD

**Issue by wbebw** [nuxsmin/sysPass#1413]
Hi, just noticed that making new values in Preset Values (Permission Preset) has a bag - there are three fields (+priority), but Profile fields suggest to choose from groups, also as Group field:
![изображение](https://user-images.githubusercontent.com/53523506/62218236-b72a5200-b3b4-11e9-8d9d-41bbf0f89900.png)
![изображение](https://user-images.githubusercontent.com/53523506/62218264-c5786e00-b3b4-11e9-93c9-43f619a39176.png)

INFO: version 3.0 (300.18122601), latest available build on docker xubuntu 18.04

**Comment by nuxsmin** [comment]
Hello, this issue was solved in latest releases. Please upgrade sysPass to latest build on https://hub.docker.com/r/syspass/syspass

Regards
