### ISSUE TITLE
Multiple Categories per password account

### ISSUE THREAD

**Issue by catrone3** [nuxsmin/sysPass#1416]
How does one assign multiple categories to a single password account? when I create a password entry I only see one place for categories, am I missing some setting that I am not seeing? or did this get removed in 3.0 after it showed up in 2.0-beta?

I saw this post, but it seems the only feature I see is for multiple tags.
https://github.com/nuxsmin/sysPass/issues/187

**Comment by nuxsmin** [comment]
Please see #1414
