### ISSUE TITLE
 Installation problem xampp,wampp

### ISSUE THREAD

**Issue by Hixr0k** [nuxsmin/sysPass#1418]
Hello
**sysPass Version**
sysPass 3.1
**Describe the question**
When you try to start the installation, a message appears. What can i do wrong? 

**Screenshots**
![image](https://user-images.githubusercontent.com/53901205/62698327-4e675900-b9f6-11e9-919c-78709084398c.png)

**Platform (please complete the following information):**
 - OS: Windows
 - OS 10
 - Browser Chrome

Can you help me?

**Comment by nuxsmin** [comment]
Hello, though sysPass on Windows is not  supported because locales issues, this error is most likely because you didn't install dependencies using composer.

Regards
