### ISSUE TITLE
Error: Actualizacion 1.1.2.24 a 1.2.0.05-rc5

### ISSUE THREAD

**Issue by ferrergl** [nuxsmin/sysPass#142]
El proceso de actualización ha sido correcto a excepción de las contraseñas que aparecían todas como NULL.
He comprobado directamente en la BBDD y hay passwords pero en una codificación extraña.

Si necesita más datos o ayuda para localizar el problema hazlo saber y estaré encantado de echar una mano.

![captura3](https://cloud.githubusercontent.com/assets/15053934/10400950/42634a1c-6ebc-11e5-91be-4b94299d2a47.PNG)
![captura](https://cloud.githubusercontent.com/assets/15053934/10400921/05281ec0-6ebc-11e5-9e39-9ed6ce4f95f8.PNG)

**Comment by nuxsmin** [comment]
Ya lo vi en sbd :)

Yo he probado varias actualizaciones sin error alguno, pero de todas formas voy a revisarlo de nuevo. Si es posible facilítame más datos sobre el entorno.

Un saludo.

**Comment by nuxsmin** [comment]
Es se nulo es problema de javascript, el json no es parseado.

Trata de refrescar la página

**Comment by ferrergl** [comment]
He refrescado la pagina, incluso he provado con los 3 navegadores, y el problema persiste.
Aqui la informacion del systema que muestra el propio sysPass. Si necesitas mas informacion te habilito un phpinfo en un momento (por privado)

Versión sysPass	1.2.0.05
Base de Datos	SERVER_VERSION : 5.5.44-0+deb7u1 
CLIENT_VERSION : 5.5.44 
SERVER_INFO : Uptime: 1501087 Threads: 1 Questions: 314896 Slow queries: 0 Opens: 1858 Flush tables: 1 Open tables: 375 Queries per second avg: 0.209 
CONNECTION_STATUS : Localhost via UNIX socket 
Nombre: syspass@localhost
PHP	Versión: 5.4.44-0+deb7u1 
Extensiones: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, json, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, curl, gd, imap, ldap, mcrypt, mysql, mysqli, pdo_mysql, mhash, xdebug 
Memoria Usada: 2048 KB 
Usuario: www-data
Servidor	Apache/2.2.22 (Debian)


mysql> SHOW VARIABLES LIKE '%character%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)

**Comment by nuxsmin** [comment]
No creo que sea de bd. Esa misma configuración es la que utilizo para el desarrollo.

Si tienes firebug, seria interesante ve la respuesta json a la petición de ver clave, es posible?

**Comment by ferrergl** [comment]
No hay problema, pero tendra que ser mañana. en cuanto lo tenga te lo mando.

**Comment by ferrergl** [comment]
No me he podido resistir, Apuntar que si actualizas el password manualmente se visualiza correctamente. El error es con los que no se han vuelto a introducir.

POST https://syspass.fmvhard.cat/ajax/ajax_viewpass.php 200 OK 552ms	 js.php?...fa62642 (línea 5)
Encabezados Post Respuesta JSON Cookies

{"title":"Clave de Cuenta","acclogin":"lferrer@fmvhard.es","accpass":null,"useimage":0,"status":0,"action"
:""}
	
![encabezado](https://cloud.githubusercontent.com/assets/15053934/10402704/39ad6afa-6ec7-11e5-86d3-e5afdfa0f39b.PNG)
![post](https://cloud.githubusercontent.com/assets/15053934/10402709/4326cd2e-6ec7-11e5-944c-8f4f4d646787.PNG)
![captura](https://cloud.githubusercontent.com/assets/15053934/10402578/8399bc5a-6ec6-11e5-97bc-e6e0a655d26f.PNG)
![json](https://cloud.githubusercontent.com/assets/15053934/10402715/4c361ff0-6ec7-11e5-894f-727e57489e5f.PNG)

**Comment by nuxsmin** [comment]
Es bastante extraño por lo que te comenté antes (ya he hecho varias actualizaciones sin problema), por lo que voy a revisar si hay algo de código que estuviera mal.

Gracias por las pruebas!

**Comment by nuxsmin** [comment]
Hola, tras varias pruebas ya he detectado el error: el hash de la clave maestra no ha sido generado correctamente ya que ha sido establecido como si la clave maestra estuviera en blanco.

**Esto no influye en las cuentas, sólo en la comprobación de la clave maestra al realizar el login**

Es necesario acceder la la BD y dejar en blanco el valor del campo "config_value" del registro "masterPwd" de la tabla "config":

``UPDATE config SET config_value = '' WHERE config_parameter = 'masterPwd';``

He subido una actualización (no es una release) a https://github.com/nuxsmin/sysPass, por lo que en el siguiente inicio de sesión solicitará la clave maestra (verificar que es la correcta) y corregirá el hash de la misma. Tras ello, ya sería posible visualizar las claves de las cuentas.

**Comment by ferrergl** [comment]
Muchas gracias por la respuesta. Ha funcionado correctamente.

**Comment by nuxsmin** [comment]
Perfecto, me alegro que funcionara bien.

Gracias por las pruebas y el feedback sobre estas versiones aún no estables, ya que sin ellas ningún software sería totalmente útil.

Saludos!
