### ISSUE TITLE
Unable to login suddently

### ISSUE THREAD

**Issue by Dezza02** [nuxsmin/sysPass#1420]
Version: 3.0.5.19020701

I have upgrade this from v2.1 to 3.0.5 for a month without any issues, but today I'm unable to login. 
I can enter my username and password fine but it will load a blank page in the google 2FA today and I'm unable to go any further. 

Removed cache/history from any FireFox/Chrome but same result. Tried on different machine same result.

Log shows:
2019-08-10 16:08:14 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2019-08-10 16:08:14 [EXCEPTION] [N/A] Context not initialized
#0 /var/www/html/syspass-3/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/syspass-3/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey('locale', NULL)
#2 /var/www/html/syspass-3/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey('locale')
#3 /var/www/html/syspass-3/lib/SP/Core/Language.php(209): SP\Core\Context\SessionContext->getLocale()
#4 /var/www/html/syspass-3/lib/SP/Providers/Log/FileLogHandler.php(104): SP\Core\Language->setAppLocales()
#5 /var/www/html/syspass-3/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\FileLogHandler->updateEvent('upgrade.config....', Object(SP\Core\Events\Event))
#6 /var/www/html/syspass-3/lib/SP/Services/Upgrade/UpgradeConfigService.php(222): SP\Core\Events\EventDispatcherBase->notifyEvent('upgrade.config....', Object(SP\Core\Events\Event))
#7 /var/www/html/syspass-3/lib/SP/Bootstrap.php(420): SP\Services\Upgrade\UpgradeConfigService->upgrade('300.18111001', Object(SP\Config\ConfigData))
#8 /var/www/html/syspass-3/lib/SP/Bootstrap.php(394): SP\Bootstrap->checkConfigVersion()
#9 /var/www/html/syspass-3/lib/SP/Bootstrap.php(297): SP\Bootstrap->initConfig()
#10 /var/www/html/syspass-3/lib/SP/Bootstrap.php(224): SP\Bootstrap->initializeCommon()
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/syspass-3/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#13 /var/www/html/syspass-3/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#14 /var/www/html/syspass-3/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#15 /var/www/html/syspass-3/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#16 /var/www/html/syspass-3/index.php(28): require('/var/www/html/p...')
#17 {main}
2019-08-10 16:08:14 [EXCEPTION] [N/A] Context not initialized
#0 /var/www/html/syspass-3/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/syspass-3/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey('locale', NULL)
#2 /var/www/html/syspass-3/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey('locale')
#3 /var/www/html/syspass-3/lib/SP/Core/Language.php(222): SP\Core\Context\SessionContext->getLocale()
#4 /var/www/html/syspass-3/lib/SP/Providers/Log/FileLogHandler.php(112): SP\Core\Language->unsetAppLocales()
#5 /var/www/html/syspass-3/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\FileLogHandler->updateEvent('upgrade.config....', Object(SP\Core\Events\Event))
#6 /var/www/html/syspass-3/lib/SP/Services/Upgrade/UpgradeConfigService.php(222): SP\Core\Events\EventDispatcherBase->notifyEvent('upgrade.config....', Object(SP\Core\Events\Event))
#7 /var/www/html/syspass-3/lib/SP/Bootstrap.php(420): SP\Services\Upgrade\UpgradeConfigService->upgrade('300.18111001', Object(SP\Config\ConfigData))
#8 /var/www/html/syspass-3/lib/SP/Bootstrap.php(394): SP\Bootstrap->checkConfigVersion()
#9 /var/www/html/syspass-3/lib/SP/Bootstrap.php(297): SP\Bootstrap->initConfig()
#10 /var/www/html/syspass-3/lib/SP/Bootstrap.php(224): SP\Bootstrap->initializeCommon()
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/syspass-3/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#13 /var/www/html/syspass-3/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#14 /var/www/html/syspass-3/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#15 /var/www/html/syspass-3/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#16 /var/www/html/syspass-3/index.php(28): require('/var/www/html/p...')
#17 {main}
2019-08-10 16:08:14 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2019-08-10 16:08:15 [INFO] [SP\Core\UI\Theme::saveIcons] Saved icons cache
2019-08-10 16:08:15 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache

Now I'm unable to get my password I was wondering if anyone can help me with this.

**Comment by nuxsmin** [comment]
Hello, these errors are not related to any issue, because neither context initialization nor locales are quite critical.

Did you get a blank page when 2FA should be displayed?. Please take a look to web server logs and let me know if there are any error messages.

This is the first time I've heard about this kind of issue.

Regards.

**Comment by Dezza02** [comment]
[error.log](https://github.com/nuxsmin/sysPass/files/3488665/error.log)
[access.log](https://github.com/nuxsmin/sysPass/files/3488668/access.log)

If I reboot the server, the 2FA will load and if I put in the 2FA code it will say success but then it will go back to login page.

2nd time I try to login it will just load blank page stuck at
https://secretserver.dev.int/syspass-3/index.php?r=authenticatorLogin%2Findex

**Comment by Dezza02** [comment]
Is it possible to enable and account via the SQL? As I know the password for all of it.
I disabled an account that doesn't require 2FA

**Comment by Dezza02** [comment]
Actually I just tried with the account without 2FA. I will login and briefly load the page with the banner with empty body then bounce me back to login page with no error message.

**Comment by nuxsmin** [comment]
Hmm, really weird. Please take a look to browser console (F12) and let me know if in network tab is there any error.

Regards

**Comment by Dezza02** [comment]
![image](https://user-images.githubusercontent.com/35958484/62821553-cdef5680-bbb5-11e9-9d09-277b68807c6b.png)

This is what I get.

Is there another way to restore this? I have back up of the SQL only and I've the master key. I wonder if I can restore it some how?

**Comment by nuxsmin** [comment]
Do you get a blank page when this request is logged?. This request is related to the page which will display the 2FA form to enter the code. Was it displayed?

**Comment by Dezza02** [comment]
It's blank page. 
Unless I delete the cache and restart apache then I will be able to load the 2FA page and when I put in the correct 2FA code it will then temporarily get into main page with just the top banner and it looks like trying to load and it automatically kick me back to login page.

Once this happened it will never load the 2FA page unless I perform the steps above.

**Comment by nuxsmin** [comment]
Could you disable the plugin in the database?. Please set  `enabled` to 0 within `Plugin` table.

**Comment by Dezza02** [comment]
I get undefined error when I log in. But when I look at the log in sysPass.log it's the usual


2019-08-10 21:53:00 [EXCEPTION] [N/A] Context not initialized
#0 /var/www/html/syspass-3/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/syspass-3/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey('locale', NULL)
#2 /var/www/html/syspass-3/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey('locale')
#3 /var/www/html/syspass-3/lib/SP/Core/Language.php(222): SP\Core\Context\SessionContext->getLocale()
#4 /var/www/html/syspass-3/lib/SP/Providers/Log/FileLogHandler.php(112): SP\Core\Language->unsetAppLocales()
#5 /var/www/html/syspass-3/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\FileLogHandler->updateEvent('upgrade.config....', Object(SP\Core\Events\Event))
#6 /var/www/html/syspass-3/lib/SP/Services/Upgrade/UpgradeConfigService.php(214): SP\Core\Events\EventDispatcherBase->notifyEvent('upgrade.config....', Object(SP\Core\Events\Event))
#7 /var/www/html/syspass-3/lib/SP/Bootstrap.php(420): SP\Services\Upgrade\UpgradeConfigService->upgrade('300.18111001', Object(SP\Config\ConfigData))
#8 /var/www/html/syspass-3/lib/SP/Bootstrap.php(394): SP\Bootstrap->checkConfigVersion()
#9 /var/www/html/syspass-3/lib/SP/Bootstrap.php(297): SP\Bootstrap->initConfig()
#10 /var/www/html/syspass-3/lib/SP/Bootstrap.php(224): SP\Bootstrap->initializeCommon()
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/syspass-3/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#13 /var/www/html/syspass-3/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#14 /var/www/html/syspass-3/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#15 /var/www/html/syspass-3/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#16 /var/www/html/syspass-3/index.php(28): require('/var/www/html/p...')
#17 {main}
2019-08-10 21:53:00 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2019-08-10 21:53:00 [EXCEPTION] [N/A] Context not initialized
#0 /var/www/html/syspass-3/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/syspass-3/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey('locale', NULL)
#2 /var/www/html/syspass-3/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey('locale')
#3 /var/www/html/syspass-3/lib/SP/Core/Language.php(209): SP\Core\Context\SessionContext->getLocale()
#4 /var/www/html/syspass-3/lib/SP/Providers/Log/FileLogHandler.php(104): SP\Core\Language->setAppLocales()
#5 /var/www/html/syspass-3/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\FileLogHandler->updateEvent('upgrade.config....', Object(SP\Core\Events\Event))
#6 /var/www/html/syspass-3/lib/SP/Services/Upgrade/UpgradeConfigService.php(222): SP\Core\Events\EventDispatcherBase->notifyEvent('upgrade.config....', Object(SP\Core\Events\Event))
#7 /var/www/html/syspass-3/lib/SP/Bootstrap.php(420): SP\Services\Upgrade\UpgradeConfigService->upgrade('300.18111001', Object(SP\Config\ConfigData))
#8 /var/www/html/syspass-3/lib/SP/Bootstrap.php(394): SP\Bootstrap->checkConfigVersion()
#9 /var/www/html/syspass-3/lib/SP/Bootstrap.php(297): SP\Bootstrap->initConfig()
#10 /var/www/html/syspass-3/lib/SP/Bootstrap.php(224): SP\Bootstrap->initializeCommon()
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/syspass-3/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#13 /var/www/html/syspass-3/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#14 /var/www/html/syspass-3/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#15 /var/www/html/syspass-3/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#16 /var/www/html/syspass-3/index.php(28): require('/var/www/html/p...')
#17 {main}
2019-08-10 21:53:00 [EXCEPTION] [N/A] Context not initialized
#0 /var/www/html/syspass-3/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/syspass-3/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey('locale', NULL)
#2 /var/www/html/syspass-3/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey('locale')
#3 /var/www/html/syspass-3/lib/SP/Core/Language.php(222): SP\Core\Context\SessionContext->getLocale()
#4 /var/www/html/syspass-3/lib/SP/Providers/Log/FileLogHandler.php(112): SP\Core\Language->unsetAppLocales()
#5 /var/www/html/syspass-3/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\FileLogHandler->updateEvent('upgrade.config....', Object(SP\Core\Events\Event))
#6 /var/www/html/syspass-3/lib/SP/Services/Upgrade/UpgradeConfigService.php(222): SP\Core\Events\EventDispatcherBase->notifyEvent('upgrade.config....', Object(SP\Core\Events\Event))
#7 /var/www/html/syspass-3/lib/SP/Bootstrap.php(420): SP\Services\Upgrade\UpgradeConfigService->upgrade('300.18111001', Object(SP\Config\ConfigData))
#8 /var/www/html/syspass-3/lib/SP/Bootstrap.php(394): SP\Bootstrap->checkConfigVersion()
#9 /var/www/html/syspass-3/lib/SP/Bootstrap.php(297): SP\Bootstrap->initConfig()
#10 /var/www/html/syspass-3/lib/SP/Bootstrap.php(224): SP\Bootstrap->initializeCommon()
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/syspass-3/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#13 /var/www/html/syspass-3/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#14 /var/www/html/syspass-3/lib/SP/Bootstrap.php(461): Klein\Klein->dispatch(Object(Klein\Request))
#15 /var/www/html/syspass-3/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#16 /var/www/html/syspass-3/index.php(28): require('/var/www/html/p...')
#17 {main}
2019-08-10 21:53:00 [ERROR] [SP\Core\Language::setLocales] Could not set locale
2019-08-10 21:53:01 [INFO] [SP\Core\UI\Theme::initIcons] Loaded icons cache
2019-08-10 21:53:01 [INFO] [SP\Core\Acl\Actions::loadCache] Loaded actions cache

**Comment by Dezza02** [comment]
I might try to spin up a new instance and restore the DB that way and see if it works. :)

**Comment by nuxsmin** [comment]
Is there a `config` directory within the app root directory (not '/app/config') ? . It seems it tries to upgrade the config file.

**Comment by Dezza02** [comment]
Nope, config directory is inside the /app/config

**Comment by nuxsmin** [comment]
Is Selinux enabled? . Which platform are you running on?

**Comment by Dezza02** [comment]
It's Debian 9. 
I've created a new instance and restored the db. Now it's working, I just need to reconfigure few things back.

Thanks for your help. :)

**Comment by nuxsmin** [comment]
Great, thanks for the feedback!
