### ISSUE TITLE
pb update to 3.1

### ISSUE THREAD

**Issue by denisght71** [nuxsmin/sysPass#1425]
**sysPass Version**
3.1-RC5

**Describe the bug**
Hello, I updated syspass from 3.1-RC5 to 3.1 and I met several problems. I clone the repository and set permissions but when I went to the web url , I obtained a white page. In the apache log I Have seen an error about the directory vendor which doesn't exist in the new. So I copied it from the older and now I cannot login to the interface "error login" (ldap user and local admin). 

**Event log**
[2019-08-19 10:16:26] syspass.EXCEPTION: logger {"message":"Login incorrect
#0 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(160): SP\Services\Auth\LoginService->authDatabase(Object(SP\Providers\Auth\Database\DatabaseAuthData))
#1 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/html/syspass/index.php(28): require(String)","caller":"N/A"}

**Platform (please complete the following information):**
 - Linux version 4.9.0-9-amd64
 - Debian 9.9

**Comment by nuxsmin** [comment]
Hello, RC5 and v3.1 are quite identical, it only changes the version number and modified mime types, so I would think that this issue is not related to the version change.

Are there any more error messages within log file?

Regards

**Comment by denisght71** [comment]
Hello,
Ok I resolved the pb (it's my fault). I set permissions on syspass directory and copy the config files after. Now I can connect to web interface but it ask me the master password for all users (I test with admin local and a ldap user). Is it normal ? (below the logs when I log in ):

[2019-08-20 08:59:52] syspass.ERROR: logger {"message":"Could not set locale","caller":"SP\Core\Language::setLocales"}
[2019-08-20 08:59:52] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-08-20 08:59:52] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2019-08-20 08:59:52] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2019-08-20 08:59:52] syspass.EXCEPTION: logger {"message":"Mot de Passe Maître non sauvegardé ou incorrect
#0 /var/www/html/syspass/lib/SP/Services/Auth/LoginService.php(180): SP\Services\Auth\LoginService->loadMasterPass()
#1 /var/www/html/syspass/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/html/syspass/index.php(28): require(String)","caller":"N/A"}

**Comment by nuxsmin** [comment]
Hello, it shouldn't ask for the master password unless the config hash would have been changed.

Every user "holds" an encrypted master password by using a derived key from his/her data and the config hash.

Regards

**Comment by denisght71** [comment]
Thanks for you reply. Where is the config hash stored ? I made no changes, just clone the new repository and copy config files into it.

**Comment by nuxsmin** [comment]
Within config.xml file

**Comment by denisght71** [comment]
I verified, the config hash are the same in the old and the new config.xml.

**Comment by nuxsmin** [comment]
Hello, here you have the commits from RC5 to final release and none of them are related to any data around the master key: https://github.com/nuxsmin/sysPass/compare/3.1.0.19072001-rc5...master

I've just upgraded the demo site and it does not require the master key on login.

**Comment by denisght71** [comment]
Hello, thanks for your time. I re-update after restore syspass directory and database, and now it works fine. Maybe a problem when downloading.
