### ISSUE TITLE
Question about using Letsencrypt Certificate

### ISSUE THREAD

**Issue by Envikia** [nuxsmin/sysPass#1426]
Hi,

I have the certificates generated, which are the files and what is the path that I should put and bind-mount to syspass? 
```
-rw-r--r--. 1 root root 2263 Jul 25 10:55 cert.pem
-rw-r--r--. 1 root root 1646 May 26 11:46 chain.pem
-rw-r--r--. 1 root root 3910 Jul 25 10:55 fullchain.pem
-rw-r--r--. 1 root root 3271 Jul 25 10:55 key.pem
```

Anyone could guide me? Thanks a lot!!

**Comment by nuxsmin** [comment]
Hi,

`fullchain.pem` and `key.pem` are the only needed and could be pointed to any location within the container, so you only need to modify `syspass.conf` file in order to point to the certificates.

Regards.
