### ISSUE TITLE
Migrating to new install

### ISSUE THREAD

**Issue by alexseys** [nuxsmin/sysPass#1428]
**sysPass Version**
moving from 3.05 to 3.1 (310.19081801) 

**Describe the question**
Did xml export import of accounts, works fine.
Question is need to move AD users defined in the old install with all settings
How this can be achieved - moving table???

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android]
 - OS Version
 - Browser [e.g. Firefox, Chrome]

**Additional context**

**Comment by nuxsmin** [comment]
Hmmm, why you didn't perform an upgrade?. XML export is for only account related items but it won't import any settings or ACLs. This way is about 
 exchanging data between applications but not for restoring.

Regards

**Comment by alexseys** [comment]
upgrade did not work, due to issue reported in June   #1355 :
"Have same problem, created docker container for 3.1.0-rc4, while install and connecting to existing 3.0.5 database :
[2019-06-10 19:14:02] syspass.EXCEPTION: logger {"message":"(P) SQLSTATE[42S22]: Column not found: 1054 Unknown column 'versionLevel' in 'field list'"

So just trying to get this working without agitating end users, not that many but still, would be nice to get accounts/settings transfered.

I will try setting up with newer version.

Thank you.
Wish I could help with development but just a sysadmin.

**Comment by nuxsmin** [comment]
@alexseys no worries about development...

Do you have authenticator plugin installed?. If so, please try to upgrade after disabling it (not removing....)

Regards

**Comment by nuxsmin** [comment]
Looking at recent releases, I noticed that your upgrade issue was solved in RC5

**Comment by alexseys** [comment]
Thank you sir.

**Comment by nuxsmin** [comment]
:wink:
