### ISSUE TITLE
Delete footer from login page

### ISSUE THREAD

**Issue by Blai01** [nuxsmin/sysPass#1431]
Hi,

sysPass 2.1 did not have any footer bar on the login page, but sysPass 3.1 has a footer bar showing the sysPass version.

Is there a possibility to delete this footer bar on the login page or at least hide the version?

Thanks

**Comment by nuxsmin** [comment]
Hi, this can be achieved by cloning the default app theme and removing this field from the footer. Be aware that you need to rename the new cloned theme in order to use it. Any changes made in default theme (from new releases) would need to be replicated in the cloned one.

Regards
