### ISSUE TITLE
API edit question

### ISSUE THREAD

**Issue by alexseys** [nuxsmin/sysPass#1434]
**

3.1 (310.19081801) Config: 310.19081801  App: 310.19081801  DB: 310.19081801
--
Database | SERVER_VERSION : 5.5.5-10.2.26-MariaDB-1:10.2.26+maria~bionic  CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $  SERVER_INFO : Uptime: 328763 Threads: 7 Questions: 13126 Slow queries: 0 Opens: 48 Flush tables: 1 Open tables: 42 Queries per second avg: 0.039  CONNECTION_STATUS : syspass-db via TCP/IP

**

**Describe the question**
Edit account info via API

**Screenshots**

**Platform (please complete the following information):**
 - OS: Linux
 - OS Cento 7
 - Browser Chrome

**Additional context**
Adding account works just fine:

curl -k -X POST -d @add_acct.json https://syspassserver/api.php
add_acct.json:
{"jsonrpc": "2.0",
  "method":"account/create",
  "id" : "1",
  "params": {
    "authToken": "token",
    "name": "ZZ-TOP1",
    "categoryId": 1,
    "clientId": 1,
    "pass": "somecrasyA$$PA$$",
    "tokenPass": "password",
    "login": "username",
    "url": "http://test/test"
    }
}
Account is created and i can get it via API:

curl -k -X POST -d '{   "jsonrpc": "2.0",   "method": "account/search",   "params": {     "authToken": "token",     "text": "ZZ-TOP1"   },   "id": 1 }' -o - https://syspassserver/api.php | json_pp
{
   "result" : {
      "resultCode" : 0,
      "count" : 1,
      "resultMessage" : null,
      "itemId" : 0,
      "result" : [
         {
            "countView" : 0,
            "categoryId" : 1,
            "notes" : "",
            "userEditName" : "",
            "isPrivateGroup" : 0,
            "passDate" : 1566572519,
            "isPrivate" : 0,
            "login" : "username",
            "dateEdit" : null,
            "otherUserEdit" : 0,
            "publicLinkHash" : null,
            "categoryName" : "Ansible",
            "clientName" : "Client1",
            "userEditLogin" : "",
            "userId" : 1,
            "num_files" : 0,
            "userLogin" : "admin",
            "userGroupName" : "Admins",
            "id" : 448,
            "publicLinkTotalCountViews" : null,
            "publicLinkDateExpire" : null,
            "name" : "ZZ-TOP1",
            "userName" : "sysPass Admin",
            "clientId" : 1,
            "passDateChange" : 0,
            "userGroupId" : 1,
            "userEditId" : 0,
            "parentId" : 0,
            "url" : "http://test/test",
            "otherUserGroupEdit" : 0
         }
      ]
   },
   "jsonrpc" : "2.0",
   "id" : 1
}

How would I build file to edit this account?

I tried editing notes field and pushing, see below, back to server but always get:
{"jsonrpc":"2.0","error":{"message":"Internal error","code":0,"data":null},"id":448}

{"jsonrpc": "2.0",
  "method":"account/edit",
  "id" : "1",
  "params": {
    "authToken": "token",
    "tokenPass": "password",
    "categoryName" : "Ansible",
    "parentId" : 0,
    "isPrivateGroup" : 0,
    "isPrivate" : 0,
    "userEditLogin" : "",
    "dateEdit" : null,
    "url" : "http://test/test",
    "id" : 448,
    "otherUserGroupEdit" : 0,
    "passDateChange" : 0,
    "notes" : "this is test note",
    "publicLinkHash" : null,
    "otherUserEdit" : 0,
    "publicLinkTotalCountViews" : null,
    "userId" : 1,
    "userGroupName" : "Admins",
    "categoryId" : 1,
    "clientId" : 1,
    "userName" : "sysPass Admin",
    "userLogin" : "admin",
    "login" : "username",
    "userGroupId" : 1,
    "countView" : 0,
    "num_files" : 0,
    "publicLinkDateExpire" : null,
    "userEditId" : 0,
    "userEditName" : "",
    "name" : "ZZ-TOP1",
    "passDate" : 1566572519,
    "clientName" : "Client1"
    }
}

tail of log file:
[2019-08-23 15:20:14] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-08-23 15:20:14] syspass.EXCEPTION: logger {"message":"Internal error
#0 /var/www/html/sysPass/lib/SP/Services/Api/ApiService.php(106): SP\Services\AuthToken\AuthTokenService->getTokenByToken(Integer,String)
#1 /var/www/html/sysPass/app/modules/api/Controllers/ControllerBase.php(134): SP\Services\Api\ApiService->setup(Integer)
#2 /var/www/html/sysPass/app/modules/api/Controllers/AccountController.php(212): SP\Modules\Api\Controllers\ControllerBase->setupApi(Integer)
#3 [internal function]: SP\Modules\Api\Controllers\AccountController->editAction()
#4 /var/www/html/sysPass/lib/SP/Bootstrap.php(181): call_user_func(Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#8 /var/www/html/sysPass/lib/SP/Bootstrap.php(470): Klein\Klein->dispatch(Object(Klein\Request))
#9 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#10 /var/www/html/sysPass/api.php(28): require(String)","caller":"N/A"}

**Comment by nuxsmin** [comment]
Hello, it seems to fail just when getting the token. Did you set the correct API token? Did you grant permission to edit accounts?

Regards

**Comment by alexseys** [comment]
No I did not, works now.

Thank you

**Comment by nuxsmin** [comment]
Thanks for the feedback! :wink:
