### ISSUE TITLE
API call error:  Oops, it looks like this content does not exist..

### ISSUE THREAD

**Issue by krnull** [nuxsmin/sysPass#1436]
**sysPass Version**
I'm running sysPass 3.1 

While interacting with API I had issues using the 
"usergroup/search" method.

I'm getting 
{u'jsonrpc': u'2.0', u'id': 1, u'error': {u'message': u'Oops, it looks like this content does not exist...', u'code': -32601, u'data': None}}

I've followed the API documentation and **all other methods work** except for "usergroup/search"

**Comment by nuxsmin** [comment]
Hello, please see: https://doc.syspass.org/en/3.1/application/api.html#user-groups

There was a typo in the documentation: https://github.com/sysPass/sysPass-doc/issues/6

Regards

**Comment by nuxsmin** [comment]
Solved
