### ISSUE TITLE
Who viewed the password [Security event log]

### ISSUE THREAD

**Issue by krnull** [nuxsmin/sysPass#1438]
It would be great if you add a log of who viewed the account password in the (Event Log)
Example:

USER: x , IP: a.a.a.a, timestamp, Viewed account (NAME)

**Comment by nuxsmin** [comment]
Hello, it's implemented indeed. Please check out the event log options under configuration section.

Regards

**Comment by krnull** [comment]
> 
> 
> Hello, it's implemented indeed. Please check out the event log options under configuration section.
> 
> Regards

Perfect!, my bad I didn't pay attention to the events field
