### ISSUE TITLE
Syslog Integration

### ISSUE THREAD

**Issue by gleisonbaioco** [nuxsmin/sysPass#144]
Hi Nuxsmin,

Do you plan to send sysPass event log to Syslog servers? This is a very important feature in order to integrate with SIEM products.

**Comment by nuxsmin** [comment]
Hi @gleisonbaioco, 

It seems that it can be easily implemented.

A nice feature ;)

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin 

Do you have idea when you could implement it?

**Comment by nuxsmin** [comment]
Hi, I'm currently working on it, because I was doing a task that will improve the actions and errors logging.

It will be finished in short and will be pushed to the dev branch.

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin,

Good news! Please let me know as soon as you push the dev branch and I will try it immediately.

**Comment by nuxsmin** [comment]
Hi @gleisonbaioco,

I've pushed an initial release which includes that functionality but need some review.

Please, take care that there are many changes on that branch, so you should install as another instance (path and database).

The facility is LOCAL0 and the message is logged on CEF format. Actually it sends all messages to the local syslog and you can collect them by the SIEM, but in the next release it will be able to send to a remote syslog (514/UDP),

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin,

I tried the dev branch and I got the following errors:

Warning: require(SP/AccountSearch.class.php): failed to open stream: No such file or directory in /var/www/html/sysPass-devel/inc/SplClassLoader.php on line 176

Fatal error: require(): Failed opening required 'SP/AccountSearch.class.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/sysPass-devel/inc/SplClassLoader.php on line 176

**Comment by nuxsmin** [comment]
Hi, because there are some changes to classes names and locations you need to delete the session cookie in your browser, so that forces to create a new one with the right values.

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin,

Now it is showing me the following information:

Application in maintenance 
It will be running in short

**Comment by nuxsmin** [comment]
Possibly it needs a DB upgrade so before the last error, it should be shown a page to enter the upgrade code. To show it again you need to edit the config file and set "maintenance" to false and reload the page, after that it will show the upgrade notice.

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin,

I have filled out the Security Code, but the page has returned to the upgrade notice requiring the Security Code again.

**Comment by nuxsmin** [comment]
Did you upgraded from a previous release or was it installed from scratch instead?

**Comment by gleisonbaioco** [comment]
At first I tried to download the dev branch and install it as a new installation but this procedure didn't work.

After that I tried to install it by upgrading from a previous release.

What is the correct procedure to execute?

Please consider that I don't need to preserve previous installations because I'm trying the product.

**Comment by nuxsmin** [comment]
You're on the right, the issue has been solved in the latest commit. An install from scratch should works now (the issue was related to a missing field on a table of the DB). The upgrade should works also.

**Comment by gleisonbaioco** [comment]
I tried the new dev branch and now it upgraded from a previous release (from a scratch release it didn't work). However, I'm not able to login by using previous admin user (no error is displayed).

By comparing folders such as "inc" between dev and master branches it is possible to observe the absence of many files in the dev release.

**Comment by nuxsmin** [comment]
Yes, I'm trying to find out what can be wrong...

All my developments and tests have been done on a running instance.

**Comment by nuxsmin** [comment]
Hi, it has been fixed now.

The app structure has changed to be compliant to PSR-4 (a PHP standard to organize OOP classes)

**Comment by nuxsmin** [comment]
I've finished the remote syslog implementation.

**Comment by gleisonbaioco** [comment]
Great news! I tried it and it is working very fine! Congratulations and thank you for your attention!

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin 

When do you plan to implement the Syslog feature in the master branch?

**Comment by nuxsmin** [comment]
Hi @gleisonbaioco 

Because the amount of changes done in the development version (code structure, new classes, new features), there is no clean "mergeability", so this needs to be put in a new release (will be 1.3) that will be closed shortly (about a month) with the proposed features and code improvements.

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta

**Comment by gleisonbaioco** [comment]
Hello RubénD,

I've accessed the sysPass 2.0 beta version and it is very interesting.

Congratulations!

Kind regards, Gleison,
