### ISSUE TITLE
after for pdo_mysql

### ISSUE THREAD

**Issue by surajtomar750** [nuxsmin/sysPass#1442]
**sysPass Version**
3.0

**Describe the question**
completing the installation, when i m hitting http://myip/syspass 
![Annotation 2019-08-28 054537](https://user-images.githubusercontent.com/13602436/63816788-1bf6af00-c957-11e9-9660-71a8bf7e6a45.png)

**Screenshots**
added

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - OS Version
 - Browser [Chrome]

**Additional context**
Try to look the screenshot

**Comment by dariusz-hub** [comment]
In php.ini uncomment:

extension=pdo_mysql
