### ISSUE TITLE
Question about external wiki

### ISSUE THREAD

**Issue by steevegldev** [nuxsmin/sysPass#145]
"Wiki search URL" works well. But I can't figure out where "Wiki page URL" is used. I found only documentation about this feature in Wiki FAQ and sysPass settings menu and those did not answer my question.

**Comment by nuxsmin** [comment]
Wiki page URL uses the filtered accounts names to point them to a wiki page that match with the whole account name. You can see it working on the sysPass demo.

By using the filters you only point those accounts names that match the expression from the beginning, e.g.: "srv-" will add a wiki link to all those accounts whose names begins with "srv-"

**Comment by steevegldev** [comment]
Ok, I would use Category for that. I gonna check if I can trick that one. Thanks
