### ISSUE TITLE
Update Syspass

### ISSUE THREAD

**Issue by computergott** [nuxsmin/sysPass#1450]
Hey there,

how I can update Syspass? (From 3.1 RC 5 => 3.1) 

Is there any manual?

Thanks!

**Comment by nuxsmin** [comment]
Hi, https://doc.syspass.org/en/3.1/updating/v3.1.html

Regards

**Comment by andrucha97** [comment]
@computergott Du kannst gerne das Skript von vmario nutzen. Ich habe zu diesem Skript ein Tool gebaut welches das Updaten vereinfacht.

Mit meinem Tool kannst du dir die Version aussuchen (Experten Modus) oder du nutzt den voll automatischen Modus welcher prüft, ob es eine neuere Version gibt oder nicht.

Du musst nur am ende den ausgegebenen Update Key aus der Konsole in sysPass eingeben und fertig.

Achja :) Das Tool macht auch ein Update von deinem sysPass also keine Angst.

https://github.com/andrucha97/syspass-install-update-backup
