### ISSUE TITLE
EXCEPTION logger

### ISSUE THREAD

**Issue by joserocha** [nuxsmin/sysPass#1451]
**sysPass Version**
3.1

**Describe the bug**
There is an exception occurring in syspass.log
syspass.EXCEPTION: logger {"message":"Unable to read/write file (/var/www/html/syspass/app/cache/colors.cache)

**To Reproduce**
Just access any page

** No visible problem with syspass. Just a log exception **

**Comment by nuxsmin** [comment]
Hello, it seems that the colors cache can't be written, this file is useful to avoid rebuilding the colors used to display the clients badge when searching. Are you using SELinux? Does this directory have the correct permissions?

Regards
