### ISSUE TITLE
database update fails when updating from 2.1.16 to 3.1

### ISSUE THREAD

**Issue by ednt** [nuxsmin/sysPass#1452]
I'm on Debian 9 latest updates installed.
Apache2 is in use.
phpmyadmin works with no problems.

I followed exactly the instructions from 
https://syspass-doc.readthedocs.io/en/3.1/updating/v3.html

There were nor error mesages during all the steps.

But when I enter the upgrade key I get

![grafik](https://user-images.githubusercontent.com/6417521/64455882-12a3da00-d0ef-11e9-92ef-726eb037c6de.png)

syspass log says:

[2019-09-06 21:25:24] syspass.ERROR: logger {"message":"Could not set locale","caller":"SP\Core\Language::setLocales"}
[2019-09-06 21:25:24] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-09-06 21:25:24] syspass.EXCEPTION: logger {"message":"Context not initialized
#0 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey(String,NULL)
#2 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey(String)
#3 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Language.php(210): SP\Core\Context\SessionContext->getLocale()
#4 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Providers/Log/LoggerBase.php(78): SP\Core\Language->setAppLocales()
#5 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\LoggerBase->updateEvent(String,Object(SP\Core\Events\Event))
#6 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeConfigService.php(216): SP\Core\Events\EventDispatcherBase->notifyEvent(String,Object(SP\Core\Events\Event))
#7 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(423): SP\Services\Upgrade\UpgradeConfigService->upgrade(String,Object(SP\Config\ConfigData))
#8 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(397): SP\Bootstrap->checkConfigVersion()
#9 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#10 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#12 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#13 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#14 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#15 /var/www/html/sysPass-3.1.0.19081801/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#16 /var/www/html/sysPass-3.1.0.19081801/index.php(28): require(String)","caller":"N/A"}
[2019-09-06 21:25:24] syspass.EXCEPTION: logger {"message":"Kontext wurde nicht initialisiert
#0 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey(String,Object(SP\Services\User\UserLoginResponse))
#2 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(232): SP\Core\Context\SessionContext->getContextKey(String,Object(SP\Services\User\UserLoginResponse))
#3 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Providers/Log/LoggerBase.php(80): SP\Core\Context\SessionContext->getUserData()
#4 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\LoggerBase->updateEvent(String,Object(SP\Core\Events\Event))
#5 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeConfigService.php(216): SP\Core\Events\EventDispatcherBase->notifyEvent(String,Object(SP\Core\Events\Event))
#6 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(423): SP\Services\Upgrade\UpgradeConfigService->upgrade(String,Object(SP\Config\ConfigData))
#7 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(397): SP\Bootstrap->checkConfigVersion()
#8 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#9 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#10 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#11 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#12 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#13 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#14 /var/www/html/sysPass-3.1.0.19081801/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#15 /var/www/html/sysPass-3.1.0.19081801/index.php(28): require(String)","caller":"N/A"}
[2019-09-06 21:25:24] syspass.DEBUG: upgrade.config.start {"message":"Konfiguration aktualisieren","user":"N/A","address":"192.168.18.132","caller":"SP\\Services\\Upgrade\\UpgradeConfigService::upgrade"} []
[2019-09-06 21:25:24] syspass.EXCEPTION: logger {"message":"Kontext wurde nicht initialisiert
#0 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey(String,NULL)
#2 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey(String)
#3 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Language.php(223): SP\Core\Context\SessionContext->getLocale()
#4 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Providers/Log/LoggerBase.php(104): SP\Core\Language->unsetAppLocales()
#5 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\LoggerBase->updateEvent(String,Object(SP\Core\Events\Event))
#6 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeConfigService.php(216): SP\Core\Events\EventDispatcherBase->notifyEvent(String,Object(SP\Core\Events\Event))
#7 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(423): SP\Services\Upgrade\UpgradeConfigService->upgrade(String,Object(SP\Config\ConfigData))
#8 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(397): SP\Bootstrap->checkConfigVersion()
#9 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#10 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#12 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#13 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#14 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#15 /var/www/html/sysPass-3.1.0.19081801/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#16 /var/www/html/sysPass-3.1.0.19081801/index.php(28): require(String)","caller":"N/A"}
[2019-09-06 21:25:24] syspass.ERROR: logger {"message":"Could not set locale","caller":"SP\Core\Language::setLocales"}
[2019-09-06 21:25:24] syspass.EXCEPTION: logger {"message":"Context not initialized
#0 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey(String,NULL)
#2 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey(String)
#3 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Language.php(210): SP\Core\Context\SessionContext->getLocale()
#4 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Providers/Log/LoggerBase.php(78): SP\Core\Language->setAppLocales()
#5 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\LoggerBase->updateEvent(String,Object(SP\Core\Events\Event))
#6 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeConfigService.php(224): SP\Core\Events\EventDispatcherBase->notifyEvent(String,Object(SP\Core\Events\Event))
#7 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(423): SP\Services\Upgrade\UpgradeConfigService->upgrade(String,Object(SP\Config\ConfigData))
#8 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(397): SP\Bootstrap->checkConfigVersion()
#9 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#10 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#12 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#13 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#14 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#15 /var/www/html/sysPass-3.1.0.19081801/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#16 /var/www/html/sysPass-3.1.0.19081801/index.php(28): require(String)","caller":"N/A"}
[2019-09-06 21:25:24] syspass.EXCEPTION: logger {"message":"Kontext wurde nicht initialisiert
#0 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey(String,Object(SP\Services\User\UserLoginResponse))
#2 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(232): SP\Core\Context\SessionContext->getContextKey(String,Object(SP\Services\User\UserLoginResponse))
#3 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Providers/Log/LoggerBase.php(80): SP\Core\Context\SessionContext->getUserData()
#4 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\LoggerBase->updateEvent(String,Object(SP\Core\Events\Event))
#5 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeConfigService.php(224): SP\Core\Events\EventDispatcherBase->notifyEvent(String,Object(SP\Core\Events\Event))
#6 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(423): SP\Services\Upgrade\UpgradeConfigService->upgrade(String,Object(SP\Config\ConfigData))
#7 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(397): SP\Bootstrap->checkConfigVersion()
#8 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#9 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#10 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#11 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#12 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#13 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#14 /var/www/html/sysPass-3.1.0.19081801/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#15 /var/www/html/sysPass-3.1.0.19081801/index.php(28): require(String)","caller":"N/A"}
[2019-09-06 21:25:24] syspass.DEBUG: upgrade.config.end {"message":"Konfiguration aktualisieren","user":"N/A","address":"192.168.18.132","caller":"SP\\Services\\Upgrade\\UpgradeConfigService::upgrade"} []
[2019-09-06 21:25:24] syspass.EXCEPTION: logger {"message":"Kontext wurde nicht initialisiert
#0 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/ContextBase.php(143): SP\Core\Context\ContextBase->checkContext()
#1 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(100): SP\Core\Context\ContextBase->getContextKey(String,NULL)
#2 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Context/SessionContext.php(392): SP\Core\Context\SessionContext->getContextKey(String)
#3 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Language.php(223): SP\Core\Context\SessionContext->getLocale()
#4 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Providers/Log/LoggerBase.php(104): SP\Core\Language->unsetAppLocales()
#5 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Core/Events/EventDispatcherBase.php(121): SP\Providers\Log\LoggerBase->updateEvent(String,Object(SP\Core\Events\Event))
#6 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeConfigService.php(224): SP\Core\Events\EventDispatcherBase->notifyEvent(String,Object(SP\Core\Events\Event))
#7 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(423): SP\Services\Upgrade\UpgradeConfigService->upgrade(String,Object(SP\Config\ConfigData))
#8 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(397): SP\Bootstrap->checkConfigVersion()
#9 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#10 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#11 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#12 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#13 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#14 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#15 /var/www/html/sysPass-3.1.0.19081801/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#16 /var/www/html/sysPass-3.1.0.19081801/index.php(28): require(String)","caller":"N/A"}
[2019-09-06 21:25:24] syspass.ERROR: logger {"message":"Could not set locale","caller":"SP\Core\Language::setLocales"}
[2019-09-06 21:25:24] syspass.INFO: logger {"message":"Saved icons cache","caller":"SP\Core\UI\Theme::saveIcons"}
[2019-09-06 21:25:24] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2019-09-06 21:25:24] syspass.DEBUG: upgrade.db.start {"message":"Datenbank aktualisieren","user":"N/A","address":"192.168.18.132","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::upgrade"} []
[2019-09-06 21:25:24] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"192.168.18.132","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-09-06 21:25:24] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"192.168.18.132","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-09-06 21:25:24] syspass.DEBUG: upgrade.db.process {"message":"Version: 300.18010101","user":"N/A","address":"192.168.18.132","caller":"SP\\Services\\Upgrade\\UpgradeDatabaseService::applyUpgrade"} []
[2019-09-06 21:25:24] syspass.EXCEPTION: logger {"message":"SQLSTATE[HY000]: General error: 1728 Cannot load from mysql.proc. The table is probably corrupted
#0 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(173): PDO->exec(String)
#1 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade(String)
#2 /var/www/html/sysPass-3.1.0.19081801/app/modules/web/Controllers/UpgradeController.php(89): SP\Services\Upgrade\UpgradeDatabaseService->upgrade(String,Object(SP\Config\ConfigData))
#3 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#4 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#5 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#8 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#9 /var/www/html/sysPass-3.1.0.19081801/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#10 /var/www/html/sysPass-3.1.0.19081801/index.php(28): require(String)","caller":"N/A"}
[2019-09-06 21:25:24] syspass.EXCEPTION: logger {"message":"Fehler beim Aktualisieren der Datenbank
#0 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Services/Upgrade/UpgradeDatabaseService.php(108): SP\Services\Upgrade\UpgradeDatabaseService->applyUpgrade(String)
#1 /var/www/html/sysPass-3.1.0.19081801/app/modules/web/Controllers/UpgradeController.php(89): SP\Services\Upgrade\UpgradeDatabaseService->upgrade(String,Object(SP\Config\ConfigData))
#2 [internal function]: SP\Modules\Web\Controllers\UpgradeController->upgradeAction()
#3 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/sysPass-3.1.0.19081801/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/sysPass-3.1.0.19081801/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/sysPass-3.1.0.19081801/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/html/sysPass-3.1.0.19081801/index.php(28): require(String)","caller":"N/A"}

Any ideas?

**Comment by alebeta90** [comment]
Hi,

I can see this message in the logs

`SQLSTATE[HY000]: General error: 1728 Cannot load from mysql.proc. The table is probably corrupted`

maybe you can check the DB health just in case.

**Comment by ednt** [comment]
mysqlcheck says OK to all databases. Also to mysql.proc

But I upgraded from jessie to stretch cause of php7.
How can I check the database access like syspass is doing it?

**Comment by ednt** [comment]
I can access the database via

 mysql -u syspass -p syspass

with the password from config.xml

**Comment by nuxsmin** [comment]
@ednt Hello, sysPass is only displaying and error thrown by the database. It uses  the standard PHP PDO interface and no low level commands for connecting.

Regards.

**Comment by nuxsmin** [comment]
There are some points on: https://serverfault.com/questions/361838/mysql-cannot-load-from-mysql-proc-the-table-is-probably-corrupted

**Comment by ednt** [comment]
mysql_upgrade -u root -p

did the trick.
