### ISSUE TITLE
Connection issues with Azure Database for MySQL server

### ISSUE THREAD

**Issue by mariusfylling** [nuxsmin/sysPass#1454]
**sysPass Version**
v3.1

**Describe the question**
When trying to install sysPass, the installer can not connect to the Azure Database for MySQL server database. The issue is probably related to how usernames work with the Azure Database for MySQL database. 

**username@database-server-name**

The issue is that the connection is made to the wrong server, it tries to connect to the server running sysPass even though the value "sysPass database server" is set to the Azure db server connection hostname. If I remove the @ from the username, the installer connects to the Azure db server, but will not be able to continue due to it being the wrong username.

Some information about the connection strings can be found here: https://docs.microsoft.com/en-us/azure/mysql/howto-connection-string

**Screenshots**
![image](https://user-images.githubusercontent.com/3841012/64519165-e60cdf80-d2f3-11e9-8f4f-c944f99cca1d.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by mariusfylling** [comment]
Some new information:
This might be an issue with PHP PDO, not with Syspass. PDO outside Syspass gives the same errors.

**Comment by nuxsmin** [comment]
Good to know :wink:

Thanks for the feedback!
