### ISSUE TITLE
Error al actualizar de 1.21 a 2.1

### ISSUE THREAD

**Issue by SNepo** [nuxsmin/sysPass#1457]
**sysPass Version**
1.21

**Describe the question**

Durante el proceso de actualización tras rellenar la clave maestra y la upgrade key nos sale el siguiente mensaje:

Error al aplicar la actualización de la Base de Datos.

Los errores en el log son asi:

2019-09-12 13:07:50 - Error en la consulta
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_level' in 'field list' (0)
Caller 1: SP\Storage\DB\logDBException
Caller 2: SP\Storage\DB\getQuery
Caller 3: SP\Log\Log\writeLog
Caller 4: SP\Storage\DB\logDBException
Caller 5: SP\Storage\DB\getResults
Caller 6: SP\Storage\DB\getResultsArray
Caller 7: SP\Mgmt\Plugins\Plugin\getEnabled
Caller 8: SP\Core\Plugin\PluginUtil\getEnabledPlugins
2019-09-12 13:07:50 - SQL : 'INSERT INTO log SET \n            log_date = UNIX_TIMESTAMP(),\n            log_login = ?,\n            log_userId = ?,\n            log_ipAddress = ?,\n            log_action = ?,\n            log_level = ?,\n            log_description = ?'
2019-09-12 13:07:50 - Error en la consulta
Caller 1: SP\Log\Log\writeLog
Caller 2: SP\Storage\DB\logDBException
Caller 3: SP\Storage\DB\getResults
Caller 4: SP\Storage\DB\getResultsArray
Caller 5: SP\Mgmt\Plugins\Plugin\getEnabled
Caller 6: SP\Core\Plugin\PluginUtil\getEnabledPlugins
2019-09-12 13:07:50 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_level' in 'field list'
2019-09-12 13:10:01 - Register Task: upgrade
2019-09-12 13:10:01 - upgradeDB: 110
2019-09-12 13:10:01 - Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'account_otherGroupEdit'
2019-09-12 13:10:01 - #0  SP\Storage\DB->prepareQueryData() called at [/var/www/html/sysPass2/inc/SP/Storage/DB.class.php:150]
#1  SP\Storage\DB->doQuery() called at [/var/www/html/sysPass2/inc/SP/Storage/DB.class.php:341]
#2  SP\Storage\DB::getQuery() called at [/var/www/html/sysPass2/inc/SP/Core/Upgrade/Upgrade.class.php:234]
#3  SP\Core\Upgrade\Upgrade::upgradeDB() called at [/var/www/html/sysPass2/inc/SP/Core/Upgrade/Upgrade.class.php:87]
#4  SP\Core\Upgrade\Upgrade::doUpgrade() called at [/var/www/html/sysPass2/inc/SP/Controller/MainActionController.class.php:101]
#5  SP\Controller\MainActionController->upgrade() called at [/var/www/html/sysPass2/inc/SP/Controller/MainActionController.class.php:72]
#6  SP\Controller\MainActionController->doAction() called at [/var/www/html/sysPass2/ajax/ajax_upgrade.php:36]

He comprobado y en la la base de datos no existe esa tabla.

MariaDB [syspass]> show tables;
+-------------------+
| Tables_in_syspass |
+-------------------+
| accFiles          |
| accGroups         |
| accHistory        |
| accUsers          |
| accounts          |
| authTokens        |
| categories        |
| config            |
| customFieldsData  |
| customFieldsDef   |
| customers         |
| log               |
| usrData           |
| usrGroups         |
| usrPassRecover    |
| usrProfiles       |
| usrToGroups       |
+-------------------+

¿Esas tablas deberían estar o deberían crearse solas?

**Comment by nuxsmin** [comment]
Buenas, por favor actualiza a la última versión de v1, luego a V2 y luego a v3

**Comment by SNepo** [comment]
¿Cual es la versión exacta de la ultima v1?

**Comment by nuxsmin** [comment]
1.2.0.21

Puedes seleccionar la rama 1.2 y descargarla

**Comment by SNepo** [comment]
He actualizado a la 1.2.0.21

Despues de actualizar y comprobar que todo funcionaba he cogido al bbdd de la 1.2 y su archivo config.

He puesto la version de la 2.1 que esta en el branch. A la hora de actualizar me salta lo mismo error en actualizar bbdd

2019-09-20 11:07:58 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_level' in 'field list'
2019-09-20 11:07:58 - Action: Actualizar BBDD -- Description: Error al aplicar la actualización de la Base de Datos -- Details: Versión : 110

**Comment by SNepo** [comment]
Buenas,

Estoy bloqueado con la actualización a la v2. He logrado actualizar a la 2.0 beta y por fin crea las tablas que me faltaban como plugin y demas.

Pero ahora no logro hacer funcionar las RC de la v2 ni la propia v2. Cuando sale el mensaje de actualizar lo pulso,me pide la clave de acutalizacion y la meto da un error 500. Despues de eso se pone en mantenimiento.

Si la saco de mantenimiento vuelve a salir la pantalla de actualizar pero ahora al darle a acutalizar no hace nada, simplemente carga la pagina index.php?upgrade=1&a=upgrade 

No ha generado ningun log de syspass.  Veo esto en el error.log

PHP Notice:  Constant BASE_DIR already defined in /var/www/html/sysPass-2.0-final/inc/Base.php on line 34, referer: https://*.*.*.*/sysPass-2.0-final/index.php?upgrade=1&a=upgrade

**Comment by SNepo** [comment]
La incidencia persiste. No entiendo porque ocurre ese fallo en la variable BASE_DIR

**Comment by nuxsmin** [comment]
Buenas, sería conveniente actualizar a la última de V2 ya que es posible que algunos fallos sean corregidos. No es necesario actualizar a todas las versiones menores, esto es actualizar de V2 a v2.1 luego a v3....

Saludos

**Comment by SNepo** [comment]
Buenas,

Sigo bloqueado, actualizo correctamente a la 1.2 pero desde la 1.2 falla al actualizar a la 2.0.

El boton de actualizar no hace nada, es como si no fuera capaz de llegar a su destino,simplemente recarga la pagina.

He hecho esto varias veces para ver si era fallo de permisos pero yo los corrigo adecuadamente.

 598  chmod -Rv 750 /var/www/html/sysPass-2.0/
  599  chown -Rv www-data /var/www/html/sysPass-2.0/

El config.xml generado del config.php esta y lo lee ya que si cambio el apartado de mantenimiento lo detecta,

**Comment by nuxsmin** [comment]
Buenas, puede ser por el navegador, cuál utilizas?

**Comment by SNepo** [comment]
He probado con Chrome, con Internet explorer y con Firefox. En todos ocurre lo mismo en la pagina index.php?upgrade=1&a=upgrade sigue saliendo el botón actualizar que apunto hacia la misma ruta.

**Comment by nuxsmin** [comment]
Buenas,  en la sección de releases de GitHub, en la última release, hay un archivo adjunto "vendor.tar.gz" que al descomprimirlo en el directorio de sysPass, evitará la descarga de dependencias.

Saludos!

**Comment by SNepo** [comment]
Buenas,

Entiendo que la carpeta vendor debe de estar en la carpeta del syspass con los mismos permisos.

Tras hacer eso ahora el mensaje que me sale en el index es este:

Class SP\Services\Plugin\PluginDataService does not exist

Y en el syspass.log que se ha generado sale esto.


#1 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Source/ReflectionBasedAutowiring.php(32): DI\Definition\Source\ReflectionBasedAutowiring->getParametersDefinition(Object(ReflectionMethod))
#2 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Source/ReflectionBasedAutowiring.php(41): DI\Definition\Source\ReflectionBasedAutowiring->autowire(String)
#3 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Source/SourceChain.php(54): DI\Definition\Source\ReflectionBasedAutowiring->getDefinition(String)
#4 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Container.php(153): DI\Definition\Source\SourceChain->getDefinition(String)
#5 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Container.php(132): DI\Container->getDefinition(String)
#6 /var/www/html/sysPass-3.1/app/modules/web/Init.php(130): DI\Container->get(String)
#7 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(142): SP\Modules\Web\Init->__construct(Object(DI\Container))
#8 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition),Array)
#9 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition),Array)
#10 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Container.php(377): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition),Array)
#11 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Container.php(137): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#12 /var/www/html/sysPass-3.1/lib/SP/Bootstrap.php(231): DI\Container->get(String)
#13 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#14 /var/www/html/sysPass-3.1/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#15 /var/www/html/sysPass-3.1/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#16 /var/www/html/sysPass-3.1/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#17 /var/www/html/sysPass-3.1/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#18 /var/www/html/sysPass-3.1/index.php(28): require(String)","caller":"N/A"}
[2019-11-05 17:12:23] syspass.ERROR: logger {"message":"Could not set locale","caller":"SP\Core\Language::setLocales"}
[2019-11-05 17:12:23] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2019-11-05 17:12:23] syspass.EXCEPTION: logger {"message":"Class SP\Services\Plugin\PluginDataService does not exist
#0 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Source/ReflectionBasedAutowiring.php(65): ReflectionParameter->getClass()
#1 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Source/ReflectionBasedAutowiring.php(32): DI\Definition\Source\ReflectionBasedAutowiring->getParametersDefinition(Object(ReflectionMethod))
#2 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Source/ReflectionBasedAutowiring.php(41): DI\Definition\Source\ReflectionBasedAutowiring->autowire(String)
#3 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Source/SourceChain.php(54): DI\Definition\Source\ReflectionBasedAutowiring->getDefinition(String)
#4 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Container.php(153): DI\Definition\Source\SourceChain->getDefinition(String)
#5 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Container.php(132): DI\Container->getDefinition(String)
#6 /var/www/html/sysPass-3.1/app/modules/web/Init.php(130): DI\Container->get(String)
#7 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(142): SP\Modules\Web\Init->__construct(Object(DI\Container))
#8 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition),Array)
#9 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(64): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition),Array)
#10 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Container.php(377): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition),Array)
#11 /var/www/html/sysPass-3.1/vendor/php-di/php-di/src/Container.php(137): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#12 /var/www/html/sysPass-3.1/lib/SP/Bootstrap.php(231): DI\Container->get(String)
#13 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#14 /var/www/html/sysPass-3.1/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#15 /var/www/html/sysPass-3.1/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#16 /var/www/html/sysPass-3.1/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#17 /var/www/html/sysPass-3.1/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#18 /var/www/html/sysPass-3.1/index.php(28): require(String)","caller":"N/A"}

**Comment by SNepo** [comment]
Buenas,

El error persiste ¿Donde debe de ir exactamente la carpeta vendor? porque tal vez no la estoy colocando correctamente y esto provoca fallos.

Yo pongo la carpeta dentro de la ruta del syspass con los mismos permisos que la carpeta de syspass.  O bien descomprimida.

Un saludo y gracias.

**Comment by HerroBert** [comment]
I got the same error _Class SP\Services\Plugin\PluginDataService does not exist_ after upgrading from 3.0 to 3.1

**Comment by nuxsmin** [comment]
Buenas @SNepo 

el directorio vendor está en la ruta correcta. Puedes verificar que el archivo `/var/www/html/sysPass-3.1/lib/SP/Services/Plugin/PluginDataService.php` existe?

**Comment by nuxsmin** [comment]
Hello @HerroBert 

could you check if `/var/www/html/[syspass_directory]/lib/SP/Services/Plugin/PluginDataService.php` does exist?

**Comment by SNepo** [comment]
Buenas @nuxsmin 

He comprobado que el archivo existe. Te adjunto captura con sus permisos y su tamaño.

![image](https://user-images.githubusercontent.com/55086018/70906767-7d768280-2007-11ea-820a-0bbdbd43e87d.png)

**Comment by nuxsmin** [comment]
Buenas @SNepo 

disculpa, ha habido un error al generar el archivo `vendor.tar.gz` por el cual no estaba actualizado el origen de los fuentes de la aplicación. Ya he subido el archivo actualizado en la última release.

---
Hello @HerroBert

Sorry for the inconvenience, there was an error while building the `vendor.tar.gz` file because the source application code wasn't updated. I've just uploaded it to the latest release.

**Comment by nuxsmin** [comment]
Buenas!

hace algo de tiempo estuve tratando una incidencia con la migración desde 1.2 por lo que podría ayudarte si estás en el mismo caso: #1548

Saludos!
