### ISSUE TITLE
Remove "listed" users from a group

### ISSUE THREAD

**Issue by bruogasawara** [nuxsmin/sysPass#1461]
**sysPass Version**
3.1

First off, thank you for this application. It's awesome.

I'm trying to set the users permissions in my groups.
I understand that a user have a main group, and if he's included in another groups, these other groups are the secondary groups.

I've added two users to a group. And they are listed in this group, since these group it's not their main group.

My question is:
How to I remove a user from this group ?
As you can see in the screenshot, I cannot see an option to remove listed users from the group.
Is it possible to do that ?
How can I do it ?

Thanks in advance,
Bruno

![image](https://user-images.githubusercontent.com/48995709/65174606-9a5ee200-da27-11e9-9f6f-015377ec7393.png)

OS Centos 7

**Comment by nuxsmin** [comment]
Hello, I'm glad to know you find sysPass useful.

Regarding your question, that list is only for displaying which users are set this group as the main group, so it's only for information purposes.

You need to unset the group on the user's card.

Regards

**Comment by bruogasawara** [comment]
Hello,

Thank you very much for your reply.

In my user card, I can only see the main group.
For example:
My main group is "Admins", as you can see in the screenshot below:
![image](https://user-images.githubusercontent.com/48995709/65179973-3857aa00-da32-11e9-8a43-8e7be57f7cf9.png)

And I have as secondary group, a group called "Operação"
I can see in the screeshot above that my user is Listed with a * .
![image](https://user-images.githubusercontent.com/48995709/65179993-47d6f300-da32-11e9-8408-cbcf80e8c76d.png)

But in my user card, I can only see my main group
How do I remove my user from the secondary group ?

**Comment by nuxsmin** [comment]
Hmm, you only need to remove your user from the group (the blue tag)

**Comment by bruogasawara** [comment]
When I click on my user (the blue tag), nothing happens.
If I double click, it doesn't work. 
I've try to click and drag away, but it doesn't work either.

When I click on it, it just change colors. 
If I click (and change the color), and try to save. It says "No changes"

**Comment by nuxsmin** [comment]
click on blue tag and press "delete" or "backspace" keys

**Comment by bruogasawara** [comment]
nuxsmin,

yes, now I've removed my account from the secondary group !!!

thanks for your support
and congratulations for the simple, good and useful tool that you developed.

**Comment by nuxsmin** [comment]
Thanks for the feedback!
