### ISSUE TITLE
Syspass error 

### ISSUE THREAD

**Issue by dvdcasta** [nuxsmin/sysPass#1462]
**sysPass Version**

.1 (310.19081801)  Config: 310.19081801  App: 310.19081801  DB: 310.19081801
--
Base de Datos | SERVER_VERSION : 5.5.5-10.4.8-MariaDB  CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $  SERVER_INFO : Uptime: 128 Threads: 7 Questions: 150 Slow queries: 0 Opens: 39 Flush tables: 1 Open tables: 33 Queries per second avg: 1.171  CONNECTION_STATUS : Localhost via UNIX socket  Nombre: syspass@localhost
PHP | Versión: 7.2.22  Extensiones: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, zip, Zend OPcache  Memoria Usada: 4096 KB  Usuario: apache  Tasa de descarga: 43 MB/s  OP Cache  num_cached_scripts : 328  num_cached_keys : 620  max_cached_keys : 7963  hits : 3999  start_time : 1569262732  last_restart_time : 0  oom_restarts : 0  hash_restarts : 0  manual_restarts : 0  misses : 597  blacklist_misses : 0  blacklist_miss_ratio : 0  opcache_hit_rate : 87,01044386423
Servidor | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.22
Copia de Configuración | Mon, 23 Sep 2019 18:15:03 +0000

**Describe the question**

I implementing a syspass in departament, so configuring a authentication for AD sending error for images 

**Screenshots**
<img width="591" alt="image" src="https://user-images.githubusercontent.com/48453641/65452798-85a79300-de07-11e9-809a-7475019ce437.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/48453641/65452839-96580900-de07-11e9-9d24-84b4c4de42e6.png">

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android]
 - OS Version
 - Browser [e.g. Firefox, Chrome]

**Additional context**

**Comment by dvdcasta** [comment]
My issue has resolved

**Comment by nuxsmin** [comment]
Thanks for the feedback!
