### ISSUE TITLE
Export from syspass to readable form

### ISSUE THREAD

**Issue by dariusz-hub** [nuxsmin/sysPass#1466]
I know there is a possibility of importing from keepass. However, can I export entries to keepass or csv? I would like to be able to view the password in the case of DR (Disaster Recovery). sysPass Decrypter probably does not allow exporting but only to view passwords. Import to another syspass instane doesnt work in docker (https://github.com/nuxsmin/sysPass/issues/1439).
I would like to protect myself in the event of a server crash and I don't feel safe at the moment.

**Comment by nuxsmin** [comment]
Hello , you could use sysPass-decrypter by parsing the console output...

Yes, it isn't the more suitable way, but as discussed for many times, sysPass is a security tool and I'm committed to create a "secure" chain by not coding such exporting ways. This doesn't mean it isn't possible, but I wouldn't code by myself...

Regards
