### ISSUE TITLE
Reverse Proxy Issue

### ISSUE THREAD

**Issue by eneamarcantoni** [nuxsmin/sysPass#1468]
**sysPass Version:** 3.1

**Question**
I have correctly setupped syspass on the webserver and everithing working well, but if I want to put it behind a reverse proxy whit HTTPS enabled I have an issue:
The browser don't load CSS and other contents because they are returned in HTTP.
For example in chrome I have the mixed content message.
I have correctly setupped the X-Forwarded-Proto header on the reverse proxy, but I think that syspass ignore it.
Is possible to force syspass to return content in HTTPS?

**Platform:**
 - OS: CentOS
 - OS Version: 7
 - Browser: All
 - WebServer and Reverse Proxy: nginx

**Additional context**
WebServer config:
[web_server.txt](https://github.com/nuxsmin/sysPass/files/3678005/web_server.txt)

Reverse Proxy config:
[reverse_proxy.txt](https://github.com/nuxsmin/sysPass/files/3677999/reverse_proxy.txt)

**Comment by nuxsmin** [comment]
Hello, yes it's possible through settings (Configuration > General)

Regards

**Comment by eneamarcantoni** [comment]
I have correctly enabled it, but I have to disable it because as you can see on the two config files attached the reverse proxy pass the request to WebServer on port 80. Enabling HTTPS from settings of syspass redirect all request to HTTPS and it is correct, but redirect the request on listening port of the WebServer: 80.
Obviously I call the reverse proxy in HTTPS on standard 443.

**Comment by nuxsmin** [comment]
Oops, the files aren't shown on mobile app..

You can use the application URL option in order to set the external URL when using a reverse proxy or LB.

Regards

**Comment by orest-gulman** [comment]
> You can use the application URL option in order to set the external URL when using a reverse proxy or LB.
Could you please provide an example. Thanks

**Comment by HaziFlorinMarian** [comment]
@nuxsmin this issue still persists.
Screenshot for website running SSL for exposed port but 80 for internal communication.
https://prnt.sc/Cj2qGThit_He
