### ISSUE TITLE
Migration to a new installation

### ISSUE THREAD

**Issue by jboissat** [nuxsmin/sysPass#1469]
Hello

Today I have a local Syspass server that works perfectly, I just created a new server in Datacenter and I want to migrate the local datacenter

My backups are well done SQL and application however I would like to know the exact procedure knowing that the two servers do not have the same masterkey

thank you in advance

**Comment by nuxsmin** [comment]
Hello, you need to restore the app files and then the database, using the same connection credentials, if not, please update the config.xml file.

Once restored, the data will be decrypted by the old master password, so no need to change the master password.

Regards

**Comment by jboissat** [comment]
Hello

Thank You

**Comment by jboissat** [comment]
Hello

Once the migration made I can connect a first, however, at the second connection I have an error "page not found"

Do you have an idea of the problem ?

Thank you

**Comment by jboissat** [comment]
Here is url redirection after log validation :

http://10.***.***.**/syspass/undefined

**Comment by Nebucatnetzer** [comment]
@jboissat try to do a manual mysql dump with:
```
sudo mysqldump syspassdb > syspass.sql
```
Then restore everything like you would normally do but use the manual dump instead of the Syspass generated one.

**Comment by ajinkyag10** [comment]
Hi @nuxsmin..
Can we use Google cloud identity which provides a simple & secure way to integrate Ldap applications, with sysPass instead of active directory??
