### ISSUE TITLE
Translate: Corrección español y otras lenguas.

### ISSUE THREAD

**Issue by ferrergl** [nuxsmin/sysPass#147]
Buenas noches.

Estoy realizando la traducción al catalán para la integración en mis sistemas y he advertido que en la linea 756 (editando con PoEdit), equivalente a la linea 3934 de los ficheros .po existe un pequeño error al escribir la palabra archivo, que aparece como "arhcivo".

La traducción al catalán esta al 80% y entre hoy y mañana estará lista. Si te interesa añadirla a los repositorios no hay inconveniente en facilitarla, es mas, me gustaría contribuir con ella y con otros temas en el futuro.

**Comment by nuxsmin** [comment]
Perfecto!! Te lo iba a comentar cuando vi el dominio .cat  pero no sabia si era tu propósito...

Voy a revisar el código, pero si quieres (y utilizas git), puedes hacer un pull request para modificar eso y añadir la traducción.

Si tienes pensado añadir alguna funcionalidad echa un vistazo a la rama dev, ya que en breve habrá avances en la estructura de la aplicación. ej: adaptado a PSR-4, a PSR-3 y nuevas clases para la construcción de los datagrid.

Gracias!!

**Comment by ferrergl** [comment]
En un futuro si, de momento estoy con la traducción ya que me corre algo de prisa y las proximas semanas estaré liado con la uni. Pero cuando tenga algo mas de tiempo si que mirare de colaborar, aunque tengo algo oxidado el tema jeje.

**Comment by ferrergl** [comment]
En la linea 4966 del fichero .po o la linia 60 de /inc/themes/material-blue/profiles.inc aparece la palabra "Var ..." cuando deberia ser "Ver ..."

#: ../../../../inc/themes/material-blue/profiles.inc:60
msgid "Var archivos de cuenta"
msgstr ""
>>>
#: ../../../../inc/themes/material-blue/profiles.inc:60
msgid "Ver archivos de cuenta"
msgstr ""
