### ISSUE TITLE
File type not allowed

### ISSUE THREAD

**Issue by decha1980** [nuxsmin/sysPass#1470]
**sysPass Version**
3.1

**Describe the bug**
Error importing file.

**Event log**
[2019-10-04 12:16:44] syspass.EXCEPTION: logger {"message":"File type not allowed
#0 /var/www/html/syspass/app/modules/web/Controllers/AccountFileController.php(226): SP\Modules\Web\Controllers\AccountFileController->checkAllowedMimeType(Object(SP\DataModel\FileData),Object(SP\Storage\File\FileHandler))
#1 [internal function]: SP\Modules\Web\Controllers\AccountFileController->uploadAction(Integer)
#2 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#4 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#8 /var/www/html/syspass/index.php(28): require(String)","caller":"N/A"}

**Platform (please complete the following information):**
 - OS: Ubuntu 
 - OS Version: 18.04.3 LTS
 - Browser Firefox, Chrome

**Additional context**
I installed syspass according to the instructions on the page:
https://kifarunix.com/install-syspass-password-manager-on-ubuntu-18-04/

**Comment by nuxsmin** [comment]
Hello, did you add the file mime type to  the allowed list in accounts configuration?

Regards

**Comment by nuxsmin** [comment]
Hello, did you add the file mime type to  the allowed list in accounts configuration?

Regards

**Comment by nuxsmin** [comment]
Hello, did you add the file mime type to  the allowed list in accounts configuration?

Regards

**Comment by nuxsmin** [comment]
Hello, did you add the file mime type to  the allowed list in accounts configuration?

Regards

**Comment by nuxsmin** [comment]
Hello, did you add the file mime type to  the allowed list in accounts configuration?

Regards

**Comment by decha1980** [comment]
Hello,
my mistake. I actually forgot to add configuration exceptions. Thank you.
