### ISSUE TITLE
Migración Base de datos

### ISSUE THREAD

**Issue by gbroin** [nuxsmin/sysPass#1471]
Hola Rubén, cómo estas?

Te quería consultar, quisiera mover la base de datos de Servidor, en éste momento tengo el servidor web y el de base de datos en el mismo equipo.

Lo que quiero es migrar la base de servidor porque estoy unificando los sistemas que tengo que utilizan MariaDB.

No recuerdo que contraseña le puse al usuario de la base de datos de syspass, tengo acceso via root (mala mía). La base ya la migré pero como no recuerdo cual es la contraseña del usuario syspass y en el archivo /var/www/html/syspass/app/config/config.xml esta cifrada quería saber que puedo usar para cifrar la nueva contraseña de usuario de la base de datos y si tengo que cambiar en algún otro lado los datos de acceso a la base.

Desde ya muchas gracias.

**Comment by nuxsmin** [comment]
Buenas!

 La configuración de la base de datos está en el archivo 'config.xml', por lo que creando las mismas credenciales que en archivo y cambiando el dbHost al nuevo nombre o IP del servidor de BD, es suficiente.

Saludos!

**Comment by gbroin** [comment]
Hola Rubén,

Entiendo, el tema es que no puedo recordar que clave la asigne al usuario dueño de la base de datos y como en el archivo config.xml esta cifrada lo que necesito hacer es en el nuevo servidor donde corre MariaDB asignarle una nueva password al usuario de la base de datos, por ende voy a tener que cifrar la clave para cambiarla en el archivo config.xml y quería saber que herramienta tengo que usar para cifrar la clave? Gracias!

**Comment by nuxsmin** [comment]
Buenas, disculpa la demora.

La clave de MariaDB no está cifrada, por lo que puedes ponerla tal cual en el archivo.

Saludos!
