### ISSUE TITLE
MyCrypt Deprecated after PHP 7.2 - What will sysPass do? 

### ISSUE THREAD

**Issue by tmanok** [nuxsmin/sysPass#1472]
From the documentation found on your docs server: https://doc.syspass.org/en/3.1/installing/debian9.html

I was in the process of installing sysPass without specifying php7.0 because apt on Debian Minimal (CD) now uses php 7.3.... Anyway so while specifying I noticed:
E: Package 'php-mcrypt' has no installation candidate
After looking a little further I noticed that php-mcrypt is no longer supported by php, which means that sysPass will need a new package in the near future. As I'm building this sysPass server for a company I cannot rely on deprecated packages. 
Thanks!

Tmanok

**Comment by nuxsmin** [comment]
Hello,

 Please note the notice about mcrypt : "mcrypt (optional for importing older XML export files)"

mcrypt was retired from sysPass since v2.0, so OpenSSL is used instead.

Regards

**Comment by tmanok** [comment]
Ok thanks! Does that mean I don't need to install mcrypt at all in that case?

**Comment by MagicFab** [comment]
> Ok thanks! Does that mean I don't need to install mcrypt at all in that case?

No.
