### ISSUE TITLE
SysPass Master Password Reset Not Working (Says it's working)

### ISSUE THREAD

**Issue by tmanok** [nuxsmin/sysPass#1473]
**sysPass Version**
3.1 (310.19081801)
Config: 310.19081801
App: 310.19081801
DB: 310.19081801

**Describe the bug**
Enable Maintenance Mode, Save Config, Click on Encryption Tab

**To Reproduce**
Install on Debian Buster CD
Install MariaDB and create root user, create syspass database
Install apache2, all PHP modules except mcrypt7.0-php
Login
Enable Maintenance Mode, Save Config, Click on Encryption Tab
Enter old master password 
Enter new master password twice following complexity requirements
Click "Confirm Change"
"The master password has been changed" or something similar (forgot to write it down but my colleague and I saw it probably 50 times while testing). No other icons or messages appear.

**Expected behavior**
Master password should change.... MySQL should load..... PHP should be processing things....

**Actual behavior**
Master password does not change and no processes take place.

**Event log**
The only relevant event can be found below:
[2019-10-07 16:23:02] syspass.DEBUG: refresh.masterPassword.hash {"message":"Master password hash updated","user":"sysadmin","address":"10.99.54.4","caller":"SP\\Modules\\Web\\Controllers\\ConfigEncryptionController::refreshAction"} []

**Platform (please complete the following information):**
 - OS: MacOS & Ubuntu
 - OS Version
 - Browser Safari, Firefox, Chrome

**Additional context**
It would appear that even randomly generated new passwords do not work. Additionally, any "Old password" even random characters is accepted...... So it's definitely not doing anything with the data. Also it says " It will be updated 0 accounts. This process could take some time long." meanwhile we have 3 test users and the primary administrator (sysadmin) account.

**Comment by nuxsmin** [comment]
Hello, you only changed the master password hash, so you didn't change the master password indeed...

The master password hash is a cryptographic string to check whether the master password is correct when entered on login screen, so changing it only generates a new hash.

Regards

**Comment by tmanok** [comment]
Ah ok my bad then.
