### ISSUE TITLE
X-Fowrward IP no set on history syspass

### ISSUE THREAD

**Issue by luigdima** [nuxsmin/sysPass#1474]
**Is your feature request related to a problem? Please describe.**

Hi!,
In my infraestructure, syspass is back than a proxypass service (traffic). When I do share password to other and external users, the syspass history ,registred a local IP address (a local adrress docker). I suppose, it don't registre x-forward IP address on history.

**Describe the solution you'd like**

This module RPAF (https://github.com/gnif/mod_rpaf) setign the formward-ip to remote_addr. It's possible include this module on Apache2 service?

**Describe alternatives you've considered**

Other solution is a selector on configuration panel for select the header meta IP.

Thanks!!

**Comment by alexanderbuhler** [comment]
Up on this one. Just happened to have a full password reset leading to numerous failed login attempts, almost immediately running into lock because of shared docker gateway ip (172.18.0.1). 

Cheers

**Comment by nuxsmin** [comment]
Hello, sysPass will try to guess the client's IP address by looking for the `X-FORWARD` headers, but sometimes it would fail and the LB or proxy address will be used. There aren't a "formal" implementation so each device would send the header in its own forma...

![image](https://user-images.githubusercontent.com/1775774/70868693-76a62c00-1f83-11ea-9b88-4ea073f8b86c.png)

Cheers!
