### ISSUE TITLE
Custom fields with API

### ISSUE THREAD

**Issue by Memurame** [nuxsmin/sysPass#1476]
**sysPass 3.1 (310.19081801)**

I want to retrieve the custom fields via API. Is this possible? I have tried it with `account/view` but the fields are not displayed here. I want to define certain fields which I would like to retrieve then urgently via API

**Comment by nuxsmin** [comment]
Hello, this FR will be implemented in next release.

Regards

**Comment by nuxsmin** [comment]
https://github.com/nuxsmin/sysPass/issues/422
