### ISSUE TITLE
TAB SAVE : Template does not contain files

### ISSUE THREAD

**Issue by jboissat** [nuxsmin/sysPass#1479]
Hello

We managed our migration ^ ^ however it remains a small problem when we go in parameter then the backup tab we have the following message: Template does not contain files

Why ?

Thank You

**Comment by nuxsmin** [comment]
Hello,

could you provide some information about your sysPass instance (`Configuration > Information` tab) and `syspass.log` file?

Regards

**Comment by jboissat** [comment]
Hello

Sorry for my late reply and for my double post which I will close.

here is the file

[syspass.zip](https://github.com/nuxsmin/sysPass/files/4013211/syspass.zip)


Thank You

**Comment by antfobe** [comment]
Had the same problem, a lot of files were missing from the backup and I manually copied them from the git v3.1 branch.
In my bash history they were:
```
app/modules/web/themes/material-blue/views/config/backup.inc
lib/SP/Services/Backup/
app/modules/web/Controllers/ConfigBackupController.php
```

**Comment by nuxsmin** [comment]
@jboissat did you place a `backup.php` within sysPass root folder?

**Comment by jboissat** [comment]
Hello

I added the missing files, the backup tab is visible now however when I start a backup the latter goes in circles and freezes syspass

![Capture](https://user-images.githubusercontent.com/43809874/87812820-1224b580-c861-11ea-86ad-db2915eeebf4.PNG)

Thank you

**Comment by HerroBert** [comment]
Same problem here after updating from 3.1.0 to 3.1.2:
[2020-08-06 15:33:08] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2020-08-06 15:33:08] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2020-08-06 15:33:08] syspass.EXCEPTION: logger {"message":"Vorlage enthält keine Dateien
#0 /var/www/sys/sysPass/app/modules/web/Controllers/ControllerBase.php(184): SP\Mvc\View\Template->render()
#1 /var/www/sys/sysPass/app/modules/web/Controllers/InstallController.php(68): SP\Modules\Web\Controllers\ControllerBase->view()
#2 [internal function]: SP\Modules\Web\Controllers\InstallController->indexAction()
#3 /var/www/sys/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/sys/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/sys/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/sys/sysPass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/sys/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/sys/sysPass/index.php(28): require(String)","caller":"N/A"}

**Comment by ThigSchuch** [comment]
Using syspass 3.2 and Authenticator
![image](https://user-images.githubusercontent.com/20743110/125791873-80eadcc0-e24c-4246-b530-8a1a63764bb2.png)

Then I get this tab in user preferences
![image](https://user-images.githubusercontent.com/20743110/125791950-3c6e7499-930c-4b51-a3d7-7d9a4cb69042.png)

If I disable plugin, that tab disappear.
