### ISSUE TITLE
Restoration Howto

### ISSUE THREAD

**Issue by nuxsmin** [nuxsmin/sysPass#148]
Add some howto to restore sysPass from scratch

**Comment by vmario89** [comment]
i think this documentation will be a little bit bigger :-D most common ways if owning config.xml and database dump, are:
- web server on bare metal / virtual machine
- web server on docker / container platform
- web server (portable) on some pluggable media

this documentation also belongs to the "how to backup" sysPass in a good way.
- save config backup manually by logging in as admin to the web frontend
- make some scripted mysql/mariadb data dump
- the coolest thing would be some database replication master-slave (i did not test this out yet). Somebody mentioned/requested compability with MariaDB Galera Cluster (https://github.com/nuxsmin/sysPass/issues/894)

**Comment by nuxsmin** [comment]
Started on https://syspass-doc.readthedocs.io/en/3.1/application/backup.html

Thanks for the feedback @vmario89 !
