### ISSUE TITLE
Local envoironment only

### ISSUE THREAD

**Issue by Felsser** [nuxsmin/sysPass#1481]
**3.1 (310.19081801) **
Can be found on `Config -> Information` tab

**Describe the question**
Hello, I'm trying to use SysPass on a local VM as Passwordserver, there should be no access from outside except for VPN (which is basically local again). 

Browsers flag the connection as insecure and even if we do a exception it flags it somehow in the adressbar. 

Is it possible to run SysPass without these warnings? 
**Screenshots**

**Platform (please complete the following information):**
 - OS: [Ubuntu 18.04.3 LTS]
 - Browser [e.g. Firefox, Chrome]
Firefox/Chrome/Edge/IE

**Comment by nuxsmin** [comment]
Hello, please use the HTTPS protocol with a valid signed certificate (eg. Let's Encrypt).

Regards
