### ISSUE TITLE
Can't delete retired AD LDAP Users

### ISSUE THREAD

**Issue by 90er** [nuxsmin/sysPass#1482]
Hi @nuxsmin,

first of all: thanks again for your great work.

**sysPass Version**
 3.1 (310.19081801)

**Describe the bug**
I'm not able to delete retired Active Directory LDAP Users. I have some LDAP users in sysPass, that are retired. I checked, that there are no accounts left for these users (use special filters in Web UI).

I haven't changed anything in the database by hand.

**To Reproduce**
1. Login as sysPass admin
2. Go to the users
3. (Try to) delete an LDAP user (already set to inactive)

**Expected behavior**
I should be able to delete these users.

**Event log**
```
Integritätsbedingung
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a
foreign key constraint fails (`syspass`.`AccountHistory`, CONSTRAINT `fk_AccountHistory_userEditId`
FOREIGN KEY (`userEditId`) REFERENCES `User` (`id`))
```

**Platform (please complete the following information):**
- OS: CentOS 7

**Comment by Remi-PAULEAU** [comment]
Hi,

Try to look here and delete : 

![rpa](https://user-images.githubusercontent.com/36929745/66755460-4ca78f00-ee98-11e9-8b16-c2f750ef3420.png)

Regards

**Comment by 90er** [comment]
Hi @Remi-PAULEAU ,

I can only find accounts in these tabs, but I try to delete a user. Can you explain me, what you mean with it?

Thanks

**Comment by nuxsmin** [comment]
Hello @Remi-PAULEAU 

It seems that the user is set in the account's history, so this means that you won't be able to delete the user because its ID is needed to restore an account from the history.

Regards

**Comment by Hr46ph** [comment]
I am having the same issue and the answer doesn't help.

Accounts history is "Accounts (H)", is that correct?

Because I completely cleared that and I still can't delete the user. I get the same error as above:
"SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row"

Can you please assist?

**Comment by Arash9703** [comment]
Hi , 
I also have the same error, and the answer doesn't help.

Kind regards

**Comment by Hr46ph** [comment]
> Hi , I also have the same error, and the answer doesn't help.
> 
> Kind regards

You need to stop using this and move to something else. The project has been dead for over a year now and the developers aren't responding to issues. Look at last commit and how many open issues there.

My advise: count your losses and move on.
