### ISSUE TITLE
Error Language

### ISSUE THREAD

**Issue by henrique-bortoletto** [nuxsmin/sysPass#1484]
Can anyone tell me how to fix this error

 Use of undefined constant LC_MESSAGES - assumed to be 'LC_MESSAGES' (this will throw an Error in a future version of PHP) in C: \ xampp \ htdocs \ systempass \ lib \ SP \ Core \ Language.php

**Comment by nuxsmin** [comment]
Hello, it seems that windows implementation of PHP has some differences with the Linux one, because some constant variables aren't set.

Regards
