### ISSUE TITLE
LDAP Port Problems

### ISSUE THREAD

**Issue by TDPI** [nuxsmin/sysPass#1485]
Hi,

I can not get LDAP to work.
After a long search, I found out that the sysPass ignored my port.

![Config](https://user-images.githubusercontent.com/30598722/67114586-8cde7880-f1dc-11e9-8fed-551c4a0a6139.png)

He is constantly trying over 389.

![error_log](https://user-images.githubusercontent.com/30598722/67114585-8cde7880-f1dc-11e9-86e0-d3688b6a4533.png)

LDAP is running on an Univention, which has samba on Port 389 and OpenLDAP on Port 7389.
I want to use OpenLDAP.

Can you help me with this?

**Comment by nuxsmin** [comment]
Hello, please let me check out the code and I'll be back  with some feedback.

Regards

**Comment by nuxsmin** [comment]
Hello, please, could you strip the protocol from the URI?
