### ISSUE TITLE
Is it possible to export/import into different versions of SysPass?

### ISSUE THREAD

**Issue by anthillinc** [nuxsmin/sysPass#1486]
**sysPass Version**
3.0 (305.19020701)
Config: 300.18111001
App: 300.18072902
DB: 300.18111901

**Describe the question**
We cannot upgrade from 3.0 to 3.1 (see issue we opened here a couple of months ago: https://github.com/nuxsmin/sysPass/issues/1435 )

If we export from 3.0 can we import into a fresh install of 3.1? 

**Screenshots**

**Platform (please complete the following information):**
SERVER_VERSION : 5.7.27-0ubuntu0.18.04.1
CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
SERVER_INFO : Uptime: 7369668 Threads: 1 Questions: 21713303 Slow queries: 0 Opens: 97273 Flush tables: 1 Open tables: 2000 Queries per second avg: 2.946
CONNECTION_STATUS : Localhost via UNIX socket
Name: syspass@localhost

**Additional context**
Version: 7.2.19-0ubuntu0.18.04.2
Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache
Unavailable extensions: ,
Used Memory: 4096 KB
User: vault
Download rate: 43 MB/s
OP Cache
num_cached_scripts : 811
num_cached_keys : 1454
max_cached_keys : 16229
hits : 125314
start_time : 1571394302
last_restart_time : 0
oom_restarts : 0
hash_restarts : 0
manual_restarts : 0
misses : 817
blacklist_misses : 0
blacklist_miss_ratio : 0
opcache_hit_rate : 99.352260744781

Apache/2.4.29 (Ubuntu)

en_US.utf8

**Comment by nuxsmin** [comment]
Hello, unfortunately the current export/import process only process accounts, clients, categories and tags, so it won't fit your need to import the whole data.

Regarding the upgrade issue, it was fixed  in latest commits, so it should work on your environment.

I've been out during a short time, but I'm committed to release any bugfix to get it working.

Regards
