### ISSUE TITLE
Is there a way to grant access to multiple clients

### ISSUE THREAD

**Issue by NEOhidra** [nuxsmin/sysPass#1489]
**sysPass Version**
sysPass 3.1

**Describe the question**
How to grant access to every account of multiple clients to a user?

**Screenshots**

**Platform (please complete the following information):**

**Additional context**
It is possible to assign an account to multiple groups but a user can be part of a single group.
If there is more then one client (every one with multiple accounts) and our team grows - how should a new team member be granted access to just 3 clients?

If every accounts (of a client is assigned to a dedicated group) does it mean that the only way of doing it is to assign the user manually to every singe account?

**Comment by nuxsmin** [comment]
Hello, a user has its primary group, but it could be assigned to multiple groups by setting the users within the group itself.

Regards.
