### ISSUE TITLE
Language translation issue

### ISSUE THREAD

**Issue by joeg1484** [nuxsmin/sysPass#149]
I just upgraded to the latest (1.2.0.06) and I noticed that part of the site is in English and some is in some other language...

Anyway to ensure site remains in English?

Thanks!
Joe

**Comment by nuxsmin** [comment]
It's very strange because it has been tested in some environments without any issue. You can take a look to the demo environment which has been updated to the same version.

Don't miss to check out the user preferences and the global app language.

**Comment by joeg1484** [comment]
Hi nuxsmin,

Ok, after I cleared my browser, it seems to mostly be working... However, in the admin configs, it still shows SI for yes options despite everything else being in English.

I also checked my locale and its set correctly. I attached a screen snip for you to look at. Its a small png file.
![syspass_example1](https://cloud.githubusercontent.com/assets/8363582/10522649/82e35fb6-7333-11e5-8bbf-e42eba999a87.PNG)


Thanks!
Joe

**Comment by nuxsmin** [comment]
Hi, it's a JavaScript cache issue, please clear the browser cache and restart the web server if it's possible, because the app uses the gnu gettext for the translations.

**Comment by joeg1484** [comment]
Ok, I restarted apache and cleared my cache again, but they still say SI - Thats not a big deal as my users dont see that, however, it also shows in the user settings if you select yes... Good thing most everyone knows that SI is Yes :-D.

Anyway, just thought I would report it. The rest of the site seems to be ok now.

Thanks!

**Comment by nuxsmin** [comment]
Ok, let me see what can be happening...that's annoying...

**Comment by nuxsmin** [comment]
Hi, for an strange reason some string weren't being translated because the function that makes the translation was not used. I don't know how his could happen...

The only views that had been affect were at the config tabs.

Thanks for the feedback ;)

**Comment by joeg1484** [comment]
Yes, I updated and now it works as its supposed to... Thanks so much for your help!!!
