### ISSUE TITLE
Issue in Security Documentation

### ISSUE THREAD

**Issue by wendelb** [nuxsmin/sysPass#1495]
Just to let you know, there is an issue in the documentation on this page: https://doc.syspass.org/en/3.1/application/security.html

According to the Apache HTTPd documentation, `FilesMatch` expects a regex. See: https://httpd.apache.org/docs/2.4/de/mod/core.html#filesmatch

In your configuration, the dot is not escaped and therefore matches a single character. Please replace this line here
```
<FilesMatch ".(png|jpg|js|css|ttf|otf|eot|woff|woff2|ico)$">
```

with this one (notice the backslash)
```
<FilesMatch "\.(png|jpg|js|css|ttf|otf|eot|woff|woff2|ico)$">
```

In the new version, the dot is escaped and therefore only matches a dot. The unescaped dot matches every possible character.

**Comment by nuxsmin** [comment]
Sure, you're right. It seems I missed to escape the dot...

Thanks for your contribution!

**Comment by nuxsmin** [comment]
Done!
