### ISSUE TITLE
Dev Branch

### ISSUE THREAD

**Issue by gleisonbaioco** [nuxsmin/sysPass#150]
Hi @nuxsmin,

As you know, I'm trying the dev branch in order to evaluate the new features and the authentication of LDAP users is not working.

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin,

I've tried the new dev branch which fixes the LDAP authentication problem, but the issue has been not resolved yet.

**Comment by nuxsmin** [comment]
Hi @gleisonbaioco,

Can you give me any hints about the issue? Is there any ldap error in the event log?

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin, 

I was trying a LDAP user name "syspass" and receiving the error below. I tried another LDAP user (for example "pwdvault") and the LDAP authentication worked fine. Probably this is due to some conflict regarding the word "syspass".

2015-10-18 17:36:19 	ERROR 	getUserDN 	SYSPASS 	10.158.133.1 	Error on searching user DN User: admin LDAP FILTER: (&(|(samaccountname=admin)(cn=admin)(uid=admin))(|objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)) objectCategory=person))

**Comment by nuxsmin** [comment]
Ok, are those users in the same search base?

In my tests I've used an user named syspass without any issue.

Looking at the event log record it appears that you tried to login with the admin user so it also needs to be in the same base and belong to the filtered group if applies.

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin,

Yes, they are in the same search base. The tool is looking for the admin user although I am using the syspass user (as showed in the error log).

I'll perform more tests in order to get more information about that. The good news is that the tools is authenticating LDAP users.

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin,

I filled out the required properties in the user syspass (such as group, profile and e-mail) and after that the login worked fine.

I think that this issue has been addressed and this ticket can be closed.

**Comment by nuxsmin** [comment]
Great, but this confuses me, because that user has been imported from ldap so those fields should be filled out since first login.

What did happen with the admin user in the ldap filter?

**Comment by gleisonbaioco** [comment]
Initially I didn't specify the LDAP group, as well as default sysPass group and profile because I was analyzing the LDAP configuration options. Due to this the user syspass was imported without these information.

I don't know why the tool was using the user admin in the LDAP search instead of the user syspass. However, after configuring the required properties in the user syspass, its login worked fine and the event log is registering the event correctly, as showed below.

2015-10-18 22:09:29	INFO	Log in	SYSPASS	*.*.*.*	(LDAP)
Login Server: *.*.*.*
User: syspass
Profile: Admin
Group: Admins

**Comment by nuxsmin** [comment]
Ok ;)
