### ISSUE TITLE
Notifications for 'copy.account.pass' and 'show.account.pass' actions

### ISSUE THREAD

**Issue by sebagarayco** [nuxsmin/sysPass#1500]
**It would be a great functionality to allow notifications when a password is viewed or copy.**

This behaviour has been acomplished by sending the logs to logstash and afterwards we have the possibility to send it to telegram or email. It would be great to have that funcionality within the app.

**Comment by nuxsmin** [comment]
Hello,

you can set it on mail settings:

![image](https://user-images.githubusercontent.com/1775774/70869072-5bd5b680-1f87-11ea-837e-c0a8ba77e760.png)

By setting the events for which the notifications will be triggered.

Regards

**Comment by sebagarayco** [comment]
Hi. If you take a look the events for show and copy are not available. I have all the events marked and still not receiving them 

Seba

**Comment by nuxsmin** [comment]
You can add more events though they aren't listed.
