### ISSUE TITLE
Access problem with admin

### ISSUE THREAD

**Issue by rogerrco** [nuxsmin/sysPass#1503]
Hello,

I am trying to login with the admin account on syspass and I was asked for the master password but I don't know the master password. I have server and bank access, what should I do in this case? Email reset was not active. I
![login-syspass](https://user-images.githubusercontent.com/59086589/71251223-7c439f00-2300-11ea-8923-4b04c57f1d2b.PNG)
 am using syspass version 3.

Thank you.

**Comment by nuxsmin** [comment]
Hello, the master password is needed, because it's used to encrypt all the account passwords. Email reset will also require the master password.

Regards.

**Comment by nuxsmin** [comment]
Please follow the guidelines when opening a new issue
