### ISSUE TITLE
Session cannot be initialized

### ISSUE THREAD

**Issue by Somora** [nuxsmin/sysPass#1504]
Hey guys,

I just installed syspass on a WAMP environment.
When trying to navigate to the syspass url i get this:
![2019-12-20 12_33_13-Window](https://user-images.githubusercontent.com/917426/71252523-84fa9c00-2325-11ea-9b3d-9b26d899c1e1.png)
Anyone knows what could be wrong?

**Comment by nuxsmin** [comment]
Hello, could you provide some info about the version? could you provide `syspass.log` file?

Regards

**Comment by nuxsmin** [comment]
Please follow the guidelines when opening a new issue.

**Comment by Somora** [comment]
Hi nuxsmin,

Sorry for not following the guidelines, it's my first time here. I will take note for the future.
These are the versions i am using:

- syspass: 3.1.1.1912160
- Apache: 2.4.39
- PHP: 7.3.5
- MySQL: 5.7.26

I've put the syspass.log in attachment. [syspass.log](https://github.com/nuxsmin/sysPass/files/3998209/syspass.log)

Thanks in advance!

**Comment by nuxsmin** [comment]
Hi, sorry for the late reply...

Unfortunately sysPass wasn't tested on WAMP environment, and it seems to have some issues with locales, so I'd recommend to install it on Linux environments or IIS+PHP, since some behavior could be annoying under WIndows.

Regards.
