### ISSUE TITLE
Language stays Espanol

### ISSUE THREAD

**Issue by CyrosX** [nuxsmin/sysPass#151]
Hello there,
my first point - thanks to nuxsmin for creating such a nice product :)
But! I have a problem! I installed it (the installation was in espanol, is this correct?)
and it seems okay. But when I change the language settings (site wide and / or my personal)
nothing happens. It stays espanol. What is my mistake ?
I'm using debian and followed the wiki!

**Comment by nuxsmin** [comment]
Hi @CyrosX!

I'm glad that you find it useful

About language, sysPass uses GNU gettext for the translations, so you need to have the right locales installed. The English translation is done for en_US locale so it need to be installed on your system.

On Debian like you can issue the command "dpkg-reconfigure locales" and select the en_US.utf-8

**Comment by CyrosX** [comment]
Thanks :+1: 
It worked. Maybe you could do some more marketing for this nice tool.
I referred to it already on t3n! I hope this was okay.

**Comment by nuxsmin** [comment]
Sure, this is a tool developed from the point of view of a sysadmin and I'm very glad that you found it useful.

Thanks so much for your support ;)
