### ISSUE TITLE
Duda SSO en versión 3.1

### ISSUE THREAD

**Issue by davidkast** [nuxsmin/sysPass#1515]
Hola,
una duda, funciona SSO en la versión 3.1? Lo activo en la configuración de sysPass y añado la web en sitios de confianza de la intranet en IE, y no me hace el logon en IE ni en Chrome, mismo resultado en Firefox, habiendo modificado también las opciones de about:config.

Probé a configurar tambien Kerberos SSO con Apache2
https://active-directory-wp.com/docs/Networking/Single_Sign_On/Kerberos_SSO_with_Apache_on_Linux.html y si mismo resultado. Me pueden ayudar?

Gracias.

**Comment by CyrosX** [comment]
My spanish is not that good - but if he's asking how the SSO / Basic Auth part should be configured and what to do to make it work - I would be interested, too! (Using a reverse proxy on Synology to docker container)

**Comment by nuxsmin** [comment]
Hola @davidkast !

El SSO no está implementado para AD (esto es usando Kerberos), y sólo funciona con "Auth Basic", por lo que si llega una cabecera HTTP el tipo "Authentication", ésta será extraída y se podrá acceder a la aplicación con las credenciales de la misma.

Saludos!
---
Hello @CyrosX 

The SSO feature is not implemented for AD (that's using Kerberos), so it only works with "Auth Basic", then if an HTTP "Authentication" header is set before login request, it will be extracted and you will be able to access to the application with the credentials within the header.

Regards
