### ISSUE TITLE
private passwords

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#152]
Is there a possibility to save private passwords so that the system admin also can not see the password?

**Comment by alexanderbuhler** [comment]
I'm wondering about a related case, but it's actually the other way round. How do I make sure the admin has the right to view and edit every entry, even if it's not shared with him or the admin group? (LDAP auth)

When I add myself to the group of the user which created the entry, I can see the name but editing functions are disabled. (I'm using admin profile with all rights enabled).

Any ideas?

**Comment by nuxsmin** [comment]
Hi Alexander,

You have two ways to enable accounts edition to groups:

- by enabling secondary groups edition on the accounts options.
- by setting accounts admin to those users you want to be able.

The profiles options enables selected actions but accounts rights are mandatory.

Hope it helps...

**Comment by alexanderbuhler** [comment]
Hi nuxsmin, thanks for the fast reply. These are the options I already considered while putting up my last question.

Without looking into code very deep I suppose there's a fast way to setup an profile option to enable "admin mode" which sees everything and has the right to edit things - what's your opinion about that?

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta
