### ISSUE TITLE
Logo SVG

### ISSUE THREAD

**Issue by ochorocho** [nuxsmin/sysPass#1520]
Hey,

is there already a SVG logo for sysPass i could use for my Browser addon?

Thanks.

**Comment by nuxsmin** [comment]
Sure, here you have:

[logo_mini_outline_bg.svg.zip](https://github.com/nuxsmin/sysPass/files/4143932/logo_mini_outline_bg.svg.zip)

**Comment by ochorocho** [comment]
Thank you :-)
