### ISSUE TITLE
Backup strategy for 3.1V

### ISSUE THREAD

**Issue by Vandinho** [nuxsmin/sysPass#1521]
I have been using the application for personal use for a few months and I need a backup configuration strategy.
Can anyone advise me the best strategy?
Best Regards

**sysPass Version**
SysPass 3.1

**Platform:**
OS: CentOS Linux release 7.4.1708 (Core)
EC2 AWS Instance

**Comment by nuxsmin** [comment]
Hello, though there isn't any particular strategy about backing up sysPass, a good starting point would be to backup config files and the whole database. If you want business continuity, it would be needed to backup the whole servers, database and application.

There are some guidelines about Docker backup in the documentation: https://syspass-doc.readthedocs.io/en/3.1/application/backup.html

Regards
