### ISSUE TITLE
Master password asked multiple times (on Chrome?)

### ISSUE THREAD

**Issue by aboydude** [nuxsmin/sysPass#1525]
Using Chrome, after entering correct username/password, sysPass ask for re-enter username/password AND master password - _sometimes_. At the same time on Safari I can login at the first try, without entering master password.

I tried with LDAP and local users, both got this message, again: _sometimes_. Not sure how to reproduce, but I use different usernames in the same Chrome window (as in Safari, which works OK).

Found some clue in #1347 and #1106... but I think the Chrome related issue wasn't resolved there.
I didn't change the master password and I only use lowercase usernames.

Any idea how to get rid of this on Chrome?

Expected behavior: do not ask for master password on Chrome.

sysPass Version: 3.1 (310.19081801), using docker image "syspass/syspass:3.1.0-php7.3"
Chrome Version:  79.0.3945.130
OS: MacOs Catalina

Log:
```
[2020-02-04 12:28:31] syspass.EXCEPTION: logger {"message":"Wrong master password
#0 /var/www/html/sysPass/lib/SP/Services/Auth/LoginService.php(180): SP\Services\Auth\LoginService->loadMasterPass()
#1 /var/www/html/sysPass/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/html/sysPass/index.php(28): require(String)","caller":"N/A"}
```

**Comment by astehlik** [comment]
I'm experiencing exactly the same problem. **Sometimes** the users are asked for the master password without any of the documented actions in the FAQ happening (changing password and so on).

What is even more strange: when I skip entering the master password and just try the login one more time it just works.

**Comment by k-s-dean** [comment]
I experience this issue as well, would be good to know what exactly is going on. 

I'm wondering if its something to do with my browser cache or cookies ?

**Comment by 11anthonym** [comment]
Same issue here, seems to work fine on any other browser.

**Comment by kalxasus** [comment]
I have the same issue If use syspass at domain with multipile locations, fo example:

- https://first-domain/syspass
- https://first-domain/site1
- https://first-domain/site2

and at the same time I use domain only for syspass pointed to same container

- https://second-domain/syspass

in this case master password was requested only one time.

All my users that said about this problem used chrome.
I hope it can help determine problem.

**Comment by aboydude** [comment]
> I have the same issue If use syspass at domain with multipile locations, fo example:
> 
> * https://first-domain/syspass
> * https://first-domain/site1
> * https://first-domain/site2
> 
> and at the same time I use domain only for syspass pointed to same container
> 
> * https://second-domain/syspass
> 
> in this case master password was requested only one time.
> 
> All my users that said about this problem used chrome.
> I hope it can help determine problem.
