### ISSUE TITLE
Recover MasterPassword sysPass 1.2

### ISSUE THREAD

**Issue by daveworthley** [nuxsmin/sysPass#1529]
Hey writing here to see if possible to get some help. I came into a client running sysPass 1.2.0.18(I know legacy) however the original Admin deleted the master Password from his records (left on bad terms). I'm trying to recover the master password so I can upgrade and then move this installation. 

Also what are best practice to get 1.2 version to latest. I have latest install on another server so I want to upgrade structure to latest (I guess so 1.2 --> 2.1 -- >3.x)? ) then I can migrate to other server? Or can I just export passwords and import into new version. ? 

I appreciate your help. 

I've been reaching through forums.

So I tried using some 'attached" replaced debug.inc file to show in debug info but it shows me this?

MASTER PASS: 9;#
Then if I inspect the element

<yqn6ga$e< li="">
        </yqn6ga$e<>

But I've tried combinations of that. Maybe I'm typing ti in wrong? Please help.

**Comment by nuxsmin** [comment]
Hello, sorry about that, some people doesn't care about such security risks...

You can either upgrade through the path you stated, that will keep permissions and users, or exporting and then exporting an XML file, which only preserves accounts, categories and clients (customers).

Regarding the master pass, it seems that some kind of HTML scapping is needed but it would be there after applying HTML filters.

Regards

**Comment by daveworthley** [comment]
Thanks for writing back. 
I'm not sure what you mean, how to apply HTML scapping? 
Any chance you can give me some ideas.

**Comment by daveworthley** [comment]
Any chance I can get a little more help with this?

**Comment by daveworthley** [comment]
masterPwd           | $2y$07$c7b4d5c9197faa74699036efb65c62946e3073cc998fab978                                                                             6bdefb198345318$$2y$07$c7b4d5c9197faa7469903ulKMMKdhFdB7UbPXfUH07Bn0zcu08NKy |
| tempmaster_attempts | 26                                                                                                                                                                                                                |
| tempmaster_maxtime  | 1581545628                                                                                                                                                                                                        |
| tempmaster_pass     | a07b8227d661a9e37b004a19af8bb1a9016db4b1104d0444b770d5a9                                                                             761f3c3e                                                                     |
| tempmaster_passhash | $2y$07$9af4c3e1bfa637098ae7fa9ad1c40e9363b0a0cf505690b86                                                                             889a0a6e5fc4969$$2y$07$9af4c3e1bfa637098ae7fOboTQ98m8zfowIF0Wj9mvh/ycxYiIugS |
| tempmaster_passiv   | 590a29279012539a46aa8e77a631f6b833e232930697ce8d1567a788                                                                             cdafe2fa                                                                     |
| tempmaster_passtime | 1581542028                                                                                                                                                                                                        |
| version             | 12018                                                                                                                                                                                                             |

**Comment by daveworthley** [comment]
Any chance for help with this still?

**Comment by daveworthley** [comment]
@nuxsmin Any chance I'll pay for your support.

**Comment by nuxsmin** [comment]
Hello,

please try to edit this file https://github.com/nuxsmin/sysPass/blob/0b8f7760096baa8db8abd9c5d71007944a49a78a/inc/themes/material-blue/debug.inc#L11 and wrap `SP\SessionUtil::getSessionMPass();` with `html_special_chars` function:

```echo html_special_chars(SP\SessionUtil::getSessionMPass();)```

Regards

**Comment by daveworthley** [comment]
Am I typing in the syntax wrong I tried. When I refresh syspass comes up blank. ??
Can you give me full line? 

<li>MASTER PASS: <?php echo html_special_chars(SP\SessionUtil::getSessionMPass();) ?></li>
<li>MASTER PASS: <?php echo htmlspecialchars(SP\SessionUtil::getSessionMPass();) ?></li>

**Comment by daveworthley** [comment]
I don't know what to do and need your help. Would you login via teamviewer with me?

**Comment by nuxsmin** [comment]
sorry, it was wrong: `echo htmlspecialchars(SP\SessionUtil::getSessionMPass());`

**Comment by daveworthley** [comment]
Is it version of PHP not supported that function. No matter how I type it the screen page doesnt refresh. What else can I try??

**Comment by daveworthley** [comment]
So what's super weird is character casing wasn't working either. It was showing everything as lowercase. 
Again thank you so much!!!

This was the master password: 9;#<yqn6GA$e

**Comment by nuxsmin** [comment]
Great!!. Yes you can upgrade (after taking a full backup of the server) to 2.1 and then 3.1. First upgrade could be a pain, since encryption schema was updated and much many improvements in the database layer.
