### ISSUE TITLE
Backup Problems (v1.2)

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#153]
I always get an error if I click on the perform button it says that I should check my log files, but I cannot find anything inside the log files.

**Comment by Goatmaster** [comment]
Does anyone know how to fix this? Maybe I got some problems with the rights of some folders or any php module is missing?

**Comment by nuxsmin** [comment]
Hi, does the backup folder exist? It needs to be created at the app root with the name 'backup'

**Comment by Goatmaster** [comment]
Hi,
yes the folder exists in the main directory of the web server.

**Comment by Goatmaster** [comment]
I changed the permissions of the backup folder to 750 now the backup worked for me!
Where can I import the Backup to another system?

**Comment by nuxsmin** [comment]
Great! You can restore it with the mysql client by issuing the command 'mysql -p < file.sql' take care that if there is another syspass database on the target system it could be deleted if it has the same name.

There is an issue to create a howto about that procedure.

**Comment by Goatmaster** [comment]
Okay I am currently trying to install it on a usb stick. Can you recommand any wamp server for the usb stick that works with the system? I tried UwAmp but its not wokring for me.

**Comment by nuxsmin** [comment]
The last I've used was xampp (about 6 months ago), but there was an issue with the translations, it doesn't work, but despite that is fully functional.

**Comment by Goatmaster** [comment]
I installed xampp on the stick and put the syspass folder into the htdocs folder, but if I try to open the site its empty.

Here is the php log file:
PHP Fatal error:  Class 'SP\Language' not found in D:\xampp\htdocs\sysPass\inc\Init.class.php on line 158

Maybe you got any idea how to fix this.

**Comment by nuxsmin** [comment]
Male sure that the inc/Language.class.php file has been copied to its directory

**Comment by Goatmaster** [comment]
Jep, the file is inside the /inc folder...

**Comment by nuxsmin** [comment]
Let me find out what could be happening, because it's very strange that error.

**Comment by Goatmaster** [comment]
I have done a Backup with the Backup System inside of syspass than I copied everything on the xampp server but it only shows a empty page. And the error I have given above is show in the php logfile.

**Comment by Goatmaster** [comment]
Is it possible that there are some problems with the rights of the folder inside of the xampp folder?

**Comment by nuxsmin** [comment]
It's very strange, because the other classes were loaded, so this one should be loaded. I haven't got time to test it...

**Comment by nuxsmin** [comment]
Hi, can you upgrade to the latest version and replace the "Init.class.php" file by this one https://gist.github.com/nuxsmin/091433f8569af8bf6643?
