### ISSUE TITLE
Syspass not redirecting to index.php

### ISSUE THREAD

**Issue by KadotyGamer** [nuxsmin/sysPass#1531]
**sysPass Version**
3.1 (311.19121601) 

**Describe the question**
After installing the Authenticator plugin, Syspass would no longer go the index.php page to log in. Instead it would go to a blank page and I would have to manually type index.php in the url.

**Screenshots**
![image](https://user-images.githubusercontent.com/19276001/74691293-2aa87b00-51b0-11ea-871c-24a48ccc1611.png)

**Platform (please complete the following information):**
 - OS: Linux
 - OS Version: CentOS 7
 - Browser: Firefox and Chrome

**Comment by nuxsmin** [comment]
Hello, are you installing the right plugin's version?. Is there any message within the log file (`syspass.log`)?

Regards

**Comment by KadotyGamer** [comment]
I installed the plugin for the version of Syspass I have which is 3.1.  I had not checked that log

Cody Knudson
President | MyVariety
cody@myvariety.net | (888) 996-3439 Ext. 001
www.myvariety.net<http://www.myvariety.net>

________________________________
