### ISSUE TITLE
Can't list all users on the LDAP group

### ISSUE THREAD

**Issue by SamuelEduardo84** [nuxsmin/sysPass#1532]
Hi,

I have configured LDAP and successfully connected SyaPass on my Active Directory server.
But when I click on **Check**, I've got only 5 objects and on my group I have 9 users.
So there is 4 users that SysPass can't find on my Active Directory.

Here is my configuration:

![Screenshot from 2020-02-27 15-32-21](https://user-images.githubusercontent.com/45987042/75492592-dd3dc200-5996-11ea-8b7a-01a5f7157ad4.png)

The 5 objects found on the AD **'passadmin'** group:

![Screenshot from 2020-02-27 15-33-29](https://user-images.githubusercontent.com/45987042/75492723-2130c700-5997-11ea-992f-6fd9ae49fb8c.png)

![Screenshot from 2020-02-27 15-07-15](https://user-images.githubusercontent.com/45987042/75492777-36a5f100-5997-11ea-9841-09bbcce183af.png)

The AD user **'syspass'** on **Account Operators** group:

![Screenshot from 2020-02-27 15-24-01](https://user-images.githubusercontent.com/45987042/75492830-59d0a080-5997-11ea-96ee-6eada4d8325e.png)

![Screenshot from 2020-02-27 15-29-55](https://user-images.githubusercontent.com/45987042/75492860-6654f900-5997-11ea-8b4c-316948efd4c9.png)

The AD group **'passadmin'** with the 7 users:

![Screenshot from 2020-02-27 15-23-37](https://user-images.githubusercontent.com/45987042/75493013-bf249180-5997-11ea-9de8-01a8210da9e1.png)

So the users bpinheiro, ljpereira, pcojunior and semartins can't be imported to SysPass. One of these users is my own user.

I'm also attaching my syspass.log and config.json files.

[config.json.txt](https://github.com/nuxsmin/sysPass/files/4264588/config.json.txt)
[syspass.log](https://github.com/nuxsmin/sysPass/files/4264589/syspass.log)

Can you help me with this problem please?

**Comment by nuxsmin** [comment]
Hello, it seems that some attributes aren't set in such users?, could you check if email is set?

Regards

**Comment by pbiggin23** [comment]
@SamuelEduardo84 and @nuxsmin see my last comment on this post

https://github.com/nuxsmin/sysPass/issues/1487

**Comment by daveworthley** [comment]
I had same issue. Change server type to STANDARD instead of ACTIVE DIRECTORY.

**Comment by misterunknown** [comment]
> I had same issue. Change server type to STANDARD instead of ACTIVE DIRECTORY.

Hm, but then you probably get deactivated users too, or not?

**Comment by daveworthley** [comment]
Why would you get de-activated users? Still same userPrincipal, location and group. When I changed it all my users showed up but when it was set to ActiveDirectory it was missing half on a new installation.

**Comment by misterunknown** [comment]
> Why would you get de-activated users?

Because as far as I can tell, there is no filter in the Standard-Ldap-Auth-Provider that checks if the user is activated in AD or not.

**Comment by daveworthley** [comment]
Why keep disabled users in the group? Once they are no longer active remove them from the LDAP group.

**Comment by misterunknown** [comment]
> Why keep disabled users in the group?

There are all sorts of reasons in bigger companies, e.g. parental leave of a employee.

Anyway, the use cases may differ, so the built-in filters should be deactivatable or configurable.

**Comment by SamuelEduardo84** [comment]
> Hello, it seems that some attributes aren't set in such users?, could you check if email is set?
> 
> Regards

Hello.
The email is set to all the users.
There some differences in the ProxyAddress, but nothing that show me some pattern.

There's some special attribute that SysPass looks to list a user?

**Comment by SamuelEduardo84** [comment]
> > I had same issue. Change server type to STANDARD instead of ACTIVE DIRECTORY.
> 
> Hm, but then you probably get deactivated users too, or not?

Great, it works perfectly.
Now all the users can be imported to SysPass.

Thank you very much.

Now there some problems when I'm trying to log with the new users.
I receive the message **User has no associated groups**

![image](https://user-images.githubusercontent.com/45987042/76538525-35c49300-645e-11ea-92e8-7714ab7b2710.png)

But all the users are in a SysPass group called **Users** and in a Profile called **Default User**.
I'm trying to solve that.
