### ISSUE TITLE
Can't bind to AD Server

### ISSUE THREAD

**Issue by IpsumRy** [nuxsmin/sysPass#1534]
**sysPass Version**
3.1 (311.19121601)
Config: 311.19121601
App: 311.19121601
DB: 311.19121601

**Describe the question**
Can't bind to Active Directory server, I followed the LDAP Troubleshooting guide, 
$ /bin/php -r 'phpinfo();' | grep ssl
`
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2
openssl
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
`

openssl s_client -connect myADIP:636
`CONNECTED(00000003)
`

openssl s_client -connect myADIP:389 -tls1_2
`CONNECTED(00000003)
`

ldapsearch -h myADIP -p 389 -b \"dc=redacted,dc=com,dc=mx\" -D \"CN=Adminsitrador,DC=redacted,DC=com,DC=mx\" -W
`Enter LDAP Password:
ldap_bind: Invalid credentials (49)
        additional info: 80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839
`

I also created a specific user for sysPass on the OU of Users and tried and got the same results:
`ldapsearch -x -h myADIP -p 389 -b "dc=redacted,dc=com,dc=mx" -D "CN=syspass,DC=redacted,DC=com,DC=mx" -W
`
`Enter LDAP Password:
ldap_bind: Invalid credentials (49)
        additional info: 80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839
`

Do I need to add extra config to sysPass?

**Platform:**
 - OS: Linux
 - OS Debian 9
 - Browser Chrome

**Additional context**
On another server with another software (Snipe IT) I was able to connect and bind with the same AD Domain Contoller, with similar configuration.
![image](https://user-images.githubusercontent.com/33967580/76560145-277a7500-6466-11ea-8986-7aafcbb1d176.png)

**Comment by IpsumRy** [comment]
I also tried
`
ldapsearch -H ldap://myADIP:389 -W -D "read.only@redacted.com.mx" -b "ou=OCMX,dc=redacted,dc=com,dc=mx"
`

And it was successfull, but when I try to apply the same config to syspass I'm still getting error 49: wrong credentials :/
![image](https://user-images.githubusercontent.com/33967580/76662482-b0b3a980-6543-11ea-8402-bbb5d6e618e1.png)
![image](https://user-images.githubusercontent.com/33967580/76662587-0425f780-6544-11ea-9c3f-80b9b9b87150.png)

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply, I've been so busy....

Could you use the CN of the user instead of the UPN, (or is  it an email?).

Regards
