### ISSUE TITLE
Active Directory Configuration not working after upgrade. 

### ISSUE THREAD

**Issue by jr-RXcode** [nuxsmin/sysPass#1535]
**sysPass Version**
version 3.1
php version 7.3

**Describe the question**
I've been running syspass version 2.1 for a while and decided to upgrade it to the newest release. I followed the documentation on the migration path and update syspass from 2.1 to 3.0 and finally to 3.1. 

Everything seemed ok until I checked the Active directory configuration, after the upgrade i'm unable to communicate with the active directory server. It was working find prior to the upgrade.  I keep getting an error message saying unable to communicate with LDAP server. 

I've created a simple php script to test the connection to the LDAP server and I am able to connect to the Active Directory server when I run the php script

Any help would be really appreciated.

Thanks and keep up the good work. 

 

*Additional context**
In the logs I see the following error message, Not really helpful to me other than it says it can't connect to the server: 

[2020-03-16 19:23:46] syspass.EXCEPTION: logger {"message":"Unable to connect to LDAP server
#0 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(156): SP\Providers\Auth\Ldap\LdapConnection->connectTls()
#1 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(113): SP\Providers\Auth\Ldap\LdapConnection->connect()
#2 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#3 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/Ldap.php(96): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#4 /var/www/html/sysPass/lib/SP/Services/Ldap/LdapCheckService.php(51): SP\Providers\Auth\Ldap\Ldap->factory(Object(SP\Providers\Auth\Ldap\LdapParams),Object(SP\Core\Events\EventDispatcher),Boolean)
#5 /var/www/html/sysPass/app/modules/web/Controllers/ConfigLdapController.php(156): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#6 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#9 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#10 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#11 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#13 /var/www/html/sysPass/index.php(28): require(String)","caller":"N/A"}

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply, I've been so busy....

it seems a network error when connecting, are you connecting using SSL?, are you using an IP address or a hostname?.

Regards

**Comment by jr-RXcode** [comment]
I've tested trying to connect both ways. I also wrote a simple php script that will connect to the AD server and ran it on the server with syspass installed,  that work fine. I'm using an IP address when trying to connect.  Below is the script I tried for troubleshooting.

`$ldapconn=ldap_connect($ldaphost);
if($ldapconn)
   echo "Connect success<br>";
else
   echo "Connect Failure";
ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3);
ldap_set_option($ldapconn, LDAP_OPT_REFERRALS, 0);

//Reference：http://php.net/manual/en/function.ldap-bind.php
if ($ldapconn) {
    // binding to ldap server
    $ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);
    // verify binding
    if ($ldapbind) {
        echo "LDAP bind successful...";
    } else {
        echo "LDAP bind failed...";
    }
}
ldap_close($ldapconn);
?>

`

**Comment by nuxsmin** [comment]
Hmm, but you're using TLS on sysPass counterpart:

` #0 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(156): SP\Providers\Auth\Ldap\LdapConnection->connectTls()`

**Comment by nuxsmin** [comment]
I found a bug when using 'ldaps' scheme and a custom port, because PHP skips the port when schema is used. It was solve in v3.2 (not released yet)

**Comment by jr-RXcode** [comment]
Well for your first question. I tried with and without TLS enabled in syspass and that wasn't working. 
I've also have other services connected to AD and they are working fine, Syspass was fine until I updated to version 3.1

**Comment by nuxsmin** [comment]
Could you switch on debug on sysPass configuration and then capture the log messages? (please tokenize them before sending...)

**Comment by jr-RXcode** [comment]
So I was doing some more investigation. Looks like I was able to sync / update my active directory password with syspass after I changed it in AD so that means syspass is talking to AD. The issue I found was when trying to check the connection using the Check button in the LDAP config section. That seems to be throwing an error when you try to check your LDAP configuration to see if it can connect to AD. I think that's what was throwing me off because it kept saying that it couldn't connect when I clicked on the Check.

**Comment by nuxsmin** [comment]
Ooops, so late, so sorry...

It seems that you aren't entering the LDAP password for checking, because once it's set it won't be available through the UI, so every time you need to check/modify the LDAP params, the password needs to be set. Please notice the warning icon aside the password field.

Regards
