### ISSUE TITLE
duplication of ldap users

### ISSUE THREAD

**Issue by zlodeh** [nuxsmin/sysPass#1540]
**sysPass Version**
sysPass 3.1

**Describe the question**

I would like to thank - many thanks for the syspass. Thank you for such a decision.

I ran into a problem when adding user authorization using ldap. 
Users can log in using the username and username@mail.com with one password.
And these are two different accounts. 
How can I disable logon for use email or unify profiles if they use ldap user and email authentication.?

<img width="872" alt="Screenshot_38" src="https://user-images.githubusercontent.com/16094858/79124315-b69be500-7da4-11ea-9c1d-3894d751f603.png">

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply, I've been so busy....

Hmmm, did you add all of them from LDAP?

Regards

**Comment by zlodeh** [comment]
Yes, users from AD - LDAP authorization.

As I know
sAMAccountName: "login"
userPrincipalName: "login@domain.com"

**Comment by nuxsmin** [comment]
So did you import from LDAP or they were added through login? (LDAP users don't need to be imported, they will be automatically added when logging in)

**Comment by zlodeh** [comment]
I don't use import. 
![Selection_031](https://user-images.githubusercontent.com/16094858/81380998-90a00100-9114-11ea-857e-d9f2083b3667.png)


I will test again and write the result.

**Comment by nuxsmin** [comment]
It seems your users are able to login using the UPN and sAMAccountName so it will create duplicated logins...

**Comment by zlodeh** [comment]
If I will import users and Login Attribute take sAMAccountName - it fixed the duplicate problem?

**Comment by nuxsmin** [comment]
No, LDAP import is a separated process from login, which provides a way for pre-creating the users for role assignment, but if the user logs in with any of both attributes, sysPass will look for the user's login and if not found, it will create a new user with current login.

Does LDAP allow to authenticate using both attributes?
