### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by fbfm** [nuxsmin/sysPass#1542]
There should be plugins for sysPass. But I have never found where? I am also looking for a user description.

**Comment by fbfm** [comment]
There should be plugins for sysPass. But I have never found where? I am also looking for a user description.

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply, I've been so busy....

Unfortunately there is only one plugin (https://github.com/sysPass/plugin-Authenticator). I made an effort to have decent plugin system, but seems that no one is interested...

Regards
