### ISSUE TITLE
Migrate v1.2 to 2.1

### ISSUE THREAD

**Issue by gwendal-tlg** [nuxsmin/sysPass#1543]
Hi everybody,

I've been tasked with updating our syspass. 
It works with a wamp on windows 2012R2, apache 2.4.23, php 5.6.25 and mysql 5.7.14.

My mission is to go up to v3.1 and migrate the database to the new server in Ubuntu. 

My first step, my first block is to go to 2.1.
I have downloaded precisely sysPass-2.1.0.17022601
I copied the config.php, key.pem and pubkey.pem
WAMP starts.
I have a blank page on http://localhost/syspass
The config.php is renamed to -old and the config.xml is created with the current configuration.
The syspass.log brings back theme access errors. No apache error in sight. But I'm reading problems accessing the theme files... I don't understand why. Rights are good.
Also, for the future, impossible to find upgradeKey

I'm not good at this, the syspass hasn't been followed by the same people...

Anyway, if there's anyone who can help me. Thanks in advance :) 

Gwendal.

**Comment by gwendal-tlg** [comment]
Hi,

Good news, i have update page with 2.1.16.18061901 version. But what can i do with 

![update03](https://user-images.githubusercontent.com/64084863/79886958-3efc3480-83fa-11ea-8ad6-f71f23c550d4.PNG)

"error while updating the database" when i start update.

![update05](https://user-images.githubusercontent.com/64084863/79887089-72d75a00-83fa-11ea-982f-9b1cad2aad36.PNG)

Gwendal.

**Comment by gwendal-tlg** [comment]
Hi,

Good news, i have update page with 2.1.16.18061901 version. But what can i do with 

![update03](https://user-images.githubusercontent.com/64084863/79886958-3efc3480-83fa-11ea-8ad6-f71f23c550d4.PNG)

"error while updating the database" when i start update.

![update05](https://user-images.githubusercontent.com/64084863/79887089-72d75a00-83fa-11ea-982f-9b1cad2aad36.PNG)

Gwendal.

**Comment by gwendal-tlg** [comment]
Oups. bad manipulation

Gwendal.

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply, I've been so busy....

It seems you provided an ID for user and group which isn't correct (0).

Regards
