### ISSUE TITLE
syspass.log is not rotated 

### ISSUE THREAD

**Issue by vvascautan** [nuxsmin/sysPass#1545]
In version 3.1 there is new file syspass.log  in config dir, it is not rotated and its size increasing the docroot path. 
-rw-------. 1 apache apache 2460420851 Apr 24 02:33 syspass.log

Is it possible to change the path or recreate it daily/weekly?

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply, I've been so busy....

Unfortunately, and because the nature on PHP, it won't rotate any logs, because it doesn't run as a daemon process, so you would need to rely on cron to perform this task.

Regards.

**Comment by patrice-go-dsi** [comment]
@angelsantillana94 Same for me. Do you find a solution ? Tx

**Comment by simoesp** [comment]
https://linux.die.net/man/8/logrotate use copytruncate if you don't want to restart it will rotate logs it will make a copy of current then truncate the existing one

/var/www/html/sysPass/app/config/syspass.log {
    daily
    rotate 7
    copytruncate
    compress
    missingok
    notifempty
}

EDIT: just found out ur using kubernetes... :-\
