### ISSUE TITLE
Site broken after OS upgrade to Ubuntu 20.04, PHP 7.4 new default on this OS.

### ISSUE THREAD

**Issue by ctetuk** [nuxsmin/sysPass#1547]
**Is your feature request related to a problem? Please describe.**
I have upgraded my OS to Ubuntu 20.04 and did not realise PHP 7.4 was being enforced on this version, older versions are not easily available yet. So I am stuck with "Required PHP version >= 7.0 <= 7.3" and cannot get to any of my passwords :( 

**Describe the solution you'd like**
Could you please add support for PHP 7.4? as Ubuntu are pushing it hard now

**Describe alternatives you've considered**
I've tried looking at installing 7.2 and 7.3 again but they are not offically available yet.

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply, I've been so busy....

Unfortunately PHP 7.4 hasn't been already tested on sysPass 3.1, so it would be a risk to enable it without any test. Noted down for next release.

Regards
