### ISSUE TITLE
Upgrade 1.2 -- > Latestest

### ISSUE THREAD

**Issue by daveworthley** [nuxsmin/sysPass#1548]
**sysPass Version**
sysPass-1.2.0.21

Current system is installed on CENTOS7. 

I am trying to upgrade from version 1.2.0.21 to 2.x then to 3.x. 
I eventaully want to move this to a XAMPP Windows system but that's a different issue. 
No matter what version or I try to do when I want to upgrade I get HTTP 500 error

1. Rename current syspass Installation to syspass_old
2. Upload new files
3. Copy old config directory to new install
4. Set permissions

When I try to navigate it gives me Http 500 error, if I remove the config it prompts for new installed. I've tried half dozen different versions and can't upgrade and stuck on version 1.x. Would this be caused by PHP version?

I've also tried this on Windows XAMPP and same results. 
I would appreciate your help with this. 

Not sure what I'm doing wrong here? I've tried everything. 

Also I'm confused, what if I just want to export all accounts and stuff and import into a new 3.x installation. When I try to export it says Internal Server Errorerror

Thank you.

**Comment by daveworthley** [comment]
So I'm not sure why this project has turned into several frustrating hours and hours. I'm having trouble updating still .

I did new OS install on Windows with WAMP. I tried 10 different Syspass versions and none come up or 500 error. 

Finally version 2.1.16.18061901 comes up with asking to upgrade. 
I have no idea what this means, and no matter what I put it still doesn't work. 

![image](https://user-images.githubusercontent.com/61018283/81455105-2ca12b00-915c-11ea-9c90-0a41638b3ad7.png)

It asks if I want to upgrade then I get this

![image](https://user-images.githubusercontent.com/61018283/81455190-7db11f00-915c-11ea-9039-55364ee70f48.png)

I've tried everything I know. This is super frustrating and could really use some help. 

Here is the log file
[syspass.log](https://github.com/nuxsmin/sysPass/files/4602072/syspass.log)

**Comment by nuxsmin** [comment]
Hmmm, could you provide the result from this SQL query?: `SELECT config_value FROM config WHERE config_parameter = 'version'`

I'm wondering why it's asking to apply the v1.10 upgrade while it's already in v1.21

**Comment by nuxsmin** [comment]
You are upgrading to v2.1, aren't you?

**Comment by daveworthley** [comment]
Yeah i'm trying to upgrade to 2.1  then 3.x to stay current. 
I've tried so many different things. I couldn't get any version to load except the one above. Every version in the 2.x range would give me 500 page error and page would never load. 

Here is the result: 12018
I was on 1.20.18 and when I installed 1.2.0.21 it didn't ask to do any kind of update or anything it just opened up and worked. 

Thank you so much for your help. I do like your project and I really want to get current. 
Also what is the orphaned things means above?

**Comment by nuxsmin** [comment]
>  I've tried so many different things. I couldn't get any version to load except the one above. Every version in the 2.x range would give me 500 page error and page would never load.

Hmm, so you managed to upgrade from v1.2 to v2.1?

>  I was on 1.20.18 and when I installed 1.2.0.21 it didn't ask to do any kind of update or anything it just opened up and worked.

Yes, that is the expected behavior, since only upgrades which need to modify the database, will ask for the upgrade code or any question related to database items.

>  Also what is the orphaned things means above?
These are some items which weren't linked by database constraints, so they need to be linked in order to get managed by the database, since they enforce the consistency of the data (eg. you won't be able to remove an user if it's linked to an account).

So you glad you found sysPass useful :slightly_smiling_face:

**Comment by daveworthley** [comment]
No I meant load as in actually show a page come up and ask for the upgrade page. I'm stuck in 1.2.0.21 version. 

Still can't upgrade. 

Yes but what ID would I put there (I tried any number and still get database error)
Every other version would just say 500 error when I navigated to index page.

**Comment by nuxsmin** [comment]
Okay, could you replace the value from the database to `1201800000`?

**Comment by nuxsmin** [comment]
An then rerun the upgrade again?

**Comment by nuxsmin** [comment]
Aside: early versions were a mess, so I decided to drastically improve the base code, that's because of these upgrades. Recent versions (from 2.1) are so smooth when upgrading, despite of some architectural changes needed to be done in order to improve the code maintainability...

**Comment by daveworthley** [comment]
When I change value I am then prompted with this. 
Even If I change it back still given this

![image](https://user-images.githubusercontent.com/61018283/81474594-93fac180-91d4-11ea-8c25-80551bc19665.png)

**Comment by daveworthley** [comment]
BANG!!. Once again, thank you for all your help. Look and feel def different in version 3.x, need sometime to get used to. !!!

What happened to the orphaned items above? Should I be worried about that? 

So you are correct once upgrade finished from version 1.x to 2.x (which took about 10-12 mins) It's on a test box so maybe slower. Version 2.x to latest 3 took like 5 seconds. 

Thanks again for your help and congrats on the continued project. 

![image](https://user-images.githubusercontent.com/61018283/81475067-b8a46880-91d7-11ea-92ee-12e9377eeb10.png)

**Comment by nuxsmin** [comment]
So great!! You did managed to get v3.1 up an running!!

> What happened to the orphaned items above? Should I be worried about that?

The user and group id of these items were set to the given during the upgrade (usually id=1), so the admin user (isn't it?), will be the owner of these items.

> One last question also, since I'm running this on WAMP (windows version) I got an error for version 3 on start about LC_MESSAGES and when I goto into I see this

WAMP, not so much testing on there, but I think I will run fine, despite some annoying messages...Such message means that locale wasn't set, so you won't be able to change the language, so does not matter if you keep on English :)

> So you are correct once upgrade finished from version 1.x to 2.x (which took about 10-12 mins) It's on a test box so maybe slower. Version 2.x to latest 3 took like 5 seconds.

It's so because from v1 to v2 it had to re-encrypt all the passwords, so it would've take about 1,5-2,5 passwords per second on average computer

> P.S. I know it's a lot to give support especially on a free project, so greatly appreciate your help, support and time.

Really grateful, It's so hard to take some time to code and support

**Comment by nuxsmin** [comment]
> Anyway to hide top line or make it all one line?
 Upper line would be dynamic, since many icons would appear depending on the account properties. 

Anyway, you can **clone** and then modify the theme to fit your needs. By cloning you won't need to be worried about future changes to the base theme, but you would need to keep on sync with the original to not miss any new feature

**Comment by daveworthley** [comment]
I understand. Any chance you know quick and dirty hack to make it all one line instead of 2? 
Thanks again. I am very grateful.

**Comment by nuxsmin** [comment]
> Any chance you know quick and dirty hack to make it all one line instead of 2?

Not actually, but there are some more stuff that need to be on the second line: tags.

**Comment by nuxsmin** [comment]
![image](https://user-images.githubusercontent.com/1775774/81475744-4e5aea80-920e-11ea-93b8-3ec2223d21b9.png)

**Comment by daveworthley** [comment]
I mean the action items as one line. (like attachments, favorite with same line as view password. It's not a big deal. You've helped me and I really appreciate it. Thanks for your time in getting me up and running.

**Comment by nuxsmin** [comment]
> I mean the action items as one line. (like attachments, favorite with same line as view password. It's not a big deal. You've helped me and I really appreciate it. Thanks for your time in getting me up and running.

Sure, sorry I didn't catch you up, you can change it on user's preferences

:wink:

**Comment by daveworthley** [comment]
Really? I must of missed that? which setting?

**Comment by nuxsmin** [comment]
Isn't it the first one?

![image](https://user-images.githubusercontent.com/1775774/81479938-b61d2f80-9226-11ea-878a-34c8ae96cfc5.png)
