### ISSUE TITLE
RE: Change Background of Login Page and Stop/Remove the redirect links at bottom of page

### ISSUE THREAD

**Issue by Fuquan999** [nuxsmin/sysPass#1551]
**sysPass Version**
3.1
We are about to put it to the test but it looks like a very useful application and well developed as we can see so far...but we shall feedback when we put it to good use.

**Describe the question**
QUICK QUESTIONS:
Q1: Where can we change the Background of the login page (I see it is possible as your demo https://www.syspass.org/en has a crush paper background image. If you could direct me as to where to make this change that would be appreciated

Q2:  At the "bottom Right" of the Login page there are two redirect links which are a bit too intrusive (as we do not mind the text/wording being there but "redirecting" our team that unfortunately is causing some concern) so if you could guide us as to where to remove the redirect links that would be helpful.

Like we said the wording being there is fine by us but the "linking" is the concern as it links to these two sites which is a bit intrusive. Thus, we should appreciate removing the actual "links" as the text can stay.

https://cygnux.org/
https://www.syspass.org/en

Thanks
Fuquan

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply.

Default theme can be changed by cloning (`app/modules/web/themes/material-blue`) it and then modify it to fit your needs. Please be aware to not modify the default theme, since future updates would overwrite your changes.

Regards

**Comment by Fuquan999** [comment]
Thanks a lot as better late than never.
