### ISSUE TITLE
please  make it work with php 7.4

### ISSUE THREAD

**Issue by bhu73** [nuxsmin/sysPass#1552]
or at least update the documentation  from PHP >= 7.0 to  PHP < 7.4 !

**Comment by nuxsmin** [comment]
Hello, I'm testing sysPass with PHP 7.4, so it would be ready for next release.

Thanks for the feedback!

**Comment by vatanparvar** [comment]
Can I kindly ask when the next release will be out? I lost my SysPass after upgrading to Ubuntu 20.04 which was 2-3 months ago.
Thanks :-)

**Comment by pajtai** [comment]
Any update on this? 7.3 only has active support until 6 Dec 2020, and then it's security fixes only for a year before EOL.

https://www.php.net/supported-versions.php

**Comment by nuxsmin** [comment]
Hello,

sorry for the delay. sysPass will be tested with PHP 7.4, so hopefully it will be available soon.

Regards

**Comment by nuxsmin** [comment]
Done 😉
