### ISSUE TITLE
'/app/config' directory permissions are wrong

### ISSUE THREAD

**Issue by computergott** [nuxsmin/sysPass#1553]
**sysPass Version**
3.1.2

**Describe the question**
Hey there! - I want to install Syspass on my Server. When I open the install page i get an "'/app/config' directory permissions are wrong"-Error.

The Permissions for the config-folder:
drwxrwxr-x  2 www-data www-data 4096 Mai 26 10:47 config

**Platform (please complete the following information):**
 - OS: Debian 9
 - Browser: all

**Additional context**

Greetings!

**Comment by nuxsmin** [comment]
Hello, please set the correct permissions as described in the error message.

Regards
