### ISSUE TITLE
Special characters in generated passwords

### ISSUE THREAD

**Issue by sq5gvm** [nuxsmin/sysPass#1556]
I don't think sysPass password generator special characters should include characters not available on most commonly used keyboard layouts. At this moment in app-util.js special characters definition include such characters as ¿¡· (ASCII codes 191, 161 and 183 dec).
Unfortunately copy & paste is not always possible also it's problematic when using devices like inputstick.

https://github.com/nuxsmin/sysPass/blob/8f78ad5b3541947b07bf0bddaecd01ec7de73837/public/js/app-util.js#L362

**Comment by k-s-dean** [comment]
I have also run into this issue in the past. 

I now just use pwgen on the linux command line to generate passwords.

I would say that those symbols should be removed.

**Comment by Yotouille** [comment]
linked to: https://github.com/nuxsmin/sysPass/issues/1197

**Comment by nuxsmin** [comment]
Hello, it will be improved in next release.

Thanks for the feedback!
