### ISSUE TITLE
LDAP is OK found 0

### ISSUE THREAD

**Issue by aszhitarev** [nuxsmin/sysPass#1558]
**sysPass Version**
3.1 (312.20030701)
Config: 312.20030701
App: 312.20030701
DB: 312.20030701

**Describe the bug**
I'm trying to importt LDAP users. On test LDAP connections - LDAP connection ok
but Found 0 objects

**Platform (please complete the following information):**
OS - Windows
webserver - XAMPP
Ldap server - windows 2008 AD
Browser - Google Chrome

**Comment by divoto** [comment]
Same result here
