### ISSUE TITLE
LDAP  log does not contain enough data

### ISSUE THREAD

**Issue by tsener** [nuxsmin/sysPass#156]
It is very hard to debug  a 'connection failed' error without  additional data;
I do not have access to the LDAP (which is MS AD)

**Comment by nuxsmin** [comment]
It should be more info about the error in the event log. All LDAP errors are logged with their error code and description

**Comment by tsener** [comment]
What I really meant  is  perhaps having a checkbox to enable 
ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
somewhere in the ldap.class.php   perhaps ?
Logs much more detailed data from the ldap communication..

fyi I am trying to get it to run  with Microsoft AD without any success whatsoever.
I will open another issue with details for this, but perhaps this debug checkbox could become a feature request ?

Regards,
Tsener

**Comment by nuxsmin** [comment]
Hi, don't worry about to open an issue,you can tell me what errors you get, or some more info about your environment.

About the FR don't care about that, I can code it for the next build.

Kind regards.

**Comment by nuxsmin** [comment]
Hi, I've implemented that LDAP option in the latest commit...hope it helps to find out what is wrong.

**Comment by nuxsmin** [comment]
Did you find out what could be happening?
