### ISSUE TITLE
Attempts exceeded applies for all users if someone failed to login for 5 times 

### ISSUE THREAD

**Issue by orest-gulman** [nuxsmin/sysPass#1560]
**sysPass Version**
3.1.2 (docker)

**Describe the bug**
I've set up a local admin users and also LDAP, if someone is failed to login for 5 times, all others can't log in with message **Attempts exceeded**, even local users.

**To Reproduce**
Try to login with the wrong password for 5 times using any AD user, then switch for another (AD, local) user and will get a message **Attempts exceeded**

**Expected behavior**
I've expect to block only specific user, who is failed to login.

**Comment by nuxsmin** [comment]
Hello,

sysPass tracking mechanism uses the client source IP address unless requests are proxied through a proxy, so in that case it will try to guess the original IP address by looking for `HTTP_FORWARDED` or `HTTP_X_FORWARDED_FOR` headers.

Regards

**Comment by nuxsmin** [comment]
Hi, unfortunately it isn't possible. Could you set the `HTTP_FORWARDED` header within Nginx?

**Comment by orest-gulman** [comment]
I have it, did I missed something?

`user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log  /var/log/nginx/access.log;
    charset   utf-8;
    keepalive_timeout  65;
    server_tokens       off;
    tcp_nopush          on;
    tcp_nodelay         off;


    server {

        listen 80;
        return 301 https://$host$request_uri;
    }

    server {

        listen 443 ssl;
        server_name syspass.euroware.it;

        ssl_certificate /etc/nginx/syspass.pem;     # server.crt
        ssl_certificate_key /etc/nginx/syspass.key;

        ssl_session_cache   shared:SSL:20m;
        ssl_session_timeout 20m;
        client_max_body_size 100m;
        ssl_protocols TLSv1.2 TLSv1.1 TLSv1;

        access_log /var/log/nginx/syspass_ssl_access.log;
        error_log /var/log/nginx/syspass_ssl_error.log;

     location / {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_pass          https://syspass-app;
        proxy_read_timeout  90;
     }
}
}`

**Comment by nuxsmin** [comment]
Hmmm, it seems that you're setting the `X-Forwarded-For ` header to the upstream proxy, so if the client does connect directly through the Nginx it won't be set. The useful header would be `X-Real-IP` but sysPas isn't looking for this one...

**Comment by nuxsmin** [comment]
This post could be useful: https://stackoverflow.com/questions/29279084/nginx-proxy-add-x-forwarded-for-and-real-ip-header

**Comment by orest-gulman** [comment]
could you please provide an example of the correct Nginx configuration for sysPass. Thanks

**Comment by nuxsmin** [comment]
sysPass will look for an "X-Forwarded-For" header so your Nginx config should look like:

```
location / {
...
 proxy_set_header        X-Forwarded-For $remote_addr;
...
}
```
