### ISSUE TITLE
import accounts max file size

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#1562]
Hey,

I tried to import accounts to a new syspass installation. The file size is about 3mb. I get an error that the file is to big. It says max is 1024.

Is there a workaround for that problem.

**Comment by vmario89** [comment]
i guess you will need to adjust your basic php.ini settings to allow larger upload files
upload_max_filesize = <integer>M
post_max_size = <integer>M

**Comment by Goatmaster** [comment]
I already tried this, but it was not working.

**Comment by nuxsmin** [comment]
Hello, it seems to be related to your PHP configuration, since sysPass only display the current settings from PHP.

Regards

**Comment by Goatmaster** [comment]
I set the following for both but it didn't work. Got the same error with the same size mentioned.

```
upload_max_filesize = 9999M
post_max_filesize = 9999M
```

I am running nginx but there I also increased the client_max_body_size.

**Comment by nuxsmin** [comment]
Hmm, did you set the max. file size in accounts configuration?

![image](https://user-images.githubusercontent.com/1775774/86018563-d2b73600-ba25-11ea-8bc3-387372d38e6a.png)

**Comment by Goatmaster** [comment]
That was the solution now I don't get the size error.

But I got another problem now. It loads the file but when the loading circle is gone nothing happens. It looks like it's finished but there are no accounts imported.

**Comment by nuxsmin** [comment]
@Goatmaster what kind of import are you performing?
