### ISSUE TITLE
Move into sysPass organization?

### ISSUE THREAD

**Issue by Neustradamus** [nuxsmin/sysPass#1566]
Can you move into https://github.com/sysPass?

**Comment by nuxsmin** [comment]
Hello, I was tackling with this question from a long time ago, and honestly I'm wondering what are the benefits of an organization when there are a few PRs in a year and not so much people contributing to solve issues. I think it's the way to a more collaborative project and to say others "hey, we're open to contributions", but I'm an OSS advocate and every contribution is welcome, so would you give me some advice about GH organizations?. Please note that sysPass org was created about a year ago and no one asked me to join, so it was a bit disappointing.

Thanks!

**Comment by nuxsmin** [comment]
https://zach.codes/pros-of-using-github-organizations/

**Comment by Neustradamus** [comment]
Other repositories are already in this organization ;)
Time to have all in one place ^^

**Comment by nuxsmin** [comment]
Please, elaborate

**Comment by Neustradamus** [comment]
There are already here:
- https://github.com/sysPass

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by nuxsmin** [comment]
Cool!

**Comment by Neustradamus** [comment]
Why it is closed?

**Comment by nuxsmin** [comment]
https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by Neustradamus** [comment]
But the migration has not been done, can you reopen it?

**Comment by Neustradamus** [comment]
@nuxsmin: After several months, when do you do it?

**Comment by Neustradamus** [comment]
@nuxsmin: Why to have this repo here and others into @sysPass organization?

No harmonization :/
