### ISSUE TITLE
Installation on Windows 10 and WAMP

### ISSUE THREAD

**Issue by sikas89** [nuxsmin/sysPass#1567]
**sysPass Version**
Can be found on `Config -> Information` tab
sysPass-3.1.2.20030701

**Describe the question**
A clear and concise description.
i'm trying to install on a Windows 10 and WAMP Server, however, I can't find any guide, and running the index.php throws errors

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/17160524/86113107-1616b080-bac9-11ea-98f4-758905728b89.png)

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android] Windows 10 and WAMP Server
 - OS Version 1909
 - Browser [e.g. Firefox, Chrome] Firefox

**Additional context**

**Comment by sikas89** [comment]
Hello @nuxsmin 

It seems that I missed the vendors.tar.gz file. However, when I downloaded it, it still gives errors and warnings:

![image](https://user-images.githubusercontent.com/17160524/86511843-2bf3e080-bdfd-11ea-8143-e1ff83b66efc.png)

**Comment by nuxsmin** [comment]
Hello,

it seems you're using an incorrect PHP version.

Regards

PS: sorry for the late reply

**Comment by Dsaamorim** [comment]
Please i need help. 

I am unable to install Syspass 3.2.4 , I have no idea how to do this.
I'm using Windows 10 and WampServer
I put the file inside the "www" but it displays the same error above the tables... But I've already tested it with all versions of PHP and nothing, can anyone help me?
