### ISSUE TITLE
0 Objects AD

### ISSUE THREAD

**Issue by CyrosX** [nuxsmin/sysPass#157]
Hello there :)
My question is:
I've connected our MS AD with sysPass but it shows 0 Objects found.
I've used "cn=Users,dc=XXX,dc=local" for the last to fields (group and searchbase?)
Is this wrong?

**Comment by nuxsmin** [comment]
Hi!

You need to use the group name to filter the users that can log in. A blank field means that no group filtering will be done.

The group and the users should be within the search base tree.

**Comment by CyrosX** [comment]
Ok, it worked after I cleared the group field and synced the hosting servers Time&Date through ntp with our AD. Maybe the combination is the solution. Thanks :)

**Comment by CyrosX** [comment]
Maybe it is normal but: shall new LDAP users always be inactive at the beginning?

**Comment by nuxsmin** [comment]
Sure, you need to leave unset the default group or profile.

**Comment by CyrosX** [comment]
Mh, so how can I make an LDAP account active from the beginning - the first login?

**Comment by nuxsmin** [comment]
Actually by setting the default group and profile:

A piece of code when creating a user from ldap:

$data['isDisabled'] = ($groupId && $profileId);

**Comment by CyrosX** [comment]
I've set the default group and profile. But it's not working :-/. Maybe because I named them both SUser?

**Comment by nuxsmin** [comment]
Don't worry about the name, the id is used internally instead.

Let me check what could be happening

**Comment by CyrosX** [comment]
![ohne titel](https://cloud.githubusercontent.com/assets/15161462/10686680/c4eca730-7966-11e5-8286-a62f72493ef5.jpg)
Hm, I've updated to the newest version. But it does not seem to work :/ 
I attached a screenshot maybe it is better to see how I've configured it.
