### ISSUE TITLE
LDAP user, changed AD username, won't change in syspass

### ISSUE THREAD

**Issue by execcr** [nuxsmin/sysPass#1571]
Hi,
i have an user called marketing@contoso.local on AD that we had changed the username  to name.surname@contoso.local.
But now in syspass it keep show as marketing@contoso.local. I cannot login as old username or new username as well.
I've tried to reload and re-doint the LDAP configuration to try to update the username but it doesn't work.

Any hint?

**Comment by CodeNinja1337** [comment]
Looks related to https://github.com/nuxsmin/sysPass/issues/1575

**Comment by nuxsmin** [comment]
Hello,

@execcr could you please provide some messages form the log?

Regards
