### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by sikas89** [nuxsmin/sysPass#1572]
**sysPass Version**
Can be found on `Config -> Information` tab

Latest Version Downloaded

**Describe the question**
A clear and concise description.

Created a dedicated VM using Linux Ubuntu 20.04, followed the installation instructions for Debian from [https://syspass-doc.readthedocs.io/en/3.1/installing/debian9.html](URL) .. After finishing the installation steps, it didn't work giving the error:

> Unable to write in file (/var/www/html/syspass/app/config/config.xml)

**Screenshots**

No screenshot. Only mentioned text above.

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android] ==> Linux Ubuntu
 - OS Version ==> 20.04
 - Browser [e.g. Firefox, Chrome] ==> Firefox

**Additional context**

**Comment by luberti** [comment]
Same issue here.
CentOS 7 
Syspass version 3.1.2

Followed instructions in 
https://syspass-doc.readthedocs.io/en/3.1/installing/centos7.html#

**Comment by nuxsmin** [comment]
Hello, 

@sikas89 @luberti it seems to be related to Selinux policies. could you please check it out?

Regards

**Comment by sikas89** [comment]
@nuxsmin I have removed the VM a while ago .. I'm deplying on a new VM using Ubuntu 16.04

syspass@syspass:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

Will tell you about the outcome.

**Comment by sikas89** [comment]
@nuxsmin Okay, so I deployed a new VM using the version mentioned above. I have the same issue.

> Unable to write in file (/var/www/html/syspass/app/config/config.xml)


I checked the SELinux, it is not installed on this version. Installed it `sudo apt install policycoreutils selinux-utils selinux-basics` , and ensured it was disabled

`syspass@syspass:/etc/selinux$ sestatus
SELinux status:                 disabled`

Also, checked the AppArmor, since it is installed by default, confirmed it is stopped, and removed from boot

`syspass@syspass:/etc/selinux$ sudo /etc/init.d/apparmor stop
[ ok ] Stopping apparmor (via systemctl): apparmor.service.
syspass@syspass:/etc/selinux$ sudo update-rc.d -f apparmor remove`

Rebooted the machine, still the same. Appreciate if you take a look and advise what the issue. I will also clone the VM and try upgrading it to a newer release and see ..

**Comment by sikas89** [comment]
@nuxsmin Okay, seems that I have been able to resolve this issue. It seems that the installation of Apache is done with a different user than the one I created for the VM.

So, I have done the below:

1. Identify the User

>syspass@syspass:~$ ps -aux | grep -i apache
>root         919  0.0  1.8 153920 36312 ?        Ss   12:17   0:00 /usr/sbin/apache2 -k start
>**www-data**     970  0.0  1.2 154824 25100 ?        S    12:18   0:00 /usr/sbin/apache2 -k start
>**www-data**     971  0.0  1.3 154956 27732 ?        S    12:18   0:00 /usr/sbin/apache2 -k start
>**www-data**     972  0.0  1.2 154884 25876 ?        S    12:18   0:00 /usr/sbin/apache2 -k start
>**www-data**     973  0.0  1.1 154852 22804 ?        S    12:18   0:00 /usr/sbin/apache2 -k start
>**www-data**     974  0.0  1.3 154820 26960 ?        S    12:18   0:00 /usr/sbin/apache2 -k start
>**www-data**    2574  0.0  1.2 154944 24260 ?        S    12:22   0:00 /usr/sbin/apache2 -k start
>**www-data**    2772  0.0  0.6 154184 13716 ?        S    12:29   0:00 /usr/sbin/apache2 -k start
>**www-data**    2773  0.0  0.6 154184 13716 ?        S    12:29   0:00 /usr/sbin/apache2 -k start
>**www-data**    2774  0.0  0.6 154184 13716 ?        S    12:29   0:00 /usr/sbin/apache2 -k start

Take note of the user in **bold**

2. Change the directory owner to the user running the process

>sudo chown -R www-data /var/www/html

This seems to have solved the issue. Now upon installing, didn't find a DBMS Engine installed. So, installing it on a VM for testing purpose before deploying in a production network for further use.

Seems that the deployment guide needs some enhancements.

**Comment by sikas89** [comment]
Some missing steps from the deployment guide:

1. Change HTML Folder to the Apache Service Owner
2. Install the MariaDB
3. Configure the MariaDB

>sudo apt install mariadb-server
>sudo mysql_secure_installation
>sudo mariadb
>CREATE USER 'USERNAME'@'HOST' IDENTIFIED BY 'PASSWORD';
>GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'USERNAME'@'HOST' WITH >GRANT OPTION;
