### ISSUE TITLE
Redirect to login page fails when running behind a reverse proxy

### ISSUE THREAD

**Issue by fago** [nuxsmin/sysPass#1573]
**sysPass Version**
3.1 (312.20030701)
Config: 300.18111001
App: 312.20030701
DB: 310.19042701 

**Describe the bug**
I'm running Syspass behind a reverse proxy (traefik). I've set the application url in the configuration to "https://myurl.com". Generally, login, redirects, and using the application works as it should, with one exception: When https://myurl.com/index.php is accessed the resulting redirect appends a bogus port 80 to the URL and the redirect fails:

```
curl -I https://myurl.com/index.php
HTTP/2 302 
cache-control: no-store, no-cache, must-revalidate
content-type: text/html; charset=UTF-8
date: Wed, 22 Jul 2020 13:39:26 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
location: https://myurl.com:80/index.php
location: index.php?r=login
pragma: no-cache
server: Apache/2.4.25 (Debian)
set-cookie: PHPSESSID=removed; path=/; HttpOnly
x-powered-by: PHP/7.3.15

```
**Expected behavior**
The redirect may not include port 80, since the application is running on default port 443 (https).

**Event log**
No related entries.

**Platform (please complete the following information):**
 - OS: Linux, using the latest docker image.

**Comment by fago** [comment]
I was able to work-a-round it by simply changing
https://github.com/nuxsmin/sysPass/blob/6197c52af128b1aab48af5f5990c73279495617f/app/modules/web/Controllers/IndexController.php#L49
to
```
        ) {
            header('Location: /index.php?r=login');
            exit();
```
However, I've no idea why the router response is adding the port 80 in this scenario while it's not doing that for other redirects.

**Comment by nuxsmin** [comment]
Hello,

this behavior can be skipped by setting the URL base for the application, since sysPass will only check the HTTP packet (which comes from a reverse proxy connecting to port 80) and not the browser URL instead.

Regards

PS: sorry for the late reply
