### ISSUE TITLE
Add new entries to the "Security Audit" tab

### ISSUE THREAD

**Issue by lucasgrelaud** [nuxsmin/sysPass#1576]
**Is your feature request related to a problem? Please describe.**
Not linked to any issue.

**Describe the solution you'd like**
I would like to know if it is possible to add new items to the "security audit" tab.
The desired items would be : 
 - First logon of a new user (LDAP / internal)
 - Log entry for each password viewed [username, viewed password, timestamp] (already available in syslog if i'm right)
 - Show the username of user when logged with LDAP.

Thanks a lot for this awesome tool !

**Comment by nuxsmin** [comment]
Hello,

such kind of data can be saved in the application log (UI and FS), so is there any reason to duplicate it?

Regards

PS: sorry for the late reply

**Comment by lucasgrelaud** [comment]
Hello back,

You gave me an information that I did not knew : these log entries can be displayed in the "Log" section

I thought they were only available through the sysPass log files, which are not very practical for quick review.

I guess my request does not makes any sense with these informations, i'll have to try it.
Thanks for the reply
