### ISSUE TITLE
Multiple php errors during account creations and edits

### ISSUE THREAD

**Issue by systemcon** [nuxsmin/sysPass#1579]
**sysPass Version**
312.20030701

**Describe the question**
NGINX and syspass gui throws some errors. From nginx error log seems to be php related errors

**Screenshots**
https://imgur.com/a/EVmTzI0

**Platform (please complete the following information):**
 - OS: Ubuntu Server
 - OS Version: 20.04
 - Browser Firefox latest

**Additional context**
Nginx Error Log:

`ge: [INFO] [Loaded actions cache] SP\Core\Acl\Actions::loadCachePHP message: [EXCEPTION] [Invalid Action
#0 /var/www/censored/html/app/modules/web/Controllers/AccountController.php(392): SP\Modules\Web\Controllers\ControllerBase->checkSecurityToken(String,Object(SP\Http\Request))
#1 [internal function]: SP\Modules\Web\Controllers\AccountController->editAction(Integer)
#2 /var/www/censored/html/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#4 /var/www/censored/html/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/censored/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback" while reading response header from upstream, client: censored, server: censored, request: "GET /index.php?r=account/edit/16&isAjax=1&sk=99ec422d6c4c71389b7b9f01335353c195a6d205&_=1596655316831 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "censored", referrer: "https://censored/index.php?r=index"

`

**Comment by systemcon** [comment]
the above error happened while i tried to create a new account, it seems to me complely random these errors, i can't find any pattern, i may receive the same error as the screenshot when i press to edit an account. I have enabled the session encryption if it related somehow.

**Comment by nuxsmin** [comment]
Hello,

it might be related to #1312
