### ISSUE TITLE
Error while copying password to clipboard

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#158]
I get an error if I try to copy a password to the clipboard. Do I need to set some extra rights on any folder?

**Comment by nuxsmin** [comment]
What error do you get?. Clipboard does not require any special rights.

**Comment by nuxsmin** [comment]
Which browser are you using?

**Comment by Goatmaster** [comment]
I use firefox.

**Comment by sebastiantiede** [comment]
same for me 
Firefox 42 on OS X

**Comment by nuxsmin** [comment]
Can you try the latest build?. The Clipboard.js plugin has been updated.

**Comment by nuxsmin** [comment]
Do you have any update?

**Comment by sebastiantiede** [comment]
sorry for my delayed reply. 
it works with the latest build.
thanks

**Comment by nuxsmin** [comment]
Great!

**Comment by dsv591** [comment]
I'm having this issue too! If I click on View password and then Copy password, it works, but if I just go directly to the "Copy Password to clipboard" button I get the "error while copying to clipboard" message.

I tried both Chrome and Opera and I'm using the latest Syspass version
