### ISSUE TITLE
depreciate php 7.0

### ISSUE THREAD

**Issue by Chris25602** [nuxsmin/sysPass#1580]
I performed a reinstall today. and it looks like one of the deps no longer is compatible with 7.0

`2020/08/07 16:28:55 [error] 11039#11039: *1 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '?' in /var/www/syspass/html/vendor/php-di/invoker/src/Invoker.php on line 106"`

so it looks like php-di requires at least 7.1 just an fyi 

I resolved my issue by using php 7.1

**Comment by CodeNinja1337** [comment]
PHP 7.0 is actually deprecated. PHP 7.3 is the lowest still supported version so its adviced to upgrade you PHP version to >7.3

**Comment by nuxsmin** [comment]
thanks @CodeNinja1337
