### ISSUE TITLE
"clone method called on non-object"-Error

### ISSUE THREAD

**Issue by HerroBert** [nuxsmin/sysPass#1581]
**sysPass Version**
3.1.1.19121601

**Describe the bug**
After upgrade, first output auf sysPass: __clone method called on non-object

**To Reproduce**
Upgrade to 3..1.1

**Expected behavior**
No error

**Event log**
15:59:27 syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
15:59:27 syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}

**Platform (please complete the following information):**
-Linux
-Debian 9
-Firefox

**Comment by HerroBert** [comment]
Same problem with 3.1.2.

**Comment by nuxsmin** [comment]
Hello,

please, let me guess out what could be happening.

Regards

**Comment by HerroBert** [comment]
ok, go on, try to guess. I deleted this installation and used newest version with success.

**Comment by nuxsmin** [comment]
That's fine, thanks!
