### ISSUE TITLE
how can users view old passwords

### ISSUE THREAD

**Issue by krystianroza** [nuxsmin/sysPass#1582]
Hi, sorry for silly question
how can users view old passwords that have bean added to account?

**Comment by CodeNinja1337** [comment]
As far as i know there is no feature for this.

**Comment by nuxsmin** [comment]
Hello,

@krystianroza users could display old passwords by selecting a point-in-time account's data. You also need to set the correct permission within roles.

Thanks for your contribution @CodeNinja1337 !

Regards
