### ISSUE TITLE
Issue with XML Export

### ISSUE THREAD

**Issue by anthathaway** [nuxsmin/sysPass#1584]
**sysPass Version**
Can be found on `Config -> Information` tab
3.1 (310.19081801)

**Describe the bug**
The program seems to fail at downloading exporting the XML option. 

When hitting the button for the XML Export, which I generated about 20 minutes ago, it sits in my download bar with the status of "Starting..." and then after about 3 to 5 minutes, it will just go to "Failed - File Incomplete"

We've tested with different INI settings for max execution and memory limit and can't ever get it to work properly.

**To Reproduce**
1. Go to Configuration and Back Up
2. Click on the play button to generate your back up
3. Click on the XML SysPass button
4. Wait for the file to download and then error after a few minutes.

**Expected behavior**
I would expect a working download function that provides me with the XML backup.

**Screenshots**
![image](https://user-images.githubusercontent.com/46323615/90539905-74b5ed80-e14e-11ea-8f56-d95ffccafeef.png)

**Event log**
Some lines from `syspass.log` file (within `config` directory) and sysPass event log that were logged when the error happened.

**Platform (please complete the following information):**
 - OS: Windows 
 - OS Version: 10
 - Browser Chrome

**Additional context**
Why is so difficult to export my data out of SysPass? I feel one must jump through hoops to get the data.

**Comment by nuxsmin** [comment]
Hello,

>  Why is so difficult to export my data out of SysPass? I feel one must jump through hoops to get the data.

I'm not agree with that, since you can SSHing to your sysPass server and take the exported file.

I'm not sure about the root of this issue, but it might be related to a proxy?, or even to server time out. Could you pleas provide some messages from the webserver  and sysPass logs?.

Regards
