### ISSUE TITLE
Conf directory as NFS Share

### ISSUE THREAD

**Issue by jorgeboti** [nuxsmin/sysPass#1587]
Moorning,

Recently we used your dockerimage to deploy app in a K8S Cluster. Persistent volumes in this cluster is based on NFS shares.

Syspass show an error when check write permissions in app/conf if directory is a NFS Share. 

My workaround was symbolik links, but it is a possible bug on the code.

**Comment by nuxsmin** [comment]
Hello!

sysPass checks directory permissions by using PHP filesystem functions, so it seems that the underlying FS (or PHP) does not "understand" the permissions set.

Regards
