### ISSUE TITLE
syspass ldap not working 

### ISSUE THREAD

**Issue by Ahmadhin** [nuxsmin/sysPass#1590]
**sysPass Version**
Can be found on `Config -> 
3.1 (312.20030701)
Config: 312.20030701
App: 312.20030701
DB: 312.20030701

**Describe the question**
LDAP bind error 49 ( not woking )

**Screenshots**
![Screenshot 2020-09-09 14 56 36](https://user-images.githubusercontent.com/40662044/92595624-56ef2a80-f2ad-11ea-8a8c-9981a708ef8b.png)

**Platform (please complete the following information):**
 - OS: centos 7
 - OS Linux  3.10.0-1062.18.1.el7.x86_64
 - Browser Chrome

**Additional context**
error log :
#0 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\Providers\Auth\Ldap\LdapConnection->bind()
#1 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#2 /var/www/html/syspass/lib/SP/Providers/Auth/Ldap/Ldap.php(96): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#3 /var/www/html/syspass/lib/SP/Services/Ldap/LdapCheckService.php(51): SP\Providers\Auth\Ldap\Ldap->factory(Object(SP\Providers\Auth\Ldap\LdapParams),Object(SP\Core\Events\EventDispatcher),Boolean)
#4 /var/www/html/syspass/app/modules/web/Controllers/ConfigLdapController.php(156): SP\Services\Ldap\LdapCheckService->checkConnection(Object(SP\Providers\Auth\Ldap\LdapParams))
#5 [internal function]: SP\Modules\Web\Controllers\ConfigLdapController->checkAction()
#6 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#8 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#9 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#10 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#11 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#12 /var/www/html/syspass/index.php(28): require(String)","caller":"N/A"}
[2020-09-09 11:57:13] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2020-09-09 11:57:13] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2020-09-09 11:57:13] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2020-09-09 11:59:13] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2020-09-09 11:59:13] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2020-09-09 11:59:13] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}

**Comment by nuxsmin** [comment]
Hello,

such kind of error is because an invalid credentials.

Regards
