### ISSUE TITLE
[MEJORA] Inclusión de subdominios en la búsqueda de LDAP/DA

### ISSUE THREAD

**Issue by ElGranLoky** [nuxsmin/sysPass#1591]
**Is your feature request related to a problem? Please describe.**
La busqueda de ldap solamente acepta configuración de búsqueda en un dominio. Haciendo imposible usar la aplicación si los usuarios se encuentran repartidos en dominios o subdominios.

**Describe the solution you'd like**
Añadir una opción de búsqueda de los usuarios en subdominios, para la consulta de directorio.

**Describe alternatives you've considered**
Teampass tiene opción de multi-dominio, sin llegar a ser una búsqueda de subdominio, se puede configurar dos entradas, una para el dominio principal y otra para el secundario, así se pueden logar los usuarios de los dos dominios, aunque uno sea subdominio del otro.

**Comment by nuxsmin** [comment]
Buenas,

disculpa el retraso. sysPass utiliza la búsqueda de LDAP para localicar los usuarios de AD, por lo que si las relaciones de confianza entre dominios están establecidas, no debería de haber problemas para localizarlos en otros subdominios, ya que la confianza en la autenticación está garantizada. Descnozco lo de aceptar un dominio secundario en el lado de la aplicación.

Saludos!

**Comment by ElGranLoky** [comment]
Buenos días,

No te preocupes todos tenemos vidaReal™

El mensaje que has publicado me ha dado que pensar y el problema radica en la conexión que estaba haciendo. Me explico, al ser una búsqueda LDAP la estaba haciendo sobre una base de búsqueda del dominio por ejemplo:

DC=foo,DC=es

pero si tienes un subdominio del estilo

DC=bar,DC=foo,DC=es

la búsqueda LDAP no va a devolver ningún resultado al estar en el **mismo bosque** pero en _**diferentes controladores de dominio**_.

Así que la solución es **hacer la consulta sobre el catálogo global** en vez de sobre un controlador del dominio. De esta forma donde se pone la configuración de LDAP del servidor, en vez de poner X.X.X.X se pone X.X.X.X:3268 o X.X.X.X:3269 que son los puertos para las consultas sobre el catalogo global en vez del 389.

Puedes ampliar la información en la documentación de LDAP, sobre todo para cuando no caes en estas cosas desde el principio, como me ha pasado.

Muchas gracias por la pista 👍 y por la aplicación 🥇
