### ISSUE TITLE
Cannot upload files

### ISSUE THREAD

**Issue by adocampo** [nuxsmin/sysPass#1593]
**sysPass Version**
3.1 (312.20030701) 

**Describe the bug**
Cannot upload files into the FILES tab. I searched in the documentation and duckducked for a solution, and here on github issues, but no clue what's happening. It complains about `File Type not allowed`
![image](https://user-images.githubusercontent.com/2266612/93591890-796dfb80-f9b1-11ea-87b6-f5b0ae2a91ec.png)
On the github issues I saw you must need to specify the extensions and mimetype, but I just got an example of the fomer, so I added into my config.xml as follows
```xml
  <filesAllowedExts>
    <item type="filesAllowedExts">PDF</item>
    <item type="filesAllowedExts">PEM</item>
    <item type="filesAllowedExts">JPG</item>
    <item type="filesAllowedExts">GIF</item>
    <item type="filesAllowedExts">PNG</item>
    <item type="filesAllowedExts">ODT</item>
    <item type="filesAllowedExts">ODS</item>
    <item type="filesAllowedExts">DOC</item>
    <item type="filesAllowedExts">DOCX</item>
    <item type="filesAllowedExts">XLS</item>
    <item type="filesAllowedExts">XSL</item>
    <item type="filesAllowedExts">VSD</item>
    <item type="filesAllowedExts">TXT</item>
    <item type="filesAllowedExts">CSV</item>
    <item type="filesAllowedExts">BAK</item>
  </filesAllowedExts>
```
No idea what to put between the mimetype tags
```xml
<filesAllowedMime></filesAllowedMime>
```
**To Reproduce**
1. Go to 'Edit account' ---> 'FILES' tab
2. Click on 'upload' or drag and drop a file (let's say a PEM)
3. See error 'File type not allowed'

**Expected behavior**
File should be uploaded if it meets the max file size limit

**Screenshots**
See above

**Event log**
```
[2020-09-18 13:24:15] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2020-09-18 13:24:15] syspass.INFO: logger {"message":"Saved icons cache","caller":"SP\Core\UI\Theme::saveIcons"}
[2020-09-18 13:24:15] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
[2020-09-18 13:24:15] syspass.EXCEPTION: logger {"message":"File type not allowed
#0 /var/www/html/syspass/app/modules/web/Controllers/AccountFileController.php(228): SP\Modules\Web\Controllers\AccountFileController->checkAllowedMimeType(Object(SP\DataModel\FileData),Object(SP\Storage\File\FileHandler))
#1 [internal function]: SP\Modules\Web\Controllers\AccountFileController->uploadAction(Integer)
#2 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#4 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#8 /var/www/html/syspass/index.php(28): require(String)","caller":"N/A"}
```

**Platform (please complete the following information):**
 - OS: Debian GNU/Linux 10 (server)
 - Client OS: any
 - Browser: any

Gracias!

**Comment by CodeNinja1337** [comment]
I cant help you with your issue but what i know is that it is a bad idea to simply upload certificates as they are stored unencrypted. I think there is currently no good feature available in syspass to store certificates.

**Comment by adocampo** [comment]
I'm using syspass internally, so that won't be a problem as is not published into the Internet, but anyway, I put a certificate file just as an example. I cannot upload _any_ kind of file I've tried so far: JPG, PNG, TXT... so I'm wondering if the feature is working at all.

**Comment by nuxsmin** [comment]
Hello,

@adocampo you need to fill in the MIME types because the old behavior by using the file extension is no longer available, because it was unsafe. Please take a look to the demo site.

Thanks for your contribution @CodeNinja1337 !

Regards

**Comment by adocampo** [comment]
Can't see where is the demo site. Besides, would you mind explaining how to fill that MIME types? Should I edit config xml file and fille the `filesAllowedMime` tag? If affirmative, what should I put on there?
Thank you!

**Comment by CodeNinja1337** [comment]
@adocampo https://demo.syspass.org/index.php?r=login
@nuxsmin you're welcome :)
