### ISSUE TITLE
issue regarding auto logout timeout session

### ISSUE THREAD

**Issue by blacksheepzven** [nuxsmin/sysPass#1594]
**sysPass Version**
3.1

**Describe the question**
Can the timeout for auto log out be modified from the config files? 

**Platform (please complete the following information):**
 Debian 10(buster) 

**Additional context**
So, one of my colleagues set timeout value to 0 in sysspass web interface. And when we login it automatically log`s out. Is there a way to modify from config files or db the setting? 
Thank you.

**Comment by gglope** [comment]
Hi, I did the same last week, thinking that `0 = disable autologout`.
I fixed the problem by editing the directive `<sessionTimeout>` in the file `/var/www/html/sysPass/app/config/config.xml` .
It seems that, for the value of this field, sysPass only accepts multiple of 300.

**Comment by blacksheepzven** [comment]
yes, I found it after 30 min after I posted, but thank you. :)

**Comment by secport** [comment]
This post saved my life, thanks a lot!
