### ISSUE TITLE
API Delete Action without tokenPass

### ISSUE THREAD

**Issue by Selfmade-RuLeZ** [nuxsmin/sysPass#1597]
**sysPass Version**
3.1

**Describe the question**
Is it wanted to delete account without confirmation of the tokenPass? I think you should hide it behind the password for security reasons.

**Comment by nuxsmin** [comment]
Hello,

it shouldn't require the tokenPass because this action doesn't need to access to any encrypted data.

Regards

**Comment by Selfmade-RuLeZ** [comment]
Ah, thx for the explenation, now I understand the usage of the token password 👍

**Comment by nuxsmin** [comment]
Great!!, thanks for the feedback!
