### ISSUE TITLE
Add SSH keys MIME by default

### ISSUE THREAD

**Issue by MarcSamD** [nuxsmin/sysPass#1599]
I think that storing SSH keys in a password manager should be supported by default, at least for the most common types.

Add something like this in the default mime.xml:
`  <mime multiple="1">
    <type>application/x-putty-private-key</type>
    <description>Putty Private Key</description>
    <extension>ppk</extension>
  </mime>`

**Comment by HerroBert** [comment]
Bad idea, database field is not encrypted! So sad...

**Comment by CodeNinja1337** [comment]
I understand what you are asking for and a way to store SSH keys is not a bad idea but i agree with @HerroBert that your suggestion is not the way to go.

**Comment by nuxsmin** [comment]
Hello

@MarcSamD you should use custom fields to store encrypted data instead of files. Files are meant to provide more context about the account (images, text,, etc.), but not for sensible data.

Thanks for your contributions @HerroBert @CodeNinja1337 !!

Regards

**Comment by MarcSamD** [comment]
Thank you all for the clarification.
