### ISSUE TITLE
CSV/XML Account Import issues

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#160]
Hi @nuxsmin,

I have encountered a couple of issues while trying to bulk import accounts into the system via CSV.

1. Header line is not skipped in the CSV. I would suggest adding a tick box to specify if a header line is included in the CSV.

2. Progress spinning wheel never finishes, and never confirms that the import is completed. I have to look at the log to see the completed message.

3. No information on what the Import Password field is for???

4. Can not view or copy to clipboard any of the Imported accounts. They show an encrypted password in the DB table but the buttons do not function. Manually added accounts work without issue.

Regards,

Basil

**Comment by nuxsmin** [comment]
HI @basil-twisleton , the issue has been fixed in the latest commit. There were a typo in the javascript code that prevented to hide the loading icon and another one that the password IV were not set correctly.

Thanks for the feedback ;)

**Comment by basil-twisleton** [comment]
@nuxsmin,

I can confirm that the import now works with the password (item 4).

However on Chrome 46 the status still shows spinning wheel, regardless of success or failure. Logs indicate results.  


Also do you have any information on item 3 from the above list. 
I have tried leaving it blank, or entering "1234" and neither appear to do anything.

Thanks,

Basil

**Comment by nuxsmin** [comment]
Hi, great news...

About the 3rd point, that password field is intended to use with an encrypted sysPass XML file, which requires its decryption password to be imported.

I'm thinking about to include some context help for it.

**Comment by basil-twisleton** [comment]
ok makes sense. 
Suggested help text
"If you are importing encrypted data generated by the sysPass export mechanism, please enter the password used during the export."
