### ISSUE TITLE
Can not delete user account

### ISSUE THREAD

**Issue by dresiss** [nuxsmin/sysPass#1602]
**sysPass Version**
3.1 (312.20030701)

**Describe the bug**
I can not delete an user which has an associated Public Link or any change on the account history.

**To Reproduce**
1. Go to 'Users'
2. Click on the search box and search the user to delete
3. Click on the delete button for the user
4. The account is not deleted and an error is shown:
Restricción de integridad
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`PublicLink`, CONSTRAINT `fk_PublicLink_userId` FOREIGN KEY (`userId`) REFERENCES `User` (`id`))

**Expected behavior**
The account must be deleted, and no errors shown

**Event log**
[2020-10-23 11:48:31] syspass.EXCEPTION: logger {"message":"SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`PublicLink`, CONSTRAINT `fk_PublicLink_userId` FOREIGN KEY (`userId`) REFERENCES `User` (`id`))
#0 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(235): PDOStatement->execute()
#1 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(175): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))
#2 /var/www/html/sysPass/lib/SP/Repositories/User/UserRepository.php(187): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))
#3 /var/www/html/sysPass/lib/SP/Services/User/UserService.php(194): SP\Repositories\User\UserRepository->delete(Integer)
#4 /var/www/html/sysPass/app/modules/web/Controllers/UserController.php(300): SP\Services\User\UserService->delete(Integer)
#5 [internal function]: SP\Modules\Web\Controllers\UserController->deleteAction(Integer)
#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#8 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#9 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#10 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#11 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#12 /var/www/html/sysPass/index.php(28): require(String)","caller":"N/A"}
[2020-10-23 11:48:31] syspass.EXCEPTION: logger {"message":"Restricción de integridad
#0 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(175): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))
#1 /var/www/html/sysPass/lib/SP/Repositories/User/UserRepository.php(187): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))
#2 /var/www/html/sysPass/lib/SP/Services/User/UserService.php(194): SP\Repositories\User\UserRepository->delete(Integer)
#3 /var/www/html/sysPass/app/modules/web/Controllers/UserController.php(300): SP\Services\User\UserService->delete(Integer)
#4 [internal function]: SP\Modules\Web\Controllers\UserController->deleteAction(Integer)
#5 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#8 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#9 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#10 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#11 /var/www/html/sysPass/index.php(28): require(String)","caller":"N/A"}
[2020-10-23 11:48:32] syspass.EXCEPTION: logger {"message":"(P) SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`PublicLink`, CONSTRAINT `fk_PublicLink_userId` FOREIGN KEY (`userId`) REFERENCES `User` (`id`))
#0 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(235): PDOStatement->execute()
#1 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(175): SP\Storage\Database\Database->prepareQueryData(Object(SP\Storage\Database\QueryData))
#2 /var/www/html/sysPass/lib/SP/Repositories/User/UserRepository.php(187): SP\Storage\Database\Database->doQuery(Object(SP\Storage\Database\QueryData))
#3 /var/www/html/sysPass/lib/SP/Services/User/UserService.php(194): SP\Repositories\User\UserRepository->delete(468)
#4 /var/www/html/sysPass/app/modules/web/Controllers/UserController.php(300): SP\Services\User\UserService->delete(468)
#5 [internal function]: SP\Modules\Web\Controllers\UserController->deleteAction(468)
#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array, Array)
#7 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#9 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#11 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap::run(Object(DI\Container))
#12 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')
#13 {main}","caller":"N/A"}
[2020-10-23 11:48:32] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2020-10-23 11:48:32] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
[2020-10-23 11:48:32] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}

**Platform (please complete the following information):**
 - OS: Debian 9 Server, Windows Chrome client

**Comment by nuxsmin** [comment]
Hello,

the user created some public links so you need to remove them before deleting the user.

Regards
