### ISSUE TITLE
Password generation

### ISSUE THREAD

**Issue by htcosta** [nuxsmin/sysPass#1603]
Is is possible for users to generate passwords using ASCII basic western chars only?

Sometimes syspass generates passwords which contains characters(symbols) that are not accepted by the application for which they intended.
For example:
R<(yIAje"·8¡
jtW)MC3·3p¡f
tPa7}a_¿=Kk?

This passwords are quite fine for most applications but if you need to login to a terminal, they just don't work.

So my question is possible to force password generation only to ASCII (character code 32-127) ?

**Comment by Hr46ph** [comment]
Duplicate of #1556

**Comment by htcosta** [comment]
Thanks
