### ISSUE TITLE
Custom Field by Category?

### ISSUE THREAD

**Issue by olivdee** [nuxsmin/sysPass#1604]
Hi, sysPass looks very promising!
I could not find the possibility to add a custom field for a certain group in the demo.
Also no info about this on the docs or here...
Is this possible or planned?

**Comment by CodeNinja1337** [comment]
In the title you ask for a custom field by "Category" and in your question you are talking about a custom field for a certain group. Maybe you can explain your request more in detail like what exactly are you looking for, where do you "expect" the field and maybe add some screenshots so the developer(s) don't need to guess or what you are meaning.

**Comment by nuxsmin** [comment]
Thanks @CodeNinja1337 you're right!

@olivdee could you provide some context?

Regards
