### ISSUE TITLE
DB access password-Field on the installation page is changing the entered password

### ISSUE THREAD

**Issue by thomasfrobieter** [nuxsmin/sysPass#1605]
**sysPass Version**
3.1.2

**Describe the bug**
The "DB access password"-Field on the installation page is changing the entered password.
If i type "abc" and click somewhere else, so the field lose focus.. the string changes to a very long Hash.. whatever.
Tried in Firefox and Edge, exact same behavoir. The other password field work fine.

**To Reproduce**
1. Install syspass with Docker (https://raw.githubusercontent.com/nuxsmin/docker-syspass/master/docker-compose.yml)
2. Open the syspass setup in the browser, in my case its: https://127.0.0.1:32769/index.php?r=install/index
3. Enter all the stuff till you reach the DB access password field
4. Type something like "abc"
5. Click somewhere outside the field, so it looses focus
6. Boom: Passwort changes to a very long string

**Expected behavior**
Dont touch the entered password.

**Screenshots**
![syspass_db_password_field_bug](https://user-images.githubusercontent.com/4060313/98015584-3cdd4e80-1dfd-11eb-842e-a415cbc187c7.gif)

**Event log**
No errors in the JS console.. nor any.. entries pointing to this issue.

**Platform (please complete the following information):**
 - OS: Windows
 - OS Version: 10 (1903)
 - Browser: Firefox and Edge

**Comment by thomasfrobieter** [comment]
Its about the data-length attribute on the input field. If i limit its value to the length of my password, the length is not changing anymore.

(Unsure if it's working with this "fix".. because of other database connection problems)

**Comment by nuxsmin** [comment]
Thanks for the feedback  @thomasfrobieter !!
