### ISSUE TITLE
Improve user activation processs

### ISSUE THREAD

**Issue by Romich777** [nuxsmin/sysPass#1606]
Currently every user should to enter master password. But this very unconformable to and you should do this on client side (key logger ?).
It would be grate that admin can activate user (enter master password) on its own side in admin panel.
So it will simplify registration and mass registration process.

This master password behaviour was the main issue for us that prevent migration to syspass.

**Comment by simoesp82** [comment]
you can generate temporary keys in the congiguration menu that can expire after 1 hour for the "activation"

**Comment by nuxsmin** [comment]
thanks for the reply @simoesp82 , you're right, temporary passwords are such kind of passwords to not be worried about a keylogger, because it will expire after some time or attemtps.

Regards
