### ISSUE TITLE
Question: Recommended setup/assistance for use with proxy server.

### ISSUE THREAD

**Issue by 11anthonym** [nuxsmin/sysPass#1608]
**sysPass Version**
3.1 (311.19121601)
Config: 311.19121601
App: 311.19121601
DB: 311.19121601

**Describe the question**
We are using a reverse proxy server and appear to be having an issue with the connection being secure where sysPass appears to recognize the connection from the browser to the proxy server as secure, but does not recognize the connection from the proxy server to sysPass as secure. I don't fully understand the backend setup so looking for some insight into a way to fix this issue, as well as recommendations on using sysPass in a proxied environment. In screen shots below we have a http symbol signifying the insecure part of the connection.

**Screenshots**
![chrome_wa8r8mZC1n](https://user-images.githubusercontent.com/62766485/98569337-2cefbf80-2280-11eb-8bc6-5009b478f0bd.png)
![chrome_GzcEeFzxmS](https://user-images.githubusercontent.com/62766485/98569347-311bdd00-2280-11eb-867e-28d60a5af44a.png)

**Platform (please complete the following information):**
 - OS: Windows
 - OS Version - Version	10.0.19041 Build 19041
 - Browser - Chrome

**Additional context**

**Comment by nuxsmin** [comment]
Hello,

It's hard to guess out for an encrypted channel when sysPass is behind a reverse proxy, because the connection isn't secure at all. You can try to set an "HTTPS" variable on sysPass server, so PHP will set the https flag on.

Regards
