### ISSUE TITLE
Devide permission for profiles into users and groups

### ISSUE THREAD

**Issue by HerroBert** [nuxsmin/sysPass#1609]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Devide permission for profiles into user permissions and group per missions.

**Additional context**
I like to force "powerusers" to grant permissions to some users only, not a group.

**Comment by nuxsmin** [comment]
Hello,

unfortunately such kind of behavior would increase the application complexity (thus development), and many role based application rely on permission at group level.

Regards

PS: sorry for the late reply
