### ISSUE TITLE
Customer not available for adding accounts

### ISSUE THREAD

**Issue by HerroBert** [nuxsmin/sysPass#1610]
**sysPass Version**
3.1.2

**Describe the bug**
User can't add a new account for an existing customer, when another account exisists for this customer, which is hidden.

**To Reproduce**
1. Clock on 'New Account'
2. Select selectbox 'customer'
3. see missing customer in list.

**Expected behavior**
Listed customer in selectbox.

**Event log**
no error logged.

**Platform (please complete the following information):**
 - OS: Linux
 - OS Version Debian 9
 - Browser Chrome

**Comment by HerroBert** [comment]
Seems to be releated to issue 880...

**Comment by nuxsmin** [comment]
Hello,

clients would be available until the first account set it, so if you don't set it as global, it will be only available for the users and groups that have permission over the account.

Regards

PS: sorry for the late reply
