### ISSUE TITLE
Unable to delete not used categori or Clients

### ISSUE THREAD

**Issue by JensMKofoed** [nuxsmin/sysPass#1612]
sysPass Version: 3.1 (312.20030701)

While creating a new account I created a new category. After saving the account I went in to change the category to anoter old category and saved the changes.
Next I went to "Items and Customizations" to delete the newly created category which is no longer in use. But I got an error message saying:
Integrity constraint
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`znlrulcu_syspass_v3`.`AccountHistory`, CONSTRAINT `fk_AccountHistory_categoryId` FOREIGN KEY (`categoryId`) REFERENCES `Category` (`id`))

The same error happens with clients.

**Expected behavior**
If a client or category is not in used and there are a delete button I expected it to be able to delete it.

**Comment by HerroBert** [comment]
Look in account history "accounts (h)" and delete these hidden (old) entries.

**Comment by nuxsmin** [comment]
Hello,

as pointed @HerroBert this behavior is because the accounts history is using the category id in older accounts, so you firstly need to look for the account in the history and delete it.

Thanks @HerroBert !!

Regards
