### ISSUE TITLE
Preset Password complexity

### ISSUE THREAD

**Issue by JensMKofoed** [nuxsmin/sysPass#1614]
sysPass Version: 3.1.2

It would be nice if we could definde standart settings for random password generation.
Something like this: Uppercase Letters, Lowercast Letters, Numbers, Customs symbols (!"#¤%&/()=?,.-;:_*). Length 24

**Comment by nuxsmin** [comment]
Hello,

this is related to #1613

Regards

PS: sorry for the late reply
