### ISSUE TITLE
Tag creation not working as expected, differing strings matching and causing tag creation to fail.

### ISSUE THREAD

**Issue by 11anthonym** [nuxsmin/sysPass#1615]
**sysPass Version**
3.1 (311.19121601)
Config: 311.19121601
App: 311.19121601
DB: 311.19121601

**Describe the bug**
When creating a tag, there seems to be an issue with the tag being created matching an existing tag, even though the strings of the new tag and existing tag do not match.

Example tags-
Existing Tag - "Board Room 123"
New Tag - "Boardroom 123"

**To Reproduce**
1. Create tag - "Board Room 123", this will succeed.
2. Create tag - "Boardroom 123", this will fail.
4. Error will pop up -
![image](https://user-images.githubusercontent.com/62766485/99291396-c1709980-280d-11eb-8ab6-9f13fd1b3cf7.png)

**Expected behavior**
Both Tags should be successfully created since the strings are different.

**Platform (please complete the following information):**
 - OS: OS Name Microsoft Windows 10 Pro
 - OS Version: Version 10.0.18362 Build 18362
 - Browser: Chrome

**Comment by JensMKofoed** [comment]
Hmm....
I will personal say that the 2 words should match and the 2nd tag should not be allowed.
Otherwise you can end up with the following tags: "MAILSERVER", "Mailserver", "mailserver", "Mail server", "Mail Server", "M a i l s e r v e r" ect.

**Comment by 11anthonym** [comment]
In my opinion I would say "MAILSERVER", "Mailserver", "mailserver", "Mail server", "Mail Server", "M a i l s e r v e r" should be able to be treated as different strings and be able to exist as different tags, I would agree in the sense that having those different tags would not be best practice in many situations, but with our use case we are using a tag as a room name, and because of this we may have a room named "Boardroom" and a room named "BOARDROOM" (meaning on the name plaque outside the room has that exact text with that case, which we document that text one for one.)

**Comment by CodeNinja1337** [comment]
I agree with @JensMKofoed even if i understand your situation @11anthonym

**Comment by nuxsmin** [comment]
I agree with @JensMKofoed  too.

It's so because sysPass is a collaborative tool, so it needs to enforce the accuracy of the data entered by several users. It's done by stripping and hashing some strings to avoid the similar ones, so yes, it will remove some characters to identify them (strings) better.
