### ISSUE TITLE
Removing all passwords

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#162]
Hi @nuxsmin,

I have a reasonable large number of password (about 200) which I bulk loaded prior to #160 getting fixed. 
How would you suggest I remove them without having to delete them all individually?

Regards,

Basil

**Comment by nuxsmin** [comment]
Actually there isn't an accounts management point, so the only way to perform this is by clearing the accounts table by issuing this command ```TRUNCATE TABLE accounts```. Take care that neither categories not customers are removed.

**Comment by basil-twisleton** [comment]
Thanks. 
I have truncated a number of tables to resolve this. 

If you are considering a Management feature for this I would suggest showing a simple list with check boxes to bulk delete records. 

Thanks,

Basil

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta

**Comment by wszychta** [comment]
@nuxsmin 

I have syspass 2.14. Can you tell me how can I delete all accounts from database. I can't do truncate accounts because of dependencies error:

> ERROR 1701 (42000): Cannot truncate a table referenced in a foreign key constraint (`syspass`.`accFiles`, CONSTRAINT `fk_accFiles_accounts_id` FOREIGN KEY (`accfile_accountId`) REFERENCES `syspass`.`accounts` (`account_id`))

**Comment by nuxsmin** [comment]
Hello @wszychta 

Unfortunately DB constraints shouldn't be disabled, because many linked records would be broken if parents are removed. Relational data structures work on that way to avoid redundancy.

Kind regards.
