### ISSUE TITLE
Will this project still be maintained? Will it be any new release ? 

### ISSUE THREAD

**Issue by ju29ro14** [nuxsmin/sysPass#1620]
Does anyone have any information if this project will have any new release ? Last activity from @nuxsmin is from June, no replies to issues anymore, and i am afraid that this project is discontinued.  

If anyone have more information please share

**Comment by CodeNinja1337** [comment]
Same question over here. 

I checked the demo project and it looks great. I has all features we need including LDAP. Unfortunately there are some known issues which are critical for us. When the project is discontinued, we cannot use this sysPass which would be realy sad. I'm also in for a small donation when the project is still alive.

**Comment by CodeNinja1337** [comment]
I mailed the developer and it seems he is still actively maintaining this project as many issues are answered or solved. I would say let we gove him some time and where lossoble some help and maybe thank him with a small donation :-)

**Comment by nuxsmin** [comment]
Hello,

sorry it isn't about donation, it about time instead :wink: 

I'm working on some personal projects that makes sysPass development a bit slower, but be sure that I'm committed with the project.

Thanks!!

**Comment by CodeNinja1337** [comment]
I understand the lack of time many of us are familiar with that issue ;-). Its not an issue when the development is slow as long as we know the project is still alive!
 
Thanks for you commitment and time investment and bringing us this great tool! Cheers!

**Comment by ju29ro14** [comment]
Thank you for your reply. we appreciate a lot the effort you put into this.
