### ISSUE TITLE
AD user Unable to login other can 

### ISSUE THREAD

**Issue by jr-RXcode** [nuxsmin/sysPass#1621]
**sysPass Version**
3.1 (312.20030701) 
Config: 300.18112501
App: 310.19042701
DB: 310.19042701

**Describe the question**
One of the AD users is unable to login to syspass. I have syspass connected to our AD server. I'm able to create new users in AD and they are able to sign in to Syspass after providing them with the master password. I'm able to sync the AD users from the ldap tab, so I don't think the issue is AD related. 
There is a particular user that can't login and keeps getting a "Wrong Login" message. I've removed the user from syspass and then synced AD users again, but the user keeps getting the same "Wrong Login" message. After the first login attempt I see an entry in the security and Audit tab -> Track that says "SP\Services\Auth\LoginService"  with the option to Unlock Track. Does that mean the account is locked?

I'm also not getting the prompt for the previous password. 
Is there a way to completely reset the user and then sync them back with AD?

**Screenshots**

**Platform (please complete the following information):**
 - OS: windows
 - OS 10
 -  Chrome, edge

**Additional context**
This is what I see in the logs..
syspass.EXCEPTION: logger {"message":"Connection error (BIND)
#0 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/Ldap.php(140): SP\Providers\Auth\Ldap\LdapConnection->bind(String,String)
#1 /var/www/html/sysPass/lib/SP/Providers/Auth/Ldap/LdapAuth.php(123): SP\Providers\Auth\Ldap\Ldap->bind(String,String)
#2 /var/www/html/sysPass/lib/SP/Providers/Auth/AuthProvider.php(119): SP\Providers\Auth\Ldap\LdapAuth->authenticate(Object(SP\DataModel\UserLoginData))
#3 /var/www/html/sysPass/lib/SP/Providers/Auth/AuthProvider.php(97): SP\Providers\Auth\AuthProvider->authLdap()
#4 /var/www/html/sysPass/lib/SP/Services/Auth/LoginService.php(154): SP\Providers\Auth\AuthProvider->doAuth(Object(SP\DataModel\UserLoginData))
#5 /var/www/html/sysPass/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#6 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#8 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#9 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#10 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#11 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#12 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#13 /var/www/html/sysPass/index.php(28): require(String)","caller":"N/A"}
[2020-12-02 19:36:29] syspass.EXCEPTION: logger {"message":"Wrong login
#0 /var/www/html/sysPass/lib/SP/Services/Auth/LoginService.php(160): SP\Services\Auth\LoginService->authLdap(Object(SP\Providers\Auth\Ldap\LdapAuthData))
#1 /var/www/html/sysPass/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/html/sysPass/index.php(28): require(String)","caller":"N/A"}

**Comment by nuxsmin** [comment]
Hello,

it seems that the user's login isn't the right one for what the LDAP searches are configured. Please take a look to user's attributes in the LDAP.

Regards
