### ISSUE TITLE
Changed admin password but forgot master password

### ISSUE THREAD

**Issue by bubbapizza** [nuxsmin/sysPass#1625]
**sysPass Version**
v3.1

**Describe the question**
I forgot what my admin password was but it was saved in firefox so I was able to change the password.  But I can't remember what the master password was so I can't login as admin now.  I do have one other user with admin rights that I can login with because the password is saved in firefox though (no idea what that password is either).

I saw some other thing that said to change debug.inc but that file is stored under themes and it didn't look the same.  Is there any way to reset the master password or figure out what it is?

**Comment by nuxsmin** [comment]
Hello,

unfortunately the master password display feature (using debug mode) was removed some versions ago, since it was a security issue.

Regards
