### ISSUE TITLE
Installation page still accessible after installation

### ISSUE THREAD

**Issue by kmmndr** [nuxsmin/sysPass#1629]
**sysPass Version**

sysPass 3.1.2

**Describe the bug**

Installation page is still accessible after installation: this means that everybody could restart the process.
After two installations the login system seems to be broken.

Look at : https://demo.syspass.org/index.php?r=install/index

**To Reproduce**

1. Follow instruction to [deploy using docker](https://syspass-doc.readthedocs.io/en/3.1/installing/docker.html), using latest release [syspass/syspass:3.1.2-php7.3](https://hub.docker.com/layers/syspass/syspass/3.1.2-php7.3/images/sha256-4d2b49053922c9d6cd14ddc78e1f2f95727f50dd12cda2d94ee77ec7cdcfc926?context=explore)
2. Complete installation (page `/index.php?r=install/index`)
3. Log into syspass and add a password
4. Log out
5. Return to installation page again and submit (page `/index.php?r=install/index`)
6. Try to login (you won't be able to login)

**Expected behavior**

After installation complete, the installation page shouldn't be accessible again

**Comment by kmmndr** [comment]
As a workaround, access can be restricted using web server

This is an example for traefik:
```
    labels:
      - "traefik.enable=true"
      ...
      # index.php?r=install/index
      - "traefik.http.routers.syspass-install-redirect.middlewares=syspass-redirect-root"
      - "traefik.http.routers.syspass-install-redirect.rule=Host(`${APP_FQDN:-localhost}`) && PathPrefix(`/index.php`) && Query(
`r=install{.*}`)"
      - "traefik.http.routers.syspass-install-redirect.entrypoints=websecure"
      - "traefik.http.routers.syspass-install-redirect.tls.certresolver=letsencrypt-tls"
      - "traefik.http.middlewares.syspass-redirect-root.redirectregex.regex=.*"
      - "traefik.http.middlewares.syspass-redirect-root.redirectregex.replacement=https://${APP_FQDN:-localhost}"
```

**Comment by nuxsmin** [comment]
Hello, 

thanks for noticing me about this issue. It'll be fixed in next release.

Regards
