### ISSUE TITLE
Copy Password Action on Search Screen

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#163]
Hi @nuxsmin,

Thought I should create a separate issue for this. 

When logged in as admin I can see the 'Copy Password' action on the right side of (next to delete etc)
![adminhascopyaction](https://cloud.githubusercontent.com/assets/2098465/10686570/ad3af5c0-7965-11e5-936e-00b2449e8208.JPG)
However when logged in as user who is a member of the Main Group I do not have the action.
![usermissingcopyaction](https://cloud.githubusercontent.com/assets/2098465/10686577/baafc5c8-7965-11e5-9f08-1a72cb662bf1.JPG)
This is the defined profile for the user (all other settings are off
![profilesettings](https://cloud.githubusercontent.com/assets/2098465/10686592/e9f0cda0-7965-11e5-81ec-9fa9493c0270.JPG)

I have found what seems to be the cause of the issue. 

In my users profile I have turned on **'Show Hidden Actions'** and the clipboard action is not shown.

If I turn this profile option off, I can then expand the hidden actions and see the copy to clipboard shortcut.

Thanks,

Basil

**Comment by nuxsmin** [comment]
Thanks so much for the feedback. This issue has been fixed in the latest commit.
