### ISSUE TITLE
Couldn't run sysPass

### ISSUE THREAD

**Issue by naylach** [nuxsmin/sysPass#1630]
Hello, I'm working on the installation of sysPass on an Ubuntu 20 server. I followed the steps given in the documentation https://readthedocs.org/projects/syspass-doc/downloads/pdf/3.0/ but when I finished I couldn't run the program on the website.
The result is the following:

```
<?php
/**
 * sysPass
 *
 * @author nuxsmin
 * @link https://syspass.org
 * @copyright 2012-2019, RubĆ©n DomĆ­nguez nuxsmin@$syspass.org
 *
 * This file is part of sysPass.
 *
 * sysPass is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sysPass is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 *  along with sysPass.  If not, see <http://www.gnu.org/licenses/>.
 */

define('APP_ROOT', __DIR__);
define('APP_MODULE', 'web');

require APP_ROOT . DIRECTORY_SEPARATOR . 'lib' . DIRECTORY_SEPARATOR . 'Base.php';
```

I've installed apache, maria db and php 7.4.
I can't find what is missing. Could you help me please?

**Comment by naylach** [comment]
![sys](https://user-images.githubusercontent.com/50495002/102384411-7207bf80-3fab-11eb-812a-14ec0d403955.JPG)

**Comment by derStephan** [comment]
Seems like PHP interpreter is not called by apache. Are you sure, PHP is working at all?

**Comment by naylach** [comment]
Yes, it is working in version 7.4. The whole complements has been installed except for mcrypt which I saw in the documentation that is optional 

![image](https://user-images.githubusercontent.com/50495002/102516229-611f8280-406d-11eb-8043-ddba261036b8.png)

**Comment by nuxsmin** [comment]
Hello,

@naylach it can be installed, though it could be missing for apache, because non-interpreted PHP code states that the PHP module isn't working on Apache.

Regards
