### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by sentretter** [nuxsmin/sysPass#1632]
Syspass v3

Hello, is there any way that I could migrate Passwords with the given permissions and the groups from Webpasswordsafe to Syspass?

Webpasswordsafe is running on a debian VM and Syspass on a docker container.

**Comment by nuxsmin** [comment]
Hello,

unfortunately there isn't such import feature in sysPass, though if you can export your current passwords to CSV format, it could be imported into sysPass by setting the correct fields.

Regards.
