### ISSUE TITLE
LDAP Causing System Failure

### ISSUE THREAD

**Issue by sikas89** [nuxsmin/sysPass#1634]
**sysPass Version**
Can be found on `Config -> Information` tab

3.1 (312.20030701)
Config: 312.20030701
App: 312.20030701
DB: 312.20030701

**Describe the question**
A clear and concise description.

When enabling LDAP, system no longer work. Upon logging in, I get redirected to http://syspass/undefined with the screenshot below. I had to disable the LDAP from the config.xml file.

**Screenshots**

![SysPass](https://user-images.githubusercontent.com/17160524/103173379-4914e380-4863-11eb-9e71-206aa09ab7d1.png)

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android]: Windows (Client) // Linux (Server)
 - OS Version: 10 (Client) // 20.04 LTS
 - Browser [e.g. Firefox, Chrome] Chrome

**Additional context**

LDAP Configuration from config.xml (stripping some information):

`
root@syspass:/var/www/html/syspass/app/config# cat config.xml | grep -i ldap
  <ldapAds>0</ldapAds>
  <ldapBase></ldapBase>
  <ldapBindPass>password</ldapBindPass>       >>>>>>>>>>>> Here using the server admin credentials
  <ldapBindUser>username</ldapBindUser>       >>>>>>>>>>>> Here using the server admin credentials
  <ldapDefaultGroup>1</ldapDefaultGroup>
  <ldapDefaultProfile>1</ldapDefaultProfile>
  <ldapEnabled>0</ldapEnabled>       >>>>>>>>>>>> Here set to 1 when enabled
  <ldapGroup>CN=****,OU=****,DC=****,DC=****</ldapGroup>
  <ldapProxyUser></ldapProxyUser>
  <ldapServer>1.2.3.4</ldapServer>       >>>>>>>>>>>> Here using the server IP Address
  <ldapTlsEnabled>0</ldapTlsEnabled>
  <ldapType>2</ldapType>
`

Connecting is done with Microsoft Active Directory

**Comment by nuxsmin** [comment]
Hello,

I'm not sure about this issue, since LDAP feature doesn't make any redirection, so any authentication logic is done through the logging in process. Are you running sysPass behind a reverse proxy?. Did you enable 2FA feature?.

Regards

**Comment by symcbean** [comment]
FWIW I see the same issue with OpenLDAP / no reverse proxy / clean install of Syspass 3.1 on Ubuntu 18.04 with PHP 7.2

**Comment by sikas89** [comment]
@nuxsmin hey, sorry for the delay. It is not behind any reverse proxy. It took me time as I had to look into the AD and review the configuration. It seems that it was a configuration issue as I have successfully integrated it with LDAP.

I have another question about assigning roles and levels. Shall I ask here, or open a new question?
