### ISSUE TITLE
copying syspass to another webspace results in ERR_CONTENT_DECODING_FAILED

### ISSUE THREAD

**Issue by wagnst** [nuxsmin/sysPass#164]
Hi @nuxsmin ..
i have copied my old installation from an apache webspace to a new installation running with nginx (and php-fpm).
Result is that i see the login page, but if i click anything i just see the header and no content...
Mysql user access is granted accordingly to the new host...
Can you help me to identify the problem?

When I want to open http://xxx/js/js.php?v=7f6ffaa6bb0b408017b62254211691b5

I get a ERR_CONTENT_DECODING_FAILED...

Thanks,
Steffen

**Comment by nuxsmin** [comment]
This seems to be related to ZLib compression. Can you tell me if it is enabled? (check zlib.output_compression in php.ini file)

**Comment by wagnst** [comment]
in php.ini of php-fpm its set
``zlib.output_compression = Off``

**Comment by nuxsmin** [comment]
Ok, let me do some tests on an environment like that, because ngnix has not been tested so much.

**Comment by wagnst** [comment]
Okay... maybe it has also to do, that i am currently not on the most current version.. i first wanted to migrate and then upgrade... but maybe i should first try a fresh install with the current version and see if this works..

**Comment by nuxsmin** [comment]
Did you test the latest version?

**Comment by wagnst** [comment]
Yes, but with a fresh install. This works... Migration did always fail...

**Comment by nuxsmin** [comment]
It's strange because migration does not take place on the app side, only on DB. If you download the latest version, you only have to take the config file and run the app. At this point, the database will be upgraded.

**Comment by wagnst** [comment]
But i was running a quite old version? It was 1.X or something, i have to look it up. I tried to migrate from apache to nginx first and then upgrade, but event not the migration worked... like i said with the fresh install and blank database it is okay now. I need to check further if all functions work properly with nginx but i'm gonna report :-)

**Comment by wagnst** [comment]
hi @nuxsmin, now i tried setting it up on new infrastructure...
the same thing happens... i am able to install the current version and database gets filled. If i try to login, i dont get referred to login page... it stays at login screen...

**Comment by wagnst** [comment]
okay i see.. .after further analysis this has probably nothing to do with nginx....
this is a SSL issue...
I don't have SSL set up because i am managing this server through automatisation. Somewhere i see that requests goes to "Request URL:https://vault.fra1.cub.yt/ajax/ajax_doLogin.php" but i am not listening on 443...

**Comment by nuxsmin** [comment]
Great!, did it work so?

**Comment by wagnst** [comment]
yes, working perfectly now under nginx... :-) closing this one then...
