### ISSUE TITLE
Password generator crashes when not selecting Letters

### ISSUE THREAD

**Issue by blabllavita** [nuxsmin/sysPass#1641]
**sysPass Version**
3.1 (310.19081801)

**Describe the bug**
When Selecting 'Include Uppercase' while 'Include Letters' is not selected in the Password generator, the Website crashes.
This Only Affects the Browser used.

**To Reproduce**
1. Click 'New Account'
2. Edit Password Complexity
3. Deselect 'Include Letters'
4. Accept
5. Generate Password
6. Website Freezes

**Expected behavior**
A Password not containing Lowercase Letters should be generated

**Screenshots**
![image](https://user-images.githubusercontent.com/9216702/104560015-8f30bc00-5645-11eb-9cbd-b4a490dcc826.png)

**Platform:**
Google Chrome 87 on Windows 10 20H2 
Syspass running on Ubuntu 18.04

**Additional context**
According to this Line:
https://github.com/nuxsmin/sysPass/blob/aa5ff5548bfbc80445516c5a129f829f8b7e7205/public/js/app-util.js#L389
Uppercase Letters will be ignored if Lowercase Letters are not Selected.

However This Line:
https://github.com/nuxsmin/sysPass/blob/aa5ff5548bfbc80445516c5a129f829f8b7e7205/public/js/app-util.js#L447
Will check Uppercase even if there are no Lowercase Letters, Resulting in an Infinite Loop.
https://github.com/nuxsmin/sysPass/blob/aa5ff5548bfbc80445516c5a129f829f8b7e7205/public/js/app-util.js#L466

Thank you for your Time.

**Comment by nuxsmin** [comment]
Hello,

this issue was solved in latest release. Thanks for the feedback!

Regards
