### ISSUE TITLE
The 2FA plugin is not enabled

### ISSUE THREAD

**Issue by opaulino** [nuxsmin/sysPass#1645]
I have the Syspass 3.2 version and I am trying to install the 2FA plugin, it installs without problem but when I go to the plugins menu it appears disabled, I click enable and it is not enabled.

The 2FA version is v2.1.0

I need your help.

**Comment by nuxsmin** [comment]
Hello,

you need to install the v2.2 version of the plugin in order to work with sysPass v3.2

Regards
