### ISSUE TITLE
Master Password can't be updated on 3.2.1

### ISSUE THREAD

**Issue by mebuffet** [nuxsmin/sysPass#1648]
**sysPass Version**
3.2 (321.21011601)

**Describe the bug**
I created a new syspass instance in the most updated version at the moment (3.2.1). After performing the initial configuration, I imported the xml of the secrets stored in another syspass instance (version 2.1) with the old master key. After performing the import, I confirmed that the current master key changed to the old one during the import process and, after that, I tried to make the change again, however, because the fields are "blocked" I was not successful.

**To Reproduce**
1. Sign in with 'syspass master admin'
2. Go to 'configuration'
2. Click on 'encryption'
3. Scroll down to 'master password'
4. See the error on fields 'current master password', 'new master password' and 'new master password (repeat)'. 

**Expected behavior**
Change the master password by filling in the fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/22630685/105755150-ab780700-5f29-11eb-9e4e-d2816e184764.png)

**Event log**
Only one error being presented, however, does not seem to be related to the problem described.

```
[2021-01-25 19:25:23] syspass.EXCEPTION: logger {"message":"Integrity check failed.
#0 /var/www/html/vendor/defuse/php-encryption/src/Crypto.php(151): Defuse\Crypto\Crypto->decryptInternal()
#1 /var/www/html/vendor/defuse/php-encryption/src/KeyProtectedByPassword.php(91): Defuse\Crypto\Crypto->decryptWithPassword()
#2 /var/www/html/lib/SP/Core/Crypt/Crypt.php(83): Defuse\Crypto\KeyProtectedByPassword->unlockKey()
#3 /var/www/html/lib/SP/Core/Crypt/Crypt.php(110): SP\Core\Crypt\Crypt->unlockSecuredKey()
#4 /var/www/html/lib/SP/Core/Crypt/Vault.php(90): SP\Core\Crypt\Crypt->decrypt()
#5 /var/www/html/lib/SP/Services/Crypt/SecureSessionService.php(85): SP\Core\Crypt\Vault->getData()
#6 /var/www/html/app/modules/web/Init.php(278): SP\Services\Crypt\SecureSessionService->getKey()
#7 /var/www/html/app/modules/web/Init.php(155): SP\Modules\Web\Init->initSession()
#8 /var/www/html/lib/SP/Bootstrap.php(232): SP\Modules\Web\Init->initialize()
#9 [internal function]: SP\Bootstrap->SP\{closure}()
#10 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func()
#11 /var/www/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback()
#12 /var/www/html/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch()
#13 /var/www/html/lib/Base.php(75): SP\Bootstrap->run()
#14 /var/www/html/index.php(28): require(String)","caller":"N/A"}
```

**Platform (please complete the following information):**
 - OS: CentOS 
 - OS Version: 7.9.2009 x64
 - OS Architecture: x64
 - Browser: Chrome
 - Browser Version: 88.0.4324.104
 - Browser Architecture: x64

**Additional context**
This problem does not occur in version 2.1.16.

**Comment by fgendorf** [comment]
Hi @mebuffet , you must enter em maintenance mode to enable this fields...
