### ISSUE TITLE
Error importando base de datos después de un backup

### ISSUE THREAD

**Issue by lfreina** [nuxsmin/sysPass#165]
Estoy haciendo una nueva instalación de mi sysPass v1.0.9. Realicé un backup con la versión 1.0.9.

Intenté instalar la nueva versión 1.2 pero me dice que la base de datos es muy vieja. 

Bien, instalé la misma versión 1.0.9 de syspass e intenté importar la base de datos pero obtengo un error: 

> "Error while retrieving configuration
> Unknown column 'vacValue' in 'field list'"

Instalé luego la versión 1.1 y la última versión 1.1.2.24 pero obtengo el mismo error. 

¿Estoy haciendo algo mal al importar los datos desde la base de datos? 

Saludos,

Fernando

**Comment by nuxsmin** [comment]
Buenas, si he entendido bien, quieres actualizar la versión 1.0.9 a 1.2, no?

Este proceso es automático, sólo tienes que descargar la versión 1.2 y copiar el archivo config.php de la versión anterior a la nueva. Ten en cuenta de hacer una copia de seguridad de todo (Aplicación y BD).

La importación desde PHPpms es para instalaciones más antiguas.

**Comment by lfreina** [comment]
Pues no exactamente nuxsmin. 

El problema es que quiero migrar todo syspass para un nuevo servidor. Al probar con la última versión me dio un error de importación diciendo que la versión era muy vieja. 

Instalé la misma versión 1.0.9 en el nuevo servidor y quice importar la base de datos pero me dió el error anterior. 
¿Hay algún proceso para mover toda la base de datos al nuevo servidor? Por el momento intenté utilizar la herramienta de importación pero no funcióno. Eso es lo que me da problemas. ¿No se puede utilizar la importación con las nuevas versiones entonces?

**Comment by nuxsmin** [comment]
Si lo que quieres es mover la instalación existente, sólo tienes que copiar el directorio de sysPass e importar la copia de la BD (que se encuentra en el directorio de backups) con las herramientas de mysql: 

<code>mysql -p < copia_bd.sql</code>

Ten en cuenta de crear el usuario/clave de conexión para sysPass (se encuentra en config.php) y darle permisos sobre la BD importada.

Tengo pendiente de realizar un HowTo para restaurar/mover sysPass

**Comment by nuxsmin** [comment]
Comentarte que la herramienta de importación es sólo para PHPpms (sysPass se llamaba antes así), para las nuevas versiones no existe importación.

**Comment by lfreina** [comment]
¡Perfecto! Muchas gracias por la información. 

Lo de los permisos en la base de datos era lo que me faltaba. 

Yo podría ayudarte a hacer el How To si te interesa. En inglés y español.

Saludos,

Fernando

**Comment by lfreina** [comment]
Dos pregunta más Rubén.

1. ¿En qué formato te sirve el manual para la restauración?
2. Al intentar actualizar de la versión 1.0.9 a la 1.2 me dice que el master password no es correcto y me corrompe toda la base de datos. He restaurado la base de datos y todo vuelve a funcionar en la versión 1.0.9. Incluso verifiqué mi master password con otro issue que estaba abierto: 
> https://github.com/nuxsmin/sysPass/issues/97
Y el master password es correcto. 

¿Sabes qué estoy haciendo mal? ¿Quieres que abra otro issue para esto?

Saludos,

Fernando

**Comment by nuxsmin** [comment]
Hola Luis, 

en primer lugar, el formato del manual me vale cualquiera ya que he de adaptarlo al formato de la wiki.

Con respecto a la actualización, la bd no se corrompe ya que las claves no se modifican, lo que ocurre es que no se guardará correctamente la clave maestra y por ello falla al desencriptar las claves. Tengo que realizar una prueba desde dicha versión, ya que he probado desde la 1.1

También puedes probar a actualizar y posteriormente cambiar la clave maestra sin modificar las cuentas.

Saludos!

**Comment by nuxsmin** [comment]
Hola Luis, ya está solucionado el fallo de actualización. Era un error en la actualización de un campo de la tabla de usuarios, por lo que siempre ndicaba que la clave maestra era incorrecta. Puedes descargarlo desde aquí: https://github.com/nuxsmin/sysPass/archive/master.zip

**Comment by lfreina** [comment]
Ya lo he probado Rubén. ¡Funciona de maravilla! 

Muchas gracias por la ayuda y feliz fin de semana.

// Fernando

**Comment by nuxsmin** [comment]
Perfecto!! Gracias ;)
