### ISSUE TITLE
No es posible conectarse a la base de datos

### ISSUE THREAD

**Issue by Dan00127** [nuxsmin/sysPass#1658]
**sysPass Version**
syspass version 3.2

**Describe the question**
Buen día e intentado acceder a syspass por web pero me aparece este error " No es posible conectar con la BD" entonces pido la ayuda de alguien que sepa como puedo solucionarlo. Gracias.

**Screenshots**
![image](https://user-images.githubusercontent.com/78495723/108539515-1bba4400-72ae-11eb-8c62-4783af8ebdac.png)

**Platform (please complete the following information):**
 - OS: Centos
 - OS Version: 7 
 - Browser: Chrome

**Comment by nuxsmin** [comment]
Hola,

podrías revisar el log de sysPass? (archivo `app/config/syspass.log`). Parece que la configuración de la base de datos es incorrecta.

Saludos!
