### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by sikas89** [nuxsmin/sysPass#1659]
**sysPass Version**
Can be found on `Config -> Information` tab
Latest

**Describe the question**
A clear and concise description.
Trying to build from scratch on a VM. Getting the error:

SQLSTATE[HY000]: General error: 1396 Operation DROP USER failed for 'sp_60323d16b9f7d'@'%'

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android] Linux Ubuntu
 - OS Version 20.04 LTS
 - Browser [e.g. Firefox, Chrome] Chrome

**Additional context**

Steps taken to deploy:

sudo apt upgrade
sudo apt update
sudo apt install libapache2-mod-php7.4 php7.4 php7.4-cgi php7.4-cli php7.4-common php7.4-curl php7.4-dev php7.4-gd php7.4-gmp php7.4-json php7.4-ldap php7.4-mysql php7.4-odbc php7.4-opcache php7.4-pgsql php7.4-pspell php7.4-readline php7.4-snmp php7.4-sqlite3 php7.4-tidy php7.4-xml php7.4-xmlrpc zip unzip mariadb-server php7.4-mbstring
sudo service apache2 restart
sudo mysql_secure_installation
sudo mkdir /var/www/html/syspass
cd /var/www/html/syspass
sudo git clone https://github.com/nuxsmin/sysPass.git /var/www/html/syspass
sudo chown syspass -R /var/www/html/syspass
sudo chmod 750 /var/www/html/syspass/app/config /var/www/html/syspass/app/backup
vi install_composer.sh

#!/bin/sh
EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
then
    >&2 echo 'ERROR: Invalid installer signature'
    rm composer-setup.php
    exit 1
fi

php composer-setup.php --quiet
RESULT=$?
rm composer-setup.php
exit $RESULT

chmod +x install_composer.sh
./install_composer.sh
php composer.phar install --no-dev
sudo chown www-data -R /var/www/html/syspass

sudo mariadb
CREATE USER syspassdb@localhost IDENTIFIED BY 'syspassdb';
GRANT ALL PRIVILEGES ON *.* TO syspassdb@localhost IDENTIFIED BY 'syspassdb';
FLUSH PRIVILEGES;

**Comment by nuxsmin** [comment]
Hello,

are you running sysPass instance along with the database?. Could you provide some log messages? (within `app/config/syspass.log` file)

Regards

**Comment by sikas89** [comment]
Hello @nuxsmin 
Database is running on the same server as the SysPass instance .. Logs are below:

tail -f syspass.log

> [2021-03-16 15:40:24] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
> [2021-03-16 15:40:24] syspass.INFO: logger {"message":"Loaded icons cache","caller":"SP\Core\UI\Theme::initIcons"}
> [2021-03-16 15:40:24] syspass.INFO: logger {"message":"Loaded actions cache","caller":"SP\Core\Acl\Actions::loadCache"}
> [2021-03-16 15:40:24] syspass.EXCEPTION: logger {"message":"SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'syspassdb'@'localhost' to database 'syspassdb'
> #0 /var/www/html/syspass/lib/SP/Services/Install/MySQL.php(243): PDO->exec()
> #1 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(279): SP\Services\Install\MySQL->createDatabase()
> #2 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(187): SP\Services\Install\Installer->setupDb()
> #3 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(99): SP\Services\Install\Installer->install()
> #4 /var/www/html/syspass/app/modules/web/Controllers/InstallController.php(94): SP\Services\Install\Installer->run()
> #5 [internal function]: SP\Modules\Web\Controllers\InstallController->installAction()
> #6 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array()
> #7 [internal function]: SP\Bootstrap->SP\{closure}()
> #8 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func()
> #9 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback()
> #10 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch()
> #11 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run()
> #12 /var/www/html/syspass/index.php(28): require(String)","caller":"N/A"}
> [2021-03-16 15:40:24] syspass.EXCEPTION: logger {"message":"SQLSTATE[HY000]: General error: 1396 Operation DROP USER failed for 'sp_6050d1682c03f'@'%'
> #0 /var/www/html/syspass/lib/SP/Services/Install/MySQL.php(327): PDO->exec()
> #1 /var/www/html/syspass/lib/SP/Services/Install/MySQL.php(261): SP\Services\Install\MySQL->rollback()
> #2 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(279): SP\Services\Install\MySQL->createDatabase()
> #3 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(187): SP\Services\Install\Installer->setupDb()
> #4 /var/www/html/syspass/lib/SP/Services/Install/Installer.php(99): SP\Services\Install\Installer->install()
> #5 /var/www/html/syspass/app/modules/web/Controllers/InstallController.php(94): SP\Services\Install\Installer->run()
> #6 [internal function]: SP\Modules\Web\Controllers\InstallController->installAction()
> #7 /var/www/html/syspass/lib/SP/Bootstrap.php(240): call_user_func_array()
> #8 [internal function]: SP\Bootstrap->SP\{closure}()
> #9 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func()
> #10 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback()
> #11 /var/www/html/syspass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch()
> #12 /var/www/html/syspass/lib/Base.php(75): SP\Bootstrap->run()
> #13 /var/www/html/syspass/index.php(28): require(String)","caller":"N/A"}
>

**Comment by sikas89** [comment]
This is after a clean install. Below is the steps done via CLI:

> sudo apt upgrade
> sudo apt update
> sudo apt install libapache2-mod-php7.4 php7.4 php7.4-cgi php7.4-cli php7.4-common php7.4-curl php7.4-dev php7.4-gd php7.4-gmp php7.4-json php7.4-ldap php7.4-mysql php7.4-odbc php7.4-opcache php7.4-pgsql php7.4-pspell php7.4-readline php7.4-snmp php7.4-sqlite3 php7.4-tidy php7.4-xml php7.4-xmlrpc zip unzip mariadb-server php7.4-mbstring
> sudo service apache2 restart
> sudo mysql_secure_installation
> sudo mkdir /var/www/html/syspass
> cd /var/www/html/syspass
> sudo git clone https://github.com/nuxsmin/sysPass.git /var/www/html/syspass
> sudo chown syspass -R /var/www/html/syspass
> sudo chmod 750 /var/www/html/syspass/app/config /var/www/html/syspass/app/backup
> vi install_composer.sh
> 
> #!/bin/sh
> EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
> php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
> ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
> 
> if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
> then
>     >&2 echo 'ERROR: Invalid installer signature'
>     rm composer-setup.php
>     exit 1
> fi
> 
> php composer-setup.php --quiet
> RESULT=$?
> rm composer-setup.php
> exit $RESULT
> 
> chmod +x install_composer.sh
> ./install_composer.sh
> php composer.phar install --no-dev
> sudo chown www-data -R /var/www/html/syspass
> 
> sudo mariadb
> CREATE USER syspassdb@localhost IDENTIFIED BY '****';
> GRANT ALL PRIVILEGES ON *.* TO syspassdb@localhost IDENTIFIED BY '****';
> FLUSH PRIVILEGES;

**Comment by nuxsmin** [comment]
@sikas89 

It seems you've created a DB user for syspass:

```
CREATE USER syspassdb@localhost IDENTIFIED BY 'syspassdb';
GRANT ALL PRIVILEGES ON . TO syspassdb@localhost IDENTIFIED BY 'syspassdb';
```

So you need to use such user to setup sysPass.

Regards

**Comment by sikas89** [comment]
> @sikas89
> 
> It seems you've created a DB user for syspass:
> 
> ```
> CREATE USER syspassdb@localhost IDENTIFIED BY 'syspassdb';
> GRANT ALL PRIVILEGES ON . TO syspassdb@localhost IDENTIFIED BY 'syspassdb';
> ```
> 
> So you need to use such user to setup sysPass.
> 
> Regards

Hello,

I already did that in the installation page, but for some reason, it shows an error with the username I provided in the error log

**Comment by nuxsmin** [comment]
Hello @sikas89 ,

in order to use a self provided user, you need to go through hosting mode: https://syspass-doc.readthedocs.io/en/3.1/installing/hostingmode.html

Regards
