### ISSUE TITLE
No funciona la búsqueda

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#166]
Hola, recientemente actualicé a la última versión  1.2.0.08, si bien actualizó al parecer ok, ahora no funcionan las búsquedas, a veces dice consulta inválida, y si no, nunca encuentra nada, o sea busco cualuqier cosa, y siempre veo lo mismo (todo.)

No encontré nada en los logs de apache. 

Algo que pueda vverificar ?

**Comment by nuxsmin** [comment]
Hola, es extraño lo que comentas, ya que no me ha pasado antes, de hecho puedes probar la demo que tiene la misma versión.

Lo de consulta inválida puede ser debido a que en cada búsqueda se regenera un token de seguridad, por lo que si el cliente no lo genera rápido, la consulta falla.

Me puedes dar información sobre el entorno?

Has recargado la página para refrescar la caché de javascript?

**Comment by gabrielsoltz** [comment]
Al borrar la cache, a veces vuelve a funcionar, otras no, pero despues de un rato de usarlo, falla nuevamente esa funcionalidad. Además, no está matcheando la búsqueda con el campo URL/IP, cuando busco por IP.

El entorno es:
root@syspass:[/home/admin]:cat /etc/*-release
CentOS Linux release 7.1.1503 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.1.1503 (Core) 
CentOS Linux release 7.1.1503 (Core) 


root@syspass:[/home/admin]:php -v
PHP 5.4.16 (cli) (built: Jun 23 2015 21:17:27) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

root@syspass:[/home/admin]:httpd -v
Server version: Apache/2.4.6 (CentOS)
Server built:   Aug 24 2015 18:11:25

Intenté encontrar una condición que lo haga aparecer: cambié de browser, borré cache, busqué errores en los logs, nada... 

Sospecho que quizas el update dejó algo mal en la base de datos o en algún archivo, podría ser ?

**Comment by GastonLex** [comment]
Mismo problema con la búsqueda luego del upgrade a versión 1.2.0.08.
Adjunto los mismos datos :
# /var/www$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.1 LTS"

# php -v
PHP 5.3.10-1ubuntu3.4 with Suhosin-Patch (cli) (built: Sep 12 2012 19:00:43) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

# /usr/sbin/apache2 -V
Server version: Apache/2.2.22 (Ubuntu)
Server built:   Feb 13 2012 01:37:27
Server's Module Magic Number: 20051115:30
Server loaded:  APR 1.4.6, APR-Util 1.3.12
Compiled using: APR 1.4.5, APR-Util 1.3.12
Architecture:   32-bit
Server MPM:     Prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APACHE_MPM_DIR="server/mpm/prefork"
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=128
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_LOCKFILE="/var/run/apache2/accept.lock"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"

El problema pareciera presentarse al intentar ingresar caracteres numéricos al principio de la caja de búsqueda, o al ingresar números con "."

**Comment by nuxsmin** [comment]
Buenas, sí, he detectado que al introducir un número con "," o una dirección IP en el campo de búsqueda el analizador de parámetros de formularios lo interpreta como un número entero, por lo que la cadena pasada en la consulta a la BD se pasa como un entero perdiendo la parte decimal.

En la siguiente compilación estará corregido.

Gracias por la información.

**Comment by GastonLex** [comment]
Muchas Gracias por la pronta respuesta. Quedamos atentos a la próxima compilación.

**Comment by gabrielsoltz** [comment]
Hola, al parecer el problema de los puntos para las direcciones ip se ha solucionado, pero sigue habiendo algún tipo de problema con la búsqueda. 
Depsues de buscar una o dos cosas, se rompe, a veces encuentra a veces no, a veces da consulta invalida. Intento hacer ctrl f5 para limpiar cache, y aparece un 0 en la barra de búsqueda, pero no se soluciona.

**Comment by gabrielsoltz** [comment]
se puede ajustar el timepo de generacion de tokens o algo por el estilo ? me parece que viene por ese lado.

**Comment by gabrielsoltz** [comment]
La primera vez después de loguearte, funciona. 
Después de esa, ya funciona de manera errática y sin sentido: a veces funciona, a veces no, a veces da consulta invalida.

**Comment by GastonLex** [comment]
Luego de la actualización a "Versión sysPass 	1.2.0.09" encuentro el mismo comportamiento. 
Cuando intento buscar una dirección IP, al momento de ingresar el  "."  (por ejm : 192.xxx.xxx) sale "CONSULTA INVÁLIDA" y deja de funcionar cualquier búsqueda que intente realizar.

**Comment by gabrielsoltz** [comment]
Hola, alguna recomendación sobre este tema ?

**Comment by nuxsmin** [comment]
Hola @gabrielsoltz y @GastonLex , al cerrar la incidencia se me había pasado responder..

Estoy modificando el comportamiento de las búsquedas para tratar de solucionar ese problema. He estado haciendo pruebas (con la versión actual) y he observado que algunas veces da "consulta inválida", pero la búsqueda sigue funcionando.

En cuanto tenga probada la nueva puncionalidad os la comento para probarla.

Saludos!

**Comment by GastonLex** [comment]
Muchas gracias, esperamos atentos.

Un Saludo

Gastón

Date: Mon, 28 Dec 2015 13:59:42 -0800

**Comment by nuxsmin** [comment]
Buenas, podéis probar el último commit?

https://github.com/nuxsmin/sysPass/archive/master.zip
