### ISSUE TITLE
AD user Keeps getting wrong Login message

### ISSUE THREAD

**Issue by jr-RXcode** [nuxsmin/sysPass#1660]
**sysPass Version**
SysPass 3.2

**Describe the question**
I have syspass configured with Active Directory for user Authentication. The issue I have is that when we update our AD password and forget to login to syspass and after serveral AD password changes the user get locked out of syspass. They keep getting "Wrong Login". At this point the user doesn't remember what their password was two password changes before. How can we updated the user password in syspass. 

I tried deleting the user that keeps getting the "Wrong Login" message from syspass and re-synced Active directory to import the user. The user was imported but keeps getting the "Wrong login" message. They are not getting the "Previous Password" prompt or to enter the master password. They only get the "Wrong Login". 

It seems that if you change your AD password multiple times and forget to login to Syspass to update the password using the previous password then the user get "Wrong Login" message and is unable to update the password.

If you login to Syspass right after an AD password update you are able to log in providing the previous password. 

**Screenshots**

**Platform (please complete the following information):**
 - OS: linux
 - OS Version
 - Browser Chrome

**Additional context**
[2021-02-25 19:30:43] syspass.EXCEPTION: logger {"message":"Wrong login
#0 /var/www/html/sysPass/lib/SP/Services/Auth/LoginService.php(160): SP\Services\Auth\LoginService->authLdap(Object(SP\Providers\Auth\Ldap\LdapAuthData))
#1 /var/www/html/sysPass/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#2 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#3 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#7 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#8 /var/www/html/sysPass/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#9 /var/www/html/sysPass/index.php(28): require(String)","caller":"N/A"}

**Comment by nuxsmin** [comment]
Hello,

that is the intended behavior, since sysPass uses several known user data to generate the encryption key, so if the user, after an AD password change (or several ones), doesn't remember the previous password, sysPass will require a temporary master password or the real master password in order to save it again (encrypted) for later use. https://syspass-doc.readthedocs.io/en/3.1/application/encryption.html#login-process

Regards.

**Comment by jr-RXcode** [comment]
Yes, I understand that is the intended behavior, but I was expecting the user to get a prompt to enter the temp Master password or Master password along with their new password, but they are not getting that prompt they are only getting the message saying "Wrong Login" Is there a way to clear a password when connected to AD? I have removed the user added the user back but I can't get syspass to prompt for a master password.
