### ISSUE TITLE
Custom Auth

### ISSUE THREAD

**Issue by ppcharli** [nuxsmin/sysPass#1661]
**sysPass Version**
v3.2.1

**Describe the question**
Me gustaría añadir una auth personalizada a sysPass

El proceso sería el siguiente:
    1. El usuario se autentica con otro método,  generándose en el servidor un token que contiene el usuario.
    2. Se llama al login de sysPass pasándole el token generado en 1  (en lugar del user/pass actual)
    3. sysPass (en el servidor con php) accede al token y dar por autenticado al usuario que contiene.

¿Alguien puede darme alguna indicación de como lo podría implementarlo en sysPass?

**Platform (please complete the following information):**
 - OS: Linux

Gracias

**Comment by nuxsmin** [comment]
Hola,

para este propósito puedes utilizar Auth Basic, que mediante una cabecera HTTP le pasa a sysPass el usuario y clave (la clave puede ser un token estático para ese usuario).

La clave/token es necesaria/o porque se utiliza, junto con otros datos, para generar una llave de encriptación para la clave maestra, por lo que cada usuario tiene que tener una clave/token diferente, pero que no cambie con cada login, para que no solicite de nuevo la clave maestra. https://syspass-doc.readthedocs.io/en/3.1/application/encryption.html#login-process

Saludos!
