### ISSUE TITLE
Como cifrar las claves de las cuentas 

### ISSUE THREAD

**Issue by Dan00127** [nuxsmin/sysPass#1663]
**sysPass Version**
3.2

**Describe the question**
Buen día, 
Quisiera saber si se pude cifrar las claves que uno le asigna a una cuenta, si hay alguna opción de configuración para habilitar el cifrado, por que parece inseguro que sean tan visibles esos datos, si alguien sabe seria de gran ayuda, Gracias. 
**Screenshots**

![image](https://user-images.githubusercontent.com/78495723/109530741-0b138600-7a85-11eb-971d-d8e1b4299131.png)

**Platform (please complete the following information):**
 - OS: centos
 - OS 7
 - Browser , Chrome

**Comment by nuxsmin** [comment]
Hola,

las claves de las cuentas están siempre cifradas, sólo se ven en claro cuando se visualizan.

Saludos!
