### ISSUE TITLE
Unable to delete imported LDAP user

### ISSUE THREAD

**Issue by Hr46ph** [nuxsmin/sysPass#1674]
**sysPass Version**
3.1 (312.20030701)
Config: 312.20030701
App: 312.20030701
DB: 312.20030701

**Describe the bug**
Cannot delete LDAP imported users after changing or removing owner references.

**To Reproduce**
Import accounts from LDAP
User XYZ has created, changed, moved and deleted accounts
Admin cannot delete imported user account XYZ and receives error message:
EXCEPTION] [SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails

Admin searches for 'owner:"XYZ"', removes all from ACCOUNTS(H) and bulk edits all ACCOUNTS where owner is set to XYZ and changes them to himself (admin).

Admin returns to remove LDAP account and still receives the above error message.

**Expected behavior**
After changing and deleting all found references to the user XYZ, I expect to be able to succesfully remove an LDAP user.

**Event log**
S[Tue Mar 16 10:28:08.338492 2021] [:error] [pid 22] [client 10.0.104.62:38404] [EXCEPTION] [SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`Account`, CONSTRAINT `fk_Account_userEditId` FOREIGN KEY (`userEditId`) REFERENCES `User` (`id`))\n#0 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(235): PDOStatement->execute()\n#1 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(175): SP\\Storage\\Database\\Database->prepareQueryData(Object(SP\\Storage\\Database\\QueryData))\n#2 /var/www/html/sysPass/lib/SP/Repositories/User/UserRepository.php(187): SP\\Storage\\Database\\Database->doQuery(Object(SP\\Storage\\Database\\QueryData))\n#3 /var/www/html/sysPass/lib/SP/Services/User/UserService.php(194): SP\\Repositories\\User\\UserRepository->delete(Integer)\n#4 /var/www/html/sysPass/app/modules/web/Controllers/UserController.php(300): SP\\Services\\User\\UserService->delete(Integer)\n#5 [internal function]: SP\\Modules\\Web\\Controllers\\UserController->deleteAction(Integer)\n#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)\n#7 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#8 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#9 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route),Object(Klein\\DataCollection\\RouteCollection),Array)\n#10 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))\n#11 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap->run(Object(DI\\Container))\n#12 /var/www/html/sysPass/index.php(28): require(String)] N/A, referer: https://syspass.mst.proxy.nl/index.php?r=index
[Tue Mar 16 10:28:08.338807 2021] [:error] [pid 22] [client 10.0.104.62:38404] [EXCEPTION] [Integrity constraint\n#0 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(175): SP\\Storage\\Database\\Database->prepareQueryData(Object(SP\\Storage\\Database\\QueryData))\n#1 /var/www/html/sysPass/lib/SP/Repositories/User/UserRepository.php(187): SP\\Storage\\Database\\Database->doQuery(Object(SP\\Storage\\Database\\QueryData))\n#2 /var/www/html/sysPass/lib/SP/Services/User/UserService.php(194): SP\\Repositories\\User\\UserRepository->delete(Integer)\n#3 /var/www/html/sysPass/app/modules/web/Controllers/UserController.php(300): SP\\Services\\User\\UserService->delete(Integer)\n#4 [internal function]: SP\\Modules\\Web\\Controllers\\UserController->deleteAction(Integer)\n#5 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array,Array)\n#6 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#7 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure),Object(Klein\\Request),Object(Klein\\Response),Object(Klein\\ServiceProvider),Object(Klein\\App),Object(Klein\\Klein),Object(Klein\\DataCollection\\RouteCollection),Array)\n#8 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route),Object(Klein\\DataCollection\\RouteCollection),Array)\n#9 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))\n#10 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap->run(Object(DI\\Container))\n#11 /var/www/html/sysPass/index.php(28): require(String)] N/A, referer: https://syspass.mst.proxy.nl/index.php?r=index
[Tue Mar 16 10:28:08.338871 2021] [:error] [pid 22] [client 10.0.104.62:38404] [EXCEPTION] [(P) SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`Account`, CONSTRAINT `fk_Account_userEditId` FOREIGN KEY (`userEditId`) REFERENCES `User` (`id`))\n#0 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(235): PDOStatement->execute()\n#1 /var/www/html/sysPass/lib/SP/Storage/Database/Database.php(175): SP\\Storage\\Database\\Database->prepareQueryData(Object(SP\\Storage\\Database\\QueryData))\n#2 /var/www/html/sysPass/lib/SP/Repositories/User/UserRepository.php(187): SP\\Storage\\Database\\Database->doQuery(Object(SP\\Storage\\Database\\QueryData))\n#3 /var/www/html/sysPass/lib/SP/Services/User/UserService.php(194): SP\\Repositories\\User\\UserRepository->delete(12)\n#4 /var/www/html/sysPass/app/modules/web/Controllers/UserController.php(300): SP\\Services\\User\\UserService->delete(12)\n#5 [internal function]: SP\\Modules\\Web\\Controllers\\UserController->deleteAction(12)\n#6 /var/www/html/sysPass/lib/SP/Bootstrap.php(240): call_user_func_array(Array, Array)\n#7 [internal function]: SP\\Bootstrap->SP\\{closure}(Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#8 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\\Request), Object(Klein\\Response), Object(Klein\\ServiceProvider), Object(Klein\\App), Object(Klein\\Klein), Object(Klein\\DataCollection\\RouteCollection), Array)\n#9 /var/www/html/sysPass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\\Klein->handleRouteCallback(Object(Klein\\Route), Object(Klein\\DataCollection\\RouteCollection), Array)\n#10 /var/www/html/sysPass/lib/SP/Bootstrap.php(464): Klein\\Klein->dispatch(Object(Klein\\Request))\n#11 /var/www/html/sysPass/lib/Base.php(75): SP\\Bootstrap::run(Object(DI\\Container))\n#12 /var/www/html/sysPass/index.php(28): require('/var/www/html/s...')\n#13 {main}] N/A, referer: https://syspass.mst.proxy.nl/index.php?r=index
10.0.104.62 - - [16/Mar/2021:10:28:07 +0100] "GET /index.php?r=user/delete/12&sk=390093d3dea34e1648a09fa68e11cf8cc4ce4780&isAjax=1&_=1615886421900 HTTP/1.0" 200 884 "https://syspass.mst.proxy.nl/index.php?r=index" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0"

**Additional context**
Same issue, unsolved but closed:
https://github.com/nuxsmin/sysPass/issues/1482

**Comment by Hr46ph** [comment]
If you are able, please find a moment to help us out as its becoming a nuiciance for us, I have started creating local accounts to work around the fact that users cant login to syspass with their LDAP accounts anymore.

Thanks!

**Comment by nuxsmin** [comment]
Hello,

it seems that the user ID is being used in other accounts for giving access (permissions.

Regards.

**Comment by Hr46ph** [comment]
I'm sorry but what does that mean? Can you please explain a bit more detail? How can I fix this?
