### ISSUE TITLE
Change appearance and / or Colors

### ISSUE THREAD

**Issue by alek10c** [nuxsmin/sysPass#1675]
Hello and excuse my English.

I want to change the appearance of SYSPASS but in reality I have not been able to change this appearance, I am a little newbie to minify the css could you give me some advice please.

I also want to congratulate you for this great work, it would be great if you could add a chrome extension.

Thank you, I stay tuned.

**Comment by ThigSchuch** [comment]
I forked syspass and did a dark theme based on the github's dark theme.
You can get it from my repo since the bot didn't passed my PR.

**Comment by nuxsmin** [comment]
Hello @alek10c 

sysPass theme should be cloned and then modify the CSS files to set the desired color theme. You need to use SASS (https://sass-lang.com/documentation/syntax) for generating the CSS files and then minify them.

@ThigSchuch I've just left a comment on the PR. Thanks for your contribution!!

Regards
