### ISSUE TITLE
search accounts examples or better explanation

### ISSUE THREAD

**Issue by Hr46ph** [nuxsmin/sysPass#1676]
**sysPass Version**
3.1

**Describe the question**
The help on search is lacking examples, can you please explain how the search query with special operators like regex, is/not, and/or work?

I tried different ways to incorporate and/or and is/not, but the search results are always empty.

Basically, if I want to find all accounts not owned by admin, I try:
owner not:"admin"

This doesnt work.

How do I use these specials?

If its not possible this way, can you help me find another way to do this, short of using 'owner:"all other names that are not admin" to get this list?

Thanks for the help.

**Comment by nuxsmin** [comment]
Hello,

unfortunately such operation isn't implemented, so you can only search for accounts with the given owner.

Thanks for the feedback!
