### ISSUE TITLE
Instalation errors

### ISSUE THREAD

**Issue by stawiu** [nuxsmin/sysPass#169]
Hello i have just spent a day to start syspass on my WAMP, this was very frustrating thus i decided to share the findings. 
Im not too familiar with github maybe there is a better place to put this but i didnt find it.
FYI: Windows 7, Apache 2.4.9, MYSQL 5.6.17, PHP 5.5.12.
I would like to ask the code owner to update the file as follows:

FILE
Init.class.php

function setPaths()
NOW=       `   self::$SERVERROOT = substr($dir, 0, strripos($dir, '/'));`
CORRECTED=  `  self::$SERVERROOT = substr($dir, 0, strripos($dir, DIRECTORY_SEPARATOR));`

function loadClass($class)
NOW=          `  foreach (explode(':', get_include_path()) as $includePath) {`
CORRECTED=   `   foreach (explode(PATH_SEPARATOR, get_include_path()) as $includePath) {`

This is concerning windows only but it would be nice for it to work. I just got to installation page lets see how it goes from here maybe i will come back to add more :P ;)

**Comment by nuxsmin** [comment]
Hi, thanks so much for the feedback, I'll fix that behavior in the next build. 

As you could see, many parts of the code uses platform independent paths, but some could be missed.

Let me know if you found any more issues on the wamp installation.

Kind regards.
