### ISSUE TITLE
DB Account User without Mysql Admin right installation

### ISSUE THREAD

**Issue by s12321** [nuxsmin/sysPass#1691]
I'm in a environment without MySQL admin right.

Does anyone know what's the reason need to use Mysql Admin right for installation?

How to install sysPass without MySQL admin right?

Can I decide which database and user for sysPass to use, instead of create a new random user (SPxxxxxxxx) and password by sysPass in my database?

Thanks

**Comment by kovacs-andras** [comment]
Tick the "Hosting Mode" on the bottom of the setup screen. This is what you need, I guess.
https://syspass-doc.readthedocs.io/en/3.1/installing/hostingmode.html
