### ISSUE TITLE
Where to get the security code from when upgrading to 3.2.2

### ISSUE THREAD

**Issue by eppixx** [nuxsmin/sysPass#1694]
**sysPass Version**
old version: 3.0.4
new version: 3.2.2

**Describe the question**
Im updating to the new version and it greets me by asking for a security code and I don't know where to get this from. I looked in the docker logs but I haven't found anything.

**Platform (please complete the following information):**
 - OS: Ubuntu docker
 - OS Version: 20.04
 - Browser Firefox and Chrome

**Comment by machado666** [comment]
Hi there you need to check the Documentation, "9. Enter the upgrade key located in “…/app/config/config.xml” file within the “upgradeKey” tag"

**Comment by eppixx** [comment]
Thanks. I cant believe I missed the updating tab. For some reason I searched in the application tab only.

For those as blind as me:
The Documention for updating to 3.1 is [here](https://syspass-doc.readthedocs.io/en/3.1/updating/v3.1.html)
