### ISSUE TITLE
After Upgrade from 3.1 to 3.2 DB not changed

### ISSUE THREAD

**Issue by machado666** [nuxsmin/sysPass#1695]
**sysPass Version**
3.2 (322.21031301)

**Describe the question**
After Upgrade from 3.1 to 3.2 there was no upgrade process for the DB, is this normal?

**Screenshots**
![image](https://user-images.githubusercontent.com/2582247/116096313-18be4400-a6a1-11eb-9ed0-f38c542ea10a.png)

**Platform (please complete the following information):**
 - OS: Centos 8

**Comment by nuxsmin** [comment]
Hello,

yes it's normal, since database upgrades are not usually performed, and if so, sysPass will require an upgrade key to perform the upgrade.

Regards.
