### ISSUE TITLE
Error install 

### ISSUE THREAD

**Issue by maseht** [nuxsmin/sysPass#170]
Buenas Tardes Estimados, presento problemas con la instalación del syspass y adjunto el log el tema parece estar con la estructura de la tabla usrdata y no me es posible disfrutar de la aplicación.

/var/log/httpd/error_log

[Mon Nov 30 16:00:44 2015] [error] [client 192.168.11.119] Action: addUser -- Description: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'user_isAdminApp' at row 1(0);;SQL: 'INSERT INTO usrData SET user_name = :name,user_login = :login,user_email = :email,user_notes = :notes,user_groupId = :groupId,user_profileId = :profileId,user_mPass = \\'\\',user_mIV = \\'\\',user_isAdminApp = :isAdminApp,user_isAdminAcc = :isAdminAcc,user_isDisabled = :isDisabled,user_isChangePass = :isChangePass,user_pass = :pass,user_hashSalt = :salt,user_isLdap = 0', referer: http://192.168.11.215/sysPass_old/index.php
[Mon Nov 30 16:00:44 2015] [error] [client 192.168.11.119] INSERT INTO usrData SET user_name = :name,user_login = :login,user_email = :email,user_notes = :notes,user_groupId = :groupId,user_profileId = :profileId,user_mPass = '',user_mIV = '',user_isAdminApp = :isAdminApp,user_isAdminAcc = :isAdminAcc,user_isDisabled = :isDisabled,user_isChangePass = :isChangePass,user_pass = :pass,user_hashSalt = :salt,user_isLdap = 0, referer: http://192.168.11.215/sysPass_old/index.php
[Mon Nov 30 16:00:44 2015] [error] [client 192.168.11.119] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'user_isAdminApp' at row 1, referer: http://192.168.11.215/sysPass_old/index.php

**Comment by nuxsmin** [comment]
Hola, es raro el error que comentas ya que tanto la instalación como migración la he probado multitud de veces y ese problema nunca ha surgido.

Dime más datos sobre el entorno (versiones y SO)

Un saludo

**Comment by maseht** [comment]
La instalación se realizo desde cero con Centos 6.7 he tratado forzar la instalación de multiples formas incluso recurriendo a versiones anteriores y sin exito. La versión de syspass es la ultima y tambien la 1.1

Gracias por tu tiempo

**Comment by nuxsmin** [comment]
Buenas, parece que en la consulta para crear el usuario admin, los valores booleanos  (true o false) no son interpretados como 1 ó 0. 

Voy a revisar porqué pasa.

**Comment by nuxsmin** [comment]
http://evertpot.com/mysql-bool-behavior-and-php/

**Comment by maseht** [comment]
Estimado logre visualizar tu link y comprendo hacia donde va un poco el tema, sin embargo no vislumbro como podria solventar.

**Comment by nuxsmin** [comment]
Buenas, la solución provisional sería deshabilitar la opción STRICT_TRANS_TABLES en la configuración de mysql. Esto no afecta en absoluto a la bd, sólo es una restricción de cómo se tratan los datos de las consultas.

Saludos.
