### ISSUE TITLE
Failed to verify the sysPass user

### ISSUE THREAD

**Issue by nicksas** [nuxsmin/sysPass#1700]
sysPass-3.2.1

The following error appears during installation:

Failed to verify the sysPass user (sp_609155860ad13)
Please check the database connection user rights

Login data is correct.

I did not find where to change the user rights to the database
![image](https://user-images.githubusercontent.com/42756021/117017355-340dfc80-acfc-11eb-91eb-a9cf53d5ebb2.png)

**Comment by nuxsmin** [comment]
Hello, 

if you're trying to install sysPass by using your own database user, you need to use the Hosting Mode: https://syspass-doc.readthedocs.io/en/3.1/installing/hostingmode.html

Regards
