### ISSUE TITLE
Syspass no permite cargar archivos word, power point, excel

### ISSUE THREAD

**Issue by Dan00127** [nuxsmin/sysPass#1702]
**sysPass Version**
3.2

**Describe the question**
Buen día

Por favor me pueden ayudar he intentado subir archivos word, power point, excel,  pero syspass no me permite,  aparece el error mostrado en la captura, ya se habilito la subida y descarga de archivos y se eligieron los Tipos MIME. Pero sigue apareciendo el error y no comprendo porque.

**Screenshots**
![image](https://user-images.githubusercontent.com/78495723/117979619-bb5d0080-b2f8-11eb-8924-57332480ea63.png)

**Platform (please complete the following information):**
 - OS: [centos ]
 - OS Version 7
 - Browser [ Chrome]

**Additional context**

**Comment by nuxsmin** [comment]
Buenas,

es posible añadir nuevos tipos MIME en la configuración de sysPass.

Saludos!
