### ISSUE TITLE
Se puede Separar la Base de Datos de Syspass?

### ISSUE THREAD

**Issue by Dan00127** [nuxsmin/sysPass#1703]
**sysPass Version**
3.2

**Describe the question**
Buenas tardes, por favor me pueden ayudar  informando si se puede separar la DB de Syspass.

**Comment by nuxsmin** [comment]
Buenas,

sí, es posible, puedes ubicarla en otro servidor e indicar el DNS/IP del mismo al configurar por primera vez sysPass.

Saludos!

**Comment by Dan00127** [comment]
Hola Buenos dias,

Entiendo pero si ya se encuentra instalada y configurada no habrá forma de
separar la base de datos.

Gracias y quedo atenta a sus comentarios.
