### ISSUE TITLE
¿Hay conflictos entre sysPass y Debian 10?

### ISSUE THREAD

**Issue by FranTercenoVelez** [nuxsmin/sysPass#1704]
Buenos días,

Actualmente he montado la plataforma bajo Debian 9.13, versión la cual dejará de tener soporte.

He probado Debian 10 pero por más que me he peleado con esta versión no he conseguido echarla a andar. ¿Existe algún tipo de problema de compatibilidad entre sysPass y Debian 10? En la documentación oficial de sysPass no encuentro nada relacionado con Debian 10, solo con su versión 9.

Cualquier comentario sobre el conocimiento de esta situación sería de gran ayuda. Muchas gracias y un saludo.

**Comment by nuxsmin** [comment]
Buenas,

sysPass es compatible con PHP 7.3 <= 7.4, por lo que sí es compatible, ya que Debian 10 incluye PHP 7.3

Con respecto a la documentación, en breve la actualizaré para incluir Debian 10 ;)

Saludos!

**Comment by FranTercenoVelez** [comment]
Mil gracias por tu tiempo y respuesta.

Tras montar la plataforma en una Debian 9, le hice un upgrade de versión al S.O a la 10 y se adapta toda la instalación correctamente a la estructura ya realizada en la 9.

Un saludo!
