### ISSUE TITLE
Force HTTPS: still on port 80

### ISSUE THREAD

**Issue by cdorabiatto** [nuxsmin/sysPass#1707]
sysPass version 3.2 (322.21031301)
Config: 312.20030701
App: 312.20030701
DB: 312.20030701

I have installed syspass via the official tar.gz packages. I then enabled 'Force HTTPS', but something is weird.

When I connect to it (http://my-server), it redirects to https://my-server:80. Notice the :80, and my browser gives me error messages that this is not correct SSL. So it seems like something is still running on :80 that is not SSL (I guess the redirector)

Observe
You should have been redirected to https://my-server
You have been redirected to https://my-server:80
I think I may have found the issue, but I could be wrong. Basically, you're testing if :443 is not already the port, and want to set it. But you still set it to :80, which leads to this bug.

To reproduce:
Start with a default installation
Enable Force HTTPS => Save
The redir is being done by HAProxy >> redirect scheme https code 301 if !{ ssl_fc }
Set the url on Application URL

Screenshots
![1](https://user-images.githubusercontent.com/64544343/119344536-c7847e80-bc65-11eb-92d8-dc5941644161.png)
![2](https://user-images.githubusercontent.com/64544343/119344653-e8e56a80-bc65-11eb-8c58-c5b27bf4af1c.png)
![3](https://user-images.githubusercontent.com/64544343/119344905-3c57b880-bc66-11eb-9e42-cc4325fba82e.png)

 - OS: Red Hat 8
 - Browser: Firefox, Chrome

**Comment by nuxsmin** [comment]
Hello,

If you force to use https through a proxy/lb it will force the connection from the proxy to be https, rather than the connection from the client instead, so the good place to force the https connection is on the proxy/lb side.

The "Application URL" is used when generating URLs and you are accessing sysPass through a proxy/lb, because sysPass doesn't know which is the good URL for the user, as it only "sees" the proxy/lb connection.

Regards

**Comment by cdorabiatto** [comment]
> Hello,
> 
> If you force to use https through a proxy/lb it will force the connection from the proxy to be https, rather than the connection from the client instead, so the good place to force the https connection is on the proxy/lb side.
> 
> The "Application URL" is used when generating URLs and you are accessing sysPass through a proxy/lb, because sysPass doesn't know which is the good URL for the user, as it only "sees" the proxy/lb connection.
> 
> Regards

The HTTPS redirect is already being done via HAProxy, however, in the chrome inspector and in the syspass footer it shows me port 80 HTTP, what should I do to solve this?

**Comment by ubalzer** [comment]
any solution on this issue? have the same problem... try to build syspass in AWS with Fargate and RDS....
