### ISSUE TITLE
SSH from Syspass UI

### ISSUE THREAD

**Issue by FrancescoOriglia** [nuxsmin/sysPass#1708]
Hello,

I have a question, is it possible to connect to a linux server from the Syspass UI ?
Is there a plugin or something else that can provide this feature ?
I have seen the WIKI link feature, it would be great if we could do the same with SSH.

Sincerely,
Francesco Origlia

**Comment by nblount** [comment]
If you specify the URL/IP field as ssh://username@ipadress then you can click on the link and it will open in Putty (or another SSH client if you have one. You just need to enter the password.

Example:
ssh://admin@hostname.com
or
ssh://admin@192.168.1.1

**Comment by nuxsmin** [comment]
Hello,

unfortunately, this feature is not currently implemented in sysPass.

Regards.
