### ISSUE TITLE
Max file size is hardcoded when uploading files

### ISSUE THREAD

**Issue by cgarciaarano** [nuxsmin/sysPass#171]
Hi, we've seen that the max file size is hardcoded in `js/function.js`, line 668. 

```php
       dropfiles.filedrop({
            fallback_id: 'inFile',
            paramname: 'inFile',
            maxfiles: 1,
            maxfilesize: 1,
            allowedfileextensions: file_exts_ok,
            url: APP_ROOT + '/ajax/ajax_import.php',
            data: {
```

We needed to import a KeePass file of ~ 1.2 MB, so we changed `maxfilesize` to 2 and it worked. Would it be possible to use the setting `General -> Files -> Max File Size` ?

**Comment by nuxsmin** [comment]
Hi, you're right, I've missed to set it as the previous function "dropFile" where the filesize is set by the "maxsize" variable...

I'll fix it on the next build.

Thanks for the feedback ;)
