### ISSUE TITLE
Expire Passwords rule

### ISSUE THREAD

**Issue by Felsser** [nuxsmin/sysPass#1711]
Hello, 

we set in "preset values" "account.password" for our Profile "users"
"Forced"
"Priority": 1
Account Password Preset: 
min length 8 = working
Accounts password expiry Expire time 365 (days) = not working
Score 0 
Regular Expression: none

Although this is set, it accepts the account creation when the user just deletes the preset expire time by clicking on the x. 
Now we have a ton of passwords without expire time. Can I search for accounts without expire time and set a value?  

How can I prevent users from creating accounts without expire time? This seems like the correct place but it doesn't work. 

Thank you very much.

**Comment by Felsser** [comment]
could someone have a look into this?

**Comment by nuxsmin** [comment]
Hello,

account expiry time is set when you enable this setting on sysPass configuration.

Regards
