### ISSUE TITLE
upgrade 2.1 to 3.0.5 but old db is not recognized?

### ISSUE THREAD

**Issue by nturri1306** [nuxsmin/sysPass#1712]
hello  i' ve uptaded linux syspass 2.1 to 3.0.5 

have changed a config.xml file db but this is ignored ( always try to create a new )

where is the corret migrate procedure 

i've see db of new version is different exist any metod for migrate and recover data of 2.1 version?

**Comment by nturri1306** [comment]
now i've used password of dump  but have this msg 

where found security code?

![image](https://user-images.githubusercontent.com/11473051/122422127-31eebd00-cf8d-11eb-8935-fe3ec21b32cc.png)

**Comment by nturri1306** [comment]
now i've used password of dump but have this msg

where found security code?

![image](https://user-images.githubusercontent.com/11473051/122422519-8134ed80-cf8d-11eb-92bc-6b7826fd5670.png)

**Comment by nuxsmin** [comment]
Hello,

please checkout the doc for the upgrading procedure: https://syspass-doc.readthedocs.io/en/3.1/updating/index.html

Regards
