### ISSUE TITLE
upgradeKey  tag is empty why?

### ISSUE THREAD

**Issue by nturri1306** [nuxsmin/sysPass#1713]
hello i've config.xml of version 2.1 but this tag is empty 

when i try update to 3.05 system require this tag

**Comment by jconnary** [comment]
I also have this problem. Did you figure it out?

**Comment by nuxsmin** [comment]
Hello,

How are you doing the upgrade?. This key will be filled in when sysPass detects a major version upgrade, so it will block the app an then ask for this key in the upgrade page.

Regards
