### ISSUE TITLE
Set multiple LDAP server for authentication

### ISSUE THREAD

**Issue by xenofree** [nuxsmin/sysPass#1714]
**sysPass Version**
3.2 (322.21031301)
Config: 311.19121601
App: 311.19121601
DB: 311.19121601

**Describe the question**
Is it possible to set multiple LDAP for authentication is syspass.
I tried to add LDAP server comma sperated but that don't seems to work

![image](https://user-images.githubusercontent.com/35098906/122523344-3364c780-d017-11eb-9f7e-218d4aa39490.png)

**Comment by nuxsmin** [comment]
Hello,

unfortunately this feature is not developed. I suggest to use a A or CNAME DNS records to pick a random LDAP server by setting multiple servers for the same record.

Regards.
