### ISSUE TITLE
The Docs reference "vendor.tar.gz” on the releases page, but I can't find it. 

### ISSUE THREAD

**Issue by jlb-devo** [nuxsmin/sysPass#1717]
**sysPass Version**
N/A - I am working on a fresh install, but having trouble with the Documenation.

**Describe the question**
Multiple pages reference "vendor.tar.gz”, but I cannot find such a file anywhere in the Github repo release page. 
https://syspass-doc.readthedocs.io/en/3.1/search.html?q=vendor.tar.gz&check_keywords=yes&area=default"

Unrelated, but also: The installation for Debian 9 uses `sudo service apache2 restart` instead of systemctl. Any reason for this? I am adapting the instructions for Ubuntu, so I am working if this is a Debian 9 thing or if the instructions just haven't been updated from init to  systemd.  (There are also problems with the prerequisites on Ubuntu versus Debian 9, but I worked through most of those)

**Screenshots**
N/A - Fresh install

**Platform (please complete the following information):**
 - OS: [Will be Ubuntu
 - OS Version: Will be 20.04
 - Browser [e.g. Firefox, Chrome]

**Additional context**

**Comment by nuxsmin** [comment]
Hello,

sorry I forgot to upload the latest vendor file to the last release.

Thanks for the feedback!
