### ISSUE TITLE
Deshabilitar el login de syspass

### ISSUE THREAD

**Issue by uritomas** [nuxsmin/sysPass#1718]
**sysPass Version**
3.2.2

**Describe the question**
Buenos días, estamos intentando utilizar syspass y nos gustaria deshabilitar el login, ya que utilizamos nuestro propio single sign on. De forma que al acceder al index nos mande directamente a la home sin pasar por el login de syspass. Me podrías decir dónde puedo deshabilitarlo, llevo horas intentandolo. 

Gracias!

**Comment by nuxsmin** [comment]
Buenas,

no es posible deshabilitar el login, ya que en este proceso se utilizan los datos del usuario para obtener la clave maestra encriptada, para así poder visualizar la claves de las cuentas.

Saludos!
