### ISSUE TITLE
Erreur de connexion (BIND) LDAP ERROR: Can't contact LDAP server (-1)

### ISSUE THREAD

**Issue by steevegldev** [nuxsmin/sysPass#172]
I have a strange issue. Best part of users can login, but few can't. That's return wrong password and get this error:

Erreur de connexion (BIND)
LDAP ERROR: Can't contact LDAP server (-1)
LDAP DN: CN=LDAPUSER,CN=Users,DC=MYBUSINESS,DC=local

They are all in the same LDAP folder, I didn't specifie Group in sysPass setting.

Could be special char in password?

**Comment by nuxsmin** [comment]
Hi, can you tell me if the LDAP connection changes on every login?. This is a feature that runs when a DNS hostname is given for the LDAP server. You can see it the sysPass event log.

**Comment by steevegldev** [comment]
Not sure what you asking for. But I juste log once with one browser and logged again in Private mode. I got this in log (Commit version: 6f44f8c):


First:
1262	2015-12-09 09:34:11	Se connecter	SXXXXXXXXX	*.*.*.*	(LDAP)
Connexion au serveur : srvdc.mybusiness.local
Utilisateur : sxxxxxxxxx
Profil : Admin
Groupe : Admins


Second:
1265	2015-12-09 09:42:18	Se connecter	SXXXXXXXXX	*.*.*.*	(MySQL)
Utilisateur : sxxxxxxxxx
Profil : Admin
Groupe : Admins

1264	2015-12-09 09:42:18	ldapBind		*.*.*.*	Erreur de connexion (BIND)
LDAP ERROR: Can't contact LDAP server (-1)
LDAP DN: CN=LDAP,CN=Users,DC=mybusiness,DC=local

**Comment by steevegldev** [comment]
I enabled Debug, I took a look in error.log. what display is wrong:

ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /etc/ldap/ldap.conf
ldap_init: using /etc/ldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: trying ldaprc
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
ldap_create
ldap_url_parse_ext(ldap://dcfiles.mybusiness.local:389)
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP dcfiles.mybusiness.local:389
ldap_connect_to_host: getaddrinfo failed: Nom ou service inconnu
ldap_err2string
ldap_err2string


No Ideal where that "dcfiles" is from. this is not what is set in the config file.

**Comment by nuxsmin** [comment]
That is the behavior that I told you, if you provide an LDAP hostname (myserver.mydomain.com) it will search for other AD servers on your domain to make auth requests.

If you only set an ip address (your AD ip address), it will not search for other servers....

**Comment by steevegldev** [comment]
OK, didn't know that. I set a IP, Tested OK

Thanks!

**Comment by nuxsmin** [comment]
Great!! ;)

**Comment by nuxsmin** [comment]
Check your AD, it could you get some annoying issues with "ghost" servers...
