### ISSUE TITLE
/bin/sh: 1: Syntax error: end of file unexpected (expecting ")") after upgrade Debian to Buster

### ISSUE THREAD

**Issue by duven87** [nuxsmin/sysPass#1720]
Hi, I'm not sure if it's an automatic syspass cron or one done by hand because I didn't install the server at the time. 
But today I upgraded my syspass server from Stretch to Buster and in the crontabs there are 3 defined.
One of them now has a bad syntax since I upgraded.

Can you tell me how to fix it?

Thanks

`Subject: Cron <root@esp-pass> [ $(date -d +1day +
`

`0  23 28-31 * * [ $(date -d +1day +%d) -eq 1 ] && /source/backup.sh monthly
`

**Comment by nuxsmin** [comment]
Hello,

sysPass doesn't configure any cron job or automated backup.

Regards.
