### ISSUE TITLE
Correct string to define multiple AD DC servers for LDAP authentication

### ISSUE THREAD

**Issue by Wrightie** [nuxsmin/sysPass#1723]
**sysPass Version**
3.2 (322.21031301)

**Describe the question**
I have two AD DCs for failover authentication; both support LDAP.
I tried to set up the servers string in various ways (even referring to previous [apparently] working server strings in PHP LDAP contexts), like this:
_dc1.mydomain.local,dc2.mydomain.local
dc1.mydomain.local, dc2.mydomain.local
dc1.mydomain.local; dc2.mydomain.local_
They all work with dc1 running, but when dc1 is down and dc2 is up I get a BIND error.

**Platform (please complete the following information):**
 - OS: Ubuntu Server
 - OS Version: 20.04
 - Browser: any (Firefox, Chrome, Edge) -> not browser dependent

**What is the correct string format to let Syspass fall back to dc2 in case dc1 fails?**

Thank you in advance for your time and effort.

**Comment by nuxsmin** [comment]
Hello,

unfortunately such feature wasn't implemented, though there's a method that will pick a random server from the `_msdcs` zone:

Providers/Auth/Ldap/LdapMsAds.php
```
return count($adServers) > 0 ? array_rand($adServers) : $server;
```
Regards
