### ISSUE TITLE
No Russian language in options

### ISSUE THREAD

**Issue by TitovLab** [nuxsmin/sysPass#173]
Install latest version of sysPass but do not see russian language in options.
I can enable russian language in options after editing inc/Language.class.php:
    public static function getAvailableLanguages()
    {
        return array(
            'Español' => 'es_ES',
            'Català' => 'ca_ES',
            'English' => 'en_US',
            'Deutsch' => 'de_DE',
            'Magyar' => 'hu_HU',
'Russian' => 'ru_RU',
            'Français' => 'fr_FR'
        );
    }

Updated Russian translation send to your e-mail.

**Comment by nuxsmin** [comment]
Thank you!!, I'll enable Russian translation on next build
