### ISSUE TITLE
Small LDAP authentication issue on Ubuntu 20/PHP 7.4

### ISSUE THREAD

**Issue by stideswell** [nuxsmin/sysPass#1730]
**sysPass Version** 322.21031301

**Describe the bug**
Previously, with sysPass 3.0.4 on Ubuntu 18/PHP 7.2, I was able to specify my LDAP server as ...

`<ldapServer>ldaps://my-ldap-server-01.mydomain.com.au</ldapServer>`

... and this worked perfectly well.

I have found that under PHP 7.4 that this does not work and that this results in a clear-text LDAP (TCP 389) connection being made to the LDAP server (not startTLS). Simply restating the LDAP config as ....

`<ldapServer>ldaps://syd-ldap-proxy-01.brennanit.net.au:636</ldapServer>`

... resolved the issue, but not without expending half a day (or more) troubleshooting the issue. I suspect some subtle change (between PHP 7.2 and PHP 7.4) in the way the regex in **LdapParams.php** works is responsible for the problem. Once I'd found the problem I also found it easy to duplicate. I'm just trying to save someone else some time if they encounter the same issue.

The issue is seen when attempting to login as an LDAP user to the web UI.

The result of doing this is a _"Connection error (BIND)"_ message in the UI and the following in the syspass.log ...

_[2021-07-29 06:39:41] syspass.EXCEPTION: logger {"message":"Connection error (BIND)
#0 /var/www/html/sysPass-3.2.2/lib/SP/Providers/Auth/Ldap/LdapConnection.php(114): SP\Providers\Auth\Ldap\LdapConnection->bind()
#1 /var/www/html/sysPass-3.2.2/lib/SP/Providers/Auth/Ldap/LdapConnection.php(95): SP\Providers\Auth\Ldap\LdapConnection->connectAndBind()
#2 /var/www/html/sysPass-3.2.2/lib/SP/Providers/Auth/Ldap/Ldap.php(96): SP\Providers\Auth\Ldap\LdapConnection->checkConnection()
#3 /var/www/html/sysPass-3.2.2/lib/SP/Providers/Auth/AuthProvider.php(154): SP\Providers\Auth\Ldap\Ldap->factory()
#4 /var/www/html/sysPass-3.2.2/lib/SP/Providers/Auth/AuthProvider.php(116): SP\Providers\Auth\AuthProvider->getLdapAuth()
#5 /var/www/html/sysPass-3.2.2/lib/SP/Providers/Auth/AuthProvider.php(97): SP\Providers\Auth\AuthProvider->authLdap()
#6 /var/www/html/sysPass-3.2.2/lib/SP/Services/Auth/LoginService.php(154): SP\Providers\Auth\AuthProvider->doAuth()
#7 /var/www/html/sysPass-3.2.2/app/modules/web/Controllers/LoginController.php(65): SP\Services\Auth\LoginService->doLogin()
#8 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#9 /var/www/html/sysPass-3.2.2/lib/SP/Bootstrap.php(240): call_user_func_array()
#10 [internal function]: SP\Bootstrap->SP\{closure}()
#11 /var/www/html/sysPass-3.2.2/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func()
#12 /var/www/html/sysPass-3.2.2/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback()
#13 /var/www/html/sysPass-3.2.2/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch()
#14 /var/www/html/sysPass-3.2.2/lib/Base.php(75): SP\Bootstrap->run()
#15 /var/www/html/sysPass-3.2.2/index.php(28): require(String)","caller":"N/A"}_

But it's clear from doing a LAN trace and debugging on the LDAP server that sysPass is connecting over TCP 389 (despite the **ldaps://**) and even setting ...

`<ldapTlsEnabled>1</ldapTlsEnabled>`

... in the config.xml doesn't seem to actually cause startTLS to be used (as evidenced in the LDAP server logs). I had to hack LdapConnection.php in order to use startTLS (see below). 

I found it very hard to get a diff to format correctly ...
**Lines:** 156c156,157
**Remove:**         $this->isTls = $this->connectTls();
**Add:**                #$this->isTls = $this->connectTls();
**Add:**                ldap_start_tls($this->ldapHandler);`

Because I prefer not to hack code (especially PHP, which I have no experience with) I opted for redefining the ldapServer parameter in my config.xml (i.e. adding **:636** to the ldapServer parameter)

**Expected behavior**
With `<ldapServer>ldaps://my-ldap-server-01.mydomain.com.au</ldapServer>` sysPass should connect over TCP 636 by default. with `<ldapTlsEnabled>1</ldapTlsEnabled>` sysPass should connect over TCP 389 by default (which it does) but it doesn't seem to use startTLS in that instance whereas it should.

**Platform:**
 - OS: Ubuntu 20/PHP 7.4
 - Browser: any, not relevant

**Comment by nuxsmin** [comment]
Hello,

thanks for the detailed issue. The TLS protocol is meant to be used for plain connections, so a plain connection over 389 port is wrapped in a secure channel. The SSL oriented connection is done through 636 port and you don't set the TLS feature.

https://kb.sos-berlin.com/pages/viewpage.action?pageId=18778435

https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/bigip-ssl-administration-11-6-0/16.html

Regards

**Comment by stideswell** [comment]
You seem to have misunderstood the issue. I'm well aware of how TLS and SSL work. Seeing as you take such a condescending attitude to my post, I won't bother raising any issues again. The fact remains, the software worked fine previously, with the existing config and failed once I upgraded PHP, with the same config. The original config was <ldaps> and no <ldapTlsEnabled>. The former doesn't work without :636, and the latter doesn't work at all, that's a defect.

**Comment by nuxsmin** [comment]
So sorry Simon, my fault.

I've re-read the expected behaviour part and I agree that 389 port should
be used when TLS is set. I'll check the code and find out which is causing
this issue, since some of this release fixes were related to LDAP server
URL handling.

Regards.

**Comment by FooBarTrixibell** [comment]
I can confirm I see the :636 issue myself, without :636 it fails to bind, with :636 it works.

I do not have a server to test TLS on.

**Comment by nuxsmin** [comment]
Hello, sorry if you set a SSL enabled URL TLS should be disabled.

Regards.
