### ISSUE TITLE
Cookies Disabled Warning

### ISSUE THREAD

**Issue by ThigSchuch** [nuxsmin/sysPass#1732]
**sysPass Version**
Version 3.2

**Describe the bug**
Any chromium browser give me this warning and makes impossible to login

> ![image](https://user-images.githubusercontent.com/20743110/129399681-2e0db66b-a24b-478b-b044-272262cdf005.png)

**To Reproduce**
1. Open site in any chromium based browser

**Expected behavior**
Normal access

**Screenshots**
> ![image](https://user-images.githubusercontent.com/20743110/129399777-ff0656f6-1811-4cf4-88cd-ecf872fc8f99.png)
> ![image](https://user-images.githubusercontent.com/20743110/129399802-a45d8fef-d275-4689-8fd5-a97340631f32.png)
> ![image](https://user-images.githubusercontent.com/20743110/129399908-03e16b20-06d1-4487-99c1-61fe4172381d.png)

**Comment by nuxsmin** [comment]
Hello,

please make sure the cookies are enabled, because sysPass use cookies for session related actions.

Regards
