### ISSUE TITLE
How to update syspass from 3.1 to 3.2.2

### ISSUE THREAD

**Issue by HelpMeBatman** [nuxsmin/sysPass#1740]
Describe the question:

How to update syspass to new version ?

Application information: 

Version syspass: 3.1 (312.20030701)
DB: 5.5.65-MariaDB
PHP: 7.0.33
SO: Centos 7

3.1 (312.20030701)
Config: 312.20030701
App: 312.20030701
DB: 312.20030701

**Comment by CyrosX** [comment]
I recommend using the docker version.
It enables to update very easily :)

**Comment by nuxsmin** [comment]
Please take a look to the documentation https://syspass-doc.readthedocs.io/en/3.1/updating/index.html

Regards
