### ISSUE TITLE
Hello, I have syspass (3.2 (322.21031301)) on centos 8. while importing .csv file appeared one problem. My .csv file format is correct accounts are imported good, but password also appeared in note tab.Logically this should not have happened. can you help me?

### ISSUE THREAD

**Issue by giorgiimnadze1** [nuxsmin/sysPass#1742]
**sysPass Version**
Can be found on `Config -> Information` tab

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Event log**
Some lines from `syspass.log` file (within `config` directory) and sysPass event log that were logged when the error happened.

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android]
 - OS Version
 - Browser [e.g. Firefox, Chrome]

**Additional context**

**Comment by giorgiimnadze1** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/41830887/130768978-28c65d32-a4fe-47a6-a1cd-31d15ca005f4.png)

**Comment by nuxsmin** [comment]
Hello,

it seems that the CSV fields aren't being mapped correctly. Please check the contextual help on the import tab.

Regards.
