### ISSUE TITLE
Imported xml backup from version 2.1 (2.1.10.17053003)  to latest version - Integrity check failed

### ISSUE THREAD

**Issue by robmorin** [nuxsmin/sysPass#1746]
**sysPass Version**
2.1 (2.1.10.17053003) 

**Describe the question**
What does "Integrity check failed" mean after import of XML accounts

**Platform (please complete the following information):**
 - OS: Ubuntu
 - OS 20.04
 - Browser Firefox

**Additional context**
I am trying to update our current version of Syspass, V 2.1 But before i do that , as a test , I install latest version on Ubuntu 20, that went just fine. So then i exported users from 2.1 and downloaded the XML file, then imported the XML file to 3.2, all looked okay till i go to see a password for a account , it just says 'Integrity Check failed" in a red bar

Maybe the export is too old?
What is best way to update 2.1 to 3.2 without messing stuff up?
:)
Thanks and have a great day!

Rob
Montreal, Canada

**Comment by robmorin** [comment]
Just to add, I cant seem to do anything, change any settings under account tab, change details in an account. It always says saved settings , but nothing actually changes

**Comment by nuxsmin** [comment]
Hello @robmorin 

The best way to upgrade from any version is described in the doc (https://syspass-doc.readthedocs.io/en/3.1/updating/index.html), so it will maintain all the objects in sysPass. By using a XML file it only saves a few objects, but not users, groups, etc.

Thanks!

**Comment by robmorin** [comment]
Thanks, that worked just fine.

Have a great day!
