### ISSUE TITLE
Wrong russian symbols in card captions

### ISSUE THREAD

**Issue by TitovLab** [nuxsmin/sysPass#175]
Wrong some russian symbols in card captions on all skins:
![syspass](https://cloud.githubusercontent.com/assets/11898568/11656298/464c1784-9dc5-11e5-82b8-49083f09da47.png)

Also wrong alt text only on classic skin.

**Comment by nuxsmin** [comment]
Hi @TitovLab 

can you send me some string examples that this issue applies?

**Comment by TitovLab** [comment]
Hi!
Examples sent to your email.
Thank you.

**Comment by TitovLab** [comment]
Not fixed.
Problem with multibyte string in strrev function.
