### ISSUE TITLE
An exception occured

### ISSUE THREAD

**Issue by prites1993** [nuxsmin/sysPass#1757]
**sysPass Version**
3.2 (321.21011601)
Config: 321.21011601
App: 321.21011601
DB: 321.21011601

**Describe the bug**
 An exception occurred Please contact to the administrator

**To Reproduce**
1. Go to 'https://ipass.8ty6.co/.'

- [ ] 

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [CENTOS]
 - OS Version:7.9 
 - Browser [ Chrome]
 - 
![syspass](https://user-images.githubusercontent.com/32664365/134638256-6653b651-ff45-48fd-af32-bf3044a533e5.png)

**Comment by s-praveen-kumar** [comment]
Am facing the same issue

**Comment by s-praveen-kumar** [comment]
[Check this out](https://stackoverflow.com/questions/4380813/how-to-get-rid-of-mysql-error-prepared-statement-needs-to-be-re-prepared)
This solved the issue for me.
