### ISSUE TITLE
Docs for upgrade steps from 3.1 to 3.2?

### ISSUE THREAD

**Issue by tomaszkane** [nuxsmin/sysPass#1760]
**sysPass Version 3.1**

**Describe the question**
Here: https://syspass-doc.readthedocs.io/en/3.1/updating/index.html is docs for upgrade to any minor or major versions.
How about upgrade from 3.1.x to 3.2.x ?

**Platform:**
 - OS: Centos
 - OS Version 7
 - Browser Firefox

**Comment by nuxsmin** [comment]
Hello, some releases don't need any special steps to be upgraded, so you can update the code and the application is ready to run.

Upgrade instructions would be published whenever a major change is made.

Regards
