### ISSUE TITLE
sysPass 3.2.2  - Use of notification

### ISSUE THREAD

**Issue by Fernand0S** [nuxsmin/sysPass#1761]
sysPass 3.2.2 
 - OS: [container]

![Captura de Tela 2021-10-07 às 12 41 22](https://user-images.githubusercontent.com/32446123/136418151-e3b9e5c6-fb7e-4d46-a40c-030cb0b75c85.png)

how to use this notification feature?

I looked in the syspass guide in documentation and it's not clear about this feature if it's just for emailing or just for search information by accounts, tags, categories etc.

**Comment by nuxsmin** [comment]
Hello,

notifications are meant to notice the application users about anything regarding the application. They will show up on the UI.

Regards
