### ISSUE TITLE
Authenticator mfa

### ISSUE THREAD

**Issue by Valvos420** [nuxsmin/sysPass#1778]
SysPass version : 3.2
OS : debian 10
Installation : LAMP 

When i install the plugin Authenticator with this command : composer requires syspass/plugin-authenticator:^v2.2
I enable this plugin : 
![image](https://user-images.githubusercontent.com/82808496/140481954-2e1ed9d3-2946-4ff6-a158-17ab2b6e71a7.png)
But if i want to enable the authentication in the preferences, the QR code doesn't appear : 
![image](https://user-images.githubusercontent.com/82808496/140482118-9bc87242-3fff-4aff-b4ee-a56148f60c14.png)

Can someone know why this append:

**Comment by FooBarTrixibell** [comment]
I am not a developer or linked to this project but I would suggest checking the logs in app/config/syspass.log and /var/log/apache.

I would also (as a matter of course) try doing a chown on the whole directory to make sure the files are owned by apache and doing a restorecon to make sure the selinux permissions are okay.

**Comment by nuxsmin** [comment]
Hello, could you please provide some event logs?

Regards

**Comment by Kalin0x0** [comment]
we also have exact problem and QR Code not loaded. it also shows nothing in log 
![2024-07-03 15_34_16-sysPass __ Systems Password Manager - Brave](https://github.com/nuxsmin/sysPass/assets/59202462/cf521ca3-fe12-4251-822a-a565a878faeb)
[syspass.log](https://github.com/user-attachments/files/16085691/syspass.log)
