### ISSUE TITLE
Can you help me, How do I run syspas on two separate servers to synchronize with each other? Like Primary and Secondary servers. Thank you

### ISSUE THREAD

**Issue by giorgiimnadze1** [nuxsmin/sysPass#1779]
**sysPass Version**
Can be found on `Config -> Information` tab

**Describe the question**
A clear and concise description.

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android]
 - OS Version
 - Browser [e.g. Firefox, Chrome]

**Additional context**

**Comment by FooBarTrixibell** [comment]
I am not a developer on this project but I would say your question does not contain enough information, a title with the default text in the body is poor form, the default body text even tells you the information which would be useful in answering your query. This is quite likely why no one has answered your question in 20 days.

As an attempt to help, however, from installing and configuring the application I can see it is mainly MySQL (MariaDB) based.

The best way to replicate such an app is via database replication, on MariaDB -

https://developpaper.com/configure-mariadb-binary-hot-backup-for-master-slave-replication-in-centos7/

You can then replicate the remainder of the application from the filesystem with Rsync (this would ensure any updates done in the master are replicated to the slave.

https://www.cubebackup.com/blog/automatic-backup-linux-using-rsync-crontab/

Of course, you could be using windows, a different database or the containerised version of the app so this information may be useless to you and a waste of my time writing!

**Comment by giorgiimnadze1** [comment]
Thank you this information was usefull for me
