### ISSUE TITLE
Unable to see pasword history after upgrade to 1.2.0.02-rc2 and later from 1.1.x

### ISSUE THREAD

**Issue by TitovLab** [nuxsmin/sysPass#178]
Unable to see pasword history after upgrade to 1.2.0.02-rc2 and later from 1.1.x: master-password error.

**Comment by nuxsmin** [comment]
No password has been changed. This issue is because there were some improvements on the encryption methods, so the master password hash (used to compare it in some checks) has been regenerated and then when you get an account's history it checks the old one against the new master password hash.

**Comment by nuxsmin** [comment]
Hi @TitovLab 

it has been updated in the latest build (not yet released).

Meanwhile, you can issue this SQL query to perform the fix:

<code>UPDATE accHistory SET acchistory_mPassHash = (SELECT config_value FROM config WHERE config_parameter = 'masterPwd');
</code>

Kind regards
