### ISSUE TITLE
how to Azure Active Directory Authentication ???

### ISSUE THREAD

**Issue by ubalzer** [nuxsmin/sysPass#1780]
Hello,

i have installed 3.2 newest version and yould like to use Azure AD for Logins.

But i didn´t find any documentation for setup this correctly.

App Registration in Azure didn´t prodive any information about user, groups, etc...
With Endpoint should be used, etc...

so how can i use Azure AD with Syspass?

many thanks

**Comment by nuxsmin** [comment]
Hello,

AzureAD full behavior is not yet implemented, it's only implemented on hybrid deployments, where an on-premise AD is available.

Regards.
