### ISSUE TITLE
https://syspass-doc.readthedocs.io/en/3.2 not found

### ISSUE THREAD

**Issue by ruben-herold** [nuxsmin/sysPass#1782]
**sysPass Version**
3.2

**Describe the bug**
Seems that the documentation is not in sync with the project...

**Comment by nuxsmin** [comment]
Hello, you're right, the documentation wasn't generated because v3.2 didn't implement any important feature, 

https://github.com/nuxsmin/sysPass/releases/tag/3.2.0

Regards
