### ISSUE TITLE
Non variable recognition on Syspass API Bash Script

### ISSUE THREAD

**Issue by forzaxhx** [nuxsmin/sysPass#1783]
When i input a variable on the **curl** with the json indexed, it takes the string value of the variable, if i scaped the double-quotes, it returns me a sintax error because of in a **json** request u have to input the data with double-quotes.
Example:
```
#!/bin/bash

token="x"
tokenPass="x"
name="prueba"
url="https://prueba.prueba.prueba"
user="prueba"
pass="prueba"
notes="prueba"

curl -k -H "Content-Type:Application/json" -d '{"jsonrpc": "2.0", "method": "account/create", "params": { "authToken": "$token", "tokenPass": "$tokenPass", "name": "$name" , "categoryId": "7", "clientId": "9","login":"$user","url": "$url" ,"pass": "$pass","notes": "$notes"}, "id": 1}' -o- https://syspass.prueba.es/api.php
```

The **curl json** request works if i input the data manually, but with the variables, when i create the account, the account is named as the string value of the variable, i mean, if the variable is named *$name* , the account created is name *$name*. Any help please?
Also i tried to input the variable: "${variable}" and either works

**Comment by nuxsmin** [comment]
Hello, you need to check the bash syntax to avoid issues with single quoted strings.

Regards
