### ISSUE TITLE
Way to determine where Groups are used

### ISSUE THREAD

**Issue by FooBarTrixibell** [nuxsmin/sysPass#1789]
Deletion of groups fails when either a user has the group assigned (either as primary or secondary group) and if the groups exist in a permission (possibly also a preset values key too).

It would be nice if there could be
- a list of the locations the group is used 
- an option to bulk change these location to a new group

It could also be a popup when the delete button is pressed instead of an error though this would be less useful

![image](https://user-images.githubusercontent.com/13545093/143791898-1d193bc6-8af1-4380-a739-d8a05e0f33d7.png)

**Comment by nuxsmin** [comment]
Hello, user group usage is displayed in the user group card. Unfortunately the bulk edition don't work for the accounts history.

Regards.
