### ISSUE TITLE
problems for ldap integration with tls and mail notifications with a microsoft exchange

### ISSUE THREAD

**Issue by KMK4ze** [nuxsmin/sysPass#1791]
**sysPass Version**
syspass 3.2.2

Currently I already have I can import ldap users in the syspass but when enabling the tls it does not work for me, and also to enable mail notifications with a microsoft exchange server it gives me an error of smtp connection failed.

![syspass ldaptls](https://user-images.githubusercontent.com/93000875/144533455-c0879c33-4eee-4c2c-9581-ba84faa50987.JPG)

centos 7

Is there a telegram group to make inquiries?

**Comment by lgomezc07** [comment]
you could solve the mail with exchange?

**Comment by nuxsmin** [comment]
Hello, could you provide `syspass.log` file?

Regards
