### ISSUE TITLE
cookies & cant login first time

### ISSUE THREAD

**Issue by thd12345678** [nuxsmin/sysPass#1792]
i've installed all the syspass and the error about cookies its appearing. I could create installation and everything, but i CANT login, it says invalid action. I search all the cookies problem on the web from SYSPASS and couldnt solve anything. Anyway i found out that the cookies = disabled on this site. IDK why, only on this one... already changed the config.xml and everything, any solution ? It is that why i cant even login from first time, because of cookies? when i ran the composer, some things says they're missing and then it appears as installs them. Idk, im saying everything i notice it was 'an issue' maybe. I've reinstalled everything several times and nothing, i also have certificates on the site, do i need to locale the certificates or smthing like that on the instalation or config ? thanks.

**Comment by nuxsmin** [comment]
Hello, could you provide `syspass.log`  file?

Regards
