### ISSUE TITLE
API and unofficial browser extensions

### ISSUE THREAD

**Issue by has-aissaoui** [nuxsmin/sysPass#1797]
3.2 (322.21031301) [docker image installation syspass/syspass:latest]

Before all, Tahnks for your job,

I can't etablish connection between sysPass server and browsers extensions.
API Password verification error
Tested with Firefox and Chrome. Tested with the two extensions availabe "syspass" and "syspass-browser"

The API Authorizations for search and view was created correctly I think and with the same password
A curl based script for tests API return me correct results.

I have never tested with older syspass version but I suppose that this browsers extensions worked in the past. So I wonder, 3.2 syspass version is it always compatible with this extensions?

Thanks in advance for your return

**Comment by miyoyo** [comment]
Hi,

Author of [syspass-Browser](https://github.com/miyoyo/syspass-browser) here,

I have just tested the extension against the latest versions of sysPass, it does appear to work.

Could you send screenshots of your configuration?
In syspass-Browser, these errors happen when an API call to the View Password endpoint fails.

https://github.com/miyoyo/syspass-browser/blob/08d6d6f8807fba9383d1ed4877b6e09558812d50/keepassxc-browser/background/keepass.js#L188

I suspect that either the API configuration is not correct, or the password is just invalid.

You could also look at the calls being made by the extension in chrome by opening the extensions page, checking the "Developer Mode" switch on the top right, then clicking on "Inspect views: Background Page" in the box for sysPass-browser.

**Comment by kolsan** [comment]
Hello 
i can confirm that the extension from miyoyo is working fine in Edge and Chrome. In the addon market we can find 2 addons for syspass, be careful because the another one is not working.

**Comment by nuxsmin** [comment]
Related to sysPass 3rd party extension.
