### ISSUE TITLE
LDAP configuration is incomplete

### ISSUE THREAD

**Issue by maxsnts** [nuxsmin/sysPass#1798]
Hello

On LADP configuration, all the values in the "Import" section, (atributes and filter) should actually be in the configuration section.
This way, all data would be saved for future sync with only one click.

On that note, you could provide a php file that just dis the sync, and people could call it periodically to sync the users (crontab) 

Thanks

**Comment by nuxsmin** [comment]
Hello, the import section is only need in some use cases, because sysPass will create each user account upon login, so you don't need to import every user you add in LDAP.

Regards.
