### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#181]
Hey, I use ssl on the webserver where syspass is running but in the bottom bar it shows a red lock. Is this fine or should it show a green lock or any other color? Is something wrong with my ssl connection?

Just asking because I am a bit confused by the red lock ...

**Comment by nuxsmin** [comment]
Hi, the lock should be displayed on a closed state. You can see the difference between yours and the one at demo.syspass.org

Does it?

**Comment by Goatmaster** [comment]
Yes it is locked. Thank you for the fast reply!

**Comment by nuxsmin** [comment]
BTW I'll code it to change its color. I can be a bit confusing.
