### ISSUE TITLE
Cannot delete User

### ISSUE THREAD

**Issue by madcoda9000** [nuxsmin/sysPass#1811]
**sysPass Version**
3.2 (322.21031301)

**Describe the bug**
get an error message when i try to delete a user

**To Reproduce**
1. login as admin
2. Click on users tab
3. klick on delete icon of the user and confirm the deletion dialog
![msedge_cEONO8NBiS](https://user-images.githubusercontent.com/25504739/160610450-b285cd9e-0d5c-47d5-80e8-68295ef041ca.png)

**Expected behavior**
i would expect that the user will be deleted

**Screenshots**
![msedge_cEONO8NBiS](https://user-images.githubusercontent.com/25504739/160610550-163bb907-7ba7-4d22-b769-dfccc3dc6048.png)

**Event log**
![msedge_egaRrcN3EW](https://user-images.githubusercontent.com/25504739/160610686-052fd1d2-5014-4fcd-8405-7b34f0b3378f.png)

**Platform (please complete the following information):**
 - OS: [ubuntu linux lts]
 - OS: 20.04.4
 - Browser: [Edge]

**Additional context**

**Comment by nuxsmin** [comment]
Hello, it seems that the user is being referenced by an account history record. You need to remove the exact record in order to remove the user.
Regards.
