### ISSUE TITLE
Import web interface hangs (CSV)

### ISSUE THREAD

**Issue by epinter** [nuxsmin/sysPass#1816]
**sysPass Version**
3.2 (322.21031301)
Config: 322.21031301
App: 322.21031301
DB: 322.21031301

**Describe the bug**
From the moment I select the file to upload (a CSV with 717 records, with multi-line notes, separated by ; and with double-quotes), the loading icon stays there and I don't know what is happening. In the logs I see the message:
syspass.DEBUG: run.import.start {"message":"N/A","user":"admin","address":"x.x.x.x","caller":"SP\\Modules\\Web\\Controllers\\ConfigImportController::importAction"} []
Some minutes after the file upload, I see the message:
![image](https://user-images.githubusercontent.com/1561280/163483679-81634f0a-7247-4a44-b840-de2f2d881eed.png)

The first time I tried, I logged out when I saw the red error message. I was not able to login again, the login page hangs (and I'm redirected to /undefined).

A few minutes after the red error message, I see in the logs:
syspass.DEBUG: run.import.end {"message":"Accounts imported: 715","user":"admin","address":"x.x.x.x","caller":"SP\\Modules\\Web\\Controllers\\ConfigImportController::importAction"} []

The web interface stopped at the moment I saw the red error message. Two records was not imported, I don't see a way to know what is missing.

The time between the import.start and import.end messages was 8 minutes. Last time I tried, the import didn't finish (the last log message was the import.start).

The file size is 115K

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Import Accounts'
3. Upload the file
4. Wait some minutes to see the Gateway Timeout

**Expected behavior**
A message indicating the completion status, with detailed information about failed import records if possible.

**Screenshots**
Above.

**Event log**
Apr 14 18:57:28 debian syspass[25838]: syspass.DEBUG: run.import.start {"message":"N/A","user":"admin","address":"x.x.x.x","caller":"SP\\Modules\\Web\\Controllers\\ConfigImportController::importAction"} []
Apr 14 19:05:19 debian syspass[25838]: syspass.DEBUG: run.import.end {"message":"Accounts imported: 715","user":"admin","address":"x.x.x.x","caller":"SP\\Modules\\Web\\Controllers\\ConfigImportController::importAction"} []

**Platform (please complete the following information):**
 - OS: Debian 11
 - Package versions:
apache2               2.4.53-1~deb11u1
mariadb-server     10.5.15-0+deb11u1
php7.4                   7.4.28-1+deb11u1

Some php settings:
max_execution_time = 1200
max_input_time = 600
memory_limit = 512M
upload_max_filesize = 500M
post_max_size = 700M

I'm using php-fpm.

**Comment by epinter** [comment]
In error log I have several error messages about truncated login and name fields.

For me these limits of 50 for login, 100 for name, and 255 for url are too low. Some logins can easily reach 70 characters depending on domain, I have several above 60. The only place these limits are enforced are in the database ?

**Comment by nuxsmin** [comment]
Hello, it seems you've a proxy server between the sysPass instance and the client, please review proxy's (eg. Nginx) logs.
Regards

**Comment by epinter** [comment]
Proxy server ???
