### ISSUE TITLE
How to get SSH keys from custom field

### ISSUE THREAD

**Issue by jmrkvicka909** [nuxsmin/sysPass#1817]
Hello, I would like to ask one question. I have created new account, where I have stored SSH key in Custom Fields. My question is, if it is possible to get this SSH key by some API request? I cannot find any suitable method for this case in API documentation. Method viewPass returns only password but not SSH key. Thank you in advance.

(sysPass 3.2)

**Comment by nuxsmin** [comment]
Hello, you can set the `customFields` request parameter in order to get the custom fields within the response.

Regards!
