### ISSUE TITLE
Custom Fields additional Passoword

### ISSUE THREAD

**Issue by vvascautan** [nuxsmin/sysPass#182]
Hello,

I added a custom fields with type "Password" and sysPass allow me to add additional password but I unable to get it.

Please let me know how to fix this.
Thanks

**Comment by nuxsmin** [comment]
Hi, you're right, for some reason the password field is being encrypted twice, because there is an encryption function on the client side and one on the server side. I've to switch off the client side encryption.

Thanks for the feedback!

**Comment by vvascautan** [comment]
Hello,
Thanks for confirmation, please leave a comment when this is improved and let me know where I can get the fix.
