### ISSUE TITLE
Accounts/Password public

### ISSUE THREAD

**Issue by alisonduarte88** [nuxsmin/sysPass#1824]
**sysPass Version**
3.2 (322.21031301)

**Describe the question**
Hello, we installed syspass on a server and we are in the testing phase.
The first question we have, when creating a new account, (in the + sign located in the upper right corner of the screen), we realize that if the user does not configure anything in the permissions tab, that account and password created will be public.
Is there any way to change this?
We have this first fear, of users creating passwords and not wanting to make them public.

**Platform (please complete the following information):**
 - OS: Ubuntu Server 22.04
 - Browser: Chrome

**Comment by nuxsmin** [comment]
Hello, by default, accounts are only visible by the owner and the primary group of the owner, so no public permissions are set by default.

Regards!
