### ISSUE TITLE
Consulta actualización de 1.2.0.08 a 1.2.0.09

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#183]
Al actualizar, nunca me pidió actualizar base de datos. Está ok o falló el proceso ?

**Comment by nuxsmin** [comment]
Sí, todo ok. Si no solicita la actialización, es que no es necesaria.

En el directorio "/sql" puedes encontrar todas las actualizaciones de la BD según la versión (para realizarlas manualmente).
