### ISSUE TITLE
Upgrading from 3.2 to 3.2.5 blank page

### ISSUE THREAD

**Issue by systemcon** [nuxsmin/sysPass#1835]
**sysPass Version**
3.2.5

**Describe the question**
After git cloning the 3.2.5 version and run php composer i got blank page at sysPass.
I have already copied the config.xml,pubkey,pem and key.pem from the previous installation at the new one.
**Screenshots**

**Platform (please complete the following information):**
 - OS: latest ubuntu server
 - OS Version
 - Browser [e.g. Firefox, Chrome]

**Additional context**
syspass.log

`[2022-06-13 11:32:38] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2022-06-13 11:32:38] syspass.EXCEPTION: logger {"message":"'/app/config' directory permissions are wrong
#0 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(399): SP\Config\ConfigUtil->checkConfigDir()
#1 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#2 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#4 /var/www/pam.systemcon.gr/html/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/pam.systemcon.gr/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/pam.systemcon.gr/html/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#8 /var/www/pam.systemcon.gr/html/index.php(28): require(String)","caller":"N/A"}
[2022-06-13 11:33:10] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2022-06-13 11:33:10] syspass.EXCEPTION: logger {"message":"'/app/config' directory permissions are wrong
#0 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(399): SP\Config\ConfigUtil->checkConfigDir()
#1 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#2 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#4 /var/www/pam.systemcon.gr/html/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/pam.systemcon.gr/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/pam.systemcon.gr/html/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#8 /var/www/pam.systemcon.gr/html/index.php(28): require(String)","caller":"N/A"}
[2022-06-13 11:33:12] syspass.INFO: logger {"message":"Extensions checked","caller":"SP\Core\PhpExtensionChecker::checkMandatory"}
[2022-06-13 11:33:12] syspass.EXCEPTION: logger {"message":"'/app/config' directory permissions are wrong
#0 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(399): SP\Config\ConfigUtil->checkConfigDir()
#1 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(300): SP\Bootstrap->initConfig()
#2 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(227): SP\Bootstrap->initializeCommon()
#3 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#4 /var/www/pam.systemcon.gr/html/vendor/klein/klein/src/Klein/Klein.php(879): call_user_func(Object(Closure),Object(Klein\Request),Object(Klein\Response),Object(Klein\ServiceProvider),Object(Klein\App),Object(Klein\Klein),Object(Klein\DataCollection\RouteCollection),Array)
#5 /var/www/pam.systemcon.gr/html/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route),Object(Klein\DataCollection\RouteCollection),Array)
#6 /var/www/pam.systemcon.gr/html/lib/SP/Bootstrap.php(464): Klein\Klein->dispatch(Object(Klein\Request))
#7 /var/www/pam.systemcon.gr/html/lib/Base.php(75): SP\Bootstrap->run(Object(DI\Container))
#8 /var/www/pam.systemcon.gr/html/index.php(28): require(String)","caller":"N/A"}
`

**Comment by nuxsmin** [comment]
Hello, please check the config directory permissions (they should be `750`): `/app/config' directory permissions are wrong`
