### ISSUE TITLE
Authentication thru LDAP need to be more flexible

### ISSUE THREAD

**Issue by turekg** [nuxsmin/sysPass#1837]
Hello, I am trying to configure v. 3.2 with my company's LDAP and it's not working at all because it assumes a specific directory tree structure which we don't have since it seems to  also require the users to be in a specific LDAP group.
All I need is the convenience of authenticating against LDAP. The first time around, that user is entered in the mysql DB and assigned the profile/group as specified in the configuration. This I can tweak for minimum access (read only for example).
Later, this user can be assigned to other groups/profiles as needed.

**Comment by nuxsmin** [comment]
Hello, you can leave the LDAP group unset, so it'll lookup the user in the LDAP base.

Regards.
