### ISSUE TITLE
German translation!

### ISSUE THREAD

**Issue by CyrosX** [nuxsmin/sysPass#184]
Hello there,
I've finished the german translation, but can't edit some mistakes.
Like "Protokol" in german it is "Protokoll".
Maybe you can add the finished translation to the next update?

**Comment by nuxsmin** [comment]
Sure, let me unlock the string edition.

Great work, I'll commit for the next build.

Thanks!

**Comment by nuxsmin** [comment]
Hi, the reviewing marked translations have been unlocked and highlighted. Sorry for the inconvenience but I need to lock the saved translations to prevent being deleted.

**Comment by nuxsmin** [comment]
Hi there!, I have just updated the German translation...good work!!

The remaining strings in review mode are unlocked, so you can fix them.

Thanks for your support!!
