### ISSUE TITLE
API method account/create and edit ignores parameter userGroupId

### ISSUE THREAD

**Issue by jmrkvicka909** [nuxsmin/sysPass#1841]
**sysPass Version**
3.2

**Describe the question**
Hi folks, I have a problem with API request for creating/editing account. I want to specify userGroupId, but it always put to default group with ID1. I a have also tried to edit account. Unfortunately same problem. Could someone help me, if I am doing something wrong, or you have same problem and it is bug? Thank you in advace.

Request:
```
{
  "jsonrpc": "2.0",
  "method": "account/create",
  "params": {
    "authToken": "...",
    "tokenPass": "....",
    "name": "test",
    "categoryId": 2,
    "clientId": 2,
    "userGroupId":5,
    "pass": "asdfasdgfwresA",
    "login": "example",
    "url": "example.com"
  },
    "id": 1
}
```

Response:
{
    "jsonrpc": "2.0",
    "result": {
        "itemId": 20,
        "result": {
            "id": 20,
            "userId": 5,
            "userGroupId": 1,
            "userEditId": 5,
            "name": "test",
            "clientId": 2,
            "categoryId": 2,
            "login": "example",
            "url": "example.com",
            "pass": "",
            "key": "",
            "notes": "",
            "otherUserEdit": "0",
            "otherUserGroupEdit": "0",
            "dateAdd": "2022-06-17 16:10:25",
            "dateEdit": null,
            "countView": 0,
            "countDecrypt": 0,
            "isPrivate": "0",
            "isPrivateGroup": "0",
            "passDate": 1655475025,
            "passDateChange": 0,
            "parentId": 0,
            "categoryName": "t1",
            "clientName": "t1",
            "userGroupName": "Admins",
        },
        "resultCode": 0,
        "resultMessage": "Account created",
        "count": null
    },
    "id": 1
}

**Comment by nuxsmin** [comment]
Hello, it could be so because of a permissions issue. Please check the permissions for the given user (Account Permissions should be set on the user's profile).

Regards

**Comment by jmrkvicka909** [comment]
Thank you very much. I have to allowed Accounts Admin. :) 
<img width="599" alt="Screenshot 2022-06-20 at 8 53 46" src="https://user-images.githubusercontent.com/82440429/174542696-695ffc47-7bde-40f9-817e-bd720bbd5864.png">
