### ISSUE TITLE
If URLs don't end with / or /something the system adds /https at the end

### ISSUE THREAD

**Issue by rgavilan** [nuxsmin/sysPass#1844]
**sysPass Version**
3.2.8

**Describe the bug**
Regarding to #1840, the original problem was solved but the solution caused another issue. Now, when an URL doesn't end with `/` or `/somethig` the system adds `/https` in search screen.

**To Reproduce**

1. Set an URL in an account without context path, for instance https://www.google.com/
2. Goto search screen and locate the account
3. Look at the URL and the link

**Expected behavior**
URLs should be parsed correctly regardless of whether they end with / or not

**Screenshots**

![image](https://user-images.githubusercontent.com/33056993/174578727-0aa68644-358e-4d2a-a742-df2642dc6da3.png)

**Comment by ska391** [comment]
I'm seeing the same problem. Also, if the URL is like "https://google.com:8080/" then you will get in result "https://google.com/https". That is, I can not specify the port in the URL.

**Comment by nuxsmin** [comment]
Hello, this issue was solved in latest release.

Thanks for the feedback!!
