### ISSUE TITLE
Syspass 1.2.0.11 LDAP and Classic Theme

### ISSUE THREAD

**Issue by bitking** [nuxsmin/sysPass#185]
Hi There,

When i first login to syspass i ge the material theme when i click in the left bottem on my user profile i select the classic theme.

When i want to change back to material theme there is not user profile button to do so resulting in completely deleting the account and create it again to be able to use the material theme.

Can you please look into this.

**Comment by nuxsmin** [comment]
Hi, you need to click on the preferences  button on the top navigation bar (aka session bar) in classic theme.

No user deletion needed  :)

**Comment by bitking** [comment]
Hi there,

Thanks for you response.

I try'd it again but i dont see a preferences button on top of the navaigation bar. i only see this.

http://imgur.com/m0REY3m

**Comment by bitking** [comment]
Oh wow i just noticed on demo.syspass.org there are 2 icons i miss in my setup.

- Change Password
- Your user preferences

Strange, what could be wrong?

**Comment by nuxsmin** [comment]
Are you using ldap auth?. I've found out that if you're using it with the classic theme, that icon is not shown. I'll fix it in next build.

**Comment by nuxsmin** [comment]
Meanwhile you can replace the sessionbar.inc file by this one https://gist.github.com/973910bef91b7a18a911

The file is located at inc/themes/classic

**Comment by bitking** [comment]
Yes i am using LDAP, thanks a lot for your support.

**Comment by bitking** [comment]
Replaced it and it works.

**Comment by nuxsmin** [comment]
Keep opened until fixing it on next build ...;)
