### ISSUE TITLE
URLs with for non standard protocol are parsed incorrectly

### ISSUE THREAD

**Issue by rgavilan** [nuxsmin/sysPass#1854]
**sysPass Version**
3.2.10

**Describe the bug**
Regarding to #1844 and #1840, the problems were solved, but I also detected a new one relative to URLs with a non standard protocol such as `mongodb+srv`, for instance an URL from MongoDB Atlas is `mongodb+srv://cluster.foo.mongodb.net/bar`. At account search is shown as `mongodb%2Bsrv://cluster.foo.mongodb.net/bar`.

The same problem is detected when we introduce instead of an standard URL a remote folder location such as `\\foo\bar`, in this case is shown as `%5C%5Cfoo%5Cbar`.

**To Reproduce**

1. Set an URL in an account in non standard format, for instance `mongodb+srv://cluster.foo.mongodb.net/bar` or `\\foo\bar`
2. Goto search screen and locate the account
3. Look at the URL and the link

**Expected behavior**

When the URL is not recognized as a standard http or https one, it should be shown as plain text (instead of a link) and without been parsed.

**Screenshots**

![image](https://user-images.githubusercontent.com/33056993/176863211-227af879-c6c6-4abd-a883-b74383a10a55.png)

![image](https://user-images.githubusercontent.com/33056993/176863611-035a7ff1-523c-46c1-aeb0-637cea5df0d9.png)

**Comment by nuxsmin** [comment]
Hello, sorry for the inconvenience, it seems that URL encoding within `href` tags is quite difficult to achieve and there isn't too much documentation or tooling to handle it correctly.

This should be solve in latest release.

Thanks for the feedback!!
