### ISSUE TITLE
syntax error, unexpected

### ISSUE THREAD

**Issue by psouza0** [nuxsmin/sysPass#1869]
3.2 (323.22052501)
Config: 323.22052501
App: 323.22052501
DB: 323.22052501 

**Describe the bug**

Each account created generates this error on the main page (with search parameters or not):
syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ')'

**To Reproduce**

add new client (ie: stand01)
add new category (ie: pb)
add new account

Name: test
Client: Customer01
Category: public
user: adm
passwd: adm

See error on search page
Expected behavior
See accounts and filter them

Screenshots
[screens.zip](https://github.com/nuxsmin/sysPass/files/8774847/screens.zip)

Platform:

OS: Linux
OS Version: Ubuntu 20.04
Browser: Firefox 104
![Captura de tela de 2022-08-26 14-25-19](https://user-images.githubusercontent.com/32044232/186959642-ea5fc084-89a2-4257-85f9-50c9958e979e.png)

**Comment by paulogeraldols** [comment]
bug fixed in release 3.2.11

**Comment by psouza0** [comment]
bug fixed in release 3.2.11
