### ISSUE TITLE
Support multple categories per password entry or allow add tags

### ISSUE THREAD

**Issue by pschichtel** [nuxsmin/sysPass#187]
I don't think passwords can always be put strictly into one category.
When I have hunderts of passwords I'd like to be able to filter for multiple categories/tags "system" "unix" "application xy".
I could add this terms to the account name, but then everyone creating accounts would need to use exactly the same terms.

**Comment by nuxsmin** [comment]
You're right, that feature is planned for the next release 1.3

It hasn't been implemented yet, but you can track the new features at the devel branch.

Thanks for the feedback !

**Comment by wagnst** [comment]
:+1:

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta

**Comment by catrone3** [comment]
How is this done? when I create a password entry I only see one place for categories, am I missing some setting that I am not seeing? or did this get removed in 3.0 after it showed up in 2.0-beta?
