### ISSUE TITLE
Syspass 1.2.0.11 LDAP email adres

### ISSUE THREAD

**Issue by bitking** [nuxsmin/sysPass#188]
Hi there,

When i log in for the first time using ldap and i dont have a email adres available in my email field in AD i get an error everytime i want to login saying i need to use the master password again.

When i fill this field in AD with an email adres it is solved.

Is an email adres in AD field mandatory for this to work correctly?

Thanks.

**Comment by nuxsmin** [comment]
Hi, user email is not used for the user's derivated key (for master password encryption), the only data used is the user's password and login, so it's very strange.

As I understand, these are the steps followed:

First time LDAP User login (no email) > sysPass Login > Master Password error > sysPass Login (back) > Master Password error (again)

Aren't they?, are there any errors in the sysPass event log?

Let me do some tests and I'll be back with more info.

**Comment by bitking** [comment]
Hmmm. Strange, now i cant reproduce the problem anymore.

I'll get back on this.

**Comment by nuxsmin** [comment]
Right, it's strange. Did you try with a new AD user?

**Comment by bitking** [comment]
No, good call. Because i did had this problem with 2 different users. Hold on ill try.

**Comment by bitking** [comment]
Nope, same. No problem anymore.

Very strange, i'll close the issue and reopen if it happens again and i can reproduce.

**Comment by bitking** [comment]
Hmm, i still have the issue. 

Log:
4215	2016-01-06 10:31:58	getDataFromUrl	212681	10.200.200.183	Failed to connect to api.github.com port 443: Connection refused
4214	2016-01-06 10:31:58	getDataFromUrl	212681	10.200.200.183	Failed to connect to api.github.com port 443: Connection refused
4213	2016-01-06 10:31:57	Log in	usernumber	10.200.200.183	(LDAP)
Login Server: xxx:3268
User: usernumber
Profile: Admin
Group: System
4212	2016-01-06 10:31:26	Log in	usernumber	10.200.200.183	(LDAP)
Login Server: xxx:3268
User: usernumber
Profile: Admin
Group: System
4211	2016-01-06 10:31:26	Logout session		10.200.200.183	User: 
Inactive time: 11.9 min.
Total time: 11.9 min.
4210	2016-01-06 10:19:29	Logout session	usernumber	10.200.200.183	User: Usernumber
Inactive time: 0.03 min.
Total time: 3.88 min.

**Comment by bitking** [comment]
And i just had it again:

4227	2016-01-06 11:55:33	Log in	usernumber	10.200.200.183	(LDAP)
Login Server: xxx:3268
User: usernumber
Profile: Admin
Group: Systeembeheer
4226	2016-01-06 11:55:29	Log in	usernumber	10.200.200.183	(LDAP)
Login Server: xxx:3268
User: usernumber
Profile: Admin
Group: Systeembeheer
4225	2016-01-06 11:55:29	Logout session		10.200.200.183	User: 
Inactive time: 10.78 min.
Total time: 10.78 min.

**Comment by nuxsmin** [comment]
And those users don't have e-mail set, right?

It's very strange because if the auth doesn't succeed there would be some records in the event log.

Can you enable debug mode and look at the webserver error log?. It'll output a bunch of data....

**Comment by bitking** [comment]
No its users (like me) with an email adres set. i'll put debug on and let you know.

**Comment by bitking** [comment]
I just had it again with debug on, can i send it to you privately?

**Comment by nuxsmin** [comment]
Sure, you can skip private data...

Send to nuxsmin@syspass.org, or create a private gist.

**Comment by bitking** [comment]
I mailed you the url of the private gist.

**Comment by bitking** [comment]
Sorry i opened the wrong issue.
