### ISSUE TITLE
Syspass 1.2.0.11 LDAP 2 times to login

### ISSUE THREAD

**Issue by bitking** [nuxsmin/sysPass#189]
Hi There,

Sorry to post another issue but now and then i am logging in using LDAP with my usernumber and password but the first time i do this i get no error nothing and the page refreshes with the login box when my password is 100% ok then i login again and i get to my passwords.

How can we troubleshoot this?

I only got this in the log:

2809	2016-01-04 17:10:16	Log in	myusernumber	10.200.200.183	(LDAP)
Login Server: xxxxxxx:3268
User: myusernumber
Profile: Admin
Group: Network
2808	2016-01-04 17:10:07	Log in	myusernumber	10.200.200.183	(LDAP)
Login Server: xxxxx:3268
User: myusernumber
Profile: Admin
Group: Network
2807	2016-01-04 17:10:07	Logout session		10.200.200.183	User: 
Inactive time: 5.5 min.
Total time: 5.5 min.
2806	2016-01-04 17:04:35	Logout session	<myusernumber>	10.200.200.183	User: myusernumber
Inactive time: 0.3 min.
Total time: 2.03 min.

**Comment by nuxsmin** [comment]
Hi, can you try it out the latest commit?

**Comment by bitking** [comment]
Thanks, what is the best way to update? I am already in production with this so i am a little carefull now :)

**Comment by nuxsmin** [comment]
If you don't want to update your production environment, you can download and unpack in a new directory and then copy the config.php file to the newly created structure.

The new instance will connect to the same database, but no changes will be performed because this build doesn't implements any database related stuff, only PHP session management.

Another solution would be to create a new installation from scratch using a different database.

**Comment by bitking** [comment]
Yes, but i noticed you only changed the MainC.class.php in syspass//web.

Cant i just override the current file with your new one?

**Comment by nuxsmin** [comment]
Sure, but there are 6 files in the latest commit....

https://github.com/nuxsmin/sysPass/commit/8e86d755be00a466b693ad96dfec8d0d5d014648

**Comment by bitking** [comment]
Problem is fixed now, thanks again.

**Comment by bitking** [comment]
I send the url of the private gist with the debug data.

**Comment by nuxsmin** [comment]
Ok, let me find out what could be happening. The debug data can be useful, but I think it isn't a LDAP related issue, because it would throw an error, and it doesn't.

It can be a PHP session issue. Can you tell me if before the failed login attempt you did a logout or was a session timeout?

**Comment by bitking** [comment]
Everytime i did a logout.

**Comment by wagnst** [comment]
LDAP login is working perfectly with my setup. Maybe I can help you somehow to configure your setup correctly?

**Comment by bitking** [comment]
Thanks a lot the problem is resolved now, logged in and out for 20 times and haven't experienced the problem anymore.

**Comment by nuxsmin** [comment]
Great, thanks for the feedback!
