### ISSUE TITLE
Select characters for password generator

### ISSUE THREAD

**Issue by TitovLab** [nuxsmin/sysPass#190]
It will be nice to choose characters for password generator.
For example remove 0 and O, I and etc.
In sysPass 1.1 I edit /js/functions.js like this:
    var keylistalpha="abcdefhkmnpqrstuvwxyz";
    var keylistalphaupper="ABCDEFHKLMNPQRSTUVWXYZ";
    var keylistint="123456789";
    var keylistspec="@#$_";
In sysPass 1.2 I can not find how to remove unwanted characters from password generator?

**Comment by vvascautan** [comment]
Hello,
In addition it would be good if generated password doesn't match existing.

**Comment by nuxsmin** [comment]
Added to roadmap #422
