### ISSUE TITLE
attached files not visible for other user

### ISSUE THREAD

**Issue by fwilly** [nuxsmin/sysPass#191]
I have a new account created and attached a text file (notes was not great enough). The I have a user give permissions. But the user can see there is an attachment but a click on the icon don't download the file. Why?

**Comment by nuxsmin** [comment]
The attachment icon shown on accounts search list, is only for information purposes. You need to view the account's details to download any attachment.

**Comment by fwilly** [comment]
In the account details no icon or other informations for attachment are visible.

**Comment by nuxsmin** [comment]
Can you test it on demo.syspass.org? I've just created a new user (view) with pass '1234' and I'm able to get the account's attachments. The user profile only allows create, view and files, and the user is neither account owner nor primary group member, he only has secondary access rights.

**Comment by fwilly** [comment]
I can see the attached files in account qwert. But in my local system I make the same and cannot see the attached files.

**Comment by nuxsmin** [comment]
Which version are you using?

**Comment by fwilly** [comment]
v1.2

**Comment by nuxsmin** [comment]
and the build number?. You get it at Configuration > Information

**Comment by fwilly** [comment]
* sysPass version: 1.2.0.08
* Database:
    * SERVER_VERSION : 5.5.46-0ubuntu0.14.04.2 
    * CLIENT_VERSION : 5.5.46 
    * SERVER_INFO : Uptime: 6760420 Threads: 1 Questions: 192842 Slow queries: 1 Opens: 3557 Flush tables: 1 Open tables: 400 Queries per second avg: 0.028 
    * CONNECTION_STATUS : Localhost via UNIX socket 
    * Name: syspass2@localhost
* PHP:
    * Version: 5.5.9-1ubuntu4.14 
    * Extensions: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, curl, gd, json, ldap, mcrypt, mysql, mysqli, pdo_mysql, readline, mhash, Zend OPcache, xdebug 
    * Used Memory: 768 KB 
* Server: Apache/2.4.7 (Ubuntu)

**Comment by nuxsmin** [comment]
I cannot figure out what can be happening...

Although there isn't any related issue in the last releases, it's advisable to upgrade to the latest one, because there have been many fixes. The upgrade path is very easy because there is no database updates, so it only affects to the sysPass code, so you only need to download the latest release and place the config.php file in its path.

**Comment by fwilly** [comment]
New version I have installed. But now I cannot login any more. I use ldap. The new version said "No account and password given".

**Comment by nuxsmin** [comment]
Can you do a page refresh?. Is that error given during login?. LDAP is working fine in latest releases, there is no related issues about that error. It's very strange, but if LDAP fails it falls back to MySQL, so LDAP is bypassed.

**Comment by fwilly** [comment]
I have changed the vhost link to the new version, then apache restarted, then open a new browser tab and tried to login. => "Keine Benutzername/Passwort eingegeben"
Then I have it tried with an other browser. => "Keine Benutzername/Passwort eingegeben"

**Comment by nuxsmin** [comment]
Can you take a look to the webserver error log?, is there any error?

Did you get the release from https://github.com/nuxsmin/sysPass/releases?

**Comment by fwilly** [comment]
I have found the problem. The owner of /config/key.pem was no correct. Now login is okay. Thanks.
But the other user cannot see the attached file also in this version. I'm the creator of the account. I can see it.

**Comment by nuxsmin** [comment]
Great!...now lets go to the primary issue...

This the piece of code that enables/disables files viewing:
<code>$this->view->assign('showFiles', (($this->_action == Acl::ACTION_ACC_EDIT || $this->_action == Acl::ACTION_ACC_VIEW || $this->_action == Acl::ACTION_ACC_VIEW_HISTORY)
            && (\SP\Util::fileIsEnabled() && Acl::checkUserAccess(Acl::ACTION_ACC_FILES))));</code>

..so, files are shown if you are viewing/editing an account and files management is enabled and user has a profile that have files access enabled, does match?

**Comment by fwilly** [comment]
I have found my mistake. In the profile of the user the file right was not set. Now it works.

**Comment by nuxsmin** [comment]
Great!!
