### ISSUE TITLE
Error 400 - Load Balance - AWS

### ISSUE THREAD

**Issue by pgabriel10** [nuxsmin/sysPass#1911]
**sysPass Version**
3.2.2

**Describe the bug**
After I put the Syspass behind de Load Balance in AWS I received the error Bad Request.

This error happens when I try to use a certificate via LB (Connection via TLS to use the aws certificate).

If I use LB without TLS with only TCP to redirect .... the access works normally. ( The problem is certificate...because is self signed )

**To Reproduce**

    Run apache service with internal IP
    Configure LB in AWS to TLS port 443 to Internal Syspass
    See error

**Error received in Browser:**

Bad Request
Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
Apache/2.4.41 (Ubuntu) Server at ip-10-0-0-132.we-east-2.compute.internal Port 443

**Platform (please complete the following information):**

   OS: Ubuntu 20:04

**Comment by oluapG** [comment]
As you mention, you are using Apache.

Can you try disable SSL in /etc/apache2/sites-available/default-ssl  ?

**Comment by pgabriel10** [comment]
I disable and works. 

Closed. Thanks.
