### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by vvascautan** [nuxsmin/sysPass#193]
Hello,

I am planing to implement sysPass hight-availability by means of master-master replication.
I was wondering if you have any suggestions on db tables that should be replicated or just sync entire syspass database.

Thank you in advance!

**Comment by nuxsmin** [comment]
Hi, you can safely sync the whole sysPass  database because there isn't stored any session related stuff, so the web app can perform queries to any db server.

**Comment by vvascautan** [comment]
Thanks!

**Comment by nuxsmin** [comment]
Did you get it working?

**Comment by vvascautan** [comment]
Hello,
>>Did you get it working?
Yeap. I did Master<->Master MySQL replication and everything is working smoothly.

**Comment by nuxsmin** [comment]
Good news,  thanks!
