### ISSUE TITLE
Will there be a sysPASS that works with PHP 8.x 

### ISSUE THREAD

**Issue by eager-2-learn** [nuxsmin/sysPass#1932]
The latest sysPass works only with PHP 7.3 or 7.4
Ubuntu 22 works with PHP 8.1

Therefore I need a sysPass that works with PHP 8.x

**Comment by Nebucatnetzer** [comment]
Yes there will be but there is no ETA: https://github.com/nuxsmin/sysPass/pull/1806

**Comment by eager-2-learn** [comment]
OK, I wait for it.
