### ISSUE TITLE
Master Password Problem

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#194]
I got a problem if I set a new Master Password in the settings at the encryption tab.
When I select the option "Do not modify accounts" and than I log in with a account and the new master password all passwords are set to "null".

Is it a bug or a feature?

**Comment by nuxsmin** [comment]
That option is only to change the master password without reencrypting the accounts passwords so you won't be able to see the passwords if the encryption key doesn't match....

Everytime you change the master password you need to reencrypt the accounts passwords.

**Comment by Goatmaster** [comment]
So for what I need the switch "Do not modify accounts". I don't get it ...

**Comment by nuxsmin** [comment]
Because if you performs a database import and the imported accounts have been encrypted with a different master password, you can set the new master password without modifying the accounts
