### ISSUE TITLE
two-factor authentication

### ISSUE THREAD

**Issue by wagnst** [nuxsmin/sysPass#199]
Hi,
i don't know if this request was already made, but I cant find anything regarding this one.

I would highly wish an integration for Google Authenticator MOTP Token for login.
So that every user (must/can) configure themselves a token which is required to login.

Thanks + regards,
Steffen

**Comment by nuxsmin** [comment]
Hi @wagnst , this feature is already present at the user preferences. Which version are you running on?

Kind regards,
Rubén

**Comment by wagnst** [comment]
ahh it's totally hidden :P
Found it now. Then another Feature request...

can you please introduce a setting to force two factor authentication per user group?

Thanks,
Steffen

**Comment by wagnst** [comment]
I just tried it out... but when i log in with two factor token, the password list is loading endless... I am able to click in footer to my profile e.g. but password list is not showing up...
![syspass_twofactor](https://cloud.githubusercontent.com/assets/7312523/12844114/c79bac76-cbfd-11e5-8664-577c668a1449.PNG)

**Comment by nuxsmin** [comment]
You're right...this issue happens because the user's profile is set after the 2fa takes place during the login.

It will be fixed shortly.

Thanks for the feedback!!

**Comment by wagnst** [comment]
Tested successfully working!
Thanks a lot @nuxsmin for your fast support!
