### ISSUE TITLE
Login Fails First Time

### ISSUE THREAD

**Issue by sikas89** [nuxsmin/sysPass#201]
Logging to the system fails first time, then asks for the Master Password. Any user level is asked for the Master Password after failing to login the first time. Kindly have this checked.

**Comment by nuxsmin** [comment]
Hi, when any user a first time login he will be asked for the master password, which is needed to decrypt the accounts passwords.

This also is done so if the user changes its password.

**Comment by goro22052** [comment]
I have the same problem.
When ldap user entering the syspass he sees prompt enter login and password again and master-password.
But if the user entered login, password again and new master-password he sees "wrong master password."
