### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Metzlmane** [nuxsmin/sysPass#202]
Hi,

i tried to install sysPass on my Qnap which is somehow not working.
I have all php-modules(5.5.31) enabled and mariadb(5.5.44) running.
When i open the page the first time i get this:

![image](https://cloud.githubusercontent.com/assets/9552092/13074865/98f397f0-d4a7-11e5-96b7-de9829c9d042.png)

The database gets created and the config file is created, but somehow i get a blank page afterwards or  redirected to this installation page. I disabled all addons and tried other browsers, but it's the same.

**Comment by nuxsmin** [comment]
Hi, that looks like an old issue with the gzlib in php, which prevents to load the js and css content.

That issue was related to a Synology NAS and posted here.

**Comment by Metzlmane** [comment]
I removed the IF statement in **Request.class.php** as mentioned in the other post:

```
public static function getRequestHeaders($header = '')
    {
        /*if (!function_exists('\apache_request_headers')) {
            function apache_request_headers()
            {
                foreach ($_SERVER as $key => $value) {
                    if (substr($key, 0, 5) == "HTTP_") {
                        $key = str_replace(" ", "-", ucwords(strtolower(str_replace("_", " ", substr($key, 5)))));
                        $headers[$key] = $value;
                    } else {
                        $headers[$key] = $value;
                    }
                }
            }
        } else {*/
            $headers = apache_request_headers();
        //}

        if (!empty($header) && array_key_exists($header, $headers)) {
            return $headers[$header];
        } elseif (!empty($header)) {
            return false;
        }

        return $headers;
    }
```

I can't find any useful information about a gzlib issue apart some information from 2008 or earlier. Can you please provide a link which describes the problem more specifically?
Thank you!

**Comment by nuxsmin** [comment]
Great!!, this issue has been fixed in the development version, so it will be merged in the next release.

I meant to a recent issue that was posted about 5 months ago...#139

Thanks for the feedback!
