### ISSUE TITLE
language not working - solved

### ISSUE THREAD

**Issue by nlmaca** [nuxsmin/sysPass#203]
can be deleted. had the issue on an rpi with the language switching not working. same as #18 
i fixed it by removing the en_GB.utf from the locales. i had to add the EN_US.ISO88591 first, but didnt know i had to delete the _GB. 
so its working. ticket can be closed or deleted.

**Comment by nuxsmin** [comment]
Great, thanks for the feedback.

It was very strange, because the language file has been compiled for utf8 only
