### ISSUE TITLE
Limiting access by group on AD not working

### ISSUE THREAD

**Issue by vplanas** [nuxsmin/sysPass#204]
Hi!

we've found a problem using an AD group to limit the application access.

Taking a look to the code we've seen that in auth.class.php 
`$ldapGroupAccess = (Ldap::searchUserInGroup($userDN) || LdapADS::searchADUserInGroup($userLogin));`
is allways true becasue Ldap::searchUserInGroup($userDN) is true when in Ldap.class.php
`if (empty($ldapGroup) || !$groupDN = self::getGroupName()) {
   return true;
}`
That's because self::getGroupName() is looking for 'cn=*' pattern in the group name and is not finding it.

We think that Ldap:searchUserInGroup should not be validated when AD config option is active. So we have added at the beginning of ldap:searchUserInGroup() function:
`if (self::$_isADS) {
   return false;
}`
Then on Auth::authUserLDAP() LdapADS::searchADUserInGroup($userLogin) will be evaluated.

It's a good fix? Or do you think we'll have some problem with this change?

**Comment by nuxsmin** [comment]
Hi!

you're right, that method should be bypassed if AD ldap is being used. It will be fixed in the next build.

Thanks for the feedback!!
