### ISSUE TITLE
CSV import error when delimiter is inside a field

### ISSUE THREAD

**Issue by vplanas** [nuxsmin/sysPass#205]
HI!

We've found that importing CSV are not working properly if the delimiter character is inside a filed (e.g. A password account including a ';'). Even when the fields are enclosured by ". 

We've found a solution changing on CsvImportBase.class.php:102
`$fields = explode($this->_fieldDelimiter, $data);`
by
`$fields = str_getcsv($data,$this->_fieldDelimiter);`

PHP 5.3 required and fields should be enclosured by ". 

Thanks!

**Comment by nuxsmin** [comment]
This has been fixed in sysPass 2.0 version, because the PHP version restriction in 1.2 version.

Thanks for the feedback!
