### ISSUE TITLE
Incorrecto Parseo de Caracteres "<" y ">" cuando se utiliza la función copiar password. 

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#206]
Cuando un password contiene los caracteres "<" o ">", y se utiliza la opción "copiar clave en el portapapeles", sin acceder al password, directo desde el listado (ruedita, copiar). 

Los caracteres "<" se copian como código: `&gt;` y `&lt;`

Saludos.

**Comment by nuxsmin** [comment]
Hola, ese comportamiento es debido a javascript, ya que tras varias pruebas, las claves se obtienen sin codificar desde la bd, pero una vez que el plugin clipboard.js copia la clave, estos caracteres son convertidos.

Voy a ver si alguna actualización del plugin lo corrige o si hay algún método en javascript para no convertirlos.

**Comment by vvascautan** [comment]
Hello Guys,

I wanted to open the issue related to &gt and &lt with password and I see it has already opened.
I confirm that if password contains characters like &gt and &lt then password will be added incorrectly.
After the &gt and &lt in password will be added ";" and view password button displays it incorrectly.

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in the latest commits.

**Comment by nuxsmin** [comment]
Hola, he hecho algunas correcciones y ya debe de funcionar correctamente.

Saludos!
