### ISSUE TITLE
LDAP Issue with syspass

### ISSUE THREAD

**Issue by rvinothkannan** [nuxsmin/sysPass#208]
LDAP issue with syspass.

>>>>
Connection error (BIND)
LDAP ERROR: Invalid DN syntax (34)
LDAP DN: Manager
>>>>

ldap_base' => 'dc=xxx,dc=com',
  'ldap_bindpass' => 'xxxxxx',
  'ldap_binduser' => 'Manager',
  'ldap_defaultgroup' => 5,
  'ldap_defaultprofile' => 3,
  'ldap_enabled' => true,
  'ldap_group' => 'xxxxx',
  'ldap_server' => 'xxx.xxx.xxx.xx',
  'ldap_userattr' => '',

**Comment by nuxsmin** [comment]
Hi, you need to provide the right bind user's dn

**Comment by nuxsmin** [comment]
Did it work?
