### ISSUE TITLE
Language will not change

### ISSUE THREAD

**Issue by navenn** [nuxsmin/sysPass#209]
So I installed syspass today, and by default it is in spanish (weird because I installed it earlier today and it was english). So I went to options and chose english. Saved it, however nothing has changed. Language is still spanish.

Here is a piece of config.php.

  'proxy_user' => '',
  'resultsascards' => false,
  'session_timeout' => 300,
  'site_lang' => '',
  'sitelang' => 'en_US',
  'sitetheme' => 'material-blue',
  'version' => '12011',

What is site_lang here?
When I change options sitelang changes but site_lang stays blank. 

I tried restarting apache, even rebooted the server.
Server is debian 8.2 with english locales set.

I will also add that I changed language to English in public demo version- that worked, but I wanted to restore it to spanish and nothing happened ;). You can take a look there.

**Comment by nuxsmin** [comment]
Hi, did you set the language in user preferences?

**Comment by navenn** [comment]
Now I did. However there is no change.
And before login it should ignore user preferences, right?

**Comment by nuxsmin** [comment]
Right, it's very strange...did you setup locales for the utf8 set?

**Comment by navenn** [comment]
Ok it was the issue. For future reference this solved the issue:

sudo locale-gen en_US.UTF-8
dpkg-reconfigure locales

in here set en_US.UTF-8 and choose as default one

Restart apache.

**Comment by nuxsmin** [comment]
Great!! Thanks for the feedback.

I'll point that in the wiki.
