### ISSUE TITLE
Common password for several applications?

### ISSUE THREAD

**Issue by navenn** [nuxsmin/sysPass#210]
Hi, 
Is this somehow possible to use one password for multiple accounts?
Let me elaborate. Let's say we have 3 MS AD accounts. Every account authenticates you to lets say 15 to 25 different applications. Therefore I would have to add 15 to 25 accounts for each domain(this is because I never remember which domain authenticates which application- that's why I need syspass in first place) and repeat the password every time. Then, when I change the password I would have to change it everywhere.
Or maybe a way to leave the password blank with a comment to proper account so then I don't have 25 different passwords for one account :D?

**Comment by nuxsmin** [comment]
Hi, this feature can be accomplished by linked accounts, but it would be available in the next release (1.3 or later).

Meanwhile you can put into the comments field the name of each application that the current account is used for and then you can perform a search for the application name.

Another way to get it (already implemented in the next release) is by using tags, so you can link many tags to each account and then perform a search by tag name.

**Comment by navenn** [comment]
Allright thanks! I will be looking forward for the next release.

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta
