### ISSUE TITLE
keep getting "Connection timed out after 10001 milliseconds"

### ISSUE THREAD

**Issue by esmeralda7** [nuxsmin/sysPass#211]
Hi all,

I installed the latest syspass version on Debian 8 Jessie, there seems to be an issue on my install though. I'm noticing syspass is very slow at times, here some log info:

202	2016-03-16 11:43:34	getDataFromUrl	ADMIN	x.x.x.x	Connection timed out after 10001 milliseconds
201	2016-03-16 11:43:24	getDataFromUrl	ADMIN	x.x.x.x	Connection timed out after 10000 milliseconds
200	2016-03-16 11:40:26	getDataFromUrl	ADMIN	x.x.x.x	Connection timed out after 10001 milliseconds
199	2016-03-16 11:40:16	getDataFromUrl	ADMIN	x.x.x.x	Connection timed out after 10000 milliseconds

Sometimes the response is immediate, sometimes very slow. What can it depend on?

Thanks,

E

**Comment by nuxsmin** [comment]
Hi, that is caused by updates checking, which tries to check it from github 

You can disable it at the config tab.

**Comment by esmeralda7** [comment]
Works like a charm.. many thanks! 

E

**Comment by nuxsmin** [comment]
Great!!
