### ISSUE TITLE
Internal server error durin export accounts

### ISSUE THREAD

**Issue by biroby** [nuxsmin/sysPass#213]
Hi,
i'm writing to you because when I try to export accounts i received an internal error and on event log I can't find anything.
Can anyone help me?

Thanks
Biroby
![error exporting accounts](https://cloud.githubusercontent.com/assets/18185189/14169138/69cb576e-f726-11e5-89db-90526089e6b0.png)

**Comment by nuxsmin** [comment]
Hi, can you check the web server log for any error?

That seems that the response wasn't sent in JSON format, so JavaScript shows that annoying error.

Please check that the backup directory exists and it's writable.

**Comment by biroby** [comment]
Yes I do. I found this error:
[Fri Apr 08 11:27:41.177732 2016] [:error] [pid 8020] [client 10.16.1.29:51923] PHP Fatal error:  Class 'DOMDocument' not found in /var/www/html/sysPass/inc/XmlExport.class.php on line 67, referer: http://syspass.psys.it/index.php

**Comment by nuxsmin** [comment]
Ok, it seems that you need to install the sinplexml php module

**Comment by nuxsmin** [comment]
Did it work?
