### ISSUE TITLE
Download size always 1MB. 

### ISSUE THREAD

**Issue by esmeralda7** [nuxsmin/sysPass#214]
Hello,

i've been using syspass a few weeks by now and i noticed a strange behaviour. I am able to successfully upload a file but when i try to download it from syspass it always cuts the file at 1MB. 
What am i doing wrong?

Thanks,

E

**Comment by esmeralda7** [comment]
Ok maybe this was a stupid question :)

**Comment by nuxsmin** [comment]
Did it work?

**Comment by esmeralda7** [comment]
Unfortunately not. It seems like (with Firefox, Chrome, under linux and windows) the file uploads  correctly. But every time we try to download, it gets "cut" at 1mb size approximately. Very strange. Still working on it! Thanks
