### ISSUE TITLE
url field

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#215]
I found a bug in the url field. 

I entered a page and inside the url was the term 'cmd=getStaticPage'.
After this the password overview list was endlessly loading.

I deleted the entry in the database and the list was shown fine again.

**Comment by Dureaghin** [comment]
I have the same issue.

**Comment by nuxsmin** [comment]
Hi there,

I've tested it without any issue. The string was appended to an URL with and without single quotes, so there would be anything else in the URLs that you're saving.

Can you tell me an example URL?

**Comment by Goatmaster** [comment]
Here is the url that makes problems: https://pki.pca.dfn.de/mpg-ca/cgi-bin/pub/pki?cmd=getStaticPage

**Comment by Goatmaster** [comment]
I also have some problems with passwords they have the "<" sign in it. The rest of the password after the sign is missing.
