### ISSUE TITLE
session timeout

### ISSUE THREAD

**Issue by farhaadn** [nuxsmin/sysPass#218]
hi
i enter 36000 for session timeout
but not work for me

**Comment by manucho6** [comment]
same problem!

**Comment by nuxsmin** [comment]
Hello, Can you take a look to the "/etc/cron.d/php" file?. It can be saved in a different path, but it's very common and healthy to purge unused/expired PHP session files by a cron job.

You can also increase the "session.gc_maxlifetime" in the php.ini file.

Why sysPass doesn't modify that parameter?. Because it would affect to the server performance by increasing the memory usage to allocate all session files in it.

**Comment by farhaadn** [comment]
what i need change ? below is my files

/etc/cron.d/php5 
`09,39 *     * * *     root   [ -x /usr/lib/php5/maxlifetime ] && [ -x /usr/lib/php5/sessionclean ] && [ -d /var/lib/php5 ] && /usr/lib/php5/sessionclean /var/lib/php5 $(/usr/lib/php5/maxlifetime)`

/etc/php5/apache2/php.ini
`session.gc_maxlifetime = 1440`

/usr/lib/php5/maxlifetime
```
#!/bin/sh -e

max=1440

if which php5 >/dev/null 2>&1; then
    for sapi in apache2 apache2filter cgi fpm; do
        if [ -e /etc/php5/${sapi}/php.ini ]; then
            cur=$(php5 -c /etc/php5/${sapi}/php.ini -d "error_reporting='~E_ALL'" -r 'print ini_get("session.gc_maxlifetime");')
            [ -z "$cur" ] && cur=0
            [ "$cur" -gt "$max" ] && max=$cur
        fi
    done
else
    for ini in /etc/php5/*/php.ini /etc/php5/conf.d/*.ini; do
        cur=$(sed -n -e 's/^[[:space:]]*session.gc_maxlifetime[[:space:]]*=[[:space:]]*\([0-9]\+\).*$/\1/p' $ini 2>/dev/null || true);
        [ -z "$cur" ] && cur=0
        [ "$cur" -gt "$max" ] && max=$cur
    done
fi

echo $(($max/60))

exit 0
```

**Comment by nuxsmin** [comment]
The php.ini variable. That takes precedence over the other one.

**Comment by farhaadn** [comment]
you mean i change php.ini file 
session.gc_maxlifetime = 1440 
to 
session.gc_maxlifetime = 3600
and change session timeout from web to 3600 and every thing ok?

**Comment by nuxsmin** [comment]
Right, then every time the cron job is ran the session files will be deleted if they have been created and untouched during the last hour.

**Comment by jrfx85** [comment]
I have changed the value to:
session.gc_maxlifetime = 43200 in /usr/lib/php/7.0/php.ini-production
and set the same value (43200) in syspass (session timeout)

Unfortunaly it doesn't work...still got logged out after 5 minutes...any idea? thanks
