### ISSUE TITLE
sysPass fails to run with an silent 500 error 

### ISSUE THREAD

**Issue by Vad1mo** [nuxsmin/sysPass#219]
Hola, 

we are trying to install sysPass inside a Docker Container. 
After the installation sysPass fails to run with an 500 error. 
`syspass_1 | 172.26.0.3 -  05/May/2016:13:04:48 +0000 "GET /index.php" 500`

This is sadly the only response that we get.

It is easy to reproduce this error. Just run the container with docker-compose that I created and attached in the zip file.

https://dl.dropboxusercontent.com/u/18073806/containerized.zip

1. install [docker toolbox ](https://www.docker.com/products/docker-toolbox) if you are on mac/win otherwise `apt-get install docker-engine  docker-compose`
2. run `docker-compose build` in the same dir where the `.yml` file is located
3. run `docker-compose up` in the same dir where the `.yml` file is located

Here is also the info.php output 
https://dl.dropboxusercontent.com/u/18073806/phpinfo.htm

We have no clues why its not working, as all php packages are installed and configured and the only response is a lousy 500 error without any further details.

**Comment by nuxsmin** [comment]
Hi, it's very strange, because I've been deployed it in docker a few days ago.

Please, take a look to nuxsmin/syspass at docker to get a working image.

The docker files are in github.

Kind regards.

**Comment by Vad1mo** [comment]
thank you,
can you share your `Dockerfile` with us so we know the steps that where done?
We can not use your image without knowing what is inside.

**Comment by nuxsmin** [comment]
Sure, they are at github, under my account repositories.
