### ISSUE TITLE
apache_request_headers breaks minify process if not existant

### ISSUE THREAD

**Issue by alexanderbuhler** [nuxsmin/sysPass#221]
Hey, me again :-)

In the minify class, some request headers are collected for cache-control and pragma. While doing so, getRequestHeaders is beeing called.

If the function is not existant...

`if (!function_exists('\apache_request_headers')) { ...`

you are declaring it. At this point, it just gets declared and - as far as I can see -  isn't called anywhere to eventually fill the `$headers` array. In my case, this leads to 500 internal server errors when calling css.php or js.php.

I moved the function content out of the declaration so that it is executed right on the spot, which fixes the problem.

It looks like this now:

```
    public static function getRequestHeaders($header = '')
    {

        if (!function_exists('\apache_request_headers')) {

                foreach ($_SERVER as $key => $value) {     
                    if (substr($key, 0, 5) == "HTTP_") {                        
                        $key = str_replace(" ", "-", ucwords(strtolower(str_replace("_", " ", substr($key, 5)))));
                        $headers[$key] = $value;
                    } else {                        
                        $headers[$key] = $value;
                    }
                }

        } else {
            $headers = apache_request_headers();
        }


        if (!empty($header) && array_key_exists($header, $headers)) {
            return $headers[$header];
        } elseif (!empty($header)) {
            return false;
        }

        return $headers;
    }
```

Kind regards
Alexander

**Comment by nuxsmin** [comment]
Hi @alexanderbuhler!

that is a great approach, but that I wanted to get with the function declaration is to make it available in the global namespace, so each call to the apache_request_headers function would be fine.

This behavior will be replaced in the next release.

Thanks so much for the feedback ;)
