### ISSUE TITLE
Unable to add new passwords fresh install

### ISSUE THREAD

**Issue by tdk1069** [nuxsmin/sysPass#222]
I get a popup saying Error adding account when trying to add a new password

In the log's this appears : 

SQLSTATE[HY000]: General error: 1364 Field 'account_userEditId' doesn't have a default value(0)

After some google it seems it's to do with the strict mode on the mysql server, no default values set for a required field or such, Due to other databases on the server, I'm unable to change the operational mode of the server. And wouldn't know where to begin to assign a default value.

Any ideas on moving on? 
Thanks

**Comment by tdk1069** [comment]
I found that the tables 'account_userEditId' and 'account_dateEdit' in the sql tables had no default values set as the table default, I have set these to "Null" and can now add and amend passwords. Hope it helps someone

**Comment by tdk1069** [comment]
Actually. Correction, I was unable to actually commit any changes or delete an entry.
I made the defaults on the tables fit inline with the actual data, (a valid ID for UserId and a valid date for date) and it seems to work fine now.
What would be better is the actual valid data being entered at the time of adding a new account, or editing an account. I'll have a poke about. but this part isn't my forte

**Comment by nuxsmin** [comment]
Hi @tdk1069!

You're right, but you may think that if you're adding a new account, no user has performed any modification, so those fields should be blank/null. 
If you can't modify the DB server behavior, you would need to provide a valid default values for those fields: 0 for account_userEditId and '0000-00-00 00:00:00' for  account_dateEdit.

Thanks for the feedback ;)

**Comment by tdk1069** [comment]
Well.. Those values make alot more sense than mine :) I stole the id off admin and I cut and paste the date of the first entry sign. I assumed all 00's would be invalid for some reason.

Can confirm. those values worked fine. Added an entry, Modified it, Deleted it. all without any errors.

I'm unable to remove strict because we are a school. and the pupils need the sql on strict as its how the syllabus is laid out for them (should teach kids validation in my eyes but hey ho) ..

I appreciate the reply very much.

**Comment by tdk1069** [comment]
Just as a heads up incase you are doing anything about default values / Someone else has similar issues.

Once I got ldap up and running, new users couldn't log in because of no default value for user_mIV in the users table. 0 defaulted it and all was fine..

Thanks :)

**Comment by nuxsmin** [comment]
Thanks for the feedback!

I'll check out if the new release does implement that fix.
