### ISSUE TITLE
Unable to export accounts

### ISSUE THREAD

**Issue by sikas89** [nuxsmin/sysPass#223]
Hi, I'm using version 1.2 ..

Tried the backup feature .. it worked as expected, however, I'm not sure how to restore the backups (not important for now as I'm on a dev server, but will need it on the prod)

The important feature that is not working now, is the "Export Account" .. I got the error below:

![image](https://cloud.githubusercontent.com/assets/17160524/15290117/ac482094-1b76-11e6-8580-a634feae830c.png)

Checked the logs, found the below:

![image](https://cloud.githubusercontent.com/assets/17160524/15290132/c4b80f54-1b76-11e6-8a59-e84f1931747c.png)

Not sure what is missing here ..

**Comment by nuxsmin** [comment]
Hi @sikas89 !

can you take a look to the web server log? It seems that you would need SimpleXML php module to get it working.

**Comment by sikas89** [comment]
Hi @nuxsmin ,

Which logs exactly are you referring to? Also, how do I install the SimpleXML? couldn't find a package with that name

**Comment by sikas89** [comment]
@nuxsmin , I checked the server config, and found that SimpleXML is already installed and enabled

![image](https://cloud.githubusercontent.com/assets/17160524/15290943/ddea7e80-1b7b-11e6-9657-bd71114e8d76.png)

**Comment by nuxsmin** [comment]
Ok, you would need to take a look to the web server logs (just after the error). If you are using Apache, they should be located at the '/var/log/apache/error.log'.

BTW, the export feature is not intended to get an usable backup, because it doesn't export any related data for users/groups/config neither any relations between them.

You should use the app/db backup instead, but is very advisable that you schedule a regular DB backup using some backup software or mysqldump utility.

**Comment by sikas89** [comment]
no errors found in the error.log file

user-web@ubuntu-syspass:/var/log/apache2$ tail error.log 
user-web@ubuntu-syspass:/var/log/apache2$ pwd
/var/log/apache2
user-web@ubuntu-syspass:/var/log/apache2$ 

So, for backups, I should take a snapshot of the database, and the syspass folder located under /var/www/html (Web Server Folder) .. Is that correct?

**Comment by nuxsmin** [comment]
Yes it's correct.

It's very strange that no errors were logged. Do you have any account? Does the backup folder exist?

**Comment by nuxsmin** [comment]
Can you enable sysPass debug mode (under config tab)?. This should print any error output to the apache error log.

**Comment by sikas89** [comment]
helo @nuxsmin ... sorry for the late reply .. I re-deployed the server and tested the export accounts feature ..

Below is the error log of the apche (error.log) as well as the debug info from the syspass GUI
[error.log.txt](https://github.com/nuxsmin/sysPass/files/363369/error.log.txt)
[debug_info.txt](https://github.com/nuxsmin/sysPass/files/363370/debug_info.txt)

**Comment by nuxsmin** [comment]
Hello @sikas89, it's very very strange...I've just done a XML export for about ~1800 accounts without any issue.

Does it throw the same error in the sysPass event log?. It failed when retrieving the accounts data from the database that is:

`SELECT account_id, account_name, account_categoryId, account_customerId, account_login, account_url, account_pass, account_IV, account_notes FROM accounts`

**Comment by sikas89** [comment]
where can I find that?

**Comment by nuxsmin** [comment]
Regarding some questions in the past...Do you have any account? Does the backup folder exist?.

Can you perform this SQL query in the database?:
<code>
SELECT account_id, account_name, account_categoryId, account_customerId, account_login, account_url, account_pass, account_IV, account_notes FROM accounts
</code>

**Comment by sikas89** [comment]
I can't check that at the moment .. I'm having another issue which I can't even install syspass .. I'm getting HTTP ERROR 500!

Seems to be an issue with the current version of PHP "PHP Version 5.5.9" .. I'm currently upgrading the OS and will see

**Comment by sikas89** [comment]
@nuxsmin I've re-deployed the Server using Linux Ubuntu 16.04 LTS this time, and have successfully exported Accounts .. I've started to believe that the issue was in the Ubuntu Version or the PHP Version ..

I can deploy another Ubuntu 14.04 LTS to check if you wish ..

In the Installation Guide, you advised to install the packages below:

`apache2 php5 php5-mcrypt php5-mysql php5-curl php5-gd php5-json mysql-server php5-ldap git mcrypt`

But on 16.04 LTS, `php5` doesn't exist, so I used the alternate below:

`apache2 php php-mcrypt php-mysql php-curl php-gd php-json mysql-server php-ldap git mcrypt`

This worked! Since I'm using VMs, I can deploy another server using Ubuntu 14.04 LTS, and use same packages used on the 16.04 LTS .. Just tell me if you want.

**Comment by nuxsmin** [comment]
Great @sikas89 !!...many thanks for the feedback.

Don't worry about testing, because I have tested it yet on several environments like Debian (6, 7 and 8) Ubuntu (14.04 and 16.04), CentOS (6 and 7) and Gentoo, so I think that there would some configuration that interferes with this feature.

Kind regards.
