### ISSUE TITLE
Fallo al copiar la clave desde Safari

### ISSUE THREAD

**Issue by trilce** [nuxsmin/sysPass#224]
Hola,
Tras actualizar de una  versión 1.1 a la ultima del repositorio, desde los navegadores Safari en MAC no se puede copiar la clave pulsando el icono de copiar clave, dando un mensaje de error que de que no se ha podido copiar la clave.
Saludos

**Comment by nuxsmin** [comment]
Hola, voy a investigar sobre esto porque en la nueva versión se utiliza un plugin de javascript en vez de flash.

Qué versión de Safari es?

Saludos.
