### ISSUE TITLE
Exportación de datos sin encriptar

### ISSUE THREAD

**Issue by RobertB1** [nuxsmin/sysPass#225]
Hola,
Primero que nada felicitaciones, está muy bueno el software!
Me preguntaba si hay alguna forma de exportar todos los datos almacenados sin encriptar?
Creo que estaría bueno tener una copia de respaldo de la info en un lugar seguro por las dudas y que no estuviera encriptada.
En caso negativo, se podría incluir en próximas versiones? O me podrás tirar alguna idea como modificar el código para hacerlo?

Gracias!!

**Comment by nuxsmin** [comment]
Hola, 

gracias, me alegro mucho que te guste y te sea útil sysPass:)

Con respecto a la encriptacion, el formato es abierto, ya que utiliza AES-256 por lo que es posible desencriptarla con cualquier software que lo implemente.

No se incluye por defecto ya que creo que es un riesgo de seguridad que alguien pueda obtener todas las claves en texto plano (ni para mí mismo lo he pensado), ya que el uso de esta aplicación está extendido en el mundo empresarial, por lo que si un administrador de la app pudiera obtenerlas, sería contraproducente para el objetivo de la misma.

En la clase crypt estan todas las funciones para encriptar y desencriptar, por lo que puedes exportar las cuentas a XML y posteriormente desencriptar las claves.

Saludos.

**Comment by RobertB1** [comment]
Hola,

Comparto lo del riesgo de seguridad. Mi razonamiento venía por el lado que en realidad en administrador ya tiene acceso a todas las claves o sea que la responsabilidad de lo que haga es indiferente de si puede o no exportarlas todas de una vez o entrando a cada cuenta.
Me parecía buena idea exportar todo y guardarla encriptadas en un contenedor para una emergencia.
Veo de programar el cambio.
Gracias!

**Comment by nuxsmin** [comment]
Hola, puede ser viable, pero creo que hay que articular algún mecanismo para asegurarse que cae en "buenas manos", ya que el ser admin no implica conocer la clave maestra, ni exportar las cuentas y desencriptarlas. Está claro que puede ver todas las claves, pero una cosa es verlas y otra llevarselas.

En varias peticiones me han pedido que el admin no pueda ver todas las cuentas, y tienen cierta razón, por lo que el mecanismo a implementar debe de ser acorde con este requerimiento.

Saludos!

**Comment by nuxsmin** [comment]
Tras analizar los riesgos de este tipo de acción, la mejor forma de realizar esta tarea es mediante la exportación a XML de sysPass y con una utilidad hacer uso de ese XML, así las claves sólo serían visibles por las personas que dispongan de la clave de encriptación.

**Comment by nuxsmin** [comment]
Hola, dicha utilidad ha sido desarrollada por un colaborador, puedes echarle un vistazo por si te sirve: https://github.com/julenpardo/sysPass-XML-Decrypter

**Comment by RobertB1** [comment]
Excelente. Gracias!

El 3 may. 2017 06:45, "RubénD" <notifications@github.com> escribió:

Hola, dicha utilidad ha sido desarrollada por un colaborador, puedes
echarle un vistazo por si te sirve: https://github.com/julenpardo/
sysPass-XML-Decrypter

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nuxsmin/sysPass/issues/225#issuecomment-298866438>, or mute
the thread
