### ISSUE TITLE
Install Problems 

### ISSUE THREAD

**Issue by JannikV1** [nuxsmin/sysPass#230]
. * */ define('APP_ROOT', '.'); require APP_ROOT . DIRECTORY_SEPARATOR . 'inc' . DIRECTORY_SEPARATOR . 'Base.php'; if (!\SP\Init::checkPostLoginActions()) { $controller = new SP\Controller\MainC(null, 'main'); $controller->getMain(); $controller->view(); } 

i cant start sysPass, can any help me ?

Tank you 
Jannik

**Comment by nuxsmin** [comment]
Hi, may be you need to enable PHP?

**Comment by JannikV1** [comment]
Thx, but how can i enable PHP ?

I use PHP 7.0

**Comment by JannikV1** [comment]
you can write in Germann :)

**Comment by nuxsmin** [comment]
You can follow the steps at http://wiki.syspass.org

I haven't tested it yet (PHP 7).

I'd like to speak German and come back again (recently I've been visiting Hamburg and beers are great), but unfortunately I only speak Spanish/English (I'm from Spain) :)

**Comment by JannikV1** [comment]
Ok, no problem, your tip was great. i found the Problem.
My Syspass works, thx.

**Comment by nuxsmin** [comment]
Great!

Thanks for the feedback
