### ISSUE TITLE
smtp password not encrypted in config files

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#232]
hello

smtp password for mail account is stored in non encrypted way in config files; this file is included in full system backup; It would be good for hash/secure the password in config file for security reasons

**Comment by nuxsmin** [comment]
Hello,

Sure, but it would require additional configuration at the MTA side and many people doesn't know how to get it working. I think it can be implemented as an option.

The config folder is secured by filesystem rights, but you may think who would need to have access rights to it.

**Comment by nuxsmin** [comment]
After thinking about it, even "encrypting" the password it can be used on the SMTP login, because you would need a password or encoded password to authenticate against the mail server
