### ISSUE TITLE
Errors after reinstalling server and importing database

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#234]
Hello

i've exported database by mysql dump and imported to reinstalled server. Now i cant delete users - and I wonder if that is the only thing that does not work...

I asked for backup and restore solution and didnt get complete answer. Should I deploy it in my company, migrate data into it, train my coworkers how to user it and trust that "everytnig will be okay?" Is this product reliable? how many installation of syspass are outhere? 

![err](https://cloud.githubusercontent.com/assets/20043789/16337807/7e54bcd6-3a18-11e6-90e0-5504503111fa.png)

**Comment by nuxsmin** [comment]
Sorry,, but I don't know how many people are using sysPass, but by github reports and many sources I think that the community would be big enough to get some valuable feedback.

I don't know why you did receive that error, because in my import tests and the real ones it were done successfully.

Let me do some additional tests to find out what can be happening.

**Comment by akurzawa** [comment]
Sorry for begin a little bit harsh, but I really liked this software and I would like to deploy it in my company. Looking forward for some feedback.

**Comment by nuxsmin** [comment]
Can you tell me if there is any error in the webserver log?

It seems that some error broke the Ajax response.

**Comment by akurzawa** [comment]
Hi

apache log debug, on user delete:

[Wed Jun 29 12:19:26.606461 2016] [authz_core:debug] [pid 1528] mod_authz_core.c(809): [client 192.168.1.165:59533] AH01626: authorization result of Require all granted: granted, referer: http://192.168.1.32/ipm/index.php
[Wed Jun 29 12:19:26.606526 2016] [authz_core:debug] [pid 1528] mod_authz_core.c(809): [client 192.168.1.165:59533] AH01626: authorization result of <RequireAny>: granted, referer: http://192.168.1.32/ipm/index.php
[Wed Jun 29 12:19:26.798089 2016] [deflate:debug] [pid 1528] mod_deflate.c(855): [client 192.168.1.165:59533] AH01384: Zlib: Compressed 4789 to 1492 : URL /ipm/ajax/ajax_appMgmtSave.php, referer: http://192.168.1.32/ipm/index.php

**Comment by nuxsmin** [comment]
Hi, not so much info...and those events aren't related to sysPass actions. Is there another action that actually throws any error?. Can you switch sysPass debug mode on and take a look to the same error file?

**Comment by akurzawa** [comment]
Hi

I've turned on debugging in syspass - too bad that You didnt mention it earlier

I was finally able to delete user from syspass but, something else happend, my master admin (ifs user) in no longer listed in users in syspass and i cant log on that account - but despite that - user is still present in sql database... 

![123](https://cloud.githubusercontent.com/assets/20043789/16451524/e8159638-3e03-11e6-8db5-f791c47bd360.png)

**Comment by nuxsmin** [comment]
Really strange...let me find out what can be happening

**Comment by nuxsmin** [comment]
Hello, the only thing that can be avoiding to show that user is that the current user that is logged in is not an Application Admin, so you won't be able to view AppAdmin accounts. Does it?
