### ISSUE TITLE
Can't login since update to 1.2.11

### ISSUE THREAD

**Issue by puzzle-it-nu** [nuxsmin/sysPass#235]
I just updated my syspass from around feb-2016 to today using git pull in the syspass folder of my webserver.
Now we can't login anymore using our AD credentials. I see that PR 204 changed the search logic and the following is logged in the log table of syspass:
5 

2016-06-26 11:20:18 

searchADUserInGroup 

*.*.*.* 

No group found with that name
LDAP ERROR: Success(0)
LDAP FILTER: (memberof:*.*.*.*.1.4.1941:=CN=Git_Admins,CN=Users,DC=ad,DC=puzzle-it,DC=nu)

The last line looks wrong to me. Also the webserver logs something similar:
[Sun Jun 26 10:57:07 2016] [error] [client 192.168.11.11] FastCGI: server "/php-fpm-handler" stderr: PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'No group found with that name' in /volume1/web/syspass/inc/LdapADS.class.php:117, referer: https://syspass.puzzle-it.nu/
[Sun Jun 26 10:57:07 2016] [error] [client 192.168.11.11] FastCGI: server "/php-fpm-handler" stderr: Stack trace:, referer: https://syspass.puzzle-it.nu/
[Sun Jun 26 10:57:07 2016] [error] [client 192.168.11.11] FastCGI: server "/php-fpm-handler" stderr: #0 /volume1/web/syspass/inc/Auth.class.php(99): SP\\LdapADS::searchADUserInGroup('USERNAME_REDACTED'), referer: https://syspass.puzzle-it.nu/
[Sun Jun 26 10:57:07 2016] [error] [client 192.168.11.11] FastCGI: server "/php-fpm-handler" stderr: #1 /volume1/web/syspass/ajax/ajax_doLogin.php(57): SP\\Auth::authUserLDAP('USERNAME_REDACTED', 'PASSWD_REDACTED'), referer: https://syspass.puzzle-it.nu/

Reverting the change in Auth.class concerning PR204 makes the login work again.

Hoping this is enough to find the problem,

Joop

**Comment by nuxsmin** [comment]
Hi, you're right, the search logic has been changed to perform recursive group membership searches, so you can be a member of the last group in the chain and then the membership look up will be success.

Let me know what ADS schema and windows  versions are you running on.

**Comment by puzzle-it-nu** [comment]
On 26-6-2016 16:50, nuxsmin wrote:
>
> Hi, you're right, the search logic has been changed to perform
> recursive group membership searches, so you can be a member of the
> last group in the chain and then the membership look up will be success.
>
> Let me know what ADS schema and windows versions are you running on.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nuxsmin/sysPass/issues/235#issuecomment-228604917>, or
> mute the thread
> <https://github.com/notifications/unsubscribe/AS9-DaBzpXW32I-XCSGMNAabGuMldxRsks5qPpHHgaJpZM4I-hTg>.
>
  'ldap_ads' => true,
  'ldap_base' => 'cn=Users,dc=ad,dc=puzzle-it,dc=nu',
  'ldap_bindpass' => 'REDACTED_PWD',
  'ldap_binduser' =>
'cn=syspass_binduser,cn=users,dc=ad,dc=puzzle-it,dc=nu',
  'ldap_defaultgroup' => 1,
  'ldap_defaultprofile' => 1,
  'ldap_enabled' => true,
  'ldap_group' => 'Git_Admins',
  'ldap_server' => 'raadhuis.ad.puzzle-it.nu',

OK, accounts in the Git_Admins group can login if the refactoring isn't
active. Using master branch makes this config unable to login.
AD server is a Samba4 AD-DC controller (raadhuis.ad)
Login is from a Windows7 Ultimate.

What I find strange is the logging with the accountname being logged
while its about groups. That can't be right.

Need anything else?

Joop

**Comment by nuxsmin** [comment]
Hi, what does happen if you switch ADS button off?, Does it log in?

I think that this AD behavior is not implemented in Samba 4 LDAP schema.

**Comment by puzzle-it-nu** [comment]
On 29-6-2016 13:05, nuxsmin wrote:
>
> Hi, what does happen if you switch ADS button off?, Does it log in?
>
> I think that this AD behavior is not implemented in Samba 4 LDAP schema.
>
>
They claim to be a full replacement for Windows AD so I think it should
work.

Could you give me the filter expression that it should generate?
I can then test if that works or not and what to change if it doesn't

Regards,

Joop

**Comment by nuxsmin** [comment]
Sure, but it can be that there are some changes in its internal behavior.

Here you have the search filter (please replace 'fill_in_user_DN' with the full user DN like cn=User,cn=Users,DC=ad,DC=puzzle-it,DC=nu):

`(&(cn=CN=Git_Admins,CN=Users,DC=ad,DC=puzzle-it,DC=nu)(|(member=fill_in_user_DN)(uniqueMember=fill_in_user_DN))(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group)))`

**Comment by JvdW** [comment]
On 29-6-2016 13:48, nuxsmin wrote:
>
> Sure, but it can be that there are some changes in its internal behavior.
>
> Here you have the search filter (please replace 'fill_in_user_DN' with
> the full user DN like cn=User,cn=Users,DC=ad,DC=puzzle-it,DC=nu):
>
> |(&(cn=CN=Git_Admins,CN=Users,DC=ad,DC=puzzle-it,DC=nu)(|(member=fill_in_user_DN)(uniqueMember=fill_in_user_DN))(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group)))|
>
>
Thanks, I'll try to test it this evening (GMT+2).

Joop

**Comment by nuxsmin** [comment]
Hi, did you test it?

**Comment by JvdW** [comment]
On 6-7-2016 22:50, nuxsmin wrote:
>
> Hi, did you test it?
>
>
Sorry, I haven't had time to test it. Will try it tonight.

Thanks for the reminder,

Joop

**Comment by puzzle-it-nu** [comment]
On 29-6-2016 13:57, JvdW wrote:
> On 29-6-2016 13:48, nuxsmin wrote:
> >
> > Sure, but it can be that there are some changes in its internal
> behavior.
> >
> > Here you have the search filter (please replace 'fill_in_user_DN' with
> > the full user DN like cn=User,cn=Users,DC=ad,DC=puzzle-it,DC=nu):
> >
> >
> |(&(cn=CN=Git_Admins,CN=Users,DC=ad,DC=puzzle-it,DC=nu)(|(member=fill_in_user_DN)(uniqueMember=fill_in_user_DN))(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group)))|
> >
> >
> Thanks, I'll try to test it this evening (GMT+2).
>
I tested by logging all ldap queries that are made to Samba and then
something struck me.
I have Git_Admins defined as the group that has access to syspass in the
syspass config and I also have defined that the searchbase is from Users
down. Git_Admins is down under that search so I don't get it why I can't
login. Removing Users from the searchbase restores the possibility to
login :-)

The following is what get send to Samba in the old way with Users in the
searchbase:
ldb_request SUB dn=cn=Users,dc=ad,dc=puzzle-it,dc=nu
filter=(&(|(samaccountname=MY_LOGIN)(cn=MY_LOGIN)(uid=MY_LOGIN))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))

This is what get send in the new way:
 ldb_request SUB dn=dc=ad,dc=puzzle-it,dc=nu
filter=(&(|(samaccountname=MY_LOGIN)(cn=MY_LOGIN)(uid=MY_LOGIN))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))
  ldb_request SUB dn=CN=Configuration,DC=ad,DC=puzzle-it,DC=nu
filter=(&(|(samaccountname=MY_LOGIN)(cn=MY_LOGIN)(uid=MY_LOGIN))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))
  ldb_request SUB dn=DC=ForestDnsZones,DC=ad,DC=puzzle-it,DC=nu
filter=(&(|(samaccountname=MY_LOGIN)(cn=MY_LOGIN)(uid=MY_LOGIN))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))
  ldb_request SUB dn=DC=DomainDnsZones,DC=ad,DC=puzzle-it,DC=nu
filter=(&(|(samaccountname=MY_LOGIN)(cn=MY_LOGIN)(uid=MY_LOGIN))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))
 
So it looks like the line that you gave me to look for doesn't show up :-(

Joop

**Comment by nuxsmin** [comment]
Ummm, it's very annoying because that group should be located under that search base.

Can you perform another search with this filter?:

```
(&(cn=Git_Admins)(|(objectClass=groupOfNames)(objectClass=groupOfUniqueNames)(objectClass=group)))
```

**Comment by nuxsmin** [comment]
Can you try out the latest commit?

**Comment by nuxsmin** [comment]
There were some bugfixes on the LDAP auth over ADS.
