### ISSUE TITLE
Users with permissions to multiple groups

### ISSUE THREAD

**Issue by jcboysha** [nuxsmin/sysPass#236]
Is there any way to assign one user to have permissions to multiple groups?

**Comment by nuxsmin** [comment]
Actually there isn't. BTW you can assign the users by group, that is the users can be assigned within the groups, so that group will be a secondary one to those users.

I think that the user tab should be clear, if there is too much fields it becomes a mess with primary and secondary groups fields.

**Comment by jcboysha** [comment]
That actually solves my problem. Thanks! I just needed one user to be able to see the passwords from 2 groups.

**Comment by nuxsmin** [comment]
Great!. Thanks for the feedback ;)
