### ISSUE TITLE
Using LDAP users to logon

### ISSUE THREAD

**Issue by guannais** [nuxsmin/sysPass#240]
Hello,

I have LDAP configuration (Active Directory 2012) done correctly (green!), it founds 9 objects when I test it but when I tried to logon with one of them it doesn´t try to use LDAP instead of MySQL. LDAP options are enabled. Any idea of the problem???

This is the event log:

![screen shot 2016-07-07 at 11 34 35](https://cloud.githubusercontent.com/assets/9401585/16648975/d6f273e2-4436-11e6-960c-678874945575.jpg)

Thanks for your great work!

**Comment by nuxsmin** [comment]
Hello,

I'm very glad that you like it!

It's very strange, because those events logged were set at the same time.

Did you save the parameters after checking them?

Does it happen with each LDAP user?

Kind regards

**Comment by guannais** [comment]
Hello,

It happends with our 9 users :( 

This is my config.php

  'ldap_ads' => true,
  'ldap_base' => 'OU=XXXXXXXXX,OU=XXXXXXXXX,DC=XX,DC=local',
  'ldap_bindpass' => 'XXXXXXXXX',
  'ldap_binduser' => 'user',
  'ldap_defaultgroup' => 1,
  'ldap_defaultprofile' => 1,
  'ldap_enabled' => true,
  'ldap_group' => 'CN=XXXXXXXXX,OU=XXXXXXXXX',
  'ldap_server' => 'ldap://XXXX.XX.XXXX',
  'ldap_userattr' => '',
  'log_enabled' => true,

This is the test of ldap settings:

![screen shot 2016-07-08 at 07 41 44](https://cloud.githubusercontent.com/assets/9401585/16678454/78465594-44df-11e6-946d-ef1fcbb7cdb4.jpg)

What can I do??

![screen shot 2016-07-08 at 07 34 15](https://cloud.githubusercontent.com/assets/9401585/16678340/6ecdc868-44de-11e6-83b6-3e794be92ba4.jpg)

Regards!

**Comment by nuxsmin** [comment]
Hola, creo que hablas español ;)

Es raro, porque la configuración es correcta, pero en ningún momento se intenta hacer el login con LDAP, sólo MySQL. Prueba a poner sólo el nombre del servidor (sin ldap://) y el grupo sin el DN completo, es decir, sólo el nombre del grupo.

**Comment by nuxsmin** [comment]
Ok, ya sé dónde está el problema...al ser ADS, las URLs del tipo ldap:// y ldaps:// no son analizadas, ya que para ADS se comprueba si existen más servidores DC en el dominio, así se obtiene redundancia.

**Comment by guannais** [comment]
Si, me has pillado 👍 

¿Hay alguna configuración / opción que pueda hacer en esta versión?

Gracias!

**Comment by nuxsmin** [comment]
Sólo poner el nombre del servidor DC

**Comment by guannais** [comment]
Mismo resultado, tambien he probado a cambiar el valor del grupo sin el DN cualificado y sigue igual. El usuario "bind" no cuelga directamente del raiz de la busqueda sino que esta dentro de una OU. ¿Puede venir por ahi?

Gracias,

**Comment by nuxsmin** [comment]
Puede ser, pero daría otro error, y es más, la comprobación fallaría.

**Comment by nuxsmin** [comment]
Prueba incluso a poner la dirección IP del servidor DC

**Comment by guannais** [comment]
He hecho una prueba, en la función donde se comprueban que los parametros esten seteados, en el fichero ./inc/Ldap.class.php he cambiado la linea 266 para que me devuelva siempre true y mira lo que me registra el log de eventos:

![screen shot 2016-07-08 at 08 26 35](https://cloud.githubusercontent.com/assets/9401585/16679200/fa985cb2-44e5-11e6-9c92-6e19e75c0ac5.jpg)

**Comment by guannais** [comment]
Vale, conseguido!!! He revertido el cambio y he puesto la IP del servidor. He conseguido acceder correctamente!!! No entiendo muy bien el motivo (soy de Sistemas) al final es una resolución DNS que esta haciendo pero por algun motivo no funciona.

Muchas gracias!!

**Comment by nuxsmin** [comment]
Pues ese error es referente a la conexión con el servidor de LDAP.

La parte del código que verifica es esta:

```
if (!self::$_searchBase || !self::$_ldapServer || !self::$_bindDN || !self::$_bindPass) {
            Log::writeNewLog(__FUNCTION__, _('Los parámetros de LDAP no están configurados'));
            return false;
        }
```

**Comment by nuxsmin** [comment]
La resolución DNS se hace con la zona "_msdcs.dominio":

```
       $dnsServerQuery = '_msdcs.' . $serverDomain;
        $records = dns_get_record($dnsServerQuery, DNS_NS);
```

**Comment by nuxsmin** [comment]
Es conveniente que revises la zona de AD, ya que puedes encontrar problemas de lentitud o aplicación de GPOs en tu dominio....(soy también de sistemas ;))

**Comment by nuxsmin** [comment]
O los servidores DNS del propio host de sysPass...

**Comment by guannais** [comment]
Estoy revisando, es un Linux, tenemos trampeado el host del servidor, tenia el registro _msdcs.dominio.local con un registro erroneo. Voy a seguir revisando y te cuento.

Un abrazo,

**Comment by guannais** [comment]
Vale, solucionado, he cambiado el registro que estaba mal y funciona por nombre DNS.

Muchisimas gracias!

**Comment by nuxsmin** [comment]
Bien!!, me alegro que vaya bien

Espero que te sea útil ;)

**Comment by MikeTheSwede** [comment]
It is a pity that you stopped writing in english, because I cannot follow the discussion now!
