### ISSUE TITLE
Conceder acceso de forma masiva.

### ISSUE THREAD

**Issue by ferrergl** [nuxsmin/sysPass#241]
Buenos días.

Al intentar dar acceso a una nueva persona a los datos de determinados clientes me he dado cuenta que no puedo conceder todos los permisos de golpe, viéndome obligado ha realizar el cambio para cada uno de las cuentas de forma individual. Seria posible implementar en futuras versiones una gestion global de permisos por cliente o categoría?

**Comment by nuxsmin** [comment]
Added to roadmap #422
