### ISSUE TITLE
identificación en dos pasos

### ISSUE THREAD

**Issue by ferrergl** [nuxsmin/sysPass#242]
Al activar la identificación en dos pasos, tras acceder y introducir el segundo factor, no se listan las cuentas. Se queda pensando un rato y se queda la pantalla con el header y el footer y nada mas.

**Comment by nuxsmin** [comment]
Buenas, he probado en el entorno demo (demo.syspass.org) y funciona correctamente. Si recargas la página funciona?

**Comment by guannais** [comment]
A mi me ha funcionado correctamente al activar los dos pasos.
