### ISSUE TITLE
creation problem new acount

### ISSUE THREAD

**Issue by JannikV1** [nuxsmin/sysPass#244]
![2016-07-13 11_39_16-syspass_neuste_version_ubuntu auf vm2](https://cloud.githubusercontent.com/assets/19976815/16798901/8c985278-48ee-11e6-9316-4aee5df81ad9.png)

Hi, 
i have a creation problem, i cant creat a new acount.
The log can you see in the pictur 

thx Jannik

**Comment by nuxsmin** [comment]
Hi, it's an old issue when mysql is set in strict mode. This behaviour will be fixed in the next release.

Please, look for a related issue in this github repository.

**Comment by nuxsmin** [comment]
Solved
