### ISSUE TITLE
mysql issue

### ISSUE THREAD

**Issue by idingir** [nuxsmin/sysPass#245]
If you trying to install latest release with mysql 5,6+ in apache error log you will see:
Exception: SQLSTATE[28000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES), referer:

On mysql 5.5 looks good.

I'm suppose it's because of validate password plugin

**Comment by nuxsmin** [comment]
Hi, really strange. I know that this issue has happened many times, but I have installed sysPass in many OS like Debian 8, Centos 7, Ubuntu 14 and some others without this kind of issue.

I think that is more related to permissions issues.

Can you tell me more info about your environment?

Thanks for the feedback!

**Comment by idingir** [comment]
CentOS Linux release 7.2.1511 (Core) 
mysql - had tried install your app with  versions -  mysql57-community \ mysql56-community,  but with them i faced with a problem (see attached screenshot.)
I noticed, that database  was successfully created but without of any data in tables.
![image](https://cloud.githubusercontent.com/assets/16521032/16812282/101e7136-4935-11e6-85aa-4ea314cdbaaf.png)


Now i'm using:
 Server version: 5.5.50 MySQL Community Server

**Comment by nuxsmin** [comment]
Ok, let me find out what can be happening.

**Comment by nuxsmin** [comment]
Hi there!.

Can you try out the latest commit?
