### ISSUE TITLE
Installation failed with a DB error '... could not find driver"

### ISSUE THREAD

**Issue by fatyogi** [nuxsmin/sysPass#247]
Hi, I am installing SysPass on Alpine Linux with MariaDB 10.1.14, PHP 5.6.23 and Light HTTPD 1.4.39 using the **Hosted** mode when I pre-created the user **syspass** and the database with the same name.

I have also written a simple PHP script that uses the same credentials to connect to the syspass database, and it connects absolutely fine. PHP5 modules php5-mysql and php5-mysqli are installed, as well as all other modules required by syspass.

Yet, when I configure the initial parameters during installation I get the following message;

**"Please, check connection parameters
could not find driver"**

That's it - nothing in the logs.

I tried the root DB user and password too with similar results.
Any ideas?

Thanks
Oleg

**Comment by fatyogi** [comment]
Oops - added PHP5-Mysql-PDO and it worked. Thank you!

**Comment by nuxsmin** [comment]
That is nice that you get it working.

**Comment by fatyogi** [comment]
Yes you can safely count Alpine Linux among those distros where SysPass
works. Cheers Oleg
