### ISSUE TITLE
"CONSULTA INVÁLIDA" todo el rato

### ISSUE THREAD

**Issue by anogues** [nuxsmin/sysPass#249]
Hola.

Parecido a problemas reportados anteriormente no paro de tener este problema.

Solo funciona la primera vez. Creo que es algo que tiene que ver con lo que se tarda en introducir el text a buscar.

Si hago un copy paste en el buscador va bien, pero si voy escribiendo el nombre de la cuenta a buscar carácter a carácter, a partir del segundo empieza a retornar consulta inválida. Y la búsqueda o va muy lenta o no acaba nunca.

La verdad que el programa va muy bien pero con esto se vuele inusable.

Hay alguna manera de arreglarlo?

Saludos,
Albert.

**Comment by nuxsmin** [comment]
Buenas, 

El problema es debido a que cada vez q se inserta un carácter a partir del tercero, se realiza un búsqueda y se genera un nuevo token de seguridad.  Este token ha de ser actualizado y enviado en cada búsqueda por lo que puede ser que no se envie a tiempo.

Hace tiempo hice una modificación en el retardo entre pulsaciones para establecerlo en 500ms, así se minimiza la incidencia.

En la versión 1.3 he modificado la forma de obtener el token. Esta versión la estoy terminando, por lo que espero que funcione correctamente.

Saludos

**Comment by anogues** [comment]
Perfecto pues, esperamos a la nueva versión.

Gracias por el curro :)

Albert.

**Comment by nuxsmin** [comment]
Buenas, en la actual versión (últimos commits) he deshabilitado la búsqueda contínua, por lo que es necesario pulsar la tecla "intro" para realizar la búsqueda por cadena de texto.

Esta característica hacía un uso intensivo del servidor, ya que cada caracter que se introduce genera una petición HTTP y la correspondiente consulta a la BBDD.

La idea para la versión 1.3 es implementar un método de autocompletado que no genere la consulta completa (estilo google).

Saludos.

**Comment by anogues** [comment]
Hola.

Pruebo de actualizar y te digo que tal va ahora.

A mi lo del intro no me supone mucho problema, mejor eso que que se quede frito, la verdad.
Saludos y gracias de nuevo.
