### ISSUE TITLE
Please help to LDAP authentication with sysPass.

### ISSUE THREAD

**Issue by nhanvolac** [nuxsmin/sysPass#250]
Hi,

I am a newbie with sysPass.

When I configure sysPass, I have an issue with LDAP authentication.

Error: 
LDAP ERROR: Can't contact LDAP server (-1)
LDAP DN: uid=...,ou=...,dc=...,dc=...,dc=...
![ldap2](https://cloud.githubusercontent.com/assets/20902182/17514307/124aebec-5e5c-11e6-99ab-1b310b7a873e.JPG)

Here is the configure LDAP .
![ldap](https://cloud.githubusercontent.com/assets/20902182/17514066/bc79714e-5e5a-11e6-891a-99b1071dcd0f.JPG)

When I click to "check" button, it shows a warning "Error on LDAP connection".

Thanks for your great work!!!

**Comment by nuxsmin** [comment]
Hi, that error is likely because your DNS settings are wrong.

Can you perform some DNS tests on your sysPass server?

The application performs a DNS query to pick a random DC server.

**Comment by Thade780** [comment]
Use a specific user account with appropriate permissions instead of using the container string for the bind user.

**Comment by nuxsmin** [comment]
+1
