### ISSUE TITLE
Ldap module Unavailable

### ISSUE THREAD

**Issue by MikeyHoef** [nuxsmin/sysPass#251]
Hello,

I've installed syspass on Debian, but i can't get the Ldap module available to configure with AD. When i go to the LDAP part in settings the Module stays unavailable. I already installed slapd on the (Debian) server and tried to configure but no results and still have the Module unavailable message. 

Could someone help me out with this, I fight with it now for 2 days.

Thanks in Advance! :+1:

**Comment by nuxsmin** [comment]
Hello,

Did you install the PHP LDAP module?

That module is needed to perform the LDAP functions. You would find it as 'php5-ldap'.

Hope it works ;)

**Comment by MikeyHoef** [comment]
Yes I did, 

php5-ldap is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by nuxsmin** [comment]
Ok, I think so but...did you restart the Apache service?

**Comment by MikeyHoef** [comment]
You're great! And i'm a n000b!!! 
Thanks alot!

**Comment by nuxsmin** [comment]
Great!!

You're welcome ;)
