### ISSUE TITLE
Disable master password

### ISSUE THREAD

**Issue by MikeyHoef** [nuxsmin/sysPass#252]
Is it posible to disable the master password so that users don't have to fill in the master password during the login.

**Comment by Goatmaster** [comment]
It's not possible, the master password is needed to decrypt the database to check the password of the user (I hope I am right here but that is how I understood it). 

But the user only need to enter the password at the first login, the next logins will work without the master password.

**Comment by nuxsmin** [comment]
You're right @goatmaster

The master password is needed to decrypt the accounts' password, but every user encrypts it with its own password so they only need to provide it once or when its own password is changed.

For security reasons, you can provide a temporary master password so you don't need to provide the real one.
