### ISSUE TITLE
Edit button not working

### ISSUE THREAD

**Issue by patm80** [nuxsmin/sysPass#253]
Hey there,

I tried installing syspass with the installation instructions. The installation seems to work fine and I can login with my admin account. What is weird is that when I try to edit an user or anything (meaning clicking the 'edit' button) syspass always shows me the from to create a new user. There were no errors while intalling and I can't find any logs regardings the installation. I followed these instructions:  http://wiki.syspass.org/en/install

I also have a question regarding the installation. I saw that there is created a mysql user when I run the installation. I was wondering how I can change those settings afterwards. Because I also ask myself which credentials will be set for the mysql user. Do I do this just by editing the config.php file?

Those questions may be rather simple but I am not able to get those answers by my self, sorry for that.

Syspass is running on a Linux Mint 18 and all the prerequisites should be installed.

Thanks in advance,
Patrick

**Comment by nuxsmin** [comment]
Hi Patrick,

I've never heard that annoying issue, it's very strange but let me find out what can be happening...

About db credentials, you can change them in the config.php file by setting dbuser and dbpass variables. The dbuser was prefixed by sp_ to avoid an username collision, and the password was generated by hashing the admin pass and the time when it was created. You can change them without any issues.

Kind regards

**Comment by patm80** [comment]
Hey,

thanks for the quick response. If you need any information from me don't hesitate to ask! I will try to make it work again.

Thanks for your help,

Patrick

**Comment by patm80** [comment]
I dont't know if I expressed myself correctly: The problem is, that when I click the 'edit' button on any page, I can't edit users or groups or whatever it is I want to edit. Instead syspass shows always the empty form of that element I want to edit (users, groups etc).

I hope that helps,

Thanks!

**Comment by ArminXG** [comment]
Are there any news on that issue? I have exactly the same problem with a just freshly installed version 1.2.0.12 on ubuntu server 16.04 (php7).
Besides showing the empty/create form when clicking on 'edit', I cannot delete a group or profile. It asks me if I really want to delete the item, but on 'yes' nothing happens.

**Comment by nuxsmin** [comment]
Hello, all tests done were fine. I'll need to install php7 to try out with that version.

**Comment by nuxsmin** [comment]
Solved

**Comment by thx2000** [comment]
I'm having this same issue.  Is there something specific I need to do to take advantage of the fix that was posted?
