### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by MikeyHoef** [nuxsmin/sysPass#254]
Goodmorning!

I finished al the dutch translations @ http://translate.syspass.org/index.php?translate-sel=nl_NL 
Al the strings have a translation, when i try to submit the page on the end of the page I get an error. 

It just say Error, nothing else. 

What am I doing wrong? We would like to have the dutch translations :)
Regards!

**Comment by nuxsmin** [comment]
Great!!

Let me find out what can be happening with the translation site.

Thanks for your work ;)

Good night!

**Comment by MikeyHoef** [comment]
Good night! :+1:
Great!!!

**Comment by nuxsmin** [comment]
Hello @MikeyHoef ,

I've just implemented the Dutch translation for sysPass (uploaded in the latest commit). There are some minor strings that would need to be translated, and I've also unlocked those which need review.

Great work!!

**Comment by stvorenje** [comment]
I could translate sysPass to Croatian if You like...

**Comment by nuxsmin** [comment]
It's great @stvorenje , I've added your language at the translate site: http://translate.syspass.org/index.php?translate-sel=hr_HR

Kind regards

**Comment by stvorenje** [comment]
Great! I'm filling it.

**Comment by MikeyHoef** [comment]
One more thing... I tried to review all the translations. But i can only save 3 reviews after the the error: "Reviews exceeded, please refresh this page" 

So... i stopped... After selected about 200 translation selections I tried to save, but it failed :(

**Comment by nuxsmin** [comment]
Umm, right, that is a security mechanism to avoid massive deletion/changing. Let me switch them for review.
