### ISSUE TITLE
LDAP parameters are not set

### ISSUE THREAD

**Issue by MikeTheSwede** [nuxsmin/sysPass#257]
I cannot get the LDAP connection to MS AD working. The LDAP settings in GUI seems ok, the "check" button recieves 14 users in the group that I have entered. The Bind user has only read permission in AD, is that OK?
When I try to login with an AD account belonging to that group, it just says wrong user/password.
In the log it says:

70 	2016-08-24 08:19:31 	checkLDAPParams 		192.168.XX.XX	LDAP parameters are not set

![2016-08-24 08_23_38-syspass __ systems password manager](https://cloud.githubusercontent.com/assets/21213523/17920400/95ca4d04-69d4-11e6-8100-32a48f49ccac.png)

**Comment by MikeTheSwede** [comment]
It seens that this issue has been discussed before https://github.com/nuxsmin/sysPass/issues/240 , but in Spanish.. So I do not know how to resolv this..

**Comment by nuxsmin** [comment]
Hi don't worry about the other issue, because it was related to a DNS issue which doesn't apply for this one.

It seems that your LDAP group filtering isn't working fine. Make sure that the group is located under the search base and try also to put only the group name.

Kind regards

**Comment by MikeTheSwede** [comment]
The group thing is not working. My account IS member of that group that I have entered "IT-Drift". I have tried both DN format and just the group name. The logs just says "The user has no associated groups". I also had to enter the IP address of the DC server, otherwise I just got "checkLDAPParams" error.
The group is also in the "search base".

**Comment by nuxsmin** [comment]
Hello, did you save the settings?

Can you take a look to sysPass config file in config directory?

**Comment by MikeTheSwede** [comment]
Yes, the settings are saved.

config.php looks fine. All LDAP entries looks ok, They are most in DN format:


`
  'ldap_ads' => true,
  'ldap_base' => 'ou=MTUA,dc=mtua,dc=XX',
  'ldap_bindpass' => 'XXXXXXXX',
  'ldap_binduser' => 'cn=AD Reader,ou=Service Accounts,ou=Special Accounts,ou=mtua,dc=MTUA,dc=XX',
  'ldap_defaultgroup' => 2,
  'ldap_defaultprofile' => 1,
  'ldap_enabled' => true,
  'ldap_group' => 'CN=IT-drift,OU=Groups,OU=MTUA,DC=mtua,DC=XX',
  'ldap_server' => '192.168.XX.XX',
  'ldap_userattr' => '',
`

User belonging to the group IT-drift gets this in the log:
`278 	2016-08-29 07:45:49 	Log in 		192.168.18.62 	(LDAP)
The user has no associated groups
User: admmosth
277 	2016-08-29 07:45:49 	authUserLDAP 		192.168.18.62 	The user doesn't belong to the group
User : CN=AdminXXXXXX,OU=MTUAdmin,OU=Admin Accounts,OU=Special Accounts,OU=MTUA,DC=mtua,DC=se
`

**Comment by MikeTheSwede** [comment]
I think I am on to something now..
It seems that Syspass is getting confused about lower- and uppercase in the LDAP login name.
In the windows world, it does not matter, but in Linux it does. So I need to use the exaxt login name with the uppercase letter to get it to work! In my Windows AD the exact account is named "AdmMOsth". so when using groups setting, "admmosth" does not work. This should be looked in to!

**Comment by nuxsmin** [comment]
Fine, so did you test it by unsetting group filtering?, If so, can you set the group filter to the group name instead of DN?.

It's very weird that case is took into account, because that behavior is set on the server side (ADS), by changing the attribute schema definition. By default, this attribute has "EQUALITY MATCHING RULE caseIgnoreMatch"

**Comment by MikeTheSwede** [comment]
I can login without group filtering, correct. Group name does not work either.

**Comment by nuxsmin** [comment]
Hello, can you try out the latest commit?, There are some LDAP related fixes.

**Comment by nuxsmin** [comment]
It seems that the group name regex only worked when the LDAP group was set to "CN=groupname"

**Comment by nuxsmin** [comment]
Can you try out with the latest commit?

**Comment by MikeTheSwede** [comment]
And how  do  I  get The latest  commit?
Just so I do  not  break anything

Skaffa Outlook för Android<https://aka.ms/ghei36>



On Thu, Sep 1, 2016 at 12:35 AM +0200, "nuxsmin" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you try out with the latest commit?

**Comment by nuxsmin** [comment]
You need to download it from the github project page, at the code tab.

You can install another sysPass instance or put in place the current one (after performing a backup). The master branch only contains the current stable version plus bug fixes, and if a db is needed, you'll need to provide an upgrade key.
