### ISSUE TITLE
Documentation request: Active Directory integration manual

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#258]
Hello

I would like to integrate syspass with MS Active Directory, can You post an example configuration/prerequisites about how to integrate syspass with AD?

There is nothing in wiki about connecting syspass to AD

![screen](https://cloud.githubusercontent.com/assets/20043789/17924968/3d1bd38c-69eb-11e6-9510-f062a6e14cea.PNG)

**Comment by MikeTheSwede** [comment]
I need this to. My Group settings does not work

**Comment by nuxsmin** [comment]
Hello @akurzawa,

You can get some info by pointing the mouse over the question icons.

The LDAP config is quite simple, but you will need some knowledge about how LDAP works and what means some terms such as DN or OU. If the connection fails, you can get some info at the sysPass event log.

**Comment by akurzawa** [comment]
Hello

Could You be so kind and post example configuration with active directory integration?

**Comment by nuxsmin** [comment]
Sure, here you have an example:
![seleccion_040](https://cloud.githubusercontent.com/assets/1775774/18047522/aa42c858-6ddd-11e6-86d8-57cb294747b0.png)

**Comment by akurzawa** [comment]
whats the minial ad permission for proxyuser?

**Comment by nuxsmin** [comment]
As simple user, no special permissions are needed. That user is only used to get the user's and groups' DN, and then the LDAP auth is done by the login user itself.

**Comment by nuxsmin** [comment]
There were some bugfixes for the LDAP auth over ADS. Please, take a look if you have any issue.
