### ISSUE TITLE
Message Module unavailable (curl) Without this module the application could not run correctly on installer

### ISSUE THREAD

**Issue by dsv591** [nuxsmin/sysPass#260]
Hey

I got the installer running but now I get this error

Module unavailable (curl)
Without this module the application could not run correctly

Curl is enabled in php.ini and server was reinstalled but installer still don't see it.

Any ideas?

**Comment by marnylopez** [comment]
Please do as following

1. Close WAMP (if running)
2. Navigate to WAMP\bin\php\(your version of php)\
3. Edit php.ini
4. Search for curl, uncomment extension=php_curl.dll
5. Navigate to WAMP\bin\Apache\(your version of apache)\bin\
6. Edit php.ini
7. Search for curl, uncomment extension=php_curl.dll
8. Save both
9. Restart WAMP

**Comment by dsv591** [comment]
it's enabled already, still doesn't work

**Comment by marnylopez** [comment]
If you still getting the message you can try with this:

1. Follow this link http://www.anindya.com/php-5-4-3-and-php-5-3-13-x64-64-bit-for-windows/
2. Go to "Fixed curl extensions" and download the extension that matches your PHP version.
3. Extract and copy "php_curl.dll" to the extension directory of your wamp installation. (i.e. C:\wamp\bin\php\<PHP VERSION>\ext)
4. Restart Apache

**Comment by dsv591** [comment]
That was it, thanks

**Comment by nuxsmin** [comment]
Great support!!

BTW curl is only needed (in this release) to search for updates.
