### ISSUE TITLE
Issue with someone else's old install

### ISSUE THREAD

**Issue by omahonyb** [nuxsmin/sysPass#261]
Hi there. Hoping you can help me. Basically I just started in a new job. They *had* this up and running previously. However when they upgraded ubuntu the accounts no longer worked. [And now most of the users have left]

I have admin & master password, as well as a number of user accounts & passwords, but nothing works.

Running v1.2.0.08 on Jessie [8.5]

**Comment by nuxsmin** [comment]
Hi!,

so it means that it was working on ubuntu and now you're trying to get it working it Debian, right?

That release is quite old (about a year ago), so I'd recommend to update it to the latest release, which solves many bugfixes (some related to master password)

**Comment by omahonyb** [comment]
Apologies, it is all ubuntu.
Ill give it a lash updating the software, and get back to you. Thanks for the response.

**Comment by omahonyb** [comment]
Hey mate, upgraded to latest [1.2.0.12], yet still the same issue. None of the three accounts [admin, and two users] can log in.
Is there a way to:
a) Reset the passwords? [Master should still work?]
b) Export the data, and move it to another server? [Planning to decommission this one in the next few months anyways]
c) Export all the data except the passwords themselves, and import them elsewhere?

**Comment by nuxsmin** [comment]
Hey,

Can you perform a password reset from the login page? It'll send an email with recovery instructions.

If that's not possible, the only way is by programming some code to generate a password for a given user, because that password is hashed using bcrypt and user's data. After that you would need to provide the master password to sign in.

**Comment by omahonyb** [comment]
Erm, I must be blind, but I dont see any password reset option on the login page? [Or even on your Demo site]

**Comment by nuxsmin** [comment]
Ok, it would be enabled if mail notifications were set. Can you edit the config.php file (in config directory) and set the email params?

**Comment by omahonyb** [comment]
Enabled everything, got the email, changed it and it doesn't work with 
There was an error
Internal Server Errorerror

TBH this looks screwed :P 
Is it possible to dump everything except the passwords and start fdrom scratch? [There is about 400 entries I dont want to retype!]. IE export mysql db, and import it?

**Comment by nuxsmin** [comment]
Sure, the db can be exported anytime.

The best way is by exporting the db, create a new sysPass instance with the same master password, import the db without "usrData", "usrProfile", "usrGroup" and "config"  tables.

**Comment by omahonyb** [comment]
Nice one homes. Ill give that a lash in the morning. Thanks for all the help!
