### ISSUE TITLE
Users unable to see passwords from assigned groups

### ISSUE THREAD

**Issue by jcboysha** [nuxsmin/sysPass#263]
I have some users who are assigned groups from both the user page, and are assigned to groups from within the groups pages. The users can only see passwords from the group assigned on their user page. How does one set it up so users can see both sets of passwords.

**Comment by nuxsmin** [comment]
Hello, I think that it may be resolved in the latest commit. Please, try it out.

**Comment by jcboysha** [comment]
That did indeed resolve the issue! Thanks a bunch!

**Comment by nuxsmin** [comment]
Great!. Thanks for the feedback
