### ISSUE TITLE
Active Directory Auth not working

### ISSUE THREAD

**Issue by eth0h4ckr** [nuxsmin/sysPass#264]
The ldap test works fine but when trying to log into syspass with AD creds I get the error below. Thanks for the help.

My config.php

'ldap_ads' => true,
'ldap_base' => 'OU=something,DC=example,DC=net',
'ldap_bindpass' => 'somepassword',
'ldap_binduser' => 'ldapuser',
'ldap_defaultgroup' => 2,
'ldap_defaultprofile' => 2,
'ldap_enabled' => true,
'ldap_group' => 'admins',
'ldap_server' => 'ldaps://usingIPhere',

Error Im seeing
"Error while searching user DN"

**Comment by nuxsmin** [comment]
Can you take a look to the sysPass event log? It should log the LDAP error and the filtering string.

**Comment by eth0h4ckr** [comment]
Thanks for the quick reply!!!

Error while searching user DN
User: firstname.lastname
LDAP FILTER:
(&(|(samaccountname=firstname.lastname)(cn=firstname.lastname)(uid=firstname.lastname))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityOb
ject))(objectCategory=person))

**Comment by nuxsmin** [comment]
Does the user exist within the search base?

**Comment by eth0h4ckr** [comment]
Yes. I can get the login to work it seems if I enter the DN for the user Im testing as the search base. Example:  

User DN: CN=User Name,OU=Network_Engineering,OU=Technical_Services,OU=Users,OU=
 REP,DC=example,DC=net

Search Base: OU=Network_Engineering,OU=Technical_Services,OU=Users,OU=
 REP,DC=example,DC=net


But if I try using: DC=example,DC=net

I get this error:
searchBase	ADMIN	10.1.1.33	Error while searching objects in base DN
LDAP ERROR: Operations error (1)
LDAP FILTER: (&(|(memberOf=*)(groupMembership=*))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))

It seems the recursive lookup is not working properly?

**Comment by eth0h4ckr** [comment]
Ideally i would like to use DC=example,DC=net as the search base as our AD environment is quite overly complicated and users are organized in many diff containers and ou's.

**Comment by nuxsmin** [comment]
Right, it should work, even nested group membership too. Really, the searching is done by ADS, so sysPass does not perform any action on the searches.

Can you perform some test with the ldp utility or whatever LDAP utility by using the filtering string?

**Comment by nuxsmin** [comment]
Hello, can you try out the latest commit?, There are some LDAP related fixes.

**Comment by eth0h4ckr** [comment]
I will give the latest commit a try and report back. Thank you.

**Comment by eth0h4ckr** [comment]
Still seeing the same issue after updating to latest commit :(

**Comment by eth0h4ckr** [comment]
Again. If I point the base search to where my test accounts DN lives I can get it to work. Otherwise, I can not auth. Let me know if I can provide more information. This seems like it would work with simple setups where all users live on one OU. This is not the case in my environment. 

OU=Network_Engineering,OU=Technical_Services,OU=Users,OU=
REP,DC=example,DC=net

**Comment by nuxsmin** [comment]
What about the ldp test? Can you perform it?, It could be useful try out with an external tool.

**Comment by nuxsmin** [comment]
Currently, this setup is running over a windows 2012 ADS environment without any issue and the search base is set some levels up to the users OUs.

I've also tested it over openLdap and edirectory services.

**Comment by eth0h4ckr** [comment]
Im using ldapsearch on ubuntu. Not 100% sure how to apply the string above to my search. Im trying it now.

**Comment by eth0h4ckr** [comment]
Example of a search that works without issue.

ldapsearch -LLL -H ldaps://domaincontroller.example.net -M -b "DC=example,DC=net" -D "_ldap_lookup@example.net" -w "password" "sAMAccountName=firstname.lastname"

**Comment by eth0h4ckr** [comment]
Ok. I have tried all the filters 

&(|(samaccountname=chris.johnson)(cn=chris.johnson)(uid=chris.johnson))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityOb
ject))(objectCategory=person))

Still no worky.

**Comment by nuxsmin** [comment]
Ok...

ldapsearch -x -W -D "bind_dn" -h servername -b "search_base" "filter string within ()"

**Comment by eth0h4ckr** [comment]
Here is the output.


root@vault:/opt/apps/syspass# ldapsearch -x -D "CN=_ldap_lookup,OU=ServiceAccounts,OU=Central_IT,DC=example,DC=net" -w "somepassword" -h dtwb1itph038.example.net -b "DC=example,DC=net" "(&(|(samaccountname=firstname.lastname)(cn=firstname.lastname)(uid=firstname.lastname))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))"
# extended LDIF
#
# LDAPv3
# base <DC=example,DC=net> with scope subtree
# filter: (&(|(samaccountname=firstname.lastname)(cn=firstname.lastname)(uid=firstname.lastname))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))
# requesting: ALL
 LHdSiS3bA4xOAAOn8ap7ZrfudbS8iEkcyyxSDKujblceoI4I960dNp+8jg50za8b+MGuPhv4ghLMf
 N06dTz6oa+a04QfN2r2Lxbeb/AAjqnzdbWUY9tprx1R8o+lfpvAi/2ap/iX5HFjPiR7N8CP2/viH+
 zD8F9U8G+CL+w0KHVtXk1e51IWUdxfBmghh8tDMHiRNsQORGXy3DLjB8l+IXxM1v4k6/Nq3iDWtV8
 Qatcf6y91G8kurhwOi+ZIWbaOy5wOwrB1dmQg/Tv71WMm5fcLnivn88pxWY1ZJa3/RGKk2rGhD4hu
 tMmtb6zuJLS8tGSSCeM/PC6Hcjj3B5/wCA19/ftX+CNL/bm/Z2sP2hvhhp0LX10TZ+PvDthHum0a/
 VN8ziFeSjH5gwBLRPE+M7wn52XEhMe3O3jr6V3X7Ln7W/jT9jn4nnxL4N1FbaS4jWDUbC4Bey1mAE
 sIp0GM4JJV1IdCTtIBYH5nMsFKsozpfHHbs090/08z0suxiot06nwy37rs0Zut+K9QbVbb7YJLeez
 k+yzxv8gb59+SpwAGJB6Y7isP8At2G6mu47qSb7O07O6R/Kw8zk9/boABwOPT7W8Y/F/wCBH7bKLq
 qx6b4J8a3Ue290rVpUtjLIfmPk3WFinG7JGCkh7xrXjPjP9lLwb4C1H7ZrF9MtrISxE97HHDIPZuO
 BweK8unUSdqsXFnsTw91elJSR84aPoeq/ELV2hsrdtyjOAfuqOOT7YAz7juRXrfiO1sv2bPhHeSrP
 /wATbVoWtrZD98u2cn1IQMWJ6ZwOCwpfG/7SXgn4U2DWnhWztNX1FI/KR4VxAgzn55erjPOEzkjqO
 tfPHjjx5qnxG8QPqWsXTXNww2qPupEvZEvoqj269Tkkk+pTpue6sjiqVIUU1F3kZsE20bc1seGfHu
 qeEJi2m6hc2XOSkcnyMfdD8rfiKw84IIxTWO4mu5q61PK80e0eGv2kbzXbJtM1K1hmkvENuLiE+WQ
 WGASvIPXnGPpV1ZMKK8b8JOR4p07/AK+o7/8AfQr14ygHp+lfoHBkUsPUt/N+hz1pNvUgvrRrxuG2
 rtxg/wA6gGkybPvx/Xn/AAoor2cTw/g69R1aid3vqZ8zGPocxX/WR/r/AIVXm8MzTKVMkDAjBDZOf
 0oorD/VfAdn97DnZRvPAlzcJtW4hC91bLL/ACrGn+EF47Flk01eewYf+y0UUf6rYDs/vY/aSI/+FO
 ajji60/wD76f8A+Jo/4U7qQ/5etP8A++n5/wDHaKKX+quX9n97H7aQv/CndRK/8fVh/wB9P/8AE0h
 +D2ok/wDH1p//AH0//wATRRR/qrl/Z/ew9tIt6H8Lb7S9ZtLh7izZLeZJGCs24gEHj5a7omiivTwO
 W0MHFwoXs3fV3M5Sb3P/2Q==
msExchUserAccountControl: 0
msExchMailboxGuid:: Vrbn1iVM2EeKBKLcq5gUbA==
msExchPoliciesIncluded: b33561ea-bb20-4611-b4a7-f997edb63fcc
msExchPoliciesIncluded: {26491cfc-9e50-4857-861b-0cb8df22b5d7}
msExchUMDtmfMap: emailAddress:247475646766
msExchUMDtmfMap: lastNameFirstName:564676624747
msExchUMDtmfMap: firstNameLastName:247475646766
msExchRecipientDisplayType: -2147483642
msExchSafeSendersHash:: x+IKDw==
msExchVersion: 44220983382016
msExchRecipientTypeDetails: 2147483648
msExchBlockedSendersHash:: qfW9A0NUbTMmiO01
msExchTextMessagingState: 302120705
msExchTextMessagingState: 16842751
msExchWhenMailboxCreated: 20150402090524.0Z
msExchRemoteRecipientType: 4

# search reference
ref: ldap://ForestDnsZones.example.net/DC=ForestDnsZones,DC=example,DC=net

# search reference
ref: ldap://DomainDnsZones.example.net/DC=DomainDnsZones,DC=example,DC=net

# search reference
ref: ldap://example.net/CN=Configuration,DC=example,DC=net

# search result
search: 2
result: 0 Success

# numResponses: 5
# numEntries: 1
# numReferences: 3

**Comment by nuxsmin** [comment]
Can you add the attribute "cn" to the end of the command?

It would look like: ldapsearch .... "cn"

So it will only return that attribute... sorry, I should mention it above

**Comment by eth0h4ckr** [comment]
```
root@vault:/opt/apps/syspass# ldapsearch -x -D "CN=_ldap_lookup,OU=ServiceAccounts,OU=Central_IT,DC=example,DC=net" -w "somepass" -h someserver.example.net -b "DC=example,DC=net" "(&(|(samaccountname=firstname.lastname)(cn=firstname.lastname)(uid=firstname.lastname))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))" "cn"
# extended LDIF
#
# LDAPv3
# base <DC=example,DC=net> with scope subtree
# filter: (&(|(samaccountname=firstname.lastname)(cn=firstname.lastname)(uid=firstname.lastname))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))
# requesting: cn 
#

# Firstname Lastname, Network_Engineering, Technical_Services, Users, CVG, example
 .net
dn: CN=Firstname Lastname,OU=Network_Engineering,OU=Technical_Services,OU=Users,OU=
 derp,DC=example,DC=net
cn: Firstname Lastname

# search reference
ref: ldap://ForestDnsZones.example.net/DC=ForestDnsZones,DC=example,DC=net

# search reference
ref: ldap://DomainDnsZones.example.net/DC=DomainDnsZones,DC=example,DC=net

# search reference
ref: ldap://example.net/CN=Configuration,DC=example,DC=net

# search result
search: 2
result: 0 Success

# numResponses: 5
# numEntries: 1
# numReferences: 3
``

**Comment by eth0h4ckr** [comment]
Appreciate the help!

**Comment by nuxsmin** [comment]
Fine, searches are working...

Did you set the bind user like "cn=user,dc=example,dc=net"?. I can't see it in some comments above?

Regarding a comment, you posted an error that shows a LDAP filter like "memberof=blank", is that right?

**Comment by eth0h4ckr** [comment]
Current bind
CN=_ldap_lookup,OU=ServiceAccounts,OU=Central_IT,DC=example,DC=net

**Test Error**
Error while searching objects in base DN
LDAP ERROR: Operations error (1)
LDAP FILTER: (&(|(memberOf=*)(groupMembership=*))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))

**Error**
Error while searching user DN
User: test.user
LDAP ERROR: Operations error (1)
LDAP FILTER:
(&(|(samaccountname=test.user)(cn=test.user)(uid=test.user))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCa
tegory=person))

**AD config block**

   'ldap_ads' => true,
  'ldap_base' => 'DC=example,DC=net',
  'ldap_bindpass' => 'somepass',
  'ldap_binduser' => 'CN=_ldap_lookup,OU=ServiceAccounts,OU=Central_IT,DC=example,DC=net',
  'ldap_defaultgroup' => 2,
  'ldap_defaultprofile' => 2,
  'ldap_enabled' => true,
  'ldap_group' => false,
  'ldap_server' => 'ldaps://someip',
  'ldap_userattr' => '',

**Comment by eth0h4ckr** [comment]
![selection_220](https://cloud.githubusercontent.com/assets/14805472/18061621/63f91136-6df1-11e6-9775-39d7d9eb9c66.png)

**Comment by nuxsmin** [comment]
Ummm...you're using ldaps so would need to import the ADS CA certificate in order to trust in it.

This website can help you:

https://www.novell.com/coolsolutions/tip/5838.html

**Comment by eth0h4ckr** [comment]
I have already completed this. I mentioned this works when Im using the test users DN as the base so I dont think the cert is the issue.

**Comment by nuxsmin** [comment]
Sure, but that "operations error" sounds that the ADS server is not responding correctly.

**Comment by nuxsmin** [comment]
Is your ADS running on windows 2003?

An excerpt from PHP:

In order to perform the searches on Windows 2003 Server Active Directory you have to set the LDAP_OPT_REFERRALS option to 0:

ldap_set_option($ldap, LDAP_OPT_REFERRALS, 0);

Without this, you will get "Operations error" if you try to search the whole AD schema (using root of the domain as a $base_dn).

As opposed to Windows 2000 Server, where this option was optional and only increased the performance.

**Comment by eth0h4ckr** [comment]
This particular DC is 2012

**Comment by nuxsmin** [comment]
Ok, but what is the domain functional level?

BTW, I'm programming a piece of code to get some raw data from the ADS by PHP.

**Comment by nuxsmin** [comment]
Can you set the LDAP group to "*"?. This would make the test to work.

**Comment by eth0h4ckr** [comment]
> Ok, but what is the domain functional 
2008 r2

> Can you set the LDAP group to "*"?. This would make the test to work.
I will do that now.

**Comment by eth0h4ckr** [comment]
```
2016-08-30 11:45:49	searchGroupDN	ADMIN	someip	Error while searching group RDN
Group: (cn=*)
LDAP FILTER: (cn=*)
```

**Comment by eth0h4ckr** [comment]
I do appreciate the help with this. I would love to get this working :)

**Comment by nuxsmin** [comment]
Well, can you put this script in your sysPass root dir and point the broswer to it? (take care to replace some config vars at the beginning)

https://gist.github.com/nuxsmin/a6b2f2701ce8b78ceadd835adc26756a

**Comment by nuxsmin** [comment]
You can also take a look to http://stackoverflow.com/a/6222836 (LDAP_OPT_REFERRALS is commented out in the script), so it seems that can be useful for any ADS version...

**Comment by eth0h4ckr** [comment]
Thanks. I will give this a go.

**Comment by eth0h4ckr** [comment]
When I browse to the script I only get this

```
Array
(
)
```

**Comment by nuxsmin** [comment]
Can you comment out the "LDAP_OPT_REFERRALS" line?

**Comment by eth0h4ckr** [comment]
It would appear its commented out already?

```
$groupName = '';
$ldapConn = @ldap_connect($ldapServer);
@ldap_set_option($ldapConn, LDAP_OPT_NETWORK_TIMEOUT, 10); // Set timeout
@ldap_set_option($ldapConn, LDAP_OPT_PROTOCOL_VERSION, 3); // Set LDAP version
//@ldap_set_option($ldapConn, LDAP_OPT_REFERRALS, 0); // Uncomment if "operations error"
@ldap_bind($ldapConn, $bindUser, $bindPass);
preg_match('/^(cn=[\w\s-]+)(,.*)?$/i', $groupName, $groupFilter);
$searchGroup = ldap_get_entries($ldapConn, ldap_search($ldapConn, $searchBase, $groupFilter[1], array("dn", "cn")));
$userFilter = '(memberof:1.2.840.113556.1.4.1941:=' . $searchGroup[0]["dn"] . ')';
$searchUser = ldap_get_entries($ldapConn, ldap_search($ldapConn, $searchBase, $userFilter, array("sAMAccountName")));
echo '<pre>';
print_r($groupFilter);
print_r($searchGroup);
print_r($searchUser);
echo '</pre>';
```

**Comment by nuxsmin** [comment]
Sorry, I meant uncomment...

**Comment by nuxsmin** [comment]
Umm...please, fill in the "groupName", because the script won't take care if this is unset, so it will fail

**Comment by eth0h4ckr** [comment]
Ok.

**Comment by eth0h4ckr** [comment]
Here is an excerpt from the output of the script obfuscated of course. This appears to be working.

```
96] => Array
        (
            [samaccountname] => Array
                (
                    [count] => 1
                    [0] => firstname.lastname
                )

            [0] => samaccountname
            [count] => 1
            [dn] => CN=Firstname Lastname,OU=Application_Development,OU=Technical_Services,OU=Users,OU=EEE,DC=example,DC=net
```

**Comment by nuxsmin** [comment]
Great!!, can you try out the latest commit?

**Comment by eth0h4ckr** [comment]
Absolutely. I will report back. Thanks.

**Comment by eth0h4ckr** [comment]
Here is what I have. What is different is Im not getting a "Wrong User/Pass" error anymore.

**Config**
  'ldap_ads' => true,
  'ldap_base' => 'DC=example,DC=net',
  'ldap_bindpass' => 'somepass',
  'ldap_binduser' => 'CN=ldapuser,OU=ServiceAccounts,OU=Central_IT,DC=example,DC=net',
  'ldap_defaultgroup' => 2,
  'ldap_defaultprofile' => 2,
  'ldap_enabled' => true,
  'ldap_group' => 'example',  (((Also tried full DN  for group)))
  'ldap_server' => 'ldaps://someip',
  'ldap_userattr' => '',


**Error On login**
Error while searching group RDN
Group: (cn=Groupname)
LDAP FILTER: (cn=Groupname)

**Test Error**
696	2016-08-30 16:54:33	searchGroupDN	ADMIN	someip	Error while searching group RDN
Group: (cn=Group)
LDAP ERROR: Operations error (1)
LDAP FILTER: (cn=Group)

**Comment by eth0h4ckr** [comment]
Also. In ldap.php output and can see my tests user samaccountname as well. I have tries multiple users to be sure.

**Comment by nuxsmin** [comment]
Regarding ldap.php, there are 3 lines that should output some info:

Outputs group filter (string): print_r($groupFilter); 
Outputs the groups found (array): print_r($searchGroup);
Outputs the users found (array): print_r($searchUser);

Can you see those outputs?

**Comment by eth0h4ckr** [comment]
All of the output I see is in the below format besides the first couple lines of course.

```
96] => Array
        (
            [samaccountname] => Array
                (
                    [count] => 1
                    [0] => firstname.lastname
                )

            [0] => samaccountname
            [count] => 1
            [dn] => CN=Firstname Lastname,OU=Application_Development,OU=Technical_Services,OU=Users,OU=EEE,DC=example,DC=net
```

**Comment by nuxsmin** [comment]
Can you give a try to the latest "ldap.php"?. I have just updated it with some modifications and useful comments. The important point is "Group Entries", that should list the group you're filtering on.

**Comment by eth0h4ckr** [comment]
np. Will try now.

**Comment by eth0h4ckr** [comment]
**ldap.php**

```
<?php
// Customization - Start
$ldapServer = 'someip';
$bindUser = 'CN=ldapuser,OU=ServiceAccounts,OU=Central_IT,DC=example,DC=net';
$bindPass = 'somepass';
$searchBase = 'DC=example,DC=net';
$groupName = 'CN=example,OU=Security,OU=Groups,OU=Central_IT,DC=example,DC=net'; // Please use DN syntax
// Customization - End
$ldapConn = @ldap_connect($ldapServer);
@ldap_set_option($ldapConn, LDAP_OPT_NETWORK_TIMEOUT, 10); // Set timeout
@ldap_set_option($ldapConn, LDAP_OPT_PROTOCOL_VERSION, 3); // Set LDAP version
@ldap_set_option($ldapConn, LDAP_OPT_REFERRALS, 0); // Uncomment if ADS
@ldap_bind($ldapConn, $bindUser, $bindPass);
preg_match('/^(cn=[\w\s-]+)(,.*)?$/i', $groupName, $groupFilter);
$searchGroup = ldap_get_entries($ldapConn, ldap_search($ldapConn, $searchBase, $groupName, array("dn", "cn")));
$searchGroup = ldap_get_entries($ldapConn, ldap_search($ldapConn, $searchBase, $groupFilter[1], array("dn", "cn")));
$userFilter = '(memberof:1.2.840.113556.1.4.1941:=' . $searchGroup[0]["dn"] . ')';
$searchUser = ldap_get_entries($ldapConn, ldap_search($ldapConn, $searchBase, $userFilter, array("sAMAccountName")));
echo '<pre>';
print_r('Group Filter (regex): ' . $groupFilter);
echo PHP_EOL;
print_r('Group Entries: ' . $searchGroup);
echo PHP_EOL;
print_r('User Filter: ' . $userFilter);
echo PHP_EOL;
print_r('User Entries: ' . $searchUser);
echo '</pre>';
```

**Output**

```
Group Filter (regex): Array
Group Entries: Array
User Filter: (memberof:1.2.840.113556.1.4.1941:=CN=example,OU=Security,OU=Groups,OU=Central_IT,DC=example,DC=net)
User Entries: Array
```

**Comment by eth0h4ckr** [comment]
Ive also tried uncommenting line 16.

**Comment by nuxsmin** [comment]
Sorry, I had a mistake so arrays weren't shown. Already updated...

**Comment by nuxsmin** [comment]
One question, does your group include numbers?, Actually the allowed chars are: letters, "_", "-" and spaces.

**Comment by eth0h4ckr** [comment]
No numbers

**Comment by eth0h4ckr** [comment]
Output looks similar to the previous script. Anything specific I should be looking for? Also, it only works if I uncomment line 21.

**Comment by eth0h4ckr** [comment]
Here is the output without uncommenting line 21.

```
## Group Filter (regex): 
Array
(
    [0] => CN=example,OU=Security,OU=Groups,OU=Central_IT,DC=example,DC=net
    [1] => CN=example
    [2] => ,OU=Security,OU=Groups,OU=Central_IT,DC=example,DC=net
)
## Group Entries: 
Array
(
    [count] => 0
)
## User Filter: 
(memberof:1.2.840.113556.1.4.1941:=)## User Entries: 
Array
(
    [count] => 0
)
```

**Comment by nuxsmin** [comment]
Please, set the group name without DN syntax, that is "example"

**Comment by nuxsmin** [comment]
Ummm, it should be "cn=example"

**Comment by eth0h4ckr** [comment]
Ok that works.

**Comment by nuxsmin** [comment]
And group entries?

**Comment by eth0h4ckr** [comment]
I see the group entries as well.

**Comment by nuxsmin** [comment]
Is there more than one entry?

**Comment by eth0h4ckr** [comment]
yes. 16.

**Comment by eth0h4ckr** [comment]
```
## Group Filter (regex): 
Array
(
    [0] => CN=example
    [1] => CN=example
)
## Group Entries: 
Array
(
    [count] => 16
    [0] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,OU=Security,OU=Groups,OU=Central_IT,DC=example,DC=net
        )

    [1] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=mail,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [2] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=services,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [3] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=ethers,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [4] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=rpc,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [5] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=netgroup,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [6] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=bootparams,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [7] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=networks,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [8] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=netmasks,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [9] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=hosts,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [10] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=protocols,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [11] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=ypservers,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [12] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=group,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [13] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=shadow,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [14] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=passwd,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
        )

    [15] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => example
                )

            [0] => cn
            [count] => 1
            [dn] => CN=example,CN=netid,CN=ypServ30,CN=RpcServices,CN=System,DC=example,DC=net
```

**Comment by eth0h4ckr** [comment]
Want me to give the latest commit a try?

**Comment by nuxsmin** [comment]
Yes, but the app won't know which group to use, so it will pick the first one, because it searches for the group name, and not for the whole dn.

Can you create a new group to sign into sysPass?

If you want to allow to every user in those groups, it's not possible, because the application will have to iterate over each group and get if the user is in it (time consuming and server overhead). You can use group hierarchy to accomplish that instead, that is create a group for sysPass and then add all those groups to it.

**Comment by eth0h4ckr** [comment]
Everything appears to be working now!!!

**Comment by eth0h4ckr** [comment]
The test fails but im now able to log into syspass with the specified group.

**Comment by nuxsmin** [comment]
Great!!

**Comment by eth0h4ckr** [comment]
I greatly appreciate the patience and effort you put into fixing this.

**Comment by nuxsmin** [comment]
I'm very glad that it now works fine.

Many thanks for your feedback and testing skills ;)
