### ISSUE TITLE
Penetration testing?

### ISSUE THREAD

**Issue by marnylopez** [nuxsmin/sysPass#265]
I would like to know if you have done some penetration testing on to SysPass?

**Comment by nuxsmin** [comment]
Hi @marnylopez ,

a time ago, there were some support for this task, and some CVEs were reported. I've done some tests by myself (burpsuite, sqlmap, ...) but it would be nice that get some support about this.

I'm very concerned about this kind of threat and every piece of code is programmed with the security in mind (XSS, CSRF, SQL Injection,...) but it can be possible that in some point I've made a mistake....

Thanks in advance!

**Comment by marnylopez** [comment]
@nuxsmin , 

Have you documented those tests?

**Comment by nuxsmin** [comment]
Unfortunately not, there were some reports (attached) and a big excel that contains logged actions.

[pentesting.zip](https://github.com/nuxsmin/sysPass/files/448397/pentesting.zip)
