### ISSUE TITLE
Cannot import CSV

### ISSUE THREAD

**Issue by mikashharia** [nuxsmin/sysPass#266]
Hi,

I'm trying to import a CSV of accounts and everytime i import i get an error saying wrong number of fields.

my csv is as follows

Dev DB;Arch;Database;192.168.1.9;root;password;test

**Comment by nuxsmin** [comment]
Hi,

Is there any " within fields?

**Comment by mikashharia** [comment]
no

**Comment by nuxsmin** [comment]
Ok, I've done some tests and it worked fine. Please, take care that if some field contains any character that matches with the field separator, it will add another field. And don't end any line with the field separator.

**Comment by mikashharia** [comment]
i have made sure that the csv is correct and tried again and still no luck.

can you attached a sample csv file that you used and i can test again?

**Comment by MikeTheSwede** [comment]
I have also work hard with CSV input. 
- It seems that it cannot handle multiple CR for example. Just one "account" per row.
- The file cannot handle "empty rows" either
- And also be sure that the file is UTF-8 encoded.

Attached are a working example(rename to testimport.csv)
[testimport.txt](https://github.com/nuxsmin/sysPass/files/456142/testimport.txt)

**Comment by mikashharia** [comment]
thanks for the test file. i still receive the same error though. lost as to what is causing it.

**Comment by nuxsmin** [comment]
@mikashharia 

I've written a piece of code that performs like the CSV import. It reads a file named "accounts.csv" and tells if there is any line with a wrong number of fields. You can get it through this gist:
https://gist.github.com/nuxsmin/3c1b91ea1dcc59dec80d458c37500552

The "accounts.csv" file can be provided by your own or take the "testimport.txt" from the last comment.

@MikeTheSwede 

> It seems that it cannot handle multiple CR for example. Just one "account" per row.

You're right, the sysPass CSV import is quite simple. I would switch to XML format, because CSVs can be a pain, and you may think that I'll need to provide some kind of "remote" support, so I should use XML instead.

> The file cannot handle "empty rows" either

Empty rows are handled but it could show an error if the database record should be set.

> And also be sure that the file is UTF-8 encoded.

Sure

Thanks for your support!

**Comment by mikashharia** [comment]
result of the csvimport.php

```
array(7) {
  [0]=>
  string(6) "Dev DB"
  [1]=>
  string(4) "Arch"
  [2]=>
  string(8) "Database"
  [3]=>
  string(11) "10.107.1.23"
  [4]=>
  string(4) "root"
  [5]=>
  string(7) "Test123"
  [6]=>
  string(11) "root login
"
}
```

**Comment by nuxsmin** [comment]
And was that the csv file you used to test the import?

**Comment by mikashharia** [comment]
yes that is the same csv file.

**Comment by nuxsmin** [comment]
That is weird, because the code is like the used in sysPass import function (CsvImportBase.class.php:94)

**Comment by mikashharia** [comment]
this is the file i used. just change to csv

[accounts.txt](https://github.com/nuxsmin/sysPass/files/456828/accounts.txt)

**Comment by nuxsmin** [comment]
It works fine...

![seleccion_059](https://cloud.githubusercontent.com/assets/1775774/18276146/14459484-744a-11e6-8427-8302d47f51a9.png)
![seleccion_060](https://cloud.githubusercontent.com/assets/1775774/18276147/14469474-744a-11e6-9b35-4af6a8ab9955.png)

**Comment by nuxsmin** [comment]
Umm, I think what could be your problem...there is a new line at the end of the file.

**Comment by mikashharia** [comment]
hmmm, maybe its something with my setup.
i have red hat 6.8, mariadb, php5.5 apache2.2.15. ill try more test

**Comment by nuxsmin** [comment]
Take care about my previous comment...

**Comment by mikashharia** [comment]
![image](https://cloud.githubusercontent.com/assets/21689142/18277375/27664580-7446-11e6-824a-daa2ca24f552.png)

i checked and only one line, still no luck.

**Comment by nuxsmin** [comment]
Hi there, Did you get luck?

**Comment by MikeTheSwede** [comment]
Thanks  for asking!

I havent really had the time to upgrade to GIT. It seems a bit complicated. We are for now happy with adding user one by one.
There is anyways the somewhat awkvard behavior with master password when adding a new user, so we have to manage every user anyways.

Best Regards
Mikael Osth

**Comment by nuxsmin** [comment]
Ok, hope you haven't too much passwords...

Regarding master password:

> The master password is needed to decrypt the accounts' password, but every user encrypts it with its own password so they only need to provide it once or when its own password is changed.

Kind regards.

**Comment by dvdfabian** [comment]
Hello,

we tried to import passwords from a linux version of KeypassX that only supports CSV export. Some of the accounts had a larger note with multiple lines. We hit the same issue as @mikashharia. The solution was to switch from using `str_getcsv()` line-by-line to `fgetcsv()`. The following snippet handles correctly multiline comments and empty lines:

```
    protected function processAccounts()
    {
        $line = 0;

        if (!($f = fopen($this->file->getTmpFile(), "r"))) {
                throw new SPException(
                    SPException::SP_CRITICAL,
                    sprintf(__('Cannot open file %s', false), $this->file),
                    sprintf(__('Cannot open file %s', false), $this->file)
                );
        }

        while (($fields = fgetcsv($f, 0, $this->ImportParams->getCsvDelimiter())) !== false) {
            $line++;
            $numfields = count($fields);

            // Comprobar el número de campos de la línea
            if ($numfields !== $this->numFields) {
                fclose($f);
                throw new SPException(
                    SPException::SP_CRITICAL,
                    sprintf(__('El número de campos es incorrecto (%d)', false), $numfields),
                    sprintf(__('Compruebe el formato del archivo CSV en línea %s', false), $line)
                );
            }

            array_map(trim, $fields);

            if (empty($fields[0]) || empty($fields[1]) || empty($fields[2])) {
                continue;
            }
            // Asignar los valores del array a variables
            list($accountName, $customerName, $categoryName, $url, $login, $password, $notes) = $fields;
...
```
Best regards,

David Fabian
