### ISSUE TITLE
Account name as link

### ISSUE THREAD

**Issue by mikashharia** [nuxsmin/sysPass#267]
when i click on the account name link i get a console error:

Uncaught ReferenceError: doAction is not defined
onclick	@	index.php:1

**Comment by nuxsmin** [comment]
If you click on the other account actions, do they work?

**Comment by mikashharia** [comment]
all the icon actions work

**Comment by mikashharia** [comment]
That seems to have fixed it.

**Comment by nuxsmin** [comment]
Great!!. It seems that is browser behavior change on latest releases, because those action icons were using the "onclick" attribute to launch the associated action.

Thanks for the feedback ;)
