### ISSUE TITLE
Kee Pass

### ISSUE THREAD

**Issue by stvorenje** [nuxsmin/sysPass#268]
Is it possible to export passwords of a certain group or users as an Kee Pass database?

**Comment by nuxsmin** [comment]
Actually not but it would be an useful feature for the next release...

**Comment by ptman** [comment]
Apparently there are already libraries for writing keepass files: https://github.com/shkdee/KeePassPHP

**Comment by nuxsmin** [comment]
Thanks for the feedback!

**Comment by nuxsmin** [comment]
Currently, a contributor has developed an standalone utility to achieve this. Please take a look to it on: https://github.com/julenpardo/sysPass-XML-Decrypter
