### ISSUE TITLE
Mail Config

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#269]
Hola, hay alguna manera de configurar el mail para que envíe a otra cuenta que no sea la misma con la que envia ? Por lo que veo únicamente se puede configurar una cuenta y esa es el source y destination de los mails.

**Comment by nuxsmin** [comment]
De momento no está implementado el envío a destinatarios diferentes, pero es posible haciendo algunos cambios. Lo pongo como mejora para la próxima versión.

**Comment by nuxsmin** [comment]
Added to roadmap #422
