### ISSUE TITLE
Microsoft AD Integración

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#270]
Hola, una consulta, pude lograr la integración con MS AD, pero únicamente puedo lograr que autentiquen usuarios que pertenecen al grupo que definí en la configuración, y que además estén bajo esa misma rama, en mi caso, una OU. Si el usuario está en otra OU, pero en el grupo correcto, no puedo hacer que valide porque no lo encuentra, y en mi caso tengo usuarios distribuidos en varias OU. No hay forma de configurarlo de esa manera ? Saludos!

**Comment by nuxsmin** [comment]
Hola, la búsqueda de usuarios y grupos se hace en la base de búsqueda, por lo que es necesario establecer una base que incluya los usuarios y grupos deseados. Está hecho así?

**Comment by gabrielsoltz** [comment]
El problema es

**Comment by gabrielsoltz** [comment]
El problema es que hay usuarios en diferentes OU que pueden acceder. 
Y si configuro una Base de Búsqueda que este en el nivel superior (todo el DC), para que incluya todas, no funciona. Al parecer, por qué no encuentra el "Grupo". 
Entonces, la única forma que tengo de hacerlo funcionar, es apuntarlo a como base de busqueda a una OU en particular, donde ahí tiene que estar el Grupo y los usuarios. 
Por alguna razón no se puede especificar un nivel superior de base de búsqueda ?

**Comment by nuxsmin** [comment]
Buenas, has probado con la última versión? Corrige varios errores en la autenticación de AD cuando la base es igual a la raíz del directorio.

**Comment by gabrielsoltz** [comment]
Si, estoy en la última versión. Pero el problema es tal cual lo decribo.

**Comment by nuxsmin** [comment]
Buenas, qué formato tiene el nombre del grupo?. Puedes adjuntarme el error que aparece en el registro de eventos?

**Comment by gabrielsoltz** [comment]
No sé por qué, pero ahora me tomó el base search como la raiz del AD y eso me soluciona el problema. Muchas gracias por el tiempo.

**Comment by nuxsmin** [comment]
Perfecto..me alegro que funcione
