### ISSUE TITLE
Install page in loop

### ISSUE THREAD

**Issue by pedrolastiko** [nuxsmin/sysPass#272]
Hi,
i'm trying to install the last version of syspass (v1.2.0.13). But after install i'm only redirected to the same installation page... the database is created, but I can't be redirected to the logon page.

any ideas ?
regards
Pedro

**Comment by nuxsmin** [comment]
Hi,

Can you see anything in the webserver log?

**Comment by pedrolastiko** [comment]
Hi !
in acces.log, i've only the syspass's ressources were acceded (http://pastebin.com/rP5Ds88w)
in error.log i've this type of error (http://pastebin.com/Nm0hujRx)
for more informations : 
1/ just after I click on the install bouton i've got a 500 error in my browser 
2 / syspass is not in "/var/www/html/syspass" but in "/var/www/syspass" but I think this is not very important..

Many thx for your help !

**Comment by nuxsmin** [comment]
Hi!

that error is mostly triggered because the database permissions aren't right. Can you tell me some info about your environment? (OS, versions, hosted or not).

**Comment by pedrolastiko** [comment]
OS : Linux lamp 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux (LAMP turnkey Linux)

**Comment by pedrolastiko** [comment]
exactly the same probleme with a fresh install on Debian 8.1.5 and last syspass version v1.2.0.13

**Comment by nuxsmin** [comment]
Are the web server and database on the same host?, Are you using a database user that have admin privileges?

**Comment by Goatmaster** [comment]
I have the same problem with Debian (nginx, mariadb). The web server and database are on the same host an I used a database user that has admin privileges.

**Comment by nuxsmin** [comment]
I'll try to find out what can be happening.

**Comment by nuxsmin** [comment]
Solved in the latest commit. Please tell me if it works fine.

**Comment by Goatmaster** [comment]
Worked for me, thank you!
