### ISSUE TITLE
Demo doesn't work.

### ISSUE THREAD

**Issue by Jonchun** [nuxsmin/sysPass#274]
How are you supposed to login to the demo? There's no sample username/password and entering anything just gives you an error.

**Comment by nuxsmin** [comment]
Please, take a look to the tooltip text on both text fields. I

**Comment by Jonchun** [comment]
Got it thanks! This should definitely be documented in the ReadMe though. (Maybe it's just me, but I've never seen a demo keep the username/password in tooltips like that and I don't really see a point in hiding it/not making it immediately obvious)

**Comment by nuxsmin** [comment]
Sorry for the inconvenience, but the demo site is linked through an icon at the sysPass webpage, so there isn't any suitable place to put the login data.

You may think it could be at the login page but I wanted to show a cleaner interface, so I decided to use the tooltip to get it.

Actually, no one has complained about it, but I think you're right, there is no clues to get it. I'll change it shortly.

Thanks for the feedback!
