### ISSUE TITLE
Problem in checkServerAuthUser() prevents login

### ISSUE THREAD

**Issue by davidpsc** [nuxsmin/sysPass#275]
I've updated syspass today from 1.1.? to 1.2.0.13 and suddenly the AD login didn't work anymore. After a bit of debugging I found that the problem was in checkServerAuthUser function (auth.class.php).
I'm running an IIS 7 webserver with PHP 5.3 and have Windows authentication enabled (which currently doesn't work because we use a DNS name for the server and the Windows auth only works when using the FQDN or servername - nevermind). But the following line only checks if the values are available, but not if they're really set (not empty):
```
if ((isset($_SERVER['PHP_AUTH_USER']) || isset($_SERVER['REMOTE_USER'])) {
			return self::getServerAuthUser() == $login;
        }
```

And (I guess because Windows auth is enabled but not working/is not used) the values of $_SERVER['PHP_AUTH_USER'] and $_SERVER['REMOTE_USER'] are available but empty.

I've now changed the line to:
```
if ((isset($_SERVER['PHP_AUTH_USER']) || isset($_SERVER['REMOTE_USER'])) && ($_SERVER['PHP_AUTH_USER'] != "" || $_SERVER['REMOTE_USER'] != "")) {
			return self::getServerAuthUser() == $login;
        }
```
and it works correctly now. Please consider this change for the next update.

Thanks!
David

**Comment by nuxsmin** [comment]
Hello, 

By AD authentication, did you mean basic authentication?

You're right, I should use either your code or empty() instead.

I'll change it for the next release.

Thanks for the feedback!!

**Comment by davidpsc** [comment]
Hi,

thanks for the quick answer!

By AD authentication I mean Active Directory (LDAP) authentication. We use SysPass in our company and have it connected to our Active Directory server.

And also thanks for having it fixed in the next release!
