### ISSUE TITLE
LDAP not working since update

### ISSUE THREAD

**Issue by ArminXG** [nuxsmin/sysPass#277]
Since changes (I think version .13) LDAP is not working any more.
I had a look into the code and found the following line which doesn't make any sense:
File: inc/Ldap.class.php Line: 189.

`$filter = '(&(|(memberOf=' . $groupDN . ')(groupMembership=' . $groupDN . ')(memberof:1.2.840.113556.1.4.1941:=' . $groupDN . '))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))';`

I guess the memberof:1.2.840.113556.1.4.1941 is an cut and paste error?

Armin

**Comment by nuxsmin** [comment]
That code is right. It allows to lookup users group membership within ADS nested groups.

Did you get any error at login time?. Can you perform the LDAP check at the LDAP tab?

**Comment by ArminXG** [comment]
Well, I use just LDAP, not AD. It works without this. When I re-add it, I get in the log:

`Error while searching objects in base DN
LDAP ERROR: Bad search filter (-7)
LDAP FILTER:
(&(|(memberOf=*)(groupMembership=*)(memberof:1.2.840.113556.1.4.1941:=*))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityO
bject)))`

Maybe it is because I don't set a special "group" to search for. When I add a group name, the group is not found:
`Error while searching group RDN
Group: (cn=syspass)
LDAP FILTER: (cn=syspass)`

When I give the full dn
`cn=syspass,cn=groups,dc=company,dc=domain`
the same error appears: 
LDAP FILTER: (cn=syspass)

**Comment by nuxsmin** [comment]
Right, that code should not be executed unless you have set ADS.

Please, checkout the latest commit at master branch (there is no new release yet).

**Comment by ArminXG** [comment]
It seems this special search is for Microsoft AD only. We use a SAMBA4 based AD which gives the error as well when I change from LDAP to AD connection.

**Comment by nuxsmin** [comment]
Right, there is a related issue: https://bugzilla.samba.org/show_bug.cgi?id=10493

**Comment by ArminXG** [comment]
Ah, I see. Thank you!!!

**Comment by nuxsmin** [comment]
Solved on latest release.
