### ISSUE TITLE
Reset master passsword.

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#279]
Existe alguna forma de resetear el master password ? 
Tengo acceso de todo tipo a la plataforma, base de datos, ssh, usuarios admin en la gui, generación de clave master temporal, etc. 
Sin embargo, se me ocurrió cambiar la master password, y encuentro que al parecer no estaba bien documentada la misma, y no puedo hacerlo. 
Existe alguna forma de resetearla ?
Gracias!

**Comment by nuxsmin** [comment]
Hola, puedes obtener la clave actual activando el modo debug, ya que la clave maestra está encriptada con una clave derivada de la del usuario.

**Comment by oguevarah** [comment]
Tengo un problema pero con las claves de usuario, no me permite cambiar manualmente las claves de usuarios y tampoco puedo ver las que el sistema les genera, alguna idea?

**Comment by oguevarah** [comment]
Y entonces cómo se les brinda acceso a otros usuarios ?

**Comment by nuxsmin** [comment]
Creando un nuevo usuario y estableciendo una clave para el mismo.

**Comment by oguevarah** [comment]
Cree un nuevo usuario, no me permite escribir un password, solo generarlo automáticamente. La pregunta: cómo veo el password? Si no me deja escribirlo sino generarlo, con que credenciales entrego el usuario? No tendría acceso, no sé si me entiendes 

Enviado desde mi iPhone

**Comment by oguevarah** [comment]
Como se les dá de alta a los usuarios de syspass sin una contraseña? Cómo podrán hacer login sin contraseña? Tengo un syspass listo para salir a producción pero no puedo crear usuarios que no podrán acceder.

**Comment by nuxsmin** [comment]
@oguevarah hola, no es posible crear usuarios sin clave. sysPass es una herramienta de seguridad y por lo tanto este tipo de prácticas no están disponibles.

Saludos

**Comment by oguevarah** [comment]
No me estan entendiendo!!!!

1. En el proceso de creación de usuario el syspass no permite escribir un
password, solo generarlo automáticamente
2. La contraseña autogenerada por syspass no esta visible, no se puede
copiar

Por estos factores anteriormente expuestos, el usuario recien creado no
podra loggearse en syspass, puesto a que, el mismo administrador del
syspass que fue quien creo el usuario desconoce la contraseña del usuario
nuevo.

Vuelvo a preguntar:
1. Cómo se loggea el usuario si no sabe la contraseña?
2. De que forma se coloca la contraseña manualmente?

**Comment by nuxsmin** [comment]
Hola, es raro lo que comentas ya que no han habido incidencias con la creación de usuarios.

Para ver la clave al crear el usuario, es necesario, sin mover el cursor del cuadro de la clave, situar el ratón encima del icono del ojo.

Por favor prueba esta función en el entorno de demo.

**Comment by oguevarah** [comment]
Saludos

La única forma que encontré para que un usuario pudiera ingresar al syspass
es:
1. Crear el usuario con una contraseña generada por el sistema
2. Hacer click en el vínculo "¿Ovidó su clave? y rellenar los campos de
usuario y correo

Luego de recibir el correo y acceder al link para cambio de contraseña, es
allí que el usuario puede agregar la clave que desee y posteriormente
loggearse

Otro detalle importante es, que el administrador de syspass no puede
cambiar la contraseña de otro usuario, solo puede generarla aleatoriamente,
si lo se hace, no se puede ver la clave, al colocar el puntero del mouse en
el icono del ojo, se ve una cantidad de caracteres enorme. Es decir, habría
que repetir el procedimiento arriba descrito para que un usuario pueda
acceder.

Esto es inconveniente realmente, porque si el usuario no es técnico, esto
no será un procedimiento agradable y representará una detalle importante
para abandonar el uso de syspass

Estoy impulsando este software en la organización donde actualmente
trabajo, pero estos asuntos deben ser corregidos antes de implementarse

Adjunto algunas imagenes de esto

Saludos

Octavio

**Comment by oguevarah** [comment]
Saludos

El demo hace exactamente lo mismo que te estoy comentando

Si yo administrador de syspass creo un usuario, debería poder colocarle la
contraseña que yo desee, y configurarlo para que al hacer login por primera
vez, le obligue a cambiar la clave, y así el usuario tiene el control de su
propio usuario. Tratando de entender la filosofía de syspass, las cosas que
los usuarios pueden dentro de syspass, serán establecidas por el
administrador.

Si pudieras corregir este detallito sería genial, puesto a que syspass es
muy completo y estoy necesitanto implementarlo

Saludos

Octavio

**Comment by nuxsmin** [comment]
Buenas, voy a revisarlo y te comento, pero nadie ha abierto incidencia respecto a lo que comentas. El administrador de sysPass puede cambiar la clave de cualquier usuario y no tiene porque ser aleatoria.

Cuando se cambia la clave, justo antes de salir del campo de clave, sin pulsar ningún botón, sitúa el puntero del ratón sobre el icono del ojo y aparecerá la clave. Si el campo de clave pierde el foco, la clave es encriptada.

Saludos

**Comment by oguevarah** [comment]
OK, voy a hacerte un video y te lo mando, tal vez no estoy llegando a donde
me dices. Si yo como administrador de syspass quiero cambiar la contraseña
de un usuario, solo puedo generarla automaticamente, porque no me permite
escribir nada en el box de contraseñas y si te fijas en las capture de
pantalla que te envie, hice lo que indicas y ese es el resultado. Agradezco
me puedas ayudar

Saludos

Octavio

**Comment by nuxsmin** [comment]
Creo que las capturas no aparecen por haberlo enviado por correo.

**Comment by oguevarah** [comment]
A que cuenta de correo puedo enviartelas?

**Comment by nuxsmin** [comment]
He revisado la demo, y de hecho la he recreado de nuevo porque el sitio estaba desconfigurado, y no he tenido problemas para crear nuevos usuarios (utilizo firefox última versión).

Con respecto a v3 puedes instalarla usando la misma bd de v2 (haciendo copia de seguridad antes...). Ten en cuenta que los archivos de configuración están ahora en `app/config`

Saludos

**Comment by oguevarah** [comment]
Acabo de probar, como te decía, y en esta demo si me permite visualizar la
clave del usuario y copiarla, generada automaticamente sin excepción, así
esta bueno porque como administrador podría entregar el usuario con su
contraseña y forzar el cambio de esta en el inicio de sesión del usuario.
Instalaré la versión 3 recién salida del beta y te cuento que tal. Para la
versión 2.1.16 hice unas correcciones al momento de instalar y cree un
playabook en ansible para automatizar la instalación, si lo consideras
pertinente, lo comparto. Podría funcionar con la nueva instalación.

saludos

Octavio

**Comment by nuxsmin** [comment]
Me alegro de que funcione.

Si puedes compartir el playbook para añadirlo a la documentación. Gracias!
