### ISSUE TITLE
Deeplink

### ISSUE THREAD

**Issue by ebcont** [nuxsmin/sysPass#28]
Hello.

We need the possibility to deeplink to every account detail and copy the password directly from there.

I am using the newest version 1.1beta.

Why?
We are documentating all our customer-information in a wiki - but we do not want to store customer-passwords there. So we wanna use syspass for this.
In our wiki we want to store a deeplink to the password in syspass - so clicking on the deeplink should open the detail-account-site and there it should be possible to copy the password.

I think this would be very helpfull for everybody who uses wikis and do not want to store passwords unencrypted in the wiki.
Our is this already possible with syspass?

Thank you.

**Comment by stefanjauker** [comment]
Yes, this would be a helpful feature. We would like to send deep links by mail or use the link for documentation.

**Comment by nuxsmin** [comment]
Hello, this feature will be implemented in next version.

**Comment by stefanjauker** [comment]
Awesome thanks for the quick feedback. Let me know if If you need a beta tester for this feature.
