### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysPass#281]
hi, 
i am wondering if it is possible to export  the data with  passwords in plaintext ? 
i am managing clients data  with your system and would like to export  entire clients stuff for
printed documentation ... 
maybe i could access stuff with api , parse it to an  .rst file  with a nice layout via latex : ) 
will this be possible ? would be really great

**Comment by nuxsmin** [comment]
Hi,

actually is not possible to perform a plain text export. It will be a new feature for the next version. The export format would be XML.

**Comment by nuxsmin** [comment]
Related #255

**Comment by osnet** [comment]
hehe nice, but even with google the translation  is  not useful ^^

**Comment by nuxsmin** [comment]
Upsss...that is not related. Sorry ;)

**Comment by nuxsmin** [comment]
It will be done in XML format and an standalone tool would be used to decrypt the file. It would keep the secure chain of the data.
