### ISSUE TITLE
i can't install

### ISSUE THREAD

**Issue by naked13** [nuxsmin/sysPass#282]
i can't install 

syspass database server 
i input : 172.25.1.90 but system alert please match the requested format.

please help me # #

**Comment by nuxsmin** [comment]
The server should match the regex "[0-9a-zA-Z_-\.]+", so it can be any number or hostname within some chars like "_", "-" or ".".
Are you installing the latest version?

**Comment by naked13** [comment]
thanks sir.
now i can install success.

**Comment by nuxsmin** [comment]
Great!!

**Comment by TheMengzor** [comment]
Trying to install 1.2.0.17 but stuck on the same problem.
In console got error:
```
Pattern attribute value [0-9a-zA-Z_-\.]+ is not a valid regular expression:
Uncaught SyntaxError: Invalid regular expression: /[0-9a-zA-Z_-\.]+/: 
Range out of order in character class
```
