### ISSUE TITLE
Setting Apache

### ISSUE THREAD

**Issue by Palazur** [nuxsmin/sysPass#283]
Good day, my friends. Who can put a screenshot of the Settings, Apache in syspass.conf file in the location and /etc/httpd/conf.d/ /etc/httpd/conf/httpd.conf. Thank you in advance!

**Comment by nuxsmin** [comment]
This is a quite simple example, but works fine.

https://github.com/nuxsmin/Docker/blob/master/syspass/000-default.conf

A more secured example would be nice, but I'll need to write and test another config.

**Comment by Palazur** [comment]
Many thanks. There is another problem. When you try to access the site opens is such a page instead of the site
![default](https://cloud.githubusercontent.com/assets/22366206/18834388/408a2e06-83fe-11e6-9830-ab96fcf290df.JPG)
what to do?

**Comment by nuxsmin** [comment]
That is most likely because you need to install PHP.

Please take a look to wiki.syspass.org and you will find some installing instructions.

**Comment by Palazur** [comment]
yes, you are completely right , the manual has not been "yum install php '. Once I found it worked !!!! But there was a problem ... When you register a user , you need to specify the " Server 
![default](https://cloud.githubusercontent.com/assets/22366206/18836494/f53e714a-8408-11e6-9dfc-9e1ea72f85b0.JPG)
DB "  . What would there not introduced , error " Enter the data in the specified format ," please tell me what exactly you need to enter?

**Comment by nuxsmin** [comment]
Great!

That field should accept numbers, characters, dot, underscore and minus sign.

Can you try out with number notation?

**Comment by Palazur** [comment]
He does not want to (
![default](https://cloud.githubusercontent.com/assets/22366206/18837188/888fd356-840b-11e6-9f8e-73968cf37316.JPG)

**Comment by nuxsmin** [comment]
That is weird, because it's a standard HTML5 tag property

**Comment by Palazur** [comment]
Shit , but I tried to register through Microsoft Edge and it worked , thanks again !

**Comment by cbtrident** [comment]
i've seen the same problem on chrome it not take database server name but work fine in internet explore

**Comment by nuxsmin** [comment]
Great!! I'll do some more tests on latest chrome versions..

**Comment by nuxsmin** [comment]
Solved in latest commit
