### ISSUE TITLE
Not all translation available

### ISSUE THREAD

**Issue by clauded** [nuxsmin/sysPass#284]
I'm using version 1.2.0.15 and I can only use the application in spanish (the default) or english : as soon as I choose another language, spanish is displayed. I've checked and the inc/locales/fr_FR directory is present (I'm trying to use french).

**Comment by clauded** [comment]
I found  the solution: install php-gettext and generate the locale for fr_FR (my server is Ubuntu):

`apt-get install php-gettext`
`locale-gen fr_FR.UTF8`
`apachectl restart`

I think this should be added to the wiki.

**Comment by nuxsmin** [comment]
Great! You're right, this could be told at the wiki. I'll put it shortly.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Done
