### ISSUE TITLE
FreeIPA LDAP

### ISSUE THREAD

**Issue by ptman** [nuxsmin/sysPass#285]
I've been trying to get the LDAP support to work with [FreeIPA](http://www.freeipa.org/page/Main_Page) without success.

FreeIPA uses [389ds](http://www.port389.org/) as the LDAP server, and provides `memberOf` -attribute on user objects by default. Also, membership is by `member` -attribute, not `memberUid`. The default hierarchy is to put users under `cn=users,cn=accounts,dc=example,dc=com and groups` under `cn=groups,cn=accounts,dc=example,dc=com`. System accounts, such as the one that should be used by sysPass to bind, are placed under `cn=sysaccounts,cn=etc,dc=example,dc=com` as per [HOWTO](https://www.freeipa.org/page/HowTo/LDAP).

I keep getting:

```
LDAP ERROR: Can't contact LDAP server (-1)
```

even though I've managed to get the green popup:

```
LDAP connection OK
Objects found: 0
```

when checking on the LDAP settings page.

Please advise

**Comment by nuxsmin** [comment]
Hi,

can you try out with this gist https://gist.github.com/nuxsmin/a6b2f2701ce8b78ceadd835adc26756a ?

I should output some results form a LDAP search

**Comment by ptman** [comment]
I did, please see the fork and comment

**Comment by ptman** [comment]
Did you get the output you needed using the script in the gist?

**Comment by nuxsmin** [comment]
Right, I put a comment on it, did you see it?

It works as expected.

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta
