### ISSUE TITLE
Saltos de línea en las notas

### ISSUE THREAD

**Issue by andresju** [nuxsmin/sysPass#286]
Buenas tardes,

acabo de realizar una migración en nuestra empresa a este sistema y estoy encantado. Quería hacerte un comentario sobre un pequeño fallo que hemos detectado:

Al hacer la importación desde nuestro anterior sistema (TeamPass), todas las notas que llevaban un salto de línea ahora mantienen los "<br/>". hasta aquí todo bien. El problema que he detectado es que cuando ves el comentario desde el listado (Haciendo hover con el ratón), los saltos de línea aparecen como <br/> en claro y cuando entras a ver la cuenta en detalle, los saltos de línea sí que aparecen. Hasta aquí todo bien.

En cambio, si los saltos de línea los introduces cuando editas/creas una nueva nota, éstos solo se ven desde el listado general, mientras que si entras en el detalle de nota, los saltos de línea desaparecen, y si introduces un <br/> "a mano" a la hora de guardar han desaparecido.

Espero haberme explicado bien, si tienes cualquier duda sobre este comportamiento, pregúntame que estaré encantado de echar una mano.

Un saludo

**Comment by nuxsmin** [comment]
Hola, me alegro que te sea útil la aplicación.

Con respecto a las notas, entiendo que es al visualizar una cuenta y no al editar. Esto ocurre porque el parseo del html no tiene en cuenta los caracteres de salto de línea, por lo que es necesario convertirlos a etiquetas html. Es sencillo por lo que en el próximo lanzamiento lo dejo corregido.

Gracias por el feedback!

Saludos
