### ISSUE TITLE
Some special characters get converted when copying to clipboard

### ISSUE THREAD

**Issue by wyverneximus** [nuxsmin/sysPass#287]
Passwords that contain a **>** have that character converted to **"&"gt;** when copying it to the clipboard with the copy to clipboard button, but when viewing the password it is correctly displayed. I am guessing this will happen for **<** as well,  I am using Firefox 49 but I have not checked this with other browsers though.

So for instance **1VWRE%^!@g>rGt** becomes **1VWRE%^!@g"&"gt;rGt**.
I have added quotes because of display issues.

**Comment by nuxsmin** [comment]
Hi,

Does it happen when you copied it to clipboard or viewing instead?

**Comment by wyverneximus** [comment]
It only happens when I copy it to the clipboard through the button.

**Comment by nuxsmin** [comment]
Are you running on the latest release?

**Comment by wyverneximus** [comment]
Yes from a couple of days ago (1.2.0.17).

**Comment by wyverneximus** [comment]
I have tested it with chromium (52.0.2743.116) and it also happens here. When using the debugger i can see that ajax_viewpass.php returs the password with &"gt; in it.

**Comment by nuxsmin** [comment]
I've done some changes, so can you try out the latest commit?

**Comment by wyverneximus** [comment]
This seems to fix the issue.

**Comment by nuxsmin** [comment]
Great!

**Comment by nuxsmin** [comment]
Solved
