### ISSUE TITLE
syspass behind  apache proxypass

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysPass#289]
Hi, 
we are running the old syspass 1.1  behind a dmz proxy. 
outside via SSL  interal  standard http
working perfect. 

now i tried to update to 1.2. 
i am now able to login   on the internal LAN host  
but via the dmz-proxy  i only see the login screen. 

no login possible  not mysql not  ldap
there are no errorlogs pointing to some  broken files  or whatever, it  just down works via  proxypass
wtf ?

**Comment by nuxsmin** [comment]
That could be a JavaScript issue, that is not being served from the origin. Please take a look to the APP_ROOT in the JavaScript code, that is set to the base URL that your proxy is using.

I have a running sysPass instance behind a Varnish proxy though Pound for SSL...sure that is not a sysPass issue.

**Comment by osnet** [comment]
hmm allright,  didn't thought of this : ) ... 
maybe i should setup a rewrite with  preserve hostname ... 
I'll kepp ya posted
