### ISSUE TITLE
Question: why I can create accounts for other groups?

### ISSUE THREAD

**Issue by mkola-greenliff** [nuxsmin/sysPass#291]
Hi All,

I am playing with syspass since few days, but I cannot figure out is following thing is a bug or a feature:

Let's say I have two profiles: Users and Admins. I have also two groups: A and B. I have also two users: a and b. Both have the same profile (Users). This profile allow to add/remove/modify accounts. Users a is in group A and user b is in group B. User a can create accounts and assign group A to this account, but it also can assign group B to this account.
Can I block this somehow? I want user "a"  only create accounts for his group and cannot add any other groups to this account. Is that possible?

Thanks!
Mathias

**Comment by nuxsmin** [comment]
Hi,

Actually, it can't be done. The user that creates the account is the owner so he can perform any operation.

It could be performed by adding a new profile option that switches between allow or deny to add groups or users for accounts.

Let me add as a new feature for the next version.

**Comment by mkola-greenliff** [comment]
Wow, you are fast:)

Thanks a lot for answering this. It would be great to have this feature!

Mathias

**Comment by mkola-greenliff** [comment]
Hi,
I would kindly ask when do you plan to release 1.3 ?
Just asking because I am really interested in this feature.

Thanks,
Mathias

**Comment by nuxsmin** [comment]
Hi, it has already been implemented in the devel branch, but I'm currently doing some changes to that release. I think it could be done at the end of this month.

I'm working hard to release it shortly :)

**Comment by mkola-greenliff** [comment]
Thanks!

Mathias

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta
