### ISSUE TITLE
Unable to create database under ubuntu 16.04

### ISSUE THREAD

**Issue by cbtrident** [nuxsmin/sysPass#292]
Hi sorry this is a funny one
using ubuntu 16.04 have installed webmin/virtualmin this has setup the database and user that have access, 
using sysPass 1.2.0.18
mysql   Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper
i enter all the information to install and i get this error 

Error while creating "admin" group
Warn to developer

only error i saw in the sql was this 
2016-10-03T11:14:35.927015Z 2485 [Note] Access denied for user 'sp_admin'@'localhost' (using password: YES)

i would say i used the root access for this and even made a use but same error in the log with sp_admin
if i make the database my self it just wipe it out and then same error show.

i know i must be missing something but don't know what it is
any idea on how i fix this

**Comment by ValkyrieUK** [comment]
I am also receiving something similar ... 
`
[Mon Oct 03 12:56:35.523003 2016] [mpm_prefork:notice] [pid 2449] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.19 configured -- resuming normal operations
[Mon Oct 03 12:56:35.523081 2016] [core:notice] [pid 2449] AH00094: Command line: '/usr/sbin/apache2'
[Mon Oct 03 12:58:31.026214 2016] [:error] [pid 2463] [client 192.168.99.1:53748] Exception: SQLSTATE[28000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES), referer: http://192.168.99.99/syspass/index.php
[Mon Oct 03 12:58:31.027671 2016] [:error] [pid 2463] [client 192.168.99.1:53748] Action: addGroup -- Description: SQLSTATE[28000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES)(0);;SQL: INSERT INTO usrGroups SET usergroup_name = :name, usergroup_description = :description, referer: http://192.168.99.99/syspass/index.php
[Mon Oct 03 12:58:31.027694 2016] [:error] [pid 2463] [client 192.168.99.1:53748] SQLSTATE[28000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES)(0);;SQL: INSERT INTO usrGroups SET usergroup_name = :name, usergroup_description = :description, referer: http://192.168.99.99/syspass/index.php
`

**Comment by nuxsmin** [comment]
That is an error while accessing to the database by using the sysPass db user. sysPass only uses the root user to create the db structure, and then it switches to its own user.

This is most likely to a wrong password hashing during the user creation, so you would need to create the db user and the db (no structure). Then you need to set hosting mode at the install page.

You can find more info at http://wiki.syspass.org

Meanwhile I will do some tests.

**Comment by cbtrident** [comment]
am using the root access but it not working 
and as i said it seem to not make the user and if i've made the db may self it deleting

**Comment by nuxsmin** [comment]
Does it mean that even setting the hosting mode it deletes the database?

**Comment by cbtrident** [comment]
not try hosting  mode
will try once i bring the server back up doing update on the vm server right now

**Comment by cbtrident** [comment]
i see bug 293 is the same bug i have lol

**Comment by ValkyrieUK** [comment]
I managed to fix this by changing the permissions for root in MySQL.

> `GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;`

Probably not the safest route but worked for me.

**Comment by nuxsmin** [comment]
I've tested it on MySQL and MariaDB on Debian and it worked fine.

I noticed that if there is a config file, it fails to install for the first time, but it worked by retrying once again.

**Comment by cbtrident** [comment]
ok got it working and it was the password policy requirement
to do that i had to do the following

uninstall plugin validate_password;

one of the option when you install mysql to harden the security 

so the password you must be doing does not have a good security setup

**Comment by nuxsmin** [comment]
Great!!, that sounds fine, I've never thought about that plugin, because passwords are generated by hashing a string, so the length and difficult are quite good, but having a look to the policy options, the medium level requires an special character, so this can be the issue.

I'll code something to make it stronger.

Thanks for the feedback!!
