### ISSUE TITLE
v1.2.0.18 clean install on clean installed debian 8 - "error creating admin group"

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#293]
Error as follow:
When I've repeated install procedure - it went through without an error and I could log in

![fresh install debian 8](https://cloud.githubusercontent.com/assets/20043789/19111213/a6bf826e-8afe-11e6-955d-2721ce8c21dc.PNG)

**Comment by nuxsmin** [comment]
What database are you running on?

**Comment by akurzawa** [comment]
yesterday installed via apt-get via syspass debian like instructions set

```
+-----------------+
| @@version       |
+-----------------+
| 5.5.52-0+deb8u1 |
+-----------------+
1 row in set (0.00 sec)
```
