### ISSUE TITLE
ability to submit file for upload during creation of asset

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#295]
hello

another request - ability to upload/attach file to asset during asset creation. Right now I need to create asses, save data, do go asset edit -> select file for upload -> save data.

That would save a lot of time during asset creations

**Comment by nuxsmin** [comment]
Hello,

Sorry it can't be done, because every file need to be linked to the account ID, so if it has not been created, it won't know what id the account has...

**Comment by akurzawa** [comment]
nooooooooooo :) it has to be done... it's not fun at all, that I cannot add file during asset creation and need duplicate every task.. :( Please think of It, maybe You will find some sneaky trick to bypass this issue.

**Comment by akurzawa** [comment]
maybe somethink like this

1) create asset 
2) save data (now we have ID) - but syspass is not redirecting me to main page
3) im still in asset - now I can add file for upload 

What do You think?

**Comment by nuxsmin** [comment]
Ummm, that behavior was doing so in the past, but you may think about those people that add an account and they don't want to edit it in the following step.

Let me think if there is anything to get it.

**Comment by nuxsmin** [comment]
Done in sysPass 2.0
