### ISSUE TITLE
request - custom fileds custom assing to assets (customers)

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#296]
Hello

Currently all custom fields (assigned to accounts) are displayed on every asset (customer).

Would that be possible to display only these custom fields on assets which have data entered (hide empty fields) ? or select which fields are available to particular customer ?

![custom fields](https://cloud.githubusercontent.com/assets/20043789/19111683/2c28e13c-8b01-11e6-9047-2cc458741fc2.PNG)

**Comment by nuxsmin** [comment]
Hello,

The first point could be easily accomplished, but the second one would need a bit of coding, so it could be done for the next release.

**Comment by akurzawa** [comment]
Yeah I'm aware that second wish :D need a lot of programming, but first option will do :)

**Comment by nuxsmin** [comment]
Added to roadmap #422
