### ISSUE TITLE
enable https - how to do it ?

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#297]
how to enable https mode on syspass? what has to be done ?

after enabling https mode I immediately recieving SSL ERROR after page relaod

beside of that url is showing strange construction like ip:80/syspasspath - SSL over 80th port?

![przechwytywanie](https://cloud.githubusercontent.com/assets/20043789/19116143/bba19148-8b14-11e6-8071-904b42cf1985.PNG)

**Comment by akurzawa** [comment]
on clean debian and apache install, ssl module is not enabled by default... a2ensite default-ssl - hope this help someone

**Comment by akurzawa** [comment]
Yes, I'm able to get into syspass via https - so I guess everything works good. My sin is that I'm not apache ninja, and in this issue it required some apache config tricks. Is that possible to implement function to check apache config (modules required for SSL etc) before applying Force HTTPS in syspass ?

**Comment by nuxsmin** [comment]
Right, it would be possible to check for SSL apache modules, but that nos ensures that it was configured correctly.

I would add a warning about that behavior, so you can decide what to do better.

**Comment by akurzawa** [comment]
i've ended up adding apaceh redirection to https://


RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{SERVER_NAME}/%$1 [R,L]

Because force https in syspass caused strange url redirection ad on screenshot - https:/1.2.3.4**_:80_**/syspass

**Comment by nuxsmin** [comment]
Great!!

Thanks for the feedback.

I'll write it down in the wiki.

**Comment by akurzawa** [comment]
`
[Mon Oct 10 08:40:45.062020 2016] [:error] [pid 24080] [client 192.168.1.165:65179] PHP Warning:  mcrypt_generic_init(): Key length incorrect in /var/www/html/ipm/inc/Crypt.class.php on line 255, referer: https://192.168.1.32/ipm/
[Mon Oct 10 08:40:45.062041 2016] [:error] [pid 24080] [client 192.168.1.165:65179] PHP Warning:  mdecrypt_generic(): 13 is not a valid MCrypt resource in /var/www/html/ipm/inc/Crypt.class.php on line 256, referer: https://192.168.1.32/ipm/
[Mon Oct 10 08:40:45.062061 2016] [:error] [pid 24080] [client 192.168.1.165:65179] PHP Warning:  mcrypt_generic_deinit(): 13 is not a valid MCrypt resource in /var/www/html/ipm/inc/Crypt.class.php on line 258, referer: https://192.168.1.32/ipm/
[Mon Oct 10 08:40:45.062076 2016] [:error] [pid 24080] [client 192.168.1.165:65179] PHP Warning:  mcrypt_module_close(): 13 is not a valid MCrypt resource in /var/www/html/ipm/inc/Crypt.class.php on line 259, referer: https://192.168.1.32/ipm/
[Mon Oct 10 08:40:45.062105 2016] [:error] [pid 24080] [client 192.168.1.165:65179] PHP Warning:  DOMDocument::loadXML(): Empty string supplied as input in /var/www/html/ipm/inc/SyspassImport.class.php on line 92, referer: https://192.168.1.32/ipm/`

damn.. not so good after all

**Comment by nuxsmin** [comment]
Those messages are related to a an encrypted XML file when trying to import it. That is not related to SSL

**Comment by akurzawa** [comment]
forget previous htaccess redirect code - above is causing error redirect, when someone is trying to view non https website

it have to be:
```
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^ **https**://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

**Comment by nuxsmin** [comment]
Thanks!!

This is mine:

```
RewriteEngine On
RewriteCond %{HTTPS} !=on
#RewriteCond %{REMOTE_ADDR} !proxy_server # If proxy server is used...
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
```

**Comment by hasanakgoz** [comment]
Are you going to fix the bad https URL?

**Comment by DanielRuf** [comment]
> Are you going to fix the bad https URL?

I made a PR https://github.com/nuxsmin/sysPass/pull/708
