### ISSUE TITLE
LDAP approach for Microsoft AD is not usable in all AD cases (not a bug)

### ISSUE THREAD

**Issue by nsi-test** [nuxsmin/sysPass#299]
Hi, we’d like to use your software and we find it very nice. (It is 1.2.0.17 and not 18, but seeng the changelog, I don’t think it matters.) We have Microsoft domain and we need LDAP. First of all excuse me because I am not very PHP  or programming aware, but I can see some things. Your approach is to search users in some group, which is in some base. But our AD is configured in other way. All users are in an OU. And it is their container. They are members of groups of course, but one cannot get them from there. So our basic container for users is something like this:

 OU=HUB,DC=example,DC=local

There is no configuration in syspass that can search users there, because it needs a group, and I get an error like this:

`Error while searching group RDN
Group: (cn=OU=HUB,DC=example,DC=local)
LDAP FILTER: (cn=OU=HUB,DC=example,DC=local)`

You see how it concatenates a ‘cn=’.
OK, I opened inc/Ldap.class.php and about line 191 I changed the filter in this code:

`if (self::$_ADS === true) {
            $filter = '(&(|(memberOf=' . $groupDN . ')(groupMembership=' . $groupDN . ')(memberof:1.2.840.113556.1.4.1941:=' . $groupDN . '))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))';
        } else {
            $filter = '(&(|(memberOf=' . $groupDN . ')(groupMembership=' . $groupDN . '))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))';
        } `

with

`if (self::$_ADS === true) {
            $filter = '(objectClass=person)';
        } else {
            $filter = '(objectClass=person)';
        }`

Yes, it is very rude and simplistic, but it works for our case. Of course it’s not a bug and my fix works only for us (I know for sure that users are with objectClass=person ).
Then, when I put in configuration search base: OU=HUB,DC=example,DC=local and empty string for group, everything works.
My question is what do you think about that. And will it be possible for us to use your software in natural way?
By the way I have another question – what do you think about encrypting files? Of course one can upload them already encrypted now too.
Sorry for inconvenience and bad English.

**Comment by nuxsmin** [comment]
Hi,

group filtering is not needed, you can let it blank, so it won't search for group membership.

Thanks for the feedback!!

Don't worry about english, mine isn't quite good too... :)

**Comment by nsi-test** [comment]
Hi again,
I am very sorry, obviously it was some my mistake. Some typo in some field, search base, may be. I returned the original code and it’s working fine!
Excuse me one more time.
P.S. Do you think that encrypting files is a feasible feature for some time in the future?

**Comment by nuxsmin** [comment]
Great!!

Don't worry, I will add some documentation about LDAP config (work in progress).

File encryption could be implemented but I'll need to run some performance tests before.
