### ISSUE TITLE
Left angle bracket "<" causes remaining characters of password to be omitted

### ISSUE THREAD

**Issue by ghost** [nuxsmin/sysPass#30]
To reproduce:
- Create a new account or edit an existing one
- Include a left angle bracket "<" somewhere in the middle of your password. For example the password "pass<word" will do.
- Save the the account

Outcome:
- The characters of the password after and including the left angle bracket are missing when viewing the password. For example the above mentioned password would show as "pass"

Expected:
- The entire original password should be shown when viewing a saved password.

**Comment by Naelwan** [comment]
Hi again, 
I have the same issues even though I'm running the latest release.

"Pass<word" is shown as "Pass"
"Pass<<word" is shown as "Pass<"

**Comment by nuxsmin** [comment]
@Naelwan unfortunatelly a parameter in the ajax request was malformed...

Solved in last commit

**Comment by Naelwan** [comment]
Thank you !
