### ISSUE TITLE
complete backup solution biultin syspass

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#301]
Hi

another request for backup solution for database inside of syspass
aha scheduled backups
ability to backup syspass database on everyday on %time, delete backups older than %days
also restore selected database in case of data corruption, _bad employee_ (these are extremely dangerous) etc....

In syspass there is backup option, buy for moderate user its not enogh. It would be good to have simple BMR scenario. eg. My server is DEAD, but wait - i have backup, I'm downloading syspass, extracting files, performin quick install, and now I can conveniently restore data using "Restore Database" option in syspass sessing which... isnt there yet :( :)

**Comment by nuxsmin** [comment]
Hi,

Unfortunately sysPass cannot manage scheduled events, because it's written in PHP, which is a runtime compiled language.

Another point is that there are many backup software that are focused in doing it well, so why to develop poor backup software implementation?

sysPass should be focused in keep it simple: store passwords with confidence and provide some kind of integration with third party software.

**Comment by akurzawa** [comment]
how about this?

http://www.kavoir.com/2011/10/php-crontab-class-to-add-and-remove-cron-jobs.html

**Comment by nuxsmin** [comment]
Sure, but...

> Provided that your user account on the server has the privileges to access crontab thus can create or remove cron jobs, you can use this PHP class to integrate crontab in your application. I created it for many of my own projects that need crontab to do scheduled jobs. It’s pretty straightforward.

It means that it only creates a crontab job and some other tools would be need to perform the backup (ie mysqldump) thus creating some scripts that perform file rotation and maintenance....

Why not to add:

`0 2 * * * root /usr/bin/mysqldump -u syspass_user -p user_pass -h db_host syspass | tar czf sysPass_DB.tar.gz -`

to the crontab? (within an script would be better). By managing cron jobs would add a bit of complexity to the app...

**Comment by akurzawa** [comment]
because I dont want to deal manuall with crontab, also it does not cover version roration :) 
aka You do it :D

**Comment by Titus1024** [comment]
Akurzawa, I have deployed syspass on a VM and I find it much more hassle free to simply backup/replicate the VM in its entirety, in the rare event where I do need a backup of just syspass the manual backup and download is quite easy and quick and even then I still almost always prefer to have a complete backup of the entire VM.

**Comment by akurzawa** [comment]
HI @Titus1024 ... that's very very interesting approach but how can I implement/apply that solution when I install syspass on hosting on some server over the internet where obviously I don't have shell access ? Or when syspass was installed on physical computer? Also when I want to keep 30 versions of database - how much space is needed to keep 30 versions of Virtual Machine? :) 
As You can see making backups of database only is much more better solution...

**Comment by Titus1024** [comment]
Hi @akurzawa , if you have access to the VM or to the Host you can use programs like Nakivo and Veeam to replicate the VM as well as do incremental backups via snapshots, which would be much more manageable as far as size in concerned.

As for a physical machine you could always set up a cronjob or something similar to automatically backup the desired folders to an external drive/location off site.

Personally something as important as a password database I wouldn't want to host it externally but if I were I would want full access to it. But in the case of a limited access environment I would generally think if you're paying them to host VM's for you they would also be backing them up.

I'm not disagreeing with you though, being able to backup the database would be an awesome feature and I hope to see it as well, this was more of a temporary solution or an alternative backup method for disaster recovery scenarios.

**Comment by itlogsupport** [comment]
Hi @nuxsmin,

I'm trying to automate a backup with mysqldump just as you've suggested but I'm having some trouble.

The mysqldump backup exports all the DB settings but not the real data. If I compare mysqldump with the manual backup made inside sysPass the output is different. The backup from sysPass has all the data.

What am I doing wrong?

Thanks in advance,
GAR

**Comment by nuxsmin** [comment]
Hi @itlogsupport mysqldump will dump the whole database within data, unless you set the "-d" param, which means that no data will be exported.

Kind regards

**Comment by itlogsupport** [comment]
Hi @nuxsmin,

I know it should dump the wholeDB but it doesn’t. I’ve just used the command with the options you’ve suggested (mysqldump -u syspass_user -p user_pass -h db_host syspass | tar czf sysPass_DB.tar.gz -) but to no avail.

This is my system information:

sysPass version

1.2.0.21

Database

SERVER_VERSION : 5.5.52-MariaDB
CLIENT_VERSION : 5.5.52-MariaDB
SERVER_INFO : Uptime: 71085 Threads: 5 Questions: 78108 Slow queries: 0 Opens: 37 Flush tables: 2 Open tables: 63 Queries per second avg: 1.098
CONNECTION_STATUS : Localhost via UNIX socket
Name: syspass@localhost

PHP

Version: 5.4.16
Extensions: Core, date, ereg, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, shmop, SimpleXML, sockets, mbstring, tokenizer, xml, apache2handler, curl, dom, fileinfo, gd, json, ldap, exif, mcrypt, mysql, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, sqlite3, wddx, xmlreader, xmlwriter, xsl, zip, mhash
Used Memory: 2048 KB
User: apache

Server

Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.1



Can you, please test?

Thanks in advance.


Kind regards,

Gilberto Ribeiro

**Comment by nuxsmin** [comment]
Hello @itlogsupport 

sorry for the late response, I missed this issue among the others. I'm wondering if you got it..
