### ISSUE TITLE
ux - mobile friendly view

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#302]
hello

I've found that front page of sysapss have some overlapping layers in mobile view - any chances to correct that?

![syspass](https://cloud.githubusercontent.com/assets/20043789/19231835/9bd75f98-8edc-11e6-9376-d954e997cae1.PNG)

**Comment by nuxsmin** [comment]
You're right and this behavior has been discussed a time ago.

Actually, I think it's better to develop a mobile app that connects to the sysPass API, so it wouldn't deal with browsers' behavior.

BTW, I'll try to make it more mobile friendly in the next release.

**Comment by akurzawa** [comment]
I think it would be very inconvenient to manual password inputting (from mobile) rather via copy from browser and paste in eg. rdp - I'm wondering of usability of such kind of app - or rather if will be useful at all. What the mobile app will be used for? Any main reason? I'd dont want You to prevent of developing such an app, but I think that syspass itself needs to be developed, some users Can't waif for new functions etc ;) May I ask how many devs working on syspass developing?

**Comment by nuxsmin** [comment]
A mobile app will be focused in some functionalities like listing accounts and viewing passwords. The full-featured app will always be on the web interface. I think on some native functions that every platform has (desktop and mobile), which prevents to develop a fully cross-compatible app.

Copy&paste actions can be done seamlessly in the mobile device.

Actually there's only one developer...me ;)...and yes, too much work!!

**Comment by akurzawa** [comment]
@nuxsmin I can help with ux design and CSS, also translation (Polish Land) - how to get in touch You?

**Comment by nuxsmin** [comment]
Great!!, that would be nice, we can get in touch through email (take a look to the source code) or instant messaging (hangout, telegram). Do you have any preference?

**Comment by akurzawa** [comment]
I've sent message to ********@****.***  =D

**Comment by nuxsmin** [comment]
Right, I've seen it. Let me some time to get in touch...

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta
