### ISSUE TITLE
error report - apache

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#303]
I've an error in apache:

`[Mon Oct 10 08:40:45.062132 2016] [:error] [pid 24080] [client 192.168.1.165:65179] PHP Catchable fatal error:  Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given, called in /var/www/html/ipm/inc/SyspassImport.class.php on line 57 and defined in /var/www/html/ipm/inc/SyspassImport.class.php on line 93, referer: https://192.168.1.32/ipm/
`

Something to worry about?

**Comment by nuxsmin** [comment]
Did you set any password when exporting to XML?

**Comment by akurzawa** [comment]
Yes, I did.

**Comment by nuxsmin** [comment]
So it failed when importing, didn't it?

**Comment by akurzawa** [comment]
yea ;] all is ok
thx for explaining this issue
