### ISSUE TITLE
binding database to syspass

### ISSUE THREAD

**Issue by Palazur** [nuxsmin/sysPass#304]
Good afternoon, crooked updated syspass, now he wants to start prtsoess installation. When you enter the database settings, syspass says that the existing database to remove. How do I get started syspass use an existing database?

**Comment by nuxsmin** [comment]
Hi!

You need to copy the config.php file to the new location.

Which version are you upgrading from?

**Comment by Palazur** [comment]
Thanks you! That helped! Syspass updated to 1.2.017> 1.2.0.18

**Comment by nuxsmin** [comment]
Great!!..Thanks for the feedback
