### ISSUE TITLE
blank screen , searching not possible

### ISSUE THREAD

**Issue by jnid** [nuxsmin/sysPass#305]
since the latest update we are having regular issues that when logging in will give a blanc page (only logo and buttons on the left visable). searching doesnt work (loading button keeps going, or notice: invalid query).
This is quite blocking when working with syspass. rebooting services or even the complete server doesnt solve anything. clearing browser cache also doesnt solve it, resetting passwords, using other browsers (firefox, chrome, ie, opera). no solution
version: syspass 1.2

update some php errors:
PHP Fatal error:  Call to undefined function SP\\mb_substr() in /var/www/html/sysPass/inc/Html.class.php on line 96, 

PHP Warning:  mcrypt_generic_init(): Iv size incorrect; supplied length: 31, needed: 32 in /var/www/html/sysPass/inc/Crypt.class.php on line 255, 
![syspass-error-screen](https://cloud.githubusercontent.com/assets/22788678/19354830/686bcfb6-9168-11e6-9bad-e9ec311cb058.png)

**Comment by nuxsmin** [comment]
Hi,

Which version are you running on (sysPass and PHP)?

You can get it at the information tab in config module.

**Comment by nuxsmin** [comment]
A link that may be useful:

http://stackoverflow.com/questions/14035698/fatal-error-call-to-undefined-function-mb-substr#14035718

**Comment by nlmaca** [comment]
thx. was running php 5.4.6 this error just came out of nowhere. we were running great on the latest syspass. fixed it (for as far as i see) on centos by installing mbstring.
yum install php-mbstring
restart service httpd afterwards. 
Checked the error logs of apache. and everything seems ok now. thx for the link and quick response!
Ticket can be closed. / solved

**Comment by jnid** [comment]
issue closed. solved (sorry, private and work account;)

**Comment by nuxsmin** [comment]
Great!

thanks for the feedback!
