### ISSUE TITLE
Keepass import?

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#306]
Is it possible to import a Keepass database?

**Comment by nuxsmin** [comment]
Sure, you can perform an import from a keepass XML export.

Let me know if it doesn't work.

**Comment by nuxsmin** [comment]
Did it work?

**Comment by itlogsupport** [comment]
Hello,

I'm exporting all the fields in KeePass 1 to XML but when I try to import them in sysPass I get the "XML file not supported - Unable to detect the application the data was exported from" error.

What am I doing wrong?

Thanks in advance,
GAR

**Comment by nuxsmin** [comment]
Hello @itlogsupport 

KeePass import has been implemented for 2.x XML version, so there would be needed some tweaks to get it working. Let me code some stuff to get it.

Kind regards

**Comment by itlogsupport** [comment]
Hello @nuxsmin, 

Thank you for your reply.

I've converted my Keepass 1 database to Keepass 2 and now I'm able to import without issues except for the attachments in the Keepass's  entries.

Keepass exports the attachments but sysPass doesn't imports them nor does it provides an error.

Is there any possibility to import the Keepass database with the attachments? I have a lot of them.

Kind regards,
GAR

**Comment by nuxsmin** [comment]
Good news!. I would need to take a look to the attachments structure, because currently the import process does not perform any action on the attachments.

**Comment by itlogsupport** [comment]
Please see the attached keepass example file. The password is "123".

[ExampleKeepassExport.zip](https://github.com/nuxsmin/sysPass/files/750272/ExampleKeepassExport.zip)

**Comment by nuxsmin** [comment]
Solved in >= 2.0

**Comment by rogeriojlle** [comment]
but how do you do it?
Confirm button is not showing
![image1087](https://user-images.githubusercontent.com/562996/236705104-4fc0905d-663a-4e29-82a7-dffcfa6c264c.png)
