### ISSUE TITLE
Categories do not update

### ISSUE THREAD

**Issue by piknik** [nuxsmin/sysPass#307]
Hello, I have sysPass 1.2.0.18 logged in as an admin and have been importing passwords from a previous password database. I ran into what seems to be a bug, where modifying a category does not update that category. I've tried modifying many categories but none of them change no matter what I enter. In fact, I cannot even delete any of the categories I've created. When I attempt to modify or delete a category, a green box on the bottom right pops up and tells me "Category updated" or "Category deleted", but nothing changes on the screen. Logging out and back in does nothing either.

I would attach debug information, but the debug that is given in debug mode does not seem to produce anything that seems relevant. If there is some other location to view debugging let me know and I'll add more details.

**Comment by nuxsmin** [comment]
Hello,

Let me do some testing to try to find out what can be happening.

I've noticed that the demo site works fine, so it's weird.

Can you take a look to the webserver logs?

**Comment by piknik** [comment]
@nuxsmin Just took a look at `/var/log/apache2/error.log` and there are no PHP errors today, which means there are no errors from updating a category.

If it matters, I have sysPass running under fresh ubuntu 16.04 with the standard [LAMP](https://help.ubuntu.com/community/ApacheMySQLPHP) stack, PHP 7.0 and MySQL. Installation of sysPass was done as indicated [here](http://wiki.syspass.org/en/install) minus installation of the stack.

**Comment by nuxsmin** [comment]
Ok, I'll need to test sysPass behaviour in an environment like yours.

sysPass won't log any warning if the debug mode is not set, so can you test it again?

Thanks for the feedback!

**Comment by piknik** [comment]
Sure thing. I've enabled debug mode in settings. Here is the access log, going to the categories page and attempting to delete a category (private information starred out):

```
192.168.1.*** - - [15/Oct/2016:22:25:10 +0000] "POST /ajax/ajax_getContent.php HTTP/1.0" 200 4719 "https://**************.net/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36"
192.168.1.*** - - [15/Oct/2016:22:27:21 +0000] "POST /ajax/ajax_appMgmtSave.php HTTP/1.0" 200 365 "https://**************.net/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36"
192.168.1.*** - - [15/Oct/2016:22:27:21 +0000] "POST /ajax/ajax_getContent.php HTTP/1.0" 200 4722 "https://**************.net/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36"
```

**Comment by piknik** [comment]
Unfortunately, no error log and nothing changed at all in the debug log display

**Comment by nuxsmin** [comment]
You're right... that seems fine.

One last thing, can you get into the database and take a look into the categories table? Can you update any category (in db) and then refresh the sysPass view?.

**Comment by piknik** [comment]
Yep, went into the MySQL workbench, accessed the categories table, and changed the name of one of the categories. Then when I refreshed the page, it shows the changed category name.

**Comment by nuxsmin** [comment]
Fine, the view is working as expected, so there would be any issue when executing the update query.

Great work!, I'll let you know any progress.

Thanks!

**Comment by nuxsmin** [comment]
This issue has been fixed in the latest commit by @ejouvin 

Can you test it?. You'll need to download from the master branch

**Comment by piknik** [comment]
I can confirm that it is working now, changes I make to categories update and stay updated even after logging out. Also, attempting to delete a category shows an error due to containing entries, which it didn't before.

Thanks!
