### ISSUE TITLE
secure account access email notification

### ISSUE THREAD

**Issue by ltguide** [nuxsmin/sysPass#311]
Would it be possible to mark accounts as secure? Whenever anyone views the password it would email the owner/admin/group members.

We have certain accounts that need to be shared, but only for emergency use. So the password needs to be monitored/changed.

**Comment by nuxsmin** [comment]
Hi, there will be public shared links, that you can limit either by account views counter or password views.

It will be available in next 1.3 version.

**Comment by nuxsmin** [comment]
BTW, it could be useful to send an email whenever the account is viewed.

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta
