### ISSUE TITLE
Can non edit user / group / profile properties on fresh install

### ISSUE THREAD

**Issue by ejouvin** [nuxsmin/sysPass#313]
Hello.

I installed the version 1.2.0.18 as a fresh install on Ubuntu + Mysql + php7

Installation was successful, and i can connect with the admin account.
But, I am not able to edit properties users / group and profile (I stop using it for that)
Then, the second user connected to LDAP can not be activated.

I noticed that in icons for actions, the item id is not set into the node attribute "data-itemid" like this :
`<img src="imgs/edit.png" title="Editer Utilisateur" class="inputImg btn-action" data-itemid="" data-activetab="0" data-nextactionid="70" data-onclick="sysPassUtil.Common.appMgmtData(this,712,'970fc748e49d6c641c3b3b8503d00e7d11703030')">
`

Something ?
I will try to investigate.

Etienne

**Comment by nuxsmin** [comment]
Hello,

it could be some issue with PHP version. sysPass has not been fully tested on PHP 7

Let me try to find out what could be happening.

**Comment by ejouvin** [comment]
Ok thanks. Can not test for now, but let me know if you want me to test this on my platform.

**Comment by ejouvin** [comment]
Finally I managed to get it works. Do not know why I have to do this.

In file mgmttabs.inc

replace
`<?php $itemId = $item->$tab['props']['tblRowSrcId']; ?>`

By
```
<?php $srcIdName = $tab['props']['tblRowSrcId']; ?>
<?php $itemId = $item->$srcIdName; ?>

```

In fact, it seems that it always "failed" when the value in 'props' is not an array.
