### ISSUE TITLE
Account Name as Link not working under Classic visual theme

### ISSUE THREAD

**Issue by Titus1024** [nuxsmin/sysPass#315]
This is a bit of an odd one, the account name as a link feature works perfectly fine under the Material Blue visual theme but it does not work under the Classic visual theme. The account name still visually behaves like a link but it doesn't do anything when you click on it.

Another little thing I just noticed that I'm going to throw in here is that the labels at the top; Customer, Name, Category etc don't line up with their respective column.

**Comment by ejouvin** [comment]
Just try on my instance, name are not display as linked in both theme.
May be a php 7 issue ?

**Comment by nuxsmin** [comment]
Could be, both themes are using the same function to open those links.

I've done some tests on PHP 5.6 and it worked fine.

**Comment by ejouvin** [comment]
I Will give à try to that in couple hours

**Comment by ejouvin** [comment]
With my instance, it works "like a charm", BUT...

There is something really confusing.
I went to application settings and set the parameter as "true". So I expected the account name will be displayed as a link.

But, when I connected, the name is only a label.
Then, I went into my user preferences, and saw that the option is disabled. I activate it and here we go.


So in fact, there is two level for configuration, one applyed as global and one specific to user.
I may have already modify my user prefrence (for sure to select the theme) without setting the option. And the parameter was retrieved from my user scope and not from the application scope.

So, not a bug, but a little bit confusing. It is exactly like the theme selection in fact. It can be classic at the application level, but if I set Material Blue into my preferences, it will override.

Hope it helps to understand.

**Comment by nuxsmin** [comment]
Right, your preferences takes precedence over the app ones, BUT only if you save your preferences for the first time. A newly created user has no preferences, so the app takes over.

Many thanks for the feedback!!

**Comment by Titus1024** [comment]
![classictheme](https://cloud.githubusercontent.com/assets/22060361/19703289/482c404c-9ad1-11e6-88cc-ebc6060624a6.PNG) Just to add some examples/pictures, this one is with the Classic theme selected, the name is showing up as a link but it does not do anything when clicked, where as this one; 
![materialbluetheme](https://cloud.githubusercontent.com/assets/22060361/19703380/9c02469e-9ad1-11e6-9ed6-c93734de7903.PNG) the name functions as a link to the details page.

**Comment by nuxsmin** [comment]
Sorry, I were unable to reproduce this issue. Please update to 2.1.

Kind regards
