### ISSUE TITLE
first installation in Spanish?

### ISSUE THREAD

**Issue by nlmaca** [nuxsmin/sysPass#316]
is it possible to change the first installation to English? in think english is a more known language when installing applications. 
no i have to google because i have no idea what Clave Maestra means ;).

**Comment by nuxsmin** [comment]
Right, Spanish is the translated language and you need to setup the locales on your OS. On Debian like distributions by issuing: ``dpkg-reconfigure locales`` and choosing your language UTF8 variant or en_US if your language is not translated
