### ISSUE TITLE
Unable to login after installing syspass

### ISSUE THREAD

**Issue by joefrancois** [nuxsmin/sysPass#317]
Hello,

I have installed Syspass and Wordpress on the same Apache2 server. I am running mod_ssl and mod_auth_openidc to authenticate users agains G suite (Google Apps). The site seem to run as expected, except that I can't login into Syspass after install. It returns "Wrong User/Password". I went so far as installing it on a virtual server, I made sure my password was working and created a dumy user. I than transfer the installation to the production server and I get the same issue. 

Not sure what else to do. Any help?

Regards,

**Comment by nuxsmin** [comment]
Hello,

Does match the Apache auth username with the user created in sysPass?

Kind regards

**Comment by joefrancois** [comment]
Hello,

I am not sure I understand, I am using the standard Debian user to start Apache. I don't have an Authentication name configure (at least not that I think of). I tried to login with admin and joe and neither of them worked. It did work on the virtual machine when I first install it.

**Comment by nuxsmin** [comment]
Hello,

the OpenId Apache module sets some headers that are read by PHP and sysPass, so if you performed and auth request before, those headers were set.

Can you test this example?: https://github.com/pingidentity/mod_auth_openidc/wiki#10-can-you-show-me-a-simple-application

**Comment by joefrancois** [comment]
Hello,

I ran the program, it looks to have quite a bit of confidential info. Which field you would like to see?

**Comment by nuxsmin** [comment]
The interesting part would be REMOTE_USER that should be the same that you use to log into sysPass

**Comment by joefrancois** [comment]
There is no REMOTE_USER variable using this code:

<html>
  <body>
    <h1>Hello, <?php echo($_SERVER['REMOTE_USER']) ?></h1>
    <pre><?php print_r(array_map("htmlentities", apache_request_headers())); ?></pre>
    <a href="/protected/redirect_uri?logout=https%3A%2F%2Flocalhost%2Floggedout.html">Logout</a>
  </body>
</html>

**Comment by nuxsmin** [comment]
But it should show "Hello, ..." where there is an username, isn't it?

**Comment by joefrancois** [comment]
oh ok now I understand. The REMOTE_USER is set to my Google Apps email address. I also have in my configuration the following line "OIDCRemoteUserClaim email". Should I change it to something else?

**Comment by nuxsmin** [comment]
No, you could set the same username within sysPass.

**Comment by joefrancois** [comment]
Sure, but the problem is that I can't even login into syspass to create users. Unless I create my username on my virtual server and do a DB dump.

**Comment by nuxsmin** [comment]
Can you disable openid for a while?. Another alternative would be to modify the username in the sysPass db by looking at the usrData table

**Comment by joefrancois** [comment]
OK I changed the admin user by my google apps email address and it works.Thank you for your help and patience. 

Is there a way for the users to keep only one password. Right now they would have a password for google and one for syspass?

**Comment by nuxsmin** [comment]
Unfortunately, by now, the user's password is used to encrypt the master password, so he won't need to enter it on every login.

I will try to find out a better solution for SSO environments.

**Comment by joefrancois** [comment]
Ok no worries, anyway it is better that way.

One last question, is there a way I can have the User field in the login page to take the value of REMOTE_USER?

**Comment by nuxsmin** [comment]
Actually not, but it can easily implemented. Let me add that feature for the next version.

This kind of auth was not intended to implement SSO, it's goal was to filter which users can log into sysPass, but I think that SSO would be useful.

**Comment by joefrancois** [comment]
That would be cool. Thank you for the great work and for your help.

**Comment by nuxsmin** [comment]
You're welcome.

Thanks for the feedback!
