### ISSUE TITLE
Accounts not loading

### ISSUE THREAD

**Issue by Naelwan** [nuxsmin/sysPass#318]
Hi,
I installed sysPass on a CentOS 7 machine last Friday and everything worked well. (good job btw.)

Today, I moved all my passwords (about 120 on 7 different customers) to sysPass and they are not loading anymore. When I click on the magnifying glass, there is a loading wheel, but it never stops and my accounts never appear.

![untitled](https://cloud.githubusercontent.com/assets/15652379/19648380/394b46ec-9a02-11e6-818c-8b27d4695a4c.png)

Any clue on this problem ?

**Comment by nuxsmin** [comment]
Hello,

I'm glad that you found it useful.

This issue could be because an account field that breaks the server response.

Can you see any error at the JavaScript console? (F12 on most browsers)

Kind regards

**Comment by Naelwan** [comment]
Yes, 2 errors : 

1st one : 
------------------------------------------------------------------------------------------------------------
POST https://x.x.x.x/sysPass/ajax/ajax_getContent.php 500 (Internal Server Error)
        send @ js.php?v=da4fb5c…:5
        ajax @ js.php?v=da4fb5c…:5
        doAction @ js.php?v=da4fb5c…:114
        onload @ index.php:11


2nd one : 
------------------------------------------------------------------------------------------------------------
js.php?v=da4fb5c…:114 Uncaught TypeError: Cannot read property 'replace' of undefined
    at resMsg (https://x.x.x.x/sysPass/js/js.php?v=da4fb5c6e93e74d3df8527599fa62642:114:16249)
    at Object.error (https://x.x.x.x/sysPass/js/js.php?v=da4fb5c6e93e74d3df8527599fa62642:114:1575)
    at j (https://x.x.x.x/sysPass/js/js.php?v=da4fb5c6e93e74d3df8527599fa62642:3:27295)
    at Object.fireWith [as rejectWith] (https://x.x.x.x/sysPass/js/js.php?v=da4fb5c6e93e74d3df8527599fa62642:3:28108)
    at x (https://x.x.x.x/sysPass/js/js.php?v=da4fb5c6e93e74d3df8527599fa62642:5:22086)
    at XMLHttpRequest.b (https://x.x.x.x/sysPass/js/js.php?v=da4fb5c6e93e74d3df8527599fa62642:5:25980)
    resMsg @ js.php?v=da4fb5c…:114
    error @ js.php?v=da4fb5c…:114
    j @ js.php?v=da4fb5c…:3
    fireWith @ js.php?v=da4fb5c…:3
    x @ js.php?v=da4fb5c…:5
    b @ js.php?v=da4fb5c…:5

**Comment by nuxsmin** [comment]
And what about the webserver error log?

**Comment by nuxsmin** [comment]
This issue is related to #305 

Please take a look to: http://stackoverflow.com/questions/14035698/fatal-error-call-to-undefined-function-mb-substr#14035718

About password and notes length, both are limited to 255 and 1000 chars.

**Comment by nuxsmin** [comment]
The above function is needed to cut down any string that has a high length, because it will break the UI.

**Comment by Naelwan** [comment]
Hi, 

Installing the package php-mbstring solved the issue.

Thanks a lot for the help.

Best regards

**Comment by nuxsmin** [comment]
Great, thanks for the feedback!
