### ISSUE TITLE
LDAP configuration form does not display the reveal password in classic theme

### ISSUE THREAD

**Issue by ejouvin** [nuxsmin/sysPass#322]
Using the material Blue theme, on the LDAP configuration form, we can see an icon to reveal the password for the account.
Also, there is the tool to generate the password, seen on demo site.

But on classic view, icon is not display, nor tools for the password.

Is it an expected behaviour or a miss ?

**Comment by nuxsmin** [comment]
So sorry for the late response... I missed this issue.

I think that has been solved in the latest commits, so could you test it again?

Kind regards

**Comment by nuxsmin** [comment]
You did a PR, didn't you?

**Comment by ejouvin** [comment]
No I did not do anything for that.
Yes I did by mistake a PR but cancelled it.

Ok, I will try from the source.

**Comment by nuxsmin** [comment]
Please, upgrade to 2.1

Kind regards

**Comment by ejouvin** [comment]
I first try to update to version 2.0, the first release.
But it failed when typing the upgradeKey on the upgrade page.

I will try the second 2.0 release, and if it is still in failure, upgrade to 2.1.

I want to do it step by step, just to check all releases. I know, I could jump to the latest one directly.

**Comment by nuxsmin** [comment]
Sure, but be aware that I've done a bunch of tests upgrading from 1.2.11 to the latest 2.1.1 over 4000 accounts and all the issues found have been fixed, so the process would go fine.

**Comment by ejouvin** [comment]
Ok, I will try.

I am trying to upgrade from 1.2.0.21 to 2.0.0.XXXX and then go to all others.
My difficulty is at this step :

![image](https://cloud.githubusercontent.com/assets/8817923/23683044/2a09c312-0397-11e7-8437-295dd4f7d784.png)

**Comment by nuxsmin** [comment]
Please, upgrade to 2.1 because the upgrade process has been improved and some features like Ajax requests make it smoother.

The 2.1 version is a key point in sysPass because it implements a new encryption schema and other security mechanisms.

**Comment by ejouvin** [comment]
For now, not already try to install the 2.1.

I know, I should do it ;)

For now, I had some difficulties to upgrade the database because of "errors" when constraints are applyed. I had some inconsistency values in my database.
All were fixed .

But as the theme classic was removed, I had error after login. I have to update my preferences then.

Will let you know, even if I should go throw 2.1

**Comment by nuxsmin** [comment]
Hi @ejouvin, don't worry about constraints, they would be fixed during the upgrade by creating "orphan" items that you could delete after.

The preferences can be set before upgrading, so there won't be such issue.

**Comment by ejouvin** [comment]
Ok, finally I was able to install all intermediate versions.
I had some error in some values in the history. But it was my failt, deleting a customer or a client is not necessary a good idea.

Now, I have the 2.1.2 installed, every weel.

Thanks

**Comment by nuxsmin** [comment]
Great!, I hope you enjoy with the new version ;)

Thanks for the feedback!

**Comment by ejouvin** [comment]
For now, I enjoy the application.

Just seen the new features, tags / account linking, but do not need them for now ;)
