### ISSUE TITLE
Deleting does nothing sitewide

### ISSUE THREAD

**Issue by DirtyCajunRice** [nuxsmin/sysPass#327]
Deleting yields no results. It shows the "Deleted" popup in the bottom right but does not actually delete it. The user has full rights to the database.

**Comment by nuxsmin** [comment]
It could be because the PHP version

**Comment by DirtyCajunRice** [comment]
[nick@WEB ~] php --version
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

**Comment by nuxsmin** [comment]
That was solved in the latest commit. It's because the PHP version
