### ISSUE TITLE
Edit does not populate

### ISSUE THREAD

**Issue by DirtyCajunRice** [nuxsmin/sysPass#328]
Editing users/groups/profiles yields no results. it does not populate the fields. It is as if you are adding in a new entry every time. If you name the entry the same as before when editing it says it already exists.

**Comment by nuxsmin** [comment]
What PHP version are you using?

**Comment by DirtyCajunRice** [comment]
[nick@WEB ~] php --version
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

**Comment by ejouvin** [comment]
May be, you should take a look at #314

**Comment by nuxsmin** [comment]
Hello, this was solved in the latest commit but is hasn't been yet tagged as a release
