### ISSUE TITLE
Master branch is stable ?

### ISSUE THREAD

**Issue by LeDistordu** [nuxsmin/sysPass#330]
I want to base my docker container on depot git source but I do not know if the master branch is stable

**Comment by nuxsmin** [comment]
Sure, I used to publish updates and bug fixes that have been already tested and then release a new version when there are enough changes or a critical bug fix is solved.

**Comment by LeDistordu** [comment]
Thank you for your reply and thank you for this great project !

**Comment by nuxsmin** [comment]
Thanks for your support!!
