### ISSUE TITLE
LDAP search base

### ISSUE THREAD

**Issue by clauded** [nuxsmin/sysPass#331]
We're using sysPass 1.2.0.18 with a Windows 2003 AD ldap backend. 

When I try to set the search base to 'DC=myorg,DC=local', the ldap check always fail with 'Error while searching group RDN'. If I use a search base like 'OU=My Groups,DC=myorg,DC=local', I get 'LDAP connection OK, 0 objects found'.

The syspass group is under 'OU=My Groups,DC=myorg,DC=local' but my users are under differents OUs not under 'OU=My Group...

**Comment by nuxsmin** [comment]
Hi, did you set ADS in the LDAP config?

**Comment by clauded** [comment]
Yes, ADS is set to ON.

**Comment by ejouvin** [comment]
Take a look at issue #321
It may help ou

**Comment by clauded** [comment]
I moved the syspass group directly under DC=myorg,DC=local. Still have the same problem.

**Comment by haken735** [comment]
Hi, 

I have the same issue.
I work with MS AD 2012 and my syspass is installed on ubuntu 16.04 (i've tried on debian 8 too).
I know my ad authentification it's ok because we use it with jenkins/ sonarqube and glpi. 

Have you any idea or something i can check for fix this ?

**Comment by nuxsmin** [comment]
Hello,

What is the group name format that you set?. Have you tried out to set in both formats (DN and non DN syntax)?

**Comment by haken735** [comment]
Hello, 

I did it this morning! I have to specifiy the port in server form (ex: ldap://my_DC:3268).
I don't know why when the port is not specified the error log returned is error RDN goup.

Thank you.

**Comment by nuxsmin** [comment]
That sounds great!!. Thanks for the feedback
