### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by CyrosX** [nuxsmin/sysPass#332]
Hello there,
I'm getting this error:

Fehler beim Sender der Mail
ERROR: SMTP connect() failed.

We changed our provider (and I changed the credentials in sysPass). But it does not work
Authentication through SSL 465 and PLAIN. Is this the problem? :-o

**Comment by nuxsmin** [comment]
May be you need to get the SSL server's CA certificate? It should be retrieved if it has a self signed certificate.
