### ISSUE TITLE
Could not perform the password change request.

### ISSUE THREAD

**Issue by fama89** [nuxsmin/sysPass#333]
Hi All!
I have a problem with syspass. I added a new user, but she/he didn't get a mail with username and password. I marked the force password change. In the log there is this message:
"Could not perform the password change request." 
Email notifications were sent to admin.
Please help me, what could be the problem.

**Comment by nuxsmin** [comment]
Hi!, it could be because a wrong mail configuration. Actually there isn't any mail config checking available (through sysPass). Let me code some stuff to perform it...
