### ISSUE TITLE
Select symbols and letters for password generator

### ISSUE THREAD

**Issue by TitovLab** [nuxsmin/sysPass#334]
Hello!
sysPass has password generator feature.
Maybe it is a good idea to provide global configuration options to sysPass admins:
- to select symbols and letters in upper and lower cases used in password generator (for example exclude "0" and "O" to prevent confusing, or "I" and "l" and etc)
- to prevent password begining with numbers and symbols, because many systems can not use this passwords
Thank you.

**Comment by nuxsmin** [comment]
Sure!! it would be a nice feature...

**Comment by nuxsmin** [comment]
Added to roadmap #422
