### ISSUE TITLE
Hide unused customers

### ISSUE THREAD

**Issue by TitovLab** [nuxsmin/sysPass#335]
Hello.
With sysPass we can delete all customer accounts and then delete customer. But this is very slow and if after a few months we will again need this customer, we need to go to the database and manually restore accounts.
Maybe it will be nice feature to hide unused customer (his accounts and his name from dropdown list on main page) and not to delete accounts. Later, if we need to restore customer, we can unhide it in Customers Management.
Thank you.

**Comment by orcas-apisch** [comment]
It would be nice to be able to hide (certain) customers per group at all too.

**Comment by nuxsmin** [comment]
Added to roadmap #422
