### ISSUE TITLE
Password not correctly shown if it contains '<'

### ISSUE THREAD

**Issue by ArminXG** [nuxsmin/sysPass#336]
If the password contains special characters (verified with '<'), the "View Password" popup window shows only the first characters until '<'. Copy to clipboard from that windows doesn't work as well.
But copy to clipboard function from Account Details view does work.
It seems to be a missing html encode function.

Armin

**Comment by nuxsmin** [comment]
Hi, that issue has been already solved in the current master branch, but it hasn't been tagged yet as a new release. Today I'll release it.

**Comment by ArminXG** [comment]
Ah, okay. I didn't check the new commits.

Thank you!!!
