### ISSUE TITLE
AD Ldap : user disabled 

### ISSUE THREAD

**Issue by anburhce** [nuxsmin/sysPass#337]
Hi Nuxsmin,

first of all: Thank you to all contributors for this great software . 

i have implemented the syspass 1.2 on centos 7 and integrated with AD Ldap .  when i try to login using AD user i am getting the below email  to for "Account Activation " .

==

Your account activation is pending.
You will receive a confirmation email shortly.

--
sysPass - Systems Password Manager
http://172.30.0.245/syspass 

==

But am not getting any confirmation  mail later  to enable the Account .

please help to solve the issue . 

currently i am activating the account by login as admin and unselect "Disabled" option in user account .

**Comment by nuxsmin** [comment]
Hi @anburhce,

That email is sent when any LDAP user is added to sysPass, but it's only for information purposes, because that confirmation email would be sent by any sysPass admin when the account is fully configured.

sysPass won't send any confirmation email.

Kind regards

**Comment by nuxsmin** [comment]
In addition, that is so because sysPass doesn't know which profile or group the user belongs to.

**Comment by tumtumdev** [comment]
Hi Nuxsmin,

Is it possible to sync or import LDAP users into syspass?
Currently the default group is limited for every 'new' user.

I want to import the new users and assign the account directly to the correct profile and group, before they login. Is this possible with a script or this tool? This is one of the reasons it is hard to control the user rights with LDAP. (First login with the masterkey > Check the login and assign the profile/group > Change userpassword option in windows for first time login > Complete)

**Comment by anburhce** [comment]
thank you Ruben .

**Comment by nuxsmin** [comment]
Hi @tumtumdev 

Actually not, but I'm implementing that feature for the next release.

**Comment by nuxsmin** [comment]
You're welcome @anburhce

**Comment by tumtumdev** [comment]
Thanks! It would also be awesome if the masterkey isnt needed for a userlogin with ldap. With a lot users, it is hard to save it or to provide every 100~ days a new key.

**Comment by nuxsmin** [comment]
The new master key implementation will be seamless, that is, it will be required for first time the user logs in and whenever the key is changed. Afterwards, the only password required will be the user's one.

**Comment by tumtumdev** [comment]
Ok, nice, It will save a lot time every ~100 days! Thank you Ruben, Tom

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta
