### ISSUE TITLE
Problems submitting passwords during install/login

### ISSUE THREAD

**Issue by gitforwebwork** [nuxsmin/sysPass#338]
I have managed to install sysPass on an AWS EC2 instance running Amazon Linux, but now I can't login. I think it is the same issue as I had when I tried to install it.

Basically, the installer did not submit/receive any passwords I entered into the pre-installation form (usernames etc. submitted fine), so for the installation I ended up hard coding them into the _Installer.class.php_ file. 

For example:
```
    public static function setPassword($password)
    {
        self::$_password = $password;
    }
```
became:
```
    public static function setPassword($password)
    {
        self::$_password = "mypassword";
    }
```
I had to do this for all passwords (admin,master,database) before the installer would run through successfully. Once the installation was finished, it took me to the login screen. I entered the admin username and password, and got the error "User/Pass not entered" in a red box on the bottom right of the browser.

You can check it out here: https://35.156.39.13/syspass/

Just enter any bogus username and password, and you will see that it will tell you "User/Pass not entered".

I have never come across the kind of issue. Any help would be greatly appreciated. I could provide you with phpmyadmin and FTP access... I launched the EC2 instance purely to test sysadmin, so there isn't any sensitive info on it.

I am using syspass version 1.2.0.18.

Server Details:
Apache 2.4, mariadb 5.5 (mysql), php 5.6

Installed php packages:
php56-bcmath, php56-cli, php56-common, php56-gd, php56-jsonc, php56-ldap, php56-mbstring, php56-mcrypt, php56-mysqlnd, php56-opcache, php56-pdo, php56-pecl-igbinary, php56-pecl-memcached, php56-process, php56-tidy, php56-xml

**Comment by gitforwebwork** [comment]
I found the issue, the key.pem and pubkey.pem files were empty, so I deleted them and they were re-created correctly.

So, as something seems to have gone wrong during the initial setup, I decided to delete syspass and start over.

Now, I can't login after the installation is done. Error message: "Wrong user/pass".

I have tried deleting all syspass files, the mysql user, the database, etc. a few times. Each time the setup worked fine (pem files were created) and the installation completed successfully (after filling out the initial form). I just can't login. I tried it with simple passwords like: admin1234 to make sure it's not some special characters. Any ideas what the issue could be?

**Comment by nuxsmin** [comment]
Fine, I was thinking about that this issue could be related to PKI files wrong set up due to directory permissions.

But now, it's weird the wrong user/pass issue. Did you check out  the webserver error log?

**Comment by gitforwebwork** [comment]
Hi,

there is a warning in the error log... but I don't think it is related to the issue.

"server certificate does NOT include an ID which matches the server name"

I've sent you an email with login details, if you would like to have a look.

**Comment by nuxsmin** [comment]
Let me take a look to your installation and I'll come back with some thoughts.

I'm glad that you like sysPass!

**Comment by nuxsmin** [comment]
PS email received

**Comment by nuxsmin** [comment]
Solved ;)

**Comment by vinod2vino** [comment]
Im also getting same error. Please let me know how to resolve this issue
![screenshot](https://cloud.githubusercontent.com/assets/25821776/23024209/2a35f684-f47f-11e6-8828-07e40f6089de.jpg)

**Comment by Negossia** [comment]
I have the same problem too with the latest version. Please, help.

**Comment by nuxsmin** [comment]
Hi @vinod2vino @Negossia 

Some questions...is there any error in the webserver log?. Could you checkout if there are 2 files named "*.pem" in sysPass config dir?
