### ISSUE TITLE
Assigning LDAP Group to sysPass group

### ISSUE THREAD

**Issue by tumtumdev** [nuxsmin/sysPass#339]
I've tested sysPass and it is pretty good, can't wait for the 1.3 release :)
As commented, the next features: https://github.com/nuxsmin/sysPass/issues/337 would be awesome.

**Feature request:**
- First time masterpassword (save forever, without asking after the password change for a new key LDAP)
- LDAP Import

**New request:**
- Example:
User1 is in AD member of group1 > Add it to the syspass Group 1 and Profile 1 
User2 is in AD member of group2 > Add it to the syspass Group 2 and Profile 2
Is it possible to add multiple AD groups, with auto assigning each AD group to a syspass group + profile?

It will save a lot time in big environments.

**Comment by tumtumdev** [comment]
Maybe it is possible to make it responsive. When adding a new AD Group > Showing next Text field etc. 
In this situation there is no group limit. (In my case 12~ AD groups) I don't know the speed limitations, but a limit for 20 groups should be fine.

**Comment by pgrigoryev** [comment]
that one will be really great to have, actually absence of this feature it's the only thing that stops us from switching to syspass now

**Comment by tumtumdev** [comment]
Is the ldap feature in progress? Still interested in Syspass, not possible to use it now.

**Comment by nuxsmin** [comment]
Hello, the "New" requests have been delayed for the next release (2.2), so currently the first ones are already implemented.

**Comment by nuxsmin** [comment]
Added to roadmap #422
