### ISSUE TITLE
Permissions for config folder

### ISSUE THREAD

**Issue by nfedyashev** [nuxsmin/sysPass#340]
I was trying to install sysPass on my VPS.

When I `chmod 750 config`folder I get this message:

![screen shot 2016-11-23 at 11 06 51 pm](https://cloud.githubusercontent.com/assets/61983/20578794/c0b03926-b1d1-11e6-94b0-3839cbee5b2e.png)

If I try to change it to `777` I get the other:

![screen shot 2016-11-23 at 11 07 48 pm](https://cloud.githubusercontent.com/assets/61983/20578806/cd59e064-b1d1-11e6-985a-07c8bbab6f1b.png)

    syspass master ? ls -al config | grep pem
    -rwxr-x---  1 www-data www-data  900 Nov 23 23:03 key.pem
    -rwxr-x---  1 www-data www-data  276 Nov 23 23:03 pubkey.pem
    syspass master ? ls -al config | grep config
    -rwxr-x---  1 root     root     1425 Nov 23 22:32 config.php.sample

Any advice on how to proceed with it? Thanks

**Comment by nuxsmin** [comment]
Please, make sure that the webserver user is the config directory owner.

**Comment by nfedyashev** [comment]
@nuxsmin it worked! Much appreciated

**Comment by nuxsmin** [comment]
Great! That is a weird issue with filesystem permissions and PHP...
