### ISSUE TITLE
Error log in with LDAP

### ISSUE THREAD

**Issue by marawu** [nuxsmin/sysPass#341]
Hi, i try set LDAP. I add config:

```
  'ldap_ads' => false,
  'ldap_base' => 'dc=example,dc=com',
  'ldap_bindpass' => 'pass',
  'ldap_binduser' => 'uid=ldap-proxy,ou=Users,dc=example,dc=com',
  'ldap_defaultgroup' => 0,
  'ldap_defaultprofile' => 0,
  'ldap_enabled' => true,
  'ldap_group' => 'its.dept',
  'ldap_server' => 'ldap01.example.com',
  'ldap_userattr' => '',
```

but when i login i have "Internal error":

```
154	2016-11-28 12:14:18	Log in		192.168.70.49	(LDAP)
Login Server: ldap01.example.com
Error on saving LDAP user data
153	2016-11-28 12:14:18	newUserLDAP		192.168.70.49	SQLSTATE[HY000]: General error: 1364 Field 'user_mIV' doesn't have a default value(0)
SQL: '
INSERT INTO usrData SET user_name = :name,
user_groupId = :groupId,
user_login = :login,
user_pass = :pass,
user_hashSalt = :hashSalt,
user_email = :email,
user_notes = :notes,
user_profileId = :profileId,
user_isLdap = 1,user_isDisabled = :isDisabled'
```

I need set value user_mIV in mysql? 

Curiously what some users have error "Wrong logn/pass", althouhgt they enter correctly login and password.

mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

**Comment by nuxsmin** [comment]
Hi, that issue is related to MySQL mode, because is was set in STRICT mode.

You can skip this, by issuing this command on you MySQL DB:

<code>ALTER TABLE `syspass`.`usrData` CHANGE COLUMN `user_mIV` `user_mIV` VARBINARY(32) NULL;</code>

I will be fixed in the next release. Sorry for the inconvenience.

**Comment by marawu** [comment]
Yep, it work! Thanks!
