### ISSUE TITLE
Add many users in one account 

### ISSUE THREAD

**Issue by marawu** [nuxsmin/sysPass#342]
Hi, i have service where used many logins and passwords. Can add ability adding many logins and passwords in one account? Thank

PS. sry my english

**Comment by nuxsmin** [comment]
Hi, that feature is not currently listed in the next version roadmap, but I could add it for future versions. 

No worries about english ;)

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Added to roadmap #422
