### ISSUE TITLE
sysPass 2.0 is coming

### ISSUE THREAD

**Issue by nuxsmin** [nuxsmin/sysPass#343]
Hi there!

I'm proudly to announce that the next sysPass release is coming soon, meanwhile you can review it at https://demo-dev.syspass.org/index.php

There are many features that I hope you would find useful like:
* Tags filtering
* Private accounts
* Favorite accounts
* Public links
* Bulk items management
* Syslog integration (local&remote) within CEF format
* Expire passwords date
* DokuWiki integration (through API)
* A new modern UI with Material Design Lite
* And many more that will be added soon

User: demo
Pass: syspass

Please, feel free to give a review about it

**Comment by gabrielsoltz** [comment]
I get this error when trying to access:

There was an error

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON dataparsererror

**Comment by JPSysadmins** [comment]
Earlier today it worked; but now i am seemingly getting the same error as gabrielsoltz. :)

**Comment by nuxsmin** [comment]
Sorry, I've done a mistake when committing some changes to a working on feature. The IDE can upload some changes to a deployment server and this one was selected from a previous session.

It's working fine now.

**Comment by nixjua** [comment]
Could be great if you consider add password & accounts policy for users's  like
Enforce Password History
Maximum Password Age
Minimum Password Length
Passwords Must Meet Complexity Requirements
Account lockout threshold
Account lockout duration

**Comment by MikeyHoef** [comment]
Looks great!!! Especially de Private function! 
When will it be released?

**Comment by nuxsmin** [comment]
It would be released by the end of this month.

**Comment by nuxsmin** [comment]
@nixjua those are very nice features that would be implemented in a later version, because I'm finishing the next version development.

Thanks for the feedback!

**Comment by diginox** [comment]
Any news about this? Maybe a beta version soon?

**Comment by nuxsmin** [comment]
Hi @diginox,
you can get it from the devel branch. I'm currently finishing the development of some features and then I'll release the beta version within all new features implemented.

**Comment by diginox** [comment]
Great, thanks for the info @nuxsmin

**Comment by nixjua** [comment]
Hi,
For the custom fields type password, could you consider add button for the copy to clipboard or view.

**Comment by lukasp2** [comment]
What's the release date? Possible to get Beta Version? :-)

**Comment by nuxsmin** [comment]
It would be available within two weeks.

**Comment by lukasp2** [comment]
any news? :)

**Comment by nuxsmin** [comment]
Hopefully, it will be available (beta version) within hours, because I'm solving an issue with 2FA migration.

**Comment by st3reo** [comment]
hey, I'm also looking forward to the new version, how is it coming along, you seem to have exceeded the projected release date mentioned earlier :)

**Comment by nuxsmin** [comment]
Hey, it has been released in early January and now it's on beta stage, but it would be hopefully RC within days :)

Please take a look at the releases github page and give it a try to get some feedback

**Comment by juanfernandovillahernandez** [comment]
has pensado en una opción para guardar las claves ssh? los pem? los pub? 
tambien alguna opción para importar las contraseñas almacenadas en el navegador?
opción para importar contraseñas de otros gestores de contraseñas?
Yo utilizo SySPass en un entorno de producción y la recomiendo ampliamente! Sigue adelante! excelente trabajo!

**Comment by nuxsmin** [comment]
Buenos apuntes Juan Fernando,

La opción de importar desde el navegador me gusta y el resto ya estarían implementadas, con campos personalizados para lo de ssh y la importación desde keepass.

Gracias por tu apoyo!

**Comment by davidpsc** [comment]
I tried the login with IE 11 but after clicking the "play" button a blank page appears. In Edge the login works as expected. Clearing the IE cache doesn't help.

Can someone confirm this issue or is it working for the other ones with IE 11? (Not that I personally would use IE 11 but one of my colleagues always works with IE and needs to access sysPass...)

**Comment by nuxsmin** [comment]
## **Update**

**sysPass 2.0** will be released at the end of this week. Documentation is already done on https://doc.syspass.org

**Comment by nuxsmin** [comment]
## sysPass 2.0 has been released
Thanks so much for your support!

Any further comment/issue/request could be done as a new issue.
