### ISSUE TITLE
Error 500 when opening website - Centos 7

### ISSUE THREAD

**Issue by kristerger** [nuxsmin/sysPass#344]
Hello

I'm trying to install SysPass over CentOS 7. I copied the files to the server and launched the website on the browser but I get an error 500.

How can I get the details of the error?

Attachment apache log:
`[Mon Nov 28 17:35:39.571311 2016] [core:notice] [pid 13505] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Mon Nov 28 17:35:39.594751 2016] [suexec:notice] [pid 13505] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
[Mon Nov 28 17:35:39.608237 2016] [auth_digest:notice] [pid 13505] AH01757: generating secret for digest authentication ...
[Mon Nov 28 17:35:39.609260 2016] [lbmethod_heartbeat:notice] [pid 13505] AH02282: No slotmem from mod_heartmonitor
[Mon Nov 28 17:35:39.612224 2016] [mpm_prefork:notice] [pid 13505] AH00163: Apache/2.4.6 (CentOS) configured -- resuming normal operations
[Mon Nov 28 17:35:39.612250 2016] [core:notice] [pid 13505] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Nov 28 17:51:06.057292 2016] [autoindex:error] [pid 13515] [client 10.88.24.218:23744] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
[Mon Nov 28 17:54:48.096134 2016] [autoindex:error] [pid 13513] [client 10.88.24.218:23944] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
[Mon Nov 28 17:55:01.135503 2016] [mpm_prefork:notice] [pid 13505] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Nov 28 17:55:02.220303 2016] [core:notice] [pid 14552] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Mon Nov 28 17:55:02.221242 2016] [suexec:notice] [pid 14552] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
[Mon Nov 28 17:55:02.255465 2016] [auth_digest:notice] [pid 14552] AH01757: generating secret for digest authentication ...
[Mon Nov 28 17:55:02.256443 2016] [lbmethod_heartbeat:notice] [pid 14552] AH02282: No slotmem from mod_heartmonitor
[Mon Nov 28 17:55:02.279089 2016] [mpm_prefork:notice] [pid 14552] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
"error_log" 167L, 38423C`

Thank you

**Comment by anburhce** [comment]
did u disable Selinux ?

**Comment by kristerger** [comment]
I forgot, I changed it, I rebooted the system, but it still does not work. The error remains the same... :/

**Comment by nuxsmin** [comment]
Hi @kristerger 

sysPass **only** would sent a 500 error if the session can't be started, that is most likely because the Apache user can't write the session files in its directory (defined in php.ini).

Could you check it?

**Comment by nuxsmin** [comment]
Thanks @anburhce for your support!

**Comment by kristerger** [comment]
My problem is that it's about permissions. What I did first was to change the owner of the root folder to the admin user. There I already let the system see, with permission 777 in the folder let me see but I make an error in the installation which says that the / config folder has to have 750 permission. When I put that folder to 750, I get error 500. How do I solve the problem?

**Comment by nuxsmin** [comment]
sysPass won't need 777 permissions, and the config and backup directories need to be set to 750, otherwise it would be a security risk.

Please, look at your server and webserver logs to find out why Apache isn't be able to access to those directories.

**Comment by Goatmaster** [comment]
Have you changed to owner of the files and folders ?

`chown -R apache:apache /var/www/html`

**Comment by kristerger** [comment]
Thanks solved and closed
