### ISSUE TITLE
Request Account Modification - How it works 

### ISSUE THREAD

**Issue by anburhce** [nuxsmin/sysPass#345]
Hi Ruben,

I just want to know how "Request Account Modification" option works ? 

![syspass](https://cloud.githubusercontent.com/assets/23453745/20794539/cdf360d2-b7f2-11e6-949b-fcc9c02eea0f.PNG)

**Comment by nuxsmin** [comment]
Hi @anburhce ,

that feature only sends an email to the account owner and its last editor noticing that a user sent a request.

**Comment by anburhce** [comment]
Thank you Ruben ,

But looks like it is not working , when i click Send button  .

I created (using anburaj.p user  ) one account test-2  . So when any user request it should send an email  to user  anburaj.p mail id right  ? 

 it is not working . So tried to debug this .

When i click  "Request Account Modification" am seeing this below post request in Apache logs .

172.18.201.202 - - [02/Dec/2016:15:04:14 +0530] "POST /ajax/ajax_getContent.php HTTP/1.1" 200 1655 "http://vault.247-inc.com/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"


but not seeing any POST request for when i click Send button . also i tried to capture packets using tcpdump  . Nothing is reaching the syspass server .


![syspass-1](https://cloud.githubusercontent.com/assets/23453745/20828925/c6901f62-b89f-11e6-93ec-68824e312a5a.PNG)


Please help .

**Comment by nuxsmin** [comment]
I'll take a look at the theme template, because it works on the material theme, so the "send" button could be broken...

**Comment by nuxsmin** [comment]
Can you give a try to the latest release?
