### ISSUE TITLE
Salt/user_pass generation

### ISSUE THREAD

**Issue by MiggyMan** [nuxsmin/sysPass#346]
This might possibly be a cheeky question but I’ll ask anyway :)

I'm looking into the idea of writing a mass-import script to pull in the bulk of our users from ldap into syspass (we have 150 users so enrolling by hand could be "fun")  and looking through the tables this doesn't look too hard but I'm trying to find out how the user_pass, user_mPass and user_hashSalt fields are generated so I can keep user information consistent  and not break syspass, since i'm not a php guy I figured it would be quicker to ask than digging through the code :)

**Comment by nuxsmin** [comment]
Hello,

You wouldn't need to import all the users, because the user will be added when the first login takes place.

In the next version there will be an option to import them all from LDAP, so you can set their group and profile.

**Comment by MiggyMan** [comment]
I understand this however with 150 users and only a singular temporary master password this is far less than useable :D

Is there any eta on the next release ?

**Comment by nuxsmin** [comment]
Sure...it will be available by the end of this month.

**Comment by nuxsmin** [comment]
Actually, that is already implemented in the devel branch, but there are some features that need to be finished before releasing.

**Comment by MiggyMan** [comment]
Nice, since we're only trialing it withing the IT team for now those timescales work quite well :D

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta
