### ISSUE TITLE
ERROR: SMTP connect() failed.

### ISSUE THREAD

**Issue by nixjua** [nuxsmin/sysPass#347]
Hi,
I could't enable the mail option, but if we do test from the server to the smtp server using directs commands works.
also I create a simple php test using  mail($to,$subject,$message, $headers); and its works too

**Comment by madcoda9000** [comment]
Hello,

I've the same error. Im able to send mails with php too. But syspass throws this error:

Error while sending email
ERROR: SMTP connect() failed.

**Comment by nuxsmin** [comment]
It could be a TLS issue, because phpmailer uses TLS if available. Please, check your TLS certificate expiry date.

**Comment by nuxsmin** [comment]
Hi, did you get any progress?
