### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by MikeyHoef** [nuxsmin/sysPass#349]
I just update Syspass to 1.2.0.18, I saw that the the dutch language is added.

After changed it and saved the config. Now everything is in Espanôl... I can't change it back.

The config said:   'sitelang' => 'nl_NL',
So something goes wrong :)

**Comment by nuxsmin** [comment]
Hi @MikeyHoef , take care that you would need to install those locales on your system, otherwise it will be shown in the default language...

If you're using a Debian based distribution, you can set them by issuing: ```dpkg-reconfigure locales```

**Comment by MikeyHoef** [comment]
Solved! Thanks!
