### ISSUE TITLE
Character '&' is showed as '&amp;'

### ISSUE THREAD

**Issue by atahualpaii** [nuxsmin/sysPass#352]
Using syspass 1.2.0.14, a password containing the character '&' it is showed as '&amp;'

sysPass version 	1.2.0.14
Database 	SERVER_VERSION : 5.5.52-0+deb8u1
CLIENT_VERSION : 5.5.52
PHP 	Version: 5.6.24-0+deb8u1
Server 	Apache/2.4.10 (Debian)

**Comment by nuxsmin** [comment]
Right, that is an old issue that has been solved in the latest commit to the master branch. There isn't release yet, but you can push it safely in the meantime a new release is rolled out.
