### ISSUE TITLE
Login faiure after ldap password changes

### ISSUE THREAD

**Issue by MiggyMan** [nuxsmin/sysPass#353]
I've just updated my password in ldap and syspass is no longer letting me log in and is again asking for the master password.

**Comment by nuxsmin** [comment]
Which sysPass version are you running?

**Comment by MiggyMan** [comment]
The 1.2 release.

Is this likely be something that changes with the next release ?

**Comment by nuxsmin** [comment]
But I'd need to know which is the build number. Currently there isn't any related issue with password change, but since a few releases ago, there were some changes to the password hashing algorithm.

**Comment by MiggyMan** [comment]
1.2.0.18

It happily lets me back in if I provide the master password again, but it would be a fair pain to have the do this every day on a company scale :D

**Comment by nuxsmin** [comment]
Great!, the master password needs to be provided when a user's password change is performed, because it has been encrypted with the user's password.

In the next release it won't be needed to provide it on every user's password change, because sysPass will require the previous user's password.

**Comment by nuxsmin** [comment]
https://wiki.syspass.org/syspass/faq-en#is_there_a_master_password_for_each_accountuser

**Comment by MiggyMan** [comment]
Brilliant, Ta :)
