### ISSUE TITLE
Files not encrypted in database?

### ISSUE THREAD

**Issue by ArminXG** [nuxsmin/sysPass#354]
I just started to use the file feature and would like to upload secret key files and certificate files to accounts. But it seems the content of the files are not encrypted in the DB, I can read them.
Shouldn't be that data encrypted as well? Is it planned for a new release?

Thank you.
Armin

**Comment by nuxsmin** [comment]
Right, files aren't being encrypted because it would add some extra load to the server while processing some big files, but it could be possible to implement it for some kind of files (like txt, cert, etc)...

Let me add this feature for the next release ;)

**Comment by nuxsmin** [comment]
Added to roadmap #422
