### ISSUE TITLE
Enhancement: Search Customfields

### ISSUE THREAD

**Issue by JvdW** [nuxsmin/sysPass#355]
I had a quick look through the current open en closed Issues but didn't see what I was looking for. I did a quick test by adding a Customfield to Accounts and trying to use that 'tag' on accounts and then search for the text but it didn't show up. Text from Notes is searched though
Am I correct in that searching CustomFields isn't implemented (yet)?
If so would this be a valid request and doable?

Thanks for a great piece of software,

Joop

**Comment by nuxsmin** [comment]
Hello, custom fields are encrypted so searching for a string within it would require to decrypt every account custom field on each searching.

If you are interested on tagging accounts, the next release will implement that feature...

https://demo-dev.syspass.org

Kind regards
