### ISSUE TITLE
Error on importing csv file

### ISSUE THREAD

**Issue by verob54** [nuxsmin/sysPass#357]
I installed version 1.2.0.19 of "syspass".
When I want to import a csv file with my passwords I have the error:
    - In Firefox: mime type not supported -Please check the file format
     - Under Chrome: Wrong field number (1), please check the CSV format in line 1
My file is in the correct format,  I also tested with a file that works (with 3 lines) find in a forum (same error)
Thank you in advance for your help if you have any ideas!
cordially

**Comment by haken735** [comment]
Hi,

I have the same issue. 
I also tried to format the CSV file like it explained in wiki: account_name;customer;category;url;user;password;notes

bye

**Comment by pgrigoryev** [comment]
same here 
syspass on Debian8
clients: Firefox & Chrome on MacOS

**Comment by Normo** [comment]
Hey,
I've encountered the same issue in the latest 2.0-beta release.

**sysPass environment info:**
- sysPass 2.0.0.17011901-beta
- Server side: Debian 8, Apache 2.4, PHP 5.6, MySQL 5.5
- Clients: Chrome 55, Firefox 50.1, Opera 42

Used CSV data:
`VOIP Account from CSV;Cliente 1;VOIP;http://syspass.org;root;password;Account for VOIP
Google Account from CSV;Google;HTTP;http://syspass.org;root;password;Account for Google
Customer 1 Account from CSV;Customer 1;SSH;http://syspass.org;root;password;Account for Customer 1`

**Comment by nuxsmin** [comment]
Could you test it with the latest 2.0 release?

**Comment by Normo** [comment]
Hello @nuxsmin ,

I've updated to the latest 2.0-beta 2.0.0.17012501. 
The CSV import seems to work now. I was able to import the CSV data which I posted in my previous comment. Accounts, Customers and Categories were created correctly. :+1:

:exclamation: **But:** The passwords were not imported correctly. Unfortunately the password field is empty.  Maybe it is related to  #https://github.com/nuxsmin/sysPass/issues/373 ?

**Comment by nuxsmin** [comment]
It could be, you should let blank the master password field because it would be used when you are importing an XML file that were encrypted within a different master password.

**Comment by Normo** [comment]
I left the master password field blank and imported CSV data again. Passwords were imported correctly. Thank you very much :+1:

(Maybe two separate forms, one for XML and one for CSV, would be better? Or at least make it more obvious that import/master password are only needed for XML import. I know there is a '?' hint, but it should be more clear at the first view.)

**Comment by verob54** [comment]
Hi
I have not tested with the latest 2.0 release but thank you for all these answers
I keep you informed of my future tests!

**Comment by Normo** [comment]
@nuxsmin: Thanks for adjusting the import options layout.

**Comment by nuxsmin** [comment]
You're welcome @Normo 

It was a bit confusing...

**Comment by nuxsmin** [comment]
Hi @verob54 and @haken735, could you try it out at the demo site?. Does it work with sysPass v2?

**Comment by verob54** [comment]
hello
We installed version 2.1 (2.1.0.17022601) and now it works for import csv files!!
Thank you very much for all
With this new version, there are just the translations of menus that are not all in French! Half Spanish and French ;-))

**Comment by nuxsmin** [comment]
That is great @verob54 !!

About the translation issues, I'll take a look because the default language for the untranslated strings is English, so it should display English anyway...

BTW, if you have some time I'd like to invite you to complete the French translation :) on https://poeditor.com/join/project/fmlsBuugyv

Thanks for the feedback!!

**Comment by verob54** [comment]
Here are some screenshots of the French / Spanish translation errors
I do the max to help you with the translation!
![image 050](https://cloud.githubusercontent.com/assets/24718341/23504587/85042092-ff40-11e6-944d-9744928dbac2.jpg)
![image 051](https://cloud.githubusercontent.com/assets/24718341/23504589/868ba084-ff40-11e6-9aa0-b0e4345ae80c.jpg)
![image 052](https://cloud.githubusercontent.com/assets/24718341/23504594/8c16f364-ff40-11e6-8186-9b6636c1e912.jpg)
![image 053](https://cloud.githubusercontent.com/assets/24718341/23504596/8e0f2c2c-ff40-11e6-8e73-ef05f91d55f2.jpg)

**Comment by verob54** [comment]
and there is no more the visual theme: Classic, there is only the theme "material blue"

**Comment by nuxsmin** [comment]
As of 2.0 version, the only visual theme is "material-blue", because I haven't enough time to maintain both themes. The theme color could be changed "easily" by downloading from https://getmdl.io/customize/index.html and adjusting some icons colors.

I think, that I could give more options by changing the theme color (maybe in a near future), but develop an entire theme is a very time consuming task :(
