### ISSUE TITLE
Error creating the group "admin"

### ISSUE THREAD

**Issue by kristerger** [nuxsmin/sysPass#359]
I have a problem when I will install now. I complete all the data to install, and when I give to install I get the following error: Error creating the group "admin"

**Comment by Goatmaster** [comment]
In my Test environment I have the same issue.

**Comment by nuxsmin** [comment]
Hello, is there any error in the webserver log?. Did it happen with the latest version?. Could you tell me which versions are you running on (OS, webserver, database)?

**Comment by nuxsmin** [comment]
Hi, this issue is related with the MySQL password strength, that requires some characters within the password. I has been fixed in the latest release.
Thanks for the feedback!
