### ISSUE TITLE
Uncaught Error: Call to a member function fetchColumn

### ISSUE THREAD

**Issue by f-r-e-e-s-k-y** [nuxsmin/sysPass#361]
Fresh installation of **1.2.0.21**.zip fails on a plain Ubuntu 16.04 + php7 + nginx + maria10 from default repos: 

#0 /var/www/html/syspass/inc/Installer.class.php(187): SP\Installer::setupMySQLDatabase()
#1 /var/www/html/syspass/web/MainC.class.php(305): SP\Installer::install()
#2 /var/www/html/syspass/inc/Init.class.php(432): SP\Controller\MainC->getInstaller()
#3 /var/www/html/syspass/inc/Init.class.php(136): SP\Init::checkInstalled()
#4 /var/www/html/syspass/inc/Base.php(45): SP\Init::start()
#5 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#6 {main}
  thrown in /var/www/html/syspass/inc/Installer.class.php on line 254" while reading response header from upstream, client: 10.*.*.*, server: _, request: "POST /syspass/index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "web.local", referrer: "https://web.local/syspass/index.php"
2017/01/09 17:10:16 [error] 15657#15657: *236 FastCGI sent in stderr: "PHP message: PHP Fatal error:  **Uncaught Error: Call to a member function fetchColumn() on boolean in /var/www/html/syspass/inc/Installer.class.php:254**

**Comment by MartinHannemann** [comment]
ubuntu 16.04, apache, php7, mysql. Same error here.

[:error] [pid 28262] [client 10.100.10.60:61784] PHP Fatal error:  Uncaught Error: Call to a member function fetchColumn() on boolean in /var/www/html/sysPass-1.2.0.21/inc/Installer.class.php:254\nStack trace:\n#0 /var/www/html/sysPass-1.2.0.21/inc/Installer.class.php(187): SP\\Installer::setupMySQLDatabase()\n#1 /var/www/html/sysPass-1.2.0.21/web/MainC.class.php(305): SP\\Installer::install()\n#2 /var/www/html/sysPass-1.2.0.21/inc/Init.class.php(432): SP\\Controller\\MainC->getInstaller()\n#3 /var/www/html/sysPass-1.2.0.21/inc/Init.class.php(136): SP\\Init::checkInstalled()\n#4 /var/www/html/sysPass-1.2.0.21/inc/Base.php(45): SP\\Init::start()\n#5 /var/www/html/sysPass-1.2.0.21/index.php(28): require('/var/www/html/s...')\n#6 {main}\n  thrown in /var/www/html/sysPass-1.2.0.21/inc/Installer.class.php on line 254, referer: http://**/syspass/index.php

**Comment by f-r-e-e-s-k-y** [comment]
It seems to be related to the "Hosting Mode" switch at the bottom of the setup page. This switch is disabled per default here. If this switch is activated, the db setup runs thru sucessfully and I can log in. But I still have no clue what "Hosting Mode" even means...

![hostingmodesw](https://cloud.githubusercontent.com/assets/11278933/21954911/491a3cd4-da5f-11e6-9a2b-56024a04f6a2.jpg)

In the logs I also see this after successful installation:

#6 {main}
  thrown in /var/www/html/syspass/inc/Installer.class.php on line 254" while reading response header from upstream, ...
2017/01/14 13:45:30 **[error] 1237#1237: *1944 FastCGI sent in stderr: "PHP message: Action: New Group -- Description: Group : Admins**
PHP message: Action: New Profile -- Description: Profile: Admin
PHP message: Action: New User -- Description: User: Admin (admin)

**Comment by nuxsmin** [comment]
The hosting mode doesn't perform some DB checks, so the error causing function isn't triggered.

Basically, hosting mode doesn't check neither if the user exist nor creates the database, it only uses the provided user and database to create the db structure:

```
        if (!self::$_isHostingMode) {
            self::setDbpass(Util::generate_random_bytes(16, true));
            self::setDbuser(substr('sp_' . self::$_username, 0, 16));
            // Comprobar si el usuario sumistrado existe
            $query = 'SELECT COUNT(*) FROM mysql.user WHERE user=\'sp_' . self::$_username . '\' AND host=\'' . self::getAdminHost() . '\'';
            try {
                // Si no existe el usuario o es distinto del anterior, se intenta crear
                if ((int)self::$_dbc->query($query)->fetchColumn() === 0
                    || self::$_dbuser != Config::getValue('dbuser')
                ) {
                    self::createDBUser();
                }
            } catch (\PDOException $e) {
                throw new SPException(SPException::SP_CRITICAL
                    , _('No es posible comprobar el usuario de sysPass') . ' (' . self::$_username . ')'
                    , _('Compruebe los permisos del usuario de conexión a la BD'));
            }
        }
```
Those error messages are normal, because the installer logs the installation messages to the error log. This is done so because the install process could fail creating the DB, so the messages couldn't be stored there.

**Comment by nuxsmin** [comment]
The hosting mode has been implemented because the hosting providers doesn't allow to query the mysql.user table (it holds all hosting user's data...) on a shared hosting. Is it your case?

**Comment by f-r-e-e-s-k-y** [comment]
No it is a local vm with default settings running on an Ubuntu KVM host. With default I mean common security practices applied, so it matches hosted setups in some points:

- mysql_secure_installation invoked after installation, with anon user removed, root password set and test db removed
- dedicated user and db for sysPass created
- dedicated sysPass user has no global privileges set but all privileges on the sysPass db

So you are correct that the sysPass user can not access "mysql.user". I tried to set global privileges for the sysPass user to:

GRANT SHOW DATABASES, SHOW VIEW, SELECT, PROCESS, EXECUTE  ON *.* TO 'syspass'@'localhost';

And ran the setup again  ("Hosting Mode" switch off). This resulted in: 

![sypassbug02](https://cloud.githubusercontent.com/assets/11278933/21955879/64d7f078-da74-11e6-8813-3efa4881f5b1.jpg)


2017/01/14 16:06:07 [error] 1237#1237: *2266 FastCGI sent in stderr: "PHP message: Exception: SQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES)
PHP message: Action: addGroup -- Description: SQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES)(0);;SQL: INSERT INTO usrGroups SET usergroup_name = :name, usergroup_description = :description
PHP message: SQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES)(0);;SQL: INSERT INTO usrGroups SET usergroup_name = :name, usergroup_description = :description" while reading response header from upstream, ... referrer: "https://web.localdomain.local/syspass/index.php"

So the setup tries to connect with sp_admin@localhost and not  the entered sysPass@localhost -
since sp_admin@localhost don´t exists it fails.

I can try the setup with "root" user (has all global privileges on the local mariadb server) and see if this works.

**Comment by nuxsmin** [comment]
The sysPass db user sp_admin is created with the supplied admin user, so that user should have admin rights over MySQL rdbms. After that, the sysPass db user (sp_admin) is used to create the whole db structure and initialization steps..

That is done so to facilitate the installation task to the end user, so he wouldn't need to create neither the user nor the database, and it also setups a generated random password for the sysPass db user.

**Comment by nuxsmin** [comment]
So, if the sysPass@localhost user cannot create users, the installation will fail everytime, so you would need to choose the hosting mode.

**Comment by f-r-e-e-s-k-y** [comment]
I see, so a workaround could be either to give some feedback to users on errors with the default hosted mode off (I get a blank screen) or set hosted mode on as default?

**Comment by nuxsmin** [comment]
Sure, the installation process has been improved in the latest 2.0-beta version, which uses Ajax and the errors are better logged on.

You could give a try to it and take a look to the new features ;)

**Comment by f-r-e-e-s-k-y** [comment]
Sure I´ll give v2 a try soon. Thanks for your feedback.
