### ISSUE TITLE
Password copy to clipboard error when password contains double quote.

### ISSUE THREAD

**Issue by ArminXG** [nuxsmin/sysPass#362]
Using latest syspass (1.2.0.21), the function of copy password to clipboard does not work correctly. If the password contains a double quote ("), the copy in the clipboard will have '&quote;' instead.
If you use function view password and then copy password to clipboard, it is correct.

**Comment by nuxsmin** [comment]
This has been fixed in the latest release.

Thanks for the feedback!

**Comment by ArminXG** [comment]
With latest release you mean the 2.0 beta? I would like not to move to 2.0 yet and stay with 2.1 for some time. Is there is fix available or can you point me to the need change? I can then path it manually.

Thank you!

**Comment by nuxsmin** [comment]
After analyzing the fixing path, unfortunately the fix would broke some other stuff because it involves some fixes in different modules, so it won't be fixed in 1.2 release.

Please upgrade to 2.0...there are several improvements, bugfixes and a security CVE solved.

Regards
