### ISSUE TITLE
Active Directory Auth not working

### ISSUE THREAD

**Issue by jlmacho** [nuxsmin/sysPass#363]
The ldap test works fine but when trying to log into syspass with AD creds I get the error below. Thanks for the help.

My config.php

'ldap_ads' => true,
'ldap_base' => 'DC=example,DC=net',
'ldap_bindpass' => 'somepassword',
'ldap_binduser' => 'ldapuser',
'ldap_defaultgroup' => 2,
'ldap_defaultprofile' => 2,
'ldap_enabled' => true,
'ldap_group' => 'group',
'ldap_server' => 'ldaps://usingIPhere',

Error Im seeing
Error al buscar RDN de grupo
Grupo: (cn=group)
LDAP ERROR: Operations error (1)
LDAP FILTER: (cn=group)

I had version 1.2.0.11 but I also have version 1.2.0.21 and also tested version 1.2.0.13 and it doesn't work.

**Comment by nuxsmin** [comment]
Can you try it out with the latest 2.0-beta release?

**Comment by nuxsmin** [comment]
Ummm, it could be an SSL issue, because you would need the public an CA certs to connect to the LDAP server.

**Comment by haken735** [comment]
hi,

did you try with the port number in the ip field ?  'ldap_server' => 'ldaps://usingIPhere**:port**',
I'm using the 1.2 version and i have to pre-register my user in syspass before they can be identified.
