### ISSUE TITLE
checkHashPass() is vulnerable to timing attacks

### ISSUE THREAD

**Issue by EdOverflow** [nuxsmin/sysPass#364]
The following line in `checkHashPass()` is vulnerable to timing attacks:

~~~
return $testHash == $validHash;
~~~

Link to source code: https://github.com/nuxsmin/sysPass/blob/master/inc/Crypt.class.php#L134

The `==` operation performs a byte-by-byte comparison, which terminates as soon as two characters do not match.

You can fix this by using the `hash_equals()` function: https://secure.php.net/manual/en/function.hash-equals.php

**Comment by nuxsmin** [comment]
You're right, and has been fixed in the latest release.

Thanks for the notice!
