### ISSUE TITLE
Offline access

### ISSUE THREAD

**Issue by AshHaque** [nuxsmin/sysPass#365]
Hi,

Is there any way to decrypt passwords from xml file? 

Cheers,
Ash

**Comment by AshHaque** [comment]
Or is there any way to export user specific accounts like user will be able to export those accounts in which he has access to.?

Thanks very much for this fantastic tool.


Cheers,
Ash

**Comment by nuxsmin** [comment]
Hi, 
regarding your points:

* Yes, the encrypted XML passwords can be decrypted (AES-256) by using the original master password and the IV provided. They are encoded in base64.
* Currently there is no way to export the accounts visible to the user. It would be a feature in the next release.

Thanks for your support!
Cheers

**Comment by AshHaque** [comment]
Thanks for prompt reply.

What's the estimated time for next release? I am eagerly waiting to have it.


cheers,
Ash

**Comment by nuxsmin** [comment]
Yesterday, it has been released as beta :) 

BTW, you can take a look at https://demo-dev.syspass.org
