### ISSUE TITLE
sysPass 2.0 beta throws the following error:

### ISSUE THREAD

**Issue by anogues** [nuxsmin/sysPass#366]
Admin group creation failed, please warn the developer :)

And the installation does not progress.

I've checked apache logs and some errors are thrown there:

[Thu Jan 12 14:17:04 2017] [error] [client 10.150.125.76] Exception: SQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES) - 1045, referer: http://XXXXXXX:8888/index.php
[Thu Jan 12 14:17:04 2017] [error] [client 10.150.125.76] #0  SP\\Storage\\DB->prepareQueryData() called at [/var/www/syspassn/inc/SP/Storage/DB.class.php:145]\n#1  SP\\Storage\\DB->doQuery() called at [/var/www/syspassn/inc/SP/Storage/DB.class.php:330]\n#2  SP\\Storage\\DB::getQuery() called at [/var/www/syspassn/inc/SP/Mgmt/Groups/Group.class.php:104]\n#3  SP\\Mgmt\\Groups\\Group->checkDuplicatedOnAdd() called at [/var/www/syspassn/inc/SP/Mgmt/Groups/Group.class.php:55]\n#4  SP\\Mgmt\\Groups\\Group->add() called at [/var/www/syspassn/inc/SP/Core/Installer.class.php:415]\n#5  SP\\Core\\Installer->createAdminAccount() called at [/var/www/syspassn/inc/SP/Core/Installer.class.php:114]\n#6  SP\\Core\\Installer->install() called at [/var/www/syspassn/ajax/ajax_install.php:55]\n, referer: http://XXXXXXXX:8888/index.php
[Thu Jan 12 14:17:04 2017] [error] [client 10.150.125.76] Action: checkDuplicatedOnAdd -- Description: error\nSQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES)(0) -- Details: SQL: SELECT usergroup_name FROM usrGroups WHERE UPPER(usergroup_name) = ?, referer: http://XXXXXXX:8888/index.php
[Thu Jan 12 14:17:04 2017] [error] [client 10.150.125.76] error\nSQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES)(0), referer: http://XXXXXX:8888/index.php
[Thu Jan 12 14:17:04 2017] [error] [client 10.150.125.76] SQL: SELECT usergroup_name FROM usrGroups WHERE UPPER(usergroup_name) = ?, referer: http://XXXXXX:8888/index.php

Thing something is wrong because it is trying to connect to the db with the sp_admin user where I specified the syspass user.

Do you know why?

BR,
Albert.

**Comment by nuxsmin** [comment]
That is so, because the sysPass db user is prefixed by sp_ to avoid username collision.

That error is because the password doesn't meet the strength requirements, so it fails.

Let me find out a solution.

Thanks for the feedback!

**Comment by anogues** [comment]
You're welcome!

**Comment by anogues** [comment]
To be hones, i have been able to finish the installation after a few retries with the same user :)

**Comment by nuxsmin** [comment]
Sure, every time you retry it , the admin pass is regenerated so if it meets the strength, you're lucky...

**Comment by nuxsmin** [comment]
This should be solved in the latest commit

**Comment by anogues** [comment]
Gracias!

Lo actualizo luego y te digo.

Salu2!

**Comment by nuxsmin** [comment]
Perfecto, espero que funcione ;)

**Comment by anogues** [comment]
Funciona :)

**Comment by nuxsmin** [comment]
Me alegro, gracias por informar!

**Comment by nuxsmin** [comment]
Ten en cuenta de estar actualizado a la última release, ya que estoy solventando algunos errores detectados.
