### ISSUE TITLE
Time zone issue

### ISSUE THREAD

**Issue by AshHaque** [nuxsmin/sysPass#367]
Hi,

My system is running in GMT+10 zone (Aus/Syd). But when I created temporary master password it's creating it for GMT+0.

How can I change the timezone for application? 2FA is also failing. I think may be for this timezone issue.

Thanks,
Ash

**Comment by nuxsmin** [comment]
Hi @AshHaque 

could comment this line https://github.com/nuxsmin/sysPass/blob/master/inc/Init.class.php#L96 ?

Kind regards.

**Comment by AshHaque** [comment]
Thank you very much for your quick response.

I comment out that line but didn't work for me. later I changed it to my timezone like 

date_default_timezone_set('Australia/Sydney');

And it worked.


Regards,
Ash

**Comment by AshHaque** [comment]
And 2FA is also working now.

**Comment by nuxsmin** [comment]
Great, but that option could be changed in the php.ini file, so any PHP application would use the right timezone.

**Comment by nuxsmin** [comment]
Solved
