### ISSUE TITLE
sysPass 2.0 Beta: Changing configuration

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#368]
Hi,

when I change any configurations I can't save them:

> An error has occurred
> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON dataparsererror

What is wrong?

Thank you & Br,
Lukas

**Comment by nuxsmin** [comment]
Hi, that issue has been solved in the latest commit.

Kind regards

**Comment by lukasp2** [comment]
In 2.0.0.17011601-beta ?

**Comment by nuxsmin** [comment]
I've just tagged it as a release, because it was only committed instead

**Comment by lukasp2** [comment]
Looks good, it's working! Thank you.
