### ISSUE TITLE
UTF-8 clipboard encoding

### ISSUE THREAD

**Issue by alexanderbuhler** [nuxsmin/sysPass#369]
Hey there, me again :-)

Got a minor bug here. When you copy passwords to clipboard which contain UTF-8 chars like ```ü``` they go into clipboard as ```&uuml;```. Nothing critical, might be just a line of code.

Best
Alex

**Comment by nuxsmin** [comment]
Hi, are you running sysPass 1.2?

**Comment by alexanderbuhler** [comment]
Yep!

**Comment by davidpsc** [comment]
I can also confirm this bug but it just seem to appear when clicking the "quick actions" clipboard button, it works correctly for me when displaying username and password first and then clicking the "copy password" button. I'm also using version 1.2.

**Comment by nuxsmin** [comment]
Solved in 2.0

Thanks for the feedback!
