### ISSUE TITLE
The Keepass import dons work in beta 2.0

### ISSUE THREAD

**Issue by camillagds** [nuxsmin/sysPass#371]
I try to import import a Keepass XML (2.0) in the sysPass and the entrys are created but the password of all are empty.

In the 1.x version works fine.

**Comment by nuxsmin** [comment]
Hi, which version of keepass are you using?

**Comment by lukasp2** [comment]
Can you tell me please, how I can exported data from 1.2 import to 2.0 ?

**Comment by nuxsmin** [comment]
Hello @lukasp2 
the 2.0 upgrade process is taken in-place, so you only need to put the config.php file in the config directory and then point your browser to the sysPass URL.
Let me know if you have any issue

**Comment by camillagds** [comment]
My version of XML is " KeePassXML (2.x).
The program is KeePass 2.34

**Comment by lukasp2** [comment]
@nuxsmin 
Great, it works for me!

**Comment by nuxsmin** [comment]
@lukasp2 that's nice!. Please take into account to keep updated with the latest 2.0-beta release:
https://github.com/nuxsmin/sysPass/releases/tag/2.0.0.17011901-beta

Thanks for the feedback!

**Comment by nuxsmin** [comment]
@camillagds I'll take a look to that version's XML format

**Comment by nuxsmin** [comment]
@camillagds I've done some tests and it works fine, did you see any error int the event log?. Can you try out with the latest 2.0-beta release?

**Comment by lukasp2** [comment]
@nuxsmin thanks for your Info. I run the update and getting this error:

Fatal error: Uncaught Error: Call to undefined function SP\Http\apache_request_headers() in /var/www/html/sysPass_v2/inc/SP/Http/Request.class.php:168 Stack trace: #0 /var/www/html/sysPass_v2/inc/SP/Http/Request.class.php(151): SP\Http\Request::getApacheHeaders() #1 /var/www/html/sysPass_v2/inc/SP/Http/Request.class.php(140): SP\Http\Request::getRequestHeaders('Cache-Control') #2 /var/www/html/sysPass_v2/inc/SP/Core/Init.class.php(127): SP\Http\Request::checkReload() #3 /var/www/html/sysPass_v2/inc/Base.php(108): SP\Core\Init::start() #4 /var/www/html/sysPass_v2/index.php(31): require('/var/www/html/s...') #5 {main} thrown in /var/www/html/sysPass_v2/inc/SP/Http/Request.class.php on line 168

**Comment by nuxsmin** [comment]
Sorry, I've done a mistake when checking the apache function. I've just pushed it to the devel branch

**Comment by lukasp2** [comment]
Thank you, I need to change the PHP file to get it working ?

**Comment by nuxsmin** [comment]
Right, you can safely replace the whole sysPass directory except the config folder.

**Comment by lukasp2** [comment]
thank you, I will do it later. I'm new to GitHub, also  noob :-)

**Comment by nuxsmin** [comment]
Fine, you can download the zip file and uncompress it...

https://github.com/nuxsmin/sysPass/archive/devel.zip

**Comment by camillagds** [comment]
@nuxsmin Not have nothing in the logs or debug. =/ 
I paste the print screen.

I'll try test in the last version.

![image](https://cloud.githubusercontent.com/assets/6138714/22112063/cb522274-de48-11e6-9327-a6701502c0b7.png)

**Comment by camillagds** [comment]
Doing a new instalation, in the login screen I have this error on print.

The logs:

[Thu Jan 19 13:21:49.821070 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Exception: SQLSTATE[HY000] [1049] Unknown database 'syspass' - 1049
[Thu Jan 19 13:21:49.821095 2017] [:error] [pid 9228] [client 10.100.29.42:59228] #0  SP\\Storage\\DB->prepareQueryData() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Storage/DB.class.php:145]\n#1  SP\\Storage\\DB->doQuery() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Storage/DB.class.php:331]\n#2  SP\\Storage\\DB::getQuery() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Config/ConfigDB.class.php:138]\n#3  SP\\Config\\ConfigDB::setValue() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Config/Config.class.php:134]\n#4  SP\\Config\\Config::backupToDB() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Config/Config.class.php:110]\n#5  SP\\Config\\Config::saveConfig() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Storage/MySQLHandler.class.php:145]\n#6  SP\\Storage\\MySQLHandler->getConnection() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Storage/DBUtil.class.php:78]\n#7  SP\\Storage\\DBUtil::checkDatabaseExist() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Core/Init.class.php:142]\n#8  SP\\Core\\Init::start() called at [/opt/sysPass-2.0.0.17011901-beta/inc/Base.php:108]\n#9  require(/opt/sysPass-2.0.0.17011901-beta/inc/Base.php) called at [/opt/sysPass-2.0.0.17011901-beta/index.php:31]\n
[Thu Jan 19 13:21:49.821540 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Action: setValue -- Description: SQLSTATE[HY000] [1049] Unknown database 'syspass' (0) -- Details: SQL : INSERT INTO config SET config_parameter = :param,config_value = :value ON DUPLICATE KEY UPDATE config_value = :valuedup
[Thu Jan 19 13:21:49.821556 2017] [:error] [pid 9228] [client 10.100.29.42:59228] SQLSTATE[HY000] [1049] Unknown database 'syspass' (0)
[Thu Jan 19 13:21:49.821570 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 1: SP\\Storage\\DB\\logDBException
[Thu Jan 19 13:21:49.821574 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 2: SP\\Storage\\DB\\getQuery
[Thu Jan 19 13:21:49.821577 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 3: SP\\Config\\ConfigDB\\setValue
[Thu Jan 19 13:21:49.821580 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 4: SP\\Config\\Config\\backupToDB
[Thu Jan 19 13:21:49.821583 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 5: SP\\Config\\Config\\saveConfig
[Thu Jan 19 13:21:49.821586 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 6: SP\\Storage\\MySQLHandler\\getConnection
[Thu Jan 19 13:21:49.821589 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 7: SP\\Storage\\DBUtil\\checkDatabaseExist
[Thu Jan 19 13:21:49.821591 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 8: SP\\Core\\Init\\start
[Thu Jan 19 13:21:49.821594 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 9: \\require
[Thu Jan 19 13:21:49.821602 2017] [:error] [pid 9228] [client 10.100.29.42:59228] SQL : INSERT INTO config SET config_parameter = :param,config_value = :value ON DUPLICATE KEY UPDATE config_value = :valuedup
[Thu Jan 19 13:21:49.821791 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Exception: SQLSTATE[HY000] [1049] Unknown database 'syspass' - 1049
[Thu Jan 19 13:21:49.821801 2017] [:error] [pid 9228] [client 10.100.29.42:59228] #0  SP\\Storage\\DB->prepareQueryData() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Storage/DB.class.php:145]\n#1  SP\\Storage\\DB->doQuery() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Storage/DB.class.php:331]\n#2  SP\\Storage\\DB::getQuery() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Config/ConfigDB.class.php:138]\n#3  SP\\Config\\ConfigDB::setValue() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Config/Config.class.php:135]\n#4  SP\\Config\\Config::backupToDB() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Config/Config.class.php:110]\n#5  SP\\Config\\Config::saveConfig() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Storage/MySQLHandler.class.php:145]\n#6  SP\\Storage\\MySQLHandler->getConnection() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Storage/DBUtil.class.php:78]\n#7  SP\\Storage\\DBUtil::checkDatabaseExist() called at [/opt/sysPass-2.0.0.17011901-beta/inc/SP/Core/Init.class.php:142]\n#8  SP\\Core\\Init::start() called at [/opt/sysPass-2.0.0.17011901-beta/inc/Base.php:108]\n#9  require(/opt/sysPass-2.0.0.17011901-beta/inc/Base.php) called at [/opt/sysPass-2.0.0.17011901-beta/index.php:31]\n
[Thu Jan 19 13:21:49.822030 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Action: setValue -- Description: SQLSTATE[HY000] [1049] Unknown database 'syspass' (0) -- Details: SQL : INSERT INTO config SET config_parameter = :param,config_value = :value ON DUPLICATE KEY UPDATE config_value = :valuedup
[Thu Jan 19 13:21:49.822045 2017] [:error] [pid 9228] [client 10.100.29.42:59228] SQLSTATE[HY000] [1049] Unknown database 'syspass' (0)
[Thu Jan 19 13:21:49.822062 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 1: SP\\Storage\\DB\\logDBException
[Thu Jan 19 13:21:49.822068 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 2: SP\\Storage\\DB\\getQuery
[Thu Jan 19 13:21:49.822074 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 3: SP\\Config\\ConfigDB\\setValue
[Thu Jan 19 13:21:49.822079 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 4: SP\\Config\\Config\\backupToDB
[Thu Jan 19 13:21:49.822085 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 5: SP\\Config\\Config\\saveConfig
[Thu Jan 19 13:21:49.822090 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 6: SP\\Storage\\MySQLHandler\\getConnection
[Thu Jan 19 13:21:49.822096 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 7: SP\\Storage\\DBUtil\\checkDatabaseExist
[Thu Jan 19 13:21:49.822101 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 8: SP\\Core\\Init\\start
[Thu Jan 19 13:21:49.822107 2017] [:error] [pid 9228] [client 10.100.29.42:59228] Caller 9: \\require
[Thu Jan 19 13:21:49.822119 2017] [:error] [pid 9228] [client 10.100.29.42:59228] SQL : INSERT INTO config SET config_parameter = :param,config_value = :value ON DUPLICATE KEY UPDATE config_value = :valuedup
[Thu Jan 19 13:21:49.822150 2017] [:error] [pid 9228] [client 10.100.29.42:59228] initError
[Thu Jan 19 13:23:31.655714 2017] [:error] [pid 9227] [client 10.100.29.42:59340] Action: Configuraci\xc3\xb3n -- Description: Modificar configuraci\xc3\xb3n -- Details: , referer: http://syspass.7comm.corp/
[Thu Jan 19 13:23:31.680260 2017] [:error] [pid 9227] [client 10.100.29.42:59340] Action: Configuraci\xc3\xb3n -- Description: Modificar configuraci\xc3\xb3n -- Details: Par\xc3\xa1metro : version\nValor : 20017011901, referer: http://syspass.7comm.corp/
[Thu Jan 19 13:23:31.682959 2017] [:error] [pid 9227] [client 10.100.29.42:59340] Action: Configuraci\xc3\xb3n -- Description: Modificar configuraci\xc3\xb3n -- Details: Par\xc3\xa1metro : config_backup, referer: http://syspass.7comm.corp/
[Thu Jan 19 13:23:31.683456 2017] [:error] [pid 9227] [client 10.100.29.42:59340] Action: Configuraci\xc3\xb3n -- Description: Modificar configuraci\xc3\xb3n -- Details: Par\xc3\xa1metro : config_backupdate\nValor : 1484839411, referer: http://syspass.7comm.corp/
[Thu Jan 19 13:23:42.701356 2017] [:error] [pid 9224] [client 10.100.29.42:59349] initError, referer: http://syspass.7comm.corp/index.php
[Thu Jan 19 13:24:16.775331 2017] [mpm_prefork:notice] [pid 32493] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Thu Jan 19 13:24:16.855097 2017] [mpm_prefork:notice] [pid 32493] AH00163: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Thu Jan 19 13:24:16.855115 2017] [core:notice] [pid 32493] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 19 13:24:25.175765 2017] [:error] [pid 9553] [client 10.100.29.42:59382] initError, referer: http://syspass.7comm.corp/index.php

![image](https://cloud.githubusercontent.com/assets/6138714/22112731/2a64c742-de4b-11e6-8885-913b39eb5f40.png)

**Comment by nuxsmin** [comment]
Hi, you would need to reload the page. That is because the JS files has been changed.

**Comment by camillagds** [comment]
Done.

I imported the XML off Keepass and click in show password and i have the same problem.

![image](https://cloud.githubusercontent.com/assets/6138714/22119542/197ffd94-de63-11e6-9f07-8c2f251e02ca.png)

**Comment by nuxsmin** [comment]
Ummm, did you reimported the accounts after the update?. 

The latest commits from the devel branch would solved that issue, but you would need to import the file again.

**Comment by camillagds** [comment]
I dont update. I drop the database, delete the folder of syspass and install again from zero.
After the instalation, I import the xml.

I've downloaded this verion: sysPass-2.0.0.17011901-beta

**Comment by camillagds** [comment]
I will install the devel branch now ^^

**Comment by camillagds** [comment]
@nuxsmin The devel Branch worked!

**Comment by nuxsmin** [comment]
Great. Every a few commits I release a new tag, that is a release, but I haven't released it yet because I'm working on improving the import process, because this module is the last before publishing the RC.

**Comment by nuxsmin** [comment]
Solved
