### ISSUE TITLE
Import fails due to Duplicated customer error

### ISSUE THREAD

**Issue by anogues** [nuxsmin/sysPass#372]
Hello.

If we have several accounts with the same customer it fails to import the entire list of accounts. porobably category has the same error.

This worked fine in version 1.x. I understand that if category exists it should grab the id and use that one, but not attempting to create it again from scratch.

Can you have a look please?

Albert.

**Comment by nuxsmin** [comment]
Hello, did you mean a CSV import?

**Comment by anogues** [comment]
Yes, csv import

**Comment by nuxsmin** [comment]
Just pushed!! It was done for XML import, but I missed to apply on CSV :(

**Comment by anogues** [comment]
haha you're the master!

**Comment by anogues** [comment]
Uhm another error now:

js.php?g=1&v=3644a68…:77 undefined<p>SyntaxError: Failed to execute 'open' on 'XMLHttpRequest': Invalid URLerror</p>
error @ js.php?g=1&v=3644a68…:77
js.php?g=1&v=3644a68…:68 Uncaught TypeError: Cannot read property 'complete' of undefined
    at Object.complete (js.php?g=1&v=3644a68…:68)
    at j (js.php?v=3644a68…:3)
    at Object.fireWith (js.php?v=3644a68…:3)
    at x (js.php?v=3644a68…:5)
    at Function.ajax (js.php?v=3644a68…:5)
    at Object.getActionCall (js.php?g=1&v=3644a68…:67)
    at x (js.php?g=1&v=3644a68…:80)
    at js.php?g=1&v=3644a68…:91
    at Object.sysPass.Main (js.php?g=1&v=3644a68…:91)
    at HTMLDocument.<anonymous> (js.php?g=1&v=3644a68…:2)

**Comment by anogues** [comment]
[Wed Jan 18 11:13:58 2017] [error] [client 10.150.125.76] File does not exist: /var/www/syspassn/js/zxcvbn.js.map

also as well

**Comment by nuxsmin** [comment]
Umm, it's weird, because that file (last one) is not called anywhere....

Are those errors shown during the import?. Is there any message in the event log?

**Comment by anogues** [comment]
No even when loggint to the app.

Maybe it is a change not linked to the csv, change from a day or two ago

access_log:

10.150.125.76 - - [18/Jan/2017:12:10:59 +0000] "GET / HTTP/1.1" 200 7141 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
10.150.125.76 - - [18/Jan/2017:12:10:59 +0000] "GET /inc/themes/material-blue/css/Roboto_400.woff2 HTTP/1.1" 200 14584 "http://ledcb580:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
10.150.125.76 - - [18/Jan/2017:12:10:59 +0000] "GET /css/fonts/MaterialIcons-Regular.woff2 HTTP/1.1" 200 44300 "http://ledcb580:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
10.150.125.76 - - [18/Jan/2017:12:10:59 +0000] "GET /js/zxcvbn.min.js HTTP/1.1" 200 821322 "http://ledcb580:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
10.150.125.76 - - [18/Jan/2017:12:12:34 +0000] "POST / HTTP/1.1" 200 - "http://ledcb580:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
10.150.125.76 - - [18/Jan/2017:12:12:34 +0000] "GET /favicon.ico HTTP/1.1" 404 298 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"


and error_log

[Wed Jan 18 12:10:51 2017] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jan 18 12:10:51 2017] [notice] Digest: generating secret for digest authentication ...
[Wed Jan 18 12:10:51 2017] [notice] Digest: done
[Wed Jan 18 12:10:51 2017] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.6.29 configured -- resuming normal operations
[Wed Jan 18 12:10:59 2017] [error] [client 10.150.125.76] PHP Warning:  date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/syspassn/inc/SP/Core/Init.class.php on line 81
[Wed Jan 18 12:12:34 2017] [error] [client 10.150.125.76] File does not exist: /var/www/syspassn/favicon.ico

Now i can't see any window

**Comment by anogues** [comment]
I see it very weird, because the lower bar says debug mode is ON, where when i chech the config file the debug mode is disabled

Also there are errors loading the page:

undefined<p>SyntaxError: Failed to execute 'open' on 'XMLHttpRequest': Invalid URLerror</p>
error @ js.php?g=1&v=3644a68…:77
js.php?g=1&v=3644a68…:68 Uncaught TypeError: Cannot read property 'complete' of undefined
    at Object.complete (js.php?g=1&v=3644a68…:68)
    at j (js.php?v=3644a68…:3)
    at Object.fireWith (js.php?v=3644a68…:3)
    at x (js.php?v=3644a68…:5)
    at Function.ajax (js.php?v=3644a68…:5)
    at Object.getActionCall (js.php?g=1&v=3644a68…:67)
    at x (js.php?g=1&v=3644a68…:80)
    at js.php?g=1&v=3644a68…:91
    at Object.sysPass.Main (js.php?g=1&v=3644a68…:91)
    at HTMLDocument.<anonymous> (js.php?g=1&v=3644a68…:2)

**Comment by anogues** [comment]
In the login screen i get that message as well: undefined

SyntaxError: An invalid or illegal string was specifiederror

Think problem may be due to some javascript not working fine.

**Comment by anogues** [comment]
In fact the version from 5 days ago, in the dev branch it works fine all but the csv import, but in the last two days versions some changes have been made that are failing my installation

**Comment by nuxsmin** [comment]
Can you disable the debug mode in the Base.php file?

**Comment by nuxsmin** [comment]
The debug mode is set for all the tests done by myself, so it could be related to any kind of config in your environment.

**Comment by anogues** [comment]
Nada, sigue sin ir:

undefined
SyntaxError: Failed to execute 'open' on 'XMLHttpRequest': Invalid URLerror

Y cuando me logueo, aparece la página entera en blanco.

He borrado toda la cache del navegador y sigue igual. Lo raro es que con la versión anterior (he probado de hacer rollback) funciona...

**Comment by nuxsmin** [comment]
Es raro, ya que lo tengo actualmente funcionando en un entorno "mediano" (~100 usuarios).

La configuración es una Debian 8, Apache/2.4.10 y MySQL

**Comment by nuxsmin** [comment]
Puedes descargar el último commit de la rama "devel"?

**Comment by anogues** [comment]
voy

**Comment by anogues** [comment]
Ha mejorado. Ahora no da el error, pero cuando entro, después dle login, pantalla en blanco

Y en el log no hay ningun error...

**Comment by nuxsmin** [comment]
Prueba a refrescar la página ya que han cambiado los Javascript

**Comment by anogues** [comment]
Nada, sigue mal.

Los errores en la foto:

![image](https://cloud.githubusercontent.com/assets/8581047/22068788/7232386c-dd96-11e6-9afb-7f4ab50fdbd2.png)

![image](https://cloud.githubusercontent.com/assets/8581047/22068795/7b6a973a-dd96-11e6-919e-f5ff214e4df4.png)


Y luego de eso, pantalla blanca

**Comment by anogues** [comment]
El segundo desde otra máquina de la red. Veo que está cogiendo dos veces el puerto :|

**Comment by nuxsmin** [comment]
Puede ser problema del puerto, ya que recientemente he hecho un cambi para permitir conexiones desde proxy inverso pero  no he tenido incidencias respecto a eso:

La línea que hace eso es:

```
config.APP_ROOT = window.location.protocol + "//" + window.location.host + (location.port ? ':' + location.port : '') + rootPath();
```

**Comment by anogues** [comment]
Tiene pinta, si. HA sido en los últimos 5 dias el cambio?

En que fichero es? voy a probar de cambiarlo a ver...

**Comment by nuxsmin** [comment]
Pufff...corregido, La variable "location.port" sobraba, ya que "location.host" ya incluye el puerto...

Actualiza con el último commit.

**Comment by nuxsmin** [comment]
Gracias por probar!!

**Comment by anogues** [comment]
A ti!

Vamos a intentar una carga masiva de unos 1.800 usuarios ya te digo que tal va.

Te voy a tener que mandar un jamón por la ayuda :)

**Comment by nuxsmin** [comment]
Jajajaja...a ver que tal va. 1800 usuarios o cuentas?. Si te surge alguna incidencia me la comentas.

Saludos!

**Comment by nuxsmin** [comment]
Por cierto lo veo un poco feo en Safari?

![syspass systems password manager - mozilla firefox_087](https://cloud.githubusercontent.com/assets/1775774/22069959/943462d8-dd9a-11e6-831e-2dfce133a7a6.png)

**Comment by anogues** [comment]
Estoy usando Chrome, no creo que sea feo la verdad. Creo que la nueva versión tiene unos controles mas estilizados que la anterior.

Por cierto ya funciona todo bien. Vamos a ver que tal la carga ahora.

**Comment by anogues** [comment]
1.300 al final todas cargadas!

**Comment by nuxsmin** [comment]
Wow, me alegro mucho!!. Estoy puliendo detalles en 2.0-beta y en breve será estable. Le he puesto beta, por que aún quedan por completar traducciones y algunos detalles, pero es usable. De hecho, actualmente la tengo implantada con ~2100 cuentas.

**Comment by anogues** [comment]
Hola.

Creo que el category lo reutiliza, pero el customer no, lo duplica, cuando se hace el import con el csv.

Si puedes echarle un vistazo cuando tengas algo de tiempo, no corre prisa tampoco, puesto que lo hemos oslucionado directamente en la base de datos.

Salu2

**Comment by vfontanella** [comment]
Muchas gracias nuxsmin, mui bueno e util syspass. Pensas ser mui difícil importar .xml  provenientes desde PasswordSafe? Yo lo entente pero retorna .xml invalido. CVS no me gusta por conta del formato tengo que inserir unos campos que non tiene PasswordSafe e mudar lo delimitador para <tab> envés de <;> o mudar lo .cvs file. Yo soy mui perezoso para esto :)
Otra cosa que no consigo hacer funcionar é hacer login en Safari. No hace login, retorna siempre al login.
Pardon por mi intento de hablar español, espero que tu entienda de alguna maniera.
Abrazo a todos.
Vicente.

**Comment by nuxsmin** [comment]
Buenas @vfontanella,
me alegro de que te sea útil sysPass :)

En estos momentos no es posible importar desde passwordsafe, pero si me facilitas un XML de ejemplo, puedo programar el código necesario.

No he podido probar Safari, pero entiendo que utilizas la versión 2.1.1, por lo que es posible que sea un problema con las cookies, ya que sysPass utiliza una cookie especial llamada "SYSPASS_SK", por lo que si no está en el navegador, la sesión no se inicia.

No te preocupes por no hablar español, es bastante bueno, gracias por el intento

Saludos!

***

Hello @vfontanella,

I'm glad that you found sysPass useful ;)

Currently it's not possible to import from passwordsafe XML format, but if you could provide a sample XML file, I can code some stuff to get it.

I've not tested sysPass on Safari, but as I understand you're running the latest 2.1.1 version, so it could be possible that there were an issue with the browser cookies, because sysPass uses an special cookie named "SYSPASS_SK", so if it's not set, the login wouldn't take place.

No worries about your Spanish, it's quite well. Thanks for trying out

Regards!

**Comment by vfontanella** [comment]
Hola Ruben,
Espero que este ejemplo del .xml sea suficiente.
Muy cierto que el problema con Safari es Cookies. Tengo muchos problemas
con Safari por eso,
empece  a usar Firefox e funciona muy bien. Vale.
------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pwlist>
<pwentry>
<group>Group</group>
<title>Title</title>
<username>User</username>
<password>Password</password>
<notes>Notes</notes>
</pwentry>
<pwentry>
<group>Group</group>
<title>Title1</title>
<username>User1</username>
<password>Password1</password>
<notes>Notes1</notes>
</pwentry>
</pwlist>
--------------------------------------------------------------------------------
Muchas gracias.

Vicente.
