### ISSUE TITLE
When importing accounts with a csv file, passwords don't get imported

### ISSUE THREAD

**Issue by anogues** [nuxsmin/sysPass#373]
They appear blank.

Also in the db the column is empty

**Comment by nuxsmin** [comment]
Did you set the master password option?. If so, it's only needed when importing XML files (doc needed), so if you set it, it was used so the process tried to decrypt every password with it.

**Comment by anogues** [comment]
it may well be yes. I thin i tried to import the csv file with the master password (no import password set).

I will retry tomorrow without setting the master password and i let you know!

Thanks

**Comment by nuxsmin** [comment]
Ok, the documentation is already being written so it would be available when the stable version were released.

**Comment by anogues** [comment]
Uhm something not working.

I am importing the following csv:

p11;server;unix;url;user;password;notes

no passwords set, neither master nor import

Importación finalizada
Revise el registro de eventos para más detalles

but then i go to check the account:

![image](https://cloud.githubusercontent.com/assets/8581047/22100179/bef8e09a-de2e-11e6-98fa-214127bac2c1.png)

It appears empty, i think it is because not setting the master password it hasn't cyphered the account when inserting it to the db

mysql> select account_pass from accounts where account_name = 'p11';
+--------------+
| account_pass |
+--------------+
| password     |
+--------------+
1 row in set (0.00 sec)


But what i want is to import the csv file, and then store the encrypted passwords in the database, like when you create manually an account.

So i tried adding the master password in the import stage with the following

p12;server;unix;url;user;password;notes

but then:

Importación finalizada
Revise el registro de eventos para más detalles

Same behaviour in the UI and the field is empty in the db:
mysql> select account_pass from accounts where account_name = 'p12';
+--------------+
| account_pass |
+--------------+
|              |
+--------------+
1 row in set (0.00 sec)

So how can i supply clear passwords in a csv file and get them encrypted on the db when these are bulk loaded?

**Comment by nuxsmin** [comment]
I'm blind....I didn't notice that the password was encrypted if it were previously decrypted...

**Comment by nuxsmin** [comment]
I'm solving an issue with the CSV delimiter...I'll let you know when solved

**Comment by nuxsmin** [comment]
Hi, it has been solved in the latest commit (devel branch). I've added the field enclosure character ("), so fields would be more safely parsed. Does it break your CSV?

**Comment by anogues** [comment]
No, we can add the quotes, no problem.

I'll try!

**Comment by anogues** [comment]
Con las quotes no funciona, vuelve a salir el password en blanco!

**Comment by nuxsmin** [comment]
Es raro...
![seleccion_089](https://cloud.githubusercontent.com/assets/1775774/22110427/f562b8f4-de5b-11e6-913a-b624dc70b905.png)

Tiene algún carácter especial?

**Comment by anogues** [comment]
No, estoy probando esto

**Comment by anogues** [comment]
"p12";"server";"unix";"url";"user";"password";"notes"

**Comment by nuxsmin** [comment]
Igual...
![syspass csv -dev-res - gedit_090](https://cloud.githubusercontent.com/assets/1775774/22110543/5c3b3b1e-de5c-11e6-964d-31320cacd9b5.png)

**Comment by anogues** [comment]
Pruebo de nuevo a ver si la he liado..

**Comment by nuxsmin** [comment]
Actualizaste al último commit? https://github.com/nuxsmin/sysPass/commits/devel

**Comment by anogues** [comment]
Si, le he dado a bajar el ultimo zip de devel

**Comment by nuxsmin** [comment]
Es más, lo último que he añadido es la ayuda sobre los campos

**Comment by anogues** [comment]
Ya está ya está, le habia puesto el master password...

Culpa mía

**Comment by nuxsmin** [comment]
Ammm...perfecto!!

**Comment by anogues** [comment]
Todo cargado ya, y funcionando, gracias!
