### ISSUE TITLE
request - ability for user to handle own passwords .. 

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysPass#374]
hi, 
til now i did not figure out  how to store passwords  just under my own user acc. 
passwords are always visible to  users with higher rights. 

is it possible to make a diference between personal passwords an passwords shared to others ?

**Comment by nuxsmin** [comment]
Hi, that feature has been added to the latest 2.0-beta release and also private accounts for main group. You can checkout it at https://demo-dev.syspass.org

Take into account that those "private" accounts are encrypted in the same way, so anyone who knows the master password and have access to the database, would be able to decrypt them.

**Comment by LeDistordu** [comment]
Private passwords are mixed with the rest, you can add a filter to see only private passwords ?

**Comment by nuxsmin** [comment]
Sure, but it has already been added...just use "private:" (need doc)
