### ISSUE TITLE
request - groupfunctionality redesign

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysPass#375]
meeep, 

current situation:
several customers - several password categories
i.e.   Microsoft - Windows Server

i created a user group called  Microsoft. 
this group is able to see stuff shared to  Microsoft. 
A user out of this customergroup  should be able to alter passwords,   - this works
A user out of this should be able to  create passwords - works

BUT , a user with right to create passwords  is able to see ALL customergroups instead of just his own.
so a Microsoft user  would be able to create / edit a password  from Linux , Oracle or SAP

know what i'm trying to say ? 
a user with permisson for group X should only be able to create / edit passwords for his group. not in others,  and he should not even see if an who is listed in the customers.

**Comment by nuxsmin** [comment]
RIght, that has been solved in the latest 2.0-beta release ;)
