### ISSUE TITLE
Account Tag searching loses focus after tag set

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#378]
I have been checking the latest beta of 2.0 hosted at https://demo-dev.syspass.org/

When using the account tags for filtering on multiple tags it always moves the focus back to the Search bar.

Browser: Chrome 55

Steps to replicate
1. Login to demo site
2. Click in the Tag filtering
3. Type a tag name and press enter
4. Focus is moved to the search bar

I would suggest that focus remains in the Tag filtering box so more tags can be entered.

My guess is this behaviour comes from the search that happens with each tag that is applied.

**Comment by nuxsmin** [comment]
Solved. Thanks for the feedback!
