### ISSUE TITLE
Master password required after LDAP password change

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#379]
Syspass Version: 1.2.0.08

Login accounts are configured with LDAP connected to MS AD. 

When the user changes their password on the LDAP server they can no longer login to syspass (with either old or new credentials), they receive an error that 'The master password is not saved or has changed'.

In order to get back into the system a temporary Master password has to be changed and the user can login. 

Is it possible to automate this process when an LDAP user has a changed password?

**Comment by nuxsmin** [comment]
Sure, but this feature has been implemented in 2.0-beta version.

**Comment by nuxsmin** [comment]
That is so because the master password is encrypted with a derivated key form the user's one, so every time the user changes its password, he will be requested to enter the master pass.

**Comment by basil-twisleton** [comment]
Thanks for the quick reply,.
If it is solved in v2.0 then that is perfectly fine., I do not need it for 1.2 as I will be upgrading to 2.0 as soon as it is out of beta.
