### ISSUE TITLE
Migrate and Upgrade Seach issues

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#381]
I have attempted to migrate to a new server. however the search page never loads. Just a spinning icon in the center. All other features seem to work fine. 

**Old Server** 
Syspass: 1.2.0.08 
OS: Ubuntu 14.04 
Database: 5.5.44
Apache: 2.4.7
PHP: 5.5.9

**New Server** 
Syspass: 1.2.0.21
OS: Ubuntu 16.04 
Database: 5.7.17
Apache: 2.4.18
PHP: 7.0.13

**Steps to migrate.**
1. mysqldump syspass database from old server
2. copy to new server and restore into new syspass database
3. migrate syspass Database user from old server to new server
4. Download 1.2.0.21 tar release from gitlab and extract to `/var/www/html/syspass`
5. Copy config file  from old server to new server
6. update config folder permissions as per install guide (chown and chmod)
7. Start apache on new server

This way the master password and encrypted data does not need to be changed/re-encrypted.

I can login with both the admin account and other users. I can see all the customers and categories. I can also export the accounts and it shows all the account names etc. 

I am not sure where to look for the cause of the query screen not loading. 

On first login there was no upgrade process suggested (not sure if there were db changes), should there have been?

**Comment by nuxsmin** [comment]
Hi, that is weird, because there weren't any database updates till 2.0-beta, so it could be a Javascript issue or any stuff related to the PHP version. Is there any notice in the apache error log?

**Comment by basil-twisleton** [comment]
Thanks for the quick response. I have just checked the Apache error  log and found there is an undefined function exception in one of the classes.

`[Tue Jan 24 14:58:09.822863 2017] [:error] [pid 21332] [client xxx.xxx.xxx.xxx:58270] PHP Fatal error:  Uncaught Error: Call to undefined function SP\\mb_substr() in /var/www/html/syspass/inc/Html.class.php:96\nStack trace:\n#0 /var/www/html/syspass/web/SearchC.class.php(267): SP\\Html::truncate('G:\\\\IT\\\\Financial...', 60)\n#1 /var/www/html/syspass/web/SearchC.class.php(161): SP\\Controller\\SearchC->processSearchResults(Array)\n#2 /var/www/html/syspass/ajax/ajax_getContent.php(86): SP\\Controller\\SearchC->getSearch()\n#3 {main}\n  thrown in /var/www/html/syspass/inc/Html.class.php on line 96, referer: http://xxx.xxx.xxx.xxx/index.php`

**Comment by nuxsmin** [comment]
Hmmm...a required module in PHP 7

sudo apt-get install php7.0-mbstring

http://php.net/manual/en/mbstring.installation.php

**Comment by basil-twisleton** [comment]
Installing mbstring fixed it and it is now fully running on the new server. I must have missed it on initial php insatllation..

Thank you for the help.

**Comment by nuxsmin** [comment]
It has been a compiled-in module in PHP < 7 so you need to install it when running on PHP 7.

FYI: this module enables multibyte string operations for those languages that requires more that 1 byte to represent a character: http://php.net/manual/en/intro.mbstring.php 

Thanks for the feedback!

**Comment by austin583** [comment]
@nuxsmin https://preprocessor.space/questions/invoke-a-method-in-a-separate-class
