### ISSUE TITLE
sysPass 2.0 Install issue

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#382]
Hi,

i'm trying to install sysPass on my webspace and I can't enter a Port for my Database Server.
Can you please fix it? I'm getting an error/message: incorrect format...

Thank you,
Lukas

**Comment by lukasp2** [comment]
Hi,

when I enter databaseserver:port and try to install sysPass on my Webspace then I get this error:

Unable to connect to the DB
Compruebe los datos de conexión
SQLSTATE[HY000] [2027] Malformed packet

Br,
Lukas

**Comment by nuxsmin** [comment]
Please, take a look to this link: https://bugs.mysql.com/bug.php?id=77298

**Comment by lukasp2** [comment]
Hmm okay, but I'm getting this error with MariaDB 10.1 too

**Comment by nuxsmin** [comment]
Ok, let me take a test on that versions and I'll be back

**Comment by nuxsmin** [comment]
Hi, did you try out with the latest release?

**Comment by lukasp2** [comment]
Yes

**Comment by nuxsmin** [comment]
Perhaps it could be wrong because the PHP mysql driver...

https://bugs.php.net/bug.php?id=72638

But I don't know why WordPress is running fine, so I think that is so because WordPress doesn't use PDO (http://php.net/manual/en/intro.pdo.php) and uses mysql_* functions instead: http://wordpress.stackexchange.com/questions/84680/wordpress-mysqli-and-pdo

**Comment by lukasp2** [comment]
I will contact my provider, i hope that they can help me

**Comment by nuxsmin** [comment]
Fine, hosting providers usually set some config parameters to avoid services overloading and other security related issues.

The sysPass demo site is on a shared hosting and the only issue detected was related to MySQL views and the prepared statements, it didn't work, so I had to set some kind of emulation in the code that wouldn't be needed on a private hosting.

Hope they help you!

**Comment by lukasp2** [comment]
I will report !

**Comment by lukasp2** [comment]
I got an answer. It's not possible to change needed settings on their database servers because I'm on a shared Server with many other customers

Also I can't use sysPass on my webspace... :-(

**Comment by nuxsmin** [comment]
Are you using "localhost" as the connection server? Did you try it?

**Comment by lukasp2** [comment]
Yes, error is:

Unable to connect to the DB
Compruebe los datos de conexión
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by nuxsmin** [comment]
Could be....

Could you replace the files attached to the gist?: https://gist.github.com/nuxsmin/38ebe238ace78542eab4d4eba80cf5aa

They are located at: "inc/SP/Storage" and "inc/SP/Core"

**Comment by lukasp2** [comment]
Thank you very much, but -> Error:

Unable to connect to the DB
Compruebe los datos de conexión
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

Do you need more informations about my webspace? I can provide you access data to my Database and FTP if you're interested?

**Comment by nuxsmin** [comment]
Sorry, I missed to remove some parts in the connection string. Please, replace the files again.

**Comment by lukasp2** [comment]
No Chance :-(

Unable to connect to the DB
Compruebe los datos de conexión
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/temp/mysql57.sock' (2)

**Comment by nuxsmin** [comment]
And what about by setting 127.0.0.1:3306 as db server? (You would need to switch back to the original files....)

**Comment by lukasp2** [comment]
Unable to connect to the DB
Compruebe los datos de conexión
SQLSTATE[HY000] [2027] Malformed packet

**Comment by nuxsmin** [comment]
I know that should be correct, but..is it the right port?

**Comment by lukasp2** [comment]
when I try that with "localhost" and no port, I get this error:

Unable to connect to the DB
Compruebe los datos de conexión
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by nuxsmin** [comment]
Could you place a file called "info.php" in the sysPass root and then access to it?

The content is as follows:
```
<?php

phpinfo(INFO_MODULES);
```
The interesting parts are those related to MySQL

**Comment by lukasp2** [comment]
You got a Mail

**Comment by nuxsmin** [comment]
Fine...it seems that the socket path was wrong...it should be "/tmp/mysql57.sock". I have just updated the gist, please replace the files again

**Comment by lukasp2** [comment]
Thank you. It seems to ignoring mySQL-User. User lukasp = Admin User for sysPass

No es posible comprobar el usuario de sysPass (lukasp)
Please, check the DB connection user rights

**Comment by nuxsmin** [comment]
If you are in a hosted environment you would need to use the hosting mode, because the installer will check some disallowed tables.

Please, take a look to: https://wiki.syspass.org/en/hostingmode

**Comment by lukasp2** [comment]
Great! It works with hosting mode now! Big thx!

**Comment by nuxsmin** [comment]
You're welcome!

And sorry about those untranslated messages, an undesired behavior on the translating function returns them untranslated. It will be fixed in next commit ;)

**Comment by lukasp2** [comment]
Everthing is fine, you're very active @github ! :-)

Can you please tell me, how I have to use comer updates?

**Comment by nuxsmin** [comment]
I've just done a commit about that... ;)

Currently I'm finishing the sysPass v2 release so every feedback is welcome and I'll try to fix it as soon as possible :)

**Comment by lukasp2** [comment]
Great, you're amazing ! :)

**Comment by nuxsmin** [comment]
Thanks!

Please, could you try it out on your environment?

**Comment by lukasp2** [comment]
Ok I used "devel" release. When I try to make a clean install:

SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by nuxsmin** [comment]
Did you use the "unix:" prefix?

**Comment by lukasp2** [comment]
No, how I have to use it?

In DB Field -> unix:/tmp/mysql57.sock?

**Comment by nuxsmin** [comment]
Right!

**Comment by nuxsmin** [comment]
sorry...DB Host field

**Comment by lukasp2** [comment]
ok, popup message tells me that I have to use correct / right format

**Comment by nuxsmin** [comment]
Agrrr,  the html regex checker wasn't modified...I've just updated it

**Comment by lukasp2** [comment]
Is working fine now :)

**Comment by nuxsmin** [comment]
Great! Hope you enjoy it ;)

**Comment by lukasp2** [comment]
Yes, I do! :-)
