### ISSUE TITLE
Case sensitive LDAP login

### ISSUE THREAD

**Issue by PxReaz** [nuxsmin/sysPass#383]
Hi,
I've configured sysPass with LDAP and some of the users have login with uppercase in.
But they try to login with their username in lower case. How can I fix this so they can do it?
Right now, the event log says the users has no group.

**Comment by nuxsmin** [comment]
That is because it couldn't lookup the user group. Which LDAP software are you running?

**Comment by PxReaz** [comment]
Im using OpenLdap with my Active Directory

Andrea Petrucci



Cordialement
Andrea Petrucci

**Comment by nuxsmin** [comment]
Ok, but the queries case should be managed by the LDAP server, because sysPass sends the user login to the LDAP server as is: http://stackoverflow.com/questions/2017152/case-insensitive-ldap-searches

sysPas only checks login case when the internal database is used for authentication.

**Comment by PxReaz** [comment]
Okay will take a look when i'm back to work 

Thanks 

Andrea Petrucci

**Comment by PxReaz** [comment]
Hi, I'm still having looking to fiyx this here is the problem:

With my login
login: xxxxxxj
login in AD: xxxxxxj
password: ******

Login works.

With my co-worker's login
login: xxxxxxj
login in AD: XxxxxxJ
password: ******

Login fails

**Comment by nuxsmin** [comment]
Ok, but I would take a look to the LDAP config (slapd.conf), because there is where search filters are defined.

**Comment by PxReaz** [comment]
I don't have any slapd.conf file.

I only have /etc/openldap/ldap.conf file that is empty

**Comment by nuxsmin** [comment]
Mmm, so are you running an Active Directory server?

**Comment by PxReaz** [comment]
I'm running Syspass on a SUSE Linux Enterprise 12 with OpenLdap connected to a Windows 2008 R2 Server that runs the Active Directory

**Comment by nuxsmin** [comment]
So, you're pointing sysPass to the ADS server, aren't you?

**Comment by PxReaz** [comment]
Yes I am

**Comment by PxReaz** [comment]
Any idea on the issue?

**Comment by nuxsmin** [comment]
Sorry, I haven't got enough time to take a look. Please, let me some time to get it.

**Comment by nuxsmin** [comment]
Hi, a silly question...Is your co-worker included in the right LDAP group that grants access to sysPass?

**Comment by PxReaz** [comment]
Hi,
Yes he is

**Comment by PxReaz** [comment]
Hi,
Thanks for the update, everything works fine now

**Comment by nuxsmin** [comment]
Great!, thanks for the feedback!
