### ISSUE TITLE
Select Customer not possible

### ISSUE THREAD

**Issue by MAndretti** [nuxsmin/sysPass#384]
Hi,

I installed the latest 2.0 beta (sysPass-2.0.0.17012501-beta).

1) added new customer
2) create new account
3) try to select customer --> nothing is shown
4) add a new customer using "+" in new account form --> all customers are shown

Looks like an error. 
Other select boxes works fine.

Thanks,
Mario

**Comment by nuxsmin** [comment]
Hi,
let me take a look, it seems that the select control is some kind of caching stuff, because if you add a new item from the account view, the control is forced to refresh, so caching is skipped.

**Comment by MAndretti** [comment]
Hi,

looks good now :)

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Great!

**Comment by nuxsmin** [comment]
Thanks for the feedback
