### ISSUE TITLE
Internal Server Error on Category or Customer delete

### ISSUE THREAD

**Issue by MAndretti** [nuxsmin/sysPass#385]
Hi,

I found some errors in latest 2.0 beta (sysPass-2.0.0.17012501-beta).

1) Append category "xyz"
2) Append customer "123"
3) delete category "xyz" -> Internal Server error 
                                       -> but category "xyz" was deleted 
                                       -> refresh missing
4) delete customer "123" -> Internal Server error 
                                       -> but category "xyz" was deleted 
                                       -> refresh missing

Error-Log: PHP Fatal error: Call to a member function getCategoryName() on string in ItemActionController.calss.php on line 577

Error-Log: PHP Fatal error: Call to a member function getCustomerName() on string in ItemActionController.calss.php on line 514

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Thanks so much for the feedback!!. I've made a mistake when retrieving the current item before deleting, that is so to save the item data (ie. name) in the event log.

**Comment by MAndretti** [comment]
Hi,

error is fixed :)

Thanks,
MAndretti
