### ISSUE TITLE
LDAP import error

### ISSUE THREAD

**Issue by MAndretti** [nuxsmin/sysPass#386]
Hi,

I installed the latest 2.0 beta (sysPass-2.0.0.17012501-beta).

1) I configured LDAP (works like a charme!)
2) Goto "Users" and click on "import users from LDAP"
3) Message "Internal Server error" is shown

 PHP Catchable fatal error:  Argument 1 passed to SP\\Core\\Messages\\MessageBase::setDescription() must be of the type array, string given, called in /srv/syspass/inc/SP/Auth/Ldap/LdapBase.class.php on line 434 and defined in /srv/syspass/inc/SP/Core/Messages/MessageBase.class.php on line 74, referer: https://syspass.hsm.dev/index.php

4) click on "import users from LDAP" again 
      -> import is ok
      -> refresh missing (new users are not shown)
5) Click on Search
6) Go back to Users -> Imported users are shown
7) delete all LDAP Users
8) Click on Search 
9) Go back to Users 
10) click on "import users from LDAP"
11) Message "Internal Server error" is shown    

Strange behavior ...

Thanks,
MAndretti

**Comment by MAndretti** [comment]
Hi,

tested and import works, but an error is shown if no new user was found.
Is this an error? 

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Sure not...I've modified the function to return "true" on that case. Thanks for the feedback!
