### ISSUE TITLE
Dropdown customers missing information

### ISSUE THREAD

**Issue by anogues** [nuxsmin/sysPass#387]
Hello

The customer drop down used in the create new account dialog is missing some information.

If a customer exists but at this time, it is not being used, i.e. it has no account using it, but it is on the database (maybe because it existed previously for a deleted account) it is not shown in the drop down box.

Think possibly you are using all "active" customers, ie, the ones referenced by any entry in the accounts table, instead of using the ones appearing in the customers table. Would it be possible to populate the drop down lins using the info on the customers table, hence all will appear.

BR,
Albert.

**Comment by nuxsmin** [comment]
Hello,

that is related to a recently closed issue  #384

It has been solved in the latest commit.

Thanks for the feedback ;)

**Comment by nuxsmin** [comment]
Solved
