### ISSUE TITLE
LDAP User Name Error

### ISSUE THREAD

**Issue by MAndretti** [nuxsmin/sysPass#388]
Hi (again),

I installed the latest version.

1) Import user from LDAP (Name in DB is "first name surname") -> correct
2) Login as LDAP-User -> works
3) user_name in table usrData is changed to  "first name surname **surname**" -> error
4) change user name back to "first name surname"
5) Login as LDAP-User -> works
6) user_name in table usrData is changed to  "first name surname **surname**" -> error

Thanks,
MAndretti

**Comment by MAndretti** [comment]
I used version 2.0 beta - 86e8c7d.

**Comment by nuxsmin** [comment]
Hi...

the current LDAP attributes is as follows:

```
        $validAttributes = [
            'groupmembership' => 'group',
            'memberof' => 'group',
            'displayname' => 'name',
            'fullname' => 'fullname',
            'givenname' => 'name',
            'sn' => 'sn',
            'mail' => 'mail',
            'lockouttime' => 'expire'
        ];
```
Then:
```
        if (!empty($res["fullname"])) {
            $this->LdapAuthData->setName($res['fullname']);
        } else {
            $this->LdapAuthData->setName($res['name'] . ' ' . $res['sn']);
        }
```
Do you know which attributes are being used on your LDAP?

**Comment by MAndretti** [comment]
Hi...

found it :)

In MS ADS the attribute "fullname" doesn't exists. But "displayname". And this is mapped to "name".
e.g. 
name="Mario Muster"
sn="Muster"

$res["fullname"] is empty (missing in ADS) and now ...
$this->LdapAuthData->setName('Mario Muster' . ' ' .'Muster');

Change your code to (e.g.):

        if (!empty($res["fullname"])) {
            $this->LdapAuthData->setName($res['fullname']);
        } else {
            if (!empty($res["displayname"])) {
                $this->LdapAuthData->setName($res['displayname']);
            } else {
                $this->LdapAuthData->setName($res['name'] . ' ' . $res['sn']);
            }
        }

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Great!

An what about this solution?:
```
        $validAttributes = [
            'groupmembership' => 'group',
            'memberof' => 'group',
            'displayname' => 'fullname',
            'fullname' => 'fullname',
            'givenname' => 'name',
            'sn' => 'sn',
            'mail' => 'mail',
            'lockouttime' => 'expire'
        ];
```

This will map "displayname" to "fullname" so no nested conditions would be needed ;)

**Comment by MAndretti** [comment]
much better 
... tested 
... looks good :)

**Comment by nuxsmin** [comment]
Nice

**Comment by nuxsmin** [comment]
Solved. Thanks for the feedback @MAndretti !
