### ISSUE TITLE
Delete user error

### ISSUE THREAD

**Issue by MAndretti** [nuxsmin/sysPass#389]
Hi,

I installed the latest version (2.0 beta - 86e8c7d).

1) Delete User
2) PHP Fatal error: Call to a member function getUserName() on string in ItemActionController.class.php on line 262
3) user is deleted
4) no view refresh

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Ummm, sorry, I missed to apply the same solution to the user's function...

I'll let you know when solved.

**Comment by nuxsmin** [comment]
Solved

**Comment by nuxsmin** [comment]
Thanks for the feedback!
