### ISSUE TITLE
Login issue for new users

### ISSUE THREAD

**Issue by darethgh** [nuxsmin/sysPass#39]
When my non admin user tries to log in, it prompts for a Master Password, but the text box is not editable.  An orange box says Master Password is not saved or is wrong.

The online demo has the same behavior.  Am I missing something somewhere?

**Comment by goro22052** [comment]
I have the same problem.
When ldap user entering the syspass he sees prompt enter login and password again and master-password.
But if the user entered login, password again and new master-password he sees "wrong master password."
