### ISSUE TITLE
Howto export accounts in csv?

### ISSUE THREAD

**Issue by MAndretti** [nuxsmin/sysPass#390]
Hi,

how can I export accounts as csv? With clear text passwords.

Can I use your api? Do you have an example (script)? Or is it possible to integrate this function imto 2.0?

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Hi,

That's a question that has been discussed during a time ago, and I'm partially disagree about exporting the passwords in plain text, because I'm very concerned on security and I think that if such feature is implemented, many people will store their passwords in an insecure way. I wouldn't want to contribute to do that.

You can export them in XML format and the passwords will remain secured by its encryption.

I would code some method to decrypt that file by providing the master password.

Kind regards

**Comment by MAndretti** [comment]
Hi,

yes, plain text is not secure. But ...

We print the list and put it into an envelope. This envelop is stored in a safe (for emergency situations). For example, if our servers were damaged by a fire. Not all passwords are for server systems or services.

If there is a better way, please tell me how. You're the professional here.

Thanks,
MAndretti

**Comment by MAndretti** [comment]
i'm so ... sorry

What is the difference between a printed list and a usb stick? No one.

I can use xampp lite. Install sysPass and import encrypted backapp. That's it.

Sorry again and thanks,
MAndretti

**Comment by nuxsmin** [comment]
Sure, I know what you may think about exporting the accounts, but I would like to keep the security chain beyond sysPass, so exporting the accounts encrypted would be safe and you could also import them in the future.

I would store the XML file with a decryption tool, so the master password should be provided to view them.

Xampp is nice and does the trick and actually we use it to access to them when a failure occurs.

**Comment by MAndretti** [comment]
Yes you are right. 

Close this request?

**Comment by nuxsmin** [comment]
Let it opened because it would remind me about coding the description tool...

**Comment by nuxsmin** [comment]
Sorry, decryption...

**Comment by nuxsmin** [comment]
Listed in sysPass v2.1 roadmap

**Comment by akzov** [comment]
Application is a trap, it accepts input from other applications but won't let you get data out again!

**Comment by nuxsmin** [comment]
@akzov Wow, really incredible!! Are you sure of that? What about an XML export?, What about this tool (https://github.com/nuxsmin/sysPass-XML-Decrypter) developed by a contributor?

Encrypted does not mean "trap", it means security instead. I won't develop any plain text export.

**Comment by akzov** [comment]
If it's not easy to move data into another product then it's lock-in, Microsoft used to do it a lot.

http://www.linfo.org/vendor_lockin.html

**Comment by nuxsmin** [comment]
So easy...you have the code, you have the power ;)

**Comment by akzov** [comment]
Yes, have to write a decryptor that actually works then integrate... so easy to move from sysPass to competitor.

**Comment by nuxsmin** [comment]
@akzov there aren't any competitors because it's a hobby with many hours spent (about 450 during last year) in developing and much more giving support to anyone, so if you found any missing feature, please open an issue and it will be evaluated.

The https://github.com/nuxsmin/sysPass-XML-Decrypter tool was written by a contributor and works nice, but it has some special dependencies that could be a hassle, so I'll modify some parts to get it working seamlessly.

**Comment by akzov** [comment]
The software doesn't work: https://github.com/julenpardo/sysPass-XML-Decrypter/issues/1

Currently there is no way to leave sysPass

**Comment by joerg** [comment]
@akzov I also just tried this and it worked quite fine, so yes, there is a way to leave sysPass and its actually quite easy and performant (too around 30 seconds for almost 500 accounts).
Syspass version is 2.1.12.17072401 (running from the official docker image). Process to recreate was:

* Clone this git repo
* Place XML that was exported with the Password 1234 (or any other, but not empty) in the cloned repo directory
* Change to the directory
* Run 
```
docker run --interactive --name syspass-decrypt --tty --workdir /app --detach --volume `pwd`:/app composer /bin/bash
docker exec syspass-decrypt composer install
docker run syspass-decrypt ./decrypt.php sysPass.xml 1234 master_pass_without_quotes_or_so out.csv
```

So actually also julenpardo/sysPass-XML-Decrypter#1 could be closed in my eyes.

**Comment by akzov** [comment]
@joerg Well if it works for you it can't be a problem! Better close the other ticket there too: https://github.com/julenpardo/sysPass-XML-Decrypter/issues/2

**Comment by MagicFab** [comment]
Hi, FYI I've forked and added feature to decrypt/export notes, working fine with 500+ records:
https://gitlab.com/MagicFab/sysPass-XML-Decrypter

**Comment by jucajuca** [comment]
@MagicFab I tried today the decrypter. I get the following error:

```
Starting decryption...
PHP Notice:  Undefined offset: 1 in /home/jccb/CODE/sysPass-XML-Decrypter/src/Decrypter.php on line 34
PHP Notice:  Trying to get property of non-object in /home/jccb/CODE/sysPass-XML-Decrypter/src/Decrypter.php on line 145

```
any ideas on what could be the issue?

**Comment by jucajuca** [comment]
at the moment the tools to export the passwords seem to be broken. 
I understand the concerns about having this function integrated, but keeping an external export tool up-to-date would help a lot. 
I want to migrate my passwords to a local storage and so long it has not been possible.

**Comment by MagicFab** [comment]
@jucajuca please file a bug report on GITLab, don't forget to indicate what your environment is (OS, PHP versions, Syspass version).

**Comment by Altes** [comment]
For syspass 3.0.5 the latest decrypter version on gitlab worked fine for me.

**Comment by jucajuca** [comment]
@Altes @MagicFab 
I made it work. I had to put the password into quotation marks and it worked then. thx

**Comment by Altes** [comment]
I wonder, how can I schedule the backup xml execution? 
@nuxsmin

**Comment by nuxsmin** [comment]
@Altes through the API and running a cron job. This would be "the Poor's man method", since it would be preferred to perform it using database and virtual machine tools.

**Comment by Altes** [comment]
Sounds good! thanks

**Comment by MagicFab** [comment]
@Altes thanks for reporting it works with v3 and how you solve dyour problem. [I've updated the README on the project at Gitlab](https://gitlab.com/MagicFab/sysPass-XML-Decrypter).
