### ISSUE TITLE
Mail Settings RegEx Issue

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#391]
Hi,
I want to enable E-Mail notifications but I can't save my entered Data because there is a regex issue with my Mail account --> xxx@xxx.technology

Can you please fix it?

Thank you,
Lukas

**Comment by nuxsmin** [comment]
Hi,

which is the view you're talking about?. I didn't see any email regex neither within user's nor mail config views.

Kind regards

**Comment by lukasp2** [comment]
Sorry for my bad description.

Configuration -> Mail -> User

My E-Mail address in User field will not be accepted

Br,
Lukas

**Comment by nuxsmin** [comment]
Sorry, but I couldn't notice any issue with this field. I've tested it at the demo site:

![captura_107](https://cloud.githubusercontent.com/assets/1775774/22418766/aac70872-e6da-11e6-9322-364408813434.png)

**Comment by lukasp2** [comment]
Oh sorry, I don't know what the problem was....but it is working now.

**Comment by nuxsmin** [comment]
Great!. Let me know whenever any issue occurs.
