### ISSUE TITLE
Delete User error

### ISSUE THREAD

**Issue by MAndretti** [nuxsmin/sysPass#392]
Hi,

i installed the latest versions of sysPass (2.0RC2).

- Import user from MS ADS
- Select e.g. two users 
- Click "delete selected"
- Do nothing with the imported users
- "Unable to delete, user in use" error is shown
- Users are not deleted
- Delete user by icon (Delete user) works as aspected

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Hi, is there any event registered in the event log?. This is most likely because the user is being referenced in any other record like accounts.

Kind regards

**Comment by MAndretti** [comment]
hi, no. There are no entries in the event log.
And the user are not assigned to any account.

**Comment by nuxsmin** [comment]
Sorry, but I couldn't reproduce that behavior. Could you refresh the browser (only hit F5)?. That is so because some javascript files would need to be refreshed.

The only issue I have had is that the "OK" message didn't show any message, but the users were deleted.

**Comment by MAndretti** [comment]
1) cleared the browser cache
2) refresh view (F5)
3) select two (LDAP) user
4) Click "delete selected"
5) "Unable to delete, user in use" error is shown

**Comment by nuxsmin** [comment]
That's weird, because I've done some tests by deleting several LDAP users and it worked fine.

The delete query does not filter by user type:
```
$query = 'DELETE FROM usrData WHERE user_id = ? LIMIT 1';
````

**Comment by MAndretti** [comment]
Tested the latest version. Looks good :)

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Great!. Thanks for the feedback.
