### ISSUE TITLE
New user first login not working

### ISSUE THREAD

**Issue by MAndretti** [nuxsmin/sysPass#393]
Hi,

I installed the latest version of sysPass (2.0RC2).

- Import user by LDAP
- Assign user to profile and group admin
- Open different browser
- login as imported user (user and password are ok)
- Error is shown (wrong credentials)
- 2. login 
- "Master password is needed" message is shown
- 3. login ok

Is this behavior OK? Or is it a bug?

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Hi, did you mean that the very first user login shows "Wrong credentials" instead of "Master password is needed"?

Kind regards.

**Comment by MAndretti** [comment]
Hi, yes.

**Comment by nuxsmin** [comment]
Is there any LDAP related error in the event log?

**Comment by MAndretti** [comment]
1. login shows:
    Level: ERROR
    Event: Log in
    Description: Incorrect login (Type: authLdap, User: xyz)
2. login shows nothing in log
3. login shows
    Level: INFO
    Event: CheckTempMasterPass
    Description: Temporary password expired

but the login works ...

**Comment by nuxsmin** [comment]
Even with wrong password??

**Comment by nuxsmin** [comment]
Could you try out the latest commit?. Thanks!

**Comment by MAndretti** [comment]
Yes of course. Try it tomorrow.

**Comment by MAndretti** [comment]
Perfect! Works like a charme now.

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Great!. Thanks for the feedback.
