### ISSUE TITLE
New User

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#395]
Hi Rubén,

I created a new User for my sysPass environment. I want to give this user access to some entries.
Is it neccessary that the news user has to enter master password to get access to entries?

Br,
Lukas

**Comment by nuxsmin** [comment]
Hi Lukas,

the master password will only be needed when the user logs in for the first time and you can provide a temporary master password (encryption tab) to not tell the real one.

Kind regards

**Comment by lukasp2** [comment]
Hi Rubén,

that means all users have a global master key? ...but I can create a temp. master password for new users therewith they can log in. 

Br,
Lukas

**Comment by nuxsmin** [comment]
No, users don't need to have any master password. They only need a temporary password for the first login.
You can also use the real master password, but if anyone knows it, they could decrypt all the account if they get a database access.

**Comment by lukasp2** [comment]
Okay, I understand now :-)

Thank you for your help! Rubén I Love your great work with great concept!

Br,
Lukas

**Comment by nuxsmin** [comment]
Great!. I'm very glad that you like it ;)
