### ISSUE TITLE
Great product - when will V2 be released? 

### ISSUE THREAD

**Issue by verticalgrain** [nuxsmin/sysPass#396]
I've just discovered sysPass and am really impressed. I will definitely be using it. 

Out of curiosity, is there a goal for the launch of V2? And, when V2 launches, will it be easy to upgrade from V1.2? 

Thank you for your hard work making this.

**Comment by nuxsmin** [comment]
I'm very glad that you found it useful!

Currently, I'm working hard to get it shortly, and the current status is RC which means that I'm fixing some final bugs to get it stable.

I'm also working on the documentation and website, so I think that it would be available within a week.

Sorry about the poor planning, but I'm a bit busy and I'm developing sysPass in my free time.

**Comment by verticalgrain** [comment]
Thanks for the update. Take your time and thanks again for putting your personal time into creating this.

**Comment by nuxsmin** [comment]
Thanks so much for your support!

**Comment by nuxsmin** [comment]
Update: sysPass 2.0 will be released at the end of this week. Documentation is already done on https://doc.syspass.org

**Comment by verticalgrain** [comment]
That's exciting news! Looking forward to trying it out. Thanks once again for using your time to create this.

**Comment by nuxsmin** [comment]
I've just released it ;)
