### ISSUE TITLE
Translation status?

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#397]
Hey,

what is the current translation status? I activated MAIL notifications (sysPass is set for english language) and some text is in spain.

Br,
Lukas

**Comment by nuxsmin** [comment]
Hi,

sysPass is fully translated into English, but the original strings are set in Spanish.

Which strings did you get in Spanish?

**Comment by lukasp2** [comment]
C&P from a mail:

**Subject:**
sysPass (Warning) - Realizar Backup


**Content:**
Action: Realizar Backup
Performed by: lukasp (84.189.xx.xx)
Application and database backup completed successfully

**Comment by nuxsmin** [comment]
Ok, I'll take a look, it could be possible that some strings would get in the original language because the UI can be set in a different language than the app, that's for example, an user can set it's own language and the event log is set in other language.

**Comment by lukasp2** [comment]
Good morning,

i used RC3 and tested your fix. Sadly without success :-(

![syspass](https://cloud.githubusercontent.com/assets/24668586/22496874/c00cef70-e84d-11e6-9e81-b637895aefad.JPG)

**Comment by nuxsmin** [comment]
Good morning!

Please,  restart your webserver, because it caches the translations.

**Comment by lukasp2** [comment]
Hey,

done but w/o success. I tried that with FireFox and Vivaldi Browser (cleared cache)

Br,
Lukas

**Comment by nuxsmin** [comment]
Hi, I've just pushed a fix that should solve the issue. You don't need to download the whole app, because there is only one changed line within a file. You could modify only that line.

**Comment by lukasp2** [comment]
Great, it's fine now :-) Thank you.

**Comment by nuxsmin** [comment]
You're welcome!
