### ISSUE TITLE
German language

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#398]
Hi Rubén,

sorry for disturbing you again, but I see that some strings are sill in spain language, when I choose german language.

What is to do to get "more" german language into sysPass?

Br,
Lukas

**Comment by nuxsmin** [comment]
Hi Lukas, don't worry about disturbing :)

I don't know which strings are untranslated, but English language is the default to fallback. Currently, the German translation is about 94% to get completed and I didn't yet merged the translated strings from POEditor into sysPass, because I would wait to get fully translated.

Are you interested to get it?

Kind regards

**Comment by lukasp2** [comment]
Hi,

okay, my default fallback is spain and not english :-) Maybe a little bug?

I'm working on german translation, but my english is not so perfect :-))

**Comment by nuxsmin** [comment]
No worries ;)

**Comment by derStephan** [comment]
@lukasp2 Maybe you could translate it and I take a look at it afterwards? I think, we can make German tranlation pretty good.

**Comment by lukasp2** [comment]
I will do my best !

**Comment by nuxsmin** [comment]
Sure!!

**Comment by lukasp2** [comment]
Translation is complete. There will be improvements during use :-)

**Comment by nuxsmin** [comment]
Ok, I'll put it into the current devel branch shortly, because hopefully it would be the sysPass 2.0 stable release :)

**Comment by lukasp2** [comment]
Tell me please when you put it into the currenct devel branch

**Comment by lukasp2** [comment]
did you? :)

**Comment by nuxsmin** [comment]
Sorry not yet... It will be ready in a few minutes :)

**Comment by lukasp2** [comment]
great ;-)

**Comment by nuxsmin** [comment]
Just pushed

**Comment by lukasp2** [comment]
Looks good I will check it while using sysPass ;-)

**Comment by nuxsmin** [comment]
Great!. Thanks for your contribution ;)
