### ISSUE TITLE
Created entries not displayed

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#399]
Hi,

I'm using sysPass 2.0 RC3 and created my 1st 2 entries. I want to access to my created items and I'm getting this error:

> Oops...
> There was an error
> Internal Server Error

What's wrong?

Br,
Lukas

**Comment by nuxsmin** [comment]
Do you mean when you want to edit them?. If so I pushed some changes since that release to the devel branch.

**Comment by lukasp2** [comment]
No, I create new entry, fill out all needed fields and save it.
When I go to magnifier then I'm getting this error. I Just want to see my created entries.

**Comment by nuxsmin** [comment]
Sorry about pushing fast, but I would like to get sysPass 2.0 out as soon as possible so the development is so quickly :)

**Comment by nuxsmin** [comment]
Actually, I'm using too the beta version in my company, so I get noticed about issues and fix them quickly.

**Comment by lukasp2** [comment]
and this is very nice from you! I will try last devel release...give me some sec.

**Comment by lukasp2** [comment]
No :-( same error

Oops...
There was an error
Internal Server Error

**Comment by nuxsmin** [comment]
Umm, that's weird, I haven't got any issue viewing the accounts. Is there any error in the web server log?

**Comment by nuxsmin** [comment]
I've added some entries too...
![001](https://cloud.githubusercontent.com/assets/1775774/22523248/fa8f62f6-e8be-11e6-86a1-ed936594818d.jpg)
![002](https://cloud.githubusercontent.com/assets/1775774/22523267/09f755e6-e8bf-11e6-93a3-b0227d6d0812.jpg)

**Comment by lukasp2** [comment]
hmm that that must be a server issue, let me check the error log

**Comment by lukasp2** [comment]
Maybe this is the problem?

> luks.technology [Wed Feb 01 20:18:44.605986 2017] [php7:error] [pid 153378] [client 84.189.203.156:58536] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to SP\\Core\\Session::setAccountColor() must be of the type array, string given, called in /nfsmnt/hosting2_1/c/3/c3618d26-dbe0-436d-a4e5-95aa6eed1ce9/luks.technology/web/sysPass/inc/SP/Account/AccountSearch.class.php on line 642 and defined in /nfsmnt/hosting2_1/c/3/c3618d26-dbe0-436d-a4e5-95aa6eed1ce9/luks.technology/web/sysPass/inc/SP/Core/Session.class.php:495\nStack trace:\n#0 /nfsmnt/hosting2_1/c/3/c3618d26-dbe0-436d-a4e5-95aa6eed1ce9/luks.technology/web/sysPass/inc/SP/Account/AccountSearch.class.php(642): SP\\Core\\Session::setAccountColor(' #')\n#1 /nfsmnt/hosting2_1/c/3/c3618d26-dbe0-436d-a4e5-95aa6eed1ce9/luks.technology/web/sysPass/inc/SP/Account/AccountSearch.class.php(332): SP\\Account\\AccountSearch->pickAccountColor(1)\n#2 /nfsmnt/hosting2_1/c/3/c3618d26-dbe0-436d-a4e5-95aa6eed1ce9/luks.technology/web/sysPass/inc/SP/Controller/AccountSearchController.class.php(194): SP\\Account\\AccountSearch->processSearchResults()\n#3 /nfsmnt/hosting2_1/c/3/c3618d26-dbe0-436d-a4e5-95a in /nfsmnt/hosting2_1/c/3/c3618d26-dbe0-436d-a4e5-95aa6eed1ce9/luks.technology/web/sysPass/inc/SP/Core/Session.class.php on line 495, referer https://luks.technology/sysPass/index.php

**Comment by nuxsmin** [comment]
Really weird...because that is a silly piece of code that I haven't touched since a long time...

**Comment by lukasp2** [comment]
strange, do I have a special environment? :-)

**Comment by nuxsmin** [comment]
BTW this is related to the accounts search

**Comment by lukasp2** [comment]
right and when I login into sysPass I'm getting same error and can't see any entries

**Comment by lukasp2** [comment]
maybe a PHP 7.x error?

**Comment by nuxsmin** [comment]
Not sure...I would need to test it

**Comment by lukasp2** [comment]
Good news: After switching from PHP 7.1 to PHP 7.0 it's working fine!

**Comment by nuxsmin** [comment]
Mmm, there would be some unexpected behavior within PHP 7.1

**Comment by lukasp2** [comment]
seems so. I will then let my config running with PHP 7.0
I hope you can fix it easily

**Comment by nuxsmin** [comment]
Sure, I'm reading the 7.1 release notes to get some info...

**Comment by lukasp2** [comment]
seems so. I will then let my config running with PHP 7.0
I hope you can fix it easily

**Comment by nuxsmin** [comment]
PHP 7.1 has many changes and a big one is mcrypt, which is deprecated in favour of OpenSSL, and sysPass encryption relies on mcrypt, so I would need to work hard to get it working fine...I go fast but not so :))

**Comment by lukasp2** [comment]
Okay I undestand. Maybe you give a hint in your Wiki that sysPass users sould use max. PHP 7.0

**Comment by nuxsmin** [comment]
Right!. I will add a check too. Thanks for the feedback!

Then it works fine now?

**Comment by lukasp2** [comment]
you're welcome :)

yes, I can finally begin to add all my accounts / passwords :)

**Comment by nuxsmin** [comment]
Great!

**Comment by nuxsmin** [comment]
Here is my current environment, you can safely use sysPass but be aware to perform backups regularly :)
![003](https://cloud.githubusercontent.com/assets/1775774/22525105/3bce3696-e8c6-11e6-8614-fc8b0e9576b5.jpg)

**Comment by lukasp2** [comment]
Wow many many entries :-) 
Cron scheduled backup option would be very nice

**Comment by nuxsmin** [comment]
Sure, but you can do it by using the API (local or remotely)

**Comment by lukasp2** [comment]
really ? Cool, can you please tell me how to do this?

**Comment by nuxsmin** [comment]
First of all you need to generate a token by using the API Authorizations tab  and then execute this script in a local o remote PC with PHP installed (there are many JSON-RPC clients on the internet...)

https://gist.github.com/nuxsmin/62338b33178544894cd7237c7fe170bd

**Comment by lukasp2** [comment]
Thank you very much I will try it

**Comment by nuxsmin** [comment]
The API methods implemented are:

- Accounts search/view/add/delete
- Customers search/add/delete
- Categories search/add/delete
- Backup

**Comment by lukasp2** [comment]
Great possibilities !
