### ISSUE TITLE
standard complexity

### ISSUE THREAD

**Issue by derStephan** [nuxsmin/sysPass#400]
Hi,

I just tried your software (1.2 stable) and really like it. I have a feature request. 

Could you add a global setting for password complexity? Now it is always 12 characters with letters, numbers and special chars. I think, 12 characters are a bit short for passwords I never need to remember.  

So I would like to set 20 as default length. Would that be possible?

And by the way... From which special chars does the software choose from when including those?

**Comment by nuxsmin** [comment]
Added to roadmap #422
