### ISSUE TITLE
Import Error (2.0RC4)

### ISSUE THREAD

**Issue by MAndretti** [nuxsmin/sysPass#401]
Hi,

1) Export Accounts
2) download xml file
3) XML Import -> click "File upload"
4) select xml file
5) Internal Server Error is shown
6) no entry in "Event log"

Decryption error, referer: https://server/index.php
PHP Warning:  DOMDocument::loadXML(): Start tag expected, '&lt;' not found in Entity, line: 1 in /srv/syspass/inc/SP/Import/SyspassImport.class.php on line 113
PHP Catchable fatal error:  Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given, called in /srv/syspass/inc/SP/Import/SyspassImport.class.php on line 76 and defined in /srv/syspass/inc/SP/Import/SyspassImport.class.php on line 114, referer: https://server/index.php

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Hello, has the XML file any content?

I've just imported an XML file with ~2000 accounts without any issue.

**Comment by MAndretti** [comment]
Yes, looks like a normal xml file.

**Comment by nuxsmin** [comment]
Ok, let me do some tests, because you have build a password encrypted XML file....

**Comment by nuxsmin** [comment]
It seems that you didn't set the right encryption key, so the XML nodes couldn't be decrypted.

I've coded some checks to avoid that behavior (not working in debug mode because output "warnings" break the JSON)

**Comment by nuxsmin** [comment]
In addition, a new attribute is added (during export) to the encrypted data node in order to check the key's hash before parsing the data.

**Comment by MAndretti** [comment]
Ok, I'm going to test the fix next week.

**Comment by MAndretti** [comment]
I performed various tests. Looks very good now.

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
Thanks for your testing and feedback!
