### ISSUE TITLE
Error while updating entry

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#402]
Hi Rubén,

I'm creating my entries in sysPass which is w/o any problems possible, but when I try to update an existing entry I get this error:

> Error while querying
> SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'account_passDateChange' at row 1 (22003)
> SQL : '
> UPDATE accounts SET account_customerId = :accountCustomerId,
> account_categoryId = :accountCategoryId,
> account_name = :accountName,
> account_login = :accountLogin,
> account_url = :accountUrl,
> account_notes = :accountNotes,
> account_userEditId = :accountUserEditId,
> account_dateEdit = NOW(),account_passDateChange = :accountPassDateChange,
> account_isPrivate = :accountIsPrivate,
> account_isPrivateGroup = :accountIsPrivateGroup,
> account_parentId = :accountParentId,
> account_userGroupId = :accountUserGroupId,
> account_otherUserEdit = :accountOtherUserEdit,
> account_otherGroupEdit = :accountOtherGroupEdit
> WHERE account_id = :accountId' 

What's wrong?

Thank you & BR,
Lukas

**Comment by nuxsmin** [comment]
Hi Lukas, it seems to be an issue with the password expiry date. Did you set any date?

**Comment by lukasp2** [comment]
Ah okay. At creation of this Item I deleted the expire date and now it is set to "1970-01-01". 
When I delete the expire date while updating my entry it is working.

Maybe a feature request to disable expired date for selected  items? :-)

**Comment by nuxsmin** [comment]
I'll take a look why a blank expiry date caused that issue, because 0 means (in Unix time) 1970-01-01, so it should be saved correctly.

Thanks for the feedback!

**Comment by lukasp2** [comment]
thank you for your really fast support !

**Comment by nuxsmin** [comment]
Solved

**Comment by dvdfabian** [comment]
Hello,

we had the same problem with the password expiry field. Updating an existing account was impossible without manually deleting the expiry field.

I found the cause of the bug. It is related to the time zone-aware recalculation of the HTML date field. When 1970-01-01 is pre-filled in the field and syspass is set to a non-default time zone, the javascript code may produce a negative UNIX timestamp which violates a DB constraint. My fix was to add Math:max(0, getUnixTime()) on line 316 in app-theme.js. Then, everything starts working. Of cource, a better solution wuld be to bound the timestamp value on the server side.
