### ISSUE TITLE
Feature request: Custom fields for Customers entries

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#403]
Hey Rubén,

it would be very nice to create custom fields for selected customer. Is it possible to implement this into your code?

Thank you & BR,
Lukas

**Comment by nuxsmin** [comment]
Hi Lukas,

Do you mean a custom field only for one customer?

**Comment by lukasp2** [comment]
yes

**Comment by Yotouille** [comment]
Hi !

Do you think it is possible to add the same feature for "Categories" ?

Many thanks !

**Comment by nuxsmin** [comment]
Added to roadmap #422
