### ISSUE TITLE
Custom fields: Password not showing correctly

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#404]
Hi again,

I created some custom fields and 2 of them are Type -> Password. It is possible to fill the password fields and save them withing my entry.

After opening my entry I can't get my saved password because there are just 3 stars (when I go to the eye right from custom password field).

Can you please check it and tell me if I'm doing something wrong?

Thank you,
Lukas

**Comment by nuxsmin** [comment]
Hi!

Which module did you set the custom field for?

The password is shown if your profile has set the view pass option or you are viewing a module other than accounts

**Comment by lukasp2** [comment]
I choosed accounts.

Hm, I don't see any "view pass option" in my profile?

**Comment by nuxsmin** [comment]
It's the third option in the profile view.

**Comment by lukasp2** [comment]
I'm logged in as Admin. Is it neccessary to set these profile options for Admin user too??

**Comment by nuxsmin** [comment]
Right, that's not needed when you're application admin

**Comment by lukasp2** [comment]
okay, good to know that :)

Other question: Is there any option to copy the password to clipboard from custom field like the "copy password to clipboard" function ?

**Comment by nuxsmin** [comment]
I found the issue, the password is shown in the account details view and not in the edit view.

**Comment by lukasp2** [comment]
ok fix is also comming ? :)

**Comment by nuxsmin** [comment]
Sure, it will be fixed tomorrow ;)

**Comment by lukasp2** [comment]
great :-)

**Comment by lukasp2** [comment]
Hey my favorite coder :-)

What's the current status?

**Comment by nuxsmin** [comment]
Hey!

Sorry for the delay, I've been working hard on documentation...

I've just pushed to the devel branch.

**Comment by lukasp2** [comment]
Good morning Rubén,

thank you!

Other question: Is there any option to copy the password to clipboard from custom field like the "copy password to clipboard" function ?

**Comment by nuxsmin** [comment]
Good morning Lukas!

Sure, let me do some tweaks to get it.

**Comment by lukasp2** [comment]
sounds very good :-) Merci!

**Comment by nuxsmin** [comment]
Done ;)

**Comment by lukasp2** [comment]
Perfect, big thanks to you!
