### ISSUE TITLE
Kee Pass feature

### ISSUE THREAD

**Issue by AshHaque** [nuxsmin/sysPass#405]
Hi nuxsmin,

I was waiting to get sysPass v.2 with all 14 features specially the kee pass # 268 one. By when I can expect this version?

Thanks for your effort.

Ash

**Comment by nuxsmin** [comment]
Hi @AshHake

sysPass v2 would be released at the end of this week. I'm currently working on the documentation and the website.

About the incoming features, I'm sorry, but that related with keepass exporting hasn't been analyzed yet.

Kind regards.

**Comment by AshHaque** [comment]
Thanks nuxsmin,

Having that feature would be good. Anyway, is there any chance to get user specific password import feature? Like user will be able to import only those passwords s/he has access to. In this way s/he can keep them in a local instance in his/her laptop.


Thanks again man for your great effort.


Ash

**Comment by nuxsmin** [comment]
You're welcome @AshHaque!

Sure, that feature is in the to-do list, but the sysPass development, in general, was lasting too much because the added features and code improvements, so I needed to cut out the goals...

Kind regards

**Comment by nuxsmin** [comment]
Added to roadmap #422
