### ISSUE TITLE
Feature: Limit Category Search to select users.

### ISSUE THREAD

**Issue by k-s-dean** [nuxsmin/sysPass#409]
Would it be possible to exclude the viewing of available category's for certain users, 

this is a security feature request as we want to block some of our personnel from knowing about certain category's e.g. 

in category's we have placed multiple host providers(Digital Ocean), we would prefer if some of our personnel could not see this category as they do not need to know which host providers we use.

From a security perspective if they know about the host provider they could try to social engineer their way in to an account.

Kind Regards 

k.s-dean

**Comment by nuxsmin** [comment]
Hello, that feature is already implemented (sysPass 2.0-RC4) on the customers select by only showing those customers that are set on the accounts that the user is granted to and those which are not used by any account.

Kind regards
