### ISSUE TITLE
Beta: LDAP Filter error (using always cn=)

### ISSUE THREAD

**Issue by maxmarkus** [nuxsmin/sysPass#41]
Hello, 
Good work so far :-)
I an currently evaluating your beta and found some glitches which you should fix, opening one ticket per error.

It seems the LDAP auth automatically adds cn= as prefix, so even if I use  ou=My Group, I recieve an Error: LDAP FILTER: (cn=ou=My Usergroup). 
Regards, Markus

**Comment by nuxsmin** [comment]
Hi there, how are you doing? Hope well

About this issue, can you give a try again and let me know if it stills occurs?

Kind regards

**Comment by maxmarkus** [comment]
Hi there, unfortunately I am not working at that company anymore and at the
new we don't need ldap. So I cannot give it a try!

2015-01-30 14:31 GMT+01:00 nuxsmin <notifications@github.com>:

**Comment by nuxsmin** [comment]
Uppps, ok, I hope all goes fine and you still use sysPass ;)

Kind regards
