### ISSUE TITLE
Coudnt Install sysPass

### ISSUE THREAD

**Issue by lfreez** [nuxsmin/sysPass#417]
Hi, 

I'm trying to install sysPass on Centos using below guide 
https://wiki.syspass.org/en/install-centos7

I have copied all files to web root and then tried to access it but it showing below..

<?php
/**
 * sysPass
 *
 * @author nuxsmin
 * @link http://syspass.org
 * @copyright 2012-2017, Rubén Domínguez nuxsmin@$syspass.org
 *
 * This file is part of sysPass.
 *
 * sysPass is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sysPass is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 *  along with sysPass.  If not, see <http://www.gnu.org/licenses/>.
 */

use SP\Controller\MainController;
use SP\Core\Init;
use SP\Core\Session;

define('APP_ROOT', '.');

require APP_ROOT . DIRECTORY_SEPARATOR . 'inc' . DIRECTORY_SEPARATOR . 'Base.php';

if (!Init::checkPostLoginActions() && Session::getAuthCompleted()) {
    $Controller = new MainController();
    $Controller->getMain();
    $Controller->view();

**Comment by nuxsmin** [comment]
Hi, that's because the PHP scripts aren't being parsed in that path.

That howto has been written a time ago, so it could be some issues for recent installations. I'll take a look to those steps.

Which sysPass version are you installing?

**Comment by nuxsmin** [comment]
As I can see, you are trying to install sysPass v2 ...

The new doc will be on https://doc.syspass.org

**Comment by lfreez** [comment]
still having same issue for me. installed on centos 7 with files in master.zip but still getting same issue.

define('APP_ROOT', '.');

require APP_ROOT . DIRECTORY_SEPARATOR . 'inc' . DIRECTORY_SEPARATOR . 'Base.php';

if (!\SP\Init::checkPostLoginActions()) {
    $controller = new SP\Controller\MainC(null, 'main');
    $controller->getMain();
    $controller->view();
}

**Comment by nuxsmin** [comment]
That issue is because the PHP script aren't being parsed, so you would need to configure the webserver properly, because any PHP script would fail to execute.
