### ISSUE TITLE
New Translations needed..?

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#418]
Hi Rubén,

congratulations to your final release :-)

I think you need to update your POEditor files. I found in cutom fields settings -> **Área de texto**

Can you check / update POEditor files / lines for german language ? I will translate them.

Thank you,
Lukas

**Comment by nuxsmin** [comment]
Thanks so much Lukas and thanks to you too for the useful feedback!

Right, there are some strings added, but I missed to add them because I was a bit busy... I'll update the Poeditor terms shortly

Kind regards

**Comment by lukasp2** [comment]
Great, I'm waiting to update them :)

**Comment by nuxsmin** [comment]
Just updated ;)

**Comment by lukasp2** [comment]
Done :-)

**Comment by nuxsmin** [comment]
Well done!
