### ISSUE TITLE
'The user has no associated groups' when using LDAP

### ISSUE THREAD

**Issue by st0rmi** [nuxsmin/sysPass#419]
I'm trying to authenticate against a Samba4 AD using the 2.0 Release of sysPass. Whenever I login using an AD Account, it fails with the message 'The user has no associated groups'.

**My LDAP config in sysPass:**
* Enable LDAP: true
* Active Directory: false (because Samba apparently doesn't support inherited group membership)
* Server: `ldaps://dc.example.com:636`
* Bind User: `cn=syspass,cn=Users,dc=example,dc=com`
* Bind Password: `secretpass`
* Search base: `cn=Users,dc=example,dc=com`
* Group: `cn=Domain Users,cn=Users,dc=example,dc=com`
* Default Group: `Users`
* Default Profile: `User`

When I try logging in using the user `adm.max.mustermann`(which is present and working in other applications) I receive the aforementioned error message. The event log shows the following:
 
> The user doesn't belong to the group
> User : CN=Admin Max Mustermann,CN=Users,DC=example,DC=com
> Group : Domain Users

and

> The user has no associated groups
> Type : authBrowser
> Type : authLdap
> User : adm.max.mustermann

I believe this behavior might have been introduced in one of the release candidates of 2.0, as I got this part to work in an earlier version (but ran into other issues which have since been fixed).

**Comment by nuxsmin** [comment]
Hello, that seems to be related to the group RDN, could you try it out by setting only the group name?

Kind regards

**Comment by st0rmi** [comment]
Thanks for the fast response. I replaced `cn=Domain Users,cn=Users,dc=example,dc=com` with just `Domain Users` and received the same error.

I also noticed the following when checking the LDAP config:
> Error while searching objects in base DN
> LDAP ERROR : Success (0)
> LDAP FILTER : (&(|(memberOf=CN=Domain Users,CN=Users,DC=example,DC=com)(groupMembership=CN=Domain Users,CN=Users,DC=example,DC=com))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))

Is a `Success (0)` really indicative of an error here?

**Comment by nuxsmin** [comment]
The query was done fine, but it didn't lookup any user that matches the given filter.

**Comment by st0rmi** [comment]
I got one step further. For some reason the memberof filter does not work for groups containing spaces. `Domain Users` does not work, another group without spaces does.

I do, however, now get the message 'The Master Password is not saved or is wrong' when logging in using the LDAP account. Logging in using the regular admin account still works just fine.

Error message in event log:
> Type : authBrowser
> Type : authLdap
> LDAP Server : ldaps://dc.example.com:636

**Comment by nuxsmin** [comment]
Regarding the group name, could you try it out by adding a backslash before every space?

About the master password, it could be related to the master password hash, because the salt used for the hashing algorithm has changed to fix an unexpected behavior in latest PHP versions. Is there any related messages in the event log?

**Comment by nuxsmin** [comment]
BTW, the group name with spaces should work, because there isn't any notice about escaping spaces within DNs

**Comment by st0rmi** [comment]
Adding a backslash leads to the following error message:
> Error while searching group RDN
> Group : (cn=Domain\ Users)
> LDAP ERROR : Bad search filter (-7)
> LDAP FILTER : (cn=Domain\ Users)

The spaces might actually be an issue on my side or due to samba. An ldapsearch using a memberOf filter from the bash has the same weird behavior.


Event log messages for the first successful login:
INFO (searchUserInGroup):
> User in group verified

INFO (New LDAP user):
> Max Mustermann (Admin) (adm.max.mustermann)

ERROR (Log in):
> Type : authBrowser
> Type : authLdap
> LDAP Server : ldaps://dc.example.com:636

I do not see anything referring to hashing or the master password in there.

**Comment by nuxsmin** [comment]
Regarding the last message, Was it saved as an error?.

Are you running a new sysPass instance or is it an upgrade instead?

**Comment by st0rmi** [comment]
Yes, the last message was saved as an error. The other to are saved as infos.

This is a completely fresh install of sysPass (2.0.0.17021301) installed on an Ubuntu 16.04 server system.

**Comment by nuxsmin** [comment]
Ok, so the master password request is normal, each sysPass instance uses its own encryption keys, so it would request for it even using the same master password and LDAP users.

**Comment by st0rmi** [comment]
For some reason the same also happens with a locally created user.

The following is shown as an error in the event log:
> Type : authBrowser
> Type : authDatabase

I don't know if this is relevant, but in the `usrData` table the fields `user_mPass` and `user_mIV` are empty (not NULL) for both the LDAP user as well as the created local user. For the admin user, both fields are present.

**Comment by st0rmi** [comment]
To test this, I just wiped the MySQL database and deleted all files from the config folder. After a reinstall (using the hosted setup instead of supplying the root login) I did the following:
* Login as admin
* Create group `Users`
* Create profile `User`
* Create local user `test.tester` with the aforementioned group and profile
* Try to login using the user `test.tester` in another browser window (in private mode, in case this matters).

This did not work and I'm asked for the master password again. I'm using build 2.0.0.17021302 now.

**Comment by nuxsmin** [comment]
Ok, but after entering the master password, does it log in?. If so, does it require the master password on next log in?

**Comment by st0rmi** [comment]
Yes, if I enter the master password, the login will work. It didn't ask for the master password again on the next login. The two empty fields I mentioned are now also filled.

**Comment by nuxsmin** [comment]
That is the right behavior :)

More info at: http://doc.syspass.org/en/application/encryption.html

**Comment by st0rmi** [comment]
Huh, then I guess I completely misunderstood how the master key is being used. Thanks for clearing that up.

**Comment by nuxsmin** [comment]
Great!!, I thought that some diagrams (besides some text) could clarify the whole process :)

**Comment by nuxsmin** [comment]
Hi, could you try it out by replacing the spaces with "\20" in the ldapsearch command filter?

**Comment by st0rmi** [comment]
That doesn't work either, sadly.

**Comment by nuxsmin** [comment]
I don't know what could be happening, because the spaces within a CN don't need to be escaped, the only ones that need are the trailing ones.

**Comment by st0rmi** [comment]
I think I might raise this issue with the Samba folks. If I figure out what is going wrong, I will let you know. Thanks for all your help!

**Comment by nuxsmin** [comment]
Great!...you're welcome

**Comment by nuxsmin** [comment]
Hello, did you find out any working solution?
