### ISSUE TITLE
Syspass V2 Install Throws Fatal Error

### ISSUE THREAD

**Issue by k-s-dean** [nuxsmin/sysPass#421]
Hi recently tried to upgrade from RC4 to syspass V2 but getting the following error using PHP7.0. 

Seems we cannot create the database/ syspass cannot create the database and shows an internal error.

```
PHP Fatal error:  Uncaught Error: Call to undefined function SP\\Core\\utf8_encode() in /var/www/html/syspass/inc/SP/Core/Installer.class.php:243\nStack trace:\n#0 /var/www/html/syspass/inc/SP/Core/Installer.class.php(118): SP\\Core\\Installer->setupMySQLDatabase()\n#1 /var/www/html/syspass/ajax/ajax_install.php(55): SP\\Core\\Installer->install()\n#2 {main}\n  thrown in /var/www/html/syspass/inc/SP/Core/Installer.class.php on line 243, referer: IP_HIDDEN
```

Kind Regards 

K.s-dean

**Comment by nuxsmin** [comment]
Hi, it seems that you need to install the PHP XML module, because the "utf8_encode()" function is included in that package.

**Comment by nuxsmin** [comment]
Which distribution are you running on?

**Comment by k-s-dean** [comment]
Thanks, just moved the install to a new machine and i thought i had installed that package, user fault -_- just came across this myself after some googling sorry, I'm running Ubuntu 16.04.  thanks for the speedy response.

**Comment by nuxsmin** [comment]
Great!! Thanks for the feedback ;)
