### ISSUE TITLE
"View password" doesn't auto-hide the password again

### ISSUE THREAD

**Issue by robert-scheck** [nuxsmin/sysPass#423]
Once I click "View password", the username and password is shown on the screen, but it doesn't seem to be hidden again automagically after e.g. 30 seconds (after 5 minutes of inactivity, I had an auto-logout though). Maybe there is a configuration option for "auto-hide", but I didn't see an obvious option in the public demo.

**Comment by nuxsmin** [comment]
Hi, that feature has been already  implemented through a Javascript timer on https://github.com/nuxsmin/sysPass/blob/master/js/app-actions.js#L785 function and https://github.com/nuxsmin/sysPass/blob/master/js/app-actions.js#L811 line

**Comment by robert-scheck** [comment]
That means...the public demo is outdated or configured wrong?

**Comment by nuxsmin** [comment]
It works fine in FF 51 and Chrome 56.

Note that you would need to enter in the password box to activate the timer.

**Comment by robert-scheck** [comment]
Testing using Chromium 56 here: I just click "View password", leave the computer for something (like an average user might do) and when returning after a few minutes, the password can be still read on the screen. No further mouse interaction after initially clicking "View password".

**Comment by nuxsmin** [comment]
You're right, but the current behavior is implemented by moving or clicking with the mouse over the floating password box.

**Comment by nuxsmin** [comment]
Hello, this behavior has been fixed in the latest commit.

Thanks for the feedback!
