### ISSUE TITLE
Option to suggest password change with user deletion

### ISSUE THREAD

**Issue by robert-scheck** [nuxsmin/sysPass#426]
When a user is deleted, it would be quite handy to have an option that allows to mark all passwords which the deleted user actually accessed, with something like "password should be changed". The more simple way would be to mark all passwords "to be changed" where the deleted user had access to (based on actual permissions/ACLs) rather the (better, but) extensive variant that requires tracking of what has been accessed by a user.

**Comment by nuxsmin** [comment]
Nice feature!

**Comment by nuxsmin** [comment]
Added to roadmap #422
