### ISSUE TITLE
Link logo in upper left with e.g. "Search" or "back in browser history"

### ISSUE THREAD

**Issue by robert-scheck** [nuxsmin/sysPass#427]
When trying sysPass, I found myself now a couple of times clicking to the sysPass logo in the upper left corner in situations

- where I wanted to go "back in browser history" as in "previous page", or
- where I expected the "Search" page functionality again (I know, there is the magnifier)

While it's just a minor thing, it could enhance the (end)user experience.

**Comment by nuxsmin** [comment]
Hello, that behavior has been implemented in the latest version.
