### ISSUE TITLE
Functionality of New User - Password Change?

### ISSUE THREAD

**Issue by k-s-dean** [nuxsmin/sysPass#428]
Hi,
I'm getting the following in the event log.

User updated
Could not perform the password change request.

Could you please explain the functionality of this feature. I noticed in another issue that someone mentioned that this is linked to email ?

## Expected behaviour

simple password is generated then handed out to user.

User is forced to change password on login.

Kind Regards 

K.s-Dean

**Comment by nuxsmin** [comment]
Hi, do you have email notifications enabled?

Kind regards

**Comment by k-s-dean** [comment]
No we will not be using that feature at this moment in time, it may be used in the future.

**Comment by nuxsmin** [comment]
That is the problem, because you need to have the notifications enabled to send an email to the user. This email will tell some instructions and an unique hash to change the password.

**Comment by nuxsmin** [comment]
You're right. After inspecting the code, that behavior makes no sense, so it has been removed.

It was solved in the latest commit.

**Comment by k-s-dean** [comment]
Hi, 

After reviewing your commit this issue does not seemed to be resolved. 
I removed the code in our syspass which you specified. ( we get the following error: please see .png)![login-error](https://cloud.githubusercontent.com/assets/23525195/22971537/f0c40d76-f36d-11e6-901e-d463476f89ea.png) 


I will try and explain your current work flow. 

## Current Behaviour
Setup Email > Password Change is sent by email > User Changes Password

The above work flow is fine if you are using email.

---

Our Work flow.

## Expected Behaviour

Create User > Select password change> user given login info > At first login: password change required

## Example

![change-windows-8-password](https://cloud.githubusercontent.com/assets/23525195/22971816/e97c5360-f36e-11e6-8b74-f80cd41a045c.png)

If email is not being used, there needs to be a way for a user to change password on first login if requested or needed.

Kind Regards 

K.s-Dean

**Comment by nuxsmin** [comment]
Hi, this issue should be solved in the latest release.

Kind regards

**Comment by nuxsmin** [comment]
Solved
