### ISSUE TITLE
Feature - Search Custom Fields

### ISSUE THREAD

**Issue by k-s-dean** [nuxsmin/sysPass#429]
We would like to be to search custom fields. 

Kind Regards 

k.s-Dean

**Comment by nuxsmin** [comment]
Hi, this question has been discussed a time ago, and currently it isn't possible to get it because the custom fields data is encrypted, so it would require to decrypt all the data when performing every search and that would impact on the server performance.

**Comment by k-s-dean** [comment]
Ok, Thanks we shall use tags instead. 

Kind Regards

k.s-dean

**Comment by nuxsmin** [comment]
Great!

Kind regards
