### ISSUE TITLE
missing translation in config-check

### ISSUE THREAD

**Issue by derStephan** [nuxsmin/sysPass#434]
I just tried to install current master. After uploading everything, I got a message in Spanish language saying that permissions of /config directory were wrong. 

My language is German but if this information is not available at this time point, all messages should be English, shouldn't they?

**Comment by nuxsmin** [comment]
Hi, do you have the es_US locales installed?

**Comment by derStephan** [comment]
I just cloned master branch from git and uploaded everything to my hoster. If it is not included in there, then I did not install it.

**Comment by nuxsmin** [comment]
The locales need to be installed on the OS, because sysPass relies on GNU gettext for localization.

**Comment by derStephan** [comment]
This is a hosted server, so I don't know that. But after correcting the rights of the folder, everything is correctly translated to German.

**Comment by nuxsmin** [comment]
Sorry, I'll fix that, because the language is set after config checks, so if any check fails, it would display the original strings.

**Comment by nuxsmin** [comment]
Fixed
