### ISSUE TITLE
Can't save customer anymore after adding custom field. 

### ISSUE THREAD

**Issue by wernerreuser** [nuxsmin/sysPass#435]
I had a few customers in SP 2.0 and decided to add a custom field...

Type text and made it a required field... When I open an existing customer now, fill in the new field and click save it gives me a message 'Customer not found'. If I remove the custom field from Customers items can be saved again. 

Probably related... With the new custom field adding a new Customer doesn't give an error but the custom field's value is not saved. If I try to edit it it also gives 'Customer not found'

**Comment by nuxsmin** [comment]
Hello, it should be solved in the latest commit. The custom field wasn't updated because the returning code from updating the customer data was wrong when the current data was the same than the stored one.
