### ISSUE TITLE
Import doesn't use default group

### ISSUE THREAD

**Issue by wernerreuser** [nuxsmin/sysPass#436]
Since updating from 1.2 to 2.0 gave me a lot of troubles I decided to do a fresh install of 2.0 and import my accounts. So I did, installation went fine and I only needed to reconfigure some stuff. 

When I ran the 'Import Accounts'  option importing itself seemed to work fine, only when I opened an account it got the wrong default group. 

Solved this with a query to change the group id, since this database was empty when I did the import that was ok to because it involved all records.

**Comment by nuxsmin** [comment]
Did you mean a CSV import or an XML instead?

**Comment by wernerreuser** [comment]
Hi Ruben

I used XML import... used the export made with 1.2 as import file...
By the way, all account info was imported properly but all passwords were empty. Could that be caused by me using a different master password for the new installation ?

Best regards,

Werner 

⁣Verzonden door BlueMail ​

Op 15 feb. 2017 21:04, bij 21:04, "RubénD" <notifications@github.com> schreef:

**Comment by nuxsmin** [comment]
Hi Werner, sure, you would need to provide the master password used by the export on the import process.

Best regards

**Comment by wernerreuser** [comment]
Thanks... had a feeling I screwed up ;)

Is that also applicable on the wrong group issue ?

**Comment by nuxsmin** [comment]
Ummm, you don't need to change the master key on source, you only would need to provide the master key when importing the XML on the target.

**Comment by wernerreuser** [comment]
Ahh ok... thanks !

Op 16-2-2017 om 19:14 schreef RubénD:
>
> Ummm, you don't need to change the master key on source, you only 
> would need to provide the master key when importing the XML on the target.
>

**Comment by nuxsmin** [comment]
I'll take a look to the group issue...

**Comment by davidkast** [comment]
Hola Ruben, ante todo muchas gracias.
Tal como comenta el wernerreuser, tengo el mismo problema, cuando importo el XML y selecciono el grupo y usuario, omite lo seleccionado y importa con el grupo y usuario logado en el momento en syspass.

Gracias.

**Comment by nuxsmin** [comment]
Hello,

the wrong user/group on XML/CSV import should be fixed. The expected form variables were wrong.

Thanks for the feedback.

@davidkast Ya debe de estar solventado, era una incidencia tonta con el nombre de los campos del formulario. Gracias por avisar!

**Comment by davidkast** [comment]
@nuxsmin Hola, actualmente tengo instalada la versión 2.0.0.17021601 (fui actualizando de la versión 2.0 final hasta esta última) y sigue el mismo problema.
Dices que esta solventado para esta versión o para alguna actualización que aun no se ha posteado?

Gracias.

**Comment by nuxsmin** [comment]
Buenas @davidkast aún no está lanzado como release, pero puedes descargar los últimos cambios desde la rama master: https://github.com/nuxsmin/sysPass/archive/master.zip
