### ISSUE TITLE
Updating from 1.2 to 2.0.0

### ISSUE THREAD

**Issue by efazenda** [nuxsmin/sysPass#437]
Dear all,

I wanted to update my Syspass instance from version 1.2 to 2.0.0 , so i have followed the documentation here : https://doc.syspass.org/en/updating.html

On the part : Copy the files (“config.xml”, “key.pem” y “pubkey.pem”) within the “config” directory from the current version to the new one

On my directory config/ of my current instance of syspass i don't have a config.xml but only a config.php
, is this normal ?

Best Regards, Edouard

**Comment by nuxsmin** [comment]
Hello @efazenda 

that's right, I'll fix the doc. When upgrading from 1.2 the config file "config.php" need to be copied, then on the upgrade process, it'll be converted to XML.

Kind regards

**Comment by efazenda** [comment]
Ok thanks , so i have copied the config.php in the config dir of the new instance of syspass and now when browsing the page it present me the a webpage "Installation 2.0"  is this normal , sorry maybe i miss some steps :)

**Comment by nuxsmin** [comment]
No worries...you would need to delete the existing XML file and it should display the upgrade page.
