### ISSUE TITLE
Ideas for features

### ISSUE THREAD

**Issue by wernerreuser** [nuxsmin/sysPass#438]
Hi, 

First of all, thank you for developing this cool tool :)

I have some ideas for new features...

- Be able to add tags to categories and customers
- Enum type custom field to force specific values (fi yes/no). Dropdown or checkbox or something like that.
- Be able to view tags or custom fields in the overviews. 
- Search on tags and custom fields. 
- Categories in Categories for more fine grained viewing. 
- Set access properties on a Category and have it inherit to Accounts in it.
- Permissions allow to add multiple user or groups but setting 'Enable edit' is the same for every user/group I add, would be nice to be able to set edit properties per user/group.

**Comment by wernerreuser** [comment]
I found a new reason for access rights on Categories and inherit them. I'd like to use the API for adding new  Accounts and in the current state I still have to login into SysPass and add all access rights.

**Comment by nuxsmin** [comment]
Nice features. Let me some time to analyze them and I'll be back, because I'm focused on solving the upgrading issues...

**Comment by wernerreuser** [comment]
Take your time, no hurry ;) Fixing issues is more important. In the mean time I already have some more ideas. I will collect them and send them later. Will see if I can make some time to implement some myself.

**Comment by nuxsmin** [comment]
Thanks!

**Comment by nuxsmin** [comment]
Sorry for the late reply (I missed your requests :( )

Some of your requests have been replied on #665 and some others added to roadmap #422 

Thanks for the feedback!!
