### ISSUE TITLE
LDAP >1000 Users

### ISSUE THREAD

**Issue by zulink** [nuxsmin/sysPass#439]
Hello!!

I apologize if this question repeated

Problem,  that  LDAP, don't load more than 1000 users
It's really to fix it?
![image](https://cloud.githubusercontent.com/assets/25300170/22973410/a2c47f40-f38e-11e6-8310-b941af4b9a90.png)

Many THX!

**Comment by nuxsmin** [comment]
Hello!!, no worries about your question, I forgot to implement it. I've just pushed to the master branch the code that should solve it ;)

**Comment by zulink** [comment]
Thank you!!

**Comment by nuxsmin** [comment]
You're welcome...Did it work?

**Comment by zulink** [comment]
Yes
Still no problems

**Comment by nuxsmin** [comment]
Great!..thanks for the feedback ;)
