### ISSUE TITLE
Error Updating to 2.0

### ISSUE THREAD

**Issue by CyrosX** [nuxsmin/sysPass#440]
Hello there,
I've tried it twice but there is an with the database when upgrading to 2.0. 
The passwords seem to be deleted now (I've got a backup!)

Version : 1316011001
ERROR : Error en la consulta (42000)
(This is the mail with error notify)

**Comment by CyrosX** [comment]
/By the way/ - is it not possible to run sysPass as Docker on Synology? (Didn't get it working several times)

**Comment by nuxsmin** [comment]
Hello, I have done some tweaks on the master branch that would solve the upgrading issues. Could you try it out?

**Comment by CyrosX** [comment]
Umm, sorry it didn't work either. I could perform the upgrade, login and stay logged in for a while but then some e-mails arrived in my inbox concerning a database update (again?) and syspass gets in something like a maintenance mode.
I've attached a protocol!
[err.txt](https://github.com/nuxsmin/sysPass/files/782966/err.txt)

**Comment by CyrosX** [comment]
// What is the default ID?

**Comment by nuxsmin** [comment]
Hi @CyrosX 

The default ID is the item ID to be used for those orphan items. It means that some database records have a non-existent ID, because it was deleted before, so now, in order to apply the database constraints, an item ID is needed for those records. It mostly could be set to the admin ID (if the item requires an user ID) which would be 1 if you didn't delete it ever.

**Comment by CyrosX** [comment]
Ah ok thanks. I've tried it at the first time with 1 (second time with 2) same result. 
Are the errors related to the ID thingy?

**Comment by nuxsmin** [comment]
Did you still receive the same error?

**Comment by CyrosX** [comment]
I didn't copy the protocol both times, but I think so

**Comment by nuxsmin** [comment]
Hi, you would need to restore the database an then run the upgrade process and provide the right IDs. I don't know if you did it before, because in the event log there are many entries that seems that the upgrade is done (with errors) but you have logged in although them.

**Comment by CyrosX** [comment]
I've tried it again.:
Downloaded new syspass and renamed it and copied the old config folder into it. 
After the update process I get a sucessfull email and an error mail:

Version : 1316100601
ERROR : Restricción de integridad (23000)

**Comment by nuxsmin** [comment]
Did you get it from the master branch instead of releases?

**Comment by CyrosX** [comment]
https://github.com/nuxsmin/sysPass/releases/tag/2.0.0.17021601
This one. Is this the wrong one?

**Comment by nuxsmin** [comment]
Right, that is an outdated release  that will be replaced by a new tag when the master branch is ready (until upgrading issues are gone).

You would need to download from: https://github.com/nuxsmin/sysPass/archive/master.zip

**Comment by CyrosX** [comment]
Ok did it: 
But now syspass is in maintenance mode for a while hm..

**Comment by nuxsmin** [comment]
If you can't log in, please edit the config.xml file and set `<maintenance>0</maintenance>`

**Comment by CyrosX** [comment]
Hm I've changed it but:
Now it wants to start the upgrade process again.
But when I click on the upgrade link nothing happens (only URL change) and it stays on the message that an admin is needed.

**Comment by nuxsmin** [comment]
Please remove also the `<upgradeKey>`  tag (you can safely remove the whole line)

**Comment by CyrosX** [comment]
Somehow it lead to the Installation 2.0 :octocat:

**Comment by nuxsmin** [comment]
Do you mean that it displays the installation page? I could be because the config file is wrong, could be? Is there any error in the webserver log?

**Comment by nuxsmin** [comment]
Hello, could you try it out with the latest release?

**Comment by nuxsmin** [comment]
This thread will be discussed on #466

**Comment by CyrosX** [comment]
Sorry! I was in the holidays. I've tried it again with the newest version and it worked fairly well! I used the preset user ID 0 and my admin account and the master password. Was this correct (especially with the ID?). Great release btw!

**Comment by nuxsmin** [comment]
Hello!, nice to hear from you!

That is right, by setting the user ID to 0 it would have created an user named "orphan user" that is assigned to those accounts (in history too) that had the user ID in blank.

Thanks for the feedback and support!
