### ISSUE TITLE
Upgrading to 2.0

### ISSUE THREAD

**Issue by nuxsmin** [nuxsmin/sysPass#441]
Hello all,

There are some issues related to items constraints when upgrading to sysPass 2.0, that is some items have been removed and left others orphan, so those items would need to be modified to set an existing item before applying the constraints.

On 2.0 version this won't occur because INNODB constraints are used, so related items couldn't be deleted.

I'm working on a solution for this issue. Please, use this thread for those related issues.

Kind regards

**Comment by nuxsmin** [comment]
Related #430 #437 #440

**Comment by Yotouille** [comment]
Hello,

I'm still not able to upgrade from 1.2 to 2.0, same _constraint_ error. I've quit trying to upgrade our production database and now doing my tries on a test environment.

I'm doing the upgrade from `v1.2.0.21` to `v2.0.0.17021601` and from `v1.2.0.21` to `master`. I'm only doing a fresh install on v1.2, create one customer, one category, one account; admin id is 1 and only user, finally there's no orphan item detected before upgrade to v2 but the upgrade process fail.

The same error is thrown in log when upgrading on these 2 tests (and same error as production upgrade):

```
Error en la consulta
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`syspass`.`#sql-1_36`, CONSTRAINT `fk_accounts_user_edit_id` FOREIGN KEY (`account_userEditId`) REFERENCES `usrData` (`user_id`)) (23000)SQL : 'ALTER TABLE `accounts` ADD CONSTRAINT `fk_accounts_user_edit_id`FOREIGN KEY (`account_userEditId`)REFERENCES `usrData` (`user_id`) ON DELETE RESTRICT ON UPDATE RESTRICT'
```

```
Error al aplicar la actualización de la Base de Datos.
Versión : 1316100601
ERROR : Restricción de integridad (23000)
```

Database is MariaDB 10.1 (docker official container)

Maybe I'm doing something wrong in the process ?

**Comment by nuxsmin** [comment]
Hello @Yotouille 

could you take a look to `account_userEditId` value in the accounts table?. In previous versions it wasn't set so the upgrade would fail. The weird stuff is that the upgrade didn't notice about that value...

Kind regards

**Comment by Yotouille** [comment]
I've just check the values ! There's only one account so one entry in 'accounts' table:

  - Before upgrade: value for `account_userEditId` in 'accounts' table is `NULL`
  - After ugprade: value for `account_userEditId` in 'accounts' table is `0`

**Comment by nuxsmin** [comment]
The 0 value would be wrong too...

So, did the upgrade process ask for an ID?

**Comment by Yotouille** [comment]
It did not ask for an ID on the test environment upgrade, only the security key. On our production db it's ask for a valid ID, for we've deleted the admin user a few months ago, I think. On both cases the upgrade fail on the same constraint thing.

**Comment by Yotouille** [comment]
New information on this case, I've been able to apply the upgrade with success on test environment. I've only changed the value for `account_userEditId` on the test account from `NULL` to `1` before starting the upgrade process.

I think I can pass the upgrade on production now, applying the right query on DB before upgrading:
```sql
UPDATE accounts set account_userEditId = 6 WHERE account_userEditId = NULL OR account_userEditId = 0 OR account_userEditId = 1;
```
_Where `6` is my new admin ID_

I'll be back in a few days with the production upgrade result.

Have a nice WE.

**Comment by nuxsmin** [comment]
Hi all,

Luckily I have found the upgrading issue...The process was done right but there is a missed behaviour, a DB transaction is started at the beginning of the process, so the updating queries weren't performed until the whole process has been finished, so the DDL operations were performed when the IDs weren't changed, so they failed...I was so blind...

A new release will be pushed shortly.

Kind regards

**Comment by nuxsmin** [comment]
Hello,

I've released a new update that should fix the upgrading issues. The orphaned items ID are still needed because the app should set those IDs for proper constraints integrity.

You can download it from the master branch.

Hope it works ;)

**Comment by nuxsmin** [comment]
@Yotouille thanks for the feedback. That is a weird issue, because I've performed this update on a DB that had thousands of orphaned items on several tables, and it worked without any issue.

Hope the latest update works fine.

**Comment by nuxsmin** [comment]
This thread will be discussed on #466
