### ISSUE TITLE
Cannot disable 2FA

### ISSUE THREAD

**Issue by fellsho** [nuxsmin/sysPass#442]
Hello,

When I try to disable 2FA I get this message:

"There was an error
Internal Server Errorerror"

And this is error log from apache:

PHP Fatal error:  Call to a member function getIV() on string in /path/to/app/inc/Plugins/Authenticator/ActionController.class.php on line 109, referer: http://syspass.dev/index.php

I'm using v2.0.

**Comment by nuxsmin** [comment]
Hello, if you're the only user that uses 2fa, you can wipe out the plugin data. This option is available on the plugin view.

Meanwhile I'll fix the issue.

Kind regards

**Comment by st3reo** [comment]
I can confirm I have the same issue on CentOS 7

**Comment by HellChords** [comment]
Same issue with debian 8

**Comment by nuxsmin** [comment]
Hello,

the issue has just been solved. There was a code behavior that didn't load the user's plugin data, so it failed when checking this data on saving.
