### ISSUE TITLE
Persistent Docker

### ISSUE THREAD

**Issue by stevetuk71** [nuxsmin/sysPass#443]
Hi,

I have installed in Docker using docker-compose. Can you let me know how I make the data persistent, as it doesn't currently survive server reboot.

error after reboot:
Error 1045: SQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'syspass-app.syspass_default' (using password: YES)

it seems when setting up the application the DB user as per the documentation is "root" It doesn't at face value look like the sp_admin has permissions.

Thanks

**Comment by nuxsmin** [comment]
That issue could occur because the container may change its IP address when restarted, so the DNS name is linked to the last IP address

**Comment by nuxsmin** [comment]
Hi @stevetuk71 be sure that the container data will survive to a server reboot. Though the sysPass container has two volumes, you can map the container directories to the host, so you could do `docker rm syspass-app` without any risk.
If you need to run another sysPass container (ie updating), you could use `--volumes-from` option to map the current volumes to the new container.
Kind regards

**Comment by nuxsmin** [comment]
No worries...that language issue was solved in the latest commit :)

Did it finally work?

**Comment by stevetuk71** [comment]
Yes all working, and survives a reboot.
Thanks
Steve
Nice Work!!

**Comment by nuxsmin** [comment]
You're welcome!. I'm glad that you find it useful :)
