### ISSUE TITLE
Updatin from 1.2 to 2.0

### ISSUE THREAD

**Issue by madcoda9000** [nuxsmin/sysPass#445]
Hello,

i am not able to update from 1.2 to 2.0.

1. i've renamed the webfolder syspass to syspass_old
2. i've created an new webfolder syspass with the new syspass 2.0 contents
3. set the correct permissions with chown to the new folders
4. copied the config files to the new config folder
5. now every time i call the page in my browser, syspass presents the install page??

How can i update?

regards
Sascha

**Comment by nuxsmin** [comment]
Hello,

please, make sure that there isn't an XML file named "config.xml", because if you didn't copy the config.php file before accessing to the sysPass URL, it would have created that file as it was the first time you start sysPass.

**Comment by madcoda9000** [comment]
Hi,

thx for your reply. This is really strange as i have copied the config.php before i've opened the apllication in the browser,. After that syspass have created a config.xml.

Regards
Sascha

**Comment by madcoda9000** [comment]
fyi:

1. i've deleted the config.xml
2. copied my config.php from my old syspass to the new syspass
3. open it in the browser and the install wizard starts

regards
sascha

**Comment by nuxsmin** [comment]
Sure, if so take a look to the XML file, it should be set all the parameters to connect to the database.

Was the config.php file renamed to config.php.old?. The XML file should exist as of sysPass v2

**Comment by madcoda9000** [comment]
yes the config.php was renamed to config.php_old

**Comment by madcoda9000** [comment]
fyi:

the generated config.xml looks like this:

```
<config>
  <accountCount>12</accountCount>
  <accountLink>1</accountLink>
  <accountPassToImage>0</accountPassToImage>
  <backup_hash></backup_hash>
  <checkUpdates>0</checkUpdates>
  <checknotices>0</checknotices>
  <configDate>1487231236</configDate>
  <configHash>f6fe3797151579681e0ecea2e04eff17</configHash>
  <configSaver></configSaver>
  <configVersion>20017021601</configVersion>
  <dbHost></dbHost>
  <dbName></dbName>
  <dbPass></dbPass>
  <dbPort>3306</dbPort>
  <dbSocket></dbSocket>
  <dbUser></dbUser>
  <debug>0</debug>
  <demoEnabled>0</demoEnabled>
  <dokuwikiEnabled>0</dokuwikiEnabled>
  <dokuwikiNamespace></dokuwikiNamespace>
  <dokuwikiPass></dokuwikiPass>
  <dokuwikiUrl></dokuwikiUrl>
  <dokuwikiUrlBase></dokuwikiUrlBase>
  <dokuwikiUser></dokuwikiUser>
  <export_hash></export_hash>
  <filesAllowedExts>
    <item type="filesAllowedExts">PDF</item>
    <item type="filesAllowedExts">JPG</item>
    <item type="filesAllowedExts">GIF</item>
    <item type="filesAllowedExts">PNG</item>
    <item type="filesAllowedExts">ODT</item>
    <item type="filesAllowedExts">ODS</item>
    <item type="filesAllowedExts">DOC</item>
    <item type="filesAllowedExts">DOCX</item>
    <item type="filesAllowedExts">XLS</item>
    <item type="filesAllowedExts">XSL</item>
    <item type="filesAllowedExts">VSD</item>
    <item type="filesAllowedExts">TXT</item>
    <item type="filesAllowedExts">CSV</item>
    <item type="filesAllowedExts">BAK</item>
  </filesAllowedExts>
  <filesAllowedSize>1024</filesAllowedSize>
  <filesEnabled>1</filesEnabled>
  <globalSearch>1</globalSearch>
  <httpsEnabled>0</httpsEnabled>
  <installed>0</installed>
  <ldapAds>0</ldapAds>
  <ldapBase></ldapBase>
  <ldapBindPass></ldapBindPass>
  <ldapBindUser></ldapBindUser>
  <ldapDefaultGroup>0</ldapDefaultGroup>
  <ldapDefaultProfile>0</ldapDefaultProfile>
  <ldapEnabled>0</ldapEnabled>
  <ldapGroup></ldapGroup>
  <ldapProxyUser></ldapProxyUser>
  <ldapServer></ldapServer>
  <ldapUserattr></ldapUserattr>
  <logEnabled>1</logEnabled>
  <mailAuthenabled>0</mailAuthenabled>
  <mailEnabled>0</mailEnabled>
  <mailFrom></mailFrom>
  <mailPass></mailPass>
  <mailPort>25</mailPort>
  <mailRequestsEnabled>0</mailRequestsEnabled>
  <mailSecurity></mailSecurity>
  <mailServer></mailServer>
  <mailUser></mailUser>
  <maintenance>0</maintenance>
  <passwordSalt></passwordSalt>
  <proxyEnabled>0</proxyEnabled>
  <proxyPass></proxyPass>
  <proxyPort>8080</proxyPort>
  <proxyServer></proxyServer>
  <proxyUser></proxyUser>
  <publinksEnabled>0</publinksEnabled>
  <publinksImageEnabled>0</publinksImageEnabled>
  <publinksMaxTime>600</publinksMaxTime>
  <publinksMaxViews>3</publinksMaxViews>
  <resultsAsCards>0</resultsAsCards>
  <sessionTimeout>300</sessionTimeout>
  <siteLang></siteLang>
  <siteTheme>material-blue</siteTheme>
  <syslogEnabled>0</syslogEnabled>
  <syslogPort>514</syslogPort>
  <syslogRemoteEnabled>0</syslogRemoteEnabled>
  <syslogServer></syslogServer>
  <upgradeKey></upgradeKey>
  <wikiEnabled>0</wikiEnabled>
  <wikiFilter/>
  <wikiPageurl></wikiPageurl>
  <wikiSearchurl></wikiSearchurl>
</config>

```

**Comment by madcoda9000** [comment]
my original config.php was this:

`
<?php
// Generated on 1486387675
// This file is generated automatically on installation process
// Please, modify with caution, it could break the application
$CONFIG = array (
  'account_count' => 12,
  'account_link' => true,
  'account_passtoimage' => false,
  'backup_hash' => '5898214d4050e',
  'checknotices' => true,
  'checkupdates' => true,
  'config_hash' => '08bbe390899631bdf49d9c218d768556',
  'dbhost' => 'localhost',
  'dbname' => 'syspass',
  'dbpass' => '*****',
  'dbuser' => 'root',
  'debug' => false,
  'demo_enabled' => false,
  'export_hash' => '589821574e3fc',
  'files_allowed_exts' => 'PDF,JPG,GIF,PNG,ODT,ODS,DOC,DOCX,XLS,XSL,VSD,TXT,CSV,BAK,XLSX,KEY,CERT,PFX',
  'files_allowed_size' => 1024,
  'files_enabled' => true,
  'globalsearch' => true,
  'https_enabled' => false,
  'installed' => 1,
  'ldap_ads' => true,
  'ldap_base' => 'OU=Benutzer,OU=IT,DC=isc,DC=beeline,DC=de',
  'ldap_bindpass' => '******',
  'ldap_binduser' => 'edvadmin',
  'ldap_defaultgroup' => 2,
  'ldap_defaultprofile' => 2,
  'ldap_enabled' => true,
  'ldap_group' => 'CN=GS_syspass,OU=Benutzer,OU=IT,DC=isc,DC=beeline,DC=de',
  'ldap_server' => '10.1.1.100',
  'ldap_userattr' => '',
  'log_enabled' => true,
  'mail_authenabled' => false,
  'mail_enabled' => true,
  'mail_from' => 'it-adm@beeline-group.com',
  'mail_pass' => '******',
  'mail_port' => 0,
  'mail_requestsenabled' => true,
  'mail_security' => 'Disabled',
  'mail_server' => '10.1.1.180',
  'mail_user' => 'sascha.heimann@beeline-group.com',
  'maintenance' => false,
  'passwordsalt' => 'a8f194d2c722c57d6643c2f1bfc26a',
  'proxy_enabled' => false,
  'proxy_pass' => '',
  'proxy_port' => '',
  'proxy_server' => '',
  'proxy_user' => '',
  'resultsascards' => true,
  'session_timeout' => 3000,
  'site_lang' => '',
  'sitelang' => 'en_US',
  'sitetheme' => 'material-blue',
  'version' => '12021',
  'wiki_enabled' => false,
  'wiki_filter' => '',
  'wiki_pageurl' => '',
  'wiki_searchurl' => '',
);
`

**Comment by nuxsmin** [comment]
It seems that it wasn't filled in with old values...very weird..

**Comment by nuxsmin** [comment]
Could you set those values?. The important ones are:
```
  <dbHost></dbHost>
  <dbName></dbName>
  <dbPass></dbPass>
  <dbPort>3306</dbPort>
  <passwordSalt></passwordSalt>
```

**Comment by madcoda9000** [comment]
i'll try...

**Comment by madcoda9000** [comment]
Hello,

i did so. But i only see this screen... :-((

https://www.screencast.com/t/aDsQE7vYPO

**Comment by nuxsmin** [comment]
Sorry, I missed to mention that '<installed>0</installed>' should be set to 1

**Comment by nuxsmin** [comment]
`<installed>0</installed>`

**Comment by madcoda9000** [comment]
ok, this seems to work. But now i got this message: https://www.screencast.com/t/B73vXeraUDWi

What have i to do now?

regards
Sascha

**Comment by nuxsmin** [comment]
You would need to enter a valid IDs for customer and category. That is so because some items were removed when there were relations with others. That behavior was controller by the app on early versions, but now the DB will be responsible for that.

You could take them from the customers and categories tables in the DB.

**Comment by madcoda9000** [comment]
but thenn all accounts will belong to one categiory, or?

**Comment by nuxsmin** [comment]
No, only those orphaned items. Actually they doesn't have either a customer nor category. BTW, those records are related to accounts history which could be removed indeed.

**Comment by madcoda9000** [comment]
ok, thats good to me. I've entered a valid customer id and a valid catefgory id and the key from config.xml.

The i received this message: https://www.screencast.com/t/aGrrfpUtoj

**Comment by madcoda9000** [comment]
by the way, now i am not able to sign in :-(

**Comment by madcoda9000** [comment]
every time i try to login with the admin account (or any other) it tells me i've entered no username and password:  https://www.screencast.com/t/9fscXMwKGLz

**Comment by nuxsmin** [comment]
It seems that the upgrade didn't take place...could you take a look to the webserver error log? There would be some logged messages about what failed.

**Comment by madcoda9000** [comment]
huhhh, there are a lot of errors :-). if you want i can send you the logfile

**Comment by nuxsmin** [comment]
You can paste it in a private gist and share it with me.

**Comment by madcoda9000** [comment]
uhhh, sorry. what is a private gist?

**Comment by nuxsmin** [comment]
That is a Gitub notepaper. Take a look to the button "Gist" at the top of this page.

**Comment by madcoda9000** [comment]
so, i've tried an update from scratch (i have an backup :-)

shortly i'll sennd you a gist with the error.log

**Comment by madcoda9000** [comment]
so i've created the gist

**Comment by madcoda9000** [comment]
oh, thx :-)

**Comment by nuxsmin** [comment]
Could you execute the following query on the DB?:
```
-- I think your database name is 'syspass'
use syspass;
describe accHistory;
```
You can safely post the screenshot (drag&drop on Github issue) :)

**Comment by madcoda9000** [comment]
sure:

https://www.screencast.com/t/GpRVGvLv05

**Comment by madcoda9000** [comment]
fyi. I've resetted everything:

1. restored original 1.2 database
2. deleted the config.xml
3. renamed config.php.old to config.php
4. also i've checked the permissions:

syspass/backup   Owner=www-data
syspass/config     Owner=www-data
syspass/config/*  Owner=www-data  -rwxr-x---

**Comment by nuxsmin** [comment]
Thanks, it's an issue related to the table structure, it warns when the table accHistory is being altered to change the fields definition. That's weird because it warns about the length of a field that is being truncated, but this field is enlarged indeed.

**Comment by madcoda9000** [comment]
ok, what can i do ...??

**Comment by nuxsmin** [comment]
Could take a look to the row 1 of the accHistory table?, what is the acchistory_userEditId value?

**Comment by madcoda9000** [comment]
the Value is NULL

**Comment by nuxsmin** [comment]
Are there any more NULLs?

```
SELECT acchistory_id FROM accHistory WHERE acchistory_userEditId IS NULL
```

**Comment by madcoda9000** [comment]
yes, 37 rows

**Comment by nuxsmin** [comment]
Did you restore the DB?. If not, you'd need to do it and then run this query:

```
UPDATE accHistory SET acchistory_userEditId  = 1 WHERE acchistory_userEditId IS NULL
```
I suppose your admin ID is still 1. Then rerun the upgrade.

**Comment by madcoda9000** [comment]
ok, i understand tzhe following:

1. restore the db and run the query
2. delete the config.xml
3. open the browser and the application
4. do the update if prompted

**Comment by nuxsmin** [comment]
Right, but the config file could be let in place if it has the right values

**Comment by madcoda9000** [comment]
ok, i'll try

**Comment by madcoda9000** [comment]
mhhh, i got this error :-)

error_outline Error while updating database
Compruebe el registro de eventos para más detalles

**Comment by madcoda9000** [comment]
Action: Update DB
Performed by: N/A (10.1.8.223)
Error while updating database.
Version : 1316100601
ERROR : Error en la consulta (1000)

**Comment by nuxsmin** [comment]
Umm, I think it would be the same error...

**Comment by nuxsmin** [comment]
Please, copy (in sysPass root) and run this gist file (pointing your browser to upgrade.php): https://gist.github.com/nuxsmin/950010a3ac12d2a723a1a9fa2d7e01f5

You don't need to restore the DB

**Comment by madcoda9000** [comment]
The for your he'll. So dar. I have to try this tomorrow as I have a meeting now


Regards
Sascha

**Comment by madcoda9000** [comment]
sorry, for this post. My mobile try's to autocorrect :-)

I ment i have to try that tomorrow as i have an appointmnet now.

Many thanks for your help till this point. If this fails too. I'll do a clean install and import the data fro0m the 1.2 installation (if this is possible)

Regards
Sascha

**Comment by derStephan** [comment]
>Many thanks for your help till this point. If this fails too. I'll do a clean install and import the data fro0m the 1.2 installation (if this is possible)

Good question. Is there a possibility to export accounts, users, groups, customers, categories und custom fields and reimport everything back? 

If this is possible, then maybe this is the better way for the upgrade.

**Comment by nuxsmin** [comment]
Currently the XML export will export the accounts, customers, categories and tags, but the other items won't. The purpose isn't to perform a full backup, because some items does have a complex structure that would be tough to replicate through an XML file.

**Comment by derStephan** [comment]
I see. Your response times are incredible. Thanks for that!

**Comment by philippebaque** [comment]
Ops… I have a similar prob when I try to upgrade from 1.2 to 2.0

 had a similar problem when I try too upgrade from 1.2 to 2.0.

A page display this:
"error_outline Error al aplicar la actualización de la Base de Datos
Compruebe el registro de eventos para más detalles "

and a mail saying:
"Action: Mis à jour BDD
Réalisé par: N/A (172.17.9.8)
Erreur pendant la mise à jour de la base de données.
Version : 1316011001
ERROR : Error en la consulta (42)"

When I log on syspass, now all is empty and the logs are:
"
67	2017-02-18 13:11:36	INFO	loadPlugin	ADMIN	172.17.9.8	No es posible cargar el plugin "Authenticator"
666	2017-02-18 13:11:35	ERROR	add	ADMIN	172.17.9.8	Error en la consulta
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspass.plugins' doesn't exist (42)
SQL : '
INSERT INTO plugins SET plugin_name = ?, plugin_data = ?, plugin_enabled = ?'
665	2017-02-18 13:11:35	ERROR	getByName	ADMIN	172.17.9.8	Error en la consulta
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspass.plugins' doesn't exist (42)
SQL : '
SELECT plugin_id,
plugin_name,
plugin_data,
BIN(plugin_enabled) AS plugin_enabled
FROM plugins
WHERE plugin_name = ?
LIMIT 1'
664	2017-02-18 13:11:32	ERROR	getResultsArray	ADMIN	172.17.9.8	Error en la consulta
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspass.account_search_v' doesn't exist (42)
SQL : '
SELECT *
FROM account_search_v
WHERE (account_isPrivate = 0 OR (account_isPrivate = 1 AND account_userId = ?)) AND (account_isPrivateGroup = 0 OR (account_isPrivateGroup = 1 AND
account_userGroupId = ?))
ORDER BY customer_name,
account_name ASC
LIMIT ?, ?'
663	2017-02-18 13:11:32	ERROR	getResultsArray	ADMIN	172.17.9.8	Error en la consulta
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_hash' in 'field list' (42)
SQL : '
SELECT category_id,
category_name,
category_description,
category_hash
FROM categories
ORDER BY category_name'
662	2017-02-18 13:11:32	ERROR	getResultsArray	ADMIN	172.17.9.8	Error en la consulta
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'account_isPrivate' in 'where clause' (42)
SQL : '
SELECT customer_id as id,
customer_name as name \n
FROM accounts \n RIGHT JOIN customers ON customer_id = account_customerId\n
WHERE account_customerId IS NULL \n OR ((account_isPrivate = 0 OR (account_isPrivate = 1 AND account_userId = ?)) AND
(account_isPrivateGroup = 0 OR (account_isPrivateGroup = 1 AND account_userGroupId = ?)))\n GROUP BY customer_id\n
ORDER BY customer_name'
661	2017-02-18 13:11:32	INFO	loadPlugin	ADMIN	172.17.9.8	No es posible cargar el plugin "Authenticator"
660	2017-02-18 13:11:32	ERROR	add	ADMIN	172.17.9.8	Error en la consulta
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspass.plugins' doesn't exist (42)
SQL : '
INSERT INTO plugins SET plugin_name = ?, plugin_data = ?, plugin_enabled = ?'
659	2017-02-18 13:11:32	ERROR	getByName	ADMIN	172.17.9.8	Error en la consulta
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspass.plugins' doesn't exist (42)
SQL : '
SELECT plugin_id,
plugin_name,
plugin_data,
BIN(plugin_enabled) AS plugin_enabled
FROM plugins
WHERE plugin_name = ?
LIMIT 1'

"

thank you for the help

Regards

**Comment by nuxsmin** [comment]
Hi all,

Luckily I have found the upgrading issue...The process was done right but there is a missed behaviour, a DB transaction is started at the beginning of the process, so the updating queries weren't performed until the whole process has been finished, so the DDL operations were performed when the IDs weren't changed, so they failed...I was so blind...

A new release will be pushed shortly.

Kind regards

**Comment by nuxsmin** [comment]
Hello,

I've released a new update that should fix the upgrading issues. The orphaned items ID are still needed because the app should set those IDs for proper constraints integrity.

Hope it works ;)

**Comment by madcoda9000** [comment]
Hello,

many thanks for your fast help. I'll try this release today or tomorrow.

Regards
Sascha

**Comment by philippebaque** [comment]
clap, clap, clap

its working for me…

mil gracias…

**Comment by nuxsmin** [comment]
@philippebaque 

Great!..I'm so glad :)

A tí por las pruebas!! Merci!

**Comment by madcoda9000** [comment]
for its working fine now too. Many thanks for your help. I've donated some books for your support.

Rgerads
sascha

**Comment by nuxsmin** [comment]
Great @madcoda9000 !!

Thanks so much for your donation!!

Have a nice day ;)

**Comment by nuxsmin** [comment]
This thread will be discussed on #466
