### ISSUE TITLE
Error trying to upgrade

### ISSUE THREAD

**Issue by andresju** [nuxsmin/sysPass#446]
Hello,

I'm trying to upgrade to 2.0 from 1.2 and I can't because I found the following error:
`
PHP Fatal error:  Class 'DOMDocument' not found in /var/www/sysPass2/inc/SP/Storage/XmlHandler.class.php on line 105`

Regards

**Comment by nuxsmin** [comment]
Hello, that is related to a missing PHP XML module.

Kind regards

**Comment by ValkyrieUK** [comment]
Hi,

I'm also receiving this error after upgrading from `php5.6.0` -> `php7`.
Tried following the upgrade documentation but it seems there are a few things missing from it.

Cheers

**Comment by ValkyrieUK** [comment]
@andresju You can resolve that by installing the `php7.0-xml` module `sudo apt-get install php7.0-xml` and then restart Apache/NGINX.

**Comment by nuxsmin** [comment]
Sure, I'll review the doc. Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hi @ValkyrieUK, I'm guessing whether the upgrade went fine or not..

**Comment by Yotouille** [comment]
Hey, 'could be `php7-dom` package here.

I need to get it for exemple when installing sysPass on Alpine, but not with Ubuntu (docker images). Maybe some differences on dependencies or default packages between distros/OS, I don't really know.
