### ISSUE TITLE
KeePass XML import

### ISSUE THREAD

**Issue by fellsho** [nuxsmin/sysPass#447]
Hello,

I can't import KeePass exported XML file.

There is an error:

"There was an error
Internal Server Errorerror"

And this is apache error:

PHP Fatal error:  Cannot use Import\\XmlFileImport as XmlFileImport because the name is already in use in /path/to/app/inc/SP/Import/XmlImportTrait.class.php on line 27, referer: http://syspass.dev/index.php

I am using Syspass v2.0.

**Comment by nuxsmin** [comment]
Solved
