### ISSUE TITLE
db login issue

### ISSUE THREAD

**Issue by testor321** [nuxsmin/sysPass#448]
Server version: 5.5.52-MariaDB MariaDB Server
I cannot connect database because of wrong password
mysql -u sp_admin -p syspass

I can change db user password, but in config.php I have

'dbuser' => 'sp_admin'
'dbpass' => ....

Is it possible change/reset password for sp_admin (on db and app side) ?
Thank you

**Comment by nuxsmin** [comment]
Hello,

You could modify those values safely. Be aware that the only value that needs to be untouched is `passwordsalt`.

Kind regards.

**Comment by testor321** [comment]
sorry
how can I modify/generate hash for config.php (dbpass) ?
I am cloning database to another host just to test update.
Seems when I create original sysPass installation (1.2) I saved wrong password for  sp_admin user

**Comment by nuxsmin** [comment]
No worries...

The admin password is a random hash, and it's not encrypted in anyway, so you could set the real password in that field.

**Comment by testor321** [comment]
Thank you
it works !!

**Comment by nuxsmin** [comment]
Great!. You're welcome ;)
