### ISSUE TITLE
Expected behaviour of Upgrading? 

### ISSUE THREAD

**Issue by k-s-dean** [nuxsmin/sysPass#449]
Hi,

Just a quick question on how syspass is updated and how database upgrades are handled. 

We expected that we would be able to supply the same details as before including the database password, a check would then be performed to see if the database matched the current syspass version if yes, syspass would use the old database and Admin passwords.

Is there a reason as to why this is not the case ? 

# Current behaviour 
__Step 1__
Download new syspass > extract archive > backup config directory 
__Step 2__
Delete old syspass files> place new release into directory > set permissions on config and backup
__Step 3__
Backup then delete the database > Finish configuration at web panel > select install
__Step 4__
Restore Database.

# Expected Behaviour
__Step 1__
Download new syspass > extract archive > backup config directory 
__Step 2__
Delete old syspass files > place new release into directory > set permissions on config and backup
__Step 3__
Finish configuration at web panel > select update/install > syspass upgraded. 

Error Thrown: `The Database Already Exists'

![selection_003](https://cloud.githubusercontent.com/assets/23525195/23068516/e573790c-f51b-11e6-8944-368e3adc0b7e.png)

**Comment by nuxsmin** [comment]
Hello, you don't need to run after the 2nd step, because the app would check if any upgrade would be needed, so it will display the upgrade screen.

Kind regards

**Comment by k-s-dean** [comment]
So it is required to remove the database upon re-installing ? we dont need a database upgrade. as we are not upgrading from syspass 1.2

**Comment by nuxsmin** [comment]
No, it isn't needed at all. The app will detect whether a database upgrade is needed or not. You only need to put the files in place.

**Comment by k-s-dean** [comment]
ok, so the above png displays the error we are getting after updating files setting permissions then heading to the web interface. 

We thought that all information had to be re-entered.

**Comment by nuxsmin** [comment]
I noticed that, because you told the current behaviour, so I thought that it shouldn't be so.

**Comment by k-s-dean** [comment]
Hi, 

we carried out the following steps but when importing the database we are sent back to the initial setup screen, we fill in the credentials and still get the same error. how do we restore the data from our sql backup? 

# Steps performed

1. delete database 
2. enter credentials and setup new database 
3. import sql backup
4. syspass goes back to setup screen
5. enter credentials again 
6. error: the database already exists is displayed 

Please advise 

i am also seeing the following error in the log 

`SQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES)`


the DB configuration section on the install screen has the user `root` but is trying to use `sp_admin`

Kind Regards
