### ISSUE TITLE
API - Get password

### ISSUE THREAD

**Issue by Ulrar** [nuxsmin/sysPass#454]
Hi,

I'm trying to get a password I created from the API, to see if syspass would fit our needs.
Here is the command I'm using : 

>curl -X POST -d '{"jsonrpc": "2.0","id": "test", "method": "getAccountSearch", "params": { "authToken": "75ca0b11409403c1d41835defdd994b5d808f3d4", "text": "rootCS" } }' -o - https://demo.syspass.org/api.php

And here is the result : 

>{"jsonrpc":"2.0","result":[{"num_files":"0","usersId":[],"userGroupsId":[],"tags":[],"category_name":"OS","customer_name":"cs","usergroup_name":"Demo","user_name":"","user_login":"","user_editName":"","user_editLogin":"","publicLink_hash":"","account_id":"58","account_userId":"2","account_userGroupId":"2","account_userEditId":0,"account_name":"rootCS","account_customerId":"29","account_categoryId":"4","account_login":"root","account_url":"http:\/\/bla.com","account_pass":"","account_IV":"","account_notes":"","account_otherUserEdit":"0","account_otherGroupEdit":"0","account_dateAdd":0,"account_dateEdit":"2017-02-20 15:22:59","account_countView":"7","account_countDecrypt":0,"account_isPrivate":"0","account_isPrivateGroup":"0","account_passDate":"1487600579","account_passDateChange":"1495231200","account_parentId":"0"}],"id":"test"}

Looks okay, but the password is empty. So I added a token for viewPassword, and I tried that : 
>curl -d '{"jsonrpc":"2.0","id": "test","method":"getAccountPassword","params":{"authToken": "34b75c404564c2e5a8cc8f9fffb14d551234d666", "id":"58"} }' -o - https://demo.syspass.org/api.php

And the result : 

>{"jsonrpc":"2.0","result":{"itemId":"58","pass":""},"id":"test"}

There again, empty password (it's not empty in the web interface).
What am I missing ?

BTW, it'd be great to specify you need a token on the API page (https://doc.syspass.org/en/application/api.html). I lost some time using --user "demo:syspass" before a colleague pasted me a bit of the source code showing you expect a token. The error isn't very helpful either.

Thanks

**Comment by nuxsmin** [comment]
Hello,

sorry about the doc, I forgot to tell that....

Regarding the account's password, you need to provide the token user's password to get it(https://doc.syspass.org/en/application/api.html#getaccountpassword). That is so (by the moment), because the master key is not stored on within the token, so it would need to be get from the users data.

**Comment by Ulrar** [comment]
Hi,

I see, indeed it works that way. But that's not really usable ..
Looks like using userPass: "12345678900" (the master password for demo I believe) doesn't work. Shouldn't it ?

**Comment by nuxsmin** [comment]
It would need the user's password which is "syspass" and not the master password (it won't be required unless you change it)

**Comment by Ulrar** [comment]
Yeah, that does work, but it's not usable to store everyone's password just to use the API.
Since logging as another account (I created "test") still allows you to see the passwords without inputting the creator's password, I assume the master password can decrypt everything. Why can't I use that as the userPass when trying to view a password from the API ? That would allow to use the API  without having to store everyone's password, right ?

**Comment by nuxsmin** [comment]
Ummm, the master password is used to encrypt every account password and custom fields data, that "key" **must be kept secret**, because anyone could get it and then he will have access to any encrypted data.

In the next release it won't be needed (user's password) for those kind of tasks.

**Comment by Ulrar** [comment]
Okay, I understand.
Well unfortunately it won't do then, guess we'll revisit in the next release if we haven't settled on anything else in the meantime.

Thanks !

**Comment by nuxsmin** [comment]
You're welcome!
