### ISSUE TITLE
sysPass upgrade (1.2 to 2.0/master)

### ISSUE THREAD

**Issue by testor321** [nuxsmin/sysPass#456]
Excuse me, but I have a special question
When I start upgrade sysPass I need input valid ID for users, category and customers (3 different fields)
How/where can I find what ID s are valid for this upgrade  procedure? 

Thank you

**Comment by nuxsmin** [comment]
Hello @testor321 
you can get them from the database, the tables where they are stored in are: `customers, categories and usrData`. Actually the user ID, if you didn't removed the "Admin" user, can be 1.

**Comment by testor321** [comment]
thank you
upgrade 1.2 -> 2 has been finished OK with latest master branch.

**Comment by nuxsmin** [comment]
Great!!...After some issues about it, it lets me breathe calmly :)

Thanks for the feedback!
