### ISSUE TITLE
Upgrade 1.2 -> 2.0 (Problema)

### ISSUE THREAD

**Issue by Therliss** [nuxsmin/sysPass#457]
Buenas,

Perdon pero no se expresarme bien en ingles.

http://oi66.tinypic.com/11rtd8x.jpg

¿Que debo arreglar para solucionar este problema?

Gracias

**Comment by nuxsmin** [comment]
Buenas @Therliss 

sin problema...Los elementos huérfanos son aquellos que estaban relacionados con otros, pero estos otros han sido eliminados en algún momento. Anteriormente, la aplicación era la encargada de mantener la relación entre los elementos, por lo que si alguno se eliminaba, sebía de actualizar los registros relacionados. Con esta nueva versión se hace uso de las restricciones  en base de datos, por lo que la coherencia entre los elementos la mantiene el motor de la base de datos (InnoDB).

Dicho esto, y viendo tu captura, sólo necesitas un ID de usuario, por lo que si mantienes el usuario "admin" original, puedes utilizar el ID 1.

Saludos!

**Comment by nuxsmin** [comment]
Hola, funcionó?
