### ISSUE TITLE
Cant Restore data after upgrading error database already exists

### ISSUE THREAD

**Issue by k-s-dean** [nuxsmin/sysPass#458]
Hi, 

we carried out the following steps but when importing the database we are sent back to the initial setup screen, we fill in the credentials and still get the same error. how do we restore the data from our sql backup? 

Relate to #449

# Steps performed

1. delete database 
2. enter credentials and setup new database 
3. import sql backup
4. syspass goes back to setup screen
5. enter credentials again 
6. error: the database already exists is displayed 

Please advise 

i am also seeing the following error in the log 

`SQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES)`

the DB configuration section on the install screen has the user `root` but is trying to use `sp_admin`

Kind Regards

**Comment by nuxsmin** [comment]
Hello @k-s-dean 
the Backup&Recovery plan should be used as a whole, that is you would need to restore the database and the configuration data (stored in the config directory). This config data is very important, because in that file is stored a hash that is used in part of the encryption process (data is not encrypted with it).

To sum up, the config is also needed, because sysPass will proceed as a new installation instead, so it will verify if the database exists.

Another key point, **sysPass doesn't use the root user**, it is only used for the initial installation steps like creating its own database user (sp_admin) and database structure and then it switches to its user for the remaining of the tasks.

Kind regards

**Comment by k-s-dean** [comment]
Hi, Thanks now i understand. 

So i have managed to restore the database. 

some notes, suggestions & concerns.

# Permissions

When carrying out the permission changes on the following folders. 

`config`
`backup`

This allows those folders to be accessible to www-data, however the files inside those folders do not inherit the permissions of the parent folder. 

syspass then has access issues to the following file. `config.xml`

this was why i kept getting the installation screen.

when appplying the correct permissions. 
`chown www-data config/config.xml`
`chmod 744 config/config.xml`

i was able to proceed

# Security 

Security issues became apparent as the following files are now exposed through a web browser.
`config.xml`
`pubkey.pem`
`key.pem`


Anybody on are network can direct their web browser to our URL and view the configuration file.

This is a serious security issue for us.

Can we reference this file somewhere else?

now users know the database name: `syspass` the database user: `sp_admin` and DB pass. 

i suggest that upon installation you allow users to setup the DB themselves for security reasons and do not create the user sp_admin.

The following config directory needs to be relocated to a secure location. As a best practice where possible, avoid referencing usernames & passwords in plain text config files.

Kind Regards

![selection_004](https://cloud.githubusercontent.com/assets/23525195/23209055/756523ae-f8ef-11e6-9c73-5543ac33aeff.png)

**Comment by nuxsmin** [comment]
Hi, those concerns are fine but I wrote some notes about it on:

http://doc.syspass.org/en/application/index.html and http://doc.syspass.org/en/application/security.html

BTW, you can modify the config location in the file `inc/Base.php` (there are some notes inside).

Thanks for the feedback!

**Comment by k-s-dean** [comment]
ahh thank you, i missed that page on your website.

**Comment by nuxsmin** [comment]
You're welcome ;)

**Comment by k-s-dean** [comment]
After Environment configuration on `http://doc.syspass.org/en/installing/debian8.html`

you should reference the security page for securing the app :)

**Comment by nuxsmin** [comment]
Sure I'll do it. Thanks!

**Comment by nuxsmin** [comment]
Solved. The documentation has been modified.
