### ISSUE TITLE
completing germant translation

### ISSUE THREAD

**Issue by madcoda9000** [nuxsmin/sysPass#459]
Hello,

i want to complete the german translation. It seems that it is not fully translated. Bute whe i follow this link (https://poeditor.com/join/project/fmlsBuugyv) to edit the language, it is not possible to select the german language.

Regards
Sascha

**Comment by k-s-dean** [comment]
The files can be modified locally. 

https://poedit.net/download

head to there and download the program. 
Or 
You can edit the file using your favourite text editor. e.g.
`Atom`



clone the repo to your computer. 

go to the following directory and edit the file.

`sysPass/inc/locales/de_DE/LC_MESSAGES/messages.po`

if you are on linux you will be required to download gettext and instructions may differ if your on mac or windows.

`apt-get install gettext`

then run the following once you have translated it to your liking 

`msgcat messages.po | msgfmt -o messages.mo -`

Kind Regards

**Comment by nuxsmin** [comment]
Hello, I've just unlocked the german translation. Actually the completed translations are locked by default.

BTW, I'll add some strings shortly, because I'm working on a security improvement.

Kind regards

**Comment by nuxsmin** [comment]
Hello, I've just added some new strings.

**Comment by madcoda9000** [comment]
ok, i'll take a look at it shortly

**Comment by nuxsmin** [comment]
Nice!

**Comment by madcoda9000** [comment]
i've finished the translation

**Comment by nuxsmin** [comment]
Thanks for your contribution @madcoda9000 your translation will be merged in the 2.1 version.
