### ISSUE TITLE
Feature: Printable Report

### ISSUE THREAD

**Issue by madcoda9000** [nuxsmin/sysPass#460]
Hello,

for security reasons we put a paper copy of all passwords in a physical safe. Therefore it would be very helpful to get an printable Report, which provides at least the following fields: Account Name, Account Description, Account Username, Account Password

Regards
Sascha

**Comment by derStephan** [comment]
>for security reasons we put a paper copy of all passwords in a physical safe. 

Why do you need a complete list? Why not taking a screenshot right after adding or changing an account?

>Therefore it would be very helpful to get an printable Report, which provides [...] Account Username, Account Password

I disagree. Disclosing everything with very few clicks may be a serious security issue in a scenario where syspass was left open by the user and another user gets access to it.

**Comment by nuxsmin** [comment]
I would export them in an encrypted XML to an external storage and then you could decrypt them when needed. I will provide an standalone tool to parse the XML file and get a given account details.

**Comment by madcoda9000** [comment]
- Why do you need a complete list? Why not taking a screenshot right after adding or changing an account?
--> because i'll have a print for every entry (over 200!). With a list it will be only two papers

- I disagree. Disclosing everything with very few clicks may be a serious security issue in a scenario where syspass was left open by the user and another user gets access to it.
--> in such a case it would be so, yes. The Problem is, that this is an official order from our CEO. He want's us to provide a full list with all accounts and passwords. If this will not be possible in any way, i have to take a look for an other solution :-(

**Comment by madcoda9000** [comment]
- I would export them in an encrypted XML to an external storage and then you could decrypt them when needed. I will provide an standalone tool to parse the XML file and get a given account details.

--> will i be able to create a list with all accounts and passwords with this tool?

**Comment by nuxsmin** [comment]
Added to roadmap #422
