### ISSUE TITLE
Request: Per-user temporary passwords

### ISSUE THREAD

**Issue by MiggyMan** [nuxsmin/sysPass#461]
With the ldap import feature in 2.0 syspass is almost perfect for use in an office environment, the only missing feature is the ability to generate a temporary master password on a per user basis, per-group is ok to some degree but with 150+ users on site all of whom may be using sys pass sending out generic temporary passwords to an entire group of people is not practical to manage!

**Comment by nuxsmin** [comment]
Added to roadmap #422
