### ISSUE TITLE
Clientes - Backups 

### ISSUE THREAD

**Issue by juanforo** [nuxsmin/sysPass#465]
Buen día.

¿Podría preguntar cuál es el significado de un cliente? ¿Tal vez es un conjunto de Cuentas?

Mi otra pregunta es ¿dónde se almacenan los backups? Cuando trato de hacer uno el log de errores me dice que verifique los permisos del directorio, pero sólo sé que está definido por  $backupDir = Init::$SERVERROOT;

Muchas gracias.

**Comment by nuxsmin** [comment]
Buenas,

cliente puede tener varios significados, pero principalmente fue asignado para el uso en una empresa que presta servicios, por lo que se asignan las cuentas según el cliente al que pertenezcan. También es posible darle el significado de departamento o proveedor.

Los backups se almacenan en el directorio `backup` en la raíz de sysPass, es decir `/var/www/html/sysPass/backup`: https://doc.syspass.org/es/installing/debian8.html

Saludos!
