### ISSUE TITLE
Campo Notas

### ISSUE THREAD

**Issue by davidkast** [nuxsmin/sysPass#467]
Buenas tardes,
¿es normal que en el campo Notas no deje escribir mas de 1000 caracteres? 

Realice una importación de una entrada que tiene mas de 1000 caracteres y los admitió sin problema, pero al editar el campo notas, no me deja guardar si supero los 1000 caracteres.

¿Se puede solucionar?

Gracias por el fabuloso trabajo que realizas.

**Comment by davidkast** [comment]
Ya vi que es problema del tema:

<textarea class="mdl-textfield__input mdl-color-text--indigo-400" rows="3" id="notes" name="notes" maxlength="1000"></textarea>

**Comment by nuxsmin** [comment]
Gracias!, me lo a punto para modificarlo, ya que la BD tiene establecido un campo del tipo `TEXT`por lo que admite hasta 65kb

**Comment by nuxsmin** [comment]
Modificado en el commit a408962798adda40473df3335468450903397565
