### ISSUE TITLE
Duplicate user login/email

### ISSUE THREAD

**Issue by zulink** [nuxsmin/sysPass#468]
Hello!
I tried to connect from AD, i take error :(

Syspass duplicate user login/email

**Comment by nuxsmin** [comment]
Hello,

As I understand, you are trying to log into sysPass by using LDAP auth, if so sysPass will create the LDAP user in its database for offline access (and store user's data), and then it will get the user's data from LDAP, so that LDAP user has a email that matches with a sysPass user's email.

Could you verify that the LDAP user's email does not match with an existing one?

**Comment by zulink** [comment]
Yes it is, how can i solve this?

**Comment by nuxsmin** [comment]
You could change the sysPass user that has set that email.

**Comment by zulink** [comment]
I have 6k+ users in my domain and it's impossible, have you got another way to solve this?

**Comment by nuxsmin** [comment]
I meant that you could change the user's email in sysPass, that is on the users tab, search for the email that were in conflict and then change it. Or maybe did you mean that all the LDAP users have the same email?

**Comment by zulink** [comment]
All users have different mail, but error for everyone
This problem started, then i today update to  syspass 2.1
![image](https://cloud.githubusercontent.com/assets/25300170/23504880/57b98db8-ff52-11e6-806b-a50889e96fe3.png)

**Comment by zulink** [comment]
I find out thats the problem, the field is empty
![image](https://cloud.githubusercontent.com/assets/25300170/23507513/820d2d3e-ff5e-11e6-9b6b-12e19fa65468.png)

**Comment by nuxsmin** [comment]
Right, I found the bug. It was caused because it was using a variable that wasn't set at the time the LDAP checks took place.

I've just fixed it in the latest commit (please download from the master branch)

**Comment by zulink** [comment]
Thank you so much!
All things is working perfect and problems were decided successfully. Also we check it on the 20 users.
You can close this issue
I'm appreciate

**Comment by nuxsmin** [comment]
Great, you're welcome!

Thanks for the feedback and tests!
