### ISSUE TITLE
Apache Authentication - sysPass Failed login

### ISSUE THREAD

**Issue by HellChords** [nuxsmin/sysPass#469]
Hello,

When I try to add a authentication basic on apache server, I'had failed to login with sysPass.

My conf for Auth :
```
        <Directory /var/www/syspass/>
                Options Indexes FollowSymLinks MultiViews
                Order allow,deny
                Allow from all
                AuthType Basic
                AuthName "Authentication Required"
                AuthUserFile htpasswd
                Require valid-user
        </Directory>

```

After login with apache, before put my ID : 
```
192.168.37.1 - - [02/Mar/2017:16:33:18 +0100] "GET / HTTP/1.1" 401 738 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:23 +0100] "GET / HTTP/1.1" 200 2298 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:23 +0100] "GET /css/css.php?v=8daa8a80857f463f36865478bdc60749 HTTP/1.1" 200 10154 "http://192.168.37.134/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:23 +0100] "GET /css/css.php?f=fonts.min.css%2Cmaterial.min.css%2Cmaterial-custom.min.css%2Cmdl-datetimepicker.min.css%2Cmdl-jquery-modal-dialog.min.css%2Cselectize.custom.min.css%2Ctoastr.min.css%2Cstyles.min.css%2Csearch-grid.min.css&b=%2Finc%2Fthemes%2Fmaterial-blue%2Fcss&v=2e904b50e7b5e9b7316dfefebc53ce04 HTTP/1.1" 200 28960 "http://192.168.37.134/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:23 +0100] "GET /js/js.php?v=2e904b50e7b5e9b7316dfefebc53ce04 HTTP/1.1" 200 167236 "http://192.168.37.134/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:23 +0100] "GET /inc/themes/material-blue/css/Roboto_400.woff2 HTTP/1.1" 200 14847 "http://192.168.37.134/css/css.php?f=fonts.min.css%2Cmaterial.min.css%2Cmaterial-custom.min.css%2Cmdl-datetimepicker.min.css%2Cmdl-jquery-modal-dialog.min.css%2Cselectize.custom.min.css%2Ctoastr.min.css%2Cstyles.min.css%2Csearch-grid.min.css&b=%2Finc%2Fthemes%2Fmaterial-blue%2Fcss&v=2e904b50e7b5e9b7316dfefebc53ce04" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:23 +0100] "GET /imgs/logo_full_bg.png HTTP/1.1" 200 116173 "http://192.168.37.134/css/css.php?f=fonts.min.css%2Cmaterial.min.css%2Cmaterial-custom.min.css%2Cmdl-datetimepicker.min.css%2Cmdl-jquery-modal-dialog.min.css%2Cselectize.custom.min.css%2Ctoastr.min.css%2Cstyles.min.css%2Csearch-grid.min.css&b=%2Finc%2Fthemes%2Fmaterial-blue%2Fcss&v=2e904b50e7b5e9b7316dfefebc53ce04" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:23 +0100] "GET /js/js.php?f=bootstrap-material-datetimepicker.min.js%2Cmaterial.min.js%2Cmdl-jquery-modal-dialog.min.js%2Capp-theme.min.js&b=%2Finc%2Fthemes%2Fmaterial-blue%2Fjs&v=2e904b50e7b5e9b7316dfefebc53ce04 HTTP/1.1" 200 21403 "http://192.168.37.134/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:23 +0100] "GET /js/js.php?g=1&v=2e904b50e7b5e9b7316dfefebc53ce04 HTTP/1.1" 200 11002 "http://192.168.37.134/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:23 +0100] "GET /css/fonts/MaterialIcons-Regular.woff2 HTTP/1.1" 200 44562 "http://192.168.37.134/css/css.php?v=8daa8a80857f463f36865478bdc60749" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:24 +0100] "GET /ajax/ajax_getEnvironment.php?isAjax=1&_=1488468843758 HTTP/1.1" 200 2977 "http://192.168.37.134/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:24 +0100] "GET /imgs/logo_icon.png HTTP/1.1" 200 11018 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
192.168.37.1 - user [02/Mar/2017:16:33:24 +0100] "GET /js/zxcvbn.min.js HTTP/1.1" 200 399915 "http://192.168.37.134/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
```
Log Apache after click for login :
```
192.168.37.1 - user [02/Mar/2017:16:33:29 +0100] "GET /ajax/ajax_doLogin.php?user=admin&pass=jxhf2HJJI3%2Fv3YA1cR5wp%2FF%2FzmGZ%2BJW7xWG3wQbrzVZo3Mesur1t7VuDE8nUdLltw4izr7Zb97gjtz6ecaby38b6BEHbhlbzGn%2B%2F7qdT3gJNPYgSsQwaWf%2FbVsodWyq3MNAlTEDnGz8yahny1m8cdVnxfsUvecM7nZCXWqxou9g%3D&oldpass=&mpass=&login=1&isAjax=1&_=1488468843759 HTTP/1.1" 200 439 "http://192.168.37.134/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
```

Error GUI after click for login :
<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="http://img4.hostingpics.net/pics/453144syspass.png" border="0" alt="Hebergeur d'image" /></a>

An idea ?

Than you

**Comment by nuxsmin** [comment]
Hello @HellChords 

are you using the same username in both?.Currently, sysPass uses Auth Basic as an authorization mechanism, this means that it will only check if the username matches (including case).

**Comment by HellChords** [comment]
Is not the same. The goal is to use OTP (with LinOPT) for connexion coming from external and do not use Auth Apache when connexion come from internal. So the password will be différent every 30s. For the tests I try with auth basic apache

**Comment by nuxsmin** [comment]
So, the OTP will ask for an user and password and then, once the user logs in, it will never ask for them, doesn't it?

**Comment by HellChords** [comment]
Ok, great it's work !!! But with Reverse Proxy and OTP authentication on it.

If I put OTP authentication directly on sysPass server, I get failed with this :

`[Fri Mar 03 09:41:58.390558 2017] [:error] [pid 26410] Rejecting authentication for user 'user'
[Fri Mar 03 09:41:58.390762 2017] [auth_basic:error] [pid 26410] [client 192.168.37.139:54855] AH01617: user user: authentication failure for "/index.php": Password Mismatch
[Fri Mar 03 09:41:58.462740 2017] [:error] [pid 26410] Rejecting authentication for user 'user'
[Fri Mar 03 09:41:58.462925 2017] [auth_basic:error] [pid 26410] [client 192.168.37.139:54855] AH01617: user user: authentication failure for "/index.htm": Password Mismatch
[Fri Mar 03 09:41:58.535895 2017] [:error] [pid 26410] Rejecting authentication for user 'user'
[Fri Mar 03 09:41:58.536076 2017] [auth_basic:error] [pid 26410] [client 192.168.37.139:54855] AH01617: user user: authentication failure for "/index.html": Password Mismatch
`

And log OTP side :
`2017/03/03 - 09:41:35 WARNI {140443453171456} [linotp.lib.tokens.totptoken][checkOtp #456] [checkOTP] a previous OTP value was used again!
 former tokencounter: 49617684, presented counter 49617684
2017/03/03 - 09:41:35 WARNI {140443453171456} [linotp.lib.tokens.totptoken][checkOtp #456] [checkOTP] a previous OTP value was used again!
 former tokencounter: 49617684, presented counter 49617684
2017/03/03 - 09:41:35 WARNI {140443453171456} [linotp.lib.auth.finishtokens][finish_checked_tokens #100] user u'user'@u'domtest' failed to auth.
2017/03/03 - 09:41:35 WARNI {140443453171456} [linotp.lib.auth.finishtokens][finish_checked_tokens #100] user u'user'@u'domtest' failed to auth.
2017/03/03 - 09:41:35 WARNI {140443461564160} [linotp.lib.tokens.totptoken][checkOtp #456] [checkOTP] a previous OTP value was used again!
 former tokencounter: 49617684, presented counter 49617684
2017/03/03 - 09:41:35 WARNI {140443461564160} [linotp.lib.tokens.totptoken][checkOtp #456] [checkOTP] a previous OTP value was used again!
 former tokencounter: 49617684, presented counter 49617684
2017/03/03 - 09:41:35 WARNI {140443461564160} [linotp.lib.auth.finishtokens][finish_checked_tokens #100] user u'user'@u'domtest' failed to auth.
2017/03/03 - 09:41:35 WARNI {140443461564160} [linotp.lib.auth.finishtokens][finish_checked_tokens #100] user u'user'@u'domtest' failed to auth.
2017/03/03 - 09:41:35 WARNI {140443453171456} [linotp.lib.tokens.totptoken][checkOtp #456] [checkOTP] a previous OTP value was used again!
 former tokencounter: 49617684, presented counter 49617684
2017/03/03 - 09:41:35 WARNI {140443453171456} [linotp.lib.tokens.totptoken][checkOtp #456] [checkOTP] a previous OTP value was used again!
 former tokencounter: 49617684, presented counter 49617684
2017/03/03 - 09:41:35 WARNI {140443453171456} [linotp.lib.auth.finishtokens][finish_checked_tokens #100] user u'user'@u'domtest' failed to auth.
2017/03/03 - 09:41:35 WARNI {140443453171456} [linotp.lib.auth.finishtokens][finish_checked_tokens #100] user u'user'@u'domtest' failed to auth.
`

**Comment by nuxsmin** [comment]
That is most likely because the webserver credentials don't match with the OTP ones, sysPass only "see" the headers sent from the webserver.

**Comment by HellChords** [comment]
Ok, I'll pass by my reverse proxy for apply OTP. Thank you for help
