### ISSUE TITLE
orphan_user in 2.1 post upgrade

### ISSUE THREAD

**Issue by chenrbs** [nuxsmin/sysPass#470]
Hello,

I have upgraded from 1.2 to 2.1, is was a success however after login I have some issues, see below.
1) there is a user called orphan_user under users
2) Accounts with attachments can not be opened or deleted, I get the following error
Oops...
There was an error
Internal Server Error
3) When clicking on a newly added account with attachment the paperclip icon does nothing

Please let me know if there is anything that can be done.

Thank you!
Ken

**Comment by nuxsmin** [comment]
Hello,

It's weird, I've just done some tests and the accounts with files are opened fine.

The orphan user is because on previous versions the related items were controlled by the app and some items were deleted when there were related items to it. Now the related items are controlled by the database, so before applying all the item should be linked.

You can remove the orphan user when there are no related items to it, that most likely would be accounts and history accounts.

Please take a look to the webserver log and syspass.log file in the config directory.

Kind regards

**Comment by chenrbs** [comment]
I cannot delete the user, these are the errors in the log file.

2017-03-02 20:54:42 - Error en la consulta
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`accFiles`, CONSTRAINT `fk_accFiles_accounts_id` FOREIGN KEY (`accfile_accountId`) REFERENCES `accounts` (`account_id`) ON DELETE NO ACTION ON UPDATE NO ACTION) (0)

2017-03-02 21:00:59 - Error en la consulta
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`accHistory`, CONSTRAINT `fk_accHistory_users_edit_id` FOREIGN KEY (`acchistory_userEditId`) REFERENCES `usrData` (`user_id`)) (0)

**Comment by nuxsmin** [comment]
Ok, these errors are because the file is in use by an account, and on the other hand, the user is in use by an account.

You can use the special search filtering (see help icon on the search view) to look up those items.

**Comment by chenrbs** [comment]
Getting error when clicking on Items and customization, nothing in logfile just on screen, see below.
Oops...
There was an error
Internal Server Error

**Comment by nuxsmin** [comment]
Please, edit the Base.php file and set debug to true.

After that, it should log any error on any of both log files.

**Comment by chenrbs** [comment]
It worked when I enabled debug but I cannot delete Orphan customer for some reason, nothing in the log.

**Comment by nuxsmin** [comment]
Ummm, that's so weird....

The customer could be linked to an account or account's history, so you would need to check out which account is using it.

**Comment by nuxsmin** [comment]
You need to be aware that an account has some kind of versioning, that is every time you perform any modification, it will save the current data in the history, so you could restore from any point in the time. 

This versioning includes all the account basic data (not including neither permissions nor custom fields nor files nor tags), so the related items like customer, category, owner, group and editor are saved in the history, then you won't be able to remove them unless the history is deleted.

Hope this clarify this behavior.

**Comment by chenrbs** [comment]
When I go to the attachment that was uploaded in version 1.2, I get this error
Fatal error: Call to undefined function SP\Html\mb_substr() in /var/www/html/syspass/inc/SP/Html/Html.class.php on line 96

**Comment by nuxsmin** [comment]
That is because a needed module is not installed. You need to install php-mbstring to handle unicode characters, and it's needed to perform some strings handling.

**Comment by chenrbs** [comment]
Thank you that fixed it!

I don't know how I can find Orphan accounts attached to Orphan user so I am unable to delete this user and group.

**Comment by nuxsmin** [comment]
Sure, you can get it by using special searching parameters (you can know them on the help icon in the search view)

**Comment by chenrbs** [comment]
I restored to version 1.2 from backup and will make a beta upgrade until all issues are resolved.

**Comment by nuxsmin** [comment]
Please upgrade to 2.1 version.

Note that the "orphan" user will remain there because some account records need to have set an user id (also in history) because the old one was deleted. The orphan user could be deleted when those account records were deleted too.

Regards.
