### ISSUE TITLE
Delete category - that was in use (latest 2.1)

### ISSUE THREAD

**Issue by MAndretti** [nuxsmin/sysPass#471]
Hi,

1) add a new category "test"
2) use this category in different accounts
3) change category in this accounts
4) no account is using category "test"
5) delete category "test"

Result:
Error while querying
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`accHistory`,
CONSTRAINT `fk_accHistory_category_id` FOREIGN KEY (`acchistory_categoryId`) REFERENCES `categories` (`category_id`)) (0)SQL : '
DELETE
FROM categories
WHERE category_id = ?
LIMIT 1'

Best regards
MAndretti

**Comment by nuxsmin** [comment]
Hi,

that's right, the category is assigned to the account's record in the history, so you would need to delete the history record from "Items and Customizations" module.

**Comment by MAndretti** [comment]
Hi,

sorry. Next time. RTFM first :)
--> Close

Thanks,
MAndretti

**Comment by nuxsmin** [comment]
No worries ;)
