### ISSUE TITLE
Password Change At login Redirects to undefined

### ISSUE THREAD

**Issue by k-s-dean** [nuxsmin/sysPass#474]
Hi, I have tested the latest database upgrade. all went fine. 

We have noticed however that selecting password change on a user, redirects to an undefined page?

Also when, trying to login to an account. We used incorrect master password and wrong password 5 -6 times, we now get an attempts exceeded for that user(Edit: we have just found out this is IP based). is there a way to reset this ?

kind regards.

**Comment by nuxsmin** [comment]
Hi @k-s-dean 

I'm glad that the upgrade went fine. Regarding the password change issue, I haven't be able to reproduce it, but I found some issues with the hash length (showing an error), so you could give a try to the latest release.

About the wrong login attempts behavior, currently it's set in code, and the values are 5 attempts within 10 minutes. In next releases it could be set through the UI.

Thanks for the feedback!

Kind regards

**Comment by k-s-dean** [comment]
Hi , it may be helpful to know that at my organisation we use very long passwords, sometimes 22 -32 characters for security reasons. Is there a maximum allowed password size ?

we are also getting that error

``` 
017-03-06 14:23:20 - Exception: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'userpassr_hash' at row 1
2017-03-06 14:23:20 - #0  SP\Storage\DB->prepareQueryData() called at [/var/www/html/syspass/inc/SP/Storage/DB.class.php:150]

```

![selection_006](https://cloud.githubusercontent.com/assets/23525195/23650938/c3478126-031b-11e7-8165-ce65ba011c60.png)

**Comment by nuxsmin** [comment]
Hi, don't worry about the user's passwords  because this issue is related to a random generated hash for resetting the password. This hash is used to make an unique and trusted request.

The password fields length is long enough (1000 chars) to contain large datasets including the encryption data.

**Comment by k-s-dean** [comment]
Awsome, thanks. 

Look forward to testing latest when released.

**Comment by nuxsmin** [comment]
Sure, it was released late yesterday ;)

**Comment by k-s-dean** [comment]
Oh, apologies. will go and test now ^^

**Comment by k-s-dean** [comment]
Tested, Works.

**Comment by nuxsmin** [comment]
Fine... Thanks for the feedback!
