### ISSUE TITLE
Session - Integrity check failed

### ISSUE THREAD

**Issue by VexedSyd** [nuxsmin/sysPass#476]
Hi guys,

Great effort. I deployed sysPass 4 days ago and everything was working great until I updated to the lastest version today.
Whenever I try to login, the login seems to be successful but I stay on the login page.

The sysPass Log is showing the below:

2017-03-07 16:45:42 - Generating a new session key.
2017-03-07 16:45:42 - Integrity check failed.
2017-03-07 16:45:42 - Integrity check failed.
2017-03-07 16:45:42 - Session data not encrypted.
2017-03-07 16:45:46 - Generating a new session key.
2017-03-07 16:45:46 - Integrity check failed.
2017-03-07 16:45:46 - Integrity check failed.
2017-03-07 16:45:46 - Session data not encrypted.
2017-03-07 16:45:47 - Generating a new session key.
2017-03-07 16:45:47 - Integrity check failed.
2017-03-07 16:45:47 - Integrity check failed.

I assume this is related to [ADD] Added session data encryption.

Is there anything I'm missing or was supposed to do during the upgrade?

Many thanks.

**Comment by nuxsmin** [comment]
Hello @VexedSyd 

You're right, the session encryption behavior is not running fine on your environment...

some questions regarding the issue: Is there any cookie called "SYSPASS_SK" on your browser?, Is sysPass behind an http proxy?.

Regards

**Comment by VexedSyd** [comment]
Hi @nuxsmin

There is no SYSPASS_SK cookie, only PHPSESSID. sysPass is not behind a proxy at all (on the local lan).

Strangely enough, When I tried to access it over the VPN now, I can see the cookie and I was able to login. I'm not aware of anything inside our network that might be stripping that cookie. It could be just random.

Thanks.

**Comment by nuxsmin** [comment]
It could be some URL rewriting so the cookie would be invalid, because its path is set to the sysPass URL. That is a security behavior.

**Comment by VexedSyd** [comment]
I'm not 100% sure, but clearing the browser cache seems to resolve the matter (at least on Chrome, Firefox but not Edge). I will get the team to check it tomorrow.

Thanks again.

**Comment by nuxsmin** [comment]
So, does it work now fine even if the VPN is not established?

**Comment by nuxsmin** [comment]
Thanks for the feedback and testing!

**Comment by VexedSyd** [comment]
yes it worked from the internal LAN after clearing the cache.

Thanks for your great effort, this such a usual app you are developing.

**Comment by nuxsmin** [comment]
You're welcome ;)
