### ISSUE TITLE
Problem with translation

### ISSUE THREAD

**Issue by HellChords** [nuxsmin/sysPass#477]
Hello,

A few translation are missing (was OK with 2.0)

For example :
http://img4.hostingpics.net/pics/9709202801.png

http://img4.hostingpics.net/pics/7320435202.png

http://img4.hostingpics.net/pics/9172764303.png

And when I change to English (default config server and from user config), language is only Spanish.

Thank you

**Comment by nuxsmin** [comment]
Hello,

that's so because the original strings are set in Spanish, so some untranslated strings (or the fuzzy ones) would be in this language. You can switch to English, but be aware that you would need to install the en_US-utf8 locale to get it working (sysPass uses gettext).

Regards.

**Comment by HellChords** [comment]
OK that's it... Thank you
