### ISSUE TITLE
New Account: Tab to select Customer/Category

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#479]
I just installed Version: 2.1.

Would it be possible to have the tab and enter key have the same behaviour when selecting the customer and category.

Currently if you enter the field and start typing the name, if you press enter it will use the selected value from the dropdown.
If you press tab it will exit the field leaving it blank.

**Comment by nuxsmin** [comment]
Absolutely right, that behavior is a hassle and I would need to modify the Selectize.js plugin to get it.

I'll be back when done ;)

**Comment by nuxsmin** [comment]
Solved
