### ISSUE TITLE
New Account: Save and New

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#480]
In version 1.2 when an account was created the screen stayed on the create page.
In 2.1 when an account is created I am redirected to the accounts entry. 

Is it possible to get another button that saves the account but keeps you on the Create page.
maybe with an icon with the save icon and a +.

It is very handy  when setting up new systems to create a number of accounts in quick succession. 
eg, I created a set of database users (5 accounts) and needed to test them all before creating the accounts in syspass. It was a fair bit easier in 1.2 to do this.

Thanks,
Basil

**Comment by nuxsmin** [comment]
Nice feature!

**Comment by nuxsmin** [comment]
Added to roadmap #422
