### ISSUE TITLE
Searching: Instant results

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#481]
Hey,

Version 2.1

Is it possible to have instant partial searching when typing in the search bar, rather than only by pressing enter. (or possibly an option to enable it, since there could be a performance impact on systems with loads of accounts)

It is very helpful to  see the cards filtering down as typing. Mainly stops from typing in more than you have to. 

Thanks,
Basil

**Comment by nuxsmin** [comment]
Added to roadmap #422
