### ISSUE TITLE
[BUG] Getting "Internal Server Errorerror" message while installation

### ISSUE THREAD

**Issue by cyb0rg01** [nuxsmin/sysPass#482]
Hey there,

I am new to sysPass and I wanted to install an evaluation instance in my virtual environment. After I setup an CentOS 7.2.1611 server and all prerequisites, I ran into an error while installing sysPass via the installer. The error message shown in my browser says "Internal Server Errorerror".

My syspass.log (/var/www/html/passwords/config/) is empty. In my httpd error log I find the following entries:

[Tue Mar 07 13:29:49.143178 2017] [:error] [pid 2496] [client x.x.x.x:53095] PHP Warning:  date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/passwords/inc/SP/Core/Init.class.php on line 97, referer: https://vhost.mydomain.com/
[Tue Mar 07 13:29:49.864020 2017] [:error] [pid 2496] [client x.x.x.x:53095] PHP Fatal error:  Call to undefined function SP\\Core\\utf8_encode() in /var/www/html/passwords/inc/SP/Core/Installer.class.php on line 244, referer: https://vhost.mydomain.com/

I am using PHP 5.6.30 from Remi's RPM repository (only good experiences with it).

For the installing, I used the description from your Docs.

Anyone any guess?

**Comment by nuxsmin** [comment]
Hello, it's a missing PHP module such `mod_mbstring`. Sorry, doc should tell that :(

**Comment by cyb0rg01** [comment]
Hey, thanks for your reply. I installed php-mbstring but this doesn't really help. The error message is still the same and the httpd error log still shows the same output.

**Comment by nuxsmin** [comment]
Sorry, I told you the wrong module (actually it's needed too), so you would need to install `php-xml`

**Comment by nuxsmin** [comment]
Please see  #446

**Comment by cyb0rg01** [comment]
No worries. It works now, but I needed to hit three or four times the "install" button, because of some error with the Database connection.

Now, just this message is still present in my httpd error log:
[Tue Mar 07 15:18:55.239951 2017] [:error] [pid 3463] [client x.x.x.x:54940] PHP Warning:  date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/passwords/inc/SP/Core/Init.class.php on line 97, referer: https://vhost.mydomain.com/index.php

But it works just fine from now. Thanks a lot!

I am looking for a new password tool; currently we are using ratticDB (dunno if your heard of it). But sysPass looks quite awesome and with many features we need for a company certification.

**Comment by nuxsmin** [comment]
I'm glad that it worked :)

About the message, it's a weird message, because the line that it points to is:
```
        if (date_default_timezone_get() === 'UTC') {
            date_default_timezone_set('UTC');
        }
``

So the timezone is set to UTC.

I've not heard about that password manager, but I hope you find sysPass useful for your needs :)

Please, don't hesitate to ask me any question regarding sysPass. You can find more info on: https://doc.syspass.org

Regards
