### ISSUE TITLE
Menu does not disappear when working in a small window

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#483]
Hey,

In version 2.1, I have found that when working in a small widow all the options (Query, New Account, Logout etc) are moved to a menu in the top left. 

This is quite cool, but I noticed a bug when the menu is open and you click on an option.
It correctly changes the background page to the new view however the menu stay open and you have to click somewhere else to make it disappear. 

It would be much nicer if it disappeared after you select the page to navigate to. 

Thanks,
Basil

**Comment by nuxsmin** [comment]
Umm, that is an MDL (Material Design Lite) behavior so it could be hard to change (now they are moving to Material Components Web).

**Comment by basil-twisleton** [comment]
Ok. It is not a big deal, just thought I would let you know.

**Comment by basil-twisleton** [comment]
Confirmed fixed
