### ISSUE TITLE
Error while copying password to clipboard with 2.1

### ISSUE THREAD

**Issue by bodkov** [nuxsmin/sysPass#486]
I have a strange issue after connecting sysPass 2.1 to our OpenLDAP (I'm not sure if it's the OpenLDAP integration)

We're currently using
-CentOS 7
-nginx
-MariaDB 10.1
-PHP7
-Latest sysPass 2.1

The Copy To Clipboard Function works fine, when I initally install sysPass. But after I connected to the LDAP and login as a different user (which all works fine), I cannot use the copy to clipboard function anymore. 

Is there a way to help you find this bug? Maybe something related to nginx or CentOS?

**Comment by nuxsmin** [comment]
Hi,
which method does not work, using the direct icon or when opening the password box?. Does it show any error?.

**Comment by bodkov** [comment]
The password box shows up just fine. It's the direct icon. 

I have another setup with nginx, php7.0, mariadb and Ubuntu 16.04 running which works just fine. The only difference is basically the OpenLDAP integration and CentOS

**Comment by nuxsmin** [comment]
It's so weird, because it relies on Javascript to get the password from an AJAX request.

**Comment by bodkov** [comment]
Can I give you some useful debug information? I've tested this on Chrome and Firefox on Fedora 25.

Ah and the error displayed is "Error while copying to clipboard". 

The Chrome Debug Console also shows no error

**Comment by nuxsmin** [comment]
Umm, it seems a browser issue, because that error is thrown from Javascript code.

**Comment by bodkov** [comment]
Anything that I can do to help you figure this one out? :)

**Comment by nuxsmin** [comment]
You could activate the debug mode in `inc\Base.php` so the browser console will output some data when Javascript code is running.

**Comment by bodkov** [comment]
![screenshot_20170308_110430](https://cloud.githubusercontent.com/assets/11457234/23699379/3950d52e-03ef-11e7-9799-bb07faaed6b0.png)

It just shows this, no error just info.

One more possibility could be my self signed certificate for nginx. Could that be an issue?

**Comment by nuxsmin** [comment]
Umm, I wouldn't think it's a certificate issue...let me do some find outs and I'll be back

**Comment by bodkov** [comment]
Thanks that's great!

**Comment by nuxsmin** [comment]
Could you try out the latest release?

**Comment by bodkov** [comment]
I have upgraded to 2.13 and the issue still occurs. Again with Firefox and Chromium on Fedora. I have also tested it with Windows 10 and Firefox and the issue is still the same. 

Ah and I have disabled SELinux, to rule that one out, but the error occurs with or without SELinux. 

My error log of nginx is btw full of ajax errors (or at least it shows up in the error.log, but doesn't state which error, because it's always a GET), can I give you my error.log file to see if you can see something in it that helps you?

**Comment by bodkov** [comment]
@nuxsmin: I switched to your dockerized solution and now everything is working fine.

**Comment by nuxsmin** [comment]
Umm, really weird. Which sysPass version is running in the container? (I don't know exactly because it's automatically built whenever a commit is pushed to the docker repository)

**Comment by bodkov** [comment]
According to the website it is 2.1

**Comment by nuxsmin** [comment]
Ok, but what about the build number? (In the information tab)

**Comment by bodkov** [comment]
2.1 (2.1.4.17032001)

**Comment by nuxsmin** [comment]
Ok, that's the latest one from master branch.

Thanks for the feedback!

**Comment by bodkov** [comment]
Yes it works quite well actually. But you should put the fact that you have to put "db" instead of localhost into the database config into your docker documentation, took me some time to find out :)

**Comment by nuxsmin** [comment]
Umm, that's already told on https://doc.syspass.org/en/installing/docker.html#acceso

;)

**Comment by bodkov** [comment]
Oh .... :D
