### ISSUE TITLE
Clientes Públicos

### ISSUE THREAD

**Issue by juanforo** [nuxsmin/sysPass#487]
Buen día.

Quisiera saber si hay alguna forma de establecer clientes públicos,de manera que así hayan cuentas privadas por grupo, sea posible para un usuario de otro grupo crear una cuenta en dicho cliente.

Veo que tengo que crear una cuenta que sea visible para todos los grupos de usuarios para poder recrear esto.

De igual forma, veo que al eliminar un cliente o una categoría se hace una restricción de integridad por la tabla acc_history. ¿Hay alguna forma de arreglar esto o es necesario arreglarlo con una sentencia en la BD?

Gracias.

**Comment by nuxsmin** [comment]
Buenas,

No he entendido la primera pregunta, ya que a los clientes no se les aplica ninguna acl.

Con respecto al historial, es posible eliminar las entradas desde "elementos y personalización", en la pestaña "cuentas (H)". Esta restricción es debido a que los datos básicos de la cuenta son versionados y los ids de usuarios, clientes y categorías se han de mantener para que la cuenta en el historial no pierda dicha información. Las cuentas prevalecen sobre el resto.

Saludos.

**Comment by juanforo** [comment]
Gracias por tu respuesta.

No sé si he entendido bien, pero si yo como un usuario de un grupo A creo una cuenta privada con un cliente específico, si un usuario de otro grupo B quiere crear una cuenta con dicho cliente, éste no me va a aparecer en el formulario, puesto que es una cuenta privada para el grupo.

La idea es por ejemplo tener un cliente "AWS" que pueda ser utilizado por varios grupos de usuarios, de manera que sea visible al momento de crear una cuenta, y se pueda utilizar este cliente de manera que los grupos de usuarios sólo puedan ver sus contraseñas privadas para el grupo.

Gracias por tu atención y amabilidad.

**Comment by nuxsmin** [comment]
Hola, ya sé a qué te refieres. Los clientes se ocultan cuando son asignados, ya que así el resto de usuarios no los ven si no están asociados a las cuentas que tienen asociado a dichos clientes.

Esa es una mejora propuesta para la próxima versión, así será posible establecer si un cliente es visible por todos los usuarios.

Saludos!

**Comment by juanforo** [comment]
Sería genial. Por ahora trataré los clientes con una cuenta pública para que todos los puedan ver, y después crearé cuentas privadas en dichos clientes.

Muchas gracias por tu atención.

Un saludo.
