### ISSUE TITLE
Messages in syspass.log - Decryption Error/Integrity Check failed

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#488]
Hey,

In v 2.1 I get a number of odd messages show up in config/syspass.log

```
2017-03-07 13:50:02 - Integrity check failed.
2017-03-07 13:50:02 - Session data not encrypted.
2017-03-07 13:50:48 - Generating a new session key.
2017-03-07 13:50:48 - Integrity check failed.
2017-03-07 13:50:48 - Integrity check failed.
2017-03-07 13:50:48 - Session data not encrypted.
2017-03-07 13:50:49 - Integrity check failed.
2017-03-07 13:56:44 - Decryption error
2017-03-07 13:57:17 - Decryption error
2017-03-07 16:26:36 - Decryption error
2017-03-08 09:15:22 - Decryption error
2017-03-08 09:15:41 - Generating a new session key.
2017-03-08 09:16:28 - Decryption error
```

The Decryption error seems to show up every time I log into my LDAP bound account. It does not show up when using the named admin account.

I am not sure why the Integrity Check failed, but it happened about 20 times yetersday

Here is the log data shown in the syspass admin
![image](https://cloud.githubusercontent.com/assets/2098465/23698469/f571c064-03eb-11e7-8a78-f6b7e59cc05a.png)

I have turned on debug mode, but I am not sure where to find additional information.

Thanks,
Basil

**Comment by nuxsmin** [comment]
Hi, that is an issue related with the browser cookies,  because the app needs to set a cookie named 'SYSPASS_SK' , so it could not be set by a proxy between the browser and sysPass.

**Comment by basil-twisleton** [comment]
Are you referring to the decryption error or teh integrity check?

The integrity check has not shown up again today, but the decryption error continues to show. 

We do not use any proxy, it is a simple Apache hosted site.

I have also cleared my  browser of all cookies for the site and it still appears. The SYSPASS_PK cookie is also generated after a fresh login but the error continues. 
 
I am primarily using Chrome 56, when trying in Firefox 51 the error does not occur. 

Even with the error message, everything appears to be working correctly.

Thanks,
Basil

**Comment by nuxsmin** [comment]
Ok, the sysPass cookie is used to encrypt the session data, so you could check if it's being encrypted on the information tab.

The session data is a PHP special file where it stores some temporary data to be used while the user is working on the app, so this data is also encrypted to avoid any leak if the webserver is compromised.

**Comment by basil-twisleton** [comment]
These are the cookies in chrome
![image](https://cloud.githubusercontent.com/assets/2098465/23712213/8050ffe8-0422-11e7-9726-45b3459329c6.png)

I checked the SYSPASS_SK and it looks like encrypted data. 

![image](https://cloud.githubusercontent.com/assets/2098465/23712148/496e4b5c-0422-11e7-968f-46c36a0b3eaa.png)

Since it is working I am not too concerned, it was more of a surprise about an error when nothing appeared broken.

**Comment by nuxsmin** [comment]
Did you check out if the session is being encrypted? (sysPass information tab)

**Comment by basil-twisleton** [comment]
When I log in as the admin account and check this tab it says "Yes".

**Comment by basil-twisleton** [comment]
I created a new standard user (not LDAP) and the error does not occur for them. 

I will try to check another LDAP user shortly and let you know.

**Comment by basil-twisleton** [comment]
After testing with a different LDAP user. 

On first login after the upgrade to v 2.1 there was no decryption error, just a message "Generating a new session key."

After a log out and back in the "Decryption error" is logged.

**Comment by nuxsmin** [comment]
To sum up, it only appears when logging in with LDAP users and performing a normal log out, is this right?

**Comment by basil-twisleton** [comment]
Correct, It only happens for
* LDAP Users
* On Login only
* In Chrome when logging in a second time (even happens in incognito mode)

**Comment by nuxsmin** [comment]
Let me do some tests and I'll be back shortly.

Thanks for the feedback and testing!

**Comment by nuxsmin** [comment]
Hi,

I've done some tests within chrome with and without incognito mode and it worked fine for LDAP users. It could be some changes done on the cookies handling in the latest commits. Please, try out again and let me know if the issue persists.

![001](https://cloud.githubusercontent.com/assets/1775774/23835411/2a3d5ce4-0767-11e7-8f5f-8764ccef26ed.png)

Regards.

**Comment by basil-twisleton** [comment]
Looks like this may be related to me having my username and password saved in Chrome.
Which is odd as the credentials are valid as they let me login.

If I remove the saved password from Chrome then the message does not appear. After saving it again the message comes back.

**Comment by nuxsmin** [comment]
Great!

Thanks for the feedback.
