### ISSUE TITLE
[REQUEST] Multiple Groups via LDAP

### ISSUE THREAD

**Issue by cyb0rg01** [nuxsmin/sysPass#489]
Hey there,

I want to use multiple groups which I defined in my Active Directory and control the access to the different passwords/accounts. Is there any chance, that your tool gives me the opportunity to handle my hole user management via my Active Directory?

We want to use it with other departments and want to set up a different levels of permissions and also want to structure it in the AD, so that other department admins can control the access for their over AD.

I have only seen one group for global access, this is working fine so far. But it would be nice to import different Active Directory Groups as well and manage the connection to different passwords and customers.

**Comment by nuxsmin** [comment]
Added to roadmap #422
