### ISSUE TITLE
Questions about sysPass 2.x

### ISSUE THREAD

**Issue by testor321** [nuxsmin/sysPass#490]
Hi
Thank you. You developing an excellent product.
I have a few questions
1. Can you share any information about plugins? If I want write something myself - specifications, limitations, etc
2. When  "tags" are used : can they be included into global search?
3. Can you give me example how to use API (getAccountData for example). What minimal rights should have user in the system to be able get information via API?

**Comment by nuxsmin** [comment]
Hi

I'm glad that you liked it :)

Regarding your questions:

> Can you share any information about plugins? If I want write something myself - specifications, limitations, etc

Currently, the plugin architecture is not documented, but you can take a look to the "Authenticator" plugin which main class is "AuthenticatorPlugin.class.php" (https://github.com/nuxsmin/sysPass/blob/master/inc/Plugins/Authenticator/AuthenticatorPlugin.class.php) and where the plugin information is defined. This class is registered (when sysPass initialization takes place) as an event receiver (using the observer pattern), so the "init()" method is called for the plugin initialization. The structure is quite similar to the sysPass itself. The plugin could store any data in the DB using a serialized object, so it won't need to rely on any database structure (ie custom tables and columns). 

BTW, let me some time for writing a proper documentation so it would clarify how it works...

> When "tags" are used : can they be included into global search?

Sure, every filter option could be used into the global search. Hope I understood you...

> Can you give me example how to use API (getAccountData for example). What minimal rights should have user in the system to be able get information via API?

The API is documented on http://doc.syspass.org/en/application/api.html and the user need to have assigned an API token, so he would be granted on those accounts that he is as a normal sysPass user and will be able to get those API actions for which the tokens are set to. A request example could be:

```
 {
    'jsonrpc' : '2.0',
    'method' : 'getAccountData',
    'params' : {
        'authToken' : 'PUT_YOUR_TOKEN_HERE',
        'id' : '1'
    },
    'id' => 1
}
```
Here you have an example of a PHP API client using curl: https://gist.github.com/nuxsmin/62338b33178544894cd7237c7fe170bd

**Comment by testor321** [comment]
Thank you very much. 
It is very helpful
but about tags usage - I will try to add more information. Seems I have formulated wrong
For example I have account "record1" with tag "testtag"
![image](https://cloud.githubusercontent.com/assets/18244189/23748183/cb10e2e6-04c2-11e7-987a-5253bd058be9.png)

If I filter in the "More filters" field then it is OK
![image](https://cloud.githubusercontent.com/assets/18244189/23748237/0eb1ed88-04c3-11e7-9cfd-36c3c5c0317e.png)

but when I try search this tag in the "common" search field - I have nothing
![image](https://cloud.githubusercontent.com/assets/18244189/23748307/5433f888-04c3-11e7-8f37-cd52fe6576b8.png)

Does it work as expected ?
thank you

**Comment by nuxsmin** [comment]
Right, tag names couldn't be filtered through the search text box. It was done so in some versions ago by using the special filter "tag:tag_name". That is so because it implies some regular expression filtering that could impact on the webserver performance.

Although you may think on a search by only entering the tag name (w/o an special filter) using a table "join" to filter out those tags names, it could get some confusing results, because you would get the matched results against account text data and tag name.

Hope I've explained it well...

**Comment by testor321** [comment]
Yes, Thank you
And excuse me, but one more question
We have 2 filtering fields : 
![image](https://cloud.githubusercontent.com/assets/18244189/23748610/a97aa5b6-04c4-11e7-9b65-452b9df2d07f.png)

When I am choosing "Customer" (for example) is it possible have filtered result in the "Category" list (for example again)
I mean - can I get/see only categories what customer (what was choosen) has ?

**Comment by nuxsmin** [comment]
Umm, that could be done by implementing some code on the returning accounts query, so the select could be updated with the returned categories.

I can be a nice feature for the next release ;)

**Comment by testor321** [comment]
Thank you very much for your support

**Comment by nuxsmin** [comment]
Hi,

I've just updated the plugins documentation on: https://doc.syspass.org/en/application/plugins.html

I hope this may be useful. Let me know if you have any question/doubt about it.
