### ISSUE TITLE
Question about custom theme

### ISSUE THREAD

**Issue by cyb0rg01** [nuxsmin/sysPass#491]
Hey there,

is there a simple way to customize my sysPass theme to meet my companies CI/CD? (Changing colors, logo etc.)

For sure, I could create a copy of the material blue default theme and customize it, but I hope to get an easier way than this.

**Comment by nuxsmin** [comment]
Hi!

Umm, currently there is no such "easy" way, so you would need to customize the provided theme by copying and then modifying some CSS and uploading your logo to the global images directory (ie. imgs).

Regards

**Comment by cyb0rg01** [comment]
Hey, you can close this one. I wrote my own theme by copying and modifying some CSS Styles. One improvement you should do: the login logo should be controlled via the CSS files, too. Like the logo in the header.

**Comment by nuxsmin** [comment]
Fine!, the login logo defined is in `styles.css` file within the selector `#login-container`.

Regards

**Comment by cyb0rg01** [comment]
Hmm ... I replaced it there, too. But it hasn't changed. The logo is also hart coded in the HTML output, directly between the <img>-tag. After I replaced it on the file system, it changed. Could also be a strange effect with my setup.

But thanks anyways! It was easy to handle it. Thanks to Google Material Design. :-)

**Comment by nuxsmin** [comment]
It could be that you forgot to minimize the css file, so it will output the same content. The only hard coded logo is the top nav bar one, it needs to be so because the layout.

Be aware that future releases could either solve some issues or implement new features that will be missed in your custom theme, so you will need to sync both.

**Comment by cyb0rg01** [comment]
I am currently working on a minimized css file, my first shot was directly editing the css files. One issue I found is, that you use !important very often in your original files. This makes it very hard to create a theme, which does not need to be updated that much.

Is there any hope, that you may fix it in a future release?
