### ISSUE TITLE
Click zone for switches too large

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#492]
Hey,

So I noticed that in V 2.1 the click zone for toggling the switches overlaps.
![image](https://cloud.githubusercontent.com/assets/2098465/23748262/2a34fd84-04c3-11e7-9c1e-8f3144201235.png)

This is the approximate area of this control, which can lead to accidental toggles if trying to press Disabled instead of password change. 
Especially as clicking on the very bottom of the "Disabled" circle toggles "Password Change". 

Behaviour appears consistent on all switches on this screen (and maybe elsewhere)

Thanks,
Basil

**Comment by nuxsmin** [comment]
You're right, the default MDL control takes a large clicking zone. It could be solved by inserting a vertical gap between switches.

Thanks for the feedback!

**Comment by basil-twisleton** [comment]
Confirmed fixed
