### ISSUE TITLE
Mobile device support

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#493]
Hey,

I saw in v 2.0 RC4 release notes it mentioned 

> [MOD] UI tweaks for mobile friendly.

I am having trouble accessing with Safari or Chrome on iOS 10.2.1.
The event logs shows my user successfully authenticates, but the login screen pops back up. 

Can you please clarify if this is expected to work?

Thanks,
Basil

**Comment by nuxsmin** [comment]
Hey!

That is not the intended behavior...(could be related to the session cookie)

Unfortunately, I haven't got any iOS device so some testing from the community would  be appreciated ;)

Regards!

**Comment by basil-twisleton** [comment]
My cookie perms in Safari were set to "Only Websites I Visit".

I cleared my Safari cookie cache and got the following messages in syspass.log

```
2017-03-09 13:52:45 - Generating a new session key.
2017-03-09 13:52:45 - Integrity check failed.
2017-03-09 13:52:45 - Integrity check failed.
2017-03-09 13:52:45 - Session data not encrypted.
2017-03-09 13:52:47 - Generating a new session key.
2017-03-09 13:52:47 - Integrity check failed.
2017-03-09 13:52:47 - Integrity check failed.
2017-03-09 13:52:47 - Session data not encrypted.
2017-03-09 13:52:47 - Generating a new session key.
2017-03-09 13:52:47 - Integrity check failed.
2017-03-09 13:52:47 - Integrity check failed.
2017-03-09 13:52:47 - Session data not encrypted.
```

I then set the cookie permissions to "Always Allow" and cleared cache again but the same sets of errors come up. 

Interesting when I look at the cookie list in safari (iOS) it does not look like it does in Chrome (Win 8).
In Chrome it is logged as _syspass.domain.com_ but on Safari this does not exist, there is just an empty one for _domain.com_.

Unfortunately it is not possible to see the actual cookie data in iOS without attaching it to a computer with Safari installed.... bah

My guess is it is a cookie related issue on iOS, but I dont know how to get you more info at the moment. 


Thanks,
Basil

**Comment by nuxsmin** [comment]
Thanks so much for the testing! 

I will fix that issue by skipping the session encryption if it weren't available.

**Comment by nuxsmin** [comment]
Hi @basil-twisleton 

could you give a try to the latest release (not tagged yet, only master branch)?

**Comment by basil-twisleton** [comment]
Just tested current Master.

Login issue is now fixed
## Search issues
* there is no button to run the search
* the return button in iOS does not execute the search (but Enter in Windows does)

The rest of the filtering work (tags, customers, categories)

If you enter search text and then change one of the filters then the search will run.

## Create Account
There is some odd behaviour on the first password field.
Normally in iOS when you are typing a password it will preview the character you entered for a few seconds (or until the next character). This works perfectly on the second Password field (confirm password), but not on the first field. 

Other than these two items everything else seems to be working ok.

**Comment by nuxsmin** [comment]
Related #502

**Comment by nuxsmin** [comment]
Please let me know if the latest code from the master branch is working fine (https://github.com/nuxsmin/sysPass/archive/master.zip).

You can also test it on the demo site: https://demo.syspass.org
