### ISSUE TITLE
Brand new install doesn't allow me to complete installation

### ISSUE THREAD

**Issue by OverByThere** [nuxsmin/sysPass#494]
When I attempt to install [2.1.1] (using username of admin, and a generated password) I get the following error:
```
No es posible comprobar el usuario de sysPass (admin)
Compruebe los permisos del usuario de conexión a la BD
```

If I change the database details I get errors about the database, so I know they work, but the above doesn't seem to work.

I have full access to server so don't want to do the alternative hosted mode.
Any additional details I need to supply please let me know.

Apache/2.4.10 (Debian)
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
MySQL: Server version 5.5.54-0+deb8u1

Any thoughts on this would be grand.

Thanks.

**Comment by OverByThere** [comment]
Additionally, the install is stuck in Spanish, even though I have done the changes in #209

**Comment by cyb0rg01** [comment]
Try to install php-mbstring and php-xml packages. This worked for me though.

**Comment by nuxsmin** [comment]
Hello,

I know there is any weird issue when creating the sysPass DB connection user and I'm working to fix it. That is because the installer firstly creates the sysPass connection user (AKA sp_admin -or whatever you set prefixed by sp_-) and then it switches to its won user to populate the database structure (ie. tables, views, data). 

About the Spanish strings, it should be something missing on your environment. Please check that locales are installed on the UTF8 variant and the webserver (Apache?) has been restarted.

Regards.

**Comment by OverByThere** [comment]
Hi @nuxsmin Okay is there a set way to setup the DB then?

I've set the locales as best I can but currently still stuck in Spanish.. I've now reinstalled and still getting same issue.

Packages above mentioned by @cyb0rg01 are installed.

Sorry if I'm confusing things!

**Comment by nuxsmin** [comment]
Hi @OverByThere you could try click a few times on the install button (right it sounds tricky) and it would let you install after a few tries...

Regarding locales, did you restart the webserver?

No worries, it's all right.

**Comment by nuxsmin** [comment]
@OverByThere please check out the latest commit in the master branch that should fix the installation issue.

**Comment by OverByThere** [comment]
@nuxsmin I decided to re-partition the server it was on.. I'll look at in around 5 hours at this rate! Thank you, I'll get back to you if it fixes!

**Comment by nuxsmin** [comment]
That's great!

**Comment by nuxsmin** [comment]
Hi @OverByThere 

I'm wondering whether it worked or not. Did you try out with the latest commit (from master branch)?
