### ISSUE TITLE
cannot login with a new account

### ISSUE THREAD

**Issue by jsaada** [nuxsmin/sysPass#496]
hello,
i'm loggued as admin, i just create a new user with admin role but i cannot login 

even if i tried to recover the password by email and follow the process
same issue with a non admin user ...
i take a look at the DB, and for my 2 buggy users , user_mPass and user_mKey fields are empty

my install is from this release:
https://github.com/nuxsmin/sysPass/archive/2.1.1.17030601.tar.gz

![image](https://cloud.githubusercontent.com/assets/2253763/23803299/677abc80-05b6-11e7-813d-a0c56011860c.png)

thank you

**Comment by nuxsmin** [comment]
Hello,

Did it display any error?

The DB fields are related to the master key, so if the user has never log in, they won't be set.

**Comment by jsaada** [comment]
hi
"login incorrect" ( français )
nothing in the syspass.log

**Comment by nuxsmin** [comment]
And what about the webserver log, is there any error there?

**Comment by jsaada** [comment]
hello

here is the acces log ( no erreur on apache log ):
the fail to login:
GET /ajax/ajax_doLogin.php?user=jerome&pass=****&oldpass=&mpass=&login=1&isAjax=1&_=1489420101304 HTTP/1.1" 200 102 "https://syspass.****.net/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"

the admin which is working
"GET /ajax/ajax_doLogin.php?user=myadmin&pass=sum0****&oldpass=&mpass=&login=1&isAjax=1&_=1489420101305 HTTP/1.1" 200 104 "https://syspass.****.net/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0"

**Comment by nuxsmin** [comment]
The request seems good. Are you using LDAP auth?, The password should be encrypted (very long string), isn't it?

**Comment by jsaada** [comment]
yes
very long password, ( 189 car )
no LDAP here
there is one plugin, i don't know if it s mandatory, but it s disabled by default

**Comment by nuxsmin** [comment]
The plugin is not needed.

Are you using the same case for the login? (the login is case sensitive)

**Comment by jsaada** [comment]
yes
i just create a new account for test:
"blah" everywhere ( login/pass/name/... ) with cut and past to be sure
but still cannot login

just to be sure, when i focus out of a password field, the input value become huge, i guess this is because of client encryption

**Comment by nuxsmin** [comment]
Still investigating...

**Comment by nuxsmin** [comment]
Which version are you running on?

**Comment by nuxsmin** [comment]
Do you use "Auth Basic" on your web server?

**Comment by jsaada** [comment]
hello,
yes there is auth digest in front of the website
is there something i should do about it ?

**Comment by nuxsmin** [comment]
Hello,

the auth username need to match with the sysPass username. That is so because this kind of auth is used for authorization: https://doc.syspass.org/en/application/authorization.html

Regards.

**Comment by jsaada** [comment]
i understand this could work but only for auth basic where the password can be retrieve
here i am using auth digest
i tried to remove the header in my vhost:
RequestHeader unset Authorization
in phpinfo, the result is ok but i still cannot login with my blah/blah user

in index.php i also added ( with no succes ):
unset($_SERVER['PHP_AUTH_USER']);
unset($_SERVER['AUTH_TYPE']);
unset($_SERVER['REMOTE_USER']);

**Comment by nuxsmin** [comment]
Since PHP_AUTH_USER is read from PHP, sysPass will compare this username against its own user's login, so they will need to be equal (note it's case sensitive) to grant access.

The `index.php` file is only used to load the main screen, but there are many scripts that won't use it (ie. Ajax or plugins).

To sum up, you could get it working by setting the same user's login in sysPass.

**Comment by nuxsmin** [comment]
BTW, sysPass will log in the event log the offending username

**Comment by nuxsmin** [comment]
You can also comment out the `AuthBrowser` behavior in: 

https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Auth/Auth.class.php#L70

**Comment by jsaada** [comment]
thanks again for your help
now everything is working properly

**Comment by nuxsmin** [comment]
Great!! That sounds good, what did you do?

**Comment by jsaada** [comment]
same username for digest auth / syspass ;)

**Comment by nuxsmin** [comment]
Nice, thanks for the feedback!
