### ISSUE TITLE
After update can not loggin in Safari

### ISSUE THREAD

**Issue by marawu** [nuxsmin/sysPass#497]
Hi, i updated before version 2.1.1 and i can not login in Safari:(

I check in Mozilla and Chrome and all right. 

In Safari me returning on login page. I view log-file, but not view errors

How to fix it?

**Comment by nuxsmin** [comment]
Hi, this issue is related to the Safari cookies handling. I've done some code changes on the latest release 2.1.2 (not tagged yet), which can be downloaded from the master branch: https://github.com/nuxsmin/sysPass/archive/master.zip

Related #493 

Regards

**Comment by marawu** [comment]
Sorry, but i try touch button "Update" nothing happens :(

**Comment by nuxsmin** [comment]
The updating process need to be done manually. Please, perform a backup, download from the link above and replace the existing files. This release does not need any upgrade.

**Comment by marawu** [comment]
Thanks, it work!

**Comment by nuxsmin** [comment]
That sounds great!. Thanks for the feedback!
