### ISSUE TITLE
sysPass 2.1 Install Issue

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#498]
Hey Rubén,

I created a new sysPass 2.1 instance, entered all needed data during setup which finished successfull. After Setup I'm trying to login but I'm getting an error:

> Internal Error

I don't have any entry regarding this problem in webserver log, just this:

> xxx.xxx.technology [Mon Mar 13 08:02:03.007211 2017] [-:error] [pid 12417] [client 185.111.192.4:35460] Setup log file: /nfsmnt/hosting2_1/c/3/c3618d26-dbe0-436d-a4e5-95aa6eed1ce9/xxx.technology/sub/trezor/inc/../config/syspass.log, referer https://xxx.xxx.technology/index.php

What could be the problem?

I used as database server -> unix:/tmp/mariadb101.sock

Thank you,
Lukas

**Comment by lukasp2** [comment]
In my DB in table "log" I see this:

Table "log_action" -> Login
Table "log_description" -> **Invalid IP**

**Comment by nuxsmin** [comment]
Hi Lukas,

that message is because the app couldn't get the client IP address to keep tracking of wrong log in attempts. Is your sysPass instance behind a proxy?

I've just added the incorrect IP address in logging messages, in the latest commit to master branch.

Regards.

**Comment by lukasp2** [comment]
sysPass instance is not behind a proxy, but my client is behind a proxy

Thank you, I will try it

**Comment by lukasp2** [comment]
Same error with last master branch :-(

**Comment by nuxsmin** [comment]
That's right because the latest release only logs the wrong IP address. Could you see it in `syspass.log`file (in config directory)?, How is the address looks like?

**Comment by lukasp2** [comment]
This is the content of syspass.log:

> 2017-03-13 09:09:13 - Session data not encrypted.
> 2017-03-13 09:09:22 - Invalid IP : 185.111.192.4, 185.111.192.4
> 2017-03-13 09:09:27 - Generating a new session key.

**Comment by nuxsmin** [comment]
Hi, it should be fixed in the latest commit (just pushed). Please let me know if it works

**Comment by lukasp2** [comment]
Hi,

now I'm getting these erros / messages in "syspass.log":

> 2017-03-13 12:08:07 - Integrity check failed.
> 2017-03-13 12:08:07 - Integrity check failed.
> 2017-03-13 12:08:07 - Session data not encrypted.

**Comment by nuxsmin** [comment]
Those errors are related to the session encryption feature. It's most likely because some scripts ran before the encryption took place, but you can verify it by looking at the sysPass information tab. Please make sure your browser has a cookie named "SYSPASS_SK".

**Comment by lukasp2** [comment]
I'm not able to login, I'm getting always back after login to my sysPass instance

**Comment by nuxsmin** [comment]
Are you using Safari? Does your browser have the 'SYSPASS_SK' cookie?

**Comment by lukasp2** [comment]
I used FireFox in privacy mode, that was my problem.

**Comment by lukasp2** [comment]
Other question: How Can i get my Data Backup (SQL) to sysPass 2.1 ?

**Comment by nuxsmin** [comment]
Do you mean how to import a 2.0 backup into 2.1?

**Comment by lukasp2** [comment]
yes

**Comment by nuxsmin** [comment]
Umm, goto #466 

In the first comment there is a brief howto about the upgrading using a db backup.

**Comment by lukasp2** [comment]
Is that working for hosting mode too?

**Comment by nuxsmin** [comment]
Yes, the hosting mode does only matter when you're installing the app, because it skips some installation steps.

**Comment by lukasp2** [comment]
I'm not able to create the user "sp_admin" via phpMyAdmin

**Comment by nuxsmin** [comment]
Don't worry about the user, you can create another user and then grant permissions over the imported database. This user need to be set in the XML

**Comment by lukasp2** [comment]
ah okay, then I'll try that now

**Comment by lukasp2** [comment]
After klicking on "updade" button on update screen, nothing happens...

**Comment by lukasp2** [comment]
I have not seen any progress, I tried just after some time to open my usual syspass URL and that worked for me now

**Comment by nuxsmin** [comment]
Umm, it seems weird. Please take a look to `syspass.log`file, it should log some stuff there, because there are some db upgrades from 2.0 to 2.1

**Comment by lukasp2** [comment]
I can see the progress in syspass.log , but I haven't seen any progress in my browser

**Comment by nuxsmin** [comment]
Did it finish fine (in `syspass.log`)?

**Comment by lukasp2** [comment]
are these the "finish" entries in syspass.log ?

> 2017-03-13 14:52:44 - Total time: 62,9210889339
> 2017-03-13 14:52:44 - Deregister Task: upgrade

**Comment by nuxsmin** [comment]
Right, those are the finish entries....

**Comment by lukasp2** [comment]
Okay, fine. Then close this Issue and thank you for your support
