### ISSUE TITLE
Dudas (wiki / export)

### ISSUE THREAD

**Issue by davidkast** [nuxsmin/sysPass#499]
Hola nuxsmin,

¿Podrías explicarme la función del apartado wiki? 
Instalé dokuwiki y configuré el acceso desde dokuwiki pero no veo la función de tenerlo configurado, como debería de usarse?

Y por otro lado, cuando se exporta la BD como XML esta cifrada, por lo que leí se puede desencriptar mediante herramientas externas al proyecto, pero no me queda claro cual sería la clave de cifrado, es la clave maestra? o alguna de entradas del archivo config.xml:
- configHash
- export_hash
- passwordSalt
- backup_hash

Gracias por tu ayuda.

**Comment by nuxsmin** [comment]
Hola David,

La opción de dokuwiki permite mediante un prefijo en el nombre de la cuenta, enlazar las que coincidan con la página en dokuwiki si la tiene, es decir, si el nombre de la cuenta coincide con la página. Si no coincide se muestran los resultados de una búsqueda en dokuwiki.

La página es mostrada dentro de sysPass (sin iframes) mediante una llamada a la API y posteriormente formateando el resultado.

Poco a poco iré añadiendo funcionalidades como dar de alta/baja y otras opciones de la API de dokuwiki.

Con respecto al XML encriptado, entiendo que usas la versión 2.1, por lo que es necesario hacer uso de la librería Defuse\php-encryption para obtener la clave a partir de la clave maestra. Esto es así porque se utilizan funciones estándar de OpenSSL,bcrypt y hmac para la encriptación y autentificación del texto cifrado.

No son herramientas al uso, pero sí se utilizan estándares abiertos y auditados.

En breve publicaré dicha herramienta para facilitar su uso.

Saludos!

**Comment by davidkast** [comment]
Perfecto, esperaré con ansias esas mejoras.

**Comment by julenpardo** [comment]
Buenas @nuxsmin,

Si existieran detalles sobre cuáles serían los pasos a seguir para obtener la clave de descifrado del XML a partir de la clave maestra, podría realizar la implementación de la herramienta para obtenerla, ya que necesitamos el XML descifrado para realizar una migración. Detalles a alto nivel, más que nada para saber qué coger y de dónde, porque no disponemos de tiempo para bucear en el código.

Gracias y saludos.

**Comment by nuxsmin** [comment]
Buenas @julenpardo 

si se ha exportado en un XML encriptado, el código que lo realiza es:

https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Import/SyspassImport.class.php#L136

```
                $securedKey = Crypt::unlockSecuredKey($node->getAttribute('key'), $this->ImportParams->getImportPwd());
                $xmlDecrypted = Crypt::decrypt($data, $securedKey, $this->ImportParams->getImportPwd());
```

el cual llama a un wrapper (clase `Crypt`) que invoca los métodos de la librería Defuse/php-encryption (https://github.com/defuse/php-encryption).

Posteriormente, cada clave de cuenta se encuentra encriptada con la clave maestra, la cual es obtenida de la sesión del usuario, que se encuentra en un objeto de la clase `Vault` (https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Core/Crypt/Vault.class.php). Este objeto contiene la clave maestra encriptada y se utiliza (mediante wrapper) en https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Import/ImportBase.class.php#L142 para obtener la clave de la cuenta.

La clave maestra, inicialmente, está almacenada con los datos del usuario, que cuando realiza el login la obtiene desde https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Mgmt/Users/UserPass.class.php#L161

Espero que te sirva ;)

Saludos!

**Comment by julenpardo** [comment]
Muchas gracias @nuxsmin,

Si tengo alguna duda, preguntaré.

Saludos.

**Comment by julenpardo** [comment]
Hola @nuxsmin,

He creado [esta simple utilidad](https://github.com/julenpardo/sysPass-XML-Decrypter) para descrifrar las credenciales a partir del XML exportado.

Lo he creado de forma independiente a sysPass, porque sólo necesitábamos algo ad-hoc para realizar una sola exportación. Pero puedes modificarlo e integrarlo en sysPass como creas conveniente.

PD: por ahora sólo se exporta en un formato `cuenta:contraseña`, en lo sucesivo haré que sea posible exportarlo en formato para LastPass.

Saludos.

**Comment by nuxsmin** [comment]
Genial @julenpardo !! Ya sabes que tenía pendiente esta utilidad, por lo que será de gran ayuda para aquellos que deseen exportarlo como medida de seguridad.

Un detalle a tener en cuenta es que sería conveniente devolver el cliente de la cuenta, ya que pueden existir cuentas con el mismo nombre y sólo se diferencia el cliente, por lo que la modificaré para ello :)

Haré un hueco en la documentación para las aportaciones/utilidades.

Muchas gracias!!

**Comment by julenpardo** [comment]
No había caído @nuxsmin, lo puedo hacer yo mismo si quieres, ya que voy a tener que seguir modificándolo para hacer la exportación compatible con LastPass :)

**Comment by julenpardo** [comment]
Hola de nuevo @nuxsmin,

En la exportación ya se incluyen las categorías y clientes de las cuentas.

También hace la exportación en CSV con el formato necesario para LastPass.

Un saludo.

**Comment by nuxsmin** [comment]
Gran aporte, gracias!!
