### ISSUE TITLE
[ISSUE] Since last version no LDAP import

### ISSUE THREAD

**Issue by cyb0rg01** [nuxsmin/sysPass#501]
Hey there,

since your last version (2.1.2) I am not able to import my users via LDAP (Active Directory). The problem is kinda weird, because it shows no error. Nor in the httpd error log else in the syspass.log. 

LDAP is able to collect my users, but when I hit the "Import" button, nothing happen.

29	2017-03-14 08:57:00	INFO	checkConnection	ADMPASS	x.x.x.x	LDAP connection OK
Objects found : 23
28	2017-03-14 08:56:11	INFO	Edit Configuration	ADMPASS	x.x.x.x	LDAP enabled
Configuration updated
Section : LDAP

The LDAP user is correct and running, as you can see in the eventlog.

Any guess, what could be wrong?

**Comment by Sispheor** [comment]
I don't know if it's the same issue but this is what I have in error.log
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /var/www/html/syspass/inc/SP/Auth/Ldap/LdapBase.class.php on line 276, referer: http://16.16.94.238/syspass/index.php
```

My AD has a lot of user. Does the code try to import each users? It's not just a read?

**Comment by Sispheor** [comment]
Also, after saving my LDAP/AD config, if I leave the config menu and come back to it, my config is gone.
I don't know if it's saved or not and effective.

**Comment by cyb0rg01** [comment]
Well, my LDAP/AD config is saved and seems to be effective too.

**Comment by nuxsmin** [comment]
Hi @cyb0rg01 

please refresh your browser (F5), because some Javascript files have been changed so the function that handles the import button could be missing.

@Sispheor the LDAP import would import all the objects found in the search base.

**Comment by cyb0rg01** [comment]
Hi @nuxsmin 

well, I have installed (only for you) Mozilla's Firefox on my rig (normally using Google's Chrome). It still does not work. I hit CMD+R (F5 on Mac) and CMD+SHIFT+R multiple times. The script does show the user via LDAP, but they don't get imported.

**Comment by cyb0rg01** [comment]
Okay, I don't know why, but suddenly it works again.

I closed Firefox and reopen it. Tried it again. And now, it works. :-D

**Comment by nuxsmin** [comment]
Great!...thanks for the feedback and testing!

**Comment by Sispheor** [comment]
if I don't use ldap, but AD. I don't need to import user, ,right?

**Comment by nuxsmin** [comment]
Ummm, AD is an LDAP directory :)

Every LDAP granted user (by group filtering) would be able to access to sysPass through normal login (the user will be created if not exist), and it would be assigned the default group and profile set on the config, but you can also import the users to pre-assign the group and profile for each imported user.

**Comment by nuxsmin** [comment]
Solved
