### ISSUE TITLE
Find is not working in Safari

### ISSUE THREAD

**Issue by marawu** [nuxsmin/sysPass#502]
Hi, i upgrade syspass to version 2.1.2 because this [problem](https://github.com/nuxsmin/sysPass/issues/497). But unfortunately now find is not working in Safari (in Firefox work). I press enter and then nothing happens :(

**Comment by nuxsmin** [comment]
Hi, there is no special behavior on the search form, because it relies on the "submit" event itself which is the default behavior for every HTML form.

BTW, I'll take a look to get it working fine

**Comment by nuxsmin** [comment]
This issue could be related to: http://stackoverflow.com/questions/18306752/pressing-enter-return-key-doesnt-trigger-button-click-in-safari#18306817
and this:
https://discussions.apple.com/thread/6038119?start=0&tstart=0

I think that Safari is not working as expected (may be a bug?)

**Comment by marawu** [comment]
Sry, but after update i can not remove user (i use ldap). The user at the entrance to the white screen and nothing happens. I need new issues?

**Comment by nuxsmin** [comment]
Sorry, but I don't know which user you mean to :(

**Comment by marawu** [comment]
Service use about 20 users. All login through ldap. After update 1 user can not login. He is enter login/pass and nothing happens. Just white screen. I try him remove, but can not do it

**Comment by nuxsmin** [comment]
The latest issue is most likely because the user's browser has some Javascript errors.

The user couldn't be removed because it could be in use by some application items like accounts or self password change requests.

**Comment by marawu** [comment]
User login on different device and trouble remains

**Comment by nuxsmin** [comment]
Hi, could you try out the latest release?

**Comment by marawu** [comment]
Hi, sorry, i have one’s hands full. I check today

**Comment by marawu** [comment]
Sry, but i can not is update. 

I download https://github.com/nuxsmin/sysPass/releases/tag/2.1.4.17032801 and copy files to my site

I open site in safari and have error, but the banner disappears immediately

![2017-03-30 12 53 49](https://cloud.githubusercontent.com/assets/17287815/24489613/ab2bc248-1548-11e7-86be-1abae4fe1f37.png)

I paste upgradekey and have 502 error from nginx.

I again refresh page and see message:

Aplicación en mantenimiento
En breve estará operativa

What am I doing wrong?

PS. Why my site became on Spanish?

**Comment by nuxsmin** [comment]
Hi,

I can't guess what could be happening. You can resume the upgrade process by pointing to the url: `index.php?a=upgrade&type=db`. The language shouldn't has been changed, indeed the log is set to English, so it could be a session issue.

Could you try out by pointing to the URL above?

**Comment by marawu** [comment]
I succeeded upgrade. I removed all files and leave only directory with config. Upgrade successful, but find in Safari still not working. :'(

**Comment by nuxsmin** [comment]
Hi @marawu some people told me that the latest release from the master branch works fine, could you try it out?

**Comment by marawu** [comment]
Hi, unfortunately is not working :( I use:

Client:
Safari 10.0.3 (12602.4.8) (macOS 10.12.3)

Server:
Debian GNU/Linux 8.4 (jessie)
nginx/1.10.2


I check on 5 different device and nowhere not work in Safari, but excellent work in Firefox.

Perhaps I'm doing something wrong?

**Comment by nuxsmin** [comment]
Some comment above I pointed to:

> 
> This issue could be related to: http://stackoverflow.com/questions/18306752/pressing-enter-return-key-doesnt-trigger-button-click-in-safari#18306817
> and this:
> https://discussions.apple.com/thread/6038119?start=0&tstart=0
> 
> I think that Safari is not working as expected (may be a bug?)

So it doesn't work on Safari indeed :(

**Comment by nuxsmin** [comment]
May be this could work:

https://9to5mac.com/2016/01/27/safari-on-ios-and-mac-crashing-today-for-many-users-bug-related-to-safari-suggestions/

**Comment by marawu** [comment]
Hi, i check, i disable  Safari Suggestions. It did not help :(

**Comment by nuxsmin** [comment]
:(

**Comment by nuxsmin** [comment]
Please let me know if the latest code from the master branch is working fine (https://github.com/nuxsmin/sysPass/archive/master.zip).

You can also test it on the demo site: https://demo.syspass.org

**Comment by marawu** [comment]
E man, it working! Thanks!

**Comment by nuxsmin** [comment]
Great!, thanks for the feedback!
