### ISSUE TITLE
Duplicate user login/email Again

### ISSUE THREAD

**Issue by maxdie** [nuxsmin/sysPass#504]
Hello, all!
Have trouble to autenticate in sysPass via LDAP
Import User from AD
![image](https://cloud.githubusercontent.com/assets/26085639/23948229/2b1890a6-0993-11e7-92f4-4dff4566eaec.png)

Log from authentication
![image](https://cloud.githubusercontent.com/assets/26085639/23948251/447a91ca-0993-11e7-9cd1-07a419307f66.png)

In Web 
![image](https://cloud.githubusercontent.com/assets/26085639/23948284/6ad45536-0993-11e7-9685-d1f345cce5b9.png)

The FIX https://github.com/nuxsmin/sysPass/commit/e97a9c5b16d261c9eba09caed3cbdd4b90cd85bb do not resolve my trouble.

Please help resolve the issue.

**Comment by nuxsmin** [comment]
Hello, is there any duplicated login or email indeed?

**Comment by maxdie** [comment]
Hello. 
I import 4 user from AD group who have Admin priveleges on sysPass.
Name, Login and email is different on AD and sysPass.
But login not sAMAccountName get form from uID atribute.

![image](https://cloud.githubusercontent.com/assets/26085639/23950013/9eca9290-099a-11e7-9e84-29fe2f9e5da6.png)

![image](https://cloud.githubusercontent.com/assets/26085639/23950131/fb4ce66c-099a-11e7-8d21-b96d1d581f26.png)

**Comment by nuxsmin** [comment]
Ok, Did you mean that the uid as login is wrong?

**Comment by maxdie** [comment]
No, uid is temporaty object from another bussines-software. By default the object uid is empty. The samAccounts object right login form, from ActiveDirectory. After Import user in  sysPass visible login have form uid object, but if I try authenticate with uid logon name have mesage "ERROR Log in  Type : authBrowser Type : authLdap LDAP Server : xxx.xx.xxx.xx " if use real samAccountsName message "	Duplicated user login/email"

Sorry for my english.

**Comment by nuxsmin** [comment]
Don't worry, I understood your issue. 

I'm currently solving it by adding an option to select which LDAP attribute should be used to the user's login. So the sysPass user's login will be the sAMAccountName in your case...

**Comment by maxdie** [comment]
Thank you very match. I will wait.

**Comment by cyb0rg01** [comment]
To simplify it: You should always use the **sAMAccountName** as your login. This is beside the UID the most unique value, to be honest. I think you should force with your code, thats my professional view.

**Comment by nuxsmin** [comment]
It should be fixed in the latest commit to the master branch. Please download from the master branch

**Comment by maxdie** [comment]
Hello.
Issue not resolve 
When I try import sAMAcountName/ uid get messages
![image](https://cloud.githubusercontent.com/assets/26085639/23990823/4aea20ec-0a48-11e7-9ad2-173056c71b14.png)

When I try import userPrincipalName or login get messages 
![image](https://cloud.githubusercontent.com/assets/26085639/23990878/750d9c32-0a48-11e7-9bc6-c1c207a7cafe.png)
But in User tab in sysPass is empty

**Comment by maxdie** [comment]
From apache Log when I import
[Thu Mar 16 13:07:24.804948 2017] [:error] [pid 11691] [client 10.111.33.180:22499] PHP Fatal error:  Uncaught Error: Call to undefined method SP\\DataModel\\UserData::getLoginPass() in /var/www/html/sysPass/inc/SP/Mgmt/Users/UserLdap.class.php:116\nStack trace:\n#0 /var/www/html/sysPass/inc/SP/Mgmt/Users/UserLdapSync.class.php(112): SP\\Mgmt\\Users\\UserLdap->add()\n#1 /var/www/html/sysPass/inc/SP/Controller/ItemActionController.class.php(1080): SP\\Mgmt\\Users\\UserLdapSync::run(Array)\n#2 /var/www/html/sysPass/inc/SP/Controller/ItemActionController.class.php(179): SP\\Controller\\ItemActionController->ldapImportAction()\n#3 /var/www/html/sysPass/ajax/ajax_itemSave.php(35): SP\\Controller\\ItemActionController->doAction()\n#4 {main}\n  thrown in /var/www/html/sysPass/inc/SP/Mgmt/Users/UserLdap.class.php on line 116, referer: http://pass.local.net/index.php

**Comment by nuxsmin** [comment]
Please download the latest update from the master branch. It should be fixed.

**Comment by maxdie** [comment]
Supper!!!! All works.

Thank you very match.
