### ISSUE TITLE
Integrity check failed when viewing accounts after upgrade to 2.1.2

### ISSUE THREAD

**Issue by eth0h4ckr** [nuxsmin/sysPass#505]
Unable to view accounts after update. If i create a new account, i can view it just fine. Cookie exists and encryption in "Information" tab show "yes" for encryption is enabled.

OS: Ubuntu 14
PHP: 7.0
HTTP Server: Apache

**syspass.log**

```
2017-03-15 09:48:24 - Integrity check failed.
2017-03-15 09:48:28 - Integrity check failed.
2017-03-15 09:48:38 - Integrity check failed.
2017-03-15 09:49:09 - Generating a new session key.
2017-03-15 09:49:21 - Integrity check failed.
2017-03-15 09:55:22 - Integrity check failed.
2017-03-15 10:05:15 - Generating a new session key.
2017-03-15 10:07:04 - Integrity check failed.
2017-03-15 10:12:46 - Integrity check failed.
2017-03-15 10:14:37 - Integrity check failed.

```
**apache error.log**

`[Wed Mar 15 10:14:37.495729 2017] [:error] [pid 16389] [client 10.1.129.1:48646] PHP Fatal error:  Uncaught Defuse\\Crypto\\Exception\\WrongKeyOrModifiedCiphertextException: Integrity check failed. in /opt/apps/syspass/inc/Exts/Defuse/Crypto/Crypto.php:286\nStack trace:\n#0 /opt/apps/syspass/inc/Exts/Defuse/Crypto/Crypto.php(88): Defuse\\Crypto\\Crypto::decryptInternal('\\xDE\\xF5\\x02\\x00r\\x9E8\\xEA2l\\xCC\\xF1\\xCF\\xDC\\xE3...', Object(Defuse\\Crypto\\KeyOrPassword), true)\n#1 /opt/apps/syspass/inc/Exts/Defuse/Crypto/KeyProtectedByPassword.php(87): Defuse\\Crypto\\Crypto::decryptWithPassword('\\xDE\\xF5\\x02\\x00r\\x9E8\\xEA2l\\xCC\\xF1\\xCF\\xDC\\xE3...', '\\xE9\\xC4:\\xED\\xAA\\x02\\xF6\\x87\\xCD\\x8F@b\\x01]\\x10...', true)\n#2 /opt/apps/syspass/inc/SP/Core/Crypt/Crypt.class.php(79): Defuse\\Crypto\\KeyProtectedByPassword->unlockKey('..')\n#3 /opt/apps/syspass/inc/SP/Mgmt/CustomFields/CustomField.class.php(252): SP\\Core\\Crypt\\Crypt::unlockSecuredKey('def10000def5020...', '...')\n#4 /opt/apps/syspass/inc/SP/Mgmt/CustomFields/CustomField.class.php(234): SP\\Mgmt\\CustomFields\\CustomField->unencryptData(Object(SP\\DataMode in /opt/apps/syspass/inc/Exts/Defuse/Crypto/Crypto.php on line 286, referer: https://syspass.example.com/index.php
`

**Comment by nuxsmin** [comment]
Hello, it's some issue related with custom fields data.

Does it happen with all the accounts?. Is there any error in the syspass.log during the upgrade?. Can you see the accounts password?.

 Those errors above are normal when setting up the session encryption.

**Comment by eth0h4ckr** [comment]
I was unable to view account passwords for all the accounts I tested. We had custom fields on all of our accounts. Unfortunately I wont be able to provide much more information as i had to revert back to a snapshot in production. I should be able to get a test enviroment up in the next few days and provide some more feedback.

**Comment by nuxsmin** [comment]
Ok, I'll wait for your feedback, because I've done a bunch of upgrading tests with a sysPass instance with ~4000 records and it worked fine (even restarting the upgrade process when running), so I would need some more info to find out what could be happening.

**Comment by eth0h4ckr** [comment]
Alright. So performing similar steps using the same environment and using the latest version (2.1.3) it looks like everything is working so far. I will do so more testing tomorrow and report back once I have some other users take a look. Thanks for your help nux. I know you're pretty busy but you always respond quickly and it's much appreciated.

**Comment by nuxsmin** [comment]
Thanks for the feedback @eth0h4ckr !

I'm also aware that you invest some time to test, find out some issues and even resolve them, so thanks again for your time.

**Comment by eth0h4ckr** [comment]
Everything seems to be working well now after the 2.1.3 update. Thanks again!
