### ISSUE TITLE
sysPass 2.1.2 - Paging options after changing number items display

### ISSUE THREAD

**Issue by ejouvin** [nuxsmin/sysPass#506]
On 2.1.2, On first display, I have some items and the navigation options are :
* page 1/X
* Navigation to next or last page

![image](https://cloud.githubusercontent.com/assets/8817923/23974763/4a87052c-09dd-11e7-9e91-067c38f02018.png)

I change the display number to the max.
![image](https://cloud.githubusercontent.com/assets/8817923/23974774/5b349376-09dd-11e7-8b89-375f79be9c9a.png)

Then I click to next page, but I am still on first page, why not. But I have the option to go to previous page
![image](https://cloud.githubusercontent.com/assets/8817923/23974810/98522bce-09dd-11e7-8891-cb80f31fdb93.png)

And when I click on previous, it will go to an empty page, and no more pagination options.

Not a big deal, but just to mention it.

Etienne

**Comment by nuxsmin** [comment]
Solved in latest release (or not reproducible anymore)
