### ISSUE TITLE
[QUESTION] How to update sysPass?

### ISSUE THREAD

**Issue by cyb0rg01** [nuxsmin/sysPass#508]
Hey there,

I am coming from version 2.1.1 and tried to update to version 2.1.3. I did like you wrote in your docs, but it didn't worked. The installation started again and I am not able to access it.

In your docs its written, that you have to set the permissions and copy the files config.xml, key.pem and pubkey.pem from the configs-folder. I did it like its written there.

Any other trick to update it to the latest version?

**Comment by nuxsmin** [comment]
Hi,

If you set the right permissions before accessing to the site, it should work. Now, you can edit the config.xml file and set the tag 'installed' to 1 so it should run fine and then redirect to the upgrade page.

**Comment by cyb0rg01** [comment]
The permissions have been set correctly, but they need to set recursive, as much as the access rights.

A `chmod -R 750 config/` and `chown -R apache config/` helped.

But it hasn't updated the base version, it still says "Running on 2.1.2", but the sources are from the 2.1.3 release.

**Comment by nuxsmin** [comment]
Hi, sorry, I missed to update the version number in the code so some update steps (like database) won't take place, but be sure that the code is up to date. The db upgrade process (a minor one) will be ran in the next release.

**Comment by nuxsmin** [comment]
BTW, you could get it from the master branch, which next version will be 2.1.4

**Comment by nuxsmin** [comment]
Thanks for the feedback! ;)
