### ISSUE TITLE
Error while upgrading to 2-1-3.

### ISSUE THREAD

**Issue by vvascautan** [nuxsmin/sysPass#510]
Hello,
I am trying to upgrade from 1.2 to 2-1-3 and I am getting HTTP ERROR 500 and following error in apche-error-log
[Mon Mar 20 15:39:16.822273 2017] [:error] [pid 11183] [client 185.34.203.0:42552] PHP Fatal error:  Call to undefined function SP\\Core\\Crypt\\hash_equals() in /var/www/html/pdb_2-1-3/inc/SP/Core/Crypt/Cookie.class.php on line 60

Server is running on CentOS7, with PHP 5.4.16.
Configs were copied and directory permissions were set correctly.

Thank you!

**Comment by nuxsmin** [comment]
Hello,

sysPass >= 2 will require PHP 5.6, so it will fail when loading (an error is shown when installing, but I'm working to display an error when loading the app).

Regards

**Comment by nuxsmin** [comment]
This issue has been fixed in the latest commit. PHP version will be detected during initialization.

Thanks for the feedback!

**Comment by vvascautan** [comment]
Confirm that I was able to perform the upgrade after installing PHP5.6

Thanks!

**Comment by nuxsmin** [comment]
Great!, thanks for the feedback!
