### ISSUE TITLE
[2.1.3] version display in Information

### ISSUE THREAD

**Issue by ejouvin** [nuxsmin/sysPass#511]
Just upgrade to version 2.1.3, and I wanted to check the version number.

But it is displayed 2.1.2.17031601
Do you also have this ?

![image](https://cloud.githubusercontent.com/assets/8817923/24175313/d17dca54-0e95-11e7-974b-9dca40fe6e3f.png)

It seems the config.xml was not updated.

**Comment by nuxsmin** [comment]
Right​, I missed to change it in the code. That will be solved in the next release and then a db upgrade will be triggered. 

Thanks for the notice!
