### ISSUE TITLE
[2.1.3] Seurity issue on config.xml file

### ISSUE THREAD

**Issue by ejouvin** [nuxsmin/sysPass#512]
By default, there is the config.xml file in the folder config.

But without any specific configuration on web server, everyone can access to the config.xml file, and other files.

Meaning, you can access to any the LDAP password, for example, and the login/password for the database.

**Comment by ejouvin** [comment]
For an Apache server, I did create a file .htaccess in the config folder with the following content.

```
# line below if for Apache 2.4
<ifModule mod_authz_core.c>
Require all denied
</ifModule>

# line below if for Apache 2.2
<ifModule !mod_authz_core.c>
deny from all
</ifModule>

# section for Apache 2.2 and 2.4
IndexIgnore *

```

**Comment by nuxsmin** [comment]
You're right and thanks for the feedback, but that is told in the documentation:

http://doc.syspass.org/en/application/security.html

You can also place the config folder outside the web root and then create a symlink to it and deny follow symlinks in the apache directory config.

**Comment by ejouvin** [comment]
Oups, sorry did not get this documentation page.

Thanks

**Comment by nuxsmin** [comment]
Don't worry...It's fine to be concerned about security risks.
