### ISSUE TITLE
sysPass 2.1 on CentOS 7

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#513]
Hi Rubén,

i'm currently playing with CentOS 7 and followed your documentation to install sysPass on CentOS 7.
When I enter all needed Data on SysPass Installation Page and goto Install, I get this error:

> Error 1045: SQLSTATE[HY000] [1045] Access denied for user 'sp_syspass-admin'@'localhost' (using password: YES)

What's wrong? Database will be during Setup created.

Thank you and Br,
Lukas

**Comment by lukasp2** [comment]
When I try "hosting mode" I get this error:

> There was an error
> Internal Server Errorerror

Content of syspass.log:

> 
> 2017-03-23 10:13:46 - Action: Configuration -- Description: Update Configuration -- Details:
> 2017-03-23 10:13:49 - Action: Configuration -- Description: Update Configuration -- Details: Parameter : version
> Value : 21417032001

**Comment by lukasp2** [comment]
Sorry, my fault...I forgot to install php-xml module!

**Comment by nuxsmin** [comment]
That sounds great!

Sorry, I haven't got enough time to check out this. BTW I'll add some info in the documentation.

Thanks for the feedback!

**Comment by lukasp2** [comment]
Other issues: I updated my Master Pass hash, after this I can't access syspass.
I'm getting this message since ~10 min.

> Application in maintenance
> It will be running shortly 

What's wrong?

**Comment by nuxsmin** [comment]
It's weird, but you can disable the maintenance mode in the config.xml file by setting the tag maintenance to 0.

**Comment by lukasp2** [comment]
Ok, thank you. That helped me with this issue.
