### ISSUE TITLE
2fa Spam

### ISSUE THREAD

**Issue by akzov** [nuxsmin/sysPass#516]
I keep getting messages such as: "The 2FA code will need to be reset within -1 days", "The 2FA code will need to be reset within -23 days"

Seems like all expiry does is spam messages, why does 2FA need to expire at all?

**Comment by nuxsmin** [comment]
Hello,

It's a security feature that was requested many times, so it was implemented since 2.0 version.

I've modified the current behavior to disallow the expiry date by setting it to 0. It will be available in the next release ;)

**Comment by nuxsmin** [comment]
Hello, this behavior has been solved in the latest release. You could set the expiry date to 0, so it would never notify about the expiry date.

**Comment by akzov** [comment]
Is it possible to implement the same thing for password expiry? It's confusing to end-users and the only feedback they get is "An error has occurred".

**Comment by nuxsmin** [comment]
Sure, it's already implemented, so you can left blank the expiry date and then​ it will never warns about the expiration.

**Comment by akzov** [comment]
If I leave it blank it will automatically fill in 1970-01-01 when editing, if a user doesn't know to blank this it will error

**Comment by nuxsmin** [comment]
Umm, that would be so because the SQL mode which prevents to left blank "datetime" fields type.

**Comment by akzov** [comment]
So why can't I disable it globally and not have to worry about it? The expiry for both 2fa and password does nothing but cause unknown errors and warnings to confuse end users...
