### ISSUE TITLE
Instalation error on Windows 2008 R2 and CentOS 7

### ISSUE THREAD

**Issue by sololuke** [nuxsmin/sysPass#52]
Hi,

Instalation is not working on Centos 7 (Mysql 5.6 Apache 2.4 and PHP 5.4) I get this errors on both v 1.1b and 0.9.
I also tried on Windows 2008 R2 with IIS and PHP 5.3 with FastCGI.

    Error on creating "admin" user
    Warn to developer

[Tue Jul 29 15:02:30.240406 2014] [:error] [pid 3336] [client 127.0.0.1:53926] PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 261, referer: http://127.0.0.1/sysPass/index.php
[Tue Jul 29 15:02:30.240425 2014] [:error] [pid 3336] [client 127.0.0.1:53926] PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 261, referer: http://127.0.0.1/sysPass/index.php
[Tue Jul 29 15:02:30.240442 2014] [:error] [pid 3336] [client 127.0.0.1:53926] PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 261, referer: http://127.0.0.1/sysPass/index.php
[Tue Jul 29 15:02:30.240522 2014] [:error] [pid 3336] [client 127.0.0.1:53926] PHP Warning:  mysqli::query(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 205, referer: http://127.0.0.1/sysPass/index.php
[Tue Jul 29 15:02:30.240537 2014] [:error] [pid 3336] [client 127.0.0.1:53926] PHP Warning:  DB::doQuery(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 211, referer: http://127.0.0.1/sysPass/index.php
[Tue Jul 29 15:02:30.240549 2014] [:error] [pid 3336] [client 127.0.0.1:53926] PHP Warning:  DB::doQuery(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 212, referer: http://127.0.0.1/sysPass/index.php
[Tue Jul 29 15:02:30.240562 2014] [:error] [pid 3336] [client 127.0.0.1:53926] PHP Warning:  DB::doQuery(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 215, referer: http://127.0.0.1/sysPass/index.php
[Tue Jul 29 15:02:30.240609 2014] [:error] [pid 3336] [client 127.0.0.1:53926] PHP Warning:  DB::doQuery(): Couldn't fetch mysqli in /var/www/html/sysPass/inc/db.class.php on line 215, referer: http://127.0.0.1/sysPass/index.php

**Comment by nuxsmin** [comment]
Hi there, thank you  for the points.

I will code that to avoid these errors.

Kind regards
