### ISSUE TITLE
Syspass allows login even user was not found in ldap

### ISSUE THREAD

**Issue by izenk** [nuxsmin/sysPass#520]
Hello.

sysPass version: 2.1 (2.1.2.17031601)
Database SERVER_VERSION : 5.5 
PHP	Version: 5.6.30-1+deb.sury.org~trusty+1 
Extensions: Core, date, ereg, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mcrypt, mysql, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, mhash, Zend OPcache 
Server: Apache 2.4

Ldap auth is enabled.
Search base: ou=Users,ou=Development Division,o=xxxxx,dc=ldap,dc=xxxxx,dc=com
Group is not set

I have a user, which is not in ou=Development Division. When he tries to login - he can't. It's ok.
Then I change his ou to "ou=Development Division" and now he can login. It's ok.

Then I change his "ou=Development Division" to "ou=Support" and he still can login.

This is ldap server log:

conn=27060122 fd=61 ACCEPT from IP=x.x.x.x:57417 (IP=0.0.0.0:636)
conn=27060122 fd=61 TLS established tls_ssf=128 ssf=128
conn=27060122 op=0 BIND dn="xxx" method=128
conn=27060122 op=0 BIND dn="xxx" mech=SIMPLE ssf=0
conn=27060122 op=0 RESULT tag=97 err=0 text=
conn=27060122 op=1 SRCH base="ou=Users,ou=Development Division,o=xxxxx,dc=ldap,dc=xxxxx,dc=com" scope=2 deref=0 filter="(&(|(?=undefined)(cn=**user**)(uid=**user**))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))"
conn=27060122 op=1 SRCH attr=dn displayname samaccountname postalAddress memberof lockouttime fullname groupmembership uid givenname sn
**conn=27060122 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=**
conn=27060122 op=2 UNBIND
conn=27060122 fd=61 closed

As you can see, nentries is 0, that means (as I understand) that user has not to login, because it was not founded in ldap. But in reality, user is able to login.

Is it correct behaviour?

**Comment by nuxsmin** [comment]
Hello,

That's right, because since the user has previously logged into the app, its data was saved, so the login would be granted using the saved data.

There would be some info in the event log regarding the auth method used.

Regards

**Comment by izenk** [comment]
Hello,
thank you for fast feedback.

Can you explain, please, what is goal of querying ldap server, if results of query not affect user login process in this case?

**Comment by nuxsmin** [comment]
Hello,

LDAP query takes precedence if the user exists, BUT, if the user has logged once, the user's data is stored in sysPass to allow offline access and save other data not related to LDAP like master key, preferences, etc.

If the user exists in LDAP the response from the server will determine if the login is granted/denied, because the user could be in several status like blocked, expired password, etc.

There is some info about this on: https://doc.syspass.org/en/application/authentication.html

Regards
