### ISSUE TITLE
Enable Edit for Secondary Groups

### ISSUE THREAD

**Issue by johnnyhotpants** [nuxsmin/sysPass#521]
Hello,

We've been using syspass at my company and it has been working great so far.  We have run into an issue regarding the edit capabilities of users belonging to secondary groups on accounts.

I'm not sure if this is a feature that was disabled in the upgrade but the "enable edit" option doesn't allow users belonging to a secondary group on an account to edit anything on the account.  Example:   "Test Group" is selected as a secondary group and "Admins" is the main group.  I am a member of "Test Group" and the option "Enable Edit" is clicked for this group.  However, when I am logged in and trying to update the password for this account, I do not have the ability to edit anything in the account.  

Is there a way around this?  I understand that the main group is able to edit accounts but we have clients who use our system and we would like for them to have the ability to edit certain accounts .  For a lot of these accounts, we would like to allow multiple groups the ability to edit them without giving them account admin status.

Here is the account I would like to give Test User the ability to edit
![enable_edit](https://cloud.githubusercontent.com/assets/26800226/24520283/e44e0c54-1555-11e7-8535-c675387c0eb6.png)

Here are the permissions I see for this account when logged in as Test User
![enable_edit_group](https://cloud.githubusercontent.com/assets/26800226/24520311/f50a872a-1555-11e7-849a-0d1f89de62be.png)

Thanks for all of your work with sysPass - so far it has been great!

**Comment by nuxsmin** [comment]
Hello, this has been recently discussed in #514 issue and the workaround would be to add an option to allow secondary groups to edit the account when the user has not set the secondary group as its main group.

It will be available shortly.

Kind regards and thanks for your support, I'm so glad that you found it useful.

**Comment by nuxsmin** [comment]
Please try out the latest release, this feature has been implemented.

**Comment by johnnyhotpants** [comment]
Hello,

We have updated to the latest release and I still don't seem to have the ability for users who are members of a secondary group on an account to edit, even when "enable edit" is checked.  I haven't been able to find a way around this yet, so any advice would be appreciated.

Thank you

**Comment by nuxsmin** [comment]
Hello, you would need to enable the option on the configuration>accounts tab.

**Comment by johnnyhotpants** [comment]
Hi there,  after checking the option, I still don't seem to have the ability to edit an account when I am granted access as a member of a secondary group.  I have always had access to accounts where my main group was listed as a secondary group, but I don't have the ability to edit the account.  The users in this secondary group are assigned a profile which gives them permissions to edit accounts but only have the option to "request modification" on these accounts instead of editing them temselves.  Let me know if this is an option that I am executing incorrectly.

**Comment by nuxsmin** [comment]
Hi, I'll check out the behaviour again, because it was tested after implementing and worked fine. One question, did you log out the user and then log in again after setting this option?

**Comment by johnnyhotpants** [comment]
Hello,  yes, I have logged out and logged in from that user after changing these configuration settings and I've also cleared my cache just to be sure.  Is there anything I can provide on my end that would possibly give you some more insight?

**Comment by johnnyhotpants** [comment]
Hi again, I just wanted to let you know that we have had multiple users test this feature and nobody has been able to enable the ability to allow secondary groups to edit accounts.  If you do find a solution to this, please let me know.  Thanks again for all of your hard work with sysPass - it is very much appreciated.

**Comment by nuxsmin** [comment]
Hi!, did you mean that they can only see those accounts?.

I really appreciate your feedback, it's very important for this project. Thanks too!!

**Comment by johnnyhotpants** [comment]
Hello!  Yes, they can see and access accounts (view passwords/usernames, etc).  I have attached a couple of screenshots of what it looks like as a user who's main group is the secondary group that is given "enable edit" access on an account.  They have a profile that allows them to edit accounts but when accessing them, they are not able to edit but can request modification.


![secondary user access](https://cloud.githubusercontent.com/assets/26800226/25134738/5e792118-241e-11e7-95be-e3d1bfadb124.png)


![secondary user access1](https://cloud.githubusercontent.com/assets/26800226/25134936/e8be6446-241e-11e7-886e-00c76dde9509.png)


Thanks again!  Let me know if I can give you any more information.

**Comment by nuxsmin** [comment]
Umm, really weird because I've just tested it on the demo site and works fine. 

Please, take a look to the user "demo_a" (pass=syspass) which is listed in "Group A" and has r/w access to those accounts where Group A is granted. The user's main group is "NETWORK"

**Comment by johnnyhotpants** [comment]
I have tested out in the demo version and it seems we are testing under different conditions.  I have created a new test user (test_z), test group (Test Z), test profile (Test-Z) and test account (Test Z Account) and given that user "enable edit" access to this test account as a secondary group.  To log in, the user is test_z (password=syspass).  If you view the profile and the account's main group on this site you can see the conditions I am trying to allow users access.  

I have noticed that through the demo, when looking at my account listings, I am met with the listing showing that I need to request modification if I want to edit:  
![screen shot 2017-04-18 at 11 24 16 am](https://cloud.githubusercontent.com/assets/26800226/25138840/999e0f78-2429-11e7-8363-f0fca371477a.png)

but when I click into the account it shows that I am able to edit:

![screen shot 2017-04-18 at 11 24 57 am](https://cloud.githubusercontent.com/assets/26800226/25138875/ac92c45c-2429-11e7-9280-74f31d60e331.png)

This isn't the case on the live site, however.

**Comment by nuxsmin** [comment]
I see, so the issue is related on the accounts listing, doesn't it?

**Comment by johnnyhotpants** [comment]
On the demo version, yes, that is the case.  On the live site with my personal account, however, that is not the case, as even when I click through I still don't have the option to edit an account.

**Comment by nuxsmin** [comment]
Which is the version you're running? (displayed on the information tab)

**Comment by johnnyhotpants** [comment]
We are currently running v 2.1 (2.1.5.17041201)
SERVER_VERSION : 5.5.54 
CLIENT_VERSION : 5.1.69

**Comment by nuxsmin** [comment]
Please, to be sure (I know I asked for it before), do you have enabled the "Secondary Group Access" option?

![captura_089](https://cloud.githubusercontent.com/assets/1775774/25140725/89d7bffc-2461-11e7-97ed-845f3d71976c.png)

**Comment by johnnyhotpants** [comment]
No problem, I understand (you have to make sure all variables are checked when testing this type of thing).  The "Secondary Group Access" option is enabled and I'm still having this issue.

**Comment by nuxsmin** [comment]
Could you activate the debug mode on the site configuration tab?. It will show some info about the session data, but the interesting one is that related to `accountAcl`which contains the ACL information for the logged in user.

**Comment by johnnyhotpants** [comment]
Sure thing.  Here is the session data related to accountAcl:

 [accountAcl] => Array
        (
            [265] => SP\Account\AccountAcl Object
                (
                    [Account:protected] => 
                    [accountId:protected] => 265
                    [action:protected] => 1
                    [time:protected] => 1492717909
                    [userInGroups:protected] => 
                    [userInUsers:protected] => 
                    [resultView:protected] => 1
                    [resultEdit:protected] => 1
                    [modified:protected] => 
                    [showView:protected] => 1
                    [showHistory:protected] => 1
                    [showDetails:protected] => 
                    [showPass:protected] => 
                    [showFiles:protected] => 1
                    [showViewPass:protected] => 1
                    [showSave:protected] => 
                    [showEdit:protected] => 1
                    [showEditPass:protected] => 1
                    [showDelete:protected] => 1
                    [showRestore:protected] => 1
                    [showLink:protected] => 1
                    [showCopy:protected] => 1
                    [showPermission:protected] => 
                    [UserData:protected] => 
                    [compiled:protected] => 
                )

**Comment by nuxsmin** [comment]
And is that the account for which the edit button isn't shown?

**Comment by johnnyhotpants** [comment]
I'm not sure how to accurately tell which user this is giving information on since I can only view the data through my admin account.  In another session with my test account, I clicked into a credential and checked the accountAcl info again.  It showed up as this:

[accountAcl] => Array
        (
            [265] => SP\Account\AccountAcl Object
                (
                    [accountId:protected] => 265
                    [action:protected] => 1
                    [time:protected] => 1492778583
                    [userInGroups:protected] => 
                    [userInUsers:protected] => 
                    [resultView:protected] => 1
                    [resultEdit:protected] => 1
                    [modified:protected] => 
                    [showView:protected] => 1
                    [showHistory:protected] => 1
                    [showDetails:protected] => 
                    [showPass:protected] => 
                    [showFiles:protected] => 1
                    [showViewPass:protected] => 1
                    [showSave:protected] => 
                    [showEdit:protected] => 1
                    [showEditPass:protected] => 1
                    [showDelete:protected] => 1
                    [showRestore:protected] => 1
                    [showLink:protected] => 1
                    [showCopy:protected] => 1
                    [showPermission:protected] => 
                    [compiled:protected] => 
                )

Not sure which account this is for but I noticed it was different from the one above.  Let me know if this is useful to you.

**Comment by nuxsmin** [comment]
Umm, unfortunately I forgot to mention that the debug info is only available for the application admins, so normal users won't get it. The displayed info is only related for the current session.

You could get to display this info by commenting out the lines 138 and 140 in https://github.com/nuxsmin/sysPass/blob/master/ajax/ajax_getContent.php#L138 **BUT be aware that some confidential info will be displayed**

**Comment by johnnyhotpants** [comment]
Hello, here is the AccountAcl info for the non-admin testuser after commenting out those lines:

[accountAcl] => Array
        (
            [267] => SP\Account\AccountAcl Object
                (
                    [accountId:protected] => 267
                    [action:protected] => 1
                    [time:protected] => 1493648115
                    [userInGroups:protected] => 1
                    [userInUsers:protected] => 
                    [resultView:protected] => 1
                    [resultEdit:protected] => 
                    [modified:protected] => 
                    [showView:protected] => 1
                    [showHistory:protected] => 1
                    [showDetails:protected] => 
                    [showPass:protected] => 
                    [showFiles:protected] => 1
                    [showViewPass:protected] => 1
                    [showSave:protected] => 
                    [showEdit:protected] => 
                    [showEditPass:protected] => 
                    [showDelete:protected] => 
                    [showRestore:protected] => 
                    [showLink:protected] => 1
                    [showCopy:protected] => 1
                    [showPermission:protected] => 
                    [compiled:protected] => 
                )

Let me know if this gives you more insight and if there is any other info I can send along.

**Comment by nuxsmin** [comment]
Hello, it's ok, let me find out what's going on and I'll be back then.

Thanks!

**Comment by nuxsmin** [comment]
And, did you set the "secondary group edit" option on that account?. I'm asking for that because, the piece of code that grants the edit permission, checks for that (among other checks that weren't passed either):

```
        $this->resultEdit = ($this->UserData->getUserId() === $AccountData->getAccountUserId()
            || $this->UserData->getUserGroupId() === $AccountData->getAccountUserGroupId()
            || ($this->userInUsers && $AccountData->getAccountOtherUserEdit())
            || ($this->userInGroups && $AccountData->getAccountOtherGroupEdit()));
```

So if the `userInGroups` is `true` and the "Secondary groups edit" is set, it should return `true` on the last check, but actually the 'resultEdit`variable is `false` (blank -0-)

**Comment by johnnyhotpants** [comment]
Yes, the "secondary group edit" option is enabled through the admin account but the test user doesn't have access to edit configuration settings, so they wouldn't be able to set it up through that account.  Wouldn't enabling that option through one main admin account enable that setting for all users?

**Comment by nuxsmin** [comment]
Ok, but I meant on the account itself:

![captura_104](https://cloud.githubusercontent.com/assets/1775774/25606325/0ee95c78-2f11-11e7-815c-e55acd029412.png)

**Comment by johnnyhotpants** [comment]
Yes, "enable edit" is set on that account.

**Comment by nuxsmin** [comment]
Hey, luckily I've found the issue and it is a displaying one, because the account's actions are built on running time the options menu wasn't shown because the request option was displayed (some disabled actions like remove, does trigger it). You can try it out by setting either "Display as cards" or "Show hidden actions" on the user's preferences, so it will display all the available options.

BTW, I'm working on a suitable solution ;)

**Comment by johnnyhotpants** [comment]
Hi There, thanks for working on a solution - I just wanted to let you know that "show hidden actions" has been displayed the whole time for that user.  Switching the display option doesn't work, either, so at least on my end it doesn't seem to be just a display issue.  Thanks for your help and hopefully we can figure this one out!

**Comment by nuxsmin** [comment]
Hi, thanks for the feedback!

so..did you try out the latest commit (master branch)?

**Comment by johnnyhotpants** [comment]
Hello,

We pulled the latest commit (#521) last week but this still hasn't been working.  It does, however, function properly when testing out this functionality on the demo site (demo.syspass.org) with the same testing parameters so I'm really not sure what the issue might be.  I did receive this Warning:

<img width="735" alt="cookies1" src="https://cloud.githubusercontent.com/assets/26800226/25953474/8243c646-3631-11e7-827d-4fda3b7df49b.png">

but I have cookies enabled:

<img width="542" alt="cookies2" src="https://cloud.githubusercontent.com/assets/26800226/25953715/29ebccc2-3632-11e7-8cfe-129788e980b3.png">


Just a shot in the dark as I'm still not sure of what the issue might be on our end.  Thanks again for all of your help!

**Comment by nuxsmin** [comment]
Hello,

regarding the warning message, it's related to a security cookie that is needed for session encryption, so the server should be able to send this cookie to the browser (named SYSPASS_SK). This may be caused by a reverse proxy. BTW, the session encryption can be disabled if you don't want to use it, so the cookie checking won't be triggered.

Regards

**Comment by ortizleo** [comment]
Hmm last release here and same problem.... Accounts with "Enable edit" can't be edited by selected users or groups... Have secondary groups enabled.

**Comment by nuxsmin** [comment]
Hi, It has been discussed before, please take a look to #704 issue, it could do the trick.

Regards

**Comment by ortizleo** [comment]
Well, i have "Secondary Groups Access" enabled, my user is in group X and "allow edit" is enable, but still can't edit account with the user (the main group is "Admins")... if i change account "main group" to the same user primary group, works. Its right? 

So maybe "An account can only be modified by either the users or secondary groups if the modification permission, on the account accesses, is enabled" is not right cause Account main group and user group need be same?

**Comment by nuxsmin** [comment]
Ok, I'll check it out, but it was tested since some versions ago, which version are you running?. Did you test it on demo site?

Regards

**Comment by ortizleo** [comment]
Last release and last master...
Will try on demo site.

**Comment by ortizleo** [comment]
hmmm I have a problem... Works on demo site...
Maybe is something with main group? Can't select one on demo..

**Comment by nuxsmin** [comment]
Hmm, in order to change the main group, you need to set the "Accounts Admin" permission on user's account.

I've already tested it and it worked fine (first case). Please notice that you need to set the "Edit" permission on user's profile (I'm sure you already set it)

Regards

**Comment by ortizleo** [comment]
Ok, can you try it this way?
User:
User group: GroupA
User profile: Some profile with ADD, EDIT, VIEW

Account
Main group: Admins
Other groups: GroupA
Enable Edit (group): Checked

Tried this and not work here...

**Comment by nuxsmin** [comment]
What password did you set for demo_a user?

**Comment by ortizleo** [comment]
On demo? inst my user. 
my user is leo and pass 123,

**Comment by nuxsmin** [comment]
Well, I've added your user to "Group A" and then changed the secondary groups for the "123456" account, so the users in "Group A" should have access to this account though secondary group access. All worked fine. Am I missing something?

**Comment by ortizleo** [comment]
hmm main group? Is admins?

**Comment by nuxsmin** [comment]
No, it's set to support.

**Comment by ortizleo** [comment]
Can you test set main group as Admins?

**Comment by mkola-greenliff** [comment]
Hi,

Is there any update regarding this issue? I am having the same problem on 2.1 (2.1.12.17080701).

Many thanks for great sysPass tool!

Mathias

**Comment by ortizleo** [comment]
Yeah, im waiting the test in admins group, have same problem in last release and master...

**Comment by nuxsmin** [comment]
@ortizleo I've just tested it and worked fine. I've used "leo" user and the first account listed.

@mkola-greenliff Did you enable "Secondary Groups Access" on configuration (already discussed on  #704)?:

![captura_018](https://user-images.githubusercontent.com/1775774/29909489-6983c17c-8e26-11e7-9734-b5c9d3e0425c.png)

Regards

**Comment by ortizleo** [comment]
Sorry but rly is not working here.... Tested again with last release 2.1 (2.1.13.17083101).
Edit for secondary groups (main is Admins) and for users not work... 
- I have USER_A, this user is in SUPPORT group and have SUPPORT profile.
- SUPPORT profile can EDIT, ADD, VIEW.
- SUPPORT group is empty (no user added on the group, just select it in user configuration)
- USER_A is in secondary group "SUPPORT - WINDOWS" (on the groups config tab)
- Account_A is in Admins main group and in secondary groups i have  "SUPPORT - WINDOWS"
- Ok, i can see the account with USER_A, but i need edit, só checked EDIT 
- Log in again and can't edit, just can request, copy etc, but can't edit, checked hide actions too, and still not working...

Also, new release haven't Plugins folder.

**Comment by nuxsmin** [comment]
Hmmm, just tested with the same users/groups:

![captura_022](https://user-images.githubusercontent.com/1775774/29957277-e6204946-8eec-11e7-8abb-00f2d63a749f.png)

**Comment by nuxsmin** [comment]
Just to add more context:
![captura_025](https://user-images.githubusercontent.com/1775774/29957370-66af47ba-8eed-11e7-8952-278a6f038990.png)
![captura_024](https://user-images.githubusercontent.com/1775774/29957372-687727ac-8eed-11e7-8a35-92c9a719473d.png)
![captura_023](https://user-images.githubusercontent.com/1775774/29957374-6aafa38c-8eed-11e7-9e0b-102627c85054.png)

**Comment by nuxsmin** [comment]
Really weird...

**Comment by ortizleo** [comment]
Yeah... Maybe is my PHP or mysql version?

sysPass version | 2.1 (2.1.13.17083101)
Database | SERVER_VERSION : 5.5.52-MariaDB CLIENT_VERSION : 5.5.52-MariaDB SERVER_INFO 
PHP | Version: 7.0.20 Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, json, exif, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, shmop, SimpleXML, sockets, sqlite3, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, zip

How i can enable 2FA codes?
Tried disable and enable 2fa again but no option for codes...

**Comment by nuxsmin** [comment]
@ortizleo I'll do some more tests to find out this weird behaviour.

Regarding Authenticator plugin, actually the codes are sent by email when you request them on 2fa login screen, but I'll add a button to send them through preferences screen.

Thanks for the feedback!

**Comment by ortizleo** [comment]
Hi.
Did you find something?

**Comment by ortizleo** [comment]
Hmmm any news @nuxsmin?
Tested in another instalation and got same problem.... 

Also, are you planning something to allow group add? Ex.: Users on GROUP_A can add accounts in GROUP_A, but can't in another groups.
