### ISSUE TITLE
syspass upgrade issue from 2.0 to 2.1.4

### ISSUE THREAD

**Issue by anikarunakaran** [nuxsmin/sysPass#522]
Hi Nuxsmin,

i am trying to upgrade syspass from 2.0 to 2.1.4 by referring below given steps.But it fails an error message "Application in maintenance" and it will be running shortly.

Please find the attached error message and let me know what could be the issue here.

https://doc.syspass.org/en/updating/v2_1.html

==================================================
Process
For the sysPass updating the following steps are needed:

Download the application from https://github.com/nuxsmin/sysPass/releases and uncompress the files

Set the sysPass directory owner and permissions

Copy the files (“config.xml”, “key.pem” y “pubkey.pem”) within the “config” directory from the current version to the new one

Open the application from a web browser

If the application requires a database upgrade:

Perform a database backup

Enter the updating code which could be found in the “config/config.xml” file within the tag “upgradeKey”

Please, enter the sysPass master password.

Please, enter a valid user login
===============================================

**Comment by anikarunakaran** [comment]
[
![syspass_error](https://cloud.githubusercontent.com/assets/4487879/24539908/5b9c08c0-160e-11e7-9524-7cbdadf8c09c.JPG)
](url)

**Comment by nuxsmin** [comment]
Hi @anikarunakaran 
when the upgrade process was triggered, it should display a link that points to the upgrading page. Looking at your version, the link would be like `index.php?a=upgrade&type=app`

Regards

**Comment by anikarunakaran** [comment]
I had to restart httpd after copying files from config directory and now it worked.

Thanks a lot for your support, appreciate it..
