### ISSUE TITLE
Does password copy work on iPad?

### ISSUE THREAD

**Issue by VexedSyd** [nuxsmin/sysPass#524]
Hi guys,

I'm running the latest version of sysPass (2.1.4) and for some reason the copy password function doesn't work at all on iPad. In Safari it says the "Password copied to clipboard" message, but the clipboard is empty.
If I click on "View password" then click on the Copy button, nothing happens.
In Chrome, it shows the same behaviour, although sometimes it says the browser is unsupported.
I have tried simple and complex passwords, no difference.

I have tested on iPad Air 2 with iOS 10.3.

Many thanks.

**Comment by VexedSyd** [comment]
I have just tested on Windows 10 mobile, and it is working as expected.

**Comment by nuxsmin** [comment]
Please see comments on #500

**Comment by VexedSyd** [comment]
@nuxsmin I have tried again with the latest commit, and PHP session encryption disabled.
same issue, the copy to clipboard function is not working on safari, chrome or firefox for iOS.
Is it supposed to work? or the whole function is unsupported on iOS?

Many thanks.

**Comment by nuxsmin** [comment]
@VexedSyd sorry for the late response, I missed to update your issue...

Unfortunately I haven't any iOS device for testing purposes, so your feedback is quite useful. The clipboard function has been developed following the HTML5 standard by using browser wide working functions, so I can't figure out what could be happening.

Thanks for your feedback!

**Comment by VexedSyd** [comment]
@nuxsmin no worries at all, thanks for your great effort here...
I have hooked up an iPad Air 2 to a iMac here and enabled developer tools for Safari. There are no JS errors, but the debugger was complaining about other stuff in the code... 
![screen shot 2017-05-04 at 9 41 28 am](https://cloud.githubusercontent.com/assets/15827925/25686994/ff06bbc4-30b5-11e7-9547-f53eb38c8dc0.png)
![screen shot 2017-05-04 at 9 40 46 am](https://cloud.githubusercontent.com/assets/15827925/25686996/ff090708-30b5-11e7-94ba-461d409d5332.png)
![screen shot 2017-05-04 at 9 40 15 am](https://cloud.githubusercontent.com/assets/15827925/25686995/ff087c8e-30b5-11e7-8da3-97f4643f9542.png)
![screen shot 2017-05-04 at 9 39 51 am](https://cloud.githubusercontent.com/assets/15827925/25686997/ff093b88-30b5-11e7-83e0-a13793ded9b3.png)

I'm not a developer, so I'm not sure if the attached images are of any help.

**Comment by nuxsmin** [comment]
Hi, thanks! I'll check out them.

I've removed some images because they contain some private data (domain)...

**Comment by VexedSyd** [comment]
Thanks, I haven't noticed the domains on those pictures.

**Comment by nuxsmin** [comment]
Hi, someone built this (https://jsfiddle.net/ToJa92/0jwnycwk/) simple script to test it, could you try it out?

Regards

**Comment by nuxsmin** [comment]
Unfortunately, it seems a known limitation https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations

So it would work when showing the password (by coding some tweak), but copy-to-clipboard button (without showing the password), won't work until a new browser API is implemented.

Added (first point) to roadmap #422
