### ISSUE TITLE
Cannot use over internet explorer

### ISSUE THREAD

**Issue by machado666** [nuxsmin/sysPass#525]
IS anyone having issues using on Internet Explorer 11, is working well on Firefox and Chrome , but on IE after i put user and password it shows a white page without error.

**Comment by nuxsmin** [comment]
I'm trying to figure out why it shows a blank page after login and no error is logged neither in the browser console nor webserver.

**Comment by machado666** [comment]
On the Browser console i have: "SCRIPT438: Object doesn't support property or method 'checkStringArgs'"

**Comment by nuxsmin** [comment]
I've seen that function is generated when the JavaScript code is compressed, so I think it could be fixed. I'll be back shortly.

Anyway, this doesn't guarantee that the application will work, because it hasn't been tested on IE, and you may be asking yourself why: because IE hasn't followed some W3C standards so it's quite tough to develop an application for this browser.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
I've done some progress on the demo site, but it stucks while loading some components on the main page...

**Comment by nuxsmin** [comment]
It seems that some element properties aren't implemented:

http://stackoverflow.com/questions/10711767/is-selectedoptions-broken-or#11169204

**Comment by nuxsmin** [comment]
Ummm, some tweaks and solved...

**Comment by machado666** [comment]
thanks for the work in progress, when it's ok tell -me and i will test the new version

**Comment by nuxsmin** [comment]
Please, give a try to the latest release and let me know if there is any issue.

**Comment by machado666** [comment]
Just updated, it already opens in Internet Explorer, many thanks for your work.
The search on Internet explorer won't assume the enter, an just works if i change customer or development .

**Comment by nuxsmin** [comment]
Please let me know if the latest code from the master branch is working fine (https://github.com/nuxsmin/sysPass/archive/master.zip).

You can also test it on the demo site: https://demo.syspass.org

**Comment by machado666** [comment]
Hi there Nuxsmin, already tried on your demo site and it look fine. Many Thanks for your great work.

**Comment by nuxsmin** [comment]
Thanks for the feedback!. The new release will be out shortly
