### ISSUE TITLE
Backup and Restore steps.

### ISSUE THREAD

**Issue by anikarunakaran** [nuxsmin/sysPass#527]
Hi,
Please provide some documentation of backing up syspass and restoring the same incase of any issue with primary installation.
Is there any plan to automate syspass backup mechanism, so it will be helpful for users to auto backup syspass on daily basis.

thanks,
Anil.

**Comment by nuxsmin** [comment]
Hi,
sure, the current documentation is under development and some howtos will be added soon.
In the meantime you could follow the steps on #466 issue to get it.

Regarding the "auto-backup", it could be performed through the sysPass API from a cron job or by using external tools like mysqldump. Here you have a quite simple API client: https://gist.github.com/nuxsmin/62338b33178544894cd7237c7fe170bd

Regards
