### ISSUE TITLE
What about Brute-force attack?

### ISSUE THREAD

**Issue by Edtigoza** [nuxsmin/sysPass#529]
What about Brute-force attack the main user password in login page?
I really appreciate this software, it is useful, but I have some doubts, about security in the login page
I tried several times filed login, and there was nothing to stop me, which made me think, " a robot could try with a big dictionary generated to decript my password"
I investigate on google and there are several tools that hackers use to decript passwords
http://tools.kali.org/web-applications/wfuzz
http://tools.kali.org/tools-listing
[kali linux,](https://www.kali.org/) Most Advanced Penetration Testing Distribution, with lots of tools. 

https://null-byte.wonderhowto.com/how-to/hack-like-pro-crack-online-web-form-passwords-with-thc-hydra-burp-suite-0160643/

I usually use ReCaptcha from [google](https://www.google.com/recaptcha/intro/invisible.html ) or [phprecaptcha](http://www.phpcaptcha.org/) and [visualcapcha](https://visualcaptcha.net/), it  is great from a client side point of view, but it's not perfect.

Thanks for the syspass, it is usefull

**Comment by nuxsmin** [comment]
Hello,

You're right, brute force attacks are possible on every system and could be mitigated by several mechanisms like captcha and other tools.

sysPass implements a tracking system that after 5 attempts within 10 minutes will stop checking login and every request will be delayed for 0.3 * number of attempts seconds, so it will make it harder.

The code is in https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Controller/LoginController.class.php

BTW, it could be a nice to use recaptcha in addition

Kind regards and thanks for the feedback!

**Comment by Edtigoza** [comment]
Thank you, I am relieved to know,
