### ISSUE TITLE
What's password for sysPass Admin user for first time  installer steps ?

### ISSUE THREAD

**Issue by NickWoo33** [nuxsmin/sysPass#530]
I gif clone sysPass, then follow 

https://IP_OR_SERVER_NAME/syspass/index.php

to open the site, it asks me sysPass Admin user and password ?

But no one/doc tells me what's the default password, I can't start the install.

Is anyone know the default password ?

Thanks.

**Comment by NickWoo33** [comment]
BTW, I try syspass-2.1.4.17032801.tar too, but same question about the password...

**Comment by nuxsmin** [comment]
Ummm, there isn't any default user/password, you only need to provide your own settings and once finished it'll setup a fully working sysPass instance.

Did you follow the steps on https://doc.syspass.org?

**Comment by NickWoo33** [comment]
Yes, I did, I don't know why.

so do you mean user admin need to be setup just like master password ? 

but there's no repeat password for admin, and master admin did have repeat password.

**Comment by NickWoo33** [comment]
the installer setup like this:


 
sysPass administrator's login 

admin

Password
 
Master Password 

Master Password (repeat)

**Comment by NickWoo33** [comment]
The first time i open the installer, "admin" is put in "sysPass admin user"

**Comment by nuxsmin** [comment]
The admin and master password should be different, because the purpose of each one is quite different. The master password will be the key used for encrypting data and the admin user is used for logging into the application.

**Comment by NickWoo33** [comment]
i know, but what's the admin's password, i can click the installer...

**Comment by NickWoo33** [comment]
<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input id="adminlogin" name="adminlogin" type="text" required
                           class="mdl-textfield__input mdl-color-text--indigo-400"
                           value="admin" maxlength="80" autocomplete="off" tabindex="0"
                           autofocus>
                    <label class="mdl-textfield__label"
                           for="adminlogin">sysPass admin user</label>
                </div>

                <div id="help-login"
                     class="icon material-icons mdl-color-text--indigo-A100">
                    help_outline                </div>
                <div class="mdl-tooltip" for="help-login">
                    sysPass administrator's login                </div>

                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input id="adminpass" name="adminpass" type="password" required
                           class="mdl-textfield__input mdl-color-text--indigo-400 passwordfield__input"
                           value="" maxlength="255" autocomplete="off">
                    <label class="mdl-textfield__label"
                           for="adminlogin">Password</label>
                </div>

**Comment by NickWoo33** [comment]
can i reset the pssword for admin by command or ?

**Comment by nuxsmin** [comment]
That password will be used to log in with admin username.

You can setup the admin username whichever you want and it will be the first user created in sysPass.

Then when the installation is finished, you will be able to log into sysPass with these credentials like on demo.syspass.org

**Comment by nuxsmin** [comment]
No, it needs to be reset through the app, because some tasks (like hashing) are done for security reasons.

**Comment by NickWoo33** [comment]
Just need to input a complicated password once, then it works :)

**Comment by nuxsmin** [comment]
Great!!
