### ISSUE TITLE
Keepass import and backup download error

### ISSUE THREAD

**Issue by bdiv** [nuxsmin/sysPass#534]
Hello!

I have syspass 2.1 running in a docker container in my environment. The container was created using your docker-compose.yml.
First of all: great work! Installation and playing around with it was really easy and satisfying!

After trying out some things I ran into the following problems:

### 1. I couldn't import data from my keepass installation (1.31):
Importing an xml-file resulted in the message `XML file not supported Help : Unable to detect the application the data was exported from`
The xml generated from Keepass had the form of a list of `<pwentry>` elements. So indeed, the application data is missing, but I wasn't able to get keepass to export those as well. 

### 2. Backup in general works but the links are broken:
I tried out the backup functionality and the files were created successfully. I tried to download them using the links, but the download failed every time using chrome. Firefox gave me a file-not-found error. After reloading I received a 403-Forbidden. I wasn't able to find a .htaccess-file or something similar, which I thought might be the cause. 
Using `docker exec` I verified that the files were created, I simply don't have access using the web-UI.

Thank you for your help and time!

**Comment by kwetiaw** [comment]
I can confirm that I am having the same issue. I am using the docker image using docker compose as per your guide.

> 2. Backup in general works but the links are broken:

I tried out the backup functionality and the files were created successfully. I tried to download them using the links, but the download failed every time using chrome. Firefox gave me a file-not-found error. After reloading I received a 403-Forbidden. I wasn't able to find a .htaccess-file or something similar, which I thought might be the cause.
Using docker exec I verified that the files were created, I simply don't have access using the web-UI.

Thank you for your help and time!

**Comment by nuxsmin** [comment]
Hello,

the files downloading is disabled by default in the docker image:

```
	<Directory ~ "/var/www/html/sysPass/(config|backup)">
		Require all denied
	</Directory>
```

**Comment by nuxsmin** [comment]
Hello (again), the KeePass XML import will only run with 2.X version:

![captura_082](https://cloud.githubusercontent.com/assets/1775774/24956334/79bb49e2-1f87-11e7-84cd-0b90acee462b.png)

**Comment by nuxsmin** [comment]
@bdiv It's rewarding that you found sysPass useful and easy to use :)

Thanks for the feedback!

**Comment by bdiv** [comment]
Thank you for the quick help! I'm still experiencing some issue while trying to import keepass 2.x files, but I'll look into it for a bit and open a separate issue if neccessary.

**Comment by Famku** [comment]
Hi,

how can I grant permissions to allow download backup files?
