### ISSUE TITLE
syspass 2.1.5 ldap group objects not updating

### ISSUE THREAD

**Issue by chenrbs** [nuxsmin/sysPass#537]
Hi,

In release syspass-2.1.5.17041201, ldap group is not working.

Thanks,

**Comment by nuxsmin** [comment]
Hi, 

please let me know what is the exact issue. Did you mean that the LDAP group filtering isn't working?, What are the tests that you performed?

Kind regards.

**Comment by chenrbs** [comment]
When I click the Check button it only finds 2 objects in the group but there are more than 2, so new users added to Active Directory group are not being added to syspass.

LDAP connection OK
Objects found : 2

**Comment by nuxsmin** [comment]
Hi, the LDAP objects are searched in the search base and should be a member of the group, if these conditions aren't satisfied, the users won't be listed.

**Comment by chenrbs** [comment]
I am aware of it, the bese is set and there are more users in the group but syspass do not find all members in the group.

**Comment by nuxsmin** [comment]
Ok, are you using a plain group name or DN syntax instead?, Are you using ADS?

**Comment by chenrbs** [comment]
I am using ADS with the full DN syntax but also tried with only the group name but got the same results.

**Comment by nuxsmin** [comment]
Did you add the users to the same search base?

**Comment by chenrbs** [comment]
Yes all users are under the same base in sub OUs in Active Directory, for some reason certain users are not being found despite them being added to the group. 

Error while searching objects in base DN
LDAP ERROR : Success (0)
LDAP FILTER : (&(|(memberOf=CN=syspass_dev,OU=Security Groups,DC=BASE_OU_STRIPPED_FOR_PRIVACY)(groupMembership=CN=syspass_dev,OU=Security
Groups,DC=BASE_OU_STRIPPED_FOR_PRIVACY)(memberof:1.2.840.113556.1.4.1941:=CN=syspass_dev,OU=Security
Groups,DC=BASE_OU_STRIPPED_FOR_PRIVACY)(objectClass=person)(objectClass=simpleSecurityObject)))

**Comment by nuxsmin** [comment]
Ok, seems fine. Could you perform an LDAP search by setting the filter logged?

**Comment by chenrbs** [comment]
Not sure what you mean

**Comment by nuxsmin** [comment]
Ummm, you can perform an LDAP search with an LDAP client like ldp (Windows) or ldapsearch on Linux, so you can set the filter that was written down in the sysPass event log and then get if there is any result​.

**Comment by chenrbs** [comment]
Hmm idk but there are users in the group and are not being found in syspass :( I even tried syspass 1.2 with same results.

**Comment by chenrbs** [comment]
I used a domain admin account and it did find all the objects, it's weird that with a bind account it only finds domain admins members objects but not all users. Can we make it so the bind account does not need to be a domain admin?

Thank you!

**Comment by nuxsmin** [comment]
Sure, the bind account doesn't need to be a domain admin at all, indeed it's a security risk, so almost any LDAP setup will use a non-privileged account. sysPass doesn't need any AD special rights, just a normal user.

You could test it with the FreeIPA service (already setup on the demo site).

**Comment by chenrbs** [comment]
Seems like it does need a domain admin account for active directory, otherwise it will not find any objects besides users who are part of the domain admins group, I tested it on versions 1.2 and 2.1.6.

**Comment by chenrbs** [comment]
Just tested it on 2.1.7 and same results, non admin object is only found if the bind user is an administrator.

**Comment by finalbeta** [comment]
chenrbs, this might be an active directory security issue. You might have to change users rights.
Please check: 
http://support.exclaimer.com/topics/850-checking-and-setting-read-member-of-permission-for-network-service-account/
And https://serverfault.com/questions/167371/what-permissions-are-required-for-enumerating-users-groups-in-active-directory

**Comment by nuxsmin** [comment]
@chenrbs really weird, because I've done some ADS integration without any issue, so it could be related to a security policy as @finalbeta has pointed.

**Comment by chenrbs** [comment]
These links are very old and applies to old 2003 and 2008 windows servers, we have 2012 servers. Also we have many other web applications and use the same non admin user to bind to ldap and it can read group membership just fine.

**Comment by nuxsmin** [comment]
Could you set sysPass debug mode and check out the webserver log after performing an LDAP check?. It will log a lot of messages about LDAP operations, so it could provide some useful info about what could be happening.

**Comment by chenrbs** [comment]
This is what I am getting
[Tue Apr 25 15:44:58.616242 2017] [:error] [pid 32554] [client 172.24.95.65:2084] PHP Warning:  date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/syspass/inc/SP/Core/Init.class.php on line 108, referer: https://syspass.*************/index.php

**Comment by chenrbs** [comment]
No idea?

**Comment by nuxsmin** [comment]
Ummm, sorry I've been busy last days.

Regarding the debug mode, you need to perform an LDAP check when it's active, so many messages will be logged to the webserver log. Be aware that those messages could contain any sensitive data.

Regards
