### ISSUE TITLE
Unable to write /config although permissions are set

### ISSUE THREAD

**Issue by gregorpl8** [nuxsmin/sysPass#542]
When trying to install sysPass I get the error message

`The "/config" directory permissions are wrong

Current: 777 - Needed: 750`

I always do 777 for install processes but ok, let's change it to 750.

Having done so, I get this:

`Unable to write into the "/config" directory`

The whole directory belongs to www-data, I've tried giving /config permissions 750 and the contents 777, but I also get the same results.

The log says:

`2017-04-18 16:00:57 - initError
2017-04-18 16:00:57 - Unable to write into the "/config" directory
2017-04-18 16:00:57 -
`
So there are no more details to be found in here.

Any ideas? Running Ubuntu 14.04 with PHP 5.6.30. Thanks in advance!

**Comment by nuxsmin** [comment]
Hello, could you try out by setting the same group as the owner?. I've noticed some issues like that.

**Comment by gregorpl8** [comment]
Hi nuxsmin!

Thanks for the reply, done that. www-data:www-data on all files and directories.

**Comment by nuxsmin** [comment]
Do you mean that, although setting the `750`permissions, it remains displaying the same error?. Is SELinux enabled?
