### ISSUE TITLE
LDAP Users import problem

### ISSUE THREAD

**Issue by jdanielcano** [nuxsmin/sysPass#544]
Hello there,

First of all, thanks for the great job you are doing with this tool, it is great and it has many and useful features.
I am trying to install the sysPass in the following way:
- Docker containers running in a Debian Jessie 8.7.
- SysPass application running in a Docker container using the SysPass version 2.1.2.17031401.
- The database MySQL 5.5. I use the Hosting option cause our database server is in a different machine, so we connect with a dedicated user into the database.

The problem:
- Every time we try to import the users from LDAP I got this output: 
```
LDAP users import finished
Imported users : 0/200
Errors : 0 
```

I checked the logs and there is no errors, even in the database logs there is anything weird or error. When I try to list the users in the LDAP configuration, I can retrieve all the users from the LDAP and I can "navigate" or list all of them, but the import is not working.

I am doing something wrong?

Thanks a lot in advance.
Cheers,
Daniel.

**Comment by nuxsmin** [comment]
Hello Daniel,

I'm very glad that you found it useful ;)

Regarding your issue, it could be related to the LDAP `Login Attribute` which is used to get the users login when performing the import, so if this attribute is not set in the LDAP user data, the user won't be imported.

Cheers!

**Comment by jdanielcano** [comment]
Hello!

Thanks for the quick answer! 

Actually the login attribute exist, in our case the UID, and I am selecting that option during the import process...

Thanks again!
Cheers,
Daniel

**Comment by nuxsmin** [comment]
I forgot to mention that the **username** and **login** shouldn't be blank so if the user login is got, the username could be the cause.

Cheers

**Comment by nuxsmin** [comment]
Sorry...and the username is got either from `displayname` or `fullname`

**Comment by jdanielcano** [comment]
Ok, then that is the cause, for the user name we use the `CN` and not the `displayname` or `fullname`.
Probably this could be another feature as it is now for the login? I mean, to be able to chose from which attribute the **username** could be taken?

Thanks a lot!
Cheers,
Daniel

**Comment by jdanielcano** [comment]
Hi again,

I add the attribute `cn` in the code and it is working, if you agree, I will make a pull request to add this attribute in the 2 files needed to add the attribute as a possibility to be used as username.

Thanks again.
Cheers,
Daniel

**Comment by nuxsmin** [comment]
Nice, please send me the pull request.

Thanks!

Cheers

**Comment by nuxsmin** [comment]
Hi @jdanielcano 

I've just implemented the code that allows to select the name attribute for importing from LDAP :)

Cheers

**Comment by jdanielcano** [comment]
Thanks a lot!!

I didn't have time a work, but this kind of things make your application
even better!

Thanks again!
Cheers
