### ISSUE TITLE
LDAP Improvements

### ISSUE THREAD

**Issue by Kifran16** [nuxsmin/sysPass#546]
Hi,

First of all, congratulations for your great job. This web app is very powerfull and helpfull :-)

I just would like to share with you some improvements regarding the integrated LDAP feature:

1- Give possiblity to auto schedule every day/weeks/... the import users from LDAP task: at this time if admins add users into their LDAP directory server, admins must go then to the syspass application and execute the import LDAP user task.

2- Give possibility to assign syspass groups and profils based on user's group member in LDAP.: at this time, all LDAP users imported are assigned to a default group & profil. If admins want to manage differents groups & profils for ldap users, admins must edit every users and assign manually a new group & profil.

I hope that it will contribuate to improv your application and make admins happy :-)

Regards

**Comment by nuxsmin** [comment]
@Kifran16 It's nice to hear that sysPass is useful, very glad for that :)

Regarding your points:

1. This feature is currently achieved because if the user doesn't exist on sysPass, it will be automatically created and the the default group and profile will be set. The import feature is to give some kind of ease to pre-set the users data before their first login.
2. This would be an useful feature. I'll add it to the feature list #422 

Kind regards

**Comment by Kifran16** [comment]
Hi nuxmin,

Thank you for your feedback.

I look forward to test the next 2.2 release :-)

Regards

**Comment by tumtumdev** [comment]
Same as: https://github.com/nuxsmin/sysPass/issues/339 ?

**Comment by nuxsmin** [comment]
@tumtumdev sure!

**Comment by corselop** [comment]
@nuxsmin , there is a case regarding scheduled import from LDAP:
if user lost or compromised his password and then changed it in LDAP, scheduled import can update user password.

**Comment by nuxsmin** [comment]
@corselop, regarding your point, be aware that sysPass will ever check (if LDAP is enabled) the user's  status and pass in LDAP, so either a compromised or lost password won't grant any access if you have changed it or the user's status (disabled) in LDAP.

Only if LDAP is not available, it will check its own database, so in this case the credentials will be checked against the database.

Thanks for the feedback!

**Comment by Kifran16** [comment]
Hi Nuxsmin,


Do you have an idea about when this feature (plan in release 2.2) will be available ?


Best regards


________________________________
De : RubénD <notifications@github.com>
Envoyé : vendredi 16 juin 2017 10:30
À : nuxsmin/sysPass
Cc : Kifran16; Mention
Objet : Re: [nuxsmin/sysPass] LDAP Improvements (#546)


@corselop<https://github.com/corselop>, regarding your point, be aware that sysPass will ever check (if LDAP is enabled) the user's status and pass in LDAP, so either a compromised or lost password won't grant any access if you have changed it or the user's status (disabled) in LDAP.

Only if LDAP is not available, it will check its own database, so in this case the credentials will be checked against the database.

Thanks for the feedback!

**Comment by corselop** [comment]
@nuxsmin , thank you for your answer. It seems I overlooked this point and need to dig deeper.

**Comment by nuxsmin** [comment]
@Kifran16 sysPass 2.2 version will be available by the end of september https://github.com/nuxsmin/sysPass/milestones

**Comment by Kifran16** [comment]
Thank you for the feedback.

Regards

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nuxsmin** [comment]
Added to roadmap #422
