### ISSUE TITLE
French translation for LDAP configuration

### ISSUE THREAD

**Issue by ejouvin** [nuxsmin/sysPass#549]
Hello.

In last version, there is a missing translation for the new LDAP configuration.

![image](https://cloud.githubusercontent.com/assets/8817923/25304986/f7920cbe-2772-11e7-9091-52fe415ad2e2.png)

Is there any project where we could push translations ?

Thanks for the job.

**Comment by nuxsmin** [comment]
Hello,

You can help to translate on https://poeditor.com/join/project/fmlsBuugyv

Thanks for your contribution!
