### ISSUE TITLE
Single sign on: Basic authorization

### ISSUE THREAD

**Issue by finalbeta** [nuxsmin/sysPass#550]
Hello, I'm wondering is sysPass supports some method of "single sign on" like basic auth? 

The setup would be: 
- User authenticates on reverse proxy. Reverse proxy validates LDAP credentials and sends them to backend server using basic auth. 
- sysPass (being one off the backend servers) has ldap users. sysPass receives the basic auth and uses it to validate/authenticate the user.

**Comment by finalbeta** [comment]
I think I need to appologise since this is already included: https://doc.syspass.org/en/application/authorization.html

**Comment by nuxsmin** [comment]
Ummm, I've understood that you want an SSO through auth basic and it would be possible since the username and password are sent in the headers, but in some circumstances sysPass will require to get some more data like the master key.

This feature could be easily implemented, but be aware that it isn't​ SSO and the password won't be encrypted unless you use SSL.

Kind regards

**Comment by finalbeta** [comment]
Thank you for your comment, I'm however not entirely certain what you mean with "This feature could be easily implemented". 
In what way is this not working at the moment? (Or do you simply mean that the first time a user logs on he will be required to enter the master key? )

PS: I'm aware about the security implications of using basic authorization and the requirement to use ssl to secure the transfer.

**Comment by nuxsmin** [comment]
The current behaviour does only authorization instead of authentication, so if the user's name doesn't match login won't succeed.

By SSO i meant that it would trigger the login process automatically so the user wouldn't need to enter the credentials again.

**Comment by finalbeta** [comment]
I see. so you mean that the user has the log in to the system first, and the "basic auth" header is then used to validate the session? 

So the missing steps would be changing the login proccess to attempt to use the "basic auth" to login the user if the basic auth is available? (And perhaps show a page to request the master key if it is unavailable)

Is this a feature request you would be willing to implement?

**Comment by nuxsmin** [comment]
That's right and this could be implemented in future releases.

**Comment by finalbeta** [comment]
Thank you for considering this for future implentation.

**Comment by nuxsmin** [comment]
Added to roadmap #422
