### ISSUE TITLE
Error 500 on php5.6/7

### ISSUE THREAD

**Issue by gitzler** [nuxsmin/sysPass#551]
Deployed sysPass two months ago as an evaluation with no problems.  Server was Ubuntu 16.04 with php7.  Decided to go to prod today on fresh VM...but I am getting an HTTP error 500.  This happens with both php5.6 and 7.0.  Apache error log points to this below.  Any help is greatly appreciated.

```
[Sun Apr 23 16:01:41.968928 2017] [:error] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/inc/SP/Core/SessionUtil.class.php on line 113

[Sun Apr 23 16:05:54.542000 2017] [:error] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in /var/www/html/inc/BaseFunctions.php:67\nStack trace:\n#0 /var/www/html/inc/SP/Core/Init.class.php(509): __('Los permisos de...')\n#1 /var/www/html/inc/SP/Core/Init.class.php(434): SP\\Core\\Init::checkConfigDir()\n#2 /var/www/html/inc/SP/Core/Init.class.php(134): SP\\Core\\Init::checkConfig()\n#3 /var/www/html/inc/Base.php(68): SP\\Core\\Init::start()\n#4 /var/www/html/index.php(31): require('/var/www/html/i...')\n#5 {main}\n  thrown in /var/www/html/inc/BaseFunctions.php on line 67
```

**Comment by nuxsmin** [comment]
Hello, this issue could be related to #381

The lastest release implements some functions to manage multi byte strings so an additional module will be needed. This module is installed by default in some distributions.

**Comment by gitzler** [comment]
Yes, that was it.  Perfect.  Thanks for the quick response.

**Comment by nuxsmin** [comment]
You're welcome.

Thanks for the feedback!
