### ISSUE TITLE
There was an error  Internal Server Errorerror

### ISSUE THREAD

**Issue by zsolnayp** [nuxsmin/sysPass#552]
Hi!

 Im trying to install sysp on centos 7 with php 5.6.30.
I filled out the brckets with passwords, for master and etc.
After I pressed the install button the folowing mesages appears in red:
"There was an error Internal Server Errorerror"
Where do I find logs or what is went wrong?

Sinc Pol

**Comment by nuxsmin** [comment]
Hi, you can check out the syspass.log in the config directory.

It seems that a missing module could be the cause.

**Comment by zsolnayp** [comment]
Thx to reply!

 As is discovered the "yum install php-xml" was missed.
Im not sure that this package is listed in the install description
of the CentOS installanion guide.

BTW it may required in the Deibian instal too.


THX!

PS: It is now working like  a charm.

**Comment by nuxsmin** [comment]
Great!! I'll check out the doc and add this module if it isn't listed.

Thanks for the feedback!
