### ISSUE TITLE
Just installed. Can't login

### ISSUE THREAD

**Issue by James137137** [nuxsmin/sysPass#554]
I get the following login page. 

![image](https://cloud.githubusercontent.com/assets/2226031/25411700/4ccf370e-2a72-11e7-97fe-ae090b43140f.png)

I put in information I used from installation and I get a wrong login error

![image](https://cloud.githubusercontent.com/assets/2226031/25411737/812b844e-2a72-11e7-99f2-28aff6feed52.png)

any ideas? (also the graphics looks a bit off)

**Comment by nuxsmin** [comment]
Please, make sure the permissions are correctly set, because it seems some style files couldn't be loaded. Is there any error in `syspass.log`file (within `config`dir)?

**Comment by James137137** [comment]
Yeah, if I run chmod -R 777 syspass/

 I get: 

![image](https://cloud.githubusercontent.com/assets/2226031/25423882/592e0b86-2aba-11e7-8aa5-48da7fbf56bc.png)

and it goes back if I go chmod -R 750 syspass/config/ or chmod 750 syspass/config/

![image](https://cloud.githubusercontent.com/assets/2226031/25424020/e83eb3ca-2aba-11e7-9055-90be2c1edb5e.png)

and I did 
chown -R www-data:www-data syspass/

**Comment by nuxsmin** [comment]
Is there any error in the webserver log?

**Comment by James137137** [comment]
[26/Apr/2017:19:24:46 +0000] "GET /syspass/ HTTP/1.1" 200 1785 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
 [26/Apr/2017:19:24:46 +0000] "GET /syspass/ajax/ajax_getEnvironment.php?isAjax=1&_=1493234682055 HTTP/1.1" 200 2273 "https://www.lolnet.co.nz/syspass/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
1

those are the only type of lines logged

**Comment by nuxsmin** [comment]
Ok, so what about the error.log file?

**Comment by James137137** [comment]
yeah I checked nginx error log. Nothing mentioning syspass

**Comment by nuxsmin** [comment]
Could you check out if these files are there?: https://github.com/nuxsmin/sysPass/tree/master/inc/themes/material-blue/css

A more advanced check would be to launch the browser console (by hitting F12) and then check out if the CSS and JS files have been loaded fine:

![captura_102](https://cloud.githubusercontent.com/assets/1775774/25480013/41905280-2b47-11e7-8203-8a26ea3ed94b.png)

**Comment by James137137** [comment]
It seem like everything is there.  though I'm not sure if it's all loading. (I've added some screenshots)
![image](https://cloud.githubusercontent.com/assets/2226031/25500864/b9ba1c3a-2be4-11e7-901c-d7bdd25c9bf3.png)


![image](https://cloud.githubusercontent.com/assets/2226031/25500836/9c03c4b6-2be4-11e7-81e3-b0b5af5d1ab5.png)


![image](https://cloud.githubusercontent.com/assets/2226031/25500813/8b9e3980-2be4-11e7-811b-48d6fe0f1e0d.png)

**Comment by nuxsmin** [comment]
It seems that your sysPass instance is hosted behind a reverse proxy or some kind of CDN is catching the requests, so any of them could be filtered out or skipped some content.

sysPass does not rely on Google Analytics or some other stuff like "rocket.js" or "cloudfare.min.js", the only requests that you should see are like in the capture from above, you can check it out by accessing to the demo site.

**Comment by James137137** [comment]
yeah it seems to be cloudflare is causing the problem
