### ISSUE TITLE
Upgrading from 2.0 to 2.1.7

### ISSUE THREAD

**Issue by newkarn** [nuxsmin/sysPass#555]
Hi!

First of all. Thanks for Syspass, it's great!

I am following the documentation, setting the right permissons, copying files from config to the new installation. But when i point my browser to the site it looks like the wizard wants to do a clean install. 

![syspass](https://cloud.githubusercontent.com/assets/28089286/25473944/bc47f246-2b31-11e7-83af-ccfce412adb3.PNG)

And I noticed I have no upgrade key in config.xml. Should that always be there?

Any advice on how to proceed?

Thanks

**Comment by nuxsmin** [comment]
Hi!

It's nice that you found sysPass useful :)

Regarding the issue, it's weird because it should have pointed to the upgrade page instead. Please look for the `installed` tag in the `config.xml`file and then set its value to 1. After that, you need to reload the browser page.

Regards

**Comment by newkarn** [comment]
Hi!

I checked and it is set to   <installed>1</installed>
I do have another config.xml that is four days older that contains the upgradekey. Would it make any difference to use that?

Best regards

**Comment by nuxsmin** [comment]
Hi, by replacing the file by an old one shouldn't make any difference, but you could try it out. Are you pointing to the same database?

Regards

**Comment by newkarn** [comment]
Yep, the database and user matches. I tried with the other config but it is the same thing.

Thanks

**Comment by nuxsmin** [comment]
Is there any message in the `syspass.log` file? (within the `config`directory)

**Comment by newkarn** [comment]
Just this line: 2017-04-27 09:59:13 - Setup log file: /var/www/syspass/inc/../config/syspass.log
Is there any way I can force an upgrade through the browser?

Or maybe even in the shell?

I have backups so I can experiment :)

Thanks

**Comment by nuxsmin** [comment]
Does the URL point to `index.php`?

Unfortunately, the only way to perform the upgrade is through the UI, because it may require some information and display some notices that would be quite hard to do through the console.

The really weird thing is that it forces to do a clean install though the `installed`tag is set to `1`. Could you remove the PHP's browser cookie? (this will force to read the configuration again -F5 should work too-)

**Comment by newkarn** [comment]
Yep, index.php is the only .php in the folder. And the page looks the same when specifying index.php too.
I tried F5 and also changing to a browser i never use for it.

Pretty weird indeed =)

**Comment by newkarn** [comment]
Well, there is api.php in the folder too. Forgot about that one.

**Comment by nuxsmin** [comment]
Is the `upgradeKey` tag still set in the config file?

**Comment by nuxsmin** [comment]
Which build number are you running? (on the information tab). Please tell me the full version number.

**Comment by nuxsmin** [comment]
Could you also tel me the DB version number?. You can get it by issuing this command in the mysql console:

```
SELECT config_value FROM config WHERE config_parameter = 'version';
```

**Comment by newkarn** [comment]
Hi! The upgradekey was set when i tried the older config. Can I copy that to the newer one?
I am running build 2.0.0.17022001 with mysql version 5.5.54-0+deb8u1.

I got this when running the query: 
mysql> SELECT config_value FROM config WHERE config_parameter = 'version';
+--------------+
| config_value |
+--------------+
| 20017022001  |
+--------------+

Thanks

**Comment by nuxsmin** [comment]
Hi!, the `upgradekey` can be replaced by the old one and you also need to set the `maintenance` tag to 1.

BTW, I've just created a gist to check if an upgrade is required. You can get it from https://gist.github.com/nuxsmin/c4b7e30a3621d034ce7ff1466243818f and the place it in the sysPass root directory. After that, point your browser URL to http://server/syspass/check_upgrade.php

**Comment by newkarn** [comment]
Hi!

I'm getting an http error 500 when browsing to it. 
And this in the apache error.log:
https://pastebin.com/hmhdcaEF

Thanks

**Comment by nuxsmin** [comment]
Sorry, I forgot to add some lines. I've just updated the gist, please, download it again.

Thanks.

**Comment by newkarn** [comment]
No problem =)
I'm not getting as much errors now. But still http error 500 and this line:

[Fri Apr 28 10:39:15.925656 2017] [:error] [pid 18602] [client 172.0.0.17:63869] PHP Fatal error:  Class 'phpseclib\\Crypt\\RSA' not found in /var/www/syspass/inc/SP/Core/CryptPKI.class.php on line 78
[Fri Apr 28 10:41:32.323612 2017] [:error] [pid 18664] [client 172.0.0.17:63874] PHP Warning:  file_put_contents(./config/config.xml): failed to open stream: Permission denied in /var/www/syspass/inc/SP/Storage/XmlHandler.class.php on line 172

Thanks for the help!

**Comment by nuxsmin** [comment]
Umm, please take a look to the last error, the `config.xml` file couldn't be written so if this script fails the app will fail too, so could you check out the file permissions?

**Comment by newkarn** [comment]
Ahh, damn.
You are right. I thought the first thing I did was fix the permissions. Sorry for wasting your time with this. (but thanks for check_upgrade.php!)

Everything works. Currently running the latest version!

Thanks again.

**Comment by nuxsmin** [comment]
That sounds great!! No worries ;) 

BTW, I'll add some kind of check to avoid this behavior.

Regards
