### ISSUE TITLE
Change password request

### ISSUE THREAD

**Issue by cleitma** [nuxsmin/sysPass#558]
Buenos días, ante todo enhorabuena por la aplicación, nos está encantando en nuestro entorno.

Tengo una duda respecto a como modificar la dirección a la que llegan los correos cuando se hace una petición de cambio de contraseña en una de las entradas que hay añadidas ya que solamente están llegando a una dirección y no encuentro forma de cambiarla

Gracias de antemano,  Cristian

**Comment by nuxsmin** [comment]
Buenas Cristian,

me alegra saber que os resulta útil la aplicación :)

Con respecto a las solicitudes de cambio, sólo llegan al propietario de la cuenta y al último usuario que la modificó, si disponen de correo. También se genera una notificación dentro de la aplicación.

Saludos!, Rubén
