### ISSUE TITLE
Apache - clients certifikate

### ISSUE THREAD

**Issue by ajtak-angelus** [nuxsmin/sysPass#559]
Hello,I would like to have sysPass protected on Apache (Debian 9) using client's certificate. I can get on the login page but I can not log in (without clien's certificate the login in is ok). 
Here I attach the apache2 configuration:
```
<Directory /srv/apache2/web/https/syspass>
                AllowOverride None
                Order allow,deny
                Allow from all
                SSLVerifyClient require
                SSLVerifyDepth 1
                SSLOptions           +FakeBasicAuth
                SSLRequireSSL
                AuthName             "SYSPASS"
                AuthType             Basic
                AuthUserFile         /etc/apache2/auth/syspass
                require              valid-user
 </Directory>
```

Thanks you for your advices.

**Comment by nuxsmin** [comment]
Hello, sysPass implements auth basic as an authorization mechanism so the certificate user's name should match with the sysPass user's login: https://doc.syspass.org/en/application/authorization.html

Currently there is no way to know which username format is using every external auth, so sysPass relies on the PHP internal variables such as `PHP_AUTH_USER` or `REMOTE_USER`. It checks them against the user's login.

In 2.2 release there will be an SSO option and an alternative user's login to match with the external auth username.

I hope it helps ;)
