### ISSUE TITLE
Upgrade to 2.1.8

### ISSUE THREAD

**Issue by madcoda9000** [nuxsmin/sysPass#560]
Hello,

i am tryin to upgrade to v2.1.8 but it will not work :-(

I did the following:

1. make a new webfolder (with 2.1.8)
2. make a new database and copied all data from old database (syspass21) into the new one (syspass21817)
3. set folder permissions to config and backup of the new webfolder
4. copy all files from old config dir to the new config dir
5. change the db name in config.xml to the new one
6. open syspass in the browser

But i everytime i try this it prompted me with a new installation and not with an update!? Is that correct?

Regards'
sascha

**Comment by madcoda9000** [comment]
Hello,

sorry, my fault :-(

I forgot to chown the config file after i've copied it into the new folder. After that the update was successful.

Regards
Sascha

**Comment by nuxsmin** [comment]
Great! I was sure that it would be a permissions issue :)
