### ISSUE TITLE
SP Replication 

### ISSUE THREAD

**Issue by zsolnayp** [nuxsmin/sysPass#562]
Hi!

Im trying to replicate an existing SP server in a master/save style :

First Im stoping mariadb and httpd, than I have copied the 
/war/www and the /var/lib/mysql/ with rsync from another machine.
After all I have got an error:

Error 1045: SQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'localhost' (using password: YES) 

Because of the pw hash for the sp_admin is different in the DB I suppose..

Is there a work as design method for replicating a SP server?

Sinc: Pol.

**Comment by nuxsmin** [comment]
Hi!

Currently there isn't any working design about that, but you could get it by clustering, that is using pacemaker and drbd to get the services synced. This will work as an active-passive cluster.

I've implemented this scenario with other applications.

You should be aware about the PHP sessions, that need to be synced between the servers, because the users will be logged out if the sessions aren't replicated.

**Comment by zsolnayp** [comment]
My goal was to made a delayed replication between two physical SP machines. (ex: a week delay)
So I automatically check&restore the MASTER backup, and if something went wrong the users can 
use the SLAVE one, with zero downtime. (Of course recommendation not to modify jut read)

I have just finished the project this time, so if it is interesting and You may left this thread open for a while, then I will copy paste some part from the commands I used to...

THX Pol

**Comment by nuxsmin** [comment]
Ok, regarding the "read only" behavior, it won't be possible, because the application writes some messages in the event log, besides other data like connection tracking and updating the user's data (login time, user's pass -if login through LDAP-, etc).

To sum up, a "read only" environment won't be possible...

**Comment by zsolnayp** [comment]
I will keep in mind this!

By design the MASTER will be in service, if devil goes on and the SLAVE will be used, then I backed up the master from the backup. 

ASAP I will provide a short dec. of replication...

Pol

**Comment by zsolnayp** [comment]
Here are the method I used to weekly replication from the MASTER to SLAVE:

In order to run this scripts,  must apply chmod +x, and I m running this with root permissions :)

***backup_master.sh***

#!/bin/sh

systemctl stop httpd
sleep 10
tar czf syspass_latest.tar.gz /var/www/html/syspass/
sleep 10
mysqldump -p --single-transaction --quick -A > syspass_latest.sql
sleep 10
systemctl start httpd
sleep 10
cp syspass_latest.tar.gz /.../backup/syspass_$(date +"%m_%d_%Y").tar.gz
sleep 10
cp syspass_latest.sql /.../backup/syspass_$(date +"%m_%d_%Y").sql


***restore_slave.sh***

#!/bin/sh

scp   root@MASTER_HOST:/root/syspass_latest* /root/
sleep 10
systemctl stop httpd
sleep 10
tar xpf /root/syspass_latest.tar.gz 
sleep 10
mysql -u root -p < /root/syspass_latest.sql 
sleep 10
systemctl start httpd

It is recomended to check it manually to make sure it do the job as you expect. 
Then schedule run as often as you like in your crontab for ex. a weekly period:

Run it at 00:00 am every Saturday morning, on your master to do the backup:

0       0       *       *       SAT      /....../backup_master.sh

Run it at 00:00 am every Saturday morning, a day after on your slave to do the restore:

0       0       *       *       SUN      /....../restore_slave.sh

PS: the 'sleep 10' is just for every case..

**Comment by nuxsmin** [comment]
Umm, why not to rsync both? You could easily sync the webserver and mysql files from the master server to the slave, that is performing an rsync from `/var/www/html/sysPass` and `/var/lib/mysql` by shutting down the services before, so you don't need to deal with export/import...

**Comment by nuxsmin** [comment]
BTW, thanks so much for your contribution!

**Comment by zsolnayp** [comment]
Huhh, you may right, I have considered the followings:

As I informed rsync is not so safe, and if I want  to do this secure,
I have to make a tunel with ssh. So scp looked easier.

I do not have so much experiment in databases and as far as I know, 
to sync mysql/mariadb with hard copy by the  /var/lib/mysql is
more risky, than  doing a logical dump from a database.
Plus a dump can easily move/store/restore on an independent 
backup/test system. 

I planed a test system in our virtual environment to follow the new versions of your marvelous code!!!

**Comment by zsolnayp** [comment]
I forgot to write that I have tried the rsync and have some issues...
