### ISSUE TITLE
[Idea] Duplicate account with the same information but without the same password

### ISSUE THREAD

**Issue by juanfernandovillahernandez** [nuxsmin/sysPass#563]
Sometimes we need document a large amount of passwords in the same machine. 
If you put a option "duplicate this account" the life of many persons would be easier.
Could you please add this feature to syspass?
Thanks in advance.

**Comment by nuxsmin** [comment]
Sure, but you already can do it by the "copy account" button. Is there any missing behaviour that I didn't take into account?

Thanks for the feedback!
