### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysPass#565]
Hi , 
i was just playing around  with updateing  vom 1.1 : ) 
therefore i had to look several times  via tail  at the apache logs 

damnit ...   apache  is logging  user and password in plaintext  to the  access.log 

please do some investigation on this case ... 
suboptimal feature if these logs are outside of an docker container : ) 

the last time i saw  this  was  2.1.5

**Comment by VexedSyd** [comment]
I'm running sysPass v2.1.8.17042901 and I have just checked apache's access.log...
The passwords are not logged in clear text.

**Comment by osnet** [comment]
confirmed.  2.1.8  does not log them  plaintext ... 
everythings ok now : )

**Comment by nuxsmin** [comment]
This issue could be related to an error debugging, so I'd forgot to remove that line...

Sorry for the inconvenience.
