### ISSUE TITLE
LDAP --> Active Directory Authentication (Win2012R2)

### ISSUE THREAD

**Issue by jrfx85** [nuxsmin/sysPass#566]
Hi everybody

First of all, I would like to thank you for this amazing project your working on. I'm almost done with the configuration to go live on the production environment...Just one little issue. Maybe you have a solution or an explanation on this.

As you can see in the attached file. the check is working (Log:  	LDAP connection OK
Objects found : 1). There is one user in the selected group and is showing up in the result (highlighted in red). After this i would like to import the user. It says, it is done, with no errors. But in the logfile there it shows the following: LDAP users import finished Imported users : 0/1 Errors : 0

Am I doing something wrong? Do I have to import the AD Users, or does it do the authentication directly querying the AD and allows the users in the defined group to login
![ldap-syspass](https://cloud.githubusercontent.com/assets/28386436/25696854/12e338ea-30b9-11e7-93a2-e63343f79f53.png)
?  Thanks for your help

**Comment by jrfx85** [comment]
Thanks for your fast reply.

As Login Attribute the sAMAccountName is used
As Name Attribute the displayName is used

The LDAP query is returning both of them.

sAMAccountName: "x.x"
displayName: "x x"

Kind regards

**Comment by nuxsmin** [comment]
I'm trying to figure out what could be happening, although you could log into sysPass with LDAP users, because they will be created if don't exist. The default group and profile will be used for the newly created users.

**Comment by jrfx85** [comment]
I can't log into sysPass with LDAP users...Also there is nothing coming in on the LDAP Server
![auth](https://cloud.githubusercontent.com/assets/28386436/25701197/9ef8b316-30cb-11e7-80b1-d1131a8b0328.png)

**Comment by nuxsmin** [comment]
Are you using auth basic?

**Comment by jrfx85** [comment]
I have some locally created users...and now I'm trying to authenticate with LDAP.
The above test should take LDAP, when I'm using username@domain or domain\username

**Comment by nuxsmin** [comment]
Currently, the LDAP login will only work with the "samaccountname" attribute, so "userPrincipalName" won't work (ie "user@foo.bar" or "foo\user").

With auth basic I meant that if your web server is prompting (through the browser) for an username and pass before accessing to sysPass, if so, the auth basic username will be checked against the LDAP username. If they match, login will be granted.

**Comment by jrfx85** [comment]
Ok, thanks for this info...
I figured it out...i have to enable LDAP and Active Directory at the same time...No it works with the LDAP Authentication and the users are automatically created...The import still does not work, but this is not important to me....so my problem is solved... Thanks for your help and have a nice day

**Comment by nuxsmin** [comment]
That sounds good!

I'll solve the import issue on another issue already opened.

Kind regards

**Comment by nuxsmin** [comment]
Have a nice day too ;)
