### ISSUE TITLE
Feature Request: about Private Account

### ISSUE THREAD

**Issue by Yotouille** [nuxsmin/sysPass#567]
¡ Hola !
Not long ago we ran into some misunderstanding behaviors using "Private" accounts. And so we have found some operations that cannot be done, for when you switch an account to "Private" it is done for the owner of the account, and more, if you are not the owner/creator, the account just disappear from your reality when you click "Save". :)
So, here is the idea when you want to modify an account to private:

An alert informs you about the owner and that some users/groups will loose access to the account. You have 3 choices here:
  - Make it Private (for the owner)
  - Make it Private for another user
  - Cancel !

Here an example where this could be usefull (work environnement):
"I need to create VPN accesses for some collegues and store them into Syspass, but at the end, I want these accounts to be private for each of my collegues."

What do you think ?

Have a good day, and keep up the good work ! 

Y.

**Comment by nuxsmin** [comment]
Hola!, 

you're right, if you aren't the account's owner, when you switch it to be private, it will disappear. Actually these kind of accounts need to be created by the user itself, and not on behalf of the end user.

Your approach is quite interesting and it will be a nice feature for the next release ;)

Thanks for the feedback!

**Comment by Yotouille** [comment]
Thanks !! 👍

**Comment by nuxsmin** [comment]
Added to roadmap #422
