### ISSUE TITLE
TAG field location on Account page ?

### ISSUE THREAD

**Issue by Yotouille** [nuxsmin/sysPass#568]
Hi again,

I only wanted to ask if anybody think it could be more natural to have the "Tag" field directly after the "Category" field ?
I found the way it is located now a bit isolated, most of time forgetting its existence.

Thanks again !

Y.

**Comment by nuxsmin** [comment]
Hi,

I think like you, but it would break the page layout, because a large bar could be a hassle in that position, so I decided to put it at the bottom. What do you think?

Thanks for the feedback!

**Comment by Yotouille** [comment]
Good point !
Maybe reducing the search field, and adding each tag directly under it ? (tags sorted on few columns)
Or maybe adding a config option to make the Tag field mandatory ? (so it will not be forgotten)

Thanks again !

**Comment by nuxsmin** [comment]
Sure, the second point would be nice (through user preferences), because the first one is already done on large screens:

![captura_121](https://cloud.githubusercontent.com/assets/1775774/25837351/b761dcfa-348d-11e7-9ced-dcab5e8912ae.png)

**Comment by nuxsmin** [comment]
Added to roadmap #422
