### ISSUE TITLE
Upgrading to 2.1

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#570]
I have a problem with the update from **1.2.0.21** to **2.1.9**.

In my test enviornment everything worked fine with the update. The only difference between my test enviornment and the live system is that I use ssl on the live system.

This is how I have done the upgrade:
- created a new folder on the webserver sysPass_N 
- copied the newest version into the folder
- copied the config files from the 1.2.0.21 version to the new one
- changed the owner for the whole folder sysPass_N
- change the config folder permissions to 750

If I now browse to localhost/sysPass_N the page keeps blank and I can not do the database upgrade.

**Comment by nuxsmin** [comment]
Hello, is there any error either in the webserver log or `syspass.log` (within config directory)?

Please, check out the modules installed, because if any PHP module were missing, it would fail too.

Regards

**Comment by Goatmaster** [comment]
The syspass.log is empty I already checked it.

What other php modules do I need in comparison to the older version ?

**Comment by nuxsmin** [comment]
If using PHP 5.6 on Debian https://doc.syspass.org/en/installing/debian8.html#instalacion-debian-8

Other distributions would need some additional modules that were not compiled within PHP.

**Comment by Goatmaster** [comment]
I am using CentOS 7

**Comment by nuxsmin** [comment]
php-mbstring php-xml (there are some issues related to CentOS https://github.com/nuxsmin/sysPass/issues?utf8=%E2%9C%93&q=is%3Aissue%20centos%20)

CentOS 7 uses PHP 5.4 by default, so you would need to upgrade to 5.6 version.

**Comment by Goatmaster** [comment]
That was the problem! 

Upgraded PHP to 5.6 and now everything is working. 

Thank you very much for you fast help (like always) !

**Comment by nuxsmin** [comment]
Great!

Thanks for the feedback!
