### ISSUE TITLE
LDAP users search error

### ISSUE THREAD

**Issue by Libeccio84** [nuxsmin/sysPass#571]
Hello, I am starting using sysPass (master branch) and I have issues in importing users from LDAP.
This is my LDAP config:
![image](https://cloud.githubusercontent.com/assets/23318355/25802868/9c822f50-33f4-11e7-873f-ae3c52a70551.png)

And this is the error from the log:
![image](https://cloud.githubusercontent.com/assets/23318355/25802887/b00da856-33f4-11e7-9f06-2e42fb469fce.png)

As far as I can see from the log this is what happens:

- I can successfully bind to LDAP
- the DN of the group containing users gets modified with a "cn=" prepended to the declared group
- the filter should be different from the group: (objectClass=person), but there is no way to declare it.

Can anyone help me?
Thanks in advance

**Comment by nuxsmin** [comment]
Hello, it seems that the group RDN has a wrong format. You would need to set to either a group name (without RDN syntax) or the full RDN (ie. cn=YOUR_GROUP_NAME, ou=USERS, dc=foo, dc=bar)

Kind regards

**Comment by Libeccio84** [comment]
The problem is that our LDAP is structured in such a way that each user, with their email is listed in the "Users" ou. Is there a way to add them in this way?

**Comment by nuxsmin** [comment]
Ummm, are using the groups in any way?. If you don't use them let the field in blank.

The group is only used for filtering which users will be granted to access sysPass. The group is not an OU.

**Comment by Libeccio84** [comment]
Great! That worked!
Many thanks
