### ISSUE TITLE
admin login disabled after LDAP sync anabled

### ISSUE THREAD

**Issue by Libeccio84** [nuxsmin/sysPass#573]
Hi all,
I am using sysyPass (master branch) and I imported users from LDAP.
As far as no users were imported, the admin account worked fine, right after that I could not login as admin anymore.
This is what I get

![screen shot 2017-05-08 at 17 36 08](https://cloud.githubusercontent.com/assets/23318355/25811881/e83f420a-3414-11e7-820e-e76e07a4ed56.png)

Am I doing something wrong?

Thanks in advance

**Comment by nuxsmin** [comment]
Are you using auth basic?. If so, the user's login will be checked against the auth basic user and if it doesn't match login will be denied.

**Comment by Libeccio84** [comment]
Actully I don't know. What I found is that if I change ldapEnabled value in config.xml from 1 to 0 i can successfully log in but I do not think this is the writh way...

**Comment by nuxsmin** [comment]
That worked because you disabled the LDAP authentication.

Does your browser prompt for an user name and password before loading sysPass page?. Could you take a look to sysPass event log? (There would be some info about the wrong log in)

**Comment by Libeccio84** [comment]
For sure it is looking for the admin account in LDAP as far as ldapEnabled is setted to 1 in config.xml:

<img width="1344" alt="screen shot 2017-05-09 at 09 14 08" src="https://cloud.githubusercontent.com/assets/23318355/25839450/fdd07426-3497-11e7-9445-463f9a31bfaf.png">

**Comment by Libeccio84** [comment]
Sure, as a matter of fact they work as soon as LDAP login is disabled. It looks like it does not check the internal DB when LDAP is enabled, regardless the fact that the user is the admin one.
Of course there is no "admin" entry in LDAP

**Comment by nuxsmin** [comment]
LDAP is mandatory if it's activated and the login will be denied if the user exists in LDAP (seeing your screenshot seems so) and the credentials are wrong.

You could change the admin login so it won't match with any LDAP existing user. This change does not take any effect on sysPass, because it's internally referenced by id. You can also create another user with the same privileges.

**Comment by Libeccio84** [comment]
Auch!
You are perfectly right: among > 100 users there was an "admin" account. Creating another non LDAP user solved the problem.
Many thanks for your precious help!

**Comment by nuxsmin** [comment]
Great!! You're welcome.

Thanks for the feedback!
