### ISSUE TITLE
Getting Internal Server Error when trying to load the content 

### ISSUE THREAD

**Issue by jr-RXcode** [nuxsmin/sysPass#574]
After importing a few users from active directory, syspass started to give me internal server error in the search page. Looking at the network tab looks like the ajax_getContent.php is getting a 500 internal Server Error. 
My system was working fine until i imported new users. running php7.0 apache 2.4  syspass 2.0

Any ideas? other tabs seems to work.

**Comment by jr-RXcode** [comment]
This is the error i see in the httpd logs 
PHP Fata error: Uncaught Error: Call to undefined function SP\\Html\\mb_substr() in /var/www/sysPass/inc/SP/Html/HTML.classphp:96

**Comment by jr-RXcode** [comment]
Here is the exact error... could it be that i added an entry with two url and that's what's breaking it ?
![error](https://cloud.githubusercontent.com/assets/25696127/25831730/ec78117a-341a-11e7-8d06-37f1a08189b3.JPG)

**Comment by nuxsmin** [comment]
Hello, that is because a PHP module is missing (also on #381):

`sudo apt-get install php7.0-mbstring`

http://php.net/manual/en/mbstring.installation.php

**Comment by jr-RXcode** [comment]
Thanks! that worked.

**Comment by nuxsmin** [comment]
Thanks for the feedback!
