### ISSUE TITLE
Cannot delete LDAP user once he has logged in at least 1 time

### ISSUE THREAD

**Issue by Libeccio84** [nuxsmin/sysPass#575]
Hi all,
after testing LDAP integration, I successfully logged in with my account.
In order to re-organize users and groups I decided to remove every account before re-importing them.
Expected behavior: each account should be deleted.
Actual behavior: every account but mine had been removed.

Here is the log:
<img width="1378" alt="screen shot 2017-05-09 at 09 45 47" src="https://cloud.githubusercontent.com/assets/23318355/25841645/395091a8-34a1-11e7-8e19-ed39007546d8.png">

Thanks in advance for the help.

**Comment by nuxsmin** [comment]
Hi!, that is so because this user is being used by an account's history record, so you need to delete it from "Items & Customizations > Accounts (H)".

Kind regards

**Comment by Libeccio84** [comment]
Many thanks, that worked.

**Comment by nuxsmin** [comment]
Thanks for the feedback!
