### ISSUE TITLE
Redirect to https://syspass.dev/index./index.php

### ISSUE THREAD

**Issue by marank** [nuxsmin/sysPass#576]
Hey there,
I wanted to try sysPass, installed it using a XAMPP server. But every time I want to access sysPass, I'm getting redirected to https://syspass.dev/index./index.php instead of https://syspass.dev/index.php. What's happening?
Thanks for your help!

**Comment by nuxsmin** [comment]
Hey!, sysPass does not redirect by itself, so you would need to check out the XAMPP config, because it's most likely that there is a redirection set in the Apache config

Kind regards
