### ISSUE TITLE
It's just showing only directory 

### ISSUE THREAD

**Issue by janarthananjana** [nuxsmin/sysPass#578]
![screenshot 64](https://cloud.githubusercontent.com/assets/28565699/25851900/eac2d9b6-34c7-11e7-93ae-8210bedc189b.png)

I can't set up the syspass i attached the image and the guide is not working .Please help me

https://doc.syspass.org/en/installing/centos7.html#modificando-selinux

Problem with epel

**Comment by nuxsmin** [comment]
Hi, you need to enable the PHP module and disable SELinux, did you do it?

**Comment by janarthananjana** [comment]
its enable bro and selinux also disabled 
![screenshot 65](https://cloud.githubusercontent.com/assets/28565699/25856180/8801bb4a-34d5-11e7-8015-12982be06764.png)
![screenshot 66](https://cloud.githubusercontent.com/assets/28565699/25856179/87f552b0-34d5-11e7-8551-4cbab927c81b.png)

**Comment by janarthananjana** [comment]
Thanks alot for the clue finally its working. Can I know it will create the database automatically?

**Comment by nuxsmin** [comment]
Great! Ummm, you need PHP 5.6 at least. The DB will be create on the install process through the browser.
