### ISSUE TITLE
Can not save new account

### ISSUE THREAD

**Issue by madcoda9000** [nuxsmin/sysPass#579]
Hello,

when i save an new account, i get the following error (see attached screenshot). This happens after update to v2.1.8.

Do you have any idea on how to fix this?

Regards
Sascha
![2017-05-10_0944](https://cloud.githubusercontent.com/assets/25504739/25896856/17788b72-3586-11e7-9606-de67fc99e2b3.png)

**Comment by nuxsmin** [comment]
Hello, is there any error in `syspass.log` (within config directory)? And what about the webserver error log?

I haven't received any issue about that, it's really weird.

**Comment by madcoda9000** [comment]
Hello,

please find attached both files.

Regards
Sascha

[apache_error_log.txt](https://github.com/nuxsmin/sysPass/files/989847/apache_error_log.txt)
[syspass_log.txt](https://github.com/nuxsmin/sysPass/files/989846/syspass_log.txt)

**Comment by nuxsmin** [comment]
Thanks, unfortunately there aren't any clues about the issue...

**Comment by madcoda9000** [comment]
so, what can i do to support you? Where can i get more informations?

**Comment by nuxsmin** [comment]
Does it still occur?. You can edit this file https://github.com/nuxsmin/sysPass/blob/master/inc/Base.php#L43 and set DEBUG to true. It will log some notices and warnings (if there were) to the webserver log file and the browser console (by pressing F12)

**Comment by madcoda9000** [comment]
so, whe i enable debug in Base.php, i get this error on hitting the save button...
![error_on_save](https://cloud.githubusercontent.com/assets/25504739/25903802/bca257b0-359d-11e7-80fd-f8ff3851b144.png)

**Comment by nuxsmin** [comment]
I've just updated the "offending" code that throws the message. Please download it from the master branch.

Regards

**Comment by madcoda9000** [comment]
sorry to bother you :-(

1. i've made a copy of the db
2. renamed my old syspass folder
3. created the new syspass folder and copied all files from master branch  into this folder
4. copied *.pem files and config.xml to new config foler
5. chown'ed backup & config folder
6. chmod 750 to all files in config folder
7. chaned db name to new db name in config file

But when i open the browser it prompted me the installation....!!?? Am i doing something wrong?

**Comment by madcoda9000** [comment]
so, i got it. I've set the installed param to 1 in config files.

Now:

1. it does not display the accounts shown in my database screenshot
2. whe i create a new account, i receive the erro message that an exception is occured. The account is stored in the database but not visible in syspass 

I've really no idea what i can do :-(

**Comment by nuxsmin** [comment]
Umm, let me think about it

**Comment by nuxsmin** [comment]
Does it occur with every newly created account?

**Comment by madcoda9000** [comment]
Hi,

Does it occur with every newly created account?
--> yes

Btw: i've made a tail -f on syspass.log and on apache error.log. But no entry in both file is shown when this error occurs.

**Comment by madcoda9000** [comment]
PS: the account is stored in the accounts table but not visible in the account_data_v view!

**Comment by nuxsmin** [comment]
Really weird...

**Comment by nuxsmin** [comment]
Please check out if there is any missing field or any that is not linked to an existing id like customer, category or users

**Comment by madcoda9000** [comment]
i found the error :-)

It was because i've copied all tables and views from previous installation into a new database. All data where copied fine.

But the views where not modified. I've take a look inot hte views and it shows that there is the old database name mentioned. I've replaced the old database name with the new one and saved the views.

Now it works without any hassle :-)

Many thanks for your help

**Comment by nuxsmin** [comment]
Great!! You're welcome.

When you restores a view the permissions are granted to the last owner and it's linked to the old database (this case), so you won't be able to execute it.

Thanks for the feedback!
