### ISSUE TITLE
Regarding data

### ISSUE THREAD

**Issue by janarthananjana** [nuxsmin/sysPass#580]
Can you give some sample data so I can test syspsass

**Comment by janarthananjana** [comment]
sample password data like 500 to 600 accounts

**Comment by nuxsmin** [comment]
Hello, here you have an xml export from the demo site, so you could import it as many times you want. The only data exported is related to accounts, customers categories and tags, so other data need to be filled.

[sysPass-9f173b0e68886acc3bd96f87963bd8c41dc33719.xml.zip](https://github.com/nuxsmin/sysPass/files/993508/sysPass-9f173b0e68886acc3bd96f87963bd8c41dc33719.xml.zip)

The master password for importing is: 12345678900

Regards

**Comment by janarthananjana** [comment]
Thanks lot
