### ISSUE TITLE
Move "Plugins" (Items & Customizations) to Configuration

### ISSUE THREAD

**Issue by Senexis** [nuxsmin/sysPass#583]
Note before starting; this might be personal preference, and if it is considered it to be, please at least provide a way to move it to the configuration section.

Today I'd like to propose to move the Plugins section from the items menu to configuration. The reason is that the only piece of real customization is the plugins sections in the first place, the rest directly affects and is related to items. Additionally, changing the enabled plugins directly correlates to how the entire system works, in order words; by changing plugins, you're configuring the site to be like you want it.

I'd like to see, again, the Plugins tab to be moved to the Configuration category, and the "Items and Customizations" text changed to "Items". Again, everything would be directly related to items and everything would be neater.

Please consider this change.

**Comment by nuxsmin** [comment]
Hello, I thought like you, it is more related to a config feature, but the config view does not rely on a grid layout, so I decided to implement it on the items layout. (which relies on a grid layout).

I'll consider your request, and think about how to implement it without breaking the config layout.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in v3. Thanks for the feedback!

Regards
