### ISSUE TITLE
UI: Only show the footer bar when logged in

### ISSUE THREAD

**Issue by Nadermane** [nuxsmin/sysPass#587]
In my own custom theme, I made the footer bar only display during logging in. This is in order to prevent possible attackers from instantly and very easily figuring out the project and version number. I was wondering if you could add this to the main theme by using `<?php if ($loggedIn): ?>` on line 7 and `<?php endif; ?>` on line 56 in `body-footer.inc`.

**Comment by nuxsmin** [comment]
You're right, the footer may be hidden to avoid to guess the app version.

**Comment by nuxsmin** [comment]
Added to roadmap #422
