### ISSUE TITLE
UI: Page titles in <title>

### ISSUE THREAD

**Issue by Nadermane** [nuxsmin/sysPass#589]
One complaint an end user had is that page titles are not displayed anywhere. Would be possible to do something like `Syspass - Configuration` in the `<title>` tag ~~and in an `<h2>` tag~~ on pages?

Edit: I know the tabs are selected and users could gather the page title from those. I am asking for something like `<?php $pageTitle ?>` to be able to use in themes.

**Comment by nuxsmin** [comment]
Sure, I could be achieved by some JavaScript hacks.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Added to roadmap #422
