### ISSUE TITLE
Managing users and groups

### ISSUE THREAD

**Issue by Libeccio84** [nuxsmin/sysPass#590]
Actually I don't know if this is an issue, or an expected behaviour, but whenever I add a user to a group from the group property, that user does not change his group; as you can see from the following screenshots.

From the admin's user panel
<img width="1399" alt="screen shot 2017-05-15 at 09 53 21" src="https://cloud.githubusercontent.com/assets/23318355/26047735/a2044458-3954-11e7-8ac1-790046ff6c14.png">

From the group properties
<img width="625" alt="screen shot 2017-05-15 at 09 54 06" src="https://cloud.githubusercontent.com/assets/23318355/26047740/a961d81e-3954-11e7-8b26-fe79162649f4.png">

From the user's personal page
<img width="125" alt="screen shot 2017-05-15 at 09 54 38" src="https://cloud.githubusercontent.com/assets/23318355/26047743/ad5a677e-3954-11e7-9d74-9760a2faa3c6.png">

Moreover I'd like to know whether it is possible to add a single user to multiple groups.

Many thanks

**Comment by nuxsmin** [comment]
Hello, the users added to a group are granted to access to those accounts​ that have the group listed as a secondary one.

The group displayed on the user tooltip is its main group.

**Comment by Libeccio84** [comment]
Unfortunately it didn't work.
I will explain you what I have done, so that you can tell me where I am makng mistakes:

1. I added users U1 and U2 to group Infra and only U2 to group netsec
2. as U2 I created an account then, I set the access panel as follows
<img width="1054" alt="screen shot 2017-05-15 at 17 33 34" src="https://cloud.githubusercontent.com/assets/23318355/26065566/aff13f7c-3994-11e7-9416-99385b0e19d6.png">

3. U1 cannot see the account (fine)
4. I added U1 to netsec as well as U2
5. I logged in as U1 as well, but I still cannot see the account

Where is (are) my mistake(s)?

**Comment by nuxsmin** [comment]
Ok, actually there are two behaviors:

- Default: The user will be granted to those accounts on which the group is added as a secondary group and that group is the user's main group.
- Extended: The user who is listed in a group will be granted to those accounts on which the group is added as a secondary group if the "Secondary Group Access" is enabled on "Configuration > Accounts" tab.

I know that there isn't enough info about that, so I'm going to fix it shortly.

Regards

**Comment by Libeccio84** [comment]
Ok, it works now. But now I am wondering what is the meaning of "Private for Group": does this mean that it can be seen only by those users which belong to that group as primary group?

Thanks

**Comment by nuxsmin** [comment]
> But now I am wondering what is the meaning of "Private for Group": does this mean that it can be seen only by those users which belong to that group as primary group?

That's right, and even if you're either an application or accounts admin you won't be able to see it.

**Comment by nuxsmin** [comment]
Documented
