### ISSUE TITLE
Managing Customers and accounts: question and feature request

### ISSUE THREAD

**Issue by Libeccio84** [nuxsmin/sysPass#592]
Hi, I am sorry since I am writing here a lot in these days, but I need to better understand syspass.
I checked around both in issues and in the FAQ section, but I couldn't find any useful info on two points:

1. is there a way to avoid the admin user to inspect the content of non private accounts? I thought that the following configuration should be enough, but it looks like it doesn't
![screen shot 2017-05-16 at 10 36 33](https://cloud.githubusercontent.com/assets/23318355/26097071/9e47fefc-3a23-11e7-9039-a8279480eb0c.png)

2. As admin I created a "Personal" customer in order to group all personal accounts under it, but, as soon as someone stores a private account under "Personal", that customer is not available anymore by anybody else. I know that the workaround is to use "Personal" as a category, instead of a customer name, but this would imply that each user would create their own "Name Surname" customer in order to have a clearer overview of their accounts in the search section. As a consequence everybody should be able to add customers causing a huge mess. Is there a solution to this problem or, at least, a way to automatically create a "Name Surname" customer per each user after the first login?

3. Further consequence: if someboy by mistakes creates an account under a "shared customer" and switches on the Private flag (instead of the private for group one, for instance) that customer might not be available anymore by anybody else without knowing the reason. Am I right? Is there a way to avoid this consequence?

Thanks in advance for the reply

**Comment by nuxsmin** [comment]
Never mind, your questions are quite useful for others :)

> is there a way to avoid the admin user to inspect the content of non private accounts? I thought that the following configuration should be enough, but it looks like it doesn't

No, private accounts is the only way to avoid admins (application or accounts ones) to view the accounts. Be aware that admin role isn't set by profile, it's set on the user's tab instead.

> As admin I created a "Personal" customer in order to group all personal accounts under it, but, as soon as someone stores a private account under "Personal", that customer is not available anymore by anybody else. I know that the workaround is to use "Personal" as a category, instead of a customer name, but this would imply that each user would create their own "Name Surname" customer in order to have a clearer overview of their accounts in the search section. As a consequence everybody should be able to add customers causing a huge mess. Is there a solution to this problem or, at least, a way to automatically create a "Name Surname" customer per each user after the first login?

> Further consequence: if someboy by mistakes creates an account under a "shared customer" and switches on the Private flag (instead of the private for group one, for instance) that customer might not be available anymore by anybody else without knowing the reason. Am I right? Is there a way to avoid this consequence?

Next release will include shared/global customers so they will be always available. Actually it's already implemented in the devel branch :)

Regards

**Comment by Libeccio84** [comment]
Can I consider the development branch as stable, in the sense that it is master+changes?

**Comment by nuxsmin** [comment]
Unfortunately no, the devel branch includes some major changes that are not well tested and it will bump the version number to 2.2. This branch need to be periodically synced from the master one since some fixes are done on it.

**Comment by Libeccio84** [comment]
Is there a deadline for the next stable release?

**Comment by nuxsmin** [comment]
;)

![captura_133](https://cloud.githubusercontent.com/assets/1775774/26100425/209935a6-3a2e-11e7-8931-f54153e024b9.png)

**Comment by Libeccio84** [comment]
Great!
Thanks again :)

**Comment by nuxsmin** [comment]
You're welcome ;)
