### ISSUE TITLE
Stuck in spanish

### ISSUE THREAD

**Issue by MiggyMan** [nuxsmin/sysPass#593]
I attempted to upgrade to 2.1.9, and despite the config file being set to English it would only display in Spanish so I was unable to carry out the database upgrade, I've rolled it back to 2.0 but..... It's still stuck in Spanish, it shows English in the configuration page but regardless of what you set the language to you only get Spanish now!

Given that I backed up and then restored the entire webroot and I've wiped any cookies during this I can only assume it's made some change in the database but looking at the databases config table I can't see anywhere this would be set ?

I do have a backup of the database and I can roll this back if needs be but it like to understand what has occurred for future reference.

**Comment by nuxsmin** [comment]
Umm, that is weird because the language is never changed on the upgrading process. Please check out that you have installed the correct locales. Did you upgrade the server OS?

The only settings that are stored in the database are those related to the user's preferences, but they won't be loaded unless you perform a log in.

**Comment by MiggyMan** [comment]
There where no changes to the os, it's currently in testing on my desktop :D

The config file in both instances has en_US, the entire webroot was copied to a backup directory and restored after so there would be no differences there from the previous installation.

The only difference at all was that I had to install the mbstrings extension to get the 2.1.9 page to even load so I don't know if this is an issue but it was removed after and the package installed nor removed any dependencies. 



Also, can we have a en_real/en_uk language setting for those of us in the uk please ? :D

**Comment by MiggyMan** [comment]
Just as a side note, since I may well be missing something obvious, you appear to be missing the es_ES locale folder in any of the versions of syspass i've had running on here but it is referenced in Language.class.php.

**Comment by nuxsmin** [comment]
Sometimes Apache gets stuck  when the .mo files (translations) are changed, so please restart the webserver.

> Also, can we have a en_real/en_uk language setting for those of us in the uk please ? :D

Sure, but since I'm not a native English speaker, some translations would be a mixin of both languages, so I think en_US is the most spread.

> Just as a side note, since I may well be missing something obvious, you appear to be missing the es_ES locale folder in any of the versions of syspass i've had running on here but it is referenced in Language.class.php.

Spanish is the default language in the code, so every string is translated from it :)
The reference in the Language.class.php is because it will be set if your browser language headers are sent with some stuff like "es_XX"

**Comment by MiggyMan** [comment]
That got it, I had done multiple restarts but it seems you need to do a stop and a start.

However, I did do a stop and start when I tried 2.1.9, do you want me to try this again and see if it still happens again ?

**Comment by nuxsmin** [comment]
Right, every time you change the translation files, apache needs to be reloaded because it stores them in the cache.

**Comment by MiggyMan** [comment]
It is interesting that a plain reload with apachectl didn't clear it but that I had to do a full stop start.

I'll have another go with the update later but it's worth noting that during the upgrade I did do a full stop start (otherwise people might have tried accessing it while I was working)

**Comment by nuxsmin** [comment]
> I'll have another go with the update later but it's worth noting that during the upgrade I did do a full stop start (otherwise people might have tried accessing it while I was working)

Sure, be aware that the app will switch maintenance mode on if an upgraded is needed, so users won't be able to access (a maintenance massage is shown). So, did you restart apache while upgrading? Did the upgrade task start?

**Comment by MiggyMan** [comment]
I literally shut down apache before I started and restarted it after id made all the changes to the webroot (which was a fresh install).

**Comment by MiggyMan** [comment]
Stopped apache, copied the 2.1.9 webroot in, set permissions, started apache, spanish....

Stopped it and started it again, English.

Weird is not the word :D

**Comment by MiggyMan** [comment]
And it's done :D

One observation, if it's setup for ldap and not using active directory you probably want to login attribute setting to default to uid and not samacountname simply because if you're not running ad it won't be present :)

**Comment by nuxsmin** [comment]
Reeeally weird :D

I have had several issues like this one while developing...

I hope it works fine now

**Comment by nuxsmin** [comment]
Don't worry about the LDAP attributes because it uses a catch-all filter:

```'(&(|(samaccountname=' . $this->userLogin . ')(cn=' . $this->userLogin . ')(uid=' . $this->userLogin . '))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))'```

**Comment by MiggyMan** [comment]
That's a mean filter :D

Mind you, you should look at the extended filter syntax if you want to know pain :D

Are you carrying out a direct bind for this or pulling the hash back and comparing it ?

I only ask because using a direct bind will ensure that any an account locked by the password policy module is not authenticated (and a lot of people manually compare hashes!)

**Comment by nuxsmin** [comment]
> Mind you, you should look at the extended filter syntax if you want to know pain :D

Sure, actually I've only dealt with nested group membership

> Are you carrying out a direct bind for this or pulling the hash back and comparing it ?

Just a direct bind...

https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Auth/Ldap/LdapBase.class.php#L212

An then LDAP status codes will tell if the account is expired, locked or whatever.

Thanks for the feedback!

**Comment by MiggyMan** [comment]
Glad to hear that, people not using binds is a bugbear of mine :)

On the subject of filters are there any plans to allow additional filter attributes to be added ? :)

**Comment by nuxsmin** [comment]
Two steps bind:

https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Auth/Ldap/LdapBase.class.php#L418

**Comment by nuxsmin** [comment]
Sure, what filters do you think are either missed or need?
