### ISSUE TITLE
make expiration date optional

### ISSUE THREAD

**Issue by derStephan** [nuxsmin/sysPass#595]
Hi,

I would like to know, if expiration date could be optional. At the moment, the current date is set if I do not change it. Does that mean that the passwort is expired tomorrow?

May I ask to leave the field empty as default (meaning: no expiration date)?

Regards

Stephan

**Comment by nuxsmin** [comment]
Hi,

the expiration date is only a notice, so the passwords will remain available. You can also perform a search filtering for the expired passwords (see search help)

> May I ask to leave the field empty as default (meaning: no expiration date)?

Actually if you leave it blank, the expiration date won't be set (or take any effect).

Regards.

**Comment by derStephan** [comment]
>the expiration date is only a notice, so the passwords will remain available

I see. But then, the password will be marked as expired which may cause confusion. 

>Actually if you leave it blank, the expiration date won't be set (or take any effect).

My point exactly. My feature request is to change the default value from ``today`` to blank. I can not imagine that ``today`` as expiration date is a useful default value in most cases. :-P

**Comment by nuxsmin** [comment]
> My point exactly. My feature request is to change the default value from today to blank. I can not imagine that today as expiration date is a useful default value in most cases. :-P

Ok, but it's set by default for 3 months, isn't it?. 

BTW, I know that an global option will be better, so I'll add this feature in the next release ;)

**Comment by derStephan** [comment]
>Ok, but it's set by default for 3 months, isn't it?.

Hehe, I did not even understand this, sorry. 

The problem is that the expiration date is almost always defined by the system where I enter the password. Pre-defining it in sysPass is doomed to failure in those cases. A guess of 3 months is hardly ever useful when there are external expiration rules. 

>BTW, I know that an global option will be better, so I'll add this feature in the next release ;)

I would really appreciate it. And I can not say thank you often enough. So... **thank you**. You are awesome and especially your response times are as well.

**Comment by nuxsmin** [comment]
You're welcome!!

Your comments and support are really appreciated too, thanks too!

**Comment by nuxsmin** [comment]
Added to roadmap #422
