### ISSUE TITLE
Columns in search view do not line up with data

### ISSUE THREAD

**Issue by twotwenty** [nuxsmin/sysPass#596]
the Column headers and their respective data do not line up in the search view.
This display issue is consistent in both chrome and firefox

![syspass_bug](https://cloud.githubusercontent.com/assets/1158515/26217302/b40ce1c8-3bbb-11e7-905e-a6e77a6290eb.jpeg)

**Comment by nuxsmin** [comment]
This has been discussed a time ago on an issue and it has an explanation: there will be some sorting parameters that wouldn't be related to the fields shown, so there is no need to align the fields. Such parameters would be like number of views, expiring date, recently updated and more..

Thanks for the feedback!

**Comment by twotwenty** [comment]
I am really happy with the program, hope I can sell it to my department. As a recommendation perhaps making the sorting graphics look a little less like they should be column headers.

Thanks.

**Comment by nuxsmin** [comment]
Sure, I know that sorting fields may be a bit confusing, so I'll try to tweak UI to be more clear.

Regards
