### ISSUE TITLE
Wrong login attempts behavior

### ISSUE THREAD

**Issue by disanvparean** [nuxsmin/sysPass#597]
Hello,
Some users on my network have sometimes connections problems related to the fact they don't put the good password...But my public IP address is regularly banned from syspass so all users can't connect during 10 minutes. That's a bit annoying. Is there a way to whitelist an IP ?
Thank you for your good work, it is amazing.

**Comment by disanvparean** [comment]
Some thing I missed to tell : I set manually the master key to each user so they don't have to do it themselves. The annoying thing is that I have regularly "too many attempts" but It seems that I don't put wrong IDs so...Maybe it's blacklisting me because I do multiple connections attempts on different accounts ?

**Comment by nuxsmin** [comment]
Hello,

I'm glad to know that you found sysPass useful ;)

Regarding your question, actually the access tracking performed by logging the source ip address but if "X-Forwarded-For" header is present, it would be taken to get the original source ip address.

> Some thing I missed to tell : I set manually the master key to each user so they don't have to do it themselves. The annoying thing is that I have regularly "too many attempts" but It seems that I don't put wrong IDs so...Maybe it's blacklisting me because I do multiple connections attempts on different accounts ?

Please, could you explain how do you set the master key?. I guess that you set the user's password and then you log out and log in with the newly created user, don't you?. 

The access tracking is logged when you (or the user) enter a wrong login or the master pass is wrong. If you force a password change and the user enters a wrong previous password, it will be logged too.

Regards
