### ISSUE TITLE
Is it possible to query for a password from the command line ?

### ISSUE THREAD

**Issue by jr-RXcode** [nuxsmin/sysPass#600]
Is there way to query for the password from the command line instead of using the web interface ?

**Comment by nuxsmin** [comment]
Yes, it can be done through the API, you can also query accounts details or some other items.

**Comment by jr-RXcode** [comment]
can you give me an example of how the api call would look like, for any of the methods? No sure how APIs work exactly.

**Comment by nuxsmin** [comment]
Sure, here you have a basic client with curl:

https://gist.github.com/62338b33178544894cd7237c7fe170bd

And you can found more functions on the documentation:

http://doc.syspass.org/en/application/api.html

**Comment by jr-RXcode** [comment]
thanks!

**Comment by jr-RXcode** [comment]
What is the API token password when trying to use the getAccountPassword method ?

**Comment by nuxsmin** [comment]
You can set it up on the "Users and Accesses > API Tokens" tab

**Comment by jr-RXcode** [comment]
I'm still confused, under the API Authorizations I only see the ability to add a new authorization, which provides me with an api token, but I don't see where you set the api token password. The getAccountPassword has as parameters authtoken,id, tokenPass, details. I don't know what the tokenPass is or where to get it from. The authtoken should be the API token generated under the API Authorization tab you mentioned above, but know sure what the other one is.

**Comment by nuxsmin** [comment]
That password has been set when you created the API authorization, don't you?

**Comment by jr-RXcode** [comment]
When I create the New authorization it only ask for the user and the Action. Then it has a save button, but no place to enter a password for the token.
![image](https://cloud.githubusercontent.com/assets/25696127/26505825/1347867c-41ff-11e7-8eb5-73cdaf6a1906.png)

**Comment by nuxsmin** [comment]
Which version are you running?

**Comment by jr-RXcode** [comment]
Syspass Version 2.0

**Comment by nuxsmin** [comment]
Ok, in that case you will need to provide the "userPass" parameter which is the user's password that the token has been generated for.

BTW if you set a wrong parameter, the API will display the options for the given action.

Please, consider upgrading to the next version because there are some major fixes related to the encryption security (a CVE was created). Therefore some big improvements have been done on usability and management.

Regards.
