### ISSUE TITLE
Problemas inciando sesión

### ISSUE THREAD

**Issue by berni69** [nuxsmin/sysPass#602]
La primera vez que accedo al aplicación con un navegador dónde no se ha generado sesión recibo el error:

En el log de php veo que se ha generado la siguiente entrada:

```
[24-May-2017 16:18:18 UTC] PHP Warning:  session_start(): Failed to decode session object. Session has been destroyed in /var/www/webapps/pwd/syspass/inc/SP/Core/Init.class.php on line 381

[25-May-2017 07:27:42 UTC] PHP Warning:  Cannot modify header information - headers already sent in /var/www/webapps/pwd/syspass/inc/SP/Html/Minify.class.php on line 156

```

Uso la versión: 2.1 (2.1.9.17050401)
PHP 7.0.13 (cli) (built: Nov 22 2016 15:49:55) ( ZTS )

**Comment by nuxsmin** [comment]
Buenas, no he tenido incidencias en este sentido y por lo que veo puede ser debido a un bug: https://bugs.php.net/bug.php?id=71972

Falla en algo la aplicación?

Saludos!

**Comment by berni69** [comment]
Solo me ha fallado el regenerar la clave maestra (que no lo he conseguido pero no está relacionado con esto)

No me he dado cuenta que falle algo más, si lo viera lo añado. Acabo de empezar  a usarlo el software

**Comment by nuxsmin** [comment]
> Solo me ha fallado el regenerar la clave maestra (que no lo he conseguido pero no está relacionado con esto)

Con regenerar la clave te refieres a cambiarla? Ha fallado?

**Comment by berni69** [comment]
Exacto, pero ha fallado porque no había cuentas creadas y ha dejado la aplicación en mantenimiento (me acabo de dar cuenta ahora, con una cuenta y un usuario creado ha funcionado). Quizá estaría bien hacer una comprobacion.

**Comment by nuxsmin** [comment]
Correcto, tienes razón, voy a revisarlo para que dicho error no se produzca al no haber cuentas.

Gracias!
