### ISSUE TITLE
Sugerencia timeout

### ISSUE THREAD

**Issue by cleitma** [nuxsmin/sysPass#604]
Buenas,

Como siempre, enhorabuena por la aplicación. Quería sugeriros una cosa por si la veis interesante, actualmente, cuando muestras una contraseña, pese a que tengas el timeout al mínimo (300), hasta que no interaccionas con la página de nuevo, tienes ahí la contraseña mostrándose. 

Intenté forzar a través del apache que hiciera un refresh, pero por razones evidentes, no es viable. Finalmente lo que hice en el index.php fue añadir lo siguiente

`
**header("Refresh: 302; url=index.php");**
use SP\Controller\MainController;
use SP\Core\Init;
use SP\Core\Session;

define('APP_ROOT', '.');

require APP_ROOT . DIRECTORY_SEPARATOR . 'inc' . DIRECTORY_SEPARATOR . 'Base.php';

if (!Init::checkPostLoginActions() && Session::getAuthCompleted()) {
    $Controller = new MainController();
    $Controller->getMain();
    $Controller->view();
`

De esa manera, teniendo un timeout de 300, una vez te ha cerrado la sesión, aunque siga mostrando la contraseña, te fuerza que refresque y te redirige a la página de Login de nuevo. El tiempo del refresh debe ser superior al timeout de sesion, ya que en caso de ser menor, estaría continuamente actualizando y nunca te cerraría la sesión.

Si no se entiende algo no dudéis en decírmelo, es meramente una sugerencia 😃 😄 

De nuevo, enhorabuena por el gestor de contraseña y vuestro esfuerzo 

Saludos!

**Comment by nuxsmin** [comment]
Buenas @cleitma 

Gracias, me alegro que te guste y sea útil :)

Lo que comentas sobre el timeout de la clave, debería de desaparecer a los 30 segundos después de mostrar la clave, pero hay que tener en cuenta que si el ratón se mueve por encima de dicha ventana, el temporizador se resetea y se volvería a activar al salir del área de la clave:

https://github.com/nuxsmin/sysPass/blob/master/js/app-actions.js#L892

Voy a revisarlo/mejorarlo.

Muchas gracias por el aporte, pero no creo conveniente que cada 300 segundos se refresque la página, porque eso implica que si estás trabajando con la aplicación también sucedería (imagínate dando de alta una cuenta o cambiando la clave maestra), lo cual puede generar errores.

Saludos!

**Comment by nuxsmin** [comment]
Realizado
