### ISSUE TITLE
UI : Align the filters and the corresponding columns

### ISSUE THREAD

**Issue by daftaupe** [nuxsmin/sysPass#605]
Hello,

I think it's disturbing that on the main page the filters (as Customer, Name, Category ...) are not exactly on top of the columns they apply to. It makes one move his eyes when figuring which filter he wants to apply on a particular column and it's easy to make a mistake.
Is there a way to fix this ? Is it planned to be changed in a future release ?

Regards,

**Comment by nuxsmin** [comment]
Hello, please take a look to #596

Regards

**Comment by daftaupe** [comment]
Ah, thank you @nuxsmin, I couldn't find it when I browsed the issues.
So I'm closing this issue.

**Comment by nuxsmin** [comment]
As I've just comment on #596: I know that sorting fields may be a bit confusing, so I'll try to tweak UI to be more clear.

Because it's UX, your feedback is very appreciated ;)

Regards

**Comment by daftaupe** [comment]
Alright, thanks a lot @nuxsmin ! :) It will be much appreciated
