### ISSUE TITLE
Unable to delete user

### ISSUE THREAD

**Issue by vvascautan** [nuxsmin/sysPass#606]
Hello,

I was trying to remove a user an got some error. I am using last version.
Error while querying
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`pdb`.`accounts`,
CONSTRAINT `fk_accounts_user_edit_id` FOREIGN KEY (`account_userEditId`) REFERENCES `usrData` (`user_id`)) (0)SQL : '
DELETE 
FROM usrData 
WHERE user_id = ? 
LIMIT 1'

**Comment by nuxsmin** [comment]
Hello,
the error says that the user is related to an account because this user edited that account.

Regards

**Comment by vvascautan** [comment]
Users modify accounts all time, but sometimes people leaving and I need to remove add users, so how can I fix that, and where to find the linked account with user.
There shouldn't be any relationship.

**Comment by nuxsmin** [comment]
You could try it out by using the special search parameters (help on doc & help icon)

**Comment by vvascautan** [comment]
@nuxsmin , I think you should fix that, as it is related to multiple tables.
I was able to remove the user only after that:
update accHistory set acchistory_userId=10 where acchistory_userId=61;
update accHistory set acchistory_userEditId=10 where acchistory_userEditId=61;
update accounts set account_userId=10 where account_userId=61;
update accounts set account_userEditId=10 where account_userEditId=61:

So, it is linked not only to accounts but to history  as well.

Thank you!

**Comment by nuxsmin** [comment]
It's called relational database, in which some fields are related to keep the integrity and performance. Why it should let you remove an user id (users are linked by id) that is linked from many tables?, If the DB lets you remove that user some fields will be nulled after it, so you will never know who edited, created or even removed a record, that is the big issue.

Another question would be to give some information about the linked records, so it would be easier to find out them.

This is a security focused application, so records should be secured with this kind of restrictions.

Thanks for the feedback!
