### ISSUE TITLE
Suggestion: bulk edit

### ISSUE THREAD

**Issue by berni69** [nuxsmin/sysPass#608]
Hi,

I was testing this app and it's working very well, I would ask if could be added this feature:

- A form for manage / edit multiple accounts at same time (chage the main group, edit the labels,... )

**Comment by MagicFab** [comment]
I'd love to see this. It's important after a big import to be able to mass-edit to properly assign permissions to groups.

**Comment by nuxsmin** [comment]
Added to roadmap #422

**Comment by Fury420** [comment]
update ?
