### ISSUE TITLE
First install in English, can't change language

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#609]
Is there a system-wide language setting?

After first install the system is in Spanish, even changing per-user language stays in Spanish, it doesn't take effect.
The OS language was set to locale en_CA.UTF-8 UTF-8 initially, changing it to en_US.UTF-8 UTF-8 made the default language English.
If the initial language looks for the OS locale string, it should probably only match the first 2 characters... or default to English anyways.

**Comment by nuxsmin** [comment]
You're right, if the en_US locale is not set, it will fallback to the default, Spanish. I will change all the strings to English, so the default will be it.

Since sysPass relies on GNU gettext, the locales must be installed on the OS, so if they​ aren't, it won't set any language.

Regards

**Comment by nuxsmin** [comment]
Added to roadmap #422
