### ISSUE TITLE
Keepass 2 XML import fails - file too big?

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#610]
I am trying to import a Keepass 2.35 database into sysPass without luck.

When using the .kdbx file directly, sysPass indicates the file extension is not accepted.

When using the exported file obtained from `File > Export > Keepass XML (2.x)` it works from a sample small file but not from my bigger real file. I am using KeePass 2.35 in Debian 8 (`keepass2` package). 

It seems the import times out after exactly 30 seconds.

 The file is ~500KB big, less than the 1024KB is the `Configuration > Accounts` section.

How can I go about troubleshooting this? I found a few closed bugs similar to this but nothing obvious.

![selection_047](https://cloud.githubusercontent.com/assets/317514/26561198/6cf46a9a-448a-11e7-9502-6d7d7543a28e.png)

**Comment by nuxsmin** [comment]
Could be, I need to reproduce this behaviour, because normal tests work fine

**Comment by nuxsmin** [comment]
@MagicFab 30 seconds is the default timeout for PHP scripts, so I think that it needs to be tweaked a bit to allow a longer running time.

**Comment by nuxsmin** [comment]
Please, could you try out the latest commit? (master branch)

**Comment by MagicFab** [comment]
Thank you, I modified [only Import.class.php accordingly](https://github.com/nuxsmin/sysPass/commit/26269c54c5d548a00e0ad04b80b76a631e0d11b7#diff-7869ea3fd0f9d9ee6fe64715ff54c174), the import tried ran for a few minutes (not stopping yet) and worked this time.

What could be done to improve feedback or speed this up? A progress indicator would be nice but this seems rather long for a relatively small database (12 categories and ~

**Comment by nuxsmin** [comment]
Since the import process is most likely to be done only once, I haven't implemented any feedback, because it would add some complexity.

How many time did it take?

**Comment by nuxsmin** [comment]
Ohh, sorry you told a few minutes...

**Comment by MagicFab** [comment]
Right, it's only done once but it's a critical moment. I suppose if it's interrupted there is the potential for data corruption. It took about 6 minutes, so at least a big fat warning on that imnport page about how long it will take is OK until something more elaborate is worth the time needed. Otherwise it gives the impression nothing is happening when in fact it's the opposite.

**Comment by nuxsmin** [comment]
Ok, I'll add some feedback while running.
