### ISSUE TITLE
Duplicidad de entradas

### ISSUE THREAD

**Issue by berni69** [nuxsmin/sysPass#611]
Hola,

Ayer haciendo pruebas me di cuenta (por error) que si creas 2 cuentas iguales con el mismo nombre,url, etiquetas, cliente, y password cambiando solo el grupo principal. Una de las dos cuentas desaparece del dashboard y al usuario le aparece con dos grupos principales, lo que me impide la gestión ya que no puedo eliminar una de las cuentas  desde la interfaz gráfica (en la base de datos aparecen ambas cuentas pero con grupos distintos)

La única opción que me quedó fue eliminarlo de la base de datos.

**Comment by nuxsmin** [comment]
Buenas, no he podido reproducir el error, ya que las he creado tal y como dices y ambas aparecen y es posible eliminarlas independientemente.

Saludos!

**Comment by berni69** [comment]
Para eliminarlas lo he tenido que hacer directamente en la basede datos ya que en la GUI me aparecían como una sola con dos grupos

**Comment by nuxsmin** [comment]
Sí, lo leí en el primer post.

He hecho una prueba en el entorno de demo (https://demo.syspass.org) y las entradas aparecen correctamente.

![003](https://cloud.githubusercontent.com/assets/1775774/26578569/a9bd66c4-4530-11e7-9637-98ad9ab7a159.png)

Si vas a hacer una prueba, hazlo con el usuario "testing" con clave "1234", ya que con otro usuario no te dejará cambiar el grupo principal.

Saludos!

**Comment by berni69** [comment]
No he conseguido duplicarlo en el entorno de test, si me vuelve a pasar intentarñe documentarlo mejor.

**Comment by nuxsmin** [comment]
Perfecto, gracias!
