### ISSUE TITLE
Lots of scrolling to view content of text fields (Notes), should take full width

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#614]
A lot of information needs scrolling to be seen, particularly in the Notes field when viewing account details.

This could benefit from resizing to full width. I am not sure how else to describe this, I've attached a screen capture highlighting the "wasted" space.

![selection_048](https://cloud.githubusercontent.com/assets/317514/26588020/0c7d828a-4522-11e7-8d76-a6de0562f78c.png)

**Comment by nuxsmin** [comment]
sysPass uses material design lite components, and they are designed using a fixed width, so any tweak to them could lead to a wrong behaviour.

BTW I will try to find out if there's any way to get it.

**Comment by MagicFab** [comment]
Just adding some more context...
I thought it was responsive design (with some bug), it gets quite hard to scroll through notes even on a tablet.
The icons are also too small to touch (on mobile), perhaps another subject.

**Comment by nodrogneirbo** [comment]
I would like to second this request. A larger 'Notes' or custom Text Area field is the only thing preventing me from rolling this out within our organisation.

**Comment by nuxsmin** [comment]
@nodrogneirbo @MagicFab It'll be fixed shortly.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, since last release, notes field can be resized on height. I've been doing some tests around sizing boxes but unfortunately they breaks the UI layout, so it needs a bit more work to get full sizing.

Regards
