### ISSUE TITLE
Can't add a user to more than one group

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#616]
I'd like to add users to more than one group.

This would let me assign permissions based on the user's role. For example an account may be accessible by both "phone system admins" and "sysadmins". Right now only one group can be defined for a specific user.

Maybe I misunderstand the current permissions model. If this is already implemented, how is it achieved? 

Otherwise I'd like to add this suggestion, i.e. implement the ability to assign a user to several groups.

**Comment by nuxsmin** [comment]
Hello, that is currently implemented by adding the users to the group itself, the you can grant access to the account by adding as a secondary group.

Be aware that the secondary group users will be granted if they have this group as their main group. You can change this behaviour by enabling secondary group access on the accounts config tab
