### ISSUE TITLE
Suggestions to correct/improve Debian install instructions 

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#617]
1) The Debian install instructions should direct to use MariaDB, not MySQL.

MariaDB is replacing MySQL in the upcoming (soon-to-be released) Debian 9 (Jessie) and is already available in Debian 8. Its packages should be used in the Debian install instructions, possible in the others too.

I used it in a couple of test installs without issue, the package is mariadb-server.

2) There is a missing slash, this:

```
Create an change the backup directory owner:

mkdir var/www/html/syspass/backup
chown www-data /var/www/html/syspass/backup
```
...should be replaced by this:

```
Create an change the backup directory owner:

mkdir /var/www/html/syspass/backup
chown www-data /var/www/html/syspass/backup
```

3) A string in Spanish is still there.

**Copiar y descomprimir el archivo sysPass en el directorio creado:** should be **Copy and decompress the sysPass file into the newly created directory:**

4) Before **Optional to enable LDAP:** there could be a small section 

**Highly recommended: enabling SSL:**

```
In order to increase the access security to your sysPass installation, consider using SSL. See <Security>(link to the Security page at https://doc.syspass.org/en/application/security.html) and the following resources for Debian:

* For LAN-only websites or to use a self-signed SSL certificate: https://wiki.debian.org/Self-Signed_Certificate
* For Internet-facing websites consider using LetsEncrypt - see https://certbot.eff.org/
```

**Comment by nuxsmin** [comment]
Done!, thanks for your contribution! ;)

Regards.
