### ISSUE TITLE
cannot change login attribute from sAMAccountName

### ISSUE THREAD

**Issue by twotwenty** [nuxsmin/sysPass#620]
Login Attribute cannot be changed from 	sAMAccountName
I use 389ds and need to set it to DN. 

when I save and then browse back to this setting its back to sAMAccountName

**Comment by nuxsmin** [comment]
Hello, the login attribute option is only needed for importing users from LDAP. You shouldn't need to change it because the LDAP filter includes some common attributes like:

```
    protected function getUserDnFilter()
    {
        return '(&(|(samaccountname=' . $this->userLogin . ')(cn=' . $this->userLogin . ')(uid=' . $this->userLogin . '))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))';
    }
```

Why do you want to change it?
