### ISSUE TITLE
Master password forgotten

### ISSUE THREAD

**Issue by tomeriko** [nuxsmin/sysPass#621]
Hi,

I know it is a common issue but I couldn't find a solution for it.
Is it possible to recover the Master Password? (I have admin account access and root privileges on the machine)

Thank you.

**Comment by nuxsmin** [comment]
Hi,
the master key could be displayed, but you need to replace the following file (in `inc/themes/material-blue/views/common`directory):

https://gist.github.com/nuxsmin/ca59f3754312fb6d54b2cf45283bf754

**Comment by nuxsmin** [comment]
I forgot to mention that you also need to enable debug mode in sysPass configuration.

**Comment by tomeriko** [comment]
Thank you nuxsmin,
I have replaced the file and enabled the debug mode.
I see the DEBUG INFO page but the master password isn't displayed. Instead, I see at the bottom of the page: Key
and under it I see the first 4 letters of the master password... not the whole password... any ideas?

**Comment by nuxsmin** [comment]
That should be the master key used. You can try it by creating a new user and enter when logging in.

**Comment by tomeriko** [comment]
Well unfortunantly, it is not... I know for sure that it is a longer password.
Anyway, I have tried the first 4 letters that it shows me but it didnt work...

**Comment by nuxsmin** [comment]
May be it contains some special characters that aren't being escaped within the HTML

**Comment by tomeriko** [comment]
You are right! there was a "<" character in the password so all of the characthers from this one to the end weren't show on the page!
After inspecting the HTML element of the KEY, I got the full master password.
Thank you very much!
This project is amazing, I love it.

**Comment by nuxsmin** [comment]
It sounds great!!. You're welcome ;)

**Comment by nuxsmin** [comment]
Please don't forget to put back the original code, because anyone with app admin rights can view the real master key.

**Comment by tomeriko** [comment]
already done :)
