### ISSUE TITLE
edit multiple accounts at once

### ISSUE THREAD

**Issue by dmaniad** [nuxsmin/sysPass#623]
Hello,
keep up the good work!
I was wondering is there an option to edit multiple accounts at one step?
For example, can I select 10 accounts and set 1 specific password for all of them?

**Comment by nuxsmin** [comment]
Hello, 

I'm glad to know that you found sysPass useful ;)

This feature has been requested a time ago (there would be an opened issue too) and will be implemented in the next release.

Thanks for the feedback!

**Comment by Fury420** [comment]
Any update ?
