### ISSUE TITLE
Import XML worked, but...

### ISSUE THREAD

**Issue by joeg1484** [nuxsmin/sysPass#625]
I installed a fresh version onto my Ubuntu 16.04 system. Before, I was running sysPass on my CentOS 6.9 system without issue.

When I try to import a recently exported account list, it imports fine, but all the passwords are some random string - perhaps the hash instead of the password?

Any idea how I can get my passwords back? I sill have the old system in place...

Thanks!
Joe

**Comment by nuxsmin** [comment]
Hello, it's weird because the import process should detect the old encryption schema (it was changed since 2.1 version). Why did you do an XML export-import instead of an in-place upgrade?. The XML export does not contain many objects like users, profiles, custom fields, etc.

Regards

**Comment by joeg1484** [comment]
Thanks for the reply!

I tried to do the upgrade but got all kinds of errors and failures with
the upgrade. I never saved the errors so I can not recall what they all
were, but I remember there was a page with some orphans and I assigned
to id 0 and proceeded, but then it still failed.

Again, I could try again to let you know what all the failures were, I
just figured that a fresh install would work better and then import in
the xml for my accounts.

Thanks!

**Comment by nuxsmin** [comment]
Sure, please give it a try again, because there were a lot of improvements on the upgrade process, so you wouldn't need to enter those orphan IDs since the app will create them for you, then you could review them later.

I hope it works fine now...

Regards

**Comment by joeg1484** [comment]
Hi Ruben,

So, I tried to do an upgrade of the existing database, but get this 
error during the process:

Error while applying auxiliary update

Then it just goes back to the update required page.

Any ideas?

Thanks!

**Comment by joeg1484** [comment]
Here is the error from the log:

`
2017-06-06 19:16:36 - Error while querying
SQLSTATE[HY000]: General error: 1214 The used table type doesn't support FULLTEXT indexes (0)
Caller 1: SP\Storage\DB\logDBException
Caller 2: SP\Storage\DB\getQuery
Caller 3: SP\Core\Upgrade\Upgrade\upgradeDB
Caller 4: SP\Core\Upgrade\Upgrade\auxPreDbUpgrade
Caller 5: SP\Core\Upgrade\Upgrade\doUpgrade
Caller 6: SP\Controller\MainActionController\upgrade
Caller 7: SP\Controller\MainActionController\doAction
2017-06-06 19:16:37 - SQL : 'ALTER TABLE `accounts` ENGINE = InnoDB'
2017-06-06 19:16:37 - Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_level' in 'field list'
2017-06-06 19:16:37 - #0  SP\Storage\DB->prepareQueryData() called at [/var/www/html/joeman1.com/sysPass/inc/SP/Storage/DB.class.php:150]
#1  SP\Storage\DB->doQuery() called at [/var/www/html/joeman1.com/sysPass/inc/SP/Storage/DB.class.php:341]
#2  SP\Storage\DB::getQuery() called at [/var/www/html/joeman1.com/sysPass/inc/SP/Log/Log.class.php:195]
#3  SP\Log\Log->writeLog() called at [/var/www/html/joeman1.com/sysPass/inc/SP/Storage/DB.class.php:296]
#4  SP\Storage\DB::logDBException() called at [/var/www/html/joeman1.com/sysPass/inc/SP/Storage/DB.class.php:347]
#5  SP\Storage\DB::getQuery() called at [/var/www/html/joeman1.com/sysPass/inc/SP/Core/Upgrade/Upgrade.class.php:230]
#6  SP\Core\Upgrade\Upgrade::upgradeDB() called at [/var/www/html/joeman1.com/sysPass/inc/SP/Core/Upgrade/Upgrade.class.php:180]
#7  SP\Core\Upgrade\Upgrade::auxPreDbUpgrade() called at [/var/www/html/joeman1.com/sysPass/inc/SP/Core/Upgrade/Upgrade.class.php:81]
#8  SP\Core\Upgrade\Upgrade::doUpgrade() called at [/var/www/html/joeman1.com/sysPass/inc/SP/Controller/MainActionController.class.php:101]
#9  SP\Controller\MainActionController->upgrade() called at [/var/www/html/joeman1.com/sysPass/inc/SP/Controller/MainActionController.class.php:72]
#10 SP\Controller\MainActionController->doAction() called at [/var/www/html/joeman1.com/sysPass/ajax/ajax_upgrade.php:36]

2017-06-06 19:16:37 - Error while querying
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_level' in 'field list' (0)
Caller 1: SP\Storage\DB\logDBException
Caller 2: SP\Storage\DB\getQuery
Caller 3: SP\Log\Log\writeLog
Caller 4: SP\Storage\DB\logDBException
Caller 5: SP\Storage\DB\getQuery
Caller 6: SP\Core\Upgrade\Upgrade\upgradeDB
Caller 7: SP\Core\Upgrade\Upgrade\auxPreDbUpgrade
Caller 8: SP\Core\Upgrade\Upgrade\doUpgrade
Caller 9: SP\Controller\MainActionController\upgrade
Caller 10: SP\Controller\MainActionController\doAction
2017-06-06 19:16:37 - SQL : 'INSERT INTO log SET \n            log_date = UNIX_TIMESTAMP(),\n            log_login = ?,\n            log_userId = ?,\n            log_ipAddress = ?,\n            log_action = ?,\n            log_level = ?,\n            log_description = ?'
2017-06-06 19:16:37 - Error while querying
Caller 1: SP\Log\Log\writeLog
Caller 2: SP\Storage\DB\logDBException
Caller 3: SP\Storage\DB\getQuery
Caller 4: SP\Core\Upgrade\Upgrade\upgradeDB
Caller 5: SP\Core\Upgrade\Upgrade\auxPreDbUpgrade
Caller 6: SP\Core\Upgrade\Upgrade\doUpgrade
Caller 7: SP\Controller\MainActionController\upgrade
Caller 8: SP\Controller\MainActionController\doAction
2017-06-06 19:16:38 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_level' in 'field list'
2017-06-06 19:16:38 - Action: Update DB -- Description: Error while updating the database -- Details: Version : 130.00000000
ERROR : Error en la consulta (0)
2017-06-06 19:16:38 - Deregister Task: upgrade

`

**Comment by nuxsmin** [comment]
Ok, I know the issue:

`Exception: SQLSTATE[HY000]: General error: 1214 The used table type doesn't support FULLTEXT indexes`

This index was removed in previous releases, but some people were pointing to an issue when applying the change because the index didn't exist, so I decided to skip that step.

https://github.com/nuxsmin/sysPass/blob/2.0.0.17011201-beta/inc/sql/1316011001.sql#L10

Please add the following line on the top of "inc/sql/13000000000.sql" file:

`ALTER TABLE `accounts` DROP INDEX `IDX_searchTxt`;`

Then perform the upgrade again.

Regards

**Comment by joeg1484** [comment]
Hi Ruben,

Ok, I will look at it when I get home from work and let you know how it
goes.

Thanks again for the quick responses and help!

**Comment by nuxsmin** [comment]
Hi, did it go fine?

**Comment by joeg1484** [comment]
Hi Ruben,

Sorry for not replying... Yes, I got it to upgrade!

However, there was a bug where the upgrade screen, where I had to enter
the long key, was ll in Spanish and not English, so I had to copy/paste
into Google translate.

But, it is all up and working now :).

Thanks so much for your help!
Joe

**Comment by nuxsmin** [comment]
Nice, I'll fix it!

Regards
