### ISSUE TITLE
"Action invalide" (invalid action) when trying to setup email notifications

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#628]
I am trying to setup email notifications, when saving I always get a red bar with "Action invalide" (French for invalid action) at the top.

I am using GMail, the credentials are verified. I tried both SSL (465) or TLS (587) with smtp.gmail.com as per [the usual instructions](https://support.google.com/a/answer/176600), this same setup is in use in other local servers.

The syspass log doesn't show any errors, is there another place I should look at or another debug level that can be enabled?

**Comment by nuxsmin** [comment]
Hello, sorry for the late response.

I've been doing some tests and couldn't reproduce this behavior. Please, could you tell me some details about the process?

"Invalid action" is mostly thrown when an HTML form has been sent with an invalid security token, so this does not have any relation with the mail parameters set.

Regards.

**Comment by MagicFab** [comment]
Thank you, I'll check again this week.

**Comment by MagicFab** [comment]
Tried again, this time right after login, it successfully updated the config. Perhaps the error message could be improved,  Thank for the hint!

**Comment by nuxsmin** [comment]
Fine..you're welcome!
