### ISSUE TITLE
Centos 7 Permissions

### ISSUE THREAD

**Issue by Eddd97** [nuxsmin/sysPass#631]
Hello! I had my syspass database running on a centos 7 box, but today I decided to make a fresh install of the OS. Now it seems I can't make it work again, most probably because of permissions. I've followed the steps mentioned in documentation, but the selinux (I do not want to disable it) was blocking apache access to index.php (and any other file from /var/www/html); I ran "chcon -R -t httpd_sys_rw_content_t /var/www/html/sysPass/" and it seems selinux stopped blocking syspass, but I still get HTTP Error 500. I've looked into httpd error logs and I've found: "PHP Fatal error:  Interface 'JsonSerializable' not found in /var/www/html/syspass/inc/SP/Config/ConfigData.class.php on line 34" . I should also mention that I've set '/var/www/html' ownership to apache:apache. Any help would be appreciated!

**Comment by nuxsmin** [comment]
Hello! you would need to install the PHP Json module (I don't know how it's named in Centos).
