### ISSUE TITLE
Login as non-required field when creating an account?

### ISSUE THREAD

**Issue by PedroMD** [nuxsmin/sysPass#632]
Hi everybody,

I'm evaluating sysPass and it seems  that, for our use case, logins should not be a required field while creating an account. Is this something you would be willing to change, by allowing us to specify which fields should be mandatory?

Thanks and keep up the good work!

**Comment by nuxsmin** [comment]
Hi @PedroMD,

you're right, login should be a non-required field, but providing a way to set which fields are required -or not- would be a time consuming task (for me) and there won't be many options, since currently there are a few optional fields and some of them are very unlikely to become a required one (eg. notes?, expiry date?, tags?) and you can use the custom fields to perform it. What do you think?

Regards

**Comment by PedroMD** [comment]
Hi @nuxsmin,

Thanks for your reply. Ok, I understand it is a demanding task. I did not, however, understood your question. I do not intend to use other custom fields, I would just like to create Accounts without having to specify a login field.

**Comment by nuxsmin** [comment]
Sure, that will be done, but I was discussing if there is any special reason to develop a feature that would allow to enforce some required fields, because the remaining fields wouldn't be useful to be required.

**Comment by PedroMD** [comment]
Oh, ok, great! Well, I can't speak for everybody, but when you're talking about this kind of software, I think customisation is always more than welcome, so we can adapt it to every special use case (not all teams/companies work in the same way). Just my 2 cents :)

**Comment by pslobo** [comment]
Hi @nuxsmin. I'm working in conjunction with @PedroMD on evaluating this and personally, while I understand that adding logic to select which fields are required or not would be time consuming, I also think it would be beneficial in the long run. Granted we don't need toggles for every field and that doesn't make sense (as you said previously), but rather adding two new toggles in the settings such as:

```Required Fields:
- Login             Yes | No
- Password      Yes | No
```

- **Use Case:** Using SysPass to securely store files (such as certificates, ssh keys etc.). In this case, login/username and possibly password don't need to be required fields as often enough, there is no data to add here and we're forced to add dummy text

**Comment by nuxsmin** [comment]
Hi @pslobo , you're right, sometimes those fields could be need to be skipped, so a config option could be added. I need to think about how to achieve it, because the password field is required in the database structure.

Regards.

**Comment by nuxsmin** [comment]
Added to roadmap #422
