### ISSUE TITLE
i can not access after install

### ISSUE THREAD

**Issue by pmz86** [nuxsmin/sysPass#633]
Hi there,
i have a problem.
After the installation (the last version available) i can't access. i always receive this message "Wrong Login". I'm sure my credentials are ok.
What can i do?.
If you need some kind of information just ask. i can give you access ftp also.

Thanks in advance.

Paul Murillo

**Comment by nuxsmin** [comment]
Hi, are you using auth basic?

Regards

**Comment by nuxsmin** [comment]
https://doc.syspass.org/en/application/authorization.html

**Comment by pmz86** [comment]
Sorry for my late answer.
I don't remember to have configured something like this during the installation.
How can i know what kind of Authirization method i'm using?
Thanks.

**Comment by nuxsmin** [comment]
No worries...

It's configured on the webserver or any proxy you're connecting through.

Does the browser prompt for any user and password before log in?

**Comment by pmz86** [comment]
No.... what i see it's the login form. there is not any password protection before log in.

**Comment by nuxsmin** [comment]
Ummm, so weird. Did you enable LDAP?

**Comment by pmz86** [comment]
I don't think so. I mean i saw this in the file config.xml
<ldapEnabled>0</ldapEnabled>

**Comment by pmz86** [comment]
"<ldapEnabled>0</ldapEnabled>"

**Comment by pmz86** [comment]
ldapEnabled 0 ldapEnabled

**Comment by nuxsmin** [comment]
Could you access to the db and check out if there's​any message in eventLog table?

**Comment by pmz86** [comment]
Sono andato sulla tabell "LOG"
ed ho sempre questo errore quando cerco di loggarmi: 
 
Wrong login
Type : authBrowser
User : admin
Authentication :  ()

**Comment by nuxsmin** [comment]
Are you using any SSO mechanism?, And what about auth basic?
