### ISSUE TITLE
Password Expiry and Two-Factor Authentication (Question)

### ISSUE THREAD

**Issue by nikhilc89** [nuxsmin/sysPass#634]
@nuxsmin The password Expiry field, can we not use it? Some passwords don't expire so how do we overcome that?
And for the Two-Factor authentication, instead of users manually enabling it, can we force users to use it when they login (if it's not enabled) so they will always have to use Two-Factor Authentication.

**Comment by nuxsmin** [comment]
Hello @nikhilc89 regarding the password expiry field, you can let it blank so the expiry date won't be set.

About the 2FA, it's a feature that will be implemented in the next version by either checking group membership or user's settings (not preferences).

Regards

**Comment by nikhilc89** [comment]
Hello @nuxsmin , perfect. 
Did not know the expiry field could be left blank.
Maybe when creating a new account it can be left blank as default? Otherwise users think it's a needed field. Or a checkbox next to it stating 'No Expiry' so users can click that.

And noted about the 2FA. 

Thank You.

**Comment by nuxsmin** [comment]
Sure, an "unset" button would be nice to get it, so users wouldn't get confused.

Regards.

**Comment by ortizleo** [comment]
What we can do if a user have 2FA and lose his access on google authenticator software (phone problem)?

**Comment by nuxsmin** [comment]
Currently there isn't any way to disable 2fa for a single user, you could either reset 2fa data, but it will delete all users data related to the plugin, or disable the 2fa plugin, so it won't require the code.

This feature will be available in next release.

**Comment by nuxsmin** [comment]
Added to roadmap #422
