### ISSUE TITLE
Customers and Tags colors 

### ISSUE THREAD

**Issue by fprina** [nuxsmin/sysPass#635]
First of all, thank you for your work, it's amazing.

As my little suggestion; Maybe could be sensible add the possibility to set static colors to "Customers" and "Tags" to better understand "at a glance" what you are seeing

Thanks again for you great code

**Comment by nuxsmin** [comment]
I'm so glad to hear that you found sysPass useful :)

Regarding your request, yes, it's planned to be done for next release, but I thought to implement it on the customers, so I'll analyze how to achieve on the tags.

Thanks for the feedback!

**Comment by fprina** [comment]
Thanks to you

**Comment by nuxsmin** [comment]
Added to roadmap #422
