### ISSUE TITLE
Lack of input sanitization in SQL queries using LIKE

### ISSUE THREAD

**Issue by LeSuisse** [nuxsmin/sysPass#636]
Hello,

I took a look at the source code of this application, I'm a bit sorry for the series of report I'm going to open. I also did not found either in the README or in the website a way to report issues with security implications so I do that here.

I only did a reading of the source code so I may be wrong. If that's case, sorry for the noise.

It seems that SQL queries using LIKE does not escape the meta-characters used in such queries (i.e. in the case of MySQL/MariaDB % and _). This can change the meaning of a query or in the worst case it can leads to a denial of service. The denial of service possibility is however limited with MySQL/MariaDB when only LIKE is used since it does not have a full regular expression support.

Impacted files:
 * `inc/SP/Mgmt/Users/UserSearch.class.php`
 * `inc/SP/Mgmt/Tags/TagSearch.class.php`
 * `inc/SP/Mgmt/Profiles/ProfileSearch.class.php`
 * `inc/SP/Mgmt/Plugins/PluginSearch.class.php`
 * `inc/SP/Mgmt/Notices/NoticeSearch.class.php`
 * `inc/SP/Mgmt/Groups/GroupSearch.class.php`
 * `inc/SP/Mgmt/Files/FileSearch.class.php`
 * `inc/SP/Mgmt/Customers/CustomerSearch.class.php`
 * `inc/SP/Mgmt/Categories/CategorySearch.class.php`
 * `inc/SP/Mgmt/ApiTokens/ApiTokenSearch.class.php`
 * `inc/SP/Account/AccountUtil.class.php`
 * `inc/SP/Account/AccountSearch.class.php`
 * `inc/SP/Account/AccountHistoryUtil.class.php`

Some (non exhaustive) references to help understand the issue:
 * https://githubengineering.com/like-injection/
 * https://www.owasp.org/index.php/Testing_for_SQL_Wildcard_Attacks_(OWASP-DS-001)

**Comment by nuxsmin** [comment]
Hello,

This issue would lead, in the worst case, to a DoS, so it could be managed, but I don't know if parsing the input would also lead to DoS because a performance issue if any kind of attack is performed.

I'm no telling that it doesn't need to be improved, but DoS could be performed in many ways. What do you think?

Kind regards.
