### ISSUE TITLE
Búsqueda de claves

### ISSUE THREAD

**Issue by s0nH4cK** [nuxsmin/sysPass#64]
Hola,

Antes de nada, enhorabuena por el proyecto!

Cuando entras en la vista principal (index.php) y haces una búsqueda de una clave, te muestra correctamente los resultados.
En cambio, si en la vista principal hay varias páginas (por ejemplo 100 claves mostradas en 4 páginas de 25 claves cada una), navegas a cualquier página que no sea la 1, la búsqueda no se hace correctamente, no muestra ningún resultado.
En la versión beta 1.1 todavía persiste este error.

Gracias, un saludo!

**Comment by nuxsmin** [comment]
Buenas, he tratado de reproducir el error que comentas y la presentación es correcta.

Puedes probar con la última version?

Saludos
