### ISSUE TITLE
Unable to create account using api

### ISSUE THREAD

**Issue by cbrassel** [nuxsmin/sysPass#640]
Hi,

I have a created an api user with "new account" right and I'm unable to create any account, I got only the error "no access", I have other rights like search, view password and they are working great.

Any idea where I can search ?

Regard's

Claude

**Comment by nuxsmin** [comment]
Hi, do you mean that you created a user through the API or you granted a user to use the API instead?

Regards.

**Comment by cbrassel** [comment]
creating account by api, my json =>
{	"jsonrpc": "2.0",
	"method": "addAccount",
	"params": {
		"authToken": "67c1430c7bb66fc77a488fd028c1f68fd17a46a2543678745d6b884e4ee36601", 
		"tokenPass": "oGjPT2YWRIH2",
		"name": "testEntry",
		"categoryId": 2,
		"customerId": 3,
		"login": "administrateur",
		"pass": "default",
		"url": "1.1.1.1"
	},
	"id": "syspassAddAccount"
}

**Comment by nuxsmin** [comment]
Seems right, so you're not be able to add more accounts now, aren't you?.

**Comment by cbrassel** [comment]
If i use the user in the web interface I can create accounts, but with the api I have this response => 
{"jsonrpc":"2.0","error":{"code":0,"message":"Acc\u00e8s non autoris\u00e9","data":""},"id":0}

it's in french .. but it say's access not authorized

**Comment by cbrassel** [comment]
I have try'ed another account (admin) but I have the same issue

**Comment by nuxsmin** [comment]
Umm, did you set the correct token's password?

**Comment by cbrassel** [comment]
yes, because the getAccountData is working whit out trouble, and I use the same token and tokenpass

**Comment by nuxsmin** [comment]
Umm, the `getAccountData` method does not use any password, because it doesn't need to decrypt any data (ie. account's password). The only methods that need a key are `getAccountPassword` and `addAccount`.

**Comment by nuxsmin** [comment]
The `token` need to be provided to execute every API function, but `tokenpass` is only needed for those mentioned

**Comment by cbrassel** [comment]
In your documentation getAccountData need authToken and userPass, but I have do the same test with getAccountPassword and it's working fine.

**Comment by nuxsmin** [comment]
You're right it's written on it!...the doc is wrong, that parameter is not being used.

Let me do some tests to figure out what could be happening.

**Comment by cbrassel** [comment]
I appreciate your help ! It's the last little problem I have to integrate this great piece of software !

**Comment by nuxsmin** [comment]
This should be fixed in the latest commit ;)

**Comment by cbrassel** [comment]
i'm really sorry ..
I have just pulled the latest commit and re-created all the api authorizations but .. {"jsonrpc":"2.0","error":{"code":0,"message":"Unauthorized access","data":""},"id":0}

**Comment by cbrassel** [comment]
the api authorization is "new account" and in the user's profile I enable the "Account add" and "management account" cursor, that's right ?

**Comment by nuxsmin** [comment]
"account management" permission is not needed, because it will let the user to manage all the accounts.

**Comment by nuxsmin** [comment]
No worries..let me do some tests

**Comment by nuxsmin** [comment]
Hi, this issue should be fixed in the latest commit. All tests went fine.

Regards

**Comment by cbrassel** [comment]
Yes i confirm ! everithing is working right !
Thank's a lot !
