### ISSUE TITLE
Actualizar syspass v.1.2 a 2.1 desplegado con docker-compose

### ISSUE THREAD

**Issue by vjfernan** [nuxsmin/sysPass#643]
Buenos días,

Tengo una instalación tradicional de syspass v.1.2 y he desplegado sin problemas syspass v.2.1 con docker-compose, siguiendo las instrucciones de https://doc.syspass.org/es/installing/docker.html. Hasta aquí todo bien.

Lo que no tengo claro son los pasos que tengo que dar para migrar, en este escenario, las cuentas/configuración de la v.1.2 a la v.2.1. ¿Es posible? ¿Cuales serían los pasos?

Muchas gracias.

**Comment by nuxsmin** [comment]
Buenas @vjfernan 

La actualización de sysPass se realiza con los siguientes pasos: https://doc.syspass.org/es/updating/v2_1.html

Si no quieres utilizar la misma base de datos (que entiendo que ya usas una instancia de Docker para ello), es necesario que realices una exportación de la anterior y la importación de la misma en la BD de Docker. Ten en cuenta de dar permisos al usuario de sysPass (en la BD de Docker) sobre la BD importada.

Simplificando:

* Exportar BD v1.2 e importar en nueva instancia MySQL de Docker
* Dar permisos al usuario (normalmente sp_admin) sobre la BD importada
* Acceder a la URL de sysPass y realizar la actualización

Espereo que te sirva :)

Saludos!

**Comment by nuxsmin** [comment]
Se me olvidaba, hay que copiar también los archivos de configuración y modificar la clave de conexión a la BD si ha cambiado.

**Comment by vjfernan** [comment]
Hola @nuxsmin 

He exportado la bd de la v.1.2 y la he importado en el contenedor syspass-db.

También, en el MySQL de syspass-db, he creado el usuario sp_admin y le he dado permisos sobre la base de datos importada:

mysql> GRANT USAGE ON *.* TO 'sp_admin'@'localhost' IDENTIFIED BY PASSWORD 'OMITIDA_PASSWORD';
mysql> GRANT ALL PRIVILEGES ON `syspass`.* TO 'sp_admin'@'localhost';

Nota: No he cambiado la password original del usuario sp_admin, he mantenido la misma.

Después he copiado los ficheros config.php, key.pem y pubkey.pem de la v.1.2 en el directorio /var/www/html/sysPass/config del contenedor syspass-app.

Cuando accedo a la url de la nueva versión de syspass obtengo el siguiente mensaje:

_No es posible conectar con la BD
Error 2002: SQLSTATE[HY000] [2002] No existe el fichero o el directorio_

Mirando el directorio /var/www/html/sysPass/config veo que el fichero config.php ha sido renombrado a 
config.php.old y se ha creado un nuevo fichero llamado config.xml.

El fichero syspass.log de ese mismo directorio tiene lo siguiente:

2017-06-16 07:53:23 - Setup log file: /var/www/html/sysPass/inc/../config/syspass.log
2017-06-16 08:40:35 - Action: Update Configuration -- Description:  -- Details: Parameter : account_count
Parameter : account_link
Parameter : checkupdates
Parameter : checknotices
Parameter : dbhost
Parameter : dbname
Parameter : dbpass
Parameter : dbuser
Parameter : debug
Parameter : demo_enabled
Parameter : globalsearch
Parameter : installed
Parameter : maintenance
Parameter : passwordsalt
Parameter : session_timeout
Parameter : sitelang
Parameter : version
Parameter : config_hash
Parameter : proxy_enabled
Parameter : proxy_pass
Parameter : proxy_port
Parameter : proxy_server
Parameter : proxy_user
Parameter : resultsascards
Parameter : sitetheme
Parameter : account_passtoimage
Parameter : files_allowed_exts
Parameter : files_allowed_size
Parameter : files_enabled
Parameter : ldap_base
Parameter : ldap_enabled
Parameter : ldap_group
Parameter : ldap_server
Parameter : log_enabled
Parameter : mail_enabled
Parameter : mail_from
Parameter : mail_port
Parameter : mail_requestsenabled
Parameter : mail_security
Parameter : mail_server
Parameter : wiki_enabled
Parameter : wiki_filter
Parameter : wiki_searchurl
Version : 211117060101
2017-06-16 08:40:35 - Action: Update -- Description: Version updating done. -- Details: Version : 211117060101
Type : config
2017-06-16 08:40:35 - Action: Send Email -- Description: Email sent -- Details: CC : DIRECCION_EMAIL_OMITIDA
2017-06-16 08:40:35 - initError
2017-06-16 08:40:35 - No es posible conectar con la BD
2017-06-16 08:40:35 - Error 2002: SQLSTATE[HY000] [2002] No existe el fichero o el directorio
2017-06-16 08:49:55 - initError
2017-06-16 08:49:55 - No es posible conectar con la BD
2017-06-16 08:49:55 - Error 2002: SQLSTATE[HY000] [2002] No existe el fichero o el directorio
2017-06-16 09:37:46 - initError
2017-06-16 09:37:46 - No es posible conectar con la BD
2017-06-16 09:37:46 - Error 2002: SQLSTATE[HY000] [2002] No existe el fichero o el directorio

¿Alguna idea?

Muchas gracias

**Comment by nuxsmin** [comment]
Buenas, el mensaje de error es de MySQL y normalmente significa que no tiene acceso al socket unix de la BD:

https://stackoverflow.com/questions/11657829/error-2002-hy000-cant-connect-to-local-mysql-server-through-socket-var-run#15039113

**Comment by nuxsmin** [comment]
Con respecto a la configuración, el nuevo formato es XML, por lo que se ha importado desde el archivo de la versión anterior al nuevo.

**Comment by vjfernan** [comment]
Hola nuxsmin,

Perdona, pero no he podido responder antes.  

Gracias por el soporte. Ya he conseguido realizar la actualización sin problemas.

Un saludo.

**Comment by nuxsmin** [comment]
Perfecto! Sin problema..

Saludos!
