### ISSUE TITLE
LDAP / AD login doesn't work

### ISSUE THREAD

**Issue by wg222222** [nuxsmin/sysPass#645]
Installed sysPass 2.1.11 and enabled AD login ... clicked "Check" button and it worked. However, when log in using an AD account, it says "Wrong login". I also tried to leave the "Group" setting blank, but it didn't help.

**Comment by nuxsmin** [comment]
Is there any logged event in the event log? Are you using auth basic?

**Comment by nuxsmin** [comment]
Does this mean that you solved the previous issue?

**Comment by wg222222** [comment]
I can modify "config.xml" manually to make changes ...

**Comment by wg222222** [comment]
Both problems still exist.

**Comment by nuxsmin** [comment]
Is there any message in the event log?

**Comment by wg222222** [comment]
I did the following search and found nothing during the time period that I tried to change the settings and log in:

grep -Ri syspass /var/log/* | grep -i Jun

**Comment by nuxsmin** [comment]
I meant in sysPass event log, within the application.

**Comment by wg222222** [comment]
Part of the event log:
....
Wrong login
Type : authBrowser
User : xxxxxx
....
LDAP connection OK
Objects found : 7
.....
Configuration updated
Section : LDAP
...

**Comment by nuxsmin** [comment]
That is the key, your browser is sending auth headers (basic, digest, ntlm, Kerberos, ...), so sysPass is checking if the auth user matches with sysPass user.

Are you using any SSO mechanism?

**Comment by wg222222** [comment]
Yes, we are using SSO for our web applications. However, I just opened private browser windows using IE and Chrome and I got the same "Wrong login" results and the same event log messages.

**Comment by nuxsmin** [comment]
It seems that your browser is sending auth headers, so the SSO login need to be the same used in sysPass

**Comment by nuxsmin** [comment]
Although you use a private tab, the browser always send the SSO auth, so sysPass will check it.

https://stackoverflow.com/questions/44081909/windows-sso-in-chrome-but-not-incognito-mode-adfs-2-0

**Comment by erselbey** [comment]
> I can modify "config.xml" manually to make changes ...

It worked for me. Thank you.
