### ISSUE TITLE
Stuck on installation screen after update

### ISSUE THREAD

**Issue by Nadermane** [nuxsmin/sysPass#648]
Heya, currently I have upgraded Syspass through your instructions at [the docs](https://doc.syspass.org/en/updating/general.html) but I keep seeing the installation screen. I have tried restarting the server but it did not fix it. Could you please help me with this, and add a "Troubleshooting" section to the page regarding this, if applicable?

**Comment by nuxsmin** [comment]
So, did it prompt for upgrading?, If so and you did it, please set the tag 'installed' to 1 (within the config.xml file) and then refresh the browser page.

**Comment by Nadermane** [comment]
It did not. It's saying "Installation 2.1", and the config was already saying installed => 1.

**Comment by Nadermane** [comment]
In addition, when trying to complete a new installation (new database), the installation screen also seems to be stuck with the config saying installed => 1 as well.

**Comment by nuxsmin** [comment]
What about the permissions of `config.xml` file?
