### ISSUE TITLE
Sugerencia: Enlace de un solo uso

### ISSUE THREAD

**Issue by s0nH4cK** [nuxsmin/sysPass#65]
¿Contempláis la posibilidad de generar un enlace de un solo uso para una clave?
Por ejemplo, para enviar a una persona que ha pedido el acceso a una cuenta.

Un saludo

**Comment by jtorresc** [comment]
Hola, ¿esta función ya está disponible o aún no está implementada?

Gracias y saludos...

**Comment by nuxsmin** [comment]
No recordaba esta petición...

Está implementada en la versión de desarrollo 1.3 que estoy tratando de cerrar, pero con las incidencias de la 1.2 la estoy retrasando :(

**Comment by nuxsmin** [comment]
Hecho en sysPass 2.0-beta

Done in sysPass 2.0-beta
