### ISSUE TITLE
Unable to view account password (Invalid action)

### ISSUE THREAD

**Issue by anikarunakaran** [nuxsmin/sysPass#650]
Please see the error message while trying to view account password.

![image](https://user-images.githubusercontent.com/4487879/27389682-ae88a2a2-56bc-11e7-882a-c0b3d1cae3cb.png)

**Comment by anikarunakaran** [comment]
and copy password to clipboard shows "Error while copying to clipboard"  error also.

![image](https://user-images.githubusercontent.com/4487879/27389754-ed2aa668-56bc-11e7-8761-980935136172.png)

**Comment by nuxsmin** [comment]
The "Invalid Action" message is always thrown when the security token does not match (it could be because you opened a new sysPass tab while working on the existing one).

The clipboard error is randomly shown in some environments and it's most likely because a browser security behavior, which does not allow to copy any text to the clipboard if the request is not triggered by the user (it's an ajax request).

**Comment by anikarunakaran** [comment]
I had only one window opened and tried to re-opened syspass, however issue still exists..
we are using google chrome browser.. please advise...

**Comment by anikarunakaran** [comment]
even for view password, it shows integrity check failed message..
please let us know how to resolve this issue.

**Comment by anikarunakaran** [comment]
![image](https://user-images.githubusercontent.com/4487879/27395909-0e2ae2c6-56cf-11e7-825f-9f4374525706.png)

**Comment by nuxsmin** [comment]
"integrity check failed" message is shown when the encrypted data is wrong. What did you do before this issue?, Did you change the master key?

**Comment by nuxsmin** [comment]
Did you perform a backup?

**Comment by anikarunakaran** [comment]
yes, i did change the master key while trying to change master password.

**Comment by anikarunakaran** [comment]
could you please help me to fix this issue?.

**Comment by nuxsmin** [comment]
Sure, was there any error during the master key change in sysPass event log?. Does it occur for all the accounts?

**Comment by anikarunakaran** [comment]
There was no error during master key change and it occurs for all accounts..

**Comment by anikarunakaran** [comment]
913	2017-06-20 04:23:45	INFO	Update Master Password	ADMIN	10.207.81.42	Master password hash updated
912	2017-06-20 04:23:45	INFO	Send Email	ADMIN	10.207.81.42	Email sent
CC : xxxxxx@abc.com
911	2017-06-20 04:23:44	INFO	Send Email	ADMIN	10.207.81.42	Email sent
CC : xxxxxx@abc.com
910	2017-06-20 04:23:44	INFO	Configuration	ADMIN	10.207.81.42	Update Configuration
Parameter : masterPwd
Value : $2y$10$vBUmp4Lb2JodtNZX3YZ20.PQvYC4eZexI/Z6ql4wpuKsCagUvYeFa
909	2017-06-20 04:18:49	INFO	Log in	ADMIN	10.207.81.42	Type : authBrowser
Type : authDatabase
User : admin
Profile : Admin
Group : Admins

**Comment by nuxsmin** [comment]
It seems that you updated the master password hash, so you didn't perform any master key change, because it only changes the hash (used for checking if the master key is correct).

**Comment by anikarunakaran** [comment]
now, how do we correct this issue for all accounts?.

**Comment by anikarunakaran** [comment]
master password reset was done after enabling debugging as you recommended in https://github.com/nuxsmin/sysPass/issues/647

**Comment by nuxsmin** [comment]
Umm, that procedure only shows the current master password, so after getting it, you would be able to change it on "Configuration > Encryption", filling in the fields and then press the play button:

![captura_223](https://user-images.githubusercontent.com/1775774/27476395-e73490d2-5808-11e7-8c6d-608c08aa0754.png)

Did you do so?

**Comment by anikarunakaran** [comment]
I did, but i have selected "Do not modify accounts" option enabled on "Configuration > Encryption".

**Comment by nuxsmin** [comment]
Then the accounts weren't encrypted with the new master password, so you won't be able to decrypt any account.

Please follow these steps:

- Change the master password by setting the old master password, **but select "DO NOT MODIFY ACCOUNTS" (please be sure you set this options)**
- Log out and log in by entering the new master key

**Comment by nuxsmin** [comment]
Please don't forget to make a backup before the process.

**Comment by anikarunakaran** [comment]
Yes, i did change the master password one more time by enabling "Do not modify accounts option" , but even after logout and login, it shows the same error.

![image](https://user-images.githubusercontent.com/4487879/27479786-ef3fe630-5832-11e7-81ac-ba357e48b624.png)

![image](https://user-images.githubusercontent.com/4487879/27479805-059ad1a6-5833-11e7-9823-6c9c5f8ce8e4.png)

**Comment by anikarunakaran** [comment]
yes, for all accounts..

**Comment by nuxsmin** [comment]
Which is the sysPass version?

**Comment by anikarunakaran** [comment]
sysPass 2.1

**Comment by nuxsmin** [comment]
Please, let me know the full version number (Configuration > Information)

**Comment by anikarunakaran** [comment]
2.1 (2.1.4.17032801)
Database	SERVER_VERSION : 5.6.24-72.2 
CLIENT_VERSION : 5.1.73 
SERVER_INFO : Uptime: 180239 Threads: 1 Questions: 1855 Slow queries: 0 Opens: 93 Flush tables: 1 Open tables: 86 Queries per second avg: 0.010 
CONNECTION_STATUS : Localhost via UNIX socket 
Name: syspass@localhost
PHP	Version: 5.6.30 
Extensions: Core, date, ereg, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, json, ldap, exif, mcrypt, mssql, mysql, mysqli, PDO, pdo_dblib, pdo_mysql, pdo_sqlite, Phar, shmop, SimpleXML, sockets, sqlite3, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, zip, mhash, Zend OPcache 
Used Memory: 1536 KB 
User: apache 
OP Cache 
num_cached_scripts : 284 
num_cached_keys : 641 
max_cached_keys : 7963 
hits : 24942 
start_time : 1498038588 
last_restart_time : 0 
oom_restarts : 0 
hash_restarts : 0 
manual_restarts : 0 
misses : 288 
blacklist_misses : 0 
blacklist_miss_ratio : 0 
opcache_hit_rate : 98.858501783591
Server	Apache/2.2.15 (Red Hat)
Configuration Backup	Wed, 21 Jun 2017 08:40:55 +0000
Language help_outline
Tells whether the language is available or not.

If it is not installed, you would need install the right operating system locales. More info at Wiki.

en_US.utf8
Encrypted Session help_outline
Tells whether the session data are encrypted in the server or not

Yes
Loaded Plugins	
extension
Authenticator 
Version: 1.0 
Autor: Rubén D.

**Comment by nuxsmin** [comment]
Please upgrade to the latest version, because that issue could be related to a solved one.

Regards

**Comment by anikarunakaran** [comment]
thanks, i will try that option.. please let me the documentation link for upgrade?.

**Comment by nuxsmin** [comment]
http://doc.syspass.org/en/updating/general.html

**Comment by anikarunakaran** [comment]
even after upgrading to latest version, i get the same error while trying to view password.

![image](https://user-images.githubusercontent.com/4487879/27674800-dcc6bef2-5cc4-11e7-840d-8fe6cd4ac70b.png)

**Comment by nuxsmin** [comment]
did you set the right master password?. This error is shown when the encrypted data cannot be decrypted because a wrong encryption key.

**Comment by anikarunakaran** [comment]
yes, i was able to reset master password.. anything else can be done to resolve this issue?.

**Comment by anikarunakaran** [comment]
Hi Nuxmin, could you please help me to fix this issue?

**Comment by nuxsmin** [comment]
Sure...Some questions regarding your environment. I know that some of them have been already answered, but we need to keep them clear and together:

- Did you change the master password using the same used when you were able to display the account's password?
- Did you change it without re-encrypting the accounts?
- Did you make a backup?

Regards

**Comment by anikarunakaran** [comment]
Please see my response..

Did you change the master password using the same used when you were able to display the account's password? - Yes
Did you change it without re-encrypting the accounts?  - yes, i did change master password without re-encrypting accounts.
Did you make a backup? - Yes, i have an old backup.

**Comment by anikarunakaran** [comment]
what can be done now.?..

**Comment by nuxsmin** [comment]
Umm, How long is the master password?. Did you change it after updating sysPass to 2.1.11? (I'll add these questions to the previous post to not miss them)

**Comment by anikarunakaran** [comment]
No, i did not change the master password after upgrading to 2.1.11..

**Comment by nuxsmin** [comment]
Could you do it without encrypting the accounts?

**Comment by anikarunakaran** [comment]
i just changed master password, but it shows same error when i click on view password option for all accounts..

"Integrity check failed."

see event logs....

ID	Date / Time	Level	Event	User	IP	Description
1030	2017-07-03 07:22:50	INFO	Log in	ADMIN	10.207.80.255	Master Password updated
Type : authBrowser
Type : authDatabase
User : admin
Profile : Admin
Group : Admins

**Comment by nuxsmin** [comment]
Now you need to set  the previous password, because you set a different password than used for encrypting the accounts.

If it doesn't work, you could try to restore the backup and then check out if the encryption is working fine.

Restore procedure:

* Create a new database
* Import data from backup file
* Install latest sysPass version (in a different directory than the current one)
* Restore config directory and files.
* Modify the config.xml file to point to the new database
* Set correct permissions for the sysPass db user
* Set files and directories permissions
* Open sysPass URL

**Comment by anikarunakaran** [comment]
I have executed restore proceedure, however its not able to connect to mysql database..
I'm able to connect database with same password, but not through syspass application.. 

]# mysql -u syspass -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 47
Server version: 5.6.24-72.2 Percona Server (GPL), Release 72.2, Revision 8d0f85b

Copyright (c) 2009-2015 Percona LLC and/or its affiliates
Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>

![image](https://user-images.githubusercontent.com/4487879/27794460-e57a0794-601f-11e7-819e-796a9aac81de.png)

**Comment by nuxsmin** [comment]
Did you set the right permissions over the restored db?. Are you using the correct user?

**Comment by anikarunakaran** [comment]
Yes, I did ..

**Comment by nuxsmin** [comment]
Please, check out the username, password and host, they need to match on both sides, database and sysPass config.

**Comment by anikarunakaran** [comment]
This is what i have in the config.xml file.

<configSaver>admin</configSaver>
  <configVersion>21417032801</configVersion>
  <dbHost>localhost</dbHost>
  <dbName>sysp</dbName>
  <dbPass>LEkAl_DuC0Z2nZ7e</dbPass>
  <dbPort>3306</dbPort>
  <dbSocket></dbSocket>
  <dbUser>syspass</dbUser>
  <debug>0</debug>
  <demoEnabled>0</demoEnabled>

As i mentined earlier, i am able to connect database from the same server.Infact, database is also hosted on the same server.

 config]# mysql -u syspass -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 50
Server version: 5.6.24-72.2 Percona Server (GPL), Release 72.2, Revision 8d0f85b

Copyright (c) 2009-2015 Percona LLC and/or its affiliates
Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sysp               |
| syspass            |
+--------------------+
5 rows in set (0.00 sec)


Is there any other place where we need to change configuration other than config.xml file?.

Thanks,
Anil.

**Comment by nuxsmin** [comment]
Sure, but be aware that "sysp" user need to be allowed to use syspass database, so you need to issue "use syspass" command to check out if this user is granted.

**Comment by anikarunakaran** [comment]
somehow i was able to restore database, but no account entries are exists.. i could see below given message in logs.


1 | 2 | 3 | 4 | 5 | 6
-- | -- | -- | -- | -- | --
2017-07-06 03:01:17 | ERROR | getResultsArray | ADMIN | 10.207.80.241 | Error while queryingSQLSTATE[42S02]: Base table or view not found: 1146 Table 'pass.account_search_v' doesn't exist (0)SQL : 'SELECT * FROM account_search_v WHERE (account_categoryId = ?) AND (account_isPrivate = 0 OR (account_isPrivate = 1 AND account_userId = ?)) AND (account_isPrivateGroup = 0 OR(account_isPrivateGroup = 1 AND account_userGroupId = ?)) ORDER BY customer_name,account_name ASC LIMIT ?, ?'

**Comment by anikarunakaran** [comment]
any other options to re-configure our original database, so that we dont have to re-enter account details one more time..

**Comment by nuxsmin** [comment]
Don't worry, it's an issue related to a database view permissions because you're using a different user.

Please, use MySQL workbench to set the view permissions.

**Comment by anikarunakaran** [comment]
I just noticed that, below given tables/views are not included during syspass database backup we take from syspass application.

 account_data_v  
 account_search_v
 track 

please note, i have used the same backup file taken using syspass backup option.
Do you think, copying missing tables/views to newly created database would resolve this issue?.

Thanks,
Anil.

**Comment by nuxsmin** [comment]
Sure, you can create them by using the dbstructure.sql file

**Comment by anikarunakaran** [comment]
i have copied above mentioned tables under newly created database and its working fine now..
Not sure it will any other issues when we start using it.. thanks for your support.

**Comment by nuxsmin** [comment]
It should be fine now. Are you running the latest sysPass version?

**Comment by anikarunakaran** [comment]
Yes.
