### ISSUE TITLE
Unable to upgrade syspass sysPass-2.1.11

### ISSUE THREAD

**Issue by anikarunakaran** [nuxsmin/sysPass#651]
Hi,

I have entered correct password, but it shows below given error while upgrading to sysPass-2.1.11

![image](https://user-images.githubusercontent.com/4487879/27522674-896724ee-5a45-11e7-8f7c-05b12a0b0207.png)

Thanks,
Anil.

**Comment by nuxsmin** [comment]
Hi, are you reinstalling it again?

**Comment by anikarunakaran** [comment]
No, i am trying upgrade

**Comment by nuxsmin** [comment]
If so, why is the installation screen being displayed?. It should display the upgrade process instead.

**Comment by anikarunakaran** [comment]
I am following the below given steps to upgrade as you recommended.

1.Download the application from https://github.com/nuxsmin/sysPass/releases and uncompress the files

2.Set the sysPass directory owner and permissions

3.Copy the files (“config.xml”, “key.pem” y “pubkey.pem”) within the “config” directory from the current version to the new one

4.Open the application from a web browser

**Comment by nuxsmin** [comment]
Umm, did you set the right permissions before accessing to sysPass site?

**Comment by ortizleo** [comment]
Tested  and instalation screen is displayed here too... How perform the update?

**Comment by anikarunakaran** [comment]
see, i have set directory permissions.

html]# ls -la
total 96
drwxr-xr-x 10 apache apache  4096 Jun 24 02:02 .
drwxr-xr-x  6 apache apache  4096 Dec  9  2016 ..
drwxrwxr-x  2 apache apache  4096 Jun 15 09:47 ajax
-rw-rw-r--  1 apache apache  1208 Jun 15 09:47 api.php
drwxrwxr-x  2 apache apache  4096 Jun 15 09:47 backup
drwxr-xr-x 10 apache apache  4096 Jun 24 02:02 backup_24_Jun_2017
drwxr-x---  2 apache apache  4096 Jun 25 22:33 config
-rw-rw-r--  1 apache apache 35147 Jun 15 09:47 COPYING
drwxrwxr-x  3 apache apache  4096 Jun 15 09:47 css
drwxrwxr-x  2 apache apache  4096 Jun 15 09:47 imgs
drwxrwxr-x  8 apache apache  4096 Jun 15 09:47 inc
-rw-rw-r--  1 apache apache  1158 Jun 15 09:47 index.php
-rw-rw-r--  1 apache apache  1173 Jun 15 09:47 INSTALL
drwxrwxr-x  2 apache apache  4096 Jun 15 09:47 js
-rw-rw-r--  1 apache apache  2333 Jun 15 09:47 README.md

**Comment by nuxsmin** [comment]
Hello, 

Could you try out setting `installed` tag to 1 within `config.xml` file?

**Comment by anikarunakaran** [comment]
installed tag is set as one already.

 <installed>1</installed>

**Comment by ortizleo** [comment]
Well, works now, but i didn't nothing different...
No upgrade process screen and nothing in event log about the update.
Also, customer accounts color still change their color when logoff/logon (idk if is a problem).

**Comment by anikarunakaran** [comment]
for me, it shows this screen though installed tag set to 1 ...

![image](https://user-images.githubusercontent.com/4487879/27636446-39b4bf70-5c29-11e7-9773-982dd2f7defc.png)


 html]# ls -l
total 88
drwxrwxr-x  2 apache apache  4096 Jun 15 09:47 ajax
-rw-rw-r--  1 apache apache  1208 Jun 15 09:47 api.php
drwxrwxr-x  2 apache apache  4096 Jun 15 09:47 backup
drwxr-xr-x 10 apache apache  4096 Jun 24 02:02 backup_24_Jun_2017
drwxr-x---  2 apache apache  4096 Jun 28 02:55 config
-rw-rw-r--  1 apache apache 35147 Jun 15 09:47 COPYING
drwxrwxr-x  3 apache apache  4096 Jun 15 09:47 css
drwxrwxr-x  2 apache apache  4096 Jun 15 09:47 imgs
drwxrwxr-x  8 apache apache  4096 Jun 15 09:47 inc
-rw-rw-r--  1 apache apache  1158 Jun 15 09:47 index.php
-rw-rw-r--  1 apache apache  1173 Jun 15 09:47 INSTALL
drwxrwxr-x  2 apache apache  4096 Jun 15 09:47 js
-rw-rw-r--  1 apache apache  2333 Jun 15 09:47 README.md
-rw-r--r--  1 apache apache   169 Jun  5 07:41 test.php


config]# pwd
/var/www/html/config
root@xxxxxxxxx:   config]# grep installed config.xml
  <installed>1</installed>

**Comment by anikarunakaran** [comment]
upgradeKey shows empty for my old version and new one, is that the issue here?.

[root@DAVXINXXNC02 config]# grep upgrade /var/www/html/backup_24_Jun_2017/config/config.xml
  <upgradeKey></upgradeKey>
[root@DAVXINXXNC02 config]# grep upgrade config.xml
  <upgradeKey></upgradeKey>
[root@DAVXINXXNC02 config]#

**Comment by nuxsmin** [comment]
Sorry about the upgrade, I've just noticed that upgrading from your version doesn't need a DB upgrade, so the upgrade process won't start.

You only need either to put the config files within the new instance, or replace the old instance files.

**Comment by nuxsmin** [comment]
The installation screen is only shown whenever a database checking fails, so please check out the syspass.log file within the config directory.
