### ISSUE TITLE
wrong documentation for Debian Stretch

### ISSUE THREAD

**Issue by colttt** [nuxsmin/sysPass#653]
Hello,
the documentation said install php5*-things, but php5 is not available in Debian 9 anymore.
Better solution is:
```
apt install apache2 libapache2-mod-php php php-curl php-mysqlnd php-curl php-gd php-json mariadb-server php-ldap
```
or
```
apt install apache2 libapache2-mod-php7.0 php7.0 php7.0-curl php7.0-mysqlnd php7.0-curl php7.0-gd php7.0-json mariadb-server php7.0-ldap
```

**Comment by nuxsmin** [comment]
You're right, I also need to check out that sysPass works fine on Debian 9 (surely yes).

Thanks for the feedback

**Comment by jhowe-uw** [comment]
Works with the following packages on Debian 9

apache2 libapache2-mod-php php php-curl php-mysql php-gd php-json gnupg mariadb-server

php-$NAME links to php7.0-$NAME packages in Debian 9.

I haven't tested with php-ldap yet.

Thanks

**Comment by nuxsmin** [comment]
Thanks for the feedback!!

**Comment by nuxsmin** [comment]
Done
