### ISSUE TITLE
Can't delete category

### ISSUE THREAD

**Issue by ortizleo** [nuxsmin/sysPass#654]
I've imported a CSV file but they create a invalid category (i think is my fault :/), now i can't delete it.
This is the error:
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`accHistory`, CONSTRAINT `fk_accHistory_category_id` FOREIGN KEY (`acchistory_categoryId`) REFERENCES `categories` (`category_id`))

How to fix?

**Comment by nuxsmin** [comment]
Hello, that is so because the category is linked to an account's history, so you need to remove the linked account.

**Comment by ortizleo** [comment]
Hm, removed in "Accounts", then removed on customers and category, works.
Thanks.

**Comment by nuxsmin** [comment]
You're welcome!!

**Comment by andrucha97** [comment]
@nuxsmin Just had the same problem. Is it possible to search for categories in the history? I tryed to search but it didn't worked.
