### ISSUE TITLE
Customers problems

### ISSUE THREAD

**Issue by Youkoulayley** [nuxsmin/sysPass#655]
Some of my users can't see certains customers. But there is not ACL on customers, right ?

**Comment by nuxsmin** [comment]
Surely, it could be related to a DB constraint...

**Comment by mcostagonzalez** [comment]
Hi!

We're also having this very same problem in a fresh install of the latest version. A non admin user cannot see every client and we don't see that an ACL exists.

Regards.

**Comment by nuxsmin** [comment]
Unassigned customers can be seen by everyone, but once it's assigned to an account, it will be only seen be those users which have access to the account.

In next version, you will be able to create global customers, so everyone could use them.

Regards

**Comment by mcostagonzalez** [comment]
Ah ok, now I understand. Thank you so much for clearing it up.

Best regards.

**Comment by tiagosleal** [comment]
I'm having the same issue. Users do not see some customers. Is there a solution to this?
