### ISSUE TITLE
can't upgrade

### ISSUE THREAD

**Issue by radkokeves** [nuxsmin/sysPass#656]
selinux enabled,

in log i can find:

[Fri Jun 30 11:41:38 2017] [error] [client 10.110.17.130] PHP Warning:  unlink(/tmp/df_sum_stat.out): Operation not permitted in /appl/syspass/inc/SP/Core/Task.class.php on line 108, referer: https://lxmvppk401vm/index.php?a=upgrade&type=db
[Fri Jun 30 11:41:38 2017] [error] [client 10.110.17.130] PHP Warning:  unlink(/tmp/FS_stat_problem.out): Operation not permitted in /appl/syspass/inc/SP/Core/Task.class.php on line 108, referer: https://lxmvppk401vm/index.php?a=upgrade&type=db
[Fri Jun 30 11:41:38 2017] [error] [client 10.110.17.130] PHP Warning:  unlink(/tmp/pkglist.out): Operation not permitted in /appl/syspass/inc/SP/Core/Task.class.php on line 108, referer: https://lxmvppk401vm/index.php?a=upgrade&type=db
[Fri Jun 30 11:41:38 2017] [error] [client 10.110.17.130] PHP Warning:  unlink(/tmp/uptime_problem.out): Operation not permitted in /appl/syspass/inc/SP/Core/Task.class.php on line 108, referer: https://lxmvppk401vm/index.php?a=upgrade&type=db

**Comment by radkokeves** [comment]
it is necessary to change:

inc/SP/Core/Task.class.php
inc/SP/Controller/TaskController.class.php

        //$this->dir = Util::getTempDir();
        $this->dir = Init::$SERVERROOT . "/config";

to use by default, or to enhance 
chcon -R -t httpd_sys_rw_content_t <tempdir>

**Comment by nuxsmin** [comment]
Fine...I'll add it in the documentation.

Thanks for your contribution!!

**Comment by nuxsmin** [comment]
Done
