### ISSUE TITLE
exclude backup from backup

### ISSUE THREAD

**Issue by radkokeves** [nuxsmin/sysPass#657]
exclude backup from backup in
inc/SP/Core/Backup.class.php

replace this:
            $archive->buildFromDirectory(Init::$SERVERROOT);
with this:
            $archive->buildFromDirectory(Init::$SERVERROOT,'/^((?!backup).)*$/');

**Comment by nuxsmin** [comment]
You're right, I'll fix it in next release.

Thanks for your contribution!

**Comment by nuxsmin** [comment]
Solved
