### ISSUE TITLE
Trouble with syspass installation

### ISSUE THREAD

**Issue by Canada514** [nuxsmin/sysPass#658]
Hello

I am a new user of centos and I try to install the syspass on a virtual machine. I followed the procedure but it does not work. Then I have help please? I have to get back at my boss this wednesday please help :

1- When I order: 
[root@localhost ~]# wget http://dl.fedoraproject.org/pub/epel/beta/7/x86_64/epel-release-7-0.2.noarch.rpm

I received this answer :
 
--2017-07-03 12:56:46--  http://dl.fedoraproject.org/pub/epel/beta/7/x86_64/epel-release-7-0.2.noarch.rpm
Résolution de dl.fedoraproject.org (dl.fedoraproject.org)... 209.132.181.23, 209.132.181.24, 209.132.181.25
Connexion vers dl.fedoraproject.org (dl.fedoraproject.org)|209.132.181.23|:80...connecté.
requête HTTP transmise, en attente de la réponse...404 Not Found
2017-07-03 12:56:46 ERREUR 404: Not Found.

it same when i write this line: 
[root@localhost ~]# cp sysPass.tar.gz /var/www/html/syspass

i received:
cp: impossible d'évaluer « sysPass.tar.gz »: Aucun fichier ou dossier de ce type

none of these commands below work :

Copy and unzip the sysPass archive in the newly created directory:

cp sysPass.tar.gz /var/www/html/syspass
cd /var/www/html/syspass
tar xzf syspass.tar.gz
Change the owner of ‘syspass/config’ directory. It should be the same user that the web server runs:

chown apache /var/www/html/syspass/config
chmod 750 /var/www/html/syspass/config
Create an change the backup directory owner:

mkdir var/www/html/syspass/backup
chown apache /var/www/html/syspass/backup
Modifying SELinux
In order to allow sysPass to write its own configuration file and backups, we have two choices:

Note
Choose one of the options
Change the SELinux user and target context to make writable the config and backup directories:

chcon -R -t httpd_sys_rw_content_t /var/www/html/sysPass/config/
chcon -R -t httpd_sys_rw_content_t /var/www/html/sysPass/backup/
Disable SELinux by editing ‘/etc/sysconfig/selinux’ file, change the “SELINUX” variable value to “permissive” and reboot your system.

Environment configuration
Open the web browser and point to the URL:

https://IP_OR_SERVER_NAME/syspass/index.php

**Comment by nuxsmin** [comment]
Hello,

Which CentOS version are you running?, You need to set the correct epel repository, because each version uses the one according to the version number.

You also need to download sysPass from github (on releases section).

Regards

**Comment by Canada514** [comment]
Actually i use centos 7 and i download syspass 2.1.11.
How can i install the dowload files ?

Thanks


-------- Message d'origine --------
De : RubénD <notifications@github.com>
Date : 17-07-03 16:14 (GMT-05:00)
À : nuxsmin/sysPass <sysPass@noreply.github.com>
Cc : Adams Ziba <aziba@crosemont.qc.ca>, Author <author@noreply.github.com>
Objet : Re: [nuxsmin/sysPass] Trouble with syspass installation (#658)


Hello,

Which CentOS version are you running?, You need to set the correct epel repository, because each version uses the one according to the version number.

You also need to download sysPass from github (on releases section).

Regards

**Comment by Canada514** [comment]
hello 
any help ?

**Comment by nuxsmin** [comment]
Please, set up epel https://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/ and then follow the steps on sysPass documentation.

I would recommend to use a Debian like distribution, because its simplicity and the needless to configure any additional repositories.

Regards.

**Comment by Canada514** [comment]
Hi,

Thanks for your help it appreciate
I followed the description for the installation but at the end when I open the browser I always receive “The connection failed”
and when I remove https://IP_OR_SERVER_NAME/syspass/index.php<https://ip_or_server_name/syspass/index.php> for http://IP_OR_SERVER_NAME/syspass/index.php
I receive this text below

<?php
/**
* sysPass
*
* @author nuxsmin
* @link http://syspass.org
* @copyright 2012-2017, Rubén Domínguez nuxsmin@$syspass.org
*
* This file is part of sysPass.
*
* sysPass is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* sysPass is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
*  along with sysPass.  If not, see <http://www.gnu.org/licenses/>.
*/

use SP\Controller\MainController;
use SP\Core\Init;
use SP\Core\Session;

define('APP_ROOT', '.');

require APP_ROOT . DIRECTORY_SEPARATOR . 'inc' . DIRECTORY_SEPARATOR . 'Base.php';

if (!Init::checkPostLoginActions() && Session::getAuthCompleted()) {
    $Controller = new MainController();
    $Controller->getMain();
    $Controller->view();
}


How I can make a troubleshooting for know where I make a mistake ?

Thanks

De : RubénD [mailto:notifications@github.com]
Envoyé : 4 juillet 2017 12:03
À : nuxsmin/sysPass <sysPass@noreply.github.com>
Cc : Adams Ziba <aziba@crosemont.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [nuxsmin/sysPass] Trouble with syspass installation (#658)


Please, set up epel https://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/ and then follow the steps on sysPass documentation.

I would recommend to use a Debian like distribution, because its simplicity and the needless to configure any additional repositories.

Regards.

**Comment by nuxsmin** [comment]
That's because the PHP module isn't enabled, so plain text is displayed.

**Comment by Canada514** [comment]
thanks for your help. I was little sick these last day.

**Comment by nuxsmin** [comment]
No worries,  hope you are getting well now ;)
