### ISSUE TITLE
Access Permissions

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#659]
Why is it not possible for normal users to change the Permissions under Access only the Application Admin can do this.

How are normal users than able to give users access or edit rights that are not in the same group like the user itself?

**Comment by nuxsmin** [comment]
Hello,

Access permissions granting can be set through users profiles.

Regards.

**Comment by Goatmaster** [comment]
Okay I got it.
Thank you.

Is it possible to delete the Orphan (user, group...) is the any specific sequence how I have to delete all ?

**Comment by nuxsmin** [comment]
Regarding the orphan items, you could remove them by guessing out where is the item linked to, but they are very often linked to an account's history.

If you try to remove them, an error is logged in the event log, so it will tell where is linked from.

Regards
