### ISSUE TITLE
Request account details by URL parameters

### ISSUE THREAD

**Issue by dmi-tsag** [nuxsmin/sysPass#660]
Hi nuxsmin,
Great application!
I suggest a useful feature to add would be the option to request the account details via URL parameter something like **https://host/syspass/index.php?account=21**.

If you click on a link with this URL it would open the account detail view. Or if you are not logged in, it would open first the login page and then the account details, if the login-user is in the right group / has sufficed rights.

You already have implement a similar feature with the "public links". The problem with this approach in my use-case is 1. that anybody with that link can get the password and 2. the "Expire Time" which have to be updated manually.

What do you think about that?

**Comment by nuxsmin** [comment]
Hi @dmi-tsag 

sorry for the late reply. Regarding your feature request, I'll study it to implement in future releases.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Added to roadmap #422
