### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#662]
Hi, I've tried almost anything I've seen here to try to change the translation.
I've used the command dpkg-reconfigure locales and used only the en_US.UTF-8 and put it as default restarted apache and nothing. Used the en_US.ISO-8859-1 with the same process and nothing. Tried installing both of them with the UTF-8 as default and no change. Do you know what could be the problem?

I'm using Debian 9 with PHP 7.0 and don't know what to do to change the language! Also, I'll help translating the pt-BR language.

**Comment by nuxsmin** [comment]
Hi, did you set it in sysPass config?

**Comment by Fizard** [comment]
I think it was cache, when I rebooted the server and also cleared all the cache it worked. Sorry for taking your time. Just one question, if I update the translation to PT-BR, when will it be available in the software? Also, in translation there is something named TRACK. Is this track as tracking something, a note or something else?

**Comment by nuxsmin** [comment]
I'm glad to know you solved it.

Regarding the language availability, I'll add it whenever you tell me it's ready.

Track is related to the logging attempts tracking system.

Regards

**Comment by yh113** [comment]
Hello,
 Regarding translation I would like to export my fruit from POE and import to sysPass. How can I do it?
Regards

**Comment by Fizard** [comment]
Hi @nuxsmin, I've updated the translation, could you please add it and tell me so I can test it here?
Thanks!

**Comment by nuxsmin** [comment]
Hi @Fizard , I've just pushed a commit with Portuguese translation added, so you can either download or check out it on the demo site (https://demo.syspass.org).

Regards

**Comment by Fizard** [comment]
Hi @nuxsmin. I've tested and it worked. I'm also changing the translation that is wrong in some places, already did a lot of changes yesterday. Thank you.

**Comment by nuxsmin** [comment]
Hi @Fizard that sounds good, please let me know when it's ready to commit those changes.

Regards.

**Comment by nuxsmin** [comment]
Hi @Fizard 

I'm wondering if the Brazilian translation is ready for publishing.

Regards.

**Comment by Fizard** [comment]
Hi @nuxsmin! I've translated all the "wrong" translations I've found in the application. I didn't test everything though, but I think this you can already publish this one to production! I'll test it more later and tell you if I change something more. Thanks.

**Comment by nuxsmin** [comment]
Hi @Fizard that's fine, I've pushed them to the master branch and will be released shortly.

Thanks for your contribution!
