### ISSUE TITLE
TemporaryMasterPassword on login

### ISSUE THREAD

**Issue by pirrimanson2000** [nuxsmin/sysPass#664]
Hi,

I'm testing the demo website and reading the docs. If I haven't understood wrong, everytime that a user  changes his password, has to enter the master/temporary password again.

I'm planning to use syspass at my organization and we are more or less 30 users. I need to configure the LDAP authentication. That means that everyuser can change his password whenever he wants.  Do I have to give them a temporary password manually everytime they needed?

Is there anyway to send them a temporary password automatically?

**Comment by nuxsmin** [comment]
Hi,

Either the master password or the temporary master password need to be used in the very first time a user logs in. If an user changes its password (through LDAP or in-app -using sysPass auth-) will be requested for the previous password.

Be aware that the temporary master password could be used many times until it expires, so you wouldn't need to provide such key for each user.

Regards.
