### ISSUE TITLE
Impossible to import CSV

### ISSUE THREAD

**Issue by pirrimanson2000** [nuxsmin/sysPass#666]
Hi,

I'm trying to import a CSV file, but always get the same error: mime type not supported (octect-stream)

What am I doing wrong?

Example attached.
[testimport.txt](https://github.com/nuxsmin/sysPass/files/1133580/testimport.txt)

**Comment by nuxsmin** [comment]
Hi,

That is because your browser is sending a wrong mime type, so which browser are you using?

Regards

**Comment by pirrimanson2000** [comment]
I tried with Chrome v59 and Firefox v53

**Comment by nuxsmin** [comment]
Hi,

I've just tried it out with success (Firefox v54 Linux):

![captura_245](https://user-images.githubusercontent.com/1775774/28512509-7849908e-7052-11e7-8e95-43ac60e48ff2.png)

**Comment by pirrimanson2000** [comment]
I tried with Firefox under Linux, and It worked. Still the same problem under Windows.

**Comment by nuxsmin** [comment]
So, It could be a file extension association issue, because the OS is sending the wrong mime type to the browser.
