### ISSUE TITLE
Active/Directory parameters not configured

### ISSUE THREAD

**Issue by pirrimanson2000** [nuxsmin/sysPass#667]
Hi,

I'm trying to connect syspass with my active directory. I save all parameters (click on the save button) and then I use the "import users groups", but get an error. In the event log there is an "LDAP parameters not configured" error.

![image](https://user-images.githubusercontent.com/29836124/27991816-40e4e1b4-6483-11e7-9b35-cb5e164933ca.png)

**Comment by nuxsmin** [comment]
Hi, did you set all LDAP parameters and click on save button?, Did the check button work?

BTW, you don't need to import all LDAP users because they will be added on first log in.

Regards

**Comment by pirrimanson2000** [comment]
I did some more test, and now I get the "RDN group" error. I'm not really sure if i'm writing the correct settings for my active directory. This is my AD tree:

DC=aa,DC=mysite,DC=com
   |-OU=my_ou
      |-OU=Users
         |-user1
         |-user2
      |-OU=Groups
        |-group1

And this are my settings:

Base:  OU=my_ou,DC=aa,DC=mysite,DC=com
Group: CN=group1,OU=Groups,OU=my_ou,DC=aa,DC=mysite,DC=com

Error al buscar RDN de grupo
Grupo : (cn=group1)
LDAP ERROR : No such object (32)
LDAP FILTER : (cn=group1)

**Comment by nuxsmin** [comment]
Ok, so your DN base should be one step higher because the group will be searched within it.

Regards

**Comment by pirrimanson2000** [comment]
I already have it that way. Still the same error.

**Comment by nuxsmin** [comment]
Hi,
please use this (https://gist.github.com/nuxsmin/a6b2f2701ce8b78ceadd835adc26756a) gist by filling in with your own connection data and then save it in your web server public path. It should get some LDAP data that could be useful to solve the issue.

Regards

**Comment by pirrimanson2000** [comment]
I have tested your code, and I think I have found the problem. In my organization some OU's of the AD contains spaces and parenthesis (for example: OU=my deparment (city),DC=test,DC=com). In fact, the group i'm setting in the config page is under a OU like that.  The code you gave me doesn't work with that sort of OU's ( ldap_search(): Search: Bad search filter). 

I have tried your code with another OU and group with no spaces/parenthesis, and it worked without problems.

I suposed that was necessary to escape the filter. I used this function that I found in Internet (https://krivokuca.net/2012/08/word-of-advice-escaping-ldap-filter-values-in-php/)

```
function escapeLdapFilter($str = ”) {

// The characters that need to be escape.
//
// NOTE: It’s important that the slash is the first character replaced.
// Otherwise the slash added by other replacements will then be
// replaced as well, resulted in double-escaping all characters
// replaced before the slashes were replaced.
//
$metaChars = array(
chr(0x5c), // \
chr(0x2a), // *
chr(0x28), // (
chr(0x29), // )
chr(0x00) // NUL
);

// Build the list of the escaped versions of those characters.
$quotedMetaChars = array ();
foreach ($metaChars as $key => $value) {
	$quotedMetaChars[$key] = '\\' .
	str_pad(dechex(ord($value)), 2, '0', STR_PAD_LEFT);
}

// Make all the necessary replacements in the input string and return
// the result.
return str_replace($metaChars, $quotedMetaChars, $str);
}
```

Then, in your code, I changed this:

```
  if ($useADS) {
    $userFilter = '(&(|(memberOf=' . $searchGroup[0]["dn"] . ')(groupMembership=' . $searchGroup[0]["dn"] . ')(memberof:1.2.840.113556.1.4.1941:=' . $searchGroup[0]["dn"]. **'))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))';**

  } else {
    $userFilter = '(&(|(memberOf=' . $searchGroup[0]["dn"] . ')(groupMembership=' . $searchGroup[0]["dn"] . '))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))';
  }

```

for this:

```
  if ($useADS) {
    $userFilter = '(&(|(memberOf=' . escapeLdapFilter($searchGroup[0]["dn"]) . ')(groupMembership=' . escapeLdapFilter($searchGroup[0]["dn"]) . ')(memberof:1.2.840.113556.1.4.1941:=' . escapeLdapFilter($searchGroup[0]["dn"]) . '))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))';

  } else {
    $userFilter = '(&(|(memberOf=' . escapeLdapFilter($searchGroup[0]["dn"] ). ')(groupMembership=' . escapeLdapFilter($searchGroup[0]["dn"]) . '))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))';
  }

```
I escaped the $searchBase and $groupName too, **and It worked fine**.

**Comment by nuxsmin** [comment]
Fine...but you're pointing to an article related to LDAP injection so escaping those chars would prevent a security flaw, however according to this https://social.technet.microsoft.com/wiki/contents/articles/5312.active-directory-characters-to-escape.aspx article, no more chars are needed to be escaped.

BTW, I'll review the escaped chars (already done before searching on https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Auth/Ldap/LdapBase.class.php#L691).

Thanks for the feedback!!

**Comment by pirrimanson2000** [comment]
You are welcome.

BTW, I have found a little bug. If you change these settings (and save):

![image](https://user-images.githubusercontent.com/29836124/28751514-db64a15c-7509-11e7-8c93-d665b646c4b7.png)

And then reload the LDAP configuration, they look like this:

![image](https://user-images.githubusercontent.com/29836124/28751527-2df14da8-750a-11e7-8c8a-c499f007c763.png)

**Comment by nuxsmin** [comment]
That's the right behaviour, because those  settings are only used when importing from LDAP (see help tooltip)

Regards

**Comment by nuxsmin** [comment]
Please, could you try out the latest commit?. It should fix this issue by using `ldap_escape()` function (available since PHP 5.6)

Regards

**Comment by pirrimanson2000** [comment]
I tried and it worked!!!

Thank you

Disculpe si soy breve, enviado desde el móvil.

**Comment by nuxsmin** [comment]
Great!!

Disculpado por la brevedad ;)
