### ISSUE TITLE
Can not log in after change password on LDAP account with 2 Factor enable

### ISSUE THREAD

**Issue by efazenda** [nuxsmin/sysPass#668]
Dear Support,

We have an user that have change his password of his account (connected with LDAP) and it as required the master password which is normal in version 1.2.0.19 , but he have 2 factor enabled on his account , now it can not connect to syspass anymore, have you got some tips workarround to fix this ?

Best Regards, Edouard.

**Comment by nuxsmin** [comment]
Hello Edouard,

Which error is being shown?. I haven't got any issue with LDAP and 2fa and, furthermore, the 2fa module hasn't anything related to the user's password.

Regards
