### ISSUE TITLE
Groups from Active Directory

### ISSUE THREAD

**Issue by wszychta** [nuxsmin/sysPass#669]
Hi,

Is there any possibility to map groups from Active Directory to groups in sysPass?
I have successfully integrated all accounts into sysPass, but I don't see possibility to import Active Directory Groups.

My configuration is:
Search Base: OU=XXX,DC=XXX,DV=XXX=DC=com
Group: CN=Employees,OU=Groups,OU=XXX,DC=XXX,DV=XXX=DC=com

All users are members of the group "Employees".

**Comment by nuxsmin** [comment]
Hi,

unfortunately this feature is not yet implemented, but will be in the next version.

Regards.
