### ISSUE TITLE
Not sending mail - syspass 2.1.11

### ISSUE THREAD

**Issue by ortizleo** [nuxsmin/sysPass#670]
Hi, syspass here is not sending mails, i have same config on one similar service and works fine.
Tested with "echo "something"|mailx mail@mail.com" and works fine too.

What can i do? Maybe some php module?

**Comment by ortizleo** [comment]
hmmm, two more things:
1. Favorite filtering won't stay selected when logoff/logon
2. Custumer color change when logoff/logon

**Comment by ortizleo** [comment]
Email problem is SELINUX fault...
This fix: setsebool -P httpd_can_sendmail 1

**Comment by nuxsmin** [comment]
I'll add a note in the documentation.

Thanks for the feedback!

**Comment by mr-gosh** [comment]
how is this debuggable? we have the same problem but i can't identify the source of the problem - any hints?
