### ISSUE TITLE
Secundary groups not working

### ISSUE THREAD

**Issue by ortizleo** [nuxsmin/sysPass#672]
Hello.
Secundary group is not working like we expect i thing...

How i am testing:
On tab USERS:
- User Leonardo is in group "support" and profile "support"
- This user is on group "SUPPORT - LINUX" as secundary group.

On a item:
-  main group: admins 
-  Groups: "SUPPORT - LINUX" 

But when I log with user leonardo, i can't see the item in "support - linux" group,.
Itens in "support" group (that is the user primary group) is OK.

**Comment by ortizleo** [comment]
Enable Secondary groups access, works now.

**Comment by nuxsmin** [comment]
I'm glad to hear that it works fine.

Thanks for the feedback!
