### ISSUE TITLE
Database Backup

### ISSUE THREAD

**Issue by Goatmaster** [nuxsmin/sysPass#673]
What rights do I need to backup the database with mysqldump ?

I used _select_ and _lock tables_ in an older version but it seems like that this is not enough anymore.

**Comment by ortizleo** [comment]
Try this:
GRANT SELECT, LOCK TABLES, SHOW VIEW, EVENT on *.* TO 'USER'@localhost IDENTIFIED BY "PASSWORD";
look mysqldump-secure, you can easy encrypt your backup.

**Comment by Goatmaster** [comment]
Thank you I will try it.

Of course I am already using encrypted backups ;)

**Comment by nuxsmin** [comment]
Thanks for your contribution and feedback!
