### ISSUE TITLE
LDAP user import still not working

### ISSUE THREAD

**Issue by ku16610** [nuxsmin/sysPass#675]
I have the same problem that everyone seems to get importing , it appears to import but when i go to the event log it shows 0/6 users imported.

I've looked at the previous threads and none of the fixes from there have worked, I'm running the latest released version of syspass.

I have changed the attribute mapping to every conceivable option but none have worked,
We are running windows server 2016.
Ldap bind seems fine as it lists all the users correctly when i click the check bottum just never imports anything , Would be nice to allow import from the check ldap button since it gives you a list of users it sees , why not add a checkbox next to each one and a option saying import selected users now :)

**Comment by nuxsmin** [comment]
Hello.

The user import, as said in other threads, won't work if either the user name or login attributes are blank, so it's most likely that you set a wrong attribute combination. As sys admin you need to know which attributes are needed for that process by simply checking out the ADS schema with MMC AD console.

I know the process could be improved but it will require some time to do it (I'm the only developer). All my efforts are put on make sysPass setup and usage easy.

BTW, be aware that you don't need to import every LDAP user because sysPass will add them on their very first login setting he default group and profile.

Regards

**Comment by ku16610** [comment]
Yes I have these fields filled out perfectly that’s why it only tries to import the 6 users in the specific group I’ve chosen. As for the one dev thing I’ll check out the project an see if I can help you out it’s a really nice tool you’ve created and it deserves to be supported.

And yeah I will check the schema when I get back to work tommorow but surely ad is preety standard with its attributes from a default install though I did try all the options possible in the ldap settings page and it made no real difference as to the outcome.


Kind regards

Richard

**Comment by nuxsmin** [comment]
Please check out this gist https://gist.github.com/a6b2f2701ce8b78ceadd835adc26756a and let me know which attributes are filled in from LDAP.

Regards

**Comment by ku16610** [comment]
Hi , yeah sure I’ll run it Tomorrow when I’m in the office.

Thank you for the kind help.

Kind regards 

Richard

**Comment by nuxsmin** [comment]
Hello, I'm wondering if it worked and how many results did you get.

Regards

**Comment by ku16610** [comment]
Hi yeah I did but I’ve been sent on a job in Scotland for the week I’m a field engineer you see normally so let me get back to you Monday next week when I’m back in office/ uk 
Kind regards

Richard

**Comment by nuxsmin** [comment]
Fine, have a nice week in that nice country (I was there last year).

Kind regards.

**Comment by nuxsmin** [comment]
Hi, how're you doing?, did you get it?

Kind regards

**Comment by ku16610** [comment]
Yeah it lists all my users fine 
Got some other probs though anyway for some reason if I add a user or a account it hangs up for a while like 1 /2 mins

**Comment by nuxsmin** [comment]
Umm, are email notifications active?. That's because everytime you add either an account or any item, it'll send an email notification.

**Comment by ku16610** [comment]
Hi Rubén,

Thanks that fixed the problem , it was indeed email notifications which 
ar'nt a major requirement for us.

kind regards and hope your having a good day :)


richard

**Comment by nuxsmin** [comment]
Great!! Have a nice day too!

Kind regards
