### ISSUE TITLE
Active Directory - Check only finds a few users

### ISSUE THREAD

**Issue by fone** [nuxsmin/sysPass#679]
I can't seem to figure out why when using the "check" tool, it'll only find a few users in my forest...
I've made about 10 users a member of a "syspass_user" security group, which is the Group I setup for syspass.

But at max it will only return 3 users to import. If I remove the group from 1 of those 3 and re-run the tool, it'll return 2 users.

Any idea where I might look to correct this? thanks

**Comment by fone** [comment]
https://github.com/nuxsmin/sysPass/issues/537

**Comment by fone** [comment]
Well I solved my issue by adding my syspass user to the "Account Operators" group. I found reference to that on a Cisco forum. https://supportforums.cisco.com/discussion/11568681/ldap-account-permission

**Comment by nuxsmin** [comment]
Nice to hear you solved it. Many people could find this useful because some ADS implementations does not allow to query accounts using a basic user account.

I'll add a note to the doc.

Thanks for the feedback!!
