### ISSUE TITLE
syspass login takes longer

### ISSUE THREAD

**Issue by anikarunakaran** [nuxsmin/sysPass#681]
Hi,
I have observed that, out syspass login takes longer everytime and if we try syspass demo given in "https://demo.syspass.org/index.php"  works much faster...

![image](https://user-images.githubusercontent.com/4487879/28661886-e217a6ce-72d5-11e7-96fd-6521991e8090.png)

could you please let me know how to improve login time?

thanks,

**Comment by nuxsmin** [comment]
Hi, are you using LDAP auth?

regards

**Comment by anikarunakaran** [comment]
yes, i have configured LDAP authentication, but currently we are using admin user(not LDAP user) to login and its taking longer.

**Comment by nuxsmin** [comment]
Although you're using the admin user, it will check for every user in LDAP and then fallback to the database backend. You could check it out on sysPass event log.

**Comment by nuxsmin** [comment]
...So the current delayed login would be caused by an LDAP checking which takes longer time. If this time is so long (> 5 sec) , you could check out for some DNS issues (unavailable DNS servers, etc).
