### ISSUE TITLE
Unable to delete user

### ISSUE THREAD

**Issue by anikarunakaran** [nuxsmin/sysPass#684]
Hi,

Please find the error message while trying to delete user from syspass.

Error while queryingSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`pass`.`accHistory`,CONSTRAINT `fk_accHistory_users_edit_id` FOREIGN KEY (`acchistory_userEditId`) REFERENCES `usrData` (`user_id`)) (0)SQL : 'DELETE FROM usrData WHERE user_id = ? LIMIT 1'
--

**Comment by nuxsmin** [comment]
Hi, it means that you cannot delete a user because its being used in an account's history record, so probably that user modified that account in some time in the past. You need to delete that record in "Items and Customizations > Accounts (H)".

**Comment by Blai01** [comment]
Hi,

I am having the same issue:

Integrity constraint
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`Account`, CONSTRAINT `fk_Account_userEditId` FOREIGN KEY (`userEditId`) REFERENCES `User` (`id`))

I have deleted all rows on ACCOUNTS(H) and still see the error when trying to delete a disabled user.

**Comment by nuxsmin** [comment]
@Blai01 hi, your issue is related to an user id set as an editor by an account.

If this user is removed you wouldn't be able to get who modified an account in the past and every field in which this id was set would become null. That is because the integrity reference is enforced.

**Comment by duven87** [comment]
Hola nuxsmin,Is there no way to delete users in this case?

I don't mind losing the information of when an account was modified if it is related to the deleted user.

**Comment by vazromju** [comment]
what I have done has been update the fields: userEditID and userID in table Account to another valid userID and I have been able to delete the user.
