### ISSUE TITLE
Can't login after LDAP user password change

### ISSUE THREAD

**Issue by tiagosleal** [nuxsmin/sysPass#686]
After changing my password in ldap, I can no longer login to syspass with the new password, only with the old password.

System info:

sysPass version	2.1 (2.1.9.17050401)
Database	SERVER_VERSION : 5.5.50-MariaDB 
CLIENT_VERSION : mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $ 
SERVER_INFO : Uptime: 6604190 Threads: 1 Questions: 60180 Slow queries: 0 Opens: 183 Flush tables: 2 Open tables: 74 Queries per second avg: 0.009 
CONNECTION_STATUS : Localhost via UNIX socket 
Name: syspass@localhost
PHP	Version: 5.6.30 
Extensions: Core, date, ereg, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, ldap, exif, mcrypt, mysqlnd, PDO, Phar, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mysql, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, json, zip, mhash 
Used Memory: 3072 KB 
User: root
Server	Apache/2.4.6 () OpenSSL/1.0.1e-fips PHP/5.6.30
Configuration Backup	Mon, 31 Jul 2017 17:49:46 -0300
Language help_outline
Tells whether the language is available or not.

If it is not installed, you would need install the right operating system locales. More info at Wiki.

en_US.utf8
Encrypted Session help_outline
Tells whether the session data are encrypted in the server or not

No
Loaded Plugins

**Comment by nuxsmin** [comment]
Hello, it's weird, because there isn't any issue related to that and we're (~50 users) using it through LDAP every day.

Please upgrade to the latest version because there were many bug and security fixes.

Regards

**Comment by tiagosleal** [comment]
Okay, so I'll do more tests. 

Thanks

**Comment by nuxsmin** [comment]
@halfmoon79 could you check out sysPass event log?, and what about `syspass.log` file (within `config` directory?

**Comment by halfmoon79** [comment]
@nuxsmin i check new version and give feedback...

**Comment by halfmoon79** [comment]
Unfortunately, the error persists.

I have updated the last version. In the user account I have not changed.
The users are read from the LDAP group "app_syspass".

Can still test something?

Log in Syspass:

669 | 2017-08-15 09:49:29 | ERROR | Anmelden |   | 192.***.***.*** | Fehlerhafte AnmeldungTyp : authBrowserTyp : authLdapBenutzer : username
-- | -- | -- | -- | -- | -- | --
668 | 2017-08-15 09:49:29 | ERROR | bind |   | 192.***.***.*** | Nutzer in Gruppe verifiziertLDAP-Verbindungsfehler (BIND)LDAP ERROR : Invalid credentials (49)LDAP DN : CN=User Namer,OU=***,OU=**,OU=*******,DC=domain,DC=de
667 | 2017-08-15 09:49:29 | INFO | searchUserInGroup |   | 192.***.***.*** | Nutzer in Gruppe verifiziert
666 | 2017-08-15 09:48:56 | ERROR | Anmelden |   | 192.***.***.*** | Typ : authBrowserTyp : authLdapLDAP Server : ldap://domain.de
665 | 2017-08-15 09:48:56 | INFO | searchUserInGroup |   | 192.***.***.*** | Nutzer in Gruppe verifiziert

syspass.log: (after login fail)
2017-08-15 09:48:56 - Integrity check failed.

**Comment by halfmoon79** [comment]
Now it works. i have tested withe 2 accounts.

Regards

**Comment by nuxsmin** [comment]
Great, so is it working fine now?

Kind regards

**Comment by halfmoon79** [comment]
It works. The problem has been solved.

Best regards

**Comment by nuxsmin** [comment]
Nice, thanks for the feedback!
