### ISSUE TITLE
Unable to install the script

### ISSUE THREAD

**Issue by sikas89** [nuxsmin/sysPass#687]
Hello nuxsmin,

I see you made a lot of progress on the script ... I haven't been using it for a while, and just remembered it again as I needed a password repository. I downloaded the latest version, and uploaded it to my web server. However, it is not installing .. I get the error below:

> Unable to check the sysPass user (admin)
> Please, check the DB connection user rights

Kindly check it and advise.

**Comment by nuxsmin** [comment]
Hello @sikas89,

I'm glad that you are going to use sysPass again ;)

That error is most likely because the MySQL credentials provided are not granted to create the sysPass database user.

Regards

**Comment by sikas89** [comment]
Hello @nuxsmin,

I've checked the DB Permissions for the user .. It has full privileges .. Is there something I might be missing?
,

**Comment by nuxsmin** [comment]
Hello,

the failed db query is `SELECT COUNT(*) FROM mysql.user WHERE user = ? AND host = ?` so may be some issue related to the db permissions, since some web hostings do not allow to query that database/table `mysql.user`. Could you check it out?.

**Comment by sikas89** [comment]
Okay .. It seems that I don't have access to the database/table `mysql.user` .. I tried to execute the query you provided right from the DB, and got an error

`#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '? AND host = ?' at line 1`

So, I decided to go with `Hosting Mode`, but still doesn't work as intended ..

When I try to add a new `Account`, I get a forbidden error

I can create the Customers and Categories using Google Chrome, but can't add any account!

`There was an error
Forbiddenerror`

**Comment by nuxsmin** [comment]
`Hosting Mode` is only intended for installing sysPass :)

It seems that your web server has some restrictions on sysPass files. Please check out sysPass directory/files permissions.

**Comment by sikas89** [comment]
@nuxsmin,

How should I set the permissions?

**Comment by sikas89** [comment]
Ok, it is working now without modifying anything! Nothing in the logs showing any failures!

**Comment by nuxsmin** [comment]
Really weird! :)

**Comment by nuxsmin** [comment]
Thanks for the feedback!
