### ISSUE TITLE
Issue with Cookies . i cannot login anymore

### ISSUE THREAD

**Issue by Canada514** [nuxsmin/sysPass#689]
<img width="735" alt="error" src="https://user-images.githubusercontent.com/29872454/28982383-978ed970-7923-11e7-814e-68c2c084f22c.png">

I finally installed Syspass on debian. I logged in and I did create some accounts (password) and a few users.
To test their account I log off from my admin account and try to log in with the users creates. I confirmed the account with the master key but since then I have started to have this message in picture. I have checked and cookies are enabled on firefox. I did a search and tells me to disable encryption but I do not want to disable it because it's necessary for the company so I would like to know how I can solve this problem?

Note that during 3 days I connected well with my admin account without problem but that since this morning after what I described above I can not get any more because I have the same error message.

Thank you

**Comment by nuxsmin** [comment]
Hello, don't worry about the session encryption, because your data will be encrypted anyway. That encryption is related to the session data and not to accounts or user data instead.

That issue could be caused because your company is using a proxy which is filtering some cookies or headers data.

Kind regards

**Comment by nuxsmin** [comment]
You can disable it by modifying the `config.xml` file.

**Comment by Canada514** [comment]
Hello

Thanks for your answer. I was already exit
 my office for the day. I will try it monday morning.

I understand your explication and i am little more worried about that. Résolu thanks.
I Will cet back To you monday for sure.






Envoyé depuis mon téléphone intelligent Samsung Galaxy.


-------- Message d'origine --------
De : RubénD <notifications@github.com>
Date : 17-08-04 18:29 (GMT-05:00)
À : nuxsmin/sysPass <sysPass@noreply.github.com>
Cc : Adams Ziba <aziba@crosemont.qc.ca>, Author <author@noreply.github.com>
Objet : Re: [nuxsmin/sysPass] Issue with Cookies . i cannot login anymore (#689)


You can disable it by modifying the config.xml file.

**Comment by Canada514** [comment]
hello 

I opened my config.xml file and put the line **** in comment. Afterwards I restarted the virtual machine but the problem is always the. 
You will find below the contents of my config.xml file 

PS: Note that currently the program is on a virtual machine in my pc and when everything is functional I will transfer it to our network serve   

any idea or line i have to modify ? 
******************************************************************************************************
<?xml version="1.0" encoding="utf-8"?>
<config>
  <accountCount>12</accountCount>
  <accountFullGroupAccess>0</accountFullGroupAccess>
  <accountLink>1</accountLink>
  <accountPassToImage>0</accountPassToImage>
  <backup_hash></backup_hash>
  <checkUpdates>0</checkUpdates>
  <checknotices>0</checknotices>
  <configDate>1501858073</configDate>
  <configHash>0163a8e2aac323790bdbdbe4dbe22e3d</configHash>
  <configSaver>admin</configSaver>
  <configVersion>211117061503</configVersion>
  <dbHost>localhost</dbHost>
  <dbName>syspass</dbName>
  <dbPass>FbefO$})WIu7&amp;2yn</dbPass>
  <dbPort>3306</dbPort>
  <dbSocket></dbSocket>
  <dbUser>sp_admin</dbUser>
  <debug>0</debug>
  <demoEnabled>0</demoEnabled>
  <dokuwikiEnabled>0</dokuwikiEnabled>
  <dokuwikiNamespace></dokuwikiNamespace>
  <dokuwikiPass></dokuwikiPass>
  <dokuwikiUrl></dokuwikiUrl>
  <dokuwikiUrlBase></dokuwikiUrlBase>
  <dokuwikiUser></dokuwikiUser>
#   ****
  <export_hash></export_hash>
  <filesAllowedExts>
    <item type="filesAllowedExts">PDF</item>
    <item type="filesAllowedExts">JPG</item>
    <item type="filesAllowedExts">GIF</item>
    <item type="filesAllowedExts">PNG</item>
    <item type="filesAllowedExts">ODT</item>
    <item type="filesAllowedExts">ODS</item>
    <item type="filesAllowedExts">DOC</item>
    <item type="filesAllowedExts">DOCX</item>
    <item type="filesAllowedExts">XLS</item>
    <item type="filesAllowedExts">XSL</item>
    <item type="filesAllowedExts">VSD</item>
    <item type="filesAllowedExts">TXT</item>
    <item type="filesAllowedExts">CSV</item>
    <item type="filesAllowedExts">BAK</item>
  </filesAllowedExts>
  <filesAllowedSize>1024</filesAllowedSize>
  <filesEnabled>1</filesEnabled>
  <globalSearch>1</globalSearch>
  <httpsEnabled>1</httpsEnabled>
  <installed>1</installed>
  <ldapAds>0</ldapAds>
  <ldapBase>ou=DRI,ou=ADM,o=college</ldapBase>
  <ldapBindPass>j1bcnqsb$</ldapBindPass>
  <ldapBindUser>cn=redmineldap,o=ldap_users</ldapBindUser>
  <ldapDefaultGroup>2</ldapDefaultGroup>
  <ldapDefaultProfile>2</ldapDefaultProfile>
  <ldapEnabled>1</ldapEnabled>
  <ldapGroup></ldapGroup>
  <ldapProxyUser></ldapProxyUser>
  <ldapServer>nldap.crosemont.qc.ca</ldapServer>
  <ldapUserattr></ldapUserattr>
  <logEnabled>1</logEnabled>
  <mailAuthenabled>0</mailAuthenabled>
  <mailEnabled>0</mailEnabled>
  <mailFrom></mailFrom>
  <mailPass></mailPass>
  <mailPort>25</mailPort>
  <mailRequestsEnabled>0</mailRequestsEnabled>
  <mailSecurity></mailSecurity>
  <mailServer></mailServer>
  <mailUser></mailUser>
  <maintenance>0</maintenance>
  <passwordSalt>993a71bea158b82dedc61a51d7faf60222dc394a9db2cf171bcf9388d8d5</passwordSalt>
  <proxyEnabled>0</proxyEnabled>
  <proxyPass></proxyPass>
  <proxyPort>8080</proxyPort>
  <proxyServer></proxyServer>
  <proxyUser></proxyUser>
  <publinksEnabled>0</publinksEnabled>
  <publinksImageEnabled>0</publinksImageEnabled>
  <publinksMaxTime>600</publinksMaxTime>
  <publinksMaxViews>3</publinksMaxViews>
  <resultsAsCards>0</resultsAsCards>
  <sessionTimeout>-1200</sessionTimeout>
  <siteLang>fr_FR</siteLang>
  <siteTheme>material-blue</siteTheme>
  <syslogEnabled>0</syslogEnabled>
  <syslogPort>514</syslogPort>
  <syslogRemoteEnabled>0</syslogRemoteEnabled>
  <syslogServer></syslogServer>
  <upgradeKey></upgradeKey>
  <wikiEnabled>0</wikiEnabled>
  <wikiFilter></wikiFilter>
  <wikiPageurl></wikiPageurl>
  <wikiSearchurl></wikiSearchurl>
</config>

**Comment by Canada514** [comment]
hello ! any update ? 

thanks

**Comment by nuxsmin** [comment]
Is there any message in syspass.log file (within config directory)?

Does it occur on the sysPass demo site with the same browser? Https://demo.syspass.org

**Comment by Canada514** [comment]
Thanks for your answer 
1- I make a command on my terminal to have the log of syspass and I put it in attached file.


[syspass_log.docx](https://github.com/nuxsmin/sysPass/files/1209209/syspass_log.docx)

2- When i try to connect on demo with the same browser it's working perfectly.

**Comment by nuxsmin** [comment]
It seems ok.

Is there any messages in sysPass event log? (you need to log into the app). Please log in with a non-ldap user.

Regards

**Comment by Canada514** [comment]
I can't login to syspass. My issue is that.
When i try To login to syspass i receive a cookies error.
I use only the admin account not a ldap users.

Thanks



Envoyé depuis mon téléphone intelligent Samsung Galaxy.


-------- Message d'origine --------
De : RubénD <notifications@github.com>
Date : 17-08-08 17:17 (GMT-05:00)
À : nuxsmin/sysPass <sysPass@noreply.github.com>
Cc : Adams Ziba <aziba@crosemont.qc.ca>, Author <author@noreply.github.com>
Objet : Re: [nuxsmin/sysPass] Issue with Cookies . i cannot login anymore (#689)


It seems ok.

Is there any messages in sysPass event log? (you need to log into the app). Please log in with a non-ldap user.

Regards

**Comment by Canada514** [comment]
Hello M.nuxsmin

In your opinion, should I restart the installation at zero ?

**Comment by nuxsmin** [comment]
That is a warning message, you should be concerned about it, because the app will work fine while not enabling session encryption (not needed in most cases).

Could you check out your browser cookies for that page?. There should be a `PHPSESSID` named cookie.

**Comment by Canada514** [comment]
Hi

In cookie folder i have this line :
127.0.0.1     PHPSESSID

So how if i don’t need session encryption how i can disable this ?
Why its working for few days and suddenly stop working and gave this warning message ?


thanks

De : RubénD [mailto:notifications@github.com]
Envoyé : 10 août 2017 02:15
À : nuxsmin/sysPass <sysPass@noreply.github.com>
Cc : Adams Ziba <aziba@crosemont.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [nuxsmin/sysPass] Issue with Cookies . i cannot login anymore (#689)


That is a warning message, you should be concerned about it, because the app will work fine while not enabling session encryption (not needed in most cases).

Could you check out your browser cookies for that page?. There should be a PHPSESSID named cookie.

**Comment by nuxsmin** [comment]
Hi, that cookie is needed for PHP session, but the encryption cookie is not set, so you're not using it.

Please check out for a request for a file called `getEnvironment.php` within the browser console (F12 > Network tab), this request should return a response with some porperties. Please let me know which is the value of `cookies_enabled` property.

Regards

**Comment by Canada514** [comment]
Thanks for your help !
I make a new installation and its ok for now
I appreciate your help.

De : RubénD [mailto:notifications@github.com]
Envoyé : 21 août 2017 02:08
À : nuxsmin/sysPass <sysPass@noreply.github.com>
Cc : Adams Ziba <aziba@crosemont.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [nuxsmin/sysPass] Issue with Cookies . i cannot login anymore (#689)


Hi, that cookie is needed for PHP session, but the encryption cookie is not set, so you're not using it.

Please check out for a request for a file called getEnvironment.php within the browser console (F12 > Network tab), this request should return a response with some porperties. Please let me know which is the value of cookies_enabled property.

Regards

**Comment by nuxsmin** [comment]
That sounds great...thanks for the feedback!!

Regards

**Comment by Jan-Mas** [comment]
Hi Nuxsmin, I have the same Problem.

It works perfekt for some days and now I get the same error message.

Cookies enabled (ajax/ajax_getEnvironment.php)
config: <encryptSession>0</encryptSession>
Webserver in lokal lan » no proxy


there is a PHP warning in error.log:
touch(): Unable to create file /var/www/html/.../inc/../config/syspass.log because Permission denied in /var/www/html/.../inc/SP/Core/Init.class.php on line 286

The config folder has 750 and www-data as its owner.

Any ideas?

Thanks for your great tool!

Jan

**Comment by nuxsmin** [comment]
Hi @Jan-Mas

Regarding the file permissions, are you running selinux on a CentOS server?

Some debug information is logged into syspass.log file which would be useful to find out the root of the issue.

Regards

**Comment by Jan-Mas** [comment]
Hallo Nuxsmin,

in syspass.log:
---------------------------------------------------------------------------
2018-02-19 19:44:40 - Error en la consulta
No es posible conectar con la BD (0)
Caller 1: SP\Storage\DB\logDBException
Caller 2: SP\Storage\DB\getResults
Caller 3: SP\Storage\DB\getResultsArray
Caller 4: SP\Mgmt\Plugins\Plugin\getEnabled
Caller 5: SP\Core\Plugin\PluginUtil\getEnabledPlugins
2018-02-19 19:44:40 - SQL : SELECT plugin_name FROM plugins WHERE BIN(plugin_enabled) = 1
2018-02-19 19:44:40 - Action: getResultsArray -- Description: Error en la consulta
No es posible conectar con la BD (0) -- Details: SQL : SELECT plugin_name FROM plugins WHERE BIN(plugin_enabled) = 1
2018-02-19 19:50:19 - SQLSTATE[HY000] [1045] Access denied for user 'XXXXXXX'@'localhost' (using password: YES)
2018-02-19 19:50:19 - 0
2018-02-19 19:50:20 - Rollback
2018-02-19 19:50:31 - Action: Configuración -- Description: Modificar configuración -- Details: 
2018-02-19 19:50:34 - Action: Configuración -- Description: Modificar configuración -- Details: Parámetro : version
Valor : 211517101701
2018-02-19 19:50:34 - Action: Configuración -- Description: Modificar configuración -- Details: Parámetro : config_backup
2018-02-19 19:50:34 - Action: Configuración -- Description: Modificar configuración -- Details: Parámetro : config_backupdate
Valor : 1519066234
2018-02-19 19:50:56 - Decryption error
2018-02-19 20:18:46 - Decryption error
2018-02-19 20:22:32 - Decryption error
2018-02-19 20:23:22 - Decryption error
2018-02-19 20:23:32 - Decryption error
2018-02-19 22:10:38 - Decryption error
2018-02-26 13:24:31 - Generating a new session key.
---------------------------------------------------------------------------

I think on this 19th it worked. Mmm ...
---------------------------------------------------------------------------
Some server information for you: 
The "Server" is a Raspbian 9.0 with Apache/2.4.25
10.1.23-MariaDB
PHP-Version: 7.0.19-1
---------------------------------------------------------------------------

apache error.log:
---------------------------------------------------------------------------
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mysql.so' - /usr/lib/php/20151012/mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
[Fri Mar 02 06:25:02.891552 2018] [mpm_prefork:notice] [pid 574] AH00163: Apache/2.4.25 (Raspbian) configured -- resuming normal operations
[Fri Mar 02 06:25:02.891624 2018] [core:notice] [pid 574] AH00094: Command line: '/usr/sbin/apache2'
---------------------------------------------------------------------------


Thank you very much for your help!

regards
Jan

**Comment by nuxsmin** [comment]
Hello @Jan-Mas 

It seems that the user isn't allowed to access to sysPass database. Have you recently changed any db configuration?

Regards

**Comment by Jan-Mas** [comment]
Hallo,

no I don't think so but I not shure anymore. I tried to restore the backup on another server. Maybe I set a new password in the wrong phpmyadmin tab. To be shure I tried to set a new password without success. If it could not connect the Error message is

No es posible conectar con la BD
Compruebe los datos de conexión 

(I tried a wrong DB User). Only the User in the config is needed, right? Or does it matter if there are more users for testing?

**Comment by nuxsmin** [comment]
@Jan-Mas the dbuser and dbpass in config.xml file are needed to be set in MySQL, so you need to create the same user and pass in the db. If you want, the db username and password can be changed, but be aware that the config.xml file needs to be updated.

Regards

**Comment by Jan-Mas** [comment]
Hallo nuxmin,

yes the mysql user/password is written in the config.xml correctly. The mysql user has full rights to the database. Mmm ... 

Are the rights correct?

![rights](https://user-images.githubusercontent.com/36881196/36982468-39594eca-2090-11e8-8a5c-f91efab777da.png)
![rights2](https://user-images.githubusercontent.com/36881196/36982470-3981cc6a-2090-11e8-942c-01991eb0a11c.png)

**Comment by nuxsmin** [comment]
Hello @Jan-Mas , files and directories permissions are ok, I meant about database user permissions.

Regards

**Comment by Jan-Mas** [comment]
Hi nuxmin, sorry for the delay. I wrote it before the screenshot. There ist a DB user for the syspass DB with full right to the DB syspass and the user and passwort is correctly written in the config.xml.

I have no idea anymore, do you?

Kind Regards!

**Comment by nuxsmin** [comment]
@Jan-Mas great news! 

The sysPass database uses its own user to connect and perform queries. That error is related to database views, so if you restored the sysPass database you would have needed to change the views definer since it's restored using the last user which created it.

Regards.

**Comment by massimomatricardi** [comment]
I have installed the version 2.1.16 and I find the same problem described above.
I cannot use sysPass with a WARNING message "Cookies Disable: The Application won't work properly"

**Comment by nuxsmin** [comment]
@massimomatricardi I know it could be a hassle, but it could be caused by a reverse proxy. Did you enable session encryption option?

Regards
