### ISSUE TITLE
Syntax error on account edit

### ISSUE THREAD

**Issue by Chefkeks** [nuxsmin/sysPass#69]
When I edit an account and e.g. change the customer from "test" to "something-else" or so it gives out an syntax error:

![image](https://cloud.githubusercontent.com/assets/2871833/4438979/11966300-47b3-11e4-9c32-6cd3ee60fea8.png)

Error log:

[Mon Sep 29 10:25:10.529587 2014] [php5:error] [pid 16695] [client XXXXXXXXX] PHP Warning:  Invalid argument supplied for foreach() in /XXXXXXXXX/syspass/inc/groups.class.php on line 392, referer: http://XXXXXXXXX/syspass/index.php

[Mon Sep 29 10:25:10.532812 2014] [php5:error] [pid 16695] [client XXXXXXXXX] PHP Warning:  Invalid argument supplied for foreach() in /XXXXXXXXX/syspass/inc/users.class.php on line 414, referer: http://XXXXXXXXX/syspass/index.php

Version is 1.1-rc1 (latest from August)

My setup:
Apache/2.4.6 (Linux/SUSE)
MySQL: 5.6.12
PHP: 5.6.0

**Comment by nuxsmin** [comment]
Hi how are you doing?, I wonder if this issue is still present.

Thanks

Kind regards

**Comment by Chefkeks** [comment]
Hey, everything fine here. Great to see some of the issues finally been fixed. Haven't used syspass since I created the issues here at github. Going to test it again next week or in 2/3 weeks (based on my schedule / work) ;)

Cheers,
Michael

**Comment by nuxsmin** [comment]
Hi, I hope you find it useful.

Cheers,
Rubén
