### ISSUE TITLE
Unable to create customers or categories on MS Edge

### ISSUE THREAD

**Issue by sikas89** [nuxsmin/sysPass#692]
Hello @nuxsmin,

I've installed SysPass on my Lab until it I'm able to install on my production server. Now I'm facing an issue. I'm unable to create customers or categories at all .. This means I can't add any entry.

I'm currently using Microsoft Edge.

**Comment by sikas89** [comment]
@nuxsmin,

Ran a test from Google Chrome, seems to be working fine .. So, the issue is with Microsoft Edge .. Can you take a look at it? I prefer to use Edge as it is consuming less resources than any other browser

**Comment by nuxsmin** [comment]
@sikas89 unfortunately Edge has not been well tested, so there would be some issues. I'll check it to find out a working solution.

**Comment by smokecatcher** [comment]
@nuxsmin I am having the same issue in Internet Explorer 11. I click the (+) button and the floating dialog opens to add whatever object I am trying to add (user, customer, category, etc), I fill in the red required fields, click the green "save" icon at the bottom of the floating dialog...nothing happens. On Chrome same steps close the floating dialog and save the object with a green success banner at top. This is a default install of IE 11. I have tried setting all security to low, enabling pretty much everything, disabling the popup blocker, etc. Nothing works. I have the same problem with your Demo site.

**Comment by nuxsmin** [comment]
Thanks @smokecatcher I'll try to find out what could be happening. 

You may think I'm not interested on IE/Edge, but actually it's a bit tough for me to test on these browsers, since I mainly work on Linux and the windows virtual machines I've set up are quite old (windows 7 in my PC), so I need to deploy a windows 10 VM to try it out.

BTW, I'm committed to get it!

Kind regards

**Comment by nuxsmin** [comment]
Unfortunately, it's an IE bug:

https://stackoverflow.com/questions/20149751/ie11-only-submit-bug#20218025

It seems that button tag implementation is buggy and doesn't accept some attributes
