### ISSUE TITLE
Another issue when creating Account

### ISSUE THREAD

**Issue by sikas89** [nuxsmin/sysPass#694]
Hello @nuxsmin,

Another issue found .. As you may know, I have two setups now for the SysPass .. 

1) Localhost (Windows 10, Apache, PHP v5.6.25, MySQL v5.7.14) .. Full Installation
2) Hosting (Linux *don't know the distro*, PHP v7, MySQL v10.0.3) .. Hosting Mode

When I create an Account, I add IPs for internal servers/devices .. 

On localhost, it accepts the IP with http/https prefix. But on the hosting server, it gives a forbidden error

```
There was an error
Forbiddenerror
```

As usual, I checked the Event Log, and nothing there to indicate this error

**Comment by nuxsmin** [comment]
Hello @sikas89

As I understand, that issue is related to the hosting installation, isn't it?

If so, it could be due to your hosting is filtering out some requests (mine does it), so there are some files that cannot be retrieved from an Ajax request. Please take a look to the browser console (F12 and network tab)

Regards

**Comment by sikas89** [comment]
Hello @nuxsmin 

I took a look as requested .. When I put a URL in this form `https://192.168.2.1:4434` .. I get the error, and I find that the file `/ajax/ajax_itemSave.php` returns `403 Forbidden` .. But when I add the URL without any port or HTTP/HTTPS `192.168.2.1` it works fine and the same file returns `200 OK` .. Have you seen this before?

**Comment by nuxsmin** [comment]
Hmmm, really weird, because the URL is built using the hostname and port.

Could you try out  the same action (within sysPass) while the browser console is opened?

**Comment by sikas89** [comment]
Hello @nuxsmin,

What do you need to see in the browser console?

**Comment by nuxsmin** [comment]
Hello, it would be useful to get the network requests to those resources, so I could figure out what is happening.

Regards
