### ISSUE TITLE
authToken...help....

### ISSUE THREAD

**Issue by smokecatcher** [nuxsmin/sysPass#695]
Can someone please explain to me how you go about getting the authToken? Where does it come from? It's not my password. Is it a hash? Is there some magic function I need to use to get it? All the examples simply say "PUT YOUR AUTH TOKEN HERE" -- which is just about useless since I don't know what it is or where to get it. 

It's probably something simple that everyone in the world knows about except me.

**Comment by nuxsmin** [comment]
Hello, the auth tokens can be got from "Users & Accesses > API authorizations". Some actions will require a password (eg. Add accounts and view password), once you set it, you don't need to set it again, unless you want to do.

Once the API token is generated, it will be the same for the other actions that the user is granted to.

Regards.
