### ISSUE TITLE
Error luego de Migrar a 2.1.12

### ISSUE THREAD

**Issue by fgleanzq** [nuxsmin/sysPass#696]
Estimados, acabo de migrar a la version 2.1.12 y cuando quiero ver la password de una cuenta me arroja el siguiente erro  'Encoding::hexToBin() input is not a hex string.' .
Aclaro de que se realizo el upgrade sin errores.
Saludos

**Comment by nuxsmin** [comment]
Buenas, me puedes indicar desde qué versión hiciste el upgrade?

**Comment by fgleanzq** [comment]
Buen día, desde la 1.2.

Saludos

**Comment by nuxsmin** [comment]
Ocurre con todas las cuentas?, Hay algún error, relacionado con la actualización, en el log de eventos de sysPass?

**Comment by fgleanzq** [comment]
Hola, si pasa en todas las cuentas, la actualizacion no arrojo errores, en el log solo aparece 2017-08-11 17:41:11 - Encoding::hexToBin() input is not a hex string.
Saludos

**Comment by nuxsmin** [comment]
Me refiero al log de eventos de la aplicación, no al archivo syspass.log

**Comment by nuxsmin** [comment]
Y los mensajes sobre la encriptación de cuentas?

Hay que tener en cuenta que la actualización a la versión 2.1 reencripta todas las cuentas con un nuevo mecanismo de encriptación, por lo que puede que hayan habido errores al encriptar las cuentas.

Es complicado saber qué ha pasado, ya que ese error no ha aparecido nunca hasta ahora.

Saludos!

**Comment by fgleanzq** [comment]
Esos mensajes como puedo verlo? 
Gracias

**Comment by nuxsmin** [comment]
En el log de eventos, tienen que aparecer los ids de cuentas actualizadas.

**Comment by fgleanzq** [comment]
El problema ya fue solucionado, lo que paso es que la base de datos que usamos de testing estaba mal importada, cuando realizamos el dump de manera correcta, hicimos y luego hicimos el upgrade sin problema.

Saludos

**Comment by nuxsmin** [comment]
Perfecto! Me alegro que funcione ;)
