### ISSUE TITLE
Unable to write into the "/config" directory on Synology 

### ISSUE THREAD

**Issue by BurgerK2** [nuxsmin/sysPass#698]
the problem is in dockerfile  "chmod 750 sysPass/config sysPass/backup" the synology can only read or/and write folder permission.

when i change the permission on read and write then:  
The "/config" directory permissions are wrong 
Current: 777 - Needed: 750

**Comment by nuxsmin** [comment]
Hello, it seems that you're using a different user from the webserver's one, so you need to set the right user to access those files in the NAS.

Regards
