### ISSUE TITLE
How to register new device for two factor Authentication 

### ISSUE THREAD

**Issue by jr-RXcode** [nuxsmin/sysPass#699]
Is there a way to reset the two factor authentication for a specific user as an Admin? They got a new phone and had 2 factor authentication enabled on the old phone, but now they can't access the password manager with out a code. They don't have a phone with them.

**Comment by nuxsmin** [comment]
Hi, unfortunately there is no way to reset the 2fa for  an user, because it needs to be done in a secure way, that is by using a recovery code which hasn't been implemented yet (planned for next version)

Resetting 2fa by admins is  very dangerous because it could be done to get access to an account.

Let me think about how to achieve it.

Regards

**Comment by jr-RXcode** [comment]
I see. So, How would I add a new device after 2factor has already been enabled ?

**Comment by nuxsmin** [comment]
Hello, I've developed this feature, please update the plugin from its own repository: https://github.com/nuxsmin/sysPass-Plugins/tree/master/Authenticator

Email notifications and user's emails need to be configured for sending recovery codes.

PS: this plugin won't be longer shipped within sysPass, so you will need to open new issues on its own repository.

**Comment by nuxsmin** [comment]
Solved

**Comment by jr-RXcode** [comment]
Thanks! for the Feature.... how would I install the plug in in syspass ? I tried copying the directory but syspass would load anymore.

**Comment by nuxsmin** [comment]
You need to update sysPass to the latest commit and then download the plugin into "Inc/Plugins" directory before removing the old plugin files.

Don't worry about the plugin data, because it's stored within the db.

Regards
