### ISSUE TITLE
[Feature-Request] Filter based on permissions

### ISSUE THREAD

**Issue by Chefkeks** [nuxsmin/sysPass#70]
Would be nice to filter accounts based on groups and users, so that the syspass admin can easily see accounts where only specific users and/or groups have access.

**Comment by Chefkeks** [comment]
@nuxsmin
Definitely need to test version 1.2 once the final is released. Overall I can see a lot fixes, improvements and also a great new design :)
Really looking forward to the final release to review syspass again against our current solution.
Cheers and keep up the good work!

**Comment by nuxsmin** [comment]
Nice to hear you and thank you for your support. Any feedback is appreciated.
