### ISSUE TITLE
sysPass Plugins

### ISSUE THREAD

**Issue by nuxsmin** [nuxsmin/sysPass#702]
Hello,

I hope you are doing fine :)

This notice is regarding sysPass Plugins, which were introduced from 2.0 version and currently there's only one plugin, Authenticator, but there will be many more in next releases, because many features wouldn't be useful for everyone, so you could enable/disable whenever you need it.

Because of nature of plugins, they will be shipped separately, so you only need to get them from https://github.com/nuxsmin/sysPass-Plugins and put into `[sysPass root]/inc/Plugins` directory, so they will be listed to enable.

Any suggestion is welcome!

Kind regards

**Comment by abandin-stratio** [comment]
Hola:

En la interfaz de usuario no veo activa la opcion plugins. No he encontrado nada en la documentacion mas alla de como se debe implementar un nuevo plugin. Podeis indicarme omo activar Authenticator?

Gracias!

**Comment by nuxsmin** [comment]
Hola!

una vez descargado el plugin y copiado al directorio `[sysPass root]/inc/Plugins`, puedes activarlo en la pestaña "Elementos y Personalización > Plugins". Una vez activado, en la vista de preferencias de cada usuario aparecerá la configuración del mismo.

---

Hello!

once downloaded and copied the plugin into `[sysPass root]/inc/Plugins` directory, you can enable it on "Items and Customizations > Plugins" tab. Once enabled, the plugin's configuration will be displayed on the preferences view of each user.

Regards
