### ISSUE TITLE
Tag docker images with version

### ISSUE THREAD

**Issue by joerg** [nuxsmin/sysPass#703]
Hi,

I am currently deploying sysPass to production using your docker containers. What is really bugging me is that the images are not tagged with the version. It would be really helpful to have something like:

nuxsmin/docker-syspass:latest   <-- basically a nightly build or so
nuxsmin/docker-syspass:2.1       <-- stable release
nuxsmin/docker-syspass:2.1-php7

And also have mysql in a separate image.

nuxsmin/docker-syspass-mysql:latest  <-- nightly build
nuxsmin/docker-syspass-mysql:2.1     <-- tested and working with 2.1

That way building the images could also be automated...

**Comment by nuxsmin** [comment]
Hi, you're right additional tagged builds would be useful. Let me figure out what would be the best way.

Thanks for the feedback!

Regards

**Comment by joerg** [comment]
Hi, great to hear. You can automate the Build from the Docker hub for free: https://docs.docker.com/docker-hub/builds/#add-and-run-a-new-build
There you can simply specify a repository, where in the repository the Dockerfile can be found and that the docker image tag should be created according to a git tag. Pretty straight forward but of course it requires some testing and playing around.

**Comment by nuxsmin** [comment]
Done :wink:
