### ISSUE TITLE
Group Permissions on Accounts ignored

### ISSUE THREAD

**Issue by coreyramirezgomez** [nuxsmin/sysPass#704]
Adding a group to an account under the permissions section is ignored. Users in the group do not have access when they login. However, adding individual users works fine. Not practical to add users one by one though.

Users are imported from LDAP.

Any help is appreciated.

**System Configuration**
OS: CentOS Linux release 7.3.1611 (Core)
SysPass Version: 2.1.12.17080701
WebServer: Apache 2.4.6
PHP: 5.6.31
Database: MariaDB 5.5.52

**Comment by nuxsmin** [comment]
Hello,

Please take a look to this http://doc.syspass.org/en/application/permissions.html#acl

Maybe you would need to enable secondary groups access  on "configuration > accounts"

Regards

**Comment by coreyramirezgomez** [comment]
That worked! Thanks for the help! (Guess I should read the manual next time)
