### ISSUE TITLE
Enable (non-admin) user to set the account main group

### ISSUE THREAD

**Issue by Matwolf08** [nuxsmin/sysPass#705]
Shouldn't a user be able to set the account main group when creating the account itself?
I can't find a way to enable a non AppAdmin or AccountAdmin user to do this.

It would be very useful if you want to create an account not visible by the members of your primary group but visible only by the members of your secondary groups.

Thanks in advance

**Comment by nuxsmin** [comment]
Hello, I forgot your question since it was posted in a closed issue. I'll think about it and let you know.

Thanks for the feedback!

Regards

**Comment by mcostagonzalez** [comment]
Hi,

I think this is a very important feature. Not having this can cause that other users can see passwords when you want a non-admin user to be able to create new accounts in the system. In the current state, they need the assistance of an admin in order to correct it and, in the meantime, it is exposed to others.

Regards.

**Comment by davidpsc** [comment]
Hi,

yes, I agree, this would also be very helpful for us. A user for example is a member of an another group but he cannot change the primary group of the account nor give permissions to that other group to the new account.
I think that users should have the permission and ability to change the primary group to other group that they have access to and give additional permissions to other groups that they have access to.

Regards

**Comment by nuxsmin** [comment]
Hi @davidpsc , that could be achieved by switching on `Permissions` button on the user's profile:

![captura_072](https://user-images.githubusercontent.com/1775774/31119049-f8d76054-a82f-11e7-872d-41e1d5d7cb15.png)

Regards

**Comment by davidpsc** [comment]
Hi,

ah, I've missed this setting obviously - thank you 👍 ! So then only the primary group change is an open feature request and the other part of my request is solved.

Regards

**Comment by ArminXG** [comment]
Hello, I vote for that feature too. It would resolve our problem that the main group of the user mostly is not the group the account should be available for. At the moment we use a workaround to have an own main group for each user to have each account initially availble for the creator only (all permissions for others is done with secondary groups).
If the user can set and change the main group, our workaround is not needed any more.

Thank you!

**Comment by nuxsmin** [comment]
Hello, I agree with you, an account owner should be able to change the main group (by setting profile option) . This feature will be implemented in next release among others like an accounts default group inherited from the group of the user, so user's main group could be overridden.

Kind regards.

**Comment by radkokeves** [comment]
hello, is it implemented yet please ?
thank you

**Comment by fago** [comment]
I have run into the same issue, with beta 3. it's quite a show-stopper as it effectively prevents people from adding passwords that are only accessible by the right groups.

>Allow to have a main group set to "none", or

I think this is what would be the easiest fix. We do not have any use for the "main group" feature else, so just setting to none should do it.

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in v3. Thanks for the feedback!

Regards

**Comment by john-jam** [comment]
Hi ! I'm sorry to re-open this conversation but I couldn't find that feature in the v0.3 release ?
The only way to edit the main group for a non-admin user is to give him application admin or account admin options in his profile.
Maybe I missed some options but I couldn't find a way to set the main group to 'none' neither.
I use your docker image nuxsmin/docker-syspass:3.0-php7.2 which install syspass 3.0 (300.18122601).

Btw, thanks for you amazing open-source project :)

**Comment by nuxsmin** [comment]
@john-jam you're right, it's my fault, some points were implemented but not the main one. Users should be able to change the main group for the accounts they own.

Thanks for the feedback!

**Comment by DDH112** [comment]
This is a really important feature for us as well, would love to see this be addressed in a future update ☺️

**Comment by Matwolf08** [comment]
Hi nuxsmin, do you have an estimated release date for this feature?

Thanks!

**Comment by nuxsmin** [comment]
Hi @Matwolf08 

It has been implemented in v3.1 indeed, but it will be released after some more features were implemented and tests passed.

Hopefully it would be ready by the end of this month.

Regards

**Comment by drewlsvern** [comment]
@nuxsmin I have tested the v3.1 branch and these features work but I'd prefer to wait until it's officially released to use in production. 

Any updates on the 3.1 release?

**Comment by nuxsmin** [comment]
3.1-RC1 has been released today, so it's time to test it to get a really stable release.

Thanks for the feedback!
