### ISSUE TITLE
Advanced XML import

### ISSUE THREAD

**Issue by joerg** [nuxsmin/sysPass#706]
Hi,

I am trying to import our KeePass data and now I am facing the issue that the direct XML import from KeePass is not ideal because the Customer/Category gets lost and CSV import is missing tags. Now I wanted to restructure the data in KeePass anyway so I was wondering: Is it possible to create a syspass XML manually? I am mostly missing the encryption part and guess that the tags and such are encrypted in the <pass> and <key> XML parts, right?
So, is there a way to manually create the syspass XML using any linux tools (preferably not php)?

**Comment by nuxsmin** [comment]
Hi,

I'm wondering which fields do you need to get imported from Keepass, because I could tweak the Keepass import to get it.

Creating a sysPass XML file is easy, since you only need to replicate the same structure as when exported, but the encryption library used to encrypt the accounts passwords is written in PHP (https://github.com/defuse/php-encryption), so would need to code a PHP based function/tool.

Regards.

**Comment by joerg** [comment]
Well, since I want to restructure anyway CSV import would be the best option for me but there importing tags is missing. And I just saw that tags are stored in a separate table in the database and not exported with the XML export.
So maybe I should open up a new issue for Import and Export of Tags?

**Comment by nuxsmin** [comment]
Tags aren't imported from a CSV file (it could be a useful feature for next release), but they are included in the XML file instead.

Regards

**Comment by joerg** [comment]
Are you sure tags are in the XML? I have this one here:
```
...
  <Tags>
    <Tag id="3">
      <name>Tag 1</name>
    </Tag>
    <Tag id="1">
      <name>Tag 2</name>
    </Tag>
    <Tag id="2">
      <name>Tag 3</name>
    </Tag>
  </Tags>
  <Accounts>
    <Account id="1">
      <name>Test</name>
      <customerId>1</customerId>
      <categoryId>1</categoryId>
      <login>bla</login>
      <url>bla</url>
      <notes/>
      <pass>omitted</pass>
      <key>omitted</key>
    </Account>
  </Accounts>
...
```

So unless the tags are part of the pass or key they are not in the XML.

**Comment by nuxsmin** [comment]
You're right, tags are only included but not linked to the accounts. I'll fix it shortly :)

**Comment by vmario89** [comment]
i ran into the same problem. i imported some dozens of accounts now and i tagged them with love. i spent much time. now the tags are not assigned to the accounts :-(

**Comment by nuxsmin** [comment]
@vmario89 did you mean that you created an XML file including tags?

**Comment by vmario89** [comment]
@nuxsmin no i directly used the export-XML from KeePass 2. I've overseen that the upper mentioned XML was sysPass format. Actually parsing KeePass tags would be nice too. They are hidden in the entries too.

![grafik](https://user-images.githubusercontent.com/5631071/35007910-360f4c7a-fafb-11e7-9386-5f4bbd98d35c.png)
![grafik](https://user-images.githubusercontent.com/5631071/35007974-73408ce4-fafb-11e7-8def-b080170444a3.png)

**Comment by joerg** [comment]
@vmario89 I ended up adding the Tags manually to the MySQL Database. There is a table which has account entry ids and tag ids in its columns. From there on it was rather simple to create a long long list of primitive SQL insert statements from my exported CSV that I had from keepass. For sure not nice and clean, but its a one time thing so who cares. ;-)

**Comment by vmario89** [comment]
dear @joerg, i got the same plan with some dirty SQL stuff. Should be easy. But would be more cool to avoid it :D

**Comment by nuxsmin** [comment]
@vmario89 totally agree, DBs aren't for humans, so let the machine do it ;)

I didn't notice about keepass tags, so this feature could be implemented.

Thanks for the feedback!

**Comment by vmario89** [comment]
KeePass is more powerful than i thought. I just found it out today :D KeePass can do much more. KeePass supports may stuff like
- Tags
![grafik](https://user-images.githubusercontent.com/5631071/35014130-dc558da6-fb0f-11e7-906a-67cb16e200b6.png)
- Field References which works like Account Linking (with the difference that Account linking seems to link only to passwords in sysPass)
![grafik](https://user-images.githubusercontent.com/5631071/35014091-c6aa0bb2-fb0f-11e7-9817-6b8b4435591c.png)
- File Attachments
![grafik](https://user-images.githubusercontent.com/5631071/35014110-d0a0c9f8-fb0f-11e7-9869-56a8b0746b54.png)
- History
- Colors (could be imported as Custom Fields)
- Custom Fields (could be imported as Custom Fields too)
and so on..^^
