### ISSUE TITLE
Assign account permissions from Add/Edit user

### ISSUE THREAD

**Issue by clthames** [nuxsmin/sysPass#707]
It would be great if we could add/edit a user and give permissions to multiple accounts at the same time from that page.  And even see the list of accounts the user has access to already.

When I bring in a new developer and want to provide access to only a couple of clients, that can sometimes be 10-15 accounts (considering cpanel, ssh, admin, frontend, godaddy, etc) and time consuming to change permissions for each one individually.

I'm also open to other suggestions for a workaround if you have one!

Thank you so much!

**Comment by nuxsmin** [comment]
You're right, such feature would be useful, one way could be by linking users to clients so  each user assigned to a client only would be granted to those accounts which the client is set for.

You can get the accounts which a user is granted for, by using special searches (help icon on the right of search box).

Regards

**Comment by adonisd** [comment]
+1 for me, being to able to assign profiles/groups/users to only certain customers would be great. Even the ability to assign them to certain categories (let us say we want to assign a networking engineer access to only see our category "Networking hardware" for example. Thank you!

**Comment by Fizard** [comment]
I think linking users to clients is very good to make the security more flexible. I was also trying to do something like this.

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in v3. You can achieve it either by using preset values or accounts bulk edit option.

Regards.
