### ISSUE TITLE
move to a syspass organization

### ISSUE THREAD

**Issue by DanielRuf** [nuxsmin/sysPass#711]
Imho projects greatly benefit from the move to an organization where multiple teams can be managed (translations, testing, PRs, PR reviews, support).

I would find it great to see the project to move to an org on GitHub and would like to contribute my free time.

**Comment by nuxsmin** [comment]
Hello, you're right, organizations would improve the projects and team management. Let me take some time to analyze how to configure the organization.

Regards

**Comment by joerg** [comment]
When you're at it you could also create a syspass organization at the docker hub. That way we could pull/use docker images like
```
syspass/app:latest
syspass/mysql:latest
syspass/app:stable
syspass/mysql:stable
syspass/app:1.2.3
syspass/mysql:1.2.3
```

**Comment by DanielRuf** [comment]
Bump.

**Comment by nuxsmin** [comment]
Hello!, just note I haven't forgot this request, but now I'm focused on v3 and it drains me out a lot of time, so I'd like to get sysPass into an organization when things are fine and focus on contributions and "social" stuff.

**Comment by DanielRuf** [comment]
How can we support/help you?

**Comment by nuxsmin** [comment]
Currently, I'm making unit tests and once they are ready, I'll put hands on new features (some of them have been already implemented). Documentation needs also to be reviewed since some installation requirements have been changed. That said, I think that it would be a good starting point to perform some functional tests and doc reviewing, since it would let you get some knowledge about the app, unless you got it before.

Thanks!

**Comment by joerg** [comment]
I can't help you with the code, since I am not a PHP dev, but if you want/need any help with Docker and automated builds and/or Travis testing I would gladly help you.

**Comment by nuxsmin** [comment]
Thanks @joerg! 

Although Docker and Travis have been already set up, you could take a look for any improvement.

* Travis: https://travis-ci.org/nuxsmin/sysPass
* Docker: https://hub.docker.com/r/nuxsmin/docker-syspass/

**Comment by joerg** [comment]
Regarding Docker, there already is a ticket: https://github.com/nuxsmin/sysPass/issues/703 ;-)

**Comment by nuxsmin** [comment]
On the way...
