### ISSUE TITLE
[Feature Request] Translate authenticator plugin

### ISSUE THREAD

**Issue by matthgyver** [nuxsmin/sysPass#713]
Hi,

There is no french translation of authenticator plugin and the default langage is spanish.
Please, is it possible to : 
 - Make english as default langage if there is no translation for a plugin
 - Translate it in french 
I can translate it in french but I'm just sysadmin and I don't well understand how it work.
I see a folder by language in this folder "inc/Plugins/Authenticator/locales/" and 2 files : 
 - authenticator.mo
 - authenticator.po
If I understand, I need to create the same folder for french (fr_FR) and modify the "authenticator.po" file but what about "authenticator.mo"
Have you a documentation please ?

Thank you

**Comment by nuxsmin** [comment]
Hello @matthgyver 

I'm glad to know you want to translate it.

Hopefully you don't need to deal with .po files (gettext) since this project is using the POEditor platform. The following link will let you join to the project: https://poeditor.com/join/project/DECOdOhqLf

Regards

**Comment by matthgyver** [comment]
Hi Nuxsmin,

I've just made the translation.
Some elements depend on the context, I've tagged it with "Fuzzy" flag.
I will adjust when I can see the result in situation.

**Comment by nuxsmin** [comment]
Sure, I've just updated and pushed the french translation. You can review it on demo site or download the code from https://github.com/nuxsmin/sysPass-Plugins

Thanks!

**Comment by matthgyver** [comment]
Your welcom. Thanks at you for your great work ;-)

I just tested the demo site and french language does'nt work for the plugin.
On my local installation, it's OK but I've 2 little bug :
 - If I type a wrong code, the error message is in french the first time but in spanish after a new error.
 - After the activation and the reloading page, the language plugin come back to spanish. If I exit the preference page and if I come back It's OK.
 
In the translation interface, I see some field that making me think that there is a system of recovery in case of problem with U2F. Where is it ?

**Comment by nuxsmin** [comment]
Hmmm, I've just tested it on demo site and worked fine. Be aware that the demo user could be being used by many people, so it's recommended to create a new user and set language preferences.

Regarding your environment behaviour, that could be caused because the gettext translations are cached by Apache so there would be some annoying behaviour that would be solved after restarting it.

And lastly, right there's a recovery feature that will be available after activating the 2fa auth. This will allow to display 10 recovery codes to use them when logging in. The recovery code will be sent by email if you request it from the 2fa login screen

Regards

**Comment by matthgyver** [comment]
Ok, just restart Apache and problems are solved.
I can't find button for requesting recovery code in the 2fa login screen : 
![selection_005](https://user-images.githubusercontent.com/6485132/29877647-80427a92-8da0-11e7-9098-4ac269fb4760.png)

Thank's

**Comment by nuxsmin** [comment]
Hmmm, have you downloaded the plugin from its own repository?

**Comment by matthgyver** [comment]
Hi,
I've made my test with the last syspass release and I've just copy the language plugin folder ...
I've fully reinstalled syspass with the last release and full last commit of the plugin.
It seem ok : 
![selection_006](https://user-images.githubusercontent.com/6485132/29922627-ae7e7b16-8e56-11e7-9774-d5a70d7bbb4b.png)

But how does it work ? If I check the lost code option and click on connexion button it tell me that the code is invalid.
There is the configuration tab : 
![selection_007](https://user-images.githubusercontent.com/6485132/29922746-326ecdae-8e57-11e7-90e8-bfb1392b6774.png)

An other bug (maybe I should open an issue on the plugin repo) : I can't unactive the 2FA. When I switch it of, type a code and click to save button, a message tell me that is unactivated but if I quit and go to the tab, the 2FA is switched on. In fact, if I close my session and try to authenticate again, I've a 2FA code demand.

Thank you

**Comment by nuxsmin** [comment]
Hi, I'll check out this issue.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, I've just pushed a new plugin version that solves this issue.

Regards.

**Comment by matthgyver** [comment]
Thank you, now I can disable the plugin.
I understand how recuperation work : full fill the code field, check the lost code and click to continue for sending a mail with recovery code. Maybe an help about this will welcome on the page.
So I've tested it with success.
Should I see anything in the  "code de récupération" field in the plugin tab ? (see my last screenshot)
I just see a popup with "Ver codigos" message, like in the screenshot.

**Comment by nuxsmin** [comment]
It seems that fuzzy translations aren't shown...

![captura_026](https://user-images.githubusercontent.com/1775774/29964133-616bf8fe-8f09-11e7-9ed0-7a3623c5ce04.png)

**Comment by nuxsmin** [comment]
Just click on that icon and codes will be shown

**Comment by matthgyver** [comment]
Yes I've try it but I don't show the code.
(I've not say in my last post but yes I've clicked on the eye picture and I've nothing.)

**Comment by nuxsmin** [comment]
Hello, 

Does it display the codes?, did you use them before?

Regards.

**Comment by vivalasvegan** [comment]
Hi,
Do you know how we can find the recovery code from the QR Code we flash when we enable the 2FA please ?
