### ISSUE TITLE
Extend API with edit ability and tags

### ISSUE THREAD

**Issue by joerg** [nuxsmin/sysPass#714]
I've only just imported all our data into syspass, but I already need to mass edit a lot of entries. For that using the API would be perfekt, but there is no edit option.

**Comment by nuxsmin** [comment]
Sure, some API methods (like editing accounts and items) are planned to be implemented in next release, since they are a key point for a fully functional API.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Implemented in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
