### ISSUE TITLE
Update Link does not work multiple times

### ISSUE THREAD

**Issue by DanielRuf** [nuxsmin/sysPass#716]
While the Account Detail page is open and after clicking the "Update Link" button, all consecutive clicks on the button throw an "Invalid Action" warning after clicking on the public link.

Is there something reset when we try to open the public link in the same browser session so the request does not work anymore?

**Comment by nuxsmin** [comment]
Hello,

that is because a security mechanism which avoid to send a form using the same security token. If you open a new tab, it will create a new token, so it invalidates the security tokens set on the other tabs (related to sysPass).

Regards.

**Comment by DanielRuf** [comment]
But if we do not click the generated link and click again on the "Update Link" button it works (green notification at the top).
