### ISSUE TITLE
IP blocking is broken when running behind reverse proxy

### ISSUE THREAD

**Issue by ghislainbourgeois** [nuxsmin/sysPass#718]
When using a reverse proxy in front of syspass, the IP blocking will cause a denial of service because the blocked IP will be the reverse proxy. Using the X-Forwarded-For header when it exists will properly block the original client, not the reverse proxy.

**Comment by nuxsmin** [comment]
Hello,

The forwarded IP address should be retrieved in https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Util/Util.class.php file by using `getClientAddress` method, so I'll find out why it isn't working as expected.

Thanks for your contribution!

**Comment by ghislainbourgeois** [comment]
Hi, I have played around some more with the code, and found some funny things going on, and I think the problem is located in the way that Docker Swarm and my reverse proxy are setup. The X-Forwarded-For header seems to be taken properly by syspass, but it is not set properly in my setup. Sorry for the inconvenience.

**Comment by nuxsmin** [comment]
Hi, the x-forwarded header is not standardized across the browsers, so it's a bit difficult to get the original IP address. BTW let me know if you get any progress on it.

Thanks again for the feedback!
