### ISSUE TITLE
config.xml

### ISSUE THREAD

**Issue by jrfx85** [nuxsmin/sysPass#720]
Hi, 
When I go directly to https://fqdn/syspass/config/config.xml it shows the XML File with all the credentials in clear text. Is that correct? Is there any solution to hide these informations?
Thanks for a short answer.

**Comment by nuxsmin** [comment]
Hi, you're right, you could move it to a directory outside the webserver public root (you need to edit Base.php file) or http://doc.syspass.org/en/application/security.html

Regards

**Comment by jrfx85** [comment]
Sorry, I should have known...Thank you very much

**Comment by nuxsmin** [comment]
You're welcome!
