### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#721]
Hello,

It seems that session timeout is a hard limit of 300 seconds (that can be set in the UI of course), whether there is activity or not since I get my session closed even if I'm working on sysPass.

Is there a way to reset the timeout on actitvity ?

Best regards.

**Comment by nuxsmin** [comment]
Hello, 

Unfortunately some parameters need to be tweaked in PHP configuration, because there's a session garbage collector that is triggered within a period of time, so active sessions will be destroyed within that time.

Please take a look to PHP configuration.

Kind regards.
