### ISSUE TITLE
Docs: Add Information for double authentication.

### ISSUE THREAD

**Issue by daMihe** [nuxsmin/sysPass#722]
I tried several times to install as i got stuck after the Setup logging in.

Cause was my previously (for other services) set up basic auth which uses other data. Solution was to disable the basic auth for the syspass-directory. Please add a hint that double authentication may create errors and may create strange behaviour.

Thanks.

**Comment by nuxsmin** [comment]
Hmm, did you mean this?

> The Auth Basic authorization is always being checked, so if the HTTP headers within the user data are being sent, it will be checked whether the sysPass user’s login matches with the Auth Basic one.

From: http://doc.syspass.org/en/application/authorization.html

Regards

**Comment by daMihe** [comment]
Yes i meant that article. The Setup guide does not hava a hint for this behavior and i did not find the page before. I think just a link like "if having trouble logging in after setup, look into authentication mechanisms". The article itself is written good aand clearly - i just have not found it.

**Comment by nuxsmin** [comment]
I agree with you :)...I'll add a link to that page.

Thanks for the feedback!
