### ISSUE TITLE
Cannot delete user who created an account

### ISSUE THREAD

**Issue by B-o-t** [nuxsmin/sysPass#723]
Hello,

One of my coworker left the company yeasterday. I would like to delete him from the users.

When i select the user and clic "Delete User", i got the following message : 

> Error while deleting the user

In the Event Log : 

> Error while querying
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass`.`accounts`,
CONSTRAINT `fk_accounts_user_edit_id` FOREIGN KEY (`account_userEditId`) REFERENCES `usrData` (`user_id`)) (0)SQL : '
DELETE
FROM usrData
WHERE user_id = ?
LIMIT 1'

The user was imported from LDAP, i thought it was maybe related to that.
I tried to create a non ldap test user, create an account with him, and delete the user test. Result is the same.

If I delete the Account, and the Account History, I can delete the user.

For now, i will disable the user who left, but it might be usefull to handle this use case :)

**Comment by nuxsmin** [comment]
Hello,

that is the correct behavior since you cannot delete a user that is being used by a database record. In this case the user is referenced by an account as its last modifier.

Regards.

**Comment by nuxsmin** [comment]
Yes, it could be a hassle but without constraints the db data would be a mess....

You can perform an special search to get those accounts that are being used by that user and then modify them. Be aware that accounts history records are also linked to users' id.

Regards

**Comment by B-o-t** [comment]
I totally agree with you about the constraints.
I've managed to do the operation, and it "seems" to be fine.
We are still testing the solution, so no big impact for now.
As a workaround, i also thought that i could recreate the account with another user, and then remove the first one, its history, etc...
Anyway, we can close this :)
Thank you!!!
