### ISSUE TITLE
trying to install syspass

### ISSUE THREAD

**Issue by abu1993** [nuxsmin/sysPass#725]
@nuxsmin 
Hi,

Thanks for your help it appreciate
I followed the description for the installation but at the end when I open the browser I always receive https://ip../syspass/sysPass-2.1.14.17090101/index.php
I receive this text below

<?php
/**
* sysPass
*
* @author nuxsmin
* @link http://syspass.org
* @copyright 2012-2017, Rubén Domínguez nuxsmin@$syspass.org
*
* This file is part of sysPass.
*
* sysPass is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* sysPass is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
*  along with sysPass.  If not, see <http://www.gnu.org/licenses/>.
*/

use SP\Controller\MainController;
use SP\Core\Init;
use SP\Core\Session;

define('APP_ROOT', '.');

require APP_ROOT . DIRECTORY_SEPARATOR . 'inc' . DIRECTORY_SEPARATOR . 'Base.php';

if (!Init::checkPostLoginActions() && Session::getAuthCompleted()) {
    $Controller = new MainController();
    $Controller->getMain();
    $Controller->view();
}

How I can make a troubleshooting for know where I make a mistake ?

Thanks

**Comment by nuxsmin** [comment]
Hi,

It seems that PHP module isn't enabled on Apache, so you need to either enable it or restart Apache.

Regards

**Comment by abu1993** [comment]
How doi enable the php module?

kindest regards
Abulele Mgxabayi

**Comment by nuxsmin** [comment]
It depends on the running OS. 

https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-debian
