### ISSUE TITLE
Only one Customer for user...

### ISSUE THREAD

**Issue by madcoda9000** [nuxsmin/sysPass#728]
Hello,

how can i assign only one customer to a user account?

I've done the following so far:

1. created a user
2. created a group 
3. assigned the user to the group
4. created a profile
5. set the permissions in the profile
6. created a new customer
7. set the group and profile in user account

Whe the user logs in, he can see all customers ans can create accounts in all customers? But he should only be able to see and create accounts in one specisifc customer.

How can i archive this?

Regards
sascha

**Comment by nuxsmin** [comment]
Hello, this feature is not currently available, since customers are not linked to users, so they are only useful for filtering. It will be implemented in next version.

Thanks for the feedback!

Regards.
