### ISSUE TITLE
Ability as an Administrator to reset locked Accounts 

### ISSUE THREAD

**Issue by jr-RXcode** [nuxsmin/sysPass#729]
User enter incorrect password to many times, now they are locked out of syspass. How long do they need to wait for the system to allow them to log back in? Is there a way an administrator can reset the locked account?

**Comment by nuxsmin** [comment]
Hello, the lockout is set for ten minutes since the last attempt.

Regards.

**Comment by jr-RXcode** [comment]
Thanks!
