### ISSUE TITLE
add composer file

### ISSUE THREAD

**Issue by DanielRuf** [nuxsmin/sysPass#730]
Currently there is no release on packagist for composer.
It would be good to have one so we can install and update it with composer (if possible).

Also a short `git clone` information would have been useful as the gitignore file does not overwrite the critical files but this method is not mentioned in the docs.

**Comment by nuxsmin** [comment]
Sure, I'd like to use composer for sysPass dependency management, so it will keep dependencies updated up-to-date. I need to some changes to implement it.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, good news!..after some tweaks, sysPass is now compatible with composer, so you can try it out from `composer` branch. Be aware that plugins need to be updated too (from their `composer` branch).

I know that vendor directory (ie. dependencies), should be downloaded once installed by the end user but I think it could be quite tough to do it by an inexperienced user, so I added this directory to git repository.

Regards.

**Comment by DanielRuf** [comment]
Awesome, thanks =)
