### ISSUE TITLE
Question about random password length

### ISSUE THREAD

**Issue by nsi-test** [nuxsmin/sysPass#733]
Hi,
recently I have upgraded syspass from version 1.2 to the last available version - 2.1.14.17090102.
Finally everything went ok, but I noticed something strange. In our organization we widely use random generated passwords with maximum complexity. When I generate a random password by syspass with given length it generates it with number of symbols plus one. For instnance if I say 5, it is 6, if 12 - 13 and so on. I checked it also in the demo on the official site, and it has the same behavior.
Is it a normal feature, because every time I generate a password I have to put the length minus one?

**Comment by nuxsmin** [comment]
Hi,

You're right, it's a bug. I'll fix it shortly.

Thanks for the feedback!

**Comment by nsi-test** [comment]
You are welcome :-)  Thank you for the fast reaction.
