### ISSUE TITLE
Upgrade issue when having a large number of accounts

### ISSUE THREAD

**Issue by davidpsc** [nuxsmin/sysPass#734]
Hi,

first of all: thanks for keeping trying to find the issue with the sysPass upgrade in Windows (issue #276)!
It looks much better now, I can see the upgrade page and finally start the upgrade.

Unfortunately the upgrade doesn't complete :/ The issue seems to be our quite large number of accounts. We have 609 accounts and about 1100 historical accounts/password changes.

It manages to finish 609 account updates but gets stuck while updating the historical data. At the webpage a message is displayed which says "Internal Server Error".

```
[12-Sep-2017 16:02:04 Europe/Belgrade] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\path_to_syspass\inc\SP\Controller\TaskController.class.php on line 175
[12-Sep-2017 16:03:32 Europe/Belgrade] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\path_to_syspass\inc\SplClassLoader.php on line 160
```

I've seen this error messages in the PHP error log and increased the PHP script execution timeout to 30 minutes (configured a value of 1800 as script execution timeout in the PHP config file).

The error message is gone but now the script failes at about 7 minutes runtime. Again 500 Internal Server Error but nothing in the PHP error log about it...

What else could be the issue here? Sometimes it finishes a few seconds (or 1 or 2 minutes) earlier so it doesn't seem to be a time limit issue.

![image](https://user-images.githubusercontent.com/5638975/30333651-b1fd53e4-97dd-11e7-801c-7bb33ba9dc39.png)

Thanks again!
David

**Comment by nuxsmin** [comment]
Hi,

It seems another kind of issue not related to the execution time duration, since I've upgraded an instance with ~7000 accounts and it took 45 minutes long.

Is there any error message in syspass.log file (within config directory)?

Regards

**Comment by davidpsc** [comment]
Hi,

sorry that I bothered you, I've had a look at the server logfile and noticed that there are additionally two FastCGI timeouts beside the normal PHP script execution timeout.

So this was again a IIS (on Windows) issue which could be resolved by increasing the FastCGI "Activity Timeout" (to 1800) and the FastCGI "Request Timeout" (to 1800).

Now the upgrade completed without problems.

The only errors I had in the syspass.log (in the config directory) are:
```
2017-09-12 13:00:23 - Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspass.plugins' doesn't exist
2017-09-12 13:00:23 - #0  SP\Storage\DB->prepareQueryData() called at [C:\path_to_syspass\syspass\inc\SP\Storage\DB.class.php:150]
#1  SP\Storage\DB->doQuery() called at [C:\path_to_syspass\syspass\inc\SP\Storage\DB.class.php:105]
#2  SP\Storage\DB::getResults() called at [C:\path_to_syspass\syspass\inc\SP\Storage\DB.class.php:81]
#3  SP\Storage\DB::getResultsArray() called at [C:\path_to_syspass\syspass\inc\SP\Mgmt\Plugins\Plugin.class.php:287]
#4  SP\Mgmt\Plugins\Plugin->getEnabled() called at [C:\path_to_syspass\syspass\inc\SP\Core\Plugin\PluginUtil.class.php:185]
#5  SP\Core\Plugin\PluginUtil::getEnabledPlugins() called at [C:\path_to_syspass\syspass\ajax\ajax_getEnvironment.php:54]

2017-09-12 13:00:23 - Fehler bei der Abfrage
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspass.plugins' doesn't exist (0)
Caller 1: SP\Storage\DB\logDBException
Caller 2: SP\Storage\DB\getResults
Caller 3: SP\Storage\DB\getResultsArray
Caller 4: SP\Mgmt\Plugins\Plugin\getEnabled
Caller 5: SP\Core\Plugin\PluginUtil\getEnabledPlugins
2017-09-12 13:00:23 - SQL : 'SELECT plugin_name FROM plugins WHERE BIN(plugin_enabled) = 1'
2017-09-12 13:00:23 - Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_level' in 'field list'
2017-09-12 13:00:23 - #0  SP\Storage\DB->prepareQueryData() called at [C:\path_to_syspass\syspass\inc\SP\Storage\DB.class.php:150]
#1  SP\Storage\DB->doQuery() called at [C:\path_to_syspass\syspass\inc\SP\Storage\DB.class.php:341]
#2  SP\Storage\DB::getQuery() called at [C:\path_to_syspass\syspass\inc\SP\Log\Log.class.php:195]
#3  SP\Log\Log->writeLog() called at [C:\path_to_syspass\syspass\inc\SP\Storage\DB.class.php:296]
#4  SP\Storage\DB::logDBException() called at [C:\path_to_syspass\syspass\inc\SP\Storage\DB.class.php:113]
#5  SP\Storage\DB::getResults() called at [C:\path_to_syspass\syspass\inc\SP\Storage\DB.class.php:81]
#6  SP\Storage\DB::getResultsArray() called at [C:\path_to_syspass\syspass\inc\SP\Mgmt\Plugins\Plugin.class.php:287]
#7  SP\Mgmt\Plugins\Plugin->getEnabled() called at [C:\path_to_syspass\syspass\inc\SP\Core\Plugin\PluginUtil.class.php:185]
#8  SP\Core\Plugin\PluginUtil::getEnabledPlugins() called at [C:\path_to_syspass\syspass\ajax\ajax_getEnvironment.php:54]

2017-09-12 13:00:23 - Fehler bei der Abfrage
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_level' in 'field list' (0)
Caller 1: SP\Storage\DB\logDBException
Caller 2: SP\Storage\DB\getQuery
Caller 3: SP\Log\Log\writeLog
Caller 4: SP\Storage\DB\logDBException
Caller 5: SP\Storage\DB\getResults
Caller 6: SP\Storage\DB\getResultsArray
Caller 7: SP\Mgmt\Plugins\Plugin\getEnabled
Caller 8: SP\Core\Plugin\PluginUtil\getEnabledPlugins
2017-09-12 13:00:23 - SQL : 'INSERT INTO log SET \n            log_date = UNIX_TIMESTAMP(),\n            log_login = ?,\n            log_userId = ?,\n            log_ipAddress = ?,\n            log_action = ?,\n            log_level = ?,\n            log_description = ?'
2017-09-12 13:00:23 - Fehler bei der Abfrage
Caller 1: SP\Log\Log\writeLog
Caller 2: SP\Storage\DB\logDBException
Caller 3: SP\Storage\DB\getResults
Caller 4: SP\Storage\DB\getResultsArray
Caller 5: SP\Mgmt\Plugins\Plugin\getEnabled
Caller 6: SP\Core\Plugin\PluginUtil\getEnabledPlugins
2017-09-12 13:00:23 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_level' in 'field list'
```

Is this normal during the upgrade? I don't see any errors after the upgrade finished, so it seems fine now :)

Regards
David

**Comment by nuxsmin** [comment]
Hi, are those errors related to the successful upgrade process, or are there because the failed upgrading?.

Nice to hear that you finally upgraded the app!

Regards.

**Comment by davidpsc** [comment]
Hi,
they seem to have no impact on the upgrade process at all. I always had those messages in the log when trying the upgrade process (before the upgrade started those messages were logged). But as the last upgrade attempt was successful those messages don't seem to be quite important I think. Logging into the database (log table) works now so doesn't seem to be an issue anymore.

Thanks again
David
