### ISSUE TITLE
Cant delete users after upgrade from 1.2 to 2.1

### ISSUE THREAD

**Issue by bitking** [nuxsmin/sysPass#737]
Hi,

I updated to syspass 1.2 to 2.1 and now when i try to delete a user i get the following message in the log.

Can you let me know what i can do to fix this problem?

------
Error while querying
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`syspass2`.`accHistory`,
CONSTRAINT `fk_accHistory_users_edit_id` FOREIGN KEY (`acchistory_userEditId`) REFERENCES `usrData` (`user_id`)) (0)SQL : '
DELETE 
FROM usrData 
WHERE user_id = ? 
LIMIT 1'

**Comment by bitking** [comment]
Okay i read in https://github.com/nuxsmin/sysPass/issues/606 that it is intended but how do i search for all the entry's for this user in the gui under accounts(h) because i cant find anything.

**Comment by nuxsmin** [comment]
Hmm, you're right it should provide some useful information about related records. Let me write down an SQL query to get it.

Regards.

**Comment by vmario89** [comment]
i guess that can be closed. This was discussed in https://github.com/nuxsmin/sysPass/issues/810 which was already solved
