### ISSUE TITLE
Preguntas sobre el proyecto      /       Questions about the project

### ISSUE THREAD

**Issue by veesalex** [nuxsmin/sysPass#738]
Buenas, me llamo Alex y me gustaría realizar unas preguntas:
La primera de todas es, para que sirve crear grupos de usuarios si se le aplican los permisos en los perfiles?
Y la segunda pregunta, es necesaria esa autenticación con la password maestra al iniciar un usuario nuevo?

Hello, my name is Alex and I would like to ask a few questions:
The first of all is, what is the use of creating groups of users if you apply the permissions in the profiles?
And the second question, is it necessary to authenticate with the master password when starting a new user?

**Comment by nuxsmin** [comment]
Buenas Alex,

con respecto a tus preguntas:

> La primera de todas es, para que sirve crear grupos de usuarios si se le aplican los permisos en los perfiles?

Los grupos de usuarios sirven para conceder acceso a las cuentas a los usuarios que pertenezcan a los mismos, bien sea como grupo primario o como grupo secundario. Los perfiles sólo son aplicables a nivel de usuario, aunque puede ser que en un futuro se apliquen también a grupos.

> Y la segunda pregunta, es necesaria esa autenticación con la password maestra al iniciar un usuario nuevo?

Sí, la clave maestra se utiliza para realizar la encriptación de las cuentas, ya que no se almacena en el servidor. Sólo se requiere en el primer login o en cambios de clave (si no se conoce la anterior).

Saludos!

---
Hello Alex,

regarding your questions:

> The first of all is, what is the use of creating groups of users if you apply the permissions in the profiles?

The user's groups let you grant access to those accounts on which the users are granted to either using primary groups or secondary groups. Profiles are only applied on the user level but it could be applied to groups in future versions.

> And the second question, is it necessary to authenticate with the master password when starting a new user?

Yes, the master password is needed for encrypting the accounts' data. It will be required either on the very first login or whenever the user changes its password (if he doesn't know the old one).

Regards

**Comment by veesalex** [comment]
Vale, muchas gracias por la aclaración, de nuevo me surge una pregunta relacionada con los Backup's de la aplicación. 
Su programa lo tengo instalado a traves del docker que nos proporciona, y cuando quiero descargar un backup me sale:  'Error: Prohibido', no se a que se debe ni como llegar a solucionarlo. Le agradeceria su ayuda. He probado de descargar el backup desde otros navegadores y tampoco me ha funcionado.
![error](https://user-images.githubusercontent.com/31921149/30420224-34e96af2-9939-11e7-81ed-65fb5712f126.png)

Gracias, Saludos
Alex

**Comment by nuxsmin** [comment]
Buenas, la configuración de Apache del contenedor de Docker impide la descarga, por seguridad,  desde el directorio de backup.

http://doc.syspass.org/es/application/security.html

Saludos!
