### ISSUE TITLE
Customer selection

### ISSUE THREAD

**Issue by olivier54** [nuxsmin/sysPass#740]
Syspass release 2.1.12

Hello,

Issue with account creation

User options : application administator --> deactivated
                       account adminstrator --> deactivated
We can't create account because we can't select any value in mandatory customer field.
It seems to only works if an account (created by a user in the same group) is already created with desired customer.

Thanks for your help.

**Comment by nuxsmin** [comment]
Hello,

this behavior will be improved in next release, since the customers are only visible by the users who are granted to the accounts in which the customer is set. In next release, it will be possible to set global customers, which will be visible by anyone.

Regards
