### ISSUE TITLE
Reverse Proxy: Insecure Warning

### ISSUE THREAD

**Issue by aeimer** [nuxsmin/sysPass#741]
Hi there,

I've set up SysPass (docker) behind a Nginx which is used as a reverse-proxy which also handles the SSL stuff.
Everything works so far, but the Logos are loaded over http... this is pretty annoying because the browser doesn't like that!

We should load these two files (like all the others) with the correct protocol/host or completly without the protocol/host.

In general it would be great, to set a base hostname, so it is possible to setup syspass under a URL like: "https://exmaple.com/syspass/" running behind a reverse proxy. Currently (as far as I experienced it) it isn't possible.

Best regards,
Alex

![grafik](https://user-images.githubusercontent.com/25035182/30431446-df19d55a-995e-11e7-96ab-2ff68af2119f.png)

![grafik](https://user-images.githubusercontent.com/25035182/30431480-f5fd8690-995e-11e7-928b-3bb5edadc760.png)

**Comment by aeimer** [comment]
After a really short research through the code I've found these two ways to fix this problem:
- Remove $WEBURI from https://github.com/nuxsmin/sysPass/blob/35a65affff1e3c987085082022b9e04906a9cea9/inc/SP/Controller/MainController.class.php#L112
- Check for `X-FORWARDED-For` and `X-Forwarded-Proto` here https://github.com/nuxsmin/sysPass/blob/35a65affff1e3c987085082022b9e04906a9cea9/inc/SP/Core/Init.class.php#L357

I'd like the second more, because then it would be possible to setup syspass as "https://exmaple.com/syspass/"

**Comment by nuxsmin** [comment]
Hi,

the URI is built using the request protocol, but you're proxying an https request through http (behind the proxy), so sysPass will set the protocol regarding the proxy request (https://github.com/nuxsmin/sysPass/blob/35a65affff1e3c987085082022b9e04906a9cea9/inc/SP/Core/Init.class.php#L357).

This is a tricky issue, since you're (proxy) telling sysPass that you're using https but not indeed, since the fully channel isn't being encrypted.

As you pointed, a nice solution would be to implement an option to set the base URL.

Thanks for the feedback!

Regards.

**Comment by aeimer** [comment]
Something like:
```
if (isset($_SERVER['X-FOWARDED-FOR']) && isset($_SERVER['X-FORWARDED-PROTO'])) {
    // This only could be http or https
    $protocol = $_SERVER['X-FORWARDED-PROTO'];
    // This may be example.com or sub.example.com/syspass
    $host = $_SERVER['X-FORWARDED-FOR'];
    self::$WEBURI = $protocol . '://' . $host;
} else {
    $protocol = isset($_SERVER['HTTPS']) ? 'https://' : 'http://';
    self::$WEBURI .= $protocol . $_SERVER['HTTP_HOST'] . self::$WEBROOT;
}
```
would solve the "proxypass" problem, right?

**Comment by nuxsmin** [comment]
Hmm, it might, but "X-FORWARDED" header is quite variable, so I need to think&test about an stable solution: https://stackoverflow.com/questions/13111080/what-is-a-full-specification-of-x-forwarded-proto-http-header#13111106

Regards

**Comment by aeimer** [comment]
If I have understood the RFC 7239 right, the `X-` is deprecated and the `Forwarded`-Header is now the right way. Because the `X-` is the de facto standard we should use both, like so:

```php
$reProto = '/proto=.+(,|$)/i';
$reHost = '/host=.+(,|$)/i';
if (isset($_SERVER['Forwarded']) && preg_match($reProto, $_SERVER['Forwarded'], $matchesProto) && preg_match($reHost, $_SERVER['Forwarded'], $matchesHost)) { // Check in style of RFC 7239
    $protocol = $matchesProto[0];
    $host = $matchesHost[0];
} else if (isset($_SERVER['X-FOWARDED-FOR']) && isset($_SERVER['X-FORWARDED-PROTO'])) { // Check de facto standard
    // This only could be http or https
    $protocol = $_SERVER['X-FORWARDED-PROTO'];
    // This may be example.com or sub.example.com/syspass
    $host = $_SERVER['X-FORWARDED-FOR'];
    self::$WEBURI = $protocol . '://' . $host;
} else { // We are called directly
    $protocol = isset($_SERVER['HTTPS']) ? 'https://' : 'http://';
    self::$WEBURI .= $protocol . $_SERVER['HTTP_HOST'] . self::$WEBROOT;
}
```

This way we check the official way first, if not set we check the x-fowarded (de facto standard) and otherwise we got called directly.

**Comment by nuxsmin** [comment]
Nice hack!, let me test it and then I'll push a new commit/release...if you don't do it before :)

Thanks for your contribution!

**Comment by aeimer** [comment]
@nuxsmin Please check my changes, I wasn't able to test them!

**Comment by nuxsmin** [comment]
Hello, I've rewritten some parts of the hack and moved out the method to a proper `HttpUtil` class, since there's no need to keep it in `Init` class. https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Util/HttpUtil.class.php#L53

It should work fine.

Regards
