### ISSUE TITLE
Importing accounts CSV with tags

### ISSUE THREAD

**Issue by bigfoot90** [nuxsmin/sysPass#744]
I'm trying to import accounts *(on Demo page)* using a csv file.

The instructions do not mention abount the `tags` field:
> The CSV import file requires the following format:
> "account_name";"customer";"category";"url";"user";"password";"notes"

Can I import my accounts with tags in some way?

**Comment by nuxsmin** [comment]
Hello, unfortunately, at this moment,  tags cannot be imported using a CSV file, but you will be able to do it in next version.

Regards.
