### ISSUE TITLE
unable create private account with viewer user

### ISSUE THREAD

**Issue by galoagui** [nuxsmin/sysPass#745]
If you only select the 'create private account' permiss you cant create it. Necesaryly you have to enable 'create account permission'.
But if you want a 'viewer user' that he can create a private account, he can´t make it

**Comment by nuxsmin** [comment]
Hello, the "private account" permission does only allow to change the account to private, but you always need to set "create account" permission.

If you're searching for create-only-private accounts permission, it isn't currently implemented.
 
Regards
