### ISSUE TITLE
Question about IE 11 support.

### ISSUE THREAD

**Issue by nsi-test** [nuxsmin/sysPass#746]
Hi,
I have the following question. Is IE 11 supported by syspass? I know that there may be such information on the site, but I couldn’t find it. It looks like some controls don’t work – for instance save button in edit or create new account. Tested with IE 11 11.608.150.63.0, Update Versions 11.0.46 (KB4036586) on Windows 10 Enterprise 1703 system. 
Well, I don’t insist that IE 11 is necessary to be supported, because I don’t use it at all. I just have to know what to say to my colleagues for sure. They have other browsers too, so it isn’t a problem at all.
Thanks.

**Comment by nuxsmin** [comment]
Hello,

Actually I'm working on IE 11 and Edge support and hopefully it will be available in next release.

Regards.
