### ISSUE TITLE
Make it so "Attempts exceeded" is configurable

### ISSUE THREAD

**Issue by guikolt** [nuxsmin/sysPass#747]
Hello,

If I'm not mistaken, there is a IP ban of 10 minute after 5 wrong access attempts.
Is this true ?

Isn't there a way to make it configurable by the admin instead of being hardcoded ?
I am trialing syspass here where I work but I'm worried about people banning everyone else here from acessing syspass due to wrong password attempts. Like, 1 people forgets his password and suddenly everyone is unable to access syspass until the 10 minute mark is gone...

Is there a way to 'flush' these bans ?

**Comment by nuxsmin** [comment]
Hello,

Currently there isn't any way to unban users, but be aware that the ban tracking is done by client IP address, even if sysPass is behind a reverse proxy.

If the client is using a proxy, all the users behind it will be banned.

However, this feature will be added in next release.

Regards.
