### ISSUE TITLE
[Feature] Passwords autocompletion

### ISSUE THREAD

**Issue by bigfoot90** [nuxsmin/sysPass#748]
I like this project so much.
I would like to have passwords autocompletion for my users.
The best solution is to have a browser extension that connects to sysPass APIs, but I don't know how to write extensions, I try to find a solution using something that just exists.

`browserpass` is a Chrome & Firefox browser extension for `pass` *(a UNIX password manager)* that allows you to auto-fill login forms.
https://github.com/dannyvankooten/browserpass

`pass` store passwords as encypted files organized into meaningful folder hierarchies (see https://www.passwordstore.org/).

The idea is to share these files using WebDAV from sysPass.
The files in the share wont be real files from filesystem, but records from database *(the accounts that the current user have access to)*.

There is `SabreDAV` (see http://sabre.io/) framework for PHP.

You can then mount the share on clients and use `browserpass` to have the auto-fill feature.

Let me know what do you think, if this something interesting for you.

**Comment by nuxsmin** [comment]
Hi!

I'm glad to know you found sysPass useful ;)

This is a cool feature that was rounded in my mind since a time ago and be sure it will be developed, but I need some time...

The main idea is using the sysPass API, which actually has some methods to get info and passwords from the accounts (and other items), so I think there is no need to use another encryption manager, since a simple Firefox/Chrome extension would be suitable.

Thanks for the feedback!

**Comment by pwFoo** [comment]
Would love to see a auto type feature / plugin 👍

**Comment by nuxsmin** [comment]
sysPass-fox repo has been created to store this development ;)

Hopefully it will be ready soon...

https://github.com/nuxsmin/sysPass-fox

**Comment by vmario89** [comment]
this will be neat :-)

**Comment by nuxsmin** [comment]
@lugio hello! I'm finishing sysPass v3 final release, and then I'll put hands on the Firefox extension. It has been a hard and intense work during last months and unfortunately there wasn't enough time to other stuff...

**Comment by lugio** [comment]
OK cool, nice news, thanks for work

**Comment by MrMEEE** [comment]
Looking forward to this :)

**Comment by jboissat** [comment]
Hello

sysPass-fox is still relevant?

Thank you

**Comment by nuxsmin** [comment]
Sure, I'm a bit busy, but I'm committed to get it soon!

Regards

**Comment by ochorocho** [comment]
@nuxsmin this is a very early state version of my sysPass Firefox Addon

Addon page:
https://addons.mozilla.org/de/firefox/addon/syspass/

Repo:
https://github.com/ochorocho/syspass-firefox
