### ISSUE TITLE
2.1 version not supporting php version 7.0

### ISSUE THREAD

**Issue by vishalprompt** [nuxsmin/sysPass#750]
I have installed php version 7.2 in centos 6.8.  Getting error 
 error_outline Required PHP version >= 5.6.0 <= 7.0
Please update the PHP version to run sysPass
any solution?

**Comment by nuxsmin** [comment]
Hello, currently sysPass isn't fully tested on PHP >= 7.1, so you would need to wait for next release, that hopefully will be compatible with >= 7.1  (including newest 7.2 -not released yet-)

Regards.
