### ISSUE TITLE
Polish is not working

### ISSUE THREAD

**Issue by osiu97** [nuxsmin/sysPass#751]
I tried to change language to Polish and it doesn't change.
I checked it and I think it's because in syspass/inc/locales/po_PO/ it's po_PO instead of pl_PL.
Also in Language.class.php it's po_PO.

**Comment by nuxsmin** [comment]
Hi, did you set the locales in the OS?

**Comment by osiu97** [comment]
Yes, I did. In fact i tried installing German to be sure and it worked, but Polosh still didn't work until i did those changes in my installation.

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply...

I've just fixed this issue by renaming the locales short name to pl_PL (I'm wondering why I set it to po_PO).

Thanks for the feedback!
