### ISSUE TITLE
LDAP Stuffs again

### ISSUE THREAD

**Issue by tceski** [nuxsmin/sysPass#753]
Seeing Wrong Login when attempting to login with imported LDAP user.

DC is server 2012r2, Domain functional level of 2008R2

seeing this in event logs;
Error while searching the user on LDAP
User:XXXXXXXXXXXXXXXXXXXX
LDAP ERROR : Success (0)
LDAP FILTER :
(&(|(samaccountname=\74\6f\6d\2e\63\65\67\69\65\6c\73\6b\69\40\6d\6f\62\69\77\6d\2e\63\6f\6d)(cn=\74\6f\6d\2e\63\65\67\69\65\6c\73\6b\69\40\6d\6f\62\6
9\77\6d\2e\63\6f\6d)(uid=\74\6f\6d\2e\63\65\67\69\65\6c\73\6b\69\40\6d\6f\62\69\77\6d\2e\63\6f\6d))(|(objectClass=inetOrgPerson)(objectClass=person)(o
bjectClass=simpleSecurityObject)))

**Comment by nuxsmin** [comment]
Hmm, it seems that someone is trying to inject some stuff within the LDAP filter, could be?

Regards

**Comment by tceski** [comment]
I should mention we use SSO. I've got the sysPass user login set the same as our SSO logins using the users e-mail address. 
If I disable LDAP under settings using only Active Directory the error changes to;

Wrong login
Type : authBrowser
User : user.email@company.com
I'm running this on Centos7.

**Comment by nuxsmin** [comment]
That message tells that your browser is sending some SSO headers so sysPass will try to match them against the login username, if it doesn't match, login will be denied.

If you are using the email address for login, it won't work unless you're setting the email as login in the user data.

This feature will be implemented in next version.

Regards.

**Comment by tceski** [comment]
For the login/user data field we are using sAMAccountname which is populated with the users e-mail address in/imported from our active directory. This matches the imported user data in sysPass for the Login column under the Users and Accesses option. Still a no go though.

**Comment by nuxsmin** [comment]
Sorry, I missed your last point regarding SSO->Login process.

It seems that your SSO backend is sending an hex encoded username so the LDAP filter doesn't know how to decode it (hex to bin works well). Do you have any way to change it?. It could be decoded through the code but how to tell to sysPass that is an hex encoded string?

Regards.

**Comment by tceski** [comment]
I did something incorrectly in my LDAP setup. Going to start over.
