### ISSUE TITLE
CSV Import Estonian characters

### ISSUE THREAD

**Issue by upsten** [nuxsmin/sysPass#754]
When csv file contains characters ÄÖÕÜ or lowercase äöõü it'll import text prior to mentioned characters so if a value starts with one of those letters the data will be empty I suspect it will also not work correctly with characters žš and ŽŠ

When manually inserted it shows the letters correctly so I suspect the issue is with the import tool.

Also is it possible to use tab as a delimiter?

**Comment by nuxsmin** [comment]
Hi, let me check out this issue.

Yes, you could use the tab delimiter by setting `\t` as delimiter.

Regards

**Comment by upsten** [comment]
Great, thanks.
I'm using v2.1 and CSV Delimiter field only allows me to input 1 character

**Comment by upsten** [comment]
Hi, do you have any new information or a workaround I could use?

**Comment by nuxsmin** [comment]
Actually, you could increase the CSV separator field length by modifying this line:  https://github.com/nuxsmin/sysPass/blob/9b0313748682e090e5ffd3fa784f09b4c92fc046/inc/themes/material-blue/views/config/import.inc#L189 and setting `maxlength="2"`

Regards

**Comment by upsten** [comment]
Okay, thanks for that.

But about the importing ÄÖÕÜ characters not working, is there any workaround for that or things I could try?

**Comment by nuxsmin** [comment]
I've just performed an import an it worked fine. Please check out the file encoding is set to UTF-8

![captura_081](https://user-images.githubusercontent.com/1775774/31169420-d836ac78-a8f8-11e7-8eda-33e413168cb6.png)

**Comment by nuxsmin** [comment]
Here you have the file used (change extension to `csv`):

[syspass.txt](https://github.com/nuxsmin/sysPass/files/1355287/syspass.txt)
