### ISSUE TITLE
All customers not showing when creating account with custom profile

### ISSUE THREAD

**Issue by B-o-t** [nuxsmin/sysPass#758]
Hello,

I created a custom profile to allow account creation.
Then I created a user and assign him the profile.
When I log in with this user, and try to create a new account, I don't see every customers in the dropdown list. Only customers with no account associated, or account which the users group has at least read access.

I think that we should be able to see and select all customers available.

The aim is to achieve this :
Let's say I have a Windows and a Linux Team (groups in SysPass)
Both team should be able to create account for customer, but not seeing account of the other team (with private to group option).

Tested on last version of teampass, and on the demo site as well.

**Comment by nuxsmin** [comment]
Hello, 

That's right and this feature is already implemented in development version, so it will be available in next version

Thanks for the feedback!

**Comment by B-o-t** [comment]
Hi,

Good to hear! You do a really nice job on this project!
Thank you for the quick answer :)
