### ISSUE TITLE
ActiveDirectory Auth not working & configuration not saved

### ISSUE THREAD

**Issue by port22** [nuxsmin/sysPass#759]
Hi, 
there was a user having kind of the same problem: https://github.com/nuxsmin/sysPass/issues/644
like him, the settings I made within ldap tab are not being saved, although web-ui says so.
I run syspass via docker-compose, permissions on config/ are 750.

I tried to fill my settings in config.xml by hand (and restarted docker container), but still login not possible and settings in web-ui are empty.

I'm not sure if the ldap settings are correct because the field declarations "search prefix" and "group" are not clear to me. I actually should also apply a filter, I think.
My settings are like this:

```
<ldapAds>1</ldapAds>
<ldapBase>OU=company,DC=company,DC=org</ldapBase>
<ldapBindPass>suhdf8suhf9Hhedf</ldapBindPass>
<ldapBindUser>CN=binduser,OU=company,DC=company,DC=org</ldapBindUser>
<ldapDefaultGroup>1</ldapDefaultGroup>
<ldapDefaultProfile>1</ldapDefaultProfile>
<ldapEnabled>1</ldapEnabled>
<ldapGroup>1</ldapGroup>
<ldapProxyUser></ldapProxyUser>
<ldapServer>192.168.1.2</ldapServer>
<ldapUserattr>sAMAccountName</ldapUserattr>
```

are they wrong or insufficient?
thanks for any hints!

**Comment by nuxsmin** [comment]
Hi,

It's quite weird, since LDAP settings are read from the config file. Be aware that although you restarted the container, the PHP session would be still active, so you need to delete the browser cookie related to sysPass site.

Regards.

**Comment by nuxsmin** [comment]
Taking a look to your XML LDAP config, the `ldapGroup` tag should be set to an LDAP group which users are member of, so this will run as a filter for login through LDAP. If you set it to `*` group filtering won't take place.

The `ldapUserattr` is not currently being used, because internal users lookup will use some common attributes.

Regards
