### ISSUE TITLE
Force HTTPS: still on port 80

### ISSUE THREAD

**Issue by lroellin** [nuxsmin/sysPass#762]
I have installed syspass via the official docker images. I then enabled 'Force HTTPS', but something is weird.

When I connect to it (http://my-server), it redirects to https://my-server:80. Notice the :80, and my browser gives me error messages that this is not correct SSL. So it seems like something is still running on :80 that is not SSL (I guess the redirector)

To reproduce:
1. Start with a default installation
2. Enable Force HTTPS => Save
3. Observe

* You should have been redirected to https://my-server
* You have been redirected to https://my-server:80

I think I may have found the issue, but I could be wrong. Basically, you're testing if :443 is not already the port, and want to set it. But you still set it to :80, which leads to this bug.
https://github.com/nuxsmin/sysPass/blob/2ff0fe000ad08c8edac833715dfdc2f81f6c438e/inc/SP/Util/HttpUtil.class.php#L42

I could very well be wrong, so then it's just a bug report.

**Comment by nuxsmin** [comment]
Hmm, it could be wrong...let me check it out in detail.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, it should be fixed in latest commit.

Kind regards
