### ISSUE TITLE
Database Access

### ISSUE THREAD

**Issue by nblount** [nuxsmin/sysPass#763]
I have attempted to install sysPass to a remote database server and it failed (whether hosting mode was enabled or not made no difference). I even ran tcpdump on the Mariadb server and saw no traffic coming from the machine on which sysPass was installed. I then installed a local Mariadb and installed sucessfully, exported the database and copied it to the remote server changing the configuration to point at the remote server instead of localhost and it gives:
Error 2003: SQLSTATE[HY000][2003] Can't connect to MySQL server on 'mysql.......' (13)
Once again a tcpdump on the Mariadb server shows no attempted connections to the mariadb.

The syspass.log:
initError
Unable to connect to the DB
Error 2003:...

The machine is a CentOS 7.4.1700 with the epel and webtatic repo's activated. php56w has been installed from webtatic repo, other packages from standard and epel. Remote mariadb is 10.1 but as it never connects I don't think that is an issue.

**Comment by nblount** [comment]
Well it appears I have found the cause of all of this even if it isn't very clear. It appears that the database connection issue to off box is caused by SELinux. Once turned off or made permissive the connections off box actually work.

**Comment by nuxsmin** [comment]
Hmm, great! Glad to know it works fine

Thanks for the feedback!
