### ISSUE TITLE
Wrong email config lets every save action hang forever 

### ISSUE THREAD

**Issue by SimplicityApks** [nuxsmin/sysPass#766]
When your email setup is slightly wrong (TSL instead of SSL for instance), every configuration change will save, but hang forever until you start a completely new session. There should at least be some feedback that emails don't send, this took me hours to figure out...

**Comment by nuxsmin** [comment]
You're right, that's so since PHP doesn't allow multiple threads per request running on a webserver, so the thread executing the script will be blocked by any task.

I'll add some email checking when configuring it.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Implemented in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
