### ISSUE TITLE
Permission bug? - accounts in additional groups cannot be found

### ISSUE THREAD

**Issue by davidpsc** [nuxsmin/sysPass#768]
Hi,

I just noticed that a user that in a main group (let's say "Group1") and is a member of another group (lets' say "Group2") can not see accounts where the permissions were set for "Group2" (and the main group is another group, let's say "Group3").

This seems to me to be a bug in sysPass. Can you check it please?

Regards, David

**Comment by nuxsmin** [comment]
Hi David!

Did you enable the "Secondary Groups Access" option (Configuration > Accounts tab)?

![captura_177](https://user-images.githubusercontent.com/1775774/32000314-9a82cf16-b996-11e7-854a-5e75e1c996a0.png)

Regards

**Comment by nuxsmin** [comment]
http://doc.syspass.org/en/application/permissions.html#acl

**Comment by davidpsc** [comment]
Sorry, the "Secondary Groups Access" was not enabled. As this feature wasn't available in the previous sysPass version (1.x...) I didn't look for such an option.

Thanks!

Regards, David

**Comment by nuxsmin** [comment]
You're welcome
