### ISSUE TITLE
Cannot delete private account

### ISSUE THREAD

**Issue by bodkov** [nuxsmin/sysPass#769]
If I change an account from group-permission to private-account I can't delete my own account marked as private any more.

To reproduce:
non-admin user creates an account, account is visible to group.
non-admin user cannot delete account
(group-admin user can delete this account)
If non-admin user afterwards changes the access to 'private'
neither the group-admin-user nor the non-admin user can see the "remove account"-item in the submenu.

**Comment by nuxsmin** [comment]
Hello,

Is set 'delete account' option in the user profile?

Regards

**Comment by andreaskuestner** [comment]
Sorry, the head-admin was too restrictive. Problem solved!

**Comment by bodkov** [comment]
Sorry, the head-admin was too restrictive. Problem solved!

**Comment by nuxsmin** [comment]
Great!, thanks for the feedback!!
