### ISSUE TITLE
Internal error: preg_split() in HttpUtil.class.php

### ISSUE THREAD

**Issue by VitosX** [nuxsmin/sysPass#771]
Latest release 2.1.15.17101701 broke sysPass installed on macOS 10.12.6, running on apache2 2.4.25 + php 5.6.30, configured with Server.app. It uses reverse proxy configuration and according to release notes, reverse proxy support was supposed to be improved in this version...

The error in apache error_log is:
`preg_split(): Compilation failed: nothing to repeat at offset 9 in /Library/WebServer/Documents/sysPass-2.1.15.17101701/inc/SP/Util/HttpUtil.class.php on line 126`

**Comment by nuxsmin** [comment]
Hello @VitosX 

it should be fixed in latest commit. A regex typo was the issue.

Thanks for the feedback!

**Comment by VitosX** [comment]
That was fast. Thank you!
