### ISSUE TITLE
Customer not visible when assigning account

### ISSUE THREAD

**Issue by bodkov** [nuxsmin/sysPass#773]
Users who do not have visible accounts for a customer cannot search for this customer and this makes totally sense. But when adding a new account the users can only assign customers from the dropdown who appear in the dropdown of the search and this does not make sense. it looks like the dropdown for searching and adding accounts uses the same customer list.

**Comment by nuxsmin** [comment]
Hello, that's right, customers already assigned to an account, won't be displayed for users who aren't granted to view that account. That behavior will be improved in next version, since there will be global customers that will be visible by all the users.

Regards.

**Comment by nuxsmin** [comment]
Implemented in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
