### ISSUE TITLE
Mail from different to mail to for notifications

### ISSUE THREAD

**Issue by matthgyver** [nuxsmin/sysPass#779]
Hi,

By default, the system notification are sent from and to the mail address define in the mailTo field of the configuration page.
Is it possible to allow the configuration of a field "from" and a field "to" for system notifications please?
I've fixed my destination mail address in the Email.class.php file, line 116 in waiting but it's not perfect : 
` 
if (empty($mailTo)) {
    $mailTo = "myMail@mail.com";
}
`

Thank you

**Comment by nuxsmin** [comment]
Hi, you're right and this feature will be implemented in next version.

Regards

**Comment by nuxsmin** [comment]
Implemented in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
