### ISSUE TITLE
Problemas login después de instalación

### ISSUE THREAD

**Issue by lfreina** [nuxsmin/sysPass#78]
Hola,

Tengo un problema. Tengo una instancia de syspass corriendo en mi servidor ubuntu. Perdí el master password y decidí volver a instalar syspass. Para ello cree una nueva instancia de syspass con una base de datos distinta. Todo bien en la instalación hasta el momento de iniciar el login. 

Cuando intento iniciar con el login no hace nada. No he logrado administrar la nueva instalación. Ya verifiqué el password. Si escribo un password incorrecto, no despliega ningún mensaje incluso. ¿Habrá algún problema con correr dos instancias de syspass en el mismo servidor? Ambas instancias tienen version 1.0.9.

Gracias.

Luis Fernando

**Comment by nuxsmin** [comment]
Hola Luis Fernando, 

No hay ningún problema para tener varias instancias de la aplicación en el mismo servidor, de hecho yo lo tengo así para el desarrollo.

El fallo que me comentas puede ser de javascript, ya que el login está diseñado así. Comprueba los fuentes a través del navegador, para ver si hay alguna salida de error que impida la carga correcta del archivo functions.php 

También puedes comprobar el archivo error.log de apache.

Saludos

**Comment by lfreina** [comment]
Hola nuxsmin.

Gracias por la pronta respuesta. Me puse a investigar un poco más y me funcionó hasta cambiar los permisos de la carpeta de syspass con chmod -R 750. En el readme file the install decía que era sólo a la carpeta de config. ¿Sabes si he configurado algo mal entonces?

Y gracias por la ayuda.

Saludos,

Luis Fernando

**Comment by nuxsmin** [comment]
Hola Luis Fernando, sólo son necesarios dichos permisos en el directorio config, lo que podía ocurrir es que el usuario del servicio web no tuviera acceso a los directorio de la aplicación.

Saludos,

Rubén

**Comment by lfreina** [comment]
Gracias por la respuesta Rubén.
 
Probé pero si le asigno a todos los demás archivos permisos 644 y dejo el usuario en www-data aún así no me permite el ingreso. 
De cualquier manera ya me funcionó y tu respuesta me ha ayudado mucho.

Tengo una duda/sugerencia. Cuando estaba en mi sitio web sitio/syspass01/ hice login con mi usuario nuevo. El sitio antiguo estaba en sitio/syspass00/. Si después de hacer el login cambio al syspass00 en la dirección de arriba logro entrar a toda la aplicación. Es cierto que no me muestra los passwords pero no sé si esto ya te había sucedido antes. A lo mejor ya lo has corregido en la versión 1.1 pero me pareció importante mencionarlo y no consideré crear un nuevo issue para esto.

Saludos,

Luis

**Comment by nuxsmin** [comment]
Me alegro que funcionara.

Con respecto a lo que me preguntas, si se ha mantenido la misma configuración y la base de datos es la misma, es normal, ya que al tener la misma estructura  la aplicación funciona, lo único que fallan son las claves de las cuentas si la clave maestra es diferente. De hecho, si guardas el archivo config.php y la base de datos,, es posible reinstalar tantas veces como quieras.

Un saludo

**Comment by lfreina** [comment]
Gracias Rubén. Agradezco mucho tu ayuda.
