### ISSUE TITLE
CSV export feature

### ISSUE THREAD

**Issue by pgrigoryev** [nuxsmin/sysPass#781]
It would be nice to be able to export passwords(accounts) in a nice unencrypted human-readable format, e.g. same  as csv used for import ("account_name"; "customer"; "category"; "url"; "user"; "password"; "notes")

**Comment by nuxsmin** [comment]
Hi, this feature has been discussed a time ago (#390) and the best approach is to use a decryption tool to maintain the security chain.

Regards.

**Comment by nuxsmin** [comment]
Thanks for the feedback!
