### ISSUE TITLE
Can't edit imported accounts

### ISSUE THREAD

**Issue by pgrigoryev** [nuxsmin/sysPass#782]
Get the "error while updating account" message when trying to edit the imported account
here's the log message:

225 | 2017-11-16 16:31:25 | ERROR | updateAccount | ADMIN | x.x.x.x | Error while queryingSQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'account_passDateChange' at row 1 (0)SQL : 'UPDATE accounts SET account_customerId = :accountCustomerId,account_categoryId = :accountCategoryId,account_name = :accountName,account_login = :accountLogin,account_url = :accountUrl,account_notes = :accountNotes,account_userEditId = :accountUserEditId,account_dateEdit = NOW(),account_passDateChange = :accountPassDateChange,account_isPrivate = :accountIsPrivate,account_isPrivateGroup = :accountIsPrivateGroup,account_parentId = :accountParentId,account_userGroupId = :accountUserGroupId,account_otherUserEdit = :accountOtherUserEdit,account_otherGroupEdit = :accountOtherGroupEdit WHERE account_id = :accountId'
-- | -- | -- | -- | -- | -- | --

Only imported accounts are affected, accounts created from the web interface are ok.

sysPass version | 2.1 (2.1.15.17101701)
-- | --
Database | SERVER_VERSION : 5.7.20-0ubuntu0.16.04.1 CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $ SERVER_INFO : Uptime: 1391822 Threads: 1 Questions: 8394 Slow queries: 0 Opens: 575 Flush tables: 1 Open tables: 414 Queries per second avg: 0.006 CONNECTION_STATUS : Localhost via UNIX socket Name: syspass_db@localhost
PHP | Version: 7.0.22-0ubuntu0.16.04.1 Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache Used Memory: 2048 KB User: root OP Cache num_cached_scripts : 313 num_cached_keys : 701 max_cached_keys : 3907 hits : 49846 start_time : 1510766720 last_restart_time : 0 oom_restarts : 0 hash_restarts : 0 manual_restarts : 0 misses : 316 blacklist_misses : 0 blacklist_miss_ratio : 0 opcache_hit_rate : 99.370041066943
Server | Apache/2.4.18 (Ubuntu)
Configuration Backup | Thu, 16 Nov 2017 15:21:35 +1300
Language help_outlineTells whether the language is available or not.If it is not installed, you would need install the right operating system locales. More info at Wiki. | en_US.utf8
Encrypted Session help_outlineTells whether the session data are encrypted in the server or not | Yes

**Comment by nuxsmin** [comment]
Hi, could you tell me what value is being set in password expiry date field?

Regards
