### ISSUE TITLE
Change owner 

### ISSUE THREAD

**Issue by densanx** [nuxsmin/sysPass#783]
Hello.
The user worked in one department, was the owner of the account.
Moved to another department, changed the primary group, but he sees the password.
How can superadmin change the account owner?

**Comment by nuxsmin** [comment]
Hello,

unfortunately, there is currently no way to do it, bu be sure it will be able in next release.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in v3
