### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by reeslo** [nuxsmin/sysPass#784]
I am trying to install on hosting : 

Tried with 2 databases

sysPass database name : example.host.xxx:12345
```json
{"status":1,"description":"Unable to connect to the DB","action":"","data":[],"messages":["Please, check the connection parameters<br>SQLSTATE[HY000] [2002] Connection timed out"],"container":"","csrf":""}
```

sysPass database name : example.host.db

```json
{"status":1,"description":"Unable to connect to the DB","action":"","data":[],"messages":["Please, check the connection parameters<br>SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known"],"container":"","csrf":""}
```

Where I'm wrong ? :(

**Comment by nuxsmin** [comment]
Hi,

it seems that sysPass host cannot resolve the db host ip address. Did you check the name resolution is working fine?

Regards

**Comment by reeslo** [comment]
Hi, 
I don't understand "the name resolution", all data for the 2 databases are correct, if you mean this.

**Comment by nuxsmin** [comment]
Hi, name resolution is done by using DNS or hosts file.

Regards

**Comment by reeslo** [comment]
They work, It's internal hosts provided by hosting service with the web hosting. (OVH).

Thanks
