### ISSUE TITLE
Can't add filetypes with more than 4 characters.

### ISSUE THREAD

**Issue by pslobo** [nuxsmin/sysPass#786]
We want to store some files in SysPass, namely `.keystore` files and can't add anything with more than 4 characters. Could this possibly be more flexible?

**Comment by nuxsmin** [comment]
Sure, it'll be available in next minor release.

Thanks for the feedback!

**Comment by pslobo** [comment]
Hi, any update on this? Just updated to 2.1.16 in the hopes it would be implemented already but still nothing.

**Comment by nuxsmin** [comment]
Hello, sorry for the so late update...

sysPass v3 uses mime type checking for files uploading so extension checking is no longer needed.

Regards
