### ISSUE TITLE
Can't specify security groups on LDAP configuration 

### ISSUE THREAD

**Issue by blopp3** [nuxsmin/sysPass#787]
Hello,

In the LDAP configuration fields we can not specify a security group , I have searched on most of the topic but it doesn't seems to have a proper solution to my problem.

I have tried to specify the group by his name and even by cn=group... but nothing seems to work, syspass keeps returning the same error .

`Error while searching the group RDN
Group : (cn=\73\79\73\70\61\73\73\5f\61\70\69)
LDAP ERROR : Success (0)
LDAP FILTER : (cn=\73\79\73\70\61\73\73\5f\61\70\69)`

Thanks

**Comment by nuxsmin** [comment]
Hello,

I've been trying to find out what could be happening, because the  PHP LDAP functions should be able to use an hex converted dn.

Let me do some tests and I'll be back.

Thanks for the feedback!

Regards

**Comment by chrisgrave** [comment]
I am also experiencing this problem.

**Comment by ohmcno** [comment]
Having the same issue. Any update?

**Comment by ohmcno** [comment]
@nuxsmin Did you have a chance to look into this?

**Comment by nuxsmin** [comment]
@ohmcno I've been recently working on the LDAP implementation and I didn't get any clues about it. Is the group stored within the search base?.

Regards

**Comment by ohmcno** [comment]
Yes, that would be correct. I would be happy to send along anything you need to assist.

**Comment by nuxsmin** [comment]
@ohmcno could you tell me which is the action name that appears in the event log  row?

**Comment by ohmcno** [comment]
Sure: 
searchGroupDN
Error while searching the group RDNGroup : (cn=\57\44\54\53\20\55\73\65\72\73)
LDAP ERROR : No such object (32)
LDAP FILTER : (cn=\57\44\54\53\20\55\73\65\72\73)

**Comment by nuxsmin** [comment]
@ohmcno are there any more groups with the same name within the search base?

**Comment by ohmcno** [comment]
No - everything under that search base is unique.

**Comment by nuxsmin** [comment]
Hello, you could try out sysPass v3 as there were many improvements in LDAP implementation.

Regards
