### ISSUE TITLE
Login Loop: Session Finished

### ISSUE THREAD

**Issue by 8BrickDMG** [nuxsmin/sysPass#789]
Hi,

I'm having an issue logging into the system at the moment. After I've entered my username, password and 2FA code, I loop back to the beginning with the notification of "session finished".

I'm not too sure what to do. Any ideas?

I'm running the app in Docker and linking to an external database.

**Comment by 8BrickDMG** [comment]
I forgot to add that I can get in if I start a new web browser session but my colleagues and myself usually keep the same session open.

**Comment by nuxsmin** [comment]
Hi, it seems that the session files are being deleted by the garbage collector. It's usually configured to run through a cron job, so you would need to tweak it in order to avoid the session deletion.

Regards
