### ISSUE TITLE
RFE: Ability to test email setup

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#791]
It would be useful to be able to test the email notifications setup ("Test email" button or similar) from Syspass configuration.

**Comment by MagicFab** [comment]
I realize the Recipient email address is CC:ed when a configuration is saved, perhaps this could be improved in the UI and documented properly.

**Comment by nuxsmin** [comment]
I agree with you, email checks should be able to be done on mail setup. Regarding the "CC:ed" address, that's right, "Recipient" email address will be always "CC:ed" whenever an email is sent from sysPass (except recovering emails).

Regards

**Comment by nuxsmin** [comment]
Implemented in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
