### ISSUE TITLE
No error when using wrong SMTP credentials for mail setup

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#792]
When chaging SMTP credentials I made a mistake and used the wrong user. 
Email notiifcations didn't work and there was no indication in Syspass logs about this, the entry indicating email was CCed when saving the configuration was identical when it failed or succeeded.
Errors from PHPMailer should be relayed back the to Syspass web interface and logged accordingly.

**Comment by nuxsmin** [comment]
Said in #791

**Comment by nuxsmin** [comment]
Solved in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
