### ISSUE TITLE
Error while importing the LDAP users

### ISSUE THREAD

**Issue by sivanovie** [nuxsmin/sysPass#795]
Hi,

All was working fine for a good few weeks. Today I had to add a new user to the AD LDAP group of syspass, no changes to actual syspass. That typically would enable the user to login to syspass, this is what we have been doing so far.

When I logged in to syspass and checkek LDAP integration settings all looked ok. When I reload users I can see the new users appearing in syspass configuration, i.e. the user is loaded ok. Then I select to import the users and the error "Error while importing the LDAP users" appears.

Event log gives me this:

> 2017-12-05 13:07:24 Connection error (BIND)
> 2017-12-05 13:07:24 LDAP ERROR : Can't contact LDAP server (-1)
> 2017-12-05 13:07:24 LDAP DN : admin@pit.local
> 2017-12-05 13:07:24 Error while importing the LDAP users

I have disabled and enabled the LDAP integration to find the same result. I have tried to delete all LDAP users and then import them all fresh - a handful of the users failed to delete with the message:

> Error while querying
> SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`sysPass`.`accounts`,
> CONSTRAINT `fk_accounts_user_edit_id` FOREIGN KEY (`account_userEditId`) REFERENCES `usrData` (`user_id`)) (0)SQL : '
> DELETE
> FROM usrData
> WHERE user_id = ?
> LIMIT 1'

Here is syspass version information:

> 2.1 (2.1.15.17101701)
> SERVER_VERSION : 5.7.20
> CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
> SERVER_INFO : Uptime: 1573326 Threads: 1 Questions: 17357 Slow queries: 0 Opens: 597 Flush tables: 1 Open tables: 584 Queries per second avg: 0.011
> CONNECTION_STATUS : Localhost via UNIX socket
> Name: sysPass@localhost
> Version: 7.0.25
> Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, mcrypt, mysqlnd, PDO, Phar, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, zip
> Used Memory: 4096 KB
> User: root
> Apache/2.4.6 (CentOS) PHP/7.0.25
> Tue, 05 Dec 2017 13:05:17 +0000
> en_US.utf8
> No
> Loaded Plugins 	

Greetings!
Stan

**Comment by nuxsmin** [comment]
Hi,

by importing all the LDAP users it will create (or fail if email/login matches) again every user but be aware the they will lose the accounts linking (ie. permissions, etc). New LDAP users will be created on first login.

It seems that you're using an invalid user/pass when connecting to the LDAP server.

Greetings!

**Comment by sivanovie** [comment]
Hi and thanks for your reply.
The password was okay, eventually I changed the hostname to IP instead, as I had my doubts about the local DNS system.
Saved, synched and imported users, this time to succeed.

Seems like the problem was outside syspass.
Thanks for help.

**Comment by nuxsmin** [comment]
Hi,

I'm glad to hear that it works fine now.

Be aware that sysPass will pick up a DC from the listed in the DNS system, so there would be some wrong DNS records that were causing the issue. That's done so to avoid to use a fixed DC, because connection could fail anytime.

Greetings
