### ISSUE TITLE
Secondary groups can't edit accounts

### ISSUE THREAD

**Issue by wszychta** [nuxsmin/sysPass#796]
Hi,

We have discovered one bug. Users don't have edit access even if they are set like in picture below:
![image](https://user-images.githubusercontent.com/11636332/33715751-ee3081c4-db53-11e7-8019-de8fa094e270.png)
They can only read accounts.

The only way to add access to edit is to change their main group to the main group of account creator.

We have tested this issue on syspass 2.1.14 and 2.1.15.

Our environment:
OS: Centos 7
DB: MariaDB 5.5.56
Webserver: HTTPD 2.4.6 with PHP 5.6.31 (from webtatic repository)
Option Secondary Group Access is set to TRUE

Can you help us with this issue? If necessary, I will answer all the questions you need.

**Comment by wszychta** [comment]
Small update:

We discovered that edit is possible, but users can't do it from main page. They need to enter account details and then they can edit account or delete it

**Comment by wszychta** [comment]
Small update 2:

Sorry, but after restarting MariaDB and HTTPD we can't edit accounts. I don't know why we could do it earlier.

**Comment by nuxsmin** [comment]
Hi,

So sorry for the late reply, I missed your issue among others  and answered the easy ones first.

It's seems an UI issue, since you noticed that users who are granted to edit can do it by entering in the account details, but you said that after restarting MariaDB, you can't edit anymore. Is it still facing?

Kind regards

**Comment by wszychta** [comment]
Hi,

Yes, My users can't edit accounts anymore. Only users in creator's group can do this.

regards

**Comment by nuxsmin** [comment]
Hi,

Did you enable "Secondary Groups Access" option within "Configuration>Accounts" tab?

http://doc.syspass.org/en/application/permissions.html#acl

Regards

**Comment by wszychta** [comment]
Yes, I have this option enable in my config from the beggining .

**Comment by ortizleo** [comment]
Same problem?
[](https://github.com/nuxsmin/sysPass/issues/521)

**Comment by wszychta** [comment]
@ortizleo - I think that you are right, this can be the same issue

I have tried turning on "Show hidden actions", but the result is the same.
My users are able to edit accounts if they are creators of them.

**Comment by nuxsmin** [comment]
@wszychta @ortizleo sorry for the late feedback, but I couldn't reproduce the issue yet.

I've implemented sysPass in my company, in which there are ~50 colleagues using it. The accounts counting rounds 3000 and I haven't received any issue like this.

I'll let you know any advance on this.

Regards

**Comment by ortizleo** [comment]
@nuxsmin OK
How we can help? debug information maybe?
Below my application information:

2.1 (2.1.16.17110201)
--
Database | 
SERVER_VERSION : 5.5.56-MariaDB
CLIENT_VERSION : 5.5.56-MariaDB
PHP |
Version: 7.0.25 
Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, json, exif, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, shmop, SimpleXML, sockets, sqlite3, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, zip
Server |
Apache

Disabled SELINUX just to test but no success...

**Comment by wszychta** [comment]
@nuxsmin If you need any other informations just ask.
Can you tell us what environment are you using in your company? When I will have free time, I will check the same config in my company.

**Comment by nuxsmin** [comment]
@wszychta just for be sure, does your users profile enable editing?

I'm running sysPass on a Debian 9 server       using PHP 7 and MariaDB. I don't really think on an OS/service version issue.

Do the newly created accounts face the same issue?

**Comment by wszychta** [comment]
@nuxsmin I'm sure that all my user profiles are enable to edit accounts and passwords.
Yes, the problem is with exported accounts and new accounts.

**Comment by nuxsmin** [comment]
Hello, could you try out sysPass v3. There were many improvements that should have fixed this issue.

Regards
