### ISSUE TITLE
Login problem after updating passwords 

### ISSUE THREAD

**Issue by Canada514** [nuxsmin/sysPass#797]
Hello

 We encounter a number of problems with the syspass platform. Indeed it happens that in my company we have a validity period on our passwords. Since last week two people on the team had to change their password, but unfortunately when they wanted to connect to Syspass, it did not recognize their new password despite the LDAP is configured.

We undertook to delete the accounts in order to redo the synchronization. 

At the beginning the deletion did not work because of table relationships so we followed the ticket solution  (https://github.com/nuxsmin/sysPass/issues/606)

**@nuxsmin , I think you should fix that, as it is related to multiple tables.
I was able to remove the user only after that:
update accHistory set acchistory_userId=10 where acchistory_userId=61;
update accHistory set acchistory_userEditId=10 where acchistory_userEditId=61;
update accounts set account_userId=10 where account_userId=61;
update accounts set account_userEditId=10 where account_userEditId=61:**

 and the deletions worked.

The problem currently is that we no longer manage to synchronize these deleted accounts even by updating the ldap, the syspass does more transfers on its platform.

so both people can not connect anymore

What can we do ?

**Comment by nuxsmin** [comment]
Hello,

It's a weird issue since sysPass doesn't synchronize the LDAP user's data to use it at all. The LDAP data is saved to allow offline access (fallback), but the login process is always performed against the LDAP server, so removing the user account, won't take any effect.

Let me know about your environment (LDAP server version, sysPass version).

Kind regards

**Comment by nuxsmin** [comment]
Hello, did you get any progress on this issue?

**Comment by Canada514** [comment]
Hello

Sorry for the delay, i come back my office just yesterday cuz I was little sick.
Not yet its still same issue. I can get everybody but not the two accounts deleted.
I create a new account in our ldap and I get it too.
Any ideas ?

Thanks

De : RubénD [mailto:notifications@github.com]
Envoyé : 22 décembre 2017 07:36
À : nuxsmin/sysPass <sysPass@noreply.github.com>
Cc : Adams Ziba <aziba@crosemont.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [nuxsmin/sysPass] Login problem after updating passwords (#797)


Hello, did you get any progress on this issue?

**Comment by nuxsmin** [comment]
Hello, sysPass 3.1-RC1 has been released out, please check it out for solving this issue.

Regards
