### ISSUE TITLE
Error actualizar datos credencial

### ISSUE THREAD

**Issue by krubenrc** [nuxsmin/sysPass#798]
Hola, puede que el error ya se haya comentado.
Cuando tengo una credencial creada y se asigna a un grupo, si con la cuenta de administración voy a la credencial y cambio el grupo principal, salta error y no se actualiza.

Incluso a veces he visto que salta error en la modificación de una credencial pero luego sí se guarda.

Un saludo.

**Comment by nuxsmin** [comment]
Buenas, me podrías indicar el error que aparece?. No he detectado aún dicha incidencia en la versión más reciente, qué versión tienes instalada?

Saludos!

**Comment by krubenrc** [comment]
Es en la última versión, recién lo instale y me ha dado error en dos instalaciones (hice una de test, y luego otra real) no sé porque da ese error, si quieres puedo pasarte credenciales de acceso FTP y la url de acceso a la web.

Ejemplo, tengo una cuenta creada, entro, le doy a editar, le modifico cualquier dato, guardar, error.

![escritorio 1_006](https://user-images.githubusercontent.com/33639842/34032405-36e214e6-e176-11e7-99e9-16e5ee534e30.png)

**Comment by nuxsmin** [comment]
Buenas, hay algún error en el registro de eventos de sysPass?

**Comment by krubenrc** [comment]
Buenas, pues al final borré el sistema entero, y lo instale con docker. Con docker no aparece ningún error. Supongo que el problema vendría de la instalación de LAMP que no sería la optima para syspass.

**Comment by nuxsmin** [comment]
Me alegro que te funcione con Docker, es el futuro...

Todas las instalaciones que he hecho han sido en Linux (Debían 8/9, CentOS 6/7, Gentoo..) y no ha ocurrido esa incidencia.

Gracias por la info!
