### ISSUE TITLE
A lot of missing dutch translation

### ISSUE THREAD

**Issue by Nickske157** [nuxsmin/sysPass#800]
How to help with the translation?

For Example
Eliminar Cuenta -> Verwijder Account

**Comment by nuxsmin** [comment]
That would be great to get the Dutch translation completed!

You can contribute on Poeditor. I don't know the URL just now, but you could get it from sysPass website.

Regards

**Comment by Nickske157** [comment]
I have updates some important language strings with poedit.
How to upload the po and mo file to syspass githun?

**Comment by nuxsmin** [comment]
Sorry but I don't know if you can export the translation files in poeditor.

If you want to commit them to GitHub, you'd need to fork the sysPass repository commit your files, and then perform a pull request from sysPass repository. I think it's bit tedious workflow so I can export and commit to sysPass repo by myself.

Thanks for your contribution!
