### ISSUE TITLE
[Feature Request] Compact Single Row Layout 

### ISSUE THREAD

**Issue by rodobodolfo** [nuxsmin/sysPass#802]
Hello! Loving sysPass so far!
In my opinion, to much space is wasted on the second row of the grid, where the action panel is located.

Could we have a (maybe optional) single row layout? 

![image](https://user-images.githubusercontent.com/12578313/34044464-d4073dac-e183-11e7-8d1b-197e1765361c.png)

**Comment by nuxsmin** [comment]
Hello!

I'm glad to know you liked sysPass :)

Regarding the FR, I agree with you but be aware that accounts tags need to be placed and some icons related to wiki, public link, etc. too, so the second row, although it will be blank for some accounts, it's needed.

Thanks for the feedback!

**Comment by rodobodolfo** [comment]
Ah yes you are right. It makes sense, I guess my test accounts ding't used any of those features thats why i'm seeing a white space.
Thanks!
