### ISSUE TITLE
[Feature Request] Allow to set default customer and category (e.g. per profile)

### ISSUE THREAD

**Issue by RolfWojtech** [nuxsmin/sysPass#803]
Thank you for writing open source software!

My backgroup is usage in a company, coming from webpasswordsafe.
Something that you could improve upon a lot is how many fields a user has to set when creating a new Account. Since many use cases will not require multiple customers or categories, I propose the following feature:

Allow the admin to set a category and a customer as default.

Option 1: per profile
Option 2: per group
Option 3: in the "Edit Customer" dialog

When creating a new account, the user will have these options set to default and does not have to enter them individually.

An alternative would be caching the last used Customer and Category.

**Comment by nuxsmin** [comment]
@RolfWojtech I'm glad that you found sysPass useful!

I agree that this feature needs to be implemented (among others like default users/groups within accesses) because the time of creating a new account would be faster and some users are not granted to edit those fields.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Hello, this feature has already been implemented in v3. You can use item presets to achieve it.

Regards.

**Comment by pabloalbea** [comment]
> Hello, this feature has already been implemented in v3. You can use item presets to achieve it.
> 
> Regards.

Hi.
Do you mean in Items and Customizations / Preset Values?
I can't see the option to configure defaults Client and Category.
Thanks.

**Comment by twindscheif** [comment]
I also look for this and can't find the presets for client and category

**Comment by twindscheif** [comment]
I changed the following line to preset client/customer ([https://github.com/nuxsmin/sysPass/blob/6197c52af128b1aab48af5f5990c73279495617f/app/modules/web/themes/material-blue/views/account/account.inc#L104](url)
)
`($gotData && $client->getId() === $accountData->getClientId()  || !($gotData) && $client->getId() === 1)`

In my case the first customer has the id 1. Now if i create a new account the first customer is preset.
