### ISSUE TITLE
[Backup] Issue

### ISSUE THREAD

**Issue by Xaviius** [nuxsmin/sysPass#805]
Hey,

I'm already tryin the whole day to get it working but nothing works :(.
I have my Backupfiles the Database and my .xml. I have tried to get it work with XAMPP but i have alot of troubles with it. First I did download the latest Version of sysPass and then installed it local with MySQL got it working with no data. So i decided to import the database - in the installation i took the same name. So I also imported my .xml file and then nothing happened so I decided to logout and login again - so theres now the update, i try to install it but always I get the message: "Error al aplicar la actualización de la Base de Datos" and I just dont get it...

Log:
2017-12-17 01:36:00 - Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'account_otherGroupEdit'
2017-12-17 01:36:00 - #0  SP\Storage\DB->prepareQueryData() called at [C:\xampp\htdocs\inc\SP\Storage\DB.class.php:150]
#1  SP\Storage\DB->doQuery() called at [C:\xampp\htdocs\inc\SP\Storage\DB.class.php:341]
#2  SP\Storage\DB::getQuery() called at [C:\xampp\htdocs\inc\SP\Core\Upgrade\Upgrade.class.php:230]
#3  SP\Core\Upgrade\Upgrade::upgradeDB() called at [C:\xampp\htdocs\inc\SP\Core\Upgrade\Upgrade.class.php:87]
#4  SP\Core\Upgrade\Upgrade::doUpgrade() called at [C:\xampp\htdocs\inc\SP\Controller\MainActionController.class.php:101]
#5  SP\Controller\MainActionController->upgrade() called at [C:\xampp\htdocs\inc\SP\Controller\MainActionController.class.php:72]
#6  SP\Controller\MainActionController->doAction() called at [C:\xampp\htdocs\ajax\ajax_upgrade.php:36]

2017-12-17 01:36:00 - Fehler bei der Abfrage
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'account_otherGroupEdit' (0)
Caller 1: SP\Storage\DB\logDBException
Caller 2: SP\Storage\DB\getQuery
Caller 3: SP\Core\Upgrade\Upgrade\upgradeDB
Caller 4: SP\Core\Upgrade\Upgrade\doUpgrade
Caller 5: SP\Controller\MainActionController\upgrade
Caller 6: SP\Controller\MainActionController\doAction
2017-12-17 01:36:00 - SQL : 'ALTER TABLE `accounts`  ADD COLUMN `account_otherGroupEdit` BIT(1) NULL DEFAULT 0  AFTER `account_dateEdit`,  ADD COLUMN `account_otherUserEdit` BIT(1) NULL DEFAULT 0  AFTER `account_otherGroupEdit`'
2017-12-17 01:36:00 - Deregister Task: upgrade

I appreciate your help and effort!
Thank you.

**Comment by nuxsmin** [comment]
Hi,

Be aware that you don't need to install a new version before the upgrade, you need to use the current database and files instead, since the upgrade process will update the current installation automatically.

Please take a look to this comment:

https://github.com/nuxsmin/sysPass/issues/794#issuecomment-349346132

Regards

**Comment by Xaviius** [comment]
I fixed it thank you very much!
