### ISSUE TITLE
[Feature Request] Posibility to specify mail sender address (reply to) in smtp parameters

### ISSUE THREAD

**Issue by rodobodolfo** [nuxsmin/sysPass#806]
Hello again.
Im trying to set up Mail notifications, my server expect a specific sender account to validate.

I see only option to configure the recipient and *I think* is the address sysPass will use as sender.
Could we have an option to specify this? 

My SMTP log looks like this:

`
To: mail@domain.com.ar    

From: sysPass <mail@domain.com.ar>    

Reply-To: sysPass <mail@domain.com.ar>    

Subject: sysPass (Warning) - Make Backup    
`
EDIT: 
I see there is a  $mailFrom in config data but probably isnt exposed in the UI

Thanks!
Rodo.

**Comment by nuxsmin** [comment]
Hello @rodobodolfo

That's is right, the recipient email address is used for Cc every email when sending. The auth email is used to set the "from".

Btw there would be such feature in next version, among others like setting additional email addresses for Cc'ing.

Regards

**Comment by nuxsmin** [comment]
Implemented in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
