### ISSUE TITLE
Gestion de grupos + LDAP incompatible

### ISSUE THREAD

**Issue by corvusmod** [nuxsmin/sysPass#807]
Llevo un tiempo usando Syspass y realmente tiene el 90% de las cosas que necesito, pero hay una que me vuelve loco. Yo tengo un ldap con 20 usuarios, que cuando los importa a syspass los mete en un grupo creado especificamente llamada ldap_users.

La necesidad que tengo es que un usuario tiene que ser capaz de crear una cuenta, poderla compartir con otros usuarios, pero que estos usuarios no sean de su grupo. Es decir, si tenemos usu1, usu2 y usu3 del grupo ldap_users (todos importados del ldap), y usu1 esta en un grupo secundario grupo1 con usu2, quisiera que usu1 pudiese crear una cuenta, compartirla con usu2, pero que usu3 no la viese.

Esto parece ser que no es posible, porque cuando se crea una cuenta se le pone como grupo primario el del usuario que la creo y se comparte entre todos los usuarios de ese grupo.

¿Hay alguna forma de evitar eso?

**Comment by nuxsmin** [comment]
Hola @corvusmod

Me alegro que sysPass os sea útil ;)

Con respecto al uso de los grupos, no es necesario que los usuarios de LDAP estén en un mismo grupo, por lo que así podrías evitar el accesorio de usu3. Espero haberlo entendido bien...

Creo que sería un buena opción el incluir la denegación de usuarios en las cuentas para la próxima versión.

Saludos!

**Comment by corvusmod** [comment]
Entiendo entonces que si no asocio a todos los usuarios del ldap a un
grupo, no compartiran las cuentas entre todos,¿ verdad?

Lo probare en cuanto tenga un rato. Gracias

**Comment by corvusmod** [comment]
He intentado hacerlo como me has sugerido, pero nada. Cuando configuro el ldap, si no selecciono nada en el menu desplegable "Grupo por defecto", no me deja continuar, porque es un valor requerido.

Si selecciono ahi un grupo, todos los usuarios de ese grupo ven las mismas cuentas, cosa que quiero evitar (lo que en mi caso seria que todos los usuarios del ldap ven las mismas cuentas).

Por cierto. Feliz Navidad!!

**Comment by nuxsmin** [comment]
Buenas @corvusmod 

igualmente, Feliz Navidad!

En grupo por defecto se utiliza para importar los usuarios, pero posteriormente puedes modificarlo en cada usuario (pestaña de usuarios y accesos > Usuarios).

Saludos!

**Comment by corvusmod** [comment]
Entiendo...

Eso quiere decir que para que no compartan contraseñas por tener el mismo grupo primario, cada usuario tiene que tener un grupo unico, ¿verdad? Yo tengo pocos usuarios, unos 20, asi que mas o menos lo puedo hacer, pero entiendo que para grupos mas grandes, eso seria una locura :)

Hay alguna forma de que directamente no se compartan las cuentas entre el grupo primario, y solo se haga en los grupos secundarios? Es decir, si yo creo todos mis usuarios en el grupo LDAP, y las cuentas de ese grupo no se comparten, yo despues crearia un grupo TODOS, donde meteria a todos los usuarios, y tambien subgrupos por departamento, para que ellos se compartieran las cuentas entre ellos. Asi todos tendrian el grupo TODOS y el de su departamento, pero todas las cuentas no se propagarian a todos los usuarios del LDAP.

**Comment by nuxsmin** [comment]
> Eso quiere decir que para que no compartan contraseñas por tener el mismo grupo primario, cada usuario tiene que tener un grupo unico, ¿verdad? Yo tengo pocos usuarios, unos 20, asi que mas o menos lo puedo hacer, pero entiendo que para grupos mas grandes, eso seria una locura :)

Correcto, con el grupo primario se comparten las cuentas. Se podría (en próximas versiones) crear un grupo por cada usuario, pero ten en cuenta que una importación masiva de cientos de usuarios, crearía cientos de grupos, por lo que no sería una buena opción.

Actualmente la importación de LDAP se puede hacer de dos formas:

- Automática: cuando se realiza login con un usuario de LDAP, se crea automáticamente con el perfil y grupo por defecto, pero la cuenta queda desactivada para modificarla antes de que acceda a la aplicación.
- Manual: mediante la importación que has realizado.

Entiendo la problemática, pero es dificil de solventar de forma automática (agrupar usuarios por grupos en la importación).

Saludos!

**Comment by corvusmod** [comment]
Pues mi gozo en un pozo entonces, porque Syspass es el que cumple todo lo que necesito (a parte de ser el mas bonito), justo menos eso, que todos los usuarios del mismo grupo no compartan las contraseñas :(

Por lo demas un gestor de contraseñas genial.

Por mi parte cierro el ticket
