### ISSUE TITLE
Timeout sesion

### ISSUE THREAD

**Issue by krubenrc** [nuxsmin/sysPass#809]
Hola, siento volverte a molestar jeje. Cuando pasan 5, 10 minutos, me cierra la sesión automáticamente, he modificado el php.ini para aumentar el recolector de sesiones y aun así no funciona, ¿sabes como puedo cambiarlo? gracias de antemano!!!

**Comment by nuxsmin** [comment]
Hola!

Si has modificado la configuración de PHP y la de sysPass, no se me ocurre qué puede pasar.

En qué SO está instalado?

**Comment by krubenrc** [comment]
Está instalado en un linux ubuntu server 16.04 sobre docker. He cambiado session.gc_maxlifetime, he mirado el crontab que comentaste en otro post, y no consigo cambiarlo.

Es bastante frustrante ya que lo uso durante 6-8h al día y tengo que meter las credenciales muchísimas veces, y encima la clave no es sencilla jajaja

¿En syspass hay algo que se pueda modificar para aumentar el tiempo de sesion?

Un saludo! gracias!!

**Comment by nuxsmin** [comment]
Hola, en la configuración de sysPass es posible establecer el timeout (por defecto 5 min.)

![captura_277](https://user-images.githubusercontent.com/1775774/34383195-e40094ee-eb13-11e7-8f24-077b4d2178ad.png)

**Comment by krubenrc** [comment]
Me faltaba eso!! lo leí en un antiguo post, y habré dado 50 vueltas por la configuración y no lo vi... Eso junto con el session.gc_maxlifetime de php.ini ya está solucionado. Gracias!!!
