### ISSUE TITLE
Please add a way to change the 'main group' for an account

### ISSUE THREAD

**Issue by cfinch** [nuxsmin/sysPass#81]
I cannot find any way to change the main group of an account after it has been created. Since the main group determines which users can see the account, there should be a way to change it in the GUI. If an account was created with a 'main group' that did not sufficiently restrict access, access cannot be limited by adding supplemental groups.

**Comment by nuxsmin** [comment]
Hi, you're right, account's main group cannot be changed.

It's easy to code it ;)

It will be available in short

**Comment by cfinch** [comment]
Thank you!

**Comment by danislav** [comment]
Mil gracias :)
:+1:

**Comment by Mattyx** [comment]
Shouldn't a user be able to set the account main group when creating the account itself?
I can't find a way to enable a non AppAdmin or AccountAdmin user to do this.

It would be very useful if you want to create an account not visible by the members of your primary group but visible only by the members of your secondary groups.

Thanks in advance
