### ISSUE TITLE
[Feature Request] Possibilty to remove shared links

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#811]
Hello,

it is possible to share Accounts to other users by URL directly on edit field. 

![grafik](https://user-images.githubusercontent.com/5631071/34381446-d49f2cb4-eb08-11e7-9f14-d1525a97451d.png)

i think there just should be a button next to public link to destroy it

**Comment by nuxsmin** [comment]
Hello @vmario89 , it can be done from the "Users & Accesses" menu, in the "Links" tab. So users can create/update (ie. renew)  links, but not removing if they haven't got access to links management.

**Comment by vmario89** [comment]
Dear @nuxsmin , yes i found this option, thanks :). 

I just thought it would make sense to configure the link sharing by the user himself (who wants to share his account data), because if he wants to share he also might want to unshare. for example in case of wrong selection/wrong publication.

**Comment by nuxsmin** [comment]
Hello @vmario89

I agree that the user should be able to delete the public link, indeed the link creator is saved among the data, so it would be feasible to let him only to delete the link. Noted for next release ;)

Kind regards

**Comment by deajan** [comment]
+1

**Comment by nuxsmin** [comment]
Implemented in latest commit

**Comment by vmario89** [comment]
appears also by email:
![grafik](https://user-images.githubusercontent.com/5631071/46634654-ce603080-cb51-11e8-864f-dad0370b49b4.png)
