### ISSUE TITLE
[Feature Request] mass data change

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#812]
Hello,

just an idea which i came up after importing data from foreign sources: I'd like to mass-change account data sets in the way that i like to select for example 10 accounts and change their category, customer, access, ...

**Comment by nuxsmin** [comment]
Hello,

I've been really thinking on this feature, since many times you need to change a bunch of data from the accounts and setting thrm one by one is a real pain.

Thanks for the feedback!

Kind regards

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in v3.

Regards.
