### ISSUE TITLE
[Feature request] Merge data sets

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#814]
And another idea xD

it would be a dream to merge accounts from 
... category A and category B to new category C  ....or just from ... category A to B ... or from .... B to A
same scenario with customers.  could this be done? 

ps: sorry for much issues spamming. I just got "stuck" into sysPass and i really like it. So i like to contribute as much as i can.

**Comment by nuxsmin** [comment]
Do you mean to change the accounts category/customer in batch mode?

I really appreciate your ideas, and be sure that this kind of contribution makes sysPass more useful ;)

**Comment by vmario89** [comment]
hey,

yes just a kind of menu to select some categories/customers and all their linked accounts to change to another category/customer in the way of merging. this means that after merging one ore more categories or customers can be empty or have less accounts linked. there could be an option to delete empty categories/customers after merging too

**Comment by nuxsmin** [comment]
Hey, this feature has already been implemented in v3. You can use accounts bulk edit to achieve it.

Regards.
