### ISSUE TITLE
Improve generic CSV import

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#815]
I did several imports with sysPass and got some failures which i like to report

i tried to import KeePass CSV files but this was impossible at first because the output of KeyPass generates 5 columns, but sysPass requires 7 columns. So i edited the KeePass csv to add 2 additional empty columns. I also renamed all columns on the way sysPass requires: "account_name";"customer";"category";"url";"user";"password";"notes"

so i imported 275 account lines with sysPass. What i forgot while importing was to set the order of the columns. Now i have 275 wrong datasets. Please see this for example:

![csv import fail](https://user-images.githubusercontent.com/5631071/34610460-77fcb56a-f221-11e7-9462-3f651691ba46.jpg)

Could you rewrite the importer in that way it ignores the static column order? Instead it should check where the correct columns are. In short: give possibility to do import pattern like

"category";"url";"user";"password";"notes";"account_name";"customer"
"category";"url";"user""account_name";"customer";"password";"notes"
"account_name";"customer";"category";"url";"user";"password";"notes"

and so on ....

**Comment by vmario89** [comment]
additional comment: Now deleting the 275 wrong items is pure pain, because there is no possible way to select all those accounts at once. Only way i see is to kill with SQL command but i do not know side effects.

**Comment by vmario89** [comment]
info: deletion worked for me the simple way by logging into phpMyAdmin@MariaDB and deleting entries

DELETE FROM accounts WHERE account_customerId != 2

**Comment by nuxsmin** [comment]
Hello, the batch item processing will be improved in next release. You did right by deleting those items, since there are no linked items yet it was possible.

Regards
