### ISSUE TITLE
[Feature request] Enforce 2FA for selected users and groups

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#816]
Hello,

just installed the 2fa plugin from your git and it works like a charm. I actually think this could be pimped up in security. I could imagine to have an option to force the usage of 2FA functionality. This would be suitable to give extra security for special admin users (the editors of ressources, settings, ...)

just an imaginary bitmap:

![grafik](https://user-images.githubusercontent.com/5631071/34612654-edfa73ca-f22a-11e7-970a-6b1ac5bfb8b9.png)

**Comment by nuxsmin** [comment]
Hello, this is already listed in sysPass roadmap #422

Thanks for the feedback!

**Comment by vmario89** [comment]
sorry, overseen! There are so many feature requests :D hope to contribute some code too. please close this issue due to duplicity

**Comment by nuxsmin** [comment]
@vmario89 no worries ;)
