### ISSUE TITLE
[Odd behaviour] KeePass import

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#817]
Hello,
as i found out, importing KeePass XML imports old history entries too. I accidently imported now 475 instead of 275 accounts because 200 entries were stored in history. They messed up my whole database.

These should be ignored by sysPass or there should be an option to ignore history. I think this is a problem because sysPass import parser just looks for the tag "Entry". it should control if the parent is "History"

The workaround for importing current passwords only is to clean the KeePass database before. 

1. Therefore just make a copy of your kdbx-file
2. then open Database Maintainance....
![grafik](https://user-images.githubusercontent.com/5631071/34613658-cb86dc6c-f22e-11e7-8ec0-c857d706e437.png)

3. remove history
![grafik](https://user-images.githubusercontent.com/5631071/34613664-d53f83b2-f22e-11e7-9b1f-38fe78ad7204.png)
just type "0" for deleting all history and push button "Delete".

4. export KeePass XML file and import into sysPass

**Comment by nuxsmin** [comment]
Hello, you're right, those entries should be either ignored or give an option to decide which to do.

Noted for next version ;)

Did you have any more issue with the import?

Thanks for the feedback!

**Comment by vmario89** [comment]
hi Ruben!

actually i did not recognize more bugs than i mentioned 
**except** the behaviour, that imported accounts may have blank customers/categories (and maybe other fields), while manually created accounts must habe customers/categories/passwor/user. Please see https://github.com/nuxsmin/sysPass/issues/804 

i recognized too that importing many accounts is really slow. Importing 475 xml OR csv accounts took about 3~5 minutes for each job. I know the statement "It isn’t like APT: doesn’t have Super Cow Powers!!" but i think it's just slow because the parser might not work effiently - but i don't know whats the real reason.

best regards, Mario

**Comment by nuxsmin** [comment]
Hi Mario,

Regarding the fields behaviour, they're required because the database constraints and it would be so too through the web UI or API.

The time spent on importing is due to the  strong encryption used. Please, notice that a regular master password change would run at about 2,4 accounts per second (measured on IBM Xeon server and EMC Raid 5 storage)

Every encryption mechanism should be secured for timming attacks, so the encryption algorithm runs its functions using a random delay and a cost, to make it harder to break.

Kind regards,

Rubén D.

**Comment by vmario89** [comment]
thanks Ruben,

encryption cycle time makes sense. i did not think about this. Maybe this could be another improvement: give a visible hint for user that starting to import may take a really long time + block the session by javascript (if not already done) so the user has to agree leaving the screen if import is running and user changes window (to prevent breaking the import). I am not at work now an dont have access to the server to test the behaviour now.

alternative solution for import: queue import into background so user session does not get blocked while sysPass imports csv/xml.

**Comment by nuxsmin** [comment]
You're right Mario, some import feedback about the progress would be fine, it's done on master password change and upgrade processes indeed.

Noted for next version ;)

Thanks for the feedback!

**Comment by vmario89** [comment]
i guess the next version will need much more time and will be a huge release. just take the time you need :D it seems the feature requests from community are tall like mount everest.

**Comment by nuxsmin** [comment]
Sure! It will be a major release because major changes in the API. The requested features will be implemented through v3 lifecycle, so I hope to get it by the end of February.

**Comment by vmario89** [comment]
i got another idea for import (because i am doing many imports right now): would be great to have the possibilty to double check. If you select a file in the dialog

![grafik](https://user-images.githubusercontent.com/5631071/34667627-15da101c-f46a-11e7-9527-73413f55388b.png)

it gets uploaded automatically and no chance to stop it. Maybe a preview with "okay, do it" and "cancel" button would be nice. And maybe a function to rollback imports which were done accidently

**Comment by nuxsmin** [comment]
Hmmw, it would be useful but a bit tough to implement, since categories and customers are created on the fly so I would need to keep a track of the changes and then commit them from an intermediate file, because database transactions couldn't be used.

I'm aware that there would be many useful improvements like this one, but I sadly need to filter out which ones will have a wider impact since the lack of time makes it hard to implement all.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Regarding an email that you sent to me through WP blog, your email provider sent me back a response about blocking it. Nevermind, I've done the changes on the website to get the sharing links working.

I've send another email to other address regarding the donation, did you receive it?

Regards

**Comment by nuxsmin** [comment]
Regarding an email that you sent to me through WP blog, your email provider sent me back a response about blocking it. Nevermind, I've done the changes on the website to get the sharing links working.

I've send another email to other address regarding the donation, did you receive it?

Regards

**Comment by nuxsmin** [comment]
Regarding an email that you sent to me through WP blog, your email provider sent me back a response about blocking it. Nevermind, I've done the changes on the website to get the sharing links working.

I've send another email to other address regarding the donation, did you receive it?

Regards

**Comment by nuxsmin** [comment]
Regarding an email that you sent to me through WP blog, your email provider sent me back a response about blocking it. Nevermind, I've done the changes on the website to get the sharing links working.

I've send another email to other address regarding the donation, did you receive it?

Regards

**Comment by nuxsmin** [comment]
Regarding an email that you sent to me through WP blog, your email provider sent me back a response about blocking it. Nevermind, I've done the changes on the website to get the sharing links working.

I've send another email to other address regarding the donation, did you receive it?

Regards

**Comment by nuxsmin** [comment]
It seems that mobile app sent several posts...

**Comment by vmario89** [comment]
hey,
no i did not get an email but its no problem. just some pocket money for some coffee for you ^^

**Comment by vmario89** [comment]
> I'm aware that there would be many useful improvements like this one, but I sadly need to filter out which ones will have a wider impact since the lack of time makes it hard to implement all.

yes i know. days are too short. was just an idea which came up when i had to struggle with import. but its totally normal to do some "workarounds".

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in v3. Thanks for the feedback!

Regards
