### ISSUE TITLE
[Question] Linked Accounts

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#822]
Hello,

i have a question about using linked accounts. I cannot find something about this in the documentation **https://doc.syspass.org/en**. 

When i create an Account A and an Account B i have a password and a user for both accounts each. Now when linking Account A to Account B, B gets the parent and A gets child dependency. After linking the parent shows the child account and the parent shows the parent acount. This is quite okay und fully logical.

Now my question: Why the child account A may still have a different username than parent Account B? Because child A shares password from B, why not sharing the user too? This causes to ask for the sense of this feature. I am missing a real world example for the use of that. I think it does not make sense to link an account with different user, but same password

Maybe linking could have the feature to select what data should be inherited from parent.

kind regards, Mario

**Comment by vmario89** [comment]
By the way i recognized when deleting the parent account there should be a warning that linked children lose their link to it. This means when killing the parent under circumstances you create thrashy account data like this error provides:

![grafik](https://user-images.githubusercontent.com/5631071/34821043-ad25a0da-f6c2-11e7-88da-2cef10f80ce6.png)

It would be nice to build in a check for this or the possibilty to clone the password into child when deleting the parent. Otherwise data may get lost.

**Comment by radoslawrewinkowski** [comment]
I looks like a bug. I think B should have separate user and password, because it's only a shortcut to parent. It would be a nice tool for making groups like server/application.

**Comment by vmario89** [comment]
i think linking should be used as an alias for accounts which means you have 3 accounts with different names and maybe urls, categories and customers BUT same password + user

grouping of accounts into some containers, which could be unterstood as some sort of systems, sounds really good to me

**Comment by nuxsmin** [comment]
@vmario89 that's the intended behaviour, since some accounts like LDAP/AD users would be allowed to log into several servers, so you can create a base account and link the others (servers, services -ie http, ftp, etc-) to it, so the "child" accounts would really hold their specific data like URL notes or custom fields.
