### ISSUE TITLE
No puedo logarme tras la instalacion

### ISSUE THREAD

**Issue by supkk** [nuxsmin/sysPass#828]
Buenos días,

he instalado la version 2.1.15.17101701 de syspass en un RHEL 7. Tras terminar esta correctamente y hacer la configuración de BBDD y actualizacion posterior, no consigo entrar en la aplicación.  Me logo con el usuario que se ha creado en la instalacion (admin/*****) y me aparece continuamente la pantalla de login. 

No es problema de password ya que si pongon una erronea me devuelve un error. ¿Alguna idea?

Un Saludo

**Comment by supkk** [comment]
Solucionado: El proceso no podia escribir en /var/lib/php/session 

Un saludo

**Comment by nuxsmin** [comment]
@supkk me alegro que se haya solucionado! Está incidencia se me olvidó responderla....y hasta pensé en que sería algo relacionado con selinux...

Gracias por la información!
