### ISSUE TITLE
[Bug] Wrong message when deleting undeletable category

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#832]
i figured out that deleting a category, which is not deletable (because it is used by an account item) shows up the message with good news "Categories deleted" but the event log tells that there was an error.

![grafik](https://user-images.githubusercontent.com/5631071/34947657-0b5f6df2-fa0b-11e7-8188-1b5defbb9546.png)

![grafik](https://user-images.githubusercontent.com/5631071/34947683-27dcf7c4-fa0b-11e7-99f7-a8ec83ca32c1.png)

this issue is similar to https://github.com/nuxsmin/sysPass/issues/810 but i wanted to report it because in this case there are overlapping two events/messages

**Comment by nuxsmin** [comment]
Hey, that is right since there is no tracking when categories are deleted in a batch processing, so it will show up that they were deleted, although some of them didn't.

It will be improved in next release.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Fixed in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
