### ISSUE TITLE
[Bug] Irritating message when restoring forgotten password

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#834]
Hello,

when restoring a lost password the message type does not fit to the content. It's displayed in evil red but should be a green notice instead:

![grafik](https://user-images.githubusercontent.com/5631071/35117133-f849c70a-fc8d-11e7-80c0-f42529d91c40.png)

regards, Mario

**Comment by nuxsmin** [comment]
Fixed in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
