### ISSUE TITLE
[Bug] User Interface wrong tab display when deleting or modifying Tag

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#836]
While editing Tags i noticed a small bug which comsumes time because it makes editing uncomfortable.

Please try to edit an existing Tag or delete a Tag. After doing one of this actions you are going to be redirected to the "Categories" tab. To edit more Tags you have to switch back to the "Tags" tab. 

It does not happen when you add new Tags on the Tag tab.

regards, Mario

**Comment by nuxsmin** [comment]
Solved in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
