### ISSUE TITLE
Improve Tag Editing

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#838]
Hello,

if you create a new Tag by pressing "+" an input windows shows up. There is missing autofocus. The user has to click into the field "Tag name" to set input. 

![grafik](https://user-images.githubusercontent.com/5631071/35117925-7cccb04e-fc90-11e7-9f8d-8b29ac472f23.png)

![grafik](https://user-images.githubusercontent.com/5631071/35117933-854e425a-fc90-11e7-9699-15fc8e3083df.png)

thanks, Mario :)

**Comment by vmario89** [comment]
![grafik](https://user-images.githubusercontent.com/5631071/35118264-873d286e-fc91-11e7-9349-371e54868ef5.png)

![grafik](https://user-images.githubusercontent.com/5631071/35118271-8b2ffd5c-fc91-11e7-9c5c-6fe8f278ba29.png)
Have some additional issues by evaluating some randomness with different characters. I think Tags should be regulated in the way like twitter hashtags are treated: use only words without non-alphabet chars (no _,.:) or to allow chars in a more controlled way

![grafik](https://user-images.githubusercontent.com/5631071/35118276-8fb90436-fc91-11e7-9048-351bebd61648.png)

![grafik](https://user-images.githubusercontent.com/5631071/35118292-97c758b2-fc91-11e7-9a73-ac885675eb1c.png)

![grafik](https://user-images.githubusercontent.com/5631071/35118299-9e099852-fc91-11e7-88f8-21e392e36030.png)

**Comment by vmario89** [comment]
sorry for much comments. i wrote a checklist with some things i recognized to give rich feedback.

belonging to the Event Log there are no Entries generated when creating, deleting or modifying Tags

**Comment by vmario89** [comment]
Hello,

i came up with the idea to have the possibility in account editing to have a "plus" button to add Tags.
![grafik](https://user-images.githubusercontent.com/5631071/35264014-56694960-001b-11e8-9f47-a79cedaa6308.png)

Could be done the same way like adding customers and categories an the fly in the same menu:
![grafik](https://user-images.githubusercontent.com/5631071/35264025-66140260-001b-11e8-8ad6-ba5ae2191439.png)

**Comment by nuxsmin** [comment]
Hello, this feature was implemented in v3.

Thanks for the feedback!
