### ISSUE TITLE
Small Improvement for Mail Event

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#840]
Hello,

by playing around with most syspass settings i recognized the following: If you enable Mail settings sysPass will send each event to the mailbox of the recipient. When you disable mail events no longer will be mailed.
In an adminstrative perspective i think it makes sense to send a "last" email to the recipient to inform him that emails are no longer configured.
in current situation disabling mail means: no more mails. no admin will ever see that emails are disabled except they are going to login later to check whats going on like "hmmm, there was no syspass mail for 5 hours now. what could it be?"

regards, Mario^^

**Comment by nuxsmin** [comment]
Hello, this feature was implemented in v3

Thanks for the feedback!
