### ISSUE TITLE
UI Improvement for search

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#841]
Hello,

in my opinion the tag search field should be visible all the time. In the up-to-date version you need to press "+" to show Tag search. Sometimes it confuses because an active filter is configured with selected Tags but the Tags are not visible, because the field is hidden. This leads to "???" when having a blank result set but you dont know why:

this is a search case where i only searched for the tag "Icinga". as you can see you can see nothing. When the display updates the result view the selected tag gets unvisible. This leads to errors if you type now something into the text search which does not fit to "Icinga". In this case it's "blubb"

![grafik](https://user-images.githubusercontent.com/5631071/35119117-3f1a66fc-fc94-11e7-8981-8a2d6202e0a3.png)
![grafik](https://user-images.githubusercontent.com/5631071/35119234-9fc0ebd4-fc94-11e7-9ec8-a5455d8a285c.png)
-------------------
![grafik](https://user-images.githubusercontent.com/5631071/35119248-ac6bd93e-fc94-11e7-926b-606c86bd5e1a.png)

-------------------
click now on the search button again. the filter is still active
![grafik](https://user-images.githubusercontent.com/5631071/35119275-bb96934a-fc94-11e7-8ab8-4c6cc7ed8c83.png)
-------------------
![grafik](https://user-images.githubusercontent.com/5631071/35119288-c0fe6d6c-fc94-11e7-98b9-f64694dd765d.png)
-----------------------
now type "blubb"
![grafik](https://user-images.githubusercontent.com/5631071/35119299-cb083c02-fc94-11e7-8889-d4689e32cc11.png)
---> no result
--------------------------
now press "+" to reveal active tag again
![grafik](https://user-images.githubusercontent.com/5631071/35119317-d7ace9da-fc94-11e7-8808-e7f716396b7d.png)
----------------------
remove "icinga"
![grafik](https://user-images.githubusercontent.com/5631071/35119332-dffefbd2-fc94-11e7-83d0-a2b8ab0fe2f2.png)

tadaaa

**Comment by nuxsmin** [comment]
Solved in v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
