### ISSUE TITLE
Improvement for Tag sorting

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#842]
Hello,

would it be possible to automatically sort assigned tags by alphabet?
![grafik](https://user-images.githubusercontent.com/5631071/35119750-3618cd62-fc96-11e7-8c0c-7f06290c003b.png)

i have some items with ~ 6-8 tags which is messy if it's unsorted.

regards, Mario

**Comment by vmario89** [comment]
whoops sorry for this ticket. i messed up my own notes. Please close it, because actually there is no bug xD my fault 👎

**Comment by nuxsmin** [comment]
Thanks for the feedback!
