### ISSUE TITLE
Event log using Mail spams mailboxes and brings explosions

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#843]
Hello,

the eventlog mailing by Email is quite cool but messy too. Is it possible to give options to select from for:
* event types
* set filter for names in event (eg. send only emails which contain 'reset' in event name)
* log error levels

this would help to reduce spam load. I know that it's easy to setup a new mailbox and use it for syspass only but the wetter way could be to have some selections what events have an email trigger.

regards, Mario

---------
last ticket for today and next time i think 🐙 i collected many things to report them fluently.

**Comment by nuxsmin** [comment]
Hello, I really agree with all features/bugs submitted, and I'm committed to get a better new version which will solve and implement many of them.

Work in progress!

Thanks for your contribution, testers and  third party feedback is very much appreciated.

Regards.

**Comment by nuxsmin** [comment]
Partially implemented in v·: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
