### ISSUE TITLE
Event log: Add event for downloading backup/export files

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#848]
Hello,
little idea: when you generate a backup of syspass an entry for event log is generated. For better audit it would be nice to add an event log entry when these files where downloaded (which admin/IP/date). Because a generated backup can be spread to different locations on different time.

kind regards, Mario

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in v3. New events are generated for backup and export operations.

Regards.
