### ISSUE TITLE
[Bug] User preferences are not applied for fresh users

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#849]
Hello,

i got a problem (experienced several times) when creating a new user: If the new user logs in his settings are not working:
![grafik](https://user-images.githubusercontent.com/5631071/35211830-588e0d52-ff58-11e7-9941-dc28d31ec90b.png)

the first view of user is always language = Catalá and all settings are disabled. The search results as cards are disabled but the user gets visualized by cards. The language also is the global as set by admin ( != catalá). Seems that the settings do not grip.

but the work as soon as you change at least one setting.

**Comment by nuxsmin** [comment]
Hello,

That's the right behaviour, since the user's preferences aren't being set yet, so  they are displayed without any selected item.

Regards

**Comment by vmario89** [comment]
Hello Ruben,

hmm its not a big thing but i think the settings should always display the state it is in real. Otherwise it looks a little bit untrusty. (cards display off but cards display on looks like a bug for the user). A small hint would solve the topic. A popup message like "Dear new user, you did not update your settings yet. You can customize for yourself... " etc. blabla^^

have a nice evening, Mario

**Comment by nuxsmin** [comment]
Hey!

Sure, be aware that global settings are being applied unless the preferences are set. A notice could be sent on first login, but I didn't want to disturb with this kind of messages which would need to be shipped within the code, so I decided to let sysPass admins to decide which would be the best way to train their users.

BTW I'll study how to improve this behaviour.

Thanks for the feedback ;)

Good night!

**Comment by nuxsmin** [comment]
It could be done by global notifications.
