### ISSUE TITLE
[Feature Request] Transfer account from one owner/creator to another

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#850]
Hey,

as the title says i want to be able to create accounts and to set a new hardcoded owner. Actually this is only possible by changing id's in SQL:

- account_userGroupId
- account_userId
- account_userEditId

use case: an administrator creates some credentials for a new employee.

kind regards, Mario

**Comment by nuxsmin** [comment]
Hello,

you're right and this was planned for next release.

Regards

**Comment by vmario89** [comment]
Hey @nuxsmin , i think i made a duplicate of this https://github.com/nuxsmin/sysPass/issues/850 
Think you can close this. Regards, Mario
