### ISSUE TITLE
LDAP user has forgotten previous password

### ISSUE THREAD

**Issue by mredaelli** [nuxsmin/sysPass#852]
We use LDAP integration.
One of my users has changed his password in Windows, tried to login to Syspass and was asked for the old password, which he does not remember ^_^
What should we do?

**Comment by nuxsmin** [comment]
Hello, that's the normal behaviour, since sysPass needs the old password to decrypt the master password. If he doesn't know his previous password, let it blank and click on login, it will ask for the master password (could be a temporary one).

Regards

**Comment by mredaelli** [comment]
Thanks!
