### ISSUE TITLE
How to import account as "private" or "private for group" ?

### ISSUE THREAD

**Issue by lcworld** [nuxsmin/sysPass#857]
Hello

I imported some accounts from csv (100 accounts), specifiing default  user and group.
But all passwords are public.

Is there a way to import them as private or private for group ?
If not, is it possible to do it after with a command line query ?
Or with a SQL query ?

Best regards

PS I check API documentation, there is nothing about visibility of account in addAccount.

**Comment by vmario89** [comment]
hello,

selecting via website options is not possible :( Documentation for this is missing, this is right.

but you can fix it by some simple sql sequences. You can use phpMyAdmin or DBVisualizer for example. Just connect to your MySQL/MariaDB

**Comment by rokx** [comment]
For anyone wondering, the query is:
`update accounts set account_isPrivateGroup = b'1';`
`update accounts set account_isPrivate = b'1';`

Warning: This will update all accounts.

**Comment by nuxsmin** [comment]
Hello, this is not possible in v2, but it is on v3 through the API instead.  Only API?, Yes it's the only way since the other methods are intended to import/export from/to other applications.

Regards.
