### ISSUE TITLE
Blank index when installing

### ISSUE THREAD

**Issue by Blai01** [nuxsmin/sysPass#859]
Hi,

I followed the steps to install sysPass on Debian 9 with PHP Version 7.0.27-0+deb9u1and MariaDB.

When I go to the final step of the installation, open http://host_ip/syspass/index.php

index.php appears white, no text displayed. 

If I create a quick something.php and put php code in it, it works, but syspass index appears white...

Any suggestions?

**Comment by diogenxs** [comment]
Make sure that module mbstring is active and enable
`apt-get install php-mbstring`
and restart apache
`systemctl restart apache2`

for me that solved

**Comment by vmario89** [comment]
i agree. got the same problem when php-mbstring was missing

**Comment by Blai01** [comment]
Solved, thanks guys

**Comment by nuxsmin** [comment]
Thanks for your support!
