### ISSUE TITLE
Request for usability improvements

### ISSUE THREAD

**Issue by cfinch** [nuxsmin/sysPass#86]
sysPass is already pretty user-friendly, but after hours of using it, I have two small suggestions to improve the user interface.
 
1. The buttons on the left-hand menu highlight when the mouse moves over them, but you cannot actually "press" the button unless the cursor is over the icon at the center of the button. I would like to be able to click anywhere on the button to "press" it.
2. The arrows that allow you to navigate through pages of accounts can only be found on the bottom right corner of the page. Those arrows should be duplicated at the top of the page (right below the "accounts per page field). When I am navigating through many accounts, I don't want to have to scroll to the bottom of the page in order to go to the next page.

These small changes will make sysPass more efficient for managing large numbers of accounts.

**Comment by nuxsmin** [comment]
You're right, there are many improvements that can be done for better usability and I want to perform them on every release that is launched.

Thank you for that points, they are very easy to implement and keep sure that next release will get them.

Kind regards.

**Comment by nuxsmin** [comment]
Hi, the newly release 1.2RC5 brings a lot of changes that improves general usability.

Hope you find it useful ;)
