### ISSUE TITLE
Error 500 when entering Web Browser

### ISSUE THREAD

**Issue by estelarules** [nuxsmin/sysPass#860]
Hello,

I have a problem with my Apache configuration. I will like to say that I am new in this world.
When I enter to the Browser and try to "localhsot" I receive the 500 error.
These are my logs:

> [Thu Jan 25 10:57:27.912791 2018] [mpm_prefork:notice] [pid 15368] AH00170: caught SIGWINCH, shutting down gracefully
> [Thu Jan 25 11:04:56.871323 2018] [core:notice] [pid 3560] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
> [Thu Jan 25 11:04:56.890756 2018] [suexec:notice] [pid 3560] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
> AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using fe80::fc02:8db8:e533:4a58. Set the 'ServerName' directive globally to suppress this message
> [Thu Jan 25 11:04:57.285393 2018] [auth_digest:notice] [pid 3560] AH01757: generating secret for digest authentication ...
> [Thu Jan 25 11:04:57.286744 2018] [lbmethod_heartbeat:notice] [pid 3560] AH02282: No slotmem from mod_heartmonitor
> [Thu Jan 25 11:04:57.326176 2018] [mpm_prefork:notice] [pid 3560] AH00163: Apache/2.4.6 (CentOS) configured -- resuming normal operations
> [Thu Jan 25 11:04:57.326203 2018] [core:notice] [pid 3560] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

I have being trying to find the solution for the past 3 days. I reached the conclusion that it might be a permissions problem. 
Any ideas?

Thanks in advanced

**Comment by vmario89** [comment]
hey,

did you check if your folders and files are in the permission group "www-data" of the apache user? if not users from outside (the web) cannot enter the page.

**Comment by estelarules** [comment]
How can I check that?
They should be able as I am trying to configure apache against Active Directory.

**Comment by vmario89** [comment]
does syspass work in "normal mode" (without AD) in general or is the problem with 500 error occuring when you configure AD?

**Comment by estelarules** [comment]
I have not tried without AD configuration. I have to do it with it as is a porject for my university.

**Comment by vmario89** [comment]
hello,

how are you able to configure syspass for AD when you cannot access syspass? Are you editing config.xml by hand?

**Comment by estelarules** [comment]
Im just editing by hand httpd.conf and nslcd.conf

**Comment by nuxsmin** [comment]
Hello @estelarules 

It seems that some Apache authentication headers aren't being recognised by sysPass.

**Comment by nuxsmin** [comment]
@estelarules BTW you don't need to configure LDAP un Apache, since sysPass can manage this kind of authentication.

Are there any errors in syspass.log (within config dir)?

**Comment by estelarules** [comment]
Hi @nuxsmin and @vmario89 ,
Sorry for the late response
My problem was that I was overriden something on my httpd.conf file. Once I moved it to httpd.d/httpd.conf Apache started working.
Thank you.
