### ISSUE TITLE
Connection error (BIND)

### ISSUE THREAD

**Issue by Gruvz** [nuxsmin/sysPass#861]
Hello everyone is glad that I was able to get here. We are playing a little with syspass, but we have a problem
Connection error (BIND).
LDAP ERROR: Can not contact LDAP server (-1)
LDAP DN: syspass

I do not how I can not figure out what's wrong, but I've been through a lot of options:
1. I was trying to specify FQDN and ip server name
2. The user is specified without prefixes simply Administrator (Domain Administrator in Active Directory)
3. I checked telnet access to ldap server
4. I tried to specify the server with all the possible prefixes ldap. *, Ldap: \\
But I'm getting this error. I want to know in addition to installing php56w-ldap, I had to do some other setup?

Here is a screenshot of my setting
![syspass1](https://user-images.githubusercontent.com/35812047/35402267-15c48ed0-020d-11e8-9e7a-1433793f88bc.png)
![syspass2](https://user-images.githubusercontent.com/35812047/35402266-15c3ccac-020d-11e8-808d-eeb2adc8d2dd.png)

**Comment by joerg** [comment]
You need to specify the full LDAP DN as bind user. The error message also tells you that "LDAP DN: syspass" is not valid.

**Comment by nuxsmin** [comment]
Thanks for your contribution @joerg @CyphorUK !
