### ISSUE TITLE
Issue when entering a password

### ISSUE THREAD

**Issue by 6arrid0** [nuxsmin/sysPass#863]
Every time I enter a password an the element loses focus my password is replaced by an automatically generated one. To bypass this I have to change input type from password to text which is less than optimal.

Here's a [video demo](https://streamable.com/i4nju)

Any thoughts?

**Comment by vmario89** [comment]
hello,
please see https://github.com/nuxsmin/sysPass/issues/826
there are already some talks about this behaviour

regards, Mario

**Comment by nuxsmin** [comment]
Please see #826

**Comment by 6arrid0** [comment]
I feel really dumb right now, did not realise it was obfuscating the passwords 😅

**Comment by nuxsmin** [comment]
No worries, it's encrypting them indeed.

BTW it will be improved to let displaying the password in plain text.
