### ISSUE TITLE
Account ID in details

### ISSUE THREAD

**Issue by bigboj** [nuxsmin/sysPass#864]
As we massively use REST API, it is the easiest way to access individual keys through their IDs. However if we want to know each account's ID, we have to use REST API as well, as there is no other way to get it.
Is it possible to implement an additional field in details view showing "itemId" ? ID-based search would be great, as well.

**Comment by nuxsmin** [comment]
Sure!, It could be easily done  by editing the account template file `.../inc/themes/material-blue/account/account.inc'

Let me code a gist with this field included.

**Comment by bigboj** [comment]
I succeded to edit details.inc by the following: 
`            <tr>
                <td class="descField"><?php echo __('ID'); ?></td>
                <td class="valField">
                    <div class="lowres-title"><?php echo __('ID'); ?></div>

                    <?php echo $accountData->getAccountId(); ?>
                </td>
            </tr>
`

However, how could I manage to search on account ID? Any idea goes. Prepared URL containing the ID or anything similar...

**Comment by nuxsmin** [comment]
Hello, I missed your latest comment. I've just implemented this feature in 3.0-beta version.

Please take a look on: https://github.com/nuxsmin/sysPass/releases

Thanks for the feedback!
