### ISSUE TITLE
New user login error (Internal Error)

### ISSUE THREAD

**Issue by Dezza02** [nuxsmin/sysPass#866]
Hi there,

I created new users to use SysPass and for some strange reason, the new accounts I created will get Internal Error when they try to log in and this is the error message I get from the logs:

2018-01-30 21:44:44 - Error while querying
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'syspass.track' doesn't exist (0)
Caller 1: SP\Storage\DB\logDBException
Caller 2: SP\Storage\DB\getQuery
Caller 3: SP\Mgmt\Tracks\Track\add
Caller 4: SP\Controller\LoginController\addTracking
Caller 5: SP\Controller\LoginController\loadMasterPass
Caller 6: SP\Controller\LoginController\doLogin
2018-01-30 21:44:44 - SQL : 'INSERT INTO track SET \n            track_userId = ?, \n            track_source = ?, \n            track_time = UNIX_TIMESTAMP(),\n            track_ipv4 = ?,\n            track_ipv6 = ?'

Does anyone know how to fix them please?

Regards,
Dezza

**Comment by nuxsmin** [comment]
Hello, did you do an upgrade from a previous version?. It seems that a required database table is missing...

Regards.

**Comment by Dezza02** [comment]
Hi nuxsmin,

No, it wasn't an upgrade, I'm new to SysPass and saw the 2.1 recently and started using it. Is there something I can fix? Because there are fair bit of password in there if I have to start from scratch will be quite painful. 

Thanks.

Regards,
Dezza

**Comment by nuxsmin** [comment]
Hi!, please run the `track` table (**only**) creation code from https://github.com/nuxsmin/sysPass/blob/54d7ed1950207910cebd3644fc23b3265a267960/inc/sql/dbstructure.sql#L420

**Comment by Dezza02** [comment]
Thanks nuxsmin,

I will give it a try tonight when I finish work and let you know how it goes.

Regards,
Dezza

**Comment by Dezza02** [comment]
Thankx nuxsmin, that sql table fixed the problem. Much appreciated.

Regards,
Dezza

**Comment by nuxsmin** [comment]
That sounds good!

Thanks for the feedback ;)
