### ISSUE TITLE
Asignacion de cuentas a grupos desde la API

### ISSUE THREAD

**Issue by supkk** [nuxsmin/sysPass#868]
Buenos días,

    ¿es posible asignar mas de un grupo a una cuenta desde la API?. ¿Y asignarle etiquetas?

    Un saludo

**Comment by nuxsmin** [comment]
Buenas,

actualmente no es posible realizar ese tipo de acciones mediante la API, pero en la siguiente versión será posible realizarlas, ya que se ampliarán los métodos disponibles.

Saludos!

**Comment by supkk** [comment]
Buenos días,

     ¿tienes alguna previsión de cuando estará disponible?. ¿Es posible acceder a esa funcionalidad, aunque sea instalando una versión Beta?

    Un saludo y gracias

**Comment by nuxsmin** [comment]
Buenos días,

en principio a finales de este mes quiero tener una beta, ya que actualmente estoy con la implementación de la nueva estructura y muchas de las funcionalidades no están migradas, por lo que la funcionalidad es parcial.

Saludos!

**Comment by supkk** [comment]
Gracias

**Comment by nuxsmin** [comment]
En cuanto tenga disponible una versión más estable, la subo al entorno de demo.
