### ISSUE TITLE
Problema al actualizar versión 2.1.15

### ISSUE THREAD

**Issue by nixjua** [nuxsmin/sysPass#870]
Al realizar la actualización a la versión 2.1.15, me sale el siguiente mensaje 
"Unable to write into the "/config" directory"

Sin embargo, los permisos se encuentran seteados a 750 al usuario apache quien es el que ejecuta el servicio httpd

**Comment by nixjua** [comment]
Al realizar el unzip, hay que refrescar los permisos a nivel SELinux

**Comment by nuxsmin** [comment]
Hola, puede ser esto http://doc.syspass.org/es/installing/centos7.html#modificando-selinux?

Si hay algo que falte ena
 la documentación, dímelo y lo añado.

Gracias por la información!

**Comment by nixjua** [comment]
Es correcto, pero para el caso de la actualización, en la documentación no indicaba que se tenía que volver a realizar el refresh.
