### ISSUE TITLE
Problema al actualizar cuentas

### ISSUE THREAD

**Issue by nixjua** [nuxsmin/sysPass#871]
Después de realizar el upgrade a la versión 2.1.15, al intentar realizar la actualización de una cuenta, para asignar que ciertos usuarios específicos puedan visualizarla, manda el siguiente mensaje de error 

Error while querying
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'account_passDateChange' at row 1 (0)
SQL : '
UPDATE accounts SET account_customerId = :accountCustomerId,
account_categoryId = :accountCategoryId,
account_name = :accountName,
account_login = :accountLogin,
account_url = :accountUrl,
account_notes = :accountNotes,
account_userEditId = :accountUserEditId,
account_dateEdit = NOW(),account_passDateChange = :accountPassDateChange,
account_isPrivate = :accountIsPrivate,
account_isPrivateGroup = :accountIsPrivateGroup,
account_parentId = :accountParentId,
account_userGroupId = :accountUserGroupId,
account_otherUserEdit = :accountOtherUserEdit,
account_otherGroupEdit = :accountOtherGroupEdit 
WHERE account_id = :accountId'

**Comment by nixjua** [comment]
El error se presente en cualquier actualización de la cuenta, también si se desea realizar una actualización de la categoría manda el mismo error.

**Comment by nuxsmin** [comment]
Hello, this issue should be fixed in v3.

Regards
