### ISSUE TITLE
Uso de grupos

### ISSUE THREAD

**Issue by nixjua** [nuxsmin/sysPass#872]
Tengo dos usuarios, los cuales pertenecen a dos grupos diferentes, sin embargo, tengo cuentas que tienen asignado uno de estos grupos, y los usuarios no pueden visualizar las cuentas.  Porque puede estar sucediendo esto?

**Comment by nuxsmin** [comment]
Hola, para que los grupos secundarios que no son el primario del usuario, es necesario habilitar el acceso a grupos secundarios desde la configuración de cuentas.

Saludos!

**Comment by nixjua** [comment]
Muchas gracias, te lo agradezco.
