### ISSUE TITLE
sysPass / LDAP module unvailable

### ISSUE THREAD

**Issue by vivalasvegan** [nuxsmin/sysPass#874]
I did all the installation steps on CentOS 7;
Now I am trying to get through this problem :
Configuration > LDAP > module unvailable

Please can someone help me ?

**Comment by nuxsmin** [comment]
Hello, did you install the php-ldap module?

Regards

**Comment by deajan** [comment]
LDAP works for me in CentOS 7 x64, using default php-fpm version.
What do the httpd or php-fpm logs say ?

**Comment by vivalasvegan** [comment]
Hi sir,

I have succeed to install the php-ldap module. Actually, I didn't have the ldap in my first installation of sysPass because I had installed the php-56 module.

Thank you for having replied.

**Comment by nuxsmin** [comment]
Thanks for the feedback!
