### ISSUE TITLE
More than one user and passwd in the same IP/HOST

### ISSUE THREAD

**Issue by rsmartins78** [nuxsmin/sysPass#876]
Hello, I started using the tool recently and I wonder if there is any way to save more than one user and password to the same IP without having to create a new one.

**Comment by nuxsmin** [comment]
Hello, you can achieve it by using custom fields, but you won't be able to search for any content within custom fields, since the are encrypted.

Regards

**Comment by rsmartins78** [comment]
I tested this function, but it did not meet my need, due to the fact that I have to enter the register and open the custom fields tab in order to see the data, my need would be to see multiple users and passwords in the same register when I clicked on the display button .

Could this issue be considered an improvement?
