### ISSUE TITLE
2FA Missing Under User Preferences

### ISSUE THREAD

**Issue by g0ldleader** [nuxsmin/sysPass#877]
Hi,

I have recently come across this project and firstly must say this looks to be very good product for team sharing passwords. I'm running into an issue with our setup on CentOS 7 when attempting to get the 2FA portion up and running. I have loaded the Authenticator Plugin successfully and it shows it's currently enabled

![image](https://user-images.githubusercontent.com/33494998/36285335-c311ef60-1270-11e8-8556-4a2bdc49e516.png)

However, when I go to a users preferences the option to enable doesn't appear.

![image](https://user-images.githubusercontent.com/33494998/36285435-26b8ad06-1271-11e8-909f-bd35e51e839f.png)

I have tried a couple things on my end in the event something was hung on the server like restarting the apache services and I also rebooted the server with no luck either.  The installation seemed straight forward by placing the Authenticator plugin (https://github.com/nuxsmin/sysPass-Plugins) and placed it into (syspass root/inc/Plugins).  Unsure why this isn't working and any assistance will be greatly appreciated as this looks like a promising solution.

**Comment by nuxsmin** [comment]
Hi,

You can get into the user preferences by clicking the top right button.

If you're wondering about forcing the 2fa for all or some users, it isn't implemented yet, but it will be available in next plugin version.

Regards

**Comment by g0ldleader** [comment]
Ok yes that was it.  I was trying to force it for a user.  Thank you for your assistance.
