### ISSUE TITLE
LDAP / users imported and password ?

### ISSUE THREAD

**Issue by vivalasvegan** [nuxsmin/sysPass#878]
Hi everyone,

Do you how can we import passwords of users already imported from LDAP to syspass please ?
Thank you

**Comment by nuxsmin** [comment]
Hi,

You don't actually need to import any password, since LDAP users are authenticated against the LDAP server. sysPass will store the user's encrypted password to allow offline access (when the LDAP server becomes unavailable).

Regards.

**Comment by vivalasvegan** [comment]
Thank you,

Excuse me but how can I see on syspass that it stocks the passwords ?

**Comment by nuxsmin** [comment]
Sure, you can display the encrypted password by looking into the usrData table in sysPass database.

Regards

**Comment by nuxsmin** [comment]
BTW, you can get the last time when a user data has been updated by displaying the details.

**Comment by vivalasvegan** [comment]
Hi Sir,

I read the password in sysPass database but it still cannot connect to syspass. 
It is like $2y$10$ecryptedpassword

Thank you for having replied

**Comment by vivalasvegan** [comment]
Hi Sir,

It seems like syspass can not recognize the logins from ldap

Here is what is written in the event log:
> Wrong login
> Type : authBrowser
> User : 

Do you have an idea please ?

**Comment by vivalasvegan** [comment]
I have fixed it when i configure both ladp + active directory 

Thank you for having replied
Have a nice day

**Comment by nuxsmin** [comment]
Hello,

I'm glad to know it's working fine.

Auth browser means that the user's login is checked against browser authentication headers, like auth basic.

Regards
