### ISSUE TITLE
The MySQL user already exist

### ISSUE THREAD

**Issue by stenaloom** [nuxsmin/sysPass#88]
During installation, whichever username I try, I get the same error message:
The MySQL user already exist (sp_admin) 
(when using username admin).

**Comment by nuxsmin** [comment]
Hi, that is very strange, because it creates the new user if it doesn't exist. Can you tell me more about your evironment? (hosting, OS, mysql/php version).

Another option is to delete the config.php file, so we ensure that no previous data is used.

Kind regards.

**Comment by stenaloom** [comment]
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.2
PHP 5.4.36-0+deb7u3 (cli) (built: Jan  9 2015 08:07:06) 


![screenshot from 2015-02-17 13 53 26](https://cloud.githubusercontent.com/assets/9654133/6227807/f783320e-b6ac-11e4-928d-25c2663bef9d.png)


Tried removing config.php, didn't help. I have created a user in mysql (syspass), database (syspass) and granted all rights to the user for the database. Tried to login manually to MySQL and the user works fine.

**Comment by nuxsmin** [comment]
Hi, despite it preffixes the username with "sp_" the searching is done for "root" user, so you need to set another username for admin account ("root" is created yet for system admin). Be aware that sysPass uses an user to connect to the database (with sp_ preffix) and the same (without sp_preffix) to give access to the app.

At the installation process, sysPass need to know which are the credentials to create its database user and structure. That user is used only for installation, and the new one is used from now on.

**Comment by stenaloom** [comment]
It doesn't matter which username I choose. I can put adasdasfasfsafsa and it still says the user exists. I think the error message is incorrect. Is there anyway to debug and get the actual output from php?

**Comment by nuxsmin** [comment]
Yes, you are right, it's a default error message, because I could show some database error messages that can be annoying for normal users:
````php
private static function createDBUser($dbpassword)
{
if (self::$isHostingMode) {
return;
}
$query = "CREATE USER '" . self::$dbuser . "'@'localhost' IDENTIFIED BY '" . $dbpassword . "'";
if (!self::$dbc->query($query)) {
throw new InstallerException('critical'
, _('El usuario de MySQL ya existe') . " (" . self::$dbuser . ")"
, _('Indique un nuevo usuario o elimine el existente'));
}
}
````

You can take a look in apache error log where there should be some information about what is happening.

**Comment by nuxsmin** [comment]
Looking at you screenshot, if you're using the user "syspass" to do the DB configuration, make sure that it have the proper permissions to create users, databases and tables. If not, the installation will fail.

**Comment by stenaloom** [comment]
Managed to get further now. I used the root user of db and got it to install, but after the installation I get the following trace and when logging in, no buttons are usable.
Notice: Undefined index: pAppMgmt in /var/www/htdocs/sysPass/inc/profiles.class.php on line 170
Call Stack
#	Time	Memory	Function	Location
1	0.0003	239056	{main}( )	../index.php:0
2	0.0024	382872	require_once( '/var/www/htdocs/sysPass/inc/init.php' )	../index.php:27
3	0.0024	383312	SP_Init::init( )	../init.php:629
4	0.0048	570824	SP_Init::checkInstalled( )	../init.php:123
5	0.0062	694344	SP_Html::render( )	../init.php:369
6	0.0073	778648	SP_Html::getTemplate( )	../html.class.php:120
7	0.0076	818872	include_once( '/var/www/htdocs/sysPass/inc/tpl/install.php' )	../html.class.php:252
8	0.0091	924392	SP_Installer::install( )	../install.php:31
9	5.8017	932672	SP_Installer::createAdminAccount( )	../installer.class.php:173
10	5.8391	1329408	SP_Profiles::addProfile( )	../installer.class.php:424

**Comment by nuxsmin** [comment]
Hi, it seems that the "pAppMgmt" array key does not exist, indeed that key does not need to exist, so I need to remove it from the function. By the way, you need to decrease the PHP error reporting, because some messages can be put in the html response and that can break some javascript output, that is because newer PHP versions have some deprecated functions and can throw a 'notice' or 'warning' message, but sysPass 1.1 is made to be  compatible from 5.1 PHP version and that can generate these messages.

**Comment by stenaloom** [comment]
Got it working. A few more errors though. When trying to remove account:
Notice: Undefined variable: accountUsers in /var/www/htdocs/sysPass/inc/tpl/accounts.php on line 436
Call Stack
#	Time	Memory	Function	Location
1	0.0010	341680	{main}( )	../ajax_getContent.php:0
2	0.0088	978320	SP_Html::getTemplate( )	../ajax_getContent.php:92
3	0.0100	1115040	include_once( '/var/www/htdocs/sysPass/inc/tpl/accounts.php' )	../html.class.php:252

( ! ) Notice: Undefined variable: accountGroups in /var/www/htdocs/sysPass/inc/tpl/accounts.php on line 457
Call Stack
#	Time	Memory	Function	Location
1	0.0010	341680	{main}( )	../ajax_getContent.php:0
2	0.0088	978320	SP_Html::getTemplate( )	../ajax_getContent.php:92
3	0.0100	1115040	include_once( '/var/www/htdocs/sysPass/inc/tpl/accounts.php' )	../html.class.php:252

**Comment by nuxsmin** [comment]
Great, nice to hear that it finally works!

About notices, don't worry about them, these are variables that aren't needed for required action so they weren't set before so their values are the default in context.

From http://php.net/manual/en/language.variables.basics.php :

> It is not necessary to initialize variables in PHP however it is a very good practice. Uninitialized variables have a default value of their type depending on the context in which they are used - booleans default to FALSE, integers and floats default to zero, strings (e.g. used in echo) are set as an empty string and arrays become to an empty array. 

> Relying on the default value of an uninitialized variable is problematic in the case of including one file into another which uses the same variable name. It is also a major security risk with register_globals turned on. E_NOTICE level error is issued in case of working with uninitialized variables, however not in the case of appending elements to the uninitialized array. isset() language construct can be used to detect if a variable has been already initialized. 

BTW I'll fix it in the next build ;)

**Comment by nuxsmin** [comment]
@stenaloom one question, what browser are you using on last screenshot?. It's very annoying to see that the layout is so distorted ;)

**Comment by stenaloom** [comment]
It's Chromium Version 40.0.2214.111

**Comment by stenaloom** [comment]
Btw, I have php error reporting set to 22519, but I still get the notice errors. Is there some override in the sysPass code somewhere?
