### ISSUE TITLE
2FA Question

### ISSUE THREAD

**Issue by Dezza02** [nuxsmin/sysPass#881]
Hi,

I got a backup question about 2FA. Do I only need to backup the SQL Dump? As I'm not sure where the 2FA is stored.

Thanks heaps. :)
Dezza

**Comment by nuxsmin** [comment]
Hi!

The 2FA plugin data is stored in the db, so the dumped data contains it.

Cheers

**Comment by Dezza02** [comment]
Thanks nuxsmin. 

Cheers,
Dezza

**Comment by vivalasvegan** [comment]
Hi, 
Please help me know how did you do to configure the 2FA functionnality ?

**Comment by Dezza02** [comment]
Hi,

You download the plugin and then copy it to your /var/www/html/syspass/inc/Plugins 

Then log on to the SysPass WebGUI --> Items and Customizations --> Plugins 
You enable the Plugins there.

To Enable 2FA for your account, you click on the 3 dots and User Preferences
Click on Security tab and Enable for your account. Done :)

Cheers,
Dezza
