### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by jucajuca** [nuxsmin/sysPass#882]
Hi 

sysPass version | 1.2.0.18
after trying to update using the php interface. I'm trying to run the SQL code manually in myphp admin.

I'm using the SQL scripts [here](https://github.com/nuxsmin/sysPass/tree/master/inc/sql). 
13000000000.sql runs fine. (Actually all comands return zero results)

13016100601.sql does not run.

Any help is highly appreaciated. Do I have to run first 12002.sql or some other scripts?

Get following error:

```
ALTER TABLE `accHistory`
  ADD CONSTRAINT `fk_accHistory_users_edit_id`
FOREIGN KEY (`acchistory_userEditId`)
REFERENCES `usrData` (`user_id`)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT
MySQL said: Documentation

#1452 - Cannot add or update a child row: a foreign key constraint fails (`juancarl_syspass`.`#sql-563ec_15a9bb3`, CONSTRAINT `fk_accHistory_users_edit_id` FOREIGN KEY (`acchistory_userEditId`) REFERENCES `usrData` (`user_id`))
```

sysPass version | 1.2.0.18

Database | 
SERVER_VERSION : 5.5.58-cll 
CLIENT_VERSION : 5.5.58 

PHP | Version: 7.0.27 Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, cgi-fcgi, bcmath, dom, enchant, fileinfo, gd, geoip, imap, json, ldap, exif, mailparse, mcrypt, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, pspell, soap, sockets, tidy, uploadprogress, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, SourceGuardian Used Memory: 2048 KB 
Server | Apache

**Comment by nuxsmin** [comment]
Hi,

manually updates are only recommended in some cases. It seems that you are upgrading from 1.x  so there are DDL updates among internal application changes like new encryption (requires re-encryption) and others.

Could you tell me what errors did you face when upgrading through the web interface?

Regards.

**Comment by jucajuca** [comment]
Hi, so I managed to do it using the steps below between 1300000 and 13016100601.sql

Now my question is: I managed to start 2.1 (2.1.15.17101701) using ?nodbupgrade=1.

However I still have the following entries in my DB, in the table config:


 lastupdatempass | 1480002288
 masterPwd | ...
 tempmaster_attempts | 1
 version | 12018

how can I fix this so that syspass recognize that the db is up to date?

```
UPDATE accHistory
SET
acchistory_userEditId = 1
WHERE
acchistory_userEditId NOT IN (SELECT
user_id
FROM
usrData) OR acchistory_userEditId IS NULL;

UPDATE accHistory
SET
acchistory_userEditId = 1
WHERE
acchistory_userEditId NOT IN (SELECT
user_id
FROM
usrData) OR acchistory_userEditId IS NULL;

UPDATE accounts
SET
account_userEditId = 1
WHERE
account_userEditId NOT IN (SELECT
user_id
FROM
usrData) OR account_userEditId IS NULL;
```

**Comment by jucajuca** [comment]
I ran the update based on version 13016100601

but the sql above is apparently necessary, so you might want to create another extra sql script before 13016100601

**Comment by nuxsmin** [comment]
Hmm, it should have triggered an aux db upgrade before upgrading the application. This auxiliary upgrade fixes missing db records as SQL script does.

Thanks for the feedback!
