### ISSUE TITLE
LDAP Filter in import users

### ISSUE THREAD

**Issue by fgendorf** [nuxsmin/sysPass#887]
Hi, is very common use filters to import users, I think this is very important for this tool.

**Comment by nuxsmin** [comment]
Hi, I'm right now working on it, there will be also a preview for objects that would be imported. Groups will be imported too ;)

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Done in sysPass v3: https://github.com/nuxsmin/sysPass/releases/tag/3.0.0.18010101-beta
