### ISSUE TITLE
Notes are not exported to XML sysPass file

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#888]
When using XML export at **Configuration > Backup > Export Accounts** it would seem the resulting file does not include the Notes field.

I am using sysPass-XML-Decrypter so I am not sure if the decrypter is not decrypting properly this field ornot at all because it's not there, [I've also reposted this on their tracker](https://github.com/julenpardo/sysPass-XML-Decrypter/issues/4).

**Comment by nuxsmin** [comment]
Hmm, it seems weird, since notes are exported indeed (https://github.com/nuxsmin/sysPass/blob/2bcead630593b35a8daefeb7c7f96062b241efc2/inc/SP/Core/XmlExport.class.php#L455)

**Comment by nuxsmin** [comment]
I found that they aren't being imported using XML-Decrypter (https://github.com/julenpardo/sysPass-XML-Decrypter/blob/cefa15e9d44b371f6649f72a76ce24bfa8c5fe6a/src/Decrypter.php#L124)

**Comment by MagicFab** [comment]
Thank you, I'll try and submit a patch there.

**Comment by MagicFab** [comment]
FYI I've forked the original and fixed this, see https://gitlab.com/MagicFab/sysPass-XML-Decrypter (v0.3).
