### ISSUE TITLE
Generated Password contains non-ASCII characters

### ISSUE THREAD

**Issue by ga8Ua3** [nuxsmin/sysPass#890]
Passwords that are generated can contain UTF-8 characters if "symbols" is selected. This causes applications that are expecting ASCII characters to fail.

The character I've seen on several occasions is the middle dot "·" (U+00B7, hex bytes 0xC2 0xB7), but there may be several others.

We're using version 2.1.14.

**Comment by nuxsmin** [comment]
Hello, I'll review the code that generates the random passwords, to find out if it needs to be tweaked to avoid some special characters.

Thanks for the feedback!

Regards

**Comment by nuxsmin** [comment]
Solved in 3.0
