### ISSUE TITLE
Session timeout for individual users

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#891]
Hi nuxmin,

i had an idea for the session timeout. At the current moment there is a global setting for session timeout after which the user gets kicked off (please also see https://github.com/nuxsmin/sysPass/issues/721). I wanted to ask if it is possible to redesign this feature in the way that the adminstrator of syspass only defines the maximum global session time but the indivual user is allowed to specify his personal desired maxium session length (like an override, but not override over maximum global setting).

best regards, Mario :)

**Comment by nuxsmin** [comment]
Hi @vmario89 !

This would be an interesting feature for next release (coming soon...see dev-3.0 branch). You're welcome as beta-tester ;)

Regards

**Comment by nuxsmin** [comment]
Hello, such kind of  feature was added in v3, but it was enforced by setting preset values for either users, groups or profiles, so a presets manager could set timeouts depending on these fields and source network. Hope it will be useful ;)

Thanks for the feedback!

Regards.
