### ISSUE TITLE
Wrong view after creating an account

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#892]
Hi,

while creating many accounts i figured out that there is a little mistake which leads to more mouseclicks which are not required.

Please create a sample user like this ("New Account"):
![grafik](https://user-images.githubusercontent.com/5631071/37684196-8eb67748-2c8f-11e8-8466-ee8d789a7439.png)
After saving the new account you are thrown into the next screen which is "Edit Account"
![grafik](https://user-images.githubusercontent.com/5631071/37684187-85fe0fa8-2c8f-11e8-8fa4-0f6e29b8e0b4.png)

if think the screen after "New Account" should be "Account Details" instead of "Edit Account":
![grafik](https://user-images.githubusercontent.com/5631071/37684252-b97dc6d4-2c8f-11e8-91c3-d20e64f98808.png)

regards, Mario ;)

**Comment by nuxsmin** [comment]
Hi @vmario89 

This behavior has been discussed a time ago and everyone has its own preferences, so I thought that the edit page would be the preferred one since you could change any mistake without and additional click.

Let me know your thoughts on it.

Regards
