### ISSUE TITLE
Import : Intern error reading file

### ISSUE THREAD

**Issue by Matmout69** [nuxsmin/sysPass#893]
Hi,

I'm trying to import our KeePass (.xml export) data to Syspass.
Had a size problem earlier so I just updated the max size in parameters, but I'm now facing an other error while importing.

When I select the keypass.xml to import, Syspass loading a bit (like 5sec) and returning me an error : Error while reading the file (or something like that).

I also tried to check on the github but couldn't find something close enough my issue.
 
I Hope i'll find a solution here ! 👍 

Thanks for reading, and all my apologies for my english.

**Comment by nuxsmin** [comment]
Hi!, please let me know if there is any error message in sysPass event log. You can also check out syspass.log file within the config directory.

Regards.

**Comment by Matmout69** [comment]
Thanks !
Didn't check correctly event log. It was my php config file, limitating my upload by 2MB.

It seems like it's uploading my file (4MB), but it's very long. I tried to log out verifiy logs, but i'm now unable to log in (Internal error). Maybe the file is still uploading and this is preventing me from any action before the end of uploading?

I'll give news.
Regards

**Comment by nuxsmin** [comment]
Be aware that PHP processes will continue running until the task is finished. During this time, it will block any request from the same client, thereby the "internal error" message.

Have you got any progress?

**Comment by Exxou** [comment]
I'm expieriencing the same issue. Can't find anything useful in the .config file.

Hope you can help,
Regards
