### ISSUE TITLE
macOS Open Directory LDAP Error or 0/xxx imported

### ISSUE THREAD

**Issue by RAFd3v** [nuxsmin/sysPass#895]
I'm trying meanwhile since to weeks to import my users from macOS OD.
Server, Bind User, Bind Password and Search Base seem to work.
If I leave the Group free it shows me LDAP connection OK, xxx users found.
After the import button it shows LDAP user import finished but in the event log 
LDAP users import finished
Imported users : 0/xxx
Errors : 0

If I fill in any type into the group field I'm getting:

Error while searching the group RDN
Group : (cn=\77\6f\72\6b\67\72\6f\75\70)
LDAP ERROR : Success (0)
LDAP FILTER : (cn=\77\6f\72\6b\67\72\6f\75\70)

**Comment by nuxsmin** [comment]
Hello, this issue could be caused by some missing fields mapping like name or email.  Please try out sysPass v3 which has many improvements in this way.

Regards
