### ISSUE TITLE
Json error using new sysPass 3.0

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#896]
Hey nuxmin,
glad to see your new release. I just played with the demo around. I found an error while clicking this:
![grafik](https://user-images.githubusercontent.com/5631071/37786238-77852754-2dfc-11e8-8778-27278ac7d8aa.png)

regards, Mario :)

**Comment by nuxsmin** [comment]
Solved. It was a silly DB constraint that was enforcing the "dateUpdate" field to be set. It should be set whenever the link is updated.

Thanks for the feedback and testing! ;)
