### ISSUE TITLE
Trimming of Tags (sysPass 3.0 Beta)

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#897]
Hey nuxmin,
i figured out that tags should be trimmed left and right sides before saving. the screenshot contains the tag "test             " with around 20 whitespaces
![grafik](https://user-images.githubusercontent.com/5631071/37786502-2bd560ca-2dfd-11e8-8dc3-604012e48c3e.png)

I am not able to add the Tag "test" twice because syspass recognizes it because i guess the check method looks for trimming (this is good behaviour so far), but: it is stored with that much whitespaces in database. i think it would be better to check first and then store it in DB 

kind regards, Mario

**Comment by nuxsmin** [comment]
Solved!, Just need some tweaking :)

Thanks for the feedback!
