### ISSUE TITLE
sysPass 3.0 Beta translations

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#898]
Hi nuxmin,
found some spanish strings in demo^^:
![grafik](https://user-images.githubusercontent.com/5631071/37801720-f0045eae-2e27-11e8-94b0-519c238e07cc.png)
![grafik](https://user-images.githubusercontent.com/5631071/37801926-b8a94acc-2e28-11e8-97ba-a0c4f5e56ebe.png)
![grafik](https://user-images.githubusercontent.com/5631071/37802196-b4871b62-2e29-11e8-9e38-376ff722a46d.png)
![grafik](https://user-images.githubusercontent.com/5631071/37802208-bc2274fc-2e29-11e8-8295-c84793ea1d6b.png)

so i remembered to translate some stuff again.

i translated some more strings on poeditor.com some minutes ago (there were abouzt 79 fuzzy strings left in german version) - maybe you could provide an updated version in poeditor for version 3 now and pull the changes later :-)

regards, Mario

**Comment by nuxsmin** [comment]
Sure!, there would be some typos within the code...I'll update PoEditor string as soon as all the new features are implemented, because I don't want to hassle to contributors (including you) with some incremental updates...

**Comment by nuxsmin** [comment]
POEditor updated. I added some tags to help tracking the new strings.

Thanks for your contribution!
