### ISSUE TITLE
Cutoff in selection box - sysPass 3.0 Beta

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#899]
hi nuxmin,
i got a design problem with the selector for linked accounts. This is really at the bottom of the page:
![grafik](https://user-images.githubusercontent.com/5631071/37802391-8495b9da-2e2a-11e8-9eb5-70aed2f60182.png)

as you can see the selection possibilities of the field "Linked accounts" are cut because it does not popup to the top side. it pops up below the end of the rendered area instead

**Comment by ortizleo** [comment]
Hmm i can't login in beta, username/password not work...

**Comment by nuxsmin** [comment]
I've just logged in using demo/syspass credentials

**Comment by nuxsmin** [comment]
@Fizard hmm, seems something went wrong.. I'll check it out shortly.

Thanks for the notice!

**Comment by nuxsmin** [comment]
Solved
