### ISSUE TITLE
Glitches in mobile theme - sysPass 3.0 Beta

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#901]
Hey,
found some issues on mobile phone with layout:
![grafik](https://user-images.githubusercontent.com/5631071/37822929-439e6464-2e88-11e8-841a-350517680692.png)

as you can see for some menu entries there are only symbols but no text.
![grafik](https://user-images.githubusercontent.com/5631071/37822962-57285f9e-2e88-11e8-96e5-415834eb7dfc.png)

and for vertical layout there is not enough space to show the text of the titles completely. maybe in vertical view an "icon only" menu would solve this.
![grafik](https://user-images.githubusercontent.com/5631071/37822952-5089d7da-2e88-11e8-971b-a49e8c0777ba.png)

kind regards, Mario

**Comment by nuxsmin** [comment]
Hey!, hopefully I've just solved them. I've also added some improvements to password fields behavior.

Thanks for the feedback!
