### ISSUE TITLE
Password complexity fails at length of 118

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#903]
Hi,
i figured out that it's impossible to generate keys longer than 117 chars within sysPass. Pushing the integrated password generator causes to fail:
![grafik](https://user-images.githubusercontent.com/5631071/37925284-70f7d7de-3134-11e8-8d70-9df8caeeb44e.png)

![grafik](https://user-images.githubusercontent.com/5631071/37925259-69c3b7c6-3134-11e8-8279-8412e9f5d4eb.png)

![grafik](https://user-images.githubusercontent.com/5631071/37925315-80d2815e-3134-11e8-8d69-88fcee8944c6.png)

It generates the value "false" :-D

tested in current 3.0 beta version

**Comment by nuxsmin** [comment]
Hello, that's so because the RSA encryption payload length. It should be less than 118 bytes.

https://stackoverflow.com/questions/5866129/rsa-encryption-problem-size-of-payload-data#5868456

BTW, I'll add some warning about it.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Solved in latest pre-release.
