### ISSUE TITLE
Unexpected token in JSON

### ISSUE THREAD

**Issue by steevegldev** [nuxsmin/sysPass#904]
Just testing v3.0.0.18032401-beta
I didn't find the documentation, so I did my best.

1. Checked out to the branch.
1. Installed dependencies with composer.
1. Given permission to app directory.
1. Completed the setup form with a new database.

Trying to login:
There was an error<p>SyntaxError: Unexpected token < in JSON at position 0parsererror</p>

**Comment by nuxsmin** [comment]
@steevegldev nice, please checkout directly from the branch and not from releases page (I didn't notice it before), because I didn't tag the lastest commits which solve some bugs.

Regards.

**Comment by nuxsmin** [comment]
Another option is try it out on demo-beta.syspass.org:10080

**Comment by steevegldev** [comment]
I reset my repo and used devel-3.0 branch but I got error about database connection in the Setup wizard... I use CentOS, may be a SELinux security parameter.

I will wait the release version.
