### ISSUE TITLE
Assign several groups to user

### ISSUE THREAD

**Issue by Xumeiquer** [nuxsmin/sysPass#906]
I don't know if this feature is already in place, but I couldn't find anything related to this.

It would be great if a user could be assigned to several groups.

Thanks and good software by the way.

Regards

**Comment by nuxsmin** [comment]
Hello, this feature is already implemented and you can get it by setting the users within the group by editing the latter.

I'm glad to know you found sysPass useful!

Kind regards.

**Comment by Xumeiquer** [comment]
Hi, I have found the option to do it. 

Thanks a lot.
