### ISSUE TITLE
Unable to connect to DB during installation

### ISSUE THREAD

**Issue by 80kk** [nuxsmin/sysPass#909]
I am trying to install sysPass on Ubuntu 17.10 (local machine) with MariaDB 10.1.30 but it is failing on DB connect attempt. I have installed other webapps using MySQL root credentials without any problems so I can rule out DB permission issue. I have also tried to create syspass db and user manually, but it didn't work as well. Also despite properly set locales installation is in spanish...

**Comment by nuxsmin** [comment]
It would be useful to take a look to `syspas.log` file within the config directory, since some db related messages will be logged into this file.

Regarding the locales, did you install the UTF-8 variant?, which locales are you using?, did your restart the web server?.
