### ISSUE TITLE
Password Reset Options

### ISSUE THREAD

**Issue by jcboysha** [nuxsmin/sysPass#910]
I've had many cases of users not remembering their previous passwords when re-authenticating after an LDAP password change. The "forgot password" option is not present (I assume because I am using LDAP authentication). Is there any way to have the system remove the master password hash, or use some other method to ensure that users are able to login after a password change if they do not have their old password?

**Comment by nuxsmin** [comment]
Sure, it will prompt for the previous password, and then, if the user doesn't set it, the app will prompt for the master password. As you said, the "forgot password?" option won't run for LDAP users, but it should be displayed if email notifications are configured.

Regards

**Comment by jcboysha** [comment]
When last this happened, and in testing, the user was never asked for the master password. Just their previous password until the account was locked out.

**Comment by nuxsmin** [comment]
Hmmm, it's weird, since it will ask for the previous one and then, if it fails, for the master password instead.

**Comment by jcboysha** [comment]
Yea, that's what I thought was supposed to happen. I do not know what's going on with it then...

**Comment by nuxsmin** [comment]
Is there any message in sysPass event log regarding an LDAP response code during a password changed login?

**Comment by jcboysha** [comment]
Bad Authentication is the response code. Repeatedly until the account is locked out.

**Comment by nuxsmin** [comment]
It means that the credentials provided are wrong, so sysPass shouldn't ask for the previous password, since a previous LDAP step has failed. This LDAP error is mandatory, so no further actions will be taken: https://github.com/nuxsmin/sysPass/blob/65b492995674e418721d52c8b4383ec144bdff91/inc/SP/Controller/LoginController.class.php#L458
