### ISSUE TITLE
Different session timeouts depending on source IP / network

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#912]
Hello,

Really enjoying sysPass, but I'd love to have the ability to set different session timeouts depending on if I use sysPass on my local network or via an external IP.
This could be such a great feature and improve our usability of this tool.
Woudn't mind paying for that feature :)

Best regards.

**Comment by nuxsmin** [comment]
Hello, it would be an useful feature. Noted down for next releases.

Thanks for the feedback!

Regards

**Comment by nuxsmin** [comment]
Hello @deajan 

latest commit includes the implementation of this feature. It's done by using "Preset Values", which could be applied to either users, groups or profiles and source ip address or network.

Please let me know your thoughts about it.

Regards.

**Comment by deajan** [comment]
@nuxsmin Just looked at your hosted beta. As of my understandings, only one IPv4 subnet can be specified, am I right ?
In my case, I would have to add 3 different IPs, can multiple session timeout presets be applied ?

**Comment by deajan** [comment]
@nuxsmin After a quick test, editing a preset value, changing users/groups produces:
```
Integrity constraint
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '62fa48a13ceec3b140c9821592064d00ce5d53a8' for key 'uk_ItemPreset_01'
```

**Comment by nuxsmin** [comment]
Right, it should be thrown whenever a duplicated entry is trying to be saved. sysPass generates a hash using userId, userGroupId, userProfileId, type and priority, so a field with the same values will be rejected.

Do you have any example of an incorrect behavior?

**Comment by deajan** [comment]
Sorry for the late answer.
I need to add 3 different IPs with different timeout settings for the same user.
So on your demo, I tried to create two entries with the same user in order to add different IPs for session timeout.
Indeed I get an integrity constraint (btw, the error message could be a bit more clear for the end user, like "you are not allowed to create duplicate entries").

After thinking around, I guess that's where the priority settings comes in handy. So I can indeed create multiple IP timeouts for the same user as long as they have different priorities.

I've successfully tested this feature... Again, thanks for your work.

Btw2, please consider adding the default timeout max value (604800) and the unit (seconds) to the UI.

**Comment by nuxsmin** [comment]
Hello @deajan 

regarding your points:

> After thinking around, I guess that's where the priority settings comes in handy. So I can indeed create multiple IP timeouts for the same user as long as they have different priorities.

Item presets precedence will work as follows:

- Items assigned to user will have the 1st precedence.
- Items assigned to group will have the 2nd precedence.
- Items assigned to profile will have the 3rd precedence.
- Priority will override the above precedences.

So talking about the session timeout, it will always return the highest precedence preset since the item's network data is read before the item is got from the database, since item's data are stored in a serialized way.

This use case could be achieved by setting more than one network address within the item (need to be implemented)

Regards.

**Comment by nuxsmin** [comment]
> Btw2, please consider adding the default timeout max value (604800) and the unit (seconds) to the UI.

Sure!

**Comment by deajan** [comment]
Sorry to bug you again with this, but I was unable to successfully implement my session timeout rules.

Here's what I need:
Have all users from profile 'READONLY' have a 1 hour session timeout from subnet 10.13.0.0/24
Have all users from profile 'READONLY' have a 1 hour session timeout from subnet 192.168.10.0/24
Have all users have a 15 minutes session timeout from anywhere.

The latter was configured in the general config tab.
Both specific rules were configured as priority 0 and 1, both being forced.
The priority 0 rule never worked (probably overwritten by priority 1 rule).

First of all, this gave me an insight of how priorities work (so the higher the number, the higher the priority). This isn't documented anywhere.

Secondly, I don't understand the 'forced' value which indicates that "Values will be merged with the existing ones."
I thought this would make both different IP rules merge, but it didn't :)

Could you please explain me what the force option does ?
Also, is there a way I can have multiple times the same group / profile session timeouts with different subnets ?

Thanks.
