### ISSUE TITLE
Restarting docker container forces reinstall syspass

### ISSUE THREAD

**Issue by Xumeiquer** [nuxsmin/sysPass#914]
Hi!

I am running syspass v3 with docker-compose so syspass is in one container and mariadb is in another container. Well, when restarting containers by doing `docker-compose stop && docker-compose up -d` forces syspass to reinstall and this will empty the database.

**Comment by nuxsmin** [comment]
Hi,

This is really weird since I use docker for every day sysPass development. Dear aware that if you issue `docker-compose down` command it will destroy the entire stack.

Worth to mention that 3.0-beta demo is running on docker and it never reset the database unless I remove the stack.

Regards
