### ISSUE TITLE
Access denied for user 'sp_admin'@'syspass-app.syspass_default'

### ISSUE THREAD

**Issue by cartelmatic** [nuxsmin/sysPass#916]
Hi,
We are really enjoy to run syspass under docker-compose but following a host ip change and a reboot, we get the following error when trying to access the syspass web page : Error 1045: SQLSTATE[HY000] [1045] Access denied for user 'sp_admin'@'syspass-app.syspass_default' (using password: YES

We used docker volume create in order to keep our configuration.
We tryed many troubleqhooting but it seem the syspass app still can't connect to the databes.
Do you know how to solve this?

**Comment by nuxsmin** [comment]
Hi!

Please, take a look to https://github.com/nuxsmin/docker-syspass/issues/13

Regards
