### ISSUE TITLE
Not able to login into admin user after LDAP integration

### ISSUE THREAD

**Issue by KannadhasanThangadurai** [nuxsmin/sysPass#917]
Hi Team,

I've tried to configure LDAP, Now am not able login with admin user but able to login with LDAP users.

Please help to login with Admin user, where i can create accounts.

Thanks,
Kannadhasan Thangadurai.

**Comment by nuxsmin** [comment]
Hello,

Be aware that sysPass will always login with the first available user, which means that LDAP will be queried first, so you will need to provide a valid LDAP credentials. Only if LDAP is unavailable, it will authenticate against the sysPass database.

You can manually disable LDAP in config.xml file by setting ldap_enable to 0.

Regards

**Comment by KannadhasanThangadurai** [comment]
Glad for the details. Thanks. :)
