### ISSUE TITLE
Encrypt Session problem with v3.0 Beta

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#919]
I just installed sysPass v3.0 and in the configuration I've enabled the Encrypt Session (even without HTTPS being configured). When I saved this configuration the application got an error and couldn't even go to the login page again.
Here is the error:
Class 'SP\Core\Init' not found

I've seen that there isn't this directory "Init" on "syspass/lib/SP/Core". Did I miss any configuration? I had to go to the config.xml file to set the <encryptSession>1</encryptSession> to 0 to log in the application again.

**Comment by nuxsmin** [comment]
Hello, this issue has been fixed in latest commit but I haven't tagged any release yet.

Regards.
