### ISSUE TITLE
New user using login with temporary master password error in sysPass v3 beta

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#920]
I tried to login with a new user and I created a temporary master key to make the first login, but I got an error when trying to login at least with the temporary master password. This was my error:
http://IP_OF_SERVER/syspass/undefined
Not Found
The requested URL /syspass/undefined was not found on this server.

Here is the log:
180	2018-04-23 18:19:28	ERROR	exception	-	xx.xxx.x.xxx	Parámetro no encontrado (3)
179	2018-04-23 18:19:28	INFO	login.masterPass.temporary	-	xx.xxx.x.xxx	Usando a senha temporária
178	2018-04-23 18:19:28	INFO	login.auth.browser	-	xx.xxx.x.xxx	
Tipo : authBrowser
Usuário : user.admin.new
Autenticação : N / d ()
177	2018-04-23 18:19:19	ERROR	exception	-	xx.xxx.x.xxx	A Senha Mestre não foi salva ou está incorreta
176	2018-04-23 18:19:19	INFO	track.add	-	xx.xxx.x.xxx	xx.xxx.x.xxx
175	2018-04-23 18:19:19	INFO	login.auth.browser	-	xx.xxx.x.xxx	
Tipo : authBrowser
Usuário : user.admin.new
Autenticação : N / d ()

Seems like there is a parameter not found, but I don't know what it is.

**Comment by Fizard** [comment]
Hi @nuxsmin, if I can test or help in this error just let me know. I know just know a little of PHP and can try to help. Thanks.

**Comment by nuxsmin** [comment]
Hello, sorry for the late response, I've been busy on this time and I missed your issue. It should be solved in the latest commit.

Regards!
