### ISSUE TITLE
Linked Account not working in V3 Beta

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#921]
I tried to add an linked account in v3 beta, but when I choose another account and save it doesn't show anywhere this linked account. It keep showing "SELECT ACCOUNT".

When I tried i just had 2 accounts, and I tried to link one with the other.

**Comment by Fizard** [comment]
Just to give more information on my application:
sysPass version | 3.0-beta (300.18033001)
Database | SERVER_VERSION : 5.6.31-log CLIENT_VERSION : mysqlnd 5.0.12-dev - 20150407
PHP | Version: 7.0.29 Extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mcrypt, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader Used Memory: 4096 KB User: root
Server | Apache/2.4.6 (CentOS) PHP/7.0.29
Configuration Backup | Thu, 01 Jan 1970 00:00:00 +0000
Language  | en_US.utf8
Encrypted Session  | No

**Comment by nuxsmin** [comment]
Fixed, thanks for the feedback!

**Comment by Fizard** [comment]
@nuxsmin, Thanks for your quick fix! Do you know when will be updated the code so I can test it?

**Comment by nuxsmin** [comment]
You're welcome. It has already been tagged, so you can download it from latest releases page.

Regards
