### ISSUE TITLE
Error while filtering on V3 Beta

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#922]
When trying to filter or clear the filter on "Items and Customizations" tab on "Accounts" and "Accounts (H)" I'm receiving the following error:
There was an error
SyntaxError: Unexpected token O in JSON at position 0parsererror.

The other tabs on "Items and Customizations" I've tested the filter and they are ok.

**Comment by nuxsmin** [comment]
Fixed, thanks for the feedback!
