### ISSUE TITLE
Can't edit or create new accounts on v3.0-beta (300.18042501)

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#924]
When I try to update an account or create new accounts after I updated to the latest release I'm having this error:

Notice: Undefined offset: 0 in /var/www/html/syspass/lib/SP/Storage/DbWrapper.php on line 103
Argument 1 passed to SP\DataModel\Dto\AccountDetailsResponse::setUsers() must be of the type array, null given, called in /var/www/html/syspass/lib/SP/Services/Account/AccountService.php on line 105.

Here is what I had in syspass.log:
2018-04-26 12:04:22 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'AU.isEdit' in 'field list'
2018-04-26 12:04:22 - #0 /var/www/html/syspass/lib/SP/Storage/Database.php(186): PDOStatement->execute()
#1 /var/www/html/syspass/lib/SP/Storage/Database.php(117): SP\Storage\Database->prepareQueryData(Object(SP\Storage\QueryData))
#2 /var/www/html/syspass/lib/SP/Storage/DbWrapper.php(89): SP\Storage\Database->doQuery(Object(SP\Storage\QueryData))
#3 /var/www/html/syspass/lib/SP/Storage/DbWrapper.php(65): SP\Storage\DbWrapper::getResults(Object(SP\Storage\QueryData), Object(SP\Storage\Database))
#4 /var/www/html/syspass/lib/SP/Repositories/Account/AccountToUserRepository.php(189): SP\Storage\DbWrapper::getResultsArray(Object(SP\Storage\QueryData), Object(SP\Storage\Database))
#5 /var/www/html/syspass/lib/SP/Services/Account/AccountService.php(105): SP\Repositories\Account\AccountToUserRepository->getUsersByAccountId(5)
#6 /var/www/html/syspass/app/modules/web/Controllers/AccountController.php(329): SP\Services\Account\AccountService->withUsersById(Object(SP\DataModel\Dto\AccountDetailsResponse))
#7 [internal function]: SP\Modules\Web\Controllers\AccountController->editAction(5)
#8 /var/www/html/syspass/lib/SP/Bootstrap.php(239): call_user_func_array(Array, Array)
#9 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#10 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#11 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#12 /var/www/html/syspass/lib/SP/Bootstrap.php(446): Klein\Klein->dispatch()
#13 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#14 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')
#15 {main}
2018-04-26 12:04:22 - Routing error: Argument 1 passed to SP\DataModel\Dto\AccountDetailsResponse::setUsers() must be of the type array, null given, called in /var/www/html/syspass/lib/SP/Services/Account/AccountService.php on line 105
2018-04-26 12:04:22 - Routing error: #0 /var/www/html/syspass/lib/SP/Services/Account/AccountService.php(105): SP\DataModel\Dto\AccountDetailsResponse->setUsers(NULL)
#1 /var/www/html/syspass/app/modules/web/Controllers/AccountController.php(329): SP\Services\Account\AccountService->withUsersById(Object(SP\DataModel\Dto\AccountDetailsResponse))
#2 [internal function]: SP\Modules\Web\Controllers\AccountController->editAction(5)
#3 /var/www/html/syspass/lib/SP/Bootstrap.php(239): call_user_func_array(Array, Array)
#4 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#5 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#6 /var/www/html/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#7 /var/www/html/syspass/lib/SP/Bootstrap.php(446): Klein\Klein->dispatch()
#8 /var/www/html/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#9 /var/www/html/syspass/index.php(28): require('/var/www/html/s...')

**Comment by nuxsmin** [comment]
Hmm, it seems that your database schema is not up to date, since there's a missing field that should be created during the installation. Did you upgrade the existing database?

Latest v3 DB schema:

https://github.com/nuxsmin/sysPass/blob/777b4b6316792db32169379e71173246e36c7a49/schemas/dbstructure.sql#L164

And because the data couldn't be fetched, the `array` of users were empty:

https://github.com/nuxsmin/sysPass/blob/777b4b6316792db32169379e71173246e36c7a49/lib/SP/Repositories/Account/AccountToUserRepository.php#L178

Please update your database by issuing these queries:

```
-- AccountToUserGroup
ALTER TABLE AccountToUserGroup
  ADD isEdit tinyint(1) unsigned DEFAULT 0 NULL;

-- AccountToUser
ALTER TABLE AccountToUser
  ADD isEdit tinyint(1) unsigned DEFAULT 0 NULL;

-- Views
CREATE OR REPLACE VIEW account_search_v AS
  SELECT
    `Account`.`id`                                       AS `id`,
    `Account`.`clientId`                                 AS `clientId`,
    `Account`.`categoryId`                               AS `categoryId`,
    `Account`.`name`                                     AS `name`,
    `Account`.`login`                                    AS `login`,
    `Account`.`url`                                      AS `url`,
    `Account`.`notes`                                    AS `notes`,
    `Account`.`userId`                                   AS `userId`,
    `Account`.`userGroupId`                              AS `userGroupId`,
    `Account`.`otherUserEdit`                            AS `otherUserEdit`,
    `Account`.`otherUserGroupEdit`                       AS `otherUserGroupEdit`,
    `Account`.`isPrivate`                                AS `isPrivate`,
    `Account`.`isPrivateGroup`                           AS `isPrivateGroup`,
    `Account`.`passDate`                                 AS `passDate`,
    `Account`.`passDateChange`                           AS `passDateChange`,
    `Account`.`parentId`                                 AS `parentId`,
    `Account`.`countView`                                AS `countView`,
    `Account`.`dateEdit`                                 AS `dateEdit`,
    `User`.`name`                                        AS `userName`,
    `User`.`login`                                       AS `userLogin`,
    `UserGroup`.`name`                                   AS `userGroupName`,
    `Category`.`name`                                    AS `categoryName`,
    `Client`.`name`                                      AS `clientName`,
    (SELECT count(0)
     FROM `AccountFile`
     WHERE (`AccountFile`.`accountId` = `Account`.`id`)) AS `num_files`,
    `PublicLink`.`hash`                                  AS `publicLinkHash`,
    `PublicLink`.`dateExpire`                            AS `publicLinkDateExpire`,
    `PublicLink`.`totalCountViews`                       AS `publicLinkTotalCountViews`
  FROM `Account`
    INNER JOIN `Category` ON `Account`.`categoryId` = `Category`.`id`
    INNER JOIN `Client` ON `Client`.`id` = `Account`.`clientId`
    INNER JOIN `User` ON `Account`.`userId` = `User`.`id`
    INNER JOIN `UserGroup` ON `Account`.`userGroupId` = `UserGroup`.`id`
LEFT JOIN `PublicLink` ON `Account`.`id` = `PublicLink`.`itemId`;
```
It should solve the issues ;)

Regards

**Comment by Fizard** [comment]
Hi, yes, that was the problem. I preferred to create a new database, but would be really nice to have partial DB upgrades with a SQL file for each change between release changes so it would be simple to correct it.
