### ISSUE TITLE
syspass on raspbian

### ISSUE THREAD

**Issue by didacsales** [nuxsmin/sysPass#926]
Hi, 

I "installed" syspass beta on my raspi. After i downloaded and moved all files on its folder and give permissions, i try to acces to the IP. Apache says all is good, but when i access to IP/syspass/index.php i only get "HTTP ERROR 500".

Previously i had installed the stable version, and had no problem. 

Any idea?

Thank you!

**Comment by didacsales** [comment]
I don't know how, but reviewing information and touching on different parts, i solved it.
Thank you deajan for caring.
I close it, and i will remove it (if possinle). Is not apporting any help to ther people. Just wanted to thank.

👍

**Comment by nuxsmin** [comment]
@didacsales no worries about the closed issue... I'm glad to know you solved it.

@deajan thanks for your support!

Regards
