### ISSUE TITLE
Account id , Auth token ,token Pass

### ISSUE THREAD

**Issue by xxCoDeBoX** [nuxsmin/sysPass#927]
Where to find the account id ?
I have generated the auth token as combination of username and password in base64 format is this right ?
tokenPass I have taken the password which I configured while creating the api auth in syspass is this correct ??

**Comment by nuxsmin** [comment]
Hello

> Where to find the account id ?

You need to perform an account search through the API

> I have generated the auth token as combination of username and password in base64 format is this right ?

You need to use the token provided in the API authorization details

> tokenPass I have taken the password which I configured while creating the api auth in syspass is this correct ??

Right, it would be needed when querying for the account's password. The other actions do not need this key.

Regards

**Comment by xxCoDeBoX** [comment]
@nuxsmin  
I am unable to fetch account details via ( getAccountSearch api ) , can u please give me a sample template or procedure for this .
This is what I am doing : 
1. Generated Authtoken 
2. https://x.x.x.x/getAccountSearch with authtoken as headers in postman .

But no response , can u help me with this .

Thanks in advance
