### ISSUE TITLE
ldap auth not working

### ISSUE THREAD

**Issue by wagnst** [nuxsmin/sysPass#93]
Hi,
the ldap filter [...] (&(' . $groupDN . ') [...] does not resolve what is inside the member value of the group..
It resolves to "cn=test,ou=..." but inside ldap there is only written "test". When I change this manually (using cn=$ldapGroup) it works, but I am still not able to sign in.. the log now says 
"LDAP session start.... user has no group assigned"... also a useraccount was not created?

What is wrong here?
Thanks Steffen

**Comment by wagnst** [comment]
as a hint.. I am using GOsa as a LDAP frontend to create the schemes..

**Comment by wagnst** [comment]
i changed group membership of my ldap group... now i get another error.. 

although uid contains the correct value and also objectClass person is assigned..


LDAP FILTER:
(&(|(samaccountname=<username>)(cn=<username>)(uid=<username>))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))

**Comment by wagnst** [comment]
May my first problem be, that I use rfc2307bis, and therefore it only saves cn?

**Comment by wagnst** [comment]
fuck... I'm sorry.. should read http://wiki.syspass.org/en/ldap next time..
working now :dart:

**Comment by nuxsmin** [comment]
Great!!

Sorry for late answer...working hours ;)

**Comment by wagnst** [comment]
fine.. maybe you should links the ldap section somehow directly to the OS-setup :dancer: 

Will there be some kind of feature with that i could assign multiple roles to an user? I am thinking of having LDAP roles for r/w and want to assign a fitting role inside syspass... so that i dont have to assign the role manually?
