### ISSUE TITLE
Mysql connection refused

### ISSUE THREAD

**Issue by xxCoDeBoX** [nuxsmin/sysPass#932]
Hi , I am trying to connect syspass with mysql DB which is located in different server but I get the following error , I have posted the error snippet below .

![image](https://user-images.githubusercontent.com/36667412/39623847-9a77672a-4fb4-11e8-9a53-e72ec45ac984.png)

kindly help me out with this .

**Comment by xxCoDeBoX** [comment]
This is the syspass log .

![image](https://user-images.githubusercontent.com/36667412/39624566-741fc02e-4fb7-11e8-9b11-4f8b48e7ab78.png)

**Comment by nuxsmin** [comment]
Hi, it seems that your database connection data are not correct. You need to provide a connection user data with admin rights. Please take a look to https://doc.syspass.org

Regards
