### ISSUE TITLE
LDAP with StartTLS

### ISSUE THREAD

**Issue by hplodur** [nuxsmin/sysPass#936]
It seems that LDAP StartTLS is not supported.

I've looked at the code it can be added with an additional line to the connect function from LdapBase.class.php just before the return:

`@ldap_start_tls($this->ldapHandler);`

Probably additional if needs to be added and a checkbox in the UI LDAP configuration to use / not use.

Can this be added to the product?

**Comment by nuxsmin** [comment]
Hello,

sure, it could be implemented in next v3 release.

Thanks for the feedback!

Regards

**Comment by nuxsmin** [comment]
Hello, this feature was added in latest commits for v3. Thanks for the feedback!

Regards.
