### ISSUE TITLE
LDAP Search for memberUID in Group

### ISSUE THREAD

**Issue by hplodur** [nuxsmin/sysPass#937]
Is there possibility to configure LDAP to search for a user inside the group through `memberUid` rather than assigning memberOf to user?

**Comment by nuxsmin** [comment]
Hello, which version of sysPass are you running?

The current stable and v3-beta versions use `uniqueMember` and `member` within the LDAP filter to check if the user is included in the group.

https://github.com/nuxsmin/sysPass/blob/65b492995674e418721d52c8b4383ec144bdff91/inc/SP/Auth/Ldap/LdapStd.class.php#L104

https://github.com/nuxsmin/sysPass/blob/78429052b9488d0906e1334283b728f3d8ea1707/lib/SP/Providers/Auth/Ldap/LdapStd.php#L106

It could be easily achieved by adding some extra attributes to the search filter. Noted for the next release.

Thanks for the feedback!.

Regards.

**Comment by nuxsmin** [comment]
Hello, this feature was added in latest commits for v3. Thanks for the feedback!

Regards.
