### ISSUE TITLE
Can't delete customer

### ISSUE THREAD

**Issue by Blai01** [nuxsmin/sysPass#938]
I'm logged in with an admin user. I'm trying to delete a customer and whenever I click the delete icon it says:

"Error while deleting the customer" 

If I select the checkbox and then choose "Delete selected", syspass says "Customer deleted" but it still appears on the list afterwards.

The customer has no entries under its name, if that helps.

Am I the only one having this trouble?

**Comment by Blai01** [comment]
I have just seen another post where something similar was discussed and have just found out. Thanks for the quick answer though!

Maybe it would be a good idea to include a message inside the error message saying "Be sure that the customer is not included in the accounts history" or something similar?

**Comment by nuxsmin** [comment]
> Maybe it would be a good idea to include a message inside the error message saying "Be sure that the customer is not included in the accounts history" or something similar?

Sure, it will be improved in next version. Every database exception is logged into sysPass event log and file (syspass.log in config directory).

Thanks for the feedback!
