### ISSUE TITLE
Multiple LDAP groups

### ISSUE THREAD

**Issue by wagnst** [nuxsmin/sysPass#94]
Will there be some kind of feature with that i could assign multiple roles to an user? I am thinking of having LDAP roles for r/w and want to assign a fitting role inside syspass... so that i dont have to assign the role manually?

**Comment by nuxsmin** [comment]
Yes, it could be accomplished for the next release.

**Comment by wagnst** [comment]
Would be really great if I could map ldap groups directly to local groups :-)

**Comment by nuxsmin** [comment]
Added to roadmap #422
