### ISSUE TITLE
Unable to Install Syspass 3.0 Beta 3.0.0.18040302-beta.tar.gz & 3.0.0.18042501-beta.tar.gz on Ubuntu 16.04

### ISSUE THREAD

**Issue by sarojamarraj** [nuxsmin/sysPass#943]
My sysPass-2.1.15.17101701 is running successfully, now i want to  test syspass 3.0 beta version
but im unable to install 

selinux is disable, firewall is turned off , system is up to date

Followed all the steps in proper way, but im stuck with the below mentioned error

 [proxy_fcgi:error] [pid 2947] [client 172.17.45.42:54137] AH01071: Got error 'PHP message: PHP Warning:  require(/var/www/html/syspass/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/syspass/lib/Base.php on line 63\nPHP message: PHP Fatal error:  require(): Failed opening required '/var/www/html/syspass/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/syspass/lib/Base.php on line 63\n'

dont think file autoload.php is available in setup

**Comment by nuxsmin** [comment]
Hello, unfortunately there is some missing documentation, since a few additional steps need to be added to the current docs:

Please take a look to https://github.com/nuxsmin/docker-syspass/blob/e32a9fe00da5345e882d934102e84091390b40e7/sysPass-dev-php7/entrypoint.sh#L20 file, which setups sysPass correctly.

Regards

**Comment by sarojamarraj** [comment]
Thanks for the prompt reply, 
after posting the question i figured out the shared link from which sysPass setups correctly.

Was able to import Users form AD in version 2.1
was expecting to Import the Groups & users from AD in version 3.0
will be too good if we manage to import the permission assigned to groups from AD to sysPass

**Comment by sarojamarraj** [comment]
I'm able to connect to AD by giving all the required details, i can even fetch and see the users and group as i click on check connection
but as i click on to Import Users & groups it gives me Error #Invalid Action, check logs Bind connectivity was also perfect still get the same INVALID ACTION.

**Comment by nuxsmin** [comment]
Please, let me find out what could be wrong. I'll be back shortly.

**Comment by sarojamarraj** [comment]
Nuxsmin, Any update on this ?

**Comment by nuxsmin** [comment]
@sarojamarraj unfortunately I haven't tested it yet since I've been programming  some unit tests for sysPass (automated testing). I'll give a try in next days.

**Comment by nuxsmin** [comment]
@sarojamarraj this issue should be solved in latest commits.

Regards

**Comment by vmario89** [comment]
I just made this dirty gist for syspass 3.0 installation. There are some quirks about root user, www-data user and so on. please oversee it and use the essentials. If there is something missing just comment. We can collect it somewhere to prepare some recent install docs. Maybe comment on the gist itself or just on this issue.

https://gist.github.com/vmario89/196ba73708b5ea77235aeb1d2bac1f77

regards, Mario

**Comment by nuxsmin** [comment]
@vmario89 good gist! I'll will update the doc as soon as I finish the unit testing and new features implementations.

Thanks for your contribution!
