### ISSUE TITLE
[Feature Request] Add user to account only temporary

### ISSUE THREAD

**Issue by gerbsen** [nuxsmin/sysPass#945]
Hey, maybe it's already possible but I couldn't find it. 
It would be absolutely helpful to our corporate workflow if we could add a user only temporary (24/48h) to an account. Most tasks only need to be done once and after that I would need to remember to remove the user from the account again.

Cheers and thanks for this awesome software!! ❤️

**Comment by nuxsmin** [comment]
Hi!, there is currently a feature called "Public Links" which let you create a one time (or many) account access through an unique URL. Once it has expired, you could recreate it by generating a new unique link.

I'm glad to know you liked sysPass!!, thanks for the feedback!.

Cheers

**Comment by gerbsen** [comment]
yeah you are right, this is exactly the same feature! thanks!
