### ISSUE TITLE
LDAPS Issue

### ISSUE THREAD

**Issue by redolphn** [nuxsmin/sysPass#951]
I just installed sysPass to give it a try... I got it up and running and now I'm trying to setup the LDAPS connection to our Active Directory domain controller.

It works perfectly with via LDAP when I attempt it that way, but every time I change it to LDAPS://domain_controller_name it fails and says "Connection error (BIND)"

I know have I LDAP over SSL working properly because I have other servers/services utilizing it.  I thought it was maybe not working because I hadn't added our CA to the sysPass server, but even after doing that I still get the same error.

I noticed in the syspass.log file it throws a "Decryption Error" whenever I try to connect via LDAPS.

What am I doing wrong here?  Thanks in advance!

**Comment by redolphn** [comment]
I added "TLS_REQCERT allow" to the ldap.conf file and LDAPS works now however this is not a good solution since this lessens the security.

**Comment by nuxsmin** [comment]
Could be related? https://serverfault.com/questions/247367/tls-reqcert-and-php-with-ldaps

**Comment by redolphn** [comment]
It does work if I point the ldap.conf file to the pem of the domain controller's cert, but then that does not allow me to have multiple LDAP servers for redundancy.  I should be able to point the ldap.conf file to the root or intermediate pem which issued the domain controller's cert, but this is not working.

**Comment by redolphn** [comment]
I got it working... had to enable the openssl module in php.

**Comment by nuxsmin** [comment]
That sounds good, I'll add a note regarding this requirement in the documentation.

Thanks for the feedback!

**Comment by itpro-tips** [comment]
Hello,
I have the same issue so for now I added 'TLS_REQCERT allow' in ldap.conf..
@nuxsmin I can't find the note in this documentation, I suppose it is not updated yet ?
@redolphn, please can you describe how you solve this issue ?

Thanks !

**Comment by deajan** [comment]
PHP 7.2 now includes openssl.
You may just check that with:
```
/bin/php -r 'phpinfo();' | grep ssl
```
or if you're like me using CentOS 7 and php via SCL:
```
/opt/rh/rh-php72/root/bin/php -r 'phpinfo();' | grep ssl
```

You may then also check if your linux box connects to your ldaps server with:
```
openssl s_client -connect yourldapsserver.domain.local:636
```
or ldap server using TLS
```
openssl s_client -connect yourldapsserver.domain.loca:389 -tls1_2
```

If those work, you may use ldapsearch to manually bind to your LDAP server and see what the problem might be.
On CentOS, install it via:
```
yum install openldap-clients
```

Simple LDAP Query
```
ldapseach -h yourldapserver.domain.local -p 389 -b "dc=domain,dc=local' -D "CN=YourBindAccount,DC=domain,DC=local" -W
```
Add -Z to use tls

If you get
```
ldap_start_tls: Connect error (-11)
        additional info: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (unable to get local issuer certificate)
ldap_result: Can't contact LDAP server (-1)
```

Your certificate might be bad.
You can override this in /etc/openldap/ldap.conf with line
```
TLS_REQCERT     allow
```

Don't forget to restart php-fpm (or apache if using mod_php) for those settings to take effect.

**Comment by nuxsmin** [comment]
Done :wink: 

https://syspass-doc.readthedocs.io/en/3.1/howtos/ldap_troubleshooting.html

Thanks for your contribution @deajan
