### ISSUE TITLE
Permissions in Syspass v3 Beta

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#954]
Hi, I'm having some problems with sysPass v3 beta permissions. It's a little difficult to explain but I'll try here. I tested also this on your demo and saw the same problem, so I'll tell here what I did in your demo so you can test there too.
First, I created a profile "FULL ACCOUNT" with all account permissions (even edit).
Then I created the groups "Application" and "DBA" and the users "app" (with password "app123" and added the group "Application" to this user) and "dba" (with password "dba123" and added the group "DBA" to this user.)
I also created the Client "Fizard" just to be more organized.
Then I was trying to create a group that could edit some accounts, so I created the account "DB - Test" and added in the Account Permission on "Groups" -> "Edit" the group "DBA" and added in the "Groups" -> "View" the group "Application".
I also created the account "Application Test" and added in the Account Permission on "Groups" -> "Edit" the group "Application" and added in the "Groups" -> "View" the group "DBA".
The problem is, when I log in with the user "dba" I can't edit the account "DB - Test" and also when I log in with the user "app" I can't edit the account "Application Test".
One curious thing, when I just remove the "Group" -> "View" from each account then I can edit normally. Is this a bug or the correct way to use it, cause I couldn't understand it.

Thanks!

**Comment by nuxsmin** [comment]
Please, let me take a look to this behaviour and I'll be back then. I need to reproduce these steps as is.

However, I'll need to run deeper testing the ACL behaviour, since it's a critical and tough part in sysPass.

Thanks for the feedback!

**Comment by Fizard** [comment]
Ok. If you need any more details or any help just ask me. Thanks.

**Comment by nuxsmin** [comment]
Hello, could give me some feedback by running the latest commit?. Unit testing reports that ACL is working fine (it ran about 16K tests).

Regards
