### ISSUE TITLE
Custom Fields Order Suggestion

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#957]
Hi Nuxmin. I was searching how to order the sysPass Custom Fields and I just found this in the lib/SP/Repositories/CustomField/CustomFieldRepository.php on getForModuleByID function:
$query = /** @lang SQL */
  ```
          SELECT CFD.name AS definitionName,
            CFD.id AS definitionId,
            CFD.moduleId,
            CFD.required,
            CFD.showInList,
            CFD.help,
            CFD.isEncrypted,
            CFD2.data,
            CFD2.key,
            CFT.id AS typeId,
            CFT.name AS typeName,
            CFT.text AS typeText
            FROM CustomFieldDefinition CFD
            LEFT JOIN CustomFieldData CFD2 ON CFD2.definitionId = CFD.id AND CFD2.itemId = ?
            INNER JOIN CustomFieldType CFT ON CFT.id = CFD.typeId
            WHERE CFD.moduleId = ?
            ORDER BY CFT.text;
```
I think it would be better to order by the required first and id after, so I changed this to:
`ORDER BY required DESC, definitionId ASC;`

But I think it should be better if there was an option that would create another column that would order as I'd like on the CustomFieldDefinition, so I could change the order of the fields the way I wanted to. Is this possible as another feature?

**Comment by nuxsmin** [comment]
Hi @Fizard !

You're right, it would be an useful feature and the default option to order by required has more sense.

Thanks for the feedback!

**Comment by Fizard** [comment]
Hi @nuxsmin, just to notice you, at the CustomFieldRepository.php you changed the line 377 to this:
`ORDER BY CFD.required, CFT.text';`
I recommend to insert the DESC after required, or else the custom fields are going to be the last in the ordering (cause the default is asc and 0 is before 1).
`ORDER BY CFD.required DESC, CFT.text';`
Thanks.
