### ISSUE TITLE
Error on Importing account in CSV file 

### ISSUE THREAD

**Issue by sinaei** [nuxsmin/sysPass#96]
hello, 

I am working with keepass, everything is ok, but I faced with a problem and do not know is it bug or no.
when I want to import the CSV file into the site, it can not be done correctly.
there are two errors, the first thing is Error on importing account, It can not split the csv file correctly and consider two or more rows in one row. 
and the other error is related to sql format. is like this :
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near
'�v�?\�@�qڟ�v�'... 

could you plesae check it and help me about it?

**Comment by nuxsmin** [comment]
Hi, I have tested import functionality with linux and windows file formats and without any issue. The file parser function stores it line by line and then each line is checked to have 7 fields delimited by ;

Can you paste a piece of that file? (No real data needed...)

Kind regards

**Comment by sinaei** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11311481/6502485/24091ff4-c324-11e4-9206-8a3df686b4fc.png)

Hello, This is the screenshot of my result. just one thing is that I changed in the code ";" with "|". with ; it gives me the same error, just for test I changed it to |, but nothing change, 
yes my file contains of  7 fields. 

this is the sample of my data
(the same error)
webgh.hjhy.gs|cutomer|category|URL1|User|password|notes
webgh2.hjhy.gs|cutomer2|category2|URL2|User2|password2|notes2
webgh.hjhy3.gs|cutomer3|category3|URL3|User3|password|notes3
webgh.hjhjds.gs|cutomer4|category4|URL4|User4|password|notes
wiudsh.hjhy.gs|cutomer|category5|URL1|User|password|notes6
jhy.òuuiers|cutomer|category|URL1|User|password|notes 5.10 
webgh.hjhy.gs|cutomer|category|URL1|User|password|notes
webgh.hjhy.gs|cutomer|category|URL1|User|password|notes
webgh.hjhy.gs|cutomer|category|URL1|User|password|notes
webgh.hjhy.gs|cutomer|category|URL1|User|password|notes
webgh.hjhy.gs|cutomer|category|URL1|User|password|notes
webgh.hjhy.gs|cutomer|category|URL1|User|password|notes
webgh.hjhy.gs|cutomer|category|URL1|User|password|notes

**Comment by nuxsmin** [comment]
Hi, sorry for the delay, I were a bit busy...

Here you have some example CSV data that was imported serveral times without any errors:

````
VOIP Account from CSV;Cliente 1;VOIP;http://syspass.org;root;password;Account for VOIP
Google Account from CSV;Google;HTTP;http://syspass.org;root;password;Account for Google
Customer 1 Account from CSV;Customer 1;SSH;http://syspass.org;root;password;Account for Customer 1
````
The only delimiter that works is ";", so it ignores other delimiters.
