### ISSUE TITLE
Feature request: Modify/renew password through API

### ISSUE THREAD

**Issue by GGOUSSEAUD** [nuxsmin/sysPass#961]
Hello again,
I was wondering if you were planning on adding a way to modify an account's password through the API apart from deleting the account and creating it again? It isn't a fail-safe way to do it and you could actually lose the data if you were working with servers and storing the password even temporarily in a file isn't an optimal option to go around that problem.

Let me know if you have anything I could've missed out on.

Regards

**Comment by nuxsmin** [comment]
Hello,

I agree with you, and it's planned for next release, since it's a must for the accounts management.

Thanks for the feedback!

**Comment by GGOUSSEAUD** [comment]
@nuxsmin Any idea when this feature will be released? (timely speaking) Even an approximation could be of use.

**Comment by nuxsmin** [comment]
Hello, the ETA for 3.0 version is by mid-July. Although this feature would be easy to implement, I'd like to complete the code improvements in which I'm working on (unit testing).

Regards

**Comment by GGOUSSEAUD** [comment]
Thank you for your answer, best of luck.
Regards

**Comment by nuxsmin** [comment]
Hello, this feature was added in latest commits. Thanks for the feedback!

Regards.
