### ISSUE TITLE
Config Themes Available Correction

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#962]
Hi @nuxsmin.

I was trying to alter the theme in sysPass v3 beta (latest) and even when I edited the name on index.php it was bringing the Material blue duplicated. So I located the problem, here is what I did to correct this.
On file lib/SP/Core/UI/Theme.php I altered this code on line 206:
`$themeFile = $this->themePathFull . DIRECTORY_SEPARATOR . 'index.php';`
to this code:
`$themeFile = VIEW_PATH . DIRECTORY_SEPARATOR . $themeDir . DIRECTORY_SEPARATOR . 'index.php';`

So it bring all themes correctly. Don't know if this will impact in something else, but hope it helps.

**Comment by nuxsmin** [comment]
Hi @Fizard 

You are right, there was a mistake in that piece of code.

Thanks for the patch!

Regards
