### ISSUE TITLE
Can't delete empty category

### ISSUE THREAD

**Issue by LeDistordu** [nuxsmin/sysPass#965]
Hello,

Can't delete empty category i have error : 

"Error while deleting the category"

**Comment by nuxsmin** [comment]
Hello, which sysPass version are you running?. What did you mean by "empty"?

Regards

**Comment by LeDistordu** [comment]
2.1.15

At first I thought that a category could not be erased because it contained something. Currently I am trying to delete a category that contains no password.

**Comment by nuxsmin** [comment]
It could be so because the category is in use by the accounts' history. I know that this could be a hassle, but items data need to be consistent so they need to keep the relations over the time, so in this way you can fully recover the item's data whenever you need.

Regards

**Comment by LeDistordu** [comment]
Account history ? How do I concretely remove a category that has this problem ?

Thank you for your help
