### ISSUE TITLE
Exportar csv

### ISSUE THREAD

**Issue by krubenrc** [nuxsmin/sysPass#966]
Buenas tardes Rubén, estuve mirando pero no veo opción de ejecutar la exportación en csv mediante la api.

Me gustaria generar con un cron un csv como el que genera la opcion de backup - csv para que en caso de fallo de syspass o servidor, tenga un csv que pueda desencriptar mediante la utilidad que encontre de un contribuidor.

¿Seria posible?

Uso la versión 2

Un saludo y gracias de antemano.

**Comment by nuxsmin** [comment]
Buenas...Rubén también?

Mediante la API sólo está disponible la opción de realizar la copia de seguridad, pero aún así, no existe exportación a CSV, ya que la relaciones entre elementos sería complicada de implementar, por lo que la forma más óptima es usando XML.

Efectivamente hay una herramienta de un colaborador que permite dicha exportación, pero me gustaría implementarla con ciertas funcionalidades como una exportación selectiva de cuentas y otras mejoras. Dicha exportación no podría ser importada de nuevo ya que almacenaria poca información, es decir, la justa para poder obtener la clave de una cuenta en caso de contingencia.

Saludos!

**Comment by krubenrc** [comment]
Ya veo, muchas gracias.

Última duda para aprovechar el hilo:
¿La versión 3.0 será compatible con la 2.0 para exportar e importar?

Un saludo y gracias de antemano.

**Comment by nuxsmin** [comment]
Si, será posible realizar la exportación e importación desde un XML de la versión 2.

Ten en cuenta que para actualizar no será necesario exportar-importar cuentas, ya que el proceso es automático.

Saludos!
