### ISSUE TITLE
Ldap setup (v3.0-beta)

### ISSUE THREAD

**Issue by Titus1024** [nuxsmin/sysPass#968]
Hello,

I have sysPass 3.0-beta (300.18040302) on a CentOS 7 machine, I am trying to set up LDAP with our AD server but am not having any luck. I am getting the following error.

Connection error (BIND)
LDAP ERROR : Can't contact LDAP server (-1)

I have not been able to find any additional log files that give me any other information. I've used the same configuration on other LDAP setups for different apps and on a previous version of sysPass successfully. Please see below for an example of how I have my LDAP configuration setup.

![capture](https://user-images.githubusercontent.com/22060361/41490037-d4bdbae6-70b7-11e8-95e4-89572f0eb315.PNG)

**Comment by nuxsmin** [comment]
Hello,

This issue could be caused by an unreachable LDAP server. Be aware that sysPass will pick a random LDAP server from the AD's DNS.

Regards

**Comment by saulp** [comment]
"sysPass will pick a random LDAP server from the AD's DNS"

butwhy.jpg

**Comment by nuxsmin** [comment]
@saulp because by this way it avoids server fixation and if there were a server failure there are more chances to pick a running server.

**Comment by Titus1024** [comment]
That makes sense, I am specifying the LDAP server by IP though, I've tried by name as well as FQDN. Would you be able to point me in the direction of some logs as well or is what's in the event viewer the equivalent of the log file?

**Comment by Titus1024** [comment]
I found this command "setsebool -P httpd_can_network_connect on" in another post, [here](https://github.com/nuxsmin/sysPass/issues/861) that fixed my issue.

**Comment by Titus1024** [comment]
For those that are having similar issues this was on a CentOS 7 machine. I'll close this now, thanks.

**Comment by nuxsmin** [comment]
Hmm selinux, what a pain!!

Thanks for the feedback
