### ISSUE TITLE
htaccess Protection leads to a login error

### ISSUE THREAD

**Issue by nickbe** [nuxsmin/sysPass#972]
As soon as i use the following .htaccess the login fails:

AuthType Basic
AuthName "Protected Area"
AuthUserFile /var/www/.htpasswd
require valid-user

**Comment by nuxsmin** [comment]
Hmm...you would need to read the docs on "authorization

Regards

**Comment by nickbe** [comment]
Yeah well. I simply need the simplest of all methods, in this case .htaccess to prevent the side from being accessible at all.

Currently I simply don't understand why it's not possible to protect the side as described above. I know how htaccess works, so the authorization documentation does not really help me.

**Comment by nuxsmin** [comment]
From doc: http://doc.syspass.org/en/application/authorization.html

> The Auth Basic authorization is always being checked, so if the HTTP headers within the user data are being sent, it will be checked whether the sysPass user’s login matches with the Auth Basic one.

it means that the provided basic auth user should match with sysPass user's login, if not, it will reject to log in.

**Comment by nickbe** [comment]
Interesting. Thanks.

**Comment by nuxsmin** [comment]
Next 3.0 version includes SSO login using Auth basic.

Regards
