### ISSUE TITLE
Language settings not working

### ISSUE THREAD

**Issue by nickbe** [nuxsmin/sysPass#973]
No matter which language I choose.... it always remain spanish.

**Comment by nickbe** [comment]
Well gentleman, there are several bugs too much for a password storage system right now. In my opinion a password safe like this is like a high security prison. There simply CAN be no mistakes. Sorry.

**Comment by nuxsmin** [comment]
Fine...

Did you installed the right locales on your system?

Regards

**Comment by nickbe** [comment]
Central settings for langauges other than spanishwhatsover is not being honored. Personal settings seem to work.

**Comment by nuxsmin** [comment]
Which version are you running?

It's really weird since demo site is running the same version without any issue.

Regards

**Comment by saulp** [comment]
> There simply CAN be no mistakes. Sorry.

And, I'm sorry this freely-available tool (and one which everybody else seems to have figured out how to change its language) is not good enough for you...

**Comment by nuxsmin** [comment]
@saulp no worries...everyone has its own opinion and flame war should be out of this site ;)

Thanks for your support!!

**Comment by vmario89** [comment]
Hey dudes,

i am currently having the same problem with spanish as unbreakable standard. I am trying to test the most recent syspass 3.0 Beta (3.0.0.18072101-beta) and struggling with the language settings. I already was able to proceed with basic installation to get the vhost display the syspass installation dialog in browser.

What i did:
- installed locales using locale-gen en_US.UTF-8 and set it to default in /etc/default/locale
-i restarted Apache
-i rebooted the whole machine
-i checked if gettext is installed. i tested this with PHP7.1 and PHP7.2
-i looked for presence of .po/.mo files in the syspass directory
all these things are fine. i am still getting spanish installation dialog. Do you have some idea?

my system is Ubuntu 18.04 LTS on an Odroid XU4 with 32 Bit ARMv7 architecture, running with Apache/2.4.29 (built 2018-06-07T21:10:10) and 0.1.29-MariaDB-6 Ubuntu 18.04

An overview of my installed php modules:
root@git-droid:/var/www/vhosts# php -m
[PHP Modules]
calendar
Core
ctype
curl
date
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

root@git-droid:/var/www/vhosts# php --version
PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul  4 2018 16:55:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.7-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
root@git-droid:/var/www/vhosts#


Somebody an idea on what i could do to test/change the language accordingly?

regards, Mario

**Comment by vmario89** [comment]
By the way it's just the installation dialog. After installation the language is working correctly:
![grafik](https://user-images.githubusercontent.com/5631071/43102794-6b3650d2-8ecc-11e8-83db-99c466b00e31.png)

and by the way i just wrote a gist file to remember what i did to install sysPass on Ubuntu without Docker things:

https://gist.github.com/vmario89/2ac0d8b1fb7342f6dde8354fa077cab5
