### ISSUE TITLE
Profile upgrade

### ISSUE THREAD

**Issue by ejouvin** [nuxsmin/sysPass#975]
Just in case.

I finally managed to have sysPass working on Ubuntu 18.04 with php 7.2
But now, I can not do any action with my users.

The problème seems to come from the userProfile configuration stores in table.
For example, I have the following :
```
|              1 | Admin            | O:10:"SP\Profile":22:{s:6:" * _id";i:1;s:8:" * _name";s:5:"Admin";s:11:" * _accView";b:1;s:15:" * _accViewPass";b:1;s:18:" * _accViewHistory";b:1;s:11:" * _accEdit";b:1;s:15:" * _accEditPass";b:1;s:10:" * _accAdd";b:1;s:13:" * _accDelete";b:1;s:12:" * _accFiles";b:1;s:17:" * _configGeneral";b:1;s:20:" * _configEncryption";b:1;s:16:" * _configBackup";b:1;s:16:" * _configImport";b:0;s:12:" * _mgmUsers";b:1;s:13:" * _mgmGroups";b:1;s:15:" * _mgmProfiles";b:1;s:17:" * _mgmCategories";b:1;s:16:" * _mgmCustomers";b:1;s:16:" * _mgmApiTokens";b:0;s:7:" * _evl";b:1;s:19:" * _mgmCustomFields";b:0;}        |
|              2 | Utilisateur      | O:10:"SP\Profile":22:{s:6:" * _id";i:2;s:8:" * _name";s:11:"Utilisateur";s:11:" * _accView";b:1;s:15:" * _accViewPass";b:1;s:18:" * _accViewHistory";b:1;s:11:" * _accEdit";b:1;s:15:" * _accEditPass";b:1;s:10:" * _accAdd";b:1;s:13:" * _accDelete";b:1;s:12:" * _accFiles";b:0;s:17:" * _configGeneral";b:0;s:20:" * _configEncryption";b:0;s:16:" * _configBackup";b:0;s:16:" * _configImport";b:0;s:12:" * _mgmUsers";b:0;s:13:" * _mgmGroups";b:0;s:15:" * _mgmProfiles";b:0;s:17:" * _mgmCategories";b:1;s:16:" * _mgmCustomers";b:1;s:16:" * _mgmApiTokens";b:0;s:7:" * _evl";b:0;s:19:" * _mgmCustomFields";b:0;} |
```

When I create a profile with all permissions, I have the following :
```
|              3 | Tmp              | O:24:"SP\DataModel\ProfileData":32:{s:10:" * accView";i:1;s:14:" * accViewPass";i:1;s:17:" * accViewHistory";i:1;s:10:" * accEdit";i:1;s:14:" * accEditPass";i:1;s:9:" * accAdd";i:1;s:12:" * accDelete";i:1;s:11:" * accFiles";i:1;s:13:" * accPrivate";i:1;s:18:" * accPrivateGroup";i:1;s:16:" * accPermission";i:1;s:17:" * accPublicLinks";i:1;s:18:" * accGlobalSearch";i:1;s:16:" * configGeneral";i:1;s:19:" * configEncryption";i:1;s:15:" * configBackup";i:1;s:15:" * configImport";i:1;s:11:" * mgmUsers";i:1;s:12:" * mgmGroups";i:1;s:14:" * mgmProfiles";i:1;s:16:" * mgmCategories";i:1;s:15:" * mgmCustomers";i:1;s:15:" * mgmApiTokens";i:1;s:17:" * mgmPublicLinks";i:1;s:14:" * mgmAccounts";i:1;s:10:" * mgmTags";i:1;s:11:" * mgmFiles";i:1;s:6:" * evl";i:1;s:18:" * mgmCustomFields";i:1;s:14:"userprofile_id";i:0;s:16:"userprofile_name";s:3:"Tmp";s:19:"userprofile_profile";N;} |
```

I do not know if I missed something from previous upgrade, but I believe this is a problem with the serialize from the ProfileClass.

In case a migration is required, it may be hard because it seems that field were modified ?

For now, I can only try to configure my profile with application administrator account. Should be quick, because I only have 2.

But may be, this is good to know, if it is the case, that profile may cause a problem.

**Comment by nuxsmin** [comment]
Hi, it seems that something went wrong when deserializing the profile data, since the serialized class has changed so the deserializing method is actually a wrapper that "casts" the old class to the new one.

It could be caused by the PHP version. I've not tested sysPass yet on 7.2 version.

**Comment by ejouvin** [comment]
Ok.

It must be an error during my upgrade. I may miss something or had an error somewhere that I did not noticed.
Anyway, this is for 2.1.16 version, just in case. I do not think it is necessary to investigate more thant that.
