### ISSUE TITLE
Inconsistent failure modes when installation failure.

### ISSUE THREAD

**Issue by KimTheFirst** [nuxsmin/sysPass#977]
The installer may or may not delete the database, depending on the specific installation failure. It seems that the flag "Hosting Mode" was intended to ensure that the installer does not perform creation / deletion routines however, this is not checked in at least one instance of createDBStructure() being called, which in the event of an error will delete the database and attempt to delete the user.

**Comment by nuxsmin** [comment]
I agree with you, it shouldn't delete the database when hosting mode is set.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
Solved in v3
