### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Smokemonster8** [nuxsmin/sysPass#98]
I cannot complete the installation process.  It seems like this type of error is recurring in sysPass...

Whenever I try to install sysPass, I get the following errors, in a loop, until PHP runs out of memory:

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/localhost/htdocs/sysPass/inc/db.class.php on line 264

Warning: mysqli::query(): Couldn't fetch mysqli in /var/www/localhost/htdocs/sysPass/inc/db.class.php on line 209

Warning: DB::doQuery(): Couldn't fetch mysqli in /var/www/localhost/htdocs/sysPass/inc/db.class.php on line 215

Warning: DB::doQuery(): Couldn't fetch mysqli in /var/www/localhost/htdocs/sysPass/inc/db.class.php on line 216

Warning: DB::doQuery(): Couldn't fetch mysqli in /var/www/localhost/htdocs/sysPass/inc/db.class.php on line 219

Warning: DB::doQuery(): Couldn't fetch mysqli in /var/www/localhost/htdocs/sysPass/inc/db.class.php on line 219

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/localhost/htdocs/sysPass/inc/db.class.php on line 264

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/localhost/htdocs/sysPass/inc/db.class.php on line 264

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/localhost/htdocs/sysPass/inc/db.class.php on line 264

Warning: mysqli::real_escape_string(): Couldn't fetch mysqli in /var/www/localhost/htdocs/sysPass/inc/db.class.php on line 264

**Comment by nuxsmin** [comment]
Hi, this usually happens when database permissions are wrong. Take care about hosting mode if you are installing on a hosting provider and there is any restrictions on database or user creation.

**Comment by Smokemonster8** [comment]
I do not believe this is a database permission issue directly.  The install script creates some tables and a user, but fails beyond that.  This is when using a database that is not "localhost".  I have tried in another environment and used localhost as the database resource, and the installer will complete, but when I log in I only get a half-loaded web page.  There are numerous other PHP applications running in the same environment (Mediawiki and PHPLdapAdmin for example) but this is the only application that fails to install correctly.

I did notice that when I try to install from on a remote database server, from a web server with more than one IP address, it tries to set up the database user as coming from the first IP address on the web server, which is more often than not incorrect.  I have modified your code to use '%' as the database user hostname, but install still does not complete correctly.

The few times I have actually been able to install this, I am able to log in with any username and password combination, valid or not.  But it does not matter, because I get a half loaded index page that does not work or display anything other than the logo and a search box/icon.

**Comment by nuxsmin** [comment]
Hi, it's very strange, I've done several tests on a few environments (Debian, centos, windows, hosting, etc) and, despite some issues with database permissions or php verbosity, the app runs fine.

Can you tell me some information about your environment?

Database user's permissions were fixed a time ago, and I think that an app should be restrictive when giving access to users, so % is not an option for me so I let to the user take his decision. A normal user does not have to deal with this kind of configuration, so advanced users can go further and take some actions before installing like create the database (no tables) and its user, so the installation can be ran in hosting mode to avoid these tasks.

**Comment by Smokemonster8** [comment]
I am trying on a Gentoo virtual machine.  It only has Apache, MySQL and PHP installed besides the base OS.  For testing the installer, the admin name and password were: admin/password.  Here is a video showing what happens when I install:

http://screencast.com/t/WAH1Terw4v

Here is what I see in the apache error logs during the install:

[Thu Mar 26 09:11:53 2015] [error] [client 192.168.1.101] Action: New Group -- Description: Group: Admins, referer: http://192.168.2.60/sysPass-1.1/
[Thu Mar 26 09:11:53 2015] [error] [client 192.168.1.101] PHP Notice:  Undefined index: pAppMgmt in /var/www/localhost/htdocs/sysPass-1.1/inc/profiles.class.php on line 170, referer: http://192.168.2.60/sysPass-1.1/
[Thu Mar 26 09:11:53 2015] [error] [client 192.168.1.101] Action: New Profile -- Description: Profile: Admin, referer: http://192.168.2.60/sysPass-1.1/
[Thu Mar 26 09:11:53 2015] [error] [client 192.168.1.101] Action: New User -- Description: User: Admin (admin), referer: http://192.168.2.60/sysPass-1.1/
[Thu Mar 26 09:11:53 2015] [error] [client 192.168.1.101] Action: Configuration -- Description: Update Configuration, referer: http://192.168.2.60/sysPass-1.1/
[Thu Mar 26 09:11:53 2015] [error] [client 192.168.1.101] Action: Configuration -- Description: Update Configuration;;Parameter: version;;Value: 11217, referer: http://192.168.2.60/sysPass-1.1/

Here is a link to a mysqldump of the syspass database that was creating during the install in this video:

http://pastebin.com/54jR1Y4w

Here is the config.php generated from the install I tried making the video:

<?php
// Generated on 1427375513
// This file is generated automatically on installation process
// Please, modify with caution, it could break the application
$CONFIG = array (
  'account_count' => 12,
  'account_link' => 1,
  'checkupdates' => 1,
  'dbhost' => 'localhost',
  'dbname' => 'syspass',
  'dbpass' => 'e91ab1a7d4b1bd9e51a5f94a968f1d57',
  'dbuser' => 'sp_admin',
  'debug' => 0,
  'demo_enabled' => 0,
  'files_allowed_exts' => 'PDF,JPG,GIF,PNG,ODT,ODS,DOC,DOCX,XLS,XSL,VSD,TXT,CSV,BAK',
  'files_allowed_size' => 1024,
  'files_enabled' => 1,
  'installed' => 1,
  'ldap_base' => '',
  'ldap_enabled' => 0,
  'ldap_group' => '',
  'ldap_server' => '',
  'ldap_userattr' => '',
  'log_enabled' => 1,
  'mail_enabled' => 0,
  'mail_from' => '',
  'mail_server' => '',
  'passwordsalt' => '565329805b90995812747a6e713a37',
  'session_timeout' => '300',
  'site_lang' => 'en_US',
  'version' => '11217',
  'wiki_enabled' => 0,
  'wiki_filter' => '',
  'wiki_pageurl' => '',
  'wiki_searchurl' => '',
);

If I can give you anything else to help troubleshoot, please let me know.

**Comment by nuxsmin** [comment]
Hi, thank you for your troubleshooting points, great work!

Can you take a look to the comments below this https://github.com/nuxsmin/sysPass/issues/88#issuecomment-74845702 ?

It seems that you have PHP logging configured for developing, so there can be some annoying messages about unused variables or deprecated functions.

**Comment by Smokemonster8** [comment]
I have set display_errors to off.  I have dropped the database and the database user created from the installer.  I have removed the config.php from the config folder.  I re-ran the installer, and I have the same exact results, only it does not display the php warning any more.  I am able to "log in" (if you can call it that) with any username and password combination, but I land on a "blank" screen with one button, which does not work at all, just as my video shows.

**Comment by nuxsmin** [comment]
Let me take a look and do some tests again on that environment. It seems that something is breaking javascript response, so content isn't loaded right.

**Comment by nuxsmin** [comment]
Hi again!!

I've successfully installed sysPass on a Gentoo fresh installation (some hours compiling and kernel hacking). You can take a look to the steps that I've taken to get it: http://wiki.syspass.org/en/install-gentoo

No errors were reported during installation and the only issue was when connecting to the DB, because "localhost" points to an UNIX socket that apache user doesn't have permission to read, so I set it to 127.0.01 (TCP connection).

Let me know if you still have any issue.

**Comment by Smokemonster8** [comment]
Wow, what great support for you to go through the pain of learning how to install Gentoo for me.  I've been using it for 15 years, but I understand it is not as friendly to install as something like Ubuntu.  Amazing level up support for an open source project which is maintained by one person (at least I think it is).

Anyway, I appreciate that you took the time to create a wiki page for this.  I will make some time to follow your guide, and I will report back with my results.  I am a PHP developer myself, so if it still does not work for me, I will try to debug and help.

I guess I should mention that my end goal here is to get this running on MySQL cluster.  I make use of the php mysqlnd_ms_plugin to have PHP applications I write load so they balance between SQL nodes in my cluster.  Once I get a basic install of sysPass working, I will try converting table engines to ndbcluster and try using the mysqlnd_ms_plugin as my database source.  I don't see why it should not work after some minor tweaking.  I thought I'd mention it.  Maybe as you continue to develop this project you will consider design decisions based on feedback like this.

**Comment by shamis-illya** [comment]
Hi,

the same issue by me. I'm trying to install SysPass at Gentoo ManagedServer, I have root permissions over MySQL DB, as I've installed my own precompiled MySQL Server at port 3309. 

Do you have any solution way about manual installation of SysPass? 
I'm able to import dbstructure.sql direct into DB, which Values should I add and how do you build the passwords in config File (MD5 Hash?!).

Thank you in advance.

**Comment by nuxsmin** [comment]
I'm very glad that you appreciate it, thanks!

I were dealing with gentoo at the very first (about year 2002), but I couldn't spent so many hours compiling, so I switched to Debian :) and now I use LMDE for desktop daily use and Debian for servers.

Now Gentoo is very nice (coloured emerge and more...), and it's not so difficult to get it working (despite kernel hacking).

I've not already set a cluster with mysql, but it would be great if you can share your experience to get it working with sysPass.

Kind regards

**Comment by nuxsmin** [comment]
Hi @shamis-illya 

you can set the default port in the file '/etc/php/apache2-php5.5/php.ini' by setting the variable 'mysqli.default_port='

sysPass does not set a db connection port, so you can tweak it in php configuration.

Kind regards

**Comment by shamis-illya** [comment]
Well, actually I also had problem installing SysPass at my Gento ManagedServer. I don't have root permissions at that server, so I cannot do the steps, that you've wrote in Wiki here http://wiki.syspass.org/en/install-gentoo.

All I could do is to user preinstalled Apache 2.4 and my own MySQL. But as the default Hosters MySQL was preinstalled at port 3306, I've decided to install my own MySQL at port 3309. I believe that SysPass has problems creating user and connecting  to the MySQL DB that runs at different port that default (3306) one.

mysql> SELECT User,Host FROM mysql.user;
+------------   +------------------------+
| User            | Host                      |
+------------    +------------------------+
| root             | 127.0.0.1               |
| sp_syspass | 127.0.0.1:3309      |
| root             | ::1                          |
|                    | localhost                |
| root             | localhost                |
+------------   +----------------------- +


SysPass could import dump into DB but it was not able to connect DB (at least I believe so). The config.php had no value 'installed' => 1 . After adding that value into the file, I've seen error message, saying that SysPass couldn't connect DB.

**Comment by shamis-illya** [comment]
OK, thanks for the hint. 
I'll try to add the port settings into local php.ini file that I'll place into SysPass folders.

**Comment by nuxsmin** [comment]
@shamis-illya  can you test the latest build (7e46e7bc325e6685befa4010482637c9abce5102)?

I've added the connection port by adding ":port_number" to hostname e.g. "127.0.0.1:3309"

**Comment by nuxsmin** [comment]
Hi there!

Did you get it working?

**Comment by Smokemonster8** [comment]
I have not been able to get it working.  I have not had time to dig in and debug the code to see where it might be failing.  I need a password storage solution, so I will give it one more shot.

**Comment by nuxsmin** [comment]
Hi, recently I've been dealing with a similar issue and the solution was to refresh JavaScript cached response by pressing ctrl+f5, because the first response was cached with the displayed errors in the code, so later responses were broken.

Let me know if it works...

Kind regards
