### ISSUE TITLE
Grupo por defecto en las cuentas

### ISSUE THREAD

**Issue by krubenrc** [nuxsmin/sysPass#981]
Buenos días Rubén, tengo una duda, ¿es posible definir un grupo por defecto para las nuevas cuentas de claves? por defecto se meten en el grupo "admin" pero me gustaría que se metieran en otro grupo distinto.

Un saludo y gracias de antemano.

**Comment by nuxsmin** [comment]
Buenas!

Si te refieres a los usuarios que se crean con LDAP activado, es posible indicarlo en la configuración de LDAP. Para el resto de usuarios es el grupo que está establecido para cada uno.

Saludos!

**Comment by krubenrc** [comment]
Hola, me refería a las credenciales, cuando creo una credencial nueva la asigna al grupo admin y me gustaría que las añadiera por defecto a otro grupo.

Saludos y gracias :D!

**Comment by nuxsmin** [comment]
Ahh, ok, me he confundido...si es posible asignarlas a otro grupo en la sección de accesos. En la siguiente versión se podrá establecer un grupo por defecto para cierto tipo de cuentas.

Saludos!
