### ISSUE TITLE
User in serveral groups only see credentials in its initial group

### ISSUE THREAD

**Issue by Xumeiquer** [nuxsmin/sysPass#982]
Hi,

When creating a user it's required to assign a group. Later I add users to other different groups.

The issue is a user only can see accounts that has user's group in the access groups permissions. But not other accouts with different gorups that the user belongs to.

SysPass version: 2.1.16

Kind regards.

**Comment by nuxsmin** [comment]
Hi, 

You would need to enable secondary group access on 'configuration > accounts' tab.

This option will grant access to those users which are included in a secondary group of an account.

Kind regards

**Comment by Xumeiquer** [comment]
It works.

Thanks a lot.
