### ISSUE TITLE
Importing users from AD

### ISSUE THREAD

**Issue by DonVahid** [nuxsmin/sysPass#984]
Hello everyone,
I'm having a problem with importing users from AD. When i click on Check button it says "LDAP connection is OK" and also "Objects found: 9" which is correct. (screenshot [here](https://ibb.co/cWnE2J) )
The problem is when i want to import these users. (screenshot is [here](https://ibb.co/nLQWXJ) )

i also tried changing Login and Name attributes, LDAP Server, Unchecked "Enable LDAP", etc. and non of them worked.

**Comment by nuxsmin** [comment]
Hello,

it seems that you didn't save the LDAP params before importing the users. Be aware that you don't really need to import the LDAP users, since sysPass will create them on their first login (using the default group and profile set).

Regards.

**Comment by DonVahid** [comment]
Hello,
Thank You it solved my problem, You Have Been a Great Help.

Best Regards.
