### ISSUE TITLE
Logs are shown in ISO-8859 Syspass v3

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#986]
Hello,

Just started my test instance of sysPass v3.
One thing I noticed, my logs show UTF-8 characters encoded in ISO-8859.

```
37615	2018-07-04 17:31:41	INFO	searchUserInGroup	 	yy.yy.yy.yy	Utilisateur vÃ©rifiÃ© dans le groupe
Groupe : CN=SYSTEMGRP SysPass,OU=Groupes,DC=domain,DC=local
37614	2018-07-04 17:25:02	INFO	DÃ©connexion	user xx.xx.xx.xx	Utilisateur : user
Temps d'inactivitÃ© : 0,07 min.
Temps total : 7,17 min.
```

My setup is a CentOS 7x64 server with rh-php70-php-fpm and apache 2.4.16.
I have another vhost configured with SysPass v2 (configs are exactly the same except of the path), and the earlier version does not have those encoding problems.
Characters involved are french accents like 'é è à'.

Best regards.

**Comment by deajan** [comment]
Just noticed that new event log messages are well encoded.
So it's just the migrated messages from v2 to v3 that have the encoding issue.

**Comment by nuxsmin** [comment]
Great!, I did a slightly check out, but didn't find any issue
