### ISSUE TITLE
Show passwords only as picture and disable clipboard

### ISSUE THREAD

**Issue by TitovLab** [nuxsmin/sysPass#99]
Good day! Thank for great application!
Many administrators and helpdesk use remote connections like RDP, TeamViewer, LogMeIn and etc. This applications tansfer clipboard to remote hosts and it is dangerous to use clipboard for passwords.
I am not a programmer, but after google I implement this like:
1. Create ./ajax/imagepass.php
<?php
// Establish image factors:
$text = $_GET['pass'];
$font_size = 11; // Font size is in pixels.
$font_file = 'tahomabd.ttf'; // This is the path to your font file.

// Retrieve bounding box:
$type_space = imagettfbbox($font_size, 0, $font_file, $text);

// Determine image width and height, 10 pixels are added for 5 pixels padding:
$image_width = abs($type_space[4] - $type_space[0]) + 3;
$image_height = 22;

// Create image:
$image = imagecreatetruecolor($image_width, $image_height);

// Allocate text and background colors (RGB format):
$text_color = imagecolorallocate($image, 85, 85, 85);
$bg_color = imagecolorallocate($image, 224, 234, 254);

// Fill image:
imagefill($image, 0, 0, $bg_color);

// Fix starting x and y coordinates for the text:
$x = 0; // Padding pixels.
$y = $image_height - 5; // So that the text is vertically centered.

// Add TrueType text to image:
imagettftext($image, $font_size, 0, $x, $y, $text_color, $font_file, $text);

// Generate and send image to browser:
header('Content-type: image/png');
imagepng($image);

// Destroy image in memory to free-up resources:
imagedestroy($image);

?>
2. Upload font file to ./ajax/tahomabd.ttf (we can get it from any Windows OS from fonts folder)
3. Comment one line in./ajax/ajax_search.php to disable clipboard button
4. Modify ./ajax/ajax_viewpass.php (I removed some < and > because github do not show this code as text):
div id="fancyMsg" class="msgInfo" style="width: 500px;">
td>IMG src="/ajax/imagepass.php?pass=<?php echo urlencode($accountPass); ?>"></td
I think developer can do this better, for exaple via configuration option in sysPass.
P.S.: I translate sysPass to Russian, how can I upload to developers .po and .mo files?

**Comment by nuxsmin** [comment]
Hi, thank you for your support, it's nice that you like sysPass and find it useful.

Your feature idea is good and I really thought about it a time ago, but I decided to leave it because there weren't many applications and I thought that other features had a higher priority, but now you have done some work about it and I think it can be useful for next release, so I can merge your code to get it working.

About translations, you can send me the .po file (translations@syspass.org) or make a pull request to merge it.

Kind regards

**Comment by TitovLab** [comment]
Translations send to translations@syspass.org
Thank you!

**Comment by nuxsmin** [comment]
Big thanks!!
