### ISSUE TITLE
Cannot remove LDAP user in sysPass v2.1.15

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#990]
Hello,

Trying to delete some LDAP imported user accounts.
Here's what I get:
```
Erreur pendant la requête
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails
(`syspass_production`.`accHistory`, CONSTRAINT `fk_accHistory_users_edit_id` FOREIGN KEY (`acchistory_userEditId`) REFERENCES `usrData` (`user_id`)) (0)SQL : '
DELETE 
FROM usrData 
WHERE user_id = ? 
LIMIT 1'
```

I guess there's data attached to the user account. If this happens to be the case, how can I "mass assign" the data to another user in order to delete the account please ?

**Comment by nuxsmin** [comment]
Hello, 

Unfortunately that feature hasn't been implemented yet, so you would need to achieve it by the "not so easy" way: updating the database.

This feature will be available in v3 ;)

Regards

**Comment by deajan** [comment]
Okay, I can live with a manual query as for now.
Man, you'll have a hell lot of work in order to get v3 ready with all the features pending...

**Comment by nuxsmin** [comment]
>  Man, you'll have a hell lot of work in order to get v3 ready with all the features pending...

Yes, they will be accomplished by priority but the key one is unit testing, it will provide more confidence and faster development.

OT: your #912 FR will be ready when releasing v3 (was by mid-July but August would be more real)

**Comment by deajan** [comment]
Thanks for letting me know about #912.
Unit testing took me quite as much time as development for my biggest git project (I'm not a pro dev btw), so well... good luck again.
Just reach out if you have more beta testing do to, I'll be glad to help.

**Comment by nuxsmin** [comment]
> Unit testing took me quite as much time as development for my biggest git project (I'm not a pro dev btw), so well... good luck again.

Nice, I didn't notice you have developed some useful software. I'm glad to know you like developing, it's a hard and addictive hobby ;)

Thanks for your support!

**Comment by nuxsmin** [comment]
Hello, this feature was implemented in v3 (bulk edit)

Thanks for the feedback!
