### ISSUE TITLE
BETA 3.0.0.18071602 Error after login

### ISSUE THREAD

**Issue by Whatsek** [nuxsmin/sysPass#991]
After a few failed update efforts I have now a working updated 3.0 version. 
With the normal update procedure the update of the database always failed or timed out. So now I installed a clean empty 3.0, I made a duplicate database of the 2.0 version, ran the upgrade database script in adminer.php, and edited the config file manually. Everything works fine, and is migrated. But when I login this error is displayed:

`SyntaxError: Unexpected token C in JSON at position 0parsererror `

When I press F5 to reload, I am in my working sysPass, nothing wrong. But when I try to login again, this error comes again.

**Comment by Whatsek** [comment]
I did not run the upgrade script, it always gave an error or timeout. (Thats why I did my workaround)

I just went to the upgrade page, en did the upgrade anyway. It said upgrade went fine (4 seconds) but the error is still there.

I also would like to thank you for a great piece of software!

**Comment by nuxsmin** [comment]
Please, could you take a look to `syspass.log` file within `app/config` directory?, and could check out the if there is any message on browser console (F12) when logging in?

I'm glad to know that you found sysPass useful!

Regards.

**Comment by Whatsek** [comment]
Yes, there an error logged. With my clean install there was no error so the cause is my way of upgrading. (But I really wanted to use 3.0 because of the User group rights management) so I can live with the error for now ;-) (And I like to try new versions out)

This is the error:

```
2018-07-19 12:38:17 - Routing error: Call to a member function composeText() on null
2018-07-19 12:38:17 - Routing error: #0 /volume1/web/syspass/lib/SP/Core/Events/EventDispatcherBase.php(120): SP\Providers\Log\SyslogHandler->updateEvent('login.preferenc...', Object(SP\Core\Events\Event))
#1 /volume1/web/syspass/lib/SP/Services/Auth/LoginService.php(382): SP\Core\Events\EventDispatcherBase->notifyEvent('login.preferenc...', Object(SP\Core\Events\Event))
#2 /volume1/web/syspass/lib/SP/Services/Auth/LoginService.php(166): SP\Services\Auth\LoginService->loadUserPreferences()
#3 /volume1/web/syspass/app/modules/web/Controllers/LoginController.php(69): SP\Services\Auth\LoginService->doLogin()
#4 [internal function]: SP\Modules\Web\Controllers\LoginController->loginAction()
#5 /volume1/web/syspass/lib/SP/Bootstrap.php(244): call_user_func_array(Array, Array)
#6 [internal function]: SP\Bootstrap->SP\{closure}(Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#7 /volume1/web/syspass/vendor/klein/klein/src/Klein/Klein.php(886): call_user_func(Object(Closure), Object(Klein\Request), Object(Klein\Response), Object(Klein\ServiceProvider), Object(Klein\App), Object(Klein\Klein), Object(Klein\DataCollection\RouteCollection), Array)
#8 /volume1/web/syspass/vendor/klein/klein/src/Klein/Klein.php(588): Klein\Klein->handleRouteCallback(Object(Klein\Route), Object(Klein\DataCollection\RouteCollection), Array)
#9 /volume1/web/syspass/lib/SP/Bootstrap.php(452): Klein\Klein->dispatch(Object(Klein\Request))
#10 /volume1/web/syspass/lib/Base.php(74): SP\Bootstrap::run(Object(DI\Container))
#11 /volume1/web/syspass/index.php(28): require('/volume1/web/sy...')
#12 {main}
```

**Comment by nuxsmin** [comment]
Hmm, it seems you're using syslog event logging handler so it needs a tweak to manage an exception message. This issue was fixed in the database event logging handler, but I forgot to apply the patch in other handlers.

Thanks for the feedback!

**Comment by Whatsek** [comment]
I disabled 'syslog' and 'remote syslog' now the error is gone. Will test with the next version! Thank you for your time.
(Also thanks for sysmonDash, would have never found it without sysPass)

**Comment by nuxsmin** [comment]
Fine! You're welcome

I'm glad to code useful applications ;)

**Comment by nuxsmin** [comment]
Hello, it should be fixed in the latest commit. Please, let me know if it works fine

Regards

**Comment by Whatsek** [comment]
Hi Nuxsmin, just upgraded to the 21 july version and enabled remote syslog, no more errors. 
Syspass working fine again!

Thank you, I will keep testing the new releases!

**Comment by nuxsmin** [comment]
Thanks for the feedback!
