### ISSUE TITLE
LDAP Connection error

### ISSUE THREAD

**Issue by kitenberg** [nuxsmin/sysPass#993]
Hi I installed sysPass and everything work properly except the LDAP integration which fail. 
Every time I try to test it, I get the following error:
Connection error (BIND)
LDAP ERROR : Can't contact LDAP server (-1)
LDAP DN : cn=xxx,ou=xxxe,ou=xxx,dc=xxx,dc=xxx,dc=net,dc=xxx (masked the details)

![image](https://user-images.githubusercontent.com/9526809/43056664-d0964686-8e80-11e8-8285-48d493f03429.png)

Every time I'm tying to test, a Decryption error log is appears in /syspass.log.

I also captured the traffic and there are no packets to the active directory server.

Does anyone familiar with that issue?

Thanks,
Dor

**Comment by kitenberg** [comment]
By capturing the traffic, I could see a DNS request for that server but I can also see that he gets a response with a proper AD IP.

Any Idea how can I debug it?

**Comment by kitenberg** [comment]
Hi, I add the se linux configuration and now it works.
But now it fails on the SSL handshake to the AD.
I can see that the AD sends the server certificate and it validated by the syspass client but the client (syspass server) is not sending any certificate back and it fails. 
Not sure where I configure the ldap client to use the right client cert+key.

Any ideas?

**Comment by nuxsmin** [comment]
Hi, it's most likely that they are stored in `/etc/ssl` but it depends on the Linux distribution. You would need to import the CA's certificate in order to avoid security warnings  or no-op on the client side.

**Comment by kitenberg** [comment]
I did that but it still doesn't work.
I'm trying now to use just normal LDAP without SSL but it says that the Domain Controller requires Strong Authentication.
Which is not true, I'm using other system with regular LDAP authentication and it works just fine.
![image](https://user-images.githubusercontent.com/9526809/43442914-c590c4b0-94e2-11e8-9260-6d603148e559.png)

How can I solve it?

**Comment by nuxsmin** [comment]
@kitenberg I haven't seen this message before. It's thrown by the PHP module, since sysPass does not enforce any connection method. Are you using a blank password for binding?

**Comment by kitenberg** [comment]
No, I'm using the correct password.

**Comment by nuxsmin** [comment]
Please, take a look to these posts:

https://stackoverflow.com/questions/5991591/php-ldap-stronger-authentication-required
https://blogs.technet.microsoft.com/askds/2009/09/21/understanding-ldap-security-processing/
https://www.dirwiz.com/kb/346

**Comment by kitenberg** [comment]
Hey, 
I added the mentioned line to the ldap.conf and now it works using TLS (LDAPS).

I don't understand why a user needs to put the master password with every first login. It's not practical. I must give everyone the master password.

Is there any way to disable this?

**Comment by nuxsmin** [comment]
@kitenberg I'm glad it's running now.

Regarding the master password, it's needed because it isn't stored anywhere, so every first login will require to enter it. You can use the temporary master password feature, so you don't need to send the real master password and it will expire by the time you set.
