### ISSUE TITLE
error after ssl certification attach in syspass while hosting..

### ISSUE THREAD

**Issue by Dexter822** [nuxsmin/sysPass#995]
**sysPass Version**
Can be found on `Config -> Information` tab

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Event log**
Some lines from `syspass.log` file (within `config` directory) and sysPass event log that were logged when the error happened.

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Android]
 - OS Version
 - Browser [e.g. Firefox, Chrome]

**Additional context**

**Comment by nuxsmin** [comment]
Hello,

sysPas does not handle SSL certificates by itself, so you would need to configure the web server to use SSL connections.

Please let me know more about this issue...

**Comment by Dexter822** [comment]
but how to configure the web server??
Is it by .htaccess

**Comment by nuxsmin** [comment]
https://www.digitalocean.com/community/tutorials/how-to-create-a-ssl-certificate-on-apache-for-ubuntu-14-04
