### ISSUE TITLE
Recover Master Password

### ISSUE THREAD

**Issue by kitenberg** [nuxsmin/sysPass#996]
Hi,

I kept the master password but looked like it was deleted.

Is there any way to restore it?

Thanks

**Comment by nuxsmin** [comment]
Hi, unfortunately there is no way to restore it. Do you still have access to sysPass as an admin user?

**Comment by kitenberg** [comment]
Yes

**Comment by nuxsmin** [comment]
You could replace this file (https://gist.github.com/nuxsmin/ca59f3754312fb6d54b2cf45283bf754) and enable debug mode on config section. It will display the current master password.

**Comment by deajan** [comment]
Could be useful in troubleshooting section of documentation :)

**Comment by kitenberg** [comment]
I replaced the file but where exactly it shows the master password in the debug log?

**Comment by nuxsmin** [comment]
It will show it up on the debug information box on the web browser.

**Comment by kitenberg** [comment]
Found it. Thanks!

**Comment by nuxsmin** [comment]
Great!

**Comment by nuxsmin** [comment]
@deajan written down in #422

**Comment by DGothmin** [comment]
Can you please give me more info? What is the local location to replace this "Debug.inc" file?
