### ISSUE TITLE
 Unable to write into the "/config" directory

### ISSUE THREAD

**Issue by atmcommunicaction** [nuxsmin/sysPass#997]
I have read all the possible resolutions for this problem.
If I insert chmod 750 on direcotry / config, this does not work yet.
How can I solve?

Thank you!

**Comment by atmcommunicaction** [comment]
i have a vps with ubuntu 16,  
what advice do you do?

**Comment by nuxsmin** [comment]
Hello, did you follow the installation instructions on the documentation site?

Regards

**Comment by atmcommunicaction** [comment]
yes yes... i try to chmod to 777 but the system response: 
![error1](https://user-images.githubusercontent.com/33314658/43527310-9a6ae2b0-95a6-11e8-89ab-9c12deb205a5.jpeg)

if i try chmod 750 : 

![error2](https://user-images.githubusercontent.com/33314658/43527383-cc2a223e-95a6-11e8-94d1-c01e108758a9.jpeg)

**Comment by nuxsmin** [comment]
Is the owner correctly set?. It should be www-data

**Comment by atmcommunicaction** [comment]
yes, /config and /backup
![error3](https://user-images.githubusercontent.com/33314658/43528351-09ccea0c-95a9-11e8-8f87-f7ce307cd033.jpeg)

**Comment by nuxsmin** [comment]
It could be the group set, could you change it?

**Comment by atmcommunicaction** [comment]
i change it, but non work.

**Comment by atmcommunicaction** [comment]
![error 4](https://user-images.githubusercontent.com/33314658/43529906-9b90fdcc-95ac-11e8-8da9-892826e2f102.jpeg)

**Comment by nuxsmin** [comment]
It should be 750, ie. rwxr-x---

**Comment by atmcommunicaction** [comment]
rwxr-x--- 2 www-data www-data  4096 Aug  1 14:50 config .   
but not work.

**Comment by nuxsmin** [comment]
Really weird, I've no idea about what could be happening.

**Comment by OnoTime** [comment]
Are you working with apache? Can you see the user use with on ps ?

**Comment by atmcommunicaction** [comment]
I resolve... with filezilla... 
but i have a another problem.


I have another problem, it does not give me the possibility to copy the password from the profiles

![password](https://user-images.githubusercontent.com/33314658/43890848-254da512-9bc8-11e8-9c99-60dce12fa081.jpeg)

**Comment by nuxsmin** [comment]
@atmcommunicaction that sounds good. Did you enable show image for account's password?

**Comment by atmcommunicaction** [comment]
little crash my mental. I resolve! TNX

**Comment by nuxsmin** [comment]
Thanks for the feedback!
